### ISSUE TITLE
[8.0] "ReplyTo" field in an email's template is never taken into account

### ISSUE THREAD

**Issue by francoislawarree** [odoo/odoo#10097]
Hi, 

I face a problem related to one of our customer who used to send email based on the email template. But depending of the email concerned he defined specific email in the field "ReplyTo" which is never propagated when the email is sent.

![image](https://cloud.githubusercontent.com/assets/11072956/11840633/93dd9c92-a3f7-11e5-883a-9e46141842a0.png)

In our case, it's always the "catchall@domain.be" which is mentioned in the "ReplyTo".

Thanks in advance for your return.

François

**Comment by beledouxdenis** [comment]
Hello François, 

The reply-to in the email template is used only in a context of mass mailing. See the below image for illustration.
![customers odoo 1](https://cloud.githubusercontent.com/assets/5822488/11846709/0fed6246-a41a-11e5-9574-345d9f0cca67.png)


In other cases, like when used in the discussion thread of a single record, like in the discussion thread of a lead or of a customer, the reply-to is ignored. This is the expected behavior.

Otherwise, if the customer replies to your email, the email would not land in the discussion thread, and this is not the expected behavior when you send the email from the discussion thread.

If you want your reply-to to be used, you must, for instance, be in the partners list view, select several partners, and then, in the more menu, send the according mail templates. Besides, you must uncheck "No threading for answers".

I hope you will understand.

Regards,

**Comment by francoislawarree** [comment]
Hello Denis,

Ok but what is then the purpose of the filed "Reply-To" in the email template configuration if i don't use the "Mass mailing module ?

Regards,

François

**Comment by beledouxdenis** [comment]
Hello François, 

You do not need the mass mailing module: You can go to the partners list, select multiple partners, and send an email template from the mail menu.

From there, you will have the possibility to use the reply-to. See the image I posted in my previous comment illustrating the matter.

Regards,
