### ISSUE TITLE
Autosave saved invalid data

### ISSUE THREAD

**Issue by jlzhou** [odoo/odoo#101459]
Impacted versions:
16.0beta

Steps to reproduce:
install sale app with demo data in a fresh db

Current behavior:
In product page, try change product type, it may prompt 'You cannot change the product's type because it is already used in sales orders', BUT the change was saved!!! Autosave saved invalid data.

Expected behavior:
Invalid data should be discard.

**Comment by bouvyd** [comment]
Hi

We don't take issues with unreleased versions, since by definition they are 'ot finished.

In addition, I was not able to reproduce the issue: I get a notification upon changing the value or attempting to save, and when refreshing the change is not saved.


Have a nice day :)
https://user-images.githubusercontent.com/9530767/192830234-4c332a56-a91d-4b24-9e86-aedfcabc147f.mp4

**Comment by jlzhou** [comment]
Thanks for your reply and the video.
After investigation current merged source code, I found the error prompt was triggered by onchange, but invalid data still be saved by autosave while refreshing the page. I guess it will be fixed before release.

BTW, I am using Chrome on desktop to do the test.
