### ISSUE TITLE
expiration_date, expiration_reason: trial. Is community edition really a trial version?

### ISSUE THREAD

**Issue by extra-0** [odoo/odoo#10198]
Hi @all,
When I go to Parameters->System parameters, I can see there's this key:

    Key : database.expiration_date
    Value: 2016-03-23
    Groups: Employee

And this key:

    Key: database.expiration_reason
    Value: trial
    Groups: Settings

I have downloaded Odoo from this repository.
Does this mean that I have a trial version and it will expire on 2016-03-23?
Thanks

**Comment by bistaray** [comment]
Hmm.

Usually, if you see these parameters, then you have the Enterprise edition.

The Community version does not normally have these parameters.

Other than this being a bug, the only way I can see you having these parameters in the Community version is if somehow, Odoo has a record of your database.uuid or if someone added a database.enterprise_code parameter that the Odoo Warranty Server is detecting as belonging to an Enterprise user.

**Comment by extra-0** [comment]
``database.enterprise_code`` parameter is not set.
Is it safe to just remove these parameters and change ``database.uuid``?

**Comment by dbo-odoo** [comment]
Hello,

First of all, don't panic: your database will not expire in March, nor after that. *Community Edition databases do not expire*. You can confirm this by simply grepping the code for these parameters, they are not called anywhere in the Community Edition

These parameters are set by the response to the update notification that are sent weekly to our server (and have been since... well, always). Deleting the parameters and changing the db uuid will simply create a new database entry in our system, and we will send you these parameters again only slightly delayed in time (depending on when you created the database in the first place). The parameters you have in your database are simply the current default we send to requests that don't have an `database.enterprise_code` (basically all community dbs).

These parameters are indeed needed only for the Enterprise Edition and will very probably be moved in the Enterprise code in version 10.
