### ISSUE TITLE
Cannot set specific physical features for different variants

### ISSUE THREAD

**Issue by jalzaga** [odoo/odoo#10252]
When you define variants for a specific product, it may happen that the volume, gross weight and net weight vary from one variant to another, e.g. size XS weights much less tan size XXL and its volume is much smaller.
At present these fields are in the template model so that they are common to all variants, there are also other fields that would be candidates to be different for each variant, such as Storage location, or cost.
Affects version 8 and previous

**Comment by flotho** [comment]
Hi @jalzaga ,

You're right it's a common problem, well known.
A common solution is to use OCA : https://github.com/OCA/product-attribute

**Comment by Yenthe666** [comment]
Hey,

That is indeed a fact and indeed OCA has modules for this.
It is not something that can be changed in the stable versions plus your bug report is for V8 which is end of life now. I'm closing it because of these two reasons and sorry for the very late reply.
CC @lap-odoo as you might want to add this as an internal task?
