### ISSUE TITLE
[9.0] Changing start time of calendar recurrent event only change current event

### ISSUE THREAD

**Issue by yvaucher** [odoo/odoo#10278]
Impacted versions:

- 9.0

Steps to reproduce:

1. create a recurring event in calendar
2. (tested with repeat: every 1 weeks, number of repetition: 20, Wed: True, Thu: True, Fri; True, Sat: True)
3.  Open the third event created, change date.

Current behaviour:

- Only this event has been changed.

Expected behaviour:

With the text:

    This event is linked to a recurrence...
    Update only this instance

It means that we should be able to change start time of every concurrencies at once.

The only way I can change start time is to edit the id in url to make sure I'm not on a virtual object.

For example if I have 
http://122883-9-0-28621b.runbot8.odoo.com/web#id=18-20160115213000&view_type=form&model=calendar.event&menu_id=280&action=360

Changing it to 
http://122883-9-0-28621b.runbot8.odoo.com/web#id=18&view_type=form&model=calendar.event&menu_id=280&action=360

Only this hack allows me to edit time for every recurring events.

**Comment by morphace** [comment]
+1

**Comment by beledouxdenis** [comment]
Hello Yannick, 

I agree the current behavior seems a bit buggy.

However, I am not sure what you actually expect.

If I create an event on February 3rd, every 1 week, on wed, tue, fri and sat, it will create an event for:
 - February 3rd
 - February 4th
 - February 5th
 - February 6th
 - February 10th
 - February 11th
 - February 12th
 - February 13th

Then, I change the event February 5th to February 12th.

You want: 
 - all the recurrent events delayed of 1 week ? Making, for instance, February 4th delayed to February 11st, and February 11th to February 18
or
 - the recurrent events should now starts from  February 12th ? So there is no event on February 10th & 11th.

Regards,

**Comment by yvaucher** [comment]
Hello @beledouxdenis 

It's mostly a matter of time than of date in my case.

Let's take a stupid example: You organize a weekly meeting on Friday at 13:00 after few weeks you finally realize this is not the good time because some people do take their lunch at this time. You want to reschedule all the meetings on each Friday at 10:00.

Now in fact you are doing the planning of 20 people. You want that for each meeting it takes you only few seconds to change the hour of the meeting. You can already achieve it but it's really hacky as you can remove the virtual part of the event's id in url. So I assume it should work, there is just a scrambling somewhere between real id and virtual ids.

As a comparison, when you do it in the form of google calendar, it asks you if you want to edit only the current event, all the events of the serie or only events of the serie in the future.

An issue can be that when you edit the 2nd occurence of a serie you must be careful not to change to consider it as the start of the serie.
--------

Changing the date should be dealt differently. It might depends on the parameters. If you gave a deadline date (February 13th), your case will result in having

February 12th
February 13th

Otherwise if you had a number of repetition (8), I would say that you need to keep that number and have:

    February 12th
    February 13th
    February 17th
    February 18th
    February 19th
    February 20th
    February 24th
    February 25th

**Comment by beledouxdenis** [comment]
Well, what you ask (at least, the different behavior according to what is changed -- the hour or the date, and the deadline or repetition thing) is kind of a a feature. A useful one, indeed, but, still, a feature. This part is probably aiming master, to not change such a behavior, in stable release.

That said, the fact it says 
```
This event is linked to a recurrence...
Update only this instance
```
While, when you change the recurrence, it only change it for this event, is obviously wrong, indeed.

We will have a look

**Comment by nle-odoo** [comment]
Hello,


I had tried some things which were mainly aimed when start/end time was changed (and not the date) with #10873 but @JKE-be found several issue (mainly when the day is changed and not just the time).

There is also an issue that if we change all the occurrences of an event at one time, it should not change them for the past occurences, for example if every monday at 10 am there is a meeting since 2010, it would not be good that changing it to tuesday at 3pm in 2016 would move 6 years of passed meeting.

The trick to remove `-#############` of the virtual id `##-#############` in url work but will cause issue reported by jke as well as the issue I'm trying to solve there:
 https://github.com/odoo/odoo/commit/33755f18826b1322283ed95dc045eb009be774ef#diff-db0c2833bd046ae435cb62a9b75e830fR1571

If no event was ever detached, these issue would not happen but since event can be detached it has to be taken into account.

All this to say; I don't think we will be able to change the current behaviour without more change which would only be acceptable in master.

Thanks for reporting.
