### ISSUE TITLE
l10n_fr : loose old tax group

### ISSUE THREAD

**Issue by fmdl** [odoo/odoo#102850]
Impacted versions: 14.0 and after
This PR https://github.com/odoo/odoo/commit/85a634c7527f20b56b15c2da90a37dfd637da63b add the new 2022 TVA report but there are no migration script.

Steps to reproduce:
Upgrade l10n_fr

Current behavior:
some tax group are unlink

Expected behavior:
add migration script

https://user-images.githubusercontent.com/16716992/197530596-079a2685-fe88-4ad0-b285-130662f43625.mov

Support ticket number submitted via odoo.com/help (optional):

**Comment by fmdl** [comment]
OPW #3012938

**Comment by fmdl** [comment]
ping @oco-odoo @sla-subteno-it @alexis-via

**Comment by fmdl** [comment]
Video :
https://user-images.githubusercontent.com/16716992/197530459-a50d022c-cf0f-470f-ba78-56675170fb1d.mov

**Comment by oco-odoo** [comment]
So, if I get you well, what you mean is that the amounts in the tax report are now 0 because of the loading of the new data, and you'd like it to contain data for the existing entries ?

There are two reasons why we didn't do a script for this: 

1 - Doing it for past periods does not make sense, as they have already been submitted to the state. It would only matter for the current period, and even so, we merged this after the start of application of the new report, so the old one was not supped to be used anymore, right ?

2 -  Converting an old report into the new one is not as trivial as it might seem: some taxes might have been created manually (in which case, we can't assign them new tags) and some tags might have been set manually on some lines (maybe even directly on misc operations - we had such cases in the past). 

The only way to do a proper conversion from report A to report B is to have a strict mapping between the lines of A and B. And this is usually not even possible (at least here, we don't have any).

This is why we prefer not to apply a solution to everyone, as the reports would be wrong in some cases.

I agree that this mechanism isn't perfect, but so far we don't have any clean solution for this, outside of a manual case by case fix.

**Comment by fmdl** [comment]
the issue is the old tag group are unlink, whereas there `ondelete='restrict'` here https://github.com/odoo/odoo/blob/14.0/addons/account/models/account_move.py#L3275

It is more an ORM issue @rco-odoo .

**Comment by oco-odoo** [comment]
@fmdl No.

The tags are removed in your case because the account.tax.report.line objects are unlinked. Doing so, this is called https://github.com/odoo/odoo/blob/15.0/addons/account/models/account_tax_report.py#L263 , then this https://github.com/odoo/odoo/blob/15.0/addons/account/models/account_tax_report.py#L280 , which forces the deletion of the tags by first removing them from the move lines.

We do this because the tags have no value as soon as the report is deleted, since the report uses a relational link to access them ; so you couldn't even recreate the report. 

We changed that in 16.0, since in that version, a tax report uses the names of the tags to access them, so removing the tax report does not prevent accessing its totals forever.

Note that if you want to prevent this behavior in 14.0 and 15.0, you could simply duplicate the tax report before updating the module. The update will then delete the original tax report, but since some of its tag are shared with another report that is not being deleted (the copy), they will remain in the db.  

As I told you, we might change the way we handle this kind of change in the future, but this is no simple decision to make, as it can have a big impact on maintenance and migration in the long term. 

For now, I'm closing this issue, since it is a limitation we are aware of, and the workaround is pretty straightforward.

**Comment by fmdl** [comment]
humm... the script is now made : https://github.com/odoo/odoo/pull/109001
