### ISSUE TITLE
[16.0] Get error "Uncaught Javascript Error > invalid parameter format" when using. export data

### ISSUE THREAD

**Issue by anhjean** [odoo/odoo#103232]
Impacted versions: Odoo 16.0 (Community Edition)

Steps to reproduce: 
 - Steps 1: Goto Contacts list view.
 - Steps 2: Choose the contacts that you want to export
 - Steps 3: Click on 'action' then click on "export' menu item
 - Steps 4: Click on ' Export' button 

Current behavior:
- Show "Uncaught Javascript Error > invalid parameter format"
- Note: This error occurred on all model export screen.

Expected behavior:
- Goto download xlsx/csv file step

Video/Screenshot link (optional):

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/51810762/196012179-227db053-f149-4db6-9509-42862fdda2bc.png">

Support ticket number submitted via odoo.com/help (optional):

**Comment by anhjean** [comment]
i found that if i changed the condition at line 225 of "addons/web/static/src/core/network/download.js  files  from "(**index !== -1** && index !== string.length)" to "(**index == -1** && index !== string.length), everything worked ok

**Comment by kmw** [comment]
How can I access addons/web/static/src/core/network to edit the download.js inside of a docker container?
By any chance will this also fix the website link from the drop down menu
https://dronesla.net/web#action=website.website_preview&path=%2F&website_id=1
https://youtu.be/V9-enVedPo8 is a video I created demonstrating this.

**Comment by rvjjcolina** [comment]
Tanks.

**Comment by vava-odoo** [comment]
Seems to be fixed, as non reproducable on runbot. Don't hesitate to re-open if it's not the case.

**Comment by megahall** [comment]
The latest odoo nightly deb still seems to hit this issue for me.

**Comment by vava-odoo** [comment]
@megahall Please provide steps to reproduce, as I'm not able to reproduce with the steps in the description above.

**Comment by andriusdj** [comment]
Hello, export does not work in any of the models. Simply clicking export causes that error.

Also there is this: https://www.odoo.com/forum/help-1/odoo16-export-data-error-in-all-modules-how-to-resolve-it-224621

> This issue is due to a wrong version for python package:
> 
>     werkzeug
>         require 2.0.2 (cf https://github.com/odoo/odoo/blob/16.0/requirements.txt)
>         David you are in 2.2.3
>         jiafei, I let you check on your side

Apparently this might be reproduced on Debian bookworm (v12) Linux distribution (current stable) where things are new and the python package mentioned is indeed version 2.2.2:

```
root@xxx:~# apt policy python3-werkzeug
python3-werkzeug:
  Installed: 2.2.2-3
  Candidate: 2.2.2-3
  Version table:
 *** 2.2.2-3 500
        500 http://deb.debian.org/debian bookworm/main amd64 Packages
        100 /var/lib/dpkg/status
root@xxx:~# apt policy python3
python3:
  Installed: 3.11.2-1+b1
  Candidate: 3.11.2-1+b1
  Version table:
 *** 3.11.2-1+b1 500
        500 http://deb.debian.org/debian bookworm/main amd64 Packages
        100 /var/lib/dpkg/status
```

All packages were installed via the distribution package manager from the repositories instead of pip as suggested in the documentation:
https://www.odoo.com/documentation/16.0/administration/install/install.html

> "Using your distribution packages is the preferred way of installing dependencies. Alternatively, you can install the python dependencies with pip."

So can we get an upgrade of this dependency? 2.2.2 should not have breaking changes to 2.0.2, no?
