### ISSUE TITLE
[15.0] Company address and logo doesn't appear in my invoices

### ISSUE THREAD

**Issue by lxwulf** [odoo/odoo#103877]
Impacted versions:

15

Steps to reproduce:

1. Setup Invoice template with addresses, names and so on.
2. Insert logo (.png format), 
3. Click to download PDF preview.

Current behavior:

In downloaded PDF preview, the addresses and company logo are not present

Expected behavior:

Company logo and Company address from my side is present

System: Fedora Linux 36

Video/Screenshot link (optional):

Preview in invoice template configurator:

[![Screenshot-from-2022-10-23-15-12-21.png](https://i.postimg.cc/jjfq8vMB/Screenshot-from-2022-10-23-15-12-21.png)](https://postimg.cc/t1XHJdQz)

Downloaded PDF:

[![Screenshot-from-2022-10-23-15-15-00.png](https://i.postimg.cc/8CNX3z4D/Screenshot-from-2022-10-23-15-15-00.png)](https://postimg.cc/xXpPNYBF)

Support ticket number submitted via odoo.com/help (optional):

_Using odoo community on my own server_

**Comment by niyasraphy** [comment]
upon checking the same in runbot, it seems working fine

**Comment by lxwulf** [comment]
Yes, this could be true on your side, but not my side. Sadly, I don't know where to start with the troubleshooting.

**Comment by lxwulf** [comment]
Changed to another software – sorry. Maybe I come later back again. See you then :v:

**Comment by Jeffabri** [comment]
I've been stuck with the same issue for days, but the cause was something else.Default odoo uses non-patched wkhtmltopdf.This causes issues on newer systems.

The patched version on it's turn requires libssl1.1 (not libssl3), which is also not by default available in recent ubuntu server versions.

Steps to solve:

Remove current installation:
sudo apt remove --purge wkhtmltopdf

Download and install libssl1.1
wget http://archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.0g-2ubuntu4_amd64.deb
sudo dpkg -i libssl1.1_1.1.0g-2ubuntu4_amd64.deb

Download and install qkhtmltopdf (with patched Qt)wget https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6.1-2/wkhtmltox_0.12.6.1-2.jammy_amd64.deb
sudo apt install ./wkhtmltox_0.12.6.1-2.jammy_amd64.deb

This solved it on my side!

**Comment by lxwulf** [comment]
Many thanks for this in-depth guide! 🤝 
Nonetheless, sadly, I moved to another application.
