### ISSUE TITLE
[8.0][9.0] tree views do not keep group_by expanded

### ISSUE THREAD

**Issue by invitu** [odoo/odoo#10428]
Steps to reproduce : 
- open a tree view
- choose a group_by
- expand the list with one or several groups
- open a record in form view
- return to the list (list button on top-right or the breadcrumb on top-left)
- the tree view is all collapsed

Wished behavior : 
- when returning in tree view, we should keep the previously expanded groups expanded

**Comment by mge-odoo** [comment]
Hi @invitu ,

The issue you mentioned was a severe limitation of the previous list view implementation and this couldn't be fixed in a stable version w/o a complete rewriting.

The views have been completely rewritten from saas-16 (just before 11.0) and the behavior you describe now correctly works.

Regards,

Martin
