### ISSUE TITLE
9.0 Report in Timesheets Module

### ISSUE THREAD

**Issue by stephaniemillet** [odoo/odoo#10484]
BY default, when you create a report in Timesheets > Reports > Timesheet
The line are defined by Users
and the Colum by period.

You can change everything, but when you save a report, and want to open it again
It had kept you column definition
But it always go back to lines per USERS

![image](https://cloud.githubusercontent.com/assets/12233420/12355701/d2217a0a-bb9e-11e5-87e4-f78bf751d241.png)

**Comment by Yenthe666** [comment]
Hi @stephaniemillet,

Thanks a lot for your bug report and sorry for the late reply.
In the meanwhile this issue has been fixed, as you can see in this example:
![image](https://user-images.githubusercontent.com/6352350/36093821-24655b26-0fec-11e8-8693-7750aae4e580.png)

If you still have this problem on your local Odoo instance then please update your source code in order to fix it.

Regards,
Yenthe
