### ISSUE TITLE
[BUG] point_of_sale: refresh is cleaning the changes in the order

### ISSUE THREAD

**Issue by fernandahf** [odoo/odoo#104935]
Impacted versions:

15.0

Steps to reproduce:

1. Open a new session of POS
2. Create a new order
3. Add a product to the order
4. Go back to the Floor
5. Click on Orders
6. Add a product to the order you created in step 2
7. Refresh the browser

After that, you should see the order only with the product added in step 2 but not the one added in step 6

Current behavior:

The order is not saved when you add products to the order and if something happens in the middle of the time, the order loses the information.

Expected behavior:

The order is saved when the user adds the product.

Video/Screenshot link (optional):

https://youtu.be/AyLNpbeqRcY

Support ticket number submitted via odoo.com/help (optional):

#3055763

**Comment by fernandahf** [comment]
cc @hugho-ad

**Comment by pedrambiria** [comment]
https://github.com/odoo/odoo/issues/104934

**Comment by hugho-ad** [comment]
@pedrambiria 

could you please re-open this?

**Comment by trj-odoo** [comment]
Hi, we don't consider it as a bug. It is working as expected and it's the limitation of pos_restaurant ever since it was introduced. In v16, the mechanism has been improved, changes are being kept and saved locally and is trying to be sent whenever possible (unless you go to the table which fetches the data and is considered as the most trustworthy). 
The syncing to the server has always been made that way when going back to the floor screen. The result will be the same when you lose connection even while adding rpc call during the adding of products.
Refreshing the browser is also not a normal use case when working

**Comment by fernandahf** [comment]
For record:

In v16.0 the issue is still reproduced:

https://youtu.be/HC_5YmpgKzw

**Comment by trj-odoo** [comment]
Hi @fernandahf, why would you refresh?

**Comment by trj-odoo** [comment]
Because it's possible doesn't mean you should do it. That's like clearing the localStorage of your browser since it's possible and then expect the PoS to still being able to load the local orders. Should we also tackles this? No. 
If there's indeed a real use case where refreshing the browser should be part of the mechanism then maybe we will consider it.
