### ISSUE TITLE
[BUG] point_of_sale: editing order and switching to another one of the same table is cleaning the changes in the first one

### ISSUE THREAD

**Issue by fernandahf** [odoo/odoo#104934]
Impacted versions:

15.0

Steps to reproduce:

1. Create 3 orders to the same table with different products
2. Edit one of the 3 and add a product
3. Click on Orders
4. Click on any of 2 orders (not the one of step 2)
5. Click on Orders
6. Click on the order edited in step 2 

You should see the order without the product added in step 2

Current behavior:

The switching between orders of the same table **must not** undone the changes applied in the orders, this is an error extremely dangerous in POS because the changes are being deleted.

Expected behavior:

The switching between orders of the same table must save all changes applied in the orders.

Video/Screenshot link (optional):

https://youtu.be/_qRVIBvUAzc

Support ticket number submitted via odoo.com/help (optional):

#3055751

**Comment by hugho-ad** [comment]
@pedrambiria 

Reopen this issue please

Next statement is the Big Issue
"So even if an order exists in the Browser cache, it will be replaced with the back-end order if it exists."

Why do you rest relevance to the cache on browser? those cache lines could be lines that were printed, leading on products that were produce or served but any Order has them because the replacement you done.

Also think on the final user, why you are making user go to floors screen, if the UI flow allows you to switch between orders without existing the ticket Screen?

""Unfortunately, we can not solve this issue yet, and the users must be careful to return to the floor screen before closing the tab or refreshing it.""

Why you can't solve it?

There you have already a proposal to fix it:
https://github.com/odoo/odoo/pull/105486


 @trj-odoo @caburj could you take a look at this please?

**Comment by nhomar** [comment]
@pedrambiria 

Totally wrong the answer.

YES, it can be solved (see the PR attached).
NO, It can not be possible to loose lines that were printed with physical evidence.
NO, It is impossible to train few dozens of waitress taking order at the same time,

What do you propose?.
