### ISSUE TITLE
[9.0]Vendor reference is not filled when creating invoice from purchase order

### ISSUE THREAD

**Issue by falinwa** [odoo/odoo#10512]
Hello Odoo,

When I tried to create invoice from purchase order,
I have filled the vendor reference on purchase order, but its not automatically filled on invoice.

The expected behavior should be:
The vendor reference is filled based on the same like on purchase order.

Thank You.

**Comment by pedrobaeza** [comment]
@falinwa the vendor reference is not propagated from purchase order to vendor invoice because both are supposed to be different references: the first one is the number the vendor has given to you purchase order, and the second one is the number of the invoice your supplier has issued to you, so the behavior you want to achieve is somehow a deformed flow. Any way, if you want to implement that, you can do it on a custom module.
