### ISSUE TITLE
[16.0] Snailmail Letter create button broken

### ISSUE THREAD

**Issue by bodedra** [odoo/odoo#105237]
Impacted versions: 16.0

Steps to reproduce:
- Go to Settings > Technical > Email > Snailmail Letters
- Click on Create button

Current behavior:
![snailmail_letter_odoo16](https://user-images.githubusercontent.com/14229503/200386537-ff6d803d-3d13-425f-a4ae-ea39f2d6f48d.PNG)

Expected behavior:
- It should allow to create a new record.

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by sswapnesh** [comment]
This seems to be failed due to widget="reference" on creating new record 
(Same happens when you click on create on **External Identifiers**)

https://github.com/odoo/odoo/commit/d85609501d2fe59b21ace21558f2c8367ae17e5d#diff-30af02c7dc05c1ba6a6cbb5c38844fcc2876d88bf6ea76520c06e3ebff39dc13R31

FYI @mcm-odoo @ged-odoo

**Comment by niyasraphy** [comment]
PR: https://github.com/odoo/odoo/pull/103754

**Comment by bodedra** [comment]
Duplicate https://github.com/odoo/odoo/issues/103756
