### ISSUE TITLE
Product Template popup not showing in sale order line item (On Mobile and Tablet device) [V16]

### ISSUE THREAD

**Issue by libu2020** [odoo/odoo#105299]
Impacted versions:odoo16 community

Steps to reproduce: Open the URL on the mobile and select the product which has a product variant (On product master make the sale variant selection->Product Configurator)

Current behavior: When we select a variant item from the sale order line (customizable desk,(eg: two variants -blue and white) that popup is not showing on mobile and tab devices. It is coming only on pc or laptop

Expected behavior: Need to popup variants, like how it is a popup on the computer.

Video/Screenshot link (optional):  https://ibb.co/PtBjcdg (this is on computer),(Product.template)

https://ibb.co/thK148g (Mobile it is not showing that popup (it is showing (product. product model)

Support ticket number submitted via odoo.com/help (optional):

- Open the URL in Mobile and Computer 
- Try to add a sale order line with the variant product.
-

**Comment by Feyensv** [comment]
AFAIK, this was the case in previous versions as well.
In mobile, you have to choose the variant manually, not through the configurator.

We might change that in future versions, but it'll stay like this in stable versions.

**Comment by libu2020** [comment]
No this is not in the previous version I tried on v14. It is working perfectly, in the community version.

**Comment by Feyensv** [comment]
Okay, I understand now, it's because we moved the responsive/mobile code in v16 from enterprise to community.
This behavior was already like that in 14 & 15 but only in enterprise, with the mobile/responsive code.
In community (14 & 15), the mobile UI was simply the standard UI, which was why the configurator was available (though the mobile views were difficult to use considering the size of the fields and other mobile problems).

Now, in 16, adding a sale order line on mobile opens the `sale.order.line` form view, where the configurator is not available.  This is the wanted behavior for now, where you have to choose the `product.product` directly.

We are thinking of making the configurator available in mobile as well, but if we do, it'll only be in future versions.
