### ISSUE TITLE
Cannot Save Changes in ODOO 9

### ISSUE THREAD

**Issue by samica31** [odoo/odoo#10522]
I am customizing the project.issue module right now. I am trying to put another field and renaming some field names. After doing it, I saved it and changes take effect. New field name was there and renamed field names. But after doing the same thing from other fields, changes did not take effect. I updated the module lists and upgraded issue tracking. I also restart the services of odoo 9. Nothing happened. Please let me know if there are issues or bugs in Odoo 9. 
Thank you!

**Comment by Yenthe666** [comment]
Hi @samica31,

The Odoo issues are used for issues with the official code (the code you fetch from Github, no custom development).
If you would still face this issue please create a question on the official Odoo help forum (help.odoo.com), I'm sure somebody can help you there.
I'm closing this issue since I don't have any example code and because it involves custom development.

Regards,
Yenthe
