### ISSUE TITLE
9.0 - Sequence fields on invoice lines incorrect

### ISSUE THREAD

**Issue by stephaniemillet** [odoo/odoo#10544]
All lines in an invoice have a "sequence" = 10
Where they should have a sequential number
Example
For an invoice with 3 lines
1
2
3

**Comment by nim-odoo** [comment]
This is the default behavior for the sequence to be equal to "10". This is not an issue, since the invoice lines are sorted by "invoice_id, sequence, id". Therefore, for a given invoice, even if all the sequences are equal to "10", the lines will still be sorted by id, which has a fixed value.

However, when you modify manually the order of the lines thanks to the handle widget, the sequence will be set accordingly and the order you have defined will be respected.

**Comment by Bartii** [comment]
Sorting is only one case when there is no matter what the sequence is (because of id field in sort order). The case is when you have to compare invoice lines with refund invoice lines. Then sequence seems to be useful. Right now first element gets 10 rest of lines get 11 (not 12,13, etc but always 11). Hence it is not possible to compare invoice lines and refund invoice lines to calculate difference

**Comment by gdgellatly** [comment]
That would seem to be wanting the field to do 2 unrelated things, generally
a bad practice, and definitely with a special field type whose value you
have little control over.  What then if someone reorders the refund?  Would
you not just be better if you really need that link to make a simple module
that explicitly links the two?

**Comment by Bartii** [comment]
sure, good idea. I created small module which links lines (one2many), so I can fully control this relationship (origin to refund). Thanks for this advice. Still, if there is sequence field it should work as it is expected: show sequence of lines
