### ISSUE TITLE
[8.0] Search view from popup limited to 160 records

### ISSUE THREAD

**Issue by Cedric-Pigeon** [odoo/odoo#10583]
In a search view_from popup, the results from a search is limited to 160.
If you add and delete a filter, all records are included.

**Comment by Bip-odoo** [comment]
It is not the bug but intended behaviour. It's not good idea that each time system load all the records, and hence default is set with 160 records. It is due to reason to avoid long response time when page is loading.

**Comment by Cedric-Pigeon** [comment]
Hi,

I don't agree with you. I think the amount total of records must be right.
If you have 283 records, Odoo must show 1-80 of 283 records and not 160.

In all tree views, Odoo retrieve 80 records and indicates the right total
of amount. It must be the same on a pop up window.

This inconsistence really disturb our customer.

What can you do to have the same behaviour ?

Regards,

Cédric.

**Comment by wtaferner** [comment]
I agree with @Cedric-Pigeon b/c it could not be the intended behavior to force the user to first search / filter, take a look if it pops up immediately in the suggestions...click into opening the tree view for the extended search and have there a look if the required data is preloaded and available to choose...go back and start all over if it did not work out the first time...and actually I thought only 80 records are fully loaded if paging for 80 is active...

**Comment by JonathanNEMRY** [comment]
:+1:  @Cedric-Pigeon

**Comment by beledouxdenis** [comment]
Hello Cédric,

This limit of 160 records is the expected behavior. This is actually a performance improvement, from the below revision:
https://github.com/odoo/odoo/commit/8c3cdce

Before this revision, attempting to open a search more popup matching hundreds of records made the loading of the popup really, really slow.

Besides, if you open a popup with hundreds of records, this is unlikely that you will browse the pages one by one, to find your records. Instead, you will precise your search criteria. When doing so, the number of records displayed will then be correct.

The funny thing is that the issue from which comes from this revision has been opened by Acsone as well, and they confirmed this patch was the right solution (I found evidence of it within the OPW issue).

Here is the original bug report posted on Launchpad, by Olivier Laurent:
https://bugs.launchpad.net/openobject-server/+bug/1190217

And the original merge proposal:
https://code.launchpad.net/~openerp-dev/openerp-web/7.0-opw-593963-acl/+merge/184053

Regards,

**Comment by wtaferner** [comment]
@beledouxdenis 
Hmm, tricky, but it is clear that the solution was not completely considering the use cases occurring.
IMHO as long not all records have been searched the popup should not be possible to open...based on this we could force the user to use the original search field for further chars and details before and only then get another search within the rich search with all possible records found.

**Comment by Cedric-Pigeon** [comment]
@beledouxdenis <https://github.com/beledouxdenis>

Indeed Olivier validated the patch. But it was a blocking issue and Odoo
only found this solution in urgence to unblock the situation with our
customer.
It is clear that it was not a sustainable solution and our new customer
does not agree with this behaviour.

In my opinion, the popup should work exactly as the tree view:

Extract the 80 first records and show the number total of records in the
pagination area.

Cédric.

**Comment by beledouxdenis** [comment]
Hello Cédric,

Anyhow, we do not regard this issue as a blocking bug, but rather as an improvement in the usability.

Improvements are not done within stable release, to avoid introducing new regressions.

To know more about our stable policy, you can read the following documentation:
https://github.com/odoo/odoo/wiki/Contributing#what-does-stable-mean
I hope you will understand.

Regards,

**Comment by Cedric-Pigeon** [comment]
@beledouxdenis 

Sorry but I don't agree with you.

In a reliable system I consider that the information must be consistent from anywhere you retrieve it.
From my point of view, giving a correct information regarding the database content is not an improvement but a must.

Odoo lets the end user believe there are not more than 160 records in database but it is wrong. Sure it isn't a blocking bug but this is really disturbing and my customer is complaining about that.

Please, could you reconsider your decision ?

Regards

**Comment by beledouxdenis** [comment]
@antonylesuisse could you consider Cédric's arguements and take the decision for us ?

To me, this isn't a blocking bug, and the risk to introduce regressions while attempting to solve this issue is far too great. This will probably not be a short patch, this will most-likely lead to a deep refactoring on how the records in the search popup are gathered, and such a refactoring in a stable release is too risky.

**Comment by sbidoul** [comment]
@Cedric-Pigeon @beledouxdenis do you know if the bug is in 9.0 too?

**Comment by adrienpeiffer** [comment]
@Cedric-Pigeon @beledouxdenis @sbidoul I confirm that this bug is in 9.0 too ...
