### ISSUE TITLE
[8.0] Change month date name of arabic language in odoo 

### ISSUE THREAD

**Issue by ronozoro** [odoo/odoo#10619]
I change the interface language to Arabic from setting--> translation--> load translation , i have a problem that the month names of (January-February-March,etc ) is translated to (كانون - ايلول ,etc ) but i need to change them in the system to (يناير -فبراير - مارس , etc ) i tried to change the files in datejs library in web module but there is no change and i search for the .po files that contains this months and edited them all with also no hope and my last try was to change the language terms of these month but still not getting what i need so could you please tell me how could i change the date months names to the required names in odoo/openerp server in either configs or code?

Thanks

**Comment by Yenthe666** [comment]
@robodoo you should do this on Transifex! Have a look at transifex.com/odoo/

**Comment by Yenthe666** [comment]
@mart-e another locky-lock. :+1:

**Comment by mart-e** [comment]
Indeed thanks.
@robodoo please submit your fixes on Transifex. See [translation wiki](https://github.com/odoo/odoo/wiki/Translations) for details

**Comment by anassahmed** [comment]
The issue with month names are not only in the _Transifex_ translation files. In Odoo `8.0`, the only Arabic language available is `ar_SY` which is the Syrian locale that doesn't represent most of the Arabian locales. They use the format 'كانون الثاني' (Kanoon II) instead of 'يناير' (January), as they call the months with different names based on the [Assyrian Calendar](https://en.wikipedia.org/wiki/Assyrian_calendar) names.

The temporary fix for that is to duplicate the Arabic language (export the whole po file from the system), replace the occurrences of these month names with your locale names, import again as a new language with new code (in my case, I called it "Arabic (Egypt)" with code `ar_EG`). This will fix another issue, which is the month names that comes out of Python directly (`datetime.strftime('%B')`) which doesn't pass through Odoo translation engine at all, but comes localized based on `locale.setlocale(self.env.context('lang'))`.

Maybe the Odoo `10.0` version is in a better state, due to the split of language and country, but I didn't read the code yet, I just hope it is.

Another issue that may still valid is that month names that comes directly from Python `datetime.strftime('%B')` depends on the system locales (the docker debian image, for example, doesn't have any locales other than 'C') which means if the locale isn't available system-wide, the month names will be printed in English.

**Comment by anassahmed** [comment]
@amrabdalkrim Just do the following:
1. Enable developer/debug mode.
2. Open "Settings" -> "Translations" -> "Export Translation".
3. Choose "Arabic (Syria)" as a language, select "PO File" as a format, and don't choose any modules, then click "Export".
4. Open the file with any translation app (e.g. POEdit) and replace the month names with the appropriate ones.
5. Open "Settings" -> "Translations" -> "Languages" and add a new language with name "Arabic (Egypt)" and code "ar_EG".
5. Open "Settings" -> "Translations" -> "Import Translation" and write name "Arabic (Egypt)" and code "ar_EG" and choose your file that you've edited in the stop 4, then click "Import".
5. Change the language in User preferences, and it should be working for most things in Odoo.

**Comment by amrabdalkrim** [comment]
I tried what you said but the main Arabic language in Odoo 11 is already translated to the right translation so when I print a report in Arabic it prints them in Kanoon II format so it must be form another please not the translation po file >> i guess js or somthing <<

**Comment by lyprono** [comment]
Hello @anassahmed  i want to change date in danish language   and   i have tied to modify  da.js in local web but anything haven't update so can you tell how can Translations?
