### ISSUE TITLE
[8.0] Closing pos session with return product not possible

### ISSUE THREAD

**Issue by laetitia-gangloff** [odoo/odoo#10627]
**Closing pos session with return product not possible**

Impacted versions:

 - 8.0

Steps to reproduce:

https://www.youtube.com/watch?v=S8ecj7JQM60&feature=youtu.be

Current behavior:

 - When "Validate Closing & Post Entries" an error message is displayed

Expected behavior:

 - "Validate Closing & Post Entries" is done. The bank statement ending balance should be correct.

**Comment by beledouxdenis** [comment]
Hello Laetitia,

I just tried to reproduce your issue, by doing exactly what you show in your video, but I did not have the error message. See the below video for illustration:
https://drive.google.com/file/d/0B5GVjjwUC-ygZ1JCNHlZdjFEaWM/view?usp=sharing

Besides, your use case implies manual operations, that can lead to have to perform manual changes elsewhere (in your case, adjust the amount with what you cancelled / duplicated). Returning a product is one thing, but duplicating an order is not really expected. If you do so, and it leads to issues because the data is no longer correct elsewhere, you have to correct what's wrong because of your manual operation.

Regards,

**Comment by Cedric-Pigeon** [comment]
@beledouxdenis 

I watched your video and you didn't exactly reproduce what @laetitia-gangloff explained. 

Have look at 00:26 second in Laetitia's video, she put the POS in "Closing Control" state BEFORE the manipulation on the pos.order.

Please try it and you will get the error.

Regards,

**Comment by beledouxdenis** [comment]
Well, you are changing the amount paid during the cash closing control. Is this a real use case ? 

Like the cashier is changing an order during the exact moment she is counting the coins within her cash boxes.

To me, this is a manual operation, that must be corrected manually and validated by a manager. Technically, you will have to update the bank statement ending balance in Accounting > Bank and Cash > Bank statements.

**Comment by Cedric-Pigeon** [comment]
@beledouxdenis 

Yes this is a real use case. We encounter the problem in production on electronic payments, not cash.

The problem is the POS user does not have any accounting rights allowing him to correct the bank statement. This is also the case for the POS manager.

**Comment by Cedric-Pigeon** [comment]
@beledouxdenis Any news ?
