### ISSUE TITLE
[9.0e] Carrier integration don't use the same source for weight

### ISSUE THREAD

**Issue by krueger80** [odoo/odoo#10651]
After looking in the code a bit deeper, I realized not all the carrier integration use the same field for weight when comes the time to "_send_shipping".

delivery_ups and delivery_dhl use picking.weight_bulk where as delivery_fedex uses picking.weight.

Not very clean what's the difference between both of those weight fields, but looking at how they are computed, they aren't the same.

**Comment by krueger80** [comment]
I was wrong... weight_bulk is for the not packages items... and it's not used as the main weight for UPS and DHL in fact...

**Comment by flyingL123** [comment]
Where were you able to find the source code for delivery_ups? I have been trying to find it so I can figure out a way to just retrieve a rate for a delivery order rather than actually creating the shipment. The carriers have this `integration_level` field, but I can't find it being used anywhere in the Odoo source.
