### ISSUE TITLE
Odoo 9 report designer

### ISSUE THREAD

**Issue by samica31** [odoo/odoo#10673]
Is report designer for odoo 9 unavailable?

**Comment by jholze** [comment]
not yet. We are working in it at the moment. It will work like the quotation templates, that a report can be edited like a website.

**Comment by wtaferner** [comment]
@jholze 
Are you talking about the qWeb reports or the deprecated RML reports? 
Because the qWeb Reports can be easily designed via the HTML Editor (website module must be installed to make use of it, but it is easy to copy paste later the produced code later)
I would be interested on what exactly you are working on :-)

**Comment by jholze** [comment]
Hi, you mean the feature when changing the type of a report from pdf to html ? This is not really working at the moment. Also the using the website snippets for reports doesn't make sense. 

Our goal is to finally create a new editor with custom features, more related to the needs you have in reports. Like Page view, different snippets & maybe a separated theme like in mail templates (marketing), add backend fields to place something like the invoice number or custom fields on  a report, add signatures like in website_sign ...

I think also a feature like website_versioning makes sense here, because otherwise each change is directly available / live and will be used eg. to print an invoice. 

And last but not least, the UX should be different to a website editor, because a website is different to a (mostly) print-report / PDF document. 

So much for theory, i hope we can finish some parts in the next few month, because the project in which we are doing it has a lot of custom needs which needs to be done before we can add all the fancy stuff :)

**Comment by wtaferner** [comment]
Well, I mean the qWeb stuff which can be changed directly via the Code Editor and as a WYSIWYG Editor in case you use the dedicated URL to have the Website Editor features...

But I think I got what you guys want to pursue...let me know if you have some kind of roadmap...I would at least be ready to contribute with ideas and experience. 

About versioning...I suggested quite a while ago to introduce versioning for views in general and other stuff to be able to see what actually happened content-wise. My concept would have been to use a local git repository to get this easily done and somehow independent and generic, but this is/was just an idea...I might chase it down at some point myself...for now mostly I can handle the content within Odoo, but I am sure some kind of historic content data can make life easier for a lot of things within Odoo.

**Comment by jholze** [comment]
@wtaferner take this BAAM! https://github.com/OCA/web/pull/300  :) from one of our devs

**Comment by wtaferner** [comment]
@jholze 
Hehe, thx for the link...I might play around with that one some time :-)

**Comment by samica31** [comment]
Hi @jholze looking forward to that. Thanks BTW. Am working on a new module. Thanks also @wtaferner

**Comment by boscoerp** [comment]
Looking forward for a best report engine like Google Charts to be seamlessly integrated with odoo.

**Comment by jholze** [comment]
@samica31 did you already finished something ? because we are back on this topic and thinking about the best way to integrate this feature. Maybe something like mail editor and website_sign editor. Would be good to know if you already finished something.

**Comment by samica31** [comment]
Hi @jholze what i did is to just use the qweb stuff and customize codes and its report output will be in a PDF format. Website_sign editor would be okay.

**Comment by brcontrols** [comment]
Hi @jholze. Can you update us about the progress for the report designer?

**Comment by jholze** [comment]
Hi, we are very busy since some month. Maybe at the end of the year something could be done to deliver to the OCA. We tested a simple approach but this is still not working fine when the changes you made on a report are very complex. We tested another approach within the website builder to only safe the diff into a view which works pretty well. Also we started first with a simple customized website builder, but this seems not useful because a report is different to a website and the editing should be different. Lets see what we could finish in the next time. 

Sorry that i don't have better news.

**Comment by lukebranch** [comment]
@jholze ,

Happy new year! 

I just wanted to check if you guys had made any headway on this project, as i've got a few users that are very interested in the prospect of a drag and drop report builder for QWeb reports.

I have just started with a new company with a small team of odoo developers, so there is a chance we may be able to cooperate on sharing the development work if the project has not been discontinued in favour of something else.

**Comment by Yenthe666** [comment]
Hi guys,

Since this is no bug in the official code or not a real issue I'll have to close this topic off.
Just continue your talk on this though, there is no problem in that!
@jholze I'm also curious about an update.
@lukebranch congratz on the new company! Hope all goes well.

Regards,
Yenthe

**Comment by lukebranch** [comment]
@Yenthe666 ,

Thanks!

**Comment by samica31** [comment]
I've also been waiting an update on this report designer. I deployed two
software using ODOO and I have a hard time designing the report manually. I
hope Odoo will do an update on this matter.
