### ISSUE TITLE
TypeError: 'NoneType' object is not iterable => problem is context

### ISSUE THREAD

**Issue by ruifranco** [odoo/odoo#10679]
In lines 328 and 396...

dict(context,

should become...

dict(context or {},

**Comment by xmo-odoo** [comment]
Lines 328 and 396… of which file, in which branch?

**Comment by ruifranco** [comment]
You're so right! :)

File: hr_holidays/hr_holidays.py
Branch: 8

To test it, you may create a leave record and, then, call the holidays_validate method. Since the context is "None" by default, the error is thrown.

**Comment by xmo-odoo** [comment]
[Line 328 seems to be correct](https://github.com/odoo/odoo/blob/8.0/addons/hr_holidays/hr_holidays.py#L326-L328), the preceding two lines check if the context is `None`, and if so set it to an empty dictionary. I'd have suggested trying to update but this code [seems to have been in since 2013](https://github.com/odoo/odoo/commit/2156c8368773082f6b685e37d9725dbc696adadc).

However you're right that [line 396 however has an issue](https://github.com/odoo/odoo/blob/8.0/addons/hr_holidays/hr_holidays.py#L396) in cloning a possibly-`None` context.

**Comment by Yenthe666** [comment]
Hi @ruifranco,

Thank you for your bug report.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
