### ISSUE TITLE
Start a server with multiple database, eg db_name = db1,db2, only the first is properly initialized.

### ISSUE THREAD

**Issue by ispiders** [odoo/odoo#107188]
Impacted versions:
16.0, not sure about previous versions
Steps to reproduce:

Current behavior:
`odoo-bin -i base -d db1,db2` only db1 properly initialized

Expected behavior:
Both db1 and db2 shoud be initialized. 

Investment: 
`odoo/service/server.py#1288`
``` python
def preload_registries(dbnames):
    """ Preload a registries, possibly run a test file."""
    # TODO: move all config checks to args dont check tools.config here
    dbnames = dbnames or []
    rc = 0
    for dbname in dbnames:
        try:
            update_module = config['init'] or config['update'] # config was updated after the first dbname initialized at odoo/modules/loading.py#526, so except for the first dbname, others will fail
            registry = Registry.new(dbname, update_module=update_module)
```

`odoo/modules/loading.py#526`
``` python
for kind in ('init', 'demo', 'update'):
    tools.config[kind] = {}
```

**Comment by Julien00859** [comment]
I'm surprised the `--database` option is capable of understand a coma-separated list of database. The option's help says (emphasis mine):

> Database related options:
> -d DB_NAME, --database=DB_NAME: specify **the** database name

I don't think that supplying multiple databases with `-d` was ever supported and I'm sure it has never been documented in that way.

It seems to me it is more of a feature request than a bug.

**Comment by Julien00859** [comment]
If you want to initialize multiple databases at once, you can do a shell script, looping on a bunch of database names and running `odoo-bin -i $module_list -d $db --stop-after-init` once per db

**Comment by iledarn** [comment]
There is another strong concern about auto-creation/initialization behavior - 
1. I had an existing db, say some_db1 in production - my db_name in config was like `db_name=some_db1`
2. lately I needed to add another db - some_db2, but made a typo in my config `db_name=some_db1,same_db2`
`same_db2` was not existing that moment

What happened after I restarted my server - my production db get initialized! It was very unexpected. `same_db2` was created as well but not initialized.

happily we have backups. Because existing company data (the one with id=1) was change, the currency was changed there.

**Comment by Julien00859** [comment]
Glad to ear you were able to restore everything thanks to backup! I totally agree that Odoo shouldn't had be able to start with that faulty configuration, I'll see what I can do to improve the situation...

I'm closing this one as supporting multiple databases with `-d` is not something we want to support
