### ISSUE TITLE
Refund on Vendor Bill shows positive amount due not negative.

### ISSUE THREAD

**Issue by elevationO** [odoo/odoo#10778]
The aged payables report shows the correct amount but the vendor bill is shown as a bill not a credit.
![screen-shot-2016-02-04-at-9 33 24-am](https://cloud.githubusercontent.com/assets/8355352/12824001/e10ae530-cb23-11e5-966c-f7d5d089d49a.png)

**Comment by csnauwaert** [comment]
Hello, actually your use case is really strange. It seems you are trying to do a refund using a bill with negative products quantities. That is not the way you create a refund. If you want to create a refund you can do it in 2 different ways: 

Either from an existing invoice/bill by clicking the "create/ask refund" or via the accounting dashboard:
![screenshot from 2016-02-05 11 46 52](https://cloud.githubusercontent.com/assets/7338483/12844745/9d3ee43a-cc01-11e5-8193-4cbd7bd709e6.png)

The fact that the amount due is positive is because the type of invoice is 'out_invoice', if you create a refund the correct way, the type would be 'out_refund' and it will appear correctly on the tree view as negative.

Hope that helps you
