### ISSUE TITLE
[8.0] list of .... name it

### ISSUE THREAD

**Issue by ddfs** [odoo/odoo#10810]
it has been few months i started using odoo and already regret it. here are the problems that i can list as far as i remember. 

- generic
-- 'website/information' is it wise?
-- accounting period starts may 24, ends in may 30 for 1st period in monthly setup.  no it does not!
-- inline css ..

- urls
-- the worst url generation mechanism ever. especially hard-coded /shop/* etc everywhere.
-- underscore in urls
-- no short code for languages
-- missing canonical urls, robots
-- shop/category/name-id or shop/product/name-id total headache. had to write custom router in front
-- ugly way of creating a sitemap.
-- robots.txt file to modify with hell of a pain
-- unpublish products straight into permission denied jungle
-- meaningless use of slug / keep
-- no proper breadcrumbs
-- page / category args attached in product urls

- cart
-- amount_total (includes tax)
-- amount_subtotal (doesn't include tax) [ overriding this breaks the functionality ?? ]
-- amount_shipping (doesn't include tax)
-- missing cart item total ( 3 x product (price: 10) = 30)

yet many more minor fixings had to do to get the whole system running and not finished.

**Comment by Yenthe666** [comment]
Hi @ddfs,

If you find a specific bug or issue you're free to report this and add a detailed description about it.
This post however is just a list of things that you label as issues, but are most likely not considered as bugs.
If you really feel some functionality is not good please create a separate issue for it and add as much information as you can. With the current list you've put here there is very little we can do or give feedback on since it contains no background information.
I'm closing this issue since it is just a list of things, not really an issue. You're free to create a new issue (or issues) with detailed information and I'd even welcome it, a discussion is never a bad thing.

Regards,
Yenthe
