### ISSUE TITLE
9.0 Invoice Refunds DATE incorrect

### ISSUE THREAD

**Issue by stephaniemillet** [odoo/odoo#10839]
Hi
When creating a refund from an invoice. Even if in the pop up you select a 'refund date' the date on the refund draft generate will be set equal to invoice date.
So if we don't pay attention, we validate the refund at a wrong date

**Comment by Yenthe666** [comment]
Hi @stephaniemillet,

Thank you for your report, I've just tested your scenario and this is indeed the case.
The refund screen:
![image](https://cloud.githubusercontent.com/assets/6352350/19036893/46c23f6e-8973-11e6-846f-34721a39b4fe.png)

The booked refund:
![image](https://cloud.githubusercontent.com/assets/6352350/19036910/5aaecab0-8973-11e6-8186-5b2763870989.png)

As you can see the date is booked on the date of the original invoice, not the date that is supplied in the refund screen.
@qdp-odoo and @csnauwaert, could you guys look at this?

Regards,
Yenthe

**Comment by qdp-odoo** [comment]
Sorry, maybe I miss something but I cannot reproduce: the date I select in the popup as refund date is used as date in my refund accordingly, and that's actually shown in Yenthe's screenshots...

I think it's just a usability issue: on the refund, the field labelled "invoice date" should be read "Document Date" because it's the same field used for invoices and refunds... Feel free to reopen the issue if it's not the case.

@Yenthe666 I knew that face looked familiar! :-)

**Comment by Yenthe666** [comment]
Hmm I must have been sleepy there, because the screenshot indeed shows the correct date.. 😄 
Thanks @qdp-odoo! And nice to have seen you in real.
