### ISSUE TITLE
Support for modern front-end frameworks such as React, Angular 2, Aurelia, etc.

### ISSUE THREAD

**Issue by jadhavajay** [odoo/odoo#10856]
Today, most of the new web development is taking [WebComponents](https://en.wikipedia.org/wiki/Web_Components) approach to UI development.

As [Odoo web](https://www.odoo.com/documentation/9.0/howtos/web.html) currently uses Jquery and Underscore, is there any thought given for providing developers an option to use one of the following leading front-end UI frameworks? (there are other similar options as well, but I have worked a bit with these..)

1. [React](https://facebook.github.io/react/)
2. [Angular 2](https://angular.io/)
3. [Aurelia](http://aurelia.io/)
4. [Polymer](https://www.polymer-project.org/1.0/)

Just a thought.

**Comment by Yenthe666** [comment]
:+1: atleast a nice thing to discuss. I'm curious if we will get any response from somebody at Odoo!

**Comment by ged-odoo** [comment]
well, right now, nothing prevents you to include one (or more, but I don't believe that it is a good idea :) ) of these frameworks in odoo.  You can simply add them in some static files, add them to your assets and use them in your js code.   

Now, if you want Odoo to use them, this is another story. We are aware of the existence of those frameworks. I personally would love to use React in the web client, but this would require a very large refactoring of the current code.  It is definitely not planned for the next few months.

**Comment by rockcesar** [comment]
In the ERP Views, you maybe should use the Odoo's JavaScript Api, as it comes. But you can integrate your own JavaScripts, here is an example of integration between Odoo ERP Views and Colorbox, an external plugin made in JavaScript, with many years since it was created (I did this module): https://www.odoo.com/apps/modules/10.0/button_popup/

And in the Web views, where you develop in QWeb (XML) as you do in the PDF reports, you can use any JavaScript Framework, there is not limitation. Look at these web pages made in Odoo (I participate in both projects):

https://app.sinco.gob.ve/

http://sincoop.mpcomunas.gob.ve/
