### ISSUE TITLE
[V9]reservation button not available for a partially available picking

### ISSUE THREAD

**Issue by flotho** [odoo/odoo#11019]
**Impacted versions:**
9.0

**Steps to reproduce:**
Create a picking with multiple lines.
Create a line with more stock than available on a product
Set the picking to 'To Be Done'
Reserve
The picking is partially available
Go to the product, update the stock to more than quantity to deliver

**Current behavior:**
Reservation button is not available so that it's impossible to recalculate the stock before validating the shipping.

**Expected behavior:**
reservation button should be available even in partially available state

**Comment by jco-odoo** [comment]
You are right.  The button Reserve should be there in partially available state too.  https://github.com/odoo/odoo/blob/9.0/addons/stock/stock_view.xml#L802 should have states="confirmed,assigned,partially_available"

**Comment by Yenthe666** [comment]
Hi @jco-odoo,

Are you talking about this line?
https://github.com/odoo/odoo/blob/11c73cd0aa2ff9cbfde8e5eebf3f22dfa1c805f1/addons/stock/stock_view.xml#L902
Would you still accept a PR that changes these states? If so I'm happy to make it in order to fix this one and save you some time.

Regards,
Yenthe

**Comment by jco-odoo** [comment]
Check the line below.  It is the same, but with a different label.

**Comment by Yenthe666** [comment]
Awesome - so this was already fixed. Thanks.
