### ISSUE TITLE
[9.0] timesheet possible on closed / archived project !

### ISSUE THREAD

**Issue by laurentmeuwly** [odoo/odoo#11022]
Impacted versions: 9.0 enterprise

Steps to reproduce:
1. Just close and/or archive a project
2. Go to timesheet
3. You are still able to enter time on the project!

Current behavior:
It is always possible to enter time on closed and/or archived project

Expected behavior:
If the project manager decide to close or archive the project, this means there should be not future activities on it. So the project must not appear in the drop-down list of projects to select.

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Hi @laurentmeuwly,

Thanks a lot for your bug report.
This behaviour is still the case.
@jem-odoo was this done by design / with a reason or should we perhaps improve this?

Regards,
Yenthe

**Comment by jem-odoo** [comment]
Hello,
Indeed, since many version you can timesheet on archived projects. It seems that the case was never thougth ^^". Now that we are avare of it, we will try to prevent this to happen.
Unfortunately, for stable version, as the fix would required to add related field, we can't fix this in 9.0, 10.0 or 11.0. Timesheet on project will change for v12, so we will try to include this in future dev.
Thanks for reporting anyway.
Regards

**Comment by Yenthe666** [comment]
@jem-odoo did this get an internal Odoo task?

**Comment by jem-odoo** [comment]
Hi,
yes for v12.0, if to be timesheetable, a project will have to be linked to an active analytic account. Other, you won't see the timesheets tab. 
Regards
