### ISSUE TITLE
Aged Partner report raises exception of referencing unbound variable for 'at_least_one_amount'

### ISSUE THREAD

**Issue by kmetaxas** [odoo/odoo#11030]
Impacted versions: 
master , 9.0. Possibly more.
Bug introduced in commit [9eb612c8161ca3b27e179226b535ac3e3258259b](https://github.com/odoo/odoo/commit/9eb612c8161ca3b27e179226b535ac3e3258259b)

Steps to reproduce:
go to accounting->pdf reports->aged partner balance

Current behavior:
exception of referencing unbound local variable "at_least_one_amount"

Expected behavior:
Get PDF report

Video/Screenshot link (optional):

in  _addons/account/report/account_aged_partner_balance.py_ 
variable `at_least_one_amount` is not guaranteed to be initialized before reaching line 158 _(if at_least_one_amount)_
Just initialized  it to False at some point (or make sure the code path is guaranteed to execute an initialization)

**Comment by Yenthe666** [comment]
Hi @kmetaxas,

Thanks a lot for your bug report.
In the meanwhile this code has changed and this issue is no longer reproducable as you can see here:
https://github.com/odoo/odoo/blob/11c73cd0aa2ff9cbfde8e5eebf3f22dfa1c805f1/addons/account/report/account_aged_partner_balance.py#L130-L167

Please update your Odoo source code to the latest version if you can still reproduce this.

Regards,
Yenthe
