### ISSUE TITLE
[14.0] fields.HTML set company_dependent doesn't work properly

### ISSUE THREAD

**Issue by houssine78** [odoo/odoo#110849]
Impacted versions: 14.0 and probably the following

Steps to reproduce:
set the signature field company_dependent and try to set two different values the connected user (though my preferences view) for two different companies. 

Current behavior:
The value doens't show in the signature field when reopening the view while it has properly be saved in the database. 
![image](https://user-images.githubusercontent.com/7766650/214300463-9a028d81-cc7b-43a4-bcd8-c9be71686110.png)
![image](https://user-images.githubusercontent.com/7766650/214301147-23fa3467-d6e3-42f0-9c9b-9ae619ab30cb.png)

Expected behavior:
Having the value being shown in the signature field.

After debugging for a while it appears that the problem comes from the cache. Reading the value [here](https://github.com/odoo/odoo/blob/14.0/odoo/api.py#L791) show that the value isn't set (print screen below) for the field while it is in the database (see previous print screen)

![image](https://user-images.githubusercontent.com/7766650/214304887-70864e22-8c2b-49aa-93a5-d1ad969db7f5.png)

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by jorv-odoo** [comment]
Hello Houssine78 (copy of official support ticket response),

After verifying a few things, here is the current situation concerning company dependent signatures:
- the company_dependent parameter is not supported for HTML fields, and more specifically the way signature is implemented in the res.user table, no easy fix is foreseeable in the near future

Nevertheless your feedback will be taken into consideration and If the “issue” you’ve mentioned comes up often, we may reconsider tackling it.

Concerning your implementation, as "company_dependent" is supported in Many2one fields, you could try creating a custom module that creates an intermediary model that stores the signature on a per user/company basis then modify the res.user.signature field to point to that model using a Many2one approach.
Since customisations are outside of the scope of standard Odoo Support, I am not able to assist you more in this matter.

Best regards
