### ISSUE TITLE
 0 cannot identify image file <cStringIO.StringI object at > in python virtual enviroment

### ISSUE THREAD

**Issue by chand3040** [odoo/odoo#11111]
Impacted versions: 9.0

Steps to reproduce:
Here is the issues that I am facing cannot identify image file <cStringIO.StringI object at some memory location>.
When I try to install odoo 9 with demo data it gives that error. Below is log of my PIL Imaging Library inside virtual environment.

---

PIL 1.1.7 TEST SUMMARY

---

Python modules loaded from ./PIL

Binary modules loaded from ./PIL

---

--- PIL CORE support ok

**\* TKINTER support not installed

--- JPEG support ok

--- ZLIB (PNG/ZIP) support ok

--- FREETYPE2 support ok

**\* LITTLECMS support not installed

---

Running selftest:

--- 57 tests passed

It says this file image is not in acceptable format and other module images after that :-

 while parsing openerp/addons/base/base_data.xml:99, near

```
<record id="public_user" model="res.users">

<field name="name">Public user</field>

<field name="login">public</field>

<field name="password"/>

<!-- Avoid auto-including this demo user in any default group -->

<field name="groups_id" eval="[(6,0,[])]"/>

<field name="image" type="base64" file="base/static/img/public_user-image.png"/>

<field name="partner_id" ref="public_partner"/>

<field name="active" eval="False"/>
```

Would like to know what is the possible solution to this the server has got multiple versions of odoo installed and all are working in virtualenviroment.

 Versions in odoo 8 works well for me I can upload png images but it creates issue in case of default odoo images that are installed in demo data.

Though I have tried a lot of stuff but seems like things are not working on it. Though I know I can wipe out and install if from scratch but that won't be feasible in my case and other cases too.

Would request if any one has a solution to it can help me out for the same.

**Comment by pedrobaeza** [comment]
Hi, this seems something related to your deployment, as all the recent builds are correctly deployed in runbot (http://runbot.odoo.com/runbot), so please be sure you are following the proper installation instructions. Check them on https://www.odoo.com/documentation/11.0/setup/install.html. In concrete, you have to use the library Pillow instead of PIL and be correctly compiled.

I'm closing this issue now, but if you feel this can be something reproducible with other steps, please reply adding all the additional information for reproducing the problem.
