### ISSUE TITLE
[9.0] api.onchange modification One2many field with NewItem does not works 

### ISSUE THREAD

**Issue by ricco386** [odoo/odoo#11236]
Impacted versions: **v9.x**

Steps to reproduce: 

define models that have One2many and Many2one raltion:

```
class ClassA(models.Model):
    _name = 'module.class_a'
    CYCLE = 'cycle'
    AMOUNT = 'amount'

    Other = (
        (CYCLE, 'Cycle'),
        (AMOUNT, 'Amount')
    )
    name = fields.Char(string='Name', required=True)
    other_influence = fields.Selection(Other, string='Other influence', required=True)
    related = fields.One2many('module.class_b', 'components')

    @api.onchange('other_influence')
    def _other_influence_change(self):
        self.related = None
        if self.other_influence == self.CYCLE:
            b = {
                'name': 'XXX', # Lets say we do generate something here, hardcoded just to show the problem. 
            }
            self.related += self.related.new(b)

class ClassB(models.Model):
    _name = 'module.class_b'

    name = fields.Char(string='Name', required=True)
    components = fields.Many2one('module.class_a', ondelete='no action')
```

Current behavior:

When clicked at _Other influence_ field in view, function __other_influence_change_ is triggered as it should, related field is cleared but when executing `self.related += self.related.new(b)` new row is added in view, but it is empty, eg. **Name field is blank**. And save ends with error:

```
openerp.sql_db: bad query:  SELECT "module_class_b"."components" as "components","module_class_b"."id" as "id" FROM "module_class_b"
                        WHERE "module_class_b".id IN ('one2many_v_id_53')  ORDER BY "module_class_b"."id"
```

However, if I change new to create in line `self.related += self.related.create(b)` and click at _Other influence_ field view works fine and new row is added, eg. **Name field contains XXX**. Save works as well, but **this is obviously bad setup** as each click on _Other influence_ would create and entry in DB (but works, both updated view and also store, but create shouldnt be used here).

Expected behavior:

When clicked at _Other influence_ field in view  function __other_influence_change_ is triggered with  `self.related += self.related.new(b)` and new row is added in view, and it shows data from variable b, eg. **Name field contains XXX**. And save to the DB successfully once user pres the save button.

Video/Screenshot link (optional):

**Comment by thomas-tankengine** [comment]
Hello ricco386,

I got the same problem on v. 9.0. New lines are added but fields are empty, though I specified their values. And I got the same problem when saving too.

**Comment by dansanti** [comment]
same problem here, in odoo9:
steps:
1.- create a one2Many field into order_line
2.- set default context to order
'default_order_line': [[5],[0,0,{ 'one2many_field':[[0,0,{'field_1':value1}],[0,0,{'field_1':value2}]], rest_order_line_fields...}]]

this make 2 empty lines in one2many_field,with ie.:

[[4,"one2many_v_id_443"],[4,"one2many_v_id_444"]]

 but if you add a onchange('some_value'), and trigger it when order line is created , and in :
``
@api.onchange('some_value')
def onchangeSome(self):
 self.one2many_field = [[0,0,{'field_1':value1}],[0,0,{'field_1':value2}]
``
works fine, :/

**Comment by dansanti** [comment]
Hi! check if with this pr can solve your problem https://github.com/odoo/odoo/pull/12249

**Comment by ricco386** [comment]
thanks @dansanti your fix seems to work for this issue. Hope your MR will be accepted soon.

**Comment by dhannyz** [comment]
This has solved the issue of an onchange in the parent clearing out the fields in a One2many in a child;
eg:  If a custom One2many in sales.order.line form view is filled out that is linked to an unsaved sale.order, and then the partner_id is changed in the sale.order form view, the One2many field values used to be lost.

However, if there is a Many2one field inside the child's One2many, and and onchange occurs in the parent, this will fail when the record is saved or created.
The ORM tries to enter the Many2one field into the database as a tuple array instead of a single integer;

**Steps to reproduce:**
product.product Many2one inside the sale.order.line custom One2many.
ie   sale.order -> sale_order_line_ids (o2m) -> sale_order_line_custom_ids (o2m) -> product_id (m2o)

- Create a new Sales Order
- Set a Partner on the Order
- Add a Sales Order Line entry via form view (tree editable="False")
- Add a Custom_Ids line entry in a tree inside Sales Order Line form.
- Return to Sales Order and change the partner (this will call some onchanges)
- Attempt to save the record

This will result in an error like;
```
  File "/opt/odoo10/odoo/sql_db.py", line 218, in execute
    res = self._obj.execute(query, params)
DataError: invalid input syntax for integer: "[12345] Test Product"
LINE 1: ...line_custom_id_seq'), 1, 12.0, NULL, 13, ARRAY[1, '[12345] T...
```
Which is caused by this attempted database operation;
```
odoo.sql_db: bad query: INSERT INTO "sale_order_line_custom" ("id", "product_int", "price", "description", "sale_line_id", "product_id", "create_uid", "write_uid", "create_date", "write_date") VALUES(nextval('sale_order_line_custom_id_seq'), 1, 12.0, NULL, 13, ARRAY[1, '[12345] Test Product'], 1, 1, (now() at time zone 'UTC'), (now() at time zone 'UTC')) RETURNING id
```
specifically **ARRAY[1, '[12345] Test Product']** is the offender
create's vals dictionary looks like
```
{..., product_id:[1, 'Product Name'] , ...}
```
when only the first entry of the array is required  (this looks like the format of a m2o name_get that isnt getting converted to a write properly)

**Workaround:**
extending the create & write functions like so works;
```
    @api.model
    def create(self, vals):
        if 'product_id' in vals:
            vals['product_id'] = vals['product_id'][0]
        res = super(MedifabSale_SaleOrderLineCustom, self).create(vals)
        return res
```
```
    @api.multi
    def write(self, vals):
        if 'product_id' in vals:
            vals['product_id'] = vals['product_id'][0]
        res = super(MedifabSale_SaleOrderLineCustom, self).write(vals)
        return res
```
There are other issues here however with onchanges in a grandparent causing grandchildren to unlink from the middle parent
