### ISSUE TITLE
"Make to order" doesn't respect "Responsible"

### ISSUE THREAD

**Issue by alaa9jo** [odoo/odoo#11291]
Impacted versions:
9.0c_20150310

Steps to reproduce:
- Login to account "administrator"
- Create a product i.e. dough and make sure "Manufacture" and "Make to Order" are both checked
- Add bill of materials to the dough,i.e. sugar etc
- Create a product "snackbar"
- Add dough as bill of materials to snackbar
- Logout of user administrator
- Login with another user i.e. "supervisor"
- Go to "Manufacture" and create a new order
- Make sure who's responsible of the new order is another user i.e. "James" by setting "Responsible" to "James"
- Click on Save
- Click on "Confirm Production"

Current behavior:
- You will notice that two manufacture orders are created, one of them is snackbar and the responsible is "James" and another order of "dough" but it's "Responsible" is "administrator" not "James"

Expected behavior:
Both manufacture orders of snackbar and dough must have the same "Responsible" , administrator have nothing to do with this

Video/Screenshot link (optional):

**Comment by sle-odoo** [comment]
Hi,
I understand that it is misleading but sadly it is the expected behavior. These automated creations of manufacturing order should be done as administrator, as they could be generated by a salesman for example, when a sale order is confirmed and the procurement_jit module is enabled.

We have an opened feedback about it, it could be fixed in the upcoming versions.

Regards
