### ISSUE TITLE
[16.0] Slow performance on shop categories with attribute.

### ISSUE THREAD

**Issue by esakarya** [odoo/odoo#113158]
We have 75k products, and 218 attributes, some attributes has high count attrbute values, eg: model attribute has 1300 value,
so when open a category on shop TTFB is almost 3 secs. its adversely affect performance.
**how can fix that ? category attrbiutes dont caching with orm ?**

and you can check the image,
odoo work on my local computer , with 8 core i5 12600k cpu, and 8 GB ram.
![image](https://user-images.githubusercontent.com/61056242/220148615-8b667806-8325-4fe9-9b78-4f7bae1bf1f0.png)

**Comment by skygunner** [comment]
For that amount of data, I'd say the main bottleneck is your hdd IOPS, ram amount and cpu. 
Go with 16 core high frequency relative new cpus like AMD 5900X in consumer leavle, 
and at least 16GB RAM, 32GB would be nice,
large 3G~4G speed NVME to help your database get IOPS,
Use pgtune website to tune your postgresql settings, 
use linux instead of windows (I think you might be running 32bit python/postgresql in windows),
make sure odoo config enabled multi - threading for running under windows (or multi process under linux)

Also the new Python 3.11 would be about 10~20% faster, but you might wont see this until odoo 17/18.
It is working with odoo 16.0, I think its ok for development, but untested for production enviroment with the combination of Python 3.11+odoo 16.0.

**Comment by moylop260** [comment]
Could you share a python profiler (py-spy) and psql profiler (pgbadger), please?

**Comment by skygunner** [comment]
> I understand but lets talk about my config. its running ubuntu 22 lts, cpu is 12600K, disk is nvme 980 pro. problem is odoo calculating 22K product.template data's attribute value's for creating filters. also i did pgtune with different ways.

I see. There should be room can be improved on the code

**Comment by esakarya** [comment]
I hope i am uploading correct reports..

[py_profiler.zip](https://github.com/odoo/odoo/files/10840951/py_profiler.zip)
[pgbadger.zip](https://github.com/odoo/odoo/files/10840952/pgbadger.zip)


just following query take 3.5 secs.

![image](https://user-images.githubusercontent.com/61056242/221598767-15ba5036-d3a9-47e4-941b-7d1e6b82d071.png)

**Comment by esakarya** [comment]
@moylop260 i applied patch's both borrar.txt is empty.
i think odoo testing similar think a few hundred products,  but need some streess tests etc.
so whats the next step ?

**Comment by moylop260** [comment]
@esakarya 

Maybe my patch is wrong

But the main focus is to know where these kinds of queries are executed

**Comment by esakarya** [comment]
ok who can help us ? can u mention anyone ?

**Comment by esakarya** [comment]
This is a serious problem for e-commerce why no one cares?

**Comment by moylop260** [comment]
> and the Time Consuming Queries is most of the time cumulative:
> - ![Screenshot 2023-02-27 at 12 15 42](https://user-images.githubusercontent.com/6644187/221648817-3c4e68d0-81ac-4d5a-9d2e-773a9a994623.png)

I think you need to look for where this query is built

**Comment by esakarya** [comment]
i am not contributor, and odoo dont care about similar important problems, they just test with a few products, but real word different no one use e commerce with 10 15 products. Anyway i will share my bad experience at everywhere.

**Comment by moylop260** [comment]
Hi @esakarya 

I had created a few issues related with performance from website, also fixing a few ones

Check the following real world using ~360k products (try to search a product)

https://www.absaonline.mx

We were frustrated than you at beginning, but could be done:
 
https://twitter.com/moylop260/status/1491593734261284864?s=46&t=AcqCBPmV8tqaYuICLcEFKg

I'm not odoo company worker but even I can help you but you need to look for where your slow queries are running from your instance from sql_db.py file in order to share you the best fix

**Comment by moylop260** [comment]
Yes, I totally agree

You are right!

It was optimized 1 year ago, maybe a recent change after that needs to be improved too, 

In this moment gtmetrix is grade C

So, it is not a good example right now

I will check it

But for your case your time response is ~3s and the time of the slow query is ~3s too

So, it could be done easier since you only need to mitigate the big query

There are many answers to reply:

Could it be done using LRU-Cache?
Is it using CDN?
Is it using new view cache feature?
Is it using ir.rule with dot domain?
Is could be computed with store?
Is the query from your custom code or an adaptation or is it out-of-the-box?
Is it using base.automation?
Is it could be optimized using another way (e.g. read_group)?

And so on...

Check the following talk about:
 - https://www.youtube.com/live/JypkEjnoink?feature=share

(Sorry my not good English, but I really want to help in similar situations)

Regards!

**Comment by esakarya** [comment]
C'monnnn odoo developers where are u ?

**Comment by antonijo01** [comment]
Can you write something more about the server on which Odoo is installed? 
Is it odoo.sh or a private server? 
What is the specification of the server?
Do you use Cloudflare for domain management and CDN?

TTFB measurement starts with the client sending a request to a server. However, the server might not get the request instantly. Factors like the time to complete a DNS lookup, the speed of the user’s connection, the location of the server, and disruptions in the connection influence the time required for a server to receive the request.

**Comment by esakarya** [comment]
Check reports, read posts.

**Comment by esakarya** [comment]
I'm leaving Odoo, I think it no longer meets the needs of the industry. 
Months past, odoo still didnt reaction bout thoose big e-commerce problems. 
bye

**Comment by vava-odoo** [comment]
Fixed by the following revert: https://github.com/odoo/odoo/pull/125187

**Comment by esakarya** [comment]
with /shop, TTFB was 7.9 now 6.8 , 12k product
