### ISSUE TITLE
cancel uninstalling module by closing confirmation dialog still tries to uninstall, breaks server

### ISSUE THREAD

**Issue by grexe** [odoo/odoo#11399]
(see also related forum thread https://www.odoo.com/de_DE/forum/hilfe-1/question/modules-marked-as-uninstalled-server-fails-to-start-99268)

When clicking "uninstall" in the apps/modules list, a confirmation dialog came up that lists dependent modules that would be uninstalled along with the module selected for uninstallation.

When trying to abort by clicking the close icon (didn't try with "Cancel" yet...), the action is still executed, and the module as well as all related modules are marked for uninstall.

While it is possible to unmark the modules from uninstallation, the web interface stopped working after 3 or so modules, and restarting the server just gave me this error (tried to uninstall the discussion module which has dependencies on all the other core modules, which I don't understand and think is a bug):

> ParseError: "The ID "sales_team.team_sales_department" refers to an uninstalled module" while parsing /usr/lib/python2.7/dist-packages/openerp/addons/crm/crm_data.xml:16, near
> True
> sales
> 

Using Debian Linux 8.3/testing with latest nightly as of today and PostgreSQL 9.5.

The only way to restore my installation was to run the server with the "--update=all" option.

**Comment by Yenthe666** [comment]
Hi @grexe,

This looks partially changed / fixed. When you now click on a module to uninstall and then click the cancel button the dialog will be closed and the button "Cancel uninstall" will be shown:
![image](https://cloud.githubusercontent.com/assets/6352350/15999235/7c6a48dc-3144-11e6-9ccd-283e9c179387.png)
The module isn't uninstalled or anything however, the buttons are just invalid.
The cancel button does exactly what it should do though.
@mart-e could you assign somebody on this or fix it? It looks quite strange.

**Comment by mart-e** [comment]
As said Yenthe, when you close the popup, you see the "cancel uninstall" button.
The explanation is that the cross and cancel button do not do the same things.

When you click on uninstall button ob a module, it will change its state from "installed" to "to uninstall" waiting for your confirmation. Clicking on confirm will pass from "to uninstall" to the "uninstalled" state and cancel will go back to "installed" state. However if you do not take any action (close the popup windows, close the browser, throw you computer by the window, etc.), the module will stay in the "to uninstall" state, waiting for another action on modules to be made (install/remove another module, restart of workers, etc.) to process it's scheduled action.

If you closed the confirmation window by mistake and want to mark all as installed again, you can click on "cancel uninstall" > "uninstall" > "cancel" to mark all as installed again.

> tried to uninstall the discussion module which has dependencies on all the other core modules, which I don't understand and think is a bug
No because almost all modules wants to be able to have a discussion, to track the changes of states, having followers to documents, share by email, etc. This is why almost all modules needs the mail module.
