### ISSUE TITLE
[8.0] Website Livechat raises mixed content warning

### ISSUE THREAD

**Issue by yannprada** [odoo/odoo#11406]
### Impacted versions:
8.0-20160318
modules: 
- im_livechat
- website_livechat

### Steps to reproduce:
- set up a server with ssl encryption and latest odoo server
- install webiste_livechat module

### Current behavior:
Firefox and chrome flag livechat calls as mixed content (http)
I inspected with the console, and, yes, some requests are made in plain http
### Expected behavior:
don't fire plain http requests

**Comment by yannprada** [comment]
Changing the ir.config_parameter['web.base.url'] to https://<host> stopped im_livechat for serving in http. But does that solves the issue ? Not sure, as I always fought with this parameter. It keeps changing back to http://

**Comment by Yenthe666** [comment]
@yannprada if you want to be absolutely sure that the `web.base.url `parameter doesn't change you can add another parameter.
Name: `web.base.url.freeze`
Value: `True`

If you add this parameter it will always use the `web.base.url` that you've configured, no matter what. Otherwise the `web.base.url` will always update when you login to your Odoo again.

**Comment by yannprada** [comment]
Yes, I just figured it out.

But, should the im_livechat module rely on web.base.url ? It seems broken if we have to manually add freeze on each database.

**Comment by Yenthe666** [comment]
@yannprada I'm not sure about that one. That is for somebody from Odoo to answer, I'm sure they have their reasons for this. 
@odony can you elaborate a bit on this?

**Comment by odony** [comment]
The `web.base.url` parameter is used in many places where the Odoo server may need to be contacted from external locations. This is the case here, as the Livechat system can be integrated on other websites. Each livechat channel also has its own URL that you can send by email to your customers to invite them for a chat.

Because this is technical stuff, Odoo uses heuristics to determine the `web.base.url` for your deployments: the last used URL when the admin account logs in. So you would only need to use `web.base.url.freeze` if you are using different addresses for accessing the backend and frontend, either via different domains, or different protocols (HTTPS vs HTTP as you describe), which is a rare case. Most people who setup SSL also use SSL for their backend access, so they do not have any issue (on Odoo Online we have an automatic redirection from HTTP to HTTPS, for instance)

So the system appears to be behaving as designed, you just need a customization because you seem to have an unusual setup (not sure why you do this?).

BTW you always need a correct `web.base.url` for proper Odoo operations, not just for the Livechat but for all external communication, emails, portal links, etc.

Hope this helps..

**Comment by yannprada** [comment]
@odony Thanks for the in-depth explanations!

**Comment by treviser** [comment]
@odony I can explain one of the reasons to have a setup like this. In our case it is because of restoring a database from another server and/or from a setup without SSL, because a new customer database is set productive after an installation/configuration phase (our customers can't go live with an empty website).

**Comment by odony** [comment]
@treviser I see, thanks. This kind of setup should not experience any issue: the `web.base.url` parameter will be reset as soon as "admin" logs into the system after the database restore. So if your (production) web server is configured to only allow HTTPS (-> redirect HTTP to HTTPS) you should not have any trouble, it will fix itself automatically, and you should not need `web.base.url.freeze` either.

**Comment by treviser** [comment]
@odony Whatever happened that I've sometimes encountered this problem, thanks to your very good explanation I now know how to avoid it. :-)
