### ISSUE TITLE
Unable to install Odoo 16.0 with latest Python version (3.11.2)

### ISSUE THREAD

**Issue by Fincentxyz** [odoo/odoo#114195]
**Impacted versions:**
16.0

**Steps to reproduce:**
Install odoo's requirements with Python version 3.11.2

**Current behavior:**
Unable to install 'gevent', 'greenlet', 'lxml', 'Pillow', and 'reportlab' with Python version 3.11.2

**Expected behavior:**
Being able to properly install all requirements with the latest Python version

---

I believe the current requirements.txt file is outdated if you're using the latest Python version (3.11.2). The installation tutorial says "Odoo requires Python 3.7 or later to run". This is currently not true however.

The 'Pillow' package for example, requirements.txt says "Pillow==9.0.1", but on the website of Pillow it says you can only use 9.0 with Python 3.10...

Either update the required packages list or specify up to which Python version you're able to use with Odoo. (Python 3.10.10 works, so put a disclaimer to use >3.7 & <=3.10.10)

**Comment by Fincentxyz** [comment]
In addition to this, some outdated packages might contain vulnerabilities, such as libass 0.18.0 according to a requirements tool on PyCharm:

![image](https://user-images.githubusercontent.com/23012061/222455143-1df50a85-9969-404f-8b9e-ab113ae48e8e.png)

**Comment by skygunner** [comment]
I believe just use newer version of gevent / greenlet / lxml / pillow would enable you to run it under python 3.11.
You can also push all packages fast forward to almost the newest like below. But it is untested, only good for testing and devleopment purpose. 
The project gives requirements.txt that is well tested and suitable for production. The vulnerability you mentioned might just not affecting odoo otherwise the team would working on that. 

`Babel==2.11.0
chardet==5.1.0
cryptography==39.0.1
decorator==5.1.1
docutils==0.19
ebaysdk==2.2.0
freezegun==1.2.2
gevent==22.10.2
greenlet==2.0.2
idna==3.4
Jinja2==3.1.2
libsass==0.22.0
lxml==4.9.2
MarkupSafe==2.1.2
num2words==0.5.12
ofxparse==0.21
passlib==1.7.4
Pillow==9.4.0
polib==1.2.0
psutil==5.9.4
psycopg2-binary==2.9.5
pydot==1.4.2
pyopenssl==23.0.0
PyPDF2==3.0.1
pyserial==3.5
python-dateutil==2.8.2
python-ldap==3.4.3
python-stdnum==1.18
pytz==2022.7.1
pyusb==1.2.1
qrcode==7.4.2
reportlab==3.6.12
requests==2.28.2
urllib3==1.26.14
vobject==0.9.6.1
Werkzeug==2.2.3
xlrd==2.0.1
XlsxWriter==3.0.8
xlwt==1.3.*
zeep==3.4.0

`
