### ISSUE TITLE
RFE: import meetings for multiple customers using CSV

### ISSUE THREAD

**Issue by grexe** [odoo/odoo#11418]
(using 9.0c.20160319 on Debian Linux 8.3 testing ("stretch"))

While it is possible to import meetings for a single customer, and also easily possible to import a list of customers using CSV files (once you know that the "Import" button is only visible in list mode, erk!), I found no way to import a list of meetings with multiple customers, which is a common use case when migrating from other systems or simple customer databases or even Excel sheets (ugh).

In my case, I had a simple database table exported from a legacy system with customer ID, meeting dates and details.

This maps nicely to Odoo's CRM concept of customers and related meetings, I'd only need a way to import a flat list with many customers and meetings, mapping the internal customer ID from Odoo's database (created after importing the customers, storing the original ID from the legacy system in an unused field, in my case the only field I found was the barcode), to the customer ID from the legacy system in the meetings table.

All other fields would be straightforward to import, but it took me some time to figure out the related tables for a meeting with all affected relations:
* calendar_event
* calendar_event_res_partner_rel
* calendar_attendee

All of which seem to be necessary for the meeting to show up in the contacts view, this is also how meetings are created by Odoo as far as I gathered.

It would really be helpful and bring Odoo into production more easily if importing data from existing systems would be more straightforward and didn't require users to write quite advanced 3-way INSERTs all over Odoo's tables just to import meetings from a legacy system...

**Comment by gdgellatly** [comment]
It doesn't require users to do that at all.  Personally I've found just
writing a bunch of linked csv's and using in a module to work fine.  Look
at any localization module, and how they import linked tables.  You could
even use the old systems IDs as an identifier.  It could be done using the
import button I suppose, but I doubt anyone tries to do a whole system like
that.

There are myriad other options, 3 way inserts being the worst of them.

**Comment by grexe** [comment]
you mean using the legacy ID as external ID field during CSV import?
Well as I said you can only import meetings for a single customer over the calendar UI's hidden import button, which is a pity and not enough for real life needs.

I don't see why 3-way inserts should be bad, they are a well documented and supported functionality in any modern database, as PostgreSQL surely is, and that way I get full transactional support.
I was following this excellent SO answer fyi:
http://stackoverflow.com/a/20561627/160799

**Comment by gdgellatly** [comment]
Gregor,

I can tell from your posts that you are very new to this.  The import UI is
not for full scale data migration.  Consider it basic data maintenance and
a small subset of the csv and xml import functionality embedded in the
framework.  Beyond the framework functionality, again look at the
localization modules for multitable csv imports, there are myriad other
ways to transform and load data, correctly, via the ORM.  Kettle for
example has an OpenERP step built in, others have created csv generation
tools, others use connectors between their systems and there are far more.
What tool you use depends on the scale and nature of what you need.

However your original statement was the users were REQUIRED to resort to
complex direct SQL queries.  This is simply untrue.

There are very many reasons that SQL inserts are not the best choice,
especially if you do not understand how the ORM works and exactly what the
data model looks like in the database schema.  Most people will tell you
security, tbh that is not a real issue to me in data loading.  More it is
functional fields, defaults, python constraints and fields that can have a
different value depending on context.  The worst of those models is the
partner model IMO.  Ordinarily, on the rare occasion I do resort to bulk
data loading via SQL, which is purely for speed and for which we wrote a
specialist tool that provides some sanity, after doing direct inserts I
need to drop any stored related and functional columns of the affected
models and then upgrade all modules, and then ensure that properties are
correctly restored.

Bypassing the ORM should be a last resort, not a first resort because the
UI doesn't do what you want, a task it was never really intended for.  But
yes if you load csv data from a module, the external_id can be anything you
want, and the legacy id is one sensible choice.

**Comment by JKE-be** [comment]
@gdgellatly Thank you for your answer :+1: 

@grexe: 
Simple way is probably to write a small python script which do it in XMLRpc (using ORM). (with Erppeek ?)
Or use the Google synchronization to synchronize an actual calendar (works well if no recurrent event).
But use the ORM and not directly in psql else you will have some unexpected behavior.
