### ISSUE TITLE
more stable, non-nightly update channel for Odoo 9 needed

### ISSUE THREAD

**Issue by grexe** [odoo/odoo#11419]
see also https://www.odoo.com/de_DE/forum/hilfe-1/question/odoo-9-stable-repository-with-security-updates-96587 - I think the original poster was looking for a more stable update channel for Odoo 9, which I am also missing.

While the dashboard mentioned in the thread above is really cool and informative, I'd need a safe update path for my Odoo 9 installation, not the latest nightly build, but tested and stabilized snapshots, just like Debian testing.

The official [https://nightly.odoo.com/](Community Edition download site) states that:
> 9 (stable) ... Current stable branch, released in October 2015 - the *recommended* version.

But just links to the latest nightlies... so is it really *recommended* to run the *nightly* builds of Odoo and call it stable? I'd not think so, in a production environment... (but Odoo 8 is quite old, so I don't want to start with an outdated version)

**Comment by odony** [comment]
Odoo uses a rolling release mechanism. Here is how it works.

Odoo installers are updated daily based on the latest bugfixes applied to the stable branches.
All commits are fully tested by our continuous integration system (runbot.odoo.com) and the nightly builds are only published if the tests pass and if the packages do install without error.

We have stopped releasing arbitrarily "blessed" minor versions 5 years ago, because there was no point:
  - those versions would not pass more tests than the automatically tested ones
  - all changes applied to [stable branches](https://www.odoo.com/page/odoo-long-term-support) respect [the stable policy](https://github.com/odoo/odoo/wiki/Contributing#what-does-stable-mean), a long list of strict criterions that makes those changes safe, low-risk, and high-value only
  - it would uselessly delay/complexify the delivery of bugfixes to customers and users

So those nightly builds are "tested and stabilized" snapshots for you.

The unstable development only happen in unstable branches: "saas-X" and "master". You could see the "saas-X" branches as the equivalent of debian testing, and "master" as debian unstable.
You should definitely never use those for production systems.

Now of course when it comes to updating software, the golden rule is: if it's working, don't fix it :-)
So unless you have a specific bugfix you'd like to pull, you probably should not be pulling updates every day.

As for critical security fixes, there is no dedicated channel for publishing them, because they often depend on earlier fixes. So when there is a security fix, you really *must* pull the latest version.

We do announce critical security fixes on public channels, including our [community mailing list](http://www.odoo.com/groups/59), twitter, and on [GitHub](https://github.com/odoo/odoo/issues?q=is%3Aissue+label%3ASecurity). Odoo Enterprise customers also receive prior notifications of these security alerts via a private mailing list.

Having dedicated update channels that only catch up with the regular ones when there is a security fix would have a very limited value, and does not seem worth the maintenance burden.
Admins should simply monitor security alerts, and when there is one, carefully review the impact and update to the latest stable build.

I hope this helps...

**Comment by eronlloyd** [comment]
This discussion is very helpful, but it should be clearer to new developers/integrators on how best to manage Odoo installations. The concept of nighly builds is still very much assumed to be unstable, development releases for testing, **not** production-ready.

**Comment by odony** [comment]
I think we can close this issue as an "answered question" :-)

**Comment by grexe** [comment]
thaks @odony for the elaborate and helpful answer! I must say I never had any issues with updating this way, so I can attest your test and build pipeline works fine:)
It's still rather unusual, though, and leaves a fuzzy feeling without an official backup+restore plugin...

Also waiting for a fix for #11417 so this is my main motivation to upgrade - performance has improved in a lot of areas, it seems, but this particular case still keeps me puzzled.
