### ISSUE TITLE
[16.0] Reset to Draft button disappear after changed Price on Vendor Bills 

### ISSUE THREAD

**Issue by rinaldifirdaus** [odoo/odoo#114732]
Impacted versions: 16.0

Steps to reproduce: 
1. Create & Validate PO>Validate transfer
2. Create Bill & post the bill
3. Click reset to draft on the bill>change price of the product>post the Bill
4. Reset to Draft button will be disappear

Current behavior:
User could not revise the bill when they need to re-modify the vendor bills.

Expected behavior:
This issue might related to below merged PR:
[[FIX] stock_account: bill price change fix #103068](https://github.com/odoo/odoo/pull/103068)
The initial comment of the PR "This commit removes previous correction layers created when the user does this action."
would be solution for the wrong valuation issue, instead of hiding the reset to draft button to prevent user modify the bills.
But somehow the commit is to hide the reset to draft button.
Is there a way for the user to modify the bills with this condition?

Video/Screenshot link (optional):
https://drive.google.com/file/d/1GXl4n-fUtxdzsWHO8ptzwb0hKf4T4Eoc/view?usp=sharing

Support ticket number submitted via odoo.com/help (optional):
Enterprise ticket #3224622

@qrtl

**Comment by yostashiro** [comment]
OPW: 3224622

**Comment by dipak-shah** [comment]
Any update on this major issue ?

**Comment by kikopeiro** [comment]
Any update please?

**Comment by dipak-shah** [comment]
@yostashiro @vava-odoo Can you help in expediting this ticket?

**Comment by vava-odoo** [comment]
Hello,

The Enterprise support ticket was closed with a "limitation of the current version" answer.

In fact, the button is hidden because clicking on it would potentially raise problems and the stock valuation can be wrong. It was therefore decided to hide it until the flow is entirely supported.

There is an internal task targeting master to better handle this flow in future versions.

In the meantime, you can customize the view to show the button by removing the `invisible` in the xml file. Keeping in mind that it may lead to valuation problems as stated before.

Best,

**Comment by pedrobaeza** [comment]
Module implementing the full feature: https://github.com/OCA/account-invoicing/pull/1813
