### ISSUE TITLE
[15.0] sale: cannot enter custom attribute value on mobile

### ISSUE THREAD

**Issue by COUR4G3** [odoo/odoo#114737]
Impacted versions:

15.0. May affect other versions unless there have been major changes to the product configurator.

Steps to reproduce:

- Create an attribute with one or more values, at least one of which allows custom entry.
- Create a product using this attribute and attribute value with custom entry.
- Create a sales order on the mobile app or browser (or use the responsive view in Chrome or Firefox)
- Select the product with custom attributes you want to add.

Current behavior:

The desktop view lets you choose a product.template and then pops out the product configurator for you to enter the custom attribute values. The mobile view only lets you choose a product.product, and has nowhere to enter the custom attribute values. This is only fine if you have attribute values that are not custom, since you can pick the exact variant.

Expected behavior:

On mobile, you should still select the product.template, and the product configurator or similar dialog should appear to allow you to enter custom attribute values - or some other method to enter custom attribute values.

Support ticket number submitted via odoo.com/help (optional):

opw-3224574

**Comment by vava-odoo** [comment]
This will not be fixed in stable, but improved in next versions.

**Comment by AbdelAzizMohamedMousa** [comment]
Based on the information provided, it seems that the expected behavior is for the mobile view to allow the selection of a product.template and provide a way to enter custom attribute values. However, the current behavior does not provide a way to enter custom attribute values in the mobile view.

To address this issue, one potential solution would be to modify the mobile view to include a dialog or form that allows users to enter custom attribute values when selecting a product with custom attributes. Alternatively, the mobile view could be updated to allow selection of the product.template and then redirect the user to a separate page or dialog to enter custom attribute values.

It's worth noting that this issue may require further investigation and development to implement a solution, and it's important to thoroughly test any changes made to ensure that they do not introduce new issues or impact other parts of the system.
