### ISSUE TITLE
[16.0] mass_mailing mobile format distorted

### ISSUE THREAD

**Issue by rowemoore** [odoo/odoo#115112]
Impacted versions:
[16.0]
Steps to reproduce:
Create email using template with images
Current behavior:
ON mobile (Android 13 Gmail App) , the images are either distorted or if they display appropriately, the text is too small
Expected behavior:
Both text and image are displayed correctly.  I have tried every variation of image sizing and played with the embedded css.  I think the behavior is happening further upstream. 

![mobile_examples](https://user-images.githubusercontent.com/14188201/224792919-0078fd55-945b-436b-9644-4509a730925c.jpg)

Support ticket number submitted via odoo.com/help (optional):
ticket ID is #3230420.

**Comment by AbdelAzizMohamedMousa** [comment]
It's possible that the issue is with the Gmail app on Android 13, as different email clients and operating systems may render emails differently. Here are some things you can try to ensure that your email template is compatible with a variety of devices and email clients:

Use responsive design: Ensure that your email template is designed to adapt to different screen sizes and resolutions. This can help prevent issues with distorted images and text that is too small.

Use alt tags for images: In case an email client can't display an image, it's important to have an alternative text description. This can also help with accessibility for visually impaired readers.

Test your emails: Send test emails to a variety of email clients and devices to ensure that your email looks good and functions properly across all of them.

Use a third-party email service: Consider using a third-party email service, such as Mailchimp or Constant Contact, that has built-in features for ensuring email compatibility across devices and clients.

By following these tips, you can help ensure that your email templates are compatible with a variety of devices and email clients, including the Gmail app on Android 13.

**Comment by rowemoore** [comment]
Images in emails should have height and width properties outside of the inline styles. Odoo adds an inline style that has the width and height (style="width: 100%; height: auto; max-width: 690px" ).  Instead (or also) it should have regular img width and height tags.  
Having multi columns, grids, etc in an email is ridiculous IMHO, and the Odoo team should just look at what folks like substack do. 

Make it simpler and better please!

**Comment by rowemoore** [comment]
[119325]

**Comment by vava-odoo** [comment]
Solved by https://github.com/odoo/odoo/pull/119325
