### ISSUE TITLE
[8.0][BUG] Website_sale decimal separator weird comportment

### ISSUE THREAD

**Issue by jlaloux** [odoo/odoo#11553]
Impacted versions: [8.0]

Steps to reproduce:
1. Configure your language with decimal separator as ","
![image](https://cloud.githubusercontent.com/assets/7678583/14171221/15c59fd8-f732-11e5-8084-67a6c9c8dd79.png)
1. Once your language is configured, go into the shop and select an article. You'll see the price correctly with the comma:
   ![image](https://cloud.githubusercontent.com/assets/7678583/14171298/74a5e9cc-f732-11e5-9ba7-50d78fff24be.png)
2. Change the quantity and you'll see the coma has changed to a point
   ![image](https://cloud.githubusercontent.com/assets/7678583/14171315/950a5180-f732-11e5-9143-fb5c9687466f.png)

(Same comportment when adding to cart and trying to change the quantity. I suppose this is the same bug)
![image](https://cloud.githubusercontent.com/assets/7678583/14171340/b367ced2-f732-11e5-90ef-df753ace4b10.png)

Current behavior:
Comma changed to point in floating numbers in the shop

Expected behavior:
Comma should stay comma after changing the quantity

Video/Screenshot link (optional):
See step to reproduce

**Comment by lapagept** [comment]
I've just tried with a fresh installation of the last nightly build of Odoo 8. 
If I load a product page and the product has some variants, the first price displayed on load doesn't respect the decimal separator. A dot is displayed instead of a comma. If I select another variant, the price is well displayed with the comma.
All is ok in the cart.
All is ok on product pages for product without variant.

**Comment by lapagept** [comment]
I see that you are working on the problem. But it doesn't seem to be still solved for Odoo 8. I come back later! Thanks.
