### ISSUE TITLE
Opportunity form view turns into Lead when page is refreshed

### ISSUE THREAD

**Issue by junem-ingenuity** [odoo/odoo#11566]
Impacted versions:
9.0 community

Steps to reproduce:
1. Goto Sales Menu
2. Create a New opportunity
3. Save it
4. Hit Refresh on your browser

Current behavior:
The page will show a filled-out Lead form (with the "Convert to Opportunity" button)

Expected behavior:
The Page should show the Opportunity form view

Video/Screenshot link (optional):
http://youtu.be/sYw680a8k7k?hd=1

**Comment by nbj-microcom** [comment]
Hi @junem-ingenuity , 

we have the exact same issue as we refresh the form view of an opportunity. 
We noticed also that the item from the left menu disappear and the menu_id parameter from the URL as well ..

We are wondering if there's a solution for this issue or Odoo is working on it  @rco-odoo @nim-odoo

**Comment by Yenthe666** [comment]
Hi @mart-e could you give your input on this one?

**Comment by mart-e** [comment]
Indeed, the lead and opportunity are the same objects so only the menu you clicked is the way we know which view should be displayed.
When you refresh a page, we lose all the history and context so we try our best and display the first view we find.

So Odoo is not really "refresh-proof" (I find no valid reason to refresh the page anyway). Maybe @ged-odoo has an idea of improvement for that but I will tag it as wishlist.

**Comment by ged-odoo** [comment]
The problem is an old one: the state of the application is not serialized in the url, so it cannot be deserialized with only the url as information.  Serializing the state in the url is not really doable, since the state contains all the filter in the search views, all the actions, possibly many, with their context.

Another solution is to use the local storage to serialize the state, but then the url can be used to reload the application only in the same browser/computer, which is not so intuitive.

I also thought that we could have a simple url shortener, and save the state server side, but this is maybe too much.  If we find enough business value to do it, this could be done.
