### ISSUE TITLE
Shipping method, wrong price charged in some cases 

### ISSUE THREAD

**Issue by xavier-bouquiaux** [odoo/odoo#116175]
Impacted versions: 14.0

Behavior introduced by this commit 
https://github.com/odoo/odoo/commit/5849e428f4f6850ee8e8a451663f42815f12483d

Steps to reproduce:

1/ Create tax "A" (price included=True) <br/>
![image](https://user-images.githubusercontent.com/79840636/226880572-6496c622-7ee9-430c-ae06-040e25362155.png)

2/  Create tax B (price included=True) with a percentage <> from  A
![image](https://user-images.githubusercontent.com/79840636/226880674-dd1a5372-085a-4127-823a-121d0d0c1b97.png)

3/ Create a Fiscal Postion to go from A to B 
![image](https://user-images.githubusercontent.com/79840636/226880783-d684552b-7932-4294-8a8f-579e1aa76709.png)

4/ Create a shipping method 
![image](https://user-images.githubusercontent.com/79840636/226880857-0afcd165-f44d-4ef7-a1f7-49c2bf4a85fd.png)

5/ On the article linked to 4/, add tax "A" as customer tax
![image](https://user-images.githubusercontent.com/79840636/226881012-79059821-b21a-4b95-8c8d-96a92be186e3.png)

6/ Create a SO with fiscal position created on 3/
![image](https://user-images.githubusercontent.com/79840636/226881132-5b815787-295b-478c-a543-889fda6bcc62.png)

7/ Add the shipping method created on 4/
![image](https://user-images.githubusercontent.com/79840636/226881250-2d52a85b-54fd-491a-9f83-ffe2ad0b638e.png)

Current behavior:

The price for the shipping method is not the price declared on the shipping method <br/>
taxes are included
![image](https://user-images.githubusercontent.com/79840636/226881448-36d30e7a-696d-42d7-90e7-f8270345dc10.png)

Expected behavior:
The price declared on the shipping method should be applied

Odoo issue : 
opw-3244338

**Comment by HANNICHE-Walid** [comment]
hello @xavier-bouquiaux 
after consulting with the accounting team it was concluded that this behaviour is actually the intended one

here we have a product with a unit price of 100 (10% tax included) meaning that the base amount is 90.91

when the tax changes to 20% tax included with a fiscal position there's two possible options keep the same unit price but modify the base amount or keep the base amount and modify the unit price

we have opted for the second approach the base amount stays constant and the unit price changes for each client depending on their fiscal position.

in this case the new unit price is 90.91 * 1.2 = 109.09

**Comment by Cedric-Pigeon** [comment]
Sorry but I do not agree. 

We are on an e-commerce environment, the price displayed is taxes included.
In EU, depending on the delivery country, you may have to apply the VAT of the destination country (https://europa.eu/youreurope/business/taxation/vat/cross-border-vat/index_en.htm#withintheeusellgoodsfinalconsumer-1).
So if you sell a product 100 taxes included, wherever the customer lives he will pay 100 but for the seller the VAT applied may change.
Since your change, this is not possible anymore.

**Comment by legalsylvain** [comment]
Hi @Cedric-Pigeon. 
IMO, Both implementations are valid.

-Your use case is totally valid, IF you want the customer pay always the same price (Vat included). (but, well, in that case, the margin of your sale changes, depending on your customer).  ("computation A")
-The Odoo use case is totally valid, IF you want to sale with always the same margin. (VAT excluded). (But, well, in that case, the total paid by the customer changes...) ("computation B")

IMO The good implementation is to add an option on the fiscal.position, to allow to selection the computation. Something like 

```
use_total_amount = fields.Selection(
    selection=[("total_vat_excl", "Total Vat Excluded"), ("total_vat_incl", "Total Vat Included")],
    required=True,
    default=total_vat_excl,    # Conservative choice,as this is odoo's new calculation mode
    help="If you select 'Total Vat Excluded', you will sell with always the same margin (but various price vat incl),"
    " If you select 'Total Vat Included', you will sell with always the same price vat incl (but various margin)"
)
```

It shoud be great if it was an odoo option @xavier-bouquiaux. What do you think ? 
Otherwise we should develop some OCA extra modules. But in my opinion, it's a pity if Odoo doesn't handle the various classic use cases.

**Note :**
In V12, it was by default in Odoo the computation A. But in my company, we wanted the computation B.
(So, from an egotistical point of view, I'm happy with this recent change !)
So, I developed a module that change computation A -> computation B for V12.
https://github.com/grap/grap-odoo-incubator/tree/12.0/account_fiscal_position_tax_included#account-fiscal-position---tax-excluded-to-included
You can use it as a base to develop a new module computation B -> computation A, if odoo doesn't want to integrate such setting in odoo code.

Interesting topic.
@xavier-bouquiaux, @Cedric-Pigeon : please ping me if you implement some code to handle both cases.

Kind regards.

**Comment by Cedric-Pigeon** [comment]
@legalsylvain Many thinks for your really accurate comment. 
Reading that, I have better understanding of both point of view.

Your suggestion seems really in my opinion. @HANNICHE-Walid As your change impact the behavior of a stable version, would you be ok with the suggested implementation ?

**Comment by legalsylvain** [comment]
@Cedric-Pigeon : thanks to you !
Until today, I thought that my ``account_fiscal_position_tax_included`` module was fixing an odoo "bug", but thanks to your explanation, I understand that the old Odoo calculation mode was useful for some people ;-)

**Comment by HANNICHE-Walid** [comment]
@Cedric-Pigeon I agree that adding the option to select between the two behaviors would actually be better but this implementation will not be accepted on a stable release I will try to push it to master for future releases

**Comment by legalsylvain** [comment]
> but this implementation will not be accepted on a stable release I will try to push it to master for future releases

Hi @HANNICHE-Walid thanks for your answer. If we set the new option with the default value that make the same computation as 14.0, it could be acceptable in stable, dont you think ?

**Comment by HANNICHE-Walid** [comment]
hi @agr-odoo if we add that parameter (keep base/unit price) as a setting instead of a field on the db would it be acceptable?
