### ISSUE TITLE
[16.0] Currency symbol on Untaxed Amount~Total of Invoice is not displayed correctly after clicks previous & next button

### ISSUE THREAD

**Issue by rinaldifirdaus** [odoo/odoo#116143]
OPW No: #3244079
Impacted versions:　Odoo 16.0

Steps to reproduce:
Set multi-currency in the database.
1. Go to Accounting-> Vendor->Bills or Customer->Invoice -> create a new invoice.
2. Set Journal in other currency, not company's currency. (e.g. company currency: USD, other currency: EUR)
3. Add product and set the price, then confirm the invoice. (the untaxed amount, tax, and total will be displayed in EUR symbol)
4. back to list view and re-open the invoice. on upper-right of the invoice will displays 1/XX (records), for example 1/11
5. click previous arrow (<) to go to record 11/11. (the untaxed amount, tax, and total will be displayed in incorrect symbol)
6. click next arrow (>) to go back to record 1/11.
7. the untaxed amount, tax, and total will be displayed in USD symbol 
8. click refresh will change back the symbol to EUR
9. repeat step 4~7, then click next arrow on 1/11 to open record 2/11
10. record 2/11 will also displayed with incorrect currency symbol

Current behavior:
in multi-currency, Currency symbol in invoice is changed after go to the last record from the first record. it's not displayed with correct symbol.

Expected behavior:
opening another record should not changes the currency symbol.

Video/Screenshot link (optional):
https://drive.google.com/file/d/18ntIq_gBSqPSPA6WYD_b8VLP3gJ5hUgU/view?usp=share_link

@qrtl

**Comment by AbdelAzizMohamedMousa** [comment]
To resolve the issue where the currency symbol on the untaxed amount and total of an invoice is not displayed correctly after clicking the previous and next buttons, you can follow these steps:

Go to the Accounting module and select either Vendor Bills or Customer Invoices.
Create a new invoice and set the journal in a currency other than the company's currency.
Add a product and set the price, then confirm the invoice. The untaxed amount, tax, and total will be displayed in the other currency's symbol.
Go back to the list view and reopen the invoice. On the upper-right corner of the invoice, it will display 1/XX (records).
Click the previous arrow (<) to go to the last record. The untaxed amount, tax, and total will be displayed in the incorrect currency symbol.
Click the next arrow (>) to go back to the first record. The untaxed amount, tax, and total will be displayed in the company's currency symbol.
Clicking refresh will change the symbol back to the other currency's symbol.
Repeat steps 5-7, but instead of clicking the next arrow to go back to the first record, click on the record number you want to open.
The untaxed amount, tax, and total should be displayed in the correct currency symbol for the record you opened.
To fix this issue, you can modify the Odoo code as follows:

Go to the Odoo code and find the function that loads the records for the list view of invoices.
Add a line of code that sets the currency symbol to the correct one for each record in the list view.
Save and restart the Odoo server.
This should fix the issue and ensure that the currency symbol is displayed correctly for each record in the list view of invoices, regardless of the record number or whether you click the previous or next buttons.
