### ISSUE TITLE
[9.0] One2Many and Many2Many properties

### ISSUE THREAD

**Issue by yucer** [odoo/odoo#11647]
Impacted versions: 8.0, 9.0

Steps to reproduce:

 Specify company_dependent=True on One2Many or Many2Many fields

Current behavior: 

The related values are not company dependent

Expected behavior: 

One of this options:
1. Create the needed schema changes and restrict the domain for the related entity.
2. Raise an exception during the update like: "company_dependent attribute not supported for One2Many and Many2Many fields" and update the ORM reference including the same hint. 

Reference:

https://www.odoo.com/forum/help-1/question/one2many-and-many2many-properties-100362

**Comment by yucer** [comment]
Just to note. I did specify:

> Impacted Versions: 8.0 and 9.0

Because those were the one who I tested. 

Do this 9.0 tag means that this problem is solved for 10.0+ ?

Or did you took what the issue description says ?

**Comment by Yenthe666** [comment]
Hi @yucer,

As the Odoo V8 is no longer supported I've tagged it 9.0 and added this label. If Odoo agrees on this and changes this it will be handled in V9 and forward ported to version 10 and 11 too.

Regards,
Yenthe

**Comment by Yenthe666** [comment]
Hi @yucer,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 9 is no longer supported as Odoo only supports three versions (10.0, 11.0, 12.0 at the moment).
If you can still reproduce this issue on Odoo 10, Odoo 11 or Odoo 12 we encourage you to create a new bug report.

Regards,
Yenthe

**Comment by yucer** [comment]
Hi @Yenthe666,

I appreciate your wait to communicate it. I can understand why this kind of old issues need to be closed.

But I still think that issues should not be closed that way, just trusting in the interest of the reporter to solve the issue.

What happen is the one who reported the issue is not active anymore? Or maybe it is not working anymore with **Odoo** ? Or he doesn't have the time to test this ?  

I invest time to report this kind of stuff, and not always because I need the fixes, just because I wanted to Odoo to improve and might be prevent another issues that might affect us later. Maybe another person has the time / resources to look for it.

I have the will to do it, but usually I have pressure from another projects, etc...

How can I find it later ? Or better... how can you find all those "expired" issues ?

Suppose that the project reach a point where the latest versions have no open issues in **github**. Can't you grantee that is free of problems ? Maybe those issues doesn't represent a problem, but something you would like to improve in the future.

Do you know a way to identify this kind among all of the issues later ? Maybe a label for them can be useful ?

My apologizes, the next time I report an issue I'll try to use a PR with a unit test that reproduce the problem for it, if I can not quickly find a solution.

**Comment by Yenthe666** [comment]
Hi @yucer,

Again, I'm sorry that I have to close them off. I honestly don't like closing issues without a solution or thorough insight either. However, when the Odoo version is no longer supported by Odoo S.A. there is not much we can do. Fixes against V8 or V9 are no longer accepted which means that there is no good reason to look at it anymore from the Odoo S.A. perspective.
Exactly for that reason I ask people to make a new bug report (or just respond back) if they can reproduce it in newer versions that are still supported. I know making those reports take time, in fact I have dozens of them myself. Some get closed off because of the same reason that this one got closed.

As for finding your own issues again, you can quickly filter them by name. For example for your name you can find all closed issues at https://github.com/odoo/odoo/issues?q=is%3Aissue+author%3Ayucer+is%3Aclosed
Any issue that is a wishlist item or something that can affect newer versions will stay open if there is an interest from Odoo S.A., even though it was reported years ago.

I hope this answers your questions a bit and that you understand.

Regards,
Yenthe

**Comment by yucer** [comment]
Hi @Yenthe666,

I am not again closing them. Just not being able to identify them among all the closed issues.

I suppose you have more solved issues than I do. Can you quickly find your dozens among all the ticket you did solve ?

It is not better to have a label for them ?

Regards

**Comment by Yenthe666** [comment]
Hi @yucer,

I've got over 110 issues myself and seem to find them quite easy. It is just a question of labeling & searching on a term where you know it is in the issue in my opinion. 😄 If I'd label all the closed off ones how should I label them? "Unanswered"? "Unsolved"? I wouldn't know if they where solved or not so thats a point.

Regards,
Yenthe
