### ISSUE TITLE
[16.0] Could not filter Analytic Distribution by Analytic Account's name in Journal Items and other menus

### ISSUE THREAD

**Issue by rinaldifirdaus** [odoo/odoo#116554]
Impacted versions: Odoo 16.0

Steps to reproduce:
- On Accounting module > Accounting > journal items, create new filter like: "[["analytic_distribution","ilike","administrative"]] " to filter journal items which have analytic account contains "Administrative"
- Clicks "Filters" > unselect "Posted" > then select the new filter.
- Even if you have record that have analytic account which contains "Administrative", the filter result will show no result

Current behavior:
In the database, value of Analytic distribution field in journal item is not presented as the analytic account name, but its presented as json data such as  "{"1":100}", "{"2":100}", etc. so the users could not filter the analytic account with the account name. especially if we add the the analytic distribution in "Add Custom Filter".
*It is not only in journal item, its also happens in vendor bills, invoice, purchase order,etc.

Expected behavior:
value of Analytic distribution field is presented as the analytic account name itself so the users can easily filter any record that they want.

Video/Screenshot link (optional):
https://drive.google.com/file/d/1P4rjxzyOG5llevztaSH71MUe0aqZuOpv/view?usp=sharing

Support ticket number submitted via odoo.com/help (optional):

<img width="488" alt="analytic_distribution value" src="https://user-images.githubusercontent.com/122415281/227534469-987c2ada-0546-41d0-8d10-f8b7d3bfc888.png">
<img width="784" alt="filter" src="https://user-images.githubusercontent.com/122415281/227534481-20bfc042-ae73-40b8-a68d-30c69c5fb752.png">

@qrtl

**Comment by niyasraphy** [comment]
seems a pr is getting ready:  https://github.com/odoo/odoo/pull/116496

**Comment by AbdelAzizMohamedMousa** [comment]
Based on the steps to reproduce and current behavior you have described, it seems that there is an issue with the way the Analytic distribution field is displayed in Odoo 16.0. Specifically, the field is presented as JSON data rather than the actual name of the analytic account, which makes it difficult for users to filter records based on the account name.

The expected behavior, as you have stated, is for the Analytic distribution field to be presented as the actual name of the analytic account, which would make it easier for users to filter records based on the account name.

To resolve this issue, it may be necessary to modify the code in Odoo 16.0 to ensure that the Analytic distribution field is displayed in the expected manner. This would likely require the assistance of a developer with experience working with Odoo.

In the meantime, you could consider using a workaround to filter records based on the analytic account name. For example, you could export the relevant records to a spreadsheet and then use the spreadsheet's filtering functionality to filter based on the account name.

**Comment by niyasraphy** [comment]
hi @rinaldifirdaus ,
the functionality has been added by this commit: https://github.com/odoo/odoo/commit/bc5b72937a1c79688f7f6dc1c8aeaa7eb4cb6744

feel free to close the ticket.
thanks
