### ISSUE TITLE
[9.0C & 9.0E] sale_stock.py using self in @api.model

### ISSUE THREAD

**Issue by phyziqx** [odoo/odoo#11664]
Impacted versions: 9.0
sale_stock/sale_stock.py
at line 270

Current behavior:

``` python
@api.model
def _run_move_create(self, procurement)
    vals = super(ProcurementOrder, self)._run_move_create(procurement)
    if self.sale_line_id:  # self is not defined and this will always return false
        vals.update({'sequence': self.sale_line_id.sequence})  # self not defined
    return vals
```

This will not assign sequences to stock moves based on SO line's sequences as self is not defined in @api.model

Suggested Fix:

``` python
@api.model
def _run_move_create(self, procurement)
    vals = super(ProcurementOrder, self)._run_move_create(procurement)
    if procurement.sale_line_id:  # The initial procurement should have sale_line_id defined
        vals.update({'sequence': procurement.sale_line_id.sequence})  # procurement is defined
    return vals
```

I came across this while writing a module to link propagated procurements and moves back to the sale order line, in an attempt to try to automate a return process or an order quantity decrease.

**Comment by Yenthe666** [comment]
Hi @phyziqx,

Thanks a lot for your bug report.
This issue has been fixed in the meanwhile, as you can see here:
https://github.com/odoo/odoo/blob/11c73cd0aa2ff9cbfde8e5eebf3f22dfa1c805f1/addons/sale_stock/sale_stock.py#L270-L275

Please update your code to the latest version in order to fix this.

Regards,
Yenthe
