### ISSUE TITLE
[POS] configuration of receipt (missing field UID, unneeded field stock)

### ISSUE THREAD

**Issue by grexe** [odoo/odoo#11733]
using Odoo 9.0 nightly and POSbox in a box-less setup on Debian 8.3, I miss a way to configure the order receipt (printout), which is quite an important feature imo since that is what the customer sees.

Esp. I'd like to remove the (for me) useless "stock" name (this is more of internal relevance but nothing the customer should care about).
Instead, I am legally required to show the UID (ATU in Austria, the company's tax number), which is not printed.

So in addition to a custom header and footer text, I'd need to configure what fields of the company info should be printed.
The POS module should provide an option to hide or show all information stored in the company info (as entered in the main Odoo configuration), and ideally a simple layout where to put that information (a list would suffice at first).

Is there a way to edit the order receipt template in the XML configuration of Odoo somewhere or can I only hack this for now? (as a workaround, I configured the header text to show the UID, but could not get rid of the "stock" text)

**Comment by wtaferner** [comment]
@grexe 
It is a combination of what you display via https://github.com/odoo/odoo/blob/9.0/addons/point_of_sale/static/src/xml/pos.xml#L666 and what you provide via Javascript (https://github.com/odoo/odoo/tree/9.0/addons/point_of_sale/static/src/js).

In case you do not have a PosBox (which is straight-forward for the officially supported hardware which is still very little + Raspberry Pi + provided image) you need to use your local hardware which is primarily optimized for receipt printing and barcode scanning (input). 

So, you have two options...to hope and wait that your requirements and wishes will become true or to customize the PoS as you need it without loosing a healthy dependency to the core...use inheritance as often you can and try to anticipate how your customization and the core won't hurt each other in the future ;-)

**Comment by jorenvo** [comment]
> Is there a way to edit the order receipt template in the XML configuration of Odoo somewhere or can I only hack this for now? (as a workaround, I configured the header text to show the UID, but could not get rid of the "stock" text)

As wtaferner was saying, there is not, since it is a JS QWeb template. The only way to do it is through a custom module (or hacking the code itself I guess). In this case you don't need a full module, you can also use a small data-only module [1]. But if you're using an on-premise installation a full module is probably easier to maintain.

I'm thinking of removing the stock location name from the receipt in master, because I agree that in most cases it is not needed and if it is it should be added in a customization. Right now it's opposite (people who don't want have to remove it in a customization).

[1] https://github.com/odoo/odoo/blob/9.0/addons/base_import_module/__openerp__.py

**Comment by shadab7368** [comment]
where is the  path of pos.xml in odoo18
