### ISSUE TITLE
Login prompt error -ValueError: Template 'BurgerUserMenu' already exists in module 'web'

### ISSUE THREAD

**Issue by hermitguo** [odoo/odoo#117430]
Impacted versions:
20230401
Steps to reproduce:
win11+python3.10+CE20230401
Current behavior:
Create a new database, select the database, and enter the user name and password. An error occurs.
Expected behavior:

odoo\addons\base\models\ir_qweb.py", line 580, in _render
    result = ''.join(rendering)
  File "<190>", line 329, in template_190
odoo.addons.base.models.ir_qweb.QWebException: Error while render the template
**ValueError: Template 'BurgerUserMenu' already exists in module 'web'**
Template: web.webclient_bootstrap
Path: /t/t/t[1]/t[4]
Node: <t t-call-assets="web.assets_backend" t-css="false"/>
2023-04-01 07:48:40,976 19552 INFO odoo16 werkzeug: 127.0.0.1 - - [01/Apr/2023 07:48:40] "GET /web HTTP/1.1" 500 - 78 0.068 8.474
2023-04-01 07:48:56,125 19552 INFO odoo16 odoo.addons.base.models.ir_cron: Starting job `Base: Auto-vacuum internal data`.

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by AbdelAzizMohamedMousa** [comment]
Based on the information provided, it seems like you are experiencing an error while rendering a template in Odoo's web module. The error message suggests that the template 'BurgerUserMenu' already exists in module 'web', which is causing a conflict.

One possible solution to this issue is to remove the 'BurgerUserMenu' template from the web module. To do this, you can try the following steps:

Log in to your Odoo instance as an administrator.
Go to the 'Settings' menu and select 'Technical -> User Interface -> Views'.
Search for the 'BurgerUserMenu' template in the search bar and select it.
Click on the 'Delete' button to remove the template from the web module.
Save the changes and restart the Odoo server.
After completing these steps, try accessing the web module again and see if the issue has been resolved.

Make sure you have the latest version of Odoo and Python installed on your system.
Check if there are any conflicts or duplicates in your modules or templates. You can use the odoo-bin scaffold command to create a new module and compare it with the existing ones.
Clear your browser cache and cookies, and restart your Odoo server.
If none of these steps work, you can contact the Odoo support team or visit their forum for more assistance.
Sure, I can show you how to use the odoo-bin scaffold command. This command allows you to create a basic module structure with some initial files. You can use it as follows:

Navigate to the directory where you have the odoo-bin file. This is usually in the server folder of your Odoo installation.
Run the command ./odoo-bin scaffold module_name folder_name, where module_name is the name of your module and folder_name is the name of the directory where you want to create the module. For example, ./odoo-bin scaffold my_module addons.
This will create a new folder with your module name inside the specified directory, and generate some files such as __init__.py, __manifest__.py, models.py, views.xml, etc.
You can then edit these files to customize your module according to your needs.

If the issue persists, you may need to investigate further and try other solutions such as updating the web module or checking for any conflicting modules or add-ons.

**Comment by naxiangzi** [comment]
Thank you for your answer, this is an official error, I have solved, use the old version, it is OK, because my cannot use the account and password to log in, so my can not use your method to solve, change to the old version is OK.

**Comment by eremiter** [comment]
Thank you for your answer, this is an official error, I have solved, use the old version, it is OK, because my cannot use the account and password to log in, so my can not use your method to solve, change to the old version is OK.

**Comment by mart-e** [comment]
@AbdelAzizMohamedMousa again, this is inaccurate, as he can not loggin, he can not go to the settings to remove the view.

@hermitguo check your installation logs, it is probably failing at some point (before login in). Maybe you are reusing an existing database?

**Comment by vava-odoo** [comment]
Hi @hermitguo 
Please re-open this if the issue is still there and you can provide more information.
Regards
