### ISSUE TITLE
change jquery version while developing custom theme in “odoo 8.0”

### ISSUE THREAD

**Issue by rosnk** [odoo/odoo#11834]
Impacted versions: odoo 8.0

Steps to reproduce: Use basic version of "owl carousel 2.0" inside custom theme. 

Current behavior: "owl carousel 2.0" works in "firefox" but does not work in "chrome". Using Jquery version "1.11.3" outside odoo works as expected but not while integrating inside "odoo 8.0". 

Expected behavior: carousel should work in both chrome and firefox.

Full detail of the problem : 
i am trying to use "owl carousel 2.0", inside "odoo 8.0" which is working fine in firefox but results in error when opened in "chrome".

It seems like the problem has to do with jquery version which ships with "odoo 8.0" installer.

**How do i switch the default jquery version of odoo into version jquery version "1.11.3"**

Error message: clicking "next" and "prev" button results in:

**_Uncaught TypeError: elem[type] is not a function. _**

**Comment by sle-odoo** [comment]
Upgrading jQuery in version 8 is not straightforward: if you want to upgrade it globally, you also have to upgrade some other libraries for the web client. I don't remember if it's safe or not to upgrade it only on the website. You should apply [this patch](01409c1d7b0050942ba5e53ff4f3bb927fd3eb51) in both case.

Anyway that's not something we are going to do on an stable release, due to all the side-effects that could arise. Your best best is to upgrade it on you environment, and i suggest only fix it on the website!
