### ISSUE TITLE
[9.0] Date problems with localization (NO)

### ISSUE THREAD

**Issue by bringsvor** [odoo/odoo#11854]
Impacted versions: 9.0

Steps to reproduce: Change to Norwegian language. go to accounting, reports. Select for example the balance report. Select custom period -> last fiscal year. See enclosed screenshot. Actually this happens other places too, If you create a sales order and fill inn the expiration date using the date chooser to, say, December last year then try to save it you get an error. See second screenshot.

Current behavior:
Gives exception that it is not a valid date.

Expected behavior:
To be able to parse dates chosen, regardless of locale.

Video/Screenshot link (optional):
  
![image](https://cloud.githubusercontent.com/assets/7498104/14882429/216e1956-0d39-11e6-8718-719695c92b1c.png)

![image](https://cloud.githubusercontent.com/assets/7498104/14882538/95088612-0d39-11e6-8c85-0c091b90dbc9.png)

**Comment by beledouxdenis** [comment]
Dear,

The issue comes the external library `moment.js` that we use.

This is a bug in the current release we use in Odoo 9.0, the release 2.8.1, which is solved in the release 2.13.0.

Here is a simple test on `fiddle.js` with the release 2.13.0 of `moment.js`.
https://jsfiddle.net/ezx2p9he/6/
![working](https://cloud.githubusercontent.com/assets/5822488/16588015/901aee3c-42cd-11e6-8d2e-ba50e704de91.png)

This is a basic test formatting the date in the format DD MMM YYYY in Norwegian, and then ask the date back in the original format. You can see in the browser console that everything is right.

Then, here is the same test with the release 2.12.0, which fails with an "Invalid date" error, in the console.
https://jsfiddle.net/ezx2p9he/7/
![notworking](https://cloud.githubusercontent.com/assets/5822488/16588021/95edad7c-42cd-11e6-8d96-60cbc9160413.png)

You can see in the browser console "Invalid date"

The thing is, we simply can't update the library to the newest release in the stable release Odoo 9.0, as the API of `moment.js` can have changed for some of its methods, therefore potentially breaking things that currently work in Odoo 9.0, or in custom / community modules of Odoo.

I am therefore searching for the exact revision of `moment.js` that solved this issue, and I will try to apply it in Odoo 9.0. I will keep you posted.

**Comment by beledouxdenis** [comment]
I just found the revision that solve this issue in `moment.js`
moment/moment@41fdb58572546740c3a840ebd36fbe9e1bcdc9cb

Given the length of the patch, we won't be able to patch it locally in Odoo, unfortunately.

The actual issue is simply the `.` at the end of the month abbreviated name (`des.`). The parsing expects `des` without the dot. The Norwegian is not the language having the issue: It also happens in French, Spanish, and so on. It doesn't happen in English, because there is not dot at the end of the abbreviated month (e.g. `dec`).

Therefore, we believe our best hope is to give up the strict mode, the `true` parameters passed here:
https://github.com/odoo/odoo/blob/9.0/addons/web/static/src/js/framework/formats.js#L168

Which will allow the difference of this one dot at the end of the abbreviation.

To avoid any regression, we will put two pass: One with the strict mode, and if it fails, one without.  This should solve your case without breaking the working ones at the moment.
