### ISSUE TITLE
[BUG][16.0] Odoo auto install unwanted application when install account module

### ISSUE THREAD

**Issue by sadeem-cloud** [odoo/odoo#118689]
Impacted versions: 16.0 Community

Steps to reproduce: Install account module on empty database

Current behavior: Install another application (project, hr)

Expected behavior: only install account and its dependency

Video/Screenshot link (optional): https://youtu.be/6wlJgZW30DM

**Comment by niyasraphy** [comment]
hi @sadeem-cloud ,
this is due to the newly introduced default_productivity_apps parameter, you may be using not updated source code of odoo 16.

Initially the default value for **default_productivity_apps** is set as True and then later is it reverted to False by following commit: https://github.com/odoo/odoo/commit/4fadf6b99a7b48a58a612e3d0be3d14a99a60ef5

so either you can update your odoo source code to its latest or in your odoo configuration file add below line

**default_productivity_apps=False** , which will solve the case.

when the default_productivity_apps=True is set, the following apps will get installed in the db:  

'hr', 'mass_mailing', 'project', 'survey',  'appointment', 'knowledge', 'planning', 'sign',

if this resolve your issue, feel free to close the ticket.
thanks

**Comment by sadeem-cloud** [comment]
Thnx for quick response 
i have download latest version today and the same i think there is problem in  deb package because this option is set to True by default
i will turn it off and check
