### ISSUE TITLE
RuntimeError: object unbound 

### ISSUE THREAD

**Issue by MrTob** [odoo/odoo#118902]
I want to test my odoo controller in a testing class.
First i have following class
```python
from odoo import http, tools
from odoo.http import Response

class MyClass(http.Controller):
 
    def my_calc(self, data):
        return data

    def do_something(self, data):
        param1= self.parse_ip_network(
            http.request.env['ir.config_parameter'].sudo().get_param('my.param1'))
        return param <= my_calc(self,data)
```
now i want to write tests for this class
```python
from odoo.tests import HttpCase, HOST, common

class TestMyClass(HttpCase):
    def test_do_something(self):
        test= my_module.MyClass()
        result =my_module.MyClass.do_something(test, 'data')
        # assert ....
```
this produce a RuntimeError("object unbound")
why?
how can i test this right?

Impacted versions: odoo 16

**Comment by chinmayroy** [comment]
The error message "RuntimeError: object unbound" is being raised because you're calling the do_something method of MyClass as a static method rather than as an instance method. In other words, you're calling the method on the class object itself, rather than on an instance of the class.

To fix this, you need to create an instance of MyClass and call the do_something method on that instance. Here's an example:

```
from odoo.tests import HttpCase
from my_module import MyClass

class TestMyClass(HttpCase):
    def test_do_something(self):
        my_class = MyClass()
        result = my_class.do_something('data')
        # assert ...
```

In this example, I create an instance of MyClass called my_class, and then call the do_something method on that instance. This should fix the "object unbound" error.

Additionally, you might want to consider using the unit test module in Python to write your tests, as it provides a more robust and flexible testing framework than the built-in HttpCase class in Odoo.

I hope this helps! Let me know if you have any further questions.

**Comment by MrTob** [comment]
i adapt the code, but still the samre error message, wehn i use a debugger, i cant inspect the created instance from the class, but when i want to call a method i got RuntimeError: object unbound
```python
from odoo.tests import HttpCase, HOST, common

class TestMyClass(HttpCase):
    def test_do_something(self):
        my_class = my_module.MyClass()
        result = my_class.do_something('data')
        self.assertTrue(result)
```

**Comment by vava-odoo** [comment]
Hello @MrTob and @chinmayroy,

Thank you for your report but please keep github only for bugs reporting on the standard Odoo. Not for questions or development help.

For help, you may try the [mailing lists](https://www.odoo.com/page/odoo-community), the [forum](https://www.odoo.com/forum/help-1) or the [support page](https://www.odoo.com/help) (for paying users).

Regards
