### ISSUE TITLE
Ooo does not hide website without permission

### ISSUE THREAD

**Issue by AnhDai1997** [odoo/odoo#119007]
Impacted versions: 
16
Steps to reproduce:
1. Create website 1 belong to company 1, Create website 2 belong to company 2,
2. Create user ABC have roles:
- Allowed Companies: 1
- Default Company: 1
- Website: Editor and Designer
- Employees: none
- Recruitment: none
3. Log in as ABC
4. Go to website

Current behavior:
Website dropout list contains: website 1, website 2
Expected behavior:
Website dropout list contains: website 1

**Comment by vava-odoo** [comment]
@rdeodoo I think the issue here is that the dropdown menu _does_ show website 2 and should not.

**Comment by rdeodoo** [comment]
Oh, yeah, I read that too quickly.

But is it really important to hide it? `website` is not protected by the multi company rules because it's something any visitor / public user can see and access. We could prevent the user to see other websites in this dropdown indeed, but nothing would prevent them to simply go to the other website manually since a website is never private (unless you don't yet have a domain / have a wip website, which should be very temporary).

Also, know that the groups are linked to "a user", not "a user on a company", meaning that when you give edition group to a user, he has rights to edit other websites too, regardless of the company.

But for such cases of multi website multi company where your employees should only have access to a website/company and not the other one, I would probably go with unchecking "Shared User Accounts" so the user really has access to one website, his account can not be used on the other website.
Remember that switching website from the switcher **will** change domain[1], meaning new session, need to login again.

At the end, the website switcher is showing you what you really have access to, even if we were to hide it, you would still have access to it through other means.

[1] Unless you have a WIP website waiting for a domain.

----------

Here is something I wrote to a client opw about the same "issue" but with WIP (no domain) websites, but it is kind of the same here:

> Using the website switcher with a WIP website which if not properly configured with a non admin user is just a door to a lot of weird behaviors.
> 
> I can have a deeper look if you really want to, but AFAIC, the user should just configure his website correctly and everything should be fine.
> By correctly, I mean set a domain on both websites.
> That will already prevent the possibility to see both website from the same domain which is just a nice to have as an admin to quickly see stuff while his domain are not configured yet.
> 
> Also, if the user really want to manage his editor users differently on his website, he has to enable the option for specific users by website (disable actually, see screenshot). Otherwise that doesn't make sense, the right to edit a website is something done at the user level not at the website level.
> 
> The website switcher is as I said, a nice to have - minimalist helper to quickly access a WIP website for which you don't have a domain yet and already want to have a preview of it / start designing some page.
> 
> But in a multi-website multi-company with restricted users with unset domain and shares users, there is no way this works as expected.
> 
>  ![image](https://github.com/odoo/odoo/assets/30048408/d068780a-812b-4201-bbcf-6c1ec11549d1)
