### ISSUE TITLE
[16] Columns not in order, views issue (in tutorial)

### ISSUE THREAD

**Issue by Gal-Noy** [odoo/odoo#119180]
Impacted versions: 16

Steps to reproduce: 

Current behavior: columns are not in right order, first column is the fill bars of the last one. In addition, I can't see the fill bars like in the odoo tutorial.

Expected behavior: as shown here: https://www.odoo.com/documentation/16.0/developer/tutorials/getting_started/06_firstui.html#tutorials-getting-started-06-firstui

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/109943831/233348326-63c697d3-77be-4d13-a6a1-f6ea988ec18a.png)

Support ticket number submitted via odoo.com/help (optional):

Thanks in advance.

**Comment by niyasraphy** [comment]
hi @Gal-Noy ,
you may not have defined a form view for your model, as of now it shows odoo generated form view that's why it looks like this.
see: https://youtu.be/IeJFxmCG2Qs?list=PLqRRLx0cl0hpu9zH6o8gq6ORBoW5xMtA-&t=2825

for such issue in development, use the help forums: https://www.odoo.com/forum/help-1
thanks

**Comment by Gal-Noy** [comment]
> hi @Gal-Noy , you may not have defined a form view for your model, as of now it shows odoo generated form view that's why it looks like this. see: https://youtu.be/IeJFxmCG2Qs?list=PLqRRLx0cl0hpu9zH6o8gq6ORBoW5xMtA-&t=2825
> 
> for such issue in development, use the help forums: https://www.odoo.com/forum/help-1 thanks

My apologies, noted. Thanks!
