### ISSUE TITLE
Point of Sale Order Time is Incorrect

### ISSUE THREAD

**Issue by PhatPixel** [odoo/odoo#11933]
Impacted versions: 9.0, 9.0c

Steps to reproduce: Process an order in POS, wait a number of minutes then process another order.

Current behavior: Order Time of second order reflects the time shown on the tab at the top of the POS screen -- however this actually reflects the time that the previous order was completed.  The Order Time recorded in the database differs from the time printed on the receipt.

Expected behavior: The Order Time recorded in the database should match the receipt, which should also match the time at which the order was Validated.

Video/Screenshot link (optional):

**Comment by jorenvo** [comment]
Hi,

The time on the order tab reflects the time at which the order is created in the front-end (eg. when a user clicks on the +). I believe it is purely informational and won't be sent to the backend. Normally the order time in the backend will reflect when the order is validated in the frontend (when the user clicks on the green validate button). Is this what you where referring to?


Kind regards,
Joren

**Comment by PhatPixel** [comment]
The time displayed on the tab is fine, however the time actually recorded against on order in Odoo should be the time that the sale is completed/validated (i.e. the same as on the printed receipt).  Currently it is time time that is on the tab that is recorded in the database.

It becomes extremely noticeable for stores that are not constantly processing sales orders.

**Comment by jorenvo** [comment]
In < 9 that's how it used to work. A change was made at https://github.com/odoo/odoo/commit/9f541d29bf58c3604f6c834ba25e1625c9ad1480 that causes the current behavior.

@mart-e, I don't disagree with your patch but this does cause the behavior described above, which is perhaps not ideal. I think with pos_restaurant installed it is fine, because then an order does not get created until you click on a table. But without pos_restaurant, it's difficult to keep the POS open without also having an order open (in theory you could stay on the receipt screen I suppose, but that wouldn't work before you're able to do your first order). Do you perhaps have a ticket number or reference to the exact issue this was solving? I'm thinking of making it so that default POS works as before, and POS with pos_restaurant works as it does with your patch.

**Comment by mart-e** [comment]
@jorenvo I believe it was for our friends F... in the mass debugging time. The reported bug was, as explained the commit, a wrong date on the order as they often got orders stuck in the queue due to bad configuration and manual intervention needed.

Was pushed in the same process:
bed4093 [ADD] point_of_sale: rescue sessions for orders on closed sessions
9f541d2 [FIX] point_of_sale: use order creation date
44f9e92 [FIX] point_of_sale: set pricelist in create
4801ce40 [FIX] point_of_sale: copy=False on stop_at field
0e30187 [FIX] point_of_sale: session_id field should always be set

I agree it may be an issue that the time is "too early" so maybe we could use a different parameter than the `creation_date`. Could we add one `payment_date` ?

**Comment by jorenvo** [comment]
@mart-e alright, thanks for explaining, I will take care of it.

> we should probably use a different parameter than creation_date. Maybe add one in the validate_order or finalize method?

Good idea, I'll probably do something like that.

**Comment by wtaferner** [comment]
@jorenvo 
what about adding a field receipt_date (for master probably) as for reprinting it must be always the same date/time...and as soon a receipt is created it must always be the same which is not the case and can be triggered/produced via the browser and under Murphy's law.
I guess as soon this is under control the reprinting does also have the correct date/time of the original.

**Comment by jorenvo** [comment]
@wtaferner when e9b1254a5c4ea008c13d0636fec87bc0f8d42245 makes it to master I'll try to make as much as possible use the newly created validation date.
