### ISSUE TITLE
[9.0] ldap user authentication

### ISSUE THREAD

**Issue by dipenpatel235** [odoo/odoo#11946]
Impacted versions: 9

Steps to reproduce: Open "https://github.com/odoo/odoo/blob/8.0/addons/auth_ldap/users_ldap.py"

Current behavior:
 uri = 'ldap://%s:%d' % (conf['ldap_server'],
                                conf['ldap_server_port'])

Expected behavior:
 uri = **'ldaps**://%s:%d' % (conf['ldap_server'],
                                conf['ldap_server_port'])

See suppose if user used 636 port so required ldaps
so you need to required patch in that file

Thanks

**Comment by ToBeReplaced** [comment]
While I agree it would be nice for the user to configure the scheme, you might consider setting the `ldap_tls` option if that is appropriate in your environment. ldaps is deprecated in favor of ldap + start tls.

**Comment by Korynkai** [comment]
While yes, ldaps is supposedly marked 'deprecated', it has been so for years and that is not going to change. Many systems still use this scheme and many systems (and administrators) continue to implement ldaps and strictly ldaps, some even deciding that STARTTLS is not preferable to this scheme in their own installations. Therefore, Odoo should be using a standard LDAP URI instead of forcing it 'ldap://'... Preferably the system administrator would be able to designate 'ldap://' or 'ldaps://' rather than strictly the address of the LDAP server (as most other web applications already do).

Therefore, the piece of code in question should preferably be as follows:
uri = '%s:%d' % (conf['ldap_server'],
conf['ldap_server_port'])

**Comment by Yenthe666** [comment]
@odony this might be for you actually, I believe you've handled LDAP reports before.

**Comment by nim-odoo** [comment]
As discussed in https://bugs.launchpad.net/openobject-addons/+bug/389033 , LDAPS won't be supported (since it is indeed deprecated).

**Comment by khorben** [comment]
Maybe it is deprecated, but `STARTTLS` may actually be dangerous. See https://nostarttls.secvuln.info in the context of e-mail for instance, some of which could be relevant to implementations of LDAPS as well.
