### ISSUE TITLE
Product tax are not compatible with multi company 

### ISSUE THREAD

**Issue by jalzaga** [odoo/odoo#11973]
The product taxes ids are not company dependant (property) as other fields such as property_account_expense or property_account_income, so that it is not possible to use the same product for several companies.
 
Impacted versions: All

Steps to reproduce:
Try to create an invoice including the same product with VAT. Try to create for Company A and Company B
Assign a TAX id to the product. It must be unique because the field is not property. Let´s choose a taxes id belonging to Company A

Current behavior:

When you invoice from company A the invoice is correct
If you try to invoice from Company B the system complains at validation time since the VAT takes a company A account for VAT.

Expected behavior:

The System should take the right taxes_id depending on the company you are working with.

Video/Screenshot link (optional):

Proposed solution: Make taxes_id and supplier_taxes_id property fields, so that they can be set according to the company.

**Comment by Yenthe666** [comment]
@qdp-odoo what do you think about this one? Would love your input.

**Comment by fpodoo** [comment]
taxes_ids are company dependant, since every tax is company dependant. It's
not a property field as it's a many2many, but the expected behaviour is the
same.

Your use case is wrong. You have to put both taxes on the product (company
A and B) and it will work for fine.
On May 9, 2016 08:21, "Jose Maria Alzaga" <notifications@github.com> wrote:

The product taxes ids are not company dependant (property) as other fields
such as property_account_expense or property_account_income, so that it is
not possible to use the same product for several companies.

Impacted versions: All

Steps to reproduce:
Try to create an invoice including the same product with VAT. Try to create
for Company A and Company B
Assign a TAX id to the product. It must be unique because the field is not
property. Let´s choose a taxes id belonging to Company A

Current behavior:

When you invoice from company A the invoice is correct
If you try to invoice from Company B the system complains at validation
time since the VAT takes a company A account for VAT.

Expected behavior:

The System should take the right taxes_id depending on the company you are
working with.

Video/Screenshot link (optional):

Proposed solution: Make taxes_id and supplier_taxes_id property fields, so
that they can be set according to the company.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub
<https://github.com/odoo/odoo/issues/11973>

**Comment by be-cloud-js** [comment]
Hi Fabian and all,

I do have the same use case and I tested your proposal and encountered an issue.

Impacted versions: Version 9.0e-20161014 (Enterprise Edition)

Steps to reproduce:
Create two companies A and B and a product that can be sold by both, eg VAT for both shall be set as explained by Fabian.

Try to create an invoice for each company including using the same product.

Current behavior:

Both invoices are using the VAT of the company configured as the default company of the user.

Expected behavior:

The System should take the right taxes_id based on the invoice company and not the user's one.

Video/Screenshot link (optional):

Proposed solution: 

It seems that when _set_taxes is called, the company_id field

company_id = fields.Many2one('res.company', string='Company',
        related='invoice_id.company_id', store=True, readonly=True, related_sudo=False)

is not initialized, in any case I put some logging and the value is null.

So

# Keep only taxes of the company
company_id = self.company_id or self.env.user.company_id
taxes = taxes.filtered(lambda r: r.company_id == company_id)

always point to the company in the user setting.

A quick fix is

# Keep only taxes of the company
company_id = self.invoice_id.company_id or self.env.user.company_id
taxes = taxes.filtered(lambda r: r.company_id == company_id)

it worked for me but it would probably be interesting to investigate the ORM to see why

self.company_id <> self.invoice_id.company_id

in this case.

Jerome Sonnet

**Comment by bizzappdev** [comment]
@fpodoo  you are completely right that adding the tax of both companies in the product itself. it will affect and get the proper Tax only when it will do onchange.
BUT, When the both tax is included in price, It will create problem,
Let's say one product A  with price 100 and Company A and B
Tax 8% for company A and 19% company B both are included in price.
Now when we will select the product in sale order, because of https://github.com/odoo/odoo/blob/10.0/addons/sale/models/sale.py#L629
it will get the proper Tax for the current company only.
But on product and uom onchange we are considering the All taxes from the taxes from the product and not considering the Company associated with that tax.
https://github.com/odoo/odoo/blob/10.0/addons/sale/models/sale.py#L906
https://github.com/odoo/odoo/blob/10.0/addons/sale/models/sale.py#L926
So IMO while calculating price also it should only consider the tax from the company of sale order.

**Comment by vcloud9ray** [comment]
Has anyone figured out how to add multiple default Sales Taxes to a product being shared between companies?

WIDGET - should have default Sales Tax of A and B.  I can't set defaults via the UI, I can't get Company Properties to work and I can't use the Accounting Settings configuration because it only supports one Tax.

**Comment by vcloud9ray** [comment]
https://www.odoo.com/apps/modules/9.0/product_tax_multicompany_default/
