### ISSUE TITLE
[15.0]Website: any menu clicking from website goes to home action

### ISSUE THREAD

**Issue by AShurikas** [odoo/odoo#119971]
Impacted versions: 15.0

Steps to reproduce:
- install 'website';
- set user Home Action;
- go to website;
- click any menu from website except menu of Home Action;

Current behavior:
Any menu click from website leads to Home Action
Expected behavior:
Clicking a menu from website should lead exactly to the action of that menu
Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by AShurikas** [comment]
The behaviour in runbot
https://user-images.githubusercontent.com/68963729/235089213-fe6c8d25-a6d7-4379-9622-c016d72ccdcc.mp4

**Comment by AShurikas** [comment]
You are indeed correct, @rdeodoo . However, the behavior I described occurs when you are already logged in and click on any menu on the website, such as "Settings." Instead of executing the intended "Settings" action, the website performs the predefined home action assigned to the current user.

**Comment by katyukha** [comment]
@rdeodoo @vava-odoo I confirm, that this issue is bug, and it hurts our client.

For example, imagine situation when you want to configure home action for your users to simplify their life: open predefined menu when they login. Then after you configured home action for that users, it works fine when they login,
But some of your users some times need to view website, and then when they want to go back from website UI to internal UI, they got stuck, because instead of viewing menu item they clicked they see the action that is configured as home action.

Just take a look at following steps and screenshots (current runbot version 15, community).

1. I login as administrator and configure Home action to *Quotations* for *Marc Demo*.
  ![image](https://github.com/odoo/odoo/assets/1129820/c7314ef2-3492-466b-b578-a371da6c888c)
2. Then i login as  *Marc Demo*, and as expected the *Quotations* menu opened.
  ![image](https://github.com/odoo/odoo/assets/1129820/1ce1cc7b-500e-4255-b484-7b0c8792983e) 
  ![image](https://github.com/odoo/odoo/assets/1129820/cc55c472-9104-48ab-81e5-d1f4ee50c1ea)
3. Then (as *Marc Demo*) i navigate to website (for example to check latest blog articles):
  ![image](https://github.com/odoo/odoo/assets/1129820/8a5d958d-7070-4639-bbeb-1458486f4d8f) 
  ![image](https://github.com/odoo/odoo/assets/1129820/e9eec12e-82fc-4cce-836e-8624fdee0141)
  ![image](https://github.com/odoo/odoo/assets/1129820/7849ed08-f5bc-445c-b4de-c3e9f68fe8ba)
4. Then (as *Marc Demo*) i try to open **CRM** to check for new leads, but instead i see **Quotations** list:
  ![image](https://github.com/odoo/odoo/assets/1129820/8f174140-c06e-4593-908c-a69168d99961)
  ![image](https://github.com/odoo/odoo/assets/1129820/e46739f6-9830-4c2a-a0c1-9f5cd9f6aee1)
5. Then (as *Marc Demo*) i become ***angry*** and start preparation **to destroy the whole world** because, for some reason, the system shows me **Quotations** instead of **CRM Pipeline** that i asked for.
  ![Death Star Attack](https://media.giphy.com/media/3K0D1Dkqh9MOmLSjzW/giphy.gif)

PS: Please, **save the world** - **fix this bug**!

Thanks a lot)

**Comment by rdeodoo** [comment]
Reopening as I don't want the world to be destroyed.
I still did not have time to travel on Road 66 from west coast to east cost.

This is certainly a bug, thank you for the in depth explanation.

**Comment by rdeodoo** [comment]
Fix for Odoo 15 and Odoo 16 will be done at https://github.com/odoo/odoo/pull/125801
The root cause is pretty simple: we don't force the `action` on those menus, meaning the Home Action will take over.

**Comment by katyukha** [comment]
Thanks a lot for a fix, it works!

Now i (as *Marc Demo*) am happy and calm, just looking at destruction of (not-finished) Death Star... It is so exciting... 

![Death Star explosion](https://media.tenor.com/0-Ymgj2Lw60AAAAd/death-star-star-wars.gif)

The world is saved now)

**Comment by rdeodoo** [comment]
> The world is saved now

You are welcome, call me anytime the world is about the be destroyed.
