### ISSUE TITLE
ImportError: No module named openerp

### ISSUE THREAD

**Issue by andytorres** [odoo/odoo#12027]
Hi, I'm deploying Odoo 8 using Apache and mod_wsgi, I followed the steps detailed [here](https://opensourceholic.com/2014/05/09/deploy-openerp-using-mod_proxy-and-mod_wsgi-on-linux-server/) and [here](https://opensourceholic.com/2014/05/30/how-to-deploy-odoo-openerp-8-with-mod_wsgi-on-ubuntu-linux-servers-vps-ec2/), but whenever I try to start the apache server, I get this error with the openerp-wsgi.py file:
`    import openerp`
`    ImportError: No module named openerp`
I even tried to launch the server running
 `gunicorn openerp.service.wsgi_server.application -c /home/andy/odoo/odoo-8.0-20150903/openerp-wsgi.py`
, but it still throws me the error.
I'd appreciate if someone points me in the right direction. Thanks in advance

**Comment by hbto** [comment]
Hello @andytorres;

That would be an interesting question for the community,

that is not to be considered an issue,

Please do not hesitate in posting this Error on community mailingList

**Comment by andytorres** [comment]
I'm following your advice, i'm already digging in the archives of the mailing list and the forum. Thanks for the suggestion

**Comment by Yenthe666** [comment]
Hi @andytorres,

Github issues are only for bugs / issues with the official code, not for custom development or configuration.
I'd suggest you to create a topic on the official Odoo help forums (help.odoo.com), there are plenty of people that can help you there!
Closing this since it isn't an issue with the Odoo code.

Regards,
Yenthe
