### ISSUE TITLE
[14.0, 15.0, 16.0] [Planning] Start date and stop date are not displayed in Gantt task and  task is not expanded on two days if stop date is on the next day

### ISSUE THREAD

**Issue by sergueikp** [odoo/odoo#120206]
Impacted versions: Enterprise 14.0, 15.0, 16.0

In Planning I see four issues:
1. If Shift Template Stop date is on 1 AM of the next day : Start date and stop date is not displayed on the shift task in the Gantt  and shift task is not extended on two days.
2. If Shift Template Stop date is on 12 AM of the next day: Start date and stop date is not displayed on the shift task in the Gantt.
3. In Gantt view, shift task is not expanded on two days: if we manually specify start and end date, for example
start date: 12/19/2023 20:00:00  stop date: 12/20/2023 02:00:00.
4. Start date and stop date is not displayed on the shift task in the Gantt view:  if we set manually stop date on the next day, for example start time: 12/19/2023 20:00:00  end time: 12/20/2023 02:00:00.

Steps to reproduce issue 1:
1. Go to Configuration > Shift templates: and create a new shift: Role Bartender, Start Hour 20:00, Duration 5 hours.
2. Go to Planning > Open shift task Bartender and select newly created Shift Template: "8 PM - 1 AM Bartender"

Steps to reproduce issue 2:
1. Open shift task Bartender
2. Select Shift Template "4 PM - 12 AM Bartender"

Steps to reproduce issues 3 and 4:
1. Open shift task bartender
4. Deselect active Shift Template.
5. Without creating a new Shift Template, enter manually new start and stop dates, for example:
start date: 12/19/2023 20:00:00  stop date: 12/20/2023 02:00:00

Current behavior:
1. Time is no longer displayed on the task in Gantt view if stop date is on the next day
2. Task extends only on one day in Gantt view if stop date is between 12 AM and 2 AM on the next day

Expected behavior:
Start date and stop date should be displayed on the shift task in Gantt view if stop date is on the next day
Shift Task should extend on two days if stop date is between 12 AM and 2 AM on the next day

Video screen recording:
[planning_gantt_bug_1.webm](https://github.com/odoo/odoo/assets/9844780/6fcb1a9b-b4a9-46c8-a3e2-a8a5bc85f2e0)

**Comment by xavierbol** [comment]
Hello @sergueikp 

Thanks for the report and sorry for the delay!

For the first issue, the time is no longer displayed when the shift is on many days. It is the standard behavior. However, because of the standard behavior that you detect when you describe the second issue, we should indeed still display the time on the pill for that special case.

In fact, in your case (for the point 2), the gantt view only displays the pill in one day because it truncate if the stop date is between 12 AM and 2 AM. I think it is to facilitate the readability and/or the rendering.

I will do a fix (in 15 and 16) to display the time for that special case.
