### ISSUE TITLE
[15.0] Portal payment link is not open properly

### ISSUE THREAD

**Issue by konsultoo-adarsh** [odoo/odoo#120379]
Impacted versions: 15.0

Steps to reproduce: Generate payment portal link

Current behavior: when we open a link then the link is not working 

Expected behavior: we have to open the payment page

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/80751186/235840864-9aebdd8b-9b73-415c-8777-e003ad27f07a.png)

Support ticket number submitted via odoo.com/help (optional):

The issue is coming up after the latest change made 2 days ago.
Solution:
 Need to Pass the **partner_invoice_id** on the check access token.

**Comment by vava-odoo** [comment]
Hi @konsultoo-adarsh 
I was not able to reproduce the error on the last [runbot](http://runbot.odoo.com/runbot) (blue door icon of the version row (15) with login/pwd as admin/admin).
I created an invoice, generate a link and open it in a new Incognito window: works fine.
Could you provide the steps to reproduce?
Regards,

**Comment by konsultoo-adarsh** [comment]
Hello @vava-odoo 
I have faced an issue on one of the projects.
this issue is sent by the client to me.
I have also regenerated the same after the latest pull on the local system as well.
it might be possible someone is updating the code.
I will check again and get back to you.

**Comment by konsultoo-adarsh** [comment]
Hello @vava-odoo 

I have facing the same issue when I generate the payment link for a sales order and then try to open a link

can you please try with the sales order??

Thanks

**Comment by vava-odoo** [comment]
Hi @konsultoo-adarsh 
Thanks for confirming. But everything seems to be working just fine on the runbot...
Can you try to reproduce on the runbot, please? Because github issues are meant for easily reproducible standard bugs.
Or may I ask you to create a ticket on the [support page](https://www.odoo.com/help)?
This would allow my colleagues to directly inspect your database.
Regards,

**Comment by vava-odoo** [comment]
Hi @konsultoo-adarsh 
Here is the PR that will solve the issue: https://github.com/odoo/odoo/pull/120751.
Sorry for the delay and inconvenience.
Regards

**Comment by konsultoo-adarsh** [comment]
Hi @vava-odoo 

I have checked the latest code the issue is still the same.

can you please update the main 15.0 branch?

Regards

**Comment by vava-odoo** [comment]
Hi @konsultoo-adarsh 
I don't get your point, the code has been updated in 15.0: https://github.com/odoo/odoo/blob/15.0/addons/sale/controllers/portal.py#L364
Are you still facing this issue?
Regards,

**Comment by konsultoo-adarsh** [comment]
Hello @vava-odoo 

I have checked on the production of the customer there is still the same error.

I have created a new ticket for the same here is ticket no: **3318675**.

can you please help me to resolve this quickly its a very urgent.

thanks

**Comment by niyasraphy** [comment]
hi @konsultoo-adarsh ,
if the client instance is hosted in odoo online or odoo sh the codes where not updated on daily basis. if am correct for the odoo sh the code will be getting updated weekly, so you may have to wait for a week so that code will get updated there.

mean while you can get a backup of client db to your local and with latest code and see if the issue happens or not.
thanks

**Comment by vava-odoo** [comment]
@niyasraphy Yes, maybe the update was not done yet. But saas db are updated daily.
