### ISSUE TITLE
[16.0] 301 redirects for products just returns a 404

### ISSUE THREAD

**Issue by Levi-Bensley** [odoo/odoo#120443]
**Impacted versions:**
v16
**Steps to reproduce:**
Create a 301 redirect for a product to any page
Leave the product as active or archive or delete
got the URL for the product
**Current behavior:**
Go to the 404 page if the product is deleted or if it is archived you go to the product page but the product is unavailable
**Expected behavior:**
It to respect my redirect and 301 to the other specified URL, no matter what the origin URL is or pointing to

**Comment by Levi-Bensley** [comment]
Upon research, I think the issue lies in [_serve_ir_http](https://github.com/odoo/odoo/blob/bff9cb778eb3ae4adef5f5518151c7be3386d8ce/odoo/http.py#L1590)

I think more of the function needs to be in the try-catch, once I put lines 1607 to line 1612 into the Try, it then worked as expected.

**Comment by vava-odoo** [comment]
Hi @Levi-Bensley 
Thanks for sharing. Maybe @Julien00859 could help here?
Regards,

**Comment by Julien00859** [comment]
My gut feeling is that there is nothing wrong with `_serve_ir_http` but that there is a problem between the website configured redirections and the http stack. I'll have a look, but not right now. cc @odoo/rd-website 

Levi, can you confirm that this redirection was created from that website menu that is only accessible in `?debug=1`, I forgot its name

**Comment by Levi-Bensley** [comment]
Yeah, they have been set up via the Redirect menu.

The initial ._match call in the Try is successful as it will return the controller route, and what id and model it should match with, it's not until pre_dispatch that it then realises this doesn't exist, and at this point, it no longer checks for redirects. 

Yeah, the issue may be deeper rooted but this was the place I managed to temporarily fix this until an official fix is made.

**Comment by rdeodoo** [comment]
Hello,

Everything should be working fine:
- You can create a 301/302 redirect for a product (or any controller) and it will be considered if the product is archived (and deleted too I guess?). This behavior was made at https://github.com/odoo/odoo/commit/3b9cd536607b1631dd375ab2e5cc94eb814a6e9b and restored in 16.0 with https://github.com/odoo/odoo/commit/fd5c6a861cae4be5498f9bc5bb3ce9300bd3a003 (then improved with https://github.com/odoo/odoo/commit/fc168b17a8e35e7b04496d7b91602b80b23c347a).
- I had a look and was able to correctly perform the redirect for an archived product to the /shop page. You need to be sure to not insert the anchor part of your URL which is typically added when you visit a product page. For instance, it should be `/shop/customizable-desk-9` and not `/shop/customizable-desk-9#attr=1,3`

Note that I will take the opportunity to summarize a few facts about redirect:
- The order in which an endpoint is served is:
1. Serve Controller + 308 + 404
2. Serve Attachment
3. Serve Page
4. Serve Redirect (301/302)
- This means that if you have a 301 redirect from /my-page to /something-else, it can't work if there is an existing page /my-page.
Indeed, if we match a page we don't consider redirect. It's done that way for perf reason -> We don't want to check if there is a redirect for the request everytime as it's used in 0.000001% cases.
- The issue you reported and the commits I mentioned are actually more a hack/fallback that a real mechanism, but it works.
If you unpublished a record, let's say job ID 4, then create a 301 redirect from /jobs/xx-4 to /a-page, it will work.
Just note that the redirect won't be seen/fired for the administrator. Otherwise, the admin would not be able to publish again his record, on top of other things.
- Hack of the hack: you could create a /404 page to give the impression to the user that he landed on a 404 page, while he actually just went through a 301/302 redirect to a real page which is designed like a 404 page.

**Comment by Levi-Bensley** [comment]
Unfortunately, no matter the state of the product, archived or deleted, it ignored the 301, archived just went to the product page saying no longer available and the deleted product 404'd

**Comment by rdeodoo** [comment]
Here is a video to do it properly: https://watch.screencastify.com/v/iExG6ArZRsUxHHUw4NoI
Are you sure:
- You are checking the redirect with a non admin user / public user ? As I mentioned, it won't be visible for admins.
- You did not add the anchor part of the URL ? As I mentioned, it should be the exact URL without it.
