### ISSUE TITLE
[8.0] Disabling taxes makes them invisible on the invoice lines

### ISSUE THREAD

**Issue by adrienpeiffer** [odoo/odoo#12066]
Impacted versions:

8.0

Steps to reproduce:

See https://youtu.be/kKBJ-fyHvoY

Current behavior:

Currently, disabling taxes makes them invisible on the invoice lines

Expected behavior:

active/non-active behavior should have no impact on existing relational fields.
So, disabling taxes should remain visible on the invoice lines

Video/Screenshot link (optional):

https://youtu.be/kKBJ-fyHvoY

**Comment by wtaferner** [comment]
Additionally it is possible to delete a tax and there is no constraint to avoid this situation which is even worse ;-)

**Comment by adrienpeiffer** [comment]
OPW 677751

**Comment by Yenthe666** [comment]
@mart-e and @odony what do you think about this one?

**Comment by odony** [comment]
As @jorenvo explained on the ticket, this is basically a consequence of how many2many relationships work. When reading a m2m, the `active` flag of the target table is taken into account. This may be desirable in some cases, and less in others (like here), but we can't suddenly change it.
For instance for a m2m to a "tag" or "category" model, you'll want the tag to disappear from all places where it was used. But for taxes you don't, because they impact the computation of the subtotals.

The initial workaround we thought of was to add `context="{'active_test': False}"` on the `invoice_line` o2m field, so that when it reads it m2m field it will also include the inactive ones, while preserving the fact that when you select a tax in the m2m, the `name_search` still ignores inactive ones.
The downside is that this only fixes the view, so if you ever happen to modify this invoice, the inactive tax will not be taken into account. So it fixes half of the problem, and introduces another inconsistency.

On second thought, a better workaround is to modify the current domain on the m2m (which only allows selecting *root* taxes), and force it to include both active and inactive entries. This will bypass the automatic "active_test" and should fix both cases (view + backend) while still preventing the selection of the tax in the UI. This is what PR #12200 does.

@adrienpeiffer Let me know if that works for you.

**Comment by wtaferner** [comment]
@odony 
What about the more severe issue that deleted m2m will be lost forever until you restore them? Not a big deal with non-critical values and models but for taxes it is highly critical I would say, right?

**Comment by odony** [comment]
Fix landed in 8.0 at cd3f52ba1064000483f1a4cd781cf576767b4e01, will be forwarded shortly in 9.0.

**Comment by wtaferner** [comment]
Should I do an own ticket/issue for my additional and related comment or do you consider it as invalid?

**Comment by odony** [comment]
@wtaferner I would prefer a PR ;-) For 9.0 I suppose the fix is as trivial as setting ondelete=restrict on account.invoice.tax (just tried that at 10f1cae877d611b4f967f2a46ed5625530a249cf). For 8.0 I suspect it will be more complicated because no record actually holds a mandatory m2o to account.tax, so ondelete=restrict will not cut it. Perhaps the easiest will be to handle it specifically in account.tax.unlink() then.

**Comment by wtaferner** [comment]
Hehe, too many PR's were already rejected so I dare to suggest a PR on such a "difficult" topic as I am short in time too ;-) 

Restricting (creating a lock model where I create stored relations automatically and restrict them via m2o fields) or teaching the user to not touch or delete tax for v8 is easier than to resolve this on a framework level and monkey patching is lame and especially you don't like it neighter...

I think Odoo/you should think about a mechanism which makes it able to lock/constraint deletion for a m2m field (maybe my approach suggested could do the trick even in your eyes) ;-) 

For sure, in case I will find the time/motivation and a solution you can not resist to merge (which is highly rare) I am more than happy to contribute this important feature in master :-)
