### ISSUE TITLE
[15] Unable to install requirements.txt on Debian 12

### ISSUE THREAD

**Issue by grzekru** [odoo/odoo#120879]
**Impacted versions:**

Odoo 15
Debian 12
Python 3.11.2

**Steps to reproduce:**

Create venv
pip3 install -r requirements.txt

**Current behavior:**

https://pastebin.com/rHMsutcH

**Comment by bayuik** [comment]
suggest using Python version 3.7 - 3.10 because Odoo 15 has specific requirements for some connected dependencies. This Python version will ensure proper compatibility with Odoo 15 and ensure optimal performance. If you use a Python version outside this range, there may be issues with related dependencies and features. Please take note of these requirements to ensure a smooth running of Odoo 15. If you need further assistance, feel free to ask.

**Comment by vava-odoo** [comment]
Hi @grzekru 
Odoo 16 has been adapted to Python 3.11 (see https://github.com/odoo/odoo/pull/114899), but AFAIK it won't be done in previous versions.
Best
