### ISSUE TITLE
[9.0] account.move.line: "amount_residual" field should depend on "account_id.reconcile"

### ISSUE THREAD

**Issue by fdegrave** [odoo/odoo#12095]
Impacted versions: 9.0

Steps to reproduce: 
1. Create an move with a line on a non-reconcilable account and post it
2. Set the account as "reconcile=True"
3. Create a reverse move of the one in step 1
4. Try to reconcile the 2 move lines on the (now) reconcilable account -> Nothing happens!

That is because the stored value of the amount_residual on the original line is "0.0" because the account was not reconcilable at the time. When the field "reconcile" on the account was changed to "True", the amount_residual on the move lines were not recomputed.

FIX proposal : in AccountMoveLine class, add 'account_id.reconcile' to the @api.depends(...) arguments on the "def _amount_residual(self)" method.

**Comment by csnauwaert** [comment]
Hello,

Sorry for the time it took to answer this issue. You are absolutely right, however we can't fix it the way you are proposing. There are two reasons for this.
The first one is for performance. According to our test, editing an account, that has a lot of move lines, to mark it "reconcile=True" will take a long time to process.
The second one and more problematic is the contrary. If you have an account that is reconcile=True and that you change it to mark it as non reconcilable. It means you'll have to change the amount_residual on all the account move lines for that account. However some move lines might have been reconciled with other move line and this could be problematic for reporting.

We've fixed this in v9.0 by adding a constraint that prevent an user to change the reconcile flag on the account if there are some account_move_line associated to that account. This is not the best fix users that makes a mistakes are kind of blocked, so we've made a better fix in a later version (v11 if I'm correct) that allows user to change their reconcile flag on the account (if there are no move that are reconciled) and recompute correctly the associated move lines.

Since this has already been fixed, I'm closing this issue

Best regards
