### ISSUE TITLE
error import csv 

### ISSUE THREAD

**Issue by hindbenessy** [odoo/odoo#12121]
hello, when i import the invoice i get this error i dont understand where 's the problem thanks 
version : odoo8
![capture du 2016-05-20 16 36 21](https://cloud.githubusercontent.com/assets/17640313/15433230/6259c254-1ea9-11e6-9cf4-2d840a65c121.png)

**Comment by tesserB** [comment]
Can you check your logs and provide a Stacktrace/Traceback?

**Comment by Yenthe666** [comment]
Hi @hindbenessy,

There is no way for us to test this or see what is wrong with just a screenshot.
This doesn't really falls under a bug either, since there is just something wrong with your CSV import.
If you still face this issue please post a question on the official Odoo forums (help.odoo.com) and provide some more details there. There are a lot of people there that can help you.

Regards,
Yenthe
