### ISSUE TITLE
[9.0][BUG] Subscription Application access rights

### ISSUE THREAD

**Issue by antonybrugger** [odoo/odoo#12181]
Impacted versions: 9.0e

Steps to reproduce:
Create a user with HR/Employee Access rights => Contracts/See Contracts are automatically added:
![image](https://cloud.githubusercontent.com/assets/2707881/15545156/9cf53cb8-229b-11e6-8777-32a62ad75bd6.png)

Current behavior:
Contracts/See Contracts are automatically added

Expected behavior:
Contracts/See Contracts should not be automatically added if we does not want the user Employee to access 'Subscriptions' application
Access right 'Contracts/See Contracts' should give access to the application 'Subscriptions' and we should be able to remove this right (=> 'Subscription' application not visible) 

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Hi @antonybrugger,

Just tested this in the latest runbot and I can confirm this is a bug.
@mart-e can you put somebody at this one?

**Comment by mart-e** [comment]
Hello,

The automatic addition is due to the inheritance defined on the `Employee` group
![screenshot from 2016-05-27 15-29-28](https://cloud.githubusercontent.com/assets/564822/15609544/dc8004a4-2420-11e6-81ca-a54c214550af.png)

The default value is maybe not optimal but we tends to have by default permission security rules that users can restrict depending on the organisation structure.
However we admit is not ideal so we have changed that at odoo/enterprise@5d67fd488c69811478b915d6b39b3058ab50b6bb

However this will only impact the new databases. For the existing ones, you will need to modify the Employee group to remove the inherit shown in above screenshot.
