### ISSUE TITLE
[14.0, 15.0, 16.0] [Planning > Gantt view] Task should expand proportionally to its duration in hours

### ISSUE THREAD

**Issue by sergueikp** [odoo/odoo#121866]
Impacted versions: 14.0, 15.0, 16.0

Steps to reproduce:
Create a task that start at 00:00am and finish at 12:00am

Current behavior:
In the week and month view mode the task expands on the whole day.

Expected behavior:
Task should expand on the half of the day.
In week and month view mode task should expand proportionally to its duration in hours.
Task should not expand on whole day if its duration is less than 24 hours. 

Video/Screenshot link (optional):
![Gantt_task_expanding](https://github.com/odoo/odoo/assets/9844780/2e17be27-bc00-4d31-9c4b-18cc4dd1d22a)

Support ticket number submitted via odoo.com/help (optional):

**Comment by xavierbol** [comment]
Hello @sergueikp ,

Thanks for the report and sorry for the delay!

For us, it is the expected behavior to be able to display the information that we think important inside the pills (that is, shifts in this case). 🙂

If you really want to change that to have the behavior that you expect that, you can alter the view definition to change the precision for each scale.

Instead of having that precision:
```xml
<gantt
      ...
      precision="{'day': 'hour:full', 'week': 'day:full', 'month': 'day:full', 'year': 'day:full'}"
      ...
>
...
</gantt>
```

You could have:
```xml
<gantt
      ...
      precision="{'day': 'hour:full', 'week': 'day:half', 'month': 'day:full', 'year': 'day:full'}"
      ...
>
...
</gantt>
```

Note: I just changed the `week` scale in the precision attribute to fit with your example.

Thanks for your understanding!

Have a nice day!

**Comment by sergueikp** [comment]
Thank you!
