### ISSUE TITLE
shall I get some materials about learning odoo?

### ISSUE THREAD

**Issue by vx0532** [odoo/odoo#12197]
Impacted versions:odoo8 / odoo9(better)

Steps to reproduce:want help.

Current behavior:learning odoo

Expected behavior:get some material to learn odoo if I just have some experience about Python.
Thanks a lot

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Hi @vx0532,

There are plenty of learning resources around the internet, such as the official Odoo tutorials and docs. 
You can find an overview of available tutorials / docs at this URL: https://www.odoo.com/nl_NL/forum/help-1/question/fyi-initiatives-from-odoo-to-help-train-and-educate-the-community-102341

I'm closing this since this is not a real issue, it is a question. You might want to post this on the official Odoo help forums (help.odoo.com), there are a lot of people that can help you there with specific questions.

Regards,
Yenthe
