### ISSUE TITLE
[9.0e] Search More on carrier_id field shows no price when done before saving sale order

### ISSUE THREAD

**Issue by krueger80** [odoo/odoo#12204]
### Impacted versions:
9.0e

### Steps to reproduce:
1) Start a new DB with demo data
2) Create a new sale order
3) Select "Pizza Inn" as Customer
4) Select "[A1232] iPad Mini" as product
7) Click the Delivery Method drop down field and select "Search More..."

### Current behavior:
All carriers are listed, with price all 0.00

They're all 0.00 because the data not saved yet isn't taken in account. 

### Expected behavior:
Prices should be calculated for all listed carriers, using data not saved yet to calculate. See #12203 that tries to retrieve good prices, but gives error instead.

**Comment by Yenthe666** [comment]
@nim-odoo can you have a look at this one? Not sure what the expected behaviour is from Odoo their side with this one.

**Comment by nim-odoo** [comment]
@rim-odoo

**Comment by rim-odoo** [comment]
If you have an efficient fix, in stable, that does not hide the errors, I will be happy

**Comment by rim-odoo** [comment]
I don't think this is critical and for some technical reasons, it is hard to fix that in stable.

**Comment by rim-odoo** [comment]
Actually, this is due to the original architecture choices of the "price" field... it is a computed-stored field relying on context hacks and having a saved sale order. Fixing it would mean some refactoring.

I agree that some refactoring should be done for a next version, but in a stable version, I think it is a minor inconvenient. People can still save their sale order at least once.
