### ISSUE TITLE
[8.0] point of sales model pos.order no sum in group by

### ISSUE THREAD

**Issue by fadeldamen** [odoo/odoo#12222]
Impacted versions: 8.0

Steps to reproduce: go to pos.orders and group by some field not sum (agregation) in total field

Current behavior:

Expected behavior:

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Hi @fadeldamen,

I can't really reproduce this issue, can you supply me with a bit more details please?
Can you reproduce this on the latest Odoo 8 (runbot)?

Regards,
Yenthe

**Comment by JKE-be** [comment]
@Yenthe666 
![image](https://cloud.githubusercontent.com/assets/4848797/15700165/a9b6352e-27d2-11e6-80dd-223c8a4c9ffe.png)

@fadeldamen 
Probably because the field total_amount of pos.order is not stored in database
To fix it, it required to store the field and so change the database structure... what can not be done in stable version.
I add wish list maybe for the v10.

**Comment by Yenthe666** [comment]
Hi @fadeldamen ,

Thank you for your bug report.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.
P.S: As this is wishlist it will still come up every once in a while too.

Regards,
Yenthe
