### ISSUE TITLE
[9.0][Cancel Journal Entries] Cannot delete cancelled Invoice after validation

### ISSUE THREAD

**Issue by alaa9jo** [odoo/odoo#12261]
Impacted versions:
9.0c Latest update ( 1 JUN 2016)

Steps to reproduce:
1) Make sure you Allow cancelling entries for journal Vendor Bills
2) Create a PO then Confirm it
3) Click on PO's invoice button and create a new invoice
4) Validate invoice
5) Click on button "Cancel Invoice"
6) Try to delete invoice,notice that a warning box appears "You cannot delete an invoice after it has been validated (and received a number). You can set it back to "Draft" state and modify its content, then re-confirm it."

7) Do what it says by clicking on button "Reset to Draft" , notice that status of Invoice is Draft,also notice that invoice is no longer have a number
8) Try to delete invoice, it will show the same warning box in step 5, the system thinks my invoice is still not a draft

Current behavior:
You cannot delete invoice in draft status, system doesn't notice that my invoice is reset to draft and it's no longer have a number

Expected behavior:
I should be able to delete draft invoice

Video/Screenshot link (optional):

**Comment by intero-chz** [comment]
As long as i know, the invoice number will be saved on an extra field (v7 internal_number). So when you've canceled the invoice, you can't delete it until this field is empty.

**Comment by alaa9jo** [comment]
@intero-chz If this is correct, then if I click on "Reset to draft", shouldn't this field become empty? OK...maybe some people want to use the same number and edit the invoice,maybe it was cancelled to fix it with correct data , but at least the system should allow deleting an invoice if it's in draft,even if it has an internal number, if this is by design,it would be great if someone can explain this

**Comment by intero-chz** [comment]
@qdp-odoo maybe can explain it.

**Comment by qdp-odoo** [comment]
not a bug, indeed: you never want to delete an invoice that has an internal number because it would make a gap in your invoice numbering... which is wrong.

So if you really don't want that invoice anymore, replace the partner and all information with the next invoice to be encoded... But, you know that's totally forbidden in many (all?) countries, right?

**Comment by qupro** [comment]
It's true that a gap in your invoice numbering is forbidden, I suppose in every country.

I think that this is an usability issue:

User expects that when they cancel a validated invoice (number assigned) they will be able to delete it too, because when they create a new one, Odoo automatically will set the invoice number using "gap numbers".

But this is not the actual working, I think the reason why is because Odoo simply adds +1 to the last invoice number created (the number is saved in "Settings > Sequences > Costumer Invoice"), without checking gaps before, so it needs the corresponding draft invoice not to be deleted to "recover the corresponding gap number".
