### ISSUE TITLE
[10.0/Master] Feature Request: Allow Restriction of Payment Methods to Countries and Regions (ie. like Delivery Methods)

### ISSUE THREAD

**Issue by lukebranch** [odoo/odoo#12310]
I would like to request a feature to allow for restricting payment methods per country and region in a similar manner to how delivery methods can be restricted at the moment in 8.0/9.0/Master. 

In my use case I need to allow direct bank transfers, cheque payments and C.O.D. for domestic orders, however I need to be able to not allow these payment methods for international orders.

<h1>Impacted versions:</h1>
8.0/9.0/Master

<h1>Steps to reproduce:</h1>
1) in backend go to:
Accounting >> Payments >> Payment Acquirers > [Any Payment Method]

<h1>Current behavior:</h1>
It is not possible to restrict payment method by country or region.

<h1>Expected behavior:</h1>
Allow restriction of payment methods by country and region to allow for more granular control of payment methods.

**Comment by lukebranch** [comment]
@Yenthe666 ,

Do you have any thoughts/comments on this feature request? I think it would make a really useful addition to 10.0/Master.

**Comment by Yenthe666** [comment]
Hi @lukebranch,

Thanks a lot for the suggestion. I personally like the idea that you can configure in which countries you want to allow specific payment methods. It is a feature that could be added since we know from where the visitor comes and the framework can handle this (with some extra development).
That being said I only have rights to arrange issues and PR's, I'm not allowed to make such big decissions in Odoo. I'll label this with wishlist for now, this'll make sure it is being discussed by the Odoo R&D team somewhere along the line.
@mart-e could you please give me input on this one? What do you think about it?

**Comment by lukebranch** [comment]
@Yenthe666 ,

Thanks for looking into this. I think it would be a very useful feature in 10.0.

**Comment by mart-e** [comment]
I agree it could be useful. I will submit the feature request, hopefully it will be accepted/developed.

**Comment by lukebranch** [comment]
@mart-e @rim-odoo ,

Thank you for considering my request. Hopefully this will be accepted and land in 10.0. It would be very useful to have this kind of control over the payment methods.

**Comment by lukebranch** [comment]
For anyone following this thread, it looks like there is a PR here:

https://github.com/odoo/odoo/pull/12668

Hopefully this lands in 10.0, it would be a very useful feature to have.

**Comment by Yenthe666** [comment]
@lukebranch I saw it popping up this morning too, looks neat!

**Comment by lukebranch** [comment]
closed with:

https://github.com/odoo/odoo/pull/12668

hopefully this lands in master for v11.
