### ISSUE TITLE
[9.0] Duplicate Product doesn't have the same Accounting inputs

### ISSUE THREAD

**Issue by alaa9jo** [odoo/odoo#12315]
Impacted versions:
9.0c , Latest update ( 7 JUN 2016)

Steps to reproduce:

1) Create a product and set all of it's accounting fields ,make sure you change every field from the default,then save
2) Click Action -> Duplicate
3) Go to tab Accounting of the duplicated product and check all fields
Current behavior:
Some/all of accounting fields are different from the original product
Expected behavior:
Duplicate product should have the same inputs of the original product,including fields related to accounting
Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Hi @alaa9jo,

This is indeed the case, not all settings are copied from a product. An example of a newly made product:
![image](https://cloud.githubusercontent.com/assets/6352350/15849940/71d805de-2c95-11e6-81d0-4ab189eb4f51.png)
An example of the duplicated product:
![image](https://cloud.githubusercontent.com/assets/6352350/15849949/7ad9210e-2c95-11e6-9d8f-0e67af2eb2d2.png)
So it just copies the taxes.
@qdp-odoo I bet there is a reason for this / is the expected behaviour. Could you give your feedback on this one?

**Comment by qdp-odoo** [comment]
the reason why the accounts aren't copied is because they are properties and property fields aren't copied by default I suppose.

Not a big deal, though, as we're only talking about default values. Men should always double check their duplicated object's values before starting to use it for real.

**Comment by Yenthe666** [comment]
Pretty much what I was thinking. What do you prefer @qdp-odoo a close or a wishlist?

**Comment by alaa9jo** [comment]
I'm not sure...are you saying Income account and expense account are properties,but what about Customer/Vendor Taxes? aren't these properties as well? but they are copied just fine
