### ISSUE TITLE
pricelist in SO is only applied after changing the amount fo the article

### ISSUE THREAD

**Issue by stefatronik** [odoo/odoo#12375]
Impacted versions:
ODOO9 nightly from 2016-06-10
Steps to reproduce:
When writing a Sales Order I need to change the order quantity to apply the chosen pricelist. Even the actualize button at the bottom of the SO doesn't calculate the correct price.  
If I change the pricelist it will not change the prices until I change the order quantity.

**Comment by JKE-be** [comment]
@tivisse @bst-odoo  King of usability... No onchange('pricelist_id') implemented... 

Should be implemented or not ? already a task on it or not ? thx

**Comment by bst-odoo** [comment]
That would be nice to do it, but isn't there any technical limitation to it ? Or is it a historic decision ?

**Comment by JKE-be** [comment]
hello @stefatronik 
It is already like that since the first version.
It is a historic but also an actual decision.

If you have updated manually unit price, or discount, you don't want to lose all your changes when you change the pricelist.

It is questionable, but the actual position of Odoo about this use case.

The 'actualize button' (save and reopen in edit mode) recomputes tax, subtotal, ..., but will not change the price (for the same reasons that above).

The standard flow is : 
  - choose the customer which one can have an preferred pricelist configured
  - choose the pricelist if you want another that the default of this partner.
  - Next create the sale order lines and adapt qty, unit price or discount if needed

**Comment by stefatronik** [comment]
Good morning JKE. Thanks for your explanation on this. 
Let me suggest an "apply" or "recalculate using current pricelist" button next to the pricelist selection box that makes it possible to apply the chosen pricelist. A hover-text over this button could explain what you wrote above...

**Comment by JKE-be** [comment]
Ok, thank you for your feedback.
I tag this issue as a wishlist.
Have a nice day.
