### ISSUE TITLE
How to open odoo after installing it?

### ISSUE THREAD

**Issue by fghhfg** [odoo/odoo#12385]
How to open odoo after installing it on win7?

first time it auto open dashboard. now I restart my computer, I am not should how to go into dashboard

**Comment by Yenthe666** [comment]
Hi @fabienmorin,

Your Odoo is available under `http://localhost:8069/` by default. The dashboard can be reached by logging in on Odoo and clicking on 'Dashboards'.
Closing this since it is not an issue but a question. If you still face issues with this or are not sure on how to use Odoo you can ask your questions on the official Odoo help forums (help.odoo.com).

Regards,
Yenthe

**Comment by fabienmorin** [comment]
I don't see any reason why my github account is associated to this thread. I think @Yenthe666 you made a mistake.

**Comment by Yenthe666** [comment]
@fabienmorin my apoligies, I've accidentally pinged you, I was a bit to fast there. Sorry!

**Comment by pldilley** [comment]
Would it please be possible to add this to the documentation installation section?

https://www.odoo.com/documentation/11.0/setup/install.html#packaged-installers
