### ISSUE TITLE
[9.0/10.0] product.pricelist.item using deprecated decorator @api.one

### ISSUE THREAD

**Issue by aristobulo-eezee** [odoo/odoo#12408]
Impacted versions:
9.0

It's strongly recommended by Odoo to avoid using `api.one` decorator, BUT, it's used in `product` module.
https://www.odoo.com/documentation/9.0/reference/orm.html#openerp.api.one

Affected code:
https://github.com/odoo/odoo/blob/9.0/addons/product/pricelist.py#L359

Please fix this method based on your on **own recommendation** about this **deprecated** decorator

**Comment by Yenthe666** [comment]
@mart-e could this be fixed in the stable? I also agree that those @api.one decorators shouldn't be here, I've seen more of them in the past.
I don't think this can be done in the stable though?

**Comment by mart-e** [comment]
It is not recommended but do you get a real issue with this method?
I also remind you our [stability guidelines](https://github.com/odoo/odoo/wiki/Contributing#what-does-stable-mean)

> No "improvement" (technical or functional) should be done in stable, they typically have a very low value/risk ratio. Often, the functional coverage is voluntarily limited.

Pull request welcome for master though

**Comment by Yenthe666** [comment]
@mart-e a pull request for the master is useless though? All modules are migrated to the new API anyways, so this should be replaced by V10 too.

**Comment by aristobulo-eezee** [comment]
@mart-e 

We are working with pricelists, so we came with two basic options:
1. use this deprecated decorator in our code
2. use multi, iterate on self and call super on each element

What I don't like is that in the future Odoo will have to fix this, leaving our code in bad shape, either with a non-working iterator or with spaghetti code just for this small thing.

I agree, is not a big problem, but it was Odoo who deprecated this decorator. What's the big issue on fixing it on a **standard** module.

**Comment by rim-odoo** [comment]
Feel free to improve master code, indeed.

**Comment by aristobulo-eezee** [comment]
What about 9.0?

**Comment by Yenthe666** [comment]
@aristobulo-eezee as Martin stated:

> No "improvement" (technical or functional) should be done in stable, they typically have a very low value/risk ratio. Often, the functional coverage is voluntarily limited.

So I guess this won't be merged in 9.0, only in the master.

**Comment by Yenthe666** [comment]
@rim-odoo I wouldn't really label this invalid, technically his bug report is correct. The @api.one should have been removed before V9.
@mart-e could you atleast fix this in the master? :gem: 
@aristobulo-eezee that downvote is not cool, don't shoot the messenger. :cactus:

**Comment by aristobulo-eezee** [comment]
@rim-odoo it's kind of irresponsible to label this as invalid, it was odoo who deprecated the decorator and still continued using in a standard module.

@Yenthe666 don't take it personal

**Comment by rim-odoo** [comment]
Ok guys, if a label is greatly offending you, I remove it.

But actually... even if this code is quite ugly, **do you have a real problem**? Something that breaks your business? Or are we, all of us, losing our time on a detail?

I can agree, we shouldn't use our own deprecated methods, but sometimes... sh**t happens. People are not perfect, sometimes they ship ugly code :( But it works.
As @mart-e recalled it, we do not perform refactoring/code cleaning in stable versions, because it has nearly no added value for end-users, while it increases the risk of introducing bugs.

As already stated above, we are open to improvements against master branch, where refactoring can and should be done. I think you can understand this position.

**Comment by odony** [comment]
@antonylesuisse @rco-odoo Actually, perhaps we should reconsider the wording of our documentation for `@api.one`, as it seems to be brought up pretty often, and generally confuses people.

That decorator seems useful when implementing computed fields, and generally for any method that does not return anything. It only gets awkward and confusing for methods that return a value (because callers may not expect the result to be packed into a list).
Perhaps instead of plainly deprecating it we should keep it and explain that its use is discouraged for methods that return a value, and really explain why (rather than a vague hint that it may not do what you expect).

**Comment by Yenthe666** [comment]
@odony in generale I'd like to propose a more detailed documentation with examples and what happens for the most used api methods. The info is to short at this point.

**Comment by moylop260** [comment]
> @rim-odoo : I can agree, we shouldn't use our own deprecated methods, but sometimes... sh**t happens. People are not perfect, sometimes they ship ugly code :( But it does the job.

FYI OCA have the following CI checks: https://github.com/oca/pylint-odoo
Feel free of implement it in your CI process in order to avoid a `ugly` code auto-detected

**Comment by pedrobaeza** [comment]
:+1: for not deprecating `@api.one`.

**Comment by aristobulo-eezee** [comment]
So based on this:
https://github.com/odoo/odoo/pull/13199#issuecomment-248230599

I kindly request this issue to be reopened as it also affects v10.0

**Comment by dbo-odoo** [comment]
Hello,

Given the output of #13199, I re-close this issue. @api.one stays depreciated, it seems.

**Comment by moylop260** [comment]
FYI `api.one` was deprecated finally for v13.0
 - https://github.com/odoo/odoo/pull/34555
