### ISSUE TITLE
Unable to Install he_recruitment module

### ISSUE THREAD

**Issue by thejunaidhashmi** [odoo/odoo#12425]
Steps to reproduce:

Current behavior:

Expected behavior:

Video/Screenshot link (optional):

**Comment by JKE-be** [comment]
Need more details...

Which version ? 7, 8, 9c, 9e ? 
Online or on promise ? 
What is the error ? A traceback ? 

We are not on twitter, you can type more than 140 characters !

**Comment by thejunaidhashmi** [comment]
hey'
 its version 8 i'm accessing

  I'm not able to Install the "Recruitment" Module in Human Resource even
though i have ticked the "manage the recruitment process" in
setting>Configuration>Human Resources>

**Comment by JKE-be** [comment]
ok, and what did you mean by 'not able'...
You have a popup with a warning message ?
You have some logs in your console ? 

Because, if you check on the runbot, it works...
So there are something on your install which block and without more details, we cannot help you...

And because it is at first view not an issue in Odoo but with your install/configuration, you should post your question on the forum: help.odoo.com.
