### ISSUE TITLE
[account] Trace Error must be handle when there is not account in journal

### ISSUE THREAD

**Issue by JulioSerna** [odoo/odoo#12441]
Impacted versions:
* 8.0

Steps to reproduce:
* Create one journal of type `cash` from importation without `accounts`
* Create bank statement
* Reconcile

Current behavior:
* It shows `Odoo server Error`

Expected behavior:
* The `Odoo server Error` must be handle with `raise exceptions`

Video/Screenshot link (optional):
https://youtu.be/wkSEXU_t7qc

**Comment by beledouxdenis** [comment]
Dear Julio, 

We do not consider this issue as a blocking issue, and it therefore won't be solved in a stable release such as 8.0.

This is not considered as a blocking issue, because:
- This behavior could not happen using the regular interface to create the journal. Users using the import are supposed to know what they are doing.
- In this case, replacing the traceback by a warning message is considered as a usability improvement.

I hope you will understand.

Regards,
