### ISSUE TITLE
Client error when discard rewards in Discount & Loyalty

### ISSUE THREAD

**Issue by minhlderp** [odoo/odoo#124785]
Impacted versions: 16

Steps to reproduce: sales -> products -> discount & loyalty -> create new record -> click exist rewards data -> click discard button

Current behavior:
error
Expected behavior:
discard success
Video/Screenshot link (optional):
![image](https://github.com/odoo/odoo/assets/14050604/ba9b936e-8bd6-46b0-a3b2-ae1f68ecdaf9)
Support ticket number submitted via odoo.com/help (optional):

how to fix: add fields reward_product_ids, all_discount_product_ids to loyalty reward kanban view

I think all fields declare in form view (include invisible fields) need declare in kanban view (i dont know why? hix)

**Comment by vava-odoo** [comment]
Hi @minhlderp 
Thanks for reporting. Will be fixed in https://github.com/odoo/odoo/pull/106888.
Next time, if you know the way to solve the issue, it is faster (for us, but maybe for you too) to create a pull request with the change to apply (If it is your first contribution, please follow [the steps here](https://www.odoo.com/documentation/master/contributing/development.html#make-your-first-contribution)
Cheers,

**Comment by vava-odoo** [comment]
Hi @minhlderp 
The issue has been fixed in 16.
Have a nice day.
