### ISSUE TITLE
Odoo Javascript Error when it minified

### ISSUE THREAD

**Issue by aftabnaveed** [odoo/odoo#12509]
Impacted versions: 8.0

Steps to reproduce: Remove the debug mode

Current behavior: Only Top navigation menu is visible rest is white page, any subsequent click won't work either.
Expected behavior:

Video/Screenshot link (optional):

Odoo version is throwing` 40af15c:3 Uncaught SyntaxError: Unexpected end of input error` when not in debug mode,  but when I turn on the debug mode the error goes away and the system resumes to normal.

**Comment by JKE-be** [comment]
Seems a problem with your own install.
That is not reproducible in runbot at first view.

Please check the char at 40af15c:3 which raise the error.
(probably a missing ; in your own code... )
Maybe you have a syntax error in a customization ?

If the root cause is one customization, please use forum (help.odoo.com)

else don't hesitate to reopen an issue with more détail...: Gist with code, module installed, how to reproduce on runbot, ...

You can also try to clear the cache.
