### ISSUE TITLE
Product price gets broken when I edit it from Web Shop and press Enter key

### ISSUE THREAD

**Issue by ricpelo** [odoo/odoo#12521]
Impacted versions: 9.0c

Steps to reproduce:

1. Go to http://localhost:8069/shop
2. Click on any product
3. Edit
4. Click on the product price to edit it.
5. Press Enter key one or two times.

Current behavior:

The price gets "broken". I can separate the digits on several lines and I'm unable to join them back again (BackSpace and Delete keys doesn't work).

Expected behavior:

If I press Enter when editing the price, the price must be entered, like if I click outside of the price field.

Video/Screenshot link (optional):

![2016-06-21-163033_1280x1024_scrot](https://cloud.githubusercontent.com/assets/616169/16233184/c44c44a4-37cd-11e6-9204-5270b26db9c5.png)

**Comment by Yenthe666** [comment]
Hi @ricpelo,

Thanks for your report. The reason for this is that when you enter inside the `span` element and move out of it, it'll create a new `span` for the 00, which is then considered another element in Odoo.
I do think this is expected behaviour and not considered as a bug though. @JKE-be what do you think about this?

**Comment by JKE-be** [comment]
As @Yenthe666 explains, the enter is the behavior of web editor.
So it is normal that enter do a return line.
In your case, it because you are in a specific case, editing a t-field and of type numeric that you would like ignore this behavior... but it is the desired behavior in most case... (even if we could improve it to avoid return line for t-field of type numeric, monetary, ... but it's is a special case that we don't want to manage currently... In any case it is a improvement, and not a fix)
