### ISSUE TITLE
[9.0] Term "Lot" for field 'restrict_lot_id' is misleading in move reports

### ISSUE THREAD

**Issue by aisopuro** [odoo/odoo#12520]
### Impacted versions:

9.0 and above. Tested on our own 9.0 deployment running the 20160318 build and on demo.odoo.com just now.

The field `restrict_lot_id` on `stock.move` is defined as having the `string` "Lot": https://github.com/odoo/odoo/blob/9.0/addons/stock/stock.py#L1991. 

This causes confusion in the stock reporting view for moves. Since Odoo 9 is able to allow the user to group by any appropriate fields of their choosing, they can group by the field "Lot", which is actually `restrict_lot_id`.
![image](https://cloud.githubusercontent.com/assets/2587901/16232746/72939cdc-37d4-11e6-886f-49ec7c36d9f1.png)

This is confusing for the user: the assumed meaning of a field like "Lot" would be "the lot that was moved". Especially "the lot that was moved to the customer". However, outgoing picking moves don't normally set the value of `restrict_lot_id`, but inventory lines do. So in many systems, you will have a number of inventory lines that correctly display the one lot that was associated with their move, but another bunch of moves that show that field to be undefined. This is especially confusing in instances where most moves only handle a single lot at a time: it is very easy for the user to assume that the system should be able to tell them what lot was in what move.
### Expected behaviour:

The field that can be selected for grouping should not be listed as "Lot", but more clearly state that it is the restricted lot. Maybe "Restricted lot", "Forced lot", "Required lot". I think this needs to be changed in the field definition itself, but maybe there is a way to override it just in the tree view.

**Comment by Yenthe666** [comment]
@fhe-odoo I believe you're the EN police here, what do you think about this?

**Comment by fhe-odoo** [comment]
@Yenthe666 Yes but this is not a terminology/wording/vocabulary/grammar question. We all agree on what a lot and a serial number are and that it's the right word. It is more a business&technical question especially considering it's refering to a technical field. Usability team is better suited for this: @bst-odoo or @tivisse 

Also, we don't make string changes in stable versions to avoid erasing translations, so this needs to be discussed for master instead of v9. And I checked master and there is no "group_by lot" on the stock move; there is a "group_by Lot/Serial Number" though. It seems to be the same field. This report in particular needs to be adapted because addons/stock/stock.py doesn't exist in master. I guess it's here https://github.com/odoo/odoo/blob/master/addons/stock/models/stock_move.py#L151

Another thing is, if a change needs to be made on a group_by label, it's on the search view or on the field definition, not on the tree view.

**Comment by aisopuro** [comment]
OK, thanks for the input @fhe-odoo. Should I change the issue name prefix to `[master]` or just leave it empty?

It's too bad that this can't make it into 9.0, but you're right, it is a string change, so merging it into `9.0` is a no-no. We'll just have to overwrite the `string` attribute in our own environments.

**Comment by sle-odoo** [comment]
Hi,
The `restrict_lot_id` was removed in 11.0, so this issue is no longer relevant.

Thanks for the report.
