### ISSUE TITLE
[16.0]Unable to translate the shu that needs to be translated in the code by itself

### ISSUE THREAD

**Issue by sum1201** [odoo/odoo#125524]
Impacted versions:
16.0
Steps to reproduce:

Current behavior:

The translation module of odoo 16 has undergone major changes. The biggest change is that the translation of the code part is all loaded from the po file when the service starts, and then put into the cache. In this way, you cannot customize the translation yourself. If you overwrite the PO file yourself, you will not be able to update the code through github. It can only be translated through tranifex and wait for Odoo's weekly synchronization.

Expected behavior:

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by sum1201** [comment]
Why is no one paying attention and discussing this issue? Or does this problem not exist?

**Comment by vava-odoo** [comment]
Hi @sum1201 
There is a discussion about it on another issue: https://github.com/odoo/odoo/issues/115876#issuecomment-1580532408.
Cheers,

**Comment by BT-jmontero** [comment]
Sadly that other issue is currently closed.

Translations of type "code" are being ignored on purpose, but I don't understand why.

https://github.com/odoo/odoo/blob/3a9b6ed6ec4fdf6131dc90f9a8502dffd8cfaa9e/odoo/tools/translate.py#L1269

Any intention to have it fixed? Right now translations coming from PY files cannot be customized because the logic in behind ignores such "rows" from the PO files.

**Comment by BT-jmontero** [comment]
Just for the record, I have proposed Odoo a possible solution to the issue. I'll put it here as well just in case this could be helpful to anyone in the meantime.

---

I have done some tests locally and the following change in code (check "BT FIX" blocks) would allow us to fix the issue as described below (which means it is technically possible to fix the issue without a big change):

NEW CODE

```
    def _load(self, reader, lang, xmlids=None):
        # BT FIX
        def filter_func_for_code_translations(row):
            return row.get('value') and 'module-overrides-' in row['comments']
        # END BT FIX
        if xmlids and not isinstance(xmlids, set):
            xmlids = set(xmlids)
        for row in reader:
            if not row.get('value') or not row.get('src'):  # ignore empty translations
                continue
            if row.get('type') == 'code':  # ignore code translations (well, not really anymore!!)
                # BT FIX
                if 'module-overrides-' in row['comments']:
                    regex = re.compile('module-overrides-(\w*)')
                    module_to_override = regex.match(row['comments']).group(1)
                    new_translations = CodeTranslations._get_code_translations(
                        row['module'], lang, filter_func_for_code_translations
                    )
                    if (module_to_override, lang) not in code_translations.python_translations:
                        code_translations._load_python_translations(module_to_override, lang)
                    code_translations.python_translations[(module_to_override, lang)].update(new_translations)
                    # END BT FIX
                continue
            # TODO: CWG if the po file should not be trusted, we need to check each model term
            model_name = row.get('imd_model')
            ...
```

The code above is meant to fix the specific issue of overriding code translations in custom addons. Instead of simply ignoring all code translations, we will determine if the translation is meant to override an existing one or not. If it is meant to override an existing translation, we will process it using the new code I'm proposing here; otherwise, we will ignore it (as we did before).

How can we know if a translation is meant to override an existing one? A simple approach would be to use the translation's comments for it. The following PO file entry defined in my custom addon "my_din5008" represents a translation that needs to be overridden (in particular, the original translation is defined in "l10n_din5008_sale", as stated via the translation's comment "module-overrides-l10n_din5008_sale").

#. module: my_din5008
#. module-overrides-l10n_din5008_sale
#: code:addons/l10n_din5008_sale/models/sale.py:0
#, python-format
msgid "Salesperson"
msgstr "Kontakt"

If I run Odoo with "-u my_din5008 --i18n-overwrite" and my code proposal and PO file are there, the desired translation gets overridden as expected ("Salesperson" is now displayed as "Kontakt" instead of "Verkäufer" on DE reports).

**Comment by Yenthe666** [comment]
@mart-e can I please ask your feedback here? There are multiple issues about this subject & I know multiple partners struggling with this (including ourself).

**Comment by mart-e** [comment]
@Yenthe666 the code translations are no longer stored in database and all translations should be done on Transifex. It's an arguable design decition but that's how it was done in 16.0 and I am not aware that's planned to be changed I am afraid.
I am no longer involved in the translation framework so I can't help you much on future changes.

**Comment by Yenthe666** [comment]
Well it is a complete nightmare :) In the past customers that knew a little bit about Odoo could do translations in the UI.
Now you cannot do this anymore for Python translations for example.. Who's responsible for the translations now? :)

**Comment by mart-e** [comment]
Apparently there is some work ongoing to solve this issue at  #124790
Closing as to keep the discussion there or on the other issues like #124124

**Comment by albertopoljak** [comment]
I get the general idea behind it, but the approach is terrible. Custom translations are now much harder, in some cases even impossible because there is a bug? feature? where code translations are ignored (especially terrible for the website/shop part, internal users can suck it down, but their customer will be confused). I have no idea how this even got into stable release,

**Comment by pedrobaeza** [comment]
I don't get why the /shop messages in code needs other translations apart from the PO ones.

**Comment by pedrobaeza** [comment]
I have also discouraged that "custom translations", both being done by customer itself or by my company. Standardization should apply here and search for a common term for all sectors. Sometimes is only habit to call things in another way.

**Comment by david-fleischmann** [comment]
@pedrobaeza 
How would you handle translations here then:
addons/l10n_din5008_sale 

This is very very custom how end customers would name their business documents. Why shouldn't it be possible to change that, this makes totally no sense.

**Comment by pedrobaeza** [comment]
I don't see how you need to change the translation of `Order No.`, `Incoterm` or similar texts that are inside that module. That are universal names. And if one customer wants to (because they are very stubborn, not by necessity) change that term, ask them to pay the development of an extension module extending `_compute_l10n_din5008_template_data` to replace `Order No.` by whatever weird they want to put. But if I find one of these cases, I usually simplify it: "It's not possible". And the world has continued spinning...
