### ISSUE TITLE
[8.0] Partial reconciliation and automatic reconciliation

### ISSUE THREAD

**Issue by chrisdec** [odoo/odoo#12589]
Impacted versions: 8.0

Steps to reproduce:
------------------------------

1.Open runbot

2.Create a customer invoice 

- Customer : Asustek 
- Taxe : None
- Total : 200

3.Validate the customer invoice 

4.Create a refund 

- Click on **Refund Invoice** 
- Refund Method : Create a draft refund 
- Reason : Test 

5.Change price of the refund from 200 to 50

6.Validate the refund 

7.Make a partial reconciliation between the customer invoice of 200 and the refund of 50

- (journal items > Reconcile entries > Partial Reconcile) 
- The balance of your customer invoice is 150

8.Create a bank statement 

9.Register a bank statement line for Asustek of 200

- Date : today
- Communication : : test 
- Partner : Asustek 
- Amount : 200

10.Save the bank statement and click on "reconcile" 

- **Delete the proposed line** and choose keep open

11.Run automatic reconciliation 

- Account : 110200 Debtors
- Power : 3

Expected behavior 
-------------------------

The payment of 200, the customer invoice and the refund are partially reconciled together 

**OR** 

Nothing happened : The customer invoice and the refund are still partially reconciled and the payment is not 

The partial reconciliation is important and can't be deleted. 

Current Behavior : 
-----------------

The customer invoice is paid and fully reconciled with the payment of 200
The reconciliation between refund and invoice doesn't exist anymore.
On the journal item linked to the refund, you have the number of Partial Reconciliation but this partial reconciliation doesn't exist anymore
 
Screen Shot 
----------

No link of payment on the refund : 

![github](https://cloud.githubusercontent.com/assets/8087371/16380088/3f39dacc-3c75-11e6-8aab-d7a9c67a605e.png)

BUT Number of partial reconciliation on journal item linked to the refund: 

![github2](https://cloud.githubusercontent.com/assets/8087371/16380114/682d3e42-3c75-11e6-820f-35a8b7a2e80f.png)

Customer invoice fully reconciled with the payment (and no information about the refund) : 

![github3](https://cloud.githubusercontent.com/assets/8087371/16380155/9dae9660-3c75-11e6-95fe-085fce691bbe.png)

**Comment by Yenthe666** [comment]
@qdp-odoo this looks like one for you. :gem:

**Comment by nim-odoo** [comment]
Hello,

I tried with fresh data (new customer, new account), and I don't face the issue you mention. See https://youtu.be/cCouWGRRKvA

Is there something I am missing?

**Comment by chrisdec** [comment]
Hello, 

Yes you are missing something. You use a new customer account "New New" on your invoice and refund but when you choose "keep open" on the bank statement, the journal item for the payment is on the general account "400000 client".  See your video at 3:25

No risk that the automatic reconciliation reconciles the invoice and the payment as they are not on the same customer account. 

If you want to use a new account, you can't choose "keep open" in the bank statement reconciliation screen. Instead, choose to put the payment of 200 on your new account. 

Thanks in advance :)

**Comment by nim-odoo** [comment]
Thanks for the explanation, I could reproduce the issue.

Regarding your use case, existing partial reconciliations are simply not taken into account when running the automatic reconciliation. The logic applied is to find the simplest matching combination of account move lines. In the case you describe, matching an invoice with a payment of the same amount is obviously simpler than matching an invoice, a refund and a part of the payment.

Therefore, we don't consider this behavior as a bug, although we agree that this might not be an expected behavior. If this functionality is really mandatory for you, a simple solution would be to add the condition `AND reconcile_partial_id IS NULL` is the method `reconcile` https://github.com/odoo/odoo/blob/8.0/addons/account/wizard/account_automatic_reconcile.py#L143

For example: https://gist.github.com/nim-odoo/4b99e1d16a30cd50a95c08ae60674a80
This will exclude the partially reconciled account move lines from the automatic reconciliation process. Therefore, you will get the expected behavior you described: "Nothing happened : The customer invoice and the refund are still partially reconciled and the payment is not"

**Comment by chrisdec** [comment]
Hello Nicolas, 

I’m sorry to insist but I don’t understand why you don’t consider it as a bug. You say exactly “we agree that this might not be an expected behavior”. A bug is not only an error message; it can also be a bad behavior. 

The customer who reports this problem is an accountant. You can easily imagine that it’s not possible for him to work with such functionalities. Whatever he decided to partially reconcile, Odoo doesn’t take it into account and simply cancels his reconciliation without notifying the accountant.  Moreover, he doesn’t see the reconciliation has been cancelled as the number of the partial reconciliation is always on the journal item linked to the refund.  

So, could you please reconsider your decision about it? 

@qdp-odoo  what do you think about it? 

Thanks a lot in advance,

**Comment by nim-odoo** [comment]
Hello,

The decision of closing the issue has been taken after a discussion with @qdp-odoo .

As I said, this **might** not be an expected behavior when you use the automatic reconciliation feature. However, this is the behavior that Odoo has been applying since 2010 (date of the [initial commit](https://github.com/odoo/odoo/commit/de7730c739ee70c22a712ed799ca94f2fe609f10)). This was introduced after the partial reconciliation concept, [introduced in 2008](https://github.com/odoo/odoo/commit/cef59b22d5887506af49a2da5515f96788f865e1). Therefore, the automatic reconciliation has never taken into account the existing partial reconciliations.

Changing a behavior which has been introduced 6 years ago in a stable version is therefore not likely to be accepted. I understand that this does not work the way you would expect it to, so I am still suggesting that you apply a local patch on your installation.
