### ISSUE TITLE
Event_sale module: Double attendee ticket registration issue after attending event

### ISSUE THREAD

**Issue by PieterPaulussen** [odoo/odoo#12583]
Impacted versions: v9.0 && v9.0e

Steps to reproduce:
Please see video for steps to reproduce.
https://youtu.be/sVCyPmn72nY

Current behaviour: When a attendee registration is completed and a sale order is linked to the attendee record, there is a new attend record created with the status 'attended'. 

Expected behaviour: The original attendee registration should be updated, not create a new one.

**Comment by Yenthe666** [comment]
@mart-e could you assign somebody on this one?
On a sidenote: the events flow is really tedious and confusing, you need to do way to many double clicks / entries to register somebody.

**Comment by treviser** [comment]
@Yenthe666 Well said. And too much unnecessary communications to the attendee. And accessory products do not work.

**Comment by JKE-be** [comment]
About the initial issue and not the refactoring discuss...
Have you tested : 
![image](https://cloud.githubusercontent.com/assets/4848797/16374373/6e170604-3c56-11e6-8895-9894adce4a94.png)

**Comment by PieterPaulussen** [comment]
Just tested it now. The 'Skip' function does not change anything. Still 2 attendee registrations get created.

**Comment by mart-e** [comment]
Hello,

This is because you are not making the flow by the expected flow. If you wish to use sale orders to register attendee, you should create sale orders directly and not manually create an attendee that is linked to a sale order you just create.

Let me explain why you got two attendees. This is what happens:
1. hit create button on attendee and fill the contact and event info
=> record not created yet as it hasn't been saved yet (if I close the window, nothing is saved yet)
2. open a new sale order pop up and add a line for the event
=> neither the sale order nor the event are saved yet
3. confirm sale order, the registration wizard opens
=> the sale order is saved (and confirmed) but not the event yet
4. confirm the event registration in the wizard
=> the attendee is not found in the database (not saved yet) so the wizard create a new one
5. close all popup and confirm the registration in the first attendee form
=> finally saving the event registration

So ironically it is not the sale order that creates the second registration but the create form you opened is the first step.

To avoid this, you need either to make sure to save your attendee before linking it to a sale order or (better) to create a sale order directly. The sale order is not required by the way.

**Comment by PieterPaulussen** [comment]
Then again it's strange that this flow does work correctly when a person registers through the website.
The current flow is very open and prone to errors then. Shouldn't this be more streamlined into a monkey proof system so attendees can be registered through the back end correctly? The amount of required fields practically demands that you use the workflow as suggested in the movie...

**Comment by mart-e** [comment]
@PieterPaulussen why is it strange? I explained what was wrong in the way you register the attendees. The point is that:
- if you only use event, adding attendees is very simple, only specify the contact
- if you only use event & sale, adding attendees is done via sale order
- if you only use event & website, adding attendees is done via the website
- if you only use event & sale & website, adding attendees is done via the ecommerce

Registering attendees manually when you are not in the first scenario is indeed error prone but it's not the intended flow. It's still possible to edit these (e.g. to correct a wrong registration) but a bit "you are on your own" kind of scenario when you try to reproduce the full flow from backend.

**Comment by Yenthe666** [comment]
@mart-e as stated by @PieterPaulussen it does work fine from the website, so it is strange (from a user/usability perspective) that it doesn't work the same from the back-end. I know it technically works different but that is no concern to the end user.
So, what if you want to create an event, add an attendee **and** want to create a sale order? I understand your statement about having to first save the record but in all seriousness, that is not something that you can require from all end users. It is not like it is documented somewhere or that it follows the default behaviour and rules from Odoo. Couldn't we atleast create a workaround or a warning dialog? 
Alright, it is not the default way but it is a way that works and in all fairness it should work or be handled then, even if it is just a warning dialog.

**Comment by mart-e** [comment]
Would putting the sale order field on the attendee readonly make you feel better about this?
We are not going to change the way odoo works but we can improve the usability to make it clear that this flow is not supported.

**Comment by Yenthe666** [comment]
@mart-e Making the sale order field a readonly untill you've saved the record? After saving the record you can then add the sale order so you can complete the flow (without the issue of two attendees).
It would avoid us from having this problem.

**Comment by mart-e** [comment]
No it's making it readonly or not. There is no `attrs` 'until it's saved' in Odoo (or just some hacky computed field maybe).
So this is why I said I don't like the idea of making it readonly. It's restricting an advanced flow, the usual usability vs features.

**Comment by Yenthe666** [comment]
Hmm I don't think that a full `readonly` is a good idea, especially not in an active version. It would confuse / bother too many people for this benefit.
Is there any rewrite planned for V10 of this module? I'd like to see this changed in the master.
