### ISSUE TITLE
[9.0] Website cart disappearing on homepage

### ISSUE THREAD

**Issue by BzJB** [odoo/odoo#12626]
Impacted versions: 9.0

Steps to reproduce:
1. Create a demo odoo 9 enterprise database with demonstration data.
2. Install website_sale.
3. Go to the website as the public user.
4. Add an item to the cart.
5. Then go back to the homepage.

Current behavior:
When you go back to the homepage the cart isn't visible but when you go to the shop it is.

Expected behavior:
The cart should be visible throughout the site.

**Comment by JKE-be** [comment]
Cannot reproduce...
Can you confirm that you have the bug on runbot ?  http://runbot.odoo.com/runbot/7/9.0 ?

**Comment by BzJB** [comment]
I was able to to reproduce on run bot.
I went to the website, logged out.
Then went to the shop, selected an item.
Clicked Add to Cart, then Proceed to Checkout.
Then when I click Home from the checkout the cart disappears from the menu.

**Comment by lukebranch** [comment]
@BzJB ,

I've just tried this on the runbot's and i'm not able to reproduce the error either.

Would you mind giving more information about your environment (ie. what browser and version you're using, what OS, etc.), and perhaps post a link to an animated screengrab using something like licecap:

http://www.cockos.com/licecap/

It is often useful to submit these reports with an animated screengrab so that others reviewing the thread can see what you're seeing and try to reproduce the issue on their end.

**Comment by BzJB** [comment]
I've recreated the issue but this time instead of not displaying the cart it displays the quantity of the previous order. I did this by creating and order then clearing the cart and creating a new order.

![cart](https://cloud.githubusercontent.com/assets/20208782/16483350/eee134c4-3eab-11e6-8465-fe47ceba6fa4.gif)

**Comment by JKE-be** [comment]
Are you sure that you don't have 2 tab open on the same chrome session ?

**Comment by BzJB** [comment]
Yes, this was the only session open.

**Comment by BzMB** [comment]
Hi,
I'm a colleague of BzJB.

Do we have any news on that issue?
Anyone with the same issue?

Thanks.

**Comment by JKE-be** [comment]
Nobody can reproduce it except you.
So their are probably missing information in the how to reproduce :(
If you have a new idea to reproduce don't hesitate to ping me, and I will reopen the issue (and fix it if needed).
