### ISSUE TITLE
not possible to allocate leaves by employee tags

### ISSUE THREAD

**Issue by bene1505** [odoo/odoo#12620]
Impacted versions:9.0

What are the steps to reproduce your issue?
Go to leaves, Leaves to approve/Leaves
create a new Department leave

What is the current behavior that you observe?

I can't select the mode "By employee tag" because in the code, I should be in the draft stage;

```xml
<field name="holiday_type" 
    on_change="onchange_type(holiday_type)" 
    attrs="{'readonly':[('type', '=', 'remove'),('state','!=','draft')]}" />
```
but I'm directly into 'To approve' stage.

What would be your expected behavior in this case?

I should be able to select the "By employee tag" option so that I would be able to allocate official leaves to several employees at once. 

Video/Screenshot link (optional):

![screen shot 2016-06-29 at 15 16 22](https://cloud.githubusercontent.com/assets/12964307/16453707/2a02a644-3e0e-11e6-9d1d-ea15f097498c.png)

**Comment by mart-e** [comment]
Hello,

Thanks for the report but actually it is wanted.
When somebody creates a leave request, most of the time it's because he want to submit it. To avoid an unnecessary click (and prevent sad scenarios where the employee forgot to press submit and got no holidays), by default it's already in confirm state.
If you do not want to submit it yet, you can reset to draft state.
The mode is a quite technical field and should definitely not be changed once an holiday has been submitted. But again, if you want to change it (which should happens less often than submitting employee request), you can reset it to draft first.
