### ISSUE TITLE
Re-introduce version tagging

### ISSUE THREAD

**Issue by x-direct-group** [odoo/odoo#12867]
Hello,
I am trying to find out how often I need to update Odoo in production. The most recent stable branch 9.0, which I am tracking, is changing on a daily basis. When looking at the commits, I have a hard time figuring out if they are mere enhancements (maybe changing APIs?) or needed (business-/security-critical) bug-fixes.
I am aware that all commits to this branch first have to pass an automated testing suite, which surely mitigates many possible regressions.
I would really appreciate if upstream gave me some hint as to which commits to regard stable, by version tagging.

Impacted versions:
branch 9.0
Steps to reproduce:
Check releases under <https://github.com/odoo/odoo/releases> .
Current behavior:
The last release was tagged on 18 Sep 2014 as 8.0.0 
Expected behavior:
I can watch the release tags to see when it makes sense to pull a new version of Odoo. And the release tags reflect the actual version of the software (e.g., the version the software itself tells it is in) . I would love to see something like here: <https://github.com/OpenVPN/openvpn/releases> 

Bye,
Simon

**Comment by mart-e** [comment]
Hello,

Actually the use of tagging introduced some problems. We maintain 3 stable versions in parallel (so currently 7, 8 and 9.0) and keep making important fixes in these and it is important that people always get an up to date version.
When going to the release page, you will fetch the package at the revision of the tag (obviously) which will quickly become outdated. If you download the 8.0.0 release, you will miss some important security patches and various fixes.

The option to prevent outdated versions would to release a 8.0.0, 8.0.1, 8.0.2, 8.0.3,... but, even if we made a tag only once a week (and we still have commits almost every day in 8.0), we would already be at 8.0.96 today! We do not wish to do that either and get an endless list of versions.

Instead of relying on Github release system, we ask people to use the github branch and we published packages of the nightly builds on https://nightly.odoo.com/
Sorry but maintaining also the releases on github would be too much work.

**Comment by Foosec** [comment]
Sorry for reviving this but not having any kind of automated tagging is not stable, i may pull 17.0 for example and be met with a build that doesn't pass tests!
You could implement automatic tagging to latest/stable via a CI pipeline easily and not have to manually tag minor versions. Then at least we would know when pulling that what we are pulling actually has passed tests and is not a broken build!

**Comment by mart-e** [comment]
@Foosec stable version should not lead to broken build, it's not supposed to contains changes of behaviour. We continiously merge bugfixes in the stable version as well as update of translations. You can simply stick to a specific revision if you don't one those ones but there is no such thing as a minor version.

**Comment by Foosec** [comment]
![image](https://github.com/odoo/odoo/assets/31885466/20005ba8-99ea-4b83-a4c3-1bcd532f6d00)
If i understand correctly, those tests show 17.0 failing, if someone had pulled at that time they would have had a broken build, no? If tagging and release management is too much, perhaps CI rules that forbid merging to 17.0 until the test pipeline passes?

**Comment by mart-e** [comment]
Not exactly, our CI tool already forbids to merge a commit that is failing. I am not sure where this screenshot was taken for but you can click on the build and see why it's red. Often, that will be a false positive due to some times out in javascript or something like this. We also have some indeterminist (but real) bugs from time to time that we detect later but our system won't merge a commit that makes our tests fail.
