### ISSUE TITLE
[8.0] website_sale_delivery ecommerce delivery price is shown without tax

### ISSUE THREAD

**Issue by paolovalier** [odoo/odoo#12872]
Impacted versions: 8.0, tested on runbot

Steps to reproduce: set the tax for the product "delivery" as included in the price

Current behavior: on the cart and checkout pages of the ecommerce you see the price of delivery without tax

Expected behavior: delivery price should be shown with tax included

**Comment by JKE-be** [comment]
Hello,

It is the default behavior in v8, not really an issue.

Base amount = 610 € (600€ ipad, 10€ delivery)
Tax = 2,1 € (21% of 10€ delivery)
Total = 612,1 €

![image](https://cloud.githubusercontent.com/assets/4848797/17099037/16430baa-5266-11e6-9499-ad582280fd02.png)

**Comment by paolovalier** [comment]
thanks @JKE-be for the answer
ok, when taxes are included in price the products' price isn't splitted (price and tax), delivery is. a bit strange,  I mean an uneven behavior, but that's just my humble opinion. thanks, bye

**Comment by eLBati** [comment]
Hello @JKE-be 
please see the sale order below

![screenshot from 2016-09-01 10-01-53](https://cloud.githubusercontent.com/assets/1033131/18159917/2595c48e-702b-11e6-9cc2-fec84e09c4c0.png)

![screenshot from 2016-09-01 10-02-16](https://cloud.githubusercontent.com/assets/1033131/18159932/34e2ccd4-702b-11e6-80a3-d9d82ab1c6b0.png)

I configured both **iPad Mini** and **delivery** with VAT 22% included in price.

Expected behaviour: in online shopping cart, **delivery** should be **10**

**Comment by treviser** [comment]
I do agree, this is a bug.
