### ISSUE TITLE
incoming email thread issue

### ISSUE THREAD

**Issue by fausthuang** [odoo/odoo#12907]
Impacted versions: V9.0 enterprise

Steps to reproduce: when a customer send a mail to odoo, (we already set incoming mail server and server action to convert the mail as a issue.) it will create a issue in project. and then odoo user will reply it in this issue with "new message" . once the customer receive the feedback email from odoo, and he reply base on this mail again. it will create a new issue in odoo, but not in same message thread . it is weird.  sometime it is ok,will in same message thread.
my question is: what is the rule(s) in odoo, that the Odoosystem will recognize the exchange mail in same thread(id).

Current behavior:

Expected behavior:

Video/Screenshot link (optional):

**Comment by dbo-odoo** [comment]
Hello,

The system is not really supposed to work this way for project in Odoo 9.0.

Instead of creating issues from the 'incoming mail server' setting, you should set an alias on your project (in the project Settings, E-mail tab). You should remove the setting to create issue from your incoming mail server and set a meaningful email alias on your project (this has the advantage of being able to create issues in different projects easily).

You can see an explanation here: https://www.bringsvor.com/en_US/blog/our-blog-1/post/configuring-gmail-with-odoo-1 (this is not the official documentation).

Regards,

**Comment by dbo-odoo** [comment]
I will close this issue as this is more of a configuration problem than a real issue. If you still have questions regarding this, you can still reply however.
