### ISSUE TITLE
[master][bug]  portal access management wizard raised singleton error.

### ISSUE THREAD

**Issue by jeffery9** [odoo/odoo#12938]
Impacted versions:
master
10 alpha

Steps to reproduce:

open the customer eg. comptocamp
click more dropdown, and select portal access management, in the ppoup window, check `in portal ` option for the contacts, and then click button apply.

it should raise error like flowing 

>
>ValueError: Expected singleton: portal.wizard.user(4, 5, 6)

Current behavior:

Expected behavior:

no any error raised.

Video/Screenshot link (optional):

![image](https://cloud.githubusercontent.com/assets/1404460/17201923/2db7c5aa-54c8-11e6-932e-e43890047718.png)

**Comment by Yenthe666** [comment]
Hi @jeffery9,

Thanks a lot for your issue. At this point the master branch is worked on very heavily and it changes from day to day so at this point you don't really have to report these issues.
@mart-e am I right here? I believe I can just close this one.

Regards,
Yenthe

**Comment by mart-e** [comment]
Exactly, while the bug is indeed correct, please avoid making bug reports on the instable version (except maybe when it's in the "freeze" period before release of v10), master changes a lot, things get broken.

@jem-odoo the bug was introduced during the new API migration of portal (bad `ensure_one()` in the second method), could you take a look?
