### ISSUE TITLE
[Wishlist] Ability to translate / change labels in developer mode

### ISSUE THREAD

**Issue by Yenthe666** [odoo/odoo#12987]
Hi guys,

It would be great to have the ability to translate / change labels in views while you've got developer mode enabled.
At this point you can only translate or change labels from `Settings > Translations`, which works ok but it can be difficult to find terms that are used a lot in the system (such as `Price`).
Something along the lines of the website where you can select text and change it (but then also the ability to translate):
![image](https://cloud.githubusercontent.com/assets/6352350/17320960/6a6ea9d8-5896-11e6-98ce-3568bf8a84ea.png)

In the front-end (to build):
![image](https://cloud.githubusercontent.com/assets/6352350/17321457/fbabaf98-5898-11e6-97cd-314babceac66.png)

**Comment by Yenthe666** [comment]
@mart-e can I ask you for feedback / what you think about this? Can I label this wishlist?

**Comment by mart-e** [comment]
Look it's already there ! Well not in the web interface directly but it's already a pretty good tool to do so.
![screenshot from 2016-08-02 10-20-20](https://cloud.githubusercontent.com/assets/564822/17321937/4d0ab6d4-589b-11e6-8a03-da73a614aea1.png)

**Comment by Yenthe666** [comment]
@mart-e well yes but it is still not very clear and besides, look at the result when clicking on it:
![image](https://cloud.githubusercontent.com/assets/6352350/17322543/32410558-589e-11e6-92dd-52f850e975d7.png)

It would be great if you could do it inside the view :+1:

**Comment by mart-e** [comment]
@Yenthe666 the empty list is because you have no language loaded ;-)

Doing it inside the view could be nice but it is not the priority. The priority is to allow an easy customisation of the view (think Odoo Studio) and then make it easier to translate but for now I think this menu is enough (maybe we can rename it, "Technical translations" is not clear).

Closing as developing a new interface in backend to translate is not something we want to do (at least not in the state of the backend web client).
