### ISSUE TITLE
Duplicate registries loaded when spaces are added to the 'db' URL parameter

### ISSUE THREAD

**Issue by jsollasvaara** [odoo/odoo#13078]
Impacted versions:
This bug is present at least in the latest version of Odoo 8.0 branch (commit 7f86272b94b26b68aa1be3933d042efd9fd53008).

Steps to reproduce:
Given your environment has a database called 'test'.

When you browse to your environment: http://localhost:8069/web/login/?db=test
Your server will log loading modules like this:
2016-08-01 09:34:40,874 3919 INFO test openerp.modules.loading: loading 1 modules...

If you add spaces to the db parameter like this: http://localhost:8069/web/login/?db=test%20
Your server will log loading modules for this 'test ' database:
2016-08-01 09:34:40,874 3919 INFO test  openerp.modules.loading: loading 1 modules...

And the same with multiple spaces: http://localhost:8069/web/login/?db=test%20%20%20%20%20
2016-08-01 09:34:40,874 3919 INFO test      openerp.modules.loading: loading 1 modules...

Current behavior:
The problems cased by this bug are:
1) Race conditions between the background jobs, which in most cases are not thread safe.
2) Files, such as email attachments, might get stored in a wrong file storage folder.

What happens is that Odoo will start multiple instances of background jobs, one for each "database".
It also creates multiple folders under $HOME/.local/share/Odoo/filestore, one for each "database", as needed.

We discovered this bug while investigating why Odoo could not locate some email attachment files that were fetched by the 'fetchmail' addon.
We found out that Odoo had stored some of the attachments into:
"$HOME/.local/share/Odoo/filestore/production" folder.
And some of the attachments into:
"$HOME/.local/share/Odoo/filestore/production\ " folder.

I would label this bug as CRITICAL because of the problems mentioned above and because:
- It can be exploited maliciously without login. This only requires access to the Odoo Login page.
- The root cause is hard to debug.

A quick fix for this issue is to restart the Odoo service.
Currently the only way to avoid this from happening is to block access to Odoo server from the Internet and ensuring that your users won't use links with spaces in the db parameter.

**Comment by dreispt** [comment]
The issue description is not clear to me. 
You state that the problem is on background jobs, but AFAICT these are not related with the URLs used by the clients. So I don't see the connection between the two descriptions.

Are you using the `database` (`-d`in the command line) and `dbfilter` conf settings?

**Comment by jsollasvaara** [comment]
Add spaces to the DB parameter in the URL and take a look at the logs.
What you will see is that Odoo will reload all the modules for this "new environment".
It also starts new backgroud jobs for this "new environment".

**Comment by dreispt** [comment]
Using dbfilter is a best practice and probably avoids that.

**Comment by jsollasvaara** [comment]
Thanks,
I finally had time to test the dbfilter and this issue can be avoided by using the dbfilter configuration.

However, the **db** URL parameter is not handled properly and should be fixed.

**Comment by dreispt** [comment]
@odony The report states that this could be a security issue.

**Comment by odony** [comment]
This happens because in 8.0 we still use psycopg2's DSN strings, which are whitespace separated and thus ignore extra spaces. 
This was fixed in 9.0 by #9690, and merged a while ago at 26a8b438b6cc94241354af9fe218d8c592e17cfa

Stretching it, malicious users could indeed annoy the admin by causing cron jobs to run in parallel and with the wrong filestore data directory. That seems to be the extent of the mishap that can be caused, though, a sort of mini denial of service.
As @dreispt mentioned, configuring a proper db_filter is trivial workaround and a key part of deploying Odoo - it's even the first item mentioned in the [Deployment documentation](https://www.odoo.com/documentation/9.0/setup/deploy.html).

Backporting #9690 is quite invasive, and using psycopg2's internal `_escape_param` is a dangerous alternative (in the master branch it recently moved). A cheap workaround could be this patch: 74c5d05206389c4ee2c72edf1be5b6d49a3f1634, stripping whitespace in the URL parameter directly instead.
@jsollasvaara could you try the patch? Thanks!

**Comment by jsollasvaara** [comment]
The patch seems to work like a charm.
