### ISSUE TITLE
MRP products to consume doesnt save

### ISSUE THREAD

**Issue by ghost** [odoo/odoo#13227]
Impacted versions: 9.0c  & 9.0e

Steps to reproduce: 
1. MRP and Inventory modules must be installed.
2. Inventory->Configuration->Settings->Multi locations must be set to -"Manage several locations per warehouse" and set back to "Do not record internal moves within a warehouse". 
3. Manufacturing -> Create new manufacturing order -> Go to "Products to Consume" and add an item.
4. In the "add new item" form, fill in product and description. And try to either "save & close" or "save & new". You get no response, no errors. The only that works is "discard". Same issue on both versions.

Current behavior:

Expected behavior:

The newly added product should appear on the products to consume list in the manufacturing order.

Video/Screenshot link (optional):

![9c](https://cloud.githubusercontent.com/assets/1849386/17811752/d974f3de-662c-11e6-95d0-ce2b93a3e7e4.jpg)
![9e](https://cloud.githubusercontent.com/assets/1849386/17811757/dba6614c-662c-11e6-8e4a-e2dba9b34dce.jpg)

**Comment by bistaray** [comment]
I was able to replicate on http://168536-9-0-da0669.runbot8.odoo.com/ following these steps:

1. Navigate to Inventory->Configuration->Settings->Multi locations, change "Manage several locations per warehouse" back to "Do not record internal moves within a warehouse"
2. Navigate to MRP.
3. Navigate to Manufacturing -> Manufacturing Orders.
4. Click CREATE.
5. Choose a product (ie: [C-Case] Computer Case)
6. Under PRODUCTS TO CONSUME, click ADD AN ITEM.
7. Enter product.

Unable to click SAVE & CLOSE or SAVE & NEW.  I wonder if this is because the source and destination location of the move need to be added?  (they do when "Manage several locations per warehouse" is set)

**Comment by pedrobaeza** [comment]
@bistaray Is this still happening?

**Comment by Yenthe666** [comment]
Hi @ghost,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 9 is no longer supported as Odoo only supports three versions (10.0, 11.0, 12.0 at the moment).
If you can still reproduce this issue on Odoo 10, Odoo 11 or Odoo 12 we encourage you to create a new bug report.

Regards,
Yenthe
