### ISSUE TITLE
[Question] Versioning on github and docker hub

### ISSUE THREAD

**Issue by fdelayen** [odoo/odoo#13369]
Impacted versions: 9

Project manager of a company developing and maintaining modules for Odoo for years, I am facing more and more problems integrating our modules with Odoo for those reasons :
- No version tags : We are always on branch 9.0 without 9.0.1, 9.0.2, etc.
- Changes made daily sometimes breaks entire classes and models, because changes are too big and we dont have any change logs to know if we are affected or not.
- On docker hub there is only one version : 9, 9.0, latest (the same thing)

Why are not you using tags and multiple versions on docker and github ? That would help everybody understand and allow testing on docker hub images to keep easily our modules up and working with latest versions of Odoo.

For now, when a new version is out on docker hub we cannot use easily older versions until we are sure our modules are still working (and often that is not the case).

**Comment by mart-e** [comment]
> No version tags : We are always on branch 9.0 without 9.0.1, 9.0.2, etc.
Yes, we maintain stable branches during ~2 years and make plenty of fixes in these branch (several commits every day). Instead of making hundreds of tags, we always ask people to use the latest revision.

> Changes made daily sometimes breaks entire classes and models, because changes are too big and we dont have any change logs to know if we are affected or not.
It should not be the case. We have [stability guidelines](https://github.com/odoo/odoo/wiki/Contributing#what-does-stable-mean) to avoid breaking such things. If it does happen, you can complain to the one who made this commit :)

> On docker hub there is only one version : 9, 9.0, latest (the same thing)
The docker process to make a new update is manual (making a PR on their repo) so you get way less frequent image of docker. If you want to have the latest image with latest fixes, I don't recommend the docker image.

The point is that a stable version should not change after the release. No new features or important changes. Well, usually it does happen a bit after the release (when things get broken) but it should not after.
What kind of incompatible changes are you referring to?

**Comment by fdelayen** [comment]
Okay, thanks for those informations. :+1: 

It did happen a few times a while ago so I cannot point you to the exact commit, but it was a function (an action triggered by a button) we were overloading in some case that was rewritten entirely and was not doing the same at all anymore.
So until we tested everything again, we could not have noticed the change and the bug in our code.

(We are on the latest docker image available)

May be the best we can do is build our own image regularly based on your docker script and test that our modules are still fine after each update.

I was asking because when we thought about updating, the first issue I've seen was #13362 and... that was kind of not encouraging :cry:

**Comment by mart-e** [comment]
A change of behaviour of a method is highly discourage if it was not producing an error. I don't say that it does not happen from time to time but should not happen :)

And regarding the issue you are mentioning, don't worry, if the database creation was broken in 9.0, we would notice it faster than 6 days :wink: (so probably configuration issue)

I am closing the issue as no real bug but feel free to ping me or reopen an issue in case of bad commit.

**Comment by fdelayen** [comment]
Ok, thank you for answering this ! :smiley:

**Comment by fdelayen** [comment]
Small question before opening a new issue...
Have you changed the behavior of child_of domain for example ?
Looks like now it's not taking the parent in. Breaking between February version and July one !
Stock addon impacted too.

**Comment by mart-e** [comment]
We need to investigate but not that I am aware
