### ISSUE TITLE
Not translated bug:ValidateError = 验证错误

### ISSUE THREAD

**Issue by leangjia** [odoo/odoo#13389]
Impacted versions:

Steps to reproduce:odoo8.0-版本 8.0-20160826(ubuntu 14.04 server+postgres 9.3)

Current behavior: 
1.[Sales]->[Create]->new Products,input [EAN13 Barcode] =201609051332.
2.ValidateError:

I find the word [ValidateError] in trasefix.com/odoo/odoo-8 result is [ValidateError = 验证错误] it is right.

Is it a bug？

@mart-e

**Comment by leangjia** [comment]
URL：https://www.transifex.com/odoo/odoo-8/translate/#zh_CN/$/49570785?q=ValidateError

**Comment by mart-e** [comment]
Hello,

Actually the translation you are showing is for the `document` module, the message you are showing is from the `product` module, so this is not the message.

The problem is that the generic validation error will always raise a "ValidateError" message (as you will get a MissingError when a record no longer exists,...). and these are not translatable.
We have changed that in 9.0 to put proper error message (it will now be "Validation Error", a bit more friendly) but unfortunately we can not change that in 8.0, some people may rely on this exact error message (like [we do here](https://github.com/odoo/odoo/blob/75a196972e9e1056c8ab9c299ddfc8e2eaafd812/addons/hr_attendance/test/attendance_process.yml#L49))
So sorry but we will not change that in 8.0
