### ISSUE TITLE
Access error shows name of record (security restrictions)

### ISSUE THREAD

**Issue by jgebel** [odoo/odoo#134643]
Impacted versions:
tested for: 15.0 + 16.0 CE & EE
May impact other versions too.

Steps to reproduce:
With a user which is not in the group (Technical / Access to Private Addresses) open a private address.
(and therefore not have the record rule `res.partner.rule.private.group`)
To do so use e.g. the ID of the record and open it via the URL.

Current behavior:
In the Access Error which is raised the record which is tried to access is listed with the (display) name of the record.
The Information can only be seen in Debug Mode with user beeing in group `Extra Rights / Technical Features`.

Expected behavior:
The name of the record should not be shown. If you do not have access to a record you shouldn't be able to access any information which would be relevant for data protection (personal data).
The ID itself may still be ok, but the name is probably a risk.
Even when the user has Access to the technical features group he might not be allowed to see the restricted data.
Maybe there should at least be a configuration to change the amount of information given in the error.

Video/Screenshot link (optional):
![image](https://github.com/odoo/odoo/assets/69352860/739ee1b7-ebfd-4ad3-ae99-0556b141d239)

Support ticket number submitted via odoo.com/help (optional):

technical Informations:
- in the `ir.rule` model of the `base` module the method `_make_access_error` uses the `display_name` of the record to provide informations to the error
- this was added in commit: `6461a0f58cc79d16a16e3519009463c0abb27332`
("[FIX] core, base: rules detail on access error")
  - before it was just telling the model but no information about the records

**Comment by vava-odoo** [comment]
Hi @jgebel 
I reported it internally and the decision was to keep it as is because, among other things, this is only shown to internal users, in debug mode, and names are not meant to hold sensible data as they can be displayed in other ways (e.g. a m2o field on a record you have access to pointing to a record you do not have access to will still display the forbidden record's name). Also, this makes it much easier to solve issues related to access rights.
Cheers
