### ISSUE TITLE
[8.0] Bad currency conversion for taxes on invoices 

### ISSUE THREAD

**Issue by adrienpeiffer** [odoo/odoo#13473]
Impacted versions:

At least 8.0

Steps to reproduce:

see https://youtu.be/GNQeLj-P6Yg

Current behavior:

Currently if you validate an invoice after the initial conversion rate has changed
(if you wait a day or more before validating the invoice). The tax amount and the credit/debit amount is not computed from the same rate.

Expected behavior:

The tax amount and the credit/debit amount must be computed from the same rate.

Video/Screenshot link (optional):

https://youtu.be/GNQeLj-P6Yg

**Comment by adrienpeiffer** [comment]
OPW 688517

**Comment by nim-odoo** [comment]
Hello,

The issue in your video comes from the fact that after changing the invoice date, you should click again on "update" to trigger a recomputation of the taxes at the corrected date. We cannot trigger this automatically, otherwise we would erase the potential manual modifications.

So it's not a bug in itself, and we cannot solve it without risking to break the workflow of existing users.

**Comment by adrienpeiffer** [comment]
Hi Nicolas,

The manual modification of the invoice date in the video is just to simulate that the invoice was validated at a different time compared at the time that the invoice is created.
So if today, I create an invoice with currency and if I'll validate this invoice tomorrow (Probably with a currency rate change) or if you change the currency rate on the same day between creation and validation, the currency rate to compute the tax amount will be wrong.
This one is responsible for several production issues for tax reporting for the fiscal administration.
I hope you will reconsider this one.

Thanks in advance,

Adrien

**Comment by nim-odoo** [comment]
Ok, I'll have a look at it again. Although, what you say is surprising since at the move creation, the tax lines are not recomputed, but fetched from the previous calculation (i.e when you clock on "update"):
https://github.com/odoo/odoo/blob/8.0/addons/account/account_invoice.py#L838
https://github.com/odoo/odoo/blob/8.0/addons/account/account_invoice.py#L1616

**Comment by nim-odoo** [comment]
OK, I got it: https://drive.google.com/file/d/0BwqtJFE-javCQmFqZ3NKQ2pqb1E/view?usp=sharing
It occurs when you validate the invoice, but the invoice date is not set. In this case, it will automatically be set to today. It implies that:
- the account invoice line linked to the product is recomputed with the invoice date (i.e, today)
- the account invoice line linked to the tax is not recomputed (see previous comment)
I'll see what can be done.
