### ISSUE TITLE
Attribute Values showing as blank when added if they have HTML Color Index

### ISSUE THREAD

**Issue by SPhu** [odoo/odoo#13506]
Impacted versions:
9e

Steps to reproduce:

Add a new product
Go to Variants tab
Add attribute Color 
Add attribute values Red, Black, White

Current behavior:

Black and White aren't showing when the field is in edit mode. When I click save, it saves them, but when I click Edit again and click on the row to edit the values, the black and white disappear again. 

Expected behavior:

the attribute should be visible in edit mode regardless of color value

Video/Screenshot link (optional):
https://docs.google.com/document/d/1f36xEPP4Drrp3rKFEgUl3Tl9ZWDvEkCy_DyFPTFcmOM/view
https://drive.google.com/file/d/0BwIMuTs77kNBSHpNR25RUUZCdnc/view

**Comment by Yenthe666** [comment]
Hi @SPhu,

Thanks a lot for your bug report!
This issue has actually been fixed in the meanwhile:
![image](https://user-images.githubusercontent.com/6352350/36159440-019ba9b2-10df-11e8-83c5-056b963d28a1.png)

If you still face this issue then please update your Odoo instance in order to fix this.

Regards,
Yenthe
