### ISSUE TITLE
[9.0] account_tax_cash_basis: Journal Entry with movements that are not from taxes

### ISSUE THREAD

**Issue by luistorresm** [odoo/odoo#13543]
Impacted versions:
9.0 with the next SHA e424a9a938749d26adfa4eb4fca830a7c7f8944e

Steps to reproduce:
1.- Configure in accounting settings the Tax Cash Basis Journal.
2.- Configure an Sales  TAX as "Use Cash Basis" and set the account.
3.- Generate a new Sale Invoice, to any customer, and in the line set the TAX configured in the step 2.
4.- Register the invoice payment.

Current behavior:
The Journal Entry generated to the TAX movements generate movements that are not from TAX. 
![iep 2016 0006 odoo](https://cloud.githubusercontent.com/assets/7606656/18685304/0ed8af38-7f3d-11e6-9439-c7bf9435a742.png)

Expected behavior:
That only generate the movements to TAX on invoice.
![iep 2016 0005 odoo](https://cloud.githubusercontent.com/assets/7606656/18685277/f87a5778-7f3c-11e6-9ad4-cf37402137d1.png)

Video/Screenshot link (optional):
[
![untitled screencast youtube](https://cloud.githubusercontent.com/assets/7606656/18685389/6c23a58a-7f3d-11e6-9bc0-64d3d04b7158.png)
](https://youtu.be/tvZCku3S0sQ)

**Comment by qdp-odoo** [comment]
Hello

this behavior is the intended one. Indeed, those 2 extra lines don't have any impact on the accounting since they have a similar value for credit, debit and account BUT they are needed in order to be able to report the base amount of the operation **at the payment date** in the VAT report. 

That's is an inconsistency that has been solved lately.

I'm closing the bug report,
Thanks for the contribution
