### ISSUE TITLE
[8.0][9.0][IMP] Critical indexes missing in sale orders process

### ISSUE THREAD

**Issue by ke-real** [odoo/odoo#13556]
Impacted versions:
8.0 and 9.0

Steps to reproduce:
Import larger amount of orders (500k-700k) resulting in automatic payment and stock moves

Current behavior:
System starts to die slowly, every new order can take up to 20 sec of time to import

Indexes are poorly set on main Odoo tables - I guess there is no policy on what should be indexed.

Indexes should be added using Odoo ORM syntax into each suffering table (specifying select=true).
Here is an sql chunk for a quick start:

```
CREATE INDEX procurement_order_group_id_index ON procurement_order USING btree (group_id);
CREATE INDEX procurement_order_sale_line_id_index ON procurement_order USING btree (sale_line_id);
CREATE INDEX procurement_order_purchase_line_id_index ON procurement_order USING btree (purchase_line_id);
CREATE INDEX account_voucher_line_voucher_id_index ON account_voucher_line USING btree (voucher_id);
CREATE INDEX account_invoice_partner_id_index ON account_invoice USING btree (partner_id);
CREATE INDEX stock_move_procurement_id_index ON stock_move USING btree (procurement_id);
CREATE INDEX stock_picking_group_id_index ON stock_picking USING btree (group_id);
CREATE INDEX stock_move_operation_link_move_id_index ON stock_move_operation_link USING btree (move_id);
CREATE INDEX stock_move_operation_link_operation_id_index ON stock_move_operation_link USING btree (operation_id);

```

Please consider adding these indexes.

To gain even more speed consider turning off workflow execution on every write (refer to #12660).

**Comment by Yenthe666** [comment]
@odony @xmo-odoo and @mart-e I'd love an official statement about this from you guys.

**Comment by odony** [comment]
The default indexes in Odoo are not meant to cover all use cases, because that's impossible. This is a task for every system administrator, based on actual measures on the real deployment.
The policy is that we try to add the most important indexes, and we don't mind adding more for common cases, but it's always a trade-off, as more indexes mean slower insert/update operations.

For example we can't blindly add indexes on each FK, as most of them are never used as query filters, and that would represent an enormous number of indexes to maintain (more disk activity, larger databases, slower inserts, etc.)

In order to determine whether those make a difference, would you mind sharing more information:
 - How long were your queries taking before creating those extra indexes (maybe you can show a few extracts of your query log)? I mean the timing of specific SQL queries, not a global time for an import. 
 - How long are the same queries taking with the indexes now?
 - Do you perhaps have some sample import data or a database dump that could be used to test the indexes with exactly the same kind and volume of data?

Thanks,

**Comment by Yenthe666** [comment]
Hi @ke-real,

I'm closing this bug report as there has been no response/feedback in over a year.
If this is still relevant for V9, V10 or V11 and if you can answer (@)odony his questions then feel free to do so.

Regards,
Yenthe
