### ISSUE TITLE
[9.0][CMS] "Rename page" does not redirect old URL (SEO issue)

### ISSUE THREAD

**Issue by auditum-pbe** [odoo/odoo#13563]
Impacted versions: 9.0c & 9.0e

Steps to reproduce:

1. In the CMS, create an new page "foobar" -> URL: /page/foobar
2. In the menu, click "Content" -> "Rename page" and rename it to "barfoo"

Current behavior:
The URL changes from /page/foobar to /page/barfoo, but /page/foobar is **NOT redirected** to /page/barfoo

Expected behavior:
The URL changes from /page/foobar to /page/barfoo and /page/foobar is being redirected to /page/barfoo

This is a critical SEO issue.

**Comment by JKE-be** [comment]
Hi @auditum-pbe 

It is not done by default, because the first idea was to rename the temporary name into the new name.
For model page (product, blog, forum, ...) in database, the slug system automatically works by default.
You can do it if you want rename one already referenced page, via an attachment redirection, or simply creating the old page, and add one meta redirect 301.

I add this feature for next version.

Thank you for the reporting

JKE
