### ISSUE TITLE
@unittest.expectedFailure no longer works

### ISSUE THREAD

**Issue by carmenbianca** [odoo/odoo#135647]
Impacted versions:

16.0, used to work in 14.0

Steps to reproduce:

Write the following test:

```python
from odoo.tests.common import TransactionCase

import unittest

class TestCase(TransactionCase):
    @unittest.expectedFailure
    def test_failure(self):
        a = 1 / 0
```

Run `odoo -c your.conf -d your-db --test-tags /your-test-module --stop-after-init`.

Current behavior:

The test runs and fails, failing the suite.

Expected behavior:

The test fails expectedly without failing the suite.

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by carmenbianca** [comment]
This is still an issue.

**Comment by vava-odoo** [comment]
Hi @carmenbianca 
Thanks for the report. Maybe @odoo/rd-framework-py can help here.
Cheers.

**Comment by Xavier-Do** [comment]
Do you have an example to explain why you need this feature? Isn't assert raise or any other assertion more useful/precise?

**Comment by Xavier-Do** [comment]
This regression was knowingly introduced in #112294, the main goal being to simplify unittest and removing features we don't need to allow easier customization and removing dirty hacks, mainly regarding immediate error logging + cross version compatibility. 

We decide that the expected failure was not a useful concept for us, mainly because we can do better assertions.

```
    def test_failure(self):
        with self.assertRaises(ZeroDivisionError):
            a = 1 / 0
```

Being more precise is a good think, lets imagine that the code is modified during some refactoring


```
    def test_failure(self):
        with self.assertRaises(ZeroDivisionError):
            a = b / 0
```

The code will fail because `NameError: name 'b' is not defined

**Comment by carmenbianca** [comment]
The use case for the decorator is to temporarily disable a test without deleting or commenting out the test code. Useful in a limited set of scenarios. Not a best practice, and I won't mourn if `expectedFailure` remains dysfunctional.

**Comment by Xavier-Do** [comment]
For this use case the @skip of @skipIf should still work :)
