### ISSUE TITLE
[ORM] Assigning a store=False field causes write_date update to DB.

### ISSUE THREAD

**Issue by elmeriniemela** [odoo/odoo#136044]
Impacted versions: at least 15 and 16. 

Steps to reproduce:
```python
class ResPartner(models.Model):
    _inherit = "res.partner"

    field1 = fields.Char(compute='_compute_field_1')
    field2 = fields.Char(compute='_compute_field_2')

    def _compute_field_2(self):
        for record in self:
            record.field2 = 'field2'
            record.field1 = 'new value' # This will cause an update to res.partner 'write_date' every time field2 is read.


    def _compute_field_1(self):
        for record in self:
            record.field1 = 'field1'
```

Also this will cause the same behaviour:

```python
class ResPartner(models.Model):
    _inherit = "res.partner"

    field1 = fields.Char(compute='_compute_both_fields')
    field2 = fields.Char(compute='_compute_both_fields')

    def _compute_both_fields(self):
        for record in self:
            record.field2 = 'field2'
            record.field1 = 'field1'


class ResPartner(models.Model):
    _inherit = "res.partner"
    
    # This will cause an update to res.partner 'write_date' every time field2 is read.
    field2 = fields.Char(compute='_compute_only_field_2') # Overwrite compute method name in an "extension module".

    def _compute_only_field_2(self):
        for record in self:
            record.field2 = 'overwritten by extending module'
```

Current behavior:
Assigning a non-stored field outside of its original compute method causes the 'write_date' on the record to be updated.
Expected behavior:
Field write_date should not be updated as nothing is written to the DB.

**Comment by ryv-odoo** [comment]
Hello @elmeriniemela ,
Assigning a non-stored compute field outside of its original compute method is a bad practice that is not fully managed by the ORM (as you show). 
The ORM uses the `protecting` mechanism to compute field values and bypass business logic of `BaseModel.write` (see `compute_value` https://github.com/odoo/odoo/blob/627d2a187ab110ed51860b78a20e5ff72c6d01f0/odoo/fields.py#L1417-L1418
and in `__set__` https://github.com/odoo/odoo/blob/627d2a187ab110ed51860b78a20e5ff72c6d01f0/odoo/fields.py#L1328-L1331

IMO, there is nothing to fix at the ORM level (we cannot prohibit this bad practice without additional efficiency costs). Instead, we should fix the assignment being done in the wrong place (or if you don't have any other choice, use the `protecting` method first).

Cheers.

**Comment by elmeriniemela** [comment]
Hi @ryv-odoo 

Yes, I agree with you that assigning a compute field outside of its original method is a bad practice. However, the ORM, unfortunately, allows it with unexpected side effects that break the "Last updated" metadata reliability and cause unnecessary UPDATE locks to DB on every read. This issue is very hard to notice during development, which is why it can easily get into a customization module. In the last few months, I've spent tens of hours on multiple different projects investigating what is causing only the write_date field to be updated when a record is viewed. Since nothing else than write_date is in the SQL, it's very hard to find the computed field that is causing the update.

I would also be happy with a restriction that raises an error if a computed field without an inverse method is assigned outside of its original method. Thank you for considering this issue.

**Comment by rco-odoo** [comment]
@elmeriniemela what you ask for is impossible without some absurd performance and complexity overhead.

First, we try to add complexity in the framework where it is actually needed, i.e., when that complexity is _necessary_ for "normal" things to work. In that case, we consider that the complexity and performance overhead is worth it. Sometimes, we also pay that price to protect the developer against critical mistakes, i.e., things that are obviously incorrect. I don't think we are in such a case here.

Second, adding too many restrictions will not protect you against stubborn developers, or cases where it is actually completely fine. My experience taught me that when you try to prevent a developer from doing something _you consider wrong_, some developers will find a way around it, and sometimes it gets worse. In this particular case, some developers will simply do the update in plain SQL, because _they_ know what's better. And you end up with memory inconsistencies down the line...

Third, you cannot implement this restriction without breaking field abstractions. For instance, if the computed field is a stored one2many field, assigning that field will automatically update some many2one field. Preventing that many2one update will break the one2many field's implementation. We want the ORM to work with any kind of field, including fields implemented by third-party contributors.

Fourth, "`write_date` should not be updated as nothing is written to the DB" is an _opinion_. You may actually _want_ the current (opposite) behavior. Suppose you have some computed field that depends on `record.write_date`, and the purpose of that dependency is actually to trigger the field's recomputation. If you have no other field to update on `record`, you can actually simply `record.write({})` to force `record.write_date` to be updated. I don't pretend it is a good way to do it, but it is simple and reasonable. I personally don't have a definitive opinion on that subject.

**Comment by rco-odoo** [comment]
By the way, we have recently added a warning for compute methods that mix stored and non-stored fields https://github.com/odoo/odoo/pull/98565. This should avoid unexpected database updates when accessing a non-stored computed field. I believe that this is more critical, since we consider that situation to be a _design_ mistake. We had a bunch of cases like that in our own codebase, and the warning helped me fix them.

To me, your use case is a _programming_ mistake. It almost never happens. So spending time and complexity for something that is not supposed to happen is not acceptable. I makes the ORM slower, with no beneficial counterpart for the "good" developers.

**Comment by elmeriniemela** [comment]
@rco-odoo This developer mistake is currently in V17 enterprise code, see: 
1. Task: https://www.odoo.com/my/tasks/4184717
2. Field defined as related: https://github.com/odoo/enterprise/blob/9b388c07f280db3eedb28c604a35ef5c808c13dd/mrp_workorder/models/quality.py#L208
3. Assigned in compute method: https://github.com/odoo/enterprise/blob/9b388c07f280db3eedb28c604a35ef5c808c13dd/mrp_workorder/models/quality.py#L292

This is causing a performance issue for the customer that was extremely difficult to debug if one did not know what to look for, as only clue was constant "Concurrent update" erros on logs where only write date

```
odoo.sql_db: bad query: UPDATE "quality_check" SET "write_date" = '2024-09-13 10:44:20.122234', "write_uid" = 57 WHERE id IN (518365, 518366, 518367, 518368, 518369, 518370, 518371, 518372, 518373, 518374, 518393, 518394, 518385, 518386, 518387, 518388, 518389, 518390, 518391, 518392, 518404, 518395, 518396, 518397, 518398, 518399, 518400, 518401, 518402, 518403, 518405, 518406, 518407, 518408, 518409, 518410, 518411, 518412, 518413, 518414, 518415, 518416, 518417, 518418, 518419, 518420, 518421, 518422, 518423, 518424, 518425, 518426, 518427, 518428, 518429, 518430, 518431, 518432, 518433, 518434, 518445, 518446, 518447, 518448, 518449, 518450, 518451, 518452, 518453, 518454, 518485, 518486, 518487, 518488, 518489, 518490, 518491, 518492, 518493, 518494, 518503, 518495, 518496, 518497, 518498, 518499, 518500, 518501, 518502, 518504, 518514, 518505, 518506, 518507, 518508, 518509, 518510, 518511, 518512, 518513, 518515, 518516, 518517, 518518, 518519, 518520, 518521, 518522, 518524, 518523, 518525, 518526, 518527, 518528, 518529, 518530, 518531, 518532, 518533, 518534, 518535, 518536, 518537, 518538, 518539, 518540, 518541, 518542, 518543, 518544, 518554, 518545, 518546, 518547, 518548, 518549, 518550, 518551, 518552, 518553, 518555, 518556, 518557, 518558, 518559, 518560, 518561, 518562, 518563, 518564, 518565, 518566, 518567, 518568, 518569, 518570, 518571, 518572, 518573, 518574, 518575, 518576, 518577, 518578, 518579, 518580, 518581, 518582, 518583, 518584, 518585, 518586, 518587, 518588, 518589, 518590, 518591, 518592, 518593, 518594, 518595, 518596, 518597, 518598, 518599, 518600, 518601, 518602, 518603, 518604, 518605, 518606, 518607, 518608, 518609, 518610, 518611, 518612, 518613, 518614, 518615, 518616, 518617, 518618, 518619, 518620, 518621, 518622, 518623, 518624, 518625, 518626, 518627, 518628, 518629, 518630, 518631, 518632, 518633, 518634, 518635, 518636, 518637, 518638, 518639, 518640, 518641, 518642, 518643, 518644, 518645, 518646, 518647, 518648, 518649, 518650, 518651, 518652, 518653, 518654, 518685, 518686, 518687, 518688, 518689, 518690, 518691, 518692, 518693, 518694, 518295, 518296, 518297, 518298, 518299, 518300, 518301, 518302, 518303, 518304, 520033, 520034, 520035, 520036, 520037, 520038, 520039, 520040, 520041, 520042, 520163, 520164, 520165, 520166, 520167, 520168, 520169, 520170, 520171, 520172, 520443, 520444, 520445, 520446, 520447, 520448, 520449, 520450, 520451, 520452, 520463, 520464, 520465, 520466, 520467, 520468, 520469, 520470, 520471, 520472, 520473, 520474, 520475, 520476, 520477, 520478, 520479, 520480, 520481, 520482, 520753, 520754, 520755, 520756, 520757, 520758, 520759, 520760, 520761, 520762, 520763, 520764, 520765, 520766, 520767, 520768, 520769, 520770, 520771, 520772, 518375, 518376, 518377, 518378, 518379, 518380, 518381, 518382, 518384, 518383, 521141, 521142, 521143, 521144, 521145, 521146, 521147, 521148, 521149, 521150, 521161, 521162, 521163, 521164, 521165, 521166, 521167, 521168, 521169, 521170, 521251, 521252, 521253, 521254, 521255, 521256, 521257, 521258, 521259, 521260, 521511, 521512, 521513, 521514, 521515, 521516, 521517, 521518, 521519, 521520, 521181, 521182, 521183, 521184, 521185, 521186, 521187, 521188, 521189, 521190, 521697, 521698, 521699, 521700, 521701, 521702, 521703, 521704, 521705, 521706)
ERROR: could not serialize access due to concurrent update

2024-09-13 10:44:57,740 739734 INFO customerdb odoo.service.model: SERIALIZATION_FAILURE, maximum number of tries reached!
2024-09-13 10:44:57,741 739734 ERROR customerdb odoo.http: Exception during request handling.
Traceback (most recent call last):
  File "/opt/odoo/odoo/odoo/http.py", line 2189, in __call__
    response = request._serve_db()
  File "/opt/odoo/odoo/odoo/http.py", line 1764, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "/opt/odoo/odoo/odoo/service/model.py", line 133, in retrying
    result = func()
--
  File "/opt/odoo/odoo/odoo/api.py", line 723, in flush_all
    self[model_name].flush_model()
  File "/opt/odoo/odoo/odoo/models.py", line 6319, in flush_model
    self._flush(fnames)
  File "/opt/odoo/odoo/odoo/models.py", line 6420, in _flush
    model.browse(ids)._write(vals)
  File "/opt/odoo/odoo/odoo/models.py", line 4517, in _write
    cr.execute(SQL(
  File "/opt/odoo/odoo/odoo/sql_db.py", line 332, in execute
    res = self._obj.execute(query, params)
psycopg2.errors.SerializationFailure: could not serialize access due to concurrent update
```


Could we not add a warning like in the screenshot below to the write method? I think it would not add too much complexity or cause performance issues.
![image](https://github.com/user-attachments/assets/c052f16f-574b-4391-a1f9-eedb832b2a0b)

**Comment by ryv-odoo** [comment]
Hello @elmeriniemela ,

Thank you reporting the issue, there is clearly a mistake in `_compute_component_data`. I made a PR for this case https://github.com/odoo/enterprise/pull/70025 (still need to be review by the Logistics team).

Not against the warning, but we need to clean a lot of business code to merge it (and it isn't possible in stable): https://github.com/odoo/odoo/pull/180194 . You can the result in the runbot: https://runbot.odoo.com/runbot/build/68174907. Most of warning are due to compute method called manually (most of them are in the test but some of them are actually in the business code :disappointed: ).

Cheer.
