### ISSUE TITLE
Stock moves created by a push rule are not cancelled when cancelling their procurement

### ISSUE THREAD

**Issue by KrilleGH** [odoo/odoo#13607]
Impacted versions: 8.0, probably 9.0 as well

Steps to reproduce: Setup a route with a pull and a push rule. When the rule is applied by a procurement it creates two stock moves. Then cancel the procurement.

Current behavior: While cancelling the procurement the stock move created by the pull rule is cancelled automatically. The move created by the push rule isn't cancelled since its procurement_id isn't set and thus it itsn't part of the procurement.

This behaviour is the case since  fe15829c1664c00bc64874af4f504eaffbe1c12f. Previously it did set the procurement_id and cancelled all related moves.

Expected behavior: As it has been prior to the mentioned commit: All stock moves created by rules are assigned their procurement_id and thus are cancelled when the procurement is cancelled.

I don't know the reason for the change made in this commit, but I belive that it is wrong as it is now since the cancellation behaviour is odd and doesn't seem to have been considered.

Video/Screenshot link (optional):

**Comment by jgrandguillaume** [comment]
Hi,


I agree this is an issue.. You also face it when you have for example a reception in 3 steps and a MTS product N° ABC:

 1) Run scheduler, Order point trigger and place a procurement on stock, pulled via the pull rules to quality and finally to input
 2) Input procurement trigger a draft PO
 3) At some point someone cancel the internal picking moving goods from input to quality, moves from quality to stock are cancelled by propagation
 4) **BUT** the moves from vendors to input is still here, with a destination move = the canceled one in 3)

Here you're stuck, because if you receive goods from your supplier, then the goods will never move from input ! The push rule is never apply again...

May be the following fix would fix it ! Basically, it add to the action_cancel method of a move:

 1) Find the parent of the cancelled move and remove the destination_move from it
 2) Re-apply push rule on the parent moves

Regards,

Joël

[patch.txt](https://github.com/odoo/odoo/files/661165/patch.txt)

**Comment by Yenthe666** [comment]
Hi @KrilleGH ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
