### ISSUE TITLE
received and billed qty in PO form are not updated properly

### ISSUE THREAD

**Issue by ccandito** [odoo/odoo#13642]
Impacted versions:
9.0
Steps to reproduce:
return delivery to vendor and refund from vendor invoice
Current behavior:
return delivery qty is not taken into account
quantity in credit note is taken into account with positive sign
Expected behavior:
return delivery qty should be taken into account with negative sign
quantity in credit note has to be taken into account with negative sign
Video/Screenshot link (optional):

**Comment by bistaray** [comment]
Please review https://github.com/odoo/odoo/issues/13299 - this is how Odoo is designed to work.

**Comment by ccandito** [comment]
so it has been designed wrongly.
following the example suggested by you, you could pay a vendor invoice for 25 pieces besides you have accepted 20 pieces only.
the right behaviour should be:
1) goods receipt for 25 pc
2) goods return to vendor 5 pcs (or the warehouse counting is for 20 pcs)
3) 20 pcs in PO form
4) the vendor sent out an invoice for 25 pcs
5) the system should suggest 20 pcs (the right qty to be paid) and the account payable clerk shoud change it in 25; an indicator has to be evaluated automatically (for cumulated invoiced qty more than received cumulated qty) to forbid invoice payment although this will be removed manually

the same correction should be done for invoiced quantity in PO form otherwise the invoice verification process does not work out: for the time being the system take into account credit note qty with positive sign instead of subtractiong them

Regards
claudio candito

**Comment by bistaray** [comment]
It may have been designed in a different way that you would like, but I don't agree it is 'wrong'.

In your example, 25 units are shipped, and you will receive and Invoice for 25 items.  This is what Odoo will suggest, based on receiving 25 units.  If you chose to return 5, that is a separate transaction and it handled via a separate Delivery and a separate Invoice (like it is in the real world).

Showing 20 items received would suggest that the original PO is still open, which it isn't.  

Suggesting an Invoice for 20 items will require work by Accounting to understand why 25 were not received (when they actually were).  

The returned quantity will generate a credit note that Accounting will see when reviewing the Invoices to be paid, and they will see that although they need to pay for 25, they can reduce the balance by 5 and pay just the balance for the 20.

You can certainly change the design, but you might also consider changing your perspective on how to handle this workflow.  What you suggest leads to TWO different ways to Invoice - one for shipments 100% received, and another way for shipments not 100% received.  Accounting has to do extra work in the case a shipment is not 100% received.  

Exceptions and extra work are not signs of an efficient design.

**Comment by aaronwestb** [comment]
I have just started using ODOO and also feel there should be a way to override the items received.    
For example , if an employee accidentally marks items as received when they were NOT received yet or were only partially received it would be necessary to fix the mistake and change the PO back to 0 items received.    How do I accomplish this?

**Comment by fpodoo** [comment]
There is a basic rule in Odoo inventory to respect when we design features:
exceptions (cancel something, return products) should be fixed manually by
the user. The system should not try to handle the use case for the user
automatically.

Why? Because there are several ways to handle an exception and, as we are
never sure what's the current use case, it's better to do nothing than
doing something wrong. Odoo's behavior is also more predicable that way.

Let's take your example. Receive 25 and return 5. Here are the possible
scenario:

1/ you expect the vendor to send you back 5 others later because you
ordered 25
2/ you ordered 25, but the vendor is flexible, he will invoice you only 20.
3/ you ordered 25, but the vendor is flexible. He already sent the invoice
for 25, so he will send you a refund invoice.
4/ as you ordered 25, the vendor is in his right to bill you 25. A conflict
starts.

-- 
Fabien

**Comment by ccandito** [comment]
Unfortunately this basic rule is weak in procurement process management because the money flow is outbound, so from the company to vendors; that means automatic checks should be implemented to avoid mistakes/frauds.
Just some simple suggestions to improve this business case:
1) the delivery quantity should take into account all the returns/cancelletions (20= 25-5)
2) when posting invoice documents, the system should suggest the real delivery quantity (20 pieces); in case the accounting payable clerk increases it at item level (25 pieces from the invoice sent out by the vendor), the whole invoice document has to be blocked for payment (an indicator at header level)
3) the invoice can be payable only after removing this indicator by an authorized user (accounting payable manager)

this is one of the several checks to be implemented for a robust invoice verification process.
Regards
claudio candito

**Comment by aaronwestb** [comment]
My point is that if I received only 20 but my employee accidentally marks all 25 received and done , how do i fix the PO so that it is correct and shows only 20 received?   We ONLY did receive 20 but my employee accidentally marked all as received.    I must be overlooking something here , because there has to be a way to fix  the PO so that it is correct.    How do I accomplish this?

**Comment by ccandito** [comment]
Any update about it.
I've noticed in the version 11 the refund option in return movement is avalable.
could it be implemented in version 10 also?
Regards
claudio candito

**Comment by sle-odoo** [comment]
@ccandito as commented in #22049, a backport of this feature is not possible. I'm thus closing this issue.
