### ISSUE TITLE
[10] Mobile view of apps form not nice

### ISSUE THREAD

**Issue by afwanwh** [odoo/odoo#13654]
Impacted versions: 10

Steps to reproduce: Open Apps >> Select a module

Current behavior: not nice. See attachment
![screenshot_20161001-030239](https://cloud.githubusercontent.com/assets/8463442/19005320/1757f6c4-8784-11e6-9c75-1205f7108f5c.jpg)

Expected behavior: should follow mobile view

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
@mart-e can you assign somebody on this one? Not sure who this is for. 😄

**Comment by mart-e** [comment]
I think @qsm-odoo and @ged-odoo are best suited for this :)

**Comment by ged-odoo** [comment]
this is the result of some weird decisions.  In this case, the problem is caused by the fact that the apps 'description' field use some kind of duplicated bootstrap css, apparently to make it work statically on the website.  And our duplicate css is simply not responsive (the .oe_row class has a width hardcoded to 928px).

**Comment by Yenthe666** [comment]
@ged-odoo now onwards to a cleaner solution then? 😉

**Comment by afwanwh** [comment]
Hello, any update on this?

**Comment by pedrobaeza** [comment]
Is there any news on this, @ged-odoo ?

**Comment by ged-odoo** [comment]
well, I just checked and this particular issue is fixed.  Thanks to whoever did it, and to anyone who reported the issue.
