### ISSUE TITLE
KeyError: 'invoice_line' 

### ISSUE THREAD

**Issue by Develoman** [odoo/odoo#13677]
Impacted versions: 9.0

Steps to reproduce: first step when installing invoicing module

Current behavior: bug error

Expected behavior: install module invoice

Video/Screenshot link (optional):
![capture du 2016-10-04 23 01 48](https://cloud.githubusercontent.com/assets/12783685/19094621/e66f232c-8a88-11e6-8f56-7f15d90e9fd9.png)

**Comment by JKE-be** [comment]
hello @Develoman 

I cannot reproduce your issue. 
Can your reproduce it on runbot (choose a 9.0 base db) ? probably not :/ Else, it will be red ! :red_circle: 

Are you sure that you have no custom module ? 

invoice_line seems to be 8.0, because in v9 it has been renamed into invoice_lines.
Try removing all custom module... and keep only a clean odoo install... to install invoice and let us know...

Waiting your feedback

JKE
