### ISSUE TITLE
[Proposal] In memory base64 strings, soo much memory used

### ISSUE THREAD

**Issue by rmmr** [odoo/odoo#13683]
Impacted versions:

All

Steps to reproduce:

Select an image (anywhere), update the model record.

Current behavior:
- json write request triggered, json body containing base64 data. 
- controller receives base64 data through arguments
- attachment system uses in memory base64 strings.
- /web/content requests use in memory base64 strings

Expected behavior:
- json write request detects binary payloads, utilizes multipart/form-data https://www.w3.org/TR/html401/interact/forms.html#h-17.13.4.2 
- controller still receives same arguments, except base64 data is wrapped inside a custom base64 object which operates against either a temporary file or an existing file (in case of attachments)
- /web/content requests utilize the same custom base64 object for creating thumbnails etc.

---

I am attempting to create above solution for this, which 'm intending to use this inside my Odooku project (run Odoo on Heroku, and any cloud like environment for that matter). However I would rather see this solution being implemented in Odoo itself, for which I am of course willing to make a pull request. Before doing this I would like to see your stance on this subject.

I can understand this may not be an issue for regular Odoo hosting solutions where a lot of memory is available, however I do believe the current system is flawed.

**Comment by JKE-be** [comment]
@KangOl maybe you have one opinion about it ?

**Comment by KangOl** [comment]
The payload already contains the raw json request. Changing this will be against [the json-rpc spec](http://www.jsonrpc.org/specification).

**Comment by adaptivdesign** [comment]
I can understand that it's easy to simply include all data in the json payload, but mind you this is not something that should be taken lightly. Below I've included a sample scenario.

Also Look at how Django handles this:

https://docs.djangoproject.com/en/1.10/topics/http/file-uploads/

```
[165] [INFO] 10.0.2.2 - - [11/Oct/2016:18:00:49 +0000] "POST /web/dataset/call_kw/ir.config_parameter/get_param HTTP/1.1" 200 85 "http://127.0.0.1:8000/web?" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36"
[165] [INFO] Memory used: 141200 (kb)

(uploaded a 6.1 mb image) 

```

**Comment by adaptivdesign** [comment]
To further clarify, the payload is send in a slightly different matter. The javascript webclient detects the use of binary data when performing a POST request. So that:

- The binary data is included outside the json payload
- The json field which contained the binary data, is replaced with something like an index value.
- The binary data is added as part of the multipart/form-data 
- So that the multipart/form-data content consists out of both the json payload and 1 or multiple sequences of binary data.
- So that we can utilize werkzeug.datastructures.FileStorage

I am willing and able to make this work, and create a pull request for it.

**Comment by keshrath** [comment]
The limitations caused by the transformation of binary data to base64 are really a problem and unfortunately deeply anchored in the odoo orm. There are even a lot of places in the odoo code that convert the base64 back into a binary to do for example image operations. It would be such a big step forward to work with binary streams instead of base64 in the backend.

**Comment by keshrath** [comment]
@rmmr have you open sourced your solution somewhere?@rmmr have you open sourced your solution somewhere? I'm afraid however that such a change can only happen in Odoo itself there are too many places that rely on a binary field to return base64.
