### ISSUE TITLE
avg= is not working on tree view

### ISSUE THREAD

**Issue by GoodERPJeff** [odoo/odoo#13713]
Impacted versions: v8 v9 v10 master

Steps to reproduce:

menu Sales - My Pipline

change to tree view
 
Current behavior:
![image](https://cloud.githubusercontent.com/assets/1857069/19231807/a94fdb64-8f0e-11e6-8b12-6223c0c7f7c0.png)

Expected behavior:

show avg probbility on footer of this column

Video/Screenshot link (optional):

**Comment by JKE-be** [comment]
Hello, 
Thanks for the reporting.
It has been fixed by commit :
    - odoo/doo@4ca06e02558b202183592f4d7c67f76f302bc0d1 in v8
    - odoo/odoo@633780a00c33089a5bd6fbbd9388ed37d46d59b9 in v8
    - odoo/odoo@62116e7 in v9

JKE

**Comment by GoodERPJeff** [comment]
how about version 10 ?

**Comment by JKE-be** [comment]
Hello,

That will be forward-ported asap... (probably tomorrow)
We always try to fix the issue to the early version where the bug appears.
And with forward all fixes from 8 to 9, and from 9 to 10, and 10 to master.

**Comment by GoodERPJeff** [comment]
Good, thanks for your work

**Comment by JKE-be** [comment]
Hello @GoodERPJeff ,

As you can see, the fix has been forward ported to v10.
But unfortunately, with a side effect... Since commit https://github.com/odoo/odoo/commit/629e175 the aggregate by default has been set to "sum"... So all sub-total are now 'sum'. So we need to change the behavior for v10.

After some discussions, we think to remove the use of the group_operator defined in python, and so force the developer/user to set in the view if he want an aggregate function or not.

In all cases, if you update your view with <field name='the_field' avg='my label tooltip'/> it will works with previous, actual and (probably) future code.

I ping you, when a solution will be found...
