### ISSUE TITLE
Answering by email an Internal Note produce a Message for customer

### ISSUE THREAD

**Issue by rafaelbn** [odoo/odoo#13717]
Impacted versions: all

- 8.0
- 9.0
- 10.0

Steps to reproduce:

- Go to an Enterprise in version 10, 9, 8
- Odoo **must have** a SMTP server to send emails and a POP/IMAP server to receive emails
- This is an problem in all objects but I will write an example with O
- Go to Sales --> Your Pipeline --> go inside an Opportunity or create a new one
- Add in this opportunity a customer with a real email address
- Add in this opportunity as follower 2 Odoo users with **real** email address
- In the opportunity as user1 write an "Internal note" to the second user2 like: "Please user2 send me the private information that customer cannot see"
- When user2 receive the e-mail of the internal note, user2 answers to the user1 via email: "Hi user1, this is the PRIVATE information that customer cannot see"

Current behavior:

- Customer as follower will receive the message "Hi user1, this is the PRIVATE information that customer cannot see"

Expected behavior:

- Customer doesn't receive the PRIVATE info and the answer is also an "Internal note"

Video/Screenshot link (optional):

**Comment by mart-e** [comment]
Hello,

The issue is that you are not answering to a specific email, you are answering to a thread, so Odoo doesn't know you are replying to a note.

But anyway, even if we could know this, I am not sure we want to implement this. It would add some magic to emails making it obscure when a email is sent to everyone and when it is sent only internally.

@bst-odoo do you agree?

**Comment by bst-odoo** [comment]
Hello,
Actually, the behavior has changed in V10 (we couldn't fix it in the earlier versions because indeed, it was like answering to a thread back then).
When you reply to an internal note, it creates a new internal note. 
https://drive.google.com/a/openerp.com/file/d/0BxqHe5rtIxY0U1pwdFRlbjFFVG8/view?usp=drivesdk

Kind regards,
BST

**Comment by mart-e** [comment]
I did not know that, thanks for the info. So I guess we can close as done in v10 (it is a change of behaviour, not a bug so will not backport it to 8 and 9).

**Comment by rafaelbn** [comment]
Thanks for answer

@antespi @yajo @pedrobaeza @sergio-teruel @carlosdauden take care in this information.

We must go to v10 quickly! :-)

@Tecnativa
