### ISSUE TITLE
[10.0] related field related field doesn't change original field value

### ISSUE THREAD

**Issue by InfernalLV** [odoo/odoo#13737]
Impacted versions: 10.0

Sometimes its desirable to have one fields in two different positions based on domain attr invisible, but if you have two instances of the same field in a form. One of them doesn't display a value.
 
Steps to reproduce:
field1 = fields.Char()
field2 = fields.Char(related='field1')

Current behavior:
field1's value is onchange set to field2. But not the other way around. That is the related field doesn't have a automatically generated onchange while the source field does.

Expected behavior:
Changing field2 should change field1 value.

**Comment by JKE-be** [comment]
Hi @InfernalLV 

We don't support this case at first view...

But anycase... if your usecase is **' based on domain attr invisible'**, so it will work for your case.

Update of Field1 will update Field2 (at onchange, and at save)
Update of Field2 will update Field1 (at save only)

So for simple field it will works, for other field that are dependencies and impact other field... it will fail...
Because if you have a field3 that depend of field1, when you write on field2, it will not trigger the onchange (because Field1 is not already updated to the value of Field2).

But if you take the code of Odoo, we never need to use this hack.
You should probably just re-think about the right place where you want to display it.

**Comment by InfernalLV** [comment]
Thank you for the prompt response.
