### ISSUE TITLE
[10.0] Invoice date is today's date, when I expect to choose the invoice date myself.

### ISSUE THREAD

**Issue by pdemil** [odoo/odoo#13758]
Impacted versions:
10

Steps to reproduce:
Create sales order in January 2016, confirm sale on, convert to Invoice.

Current behavior:
Date confirm sale is January 30, 2016, when an invoice is created it is using today's date (October 12, 2016)

Expected behavior:
I want to be able to choose the invoice date.

Video/Screenshot link (optional):

**Comment by JKE-be** [comment]
Hello @pdemil 

> Date confirm sale is January 30, 2016, when an invoice is created it is using today's date 

That is the expected behavior.
If you confirm an order that you invoice 3 month later, you don't want to have a invoice in previous period or previous year...


> I want to be able to choose the invoice date.

When you create the invoice (from the sale order in your case), before to validate it, you can edit the invoice date at the top right

![image](https://cloud.githubusercontent.com/assets/4848797/19306942/53e95e1e-9078-11e6-96d8-630e65e75d33.png)

So, the expected behavior is ok ?

**Comment by pdemil** [comment]
Reasson why I want this: when we start with Odoo, we have to enter all the previous Invoices, to have it all in the system...

I can't change the Confirmation date of the Sales Order. 
I clicked "Create and View Invoices", which gave me the invoice with today's date. 
Using "Create invoices": it works and I can set the invoice date usint "edit"

Thanks for the quick reply.

**Comment by JKE-be** [comment]
"Create and View Invoices" and "Create Invoice" should do exactly the same thing.
Except that one redirect you on the invoice view, the other one let you on the sale order form.

![output](https://cloud.githubusercontent.com/assets/4848797/19308056/fed14940-907d-11e6-8bbc-be551275ae5b.gif)
