### ISSUE TITLE
PDF Invoice Duplicated when is send by email

### ISSUE THREAD

**Issue by luistorresm** [odoo/odoo#13838]
Impacted versions:
9.0 2ce7679032dd556314060ec9b64e1eff1db59526

Steps to reproduce:
1.- Generate a new customer invoice
2.- Validate it
3.- Send the invoice by email

Current behavior:
The Invoice PDF is attached in two times in the invoice

Expected behavior:
Only have an PDF Attached in the record

Video/Screenshot link (optional):
https://youtu.be/YCkX96Xiqj8

**Comment by intero-chz** [comment]
That's because the report itself is generating another report attachment name than the email template.

report: (object.state in ('open','paid')) and ('INV'+(object.number or '').replace('/','')+'.pdf')
template: Invoice_${(object.number or '').replace('/','_')}_${object.state == 'draft' and 'draft' or ''}

**Comment by pedrobaeza** [comment]
This is the expected behavior, as each sending is independent from the rest of operations, and should be self-contained, generating a new PDF, as you can't know what the other attachments contain. This is not an actual bug, so I close.
