### ISSUE TITLE
[7.0] search more m2o fields

### ISSUE THREAD

**Issue by ernesto-gm** [odoo/odoo#1386]
Not shown complete records in "search more..." view when have more of 160 records on m2o field.
- **Impacted versions:**
  7.0 and above
- **Steps to reproduce:**

go to some m2o field  
click on search more ...
![search_more](https://cloud.githubusercontent.com/assets/7605672/3703939/edb7823e-140e-11e4-96f1-70c5b84bf006.png)

use some "group by" 
![search_group_by](https://cloud.githubusercontent.com/assets/7605672/3703940/f443a696-140e-11e4-8be1-49ffd3af92fc.png)

remove the grouping 

![search_without_group](https://cloud.githubusercontent.com/assets/7605672/3703941/f7e044ee-140e-11e4-81b7-f9563ca33d78.png)
- **Current behavior:**

show 160 records in search more view.
- **Expected behavior:**

show total records in search more view.

**Comment by cyrilgdn** [comment]
Same problem in V9... There is a limit 160 hard-coded here https://github.com/odoo/odoo/blob/9.0/addons/web/static/src/js/views/form_common.js#L213 .

And the behaviour is worse if you defined a default filter for the comodel.
In my case, when I click on Search More, the popup list is empty because the 160 ids passed to the popup don't match my default filter so I have to remove it and select it again... It's sad :(

@odony  Is this a desired behaviour?

**Comment by Yenthe666** [comment]
Hi guys,

First of all, sorry for the very late reply on this.
as @cyrilgdn has pointed out this is hardcoded in Odoo and is done for performance reasons. You could bypass this by simply searching something and removing the filter again, or expanding it. This has been done on purpose.
This might eventually be changed to a configurable setting but is not the case up untill now (V10)

Regards,
Yenthe
