### ISSUE TITLE
[10.0] [10.0_Enterprise] Wrong Redirect Link while installation of "Revenue Recognition"

### ISSUE THREAD

**Issue by suniljagyasi** [odoo/odoo#13882]
Impacted versions:
10.0

Steps to reproduce:
1. Go to Setting
2. Click on Accounting Planner
3. Select Extra Features
4. Try to Install "Revenue Recognition"

Current behavior:
Instead of open "Revenue Recognition", system redirect open "Assets Management".
Expected behavior:
Revenue Recognition Module should be there.

**Comment by Yenthe666** [comment]
Hi @suniljagyasi,

Could you add a bit more information about 'Click on Accounting planner'? What exactly do you mean with this? Could you add some screenshots or a video please?

**Comment by JKE-be** [comment]
@Yenthe666 Settings = web_planner

**Comment by JKE-be** [comment]
@suniljagyasi account_deferred_revenue module is in enterprise only.

@apr-odoo what is your opinion about it ?

**Comment by ajaychauhan727** [comment]
@JKE-be The issue is that it redirects again to "Assets Management".
Issue is reproducible on **10.0 community** & **enterprise**, both versions.

Suggested solution:
1> Revenue Recognition should not be there in community version planner.
2> Redirect to **account_deferred_revenue** module while clicking on Revenue Recognition in enterprise version.
