### ISSUE TITLE
[9.0][BUG] JS error after log in when record rule for ir.attachment is created

### ISSUE THREAD

**Issue by analisaodoo** [odoo/odoo#13895]
**Impacted versions:**
9.0 

**Steps to reproduce:**
1. Activate developer mode 
2. On Settings -> Technical -> Record rules create a new record rule for object ir.attachment with all access rights checked, domain: [('res_model', '=' , 'hr.employee'), ('res_id', 'in', [emp_id.id for emp_id in user.employee_ids])] for groups Human Resources / Employee
3. Create another record rule with all access rights checked, domain: [(1, '=', 1)] for groups Human Resources / Officer 
4. Create an user 'test' only with Human Resources -> Employee as groups 
5. Create an employee related to user 'test' 
6. Log in with user test (without active developer mode)

**Current behavior:**
JS error on browser console when user test try to log in. If developer mode is active there is not JS error. When an officer (or manager) log in there is not JS error

**Expected behavior:**
On employee form, an employee should not see the attachments of other employees

Video/Screenshot link (optional):

**Comment by JKE-be** [comment]
Hello @analisaodoo,

At first view, it is not really a bug, but a misconfiguration on your instance...

The first rule, say: 'you can just read attachments from your own employee.

Doing it, you remove access to all others documents as invoice/sale.order, ... AND **assets**.

So when you are not in mode _?debug_, the loading of assets failed (due to an access denied/404) and because the js is not loaded, we cannot show you an error.
If you are in debug mode, you load all scripts one by one, without the asset (ir.attachment containing all the script to be cached in only one file), so you can see the error.

So the fix should be done in your config, with an access rule less strict... 
eg: `['|', '&',('res_model', '=' , 'hr.employee'), ('res_id', 'in', [emp_id.id for emp_id in user.employee_ids]),('res_model', '!=' , 'hr.employee') ]`

Let me know if it fix your problem.

Best regards

JKE

**Comment by aristobulo-eezee** [comment]
@JKE-be should assets be accessed as/or via `ir.attachments`?  I just realized this after your previous response, is it for an specific reason? 

BTW, thank you for the advice, the rule works fine now.

**Comment by analisaodoo** [comment]
Hello @JKE-be yes, the rule works fine now, thank you 👍

**Comment by JKE-be** [comment]
@aristobulo-eezee, yes the assets if the concatenation of all statics files (JS and less/css) saved in one file to allow Odoo to get it in only 1 request.
(commonly separated by FE,BE,Common)

Odoo decides to use the attachment since the model do exactly what we want: 
    allow to save text
    render it via an url
    make it public

Best regards

JKE
