### ISSUE TITLE
Vimeo Pluginn doesnt work

### ISSUE THREAD

**Issue by GuidoDeDuif** [odoo/odoo#13996]
Impacted versions: 10
Steps to reproduce: try to embed a vimeo video

Current behavior: shows error 404 page not found. 

Expected behavior: Should show the vimeo player.

Video/Screenshot link (optional):

**Comment by JurreCl** [comment]
Confirmed its broken. Instead of rendering the video it creates and iframe that redirects to the website with src='undefined'


see attached screenshot 
<img width="1046" alt="screen shot 2016-10-27 at 13 29 35" src="https://cloud.githubusercontent.com/assets/418230/19765707/165276e8-9c4a-11e6-9213-3bb585a9e991.png">

**Comment by qsm-odoo** [comment]
Hello, this bug has been fixed with commit https://github.com/odoo/odoo/commit/2757775ed32f3860ee27c34245606edbf1dc3315
