### ISSUE TITLE
[10] BUG - Sales order not confirmed when using stored card via Authorize.net

### ISSUE THREAD

**Issue by KurtHaselwimmer** [odoo/odoo#14007]
Impacted versions: [10.0]

Steps to reproduce: On Authorize.net configuration

Order Confirmation: Authorize the amount and confirm the SO on acquirer confirmation (capture manually) 
Store Card Data: Always

Current behaviour

For Ecommerce Sales Order 1 - Customer selects Authorize.net and enters card details - checkout proceeds and customer is returned to Order confirmation page. 

Sales Order Created, Payment Transaction Authorised, New Customer information record created on authorize.net sandbox.

For Ecommerce Sales Order 2  - Customer selects the card previously stored with authorize.net - checkout proceeds and customer is returned to Order confirmation page

Sales Quotation Created but **not converted to a sales order,** Payment Transaction Authorised

Expected behaviour

The Sales order confirmation behaviour should be the same for both methods of authorize.net checkout - standard card entry (1) or stored tokenised card (2)

**Comment by dbo-odoo** [comment]
Hello,

The documentation for authorize.net configuration is not yet available (it's coming, I promise! *wink* *wink* @fgi-odoo ), so I'm going to assume the problem is a misonfiguration here (I've just tested it and it works correctly on a sandbox).

Could you check your Authorize.net configuration?In Account > Response/Receipt URLs, the Default Receipt URL should be <server_url>/shop/confirmation and the Default Relay Response URL (akin to Paypal IPN) should be <server_url>/payment/authorize/return. See screenshot for example.
![authorize.net url configuration example](https://cloud.githubusercontent.com/assets/9530767/20099715/51520c44-a5ba-11e6-9cfd-4bf1e943e47a.png)

Can you test with this change and tell me the result? Can you also check that the `payment.transaction` record (Accounting > Payment > Payment Transactions) is not in the *Draft* state (if it is, it means that the validation does not reach your server).

Thanks,

**Comment by KurtHaselwimmer** [comment]
Damien,

I have checked the settings on the authorize.net sandbox and set them as you have specified. I have repeated my tests and found that the previous behaviour is repeated exactly. 

See the attached screenshots that show transactions SO 009-SO 012 made using authorize.net test card 4111111111111111 (exp 1119)

SO 013 is made by selecting one of the stored payment cards - as you can see the quotation is created but this is not turned into a sales order.















Furthermore I have found other problems - namely that new stored cards are created every single time - EVEN IF THE CARD IS ONE THAT IS ALREADY STORED. This is regardless of whether the name of the card is different or the same as one stored previously for that card - it makes no difference.

See the attached screenshot





This is also not appropriate behaviour - if the card is the same as one previously stored then a new one should not be created for every transaction - this will just confuse the hell out of customers.

I await your feedback.

regards

Kurt

Dr. Kurt Haselwimmer

-------------------------------------------------------------
Willow House, 100 High Street, Somersham, PE28 3EH
Tel +44 (0) 845 899 0256  Fax +44 (0) 845 899 0259
-------------------------------------------------------------

**Comment by dbo-odoo** [comment]
Hello,

I'm sorry, but your attachment did not make it to github. Could you edit your message and re-add it?

Just to be sure that we are on the same page, I've just [made a video](https://drive.google.com/file/d/0B5qMvKgBOKBkSEs3VFprUXNTYnM/view) of the flow I'm testing.
Namely: 
1. Log in (cards are not saved for non logged users)
2. Shop for something
3. Pay using authorize (normal payment)
4. Order is confirmed (assuming authorize.net can reach your server)
5. Shop again
6. Pay with saved card

In both cases, my transactions in Odoo are in the Authorized state (and I can capture them, which triggers the capture normally in Authorize.net).

Could you please detail your test flow or, ideally, make a screencast?

Important question: is your server accessible from the internet with either a reverse proxy, a dbfilter or a single database on the server? Because if authorize.net cannot reach your server, it will not work.

If you try the same flow by setting the acquirer in Authorize & Capture instead of Authorize Only, does it work normally?

**Comment by KurtHaselwimmer** [comment]
Damien,

here it is again:

if it still doesn't come through let me have a different email address.

Kurt

I have checked the settings on the authorize.net sandbox and set them as you have specified. I have repeated my tests and found that the previous behaviour is repeated exactly. 

See the attached screenshots that show transactions SO 009-SO 012 made using authorize.net test card 4111111111111111 (exp 1119)

SO 013 is made by selecting one of the stored payment cards - as you can see the quotation is created but this is not turned into a sales order.















Furthermore I have found other problems - namely that new stored cards are created every single time - EVEN IF THE CARD IS ONE THAT IS ALREADY STORED. This is regardless of whether the name of the card is different or the same as one stored previously for that card - it makes no difference.

See the attached screenshot





This is also not appropriate behaviour - if the card is the same as one previously stored then a new one should not be created for every transaction - this will just confuse the hell out of customers.

I await your feedback.

**Comment by dbo-odoo** [comment]
This is not the e-mail the problem, the problem is that github does not display attachment from emails; you must come to the github issue page and add it manually.

**Comment by dbo-odoo** [comment]
Hello,

I was finally able to reproduce it, my apologies for the delay.

I've created a support ticket for easier traceability, it will be taken care of by our bug-fixing team.

opw-693517

**Comment by KurtHaselwimmer** [comment]
Damien,

I have access to other support tickets that are connected to my account - but 693517 is not on the list that I can see under 'Your Issues' on my odoo account dashboard. Can you give me access to the issue.

regards

Kurt

**Comment by vonpupp** [comment]
Hi,

I have followed the explanations on this thread, see below.
![2017-05-10-211943_2720x1024_scrot](https://cloud.githubusercontent.com/assets/1082073/25926618/97e17770-35c6-11e7-8106-494f75604fcf.png)
![2017-05-10-211949_2720x1024_scrot](https://cloud.githubusercontent.com/assets/1082073/25926621/9c967d74-35c6-11e7-941c-28cb00b7980f.png)

However I always get the following error:
The following errors have occurred.

(14) The referrer, relay response or receipt link URL is invalid.

Authorize do not even redirect back to the Odoo website.

Is there any documentation on how to setup authorize?

Thank you.

**Comment by vonpupp** [comment]
Nevermind, I could solve this.

I think it was a `base_url` problem that didn't have https.

Thank you anyway.
