### ISSUE TITLE
[10.0 Community] Frequent Session Expired messages with multiple open windows

### ISSUE THREAD

**Issue by augustosamame** [odoo/odoo#14062]
Impacted versions: 10.0

Steps to reproduce: Open multiple windows with same user. Log out in one window. Log in again.
The issue does not appear when a single window is open.
Chrome on Mac OS: Version 54.0.2840.71 (64-bit)
No extensions messing with cookies.

Current behavior: After 2 or 3 screens will get a Session Expired error message and will redirect to login.

Traceback (most recent call last):
  File "/opt/odoo/odoo-10.0/odoo/http.py", line 638, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo-10.0/odoo/addons/base/ir/ir_http.py", line 184, in _dispatch
    auth_method = cls._authenticate(func.routing["auth"])
  File "/opt/odoo/odoo-10.0/odoo/addons/base/ir/ir_http.py", line 112, in _authenticate
    getattr(cls, "_auth_method_%s" % auth_method)()
  File "/opt/odoo/odoo-10.0/odoo/addons/base/ir/ir_http.py", line 85, in _auth_method_user
    raise http.SessionExpiredException("Session expired")
SessionExpiredException: Session expired

1 out of 10 I will get the following error instead:

Bad Request
Invalid CSRF Token

Expected behavior:

Session should not expire

**Comment by robertallanroker** [comment]
I get the same error but on every pages request.  Implemented using reverse proxy and db_filter.  Have no idea...

**Comment by augustosamame** [comment]
I fixed my issue by just clearing cache and cookies each time I switched databases. It's a nuisance but something that should not happen to actual users, but only to us integrators. In the case of users my production URLs include the target database just in case: www.myoddo.com?db=mydbname

**Comment by dreispt** [comment]
Multiple tabs share the same Odoo session.
When you change login in on Tab, all the others "expire".
The best solution to have two different at the same time is to use "Private Window" browser session, or even a different browser.

**Comment by augustosamame** [comment]
Yes that makes sense, but it's not what's happening.
What is happening is that even if you log into odoo in an active tab while
selecting a different database,  it will appear to work,  but after a
couple of clicks you get the session expired error and get kicked back to
the database selection screen.

**Comment by dreispt** [comment]
Yes, when I said "change login", that includes changing your database. As long as the URL is the same, you can't have two tabs with login sessions (to different or same databases).

**Comment by osluys** [comment]
@augustosamame If users are sharing a computer, then it is something that could happen to them. This behavior doesn't really have anything to do with switching databases (see my explanation further on down), so including the target DB in the URL doesn't prevent it.

**Comment by osluys** [comment]
@dreispt You can't reasonably expect end users (usually technically less literate) to remember to open a private session everytime they want to login using a shared computer. Ditto for using different browser profiles. The most likely scenario is that one user logs off of Odoo and another user logs in.

**Comment by osluys** [comment]
The session expiration error occurs because an old window/tab from a previous login is sending a polling request to the Odoo server. The server receives the request and somehow determines that it is not from the same user and acts as if the current user's session has expired, thus kicking off the user and forcing a login again.

I have confirmed this by logging into Odoo as _admin_ and then middle-clicking a link to open a second tab. I then logged off in the first tab and logged in as _demo_ and pulled up Firefox's developer tools to watch the network monitor in both tabs. As soon as the second tab sends a _poll_ request and afterwards you make a request in the first tab (clicking a link, polling, etc.), you'll get the error message.

**Comment by gdgellatly** [comment]
@dreispt There are better solutions to having multiple active sessions than private windows or seperate browsers.

Firefox Beta has support for multiple sessions built in https://testpilot.firefox.com/experiments/containers/
Before containers there was another extension - I forget the name.
 
Chrome has plenty of 3rd party extensions, I think the one I use is called SessionBox.

A must for development, rather than private windows.

**Comment by dreispt** [comment]
@gdgellatly :+1: I've been also using Firefox containers since that was released.

**Comment by Yenthe666** [comment]
Hey all,

As already answered: multiple tabs of the same URL will get you into troubles. This is known and not considered a bug. You'll either need to use private tabs or different browsers when you log in and off in multiple tabs.

Regards,
Yenthe
