### ISSUE TITLE
Database backup over xmlrpc leads to exhausted memory

### ISSUE THREAD

**Issue by funbaker** [odoo/odoo#14154]
Impacted versions:
8.0, 9.0, 10.0

Steps to reproduce:
Install on a system with low memory.
Create and fill a database, so that it is larger than available memory.
Try to backup it with https://github.com/Yenthe666/auto_backup

Current behavior:
In the background, this Exception is raised:

```
Traceback (most recent call last):
File "/*/odoo/openerp/service/wsgi_server.py", line 56, in xmlrpc_return
result = openerp.http.dispatch_rpc(service, method, params)
File "/*/odoo/openerp/http.py", line 115, in dispatch_rpc
result = dispatch(method, params)
File "/*/odoo/openerp/service/db.py", line 379, in dispatch
return g[exp_method_name](*params)
File "/*/odoo/openerp/service/db.py", line 160, in exp_dump
return t.read().encode('base64')
File "/usr/lib/python2.7/encodings/base64_codec.py", line 24, in base64_encode
output = base64.encodestring(input)
File "/usr/lib/python2.7/base64.py", line 313, in encodestring
for i in range(0, len(s), MAXBINSIZE):
MemoryError
```
(Examine the Exception caught in https://github.com/Yenthe666/auto_backup/blob/9.0/auto_backup/backup_scheduler.py#L163 to get the error message above)

```return t.read().encode('base64')``` allocates a HUGE amount of memory, depending on database size.

Expected behavior:
Business critical automatic backups are running without exhausting all the memory.
Response is returned in chunks.

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
@JKE-be, @mart-e and @odony could I ask you guys for feedback please? I have several people that have this problem and it looks to come back from the Odoo side.
Do any of you guys have a clue?

**Comment by odony** [comment]
@funbaker @Yenthe666 I'm afraid this is to be expected. RPC protocols such as XML-RPC and JSON-RPC serialize the RPC calls using a single root container data structure, which must be finite and in-memory at the time of the call/response. I don't see how you could possibly return a result that does not fit in memory, because the server wouldn't be able to construct the response packet. The protocol would need to support a streaming mode natively, or you would need to implement it yourself by exchanging smaller finite packets and re-assemble them on the other side.
So I would say this is a limitation of the protocols, and you should never try to retrieve backups via one of the RPC protocols if you want to avoid memory errors.

Fortunately this should be a minor concern because Odoo exposes an HTTP route for retrieving backups using a streaming encoding: `/web/database/backup` as implemented [here](https://github.com/odoo/odoo/blob/62b3de52dccc1c6b9e16e5a86320524efb474ad4/addons/web/controllers/main.py#L681-L697). This is what is used by the database manager, and presumably what the `auto_backup` module should do to avoid memory issues.
