### ISSUE TITLE
[10.0 Community] It does not show well taxes on e-commerce

### ISSUE THREAD

**Issue by nuelgoz** [odoo/odoo#14162]
Impacted versions:[10.0 Community] docker ODOO_RELEASE 20161103

settings taxes is marked as version 9 to display the price with tax included, but in version 10 ecommerce shows prices without tax, only it shows the price with taxes at the end of the purchase.

https://goo.gl/xUy8KL

**Comment by JKE-be** [comment]
Hello,

Check the user that add the item to the cart (public, admin, ...).
In case of public user, the fiscal position is detected on geolocalization.
In other case, it should follow the behavior from the backend.

If you see the tax only at the end, it is probably because before it, we don't know the country, and so the tax to apply.

Take the case where you have an belgian ecom , you don't add tax if the customer is in US, so we cannot show the belgian tax by default. Else you will lost your US customer because price is wrong.

The best way to test in test environment, is to have a IP that can be geolocalized... or uses an existing user with the country correctly set.

**Comment by treviser** [comment]
According to my understanding, in the EU and other countries, it is mandatory to show prices including taxes in B2C, even if it is not possible to know a priori where the anonymous visitor is located.

**Comment by JKE-be** [comment]
@treviser thanks..  any source ?

**Comment by treviser** [comment]
We had a lenghty discussion on the Odoo mailing lists a couple of months ago. There is also a discussion starting here: https://woocommerce.com/2014/12/handling-eu-vat-woocommerce/#comment-1565795
I know, that's not reliable source, it's just to make aware. I'll dig out some official sources soon.

**Comment by nuelgoz** [comment]
Solved, it was a configuration failure, this works ok

![captura de pantalla de 2016-11-08 09-39-20](https://cloud.githubusercontent.com/assets/9434922/20092259/6533eae8-a597-11e6-84bd-197b13fe360e.png)

**Comment by JKE-be** [comment]
@nuelgoz yes, mode b2c show price tax included, but as specified, it is based on localization to detect the fiscal position... 

@treviser, According to your link, it seems that some laws forbid to change price during checkout, but their are no 'realist' way to do it. I don't like the suggested idea to ask to the user the shipping country before to show the price... that is just to ruin your business. And I don't like the idea to change the unit price according to the tax to match the first price displayed with a mean of tax... there are no sens in most business...  Open to find a realist solution... but not with a crappy idea like suggested in woocommerce post. (That's remind me another law: https://silktide.com/wp-content/uploads/2013/01/Cookie-Law-summarised.png)

**Comment by treviser** [comment]
@JKE-be You are so right, but law is law. As far as I know, this law is for sure valid for digital products, but I remember that at least in some EU member states it's valid for all products in distance/online sales. I'll do some more research in order to clarify the issue.
