### ISSUE TITLE
Drag and drop in list view

### ISSUE THREAD

**Issue by jacobuserasmus** [odoo/odoo#141734]
Impacted versions: 17

Steps to reproduce: Open product category list view, 

Current behavior: When you click on the category on the list and drag the mouse it selects the text in the rows

Expected behavior: The view is hierarchical, meaning that you can move the categories to be part of other categories. I expected that when selecting an item I could drag and drop it to link it to another parent. (It could also have a handle to accomplish this). Considering the new GUI changes to 17 I expect these type of things to start working.

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by vava-odoo** [comment]
Hi @jacobuserasmus 
Thanks for your message. 

> Considering the new GUI changes to 17 I expect these type of things to start working.

Yes, it works, see for example product pricelist list view

The problem is that it requires an additional field on the model, so it is not automatically added. For the same reason, it won't be changed in stable.

I'll do the feedback internally for an improvement in next version.

Cheers!
