### ISSUE TITLE
"Street" name from address is added on "Company Name" of "Billing Information" page on website.

### ISSUE THREAD

**Issue by bista-amitd** [odoo/odoo#14228]
Impacted versions:
9.0 + Enterprise

Steps to reproduce:
Put Full Address on partner of user named "Demo User"
Now purchase anything with this user on website
Click on "Process Checkout" and see the "Billing Information"

Current behavior:
You will find address added on street field is on "Company Name" which is wrong

Expected behavior:
Either Street and Street2 should be added on Street field of website page or Street 2 should be added on page so both value can be set on their field.

And i think portal user will not have company so it label can be changed to street2

OPW  is posted #693469

[out-14.ogv.tar.gz](https://github.com/odoo/odoo/files/580319/out-14.ogv.tar.gz)

Video/Screenshot link (optional):

**Comment by JKE-be** [comment]
Thanks for the reporting.

Duplicated of:
https://github.com/odoo/odoo/issues/2541
https://github.com/odoo/odoo/issues/11619
https://github.com/odoo/odoo/issues/12541
https://github.com/odoo/odoo/issues/12590
https://github.com/odoo/odoo/issues/13198

It has been by design, until v10, to avoid the duplication of res_partner.

In v10 it has been updated, using a real field company_name instead of street2 and a button to create the real res_partner.

Thanks
