### ISSUE TITLE
Arabic letters issue in PDFs downloaded from Sign Module

### ISSUE THREAD

**Issue by MasoudEBS** [odoo/odoo#143283]
Impacted versions:
16 , 17 

Steps to reproduce:
- Upload PDF To Sign
- Add ( Text, Name or multi-line Text) Item Type
- Begin signing and writing in Arabic.
- Download PDF after signing.

Current behavior:
- The Arabic words appear with strange letters in the downloaded PDF. However, it looks fine in the Preview.

Expected behavior:
- Downloaded PDF should be as the Preview

Video/Screenshot link (optional):
![arabic issue](https://github.com/odoo/odoo/assets/93579327/339c1200-f940-4cd8-8928-8f0638e7bf0a)
![arabic issue1](https://github.com/odoo/odoo/assets/93579327/c1eb74b2-7299-47bb-851c-072af2e8d7c8)
[sample-nda.pdf](https://github.com/odoo/odoo/files/13446804/sample-nda.pdf)

**Comment by vava-odoo** [comment]
Hi @MasoudEBS 
Maybe @sleepy-monax could help, if it is related to wkhtmltopdf?
Cheers

**Comment by sleepy-monax** [comment]
@vava-odoo It's not related to wktmltopdf, I'm able to render page with arabic text without issue

**Comment by nabilragab** [comment]
are we able to solve this open issue ?

**Comment by leonardopavanrocha** [comment]
@arj-odoo just FYI!

**Comment by arj-odoo** [comment]
Hello :wave: Thanks for the report. I already answered to @MasoudEBS  in https://github.com/odoo/odoo/pull/165774#issuecomment-2194112581 but I will close the ticket and explain the steps to fix this for future user who would like to handle correctly Arabic content in sign.

 If you want to handle Arabic content in sign, you need two things. 

First the font must be correctly configured? It will prevent the black box you are observing. See the linked comment, you need to define the ir.config.parameter "sign.use_custom_font". 

Secondly, Arabic is quite different from Latin languages.  Arabic letters are not displayed properly in 16 and 17. In particular they have the correct direction but lack ligature, since Arabic letters have different shapes depending on the surrounding letters. They were displayed in one shape only (The isolated shape).
We fixed that issue in master recently. It is not possible to back port this easily as the diff is quite big and it rely on a big change in the base module. 

Thanks @leonardopavanrocha for the ping ! :wave:
