### ISSUE TITLE
Binary Field: widget='pdf_viewer', download option doesn't appear when the field is defined inside notebook.

### ISSUE THREAD

**Issue by deepa4lok** [odoo/odoo#14322]
**_Impacted versions:_**
Odoo 10E
I have a binary field, on which I has specified widget='pdf_viewer', which works perfectly for open, downloading etc.
However when the same is placed inside notebook, it expands and fits into the notebook-page, which is absolutely fine, but I could not find the top 2 options, which includes 'open', 'download' options.

**_Steps to reproduce:_**
Create a 2 fields of type Binary, say fieldA, fieldB

In XML views,
place the fieldA in the form, inside a group.(portrait view)
similarly place the fieldB inside a notebook & into page (landscape view)

**_Current behavior:_**
In Portrait View, Options for open & download are accessible from drop-down list, which is great.
In Landscape View, Options for open & download are missing

**_Expected behavior:_**
In Landscape view, I believe an icon is placed just like Current-view option, but it failed to load, please find the screens attached

**_Video/Screenshot link (optional):_**

When a field in declared inside form (portrait view)
 
![image](https://cloud.githubusercontent.com/assets/8802906/20301357/01649d84-ab49-11e6-85bc-0749bc6cccd8.png)

When the field is declared inside Notebook (Landscape View)

![image](https://cloud.githubusercontent.com/assets/8802906/20301448/57384864-ab49-11e6-8029-46c25fd659e0.png)

**Comment by pedrobaeza** [comment]
Is this still happening on latest compilation?

**Comment by hw-aka** [comment]
I can confirm that this issue still exists today (Odoo 11.0+e on Odoo.sh).

In the mobile view, when the width of the iframe is no more than 660px, the download button is displayed under the "Tools" menu.
![small](https://user-images.githubusercontent.com/34575341/40595254-ef5e0dea-6209-11e8-86b9-c23d0890a2fc.png)

When the width is more than 660px, the download button is supposed to be displayed in the right side of the toolbar, but it is not visible on both the toolbar nor the tools menu.
![large](https://user-images.githubusercontent.com/34575341/40595284-27e7226e-620a-11e8-9359-2a04f24e371e.png)

Expected behaviour when width is big - download button on toolbar
![expected](https://user-images.githubusercontent.com/34575341/40595333-50d4a250-620a-11e8-81d1-801dc2e933ba.png)

**Comment by pedrobaeza** [comment]
Thanks for the detailed explanation.

@qsm-odoo I think this is something for you.

**Comment by qsm-odoo** [comment]
@ged-odoo

**Comment by ged-odoo** [comment]
fixed in master

**Comment by Zdakman** [comment]
hello, @ged-odoo, may be it is dramatical question, but, i want to desable the download button into the navigation bar from the pdf_viewer widget?

**Comment by Yenthe666** [comment]
@Zdakman thats not really related to this ticket. You'll need to inherit the JS functions and remove/make it unclickable there.

**Comment by Zdakman** [comment]
> @Zdakman thats not really related to this ticket. You'll need to inherit the JS functions and remove/make it unclickable there.

I apologize for the question, @Yenthe666 and thankyou for your reply;
Where i can find the js file location defined this widget and witch template it uses?
