### ISSUE TITLE
variable 'datebirth' can named in view model lia ' cumpleaños'

### ISSUE THREAD

**Issue by Marcogb81** [odoo/odoo#14333]
Impacted versions:8.0.0.1

Steps to reproduce:datebirth = fields.Date(string='Nacimiento',required=True, translate = True)

Current behavior:'arch' not work, say datebirth do not sxist

Expected behavior: show field with title 'nacimiento'

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Hi @Marcogb81,

Thanks a lot for your report but the Github issue tracker is only for bugs in the official code, not for custom development.
I suggest you to create a new topic on the official Odoo help forums (help.odoo.com).
P.S: Please post both the Python and XML code too, otherwise we can't see what is wrong. This line of code looks fine.

Regards,
Yenthe
