### ISSUE TITLE
[bug]user who has administration access rights can create a user has settings rights

### ISSUE THREAD

**Issue by yueqin** [odoo/odoo#14355]
Impacted versions:
[10.0]
Steps to reproduce:
1. create a user 'father' who's rights to administration is access
2. login by user 'father'
3. create a user 'child', the father can give the settings rights to the child
Current behavior:
the father can give the settings rights to the child
Expected behavior:
The father user without the settings rights can't create a user with the settings right
Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
I agree with this consideration: a user that can create users but not fully right, shouldn't be able to change its permissions to a higher grade or create other user with that rights.

@odony this can be considered as a security problem, but not in the traditional way of vulnerability. Can you please check?

**Comment by odony** [comment]
Anybody with the first level of access credentials (Access Rights) is a super-user, because they can change all access rights, and through this, do whatever they want with the system and data.
The 2 administration levels "Access Rights" and "Settings" are therefore equally powerful - the difference is in terms of usability and avoiding mistakes by hiding some features. There would be no point trying to restrict them in different ways. Unless we completely revamp all access rights, which is clearly not the point of this issue.

**Comment by pedrobaeza** [comment]
The problem is that when you want someone to admin users, you need to give him/her full control, which is the problem as we (as implementators) have with some customer power users. Can we think about a solution on this?

**Comment by pedrobaeza** [comment]
What I'm trying to protect is that they install more modules (I know that you can install them by checks in the configuration part, but this is another "entry point" that can be mitigated easily).
