### ISSUE TITLE
[10.0] There is no option to reprint POS receipts

### ISSUE THREAD

**Issue by smartupdo** [odoo/odoo#14391]
Impacted versions:
10.0

Steps to reproduce:
Enable reprinting on both module settings and point of sale settings. Make a sale, go to Orders and attempt to reprint the receipt.

Current behavior:
Option to reprint the receipt is not shown.

Expected behavior:
On the Order screen, a reprint button is expected to show as in 9.0

Video/Screenshot link (optional):
https://www.odoo.com/documentation/user/9.0/_images/reprint05.png

**Comment by mart-e** [comment]
Hello,

Sorry but this button was removed at 0650047fd59bd5fb28e2ba5f1c9bb47a95295980 in 10.0 to promote backend reports.

**Comment by sbidoul** [comment]
@mart-e allow me to reopen on old one.

What do you mean exactly by *promote backend reports*? As far as we can see, there is no way in v10 to reprint a single receipt as it was possible in v8, nor from the frontend nor from the backend, and customers are complaining.

**Comment by mart-e** [comment]
Seeing the commit message, I believe it was intended _frontend_ reports. We have the reprint the last ticket option.
However, I agree with you, there, at the moment, no way to reprint a specific ticket.

**Comment by wtaferner** [comment]
@sbidoul 
I started an initiative in https://github.com/odoo/odoo/pull/16452 and @jorenvo provided an improvement in https://github.com/odoo/odoo/commit/4d461cbe4170e8d5dbdb0c6bef1b313982d064fd (I guess you can easily backport) whereas I was resolving the issue of global reprinting quick and dirty in the PoS by saving the print_xml and print_html (posbox and local) to the backend and getting it on demand and ticket number in the frontend like customer, etc.

I wonder if at some point we will have a single point of PoS receipt...based on the removal in the backend there are only two ways of representation instead of three ways in v8.

**Comment by sbidoul** [comment]
@wtaferner thanks for the pointer! cc/ @Cedric-Pigeon

**Comment by Ark74** [comment]
@wtaferner So this won't let (re)print a passed ticket from the order archive?
I got lost.

**Comment by wtaferner** [comment]
@Ark74 
Nope, not out of the box, it will let you reprint the last order also on a local printer (this is what Joren fixed)

**Comment by Ark74** [comment]
Ohh!
Ok. I'll try again with v10.

**Comment by wtaferner** [comment]
@Ark74 
You need to backport first to v10 does not support it at the moment.

**Comment by Ark74** [comment]
Ohh. Then it makes sense why I keep getting those errors.

Thanks for the heads up :)

El 5 de octubre de 2017 1:25:09 AM CDT, Wolfgang Taferner <notifications@github.com> escribió:
>@Ark74 
>You need to backport first to v10 does not support it at the moment.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/odoo/odoo/issues/14391#issuecomment-334370279

-- 
Enviado desde mi dispositivo Android con K-9 Mail. Por favor, disculpa mi brevedad.
