### ISSUE TITLE
[Enterprise 10.0] Currency doesnt change based on company currency

### ISSUE THREAD

**Issue by thegunshow** [odoo/odoo#14400]
Impacted versions: Enterprise and community 10

Steps to reproduce: Change company currency from USD to ZAR (South Africa). Go generate a quote.

Current behavior: The pricing remains as USD or has no currency symbol in the front.

Expected behavior: $24.00 -> R24.00. The only way I can get this to work is to create a price list and set a location to South Africa, then use that price list.

Video/Screenshot link (optional):

**Comment by filsav** [comment]
I confirm this behaviour, Odoo Community 10.

**Comment by AEK-BKF** [comment]
same with me 
:+1:

**Comment by AEK-BKF** [comment]
Ok I've found the solution ^^ (Sorry I'm newer in Odoo)
Just activate your currency to appear in the list :)

**Comment by csnauwaert** [comment]
Hello,

Actually all the active currency and their symbol are stored browser side when odoo is loading. Which means that if you activate a new currency like ZAR and change the company currency to ZAR then try to create an invoice, no currency symbol will be displayed because it has not been reloaded in your browser. However if you reload your page by pressing F5 or ctrl+F5 the problem will be fixed. Please note that even if nothing is displayed, the currency is still correct and next time you'll load Odoo in your browser, everything will be displayed correctly even the previously created entry where no symbol where visible.

Best regards
