### ISSUE TITLE
[sale] "quotation" not translated

### ISSUE THREAD

**Issue by guestisp** [odoo/odoo#144697]
Hi guys
in v17, when sending a quote to a customer, the "quotation" string inside the email body is not translated.

Even the email subject is not translated. is the Italian translation incomplete ?

**Comment by vava-odoo** [comment]
Hi @guestisp 
Indeed, this was not translated when you opened the issue. It is now, since [this change](https://github.com/odoo/odoo/commit/8ab45d4a8562ff117122867f46282d5b04e57674#diff-6672aaf76d78e2cf30f2dd68bde5479e3f005ea5f7037b8c5c51ed64c7163dccR649).
For further information, please check the [translation documentation](https://github.com/odoo/odoo/wiki/Translations), the translations are handled on [Transifex](https://explore.transifex.com/odoo/), not Github.
Cheers
