### ISSUE TITLE
Problem with Contact Details Page

### ISSUE THREAD

**Issue by hurrinico** [odoo/odoo#14461]
Impacted versions: 9.0

Steps to reproduce: 
 - Install website_portal module
 - Go to sale, Open partner linked to to your user, Fill street field save
 - Go to website, click on your user name on the right-top of the page, click on my account and click change near your name on the left.
 - Now watch the form

Current behavior:
You will see Company Name div filled with street field

Expected behavior:
Company Name div filled with company name 
and street div filled with street name

**Comment by eLBati** [comment]
Fixing with https://github.com/odoo/odoo/pull/14473

**Comment by JKE-be** [comment]
Thanks for the reporting.

Duplicated of:
https://github.com/odoo/odoo/issues/2541
https://github.com/odoo/odoo/issues/11619
https://github.com/odoo/odoo/issues/12541
https://github.com/odoo/odoo/issues/12590
https://github.com/odoo/odoo/issues/13198

It has been by design, until v10, to avoid the duplication of res_partner.

In v10 it has been updated, using a real field company_name instead of street2 and a button to create the real res_partner.

Thanks
