### ISSUE TITLE
many2many_tag widget not underlined when required field

### ISSUE THREAD

**Issue by sodabuzz** [odoo/odoo#14519]
Impacted versions: Noticed on 9.0 Enterprise

Steps to reproduce: Use the widget many2many_tag and set the field as required

Current behavior: Not displayed as a required field

Expected behavior: The filed would be displayed with an underline

Video/Screenshot link (optional): 
![bug001](https://cloud.githubusercontent.com/assets/10454279/20718784/256bf03a-b65a-11e6-9213-d5f14f95c326.png)

**Comment by pedrobaeza** [comment]
Is this something about enterprise interface?

**Comment by Yenthe666** [comment]
Hi @sodabuzz,

Thank you for the report.
I've just tested this and your issue has been fixed in the meanwhile. I've made the `many2many_tag` required for a field in fleet and it is showing the required color on 9.0:
![image](https://user-images.githubusercontent.com/6352350/39614749-709837c8-4f72-11e8-9e73-d826f56361a2.png)
