### ISSUE TITLE
QuotaExceededError on Safari Private Browsing Window

### ISSUE THREAD

**Issue by lslaz1** [odoo/odoo#14579]
Impacted versions: Safari Version 9.0.3, Odoo V 9.0

Steps to reproduce: Open Safari private browsing window, log in to an Odoo db

Current behavior: After logging in a pop up appears with error:

`QuotaExceededError: DOM Exception 22: An attempt was made to add something to storage that exceeded the quota.`

Expected behavior: Log in directs you to Odoo backend without error.

Video/Screenshot link (optional):

<img width="1440" alt="screen shot 2016-12-03 at 9 50 09 am" src="https://cloud.githubusercontent.com/assets/10367837/20860440/eed4a332-b93d-11e6-80cc-18c4310cf4b7.png">

**Comment by aab-odoo** [comment]
Hello,

What is the impacted version of Odoo?

Regards

**Comment by lslaz1** [comment]
Oh yes, I apologize!

Odoo V9.0

**Comment by adr-odoo** [comment]
Hello,

This issue has been fixed in saas-12 by these commits:
https://github.com/odoo-dev/odoo/commit/8580636bad43df2b4879b1985965a766cb796543
https://github.com/odoo-dev/odoo/commit/a9b05611060478c96d3b14b5892a5285900258ec

Unfortunately, Odoo does not support Safari private browsing in 9.0.
Sorry about that.

Greats,
