### ISSUE TITLE
[17.0][Rental] Calendar icon not available for select the rental period

### ISSUE THREAD

**Issue by nithwith** [odoo/odoo#146177]
Impacted versions: 17.0

Steps to reproduce:
Go to rental module and try to schedule a new rental for two days 

Current behavior:
The calendar icon is not available so you can't change the period of your rental.

Expected behavior:
The calendar icon in the red square

Video/Screenshot link (optional):
![image](https://github.com/odoo/odoo/assets/19471913/18fe35c8-ac64-4e95-a22a-be56e33c5286)

**Comment by vava-odoo** [comment]
Hello @nithwith 
In 17, the rental period moved from sale order line to sale order (one period for all lines). You'll be able to change it a bit above (Rental period).
Cheers

**Comment by fahhadalsubaie** [comment]
@vava-odoo I can only control all items at once, what about if I want to assign different rental periods for each item?

**Comment by vava-odoo** [comment]
Hello @fahhadalsubaie 
Yes, since 17, one SO = one rental period, but you can still have early pickup and late return.
This is a trade-off that was made to make it evolve further and keep things simple. This change now allows users to
- use catalog, quotation templates and optional products in Rental;
- change the rental period of all lines at once;
- handle the stock with a better integration with other inventory modules;
- simplify the quotation step with the deletion of the wizard.
There was a talk about what's new in rental at the OXP, in case you missed it https://www.youtube.com/watch?v=jF_t_KqdThc
Cheers
