### ISSUE TITLE
Odoo not converting Foreign Currency product price in a Invoice if the Invoice Date is >= first Foreign Currency Rate Update

### ISSUE THREAD

**Issue by marciorpbradoo** [odoo/odoo#14611]
Impacted versions: saas-10

**Steps to reproduce:**
**Assuming the steps are being produced in a fresh Odoo database, where the company currency is BRL.**
- Install Accounting
- Open Accounting
- Create a product and add a price in BRL
- Activate Multi-Currency Support & click "Update Now"
*At this point, Odoo has only the currency rate of the current date.
*My Enabled Currencies are: BRL (company currency), EUR, USD. They can be enabled in Configuration > Currencies, inside the Accounting Module.
- Create an Invoice, where the Invoice Date is < Current Date
- Set the Invoice Currency to be EUR or USD
- Add the product to the Invoice
- Save the Invoice

**Current behavior:**
The price is not converted to the Foreign Currency that was set on the Invoice.
This happens because according to the system rules, the currency rate used inside a Invoice is always from the previous day, in this case, the currency rate was just updated and it's going to be used tomorrow. So we have no applicable currency rate to use for Invoices that might have happened before.

**Expected behavior:**
There should be a warning informing the user that there is no applicable Currency Rate for the Foreign Currency being used on the Invoice, and that's why the price wasn't automatically converted.

**Video/Screenshot link (optional):**
This is an example. This product has it's price in BRL. Instead of converting the corresponding value to USD, Odoo just changed the currency symbol. If it had a usable Currency Rate for the date of this Invoice the value would've been converted.
![captura de tela de 2016-12-06 13 15 31](https://cloud.githubusercontent.com/assets/22821998/20930940/7a9f1544-bbb6-11e6-88d3-82d3661db359.png)

**Comment by gustavovalverde** [comment]
I can confirm this @qdp-odoo. 

Actually, before an invoice (or payment) can be validated in a foreign currency there must be a currency rate set for that date.

**Comment by pedrobaeza** [comment]
I consider this that it's normal initial setup that you set correctly the initial rates from the beginning of the activity, but I let @qdp-odoo the final word.

**Comment by qdp-odoo** [comment]
I agree with @pedrobaeza : this can't be considered as a bug. 

Moreover, the fact that the rate only applies on tomorrow is no longer a problem since we changed to a date instead of a datetime, in res.currency.rate

**Comment by jtbr** [comment]
I'll say for a new user like me, this functionality was very difficult. In Settings I had already set up an exchange rate provider and selected for automatic daily updates. However it had apparently not updated yet, and there were no manually entered exchange rates. As such when I imported transactions from my banks, they did not have the right exchange rate and the differences showed up as differences in the suspense account (trying to enter correct currency valuations for bills led to bizarre results) This was very tricky to fix even once I found where to and manually added exchange rates, as all the bills and references had to be removed and re-created. And I only thought to do this because I found this bug! At a minimum, a warning should be given if you create records that require an exchange rate and none are yet in the database. Better than that, if there is provider, an exchange rate should be automatically downloaded, or confirmed by/requested of the user. 

I would strongly encourage you to re-consider fixing this issue.
