### ISSUE TITLE
[10.0] WYSIWYG editor ignores changes made in the code view when saving

### ISSUE THREAD

**Issue by Yenthe666** [odoo/odoo#14648]
Impacted versions: 9.0, 10..0

Steps to reproduce:
1. Activate technical features
2. Go to mass mailing, open a template and edit it in the code view. Remove a part of the text (for example "You get a 20% discount for signing up!")
3. Click on save without changing from the code view to the graphical view.
4. Behold, the code (text) you've just removed is still there:
![image](https://cloud.githubusercontent.com/assets/6352350/21004032/ae21250a-bd2e-11e6-9dce-a3f1386f2904.png)

If you do the exact same proces but change from the code view to the graphical view it will be updated and saved. It looks as if you're in the code view and click on save that the changes are not appended on the record.

Current behavior:
Changes in HTML fields are ignored if you're in the coding view and save right away.
This is the case for every HTML field in Odoo.

Expected behavior:
Changes in HTML fields are kept if you're in the coding view and save right away.

**Comment by Yenthe666** [comment]
Hi @nle-odoo, perhaps this is related to https://github.com/odoo/odoo/commit/a6e3ae6b8c08b3e2abfda248b5f77a1781244683 or one of the other commits about this? Could you have a look at it?

**Comment by nle-odoo** [comment]
Hi.

Passing back to wysiwyg view is the current needed behavior. I heard there was at one time no way to save in code view (you needed to get back on wysiwyg view but now it is not explicit).

https://github.com/odoo/odoo/commit/897290dd3ff was changing this fact by clicking automatically to get back in wysiyg, but was reverted because of introduced issues.

A fixed fix should be introduced soon with : https://github.com/odoo/odoo/pull/14475

Regards,
