### ISSUE TITLE
[v9] Q: how to override *all* twitter bootstrap variables properly

### ISSUE THREAD

**Issue by simahawk** [odoo/odoo#14657]
bootstrap resources are loaded indirectly with [this line ](https://github.com/odoo/odoo/blob/9.0/addons/web/views/webclient_templates.xml#L103) that loads [import_bootstrap.less](https://github.com/odoo/odoo/blob/9.0/addons/web/static/src/less/import_bootstrap.less) that in turns does `@import "bootstrap";` that "magically works" (bootstrap.less is not exposed at all).

I guess the magic happens because of [this trick in ir_qweb](https://github.com/odoo/odoo/blob/9.0/openerp/addons/base/ir/ir_qweb.py#L1694).

If you try to import local file variables in your theme you sometimes get an error like "Local import '%s' is forbidden for security reasons." because of [this sanitization](https://github.com/odoo/odoo/blob/9.0/openerp/addons/base/ir/ir_qweb.py#L1433).

I tried to override the import_bootstrap.less to make it import my copy of bootstrap but then I get the error above...

What is the correct and official way (if any) to override bootstrap variables (or any other bootstrap component) then?

**Comment by pedrobaeza** [comment]
I think @ged-odoo can be the correct guy to answer this.

**Comment by simahawk** [comment]
hmm, I just did a test.

Before I had `@import variables.less` inside my `styles.less` (as you usually do in LESS theme files) + a line to load the variable in the frontend assets (otherwise LESS compilation is broken).

Now I removed `@import variables.less` aaaaaand: it magically worked! :)
I thought that since my variables are loaded after all bootstrap*less stuff it could not work, but sounds like it is...

@ged-odoo can you provide any insights on how it works?

**Comment by pedrobaeza** [comment]
I remember that @Yajo told me that there's some "magic" imports that make this to work without import, but he's on holidays and I didn't remember the piece of code that makes this.

**Comment by Yajo** [comment]
Hi @simahawk, I think you are falling in _the way we usually program vs. the way to program Odoo_ problem. I worked with @antespi in #13710 and we realised current asset bundling in Odoo is quite weird, but quite hard to fix without losing features too. They are removing local references for some kind of security hole (not sure which). This also affects why we cannot have normal NPM packaging like in #14258.

I think it's part of Odoo's NIH syndrome, but in short **what you have to do is add your `varialbes.less` to the `website.assets_frontend` (or whatever) view**, and then it gets loaded and taken into account.

Remember that LESS is supposed to declare variables after using them, so add it at the end.

This will be closed I guess, as this is by design. I'm not saying I like that design, but that's what we have...

**Comment by ged-odoo** [comment]
Dear All, Yajo is totally and completely right. The tricky part is that in LESS, the last definition of a variable is the one that counts (less compiler read all variables, and only then generates the css), so your overrides will be used instead of the default value.  Currently, Yajo's answer is the 'odoo' way to do it.

Maybe someday we will be closer to most other web projects, but that is not for now.

**Comment by simahawk** [comment]
@Yajo @ged-odoo that's what I discovered indeed. Thanks for the explanation :)

**Comment by Yenthe666** [comment]
Woha - I was totally bitten by this too today.
Thanks a lot for the answer/fix @simahawk.
@ged-odoo couldn't we expand that warning message? At the moment we have:

> Local import '%s' is forbidden for security reasons.

What about:

> Local import '%s' is forbidden for security reasons. Please remove all @ import "your_file.less" imports in your custom less files. In Odoo you have to import all less files in the assets and not through the @import statement.

Something along these lines would have saved me like an hour.
