### ISSUE TITLE
[16.0 Enterprise, 17.0 Enterprise] Shift Template Planned End Hours are badly calculated

### ISSUE THREAD

**Issue by sergueikp** [odoo/odoo#146658]
Impacted versions: 16.0 and 17.0 Enterprise

Steps to reproduce:
Go to Planning > Configuration > Shift Templates and create a new template
Specify Planned hours start : 20:00
Duration: 05:00 hours

Current behavior:
Planned End hours is badly calculated, 
for example if you specify Start & End Hours (Planned hours) at 20:00 and duration 05:00 hours, End hours will be 14:00

Expected behavior:
End hours should be 01:00, because 20:00 + 5 hours == 01:00 on the next day. 

Video/Screenshot link (optional):
Version 17.0
[Shift_Template_hours_v17_bug_1.webm](https://github.com/odoo/odoo/assets/9844780/dd2dac7a-d4fb-4d7b-a313-46766fdd17d0)

Version 16.0
[Shift_Templates_v.16_bug_1.webm](https://github.com/odoo/odoo/assets/9844780/9b57fa0b-3046-4a1b-a4fd-5462cce4fe6c)

Support ticket number submitted via odoo.com/help (optional): 
I have a subscription for Odoo Enterprise but for unknown reason it's impossible for me to create a support ticket via odoo.com/help

**Comment by xavierbol** [comment]
Hello @sergueikp ,

Thanks for the report! 

In fact, the end hours computed in shift template takes into account the working schedule (= resource calendar) of the current company, that's why you have that behavior.
We are aware we don't correctly manage with the flexible hours (the resource without any resource calendar) for the templates. However, if you select a template during the shift creation for a resource without resource calendar then it will normally set the date end that you expect on the shift. 

We have a task for the next version to manage the flexible hours and also improve the shift templates to facilitate the creation of those templates.

Thanks for your understanding!

I let the issue opened in the case you have other questions about shift templates. 🙂 

Have a nice day! 🙂
