### ISSUE TITLE
No database reference ID for "Quantity" and "Forecasted Quantity" when importing CSV into Products

### ISSUE THREAD

**Issue by WhitleyStriber** [odoo/odoo#14669]
Please forgive me if I'm ignorant, but I sat down today with a coworker and we couldn't figure out how to import product "Quantity" from a CSV file. We couldn't find any official documentation for Odoo 10 informing the user of the correct Reference ID that relates to Product Quantity. I see many other values listed but Quantity and Forecasted Quantity is not there. It also don't automatically reference the correct ID. I am seeing BOM Quantity, and it's confusing, even with the "Show all fields for completion (advanced)" checkbox ticked. Can anyone provide clarification? 

Impacted versions:
Odoo 10.0 (Community Edition)

Steps to reproduce:

1. Export a .CSV of all fields of any item from the Products menu
2. Import back into Odoo through the Product's import function

Current behavior:
Odoo does not reference "Quantity On Hand" and "Forecasted Quantity" automatically, and there isn't a drop-down Reference menu item for "Quantity."

Expected behavior:
"Quantity" and "Forecasted Quantity" should appear and reference correctly to the database. There should also be a drop-down menu item

Video/Screenshot link (optional):

![image](https://cloud.githubusercontent.com/assets/5761757/21063522/018e8926-be24-11e6-8648-843acf13350b.png)

**Comment by bistaray** [comment]
Certain fields in Odoo do not have values you can directly edit or upload.  These are called functional fields, because their values are computed from functions.

Both the fields you are looking for are functional.  Stock quantities are computed from stock moves that exist in the system - to allow Odoo to consider stock moves that are planned to happen but have not yet happened (when you want to deliver an item but have not yet delivered it, or plan to receive an item but have not yet received it).

You can import via Warehouse -> Inventory Control -> Inventory Adjustment - look there instead.

**Comment by Yenthe666** [comment]
Hi @WhitleyStriber,

@bistaray is in fact correct, because these fields are functional they're not directly accessible to import data on. It is indeed correct that you could trigger this from the stock moves (which populate the stock quantities for products).

Regards,
Yenthe
