### ISSUE TITLE
[10.0] Content Search Issue

### ISSUE THREAD

**Issue by iju-odoo** [odoo/odoo#14699]
Impacted versions: 10.0

Steps to reproduce: Go to Recruitment >> Application >> Add Document (.docx) >> go to Documents kanban view >> Search by content and type any word available in doc.

Current behavior: No result found

Expected behavior: Match content document display as a search result

Video/Screenshot link (optional):
![not_found_content](https://cloud.githubusercontent.com/assets/11677925/21141413/0110015e-c163-11e6-9955-58fb15cfc624.png)
![search_by_content](https://cloud.githubusercontent.com/assets/11677925/21141414/01173d5c-c163-11e6-8cc9-cbe2effc7212.png)
![with_content](https://cloud.githubusercontent.com/assets/11677925/21141415/01281ab4-c163-11e6-8499-e44e142df511.png)

**Comment by iju-odoo** [comment]
Please Provide Solution for that.

**Comment by pedrobaeza** [comment]
This is because the content of the document has not been indexed. You need extra libraries for some content indexing (poppler, antiword...), but I'm not sure if docx format is supported. Any way, there's no real issue, so closing this.

P.S.: You shouldn't use a nickname in GitHub with the same form of the Odoo's employees, as it leads to confusion that you are also an Odoo employee.

**Disclaimer**: I'm not an Odoo employee, but a community member that voluntary contributes to triage / classify / solve issues. Take also into account that there's no obligation to answer nor solving things put in Odoo Community issue tracker. And thus, please consider this as a best effort initiative.
