### ISSUE TITLE
What is the detailed configuration of the ODOO HA solution?

### ISSUE THREAD

**Issue by kangcehua471961457** [odoo/odoo#147435]
Impacted versions:

Steps to reproduce:

Current behavior:

Expected behavior:

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by khaymanii** [comment]
Please I don't really understand what this issue means, what configuration exactly do you mean?

**Comment by EmmanuelAjibokun** [comment]
@kangcehua471961457 Could you please elaborate on what the issue raised is about? I'm confused on what ODOO HA solution means.

**Comment by kalungia** [comment]
There is no question here, but if you are looking for docmenation go [here](https://www.odoo.com/documentation/17.0/applications/hr/attendances.html#:~:text=Inventory%20%26%20MRP-,Human%20resources,-Marketing)

**Comment by khushinj** [comment]
Impacted versions:       Odoo 16

  Steps to reproduce:     To solve this, please ensure we define a model inside a Many2One field like the code below.

' product_id = fields.Many2one('product.product', string="Product") '

 Current behavior:        AttributeError: '_unknown' object has no attribute 'id'

Expected behavior:      It should not show the issue
