### ISSUE TITLE
Import BoM doesn't recognize Apply on Variants / Attribute , Value, ...

### ISSUE THREAD

**Issue by advrider** [odoo/odoo#147853]
**Impacted versions:** 16.0

**Steps to reproduce:** Export a BoM that has Apply On Variants values. Check import-compatible box. Selecting these columns :

_BoM Lines/Apply on Variants
BoM Lines/Apply on Variants/Attribute
BoM Lines/Apply on Variants/Value_

**Current behavior:** When importing the file back, it does not recognize "BoM Lines/Apply on Variants" values. And has no option in the columns to select Attribute, Value, ... (The only available columns to select are : 
_BoM Lines/Apply on Variants
BoM Lines/Apply on Variants/External ID
BoM Lines/Apply on Variants/Database ID_

**Expected behavior:**
Since import-compatible is checked off during export, the columns provided in the export file should be available to select in the import page.

![2024-01-02 11_06_44-Window](https://github.com/odoo/odoo/assets/1637309/19e0affc-fa9e-498b-a477-de3bbb0f84d6)

**Comment by advrider** [comment]
**Correction:**
When I select "import-compatible" on 
_BoM Line/Apply on Variants
BoM Line/Apply on Variants/External ID_

are available to export.

Odoo still does not recognize the values in **BoM Line/Apply on Variants** column when importing back.

Values in BoM Line/Apply on Variants look like this:
attribute_name: value

**Comment by john-herholz-dt** [comment]
I am facing the same issue.
There is no official response right now, right?

I think the issue would be solved, if the actual attribute_id was used to identify the import instead of the product_template_attribute_id.

The product_template_attribute_id is unique per product template and when searching for an attribute value, it finds the same value applied on multiple product templates.

@vava-odoo , can we improve this behaviour?

Either by allowing to reference the attribute id on the import or by filter the results of the actual product that is used in the bill of material.

**Comment by vava-odoo** [comment]
Hello @advrider & @john-herholz-dt 
Don't know much about this, to be honest. Maybe @ticodoo could help here?
Cheers!
