### ISSUE TITLE
[16.0] account_edi: implement record limit for single job

### ISSUE THREAD

**Issue by salvorapi** [odoo/odoo#148849]
**Impacted versions**: 16.0

### Steps to reproduce:

You need to have an Odoo instance with EDI exchange enabled.

- generate a lot (i.e. 10000) of records inside `account.edi.documents` model 
- call the _cron_process_documents_web_services or the `ir_cron_edi_network` cron.

### Current behavior:

The current behavior is that only one single job with all records (i.e. 10000) are generated.

This can take a lot of time or synchronization problem for cron process the queue.

### Expected behavior:

Implement a size limit parameter for a single job so that the cron can enqueue items in buckets.

@lordkrandel

**Comment by lordkrandel** [comment]
@jco-odoo if the job is just one, then the job_count gets bypassed. Can it be that when we started "batching" sending requests in `account_edi` we forgot to split every `n` invoices, like we do when receiving?

@salvorapi In Odoo 17 the whole process is manually controlled with the Send & Print dialog. I suppose that you need some fix for `16.0` because your clients are on Odoo.sh (for the OCA modules) and not on SaaS... ?
(maybe also saas-16.4? don't remember)

**Comment by salvorapi** [comment]
@lordkrandel I confirm. I need some fix for `16.0` deployed on `Odoo.sh`.

Salvo.

**Comment by lordkrandel** [comment]
Done!
