### ISSUE TITLE
Anyone helps validating this: Spreadsheet saving local vs external

### ISSUE THREAD

**Issue by chapital** [odoo/odoo#149318]
Hi

Please user that have odoo onpremise installed, Can you help me to verify this:

If I go to a spreadsheet and create a new one.

Then make some changes (write something in any cell)

Then change the cell

In local (ex.192.168.1.20:8069) access the spreadsheet says "SAVING...", sometimes saves other ones not.

In external (ex. domain.com) access the spreadsheet says "SAVED", and everything saves.

Tell me if also this error happens to you

Or if anyone knows the solution please let me know

Tested in odoo v16 enterprise, external and local it's the same database. 

Thanks

**Comment by rrahir** [comment]
the "saving..." appears because the spreadsheet does not receive messages from the server via websocket,I think you probably have the same kind of issue when you send messages between users via the discuss app.
I suggest you take a look at https://www.odoo.com/documentation/17.0/administration/install/deploy.html?highlight=websocket as your setup might require that you redirect the websocket calls to a dedicated address.

**Comment by chapital** [comment]
Tested and also happened with discuss, I will validate how to configure a web socked to a dedicated address, or if you have a guide please let me know.

Thank you
