### ISSUE TITLE
[10.0] Assetsbundle checksum will never work!

### ISSUE THREAD

**Issue by rmmr** [odoo/odoo#14938]
Hi again,

I've looked at the checksum calculation method for the assetsbundle class. This will never work! A hash is calculated from a json dump from an array of dictionaries. 

This will always be random. This causes assetbundles to be invalidated on worker restart. 

My suggestions is to use an OrderedDict.

Impacted versions:

10.0, and my guess is other versions too.

Steps to reproduce:

- Modify checksum function at file:
 https://github.com/odoo/odoo/blob/10.0/odoo/addons/base/ir/ir_qweb/assetsbundle.py : 151
- Add a print statement to output hashlib.sha1(check).hexdigest()
- Call the web/login url (or any other)
- Look at the checksum
- Restart the server
- Call the web/login url
- Look at the checksum

Current behavior:

They will always differ (unless there is random luck)

Expected behavior:

They should not differ unless assets have actually changed

**Comment by Yenthe666** [comment]
@xmo-odoo and @odony can I ask you guys for feedback? I'm not sure about this one 👍

**Comment by adaptivdesign** [comment]
I've created a fix for this solution, but this really should be addressed by Odoo. I know these are low level issues, but they fundamentally impact the way Odoo performs. Let me provide some more context on the problem and the solution.

**The problem:**

First of all, I noticed this issue because I run Odoo on Heroku. Because of this all attachments are copied over to a S3 bucket. As Heroku instances can go online and offline at any time, it causes Odoo processes to go up and down. Every time a new process goes up, these asset bundles are recreated (because of this bug). This in turn causes the attachment filestore to keep on changing.

I can imagine this issue is much less noticeable in regular Odoo installations. It still gives a performance decrease, that should not happen.

**The solution**

**Fix the checksum method, see my patch at line 156:**
https://github.com/adaptivdesign/odooku-compat/blob/10.0/patch/odoo/addons/base/ir/ir_qweb/assetsbundle.py

The checksum will now change whenever an actual javascript or stylesheet has changed.

**Fix dynamic javascript**

Two assetbundles will still keep changing the checksum because of dynamically generated javascript, which should stay the same unless modules are installed or removed. This problem is found in:

https://github.com/odoo/odoo/blob/fc2e80cb4bcc450762c7ac5cb82a3e2d88062b38/addons/web/views/webclient_templates.xml  line 126:

```
<script type="text/javascript" charset="utf-8">
     odoo._modules = <t t-raw="get_modules_order()"/>; 
</script>
```

Nothing wrong with this line, but the module order keeps on being semi random. The problem of this can be traced down to the function "module_installed" line 153:
https://github.com/odoo/odoo/blob/10.0/addons/web/controllers/main.py

Yes the modules are topologically sorted, but part of the order keeps being semi random. The reason is again, you are using a regular dictionary. A fix can be found here, simply use an OrderedDict:
https://github.com/adaptivdesign/odooku-compat/blob/10.0/patch/addons/web/controllers/main.py

I hope this provides enough detail to address this issue. I can make a pull request for this.

**Comment by adaptivdesign** [comment]
Any news on this? For reference, a fixed checksum method can be found at 

https://github.com/adaptivdesign/odooku-compat/blob/10c6671f318d26b4fa675e33a45e0c90c3ee3302/patch/odoo/addons/base/ir/ir_qweb/assetsbundle.py

**Comment by pedrobaeza** [comment]
@xmo-odoo can you give us any comment about this?

**Comment by Yenthe666** [comment]
Closing this one as V10 has been long end of life.
