### ISSUE TITLE
[10.0]odoo 10 Inherit Partner

### ISSUE THREAD

**Issue by jamshu** [odoo/odoo#14940]
When Inherit Partner,need to update Base from Backend,Its getting Internal server front end and cant go to apps page to update,

We need to login odoo user in server and need to run python odoo/odoo-bin --update=all

**Comment by Yenthe666** [comment]
Hi @jamshu,

Thank you for your report but we only use the Github issue tracker for bugs in the official software, not in custom development.
I'm not sure what you mean though. If you inherit the existing module in `manifest.py` and when you then inherit the model `res.partner` in the Python file with `_inherit = 'res.partner'` you can simply add your own fields to the model.
If you then install your custom developed module you'll see the new fields, functions and views showing up. This does not require an update of the `base` module or whatsoever.
I'd suggest you to ask this question on the official Odoo help forums (help.odoo.com) and to add code in the question so we can look at it.
Closing this since it is not an official bug.

Regards,
Yenthe
