### ISSUE TITLE
V10 "company_type" can not be set to "company" as default in Contacts

### ISSUE THREAD

**Issue by aduijs** [odoo/odoo#14955]
Impacted versions: V10c (might as well 10e)

Steps to reproduce:
- Login to Odoo as admin and activate developer mode
- navigate to contacts and open form "create new contact"
- select "is company" radio-button
- from the developer dropdown select  "set defaults"
- choose 'company_type' = 'Company'  and save
- when creating a new contact you see that company is selected as expected, but in a millisecond switched back to individual

other way tried to solve this (by @ovnicraft )
he wrote a module to overwrite the default, and that doesnt work either
https://gist.github.com/ovnicraft/757797fb095a0f73987380144f079a2d

Current behavior:
after the default is set, when creating a new contact you see that company is selected as expected, but in a millisecond switched back to individual

Expected behavior:
the default is company

**Comment by ovnicraft** [comment]
I confirm this bug with latest revision.

**Comment by Yenthe666** [comment]
Hi @aduijs,

Thank you for your report.
I've just tested this on the latest Odoo 10 community and can confirm that this is a bug.
@mart-e can you look at it? Looks like it is overriden after a few milliseconds.

**Comment by mart-e** [comment]
Hello,

Yes it is not possible to set a default because it is not a field stored in the database, it is a field automatically computed based on the flag `is_company` of the partner

```python
@api.depends('is_company')
def _compute_company_type(self):
    for partner in self:
        partner.company_type = 'company' if partner.is_company else 'person'
```

If you want to change the behaviour, you will need to change this method

**Comment by ovnicraft** [comment]
So `is_company = fields.Boolean(default=True)`solve the problem.

Thank you.

**Comment by gustavovalverde** [comment]
I'm trying to do this in the partner create() function:

```
                if len(vat) == 9:
                    vals.update({"company_type": "company"})
                else:
                    vals.update({"company_type": "person"})
```

Do I also have to overwrite the _compute_company_type function for this to work?

**Comment by bistaray** [comment]
`is_company = fields.Boolean(default=True) `  will cause ALL new res.partner records to be Companies, even CONTACTS and ADDRESSES you add on the tab on the Form View.  

NOT what you want I think (since I just ran into this myself)

My requirement:  Default the creation of all new partners to COMPANY, except those added from the res.partner form view on the Contacts and Addresses tab - which should be INDIVIDUALS. 

Ideas?

**Comment by Yenthe666** [comment]
@bistaray passing it along in the context?

**Comment by bistaray** [comment]
Tried this and it isn't working:

```
  <field name="child_ids" position="attributes">
        <attribute name="context">{'default_parent_id': active_id, 'default_street': street, 'default_street2': street2, 'default_city': city, 
                         'default_state_id': state_id, 'default_zip': zip, 'default_country_id': country_id, 'default_supplier': supplier, 
                         'default_customer': customer, 'default_lang': lang, **'default_is_company': False**,}</attribute>

    </field>    
```

**Comment by bistaray** [comment]
Hmm.  I can see that context is setting the value correctly and BEFORE write the record has the correct values.  Not sure how is_company is getting changed back to COMPANY.  I can't see to create CONTACTS as 'person' records using the TAB on the FORM VIEW.

**Comment by bistaray** [comment]
Figured it out - the is_company field isn't on the popup form view, so setting context won't make any difference.  Once I added it (hidden), setting context as above worked.

**Comment by bistaray** [comment]
IMHO it isn't user friendly to allow a user to do something that doesn't work (set a default value for a field that can't have a default value) - the solution expects the user to know somehow that this field in the list given to them is not stored in the database - can't that list be filtered with store = False so that these kinds of fields are never shown to the user?

**Comment by gdgellatly** [comment]
can't you just set company_type to 'company' as default in UI.  Thats the
field that determines the function.

**Comment by bistaray** [comment]
No. This issue was created after someone tried that exact thing.  

First post in this thread:

Steps to reproduce:

* Login to Odoo as admin and activate developer mode
* navigate to contacts and open form "create new contact"
* select "is company" radio-button
from the developer dropdown select "set defaults"
* choose 'company_type' = 'Company' and save
* when creating a new contact you see that company is selected as expected, but in a millisecond switched back to individual

**Comment by ovnicraft** [comment]
Write a method to est default value in company_type, in this method evaluate parent_id field, if this field is empty is not a contact.

**Comment by gdgellatly** [comment]
Oh yeah, I noticed that the other day when trying to default the contact
type as well after adding a new type to the selection.  So much intertwined
functions and onchanges in that part of code.

**Comment by spookiecookie** [comment]
Confirming that solution by Mr. bistaray (https://github.com/odoo/odoo/issues/14955#issuecomment-321898004) worked for me (odoo v10). Must define in context 'default_is_company': False and modify pop up form so that it contains 'is_company' field (can hide it with invisible='1' tough).

**Comment by travish2** [comment]
Another alternative: Settings -> Technical -> User-Defined Defaults, create rule "Is a Company (res.partner)" = true

Works on v12 and does not set contacts as company
