### ISSUE TITLE
mail composer mess with html and css code from mail template

### ISSUE THREAD

**Issue by JoaoPauloSouza** [odoo/odoo#14979]
Impacted versions: 10

Steps to reproduce: create a mail template with custom css for model_id base.model_res_partner and try to compose a message with this template on mail composer on partner form

Current behavior: it changes css and html in some way and mess with the layout

Expected behavior: html and css layout must match the one from template

Video/Screenshot link (optional):

template http://prntscr.com/dskces
composer http://prntscr.com/dskco2

**Comment by Gyuri77** [comment]
The mail composer adds extra "</p><p>" on the end of many lines, mostly after <br/> breaking formatted paragraphs, and creating many unformatted ones. We face this on Odoo 9. After checking your screenshot, I think the same effect in odoo 10. You can check it, with changing to source view in mail composer and compare with original template source.

**Comment by pedrobaeza** [comment]
This is because the HTML editor is not intended for that. You have to edit these things in code editor directly (developer mode + button for showing code).

Closing as no real issue, but a desired improvement.

**Disclaimer**: I'm not an Odoo employee, but a community member that voluntary contributes to triage / classify / solve issues. Take also into account that there's no obligation to answer nor solving things put in Odoo Community issue tracker. And thus, please consider this as a best effort initiative.
