### ISSUE TITLE
[10.0] Group Technical Settings / Discount on lines depends of sale module 

### ISSUE THREAD

**Issue by JesusZapata** [odoo/odoo#15094]
**Impacted versions:** 10.0

**Steps to reproduce:** 

1. Install module `sale`
2. Activate the developer mode
3. Go to Settings > Groups and find group `Technical Settings / Discount on lines`
4. Add to group Administrator User
5. Go to Administrator User and `Discount on lines` is enabled

**Current behavior:** Now the group `Technical Settings / Discount on lines` depends of module `sale`

**Expected behavior:** The group `Technical Settings / Discount on lines` should not depend on `sale` module 

Video/Screenshot link (optional):
![image](https://cloud.githubusercontent.com/assets/1387970/22012924/c6cc9154-dc6c-11e6-8f1b-1ef8e0c18132.png)

**Comment by mart-e** [comment]
Hello,

I confirm the group "Discount on lines" is created in sale and used in account. However it is not something we can change in v10 (cf [stability guidelines](https://github.com/odoo/odoo/wiki/Contributing#what-does-stable-mean)).

I have worked on a patch for master at #15100

**Comment by JesusZapata** [comment]
@moylop260 What think about this?

**Comment by moylop260** [comment]
Thanks @mart-e 
cc @nhomar @qdp-odoo

**Comment by nhomar** [comment]
I understand the policy.

@JesusZapata Make a patch in Vauxoo/odoo#10.0 and 9.0 with this fix Copying the solution proposed by @mart-e and make a proper PR just in case they want to merge after a second revision.

@mart-e I do not understand how a missing xml_id cannot be fixed in the core because an stability reason, if you check the problem it can be solved with a -u sale,account which is what everybody does when update an stable version, and such missing xml_id fix several inconsistencies in usability and save a lot of problems to us the developers and maintainers, I think you should reconsiders wither the solution (instead move to account the group, delimit the group to sales and create a new view definition in account for stable), with that you will not brake the policy because you are not creating any new record just fixing a corrupted xml (which can and must be done in stable under the licence agreement).

Regards.

**Comment by mart-e** [comment]
Hello Nhomar,

> It is fine if a bugfix requires an explicit update, as long as it is safe for users who are not aware of it and do not perform the update.

Moving a res.group from sale to account does not respect this. As you saw in the master patch, it changes the `implied_group` of the field `group_discount_per_so_line`, which would break without a `-u`.
Also there is some references in enterprise repository that needs to be updated (and probably in some community modules too).

I have made at #15098 another proposal with changes that could be accepted in stable but the `group_discount_per_so_line` is not one of them.
