### ISSUE TITLE
[16.0] account_asset : random depre

### ISSUE THREAD

**Issue by fmdl** [odoo/odoo#151292]
Impacted versions: 16.0

Steps to reproduce:
- Create an asset with this config (https://57126200-16-0-all.runbot163.odoo.com/web#cids=1&menu_id=633&action=1328&model=account.asset&view_type=form&id=3):
![image](https://github.com/odoo/odoo/assets/16716992/e6b47d74-805a-41ae-8abd-5f89ca5093a3)
- Compute Board
![image](https://github.com/odoo/odoo/assets/16716992/b18143af-7555-48cf-9ebb-0bdfa059bf6b)
--> the depreciation is not the same each month

Support ticket number submitted via odoo.com/help (optional):
OPW #3704574

**Comment by fmdl** [comment]
ping @oco-odoo

**Comment by fmdl** [comment]
It should come from this line : https://github.com/odoo/enterprise/blob/16.0/account_asset/models/account_asset.py#L537
Because with this it works :
computed_linear_amount = self.currency_id.round(amount_after_expected - amount_expected_previous_period - sum(amount_of_decrease_spread_over_period))

**Comment by gawa-odoo** [comment]
Hello!

We don't think it's an issue as it is in fact not random. We do think it makes more sense than before.
The goal is that the amount depreciated at the end of the period corresponds to the total amount that should have been depreciated at this moment.
So, for example, in your case, the amount that is depreciated each month would be 86300/120 => 719,1666.... 
719.67 each month would mean that you depreciate a tiny bit too much. 
What we currently have is 2 months of 719.67, then 1 with 719.66, which corresponds to the amount that should be depreciated at the end of each period of 3 months.

The best example would be to have an asset where you want 2000$ depreciated on 6 years without prorata.
You will have 333.33, 333.33 then 333.34 for the first 3 years. So that at the end of the 3rd year, you would have 1000$ total depreciated, which corresponds to the amount that is expected.
What we did before, in 15.0, was do 333.33 always, with the remaining amount on the last entry. But it makes it so that at the end of the 3rd month, you would have 999.99 and not 1000. 

For this reason, I don't think there is an issue here.

Don't hesitate if you have further questions,
Gauthier

**Comment by fmdl** [comment]
@gawa-odoo I understand this method. 
But generally other accounting software use the same amount for all periods (except last one). Maybe you can add an option (with res.config.parameter) to change the behaviour.

Regards
