### ISSUE TITLE
translation problems

### ISSUE THREAD

**Issue by haitac261189** [odoo/odoo#152632]
Impacted versions: 17
![image](https://github.com/odoo/odoo/assets/15794711/e8d9757b-62b2-412d-a317-2b1bc9de9ca8)

**Comment by vava-odoo** [comment]
Hello @haitac261189 
This was fixed with https://github.com/odoo/odoo/commit/1b9fd01d46f73406d2e804edd914d0ac81f08b5c
Thanks for the report but please check the [translation documentation](https://github.com/odoo/odoo/wiki/Translations), the translations are handled on [Transifex](https://explore.transifex.com/odoo/), not Github.
Please submit your changes there and let me know if you have issues.
Cheers
