### ISSUE TITLE
[10.0] account: context "default_type" of invoice affects "ir_attachment.create" method

### ISSUE THREAD

**Issue by moylop260** [odoo/odoo#15279]
Steps to reproduce
==============
0. Branch used: https://github.com/odoo/odoo/tree/saas-14 with sha: 5b521136d4f1682dfa77c5bcb8c1ad899024a9a7
1. Install enterprise and `account_accountant`
2. Apply the following patch
```diff
diff --git a/addons/account/models/account_invoice.py b/addons/account/models/account_invoice.py
index 6cee000e5..cc54212dc 100644
--- a/addons/account/models/account_invoice.py
+++ b/addons/account/models/account_invoice.py
@@ -911,6 +911,9 @@ class AccountInvoice(models.Model):
             if invoice.type in ('in_invoice', 'in_refund') and invoice.reference:
                 if self.search([('type', '=', invoice.type), ('reference', '=', invoice.reference), ('company_id', '=', invoice.company_id.id), ('commercial_partner_id', '=', invoice.commercial_partner_id.id), ('id', '!=', invoice.id)]):
                     raise UserError(_("Duplicated vendor reference detected. You probably encoded twice the same vendor bill/refund."))
+            attachment_id = self.env['ir.attachment'].create({
+                'name': 'test', 'res_id': invoice.id, 'res_model': invoice._name,
+                'datas': ''.encode('base64'), 'datas_fname': 'test', 'description': 'test'})
         return self.write({'state': 'open'})

     @api.model

```
2. Create a customer invoice from account dashboard
3. fill required fields and confirm it

Current behavior
============

```bash
...
odoo/fields.py", line 1740, in convert_to_cache
raise ValueError("Wrong value for %s: %r" % (self, value))
ValueError: Wrong value for ir.attachment.type: u'out_invoice'
```
Because context has `default_type: invoice` from invoice context but it was used from attachment create method.

Expected behavior
==============

Maybe a message of a wrong way use of create attachments or avoid use default_* variables from context for `ir.attachment` (I don't know)

Video/Screenshot link (optional)
=======================

[![IMAGE ALT TEXT](http://img.youtube.com/vi/Vy-7hjFhGzs/0.jpg)](http://www.youtube.com/watch?v=Vy-7hjFhGzs "Video Title")

Notes
=====

I don't know if is a real issue but I prefer report it because I found other users with the same problem like as this [thread](https://www.odoo.com/es_ES/groups/community-59/community-18816567)

I fixed using
```python
ctx = self.env.context.copy()
ctx.pop('default_type', False)
attachment_id = self.env['ir.attachment'].with_context(ctx).create({
...
```
But I'm not sure if is the best way or there is other valid way from core

**Comment by osvalr** [comment]
also tested in branch `10.0`

**Comment by osluys** [comment]
I was about to file a similar issue but found this one instead. This issue encompasses more than just `ir.attachment` and potentially affects any model that has had a window action defined that includes default values in the context.

For example, create a new sales order document from the following window action definition:

```xml
<act_window id="sale_order_no_quote"
   name="No Quote Sales Orders"
   res_model="sale.order"
   view_mode="tree,form"
   context="{'default_state': 'sent'}"/>
```

When the _Confirm_ button is clicked, a similar error as the OP's is raised:

```
  Traceback (most recent call last):
  File "/home/odoo/odoo/odoo/http.py", line 640, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/odoo/odoo/http.py", line 677, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo/odoo/odoo/http.py", line 333, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/odoo/odoo/service/model.py", line 119, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/odoo/odoo/http.py", line 326, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/odoo/odoo/odoo/http.py", line 935, in __call__
    return self.method(*args, **kw)
  File "/home/odoo/odoo/odoo/http.py", line 506, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/odoo/odoo/addons/web/controllers/main.py", line 882, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/odoo/odoo/odoo/addons/web/controllers/main.py", line 870, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/odoo/odoo/odoo/api.py", line 681, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/home/odoo/odoo/odoo/api.py", line 672, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/odoo/odoo/odoo/addons/portal_sale/models/sale_order.py", line 16, in action_confirm
    return super(SaleOrder, self).action_confirm()
  File "/home/odoo/odoo/odoo/addons/sale/models/sale.py", line 454, in action_confirm
    order.order_line._action_procurement_create()
  File "/home/odoo/odoo/odoo/addons/procurement_jit/sale.py", line 12, in _action_procurement_create
    res = super(SaleOrderLine, self)._action_procurement_create()
  File "/home/odoo/odoo/odoo/addons/sale/models/sale.py", line 663, in _action_procurement_create
    new_proc = self.env["procurement.order"].create(vals)
  File "/home/odoo/odoo/odoo/addons/procurement/models/procurement.py", line 136, in create
    procurement = super(ProcurementOrder, self).create(vals)
  File "/home/odoo/odoo/odoo/addons/mail/models/mail_thread.py", line 228, in create
    thread = super(MailThread, self).create(values)
  File "/home/odoo/odoo/odoo/models.py", line 3811, in create
    record = self.browse(self._create(old_vals))
  File "/home/odoo/odoo/odoo/models.py", line 3886, in _create
    self._check_selection_field_value(name, val)
  File "/home/odoo/odoo/odoo/models.py", line 2116, in _check_selection_field_value
    field.convert_to_cache(value, self)
  File "/home/odoo/odoo/odoo/fields.py", line 1737, in convert_to_cache
    raise ValueError("Wrong value for %s: %r" % (self, value))
  ValueError: Wrong value for procurement.order.state: u'sent'
```

In the stack trace, you'll notice that a procurement order is being created, which at some point calls the `create()` method of the `BaseModel` class (_models.py_). One of the first things done in the `create()` method is to add any missing default values to the passed-in values dictionary:

```python
    @api.model
    @api.returns('self', lambda value: value.id)
    def create(self, vals):
        ...
        # add missing defaults, and drop fields that may not be set by user
        vals = self._add_missing_default_values(vals)
        ...
```

What that ends up doing though, is using the context to determine what default values should be added to the created record. In my example above, since I had set a `default_state` value in the context, the `state` field for the new procurement order record will get the default value of `'sent'`, but since that is not a valid selection item for its `state` field, the `ValueError` is raised.

Obviously, when I defined `default_state` in the context of the window action, I intended it to only apply to sales order records and not to any related records that were created as a byproduct. Had `default_state` been set to a value that both `state` fields of `sale.order` and `procurement.order` shared in common, that error would never have been raised, and I would have been left with unintended behavior that most likely would have been very difficult to track down.

**Comment by idealisconsultingbe** [comment]
Any news about this issue?

**Comment by rrahir** [comment]
This behaviour is  side effect of the way default_ fields work inside Odoo. When looking for a default field. We first look a the keys in context and then we look at the default value on the field.
If you wish to have the default value of the field, you need to clean the context from the default key.

This is a standard, documented and used behaviour in Odoo and as such, we do not intend to change it.

If you consider this to be a flaw in the design, you can contact our feedback team at feedback@odoo.com to suggest improvements.

**Comment by wpichler** [comment]
I would like to reopen this - i also encountered the problem - and fixed it by coping the context and poping the default_type key from the context - before i call the next function.

I did added a send mail button to account.invoice to directly send the mail - when the mail.template does render the attachment - the error will happen.

It does happen - because in report.py it does generate the attachment - and does not specify type=binary there.

So the simplest way to fix it would be to add 'type': 'binary' to the function _run_wkhtmltopdf - it won'T hurt anything existing - but will help others...

**Comment by mhazbilly** [comment]
How to should fix it?
I found a similar error after adding filters search
<search string="Admin">
             <filter string="Draft" name="state" domain="[('state','=','draft')]"/>
</search>
and using this context 
<field name="context">{
    "search_default_state": 1,
    "default_state": 1}
</field>.

**Comment by jeej62** [comment]
Thanks so much Wpichler. I just found the error in Odoo v12. It was driving me crazy for the hole day. I follow your suggestions and found where to add 'type': 'binary' 👍 It was located in /addons/base/models/ir_attachements_report.py. The function was:

def postprocess_pdf_report(self, record, buffer):

attachment_vals = {
            'name': attachment_name,
            'datas': base64.encodestring(buffer.getvalue()),
            'datas_fname': attachment_name,
            'res_model': self.model,
            'res_id': record.id,
            'type': 'binary'
        }

It worked very well

**Comment by wpichler** [comment]
@rrahir It seems the "bug" still does exists - so what about my small fix to get around it ? Any side effects ?

**Comment by rrahir** [comment]
@wpichler  @jeej62 Could you provide a more in-depth example on how to reproduce this issue in your case? The idea of adding a key 'type'='binay' should not be necessary if the context is properly managed since it is the default value of an attachment.

**Comment by jeej62** [comment]
Hello.

I am working on an accounting localization for Ecuador. The system generates electronic XML and PDF receipts from the different billing forms: out_invoice, out_refund and in_invoice withholdings. There were no problems in the attachments generation for out_invoice tests and in_invoice retentions. The code generate the attachments to the forms without problem. However, when I proceeded to test the electronic invoicing with out_invoice, the problem arose and the system even generated the error from the other two forms. This worried me a lot and I thought it was a problem with my code. I decided to debug it, review it and try it for a week.

I decided without finding the source of the problem, seeking help by reading all the articles where "Wrong value for ir.attachment.type:" is mentioned. I found wpichler comments and it made a lot of sense. I had never tried changing the Odoo code before. I use Pycharm to program and I could easily find the lines of code that generated the error within "ir_actions_report.py" specifically in "def postprocess_pdf_report (self, record, buffer):". The rest was just a piece of cake and joy.

It is difficult for me at this time to try to reproduce the isolated error and in a simple way, since it is part of a whole. However, I will send the code where it is produced.

As you can see. In the creation of the attachment, I do encode the binary type. Despite this, the error appears.

My program validates the XML file sent to the SRI Ecuadorian Tax Collection Service. As can be seen in the history log, the SRI validated the XML file sent, but the program stopped in the process of adding attachments that were executed after receiving the valid authorization from the SRI, and prior to sending an email with these 2 files to the respective customers or suppliers.

I hope my explanation contributes to your comments. English is not my native language. Sorry if something is not very clear. I can try to improve the explanation if you require it.

@ api.one
    def add_attachment (self, xml_element):
        Authorization date = {}
        # ------------------------------------------------- --------------------------------
        # ADD THE ATTACHED XML AND PDF FILES TO THE ELECTRONIC DOCUMENT FORM
        # ------------------------------------------------- --------------------------------
        attachment_obj = self.env ['ir.attachment']
        # ------------
        # XML FILE
        # ------------
        buf = StringIO ()
        buf.write (xml_element)
        document = base64.encodebytes (buf.getvalue (). encode ()). decode ('ascii')
        buf.close ()
        attach_ids = []
        attach = self.env ['ir.attachment']. create (
            {
                'name': '{0} .xml'.format (self.number_authorization),
                'datas': document,
                'datas_fname': '{0} .xml'.format (self.numero_autorizacion),
                'res_model': self._name,
                'res_id': self.id,
                'type': 'binary'
            },
        )
        attach_ids.append (attach)
        # ------------------------------------------------
        # READING THE DATE Authorization from the XML FILE
        # ------------------------------------------------
        root = ET.fromstring (xml_element)
        for authorization in root.iter ('authorization'):
            authorization date = authorization.find ('authorization date'). text
       if date Authorization:
            # ------------
            # PDF FILE
            # ------------------------------------------------- ----------------------------
            # self.tributory_document_type DEFINES THE TYPE OF REPORT USED FOR 
            # ------------------------------------------------- ----------------------------
            report_id = {}
            ids = []
            ids.append (self.id)
            data = {'ids': ids, 'model': self._name}
            if self.tripo_documento_tributario == 'PURCHASE CHECK':
                report_id = 'l10n_ec_invoice.l10n_ec_invoice_retention'
            if self.tipo_documento_tributario_= = 'SALES INVOICE':
                report_id = 'l10n_ec_invoice.l10n_ec_invoice_out_invoice'
            if self.tripo_documento_tributario == 'SALES CREDIT NOTE':
                report_id = 'l10n_ec_invoice.l10n_ec_invoice_out_refund'
            if self.tributory_document_type == 'REMISSION GUIDE':
                report_id = 'l10n_ec_invoice.l10n_ec_invoice_delivery_guide'
            if self.tributory_type_type == 'PURCHASE LIQUIDATION':
                report_id = 'l10n_ec_invoice.l10n_ec_invoice_purchase_clearance'
            if report_id:
                pdf = self.env.ref (report_id)
                try:
                    pdf = pdf.render_qweb_pdf (self.ids)         # <-- HERE IS WHERE THE ERROR AROSE
                except Exception as error_message:
                    # ------------------------------------------------- -----------------------------------
                    # ANY ERROR WITHIN THIS PROCESS STOPS THE VALIDATION PROCESS
                    # ------------------------------------------------- -----------------------------------
                    log_msg = 'ERROR: (Añadir archivos)' + str (error_message) .replace ("'", "")
                    logging.info (log_msg)
                    self.history_log (log_msg)
                    self.estado = "ERROR"
                    return
                ride = base64.b64encode (pdf [0])
                attach = attachment_obj.create ({
                    'name': '{0} .pdf'.format (self.numero_autorizacion),
                    'type': 'binary',
                    'datas': ride,
                    'datas_fname': '{0} .pdf'.format (self.numero_autorizacion),
                    'res_model': self._name,
                    'res_id': self.id,
                })
                attach_ids.append (attach)
        return attach_ids

![Captura de Pantalla 2019-12-09 a la(s) 11 07 05](https://user-images.githubusercontent.com/45579351/70457791-c9ad4a00-1a7e-11ea-8a40-ac90c343b16f.png)
