### ISSUE TITLE
[8.0] Invoice remains open even if reconcilied

### ISSUE THREAD

**Issue by Cedric-Pigeon** [odoo/odoo#15287]
Impacted versions: 8.0

Steps to reproduce:

- Create an invoice for a customer.
- Create a refund for the same customer but with a bigger amount than the invoice
- Reconcile the refund with the invoice

Current behavior:

The invoice remains open.

Expected behavior:

The invoice should be marked as paid

Video/Screenshot link (optional):
Please watch this video done on runbot: https://youtu.be/iTgtscKHmFA

**Comment by Cedric-Pigeon** [comment]
OPW-706653

**Comment by adrienpeiffer** [comment]
:+1:

**Comment by nim-odoo** [comment]
Hello,

If I am not misleading, in v8 an invoice is considered as paid when it is fully reconciled. In this case, the invoice is partially reconciled due to the fact that the payment is not fully reconciled: the invoice has a partial reconciliation ID, not a full reconciliation ID.

That's one of the reason a major refactoring was performed in v9, so we consider an invoice paid when the residual amount is zero. Therefore, I'm not sure this can be solved in v8.

@qdp-odoo : could you please confirm?

**Comment by qdp-odoo** [comment]
exactly Nicolas.

@Cedric-Pigeon : this is a limitation of v8, your invoice will appear as paid only when the total residual amount will be 0, which will be achieved when the refund is totally paid (with a writeoff or another invoice for example).
