### ISSUE TITLE
[10.0][google_spreadsheet] Google Spreadsheet script security problem

### ISSUE THREAD

**Issue by NeoPolus** [odoo/odoo#15328]
**Impacted versions:** 10.0 (and previous)

**Steps to reproduce:** 
- Install _google_spreadsheet_ module on Odoo 10.
- Go to partners list (or any list).
- Create a new search view (i.e. filter the list by "Customer") 
- Use the "Add to Google Spreadsheet" action of the search view (in the Favourites drop down menu).
- It creates a new Google Docs SpreadSheet, for the current search view, based on this template: https://docs.google.com/spreadsheet/ccc?key=1KUlSSzZMzkEEzyroyZ2NerRt1RVCspkG9VQIh2V6dnM 

**Current behavior:**
- The created spreadsheet stores the Odoo connection username and password as plain text in the _ScriptProperties_ attached to the document.
- _ScriptProperties_ are visible by anybody using this document (its scope is this document and script, not limited to current user). **If we share the generated document (i.e. with a team mate), we are sharing our password.** 

Expected behavior:
- It should use **UserProperties** (visible to current user only), not **ScriptProperties** (visible to other users), to store the connection data.

**Comment by odony** [comment]
Thanks for reporting this issue. Given the fact that it is security sensitive, it would have been better to follow our [responsible disclosure](https://www.odoo.com/page/responsible-disclosure) process, as explained in our [contribution guidelines](https://github.com/odoo/odoo/wiki/Contributing#reporting-issues). Following this process demonstrates responsibility and care for the safety of other users. It ensures that issues are disclosed along with a verified impact analysis and an officially tested solution.

Now that you've described the problem, here is a quick assessment of the situation:

## Preliminary analysis
Google's API has unfortunately changed since the original implementation of the google spreadsheet module. However, sharing a document in read-only mode (the only sensible option for public sharing) still **does not** allow other people to access the **UserProperties**. So _public sharing_ is normally not a risk.
Sharing a spreadsheet in read-write mode, typically with your coworkers, is entirely different. In that case, your co-workers can read the ScriptProperties and should not be able to access your password.
We can fix this by immediately modifying our template to use UserProperties.

**Warning about _read-write_ sharing**: it should be kept in mind that fully securing a spreadsheet in _read-write_ mode is generally impossible. Malicious "co-workers" can modify the script, so they have full control. They could silently alter the script and create a fake password prompt to send them your login credentials directly (social engineering techniques). This kind of sharing should be done with great care in any case!

**Warning about Google "organizations"**:  If your Google account is part of an organization, please be mindful of the default sharing policy for your google spreadsheets! Administrators can control the default sharing policy, and even disallow public sharing or sharing outside the organization. Please refer to the [G Suite documentation](https://support.google.com/a/answer/60781?hl=en) for more information.


## Remediation
We **have fixed the issue on our side** by immediately modifying our template to use UserProperties instead of ScriptProperties.

In order to guarantee safety, users of the `google_spreadsheet` module should follow these guidelines:
1. For **new** spreadsheets created with the `google_spreadsheet` module:
They are safe as the template is now based on **UserProperties** by default. 
2. For **existing** spreadsheets created with the `google_spreadsheet` module:
  - If the spreadsheet has been shared in **read-write** mode with other people, it is vulnerable to the problem. We recommend users upgrade their spreadsheet to the new template by creating a new spreadsheet, copy/pasting the contents of their spreadsheet in the new one, and finally deleting the old one from their google account.
  - If the spreadsheet has **not** been shared, or only shared in **read-only** mode, it is safe. We recommend to follow the procedure above to upgrade their spreadsheet to the new template nevertheless.

Please kind in mind the above warnings about _read-write_ sharing and _organizations_!

---
**Note:** We will publish a more complete Security Advisory as soon as everything is double-checked.

**Comment by NeoPolus** [comment]
Hi @odony and thanks for the quick reply!
Thanks for pointing me to https://www.odoo.com/page/responsible-disclosure too! I've been away from OpenERP (now Odoo) development for a long time (since the launchpad 'good' old days) and didn't knew there are more appropriate channels to report security problems now. I'm testing Odoo 10.0 these days for a personal project so I'll be reporting any bug I find :)
