### ISSUE TITLE
[10.0] No mode editor for email template languages

### ISSUE THREAD

**Issue by collex100** [odoo/odoo#15371]
Impacted versions:10

Steps to reproduce:
Actions do in the language other than English.
Mass Mailings -> Mail Templates -> Choose any template - Edit -> Select the language for the template edition

Current behavior:
There is no mode for editing email template for a language other than English.

Expected behavior:
It should be edition mode for the language.

Video/Screenshot link (optional):
https://youtu.be/u-HdcJqB380

**Comment by Yenthe666** [comment]
Hi @collex100,

Thank you for your report.
If I'm not mistaking this is by design and the desired behaviour.
I believe the idea is to edit and change the e-mail template in the main language (English). If you then want to translate the e-mail template you should go to the translations and translate your just edited e-mail template there.
@JKE-be or @mart-e can one of you confirm that I'm correct?

Regards,
Yenthe

**Comment by mart-e** [comment]
Hello,

Sorry but, indeed the editor works only in one language. You have to use the list of translations to change the content in other languages.
We works with a master reference and then, split the content in translatable chunks that you can translate manually.

**Comment by collex100** [comment]
This section has been removed / hidden in version 10. This section is no longer in the visible part.
