### ISSUE TITLE
Sale Order: get_address > "default to type 'contact' or the partner itself"

### ISSUE THREAD

**Issue by BzMB** [odoo/odoo#15417]
Impacted versions:
10 community

Steps to reproduce:
1.
Sales > Settings > Addresses
Activate: Display 3 fields on sales orders: customer, invoice address, delivery address
Press Apply

2.
Create a Customer 
       Is a Company: yes
       Create a new contact, contact type: Contact
Raise a Sale order and select the partner just created as Customer

Current behaviour:
The system will default the Invoice Address to the Company Contact rather then the Company itself (Expected behaviour)

Expected behaviour:
The system should leave the Company record into the Invoice and Shipping Addresses as there are no valid Contact type(Shipping or Invoice) to select
Is there any business or technical reason for that?

Video/Screenshot link (optional):
Code
https://github.com/odoo/odoo/blob/master/odoo/addons/base/res/res_partner.py#L745

**Comment by pedrobaeza** [comment]
I don't think this is a bug, but the expected behavior: if you select a contact, the contact will be used in all addresses unless you have other partners of type "Invoicing" or "Send address". Closing this.

**Disclaimer**: I'm not an Odoo employee, but a community member that voluntary contributes to triage / classify / solve issues. Take also into account that there's no obligation to answer nor solving things put in Odoo Community issue tracker. And thus, please consider this as a best effort initiative.
