### ISSUE TITLE
IM livechat

### ISSUE THREAD

**Issue by juan-oa** [odoo/odoo#15426]
Impacted versions:
9.0

Steps to reproduce:
Include links from IM livechat on an external website
```html
<link href="https://internal_url/im_livechat/external_lib.css" rel="stylesheet"/>
<script src="https://internal_url/im_livechat/external_lib.js" type="text/javascript"></script>
<script src="https://internal_url/im_livechat/loader/1" type="text/javascript"></script>
```
Open a chat with an agent using the popup

Current behavior:
Image links are missing as URL generated does not point back to the Odoo server hosting the images
![image](https://cloud.githubusercontent.com/assets/6720550/22777807/1a17989c-eebd-11e6-949e-0ca0c2d339c7.png)

```js
/im_livechat/external_lib.js line 206
`        // Compute the avatar_url
        if (msg.author_id && msg.author_id[0]) {
            msg.avatar_src = "/web/image/res.partner/" + msg.author_id[0] + "/image_small";
        } else {
            msg.avatar_src = "/mail/static/src/img/smiley/avatar.jpg";
        }`
```
Expected behavior:
Unbroken links to images and resources which can fetch from the Odoo instance in an external website

**Comment by adekock11** [comment]
@Yenthe666 did you take a look at this one? The problem here is that if you use IM LiveChat on an external website, the avatar and other resources aren't loaded, since the URLs are relative instead of absolute.

**Comment by fiddler0305** [comment]
I have similar problem.

**I have done**
Include links from IM livechat on an external website
`<link rel="stylesheet" href="http://internal_url/im_livechat/external_lib.css"/>`
`<script src="https://internal_url/im_livechat/external_lib.js" type="text/javascript"></script>`
`<script src="https://internal_url/im_livechat/loader/1" type="text/javascript"></script>`

**but I saw errors on console**

`http://external_url/web/webclient/qweb?mods=`
`Failed to load resource: the server responded with a status of 404 (Not Found)`
`http://external_url/web/webclient/bootstrap_translations`
`Failed to load resource: the server responded with a status of 404 (Not Found)`
`http://external_url/im_livechat/init` 
`Failed to load resource: the server responded with a status of 404 (Not Found)`

**I wonder why these requests access external_url instead of internal_url?**

**Comment by Yenthe666** [comment]
@mart-e what do you think?

**Comment by jem-odoo** [comment]
@juan-oa It seems to be fixed with https://github.com/odoo/odoo/commit/adb0312faf2bdb6d8d7ffc25204d5ab4084a9bb1
Update your source code, and it should ok.
