### ISSUE TITLE
Firefox (v45 - 51) JS bug with Calendar Module. Please help !! Chrome is fine with this

### ISSUE THREAD

**Issue by khoapn102** [odoo/odoo#15455]
Impacted versions: Odoo v9.0

Steps to reproduce:
Click on Calendar Menu

Current behavior:
Error Display as following pictures:
[http://imgur.com/a/2Z1RZ](url)
[http://imgur.com/a/vuPJc](url)

In summarize 2 errors: Allocation size overflow and TypeError: slotTable is not defined. I did not do anything to the module. 

Expected behavior:
Calendar should view as normal as in Chrome: 
[http://imgur.com/a/Q9JEq](url)

Video/Screenshot link (optional):
(as mentioned above).

I have no idea what was the bug in JS that caused the failure in firefox but not in chrome. Please help me, its an urgent. Thank you

**Comment by Yenthe666** [comment]
Hi @khoapn102,

Thank you for your report.
I've just tested this on the newest code on Firefox 51.0.1 without any problems:
![image](https://cloud.githubusercontent.com/assets/6352350/23943331/639947a0-096f-11e7-933f-1f4ef994db88.png)
Could you please update your Odoo codebase and try again? If you still face this can you still reproduce it on a runbot too? (runbot.odoo.com)
If this is the case let me know and I'll reopen this issue.

Regards,
Yenthe

**Comment by cuongpk** [comment]
Hi @Yenthe666,
I have the same problem with Odoo 10 enterprise,
![screenshot from 2017-11-06 15-24-35](https://user-images.githubusercontent.com/23528443/32431601-bc3a9b56-c306-11e7-814d-db5a332869db.png)
Please help me to re-check this error.
Thank you

**Comment by Yenthe666** [comment]
Hi @cuongpk,

I've just tested this on Firefox 56.0.2 and it works fine out of the box.
Can you reproduce this on a runbot?

Regards,
Yenthe

**Comment by cuongpk** [comment]
Hi @Yenthe666,
I have to try with runbot
![screenshot from 2017-11-06 15-49-14](https://user-images.githubusercontent.com/23528443/32432449-4694d354-c30a-11e7-8d12-f29e6ea1fa86.png)

Regards,
Cuong

**Comment by Yenthe666** [comment]
I guess it has been changed in Firefox 56.0.2 then. @ged-odoo could you have a look?

**Comment by ged-odoo** [comment]
The traceback shows that the error occurred in a function named 'buildSkeleton'.  A quick search showed that it is a function in fullcalendar (v1.6.4, which is the one used in 10.0).

We updated fullcalendar to v3.0.1 in version 11.0, and that function buildSkeleton is no longer present.  Also, I could not reproduce the error in any version. So, I believe that this error, whatever it is, is fixed in version 11.0

So, I have to assume that this is a bug in version <= 10.0, and without more information, I'll let the bug fix team decide what to do.
