### ISSUE TITLE
Performance Issues of QWeb PDF Reports: Wkhtmltopdf, GIL Lock and DB Queries Frozen

### ISSUE THREAD

**Issue by aek** [odoo/odoo#15458]
Impacted versions: 8.0, 9.0, 10.0 ...11.0?

Steps to reproduce: 
1- Create a simple QWeb Report that use some model fields, just to get used the database cursor by the ORM, nothing to heavy, any normal report could be used to reproduce the bug
2- Make an intensive use of the report to get it printed as PDF by Wkhtmltopdf, like more than 1000 users creating model records and pushing a button to download the report PDF. The report could have images too if that helps to reproduce it, (3 in my case, 480kb and 240kb, and a QR generated image)

Current behavior:
When the report print functionality reach more than 1000 concurrent users or at least an intensive use depending on the server specifications, the performance problems start to show up. The Odoo Report print service workflow I think that it's a little more complicated than needed. I will describe parts of the workflow just for references on the story 
When the controller receive the report pdf download request it call to the report service that create a python thread for do the pdf report generation calling the render_report method of the ir.actions.report.xml that will call the get_pdf method of the report model. The controller method will be waiting in a loop until the report generation is ready. 
The target method of the thread is actually the responsible for create and close the cursor used for the report HTML generation that will be needed to send it to wkhtmltopdf to generate the pdf file at the end of the get_pdf method. Inside the get_pdf method and once the html is generated the cursor is still open even when it's not needed anymore or at least not for the pdf generation
Due to the cursor will be closed by the report service in the running thread if the reports threads reach a GIL Lock after the intensive use (mostly I think because of I/O waiting) the queries used in the cursor remains open even simple queries like selects from ir_config_parameter with just 10 records it will shows as red in pg_activity and will cause the Odoo lag and freeze all over the place. After closing the cursor modifying the Odoo code inplace just to see if that helps I find that it helps just a little because the red queries will be released soon without waiting for the wkhtmltopdf executions ends and also the report thread close the cursor. But still there will be a GIL Lock on the threads and reports will not print anymore until an Odoo restart. 
I have some suggestions and solutions that I develop and try for this matter but maybe I'm missing something.
1- I create a module just to be able to print reports using a synchronous approach without create any thread for the report generation. Tested in my local development environment but not tested with production like load yet. And here my question is: Why are the threads used here? Not even gevent is used to make it greenlets. I will share my results with the heavy tests
2- I move the report pdf print to the browser using a client action and a js library to print the html version of the pdf report, very close solution to the results of wkhtmltopdf, just there are a few stuff that I don't control yet like header/footer css print and page format but there is a way to get it done. That approach will free up the Odoo instance of about 80% or more of the report print workload, just leaving an space for reports that need to have managed internally inside Odoo server without the user browser interaction. My question here is: Did Odoo s.a look at something like this or there is more inconveniences that I'm missing here?
3- The report pdf generation with wkhtmltopdf could be delayed to be executed when the cursor is closed so no queries lag or frozen related to that. It could be moved with all the info needed to call wkhtmltopdf but not inside get_pdf

Is this even possible or to be happening or maybe it's something more? 
I even modified Ubuntu ulimits for the Odoo, PgBouncer, PostgreSQL and Nginx Servers without improve nothing

**Comment by Yenthe666** [comment]
Hi @aek,

Thanks for your report.
Quite an advanced usecase you have there to test / debug 😉 
@xmo-odoo and @odony could one of you give feedback perhaps?

**Comment by odony** [comment]
You're mixing so many topics here that I have no idea where to start ;-)

Maybe just a few unsorted comments:
- Your situation seems to be rather specific, and might call for customizations of the report system, or alternative solutions. You might also have some sizing issues -- you did not mention anything about the hardware, configuration parameters (--workers, limits, etc..)
- If you are printing with the normal `/web/report` route and with a properly configured multi-process server (`--workers`) you are very unlikely to hit GIL problems, as you will only render 1 report per Odoo process.
- Lines in *red* in pg_activity are simply transactions [running for 3+ secs](https://github.com/julmon/pg_activity/blob/master/pgactivity/UI.py#L1985-L2002). This is a symptom, not a problem. The SQL that is displayed is the *last query* that was executed in the transaction, not the *currently* executing query. Such a query may be "idle in transaction" (doing nothing) and is not necessarily a problem if it does not hold any locks that other transactions are waiting for (switch to the "waiting" (F2) "blocking" (F3) views of pg_activity to view those).
- The report service is partly based on a legacy design where the web server was running as a separate process from the Odoo service, so an async protocol was created using `report` + `report_get` API methods. Nowadays the `/web/report` routes hides those implementation details. The fact that a thread is used behind the scene should not matter much when using multi-process mode.

Also, regarding your proposed solutions:
- 1- As discussed above, removing the thread should not matter if your deployment is using `--workers` mode and the `/web/report` route, so you change is unlikely to solve the situation by itself. Exploring alternatives is still a good idea, as your situation seems rather specific.
- 2- Printing client-side is generally not possible for reports, as they sometimes need to included data that the user cannot directly access via RPC. It might work for your case, but is not an option for Odoo.
There are many other reasons for preferring server-side printing: full control of the result, no dependency on the browser version, control on the hardware, less bandwidth, etc., etc.
- 3- I don't think this is relevant. Your problem is most likely elsewhere, and you need to analyze further the situation to find out where your bottleneck is: server load, cpu activity, real I/O activity, worker utilization. You did not mention much in terms of metrics, and "performance problems" can hide an infinity of different problems with different solutions. ;-)

**Comment by aek** [comment]
Hi @odony and @Yenthe666 
Thanks for your notes and tips, I also will try testing the report generation at that scale using the Odoo Gevented way that I found that it's having more performance and non-blocking than using workers prefork and I could get the workers CPU management by running mutiples Odoo Gevented instances and get it used behind the reverse proxy load balancer
Also I think that closing this issue is like hiding the issue because there are no sizing issues in my setup, the hardware resources are not consumed or exhausted at any time. it's a very very big good server with a lot of CPU cores and a large amount of RAM, a dedicated server on premise, not on any cloud.

**Comment by odony** [comment]
@aek I closed the issue because it seemed more like an open discussion better suited for a mailing-list. A "performance problem" can only be solved from outside with a reproducible test case, which seems difficult given your specific use case.
You would need to provide a ton of data about your setup and the configuration of all components for us to be able to analyze your situation.

All the tools are in place with Odoo to maximize the server utilization. If you throw lots of report requests at your server, you should be able to reach a very high load. Performance problems with a low server load are generally an indication that you have a config problem, because you're not using the hardware as you should be, even if it is appropriate. So you first need to identify that bottleneck.

For example if you see an improvement when using the gevent mode, it could mean your bottleneck was the number of `--workers` you used. If you configured 30 workers, you will only be able to print 30 reports at the same time, the others will be queued. If your server is able to handle more than 30 reports at a time, then simply increasing the `--workers` should help. The real limit for how many workers you can run is the RAM of your server (i.e. each worker will take a fixed amount of RAM that depends on the modules installed in your database, typically between 30 and 150Mb).
If and only if you reach the RAM limit quicker than how many reports you can print in parallel, then load-balancing multithreaded workers might be a workaround (gevent-based or normal servers with `--workers=0`).
But you'll have to be very careful:
- multi-threaded mode (gevent or `--workers=0`) suffers from the Python GIL bottleneck, so it can only use 1 CPU core. You will need to have enough servers to use all the hardware (but you need some for wkhtmltopdf and the database), and implement the load-balancing yourself.
- multi-threaded mode does not implement the multi-worker synchronisation mechanisms: no shared cache invalidation, no shared registry invalidation. You would have to take care of that, and to understand the consequences.

Then once you are able to maximize the server load, you can start looking for the next bottleneck, e.g. reducing the CPU time consumed for printing a single report, etc.

I have no issue reopening this issue (or another) if you provide supporting evidence to show that we do have a mistake in the code that limits the possible throughput you can get from the system. But you need to get the facts right, because we can't reproduce your situation and identify the bottleneck for you.

**Comment by tebanep** [comment]
We are having similar problems with the reporting system in Odoo as well. @odony do you know if running multiple processes with gunicorn and its gevent type worker processes, behind nginx, cause any problems in Odoo? This is a solution we are exploring just as @aek did, so the python processes don't block while large PDF reports are being rendered by wkhtmltopdf.

**Comment by elsayedmohamediraky** [comment]
@Yenthe666 
hi .. 
how to  print qweb report from direct printer without download pdf

**Comment by Yenthe666** [comment]
@elsayedmohamediraky you might want to ask this on the official help forums (https://www.odoo.com/forum/help-1) instead of posting on a Github issue. ;)
