### ISSUE TITLE
[17.0-CE/EE] widget="boolean_toggle" does not trigger the onchange function

### ISSUE THREAD

**Issue by anhvu-sg** [odoo/odoo#155063]
Impacted versions: 17.0 CE/EE

Steps to reproduce:
1. Create a boolean field X.
2. Define an onchange function for field X.
3. Specify widget="boolean_toggle" in the XML.

Current behavior:
- The onchange function does not trigger when the boolean field is changed.

Expected behavior:
- The onchange function should trigger when the boolean field is changed.

Video/Screenshot link (optional):
N/A

Support ticket number submitted via odoo.com/help (optional):
N/A

**Comment by vava-odoo** [comment]
Hi @anhvu-sg 
It looks like you forgot the decorator. See for example: https://www.odoo.com/fr_FR/forum/aide-1/how-to-apply-api-onchange-on-boolean-field-206843
Hope it helps.
Cheers

**Comment by owenzhang-i2t2** [comment]
In v17, all widgets have been refactored using owl components. 

`'boolean_toggle'` now accepts an new option named 'autosave', make sure to set this to false in form view in order to keep the form in edit mode when you toggle the button, otherwise it will auto save data and call `update()` on record, which doesn't trigger the onchange function.
`<field name="your_field", widget="boolean_toggle", options="{'autosave': false}"`

**Comment by anhvu-sg** [comment]
thanks @owenzhang-i2t2
