### ISSUE TITLE
[9.0, 10.0] Calendar view drag & drop does not respect client's timezone

### ISSUE THREAD

**Issue by yostashiro** [odoo/odoo#15540]
### Impacted versions:

9.0 and 10.0 (8.0 seems to work properly)

### Steps to reproduce:

1. Set your client machine's timezone to UTC+08:00
2. Open task calendar view (or any calendar view that supports drag & drop)
3. Try to move a task to another date by drag & drop.

### Current behavior:

The task moves to the day before where it was dropped.

I am not sure how exactly Odoo identifies the target date, but the problem does not occur when I change the timezone of my machine to UTC.

### Expected behavior:

The task moves to the date it was dropped.

**Comment by JKE-be** [comment]
Hi @yostashiro 

@nle-odoo are working at this time on a fix for your issue... 

It has been introduced during the migration from datejs to moment js.
That's why in 8 it was working and not in 9.

It should be fixed in the next hours.

@nle-odoo: Can you ping here the commit plz when it's done... thx

**Comment by yostashiro** [comment]
Thanks @JKE-be !   Looking forward to the fix arriving soon.

**Comment by nle-odoo** [comment]
hi @yostashiro, it should be solved with https://github.com/odoo/odoo/commit/a9da6e9f3f7 which will be soon (usually the time it takes is between 0-7 days) forward-ported in 10.0
