### ISSUE TITLE
[10.0] Unique constraint error with account code because trailing zeroes of the account code are cut off

### ISSUE THREAD

**Issue by JosefKaser** [odoo/odoo#15573]
**Impacted versions:**

odoo 10, maybe also odoo 9 (not tested)

**Steps to reproduce:**

Install the german SKR04, set the number of digits to 4 (parameter code_digits), create a debitor account with the number 11510, then change and save accounting settings or try to open the company settings.

**Current behavior:**

Validation error "The code of the account must be unique per company !".

The message results from the SQL constraint at

[https://github.com/odoo/odoo/blob/10.0/addons/account/models/account.py#L120](https://github.com/odoo/odoo/blob/10.0/addons/account/models/account.py#L120)

```
    _sql_constraints = [
        ('code_company_uniq', 'unique (code,company_id)', 'The code of the account must be unique per company !')
    ]
```

Root cause of the error is the function reflect_code_digits_change(self, digits) at [https://github.com/odoo/odoo/blob/10.0/addons/account/models/company.py#L75](https://github.com/odoo/odoo/blob/10.0/addons/account/models/company.py#L75)

It strips trailing zeroes from the account code before padding the code to the configured number of digits. In the example mentioned above this leads to the following:

- the account code 11510 is being changed to 1151
- this results in a duplicated account number because SKR04 has a standard account 1151

**Expected behavior:**

Accounting settings could be saved and company settings could be opened without getting the error. Trailing zeroes must not be stripped off of the account code when appliying the value from the parameter code_digits.

Video/Screenshot link (optional):

**Comment by qdp-odoo** [comment]
Well, this issue seems a bit complicated to get:
* you need to have defined 2 accounts that would overlap if the number of digits set was respected
* you need to change something in the settings
* you need to be in debug mode

It's unlikely something people will face in real life, although I recon that it's quite annoying. On the other hand, I do not want to restrain people from creating their accounts as they want since it would create even more issues.

So unfortunately, this is not something we can solve in stable versions, but we already planned to remove the code_digits from the settings(*), so that will be automatically fixed at that time. Thanks for your understanding.



(*): people will still be able to to switch the number of digits of all their accounts, by doing an export/import of their CoA.

**Comment by mncoon** [comment]
@qdp-odoo On your plan, I think it will be good to have a data-field in the xml of the accounting charts to set the standard-digits, on installing the chart.

**Comment by qdp-odoo** [comment]
this is already the case https://github.com/odoo/odoo/blob/11.0/addons/account/models/chart_template.py#L94

**Comment by mncoon** [comment]
Yes I know, but here in Germany we have always 4 digits as standard, which means on your plans, we always need to export import the charts on each customer....

**Comment by qdp-odoo** [comment]
ok that will be fixed to 6 by default

**Comment by qdp-odoo** [comment]
@csnauwaert

**Comment by JosefKaser** [comment]
@qdp-odoo 
Please be aware of two things:

In Germany general ledger accounts do have 4 digits because most companies and tax consultants are using a CoA which is based either on the SKR03, the SKR04 or the IKR.

Debitor and creditor accounts do have 5 digits most of the time, following the recommendations of DATEV which is the key player in the software and service market for tax consultants and SMEs.

Setting the digits to 6 would break this, all non-6-digit accounts would be padded with trailing zeroes. This would confuse accountants and tax consultants.

**Comment by qdp-odoo** [comment]
thanks Josef for your clarification. It will then stay as it is now
