### ISSUE TITLE
[9.0] Mismatched labels and form fields in ecommerce checkout

### ISSUE THREAD

**Issue by Armitxes** [odoo/odoo#15617]
Impacted versions: 9.0 (not tested for others)

Steps to reproduce:
Install Website Sale Module. Fill partner details (street, w/wo parent_id, name, etc.) and make him a portal user, add a purchasable product. Login as the partner, add the product to cart & go to the checkout.

Current behavior:
The form fields are named & filled completly wrong. Different (yet wrong) behaviour dependend of if you have a parent_id set in the partner or not.

Expected behavior:
"Your Company" must be labeled "Street"
"Street" must be labeled something like "Additional address Information"

Video/Screenshot link (optional):
![odoowtf](https://cloud.githubusercontent.com/assets/6265296/23269666/9ac2ec50-f9f1-11e6-95c6-929c177868bf.png)

**Comment by mlaitinen** [comment]
Please use more descriptive title and instead of typing "self-explanatory" in the expected behavior, tell how you expect it to work, even if it was quite obvious.

Usually it's hard to find issues if the titles are "Serious bug in <insert module>" or "This would be a cool feature". A title such as "Mismatched labels and form fields in ecommerce checkout" makes it easy to find this issue.

**Comment by JKE-be** [comment]
Thanks for the reporting.

Duplicated of:
#2541
#11619
#12541
#12590
#13198
#15354
#15221 
...

It has been by design, until v10, to avoid the duplication of res_partner.

In v10 it has been updated, using a real field company_name instead of street2 and a button to create the real res_partner.

Thanks
