### ISSUE TITLE
Bug in retrieving purchase price: sorting by min_qty

### ISSUE THREAD

**Issue by marcwimmer** [odoo/odoo#15616]
Impacted versions:
9.0

Steps to reproduce: 
- create two seller_ids at product (product.supplierinfo)
- sort them
- sort the smaller min_qty above:

SORT  MIN_QTY         PRICE
1             1                     10,-
2           1000                  9,-
- make purchase order and set quantity to 2000 --> price 10,- is picked

Current behavior:

price 10,- is picked

Expected behavior:

price 9.0 should be picked

Video/Screenshot link (optional):

suggestion:

- change product.py around line 926:

for seller in product_id.seller_ids:

to 

for seller in product_id.seller_ids.sorted(lambda seller: seller.min_qty, reverse=True):

then it is correct!

**Comment by pedrobaeza** [comment]
I confirm the problem, but I think a better solution is to change the order of the model by `min_qty desc, sequence...`.

@nim-odoo maybe you can check this

**Comment by gdgellatly** [comment]
@pedrobaeza I don't think either is a good solution, just because you might have multiple different sellers (i.e. partners).  While it won't get sorted in 9.0 I think a better design is storing the qty breaks on a single seller record.  Afterall, none of the other information changes with qty except price in that case.

I'd love for this bit of code around supplierinfo to have some refactoring/redesign though.  Its kind of had a few workarounds put into the procurement rules but there is often more complex business rules to selecting a seller than just min_qty (e.g. leadtimes, location, percentage share agreement).  I think also in 11 I managed to get a bugfix for the date issues put in, and those conditions maybe factored out.

**Comment by pedrobaeza** [comment]
I agree with you that this can be improved, but on current data model, it can be the solution. Any way, if I don't remember bad, there's a method that select the supplier that can be extensible for getting what you want.

**Comment by gdgellatly** [comment]
@pedrobaeza Unfortunately you don't remember correctly.  The method can't really be extended.  It loops, runs a cascade of if tests, then breaks on first match making it literally impossible to extend.  Only choice is complete overwrite.

Also this isn't to me a real solution, just because
Preferred Supplier A - min qty 1  price $8
Alternate Supplier B - min qty 2  price $9

**Comment by pedrobaeza** [comment]
Yeah, then we can propose a PR in master for changing this for >=v12

**Comment by Yenthe666** [comment]
Hi @marcwimmer,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 9 is no longer supported as Odoo only supports three versions (10.0, 11.0, 12.0 at the moment).
If you can still reproduce this issue on Odoo 10, Odoo 11 or Odoo 12 we encourage you to create a new bug report.

Regards,
Yenthe

**Comment by marcwimmer** [comment]
no prob - i personally patched the def.
thanks for feedback and fixing this - odoo is great.
cheers
