### ISSUE TITLE
[10ee+ce] sales to invoice does not take down payments into account

### ISSUE THREAD

**Issue by aduijs** [odoo/odoo#15629]
Impacted versions:  10ee+cc

Steps to reproduce:
create sale, create downpayment invoice, (optional: register payment of the downpayment)
go to sales -> invoicing -> sales to invoice

Current behavior:
sales to invoice shows the total value of the sales order (but xx% already has been invoiced)

Expected behavior:
sales to invoice should show the amount left to invoice.
If an downpayment invoice has been created (and paid) it should decrease that amount

Video/Screenshot link (optional):
![image](https://cloud.githubusercontent.com/assets/7501203/23307136/7079e272-fa74-11e6-8751-ff41e0d405cf.png)
![image](https://cloud.githubusercontent.com/assets/7501203/23307168/939f07dc-fa74-11e6-879b-33c61698ab61.png)
![image](https://cloud.githubusercontent.com/assets/7501203/23307179/a3dd7cbe-fa74-11e6-8c89-339fa39e6682.png)

**Comment by Yenthe666** [comment]
@qdp-odoo can you look at this?

**Comment by hex2a** [comment]
is there any update on this bug?
this bug breaks the downpayment feature almost completely..

**Comment by aduijs** [comment]
nothing so far.

**Comment by fpodoo** [comment]
When you invoice the sale order, there is two options: decrease down payments (second option) or not (first option). Did you choose the second option?

If not, it's more a usability issue than a bug.

**Comment by aduijs** [comment]
@fpodoo fabian that is working fine. 
what i am pointing out is when you have generated your down payment and click the menu option "sales to invoice"
![image](https://user-images.githubusercontent.com/7501203/28597230-560426ae-7162-11e7-9ff3-6ff5bfd4ae7b.png)
that next screen has all the amounts without the down payments reduced.
so you never know exactly what amount is still open to invoice or can be invoiced

this is the case in EE and CE

**Comment by aduijs** [comment]
so in my example the total invoice is 3540
a down payment has been generated and paid of  1770 (50%)
so the screen "sales to invoice" should say: 1770  and not the full amount of 3540

**Comment by qdp-odoo** [comment]
@lap-odoo can you make a task in some internal project for that?

**Comment by lap-odoo** [comment]
@qdp-odoo : done, task 35444

**Comment by fgi-odoo** [comment]
@aduijs this view shows the SO total like other SO views. I don't see enough added value in adding that for accountant users. The most important for accountants is to easily find the orders to invoice, not the amount to invoice. Managers can find this metric in sales reporting: https://drive.google.com/a/odoo.com/file/d/11V1uZc4cdKeXzYG3iYhwMjIutx3Jfs34/view?usp=drivesdk.
If you or your customer need that, this can be easily added as a new customized field.

**Comment by janbec** [comment]
Thank you for getting back on this issue @fgi-odoo 
I will have to disagree though. From our point of view, displaying the amount to invoice would add a lot of value. Especially since the Sale to order is a replica of orders with invoiceable filter.

We are in B2C and have a lot of long-term projects and we don't want to spam our customers with little amount invoices. So having this metric would be relevant for us (the link you posted is only available in v11). Since I am not a developer, could you outline on how to achieve this?

**Comment by janbec** [comment]
@hex2a @aduijs 
If you are still having trouble with this, I wrote a small application for us available [here.](https://github.com/janbec/odoo/tree/master/sale_order_amount_to_invoice)

I had to put in some extra logic because we have a customization running for unit_price which can be easily removed. Had to replace the Sale to invoice view because view id was the same as for the regular sale order tree view.

**Comment by TelmoSenseFly** [comment]
I am the same issue. Down payment is not taken in consideration.

**Comment by janbec** [comment]
@Yenthe666 
This issue has been around for over a year and it looks like odoo considers this a customization case. 
I posted a link to my customization to solve this. How do you want to proceed with issues like this? Close?

**Comment by Yenthe666** [comment]
@janbec hmm yes, as there is an internal task and the feedback was it is not considered a bug I'm closing it. Sorry.

**Comment by janbec** [comment]
ok, maybe @lap-odoo can check what happened to task 35444 ? Thanks!

**Comment by Yenthe666** [comment]
Yep, or @fgi-odoo :)
