### ISSUE TITLE
[17.0] Automatic inventory valuation settings lost

### ISSUE THREAD

**Issue by vladignatov** [odoo/odoo#156226]
Impacted versions: 17.0 Community

Steps to reproduce:  

1) Log in as Admin and enable Developer mode.
2) Add the Admin user to
- Technical / Stock Accounting Automatic group
- Technical / Show Full Accounting Features group
3) Switch to Inventory module. Then Configuration > Product Categories
4) Pick a product category (I picked All / Salable) and change it to Automatic inventory valuation. Save settings.
5) Switch to Settings and immediately click Save without making any changes.
6) Go back to the Product Category that you se to Automatic and verify that your change has been reverted.

Current behavior:  "Automatic" valuation setting on a Product Category is reverted to Manual by the system.

Expected behavior: "Automatic" valuation setting on a Product Category persists after changes to system settings.

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by vladignatov** [comment]
This is the same issue as https://github.com/odoo/odoo/issues/159651 
It is better described in there.

**Comment by 0xSaltyHash** [comment]
The culprit pull request is #133229. 

from my understanding is that if the user has the group `Technical / Stock Accounting Automatic group` and adds a product category with valuation set to Automatic but the feature is disabled from the Inventory Settings it will reset it to manual. the logic behind this as I understand it that if a user updates the `res.config.settings` it will check if the feature is enabled by checking the field `group_stock_accounting_automatic` but the catch is that this field is always `False` and it is not present in the view so there is no way for a user to set/enable it. 

I am creating a pull request to correct this behavior because currently if the only way a user is able to add a product category with valuation set to automatic by obtaining a group and then finding it reset because the feature is disabled with no way of enabling it.

**Comment by 0xSaltyHash** [comment]
On a second look, I have found the Feature toggle but in enterprise as part of Accounting Settings. I don't know if this is something that is supposed to be enterprise only? as accounting is Part of OE.

**Comment by vladignatov** [comment]
> On a second look, I have found the Feature toggle but in enterprise as part of Accounting Settings. I don't know if this is something that is supposed to be enterprise only? as accounting is Part of OE.

You are correct that this is a setting that is part of the Accounting module.  It was always available EE, but could also be enabled in CE after jumping through some hoops.  Like, enabling full accounting.  This was the case in 16 and I doubt that the intent was to remove this functionality from CE in 17 and moving forward.

**Comment by 0xSaltyHash** [comment]
I think we will require the input of one of the odoo team to clarify some points first, because it is not clear to me yet how to handle this for CE. 

one way I see it in this method:

https://github.com/odoo/odoo/blob/bad8b1e83798e8db6b4c37094c0fcd83bcbe294f/addons/stock_account/models/res_config_settings.py#L17-L22

requires some modifications if one would need to retain the product categories with automated valuation if it was created/modified by a user with the Stock Accounting Automatic in CE while the feature is disabled (because in community you don't have the option to enable it). 

so I propose to modify this to be 

```
def set_values(self):
        automatic_before = self.env.user.has_group('stock_account.group_stock_accounting_automatic')
        super().set_values()
        if automatic_before and not self.env.user.has_group('stock_account.group_stock_accounting_automatic'):
            self.env['product.category'].sudo().with_context(active_test=False).search([
                ('property_valuation', '=', 'real_time')]).property_valuation = 'manual_periodic'
```

This way if:

A: The user had the group set manually by an admin, and then created or modified a Category with Automated Valuation > then does any modifications to the settings and saves then the Product Categories that are with automated valuation will not change. 

B: user in OE disables the Automatic Accounting feature then it will revert the Automatic valuation option that was previously set on the Product categories. 

but I am not sure this is the best course of action.

@ticodoo @amoyaux Can we please have your inputs here.

**Comment by vladignatov** [comment]
Agree.  There are multiple ways of addressing this. On my current instance of 16 CE I simply exposed in the Settings menu by extending the view with the following code:

<xpath ***@***.***='languages']" position="before">
                <div id="stock_accounting">
                    <block title="Stock Accounting" id="stock_accounting_div">
                        <setting string="Automatic Stock Accounting" help="Enable use of automatic inventory valuation" title="Enable use of automatic inventory valuation" name="stock_accounting_setting_container">
                            <field name="group_stock_accounting_automatic"/>
                        </setting>
                    </block>
                </div>
            </xpath>

This gave me the option of enabling/disabling automatic inventory valuation by ticking a checkbox and the settings persist.

Vlad
________________________________

**Comment by vladignatov** [comment]
![image](https://github.com/odoo/odoo/assets/12549381/5e86db9a-1797-4fd1-8191-debf6a201f98)

**Comment by javaamps** [comment]
Is there any traction on this? I was ready to go live until discovering this bug. Is a workaround feasible without causing future issues with Inventory valuation?

**Comment by vladignatov** [comment]
> Is there any traction on this? I was ready to go live until discovering this bug. Is a workaround feasible without causing future issues with Inventory valuation?

Can’t really say… I found it and came up with the fix that worked for me. However, I’m new to Odoo and don’t know how my patch will affect the larger code base.  I did go live with this patch, but to be fair we are not fully using automatic inventory just yet.  

Need experts to weigh in.

**Comment by javaamps** [comment]
Thanks Vladignatov. I'll probably go with the solution similar to yours, although I'm on Odoo 17 CE.

I am not a programmer - could you help me understand which exact view you modified and what this line does:
    <xpath ***@***.***='languages']" position="before">
Are the *'s to be modified with an actual reference?

**Comment by vladignatov** [comment]
You need to add an extended view to **res.config.settings.view.form.inherit.base.setup**

just open it up, go to Inherited tab and add a new view from there.  Call it:
**res.config.settings.view.form.inherit.base.setup.customizations**

put <data><\data> tags in the text box and paste the code from above in between the tags.

**Comment by javaamps** [comment]
Thanks for your help. I apologize for being obtuse but I still don't understand the xpath statement. What am I supposed to do with this part -  ***@***.*** ?

I'm obviously getting it wrong as I get this error, with line 1, col 8 being at the first *
  "error parsing attribute name, line 1, column 8"

**Comment by javaamps** [comment]
I got it. I didn't realize the forum was modifying your actual xpath statement with asterisks. Thank you for your help!

**Comment by epidemiaf1** [comment]
could you provide a pic of the actual xpath statement? I can't figure it out.

**Comment by vladignatov** [comment]
Here you go.  I hope this goes though.

Vlad
________________________________
