### ISSUE TITLE
[>9.0]Unable to assign the same bank account to different employees

### ISSUE THREAD

**Issue by treviser** [odoo/odoo#15636]
It is not possible to assign the same bank account to more than 1 employee. IMHO this is an unnecessary restriction and it is a serious problem for example when 2 married persons sharing one bank account are working together in the same company.

**Comment by wtaferner** [comment]
@treviser 
Here is the simple fix for your issue, I'll backport it to v9 and will make a pull request that it might get merged. IMHO it should be possible as it does not hurt the stable policy as it just gives a little more freedom in case you update the base module.

**Comment by treviser** [comment]
Cool, thanks!

**Comment by Yenthe666** [comment]
Hi @treviser,

I'm closing this issue as an official response has already been given at https://github.com/odoo/odoo/pull/15638
The response from Martin:
```
Hello,

As it for now, after discussion with @qdp-odoo, I don't think it is a good idea to allow several people to have the same bank. The reason we added this constrain in the first place was to prevent having 2 companies sharing the same account.
```
Thank you for the suggestion though!

Regards,
Yenthe

**Comment by treviser** [comment]
I'm afraid I have to surrender unconditionally. I'm not comfortable with the situation. It is truly a very nasty and incomprehensible obstacle to use Odoo for millions of typical small family businesses.

**Comment by Yenthe666** [comment]
@qdp-odoo after relooking at this.. why don't we expand the constraint so this is possible?

**Comment by akselon** [comment]
We also have multiple contacts, where we would like to add the same bank account. See my question on Stackoverflow: https://stackoverflow.com/questions/58185438/odoo-is-it-possible-to-use-the-same-bank-account-for-multiple-contacts/

**Comment by akselon** [comment]
Please add this solution to official Odoo code: https://github.com/wtaferner/odoo/commit/326727bbd7161f6c2af68009d3d9fc924772d665

**Comment by Yenthe666** [comment]
@qdp-odoo would love to hear back from you buddy ;)

**Comment by qdp-odoo** [comment]
right, as requested, we will discuss that topic with @avw-odoo . I'll keep you informed

**Comment by egonravalah** [comment]
2 months have passed, how did the talking went?

**Comment by qdp-odoo** [comment]
the constraint is a limitation of the current system and cannot be changed in stable. No way. It's currently used to try to match a bank account number (from bank sync or statement imports) with open journal items for the _same_ partner. The algorithm is based on the partner detection and assumes that at most **one** partner with the given bank account is found. 

So you'll understand that relaxing the constraint would mean more than a one-line patch: it would need a deeper refactoring and would be, anyway, a behavior change. For these reasons, no patch regarding that would land in stable any time soon.

That being said, we acknowledge the situation needs improvement and we plan to do so, in master, before the release of version 14.

In the meantime, if you're in situation where you'd need it, let's say: two employees that are married and share the same bank account, I'd recommend:
+ setting to both your employees a new commercial partner id as parent (family \<last_name>)
+ setting to the parent partner the bank account they share

Hope that helps.... I'm closing the bug report, since we don't plan to change anything in stable.

best regards.

**Comment by alexis-via** [comment]
FYI, the constraint has been changed in odoo v16:
https://github.com/odoo/odoo/blob/16.0/odoo/addons/base/models/res_bank.py#L89

```
unique(sanitized_acc_number, partner_id)
```

So this problem only affects odoo up to v15 included.
