### ISSUE TITLE
POS doesn't update quantity on hand. 

### ISSUE THREAD

**Issue by arkotech** [odoo/odoo#15635]
Impacted versions: 
9.0c

When making sales through POS, quantity on hand for the product sold isn't updated.

**Comment by arkotech** [comment]
So far I learned that if a POS is used by administrator, this problem doesn't happen. 
Please any help because it doesn't make any sense to make every cashier an administrator

**Comment by jorenvo** [comment]
It's most likely because the system is unable to auto-validate the pickings generated by the POS, because that is the way quantity on hand is modified. Could you verify that the user you're using can validate pickings? If this is not the case you can either give the POS user access to do this or you will have to do it manually with another user.

Do keep in mind that this 'auto-validation' feature will not work for products tracked by lot or serial numbers.

**Comment by arkotech** [comment]
Thank you for the hint.
It turns out that the problem was in the user creation. The users that didnt have the login username as an email format, where creating empty PoS Orders that couldn't be validated.

**Comment by travish2** [comment]
Thank you for posting the answer, I had this exact issue in v10.

Should this not be considered a bug?

**Comment by arionkosturi** [comment]
Yeah basically. If it needs an email format it shouldn't validate on user creation or in login auth.
