### ISSUE TITLE
Error when selecting UPI as payment method in Odoo App Store

### ISSUE THREAD

**Issue by samuddhan-sttl** [odoo/odoo#157352]
**Impacted versions:** Odoo App Store UPI Payment Issue

**Steps to reproduce:**
1. Add any paid module to the cart.
2. Proceed to checkout.
3. On the payment page, select UPI as the payment option.
4. Click on "Pay Now."

**Current behavior:**
- Upon selecting the UPI option, no field for UPI details is displayed.
- When clicking on "Pay Now," an error occurs: "Incorrect Payment Details [ Cannot read properties of undefined (reading 'getState')]"

**Expected behavior:**
- Upon selecting the UPI option, a field for inserting UPI details should be displayed.
- Users should be able to make payment through the UPI option successfully.

**Video/Screenshot link (optional):** https://www.awesomescreenshot.com/image/46697804?key=5dda8d1fc4eafc8db48581adcdc8af4a

**Support ticket number submitted via odoo.com/help (optional):**

@fpodoo @mga-odoo

**Comment by Adityaupadhye** [comment]
This error is on production?

**Comment by samuddhan-sttl** [comment]
> This error is on production?

Yes, this is on production in Odoo App Store.

**Comment by madprog** [comment]
Hello, and thank you for reporting this problem.

However, I tried but couldn't manage to reproduce the issue.

Do you still observe the issue?
It might have been fixed in the meantime if someone else reported it.

Do you also observe the issue if your cart contains a product from /shop (e.g. IoT Box or a ScaleUp! box)?

Thank you again for your feedback

**Comment by samuddhan-sttl** [comment]
Hello,
I also tried to reproduce it but couldn't. It might have been fixed.
