### ISSUE TITLE
[9] POS interace dosen't load on iPad 2

### ISSUE THREAD

**Issue by FelixINX** [odoo/odoo#15794]
## Impacted versions:
Odoo 9 (Online). Tested on iPad 2 with iOS 9 (latest version).
**The following browsers as been tested : Safari, Chrome, Firefox and Opera Mini. Opera Mini is the only working.**

## Steps to reproduce:

- Open example.odoo.com and login
- Open a session in the POS module
- Click on continue session to load example.odoo.com/pos/web

## Current behavior:

- Grey screen, no loading

## Expected behavior:

- Loading UI

## Screenshot:
![From #6292](https://cloud.githubusercontent.com/assets/12483798/7670674/a414a010-fce0-11e4-9508-c0fc8a3dad93.png)

Taken from #6292. However, we don't have the restaurant mode enabled.

## Aditionnal info
The iPad has been hard reset. I have also tested this issue on an iPad Mini 1, same iOS version, working on this one.

_Followup @Yenthe666_

Thanks!

**Comment by Yenthe666** [comment]
Hi @FelixINX,

Thank you for your report!
@nim-odoo and @jorenvo could you guys look at this?

Regards,
Yenthe

**Comment by nilshamerlinck** [comment]
@FelixINX Could you add `?debug=` to the URL and check for errors in Chrome's DevTools Console? Also, could you report the exact version of the Safari rendering engine running?

**Comment by FelixINX** [comment]
@nilshamerlinck Thanks but we were in march break, and back, all is working fine. I don't know what happen (no updates of iOS).

For the `debug` param, it dosen't do anything, there is no dev tools...

Still keeping it open if you want to investigate

**Comment by jorenvo** [comment]
I tested briefly with the same iOS version when this was originally reported but could not reproduce. It means that there is either some state the POS is in that is throwing the error (maybe just on iOS?), or it is an iOS issue somehow.

The issue is further complicated by the fact that there is no easy way to get to a JS console where you could see the error. In order to do that I think you would need a Mac and you would have to set it up so you can remotely debug an iOS device. If you ever run into the issue again and you want to spend the time to do this it would help greatly in fixing this issue.

By the way, as far as I know all browsers on iOS use the same rendering engine, even Chrome. So if it doesn't work in eg. Safari, it won't work in Chrome or any other browser either.

**Comment by nilshamerlinck** [comment]
For the record I had a similar issue with Safari rendering engine version 601.1.46, and indeed as all browsers are forced to rely on the same engine, it wasn't working for any of them (tested with Safari/Chrome/Opera). An update to latest version of iOS, bringing Safari engine 602.1, solved the problem.

**Comment by pedrobaeza** [comment]
@jorenvo any news about this?

**Comment by jorenvo** [comment]
I have again tested on a (simulated) iPad 2 and everything seems to work as expected. If you are still experiencing this issue please let us know and we will reopen this.

![bs_ios_tablet_ipad 2 5 0 -5 0](https://user-images.githubusercontent.com/10252581/39882673-53fc322e-5439-11e8-8579-ff498cfec5e9.jpg)
