### ISSUE TITLE
[10.0][BUG] The name of sale.order is always new when the language is not English 

### ISSUE THREAD

**Issue by eneldoserrata** [odoo/odoo#15839]
Impacted versions:
10.0
Steps to reproduce:
1-Change the language other than English
2-Create sale order
Current behavior:
Check the name and note that it does not take the sequence
Expected behavior:
Let the name have the proper sequence
Video/Screenshot link (optional):
<img width="1228" alt="pasted_image_3_13_17__1_24_am" src="https://cloud.githubusercontent.com/assets/360270/23842628/02e06946-078c-11e7-8b7b-25f212a733c3.png">
<img width="998" alt="sale_ _sale_py_-_odoo10_-____pycharmprojects_marcos_odoo10_" src="https://cloud.githubusercontent.com/assets/360270/23842683/5d9b620a-078c-11e7-8b40-864780d66f50.png">

**Comment by mart-e** [comment]
Hello,

>  2-Create sale order

This part was the important one to explain. This bug is not reproducible in most cases as the name is not given in the web interface (readonly field), so only if you manually assign the default value.

But anyway, even if you should not really get into a bug (I guess due to a customisation), the condition in the create is not consistant with the default value.

Fixed at 4c79aa8d9d5
