### ISSUE TITLE
Output of the "float_round()" function appears to be incorrect

### ISSUE THREAD

**Issue by safi-ibrahim-95** [odoo/odoo#158715]
Impacted versions: 15, 16, 17

Steps to reproduce: 
```python
_logger.info("float_round(499.6800000000001)" + str(float_round(499.6800000000001, precision_digits=2)))
_logger.info("float_round(500.6800000000001)" + str(float_round(500.6800000000001, precision_digits=2)))
_logger.info("float_round(510.6800000000001)" + str(float_round(510.6800000000001, precision_digits=2)))
_logger.info("float_round(511.6800000000001)" + str(float_round(511.6800000000001, precision_digits=2)))
_logger.info("float_round(512.6800000000001)" + str(float_round(512.6800000000001, precision_digits=2)))
_logger.info("float_round(513.6800000000001)" + str(float_round(513.6800000000001, precision_digits=2)))
```

Current behavior:
the output is :
499.68
500.68
510.68
511.68
512.6800000000001
513.6800000000001

Expected behavior:
499.68
500.68
510.68
511.68
512.68
513.68

Screenshot link:
![image](https://github.com/odoo/odoo/assets/164418360/2fbd25f6-5487-4857-b46a-86d82a6ee4a4)

I don't know why float_round() function not rounding the number above 512 in this example. dose anyone have same issue?

**Comment by Feyensv** [comment]
This is not an issue of `float_round` but the inability of python to represent some floating points numbers.

More information:
https://0.30000000000000004.com/ (short description of the underlying issue)
https://docs.python.org/3/tutorial/floatingpoint.html

That's why python has a dedicated library and type to perfectly represent decimals: https://docs.python.org/3/library/decimal.html (which is not used in odoo until now, notably for performance reason, but might be in the future).
