### ISSUE TITLE
Using custom front-end owl-components in custom assets bundles

### ISSUE THREAD

**Issue by sanderlienaerts** [odoo/odoo#159056]
Hello there,

In a project we are incorporating custom owl components with a custom assets bundle to use in front-end pages, while following best practices mentioned in the [guide](https://www.odoo.com/documentation/17.0/developer/howtos/standalone_owl_application.html#creating-an-assets-bundle-containing-our-code ) for creating a standalone owl application and the [guide](https://www.odoo.com/documentation/17.0/developer/howtos/frontend_owl_components.html) for creating front end owl components.

This works like a charm. However implementation questions remain. For future compatibility we want to make sure that the `public_components` service is used correctly. 

Therefore: Is it OK to use the public components service for custom owl components defined in a custom assets bundle? Or should we follow the guide, and define the custom front-end owl components in `web.assets_frontend`?

**Comment by chrisb-c01** [comment]
@sdegueldre perhaps you can advice in this?

**Comment by chrisb-c01** [comment]
I think the main question is if the public components service can access/is interoperable with custom assets bundles or is it limited to the default (frontend/backend) bundles? This, because the [example](https://www.odoo.com/documentation/17.0/developer/howtos/frontend_owl_components.html#adding-your-component-to-the-web-assets-frontend-bundle) in the documentation states that assets need to be added to the frontend assets bundle.

**Comment by sdegueldre** [comment]
It was designed to be compatible with the way that we start the services and stuff in the frontend assets but if it's useful to you in custom bundles, you can use it. There's nothing special or magical about the frontend assets bundle, it's just a different lifecycle from the backend so it needs to allow mounting components differently. If you have a use case where most of the page is rendered server-side and you want the ability to mount owl components piece-meal in various places then the public component service is a good choice and can be included in your custom assets bundle, but you should also consider simply using the frontend assets bundle instead of a custom one unless you have a good reason to want a custom bundle, since the frontend assets will already do a bunch of the heavy lifting for you.

**Comment by sanderlienaerts** [comment]
Thanks @sdegueldre, that really answers the public components questions we had.
