### ISSUE TITLE
[web] List views with *2many_tags widget perform 2 requests per record

### ISSUE THREAD

**Issue by Yajo** [odoo/odoo#15920]
Impacted versions: 8.0, 9.0c, 9.0e, 10.0c, 10.0e

Steps to reproduce:

1. Open runbot in any of those versions.
2. Go to contacts (or sales/customers) and filter by those contacts where *Tags is set*.
3. You're in kanban view, right? Then open the network inspector and refresh the search, you'll see something like:
   ![captura de pantalla de 2017-03-17 13-12-24](https://cloud.githubusercontent.com/assets/973709/24042916/72fa02e2-0b14-11e7-814f-47324ef19a25.png)
   Cool, 2 requests, 2 models.
4. Clear your network inspector and switch to list view.

Current behavior: 15 requests! 1 for your current search and 2 for each of the results:
![captura de pantalla de 2017-03-17 13-13-39](https://cloud.githubusercontent.com/assets/973709/24042953/9367f23c-0b14-11e7-9447-cf043fd626a1.png)

This has severe performance impact on slow servers/networks and big usage of tags.

Expected behavior: 2 requests, like kanban.

@Tecnativa

**Comment by wtaferner** [comment]
@Yajo 
There is more fun with the list views...have you ever tried to move a record with the sequence widget, especially in an embedded one2many or many2many? Besides it needs to change the other records in the list view (on client side obviously by now), it also is designed to increase by exactly one integer instead of introducing bigger steps on create and smaller steps on change and a better algorithm to handle the client side. Anyway, it is all about to be improved at some point I guess :-)

+1

**Comment by Yajo** [comment]
Well that should be handled in backend to make it faster indeed, but in any case it seems a different issue.

**Comment by wtaferner** [comment]
True and true, just wanted to show that it is a bigger construction site to fix your use case and other issues like that and I am pretty sure it is not as easy :-) So, let's do it (or at least wait for it) ;-)

**Comment by pedrobaeza** [comment]
@ged-odoo I suppose all of this changes with new view architecture, but as this affects all the previous supported versions (8-10), this deserves to be fixed, isn't it? Shall we investigate further?

**Comment by ged-odoo** [comment]
![screenshot 2017-03-20 12 12 40](https://cloud.githubusercontent.com/assets/7579538/24097628/017f6990-0d67-11e7-9a12-807e55cf4d15.png)

Totally unrelated note: cool, I just learned how to share images on github threads. 

To answer the question, the new views indeed do solve that problem, as you can see in the screenshot (also, it now renders many2many tags like in the form view, since it is exactly the same widget).  

This is indeed a bug, and should be fixed if possible. Sadly, it may be tricky/dangerous. I am not sure about this exact case, but batching the reads together may be a large architectural change, which is really really dangerous in stable (messing with x2manys in x2manys is a pretty sure way of breaking onchanges, or something). However, maybe we could find a way to at least do only one nameget per result, this may be a small and safer change.

In any case, I leave the issue open

**Comment by pedrobaeza** [comment]
Thanks for the confirmation, Géry. @Yajo, let's work us on solving the double nameget.

**Comment by Yenthe666** [comment]
Thanks for the confirmation @ged-odoo! In any case, if this change is too big for V10 we could still try to land it in master (V11). It is a neat improvement.
@Yajo good luck 😉

**Comment by Yajo** [comment]
Please check out https://github.com/odoo/odoo/pull/15967, which fixes the easy part.

**Comment by ged-odoo** [comment]
Thank you @Yajo  for your commit.  It looks good, and will be merged as soon as the runbot is green. 

Meanwhile, I acknowledge that the nameget rpcs should be batched, and this is a bug, but this is 'only' a performance bug, and is way too risky to change in stable.  Also, it is fixed in a branch that will be merged in master soon.

Therefore, I am closing this issue.  Thanks everyone for your comments/help.

**Comment by Yajo** [comment]
I'm eager to see the *promised branch*, thank you too 😉
