### ISSUE TITLE
Invoice PDF not updated

### ISSUE THREAD

**Issue by andriusdj** [odoo/odoo#159308]
Impacted versions: 17

Steps to reproduce:
1) Create an invoice and confirm it and check the generated PDF
2) Reset the invoice to Draft and change something in it, e.g. invoice sequence number and/or customer language
3) Save draft and confirm again (observe language is changed and sequence is corrected)
4) Send the corrected invoice to customer and/or print the PDF

Current behavior: Old invoice (from 1.) is sent to customer/printed in step 4.

Expected behavior: Current/correct invoice PDF is sent to customer in step 4. 

Confirm button should always regenerate PDFs or there should be a warning and a button which would allow to remove the old and invalid PDF. Also preview is showing the new and correct data. Now the data in PDF and in database/system differs which makes this a very dangerous issue.

Video/Screenshot link (optional):  
![Screenshot from 2024-03-26 13-51-28](https://github.com/odoo/odoo/assets/12236535/a8f09bb2-f30c-43b6-9a7f-6d8ab0442e04)
![Screenshot from 2024-03-26 13-45-38](https://github.com/odoo/odoo/assets/12236535/48fddd1d-168b-4837-9f23-dc10ec2d7071)

Support ticket number submitted via odoo.com/help (optional): n/a

Similar issue was already posted #151402, however this is still an issue on our case.

**Comment by andriusdj** [comment]
as a workaround I have found a very tiny almost invisible to the UX point of view button to show attachments and after removing the attachment the invoice has been regenerated.

UX/UI here needs improvement:
1) a warning flag needs to be present when PDF differs from actual data 
2) the attachment view needs to be expanded when the flag is present with an option to remove or recreate

**Comment by Yenthe666** [comment]
This workflow/proces has been in Odoo for 7+ years like this actually. If you delete the invoice attachments & click print again Odoo will generate the new version

**Comment by gdgellatly** [comment]
The workflow has been like this for way more than 7 years. It is absolutely necessary. Let's take a different example. 5 years ago you sell a company something. 3 years ago they change their name, 2 years ago their address. When the authorities come knocking, let's say a tax audit, you better be reprinting the original as sent.

**Comment by Yenthe666** [comment]
Indeed. So this is not an issue but done by design :)

**Comment by GOinfo-Ltd** [comment]
Hello.
Sorry for commenting on a closed issue.
I fully understand the concept behind being able to reprint exactly as first printed.

Without deleting the attachments, how do you suggest we can alter those invoices, for example to add late payment fees?

Would it not be possible to have a dropdown selection of generated attachments, so you can choose which document to send to the customer?

Thank you

**Comment by orfisko** [comment]
@Yenthe666 @gdgellatly I don´t agree at all that this is logical. That the generated invoice is being kept, fine. But the moment that I cancel an invoice, the original invoice _could_ be kept for archiving (although Odoo is not a document archival solution) but it _should_ generate always the pdf in its latest form if I then send the revised document. What we currently have is clearly a bug since:
-  the amount that is shown in the email if you use the default template could deviate from the amount shown in the document in case something changed to sale order lines or any other change after cancel and reissue.
- the pdf that is generated when the email is sent with the doc in attachment is only visible **after** the email is sent. The email interface indicates that there is an attachment, but you cannot open it in the email dialog
- the generated pdf when clicking on 'print' when using the 'gear' icon should always be the document that would be sent the moment that the invoice is being sent by email, that is now also not the case. 

To me it would make most sense that the system keeps copies of pdf versions of invoices as an audit trail, that is the single and most professional way to handle this.

**Comment by gdgellatly** [comment]
> [@Yenthe666](https://github.com/Yenthe666) [@gdgellatly](https://github.com/gdgellatly) I don´t agree at all that this is logical. That the generated invoice is being kept, fine. But the moment that I cancel an invoice, the original invoice _could_ be kept for archiving (although Odoo is not a document archival solution) but it _should_ generate always the pdf in its latest form if I then send the revised document. What we currently have is clearly a bug since:
> 
> * the amount that is shown in the email if you use the default template could deviate from the amount shown in the document in case something changed to sale order lines or any other change after cancel and reissue.
> * the pdf that is generated when the email is sent with the doc in attachment is only visible **after** the email is sent. The email interface indicates that there is an attachment, but you cannot open it in the email dialog
> * the generated pdf when clicking on 'print' when using the 'gear' icon should always be the document that would be sent the moment that the invoice is being sent by email, that is now also not the case.
> 
> To me it would make most sense that the system keeps copies of pdf versions of invoices as an audit trail, that is the single and most professional way to handle this. In addition, it should then always send the latest valid version that has been confirmed or created by the user.

This is very much a corner case. I don't disagree such cases exist, but for the majority of the time it is undesirable.  In any case it can be worked around, e.g. when I cancel an invoice I delete the attachments, alternately change the naming scheme to include last_update, amount or partner name. Or you can just disable the reuse on the report.

**Comment by Jeffabri** [comment]
I've been stuck with the same issue for days, but the cause was something else.Default odoo uses non-patched wkhtmltopdf.This causes issues on newer systems.

The patched version on it's turn requires libssl1.1 (not libssl3), which is also not by default available in recent ubuntu server versions.

Steps to solve:

Remove current installation:
sudo apt remove --purge wkhtmltopdf

Download and install libssl1.1
wget http://archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.0g-2ubuntu4_amd64.deb
sudo dpkg -i libssl1.1_1.1.0g-2ubuntu4_amd64.deb

Download and install qkhtmltopdf (with patched Qt)wget https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6.1-2/wkhtmltox_0.12.6.1-2.jammy_amd64.deb
sudo apt install ./wkhtmltox_0.12.6.1-2.jammy_amd64.deb

This solved it on my side!
