### ISSUE TITLE
RFC: Support addons compatible with multiple Odoo versions

### ISSUE THREAD

**Issue by dreispt** [odoo/odoo#15992]
As a maintainer of community addon modules, I see with frustration all the difficulties involved in porting modules between several versions, and ensuring that fixes and improvements are replicated between branches.

For modules that have little or no dependencies on official addons, most of the code is the same across for the severall Odoo versions.
So at the end of the day all the housekeeping required to maintain the several branches can seem like a waste of time.

What if Odoo modules could be made packaged in a way that they would be compatible with multiple Odoo versions?

In the cases where there are differences between versions, Python code files can detect the installed Odoo version and decide what code to run. This is already possible, so no additional features are needed here.

For data files, we would need to pick what to load based on the target Odoo version at hand.
I suggest allowing the "data" manifest key to be a dictionary stating the allowed Odoo versions for each data file.
For example:
```
'data': {
    'views\model_view_8.xml': ['8.0'],
    'views\model_view_9.xml': ['9.0', '10.0'],
    'security\ir.model.access.csv': [], # all versions
    },
```

Complementary to this, it would be nice to have a manifest key declaring the target Odoo versions for a module. This would save common frustrations, like installing a module for 8.0 on 10.0, and would ease the work for the App store to present the compatible Odoo versions in the module page.
Example:
```
'versions': ['8.0', '9.0', '10.0'],
```

If this is implemented, community module repositories can have a single branch ("stable" or "master") holding modules for several Odoo versions, and each module contains information on what versions it is compatible with.

Porting a module to a later version in many cases can be as simple as adding the new Odoo version the versions lists. 
If some tweaks are needed, we have the tools to allow performing specific installation actions only on some target versions.

I'm willing to give a try at the implementation, but I would like to first collect some feedback on the idea and proposed design. 
The initial implementation would target master, but for full effect should be backported the the active LTS versions.

@antonylesuisse @odony your comments are appreciated. Thanks!

**Comment by bealdav** [comment]
:+1:

**Comment by rvalyi** [comment]
@dreispt a problem I can think about: imagine that some repo R has module X living in the '10.0' serie branch and a module Y living in the master branch.

Imagine that you need both X and Y. You could even imagine a case where X is kind of a generic module that can cope with different Odoo versions while Y is an extension of it (Y depends on X) that is tied to an Odoo serie. I could imagine such a case in a localization with the base (partners) module being quite serie proof while accounting module would be tied to a specific serie.

How to cope with installing and testing such modules then if they live in the same repo under different branches?

Overall I like your idea, but we would need a solution for the problem I mentioned.

**Comment by dreispt** [comment]
@rvalyi You have a point, we have to think about the distribution process.
Different distribution channels may require different solutions: App store, Python packages, or Git.

Regarding Git, the simplest solution is to handle version branches ("10.0", "9.0") and the "master" (containing the multi-version modules) as if they were different repos: you would clone both R/10.0 and R/master, and add them both to your addons path.

**Comment by odony** [comment]
@dreispt I understand your pain, maintaining addons across versions is definitely time-consuming work. But doing it properly is a necessary task for many reasons related to maintenance, cleanup, etc. Even if a module technically "still works" in a newer series of Odoo, don't you think that it is important to do a decent review of the code and cleanup/simplify what can be cleaned thanks to the newer version? Think of new API primitives, higher-level business functions, cleaner extension points, etc. Every new version comes with many of those.
If we make it a policy that it's better to skip the upgrade phase of addons whenever you can, wouldn't we get lower overall quality of code in community modules?

As you noted, it's already possible to write a module that works differently depending on the server version. You can even register it for a different series on the Apps Store. But I'm not sure that's a good practice at all. You'd eventually end up with spaghetti code and tons of `#ifdef`-like blocks in your modules.
Upgrading your module for a newer series gives you a real opportunity to cleanup the past, rather than accumulating cruft.

We really felt the pain of upgrading all modules for the new API, but it was really worth it. Would you have kept the 2 versions of the code in your modules? Or decided to go for a clean upgrade and fork the module anyway? Not saying we'll overhaul the API very often, but I think that's a relevant example.
If you decide to split your module cleanly, you'll indeed end up with a complicated layout of repositories, with some modules forked for the new series, others upgraded "in place", and a much more complicated landscape for finding dependencies (as was already mentioned).

Looking at your "version-specific data files" proposal, it seems even more obvious that you'll end up doing almost as much work as you would with a clean upgraded fork of your addons, except you'll be doing it in place and accumulating "dead code".
You'll start refactoring the pieces that are generic in a `model_view_common.xml`, splitting the version-specific stuff version after version. This will introduce noise in your blame history, make code harder to read and follow than it could be, etc.

I'm really not sure the net outcome would be positive, when you make the balance between time saved in maintenance vs. complexity of the repository landscape and quality/cleanliness of modules for the future...
Maybe I'm missing a major benefit, though... :pensive: 

Note: adding a manifest key to specify *the* target series could make sense, but would be redundant in most repositories, and entirely block cases where a module would have worked by luck in a newer version. That said, there are probably more cases where a module breaks in a different series, so we'd be doing a favor to the users in the long run. Feel free to make a PR for that part ;-)

**Comment by hparfr** [comment]
Hi, 

Another possibility is to adopt the following versioning scheme: 

Update module's version
==================

(in \_\_manifest.py\_\_:['version'])

module __x__.__y__.__z__

* __x__: odoo major series
* __y__: module breaking changes
* __z__: modules updates 


For _improvements_ (bugfix, features, documentation): 
increase __z__: a_module 9.0.1 -> a_module 9.0.2

For _breaking changes_ (refactorings):
increase __y__: a_module 9.0.2 -> a_module 9.1.0

When a _new version of Odoo_ is out : 

If there is almost no changes in Odoo :  
increase __z__ : a_module 9.1.0 -> a_module 9.1.1
(at least update \_\_manifest.\_\_.py:['depends'])
_a\_module 9.1.1 will work against odoo 10_

For _major changes_ in Odoo : 
increase __x__: a_module 9.1.0 -> a_module 11.0.0
_a\_module 11.0.0 will only work against odoo 10 and upper._

Dependency modules
================

b_module depends of a_module.

In b_module' \_\_manifest\_\_.py
``` depends: { 'a_module': '>=9.0.0', }```

When new version of a_module is out : 

* If it's a minor update: a_module 9.0.1 . We know it has no breaking changes
``` depends: { 'a_module': '>=9.0.0', }``` (no changes)

* If it has breaking changes:  a_module 9.1.0. But we found it doesn't impact b_module.
``` depends: { 'a_module': '>=9.0.0 <9.2.0', }```

* If  it has breaking changes : a_module 9.2.0. And we found it impacts b_module
``` depends: { 'a_module': '>=9.2.0', }```

**Comment by Yenthe666** [comment]
Hmm, I believe we can conclude that it would be almost as much work as it is right now and that it is not on the roadmap?
Is a closure fine?
