### ISSUE TITLE
[17.0] stock : FIFO Costing method not working in product category

### ISSUE THREAD

**Issue by jamshu** [odoo/odoo#160275]
Impacted versions: 17.0

Steps to reproduce: add a new product category with FIFO Costing method

Current behavior: taking the cost as average , when we purchase the product with different cost
Expected behavior:when we purchase the product under fifo costing method, the cost should take from the exact price we 
purchased but it taking average costing

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by ray-odoo** [comment]
The cost in Inventory is correct.

It is just the cost on the product page we now show as average because we have to show a single cost on the product. 

We can't show all the costs like we do in Inventor

We still use inventory cost (not product cost) for cost of goods calculations.

See also the Odoo 17 Release Notes:

FIFO product costs
The cost of FIFO products is now set to the average price of the remaining quantities

**Comment by trinanda** [comment]
@ray-odoo, when we sell a product in Sales, the margin is still considered from the average cost, how do we handle this?

**Comment by ray-odoo** [comment]
@trinanda until a specific order is delivered I don't see how it is possible to know the true cost since other others may be picked before it. Essentially nobody knows the cost of what will be delivered until it is delivered. The only true margin comes from the Invoice when the cost of what was delivered is known.
