### ISSUE TITLE
fleet module and adblue

### ISSUE THREAD

**Issue by icf20** [odoo/odoo#16067]
Impacted versions: 10

i am testing fleet module and there is no way to add a second fuel to an vehicle, how i can add adblue fuel on top of the default one ?

**Comment by Yenthe666** [comment]
Hi @icf20,

By default you can only add one fuel type to one car, this is because it is a selection field in Odoo.
This means that you can't add two fuel types to the same car (for example: diesel and adblue) at the moment.
If you would like to do this you could add some custom development that allows you to add a second fuel type.

Regards,
Yenthe
