### ISSUE TITLE
[10.0]Bug:Shopping cart don't apply the Pricelist calculate

### ISSUE THREAD

**Issue by ed29** [odoo/odoo#16062]
Hi:
I am using odoo 10,it has a bug,that is Shopping cart don't apply the Pricelist calculate.

**Comment by Yenthe666** [comment]
Hi @ed29,

I'm sorry but with such a short bug report there is really nobody that can help you.
Please create a new issue in which you follow the template and fill out the steps on how to reproduce this.
Have you also tested this on the latest Odoo instance? (runbot.odoo.com).
Closing as we really need more feedback in order to help you.

Regards,
Yenthe
