### ISSUE TITLE
[10.0] Graph view Issue

### ISSUE THREAD

**Issue by vieterp-viet** [odoo/odoo#16296]
Impacted versions:
10.0
Steps to reproduce:
Graph view issue
Current behavior:

Expected behavior:

Video/Screenshot link (optional):
[Graph Issue](https://youtu.be/pkCpqMYSgpA)

**Comment by Yenthe666** [comment]
Hi @vieterp-viet,

Thanks for your report.
I can already see this is not a common Odoo as you've installed theme's and did custom development.
Because of this we can't accept this issue. Can you reproduce this on an official Odoo? (runbot.odoo.com) and if so, how did you do it? If you can reproduce it on an official just reply here and I'll reopen this.

Regards,
Yenthe
