### ISSUE TITLE
[16.0][i18n] Impossible to update wrong translation for country name

### ISSUE THREAD

**Issue by NL66278** [odoo/odoo#163252]
Impacted versions: 16.0

Steps to reproduce:
The country name 'Liberia' is translated in the base module as 'Liberië' in dutch. This is incorrect,. the dutch name is also Liberia.

Current behavior:
I tried updating this with an nl.po file in a directory i18n_extra in my own module: the canonical way to change standard translations that you want to overrule. Then I updated my module and next updated the dutch language specifying overwriting existing terms. This had no effect whatsoever. Then I updated the odoo source direcly (in odoo/addons/base/i18n/nl.po) and again updated the dutch language specifying to overwrite terms. No effect either.

Expected behavior: Either using i18n_extra, or patching standard odoo po files, should make it possible to correct wrong translations.

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by vava-odoo** [comment]
Hi @NL66278 
Thanks for reporting. Since 16.0, you can't update translations yourself. The change needs to be done in standard.
Translations in odoo are handled on [Transifex](https://explore.transifex.com/odoo/), not Github ([see documentation](https://github.com/odoo/odoo/wiki/Translations)).
Please submit your changes there and let me know if you have issues.
Cheers

**Comment by NL66278** [comment]
@vava-odoo I actually suggested the corrections in Transifex. Hope somebody will pick them up. Nevertheless the i18n_extra module is meant to customize translations, and still works in general, however apparently not for translatable fields.
