### ISSUE TITLE
[10.0] Bad filter on Journal entry from expense sheet

### ISSUE THREAD

**Issue by adrienpeiffer** [odoo/odoo#16375]
Impacted versions:

10.0

Steps to reproduce:

- Create one expense
- Submit this expense in an expense sheet
- Approve the sheet
- Post entry from the sheet
- Click on Accounting entries button

-> You can view one entry

- Go back to the created expense
- Create a duplicate from this one
- Submit this expense in an expense sheet
- Approve the sheet
- Post entry from the sheet
- Click on Accounting entries button

-> Now, you can view 2 entries

(See https://youtu.be/XEZQ_welkTk)

Current behavior:

The accounting entries button on expense sheet doesn't work correclty.

Expected behavior:

The accounting entries button on expense should work correclty.

Video/Screenshot link (optional):

https://youtu.be/XEZQ_welkTk

In Bonus, the related commit https://github.com/odoo/odoo/commit/0ff9af64ef5d64f3f3a9bdce072f925b8e93f2a5

**Comment by simongoffin** [comment]
@adrienpeiffer As explained, this issue has been fixed in saas-14 with the following commit:
e7b853493bb78cb1b23324eb96e191d3183a8ec3
But for technical reasons, we couldn't fix it in 10.0
A work around for this issue is to change the description of the expense(field name) when duplicating it because in 10.0 the filter uses the name of the expense to find the entries.
