### ISSUE TITLE
[10.0] Multiple journal entries for expense sheet

### ISSUE THREAD

**Issue by adrienpeiffer** [odoo/odoo#16376]
Impacted versions:

10.0

Steps to reproduce:

- Go on expense module
- Create an expense
- Create a second one
- Check both expenses in tree view
- Click on Action/Submit To manager
- Click on Approve
- Click on Post journal entries

Current behavior:

You have 2 journal entries (one for each expense).

Expected behavior:

There should be only one journal entry (with only one line on the customer account).

I think there is a design problem in the code in relation to that. For me, the logic of the generation of the journal entry should be at the level of the sheet and not at the level of the expense.

Video/Screenshot link (optional):

**Comment by nim-odoo** [comment]
That's the expected behavior. Maybe @qdp-odoo or @simongoffin can detail a bit more.

**Comment by adrienpeiffer** [comment]
Hi Nicolas,

Thanks a lot for your answer.
Anyway, I hope this will change in the next version because for me this is not usable as is. So, there will be as many open line on the employee's account as expense line on the sheet ... This makes the payments very difficult or impossible.

In addition, there are other problems related to this https://github.com/odoo/odoo/issues/16375

@qdp-odoo, @simongoffin , @nim-odoo Is there a functional explanation for creating a move per line?

Thanks,

Adrien

**Comment by qdp-odoo** [comment]
there is one problematic use case: several expense lines on the same sheet, paid by the company.

Indeed, if you create a single account.move for that, you would have one blue line per expense in the bank statement reconciliation widget and you wouldn't be able to reconcile all of them since the link between bank statement line and the accounting was on the move. So when you were trying to reconcile the second blue line, it removed the link you already saved for the 1st line.

That has already been improved in saas-14 where we moved the link on the account.move.line level, so 
 in the future versions we will be able to create one single journal entry per expense.... but for prior versions, the database structure can't be changed, and we have to avoid creating an account.move with several account.move.line on a bank account since it is not fully supported.
