### ISSUE TITLE
Inventory value does not update from vendor bill.

### ISSUE THREAD

**Issue by elevationO** [odoo/odoo#16441]
Impacted versions:
9.0e
Steps to reproduce:
"Real price" and "perpetual" inventory.  Create PO and receive.  Get vendor bill with different cost.
Current behavior:
Inventory valuation comes from the PO, not the vendor bill.
Expected behavior:
Inventory value and qty should come from vendor bill.
Video/Screenshot link (optional):
https://youtu.be/AHpYxhGD9Yo

**Comment by sle-odoo** [comment]
Hi,
I understand your concern. We plan to "fix" this in the upcoming versions. This is the expected behaviour for Odoo 8-11 though. Note that the price difference account is impacted when the vendor bill has a different price than the purchase order.

I'm closing this issue as it's not really a bug but how Odoo handles things at this level, and there's no chance we'll change this behaviour in stable versions.

Regards

**Comment by dcorio** [comment]
@sle-odoo do you know if this has been resolved on v12?
