### ISSUE TITLE
Inventory Module Return Product Bug

### ISSUE THREAD

**Issue by RealDev05** [odoo/odoo#164661]
Impacted versions: 17

Steps to reproduce: Return a delivered product repeatedly

Current behavior: Can return an infinite amount of products and that too multiple times

Expected behavior: Should only be able to return once and the product count shall not go above what ordered

**Comment by vava-odoo** [comment]
Hi @RealDev05 
I don't really get your point. It seems like it has been like that since a long while, i.e. not blocking you to return twice. 
There is a warning + a quantity set to 0 in the wizard, advising you not to do so. 
![image](https://github.com/odoo/odoo/assets/112173839/3af47c12-bc8f-4b07-8c7e-ea0ff5948757)
But you can indeed proceed if you know what you're doing.
Cheers,
