### ISSUE TITLE
[10.0] hr_holidays number of days

### ISSUE THREAD

**Issue by abdallamhafeez** [odoo/odoo#16466]
Impacted versions:
10.0

Steps to reproduce:
1. Add "Working Time" to employee that work from 7:30 to 15:00 so employee should work 7 and half hours.
2. Employee create leave request from 7:30 to 15:00

Current behavior:
Number of days is equal 0.94 

Expected behavior:
Number of days should to be  equal 1.00 and system should calculate when  employee should sign in and out and get deference between them.

**Comment by RomainLibert** [comment]
Hello @abdallamhafeez 

Your issue is linked to the fact that in version <= 11 we hardcoded that a day is 8 hours long (if you do the computation for your example you see that 7.5/8 = 0.935 which is rounded as 0.94)

As fixing this issue will at least alter the behaviour of the resource module, we cannot fix it in a stable release, but we already addressed this in v12 where we compute the number of hours according to the hours worked per day
