### ISSUE TITLE
[10.0] Can't set a reminder in calendar if inviting an external partner

### ISSUE THREAD

**Issue by edsersolis** [odoo/odoo#16472]
Impacted versions: v10 Enterprise / v10 Community

Steps to reproduce:
1. Create a meeting with an external partner.
2. Set a reminder.
3. Save.

Current behavior:
Odoo will give an error stating that only users in Employees/Employee have access to calendar.alarm.

Expected behavior:
Should be able to save the reminder and notify all the users. If notification to external partners is not allowed simply not send them a notification but still do it for internal users.

**Comment by Yenthe666** [comment]
Hi @edsersolis,

Can you try this again on the latest Odoo 10.0 runbot? I've just tested this without any issues? Example:
![image](https://cloud.githubusercontent.com/assets/6352350/25696438/7afa7738-30b7-11e7-9b09-4db519011cf5.png)

Regards,
Yenthe

**Comment by Yenthe666** [comment]
Hi @edsersolis,

There has been no response or feedback in almost a month so I'm closing this report because of that.
If you can give us more information on how to reproduce this (if it still is) then please post it here. I'll re-open the report if this is the case.
It doesn't seem to be reproducable anymore though.

Regards,
Yenthe
