### ISSUE TITLE
[8.0] Journal Items - manual posting with Accounts containing default Taxes gives wrong results

### ISSUE THREAD

**Issue by svenpetersen** [odoo/odoo#1655]
Hello,

I remember similar Issues with the first builds of 6.1 and 7.0 and now it's the same with 8.0 rc.

This is just example demo data and might make not much sense, but it shows that the counter part line (3) ignores the calculated tax amount of line (2):
![image](https://cloud.githubusercontent.com/assets/3729082/3842490/bebff212-1e37-11e4-8eec-e0142930428f.png)

To simulate it on runbot:
In the Account "701000  - Ventes en Belgique" add the VAT-OUT-21-S as a Default Tax.
In Journal Items select the "Sales Journal (EUR)" Journal and create:
One Line with: Name = test line 1, Account = 550002 Bank, Debit = 121,00 and hit Enter.
Odoo generates the second line, but the Credit amount is equal to the Debit amount despite the generated line contains the Tax. -> In this case the Credit Amount should be the Debit amount less the Tax Amount!
If you click on save, Odoo will generate the Tax Line with the correct Tax Amount.

with kind regards,
Sven

**Comment by beledouxdenis** [comment]
Hello Sven, 

In stable releases, such as 7.0 and 8.0, we only accept proposals solving a blocking issue, or solving a regression. New features are forbidden:
https://github.com/odoo/odoo/wiki/Contributing#what-does-stable-mean

I just tested in Odoo 8.0, and, indeed, the second line is equal to the debit amount. However, this behavior is the same in Odoo 7.0.

I do not believe this is expected to compute these amounts with the default taxes of the account. This is therefore considered as a feature request rather than solving a blocking bug. The amounts can be changed manually after all.

Such a pull request should therefore be done against master, the branch currently in development, accepting new features.

I hope you will understand.

Regards,

**Comment by svenpetersen** [comment]
Hello and thanks for processing the issue.

It's a long story. I wouldn't call it a new feature, as it worked fine in the old GTK Clients:

6.0 -> https://bugs.launchpad.net/openobject-addons/+bug/834512
6.1 -> https://bugs.launchpad.net/openerp-web/+bug/1020929

I understand that the accounting gets refactored in 9.0, but it should be considered, that some users use the journal items to post accounting records and expect to get the right counterpart entries.

with kind regards,
Sven
