### ISSUE TITLE
[10.0] product margin with Graph view

### ISSUE THREAD

**Issue by abdallamohamed1992** [odoo/odoo#16565]
Impacted versions:
10.0
Steps to reproduce:
1. Got to Accounting - Reports - Management - Product Margins
2. Click on Graph view

Current behavior:
Error appear that fields must be store=True

"AssertionError: Fields in 'groupby' must be regular database-persisted fields (no function or related fields), or function fields with store=True"

**Comment by Yenthe666** [comment]
Hi @abdallamohamed1992,

Thank you for your bug report.
I've just tested this and I can confirm that this is a bug:
![image](https://cloud.githubusercontent.com/assets/6352350/25651936/f0d8d210-2fe5-11e7-9777-c55f5f2296ec.png)
The bug is coming from https://github.com/odoo/odoo/blob/10.0/addons/product_margin/models/product_product.py#L48-L77
@nim-odoo perhaps this is one for you?

Regards,
Yenthe

**Comment by glitchov** [comment]
The bug is caused by the field product.product.turnover at line 53
https://github.com/odoo/odoo/blob/10.0/addons/product_margin/models/product_product.py#L53
because it appears in the groupby parameter and is not store=True.
The stack trace comes up directly in the super and the code doesn't go further. 
If turnover is removed  from the groupby parameter (but kept in the fields parameter) than it goes through the _compute_product_margin_fields_values and everything is ok.
Don't know how this grouby parameter is feeded because the graph view (product.margin.graph) references the 3 fields that appear in fields parameter.
