### ISSUE TITLE
[website] Concurrent Update error by rapid reloading of website pages with record writes (TransactionRollbackError)  

### ISSUE THREAD

**Issue by michaelkarrer81** [odoo/odoo#17037]
@odony Any website (qweb template) in odoo that triggers a write / update of an record will produce a concurrent update error (TransactionRollbackError) if the page is requested to frequently. E.g.: By double clicking or frequently reloading the page (hitting STRG+F5 or CMD+R)

This may be the *desired* behaviour for writes coming from different sessions but should not happen for subsequent calls of the same controller from the same session! 

# Impacted versions:
8.0 (maybe also 9.0 and 10.0)

# Steps to reproduce:
Rapidly reload any webpage that may write or update a record in the database (e.g.: cart update, blog visits, ...). 
Even a "double klick" of the user may lead to an TransactionRollbackError.

# Current behavior:
Traceback (most recent call last):
  File "/odoo/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
TransactionRollbackError: could not serialize access due to concurrent update

# Expected behavior:
Detect and handle subsequent calls of the same controller from the same session.
(This may be problematic for all resources but at least for web controllers and calls from the same session it should be no problem?)

At least for web controllers odoo should delay subsequent requests from the same session until the last has finished.

**Comment by odony** [comment]
Subsequent requests from the same session can be handled by different workers on different machines. As far as the system knows, these are independent requests, and because they touch the same record, they must conflict. This is all normal behavior.

The RPC API has an auto-retry mechanism to silently replay RPC calls in such cases, hiding most occurrences. We don't have the same mechanism for the web frontend because there are much fewer cases where this happens, in normal situations. Moreover, contrary to what happens with RPC, replaying an HTTP POST from a front-end page will always cause the action twice, like adding 2 products to the cart, or posting 2 identical tickets, etc. Not a desirable solution at all.

The best fix is probably to automatically disable the front-end submit buttons after the first click, to prevent accidental duplicate requests. Low-priority minor improvement, but you're welcome to work on it if you like ;-)

**Comment by michaelkarrer81** [comment]
@odony 

> The best fix is probably to automatically disable the front-end submit buttons after the first click, to prevent accidental duplicate requests.

:D -> Just what i did by java Script right now 

The only way i can think of, to handle such situations is to write an in progress flag to a persistent data store (e.g.: database or hard drive) on every request of a potentially problematic website controller so that this is thread independent. This may slow things down but may be preferable instead of just loosing data? 

Might this be the right direction?

**Comment by odony** [comment]
> Might this be the right direction?

Nope, we just discussed the better fix :P
Where do you see any chance of data loss in the presence of duplicate requests?

**Comment by pedrobaeza** [comment]
No further answer, and I can say that this has been worked during this time, disabling several buttons on website that could lead to double clickings. I close this by these reasons.
