### ISSUE TITLE
Multi companies Inventory Delivery - Receipt: 'Serial Number must be unique' Error

### ISSUE THREAD

**Issue by osovskaya** [odoo/odoo#17107]
Impacted versions: Odoo 10.0 Community 

Steps to reproduce: 
When manage multi companies in one Odoo instance and make delivery-receipt operations between two companies, serial number is considered as duplicate.

1. Enable Inventory setting 'Track lots or serial numbers'.
2. Enable setting 'Manage multiple companies'.
3. Create product with tracking by serial number.
4. Create in Inventory Delivery Order from Company 1 to Partner Locations, set serial number for product,  validate transfer, print Delivery Slip.
5. Change current company to Company 2.
6. Based on Delivery Slip from Company 1, create Receipts from Partner Location to Company 2, set serial number for product the same as in delivery slip.
7. Validate transfer.

Current behaviour:
Validation Error: The combination of serial number and product must be unique !

Expected behaviour:
Stock move is validated and product is available in stock in Company 2.

**Comment by jco-odoo** [comment]
Lots are not company dependent, so it is normal you can use the same lot over multiple companies.  It seems to me that your issue has more to do with the setting on the picking type 'Create Lots' (and not Use existing lots), which shows a text field instead of a lot number.  With the text field it tries to create lots all the time, while the many2one might solve your issue.  (and avoid to create the same lot twice)

**Comment by nagybal** [comment]
I do have the same on single company.

Where can I find this option?
