### ISSUE TITLE
[9.0] request.context in not propagated in orm functions calls

### ISSUE THREAD

**Issue by hugho-ad** [odoo/odoo#17117]
Impacted versions:
9.0

Steps to reproduce:

Inherit confirm order:

```python
    @http.route()
    def confirm_order(self, **post):
        order = request.website.sale_get_order(context=request.context)
        if not order:
            return request.redirect("/shop")
        redirection = self.checkout_redirection(order)
        if redirection:
            return redirection
        # HERE IS THE NEW KEY IN CONTEXT
        request.context['new_context_keyr'] = True
        return super(WebsiteSale, self).confirm_order(**post)
```

**confirm_order**
Then add some prints in order to debug in original function
After this line add a `print context`
https://github.com/odoo/odoo/blob/9.0/addons/website_sale/controllers/main.py#L668

**sale_get_order**
Then add one more in before this line
https://github.com/odoo/odoo/blob/9.0/addons/website_sale/models/sale_order.py#L309

Current behavior:

The result is that `sale_get_order` is not receiving the new key in context

![image](https://cloud.githubusercontent.com/assets/10233975/26262024/f751036e-3c98-11e7-881f-d50ef91b19ea.png)

Expected behavior:

Context be propagated properly 
Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
You are not using correctly the website framework, as request, due to its nature, can't propagate contexts the way you want. You should use post values or session ones for propagating any value.

Closing as no real issue.

**Disclaimer**: I'm not an Odoo employee, but a community member that voluntary contributes to triage / classify / solve issues. Take also into account that there's no obligation to answer nor solving things put in Odoo Community issue tracker. And thus, please consider this as a best effort initiative.
