### ISSUE TITLE
Longpolling not working on 10.0C, workers > 0

### ISSUE THREAD

**Issue by thedextazlab** [odoo/odoo#17129]
**Impacted versions: 10.0C**

**Steps to reproduce:** 

1. Using default configuration after cloning the Odoo repo, with Nginx properly configured as a reverse proxy using the recommended directives, change the ~/.odoorc configuration to proxy_mode = True and workers = 2 (or any number > 0).
2. Start a chat from the Discuss page or via the chat drop-down.

**Current behavior:**
Chats don't go through. Longpolling is not working (nothing listens on port 8072), hence error 502 from Nginx.

**Expected behavior:**
Gevent to automatically listen for longpolling on port 8072 and chats/messaging to work.

Server: Ubuntu 16.04 x86_64 on a 8GB Linode VPS

Screenshot:

![image](https://cloud.githubusercontent.com/assets/10960412/26278993/f38b0004-3db0-11e7-983e-da4b1e62dc21.png)

**Comment by thedextazlab** [comment]
I fixed it by creating another startup script, mod the original script and modifying odoo/service/server.py, odoo-bin and the odoo init (__init__.py) to check for whether odoo.evented is true or false and start the needed server for Longpolling (GeventServer). For reasons I yet can't understand, the PreforkServer does not spawn longpolling as required. With my workaround, I get the PreforkServer started then run the GeventServer by calling another startup script that sets odoo.evented to true. 

I am using supervisor to manage the startup scripts.

**Comment by sylnsr** [comment]
`start the needed server for Longpolling` -- could you elaborate on what this means. I have also seen the documentation at https://www.odoo.com/documentation/10.0/setup/deploy.html#odoo-as-a-wsgi-application say to "deploy an evented Odoo via odoo-gevent" however I see there is an `odoo` bin in my installlation, but not `odoo-gevent` bin.  Not sure how one is supposed to start up this other "event" server or what its for since my understanding is that the werkzeug server that runs Odoo will also handling longpolling requests

**Comment by gadLinux** [comment]
@thedextazlab can you post your scripts, please?

**Comment by pedrobaeza** [comment]
Use a dockerized solution like https://github.com/Tecnativa/docker-odoo-base and you will forget all of these problems as everything is already packed.

**Comment by gadLinux** [comment]
@pedrobaeza That's a nice solution. Thank you a lot for the link. But I think, at least in my case. I prefer to resolve the problem and see how can I get it working on my developing machine. 

For example I tried an integration today, and because this (I think) the integration broke, then it started automatically again, and then broke again. The problem is that it created a high load in the dev machine and DB but without any result. And no info in the log. 

When I moved to no workers it started to work again. For running tests in local and watch closely what's happening I prefer to run local, even if docker is a great solution either. 

Thank's for your high activity. :+1:

**Comment by celm1990** [comment]
Hello,
With workers > 0 on odoo config file:

**When install library event=1.1.2 odoo service start** 
![image](https://user-images.githubusercontent.com/7775116/41193960-e029fde6-6bd9-11e8-8c10-31fbe859d222.png)

**But when library event is not install odoo service start** 

![image](https://user-images.githubusercontent.com/7775116/41193988-58369e34-6bda-11e8-848c-1a8ab01aafdc.png)

event is a [odoo requeriment](https://github.com/odoo/odoo/blob/11.0/requirements.txt#L6), so, Which one should I use: [Event or Worker](https://github.com/odoo/odoo/blob/11.0/odoo/service/server.py#L964-L977)?
