### ISSUE TITLE
[8.0-10.0.] res.users record rule sees users from companies not included in Allowed Companies

### ISSUE THREAD

**Issue by LilyMaster** [odoo/odoo#17146]
The record rule 'user rule' for `res.users` with domain `[('company_ids','child_of',[user.company_id.id])]` allows to see users of the companies that are not in the list of a user's `Allowed Companies` list. This is because the domain is written backwards (I think). The current user can see all users, who have the current user's company in _their_ `Allowed Companies` list.

I am not sure if that is the intended behavior and would appreciate an answer on this, especially if this _is_ the intended behavior. If it is a bug, it is quite old.

**Impacted versions:**
8.0-10.0

**Current behavior:**
`[('company_ids','child_of',[user.company_id.id])]`
Current user can see users, who have the current user's company in their Allowed Companies list.

**Expected behavior:**
`[('company_id', 'child_of', user.company_ids.ids)]`
Current user can see users, whose company is in the current user's Allowed Companies list.

**Comment by odony** [comment]
Yes, it is the intended behavior for this default rule, as the [history of that source code line](https://github.com/odoo/odoo/commit/3f5fb80a76099f4aefe3e1b61aac4f014ce58f6d) reveals ;-)

Quoting the commit comment:
> Contrary to regular records, the company_id field on res_users does not represent a permanent
> relationship, this field is rather used by the user to select the 'company context' in which
> she would like to work.
> We don't want the list of assignable users on a task to change depending on which company
> these users are currently viewing data, for example.
> The real field that holds the list of companies a user belongs to is the 'company_ids' field.

In other words, let's say we have the following users, with their *allowed* companies ((cur) = current company):

User     | Company A |  Company B  | Company C |
-------- | ----------|-------------|-----------|
User U   |   X (cur) |      X      |           |
User X   |     X     |             |  X (cur)  |
User Y   |           |    X (cur)  |           |

Then, when User U has selected Company A as their **current** company, they should:
 - see User X who *can work* for Company A, regardless of user X's *current* company. i.e. see the content of the Company A column)
 - *not* see User Y who only works for Company B, because that makes no sense in the context of Company A (even is User U *could see* User Y after switching company)

Of course this is only the default behavior, administrators are free to customize this as necessary.

/cc @mart-e
