### ISSUE TITLE
Ir Config Parameters group_ids missing intentionally?

### ISSUE THREAD

**Issue by nhomar** [odoo/odoo#17198]
Impacted versions:

master: (since saas-14)

Steps to reproduce:

![image](https://cloud.githubusercontent.com/assets/338634/26423885/f724383e-4094-11e7-9c0b-9df77fa8b0a8.png)

Current behavior:

No posibility to hide for some group a config parameter.

Expected behavior:

Secure this variables.

Video/Screenshot link (optional):

**Comment by odony** [comment]
As of Odoo 11 ir.config.parameters (and many other similar internal tables) are only accessible by the system (administrators). This is a much better default, in order to harden the security.
When addons need to use a system parameter on behalf of a normal user, they can access it with a limited sudo() call. This ensure that all config parameters are safe *by default*. It was too common for security groups to be forgotten by mistake, exposing them easily via RPC to unprivileged users.
