### ISSUE TITLE
[9.0, 10.0] Loyalty program glitches when you remove price and apply it again

### ISSUE THREAD

**Issue by Yenthe666** [odoo/odoo#17335]
Impacted versions: 9.0, 10.0

Steps to reproduce: 
1. Create a customer, add a loyalty program and start a new session
2. Create an order for this customer and make sure the customer has x amount of points. For example:
![image](https://cloud.githubusercontent.com/assets/6352350/26632874/d8579112-4611-11e7-9812-4b15639b2622.png)
3. Pay the order, create a new order, choose the customer again and add a product:
![image](https://cloud.githubusercontent.com/assets/6352350/26632903/f0200f2c-4611-11e7-9f1f-dbf3e629c3b7.png)
4. Click on 'Rewards', you'll see a new line added:
![image](https://cloud.githubusercontent.com/assets/6352350/26632948/0b2ecd76-4612-11e7-800a-b64ce3fde439.png)
5. Click on 'Price' on the numpad and backspace untill the price shows 0.00:
![image](https://cloud.githubusercontent.com/assets/6352350/26632967/22f6b72a-4612-11e7-91c6-8b65f5c492d2.png)
6. Now fill in a new price (it can be the same too):
![image](https://cloud.githubusercontent.com/assets/6352350/26633005/3f758b06-4612-11e7-8675-f69dbfe0f157.png)
The points amount now changed from '- xx' to '-- xx', which is interpreted by the JavaScript as + (-- becomes +). This means the point result has now changed in total from 700 (which should be the result) to 2.100 points (700 you had, 700 new points for the second order and then +700 for the -- negotion).
On top of this the loyalty line its total has changed from - x € to + x €. So both logics are flawed.

Current behavior: The loyalty points are no longer substracted but are added.

Expected behavior: The loyalty points are substracted instead of added to the total.

**Comment by Yenthe666** [comment]
@jorenvo this one is for you. 😉

**Comment by jorenvo** [comment]
After looking a bit closer I'm not sure I fully understand the issue. The reason it's doing --700 is because you're essentially applying a 'positive' discount. If you were to make the price of that discount line negative again you would end up in the same state as in step 4.

**Comment by Yenthe666** [comment]
Hi @jorenvo,

Thanks for your feedback.
How you explain it is indeed the case and from a technical profile it still makes (kind of) sense. However, from an end user (or somebody functional) it doesn't. To an average person doing twice '-' shouldn't become '+'. Perhaps this is more of an usability issue but I can understand that this is quite confusing and unnatural to end users..

**Comment by jorenvo** [comment]
I suppose, although I'm sure people are using positive discounts for some weird use case. But I'm not sure what else to do. You manually specified the positive amount, it was not generated by the system. It's a bit clearer if you forget about the points and just look at the total of your order. In step 6 you end up with 1400 (700 + 700) instead of 0. I guess we could somehow make the POS remember the sign (+/-) on an orderline so that in step 5 you would have ended up with -0 instead. But I think there's other use cases where that would annoy people. I'm closing this cause I can't think of a way to improve this. If you have any idea then let me know and I will reopen.
