### ISSUE TITLE
 Security: Access to any file content on the system

### ISSUE THREAD

**Issue by cedk** [odoo/odoo#17390]
This is a security issue that was reported to Odoo security team three months ago (03/03/2017) but still not fixed.
Following the [Project Zero](https://en.wikipedia.org/wiki/Project_Zero_(Google)#Bug_finding_and_reporting) rules, here is the disclose of it. I hope it will push Odoo to fix it as soon as possible.

Here is the copy of my initial email:

> Hi,
>
> I have discovered that it is possible to retrieve the content of any
> file readable by the odoo user.
> For that, you need to modify from ir.actions.report.xml the char field
> report_rml or report_sxw and set as value a valid path (ex:
> /etc/passwd). Then the content of the file is available on the computed
> field report_rml_content or report_sxw_content.  Of course, it requires
> to have write access to ir.actions.report.xml which is by default only
> allowed to Administrator.
> 
> The exploit was tested on demo.odoo.com and the file '/etc/passwd' has
> been read.
> 
> But the issue is mainly in the tool file_open which does not restrict
> the access. So other modules could be affected if the tool is used with
> untrusted data.
> 
> 
> FYI, it is the same kind of issue as
> https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2016-1242
>
> Regards,

It appears that other places like https://git.io/vy4rL

**Comment by odony** [comment]
Locking the issue temporarily while we process the aggressive disclosure.

**Comment by odony** [comment]
See #17394.

For the record, this disclosure is considered unethical because the disclosure and its timeframe were never discussed with the security team (we never even heard back from our initial reply?).
Project Zero researchers *do* discuss timeframe with the vendors, and never go public without prior notice. Probably because they're trying to be helpful, not harmful.

In addition, this disclosure contains material copied from original and deeper research done by other security researchers. This was confidentially disclosed to the OP during the analysis of his (duplicate) report, and then disclosed with absolutely no permission. Brilliant.
