### ISSUE TITLE
hr_holiday OE : if no description, "false" is display in Gantt view

### ISSUE THREAD

**Issue by fmdl** [odoo/odoo#17451]
Impacted versions:
Master,10,9

Steps to reproduce:
Create an holiday without description.

Current behavior:
![image](https://user-images.githubusercontent.com/16716992/26848308-45b50df0-4b00-11e7-8834-bb4103054cf8.png)

Expected behavior:
The best result is to have the type of allocation in Gantt view, it is more easier to track holidays.
Exemple :
![image](https://user-images.githubusercontent.com/16716992/26848360-76c4c872-4b00-11e7-8a89-f6432e9803f5.png)

Solutions :
1. add required=True in name field
2. add a new field (description with oldname=name), add a compute like this to the name field, and update xml views: 
```
    @api.multi
    @api.depends('description', 'number_of_days_temp', 'holiday_status_id')
    def _compute_name(self):
        for holiday in self:
            name = _('%s %s : %s day(s)') % (holiday.holiday_status_id.name, holiday.number_of_days_temp)
            if holiday.description:
                name = '%s / %s' % (name, holiday.description)
            holiday.name = name
```
3. update Gantt view to choose any field for the display name

**Comment by mart-e** [comment]
Hello,

[There is](https://github.com/odoo/odoo/blob/20ed57f874176161a043dee834b25c7f0b3dc175/addons/hr_holidays/models/hr_holidays.py#L334) already a `name_get`, no need to create a new field. What you are probably looking for is the `display_name`.

@sle-odoo [we have hardcoded](https://github.com/odoo/enterprise/blob/7bcacaf47af1977bd2443dc595fab75ad58e3592/web_gantt/static/src/js/gantt.js#L60) (_enterprise_) the use of the `name` field in gantt. Shouldn't we use or fallback on the `display_name` field?

**Comment by sle-odoo** [comment]
@mart-e it's done since [saas-15](https://github.com/odoo/enterprise/commit/afd68a7d85eb6589fa4a5b3dd20248466158aabf)

**Comment by mart-e** [comment]
Thanks for the update. However, I am not sure the saas-15 is ideal too (for hr.holidays at least).

v10
![page-shot-2017-6-7 all leaves - odoo2](https://user-images.githubusercontent.com/564822/26870764-558e98ce-4b71-11e7-82fc-74e3df763886.png)

saas-15
![page-shot-2017-6-7 all leaves - odoo](https://user-images.githubusercontent.com/564822/26870757-507ca92a-4b71-11e7-82f3-79805f7ac1fb.png)

We no longer see the holiday content.
But maybe the issue is that the name_get is too long/not showing relevant info. Will check with @bst-odoo
