### ISSUE TITLE
Error when making payment for invoice using wire transfer

### ISSUE THREAD

**Issue by livewellvn** [odoo/odoo#17508]
Impacted versions: 10.0

Steps to reproduce:

Login to front-end website. From user menu, select My Account.

In Your Invoices and Payments, click on Pay Now link (next to invoice).

(Payment method is wire transfer)

Click on Pay Now

Current behavior:

There's error:

"Oops! There was a problem with your payment."

Expected behavior:

Payment should be done.

![odoo-payment-wire-transfer-error](https://user-images.githubusercontent.com/29296648/26960392-f6300cbe-4d00-11e7-83a5-1f2c7879bae4.jpg)

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Hi @livewellvn,

Thank you for your report.
Have you configured your payment methods? Can you reproduce this on an official runbot (runbot.odoo.com)?
CC @JKE-be 

Regards,
Yenthe

**Comment by livewellvn** [comment]
Hi @Yenthe666 

You can check on:
http://237927-10-0-dc8b47.runbot10.odoo.com/web/login
database: 237927-10-0-dc8b47-all
user: admin
pw: admin

I don't think Wire Transfer provider needs special configuration, just setting a few messages.  I published it. Either 'Test' or 'Production' environment you get the same error.

**Comment by JKE-be** [comment]
The message needs to be improved, but that makes sense that we will be not able to make payment with wire_transfer into this form ;)

**Comment by pedrobaeza** [comment]
@JKE-be have you improved already the output of wire-transfer? Indeed, you can't pay with it, as there's no real payment behind. Another option is to not allow to pay through that payment type in the website.

**Comment by XeJames** [comment]
Any update please?  Behavior a year later seems identical to original poster's description.  Customer chooses "pay by wire transfer" and is answered with "Oops there was a problem with your payment" - the information details about wire transfer never appear - just the error message.

However the wire transfer is noted in Odoo - Accounting/Configuration/Payment Transactions does list all attempts (and failures) to make a wire transfer - each Customer Invoice is suffixed with x1, x2, x3 as they try and try to make their payment.
![image](https://user-images.githubusercontent.com/29873462/42903858-1c7f9496-8aa1-11e8-9728-56f9d64b33d3.png)

If the client simply then manually transfers using their own banking interfact, their wire transfer appears in the Bank Reconcile and you can then manually enter their payment to the Invoice or Sales Order.
![image](https://user-images.githubusercontent.com/29873462/42903920-49ca7934-8aa1-11e8-8eea-105b767e7cf7.png)

My understanding that the expected behaviour is for the client to be offered information about HOW to transfer the funds and that this is based upon the "Electronic Transfer" checkbox being set in the banking information for that account.  

The current situation is very confusing to clients and does cause bad feelings.  Any response about the roadmap of this bug would be very welcome.
