### ISSUE TITLE
[v10] Issue with "Real cost", or wrong documentation

### ISSUE THREAD

**Issue by gustavovalverde** [odoo/odoo#17503]
**Impacted versions:**
10.0

**Steps to reproduce:**
1. Configure category "All" with **Real Cost** and **Perpetual** valuation.
2. Create a product "Computer" under  the "All" category
3. Go to the Product Template (price can be modified) and leave cost as 0.
4. Make a PO buying "Computer" at $10.
5. Validate the PO and validate the Picking.
6. Create the Vendor Bill at $10 and validate it

**Current behavior:**
The Cost in the Product template **won't update**. And it can also be manually modified without any record of it.

**Expected behavior:**
Real price should not allow product cost modification on the template, and the cost on the template should be update after an Incoming Picking validation and/or after a completing an MO, as this is the expected cost to be used for selling purposes. 

The only moment when this cost is updated is when you sell it, but I'm expecting this to be shown before selling it. 

**This issues are all related:**
https://github.com/odoo/odoo/issues/16721
https://github.com/odoo/odoo/issues/16441
https://github.com/odoo/odoo/issues/15618

Not so much, but also being affected by real price:
https://github.com/odoo/odoo/issues/10600
https://github.com/odoo/odoo/issues/14276

**Comment by gustavovalverde** [comment]
@nim-odoo @qdp-odoo @Yenthe666 

Am I losing something here?

**Comment by gustavovalverde** [comment]
Hi, just let me know if I'm not getting it right to close the issue, as from my POV this is not working correctly.

**Comment by invitu** [comment]
I link @fhe-odoo and @fpodoo answers in the mailing list : 
https://www.odoo.com/groups/community-59/community-28876213?mode=thread

**Comment by mohamedhagag** [comment]
@fhe-odoo 

The real price gets updated after the sale not after purchase.

I did try it many times last weeks with the same result. The process is to 
1- buy qty and 
2- sell all of it then 
3- buy another qty with higher price and 
4- try to sell from it 
The result is - you will get the old cost instead of the new cost although all old stock sold .

I tried on runbot also,

Product: http://296281-10-0-822a5e.runbot14.odoo.com/web#id=479&view_type=form&model=product.template&menu_id=424&action=280

and related sales and purchase.

Would anyone check and confirm ?

**Comment by sle-odoo** [comment]
@gustavovalverde I'm not sure i understand the problem here. The cost from the PO will be set on the unit_cost of the quant and, once transferring this quant to the customer, this unit_cost will be used to create the accounting entries. I think the only case where the cost on the template will be used is when you add items to your inventory via an inventory adjustment (so not linked to a document specifying an unit_cost). Also, this field is updated after each delivery (so if you sell the item at 10$, if you add items to your stock via an inventory adjustment, they will cost you 10$).
