### ISSUE TITLE
[8.0, 9.0, 10.0] Qweb Report Barcode Accepted Types

### ISSUE THREAD

**Issue by xubiuit** [odoo/odoo#17515]
Impacted versions: 8, 9, 10

Steps to reproduce:
You just need to go through: [EAN13](https://demo2.odoo.com/report/barcode?width=200&type=EAN13&value=text&height=200), meanwhile [QR](https://demo2.odoo.com/report/barcode?width=200&type=QR&value=text&height=200) is working fine

Current behavior:

> Accepted types: 'Codabar', 'Code11', 'Code128', 'EAN13', 'EAN8', 'Extended39',
        'Extended93', 'FIM', 'I2of5', 'MSI', 'POSTNET', 'QR', 'Standard39', 'Standard93',
        'UPCA', 'USPS_4State'

Check at: 
[Odoo 8](https://github.com/odoo/odoo/blob/8.0/addons/report/controllers/main.py#L82), [Odoo 9](https://github.com/odoo/odoo/blob/9.0/addons/report/controllers/main.py#L62), [Odoo 10](https://github.com/odoo/odoo/blob/10.0/addons/report/controllers/main.py#L62)

But when I tried, there are a few work, e.g: QR, Code128, but others never work

Expected behavior:
If Odoo does not support those types, please change your comments. Or fix that

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/5255048/26964458-c19808ce-4d1b-11e7-85b8-21ae28004c68.png)

**Comment by Yenthe666** [comment]
Hi @xubiuit,

Thanks for your report.
When I look at your screenshot it is doing exactly what it should do though. You're passing along some text as an `EAN13` barcode, while it is not mathematically correct.
Example with text:
![image](https://user-images.githubusercontent.com/6352350/33614863-c3f2f44a-d9d8-11e7-9486-228d574fe489.png)
Doing the same with a valid EAN13 (for example "0075678164125") it works fine (as it should):
![image](https://user-images.githubusercontent.com/6352350/33614924-fa40fee8-d9d8-11e7-9945-a8f34d2469f5.png)

When you pass along a barcode type that has to be a correct number you cannot expect it to work. Closing as it is invalid.

**Comment by liebana** [comment]
EAN13 type is not 100% accurate. It's printing an ITF barcode  [1]

![image](https://user-images.githubusercontent.com/7783296/45614348-89247380-ba69-11e8-9c6b-1221f88c3670.png)

instead of:

![image](https://user-images.githubusercontent.com/7783296/45614358-93df0880-ba69-11e8-80ad-65bc8041325b.png)

Although the scanning of the ITF code shows the EAN13 code number, in some industries (manufacturing or clothing, for example) it's not valid due to lenght and encoding issues. 

ITF should have it's own type and EAN13 should print the standard barcode.




[1] https://en.wikipedia.org/wiki/Interleaved_2_of_5
