### ISSUE TITLE
Unittests Failing in IDE environment

### ISSUE THREAD

**Issue by PieterPaulussen** [odoo/odoo#17518]
Impacted versions:
All

Current behavior:
The Odoo unittests can't be run from inside an IDE (Pycharm). There is a missing parameter for running the tests inside the IDE.  This provides a clearer interface for running tests than standard Odoo logging

Expected behaviour:
Odoo allows for running tests in an IDE environment

This is the traceback Error
![error](https://user-images.githubusercontent.com/17935026/26965359-ae40658a-4cf5-11e7-92f1-5aebea51ceba.jpeg)

**Comment by xmo-odoo** [comment]
Yes, Odoo tests have to run *within* Odoo at this point, not the other way around, sadly it is not currently possible to run tests "independently" from Odoo.

And because running tests by and large has to be interleaved with installing modules (as the basic "unit tests" of a module will not cope well with an extension adding required fields) that's unlikely to change any time soon unless somebody manages to square the circle.
