### ISSUE TITLE
Unknown Odoo V8 version number.

### ISSUE THREAD

**Issue by rolero** [odoo/odoo#17572]
Impacted versions: Odoo Version 8.0-98bd673

Steps to reproduce: 
Fresh Centos Os with Odoo Version 8.0-20161106 install
Trying to move to new server using database dump from Version 8.0-98bd673

Current behaviour:
We tried to find out which Odoo version to use but there is no version called  8.0-98bd673. So we guessed by comparing the information available in /website/info (I know this is terrible but the customer has no root access to the server). We compared all updates and dates. After testing it in our development system, we noticed too many database and view errors. Most of them we could correct but we have a huge issue with the presentation of sales numbers based on the warehouse module. Some difference we noticed:

- Warehouse settings: "Invoice products in a different unit of measure than the sales order" versus "Store products in a different unit of measure than the sales order".

- Products amounts suddenly have three decimals instead of two.

- Product sales amount incorrectly (product.template view)

- Sales order lines empty or giving and error: Documents missing.

etc. Also making a backup on the new system fails due to DB consistency issues. Conclusion wrong version. 

Expected behaviour:
I hope somebody can help me to find the right version to download that I can use on CentOs 7.

Video/Screenshot link (optional):

**Comment by JKE-be** [comment]
"there is no version called 8.0-98bd673"
This name means: version 8 with last commit 98bd673 (https://github.com/odoo/odoo/commit/98bd673)
So if you checkout this ref, you will be exactly with the same code that before the backup.

Anyway one backup of v8 version (!= 8.~saas-xxx) should be compatible for all v8 refs.

Since this tracker is for issue in Odoo Code, I invit you to follow this discussion on forum.odoo.com.

Best regards
