### ISSUE TITLE
Dashboard responsive

### ISSUE THREAD

**Issue by JanisJanis** [odoo/odoo#17606]
Impacted versions:
v10

Steps to reproduce:
1. for example CRM > My Pipeline
2. group by 2 fields (in example Stage > Country)
3. Graph view
4. Add to dashboard

Current behavior:
In dashboard it looks like
![image](https://user-images.githubusercontent.com/7612247/27125598-6c9395b0-50fd-11e7-921a-7441b3d5fa3e.png)

Expected behavior:
Would like in dashboard picture like this
![image](https://user-images.githubusercontent.com/7612247/27125650-a3110c80-50fd-11e7-9131-6128fa223130.png)

Video/Screenshot link (optional):

**Comment by JanisJanis** [comment]
Are there any news about this?

**Comment by Yenthe666** [comment]
Hi @JanisJanis,

Thank you for your report. This issue has been fixed in the meanwhile, as you can see here:
![image](https://user-images.githubusercontent.com/6352350/34934113-90ea50b8-f9d9-11e7-8583-97b079bee7a8.png)
Please update your Odoo source code to the latest version to fix this.

Regards,
Yenthe
