### ISSUE TITLE
[10.0] Odoo truncates the entered SMTP password when is longer than 64 chars

### ISSUE THREAD

**Issue by Naroh091** [odoo/odoo#17647]
**Impacted versions:** 

v10, at least

**Steps to reproduce:**

This is only happening when using 3rd party mail servers that provide a very loooong password, like SendGrid. The issue is the same as #15702, reported by @cgaffney099.

The steps are simple: just try to establish a test connection with the username and password given by SendGrid.

The password gets stored in the DB using a char field with max size 64, so it gets truncated.

**Current behavior:**

Odoo truncates the password entered in the configuration. The password stored in the db is 64 chars long at most when the original password is 69 chars long, therefore the software is unable to establish a successful connection. 

**Expected behavior:**

Odoo establishes a connection with the SMTP server using the password as entered.

**Comment by Yenthe666** [comment]
Hi @Naroh091,

Thank you for your report.
This has actually been fixed in the `master` Odoo version by me actually. (see https://github.com/odoo/odoo/pull/17269 and https://github.com/odoo/odoo/commit/c8d132f75119d809a1e729c31986002e64c7078d).
We can't change models and fields in a stable version so this is already handled.

Regards,
Yenthe
