### ISSUE TITLE
In multi company invoice issue base on pos session.

### ISSUE THREAD

**Issue by jar-odoo** [odoo/odoo#17666]
Impacted versions:
10.0
Steps to reproduce:
step 1: Go to settings -> General settings -> Manage multiple companies (enable)
step 2: create a new company (e.g: test) on companies menu
step 3: create a new user with test company.
step 4: login with test user.
step 5: create a new pos session related test company.
step 6: open pos session and add some product , add customer after payment and select "Invoice button" and after click on "validate" button.

See attached video to getting a better idea.

Current behavior:

Expected behavior:

Video/Screenshot link (optional):
[multi company pos traceback](https://youtu.be/JGmmUUwofTM)

**Comment by Yenthe666** [comment]
@jorenvo perhaps another one for you? (cc @mart-e)

**Comment by jar-odoo** [comment]
any updates ?

**Comment by Yenthe666** [comment]
Nothing yet - when jorenvo has time I'm sure he'll look at it. 😉

**Comment by pedrobaeza** [comment]
The main problem here is to use administrator user, which bypasses all the record rules and mixes things between several companies, so this is not a real issue.

Please redo steps with a regular user and you'll see that the problem is gone. If not, please reply back with a video done with other user.

I'm closing this meanwhile.

**Disclaimer**: I'm not an Odoo employee, but a community member that voluntary contributes to triage / classify / solve issues. Take also into account that there's no obligation to answer nor solving things put in Odoo Community issue tracker. And thus, please consider this as a best effort initiative.
