### ISSUE TITLE
[10e] Accounting Online Synchronization - Yodlee connection error 400

### ISSUE THREAD

**Issue by BzMB** [odoo/odoo#17795]
Impacted versions:
Odoo 10 enterprise

Steps to reproduce:
Accounting >> Bank >> Online Synchronization >> Add a new bank to the System

Current behaviour:
Insert the first 3 character of your bank
HSB 
(looking for the bank HSBC)

The system show the following error:
```
Yodlee is experiencing connection problems at the moment, please retry and be patient!

(Diagnostic: 400 for URL https://onlinesync.odoo.com/yodlee/api/2/providers?name=HSB)
```

Expected behaviour:
Insert the first 3 character of your bank
HSB 
(looking for the bank HSBC)

The system should return a list of possible matching bank against the criteria inserted by the user

Any Ideas?

![odoo_rms_account banking synchronization_issue](https://user-images.githubusercontent.com/20208755/27482853-fbe82a4a-581a-11e7-88e9-4bbf15414f1e.png)

**Comment by Yenthe666** [comment]
@csnauwaert I believe you've made this module. Could you give feedback?

**Comment by csnauwaert** [comment]
Well message is self explanatory. We are using a third party provider to fetch transactions and this error happens when a reply is not received in 30 seconds. This can happen when too many people uses the API at the same time for example. Usually retrying a few minutes or a bit later fixes the issue.

This issue does not tell if it happens all the time. So my guess is that this only happened at a given time when Yodlee's servers were overloaded. I'll close this, feel free to reopen if issue persist and you've tried at different moment of the day.

Best regards
