### ISSUE TITLE
Activity sequence in routing

### ISSUE THREAD

**Issue by ccandito** [odoo/odoo#17922]
Impacted versions:
9.0
Steps to reproduce:
create a routing with more than one activities
Current behavior:
scheduling in series
Expected behavior:
we need a feature to schedule activities in overlapping 
Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
@ccandito thank you for your report. Could you please add more information and examples of what you'd like please? We don't really have enough information at this point.

**Comment by ccandito** [comment]
Dear Yenthe,
just two examples for two business cases not managed:
1) a routing with three activities: the first one in sequence and the other two in parallel, so the second and the third one could start only if the first has been concluded, but they could start together at the same time or in different moment;
2) a production order for 100 pcs, the corresponding routing with 2 activity in sequenza, but the second could start just after the first 5 pcs have been processed by the first.
Regards
thanks in advance
claudio candito

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a feature request. There has been some work on planning part on latest versions and in enterprise modules, so I invite you to check them, for example on runbot, but this can't be covered in the specified version due to stability policy.

Closing this by the reason above.
