### ISSUE TITLE
[8.0] website: Cannot alter tables once created (add or remove colums/rows, etc)

### ISSUE THREAD

**Issue by pedrobaeza** [odoo/odoo#1793]
When I insert a table on a website page, I can define the number of columns/rows, but if I want afterwards to change this number, I can't do it but removing current table and adding a new one.

I can't also change border properties.

**Comment by Yenthe666** [comment]
Hi @pedrobaeza,

Thank you for your report.
I agree that this would be a neat improvement in the Odoo website builder (for V8) but since it is almost end of life it won't be added anymore.
This is however available in V10 now:
![image](https://user-images.githubusercontent.com/6352350/27579467-e897ed1c-5b27-11e7-9903-459778df4508.png)
I'm closing this issue as it is no longer a problem in the latest version and V8 is almost EOL.

Regards,
Yenthe
