### ISSUE TITLE
Overriding window action context key with button context not working

### ISSUE THREAD

**Issue by flyingL123** [odoo/odoo#17947]
I have a button defined in an Odoo sass14 view like this:

    <field name="x_stock_picking_type_id" invisible="1"/>
    <button type="action" name="449" string="Process Orders" class="btn btn-primary" context="{'search_default_picking_type_id': x_stock_picking_type_id, 'search_default_x_stock_picking_group_id': active_id}"/>

Window action 449 is in the database and is defined with the following context value:

    {'search_default_picking_type_id': [active_id], 'default_picking_type_id': active_id, 'contact_display': 'partner_address', 'search_default_available': 1,}

My hope was that by passing in the `search_default_picking_type_id` key on the button context, that it would override the context defined in the window action. The Odoo documentation says that button context is:

> merged into the view's context when performing the button's Odoo call

When I click the button however, the resulting view seems to still use the context defined on the window action. It's using `active_id` for the value of `search_default_picking_type_id` rather than `x_stock_picking_type_id`.

Is this intended, or a bug? Should a key on the button context override the same key in the window action context? The word "merged" in the documentation leads me to believe it should.

**Comment by odony** [comment]
Well, the problem with merging is that you need to a conflict-resolution strategy. In this particular case we believe that the server-side (dynamic Python code) is able to provide more dynamic and "final" values than the client-side, because it receives the whole client-side `context`, and can decide to preserve or override them in the returned `context`. This is not really obvious with static "window action", but more so with "server actions".
So the intended behavior if to give priority to the returned context.

You're right that we ought to improve the documentation in this particular aspect, though. If you want to submit a [PR to update it](https://github.com/odoo/odoo/wiki/Contributing#making-pull-requests), I'd be happy to review it :-D
