### ISSUE TITLE
[9.0][10.0] Invoices are using yesterday's rate when user inputs a new rate.

### ISSUE THREAD

**Issue by gustavovalverde** [odoo/odoo#18048]
### Impacted versions:
9.0, 10.0

### Steps to reproduce:
I've been experiencing that every validated invoice is using yesterday's rate instead of today's rate.

When creating a new rate 00:00:00 is not the default:
![image](https://user-images.githubusercontent.com/16890942/27509494-392358d8-58cc-11e7-830d-1c2d130cece7.png)
This is using runbot.

### Current behavior:
Currently, users have to input **today's rate with yesterday's date**. Apart from being a wrong approach, it also raises and Audit problem for companies; and we could save ourselves the explanation to the Auditor of why every single rate has the wrong date.

### Expected behavior:
When creating a new rate, 00:00:00 should be the default. 

The fix for current stable seems easy, just as @suniagajose exposed in https://github.com/odoo/odoo/issues/15071#issuecomment-272578976, changing the [following query to](https://github.com/odoo/odoo/blob/10.0/odoo/addons/base/res/res_currency.py#L42):

```sql
SELECT c.id, (SELECT r.rate FROM res_currency_rate r
WHERE r.currency_id = c.id AND r.name <= '2017-01-13 07:00:00'
AND (r.company_id IS NULL OR r.company_id = 1) 
ORDER BY r.company_id, r.name DESC          
LIMIT 1) AS rate 
FROM res_currency c  
WHERE c.id IN (3);
```

**Comment by bimajatiwijaya** [comment]
Hi any progress with this issue ? I can reproduce this issue.
Regards

**Comment by gustavovalverde** [comment]
@lap-odoo maybe you could have a look at this behavior

**Comment by lap-odoo** [comment]
@gustavovalverde Did you send a ticket about that issue ?

**Comment by gustavovalverde** [comment]
Just did. Ticket 778671

**Comment by csnauwaert** [comment]
Hello,

I've already replied to the ticket, however I'll also reply here:

Actually this has been fixed in version 11 where the correct solution is to use a date field instead of a datetime. As for the previous version (9 and 10) the default is already at 00:00:00, however all the dates server side are in UTC, when you view the rates on your browser, the date is displayed using your timezone, you actually see the previous day (I assume your timezone is UTC-4) but the date is actually the current day at 00:00:00, and if you change the value to manually set the datetime to 00:00:00, you'll change the server date to 4am.. (which is wrong) 
This is a well know problem and this is why we change the field in version 11. We however won't fix this in version 9 and 10

Best regards
