### ISSUE TITLE
[10] dont integrate with firefox dark theme

### ISSUE THREAD

**Issue by icf20** [odoo/odoo#18100]
Impacted versions:
10

Steps to reproduce:
1 open fiewfox
2 in firefox go to themes
3 activate compact theme
4 log in odoo

Current behavior:
![imagen](https://user-images.githubusercontent.com/17784575/27951964-f8443824-6306-11e7-92aa-df983e538ec8.png)

Expected behavior:
white text over dark fields

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Hi @icf20,

I don't really see the issue. You have chosen for a specific theme in Firefox, which has nothing to do with Odoo.
I agree that this is hard to read and not very clear but if I'm not mistaking this is all handled by the FireFox theme side?
If we would change these colours in Odoo (so it looks nice on this specific theme) it will probably render bad/ugly on another Firefox theme. Or am I missing something?

Regards,
Yenthe

**Comment by icf20** [comment]
i expect something like the following

light theme

![imagen](https://user-images.githubusercontent.com/17784575/27952999-8c3a1078-630a-11e7-934e-928307f7634f.png)

dark theme

![imagen](https://user-images.githubusercontent.com/17784575/27952908-475cfa1a-630a-11e7-8ead-ffb9dc008b0b.png)

**Comment by Yenthe666** [comment]
Hi @icf20,

I understand that you would like different colours depending on the theme in the browser.
This is not something that Odoo wants to implement though, as it would mean that we would need to check/change CSS depending on too many factors.
Closing as it is not really a bug and because this is not on the roadmap for Odoo. I'd suggest you to choose another theme or add your own CSS to Odoo to change this behaviour.

Regards,
Yenthe
