### ISSUE TITLE
sequence on financial report not working

### ISSUE THREAD

**Issue by sitimawaddah** [odoo/odoo#18155]
Impacted versions:
9c, 10c

Steps to reproduce:
Adjust sequence on financial report setting (menu: Accounting/Configuration/Financial Reports/Account Reports)
set sequence on:
Assets (View) = 100
Liability (View) = 50

Current behavior:
On Balance Sheet report, displayed report still
Assets then Liability

Expected behavior:
On Balance Sheet report, displayed report should be
Liability then Assets

I change to many value, until I set minus to Liability like this:
Assets (View) = 100
Liability (View) = -100

then its displayed correctly
Liability then Assets

I also do debug function _get_children_by_order
I dont understand why it just working if i put value minus on Liability

![image](https://user-images.githubusercontent.com/12973701/28063459-5c761c2a-665b-11e7-9654-1923d660312d.png)

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Hi @sitimawaddah,

Thanks for your bug report.
Negative values are not working in combination with sequences and this is by design. Recently a small change was made so it automatically suggests `1` as first number. If you manually set it to negative it won't work though.
Odoo doesn't consider this a bug and, well, you shouldn't ever have negative sequences anyways? 

Regards,
Yenthe
