### ISSUE TITLE
[10.0] Constrains function on default_code of product.template called multiple times with False value on subsequent calls

### ISSUE THREAD

**Issue by osluys** [odoo/odoo#18162]
Impacted versions:
10.0

Steps to reproduce:

1. Inherit 'product.template'
2. Define `@api.constrains('default_code')` function
3. Insert debugger statement in function
4. Create a new product
5. Set _Product Code_ to any value
6. Save product

Current behavior:

When the debugger initially breaks in the _constrains_ function, `default_code` will contain the value entered in step 5. What is suprising though, is that after continuing in the debugger, the debugger breaks at the same line again, but now `default_code` is `False`.

Expected behavior:

I didn't expect the _constrains_ function to be called multiple times, but even so, the fact that `default_code` has differing values across the calls (first with the user-entered value and subsequently with `False`) makes it more difficult to write an appropriate _constrains_ function. It should at least have the same value across the calls.

**Comment by pedrobaeza** [comment]
That's because you are defining the method on `product.template`, and `product.product` directly inherits these constraints, but they are 2 separate models (as the inheritance is by delegation), so it's expected that this is called for the product.template record and for the product.product record(s).

Just put the constraint in product.product if you don't want this multiple call.

Closing as no real issue.
