### ISSUE TITLE
No Analytic accounts in invoice lines when invoicing based on incoming shipments

### ISSUE THREAD

**Issue by jalzaga** [odoo/odoo#1820]
When a purchase order is invoiced based on incoming shipments, the analytic accounts you enter in the purchase order lines are not transfered to the invoice lines, they are blank.

**Comment by adrienpeiffer** [comment]
Hi,

I confirm this issue.

A little more explanation:
Here a scenario on runbot 8.0:

Steps to reproduice:
-------------------------
- Go on runbot 8.0
- Go on purchase menu and select request for quotation.
- Click on Create button
- Fill in all required fields
- Add a line with a stockable product and set an analytic account or distribution
- On Deliveries & Invoices page, select 'Based on incomming shipments' for invoicing control.
- Click on save 
- Confirm order and approve it
- Click on receive product on the new view
- Click on transfert and Click on Apply in the new popup
- Click on create invoice
- Click on Create on the new popup
- Click on the created invoice

Expected behavior
------------------------
- Invoice line with an analytic account or distribution

Current behavior
----------------------
- Invoice line has no analytic account or distribution

**Comment by adrienpeiffer** [comment]
OPW 627411

**Comment by adrienpeiffer** [comment]
Fix on #5127
