### ISSUE TITLE
[10.0] Email - >Templates -> Sale Order Notification Email is empty

### ISSUE THREAD

**Issue by collex100** [odoo/odoo#18234]
**Impacted versions:**
10

**Steps to reproduce:**
Make a sale (I tested from my account). I received an almost empty letter with an account. 
I went to Email -> Templates -> Sale Order Notification Email
and 
Email -> Templates -> Invoice Notification Email

**Current behavior:**
These templates are empty (except for the heder and footer):
![screenshot_7](https://user-images.githubusercontent.com/11208423/28207819-b866c54a-6893-11e7-8c9e-852e5031f2fd.png)
![screenshot_8](https://user-images.githubusercontent.com/11208423/28207823-bb1dd576-6893-11e7-81b5-d30015ee635f.png)

**What I receive by mail.**
![screenshot_12](https://user-images.githubusercontent.com/11208423/28211295-8a7a3c1e-68a4-11e7-85e5-2bb9fb40a385.png)

**Expected behavior:**
Your native order letters contain content:
![screenshot_9](https://user-images.githubusercontent.com/11208423/28207933-1fae43c2-6894-11e7-94da-752be3c70f69.png)

**So is it planned that these email templates would be empty?**

Video/Screenshot link (optional):
**What I receive by mail.**
![screenshot_12](https://user-images.githubusercontent.com/11208423/28211295-8a7a3c1e-68a4-11e7-85e5-2bb9fb40a385.png)

**Comment by Yenthe666** [comment]
Hi @collex100,

It looks like your email templates got destroyed by somebody/something along the line.
You might want to update your Odoo, delete the default e-mail templates and reload them to fix this.
This issue is no longer present in the latest Odoo 10. If you still face this problem then please try to reproduce it on an official runbot (runbot.odoo.com) and post back here.

Regards,
Yenthe

**Comment by collex100** [comment]
I found the problem. It was associated with a wrong translation in email templates because of which the sending template broke. Thank you!

**Comment by Yenthe666** [comment]
Awesome - you're welcome!
