### ISSUE TITLE
ODOO 8 Error and very long time query performance on creating/duplicating BOM (Bill Of Material) manufacturing

### ISSUE THREAD

**Issue by sapdenny** [odoo/odoo#18249]
Impacted versions:
odoo 8
Need long time to create/duplicate data under BOM section. 
Cant see or explain if this problem comming from odoo/code.
To make sure the problem, I run the query on non office hour so there is noone logging into system at the time.

Steps to reproduce:
Create/duplicate BOM

Current behavior:
Error 502 bad gateway after loading almost 30minutes

Expected behavior:
Should be done without any lag/error

Video/Screenshot link (optional):
the system running on IBM server 32cores with 64GB RAM and 2TB HD (RAID5)

biggest table
![biggest_table](https://user-images.githubusercontent.com/22925355/28243946-fbf61054-6a05-11e7-9a9a-86d9aa662028.JPG)

most read
![most_read_table](https://user-images.githubusercontent.com/22925355/28243948-0d568dc4-6a06-11e7-8450-a6063badf786.JPG)

most written
![most_written_table](https://user-images.githubusercontent.com/22925355/28243949-15995ae8-6a06-11e7-8c08-4d1e1e1cd6ef.JPG)

Best Regards,
Denny S

**Comment by Yenthe666** [comment]
@odony could you give some feedback here? With 32 cores and 64GB of RAM it looks almost impossible for me to take 30 hours.
Could you help a hand in here? 😉

**Comment by sapdenny** [comment]
lol @Yenthe666 :v , the query last spotted at least 30minutes and then its gone. System give me msg something like "bad gateway".
Any help would be apreciated.

Regards
Denny S

**Comment by odony** [comment]
@sapdenny could you show a short video of what you're doing in the UI when it happens, and what the database activity looks like on the server side, e.g. the real time output of `htop` and `pg_activity` while your operation is running? Creating/duplicating a BOM is a light operation that is not expected to last more than a few seconds, unless something else is blocking it.
You can use the shortcuts F1, F2 and F3 to switch between view modes in pg_activity and display ALL, WAITING and BLOCKING queries.

The statistics you show indicate that you might benefit from raising the memory allocated for caching. What are `effective_cache_size` and `shared_buffers` set to in your PG config? This is very unlikely to be the main problem, though.

Is your RAID5 array healthy?

**Comment by sapdenny** [comment]
hi @odony thanks for reply.
Yes I think video could explain more, lemme arrange time to capture it all maybe tonight. (i'll post it later)

Here are some information about how we tune our odoo/postgresql engine.
- workers = 54
- shared_buffers = 8GB
- effective_cache_size (not setting yet)
- listen_addresses = '*'
- max_connections = 500
- work_mem = 96MB
- maintenance_work_mem = 32MB

About our server i couldnt see the problem coming from hardware(harddrive) since there is no fault/error from smartcheck.
We build the machine at 2015.
![server_information](https://user-images.githubusercontent.com/22925355/28297351-a085c136-6b97-11e7-8405-32bab34a0f40.JPG)

Our odoo run for 2 years with rapidly increasing data. From everyday backup estimated data growth 30MB/day (.psql file). Everything good at the first year.

Regards

**Comment by sapdenny** [comment]
Hi @odony 
Ive done with 10mins video https://drive.google.com/open?id=0BykAWynctHacYzVZbGdOcXFLYXc](url)
Actually the query still running for more than 30mins
Hope you can see the problem there

Best Regards
Denny S

**Comment by Yenthe666** [comment]
Hi @sapdenny,

Your URL doesn't seem to work (neither with (url) and without (url) behind it).
![image](https://user-images.githubusercontent.com/6352350/28353502-5bd999b6-6c5c-11e7-9baf-af84c391e6b7.png)
Could you check again please?

Regards,
Yenthe

**Comment by sapdenny** [comment]
@Yenthe666 
Sorry my fault. So letme know if this one cannt open https://drive.google.com/open?id=0BykAWynctHacYzVZbGdOcXFLYXc

Regards
Denny S

**Comment by Yenthe666** [comment]
Yep this works - thanks! I'm sure Olivier will give feedback soon 😉

**Comment by sapdenny** [comment]
Hii all @Yenthe666 and @odony 
have you all found the problem here?

Regards

**Comment by gdgellatly** [comment]
@sapdenny I'm not with Odoo, just like to get involved in this kind of performance stuff. From your video I don't think postgres is your issue.  It's just doing what its told.

Likely candidates:

- Worker memory/CPU limit set to low causing workers to restart (test with workers=0 or just raising the hard limits)
- A functional field that is poorly configured that is getting updated, like say a product cost field which is recursive or computationally heavy.  I noticed in the queries there seemed a lot of custom columns and some property fields that were being updated/accessed related to products themselves, this is not standard I think.
- A combination of those 2 things.
- Some kind of undetected recursion in the BoM structure (or customizations).

**Comment by sapdenny** [comment]
@gdgellatly thanks for feedback.
Regarding to worker and CPU limit I need to found the right value and Im agree to explore about limit memory size.
About the recursive query and some custom columns, I have no idea what to do.
If there is any related refference link for me to learn. I would apreciate.

Regards

**Comment by odony** [comment]
@sapdenny Thanks for the video! It tells us a few things:
 - You're duplicating a small BOM (only 6 lines?), which should be very fast in a standard Odoo 8 setup
 - Your database has several hundred thousands products, BoM and BoM lines. Normally this is not relevant for a simple BoM duplication, but in your case the system appears to access *a lot* of those other records, for some unknown reason.
 - The duplication request seems to be wasting a lot of time (re)computing data on your products and BoMs, which could point at some custom code with computed fields, constraints or something like that
 - There's a good chance we can exclude any limit/sizing problem, it seems to be purely algorithmic. You won't be able to speed it up with hardware/limit tuning, you have to find what is being computed, and why.
 - And of course: it would be much simpler to troubleshoot this is we had remote access to the live system or a dump of the database ;-) But that would cause many other classes of problems I guess (not to mention the database dump size), so let's continue troubleshooting without this.

This brings us to the _next questions_:
 - What non-standard/custom modules and code are you running on this installation? Are those public ones? Can you perhaps share the code/links?
 - What is your Odoo configuration? Do you use `--workers` mode (hopefully you do, otherwise your hardware is wasted). This is not relevant for the BoM duplication, but it is relevant for the next step.

**Next step**: please run the same experiment you did in the video, but this time you will need to identify the process that is computing all that stuff, and send it multiple SIGQUIT (-3) signals to trace it.
Here is how to do it, if you're not sure:
 - after starting `htop`, press F6 and sort by CPU activity `PERCENT_CPU` (you can also run `htop -u odoo` to only view Odoo processes)
 - while the duplication is running (after 1 minute or so), look in htop to find the Odoo process that is consuming a lot of CPU (should be at the top). Write down its PID (first column). In your video it was process `1587`, the only one eating memory in the middle of many PG processes. 
- now open a different terminal, and run this command after connecting as the `root` or `odoo` user:
  `kill -3 <PID>`
  Here `<PID>` is the PID of the process you found in previous step. This will cause the process to logs a trace in the Odoo logfile.
- repeat the `kill -3 <PID>` command 10 times, waiting 2-3 seconds between each (so we 10 different traces in the log)
- Now copy the contents of the Odoo log file to pastebin.com and post the link here (make sure to include all the traces, they look like this:

        2017-07-25 17:40:48,307 6696 INFO 8 openerp.tools.misc: 
        # Thread: MainThread (id:140280256386816) (uid:n/a)
        File: "./openerp-server", line 5, in <module>
          openerp.cli.main()
            (... long list of frames follow ...)
        File: "/home/odo/repositories/odoo/openerp/tools/misc.py", line 1258, in dumpstacks
          for line in extract_stack(stack):

- if possible, record what you do in a video, so we can confirm that everything worked as expected. Just the first 1-2 minutes after clicking `Duplicate` is enough.

Thanks, and good luck!

**Comment by intero-chz** [comment]
Just a wild guess: with lots of products, attributes and so on getting the price extra of variants (maybe on browse) can be the hell https://github.com/odoo/odoo/blob/1e3e3b4bbe8f2152884af62c5119b0b19143be92/addons/product/product.py#L981

**Comment by Yenthe666** [comment]
Hi @sapdenny ,

Thank you for your bug report.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.
P.S: Also don't forget to answer/follow the detailed answer from (@)odony!

Regards,
Yenthe
