### ISSUE TITLE
Hr_holidays Department managers and other followers of the department are not notified and added as followers on new leave requests in their department

### ISSUE THREAD

**Issue by Burtonsnow82** [odoo/odoo#18296]
Impacted versions: Odoo 10

Sorry but I've the same .py file mentioned on commit 1879964, but the problem still remaining.
When employe insert new leave request, his manager don't receive any notification...please help me

**Comment by Yenthe666** [comment]
Hi @Burtonsnow82,

Not sure why you'd create a new report and reply on the old one to be honest.
Have you updated your Odoo source code to the version past the commit https://github.com/odoo/odoo/commit/1879964116b9ca6635f46ef640748198832bd6a6 ?

Regards,
Yenthe

**Comment by Burtonsnow82** [comment]
Hy Yenthe666

I have copy and paste the entire code on hr_holiday.py...Is it correct?

Tnks and sorry for my bad english

**Comment by Yenthe666** [comment]
Hi  @Burtonsnow82,

Well that is not really the best way. Usually you update your whole Odoo code base and not just copy/paste a .py file. Let us assume, for now, that this is fine though. Have you updated your module too?

**Comment by Burtonsnow82** [comment]
No...I've only paste the code in hr_holiday.py.
How I can update my module?

**Comment by Yenthe666** [comment]
Hi @Burtonsnow82,

It is clear that you lack some good knowledge / details on how Odoo works. I'd suggest you to have a look at some of the Odoo tutorials. Have a look at https://www.odoo.com/documentation/10.0/setup/deploy.html and https://www.odoo.com/nl_NL/forum/help-1/question/what-is-the-right-way-to-upgrade-odoo-server-from-github-e-g-from-odoo-v8-saas-5-to-master-57423 and https://www.google.be/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0ahUKEwjKtcTk75LVAhVSalAKHcXRD6AQFggnMAA&url=https%3A%2F%2Fwww.odoo.yenthevg.com%2Fupdate-odoo-environment-github%2F&usg=AFQjCNF-Es-fuQx0ByOXAVcSXPPRMRyFAg which are all related to your questions.
You can find all documentation at https://www.odoo.com/nl_NL/page/docs
Since you've never updated your source code it is logical that the bug is still there. It is in fact working in the latest Odoo's as far as I can see though.

Regards,
Yenthe
