### ISSUE TITLE
[10.0][Bug] Blog Rss Feed <updated> field bug

### ISSUE THREAD

**Issue by Fuchur777** [odoo/odoo#18477]
**Impacted versions:**
-Working with Odoo 10 CE

**Steps to reproduce:**
1. Post blog post 1 on date x
2. Post blog post 2 on date y
- Both posts now get date of y

**Current behavior:**
- All posts get date of last post

**Expected behavior:**
- Posts to keep their original date

**Feed that shows issue:**
https://ubports.com/blog/1/feed

**Comment by Yenthe666** [comment]
Hi @Fuchur777,

Thank you for your report.
I've just tested this on the latest Odoo 10 and it has been fixed in the meanwhile:
![image](https://user-images.githubusercontent.com/6352350/34407633-af92aede-ebbf-11e7-82be-7b2dc9ff363d.png)
Please update your Odoo to the latest source code to fix this.

Regards,
Yenthe
