### ISSUE TITLE
[10][BUG][OE] Quality: Impossible to validate a partial picking

### ISSUE THREAD

**Issue by fmdl** [odoo/odoo#18497]
Impacted versions:
V10, Master (and maybe Saas)

Steps to reproduce:
- Create a quality point with product A with the Picking P
- Create a product B without quality point
- Create a Picking P with product A and the product B
- Process only the product B
- Validate the picking
- When you click on "Create Back Order" or "No Back Order" you see this message : `You still need to do the quality checks!`

Current behavior:
Impossible to valide a partial picking

Expected behavior:
Possible to valide a partial picking

Solution update enterprise/quality/models/stock_picking.py:
```
@api.multi
def do_transfer(self):
    product_to_check = self.pack_operation_product_ids.filetered(lambda x: x.qty_done != 0).mapped('product_id')
    if self.mapped('check_ids').filtered(lambda x: x.quality_state == 'none' and x.product_id in product_to_check):
        raise UserError(_('You still need to do the quality checks!'))
     return super(StockPicking, self).do_transfer()
```

**Comment by matt454357** [comment]
This problem is bigger than the do_transfer method.  For example, it's also impossible to partially inspect the products.  Try these steps:

**Steps to reproduce:**
1. create products A and B **both with quality points**
1. create picking for products A and B
1. pick all of product A but not B (set done qty to full required amount on product A)
1. save the picking and click Quality Checks button

**Current behavior:**
User is prompted to inspect products A and B

**Expected behavior:**
User should only be prompted to inspect product A

https://www.youtube.com/watch?v=DHDuJWs8ZdM

**Comment by fmdl** [comment]
Other methode to update after the issue find by @matt454357 

```
    @api.multi
    def check_quality(self):
        self.ensure_one()
        product_to_check = self.pack_operation_product_ids.filtered(lambda x: x.qty_done != 0).mapped('product_id')
        checks = self.check_ids.filtered(lambda check: check.quality_state == 'none' and check.product_id in product_to_check)
        if checks:
            action = self.env.ref('quality.quality_check_action_small').read()[0]
            action['context'] = self.env.context
            action['res_id'] = checks.ids[0]
            return action
        return False
```

```
    @api.one
    def _compute_check_todo(self):
        # TDE: measure_success use ?
        product_to_check = self.pack_operation_product_ids.filtered(lambda x: x.qty_done != 0).mapped('product_id')
        if any(check.quality_state == 'none' and check.product_id in product_to_check for check in self.check_ids):
            self.check_todo = True
```

**Comment by Yenthe666** [comment]
@jco-odoo could you give feedback here and look at this? Multiple issues/points seem to be handled here.

**Comment by jco-odoo** [comment]
It is ok for me to improve it, because functionally, you can be blocked for no reason.  I would always show all the quality checks because it is possible you do this first before you give the quantity.  But for the validation of the picking, you should not be blocked if you are going to put the rest in backorder and the backorder should only have the quality checks related to its products.

**Comment by Yenthe666** [comment]
@fmdl I encourage you to make a PR in this case. 😉

**Comment by fmdl** [comment]
I will make a PR, the Odoo Team give me the acces to enterprise reposit today.

**Comment by fmdl** [comment]
I have made the PR.

But for me it is an issue because it is no sens to do the quality of check of product which are not in your hand.

**Comment by fmdl** [comment]
Fix here : https://github.com/odoo/enterprise/commit/6eb56ef10441c7662478dd8a0bb6ac5c98bb0ef0
