### ISSUE TITLE
Cannot install app store

### ISSUE THREAD

**Issue by bandanagyrl** [odoo/odoo#18505]
Impacted versions: Community Version

Steps to reproduce: It looks like according to documentation that you should simply click on app store and install directly from odoo but my window says 'start your journey' and opens in a new window. I download but can't seem to find how to install.

Current behavior:

Expected behavior:

Video/Screenshot link (optional):

I found old info stating that you should use the add ons folder and simply place inside and then update your app list. I have 3 add on folders for odoo and no idea which is correct. Copied to all 3 and hit update - nada. Same 35 preinstalled apps.

Help!

I am using Windows 2012r2 also if relevant

**Comment by Yenthe666** [comment]
Hi @bandanagyrl,

In the meantime the app store doesn't allow you to download apps from within your Odoo anymore.
This has been removed/disabled because of security reasons and to prevent unallowed remote access.
You should now add your custom modules inside the addons repository and update your Odoo to reload them.

Regards,
Yenthe
