### ISSUE TITLE
Wrong Source Location in Transfer wizard [V8]

### ISSUE THREAD

**Issue by 7Eleven1995** [odoo/odoo#18507]
Here is the scenario to reproduce the issue: 

1. I have a product (Product 1)  and the current stock is 10 quantities in WH/Stock.

2. I do internal transfer from WH/Stock to WH/Stock/Dep - 1 qty of Product 1

3. The current stock of Product 1 is 1 qty in WH/Stock/Dep and 9 qty in WH/Stock.

4. I created a sales order with 1 qty of Product 1 and view the delivery order

5. I clicked on the Check Availability button and upon checking on the reserved quants, the item that was reserved is from WH/Stock/Dep although the Source Location indicated is from WH/Stock.

6. When I clicked on Transfer button, the Source Location is WH/Stock/Dep instead of WH/Stock.

7. So I tried to change the source location to from WH/Stock/Dep to WH/Stock and clicked Apply button.

8. I checked the current stock of Product 1(Product From) but the view shows only the stock from WH/Stock.

9. When I check in Current Inventory Value, it shows that in WH/Stock (8 qty) and in WH/Stock/Dep (1 qty) which is right since I changed the source location in the Transfer wizard.

The two views are showing different information. I tried this on a default database without any custom modules installed. Will someone explain why this is the behavior of Odoo? Is this a bug?

**Comment by odony** [comment]
It's the correct behavior as of v8:
 - Stock moves handle the stock flows from Warehouse to Warehouse, with push and pull rules, but not the exact locations
 - A new concept, "stock pack operation" is used to indicate the actual location from which the goods should be picked, as well as to manage serial numbers and packs
 - "Quants" now represent sets of identical goods moving from location to location, and also provide the traceability features.

For more information please refer to the the documentation: 
 - https://www.odoo.com/documentation/user/9.0/inventory.html
 - https://www.odoo.com/slides/slide/introduction-to-odoo-warehouse-management-44

**Comment by 7Eleven1995** [comment]
@odony Will you please explain why the two views shows different information because when I checked the Configuration > Locations > WH/Stock/Dep > Current Stock (same with Product Form), there's no available products which is different from Current Inventory Valuation which is correct. WH/Stock/Dep should have 1 qty of Product 1.

**Comment by odony** [comment]
The data is consistent, you're just looking at it at different levels of granularity. The system does not refer to sub-locations such as "WH/Stock/Dep" in the history of stock moves, unless you force it to by making explicit internal transfers. When you process a sales order, the system reserves the goods in their actual sub-location (as shown in the "Operations" tab of the DO), but records the moves at the "main location" level.

In your example, you explicitly moved goods into the sub-location, and later processed a SO, so it looked odd when you only look at the "stock move" entries, because one product seemed to have arrived into "WH/Stock/Dep" and then departed from "WH/Stock". But this does not matter ultimately, the balance is correct at the level of "WH/Stock", and at quants level.

In fact you can see this clearly in the places you mention:
 - The "Product Form > On Hand" view gives you an overview of the Stock Quants by location (same info indeed via Configuration > Locations > WH/Stock/Dep > Current Stock)
 - The "Current Inventory Valuation" view gives you a reconstructed virtual history based on Quants and their moves, whose sums of quantities by product will match the one of "Product Form > On Hand". If you drill down inside sub-locations the granularity will match the one of the stock moves, so the sums may not match what you expect (cf above).

You can examine the actual data for Stock Moves and Quants in the "Warehouse > Traceability" menu if you want to follow exactly what the system does (watch our for the filter on Internal locations if you're interested in already delivered quants).
On a specific Quant you can also use the "Quants history" button to track its past moves. Here is a what you might get with your example:
![moves](https://user-images.githubusercontent.com/2039870/28790230-87c25d12-7628-11e7-9b80-0386c2732b87.png)
The balance is correct even if the source of each move is not always recorded at the same level of granularity

**Comment by 7Eleven1995** [comment]
@odony Hi Sir, thank you for your explanation. I now understand the difference between the Current Inventory Valuation and Current Stock.

Please correct me if I'm wrong since I'm still a bit confused and this is for clarification. Based on my understanding,  the default source location (reserved quants in the delivery order) is because of FIFO method (default). I tried to reproduce the issue again and provide screenshots.
Source: https://www.odoo.com/documentation/user/9.0/inventory/routes/strategies/removal.html

In my example, I have 10 quantities of the product as the beginning inventory and I've created the WH/Stock/Dep as a child location of WH/Stock. When I transferred one quantity of the product from WH/Stock to WH/Stock/Dep, the item moved by the system from WH/Stock is the old(first) record of the product (the system used FIFO method). Am I right?

**Warehouse > Traceability > Quants**
![image](https://user-images.githubusercontent.com/30518646/28851118-2b9cf656-7753-11e7-83d2-51e2d3069d8f.png)

I processed a sales order, checked availability of the product and  the default source location in the delivery order is WH/Stock/Dep because the old(first) record of the product is located in WH/Stock/Dep location. (based on internal transfer). The system used FIFO.

**Delivery Order**
![image](https://user-images.githubusercontent.com/30518646/28851191-7e647e18-7753-11e7-9bbf-eae98e55dee6.png)

**Reserved Quants**
![image](https://user-images.githubusercontent.com/30518646/28851215-b4521e36-7753-11e7-849c-4adf9295d9c2.png)

**Warehouse > Traceability > Quants > WH/Stock/Dep**
![image](https://user-images.githubusercontent.com/30518646/28851280-23f3553e-7754-11e7-9f1a-110efd315a26.png)

In this form, I checked the **Quant History** and got the same information you've shown in your explanation.

In the transfer wizard, I changed the source location from the default source WH/Stock/Dep to WH/Stock. 
![image](https://user-images.githubusercontent.com/30518646/28851370-91801e98-7754-11e7-8e49-8b0a5412d2dc.png)
![image](https://user-images.githubusercontent.com/30518646/28851377-9acf55c2-7754-11e7-9e6c-ba2bfb2c0189.png)

I checked the Quants menu and WH/Stock/Dep is not there.
**Warehouse > Traceability > Quants**
![image](https://user-images.githubusercontent.com/30518646/28851447-126d9f12-7755-11e7-9573-0449a8ff3cb2.png)

I have two guesses about it. 
(1)  Since the reserved quant is located at the WH/Stock/Dep, regardless of the indicated source location in the Transfer wizard, the system moved the reserved quant to Customers or though I changed the source location, since the old(first) record is at the WH/Stock/Dep and the system used FIFO as the default removal strategy, the system still moved the reserved quant (located at WH/Stock/Dep) to Customers

(2) It's almost the same idea with no.1 because of FIFO method. Since the reserved quant is located at the WH/Stock/Dep, the system moved the product from WH/Stock/Dep to  WH/Stock (since I changed the source location in Transfer wizard) and moved to Customers. I'm not sure with this idea because there is no document to support the internal transfer from WH/Stock/Dep to WH/Stock.

I don't know which one is correct, makes sense or both are wrong. 

PS: Sorry Sir if I'm still a bit confused from your last response. I appreciate your effort for answering my issue.
