### ISSUE TITLE
Hugely degraded performance for the translation subquery injection in _generate_translated_field

### ISSUE THREAD

**Issue by taifu** [odoo/odoo#18679]
The injection of the subquery in _generate_translated_field causes a performance degradation that is unacceptable. A flag environment variabile to skip the injection is necessary (https://github.com/odoo/odoo/blob/10.0/odoo/models.py#L4091)

Impacted versions: 10.0

Steps to reproduce: use an intensive query on stock_quant

Current behavior: hugely degraded performance (from 1 seconds to 90)

Expected behavior: same performance

Video/Screenshot link (optional): https://github.com/odoo/odoo/blob/10.0/odoo/models.py#L4091

**Comment by Yenthe666** [comment]
@odony another performance report. Could you comment please?

**Comment by taifu** [comment]
A workaround we found is to use with_context({"lang": ""}) in our queries. But I'd prefer an explicit flag variable to prevent any subquery injection at all

**Comment by taifu** [comment]
Moreover you can't inject it in the code base

**Comment by rousseldenis** [comment]
@taifu @Yenthe666 @odony Same here. Impact in two projects. Investigating

**Comment by Yenthe666** [comment]
@wardm95 and @vincentadriaensen might be somewhat related to our issue too? 😕 
@mart-e adding you in the chain too.

**Comment by taifu** [comment]
This is a huge, huge problem if you have a lot of data translation (we have 500.000 translations). The number of subqueries injected is abominable

**Comment by rousseldenis** [comment]
After investigation, we reproduced the issue within a script :

1/ Install a database with stock module

2/ Run the following code through shell command:

```python
# -*- coding: utf-8 -*-
import logging

_logger = logging.getLogger(__name__)
self = self  # noqa

# Install a language

wizard = self.env['base.language.install'].create({
        'lang': 'fr_BE'
    })
wizard.lang_install()


# Product creation
nb_product = 5000

i = 0

while i < nb_product:
    prod = self.env['product.template'].with_context(
        tracking_disable=True, lang='fr_BE').create({
            'name': 'product_%s' % i,
        })
    i += 1
    if i % 1000 == 0:
        self.env.cr.commit()
        _logger.info("%s Products Created" % i)

# Add a lot of fake translations
cpt = 200000
values = []
cr = self.env.cr
while cpt:
    cpt -= 1
    values.append(
        cr.mogrify(
            "(%s, %s, %s, %s)", (
                'fr_BE',
                'product.template,name',
                'translated',
                '%s' % cpt)
        )
    )
_logger.info('Create %d fake translations' % len(values))
self.env.cr.execute(
    """
    INSERT INTO ir_translation (lang, name, state, value) VALUES
    """ + ','.join(values))
_logger.info('%d fake translations created' % len(values))

# Update stock
i = 0
for product in self.env['product.product'].search([]):
    self.env['stock.quant'].sudo().create({
        'product_id': product.id,
        'location_id': self.env.ref('stock.stock_location_stock').id,
        'qty': 1.0
        })
    i += 1
    if i % 1000 == 0:
        self.env.cr.commit()
        _logger.info("%s Quants Created" % i)

```

3/ Run this python code:

```python

# -*- coding: utf-8 -*-
import logging
import time

_logger = logging.getLogger(__name__)
self = self  # noqa

# Read
_logger.info('BEFORE NORMAL READ')
start_time = time.time()
self.env['stock.quant'].with_context(lang='fr_BE').read_group([
    ('location_id',
     'child_of',
     self.env.ref('stock.stock_location_stock').id)],
     ['product_id', 'qty'],
     ['product_id'],
     limit=80)

elapsed_time = time.time() - start_time

_logger.info('AFTER NORMAL READ -- Elapsed time: %s', elapsed_time)

start_time = time.time()
_logger.info('BEFORE LANG READ')

self.env['stock.quant'].with_context(lang='').read_group([
    ('location_id',
     'child_of',
     self.env.ref('stock.stock_location_stock').id)],
     ['product_id', 'qty'],
     ['product_id'],
     limit=80)

elapsed_time = time.time() - start_time

_logger.info('AFTER LANG READ -- Elapsed time: %s', elapsed_time)

```

In the second script, I call the same kind of read group than those in stock computation.

As you can see, if we don't disable lang in the context, the query is 6x time slower (in this case and degrading with more translations).

```shell
2017-08-24 13:01:54,012 20557 INFO ? odoo: database: default@default:default
2017-08-24 13:01:54,018 20557 INFO ? odoo.service.server: Initiating shutdown
2017-08-24 13:01:54,018 20557 INFO ? odoo.service.server: Hit CTRL-C again or send a second signal to force the shutdown.
2017-08-24 13:01:54,026 20557 INFO odoo-translation-test odoo.modules.loading: loading 1 modules...
2017-08-24 13:01:54,107 20557 INFO odoo-translation-test odoo.modules.loading: 1 modules loaded in 0.08s, 0 queries
2017-08-24 13:01:54,126 20557 INFO odoo-translation-test odoo.modules.loading: loading 24 modules...
2017-08-24 13:01:54,138 20557 INFO ? odoo.addons.bus.models.bus: Bus.loop listen imbus on db postgres
2017-08-24 13:01:54,224 20557 INFO odoo-translation-test odoo.addons.report.models.report: Will use the Wkhtmltopdf binary at /usr/local/bin/wkhtmltopdf
2017-08-24 13:01:54,286 20557 INFO odoo-translation-test odoo.modules.loading: 24 modules loaded in 0.16s, 0 queries
2017-08-24 13:01:54,542 20557 INFO odoo-translation-test odoo.modules.loading: Modules loaded.
2017-08-24 13:01:54,569 20557 INFO odoo-translation-test __builtin__: BEFORE NORMAL READ
2017-08-24 13:01:56,853 20557 INFO odoo-translation-test __builtin__: AFTER NORMAL READ -- Elapsed time: 2.28369307518
2017-08-24 13:01:56,853 20557 INFO odoo-translation-test __builtin__: BEFORE LANG READ
2017-08-24 13:01:57,069 20557 INFO odoo-translation-test __builtin__: AFTER LANG READ -- Elapsed time: 0.21538901329

```

This is the case for one query, but in stock computation there are more than one call to the read_group...

@rco-odoo @xmo-odoo @KangOl

**Comment by odony** [comment]
There was a bugfix (see 6a366b216b3d119cd5546c877a2f77b5342cb452) behind this specific subquery. Having a flag to deactivate the fix would be incorrect, and would soon backfire.
Having a flag that goes back to using postprocessing for translations instead of JOINs would be a step back, with its own performance problems too.

But perhaps the upfront cost of the subquery can be reduced on the PostgreSQL side.
I would suggest to try a few things:
- Check your `work_mem` setting in PG. If using the default setting (1MB), large sorts are spilling to disk, thus slow, even more so if you have non-SSD storage. Make it 128MB or better if you can afford it. With large numbers of translations there's a good chance you'll need 64MB of `work_mem` at least to avoid disk sorts.
- Then consider creating this index, to help with the initial subquery sort:

        CREATE INDEX ON ir_translation (name, lang, res_id, id DESC) WHERE value != '';

  Here are [the timings I get](https://gist.github.com/odony/71f8b3b2e2f634ff534032128e738785) on a vanilla 10.0 (rev. 7ec4f2d), with and without this index.
- If none of the above helps, try running the slow queries through EXPLAIN ANALYZE and post the results here, like I did, to see if anything else can be done. You can find the slow queries easily in your PG logs with `log_min_duration_statement = 1000`.

**Comment by taifu** [comment]
We already implemented all of your (good) advices. Unfortunately this doesn't help. With this image, adding a row to an order increased from subsecond delay to unacceptable 5 seconds. I try to implement a monkey patch that leaves the subquery injection only for ui_* tables and this helps. Which are the problem you fear will backfired us? Thanks a lot @Odony

**Comment by taifu** [comment]
We logged every query and there are tenths of them that increased from 20 milliseconds to 200. This was the real problem. Using English as the interface language, solved the delay problem so it's surely this fix the culprit @Odony

**Comment by taifu** [comment]
Looking 6a366b216b3d119cd5546c877a2f77b5342cb452
I see it's only a workaround to prevent problem with double translation for the same term and language. I find this really strange: such a degrading fix only to prevent a wrong situation. A unique key would be enough. Or a task that send an alarm for double translations. But this fix is a nightmare :-(

**Comment by odony** [comment]
> Which are the problem you fear will backfired us?

Well, the problems that were fixed by the patch: incorrect numbers of results in SELECT queries in the presence of duplicate translations. You'll need to protect against that in a some way.
Having a unique constraint might work for you, but you'll need to care for adding it, and handling the cases that will possibly be broken by the constraint. This is not something we can do [in a stable version](https://github.com/odoo/odoo/wiki/Contributing#what-does-stable-mean), because as surprising as it is, it will affect more users negatively than 6a366b216b3d119cd5546c877a2f77b5342cb452

For the record, this patch is more than 1.5y old, and we haven't heard of many customers that were strongly impacted by it, so something else might be at play in your case.

By the way this patch should only impact queries that do read a translatable field. If you see many affected queries, it might be because of prefetching. You could try turning prefetching off selectively on certain fields (e.g. location and product name), like we did for [ir_attachment.index_content](https://github.com/odoo/odoo/blob/7ec4f2d6f5e5974f9e16b60fde305477668a39d3/odoo/addons/base/ir/ir_attachment.py#L289). Or you could try to prevent prefetching globally for all translatable fields (e.g. [here](https://github.com/odoo/odoo/blob/7ec4f2d6f5e5974f9e16b60fde305477668a39d3/odoo/fields.py#L467-L469))

**Comment by odony** [comment]
@rco-odoo @antonylesuisse @beledouxdenis Given the focus on performance in Odoo 11, it might be time to replace 6a366b216b3d119cd5546c877a2f77b5342cb452 in master by something smarter and faster, like a unique constraint.

**Comment by taifu** [comment]
@Odony thanks a lot. Reading again my messages,  I find them a little bit too rude. It was not my intent. Thanks again.

**Comment by rousseldenis** [comment]
@odony 

> For the record, this patch is more than 1.5y old, and we haven't heard of many customers that were strongly impacted by it, so something else might be at play in your case.

Maybe it's the delay to have installed instances and populated DB with a sufficent amount of translations...

I regret the index (or another way was not found before launching v10 and when the https://github.com/odoo/odoo/commit/6a366b216b3d119cd5546c877a2f77b5342cb452 was developped.


So, after having created index, performances are better. A gap lasts with lang declared and not (0,5 seconds and 0,1) with the script here above.

**Comment by taifu** [comment]
That's a 500% performance impact. From 0.1 to 0.5 second is negligible. From 2 seconds to 10 is devastating (at least looking at our customers reactions)

**Comment by lmignon** [comment]
@odony We already have fine tuned our database (pg 9.6)
```
shared_buffers = 2GB
effective_cache_size = 6GB
work_mem = 41943kB
maintenance_work_mem = 512MB
min_wal_size = 1GB
max_wal_size = 2GB
checkpoint_completion_target = 0.7
wal_buffers = 16MB
default_statistics_target = 100
```
Even if the patch is more than 1.5y old, we are seriously impacted on 2 large projects with a lot of records and translations into the database (multilingual context). 
The tree view and the kanban view of products are unusable (minimum 8 seconds to display the first 80 items). Indeed as mentioned by my colleague @rousseldenis https://github.com/odoo/odoo/commit/6a366b216b3d119cd5546c877a2f77b5342cb452 seriously impacts the calls to `read_group` done into the method `_compute_quantities_dict` in the addon `stock` https://github.com/odoo/odoo/blob/10.0/addons/stock/models/product.py#L146  If you debug for ex the first call to `read_group` on `stock.move` you 'll see it do read a translatable field.... (the product name). The code provided in https://github.com/odoo/odoo/issues/18679#issuecomment-324632965 highlight this problem and the read_group done in this code is comprable to those done in `_compute_quantities_dict`.
We must find a way to avoid the impact of https://github.com/odoo/odoo/commit/6a366b216b3d119cd5546c877a2f77b5342cb452 in the context of the  `_compute_quantities_dict`  method. 
As experiment we have modified the lines https://github.com/odoo/odoo/blob/10.0/addons/stock/models/product.py#L142 and https://github.com/odoo/odoo/blob/10.0/addons/stock/models/product.py#L143 as follow:
```python
Move = self.env['stock.move'].with_context(lang='')
Quant = self.env['stock.quant'].with_context(lang='')
```
This simple change brings a performance boost in the display of the product tree/kanban view but not only. All the functionalities based on the product quantities are a lot faster. (reordering rules, ....).
IMO this change could be safely introduced in Odoo 10.0 to minimize the impact of https://github.com/odoo/odoo/commit/6a366b216b3d119cd5546c877a2f77b5342cb452 at least in the context of the quantity calculation.

For V11 it would be nice to be able to use `read_group` with an option to disable the translation and the calls to `name_get`.

**Comment by rousseldenis** [comment]
@taifu Agree.

After further tests, no significant changes on interface.

Waiting for a real solution for this.

**Comment by taifu** [comment]
@rousseldenis You could add a constraint to prevent double translation and monkey patch the method _generate_translated_field reverting it at the previous version. I already did it

**Comment by rousseldenis** [comment]
@taifu That's a workaround. I would prefer having a more durable and global solution

**Comment by gdgellatly** [comment]
I've ummed and ahhed about whether to comment on this for a couple of days as I don't want to hijack so sorry in advance but if we are looking at it I was wondering why we use ir_translation table at all?

Translation performance is a major production issue, not just for this report.  There are lots of modules out there to disable various translatable fields for either performance or usability reasons, and I know that I avoid installing any languages if I can possibly avoid it (and with 10 we no longer need UK English).

To me, for translatable fields, it seems a fields.Serialized (probably no good as I think it uses a lot of python) or one of the postgres jsonb fields on the model itself might be a good future candidate.  

Obviously I know nowhere near as much as the people on this thread, but with such an index wouldn't it become something like 'SELECT * FROM product WHERE name='x' or trans @> '{'FR_fr': 'x'}'', avoiding all subqueries, neatly indexed and real fast.  idk, I been thinking on this ever since jsonb type was released, but not as knowledgeable as I'd like esp around the ORM and psycopg side.

Sorry for the hijack, I know it doesn't solve v10 issues.

**Comment by taifu** [comment]
@rousseldenis I agree. The problem is that our customers don't 😁

**Comment by taifu** [comment]
@gdgellatly wow! Great idea. I think that ir_translation has its "raison d'etre" for UI data, but for customer's data this is great!

**Comment by taifu** [comment]
@gdgellatly wow! Great idea. I think that ir_translation has its "raison d'etre" for UI data, but for customer's data this is great!

**Comment by taifu** [comment]
@gdgellatly wow! Great idea. I think that ir_translation has its "raison d'etre" for UI data, but for customer's data this is great!

**Comment by taifu** [comment]
Damn cellphone! I didn't want to close it!!

**Comment by gdgellatly** [comment]
@taifu thx.  There is one other opportunity for this datatype as well that I see and that is certain ir.property fields (the non relational ones mostly) which also suffer performance issues.

e.g. 'SELECT name, company_cost_price -> '9' FROM product WHERE ...;' where 9 is the company_id of the company.

**Comment by taifu** [comment]
Yup! Also ir.property fields would benefit a lot. Hope Odoo is listening here 😉

**Comment by rousseldenis** [comment]
@odony @rco-odoo  Any news on this ?

**Comment by Cedric-Pigeon** [comment]
@odony Hi, I also suffer of this problem. I have some performance issues on the whole application. For example, on sale order confirmation. If I work in English, process is much more quicker.
Confirming a sale order with 17 lines in French takes 34 secondes. The same in English only takes 4 secondes...
I have a reallly huge databases and my customer works with 5 languages. So ir_translation has many records.
A lot of processes are impacted, I also notice this behavior in picking confirmation for example.

OPW-769715

**Comment by odony** [comment]
Looking closer at the reproduction case provided by @rousseldenis, it turns out the only reason the system is using translations while computing inventory quantities, is because of the sorting on `product_id`.
By default `read_group()` uses the grouped field for sorting, as this gives an expected result in the web UI. For non-interactive `read_group()` calls where the order is irrelevant, this can be easily turned off by passing `orderby='id'` to the call. This should even be faster than forcing the contextual `lang=''`, because it can sometimes remove the need for another JOIN towards the product table, for the sole purpose of sorting.
You can try it easily with the repro case:

```python
self.env['stock.quant'].with_context(lang='fr_BE').read_group([
    ('location_id',
     'child_of',
     self.env.ref('stock.stock_location_stock').id)],
     ['product_id', 'qty'],
     ['product_id'],
     orderby='id',
     limit=80)
```

So for 10.0, I propose to selectively use this technique to speed up indirect `read_group()` calls wherever it makes a big difference (starting with locations quoted above). We can't change the default behavior of `read_group()`, even if that would of course be easier.
Together with the extra index mentioned earlier, we might get acceptable performance until we can get rid of the subquery entirely.

For master we'll start with the creation of a UNIQUE constraint and the removal of the subquery, and consider other possible improvements. At the end of the day, our translations system has to support many other features than this one, such as simple import/export mechanisms, external translations requiring metadata, and so on. This makes the current table-based approach rather well suited.

**Comment by gdgellatly** [comment]
@odony FWIW

1. I was under no illusion that any such change would be trivial (for the reasons you identified, plus the general complexity of jsonb queries and indexing not to mention differences between pg versions in available operations)
2. To satisfy my curiosity I made up a half reasonable test rig of random data, around 300,000 records using random md5 hashes.  These are roughly the results.

- With both tables non/poorly indexed, jsonb was about 15ms vs 280ms for ir_translation.
- Properly queried and indexed (as per your guideline for ir_translation) the jsonb records were about twice as fast but the absolute difference was minimal 0.6ms vs 1.4ms, however constructing good jsonb queries and indexes is a lot more complicated, so I kind of came to the conclusion it wasn't worth it.  I didn't test with a UNIQUE index, but it would only have brought the 2 results closer.
- Using GIN indexes and pg_trgm for some other slow performance issues was pretty much a dead heat on openended ilike value queries.

**Comment by Cedric-Pigeon** [comment]
@odony Indeed, this subquery is triggered each time an order by product_id is triggered but this is not limited to read_group() methods. It is overall the application.
As I explained I have performances issues when validating a sale order because a lot of queries are including this join.
This join in this kind of queries are really painful, even with the index.
`  SELECT "stock_move"."id" as "id" FROM "stock_move" LEFT JOIN "product_product" as "stock_move__product_id" ON ("stock_move"."product_id" = "stock_move__product_id"."id") LEFT JOIN "product_template" as "stock_move__product_id__product_tmpl_id" ON ("stock_move__product_id"."product_tmpl_id" = "stock_move__product_id__product_tmpl_id"."id") LEFT JOIN 
	                (SELECT DISTINCT ON (res_id) res_id, value
	                 FROM "ir_translation"
	                 WHERE name='product.template,name' AND lang='fr_FR' AND value!=''
	                 ORDER BY res_id, id DESC)
	             as "stock_move__product_id__product_tmpl_id__name" ON ("stock_move__product_id__product_tmpl_id"."id" = "stock_move__product_id__product_tmpl_id__name"."res_id")
	                        WHERE "stock_move".id IN (1123381, 1123382) AND ("stock_move"."company_id" IS NULL   OR  ("stock_move"."company_id" in (4)))  ORDER BY "stock_move__product_id"."default_code" ,COALESCE("stock_move__product_id__product_tmpl_id__name"."value", "stock_move__product_id__product_tmpl_id"."name") ,"stock_move__product_id"."id" ,"stock_move"."date_expected" DESC,"stock_move"."id"`

They are plenty of example like that, the order by clause on product.template columns are totally useless in this case and causes a big lake of performance.
On each join on product_product or product_template, the order by clause is added, even if we don't select any columns of them.

**Comment by Cedric-Pigeon** [comment]
Another example of this useless join on ir_translation:

`SELECT "stock_pack_operation".id FROM "stock_pack_operation" LEFT JOIN "product_product" as "stock_pack_operation__product_id" ON ("stock_pack_operation"."product_id" = "stock_pack_operation__product_id"."id") LEFT JOIN "product_template" as "stock_pack_operation__product_id__product_tmpl_id" ON ("stock_pack_operation__product_id"."product_tmpl_id" = "stock_pack_operation__product_id__product_tmpl_id"."id") LEFT JOIN 
	                (SELECT DISTINCT ON (res_id) res_id, value
	                 FROM "ir_translation"
	                 WHERE name='product.template,name' AND lang='fr_FR' AND value!=''
	                 ORDER BY res_id, id DESC)
	             as "stock_pack_operation__product_id__product_tmpl_id__name" ON ("stock_pack_operation__product_id__product_tmpl_id"."id" = "stock_pack_operation__product_id__product_tmpl_id__name"."res_id") WHERE ("stock_pack_operation"."picking_id" in (186787,186788)) ORDER BY "stock_pack_operation__product_id"."default_code" ,COALESCE("stock_pack_operation__product_id__product_tmpl_id__name"."value", "stock_pack_operation__product_id__product_tmpl_id"."name") ,"stock_pack_operation__product_id"."id`

**Comment by odony** [comment]
@Cedric-Pigeon the difference is that `read_group()` has an implicit sort order, and grouping on `product_id` is a common thing to do, so `read_group` calls are a likely culprit. They're also easy to optimize, as the sorting is often not intended.
Whereas even if other `search`/`read`/`search_read` also have an implicit order (the model's `_order`), those aren't likely to be based on `product_id`. The remaining cases are therefore likely to be caused by explicit sorting, which is much harder to optimize without breaking features, obviously.

BTW if you find many "useless joins", it would be pretty useful to identify the piece of code that triggers it, to see if we can get rid of the sorting. Raw queries on their own aren't as helpful.

**Comment by odony** [comment]
@gdgellatly thanks for the insightful feedback!

**Comment by nim-odoo** [comment]
@Cedric-Pigeon Actually, many `read_group` calls are triggered from computed fields. Most of them are non-stored fields, so they should not be computed during actions which are not explicitly calling them. For example, in my setup, validating a SO doesn't trigger a call to `_compute_quantities_dict`, and therefore the fix proposed in https://github.com/odoo/odoo/issues/18679#issuecomment-324849765 is not likely to help.

The query you mention in https://github.com/odoo/odoo/issues/18679#issuecomment-326941971 is interesting, but as @odony said, it would be more useful to know in which case it is triggered. I tested the SO validation on my side with a stockable product, and this query is not generated. On the other hand, opening the form view of a product is affected by these queries, obviously because all these non-stored computed fields are called (cf. https://github.com/odoo/odoo/issues/18679#issuecomment-324849765).

We don't have a plan for a global fix of the problem in stable version, but instead fix the use cases separately. PR #19247 should fix the use case mentioned previously. However, that would be useful to get more details on your setup so we would be able to reproduce these 'useless joins'.

**Comment by Cedric-Pigeon** [comment]
@odony @nim-odoo  I looked deeper on my code to find the origin of these queries and I found the reason. I found an order by redefinition on stock.move and stock.operation using product_id columns. This explains why the orm generates the join on ir_translation. I redefined them in tree views and performances are better. My apologizes for this.
So please forget this point. It only remains the read_group issue but as I can see you are looking for a fix. Thanks for that.

**Comment by Cedric-Pigeon** [comment]
@odony @nim-odoo I removed my override to put `lang=''` in `read_group` context to replace it by your suggested fix. Unfortunatly it doesn't solve the time repsonses.

With`lang=''`, my tree view on products takes 2.6 secondes to load.
With your fix, it takes 6 secondes.

So I think there is still a problem somewhere.

**Comment by nim-odoo** [comment]
@Cedric-Pigeon What are the fields displayed in your tree view?

**Comment by Cedric-Pigeon** [comment]
@nim-odoo The standards one + a custom one. If if remove these lines in tree view:
` <field name="qty_available"/>
  <field name="virtual_available"/>`

The loading time fails to 1 seconde.

**Comment by nim-odoo** [comment]
To go a bit deeper in the method itself, I focused on the time spent on the line https://github.com/odoo/odoo/blob/10.0/addons/stock/models/product.py#L146. I reused the script provided by @rousseldenis to generate the data, and executed 3 flavors of the same `read_group`. Each instruction is run twice in the same transaction.

```
Case 1: Move.read_group(domain_move_in_todo, ['product_id', 'product_qty'], ['product_id'])
Run 1: 1.443234920501709
Run 2: 0.4054238796234131

Case 2: Move.read_group(domain_move_in_todo, ['product_id', 'product_qty'], ['product_id'], orderby='id')
Run 1: 1.0450448989868164
Run 2: 0.004614114761352539

Case 3: Move.with_context(lang='').read_group(domain_move_in_todo, ['product_id', 'product_qty'], ['product_id'])
Run 1: 0.01329183578491211
Run 2: 0.007340908050537109
```

The order of magnitudes are similar to what I observed when testing this with @odony . What we noticed (but didn't pay attention to) is that the second run of the query is much faster than the first run, especially in the second case.

So that looks good on the paper, but in practice, when the view `product_template_tree_view` is opened (or when one uses the pager), the durations of Run 1 need to be considered. In that case, our solution improves the view loading by ~30%, which is not that good considered the absolute values of the durations.

More details on the queries generated:
Case 1: https://gist.github.com/nim-odoo/b143667c2793358763a507b30cf08472
Case 2: https://gist.github.com/nim-odoo/cd1fc2bdfb712f0e0c8d9bac8b7d61d6
Case 3: https://gist.github.com/nim-odoo/74be47a034de71f2bac0e1d77aafa86b

The costly subquery is used:
Case 1: 4 times
Case 2: 3 times
Case 3: never

To be continued...

**Comment by nim-odoo** [comment]
Another global improvement is to apply the following commit in v10: https://github.com/odoo/odoo/commit/439fa82676a011328c7f03c1259b9ec545a06039
(see https://gist.github.com/nim-odoo/d111dad2a9663e9bef691e082b6bf666)

That's another ~600 ms won on the test instruction, although we cannot commit such a change in stable. For the record, the SQL queries generated: https://gist.github.com/nim-odoo/e618b99c3d1982809823f899a92f09fd

**Comment by taifu** [comment]
@odony wrote:

> @rco-odoo @antonylesuisse @beledouxdenis Given the focus on performance in Odoo 11, it might be time to replace 6a366b2 in master by something smarter and faster, like a unique constraint.

I see that this isn't yet true: https://github.com/odoo/odoo/blob/11.0/odoo/models.py#L3545

Please, add the constraint. Don't leave this huge performance problem also in Odoo 11 :-/

**Comment by Yenthe666** [comment]
@nim-odoo can I ask for you a feedback on this issue please? Sorry for the ping.

**Comment by taifu** [comment]
So sad this it's going to stay in 11 :-(

**Comment by Yenthe666** [comment]
@nim-odoo any update please?

**Comment by mart-e** [comment]
@Yenthe666 @taifu we are going to remove the distinct in master at #21472 but we can not do that on a stable version, would not be very safe.

Still need more testing before merging.

**Comment by taifu** [comment]
@mart-e GREAT! This is the first step. Thanks a lot for your effort. Really

**Comment by mart-e** [comment]
The performances should be improved in master at 160d657704037fd22051f4101e9b477ae1ff0340
Let us know if you find corner cases where the constraint is raised.

**Comment by Yenthe666** [comment]
@mart-e thanks a lot for the great job! I'll try to test it a bit in the master soon.

**Comment by rousseldenis** [comment]
@mart-e Could you provide a blocked PR for our OPW on 10.0 branch ?

**Comment by mart-e** [comment]
@rousseldenis sorry but what do you need? You should be able to apply 160d657704037fd22051f4101e9b477ae1ff0340 and ad3b28fd8957a717b4a5ba7292068276925495ee on your 10.0 branch if needed but we can not backport it.

**Comment by rousseldenis** [comment]
@mart-e No, that's ok if I can apply these commits to 10.0 directly

**Comment by rousseldenis** [comment]
@mart-e https://github.com/odoo/odoo/commit/160d657704037fd22051f4101e9b477ae1ff0340 cannot be applied on 10.0 directly.

Can you provide the patch ? Thanks

**Comment by mart-e** [comment]
Well it applies but the file was renamed 😉  try with odoo-dev/odoo@f227d9877d069fb7e07d74cb2a5cdc6ad5e0ef8b

**Comment by rousseldenis** [comment]
Function 'create_unique _index' does not exists in v10...

**Comment by mart-e** [comment]
Right, but it is not too complex to backport too 
https://github.com/odoo/odoo/blob/4637bdf9bf1fa2644a048d5e586fc1b655a2940e/odoo/tools/sql.py#L192-L198

**Comment by eantones** [comment]
Hi!
Is there a way to propose a PR to Odoo official repository (not only on OCB) not for merge (we have to wait till v12 for that) but to use as a remote patch for manual merging or via tools like https://github.com/acsone/git-aggregator
Now I am doing this from my repo but, I think that would be interesting to have it on official repo too. Maybe there's another more appropriate way to achieve the same, if that's the case I'd like to know how.
I think this issue is important enough to make it easier for people to apply it.
Thank you very much
