### ISSUE TITLE
[10.0] adding product attributes reset variant customizations

### ISSUE THREAD

**Issue by lukebranch** [odoo/odoo#18682]
<h1>Enterprise Support Ticket Reference:</h1>
<h3>762743</h3>

<h1>Impacted Versions:</h1>

- 10.0
- Master

<h1>Steps to Reproduce:</h1>

1. Create an attribute with create_variant boolean un-ticked (ie. don't create variants from these attributes). For example 'Test Attribute'
2. Create attribute values related to the above attribute. For example 'Test 1', 'Test 2', etc
3. Create a product (product.template) and assign some attributes and attribute values that will create variants (eg. in runbot try color, and memory)
4. Assign a default_code and barcode to each of those variants
5. On one of the product variants, add one of the attribute values for the attribute we've created in step 2 to the attribute_value_ids field to allow for filtering by product attributes that do not create variants (for example these attributes will provide a specification that is not necessarily configurable).
6. Create a purchase order for this product variant and receive the product into inventory (eg. purchase one unit).
7. Go back to product template and add another attribute value to an attribute where create_variant == True
8. Our value from attribute_value_ids is gone, and the inventory is no longer visible on the product variant in question.

<h1>Current Behaviour:</h1>

- Product variant is not retaining additional attribute_value_id's for attribute values with an attribute where create_variant == False
- In this scenario a product seemingly vanishes from inventory (from the user's perspective at least)
- Filters are lost on those attributes and attribute values where create_variant == False

<h1>Expected Behaviour:</h1>

- Product variants should retain their attribute_value_ids for attribute values with an attribute where create_variant == False even after additional variants are created by adding attribute values to attributes where create_variant == True
- In the same way, the product variants where these attribute_value_ids with create_variant == False are assigned should stay visible in inventory as the attribute_value_ids should retain those attribute values where create_variant == False
- Filters for attributes where create_variant == False should remain in place on the e-commerce website

<h1>Video/Screenshot link (optional):</h1>
Please see the following youtube video for reference:
<a href="https://youtu.be/JNqpYKxZkPo">https://youtu.be/JNqpYKxZkPo</a>

The example scenario, and video has been tested on the latest version 10.0c runbot as of 6:00PM HKT (Hong Kong Time)

**Comment by lukebranch** [comment]
@Yenthe666 ,

Sorry to tag you on this one, i'm not sure who to talk to about this issue. It seems like a rather critical bug if create_variants is to be used on attributes. Any help would be appreciated.

Once I have added a video i'll submit a support ticket with my customer's enterprise subscription code.

**Comment by Yenthe666** [comment]
No problems on tagging me in. This looks like one for @mart-e to me. 👍 
Also, no feedback on the ticket yet?

**Comment by lukebranch** [comment]
Thanks Yenthe. No response on the ticket so far, however I submitted it at the same time I submitted created the github issue.

**Comment by lukebranch** [comment]
I believe this issue is related to:

https://github.com/odoo/odoo/issues/16806

**Comment by Yenthe666** [comment]
@lukebranch,

Making the field attribute_value_ids in the front-end readonly wouldn't be the right way. We have plenty of customers that use it from there for example.
As to the other issue you've linked, this is from my collegeau Ward. What it comes down to is if you create a new attribute after you've already had one or more it'll automatically delete all the 'old' records and re-create them. I've had a talk about this with the guys of Odoo and their information was "well, you know what attributes you have so if you create them all at once at the beginnen of the problem you won't have any problems". In my opinion this logic is flawed and the `variant.unlink()` should be replaced with another option so that attributes don't get dropped and re-created. 😄

**Comment by lukebranch** [comment]
@Yenthe666 ,

I wholeheartedly agree, it's incredibly confusing for the end-user. I believe the behaviour of this function needs to be revisited, as it makes using attributes to generate product variants incredibly fragile from a user's point of view.

In my use-case it's useful to have attributes such as 'Gender', 'Collection', etc. as create_variant == False, as this allows users in the website to filter based on these attributes, however this becomes unusable for this use-case if they are not able to add additional create_variant == False attributes without wiping over existing variants.

**Comment by Yenthe666** [comment]
Yep I feel your point there. Sadly we face some of these issues too and we had to do custom development eventually to by-pass this problem.. (read: don't drop all attributes in production.)

**Comment by mart-e** [comment]
Hello,

Indeed, it is +/- the same issue. Adding product attributes afterwards will mix up existing variants.
It is a known limitation and I agree we should improve this.
You should get an answer soon on the ticket.

**Comment by Yenthe666** [comment]
@mart-e is this something that'll be handled in V11 or is it not yet determined when/what will happen to change this?

**Comment by lukebranch** [comment]
@mart-e ,

Thank you for looking into this. I'll keep an eye out for the response on the ticket.

Should I mark this one as closed in favour of #16806?

**Comment by nim-odoo** [comment]
I think this can be partially solved with #18813

As long as you add an attribute with only one value, the products should not be unlinked/archived. However, if you add an attribute with more than one value, that won't change anything: the products will be unlinked/archived.

**Comment by lukebranch** [comment]
@nim-odoo ,

Thank you for the quick response. I'll test and provide feedback on this issue as soon as possible.

**Comment by Yenthe666** [comment]
@nim-odoo thank you for the (partial) fix.
However, the line of code `variant.unlink()` is still being triggered so what if I add a new attribute **and** new attribute values? The unlink will still be triggered and I still lose my data (as they are reappended).

**Comment by nim-odoo** [comment]
@Yenthe666 : My fix only filters out attributes which are not supposed to create variants, which makes sense since we are in the variant creation part. Other than that, yeah, that is still the same logic. The only advice I can give is to NOT modify attributes as soon as the product has been used.

**Comment by gdgellatly** [comment]
@nim-odoo I was thinking a similar thing in terms of ultimate resolution.  A bit like product uom's that can't be changed.  In essence (pseudo logic)

as soon as a product has been used - 
attribute line becomes edit only, no new attributes can be added.
attribute_id on attribute_line also becomes readonly. 

That way attribute values can still be freely added and removed, and this works well (current bug aside), however the solution for adding a new attribute line becomes one of duplication of the template and start from scratch.  This has a few benefits - firstly, by definition, if a product has a new attribute - then really it is a different product now anyway, so it should be a new product.  Secondly, existing older products are preserved and can be deactivated, removed, stock transferred, reworked etc as appropriate.  Finally, it will save users from themselves (much like the UoM rule)

However, that won't solve this bug, as it occurs when adding attribute values, but it would resolve the create_variant == True ones.  I'm unfortunately not familiar with create_variant == False.

**Comment by Yenthe666** [comment]
@nim-odoo it is a great advice but what if your product gets a new type of attributes or a new range? You can't product which attributes will follow or what will change on some products so there is no way for you to know that before the moment is there. As stated in the other topic, I still find this a bug / real world problem.

**Comment by nim-odoo** [comment]
@gdgellatly I think our main issue is to silently unlink or archive products. I would say that the unlinking might still be acceptable, since it probably means that the products hasn't been used. `product_id` is a field required on many object, so unlinking it will raise an error. However, that is not 100 % true, and issues may arise.
But falling back on archiving means that products will suddenly disappear from the inventory or list of available products. IMHO, this is not logical: at some point, we probably received these products in our inventory, we have been using them, so no reason to deactivate them without warning. The information is not lost, but I don't think lambda users will understand what just happened.

**Comment by gdgellatly** [comment]
@nim-odoo all this time i've been misunderstanding how that function worked with new attributes.  This is a bit long, but a real use case that may give you some ideas.  You are correct.  However I still think silently inactive makes no more or less sense than unlinking, at least in the case of adding or removing attribute values.  Afterall, if its no longer available in Red its no longer available.  However, there are some caveats about what available (and used) means. 

My real use case is 300,000 products over 1600 variants.  The primary attribute is colored steel and these change occasionally, new colours introduced, ranges restricted for some products etc.  And this is the real problem.  

Lets say a supplier decides to kill off 10 colours.  Now if I stock them, I probably don't want to deactivate until I have no stock, but how do I know when I have no stock? (Actually in this case deactivating works well as I can no longer purchase it, and its raw materials that aren't sold, but if I purchased to sell I'd want it it unavailable for order, available for sale until sold out.)  

Now this colour is used in say 13 different BoMs for other products, I may never have even used some of the BoMs for that colour, yet now that product will be unlinked as never used, yet I could still supply it.  (So I'd say any product that can be manufactured, maybe unlinking isn't a great idea)

So what I really want to do is remove/deactivate the product when I can no longer supply it, and today that is a very arbitrary process.  It goes something like this.  I update the attribute value and append a marker, in my case '(O)' for obsolete.  Sales knows they need to check stock carefully then before accepting an order.  Then every few weeks or so I check whether we have sold through all stock of the raw materials.  To make matters more difficult, stock is multicompany across 9 companies and 14 warehouses.

After a year or so, the last of it is sold through.  Just in time for the next change.

I could probably write a module to handle that, the only proviso would be that the unlink part of create_variant_ids would need to be factored into a seperate function.

So if I think about how I would handle variant creation and deletion in a perfect world.
Immediately on change
1. Not manufactured or sold - current behaviour.
2. Not manufactured but sold - available on SO until no stock left, never on PO.
3. Manufactured - only unlink if a product required to manufacture is also unlinked, otherwise deactivate.

However, in practice I think maybe option 1 and 3 are enough if 

Either make inactive stocked products visible in SO, Product Lists etc (option 2),or 
Make Active / Inactive highly visible in appropriate search views and add a button to disable active_test on SO.  e-commerce may need similar.

**Comment by lukebranch** [comment]
@nim-odoo ,

Thank you for the fix, and my apologies for getting back to you so late. The fix works as expected.

I have seen a bit of activity in a dev branch with a new module called 'product_configurator'. Is there a major refactoring planned for variants in the future, or is this just the early stages of R&D for those additional features?:

https://github.com/odoo-dev/odoo/tree/master-product-variantification-kap/addons/product_configurator

**Comment by treviser** [comment]
I just stumbled upon this issue and I'm asking myself what is the reason for this behaviour? Why must existing variants be reset in the first place (they are not archived, as I can see) when new variants are created?
Sample business case: Wines
The product template for a wine is very extensive, many attributes, a lot of description. Year after year a new vintage is available, but I still have older vintages on stock and I do not want to create new products because of one simple attribute, but I should be able to assign a particular price to a vintage. Also I have to order wines with the new vintage while I'm still having old vintages on stock. What am I supposed to do in this case?

**Comment by Yenthe666** [comment]
@treviser I guess override the function that unlinks and prevent the unlink. We've done it in the past too. Its a shitty flow for functional people 😕

**Comment by treviser** [comment]
@Yenthe666 As an old-school conceptional data modeler, I can not understand the design concept behind this behavior. To me it is absolutely useless. Why bother about doing/unlinking something when it is not necessary in the first place from a logical point of view? Or is the design of Product Templates vs Product Variants still unclean?

Anyway, do you have a code snippet or something that helps/guides a Not-Die-Hard-100years-Experienced Coder such as me?

**Comment by Yenthe666** [comment]
@treviser,

You could do something along the lines of (look at the end with the logger statement):
```
# -*- coding: utf-8 -*-

from openerp.osv import osv, fields, expression
import logging
_logger = logging.getLogger(__name__)

class product_product(osv.osv):
    _inherit = 'product.template'

    def create_variant_ids(self, cr, uid, ids, context=None):
        product_obj = self.pool.get("product.product")
        ctx = context and context.copy() or {}
        if ctx.get("create_product_variant"):
            return None

        ctx.update(active_test=False, create_product_variant=True)

        tmpl_ids = self.browse(cr, uid, ids, context=ctx)
        for tmpl_id in tmpl_ids:

            # list of values combination
            variant_alone = []
            all_variants = [[]]
            for variant_id in tmpl_id.attribute_line_ids:
                if len(variant_id.value_ids) == 1:
                    variant_alone.append(variant_id.value_ids[0])
                temp_variants = []
                for variant in all_variants:
                    for value_id in variant_id.value_ids:
                        temp_variants.append(sorted(variant + [int(value_id)]))
                if temp_variants:
                    all_variants = temp_variants

            # adding an attribute with only one value should not recreate product
            # write this attribute on every product to make sure we don't lose them
            for variant_id in variant_alone:
                product_ids = []
                for product_id in tmpl_id.product_variant_ids:
                    if not variant_id.attribute_id <= product_id.mapped('attribute_value_ids').mapped('attribute_id'):
                        product_ids.append(product_id.id)
                product_obj.write(cr, uid, product_ids, {'attribute_value_ids': [(4, variant_id.id)]}, context=ctx)

            # check product
            variant_ids_to_active = []
            variants_active_ids = []
            variants_inactive = []
            for product_id in tmpl_id.product_variant_ids:
                variants = sorted(map(int, product_id.attribute_value_ids))
                if variants in all_variants:
                    variants_active_ids.append(product_id.id)
                    all_variants.pop(all_variants.index(variants))
                    if not product_id.active:
                        variant_ids_to_active.append(product_id.id)
                else:
                    variants_inactive.append(product_id)
            if variant_ids_to_active:
                product_obj.write(cr, uid, variant_ids_to_active, {'active': True}, context=ctx)


            # fix product cost price set to zero
            products = self.pool.get('product.product').search(cr, uid,[('product_tmpl_id.id','=',tmpl_id.id)], context=context)
            price = 0
            if products:
                ids = self.pool.get('product.price.history').search(cr, uid, [('product_id.id','=',min(products)),('cost','!=',0)], context=context)
                if ids:
                    price = self.pool.get('product.price.history').browse(cr,uid,max(ids),context=context).cost
            if price == 0:
                price = tmpl_id.standard_price

            tmpl_id.update_standard_price_for_all_variants = tmpl_id.standard_price

            # create new product
            for variant_ids in all_variants:
                values = {
                    'product_tmpl_id': tmpl_id.id,
                    'attribute_value_ids': [(6, 0, variant_ids)],
                    'standard_price': price
                }
                id = product_obj.create(cr, uid, values, context=ctx)
                variants_active_ids.append(id)

            # unlink or inactive product
            for variant_id in map(int, variants_inactive):
                _logger.warning("Product variant " + str(variant_id) + " should not be unlinked because they could still have stock.")

        return True
```

**Comment by treviser** [comment]
@Yenthe666 What if I simply remove the "elseif" statement at line 393/394 here:
https://github.com/odoo/odoo/pull/18813/files ?

**Comment by Yenthe666** [comment]
@treviser probably also an option. 😉

**Comment by treviser** [comment]
@lukebranch I've seen in your post here dated August 7 2017 that you are using attributes the same way as I do, are you aware of the "quasi-variants" as described here: https://github.com/odoo/odoo/issues/23538 ?

**Comment by lalitkumar2k10** [comment]
Hi there, any update on this. Is the workflow still same or there is some changes over this?

**Comment by treviser** [comment]
I stumbled upon the release notes for 12.5, section eCommerce/Product Variants: https://www.odoo.com/fr_FR/odoo-12-5-release-notes
But I can't find the code nor any description what it really means.

**Comment by advrider** [comment]
It's almost 2024 , 17.0 is out and I see this issue is still part of Odoo. I discovered this the hard way.

When Odoo can't figure out what the attribute should be for existing variants, it should give the user the choice to re-create the whole variant bank or stop and allow the user to make the variants based on the newly added attribute,  not to remove them and delete all the inventory data, SKU, barcodes etc. without warning. User may not realize what has happened until it's too late.

Odoo doesn't delete (unlink) variants when the newly added attribute has "Variant Creation Mode" set to Dynamically or Never. Because of course it isn't need to

Real world example:

We have been selling a t-shirt product that was always black. We have plenty of stock in all sizes. (S, M, L, XL,...) they even included in some bundles, they have barcodes etc. Now we want to add two new color to jazz things up. A new color attribute is added. I add the attribute (with default setting for Variant Creation Mode set to Instantly and I can't change it because the attribute color is used for other products). I select Black, White and Red. I click save and boom all my inventory data, the barcodes, inventory, BOM's for exiting t-shirts is gone without warning. How is that OK ?

A workaround would be add just one value to the new attribute SAVE, and THEN add more attributes, so Odoo knows what it should do with existing variants. Add Black, Save, so now all existing t-shirts are set to Black, then add other colors. This way all data is preserved. Even with Variant Creation Mode set to "Instantly". Why don't we share that with users on that page. This is very useful info.

Also some sort of check for admin to allow or disallow users to take any action that results in recreating variants (loss of data). Wouldn't this make sense?

**Comment by Sisyfos33** [comment]
Hi,
I have recently encountered the problem with variants creation in Odoo and I must say that I agree with @advrider.
It is baffling that the variants creation is so stupid.
However, I think that the best solution would be not to create any variants at all automatically.
Instead I think you should be able to just import the variant combinations you want.
That way you could import only the variants  with the attribute and value combination you need.
you'd still have the benefit of having everything under one product type and see all the variants under it.
But, I still think that if you add a new attribute to your template it is technically a new product so it should really be a whole new set of variants but it should not delete the old ones.

**Comment by majorbird-team** [comment]
+1 with @advrider and @Sisyfos33 .
