### ISSUE TITLE
[10.0] account: Statement reconcilation of already manually reconciled entries

### ISSUE THREAD

**Issue by pedrobaeza** [odoo/odoo#18972]
Impacted versions: 10.0

Steps to reproduce:

1. Go to runbot
2. Create one invoice for any customer and validate it.
3. Create a manual journal entry with a line for the bank account (101401) and another with the partner account, with the amount of the invoice.
4. Reconcile manually both partner lines (invoice and manual one).
5. Create an statement with the same amount.

Current behavior:

There's no possible line for reconciling.

Expected behavior:

The bank line appears in blue and you are able to reconcile. It's the same process as you expect when creating a payment in Odoo and you later reconcile that payment.

Additional information:

This was introduced in this commit: https://github.com/odoo/odoo/commit/9188d0193465e7aca5c7c9a43ee2b16ba00cbae6, and I think it was motivated for differentiating black and blue lines, but the black part has been later restored as it was (and it's correctly working), and the same can be applied for blue lines. In v9 it's working correctly as it was without mixing lines: 
https://github.com/odoo/odoo/blob/68de5c7e9fe00824a692fab06b5b19c7d5741570/addons/account/models/account_bank_statement.py#L565

One reason for being this important is because not always you have an account.payment record for recording the payment. In this case, the problem has arisen using payment returns via this OCA module: https://github.com/OCA/account-payment/tree/10.0/account_payment_return, as we want to reconcile the amount indicated on the statement with the already reconcile amount handled when confirming the return. There's no sense to create an extra account.payment record (and it would generate incorrect account.move.line records) for being able to do it. Think also in other journal items import processes that need also to be able to reconcile bank statement lines.

**Comment by rafaelbn** [comment]
Video reproducing the issue: https://youtu.be/bdp8ZbHZg4M

**Comment by Yenthe666** [comment]
Hi @pedrobaeza and @rafaelbn,

Thank you for the report and the video. Videos are really handy to see the problem and reproduce.
To me this does indeed look like a bug that has to be fixed.
@qdp-odoo could you have a look and give feedback?

Regards,
Yenthe

**Comment by pedrobaeza** [comment]
The fix is very simple: revert back the domain to what it was, which is removing `('payment_id','<>', False)` condition.

**Comment by Yenthe666** [comment]
@pedrobaeza yes but I'm not sure if there was another reason why qdp introduced it so I'll wait for some feedback. If this is the case he can revert it for you guys 👍

**Comment by qdp-odoo** [comment]
Hello,

we are aware of this issue but unfortunately, as Yenthe sensed, we can't just remove that part of the domain since the problem isn't just that simple.

Indeed, this part of the domain is also important for hiding lines in case of an accounting being imported in Odoo: you don't want to see in the bank statement reconciliation widget all the lines of past years. 

Moreover, all bank operations made by Odoo official modules do create an account.payment (even the bank statement reconciliation widget) and men could argue that, from an auditing point of view, this is defensible as it's nice seeing in a single place bank transactions created by bank statement or directly registered on invoices/bills.

For these 2 reasons, this bug report cannot be considered as a bug, and will be closed. But please note that we know there is here room for improvement and that's something we'd like to address in future versions.

Thanks for your understanding

**Comment by pedrobaeza** [comment]
Quentin, has this finally been improved in v11? I hadn't got yet enough time to check.

**Comment by qdp-odoo** [comment]
nope, unfortunately...

**Comment by pedrobaeza** [comment]
OK, thanks for telling.
