### ISSUE TITLE
"Add an Item" doesn't showing in the many2many field.(odoo 9)

### ISSUE THREAD

**Issue by robin1922** [odoo/odoo#18987]
I have wizard containing a man2many field to product.product. those users who have the create permission in product.product object can see the "Add an Item" link.the users don't have the create permission are unable to see the mentioned link. 

![picking](https://user-images.githubusercontent.com/3063320/29562038-60a4ab70-8755-11e7-8f6d-5c43a4160ea4.png)

**Comment by Yenthe666** [comment]
Hi @robin1922,

Thank you for your report.
This is however default behaviour and is in fact the desired behaviour.
If a user has no create permissions the "Add an item" will not be shown, otherwise it will.
In short: not a bug - you'll need to give the users correct access rights.

Regards,
Yenthe

**Comment by sandeepksrana** [comment]
@Yenthe666 For many to many field that's not correct while read only permission is there sometime user can have permission only to read it while no create permission,  before v9 it was there and work fine

**Comment by Yenthe666** [comment]
> while read only permission is there sometime user can have permission only to read it while no create permission,

Huh? You're saying that you have read permissions when you have read permissions. Sounds logical to me. Can you please rephrase and add an example that shows something is wrong here? Because I don't see any issue

**Comment by sandeepksrana** [comment]
Yes, see  I have a model `hr.employee` and i have added a field  `many2many` relation with this model in a wizard. now i reporting manager have access to his employee while he can't create an employee, now in many2many the employee should be selected but the add an item button is not displayed, when giving him the create access it show up.  before v9 it worked fine,

**Comment by FabioTechSpell** [comment]
@Yenthe666 Consider that you are using in a wizard, usually with TransientModel, and you need only to link object  chosen to current one. So having write permission on group is useless, nevertheless you should avoid to assign permission rules to TransientModel. Last but not least, if you try to create the rules, to allow to write on that group, you won't be able to have "Add an Item" with any user than "admin". In my opinion, this behavior sounds as a bug.

**Comment by yk2kus** [comment]
It is a bug indeed. If the user has read/write access on the record it should show "Create an Item" button to be more correct it should show "Select an item". The user is not supposed to create a record in the target mode but at least he should be able to select already created records in the many2many field since he has write access on both source and target model.
If I remember correctly, this behavior was correct in order versions.

**Comment by martinvarela** [comment]
It's a bug. In v8 works OK. 
A workaround is to add in the tree part of the many2many field:  create="true" delete="true" edit="true"

**Comment by bjccdsrlcr** [comment]
> It's a bug. In v8 works OK.
> A workaround is to add in the tree part of the many2many field: create="true" delete="true" edit="true"

In v10 create="1" works fine? I have tried but doesn`t work. In addition, I have also tried create="1", editable="bottom"

**Comment by oerp-odoo** [comment]
If Odoo thinks its correct, it does not make sense, because if you for example add widget `many2many_tags`, then you can select records even if you have readonly access. But if you are not using any custom widget, then you need create permissions or `create=true` on tree which does not really like being intended.
