### ISSUE TITLE
[10.0] Wrong UoM Factor exported and imported

### ISSUE THREAD

**Issue by gustavovalverde** [odoo/odoo#19089]
### Impacted versions:
10.0

### Steps to reproduce:
Export a UoM that's **bigger** than the unit of reference by a `factor` of 2.0

### Current behavior:
Exported factor is 0.5 instead of 2.0

### Expected behavior:
Depending on the `uom_type` the factor should be correctly computed for import or export, otherwise different fields should be used. Right now it's very confusing to make imports or mass corrections on units of measure.

**Comment by amoyaux** [comment]
It happens because the system only use the same field in order to compute related data. We won't make a check on type each time we have to use the ratio on the UOM.

If you want to export the correct ratio, you have two choice:
- Make a script on your excel in order to update the ratio on bigger uom than reference with ratio = 1/ratio
- Create two export file: Filter on odoo on bigger than reference and export bigger ratio instead of ratio (don't forget to check Export all Data and you won't be able to import them after)
and for the second file for smaller than reference and reference use ratio.
