### ISSUE TITLE
Diagram view ERROR

### ISSUE THREAD

**Issue by esmairi** [odoo/odoo#19132]
Impacted versions: 9.0 entreprise

Steps to reproduce: Go to Lead Automation -> Compaigns -> NEW -> fill the form -> click Diagram icon

Current behavior: Odoo Warning - Access Error

Expected behavior: No Error

Video/Screenshot link (optional): 

![campaigns odoo](https://user-images.githubusercontent.com/3525198/29821262-31753bb6-8cbf-11e7-8a10-40c46b2fd518.png)

![campaigns odoo](https://user-images.githubusercontent.com/3525198/29821025-66269554-8cbe-11e7-9293-a1d1a4e2bd3c.png)

**Comment by Yenthe666** [comment]
Hi @esmairi,

Thanks a lot for your report.
This does indeed give a security error that shouldn't go off. However, if this would be fixed you would get another error though as you haven't saved the record yet. Example:
![image](https://user-images.githubusercontent.com/6352350/34439307-36ffae10-ecad-11e7-94a1-7d7097742f5e.png)
Nevertheless I believe the first dialog (from your report) shouldn't be triggered.
OPW 803077

Regards,
Yenthe

**Comment by Yenthe666** [comment]
Hi @esmairi,

I was facing this 'issue' too so I've asked feedback from Odoo itself and I really thought it would qualify as a bug. The official response:

> Hello,
Thank you for your inquiry. In order to view your Lead Automation Campaign in diagram view, you will first need to save the campaign. Once the campaign has been saved, you should be able to view it as a diagram without error. In order to further demonstrate this, I am attaching a brief video for your reference. 


So I'm closing this bug report as Odoo does not consider it a bug. I guess we'll just need to save before going to the view. 😉
