### ISSUE TITLE
Text search is sub-standard due to unnecessary Odoo imposed limitation

### ISSUE THREAD

**Issue by elgow** [odoo/odoo#19208]
Impacted versions: 9.0, 10.0

Steps to reproduce: Attempt to utilize powerful postgresql full-text search feature by defining a search view like:
```
     <search>
            <field name="description" operator="@@"/>
```

Current behavior: 
An exception is thrown by Odoo code
```
  File "/Volumes/Work/Home/UW/PycharmProjects/odoo10/odoo/osv/expression.py", line 289, in distribute_not
    elif token in DOMAIN_OPERATORS_NEGATION:
TypeError: unhashable type: 'list'
```

Expected behavior: 
Because of Google, etc. the form of search most people know and expect is full-text search. People generally do not know about SQL `ilike` and its wildcard '%'. Postgresql provides an excellent full-text search feature accessible via the `@@` operator. The ONLY reason that the search view definition above won't work is one line of Odoo code, _odoo/osv/expression.py:141_. Allowing users to get full-text search on a single column, albeit w/o an Odoo ORM created full-text index, is as simple as adding `@@` to the list of `TERM_OPERATORS` defined at the line cited above. I am using this and it works. Please add that operator to the maintained branches of Odoo so that your users have the option of better search behavior. 

Video/Screenshot link (optional):

**Comment by elgow** [comment]
For those who cannot wait for Odoo to add the required six character fix of `, "@@"` to the code, the following code can be added to your own code to get full-text search functionality. 
```
# add full-text search capability
if '@@' not in expression.TERM_OPERATORS:
    expression.TERM_OPERATORS = tuple(list(expression.TERM_OPERATORS) + ['@@'])
```

**Comment by blaggacao** [comment]
@rim-odoo If true, seems **very** valid.
This feature is a huge usability increase. Nothing to add to @elgow reasoning...

**Comment by blaggacao** [comment]
Link to the docs: https://www.postgresql.org/docs/9.5/static/textsearch-intro.html#TEXTSEARCH-MATCHING

**Comment by blaggacao** [comment]
@Yenthe666 Look at that one :smiley:

**Comment by elgow** [comment]
Will take some time to do CLA as I'm at work. I don't mind doing a pull request, but Odoo could probably make the change faster than I can get a CLA ready.

**Comment by elgow** [comment]
This would be far better if there was a full-text GIN index on the columns, but even w/o it's probably as fast as `ilike`, since that isn't indexed in the general case either.  I'll look at what it would take to integrate a GIN index spec into a model definition.

**Comment by blaggacao** [comment]
@odony I think you might like this topic, as well.

**Comment by elgow** [comment]
@blaggacao The powers that be have concluded that minor patches should be submitted by me as an individual since there is not enough there to represent definable IP. CLA is in so I'll submit the  pull request for the minimal patch.

**Comment by Yenthe666** [comment]
The PR can be found here: https://github.com/odoo/odoo/pull/19211

**Comment by odony** [comment]
I'm afraid this may not be as straightforward as it seems. If I recall correctly, if we simply replaced our current wildcard-search with implicit `@@` full-text search (FTS), we would not always get the expected result, and greatly confuse users.
They might be able to match unordered terms and similar words thanks to stemming/lexemes, but at the same time they might fail to find documents that should have otherwise matched.

Here's a simple SQL example of wildcard-match (`ilike`) vs FTS (`@@`):
```
t=# select subject from mail_message where subject ilike '%info%';
                            subject                            
---------------------------------------------------------------
 Information meeting
 RE: Information meeting
 RE: Information meeting
 RE: Information meeting
 RE: Information meeting
 Reminder: Lead Need Info about your Services from T. P.
(6 rows)

t=# select subject from mail_message where subject @@ 'info';
                            subject                            
---------------------------------------------------------------
 Reminder: Lead Need Info about your Services from T. P.
(1 row)
```
According to `ts_vector()`, the missing matches in the FTS query come from the stemming of "information" to "inform" rather than "info". This illustrates why we cannot simply use the '@@' operator as a drop-in replacement for our 'ilike' operator.

Doing proper FTS would of course be interesting, but I think that it requires a lot more instrumentation:
- building proper "documents", as FTS is not meant for individual field-based search
- handling language differences (stemming/lexemes are language dependent, and the situation is even quite different for e.g. Asian languages)
- using fuzzy search/similarity scores to work around misspellings
- possibly returning a "ranking" or "relevance" score for documents
- and of course, dealing with the performance aspects of querying this dedicated FTS data

Most of this should be possible with PG's FTS support, but should require the creation of specific fields/tables, [materialized] views, indexes, and as importantly, the addition of appropriate business logic to setup, maintain and access the FTS data.

We can discuss plans for such an addition in the future, but allowing the use of `@@` operator in domain expressions seems rather premature, and incompatible with our [stable policy](https://github.com/odoo/odoo/wiki/Contributing#what-does-stable-mean).

Please also note that we tend to reject new framework features unless we plan to use them immediately in official addons. Without this kind of commitment, the feature risks being quickly removed/broken by the natural evolution of our source code (refactorings/optimizations/cleanups). The recommended strategy is to build the feature in a third-party module, depending on a documented extension point of the framework to inject it.

**Comment by elgow** [comment]
I agree with some of the concerns that you've put forward for the notion of replacing your standard search with the `@@` full-text search. You should note, however, that my PR did not do that. It simply made it possible for the the developer of a view to *choose* to use the `@@` operator if their users find your default search to be inadequate, as mine did. For any user not choosing to use `@@` it's an invisible change.

A fully functional implementation of FTS would indeed call for specification of indexes, language settings, combination of fields, etc., but the bare bones version is still far better than your default search for some cases.  The ranking feature would be nice, but is not necessarily in scope, so it should not be an excuse for having your code deny users the chance to choose their search operator. Further, the notion that the six character addition of one DB operator to a list might be broken by your refactorings, etc. seems a bit rich.  

I invested a lot in convincing my organization to use Odoo. The awful search, which represented a step down from what the existing 6 year old rudimentary Flask app provides, was shaping up as a deal breaker.  As with another bug I filed, https://github.com/odoo/odoo/issues/17945, which was originally filed by someone else against **_Odoo version 7_** and never addressed, I'm pretty underwhelmed by your level of consideration for the needs of your users.

**Comment by gdgellatly** [comment]
@elgow if you are choosing to use, then it would be in custom design, yes I assume as you reference developer.  If it is as you say (and I doubt this for the unaccent case at least), just adding it to TERM_OPERATORS at runtime, so you can easily do in any custom module by importing and updating it.  Sure its 2 lines of code or so rather than 6 characters, but no biggie.  Indeed, they've made it easily inheritable so its not exactly denying users, just not supporting.

After very many years at this, I can promise you what @odony says is true.  Odoo will manage to break it if they don't use it.  Indeed sometimes I wonder if the last part of that sentence is even needed.

**Comment by elgow** [comment]
@gdgellatly The difference lies in how accessible the `@@` operator is to the developer designing a search view. If Odoo added it to their list then it would be accessible from the XML view definition and could possibly be specified via the GUI. If it's done the way I have then it requires a custom module, knowledge of the Python core Odoo code that specifies the list, and it is subject to breakage if Odoo renames their variable, module, etc.  Doing it as a monkey-patch in an addon module is just not as good as having them lift the restriction that their code imposes on use of that Postgresql feature.

I'm pretty new to Odoo, so I'll defer to your experience on the likelihood that they could manage make a tiny change to a list of strings w/o breaking things.

**Comment by lasley** [comment]
@elgow - May want to look at [`base_search_fuzzy`](https://github.com/OCA/server-tools/tree/10.0/base_search_fuzzy). Not exactly what you're looking for I think, but implements the proper Trigram index handling so that the new `%` operator can be used.

**Comment by gdgellatly** [comment]
@lasley thanks, I kind of knew that module existed, just didn't know its name, and have been looking out for it everywhere.

**Comment by lasley** [comment]
Np - it's quite useful. Off-hand I know we at least use if for [e-commerce search](https://github.com/OCA/e-commerce/tree/10.0/website_sale_search_fuzzy)

**Comment by elgow** [comment]
@lasley Thanks for the pointer. As you say, it's not quite the search I'm looking for. For my purposes the default  `text @@ text` behavior is what's desired as my users are accustomed to a full-text search as provided by sqlite.  For now my patch code is probably the best option, so perhaps the advice from @gdgellatly to contribute it to OCA as the world's most minimal Odoo module is the way to go.

**Comment by lasley** [comment]
> to contribute it to OCA

IMO OCA is the best place for any new feature. Ping me when you submit the PR

> world's most minimal Odoo module

Meh I might have you beat there. [Gotta love glue modules](https://github.com/LasLabs/multi-company/tree/139040283346d7bc277672a302359fb1a33e1967/website_product_multi_company).

**Comment by gdgellatly** [comment]
@lasley I might have been rolling it myself for some time now https://twitter.com/ggellatly/status/478435233629339649 but I'll ditch that and work on this. Anyway I'm going to continue this over at server-tools repo.

**Comment by blaggacao** [comment]
@odony I think, if you could commit to raise this into some internal discussion, it would be adequate.

The title "sub standard search" of this issue point's it out quite precisely. It definitely constitutes an instance (or at some point will) of a competitive disadvantage.

Being strict on natural code evolution is surely a wise thing, but I bet (or bitterly hope :wink: ) that you have means, routines and policies in place to enable consistent and long lasting core improvements. It then comes down to priorization, which is, no doubt, editor's sole discretion (and sometimes also might depend on developers preferences).

It is absolutely true, that most of the target user group are meanwhile overwhelmingly familiar with google search and that this leaves an unpolished impression on Odoo, and CAN be a deal breaker.

The usability implications are rather huge. We all have seen those kind of users typing confusedly with their index fingers only at the speed of a european pond turtle. Maybe this kind of "inspirational issue", was just about what is needed to surface this on the current agenda?

And how many unintended clicks on quick create in the search drop down have we all seen? - Because of this (eg. an added unintended space at the end).

BTW, I'm also a big fan of the more curated approach!

**Comment by elgow** [comment]
@blaggacao Thank you for helping to impress upon @odony the the very high level of importance that end users place upon search functionality. My test users were quite literally both incredulous and disgusted when I explained how the Odoo text search works. They had never seen such a thing. 

Even more concerning than the failure to consider the perspective and needs of the users is the fact that my essentially trivial PR is rejected based on the Odoo [stable policy](https://github.com/odoo/odoo/wiki/Contributing#what-does-stable-mean). If you actually look at that policy, my PR violates only one of the 13 points, and that one is "No "improvement" (technical or functional) should be done in stable".  This rules out the possibility of PRs from the open-source developer base getting into the current version. Combine this with the fact that database migration to the next version is available only to paying customers and you end up with Odoo not actually being open-source, despite the claims on their website. Where is my incentive to release any code I write to enhance Odoo if I'll have to pay to be able to use it in the next version? 

Certainly Odoo needs to curate their codebase. That is why changes are suggested in a PR that must be vetted and pulled in by Odoo devs. A blanket policy of not taking PRs for the stable version and charging for upgrade to the next sends a clear message that open-source users should not bother contributing code. Is Odoo's in-house development resource so great that they can afford to do without open-source contributions? The Odoo website boasts of having 5400+ developers, but they actively discourage those developers from contributing to the core codebase. Is that the sensible course in competing with Oracle, SAP, Microsoft, etc.?

**Comment by blaggacao** [comment]
> sends a clear message that open-source users should not bother contributing code

I hear that message, too, and I beg a lot of partners hear it as well. If you decide to contribute, it's a professional marriage because you have an incentive to transfer your maintenance costs to Odoo, definitely not out of pure love (at least at the moment). But, hey, probably we are in a pendulum reaction out of past experiences or it's pre-release schedule for v11...

Generally, and on the long term, feedback will be heard and transformed into momentum at some point. Some implicit and intelligent agenda setting on behalf of the user voice is always a good idea, though.

**Comment by Yenthe666** [comment]
Hi guys,

Just wanted to throw in my five cents. Not all of you may know me but some do. I do not work for Odoo but I have been actively contributing and managing bugs for Odoo. Ever since I started doing this I've been trying to grow my reach and improve things beyond my decision level or reach.

This october I will be at Odoo S.A. to talk about the community and to improve the relation/collaboration with the community (with odony). I can't make any promisses but I'll try to do my best to get things like this on the table in order to improve collaboration.

Regards,
Yenthe

**Comment by odony** [comment]
@blaggacao we do have a backlog task for developing a FTS system in Odoo, indeed. It's still in the inception phase though, pretty much for the same reasons exposed above: we need to design a good Odoo integration. Any suggestions on the integration are welcome, which is why I had not closed the issue (sorry if that was unclear)

We're not just a high level DSL for querying PostgreSQL, though, we have a framework, a UI, an integrated set of business features, and usability is a key focus. We often prefer to keep a feature outside of the scope, at least temporarily, rather than risking to confuse users, which can be much harder than it seems. On the other hand our framework is meant to be easy to extend, so adding the features in third-party extensions isn't usually very difficult. That's the trade-off.

I'm not saying it's perfect, or that all the decisions we take are always good, obviously, just explaining what drives the decisions in terms of new features.

**Comment by blaggacao** [comment]
FTS on backlog is indeed great news, thanks. Something Uservoice-like ranking would perspectively help to keep discussions organized and transparent and keep the spirit of open source up. But that's another topic of it's own. :)

On integrations I had a look at the OCA module for some ideas, but I'm not specially an expert on the topic. An easy way to write operators (AND OR XOR) to concat search would be something near-topic on this and very useful for power users.

**Comment by Yenthe666** [comment]
@odony has there been looked at any systems and if so which ones? Perhaps it is better to create a separate topic for this which we label framework + wishlist. The discussion can be held there and everybody can jump in. What do you think?

**Comment by elgow** [comment]
@odony The problem with creating an addon for FTS is that it reaches too deep into the core framework. The list of operators at _odoo/osv/expression.py:141_ constrains DB queries at the lowest level. In my own plugin I include the code shown in https://github.com/odoo/odoo/issues/19208#issuecomment-326671592 to modify the operators list inside the core module. I think that is not something an addon is supposed to do, so asking for an addon to provide FTS is really asking for a rogue addon.

I'm glad that Odoo is at least thinking about FTS. Sadly since Odoo 11 is about to become the stable version it would seem that we are at least a year away from getting an official FTS for Odoo. I think that the Odoo team needs to take a reality check on the importance of search and on the expectations that typical users have for it. Good, intuitive search functionality is simply part of the table stakes for any web application these days.  I found that when I tried to explain what they needed to do to use the Odoo `ilike` based text search my users looked at me like I'd asked them to use the MSDOS command line. The Odoo text search is far below the standard expected by _anyone_ who has ever used a web browser. I think that Odoo needs to recognize what a glaring flaw in the product the current text search is.

**Comment by elgow** [comment]
@blaggacao One interesting thing about the `@@` FTS operator solution is that it does provide a reasonably effective way to do AND and OR searches. Words entered in a single search entry are treated as AND by the Postgresql FTS because order and intervening words don't matter. Any additional text search strings get treated by Odoo as OR, so just entering separate search strings gets you that. This is less explicit than having the users enter AND or OR, but it's easy enough to understand and do that I'm not getting complaints about it.
