### ISSUE TITLE
[UX USER STORY] account: Alert on moving liquidity accounts on simple moves

### ISSUE THREAD

**Issue by blaggacao** [odoo/odoo#19221]
## User Story

- AFAIK: All maintained versions.
- Based on a real user story.
- Male user, treasure, age of 68.
- Family SME, 60 employees.

As a treasurer, new to Odoo, and doing my work on importing the fist payments, I am (possibly) accustomed from other (less advanced) accounting software to just do accounting entries in order to audit and keep in sync my liquidity accounts (bank and cash).

I'm still not aware of Odoo's world class reconciliation features, so I just start to move payments directly from the account move view, directly affecting accounts.

I then upload my first bank statement and am completely shocked by the (supposedly) missing functionality of Odoo to map what I just moved to the liquidity account with what is on my bank statement.

I then realize (thanks to Odoo support, or my implementation partner), that the expected mapping is a feature only available when a payment has been done via the different payment models.

I curse myself and will set for a fix, only to see that the journal items once created by error cannot be canceled (of course, this is expected, but in this moment I wished to be able to cancel them). I then realize the 'account_cancel' module and how to use it, only to realize that even though I've set it up correctly, I cannot cancel the moves, because there is an additional internal check which guards over the move sequence.

I then revert the moves as indicated. And would wish to proceed with my bank statement reconciliation, but what a unpleasant surprise: Now I'll find the originally wrong move + its reverting counter party in the receivable/payable account.

I got completely confused and refuse to work further with Odoo. This first impression, was too unpleasent. And I'm responsible for the damn money of this company. I turn back to my old accounting system. As I'm probably the most important person after my boss, my boss has no other means than to abandon the project.

**End of story.**

## Analysis

This real user story has an unfortunate concatenation of UX bugs which typically appear in conjunction and in sum could cause severe impacts on user acceptance.

What happened is that the first UX bug A (able to move liquidity accounts in move views without warning) lead to the necessity (via some odissea) to reverse moves which is a process that reveals a second usability bug B (not reconciling automatically the amls on reconcilable accounts of reverse moves), which then is to be detected as an unexpected side effect in a principally unrelated operation (reconciliation), that could have been executed even by a different person.

## Solution

The end of the story could have been changed by two simple improvements:

- Require an informative warning + confirmation, if a user tries to touch liquidity accounts directly via the Account Moves menu.
- Automatically reconcile amls of reverse moves with their originators, if originator and reversing move "take place" in a reconcilable account.

@qdp-odoo What do you think? It's based on a real world user story in a family SME with 60 employees. I think, it should not happen again...

**Comment by blaggacao** [comment]
Linked Report for Reported Bug B #19222

**Comment by nhomar** [comment]
Well.

I can show you no less than 10 user stories that say exactly the oposite on this regard.

Not only in Odoo (any software) if a customer does not pass the very first steps of train themselves then it is impossible to help them.

I solve this with a lot of training - training - training, if the most important person in a company after the boss, does not understand the importance of "Business Process, Training and testing" then nobody under him will, and then this is a lost battle even with the best of the intentions.

If you lost liquidity accounts manually, then you must know the manual conciliation process (base knowledge in odoo) if account cancel fails then we must fix account cancel (but this is not the case).

All this story is a normal story that I live a lot and never loss a project because of it, Which is the mindset to change?, simply: An accountant is an auditor "analyze account move" not a "Account move loader" (as older softwares).

End of story!

**Comment by qdp-odoo** [comment]
> Automatically reconcile amls of reverse moves with their originators, if originator and reversing move "take place" in a reconcilable account.
That's the case already since https://github.com/odoo/odoo/commit/7544c22d

> Require an informative warning + confirmation, if a user tries to touch liquidity accounts directly via the Account Moves menu.
That indeed may lead to some awkward situations but it is supposedly mitigated by some training or support at any point. I don't see that like a blocking point even if I admit it could be improved somehow.

So I read your story, and don't think we need to keep that "issue (?)"  open.
Thanks for sharing your experience

**Comment by blaggacao** [comment]
@nhomar I think you are right 😉 , although, I also think, that such a user story can give the full context of a very detailed, but valid, situation (age 68). The ultimate is usability excellence, I guess.

@qdp-odoo I can agree, especially with 7544c22 that big part of the combined adverse effect of a human error is mitigated. This makes the second point less adverse. It can be handled by training and support, indeed. I'm glad, though, you agree that it is not usability excellence.
