### ISSUE TITLE
Odoo 9: Move Snippet Box

### ISSUE THREAD

**Issue by auditum-sbl** [odoo/odoo#19266]
**Description:** 
If you only have one box in a section, you can´t move this box to other sections or positions, only when you duplicate them because you have two boxes in a section. 
In Odoo 10 it is possible.

**Video/Screenshot link (optional):**

**Odoo 10 Screenshot**
![odoo 10](https://user-images.githubusercontent.com/22189188/30058314-baf7ba50-923a-11e7-807f-8d662056451d.png)

**Odoo 9  Screenshot**
![odoo 9](https://user-images.githubusercontent.com/22189188/30058303-b29e171e-923a-11e7-9169-47fa2d537abf.png)

**Comment by Yenthe666** [comment]
Hi @auditum-sbl,

Thank you for your report.
V10 saw quite some improvements and changes, under which the web editor is also improved. This is simply something that was not in V9 but has been made for V10 (and upcoming V11).
I don't think there are any plans to backport these kind of improvements to V9 because this could cause bugs or issues in a stable version.
@Gorash up to you to decide I guess (cc @JKE-be).

Regards,
Yenthe

**Comment by auditum-sbl** [comment]
Hi @Yenthe666,
 
thank you for your answer. An update to Odoo10 will not be feasible for our enterprise-customer at the moment, so I guess we would have to fix the issue, if you will not do so. @gorash?
 
Kindly Regards,
Sarah

**Comment by Yenthe666** [comment]
Hi @auditum-sbl,

After a second check this would actually be against the stable policy. New features or backports of new features are not allowed in older versions. Sorry!

Regards,
Yenthe
