### ISSUE TITLE
[10.0]Product description field(AKA internal Note)  disappear from Form views

### ISSUE THREAD

**Issue by flotho** [odoo/odoo#19279]
The description field doesn't appear anymore in any view neither for template nor for product.
tested here : http://261223-10-0-80ca45.runbot8.odoo.com/web?debug=1#id=31&view_type=form&model=product.template&menu_id=424&action=280

Is it normal, what is the idea behind this?

regards

**Comment by Yenthe666** [comment]
Hi @flotho,

About which technical field are you talking exactly? Are you talking about one of these?
![image](https://user-images.githubusercontent.com/6352350/30148896-bff0d80e-93a5-11e7-98f9-6eb400a8ce72.png)

**Comment by flotho** [comment]
Hi,

I mean the one available in v8 :
![spectacle xl8418](https://user-images.githubusercontent.com/1043935/30232336-c560aa08-94ef-11e7-85a6-5d58e24d18cc.png)
The field still exist in v10 but is no more displayed

**Comment by Yenthe666** [comment]
Hmm, even though it is not used it still can't be removed as it would be against the stable guidelines (https://github.com/odoo/odoo/wiki/Contributing#what-does-stable-mean).
If this is still the case in the master it could be removed there I guess (cc @mart-e)

**Comment by flotho** [comment]
My point is more how to set an internal comment ofr a product for colleagues if there is no more description available?
What is the Odoo recommendation for this ?

**Comment by mart-e** [comment]
Hello,

It was indeed removed from the view at af9d21b379f1dd42e83dcfa164af489c9261542d
Actually, this one is a bit a special case. 
We have removed it because we no longer want to push its use. We did not remove it from the model (only from the view) because some of our users do use it. I think it is also used in the search of the ecommerce to have better search results.

For those who are migrating from previous versions or still need it, a customisation is needed. You can inherit the view to add the field back but we do not want to display it in standard.
