### ISSUE TITLE
Need to pass user's company context

### ISSUE THREAD

**Issue by oliverzgy** [odoo/odoo#19445]
https://github.com/odoo/odoo/blob/052bc3880534e45f168f396005e7cfc3edad0490/addons/account/models/partner.py#L208

tables, where_clause, where_params = self.env['account.move.line'].with_context(
            company_id=self.env.user.company_id.id)._query_get()

**Comment by Yenthe666** [comment]
Hi @oliverzgy,

Thank you for your report.
Please do add more information, context, details about why/how something should be changed so we have enough information. That is where the template is for 😉 
@mart-e if I understand this correctly the `partner.py` query does not look at the context (so, the company in this case) in order to get the `account.move.line` details. Would a PR be welcomed? Happy to make one.

Regards,
Yenthe

**Comment by mart-e** [comment]
Well before making a pull request, indeed say what does not work, how to reproduce, ...

**Comment by oliverzgy** [comment]
the code is there, please do read the code

https://github.com/odoo/odoo/blob/236a24de964d4fb4cdcab9bc2f43f29b2bbe47fe/addons/account/models/account_move.py#L1293

**Comment by oliverzgy** [comment]
The credit of a partner is specific to the company where the accounting journals are recorded with this partner. If not specify the company in the query, it would be a big issue in a multi-companies instance, not only one company might have business with this partner.

**Comment by pedrobaeza** [comment]
@oliverzgy please make the PR with the proposed solution to clarify what do you want to get.
