### ISSUE TITLE
Stripe API Invalid Key

### ISSUE THREAD

**Issue by performancem** [odoo/odoo#19468]
Impacted versions:

Odoo 10

Steps to reproduce:

Enter payment for Invoice via Account. The following message occurs:

Stripe: invalid reply received from provider, missing reference. Additional message: Invalid API Key provided: *alse None 

The same payment processes normally using ECommerce Checkout.

Current behavior:

Transaction fails.

Expected behavior:

Successful payment.

Video/Screenshot link (optional):
![stripe-error](https://user-images.githubusercontent.com/31965853/30444459-0fdad1fc-9951-11e7-927b-4f99a48d04e6.jpg)

**Comment by performancem** [comment]
I neglect to mention that the error is preceded by this error in the log file.

ValueError: invalid literal for int() with base 10: 'USD'

Thank you

**Comment by robindierckx** [comment]
+1

I managed to remove the issue by overwriting `addons/payment_stripe/static/src/js/stripe.js` with an earlier version.

The problem comes from this line (and maybe other lines as well) :
https://github.com/odoo/odoo/blob/808c0e5dde61027241ff59b1674b159067da0d7e/addons/payment_stripe/static/src/js/stripe.js#L70

As in earlier version, this line should get `currency_id` instead of `currency`. Despite the error caption, it has nothing to do with the api key.

**Comment by Yenthe666** [comment]
@nim-odoo could you have a look?

**Comment by rdeodoo** [comment]
Fix landed [here](https://github.com/odoo/odoo/commit/cca12fbb08626094c24a245c5bf54dad2696fae7)
Thank you for reporting this issue
