### ISSUE TITLE
Questions about extra crypto-related features (e.g. in the context of GDPR)

### ISSUE THREAD

**Issue by rosenvladimirov** [odoo/odoo#19583]
What is plans to integrate cryptography (EU-GDPR) in field object.
1. Connections to posgres to be by hostssl
2. Integrate in SQL-queries pgcrypto extentions
3. Make or read from remote keystore server pgp keys
possibility:
1. Add new parameter in fields char crypt.
2. Mark all fields with critical data as crypt.

**Comment by Yenthe666** [comment]
Hi @rosenvladimirov,

Thank you for this topic and I was actually wondering the same thing a few days ago.
@odony and @xmo-odoo could you guys please give an official statement about GDPR? It will become important in the future.

Regards,
Yenthe

**Comment by odony** [comment]
I'd like to make it clear Odoo (the software) is under no obligation under GDPR, because the data privacy regulation applies to organisations, not software. Odoo will be in a position to _help_ organisations with GDPR compliance, for example by more easily identifying, managing and protecting Personally Identifiable Data (PID) processed by an organisation.
Your points are generic encryption-related questions, which might be relevant under GDPR, not the other way around.

Odoo SA (the company) will have to be compliant with GDPR. However, it is my understanding so far that most of GDPR is comprised of common sense and best practices, so Odoo SA is already very close to being fully compliant (more info on our [Security](https://www.odoo.com/security) and [Privacy](https://www.odoo.com/privacy) pages.

Please pardon this digression, but I found the issue title a bit misleading, and as things stand, GDPR discussions are confusing enough.

**Comment by odony** [comment]
Now, about your specific questions:

1. This requires a rewrite of our DSN parsing, we plan to do that for a future version. In the meantime we recommend deploying with a local network link between Odoo and the DB (e.g. local unix socket), or to put communications in a separate, secure, network/VLAN.

2-5. Implementing crypto in the business data itself would have a big impact:
 - It may partially or entirely block search/indexing features. As a CRM system includes a lot of PID, this sort of change could cripple the system
 - It would cause performance penalties
 - If key management and the whole crypto layer is not done *right*, the data might be more at risk than if it was in cleartext (data loss risk), or just as insecure, bringing all the downsides with no advantages, _and_ a false sense of security. (e.g. GDPR tells you that you don't need to disclose a data breach if the data was encrypted. Well, that really depends on whether the encryption was actually done right, and the keys are still safe. Sadly, GDPR seems to overlook the fact that it's very easy to get your encryption wrong)
 - etc.

More generally, it's always a great risk to "roll your own crypto".
In the context of password hashing, it was rather straightforward to use a battle-tested lib like `passlib`, for one-shot hashing (and even that isn't as simple as it seems!). It would be quite a different story to manage the reversible encryption of entire database columns, while preserving some desirable properties of the data (like searchability, indexes, no data loss, etc.), and securely handling the keys.

Going even further to end-to-end encryption would be very nice, but the trade-offs would be enormous for a flexible multi-user management software like Odoo.

So at this point, it's really not clear that we should go in the direction of live PID encryption.

It might be a different story for medical PID, where privacy concerns are much higher, and security protocols more established, with accepted trade-offs. But that's mostly out of scope of the Odoo framework at this point.

OTOH, we've been thinking about providing a way to encrypt the filestore at rest, with techniques inspired by [restic](https://github.com/restic/restic) and similar file-level encryption schemes. It lives outside the database, so it does not have the usual searchability/indexing/performance requirements. This could also enable easy incremental encrypted backups: just encrypt your database dumps and put them next to your encrypted filestore in the area of the filesystem that is included in your remote backups, and you can have cheap incremental _encrypted_ backups.
And because encrypting data in-transit is trivial, this only leaves you with the problem of securing your live production database. The data will need to be decrypted server-side at some point anyway (for the kind of usage done with Odoo), so that production server ought to be secure anyhow.

Those were just random thoughts on the encryption topic. Sorry if you were looking for more specific or definitive answers :innocent:, I guess we're not there yet.

**Comment by odony** [comment]
Of course you're always free to implement encrypted columns with pgcrypto or other tools yourself. Recent framework improvements have made this even easier, for example serialized/sparse fields are now implemented in a separate module: [base_sparse_field](https://github.com/odoo/odoo/tree/master/addons/base_sparse_field).
This way if you get the encryption wrong, you'll know who you can blame ;-)

**Comment by rosenvladimirov** [comment]
The essence of the retention of personal data is that it is impossible to identify the subject. In other words, not nessery all of the information about the subject must be encrypted, only that which is nodal.
As an example I can give:
The partner can be intedificated through the fields:
1. ID (WAT, EIC, ....) indentification codes obtained upon registration in the relevant service.
2. The names
3. Address
the latter also have of index codes.
In my opinion, naming names is unnecessary because the name without the ID code is not sensitive personal data.
If only the encryption fields are sufficient, it will suffice as the encryption between all interlocking elements will break.
In terms of data entry. At the moment, the odoo engine allows to search in any field based on the constructor's query to access to the base (sql query). There is no single model for creating an indexable key that can be manipulated like as releted database indexing. As an example of a drawback to the current issue is the need to assemble an index at a POS that does not correspond to the nucleus in any way. I have tried to avoid this problem with one of the modules, but this can not be achieved at 100% because of the need for feedback.
I raised this discussion because I think it is not a problem for the organization how to manipulate its databases but rather a problem with the tools that manage those databases.
Running on the same machine the tool and the base of the creacy of security is a very serious mistake. In principle, the basic rule of security is to create different points for storing and managing critical information. This is because if the hardware is stolen, the thief will also have the data and the tool for manipulating them.
I would be glad to make an effort to seek a solution to this and other such cases before problems arise with them.

**Comment by odony** [comment]
For the record, point 1 (support for `hostssl` connection to the database backend) has been included in Odoo 11, via the new config option `db_sslmode`. See `odoo-bin --help`.

**Comment by rosenvladimirov** [comment]
I found i odoo problems linked indirectly with GDPR. Security control on session is not in high level. Problem: in odoo not have time based control for security like as RADIUS server. Meaby is better to add module for intgrations with freeipa server (not ldap).

**Comment by mart-e** [comment]
Closing as Olivier answered the questions

**Comment by cvinh** [comment]
Hello @odony is there any updated roadmap about that subject ? What would you recommand in 2024 for sensitive application (medical or citizenship fiscality) ?
It would be great if you may point out some advice.
Thanks in advance
Best regards
