### ISSUE TITLE
Priceliste order ecommerce

### ISSUE THREAD

**Issue by JKE-be** [odoo/odoo#19595]
See comment in: https://github.com/odoo/odoo/commit/eb90e1113475c02423d94943cb0204c39fc7be7c#commitcomment-24434928

**Comment by JKE-be** [comment]
@mlaitinen 

Hello

Not sure,

case 1: If you specify a specific pricelist to the partner, it is the first selected.

case 2: If not, that will check to find which pricelist is available for your country (based on country's partner or geoip). If you have 2 pricelists (for 2 currencies, or 2 prices according to the region), you can here choose which country use which pricelist e.g.

If you don't set a country group on your price list, it is (IMHO, let me know if you have another case)) because you just have one price list to use by default for all users (case 3), and other(s) pricelist(s) are specific and will be used for a restricted list of partner (you will match the case 1).

case 3: A global pricelist and several specifics, in this case, you just need to drag the global pricelist at the first one in the list (without country group). And its wrong, that will be not a "random pick one", that will be always the first one (based on sequence) that will be returned !

Case 4: The last one case, is only one fallback, if you don't have pricelist without countries and that you don't match a pricelist for the current country, we return the first one based on the sequence again and not randomly?

**Comment by mlaitinen** [comment]
You're _almost_ correct. Just the case 1 isn't entirely correct.

See https://github.com/odoo/odoo/blob/44276dfdc3b69cd9b834bfa7037671558e6d0078/odoo/addons/base/res/ir_property.py#L221 which is called in here https://github.com/odoo/odoo/blob/44276dfdc3b69cd9b834bfa7037671558e6d0078/addons/product/models/res_partner.py#L35

So, my point is that if you select the default pricelist for the partner, the partner will not have its own explicitly created `ir.property` record, because Odoo only creates a property record if it differs from the default. And when there's no dedicated `ir.property` record, Odoo will go through the following steps:

1. Check if the record has an `ir.property` record for `property_product_pricelist`. (it doesn't)
1. Check if there's a pricelist with a matching country. (no pricelists)
1. Check if there are pricelists WITHOUT a country group (**<- this one gets selected** and it just randomly picks any pricelist from all the pricelists that doesn't have a country group defined)
1. Check if the default pricelist is defined (this should be selected, but it's ignored)
1. Take the first whichever pricelist you find (also ignored)

What happened with our own Odoo 10 installation was that I couldn't select the default pricelist (=public pricelist) for a new partner because even though it was stored correctly by the inverse method, the compute method of `res.partner.property_product_pricelist` would always return the wrong value (=a special pricelist for our friend companies) because that was the first pricelist without a country group it could find. Neither of our pricelists have country groups defined and we don't have a reason to do so, but I was able to create a workaround by creating a "dummy" empty country group for that special pricelist. But then again, we would have to have those dummy country groups for each non-default pricelists.

**Comment by JKE-be** [comment]
Yes one thing that is ambigous and not clear, is that:
   - the default price list should be always the first in the list (ordered by sequence).
   - All pricelist should have at least 1 country_group or None...

In this case you will not get your 'friends pricelist'.
