### ISSUE TITLE
[v8] Sale Reference Not going anywhere.

### ISSUE THREAD

**Issue by richard-willdooit** [odoo/odoo#1963]
Minor change.  The reference on a sale.order does not make it to the generated invoice.

**Comment by Yenthe666** [comment]
Hi @richard-willdooit,

Thank you for your report.
I've just tested this on the latest Odoo V8 and it has been fixed in the meanwhile. The SO:
![image](https://user-images.githubusercontent.com/6352350/27580269-60a864f6-5b2a-11e7-89f3-1f13f52bfcb0.png)

The invoice, made from the SO:
![image](https://user-images.githubusercontent.com/6352350/27580319-81ed9db6-5b2a-11e7-9eb5-e6fef3a84efa.png)

I'm closing this issue as it has been solved.

Regards,
Yenthe
