### ISSUE TITLE
8.0 ORM is very slow performing read vs direct sql query

### ISSUE THREAD

**Issue by aliomattux** [odoo/odoo#19660]
Impacted versions:
8.0. I know this is an older version, but assume that some of the behavior is consistent in the application.
Steps to reproduce:
Test 1
Database with 50,000 products. No customizations
Perform a read on a couple of product text fields.
Result is over 1 minute to return data.
Perform the same query directly in the database returns in 2 seconds

Test 2
Perform a read on any stock field, qty_available, virtual_available, etc. Just 1 field only
Read operation takes several minutes to return

Perform a direct database query on the stock_quant table. Query returns in under 4 seconds.

All of the documentation in Odoo and quotes from Olivier Dony suggest never using a direct sql query and always using the ORM, however, the ORM is unusably slow to run reports on medium sized datasets, taking 100x more to produce the same dataset that could be run directly on the database.

My conclusion is that this behavior is caused due to the ORM looping over data and performing calculations on each record which is exponentially slower.

An example of using the UI purely with no code and no customization, with a database of 50k products and inventory locations, go the warehouse > run inventory report. It takes several minutes to produce, extremely slow

Using the database directly appears to be the  best viable solution to creating enterprise reports in a timely fashion

**Comment by Yenthe666** [comment]
Hi @aliomattux,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.
P.S: You will notice that performance has increased quite a lot in Odoo 11. Big performance bugs or problems are usually fixed in the newest (or master) version.

Regards,
Yenthe

**Comment by hamedsafari** [comment]
sd
