### ISSUE TITLE
Payment  is not  being set to reconcile state in any circumstances

### ISSUE THREAD

**Issue by bharatkhandelwal** [odoo/odoo#19681]
![paymentstateissue](https://user-images.githubusercontent.com/11583449/30803930-1f00b1cc-a209-11e7-908c-b0001a54cc09.png)

![vendorinovice](https://user-images.githubusercontent.com/11583449/30803925-17fa5b08-a209-11e7-84dd-a7adbb2eb63c.png)

Impacted versions: odoo-10.0(Enterprise) and odoo -11.0(Enterprise)

Steps to reproduce:  (1) Create payment and select payment type send money and select  payment journal bank or cash
(2) payment confirm  and after create invoice related payment partner id and after invoice validated and add payment then invoice is paid state and related payment  is not being set to reconcile
 
Current behavior: payment state is set  posted 

Expected behavior: Payment is set to reconcile state 

Video/Screenshot link (optional):

**Comment by murtadakarjikar** [comment]
There are two types of reconciliations in Odoo – 

One is payment reconciliation – This happens when a payment is processed and the vendor or customer account is reconciled. This reconciliation ID can be seen when we drill down in the payment entry eg. A223 etc. 

Second is the accounting term generally termed as Bank Reconciliation. The issue you are reporting is this type of reconciliation. When you create a bank reconciliation statement for that journal, reconcile the payment, then the status will be set to Reconciled state. 
See the snapshot below. 

 

![image](https://user-images.githubusercontent.com/21281223/31229672-5ed354fa-a996-11e7-9caf-8352fc994ae1.png)

**Comment by bharatkhandelwal** [comment]
@murtadakarjikar 

I  have  checked as per step and i clarified  its not bug . thanks for help and clarification
