### ISSUE TITLE
Master - Location Barcode Report only prints last four locations

### ISSUE THREAD

**Issue by gdgellatly** [odoo/odoo#19698]
Impacted versions: Master

Steps to reproduce:
Login to runbot as Admin
Go to Inventory Locations
Select all locations from default view
Print Location Barcodes

Current behavior:
Only the last 4 print.

Expected behavior:
They all print

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Hi @gdgellatly,

Thank you for your report.
This is indeed bugged:
![image](https://user-images.githubusercontent.com/6352350/31057034-55c5e812-a6dc-11e7-8100-416bf445a63b.png)
@jco-odoo could you look into this? It seems to render only one page.

**Comment by pimodoo** [comment]
@KangOl It's up to you, problem since saas-14

**Comment by qsm-odoo** [comment]
@KangOl Any reason you assigned this issue to me ?

**Comment by Yenthe666** [comment]
Hmm nobody seems to like this issue. 😉

**Comment by KangOl** [comment]
It's look like a css problem as each `page` of the report are rendered at the same position (absolute), overwriting previous one.

By adding the following snippet in the report qweb view, the html report is ok, but not the pdf version.
```css
.article { height: 100%; }
.page { height: 100%; position: relative;}
```
I don't know if it's safe to have this for all reports.

Note: bug present since saas~14

**Comment by nle-odoo** [comment]
hi,

this should be solved in saas-14 with https://github.com/odoo/odoo/commit/ef2646ae9d9 and will be fixed soon.
