### ISSUE TITLE
[Master][OE] Accounting : Partner ledger report

### ISSUE THREAD

**Issue by fmdl** [odoo/odoo#19781]
Impacted versions:
Master entreprise

**Steps to reproduce:**
Create an invoice A in 2017, register a payement in 2017.
Create an invoice B in 2017, register a payement in 2018.
Select "Show Only Unreconcilied Entry"
Select year 2017.

Invoice A and B are not show (because they are reconcillied).

**Issue :**
If you need to know wich invoice is not reconcillied in 2017 (you have select 2017), the invoice B is considered like reconcilied in 2017, but the payment is in 2018. In 2017 the invoice B is not reconcillied.
For the KPI of the company it is important for the accountant to know what is reconcilied or not at date (not for every time).

**Expected behavior:**
Solution 1:
Add a symbol near the matching to say that is not reconcillied in select date.

Solution 2:
Add a new filter : "Show Only unreconcillied Entry at selected Date".

Regards.

**Comment by fmdl** [comment]
@qdp-odoo

**Comment by qdp-odoo** [comment]
I'm not sure. It seems legit to keep this as it is now, since
* the partner ledger report is a "date-range report" (needs a "date from" and a "date to") and I believe it has sense to keep it like that
* you have an option to include reconciled entries or not ("reconciled nowadays", I mean)
* you have the aged partner balance that gives you the information on what was reconciled at a given date

Is there anyone else that is shocked by this behavior? If yes, let me know and we might consider improving that in a next version.
