### ISSUE TITLE
@api.onchange always expect res to be dictionary

### ISSUE THREAD

**Issue by mohamedhagag** [odoo/odoo#19823]
https://github.com/odoo/odoo/blob/682b2c0985463a740b5126b06858339af0297205/odoo/models.py#L5372

@odony 

This causes an error with functions that return a list - error code below:
File "odoo/odoo/models.py", line 5372, in process
    if res.get('value'):
AttributeError: 'list' object has no attribute 'get'

the function that gives this error is like below:
@api.onchange('field_A','field_B')
def my_func(self):
   list_ids = []
   list.append(3)
   return list_ids

the same function is working on v8 fine .

**Comment by gdgellatly** [comment]
@mohamedhagag onchange has expected to return a dictionary since at least v5 (or None in new API).  If its working to return a list on v8 then you might be best to raise a bug on v8 saying that onchange allows you to return a list as it shouldn't.

https://www.odoo.com/documentation/10.0/reference/orm.html#module-odoo.api
https://www.odoo.com/documentation/8.0/reference/orm.html#module-odoo.api

"The method may return a dictionary for changing field domains and pop up a warning message, like in the old API"

**Comment by mohamedhagag** [comment]
@gdgellatly  Thanks.

**Comment by adnanadam10** [comment]
@gdgellatly  i have same problem 
the thing is i want to migrate code writing in v8 to v12

**Comment by gdgellatly** [comment]
You need to ensure that onchanges return a dictionary in the format prescribed in the api.  I have no idea why you would want to return anything else anyway but I can almost guarantee the code is incorrectly conceived.  You will need to refactor that part.

**Comment by adnanadam10** [comment]
my method dosnt return anything as you mention above.but still give the
error when I  click on create button ,server error.on the terminal the
error as I post.
even though the form is opened.

**Comment by adekock11** [comment]
I had a similar problem and it was because I declared @api.one with an @api.onchange. I removed the @api.one and everything worked fine.
