### ISSUE TITLE
open mail alerts

### ISSUE THREAD

**Issue by roccocesetti** [odoo/odoo#19832]
Impacted versions:8.0

Steps to reproduce:Send emal mass-mailing 

Current behavior:
It does not indicate how many mails have been opened

Expected behavior:
odoo should indicate how many mails have been opened
Video/Screenshot link (optional):
![schermata del 2017-10-02 11 52 24](https://user-images.githubusercontent.com/4387127/31071940-4391e63e-a766-11e7-8f2d-ed887e98b606.png)

**Comment by Yenthe666** [comment]
Hi @roccocesetti,

Thank you for your report.
This functionality does work fine though. The reason that this is not working for you is because you have multiple Odoo databases and no database filter or anything. Because of this Odoo cannot know for which database the openings / clicks are and it cannot keep track of it. Have a look at https://www.odoo.com/documentation/10.0/setup/deploy.html for example.

Regards,
Yenthe

**Comment by roccocesetti** [comment]
thank you very much
