### ISSUE TITLE
Some mandatory informations missing on invoices from french company (l10n_fr)

### ISSUE THREAD

**Issue by zeroheure** [odoo/odoo#19876]
Impacted versions: all

According to french law , invoices should obey to strict rules :

- Total including tax must be labeled at least "Total TTC"
- Companies not using VAT (exo-0 tax) must include "TVA non applicable, article 293 B du Code général des impôts"

Reference
https://www.service-public.fr/professionnels-entreprises/vosdroits/F31808
See also https://www.cabinet-antoine.fr/spip.php?article138 for clarification

Steps to reproduce: set tax code exo-0 on products, create an invoice.

Current behavior: invoice don't display "TVA non applicable,  etc." Total doesn't mention "TTC" 

Expected behavior: invoices automaticaly display "TVA non applicable,  etc." if exo-0 is used, Total priinted as "Total TTC"

**Comment by Yenthe666** [comment]
@qdp-odoo and @lap-odoo this is relevant for you two.

**Comment by lap-odoo** [comment]
@zeroheure Hi, I've checked the text. It says that the total TTC must appear on the invoice (and it's well the case) but not that it should be labelled as such. But if you want to do it it can be achieved easily by changing the translations for the invoices report. 

Regarding the exo-0 taxes, I suggest you to create a fiscal position for this so that you can add the mandatory text in the fiscal position to make it appear on the invoice.

**Comment by zeroheure** [comment]
@lap-odoo Hi, thanks for the explanation, I should have understand this myself.
