### ISSUE TITLE
Installation Guide Odoo 11

### ISSUE THREAD

**Issue by F3000** [odoo/odoo#19935]
I search a installation guide for version 11 on CentOS . 

Can somebody help me ?

**Comment by Yenthe666** [comment]
Hi @F3000,

You can find the official installation guides at https://www.odoo.com/documentation/10.0/setup/install.html

Regards,
Yenthe

**Comment by F3000** [comment]
That is for version 10 . 11 is a little bit different . There is no repo to add

**Comment by Yenthe666** [comment]
True, as you'd need Python 3 support too. I'm afraid the 11.0 docs and guides are not yet released at the moment. Alternatively if you're fine with running Odoo on Ubuntu instead of centOS I have an installation script for Ubuntu 16.04 at https://github.com/Yenthe666/InstallScript/blob/11.0/odoo_install.sh
If you really need help I'd suggest you to ask this on the official help forums (help.odoo.com)

Regards,
Yenthe

**Comment by F3000** [comment]
Thanks for that :) 

Ubuntu is no option for me because the company use CentOS on all servers .

Did you know a date when you will publish the new docs ?

**Comment by Yenthe666** [comment]
Hmm I don't, sorry.
@mart-e as you usually fix this, do you have any idea how long it'll take or what the progress it?

**Comment by AlexanderIgnacz** [comment]
@F3000 , How did you install python3 on CentOS?
Is python3.6 ok too?

**Comment by AlexanderIgnacz** [comment]
@Yenthe666 , which OS should I refer for CentOS on installation guide?
I'm not able to find CentOS or yum part.

**Comment by F3000** [comment]
Yes . Minimum is 3.5 . 



Von meinem iPhone gesendet
