### ISSUE TITLE
HR Expenses record

### ISSUE THREAD

**Issue by fouasha** [odoo/odoo#19957]
Impacted versions:10

Steps to reproduce:
1-create expense to submit.
2-save.
3-edit and change employee.
Current behavior:
The expense disappear 

Expected behavior:
Change the employee

**Comment by Yenthe666** [comment]
Hi @fouasha,

This is desired behaviour. You're simply not seeing the expenses since they do not belong to you or you do not have enough rights. You can test this by creating an expensive for another user, clicking save, clicking edit and then changing it to your name. You'll then see it pop up under your expenses, so this proves there is no problem.

Regards,
Yenthe

**Comment by fouasha** [comment]
Hi @Yenthe666 

Kindly be noted that the user I was testing with was that admin user and no filter was used.
The same issue occurred on 11 too.

**Comment by Yenthe666** [comment]
@fouasha,

Yes this happens to any user, as you'll only see your own reports from that screen.
