### ISSUE TITLE
[11.0] Traceback on duplicating user

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#20002]
Impacted versions: 11e

Steps to reproduce: Go to[http://269855-11-0-0dd370.runbot8.odoo.com] http://269855-11-0-0dd370.runbot8.odoo.com --> Users --> Duplicate any user

Current behavior: Throws traceback 
![duplicate_user](https://user-images.githubusercontent.com/16624719/31377510-e502f746-adc5-11e7-9eb5-e10f8620ab34.png)

Expected behavior: Should duplicate user

Video/Screenshot link (optional): [https://prnt.sc/gvizhb](https://prnt.sc/gvizhb)

**Comment by Yenthe666** [comment]
Hmm there seems to be more off here. Simply clicking on create:
![image](https://user-images.githubusercontent.com/6352350/31378317-2ba51668-adab-11e7-9c92-44a08627edcb.png)
@mart-e for you 😉

**Comment by mart-e** [comment]
Ok, next question : why do you want to duplicate a user? 😕  While it seems like a strange idea, it should nevertheless work.

However, testing on a runbot is always tricky because many people do a lot of testing operation and you got all possible modules while some are not compatible.

I will however reject your issue without additional information. In your runbot example, it seems some people were heavy on the customization. It seems that taxcloud was uninstalled and some fields are remaining. However testing on a new runbot and removing taxcloud does not trigger the error.

Please try on a fresh database where you can give all the tests to reproduce, preferable starting with base instead on all modules.

**Comment by Yenthe666** [comment]
Both cases work on the newest runbot that where just generated. 😉
