### ISSUE TITLE
[11.0] Account Report Hierarchy menu

### ISSUE THREAD

**Issue by milanpatel1519** [odoo/odoo#20079]
Impacted versions: 11.0

Steps to reproduce: Invoicing -> Configuration -> Financial Reports -> Account Report Hierarchy menu

Current behavior: Opening form view

Expected behavior: Has to open Tree view

Video/Screenshot link (optional):

![account_report](https://user-images.githubusercontent.com/21196280/31482011-ddfafa5a-af43-11e7-8ae2-333c1046791d.png)

**Comment by Yenthe666** [comment]
@qdp-odoo could you check & give feedback?

**Comment by qdp-odoo** [comment]
not an Odoo module.

**Comment by milanpatel1519** [comment]
How come it's not an Odoo module.
It's in **account** module by **Odoo S.A.**.

Check Link: https://github.com/odoo/odoo/blob/11.0/addons/account/views/account_view.xml#L2192-L2214

**Comment by qdp-odoo** [comment]
ok, my bad: I didn't even know there was a way to get this old menuitem back since it should have been removed given that the accounting app is not in community anymore.

Moreover, the hierarchical tree view has been removed since saas-16 and this menuitem's purpose is gone with it. "Fixed" by the revision https://github.com/odoo/odoo/commit/8c8af672dd10abcc13beb4e91790b63c796a8b03 though

**Comment by davidtranhp** [comment]
Same situation with hr_payroll:
1. Activate Developer mode
2. Navigate to Payroll > Configuration > Salary Rule Categories Hierarchy
It is expected to see a hierarchy like what in the previous Odoo versions, instead of a form view

**Comment by qdp-odoo** [comment]
second problem, reported by @davidtranhp , "fixed" in v11.0 at revision https://github.com/odoo/odoo/commit/7bd16940087ed4cdae35c86c03a6733262734cea
