### ISSUE TITLE
Changed Search contexts are ignored by dependent views

### ISSUE THREAD

**Issue by gdgellatly** [odoo/odoo#20071]
Impacted versions: since at least 10, maybe as early as 8.0.  Definitely worked as expected in 7.0.

@ged-odoo I noticed this a long time ago, but tbh it was at a time when Odoo was less than responsive to issues so I never reported it, but rather just left it as a known issue in an OCA module that fixed it, but I just came across it again and seeing we want a rock solid client I'll report now.

Steps to reproduce:
You just need any view in which the search view is supposed to set a context.

In runbot - enable Variants and Pricelists.
Go to Product Variants
Select a pricelist.

Current behavior:
Nada
Expected behavior:
The tree view changes to show the price from the pricelist.

Note the opposite is also true - if you open a view with a default filter containing a context and remove it, the context remains.

Now why I think this is important, is that often we wish to change behaviour based on a passed context.  Obviously showing pricing is one example (although this was in itself a workaround to a performance issue in v6).  But equally we might want to restrict the default search of a field in a form, control whether something is editable, or a o2m readonly etc.  Believe me, if it works it is really powerful, as it allows the user to dynamically define context based on the task they are doing.

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/5093264/31474466-7d46e804-af57-11e7-9c73-8c82a025bf1d.png)
![image](https://user-images.githubusercontent.com/5093264/31474490-9e784662-af57-11e7-98fb-9e9a2ebae6b0.png)
![image](https://user-images.githubusercontent.com/5093264/31474563-188debfa-af58-11e7-80e5-0fbd78566012.png)

**Comment by gdgellatly** [comment]
#16094 I lie I did report it before at least once.

**Comment by ged-odoo** [comment]
@gdgellatly This looks indeed useful.  However, I just tested as you suggested, and I can see that the webclient actually send the pricelist key ('usd' or 'eur' in my test) in the context of the search_read (when reloading). So, in this case, it seems that the problem is actually in the business code for product.product, which does not take the key into account, when computing the value of lst_price.  For this exact situation, I think that the web client is doing its job.

Do you agree with that?

**Comment by gdgellatly** [comment]
@ged-odoo don't worry about the code, thats not important here.  

Worry about the fact that a context key is set and its purpose is to make a column visible, but the column remains invisible.  Some detail on this particular view is their are two price fields.

list price and pricelist price.  When you choose a pricelist, the price column should become visible.

To see it working properly, you could always try v7 :)

**Comment by ged-odoo** [comment]
ooh i see

**Comment by ged-odoo** [comment]
When we rewrote the views, we kind of assumed that the invisible attribute (not the modifier) was static. Then, we had to make sure it is evaluated, because it can actually depends on the context. But we did not think of updating its value when the context changes. 

This is indeed a bug, but since it was here for a long time, I will assume that this is not urgent. I added it to our internal list of bugs to process. Hopefully should be done sometimes in the next few weeks

**Comment by gdgellatly** [comment]
@ged-odoo at your leisure, funnily enough it doesn't solve my actual issue, which was trying to get a context dependent editable flag on a tree view, essentially something like this

```xml
<field name="order_line" editable="not context.get('advanced_edit_mode')">
```

But I can workaround with two menu entries.
