### ISSUE TITLE
Scrapping unavailable for basic users

### ISSUE THREAD

**Issue by adrien3d** [odoo/odoo#20125]
Impacted versions: 10.0-20170207 (Community Edition)

Steps to reproduce: Log-in as a basic user, go to inventory and go to scrap, there is no button to create a scrap button.
Or go in the Initial demand tab in Receipt, delivery order, or Internal transfer, no way to scrap a product.

Current behavior: Impossible to scrap a product for a basic user

Expected behavior: Let the same behaviour to the basic user, as the one for the admin

Video/Screenshot link (optional):
<img width="1195" alt="capture d ecran 2017-10-12 a 23 37 30" src="https://user-images.githubusercontent.com/3111324/31533592-4fa8a0c6-aff3-11e7-87e9-91c880e5c171.png">

**Comment by Yenthe666** [comment]
@jco-odoo was this done on purpose and if so, why?

**Comment by pimodoo** [comment]
Hello,

We have tested on our side and we are able to create scrap from picking and from scrap views (see screenshots attached). A picking must be in state done to allow scrap.

It also seems that your odoo version has not been update since 7th februrary 2017 and your bug has maybe been fixed since.

Best regards
![scrap odoo 3](https://user-images.githubusercontent.com/20767708/31897949-23c982cc-b818-11e7-95bc-4499a2e87ffb.png)
![scrap odoo 2](https://user-images.githubusercontent.com/20767708/31897951-23f35b92-b818-11e7-98be-022fde760e93.png)
![scrap odoo 1](https://user-images.githubusercontent.com/20767708/31897953-2418380e-b818-11e7-8b19-80df5387e6c5.png)
