### ISSUE TITLE
V10- Theme ZAP - missing dependecy theme_treehouse

### ISSUE THREAD

**Issue by sharkutz** [odoo/odoo#20129]
Impacted versions: V10

Steps to reproduce: 
1.Buy theme ZAP from odoo online
2. download 
3. install

Current behavior:
Error message: It depens on theme_treehouse that is not present in your system

Expected behavior:
Dependencies should be available in the ZIP of theme ZAP when downloading

Video/Screenshot link (optional):

**Comment by dmo-odoo** [comment]
Hello,

Could you please tell me your sale order number ? It should be something like SO2017/183040.

Best regards,
David

**Comment by sharkutz** [comment]
SO2015/29934

**Comment by sharkutz** [comment]
this is the content of the zip file
![theme zap error](https://user-images.githubusercontent.com/7041048/31613480-ec583eaa-b28b-11e7-9275-4c1ae19bbf15.JPG)

**Comment by dmo-odoo** [comment]
Since this kind of issues are supposed to go to apps@odoo.com rather than here and that I just noticed you sent us a proper ticket through apps@odoo.com, I'll continue handling this issue in its proper channel, that is on your support ticket. I'm closing this. You'll hear from me soon on the ticket.
