### ISSUE TITLE
[11.0 EE]: Bank reconciliation won't allow to use base.main_partner childs

### ISSUE THREAD

**Issue by gustavovalverde** [odoo/odoo#20224]
### Impacted versions:
10.0 and 11.0 EE

### Steps to reproduce:
- Start a Bank reconciliation
- Try to reconcile a transaction against a child of the `base.main_partner`

### Current behavior:
- `base.main_partner` childs won't appear

### Expected behavior:
I should reconcile payments and emissions against company employee's and/or investors.

**Comment by gustavovalverde** [comment]
Ticket 777625

**Comment by Yenthe666** [comment]
@gustavovalverde did you get any feedback on the ticket yet?

**Comment by oco-odoo** [comment]
This use case is unfortunately not supported by our modelling.

Here is the answer Antoine gave on the ticket, 4 months ago: 

"Unfortunately, at the moment there are no other ways than changing the structure of your partners by having that employee unlinked from the parent company, as otherwise (and I'm here not even talking about the reconciliation process, but on a wider scale, about the way we create journal items) the parent company will always be the partner mentioned in the partner_id field. You can see it working that way even in our expense App. "
