### ISSUE TITLE
[11.0] "Country search" dialog doesn't show enough country

### ISSUE THREAD

**Issue by hongquan** [odoo/odoo#20402]
#### Impacted versions:
11.0

#### Steps to reproduce:

Go to Settings > Company > Edit company > Click to change country. The "country search" dialog shows up.

#### Current behavior:

The dialog shows 160 countries

#### Expected behavior:

The dialog shows all countries (> 200)

Video/Screenshot link (optional):

![screenshot from 2017-10-24 10-39-23](https://user-images.githubusercontent.com/314607/31923883-b2d41498-b8a7-11e7-8de2-5656139133d5.png)

**Comment by Yenthe666** [comment]
Hi @hongquan,

Thank you for your report but this is the default behaviour from Odoo.
Odoo only shows this number by default because of performance and historical reasons. If you would want to see all the records you would first need to do a search and then remove the filter for example.

Regards,
Yenthe

**Comment by hongquan** [comment]
Thank you.

I wanted to pick "Viet Nam", which is at the bottom of the list, so I thought the  list should be shown fully.
Now, I try doing as your suggestion, and can find "Viet Nam".

**Comment by Yenthe666** [comment]
Perfect - best of luck!
