### ISSUE TITLE
[11.0] Automated actions no longer have the option to set workdays

### ISSUE THREAD

**Issue by Yenthe666** [odoo/odoo#20448]
Impacted versions: 11.0

Steps to reproduce:
- Go to a scheduler under `Settings > Technical > Automation > Scheduled actions`
- Activate developer mode
- Hover over the field `interval_type`
In version 10 you have a value (key) named `work_days`, which is no longer present in V11.
V10 example:
![image](https://user-images.githubusercontent.com/6352350/31983997-0117a67a-b960-11e7-85cf-aaec434a0fd2.png)

V11 example:
![image](https://user-images.githubusercontent.com/6352350/31984009-0fe354f6-b960-11e7-9b98-23bcb3884e05.png)

Current behavior: The key `work_days` has been removed in V11

Expected behavior: Having the ability to only trigger schedulers on workdays?

**Comment by JKE-be** [comment]
Was introduced here (not working) https://github.com/odoo/odoo/commit/004a0b996ff8f269451e07346f71a129a1f3fbaf

Was removing here (because never worked) https://github.com/odoo/odoo/commit/4ea356110e7fb5ebd60b550cad818ae048e23361

Could be added in a next version again using the resource module to know the work_days? seems a nice feature!

/cc @tde-banana-odoo your pov ?

**Comment by tde-banana-odoo** [comment]
Hello,

It should be quite easy to do if functional people want it.

**Comment by Yenthe666** [comment]
@tde-banana-odoo I bet there are some good options for this. I used it for all our database backups (with my backup module from https://github.com/Yenthe666/auto_backup/tree/11.0) but since the key has been removed I had to change to daily.

**Comment by tde-banana-odoo** [comment]
Hello,

What is exactly the use case of doing automated action only on working days ? Is there any real impact of doing it every day ?

**Comment by Yenthe666** [comment]
For example with my backup module: Imagine that you have nobody working in the weekend and you have a database of 50GB. You're esentially backing up 100GB of data that you don't need? I bet there are better cases, but this is an example that I could think off right away.

**Comment by Yenthe666** [comment]
@tde-banana-odoo could you give it some TLC? 🙏

**Comment by Yenthe666** [comment]
@tde-banana-odoo or @JKE-be could we re-add this before V12?

**Comment by JKE-be** [comment]
No, it is an improvement.

But if you really needed for you, you are free to implement it in your own module.

**Comment by Yenthe666** [comment]
@JKE-be no its not an improvement. This feature worked fine at some point and then broke in another version. We also made an OPW and it was closed with an excuse too. If a feature was there and it worked and now it doesn't it has to be a bug no?

**Comment by JKE-be** [comment]
This feature is not implemented at least since v8.
That's why we remove the Unimplemented option form the list.

But yes that could be a nice feature, but no it's not a bug.

And my PoV stay the same that previously, if you really needed for you, you are free to implement it in your own module of backup, it is really trivial feature if you just want to avoid week end, regardeless public holiday.
