### ISSUE TITLE
Odoo.sh Bitbucket support

### ISSUE THREAD

**Issue by jusle** [odoo/odoo#20568]
Hello!

Currently [Odoo.sh](https://www.odoo.sh) only supports GitHub. There should be support for [Bitbucket](https://bitbucket.org), too.

**Comment by Yenthe666** [comment]
@amigrave & @dbo-odoo could you guys give feedback? 😉 I don't think this is planned.

**Comment by bringsvor** [comment]
+1 for Bitbucket support, but I don't think it's planned.

2017-10-30 9:53 GMT+01:00 Yenthe V.G <notifications@github.com>:

**Comment by dbo-odoo** [comment]
Hello,

We also received feedback for the same integration with Gitlab, unsurprisingly :)

We have no plan to do that at the moment since it would require quite a lot of development efforts (although some of our code is platform-agnostic, not all of it is). We'd rather invest in what we have promised for the release first.

This doesn't mean it will never be done (we know that people won't migrate to Github just for Odoo.sh, meaning that it might be a deal-breaker for some); simply that it is not a priority at this point.

Thanks for the feedback anyway, always appreciated :)

Regards,

**Comment by amigrave** [comment]
@jusle May I ask you to use the "Send feedback" option in the top right menu of the Odoo.sh main interface for everything related to Odoo.sh ? Thanks in advance.

**Comment by jusle** [comment]
@dbo-odoo OK, thanks.

@amigrave I would but we haven't signed to Odoo.sh because we don't have any GitHub repositories.

**Comment by Yenthe666** [comment]
@jusle you can create a free account and let Odoo.sh generator a repository to play with though. Give it a try!

**Comment by AMhadhbi** [comment]
Hello! @amigrave & @dbo-odoon we plan to use odoo.sh but currently Odoo.sh only supports GitHub. how can use odoo.sh in our Bitbucket? there is migration or integrate from Bitbucket to Github? how can we use Odoo.ssh if we are not working in Github repository?

**Comment by Yenthe666** [comment]
I believe the simple answer is you can't.

**Comment by AMhadhbi** [comment]
@Yenthe666 thanks for fast you reply. but we used Bitbucket in our project and we need a best tool as odoo.sh to use it. have you any idea about best integration continuous tools ?

**Comment by Yenthe666** [comment]
@AMhadhbi if you don't go for Odoo.sh you could look into runbot or another automated tool.

**Comment by amigrave** [comment]
Integration with other SCM hosts is actually in our wishlist but with a low priority to be honest.

Meanwhile I'm afraid there's not confortable solution. There's a hack you could build up with some webhooks: let's say your repository is on bitbucket, you could have an intermediate repository on github for Odoo.sh that would have a submodule pointing on your repository on bitbucket. It is not confortable in the sense that you would have to setup some webhook trickery on your own in order to bind the two repositories so it would commit something in the github repository when there's a commit on the bitbucket repository, then Odoo.sh would receive the github webhook and would fetch the submodules (hence the bitbucket repository). Completely untested and I don't know if it would require some custome code but I don't see any reason why it wouldn't work.

PS: for any feedback/question about Odoo.sh, **please do not use the Odoo github issues**, instead  address them to `odoo.sh<AT>mail.odoo.com` so it will land directly in the Odoo.sh team inbox. Thanks!

**Comment by AMhadhbi** [comment]
@Yenthe666 we planned to go for Odoo.sh but as I told you our repository is bitbucket so we can't used now it.  Odoo.sh is best automated tools for our projects, we will continue to plan for odoo.sh also with another automated tools. thanks
@amigrave as you said it is not comfortable solution to have two repositories so I understand we can't used our repository with Odoo.sh. Ok for other question about Odoo.sh I will contact directly in the odoo.sh. thanks

**Comment by amigrave** [comment]
@AMhadhbi Please note that I was not talking about a mirror repository from bitbucket to github, but about a github repository that points to (and does not include) the bitbucket repository thanks to the [git submodule](https://git-scm.com/docs/git-submodule) which is the way we handle project dependencies on Odoo.sh.
So basically the idea I explained is that the github repository only contains the submodule link to the bitbucket repository.

The [submodules section in our FAQ](https://www.odoo.sh/faq#how_to_submodules) is in the process of being improved for more clarity.

**Comment by vayalaivadivel** [comment]
Hi Colleagues, Any one have sample odoo.sh or developer guide to integrate bitbucket with odoo.

Thanks,
Vadivel.

**Comment by seyed-mohammad-motahar** [comment]
@vayalaivadivel There is no way to integrate now. I tried that and it can be time consuming to maintain

**Comment by vayalaivadivel** [comment]
@seyed-mohammad-motahar Thanks for your effort.

**Comment by phoenixsampras** [comment]
So when this is happening?
