### ISSUE TITLE
Internal Server error when change shipping address on website

### ISSUE THREAD

**Issue by htr-odoo** [odoo/odoo#20667]
Impacted versions: 10.0

Steps to reproduce:
1) Go to sales-> Customer and create with following detail and save
   Name : Test User
   Email :  testuser@gmail.com
2) Then assign the company with address fields or create new one.
3) Now give him portal access. Can do using "Actions-> Portal Access Management" and then for this user change password and login with that
4) Buy something and checkout
5) When you see shipping address then try to change address and click on next with give you internal server error.

Current behavior: Giving internal server error when change shipping address

Expected behavior: 
->Give proper warning message why not able to change this or not allow to change that bcz its company address.

Video/Screenshot link (optional): https://youtu.be/o6KZNnMg2Ok

**Comment by Yenthe666** [comment]
Hi @htr-odoo,

Thank you for your report. I've just tried the exact same thing on the latest Odoo 10 and it worked without any issues. 
Original adress in the backend:
![image](https://user-images.githubusercontent.com/6352350/33662897-ed3a6ff8-da8d-11e7-92a1-ecc87c28c77d.png)

New frontend shipping address:
![image](https://user-images.githubusercontent.com/6352350/33662863-cc38c5fc-da8d-11e7-8da5-8ae9fa4bce2c.png)


So I believe it has been fixed in the meanwhile.

Regards,
Yenthe
