### ISSUE TITLE
Is there way to select fonts without code? [website module v10]

### ISSUE THREAD

**Issue by alaherma** [odoo/odoo#20776]
Impacted versions:
v10 Website module
Steps to reproduce:

Current behavior:
The only way to change the font-family is by customising HTML. Is someone developing an upgrade for this?
Expected behavior:
Can change font family with a dropbox or a button next to the font size in this bar
Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/16642593/32514091-9240cb66-c3c1-11e7-90b9-02e6efa64e96.png)

**Comment by Yenthe666** [comment]
Hi @alaherma,

Thank you for your report. At the moment you can't choose your own font-family through a button or setting right away. The only way to do this (that I am aware off atleast) is to add it with code.
@JKE-be perhaps we could make this a wishlist item? For example: the ability to choose from default fonts atleast?

Regards,
Yenthe

**Comment by JKE-be** [comment]
Hi,

When you have a theme, you can select the font in the '"Customize Theme" panel.

That will avoid that you hard code a font everywhere instead of using a global font. 
And with this solution, you can easily switch all pages from your website in one click without update the font on each page one by one.

Now if you really need the hacky style for one line, you can always make a past from the styled line or do it via the HTML editor.

This feature will be probably not added in the old version, but I don't say that you will never see it in a future version.

Regards
