### ISSUE TITLE
float_round doesn't work correctly

### ISSUE THREAD

**Issue by MeeleCode** [odoo/odoo#20856]
Impacted versions:
10.0, 11.0

Steps to reproduce:
Try rounding 993.42 using uom rounding 0.001

Current behavior:
Result will have extra decimals: 993.4200000000001

Expected behavior:
Result should be 993.42

Where is the problem:
The problem is in the last line of the function
result = rounded_value * rounding_factor # de-normalize
This will create extra decimals and that is why you need to round the result after this operation to the number of decimals that are sent to the function (0.001=3) before returning it.

**Comment by Yenthe666** [comment]
@qdp-odoo rounding related 😉

**Comment by qdp-odoo** [comment]
I don't think it's effectively related to what you suppose: it's simply that python cannot represent some floats precisely. So float_round _does_ round to 3 decimals, as asked, but then python shows the result with more than 3 decimals.

And most of the time is perfectly fine since the tiny error is not a problem, and Odoo itself has no problem with it. 

Should you need a float with 3 decimals only, you should have a look at float_repr() instead

**Comment by gdgellatly** [comment]
@qdp-odoo Python can certainly represent 993.42 correctly, so perhaps there just may be an issue with float_round. 
```python
In [1]: from odoo.tools import float_round

In [2]: float_round(993.42, precision_digits=3)
Out[2]: 993.4200000000001

In [3]: float_round(993.42, precision_rounding=0.001)
Out[3]: 993.4200000000001

In [4]: round(993.42, 3)
Out[4]: 993.42

>>> x = float(993.42)
>>> x
993.42
>>> repr(x)
'993.42'
>>> round(x, 3)
993.42
>>> 

```

**Comment by gdgellatly** [comment]
btw I just switched that last line to be `result = rounded_value / (1/rounding_factor)` and couldn't get it to fail, including on my own rounding bugs.  Before that they all failed unless precision was set to 6, which was the clue that the rounding factor was the issue.

**Comment by odony** [comment]
@gdgellatly Well, 993.42 is not a binary fraction, so it doesn't have an exact representation as a float in Python, even if `repr()` does a good job at hiding it.

@MeeleCode This is why we have a `float_repr()` method, as @qdp-odoo mentioned, and that's [what the framework uses](https://github.com/odoo/odoo/blob/d8e49d3886ab7c5443b9173bd9b3e45e05b72c6c/odoo/fields.py#L1227) to send float values to the database, for proper storage into NUMERIC.

If you want more gory details:

```python
>>> f = 993.42
>>> f
993.42
>>> "%.20f" % f
'993.41999999999995907274'

# Where does this come from?
# Internally, f is stored as: (sign, mantissa, exponent)

>>> f.hex()
'0x1.f0b5c28f5c28fp+9'

sign = 0 (+)
mantissa = 1 + (0xf0b5c28f5c28f / (2**52))
exponent = 9

>>> m = 1 + int("f0b5c28f5c28f", 16) / float(2**52)
>>> m
1.9402734375
>>> m * 2 ** 9
993.42

# Internally, 993.42 is approximated as (1 + 0xf0b5c28f5c28f / 2**52) * 2**9
```

Contrast this with a number that is a binary fraction, for example 993.25:
```python
>>> f = 993.25
>>> "%.20f" % f
'993.25000000000000000000'
>>> f.hex()
'0x1.f0a0000000000p+9'
>>> m = 1 + int("f0a0000000000", 16) / float(2**52)
>>> m
1.93994140625
>>> m * 2**9
993.25

# Internally, 993.25 is represented as (1 + 0xf0a0000000000 / 2**52) * 2**9
```

Due to the way our `float_round()` method applies an epsilon value to tip the tie-breaking in the right direction, rounded values are sometimes less "repr() friendly" than literal values, but better suited for avoiding rounding errors.

Don't worry, though, this is the expected behavior, and if you need a reassuring representation, just use `float_repr()`:

```python
>>> f = 993.42
>>> rounded = float_utils.float_round(f, 2)
>>> rounded
993.4200000000001
>>> print float_utils.float_repr(rounded, 2)
993.42
```

**Comment by MeeleCode** [comment]
Ok, great, thank you for your detailed answer, but the problem is that you still use this to show this value in the frontend. This is the product form:
![untitled](https://user-images.githubusercontent.com/30649715/32844160-f9cc104a-ca21-11e7-8df4-5dcb472337b5.png)

**Comment by gdgellatly** [comment]
![image](https://user-images.githubusercontent.com/5093264/32849793-17e6b8f0-ca95-11e7-8fe2-444b34e5435c.png)

Another from runbot.  @odony any chance we get to see decimal in the near future (V12).  I think its worth the discussion at least.  Its not like Odoo does that much math, and the cost of setting up a decimal is maybe 10x less than a call to float_round and the math is pretty quick now in Py3.  Summing a list of 100000 random numbers including individual instantiating each decimal was only 0.2 seconds (including the rand overhead and a divisor).  Without instantiation 0.01. (A single call to float_round was 0

**Comment by odony** [comment]
@MeeleCode it's a different issue then, related to the widget used to display the value in the form.

**Comment by MeeleCode** [comment]
@odony it’s good to know for float_repr and sorry if I’ve didn’t provide all the necessary information. Do we need to open a new issue or?

**Comment by pedrobaeza** [comment]
@MeeleCode coming to this by reference, if the problem still continues, it's good to open a new issue expressing that. I will ask other team to check it, as as said, it's another different thing.

**Comment by mrm-david** [comment]
It's so sad that Odoo doesn't work with python Decimals.

**Comment by qdp-odoo** [comment]
:trollface:

**Comment by voronind** [comment]
:+1: for Decimals
