### ISSUE TITLE
update aplicacion list dont work

### ISSUE THREAD

**Issue by icf20** [odoo/odoo#20861]
Impacted versions:
10

Steps to reproduce:
set a ubuntu 16.04 vm via vagrant 
get sudo wget https://raw.githubusercontent.com/Yenthe666/InstallScript/10.0/odoo_install.sh
sudo chmod +x odoo_install.sh
sudo ./odoo_install.sh
go to webgui and then try to update the app list

Current behavior:
it only show ~300 apps

Expected behavior:
to show the whole app list https://www.odoo.com/apps/modules/browse?series=10.0&price=&old_series=10.0

**Comment by vcloud9ray** [comment]
Update Apps List is designed to re-read all of the Odoo Server addon paths looking for local modules (Apps) that are not already in the list.

The Apps at the link you posted are ONLINE and are accessed via the App Store link, not the Apps link.  I believe one click install of Apps is still disabled due to abuse in the past with malicious modules.

If you want all of those modules available you need to download and copy each one to an addons folder on your server.

**Comment by Yenthe666** [comment]
Hi @icf20,

Thank you for your report.
@vcloud9ray is absolutely correct here. The apps list only shows and uses apps that are on your own Odoo (under the addons paths). The remote apps from the app store aren't listed here.

Regards,
Yenthe

**Comment by icf20** [comment]
ok, then add the word "local" before the word list to get a hint what the option does
