### ISSUE TITLE
Web Editor Bug

### ISSUE THREAD

**Issue by LiJiaPeng-1** [odoo/odoo#20877]
Impacted versions: V10 Enterprise

Steps to reproduce:
1、html fields,drag too many 187*187 image to this field
2、you will have some image can not show resize function

Current behavior:

Expected behavior:

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Hi @LiJiaPeng-1,

Thank you for your report.
Do you mean to select multiple files in the file explorer and then drop them all in the HTML field in order to trigger this or? Could you add a little bit more information and/or a video? Does it only happen when the filesize is exactly 187x187?

Regards,
Yenthe

**Comment by LiJiaPeng-1** [comment]
![image](https://user-images.githubusercontent.com/21254120/32761183-e779768a-c92c-11e7-9b87-49f57b04bc38.png)
![image](https://user-images.githubusercontent.com/21254120/32761198-048793f6-c92d-11e7-92a3-fa3032f2ae47.png)

**Comment by Yenthe666** [comment]
@qsm-odoo probably for you.

**Comment by qsm-odoo** [comment]
Hello,

The bug has been fixed in 9.0 with commit https://github.com/odoo/odoo/commit/216edc206c73cbde193e178c91d71d565c2097dc, it will be available in 10.0 as soon as possible.
