### ISSUE TITLE
MRP :: UoM false calculation from BOM (critical!) 

### ISSUE THREAD

**Issue by blaggacao** [odoo/odoo#2098]
This is funny lunacy:
Tha BOM is in g (grams) to adapt to the measurment unit in production
![image](https://cloud.githubusercontent.com/assets/7548295/4104492/fed2ca2e-318c-11e4-8031-140bdefda853.png)

<hr\>
1. There are two consumtions and two stock moves (!) - (first is when availability is checked)
2. The quantities in g should be the quantitites in default uom
3. and vice versa

**Comment by spadae22** [comment]
Any updates on this, please let me know.

**Comment by jco-odoo** [comment]
This is from a very long time ago and some things have been changed on the uom of mrp since, so if you still have this error, it would be good to know.

**Comment by spadae22** [comment]
Right, it seem when uom rounding precision, and decimal precision are different and I do MO orders that do not consume all products and show 0.0 of a product not consumed and the MO can never be "Finished" so it look like the same issue that was causing the above. The workaround that use the rounding field in the BOM lines. Notice the 6021 is listed twice, I had to cancel the MO because it would not consume a zero qty?
![screen shot 2015-01-08 at 11 30 43 am](https://cloud.githubusercontent.com/assets/7741100/5665927/f6ec1100-9729-11e4-9d2a-eaed95425982.png)

**Comment by Yenthe666** [comment]
Hi @blaggacao,

Thank you for your report.
I believe JCO handled some of these cases and as 8.0 is no longer supported I'm closing this issue.
If you still face this in 9.0, 10.0 or 11.0 then please create a new bug report.

Regards,
Yenthe
