### ISSUE TITLE
[10.0][BUG] Payment with draft journal entry

### ISSUE THREAD

**Issue by lithint** [odoo/odoo#21066]
Impacted versions: 10.0

Steps to reproduce: 
1. Create a manual journal entry for AP payment
Accounting -> Advisor -> Journal Entries -> Create an Entry for a vendor(say Partner A)
state: draft
2. Create a Vendor Bill for the same vendor (Partner A) and validate the invoice.
3. You will able to see , AP payment entry as outstanding debits  from that vendor and can Add it to that particular invoice. 
 
Current behavior:
Even the Payment Journal entry is in draft state, draft entry is able to reconcile the open invoice and makes it paid.

Expected behavior:
Is it correct to have a reconciliation of a draft entry with an Invoice ? 
If yes, please help me to clarify my query.

**Comment by oco-odoo** [comment]
Hi @lithint , and thank you for reporting the issue. This is actually a limitation of the current modelling, where the "draft" state of account entries is not non-significant (which, I agree, is a bit counter-intuitive). But this is the expected behavior. In the typical workflow, you should always post your entries. We won't be able to change this in old versions, but will consider it for the future of Odoo. 

I'm closing the issue, but @lap-odoo keeps a note of your feedback ;)
