### ISSUE TITLE
Report Background template incorrect on reports more than 1 page

### ISSUE THREAD

**Issue by gdgellatly** [odoo/odoo#21073]
Impacted versions: 11.0

Steps to reproduce:
Create a sales order with lots of lines (enough to just go over 2 pages).
Set template to background.

Current behavior:
The background image, starts halfway down page, then continues on second page.

Also related is create a short sale order, say one line, background image - you will see image is placed differently than an so with 5 lines.

Expected behavior:
Back ground image fixed in position on each page.

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
@sle-odoo or @mart-e probably for one of you?

**Comment by Yenthe666** [comment]
@smetl could you give an update please?

**Comment by smetl** [comment]
@gdgellatly Do you have a screenshot or a video depicting the problem plz? The default templates available on runbot seems to work perfectly.

**Comment by gdgellatly** [comment]
@smetl If someone can fix runbot, I can try to reproduce.  Its been a while.

**Comment by gdgellatly** [comment]
[Quotation - SO121 (2).pdf](https://github.com/odoo/odoo/files/2053996/Quotation.-.SO121.2.pdf)
[Quotation - SO121 (1).pdf](https://github.com/odoo/odoo/files/2053997/Quotation.-.SO121.1.pdf)
[Quotation - SO121.pdf](https://github.com/odoo/odoo/files/2053998/Quotation.-.SO121.pdf)

@smetl Hopefully enough to show issue - from http://332449-11-0-6e7f22.runbot17.odoo.com

**Comment by smetl** [comment]
Unfortunately, we are not able to fix it with the actual version of wkhtmltopdf supported by Odoo.

To create a PDF, Odoo builds an HTML report and then, convert it to a PDF using the wkhtmltopdf engine. Because this background is added at the HTML-step, only one is added per business document no matter its size). To fix this problem, this background should be managed during the PDF creation by wkhtmltopdf and then, get a background per page (not by document). To do so, we need to upgrade the wkhtmltopdf version used by Odoo that will break a lot of things.
