### ISSUE TITLE
Version 8 and 9 apps on odoo 11

### ISSUE THREAD

**Issue by conroyke56** [odoo/odoo#21090]
Not sure where I should post, new to odoo and github.

Is there anyway to install odoo 7,8,9 addons onto odoo 11 easily? 
Below explains our situation. And would seem a lot of mofulss have been built for precious versions. 

My company stores stock on behalf of our customers. 
Receipt goods on advice, deliver goods when requested.
I can't find a way to restrict stock picking to owner. 
As in respect owners on delivery dockets.  
In our case, the vendor is always the stock owner.
Is there any shortcut way to do this.

**Comment by Yenthe666** [comment]
Hi @conroyke56,

Thank you for your report.
As this is not a bug but a question you're better off asking this on the official help forums (help.odoo.com) as there are plenty of people who can help you there and because this isn't a bug.
In short: if you want to use an app that was made for V7, V8 or V9 you will need to migrate it to V11. This will require some code rewriting as Odoo 11 runs on Python 3 and some other things have changed too. So you will have to either write custom development or migrate an older app version. 😉 

Regards,
Yenthe
