### ISSUE TITLE
[11] fields.py Onchange error: AttributeError: 'int' object has no attribute 'ref'

### ISSUE THREAD

**Issue by dhannyz** [odoo/odoo#21127]
https://github.com/odoo/odoo/blob/11.0/odoo/fields.py#L2122-L2123
``` python
            if not record.id:
                result.append((0, record.id.ref or 0, vals))
```
How is the above code supposed to work?
A falsy record.id value doesnt have a .ref attribute
Is this meant to be `(0, 0, vals)`?

**Comment by rruebner** [comment]
@Yenthe666 Is the case "adds a new record created from the provided value dict" changed now that it also works with "(0, record.id.ref or 0, vals)"? Because the documentation says "(0, _, values)".

**Comment by xmo-odoo** [comment]
@dhannyz 

Looking further into it, this specific bit was implemented in 6cf98c4c87d644928897a76b9985947ab2ebc607 which added a `ref` attribute on `NewId()`, which *should* be what's present for "falsy" record ids (ids of records which have not yet been saved to the database).

Could you indicate how you reached this error? Apparently you managed to have a record with an id of `0` somehow, which should not normally happen.

**Comment by dhannyz** [comment]
@xmo-odoo 
Right, so an onchange creating values in a o2m by
```
self.update({
    'o2m_field':[(0, 0, {...}),...]
})
```
Or any other falsy middle value would cause an error?

Can the usage of this new reference be clarified, the (0, 0, vals) arrangement is referenced many times online, and this addition of the ref seems to break it?

**Comment by rco-odoo** [comment]
@dhannyz since Odoo 11, the web client may invoke `onchange()` with field values that contain a *reference* for new one2many lines:
```python
{'line_ids': [(0, 'line1', {...}), (0, 'line2', {...}), ...]}
```
The line references (the strings `'line1'` and `'line2'` in this case) are hidden inside the `NewId` instances of the corresponding records in the server. These special record identifiers are falsy, and provide identities to records that do not exist in the database yet. When the server sends back the value of the one2many field, it serializes those new records as commands `(0, ref, vals)` where `ref` is either a reference from a `NewId` (the one passed by the client) or `0`.

This mechanism allows the web client to identify the new lines sent back by the server. It is useful, for instance, for keeping the input focus on the right line.

Can you please send us something (a script or module) to reproduce the issue? This would allow us to either fix the actual issue (by understanding how it happened) or point out a mistake in code.

Thanks,
Raphael

**Comment by dhannyz** [comment]
@rco-odoo 
I simply encountered the issue when explicitly using integer `0` in the ref position. `(0, 0, vals_dict)`
Hence the error `'int' object has no attribute 'ref'`

If for some reason `record.id` is equal to  `0`, `0.ref` would cause this error 

However after pulling new commits and retesting, this issue seems to have been resolved for me. If it happens I'll send a script that reproduces it
