### ISSUE TITLE
Google Drive™ integration, is feature complete ?

### ISSUE THREAD

**Issue by icf20** [odoo/odoo#21261]
is this add-on feature complete ? unless i am missing some great features this add-on is useless

my expectations were to use Drive like storage/backup for attachments 

my use case if when user gets a invoice adds the invoice in odoo and then want to attach a scanned copy of the invoice from Drive or to upload one file from local PC and get the file uploaded/hosted on Drive

**Comment by vcloud9ray** [comment]
It would be helpful to explain what you have tried and what happened.  

How far did you get?  
What steps worked?
What errors or unexpected behavior did you encounter?  

Questions should really be asked on the Odoo Forum at http://help.odoo.com as this is a place for Issues  that are straight forward to understand and replicate.  I don't see any steps that can be tested.

You should adhere to the template:

Impacted versions:

Steps to reproduce:

Current behavior:

Expected behavior:

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Indeed. Google Drive is integrated in Odoo so not a bug report.

**Comment by icf20** [comment]
@Yenthe666 so what it does ?
