### ISSUE TITLE
[11.0] cannot read property of undefined

### ISSUE THREAD

**Issue by Karsten-77** [odoo/odoo#21321]
Impacted versions: 11.0

Steps to reproduce:
Something like https://www.odoo.com/de_DE/forum/hilfe-1/question/odoo-js-error-typeerror-cannot-read-property-include-of-undefined-121226
I create a custom module and include a js file which should overwrite payment.payment_form

```
<template id="assets_frontend" inherit_id="web.assets_frontend" name="Payment Tx Assets">
            <xpath expr="//script[last()]" position="after">
                <script type="text/javascript" src="/payment_secure_trading/static/src/js/secure_trading_payment.js"></script>
            </xpath>
        </template>
```
in that file:
```
odoo.define('payment_secure_trading.secure_trading_payment', function(require) {
    "use strict";

    var PaymentForm = require('payment.payment_form');
    console.log(PaymentForm);
```

Current behavior:
Console log prints out: undefined

Expected behavior:
defined object of payment.payment_form

What Iam doing wrong? Where I can find an exact tutorial, how to change existing widgets and create new ones? The old documentation (https://www.odoo.com/documentation/11.0/howtos/web.html)  seems not suit anymore or I read wrong. Why its so hard to understand that part of odoo? What is best and recommended way to overwrite a method https://github.com/odoo/odoo/blob/11.0/addons/payment/static/src/js/payment_form.js#L355 ?
Every Help appriciated! Thanks.

Regards.

**Comment by rruebner** [comment]
@Yenthe666 Can you check please?

**Comment by Yenthe666** [comment]
Hi guys,

If I'm not mistaking you're simply doing this wrong as the JS framework changed in Odoo 11.
@ged-odoo could you check & give feedback please?

Regards,
Yenthe

**Comment by ged-odoo** [comment]
@Karsten-77 The problem is not in your code, but in https://github.com/odoo/odoo/blob/11.0/addons/payment/static/src/js/payment_form.js

That module does not export its value (it should do a return PaymentForm at the end).

The correct way to do what you need to do (and I assume that this is exactly what you had in mind) is to import the widget with a require statement, then to 'include' it (include = modify in place, extend = create sub widget). 

To help you with this, I just did this: https://github.com/odoo/odoo/commit/d2815c474d7ab24a06f5365d967a602119252b95

With this commit, your 'require' statement should return the widget, as expected, instead of undefined.

**Comment by Karsten-77** [comment]
Thanks ged-odoo - I was suggesting, that this module not follows the odoo pattern like a few other core modules.
Should not the documentation be adapted slowly?

**Comment by ged-odoo** [comment]
@Karsten-77 the documentation should definitely be updated.  The JS doc is not good. Just need some resources to do it :)

**Comment by Karsten-77** [comment]
@ged-odoo Would you please provide, how I can call a method at server side?
web.DataModel seems not to exist anymore.

**Comment by ged-odoo** [comment]
you can use the method _rpc, which is defined in all widgets.  For example, https://github.com/odoo/odoo/blob/11.0/addons/web/static/src/js/views/basic/basic_model.js#L227

**Comment by Karsten-77** [comment]
@ged-odoo Sorry for pinging you again, buts really hard to understand the processes and a lot of things confusing me.
As example, https://github.com/odoo/odoo/blob/11.0/addons/payment/static/src/js/payment_form.js#L151
Here we are trying to get the action_url from data-actionUrl attribute, but that can never happen, cause all I find out, all submodules like Ogone https://github.com/odoo/odoo/blob/11.0/addons/payment_ogone/views/payment_ogone_templates.xml#L5 using attribute data-action-url .
How can that work? Or do I miss something?

**Comment by Karsten-77** [comment]
Another thing:
Odoo offers to use render_values also for the sale_button
https://github.com/odoo/odoo/blob/11.0/addons/sale_payment/models/payment.py#L199
but the controllers like https://github.com/odoo/odoo/blob/11.0/addons/website_sale/controllers/main.py#L827 doesnt parse through.
Should it not be return tx.render_sale_button(order, '/shop/payment/validate', render_values=kwargs) ?

**Comment by Karsten-77** [comment]
How to using
```
@http.route(['/payment/XXX/s2s/create_json'], type='json', auth='public')
```
I cant find any position where it is called, only
```
@http.route(['/payment/XXX/s2s/create_json_3ds'], type='json', auth='public', csrf=False)
```
But its integrated in most submodules. Is this important?

**Comment by Karsten-77** [comment]
@ged-odoo 
Hello, would need your help again with this.
Now I can overwrite and include methods like odoo intend. 
Like as simplified:
```
odoo.define('my_module.payment_form', function (require) {
    "use strict";

    var PaymentForm = require('payment.payment_form');

    PaymentForm.include({
        updateNewPaymentDisplayStatus: function () {
            console.log('DOING SOMETHING DIFFERENT');
        },
    });
```
But the problem I have, that this is not executed, when https://github.com/odoo/odoo/blob/11.0/addons/payment/static/src/js/payment_form.js#L28 is executed. It is first executed, when the radio click event https://github.com/odoo/odoo/blob/11.0/addons/payment/static/src/js/payment_form.js#L28 is triggert. How can I solve this? What Iam missing? This method should overwrite the original method also when start is called.
Thanks in advance.
Regards,
Karsten

**Comment by ged-odoo** [comment]
@Karsten-77 Your issue is certainly due to the fact that your module is loaded after the start method from payment_form is executed.  The method does actually overwrite the original method for every method calls, but it cannot work if the PaymentForm.include(...) statement is executed after start is called.

I suggest that you try to add your file earlier in the asset lists.  Maybe make sure that your module does not have 'long' dependencies (for example, some dependencies are asynchronous and will delay the loading of your module enough to cause you this problem.

**Comment by Karsten-77** [comment]
@ged-odoo Please have a look at my answers #21702
I think the problem rely that the return statement is included from dom_ready

**Comment by Karsten-77** [comment]
And cause definition of PaymentForm and init is in same file, I cannot get between.

**Comment by Karsten-77** [comment]
Found another error in https://github.com/odoo/odoo/blob/11.0/addons/payment/static/src/js/payment_form.js#L134
$('input[name="o_payment_form_save_token"]') returns an array, so $('input[name="o_payment_form_save_token"]').checked is everytime undefined.
if ($('input[name="o_payment_form_save_token"]').length > 0){
    var form_save_token = $('input[name="o_payment_form_save_token"]')[0].checked === true;
}
would be correct.

**Comment by Karsten-77** [comment]
@qsm-odoo
Should I start a new issue, or do you want to integrate a fix for that additional error without? See last answer.
Regards,
Karsten

**Comment by qsm-odoo** [comment]
I will handle it

**Comment by Karsten-77** [comment]
@qsm-odoo please can you review my answers in this issue too, where I added you at bottom? Have not got any statement to this things. But possible important for payment.

**Comment by qsm-odoo** [comment]
> As example, https://github.com/odoo/odoo/blob/11.0/addons/payment/static/src/js/payment_form.js#L151
Here we are trying to get the action_url from data-actionUrl attribute, but that can never happen, cause all I find out, all submodules like Ogone https://github.com/odoo/odoo/blob/11.0/addons/payment_ogone/views/payment_ogone_templates.xml#L5 using attribute data-action-url .
How can that work? Or do I miss something?

`data-some-value` in XML can be found with the `someValue` key in the `dataset` variable of a JavaScript DOMElement object. jQuery allows to find the value with both `.data('someValue')` and `.data('some-value')`. camelCase is a standard convention in JavaScript and hyphen-separated attribute is a standard convention in XML, that's why it works this way.

> Should it not return tx.render_sale_button(order, '/shop/payment/validate', render_values=kwargs) ?
Why we need to overwrite this methods, when the feature is allready intended?

Sorry I am not the right person to ask that, I suggest you open another issue for this.

**Comment by Karsten-77** [comment]
@qsm-odoo Thank you for your answer, that Ive not known until now that jQuery offer to find both. You never stop learning.
With the other I will report a new issue.
Regards.

**Comment by qsm-odoo** [comment]
Merged https://github.com/odoo/odoo/commit/91b3a4fa8c44cbb9b0a2a0142363e136f99fd04c and https://github.com/odoo/odoo/commit/506e45e73f4c6cb19b9d68098d663c7aac7f8fc6
