### ISSUE TITLE
[11.0] Incorrect reconciliation entry via Bank statement

### ISSUE THREAD

**Issue by elicoidal** [odoo/odoo#21395]
Impacted versions:
v11.0
Tested the same process in v10.0 and result is correct

Steps to reproduce:
1. Create a new customer (set as company)
2. Create a new bank statement
<img width="1036" alt="1bst" src="https://user-images.githubusercontent.com/7600613/33514548-f2b33816-d790-11e7-9720-a79a42cf7441.png">

3. input 600 payment received from customer 
4. reconcile with open balance
<img width="1022" alt="2bst" src="https://user-images.githubusercontent.com/7600613/33514551-fd186006-d790-11e7-9b7f-7ee7af1b38ff.png">

Current behavior:
5. Entry AR is duplicated and shows 1200 AR for 1200 bank 
<img width="1032" alt="5bst" src="https://user-images.githubusercontent.com/7600613/33514560-0844fb6a-d791-11e7-9627-edcd37825a0a.png">
6. Obviously payment is doubled
<img width="1004" alt="6bst" src="https://user-images.githubusercontent.com/7600613/33514568-1ba1c1b6-d791-11e7-8a91-9abc978e06a8.png">

Expected behavior:
7. Entry AR is 600 vs Bank 600 (check v10.0 output)
![screenshot from 2017-12-02 18-46-43](https://user-images.githubusercontent.com/7600613/33514570-2dac86e8-d791-11e7-953c-9bf580e8fbf1.png)

**Comment by elicoidal** [comment]
@qdp-odoo

**Comment by qdp-odoo** [comment]
@csnauwaert oops

**Comment by qdp-odoo** [comment]
Cédric is working on that, thanks for reporting that bug.

**Comment by csnauwaert** [comment]
Hello,

The problem was introduced by this commit https://github.com/odoo/odoo/commit/2f3b469dee6f18cbccce1cdf2a81cfe57960c533 and only happens when trying to validate a reconciliation without any lines.

It has been fixed in Saas-16 at rev: https://github.com/odoo/odoo/commit/3549688b21eb65e16b9c3f2b6462eb8d8b52cd47 and will be available in version 11 in a few days when the forward port will be done.

Thanks for reporting.
Best regards

**Comment by elicoidal** [comment]
@qdp-odoo @csnauwaert Thanks for your quick feedback
