### ISSUE TITLE
Email Bcc not working as expected after customization.

### ISSUE THREAD

**Issue by burmesepythis** [odoo/odoo#21421]
Impacted versions:
9.0
Steps to reproduce:
Add a new field email_bcc and customize the functions impacted with model mail template, and mail. mail model and mail template model will have the new field email_bcc, and while generating mail emai_bcc field is added. sending mail including email_bcc field as a dict is success and on gmail window the recieved mail shoes bcc mail ids under the field bcc.
Current behavior:
email_bcc field is added to make bcc concept on mail, but the bcc mail ids are shown on email

Expected behavior:
bcc mail ids should not be shown for others.
Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
Handled in 2445f9e, so I close.

**Comment by sswapnesh** [comment]
Fix has not been added to v9 yet.

**Comment by pedrobaeza** [comment]
Yeah, but the problem is solved, and this maybe never get to this version, as it's in its end of life cycle, but this is something inherent to Odoo: you need to upgrade to newer versions sometimes for having certain things solved.

If the DB is under an enterprise contract, you can put an OPW ticket for forcing the fix to get to this version any way.
