### ISSUE TITLE
Stock Valuation at Manufacturing Order.

### ISSUE THREAD

**Issue by jaymaniar** [odoo/odoo#2147]
I checked stock valuation at manufacturing side.  It seems that ERP system doesn't calculate Cost of Raw Materials consumed in manufacturing order. 

Example :

Raw Materials : X,Y,Z

Finished Product : XYZ

When I produced XYZ product, at that time system should calculate cost of X,Y & Z based on Removal Strategy we set & set that valuation  for XYZ product as well.  However there are many cases such as work center costing and all.  But atleast system should calculate cost of Raw Material.

**Comment by spadae22** [comment]
So does this issue also creates wrong costs when using manufacting effeciency on the BOM line for raw materials. Even if I manually recalculate, the BOM cost in only the usage defined and not the actual amount or costs in the MO?
![screen shot 2015-01-08 at 10 22 54 am](https://cloud.githubusercontent.com/assets/7741100/5664814/3eaa1874-9721-11e4-8845-8b39fbe208d4.png)
![screen shot 2015-01-08 at 10 22 39 am](https://cloud.githubusercontent.com/assets/7741100/5664816/416664b4-9721-11e4-9364-b39aea481518.png)

**Comment by spadae22** [comment]
I updated one line in product_extended.py to product_extended module in: 
 def _calc_price(self, cr, uid, bom, test = False, real_time_accounting=False, context=None):

my_qty = sbom.product_qty to 
my_qty = sbom.product_qty / sbom.product_efficiency

Same as it calculates the workcenter BOM costs. Is this wrong?

**Comment by michaeljohn32** [comment]
I have done a little work on this for FIFO, but I'm nowhere near complete for all cases and doesn't include anything that I don't use(eg work centers).  Feel free to pull request to my repository (https://github.com/michaeljohn32/odooaddons) mrp_bom_calculation with any updates.  Either way, it sounds like this functionality will not be in "standard" odoo anytime soon.

I take the standard price for some cases because the products don't have quants yet or some other reason, but it is getting close.  From an accounting standpoint, we needed to set the input account of the produced product to the consumed products' output account to make the correct entries.

I also put warnings up for some cases where it didn't make sense in my workflow to make my life easier.

Hope it helps!

**Comment by leotran** [comment]
Hi all,

I  don't think "product_extended" will not solve our problem. It only right for "standard price" and "MTO". If you use "average" or "real price", you have to re-calculate cost price and re-enter value on journal entry (this time, you cannot use cost price field on product form).

If you use "average" or "real price", finished product must be calculate base on MO (like PO when you buy product) and use "serial number" for Specific Identification method (like Quants). So, base on cost price on MO, you can calculate production cost by LIFO, FIFO or Specific Identification.

**Comment by lem8r** [comment]
Best way to get real cost of produced product is accumulation of costs using analytic account.
Material costs, wages, other distributed costs should be entered in analytic account.

At the moment stock moves are not doing analytic entries.
There should be two things happening: 
-  When MO is doing stock move `Stock` -> `Manufacturing` analytic entry should be generated.
-  When finished product is returned from `Manufacturing` to `Stock` there should be way to enter its price so when average or real price is set it will be updated in proper way.

**Comment by dpelaez** [comment]
The only workaround I have found so far is to do the following:

1. Set the products costing method to real price.
2. Set cost price = 0
3. Create manufacturing order.
4. Consume only the raw materials.
5. Check the value of the raw materials consumed in current inventory valuation.
6. Set the cost price equal to the value of the raw materials consumed.
7. In the MO produce order.

If you go the current inventory valuation you should see that the product move from production->stock has a value of the cost price set and as well in the accounting entries you should see the entries with the correct values.

### Important note: 
if you do not set the cost price = 0 before creating the manufacturing order, when you produce the product the price used is the **cost price that was set before** the MO was created, even if you change it before you click produce.

**Comment by seyed-mohammad-motahar** [comment]
The last post was on Sep 15 2015. 

Is it already fixed in Odoo 10 ? I tested it in Enterprise and it is still an issue. 

The customised module to address this issue just need to modify the stock accounting posting to reflect the cost of raw materials instead of looking into the cost price field of the finished Product or it's configuration (like real price or average etc).

@dpelaez  Are you saying that these 7 steps have to be done every time we create MO or it is just the first time and then system can track the cost of finished item based on the raw materials for further MOs ?

**Comment by dpelaez** [comment]
@seyed-mohammad-motahar Unfortunately, this steps have to be done every time an MO is created. It's a tedious process, but it is the only solution I have found so far.

One thing I forgot to mention is to divide the value of the raw materials by the number of pieces produced. That would the price that goes in cost price.

**Comment by Yenthe666** [comment]
@jco-odoo could you give an update on this one? Can't we close this one by now?

**Comment by pedrobaeza** [comment]
@jco-odoo is there any news on this?

**Comment by jco-odoo** [comment]
We did this for v10 (even before I guess) and v11.  So I don't know why this should still be open.

**Comment by bunhin** [comment]
Hi, @jco-odoo 
Actually this issue is closed without solving the issue, is it right?,  i tried [v-10 with lates code] that finished product not respect raw material consumed at all, so odoo v10 ce will have leaking inventory value when doing mrp production.  Hope it is really fixed.  Thank you

**Comment by dpelaez** [comment]
> Hi, @jco-odoo
> Actually this issue is closed without solving the issue, is it right?, i tried [v-10 with lates code] that finished product value does not respect raw material consumed at all, so odoo v10 ce will have leaking inventory value when doing mrp production. Hope it is really fixed. Thank you

I'm using V11 and this issue is fixed.

**Comment by SIC-pmrteixeira** [comment]
HI All,
What's the best way to have the labour costs in the finished goods?
I can't find a way that I accept to valuation the MO with the labour.
Can you share your opinion on this issue?
Thanks,
Pedro

**Comment by bunhin** [comment]
since Odoo 12 and earlier do not calculate the produced product unit cost from the consumed materials or services, I do some workaround: first, to create/override the post_inventory function to calculate the cost from the consumed products (or bom), after that we override the create stock move function, to create account move entry when the product type consumable as well if we want it, indicated by setting the flag 'create account move' in product form when product type is consumable is selected. Then list labor as a component in bom with type = consumable then check the "create_account_move" option.
