### ISSUE TITLE
Feature Request: CockroachDB Support

### ISSUE THREAD

**Issue by raarts** [odoo/odoo#21479]
Impacted versions:

All

Steps to reproduce:

Replace PostgreSQL with CockroachDB. It is wire compatible.

Current behavior:

Does not work.

Expected behavior:

Would like it to work. Note that CockroachDB has some great advantages over PostgreSQL especially in docker environments.

Video/Screenshot link (optional):

**Comment by lukebranch** [comment]
FWIW: here's information on some of the key differences between CockroachDB and PostgreSQL:

https://www.cockroachlabs.com/docs/stable/porting-postgres.html

It looks like an interesting proposition for perhaps introducing CockroachDB support in the ORM in addition to PostgreSQL, but I would suggest providing more information on what you propose.

https://www.cockroachlabs.com/
https://www.cockroachlabs.com/product/cockroachdb/

**Comment by lasley** [comment]
Odoo ORM uses the [psycopg](http://initd.org/psycopg/) library for interaction with Postgres, so it's not as simple as just making sure db queries are correct.

IMO if something like this were to be taken on, my recommendation would be to replace Psycopg with [SQL Alchemy](http://initd.org/psycopg/) instead, which supports multiple DB engines as long as they're Python DB-API compliant. I would assume it supports CockroachDB, but haven't looked.

Gargantuan undertaking though, with far reaching ramifications.

**Comment by lukebranch** [comment]
@lasley ,

Here's a blog post i've just found on SQL Alchemy and CockroachDB:

https://www.cockroachlabs.com/blog/building-application-cockroachdb-sqlalchemy-2/

Definitely an enormous undertaking, but perhaps one worth some discussion IMO.

@mart-e , @odony , @gdgellatly, @Yenthe666 , @spadae22  what are your thoughts on this?

**Comment by gdgellatly** [comment]
@lasley Cockroach uses psycopg2 and postgres dialect by design.  

@lukebranch I think the main issue would not be the day to day crud, mostly sequences, postgres database queries, and the like, the low level stuff.  Also its lack of good text indexing would be an issue, and most people build that in over top of standard odoo, usually GIN pg_trgm composites.  However it's still missing some features, e.g. no blob type (although think Odoo uses bytea anyway, didn't check if it had a bytes type), and major performance penalties of 200-1900% on exactly the kind of data that Odoo has a lot of (indexed selects on small tables).  

For me its interesting, but no more interesting than the other hundreds of things.  If ever there was a good candidate for a second database engine, a widely accepted, performance fixed, mature supported version of this would be it.

**Comment by lukebranch** [comment]
@gdgellatly ,

Thanks for the valuable insight!

**Comment by mart-e** [comment]
Hello,

Thank you for the proposal but PostgreSQL is a robust technology we know we can rely on.
While CockrachDB seems a promising solution, it is a relatively new (3 years old) and unknown technology.
We already got complains that PostgreSQL is not as known/deployed as MySQL or Oracle, so suggesting a db engine that is not even in the Debian repositories is unlikely to make it.
As said @gdgellatly there is a lot of alternative out there and we prefer to keep focus on the one we are sure are mature, for something as critical as the db engine.

Adding support for another database engine is likely to require a lot of work (even if the syntax is mostly compatible) and it is not something we would like to do at the moment, sorry.
