### ISSUE TITLE
[usability] mail.compose.message wizard doesn't show email address of receipients

### ISSUE THREAD

**Issue by alexis-via** [odoo/odoo#21523]
Impacted versions: 9.0, 10.0, 11.0

Steps to reproduce:
1) login to runbot as admin
2) go to the menu "Accounting > Customer Invoices"
3) select an invoice in "open" state with a partner that has an email address
4) click on the button "Send by Email"
5) In the "Recipients" field, there is only the name of the partner, not it's email address
-> This is really a problem, because we can't easily check the email address before sending the email

Code analysis:
In the name_get() of res.partner, it display the email next to the name if the 'show_email' key is present in context, cf https://github.com/odoo/odoo/blob/11.0/odoo/addons/base/res/res_partner.py#L593
In the mail.compose.message wizard, for the field partner_ids, the 'show_email' key is given in context:
https://github.com/odoo/odoo/blob/11.0/addons/mail/wizard/mail_compose_message_view.xml#L57
But it seems that the widget many2many_tags_email that is used for the partner_ids field is not using name_get()...

**Comment by Yenthe666** [comment]
Hi @alexis-via,

Thanks for the report.
I think it would be neat to see the e-mail there too, in order to verify that you're sending to the correct e-mail.
@qdp-odoo and @mart-e can I ask you guys for feedback?

Regards,
Yenthe

**Comment by alexis-via** [comment]
The fix works great! Thank you very much!

**Comment by anj4u** [comment]
I have the same problem on Odoo 12, just reproduced it on runbot. Isnt it merged to Odoo 12 and higher versions?

**Comment by Yenthe666** [comment]
@anj4u works fine? I just tested on the latest 12.0 by hovering (a longer time) over the recipient:
![image](https://user-images.githubusercontent.com/6352350/107121558-6a6de400-6893-11eb-8c97-724f8dd0d89c.png)

**Comment by anj4u** [comment]
HI @Yenthe666 , maybe i was wrong in my expectations, but I thought that the name_get is taken for the "tag name" (Deco Addict" in your example), and not only for the "title" attribute, as you show it here.
So my expectation was that "**Deco Addict**" would be "**Deco Addict <deco.addict82@example>**"
because the default call is something like

`context="...show_email=True..."`

The search list is using this name_get variant which renders the name with the email together, but after adding it, it is using the default name_get. It it a "expected" behaviour in Odoo?

**Comment by Yenthe666** [comment]
Yeah as far as I know it is expected and has been the case for years already.
