### ISSUE TITLE
[11.0] Reordering feature does not work as expected

### ISSUE THREAD

**Issue by josemoralesp** [odoo/odoo#21535]
Impacted versions:
11.0

Steps to reproduce:
To replicate this issue you have to create a Purchase order with some lines and then you have to try to change the order of these lines. 

Current behavior:
You cannot see the new order of the lines until you write the document.

Expected behavior:
You should be able to see the new order of the lines at the moment you change them 

Video/Screenshot link (optional):

https://www.youtube.com/watch?v=QxFpYt5w4P0

**Comment by wtaferner** [comment]
@josemoralesp 
It has been introduced sometime ago in order to fix another huge performance issue with onchange (https://github.com/odoo/odoo/issues/2714) and the fix is on the way in https://github.com/odoo/odoo/pull/21135 - it is obviously complicated and I appreciate that this is fixed with the needed attention...but it is happening, so I guess we/you just need a little bit of patience ;-)

**Comment by mge-odoo** [comment]
Hi @josemoralesp 

Thanks for reporting the issue. As mentioned by @wtaferner it has been fixed in #21135 and merge in 11.0 at the revision https://github.com/odoo/odoo/commit/b7ee1aa4b1ea906195c234020cb708a1da9de6a7

I therefore close this ticket.

Regards,

Martin
