### ISSUE TITLE
Inventory Valuation is zero for over receiving an item from PO > Pikcing

### ISSUE THREAD

**Issue by asoral** [odoo/odoo#21551]
Impacted versions: 10, 9 & 8

**Steps to reproduce:**
1. Create a PO with a stockable Item and set Unit price as 100 and qty as 1, add no taxes (we'll keep it simple)
2. Confirm the PO and navigate to the receiving screen.
3. Open the picking and enter 2 qty in "done" column. This way you will receive more than the qty ordered (which brings up the bug)
4. Go to Inventory > Reports > Inventory Valuation
5. Check the valuation of the two quants, the first one will have unit cost = 100 and another one will be = 0.
6. Go back to the PO and create a vendor bill. If the billing policy is set to received qty then the system will create a vendor bill for 200. Whereas, the inventory valuation is only 100.

**Current behavior:**
System only adds unit cost to the quants which are created first because of the quant split rule of over receiving. This sets the over received quant valuation as zero which is totally incorrect, because we ended up paying for the over received item as well.

**Expected behavior:**
1. I dont expect the quants to be split just because of over-receiving (even same lots get split)
2. If the quants are being split, then system should keep the same stock valuation to the over received quant as well.

Video/Screenshot link (optional):

**Comment by lap-odoo** [comment]
@asoral Thanks for reporting this. However, that was well the expected behavior for the version 9.0 and 10.0. Note that there have some changes done in the inventory valuation for V11. Now, your use case works fine. There is also a test verifying this : https://github.com/odoo/odoo/commit/3c0337673385876922da95296e70a0b7b728f275#diff-992a918f29175f122ff7fdd224ed4c64R202.
