### ISSUE TITLE
Add real dashboards to Odoo apps

### ISSUE THREAD

**Issue by fgi-odoo** [odoo/odoo#21671]
Dear community,

We would like to introduce real manager dashboards in Odoo, with the same level of intuitiveness and flexibility than Google Analytics:
- more meaningful report measures for graphes and pivot tables,
- ability to compare periods,
- key statistics, etc.

Here is a quick sketch of what we have in mind for eCommerce: https://drive.google.com/a/odoo.com/file/d/1hz22HmHf_bSZ2PIXq4NBUChL0JHf3Hnt/view?usp=drivesdk

This could potentially replace or go on top of current Reporting views.

We look forward to hearing from you. Any suggestion or remark will help.

Thanks!

**Comment by fmdl** [comment]
Hi @fgi-odoo 

It a great idea, because the apps DashBoard is not the best. And today it is long and hard to built an dashboard.

The key feature is the ability to build very easely an Dashboard, find some ideas below:
- The dashboard is not limited at one model (like the accounting dashboard is only for the `account.journal`). You can add any `model` on the dashboard. Like that on the Purchase Dashboard you can see last purchase order, and last invoice.
- Add one dashboard in each apps
- The dashboard can include next activities
- It is fully configurable online (XML + python code which return JSON data)
- Respect the access rules (if you have no access to an model, the cards is not show (no raise))
- Configure scale time easely (exemple : show only the 6 last month).
- Printable
- Add tabs
- User can define his own dashboard from a list of cards (define by admin). exemple : the administrator create some "cards" for the purchase dashboard, by default an user show all, but he can remove, move and re-add (exsiting) cars.
- auto update and fullscreen mode (with a secret url link + multi dashbord mode (change evry x seconde)) (like that you can show on big TV in the middle of the office, I have do that in the wharehousse, but it is not easy (you need some Chrome extension, ...))

Please find screen shot from SAGE X3, all the KPI (Dashbord), can be access easely:
![image](https://user-images.githubusercontent.com/16716992/34106629-44ce295c-e3f9-11e7-8870-2781751e1a58.png)

Regards

**Comment by fgi-odoo** [comment]
thanks @fmdl for your precious ideas. 

As a priority we are thinking about native dashboards that are fully dynamic (change filters, apply comparison, several graph modes, pivot mode, etc.) so that you don't even need to "customize" them (with custom dashlets) or build your own dashboard on top.
Google Analytics is the perfect example. You can build your own dashboard but it's pretty much useless since default dashboards are super intuitive.

**Comment by fmdl** [comment]
Hi @fgi-odoo 

There are two "configuration"

### 1- Hard configuration
by the admin to create an dashlets (from template, with complex function (with python) or built-in function). each dashlet can be save in XML (to import/export)

### 2 - End user configuration
by the end user to create from dashlet from "1" or from built-in dashlet
Exemple in purchase apps:

User 1 have select:
- graph of amount of last purchase order
- graph of unpaid invoice of last invoice

User 2 have select:
- graph of amount of last purchase order
- pie of country
- list of un received purchase order
- last product created

**Comment by blaggacao** [comment]
Please consider including `statsmodels` and `seaborn` for some more intresting analytics, well hidden away to the expert user...

**Comment by Yenthe666** [comment]
Hi @fgi-odoo,

Thank you for the report and a place to discuss everything.
I like what @fmdl and @blaggacao suggested. The current dashboards have a lot of options to improve and become better than what it is now. I think quite some ideas and concepts can be taken from PowerBI. It has some great tools and the dashboards are really clean and intuitive. An example:
![image](https://user-images.githubusercontent.com/6352350/34195563-7e7c09a6-e55e-11e7-822c-22d4a95c8010.png)
Dashboards that allow grouping on countries, cities in combination with extra filters - such as from 100$ to 1000$ for example - gives great dashboards.
Just my five cents!

Regards,
Yenthe

**Comment by adekock11** [comment]
I see in the sketch there is a "Share" button. Will that send a share URL to someone via email so that they may click to view the report, @fgi-odoo? Because that will be great!

I agree with @fmdl that there should be a setting for the dashboard to auto-refresh. It was debated [here](https://github.com/odoo/odoo/issues/6437) that the auto-refresh might not be a good idea, but in the case of dashboards I think it is a great feature.

Another point I agree on with @fmdl is that the time scale should be very easy to be changed. At the moment it is either up to the user to create an advanced filter or it is up to the developer to include all of the predefined date filters such as "Today", "Yesterday", "Last Month" etc. What's more, is if the user adds their filter to favourites, the filter is saved after being parsed - i.e. the context_today() isn't saved, but instead the actual date. If you come back tomorrow, the favourite filter will no longer work.

If I understand you correctly, @fgi-odoo, you're saying that the old <board> module is actually not needed anymore. In my opinion it was actually a pretty useful. The ability to have one screen and see everything that's going on across all the apps is nice because you don't have to go into each app to see what's cooking.

**Comment by fgi-odoo** [comment]
Building new dashboards with custom dashlets is advanced. At first we would like to introduce a new generic "Dashboard" view that most users won't even need to customize. We tested the dashboards of lots of systems and no one seems better to us than Google Analytics in terms of easiness and flexibility. You don't even have to build or customize your dashboard. That's what we expect to reach. We know the historical dashboard screen of Odoo should be improved (better use of filters, list of default dashlets,etc.) but this should come down the road. The new dashboard view should be in xml, so easily customizable.

**Comment by fgi-odoo** [comment]
@adekock11 To answer your question, indeed a share button would be great. Also I'm not saying that we aim to remove the Dashboard app. No, the idea for now is to keep it for advanced users.

**Comment by danger89** [comment]
For which modules are you thinking? E-commerce is apparently one. But also for accounting I guess or?

What is your vision, strategy and planning?

**Comment by fgi-odoo** [comment]
The current plan is to develop the concept with eCommerce app first. This new dashboard view will be part of the first screen in the Website menu. We are still nurturing the specs; Dev should start soon. Then, we will extend it to all the main apps, starting with CRM & Sales. In those apps, this view could potentially replace the current reporting views.

**Comment by yanfrank** [comment]
+1

**Comment by karsapapp** [comment]
@fgi-odoo any updates on the project?

**Comment by Meyssa** [comment]
@fgi-odoo any updates?

**Comment by Ark74** [comment]
@fgi-odoo how should this be approached by people interested?

Does Odoo development could be powered by https://www.bountysource.com/?
Or is this an EE matter only?

Cheers!

**Comment by Yenthe666** [comment]
@fgi-odoo why the silent closure? Can you enlighten us about what happend?

**Comment by fgi-odoo** [comment]
The output was the new dashboard view in Odoo 12 Enterprise. Dashboards will be improved in v13 thanks to a new graph library (chartjs) and new views (Map view developed for field service, etc.).

**Comment by Yenthe666** [comment]
Thanks for the feedback! With the map view you mean there will be a new view type to be able to add Google maps inside a form right away? 😮

**Comment by fgi-odoo** [comment]
We will use Openstreetmap. Yes, this kind of view will allow to visualize addresses anywhere and make routes in the field service module.
