### ISSUE TITLE
Payment Difference Amount is not updated correctly

### ISSUE THREAD

**Issue by libukoshy** [odoo/odoo#21886]
Impacted versions: v 11

Steps to reproduce: Create a sale order, create Invoice for that order ,register payment then choose down payment with fixed amount ,it showing this behavior.

Current behavior: In Register payment popup wizard generate with a unknow value as payment due.

Expected behavior:

Video/Screenshot link (optional):

![sc1](https://user-images.githubusercontent.com/4153342/34399015-99ea2046-eba9-11e7-9f4f-6c854d3714ab.png)
![sc2](https://user-images.githubusercontent.com/4153342/34399017-a0466df0-eba9-11e7-9018-83d0391f8e2d.png)

**Comment by auyeung112002** [comment]
Different Currency? Bank(INR)

**Comment by lap-odoo** [comment]
@libukoshy It's because you're paying an invoice in USD with a payment in INR. Are you sure you've activated the multicurrency in your settings ? If you do it, you should be able to choose the currency in the register payment wizard : https://drive.google.com/a/odoo.com/file/d/1xc6SvRhpexan2CiuqCnzKve0T7oA9xBX/view?usp=drivesdk.
