### ISSUE TITLE
[11.0] Calendar - wrong time format

### ISSUE THREAD

**Issue by satriani-vai** [odoo/odoo#21943]
Exactly the same issue es this [#9977](https://github.com/odoo/odoo/issues/9977)
Version 10.0 does not have this problem

**Comment by Yenthe666** [comment]
@satriani-vai please add steps and details on how to reproduce it on V11 again.
What language? Any specific settings?

**Comment by JKE-be** [comment]
@adr-odoo

**Comment by Yenthe666** [comment]
@adr-odoo and @JKE-be any update?

**Comment by Gorash** [comment]
Thanks for the repport, I'll merge the fix: https://github.com/odoo/odoo/pull

**Comment by Gorash** [comment]
After further study of this behavior, we can not modify it in stable version.
Indeed, the current configuration for hours am / pm format if we make dependent on the configuration of the language, by default it will apply the format 01:00 in English instead of 1 am, which will not match either. Indeed, the information on the formatting of the time does not exist by default and therefore can not be applied. We will see to make this change of behavior in master.
