### ISSUE TITLE
[7.0][account_asset] Wrong Asset depreciation line

### ISSUE THREAD

**Issue by kenvac** [odoo/odoo#2195]
Hi,

I am trying to setup assets and it calculating depreciation line weirdly unless I am doing something wrong. 

[Pre-requisite]
- Install account_asset module

[Steps to reproduce bug]
- Create new asset from menu Accounting --> Assets --> Assets. The following are asset values 
  - Item A Purchase Date: 28/02/2014
  - Currency: EUR
  - Company: Default company
  - Reference: A-0009
  - Gross Value: 625.58
  - Computation method: Linear
  - Time Method: Number of Depreciation
  - Pro rata Temporis: True
  - Number of Depreciation: 36
  - Number of Months in a period: 1
  - Salvage Value: 0.0
- Press Compute button located in second tab (Depreciation Board)
- Few things are wrong here. 
  - First and last entry do not match with other entries
  - Depreciation date should not start from purchase date but it should start from month following

**Comment by kenvac** [comment]
This is not resolved yet. 

Tested on runbot:
V8: http://28269-7-0-02270b.runbot.odoo.com/runbot/1/8.0

**Comment by mistotebe** [comment]
Hi, this is still an issue for v7 and v8 at least.

**Comment by hbto** [comment]
It is affecting all odoo versions, AFAIK.

**Comment by rwfnf** [comment]
@nim-odoo @qdp-odoo @kenvac In regards to this issue and related #13610, it seems to me like the current implementation of depreciation can be awkward. The commits above apparently went some way to fix this but I see they have not been implemented.

From an accountant's point of view, we would normally want a depreciating journal entry to be posted at the end of our company's accounting period. For example, if our accounting year is 01/01/17 to 31/12/17. Whether we use monthly or yearly depreciation, we'd want the asset and depreciation accounts to be accurate on 31/12/17. Achieving this can be difficult in Odoo. Please see a comparison to Xero below:

## Scenario 1 (yearly)
**Odoo**
Purchase 21/09/17, Prorata Temporis: yes, no. of entries: 5, no. of months per period: 12
Result: First depreciation date is 21/09/17, then 21/09/18, etc.
Pros: Accounts are accurate at end of year (31/12/17) Cons: Inaccurate if we look at balance sheet on 21/09/17 - the depreciation entry should really be posted on 31/12/17.

**Xero**
The first depreciation journal entry is posted on 31/12/17 which is calculated either by full month averaging (rounds to the month) or actual day averaging method ((depreciation for full year / 365) * days between purchase date and end of accounting period). Accounts are accurate both on 21/09/17 and at end of year.

## Scenario 2 (monthly)
**Odoo**
Purchase 21/09/17, Prorata Temporis: yes, no. of entries: 60, no. of months per period: 1
Result: Depreciation entries on: 21/09/17, 21/10/17, etc.
Closer, but still not accurate asset and depreciation accounts at end of year (31/12/17)

**Xero**
Acts the same as scenario 1, does not allow monthly journal entries, a journal entry at the end of the accounting year.

## Scenario 3 (yearly)
**Odoo**
Purchase 21/09/17, Time method based on ending date: 31/12/2022, months per period: 12
Result: Depreciating journal entries are dated 01/01/17, 01/01/18, etc so that balance sheet at company end of year is incorrect. Why not use the actual end date specified? We also don't get the option of Prorata Temporis, so first year depreciation amount is not accurate.

**Xero**
Same as before

## Other Odoo scenarios
It's also possible to change the purchase date on the asset to the end of the month (with monthly) or the end of the year (for yearly) but in one way or another this introduces an inaccuracy in the accounts, either at the company year end date or on the purchase date (or in between).

## Proposed Solution
1) With prorata temporis on, always depreciate at the end of a period. If purchase date is 11/11/17, first depreciation posting should be 30/11/17 (for monthly) and at end of every following month. For yearly,  the first depreciation entry should be at the company's year end (31/12/17 in this case).

2) If time method = ending date is selected, depreciate on the actual ending date (or make this an option by making visible the prorata temporis checkbox).

3) With the above implementations, allow to choose between full month averaging or actual days averaging (see Xero reference below for details) which covers the two methods accountants normally use.

**References**
Details of how Xero handles depreciation calculations and entries:
[https://help.xero.com/uk/FixedAssets-CalculateSLDepreciation-UK](url)

**Comment by Yenthe666** [comment]
Hi @kenvac,

Thank you for your bug report.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
