### ISSUE TITLE
[11.0] translation of res_company.overdue_msg cannot be imported

### ISSUE THREAD

**Issue by yostashiro** [odoo/odoo#22059]
### Impacted versions:

11.0

### Steps to reproduce:

- Install Japanese language
- Install account module

### Current behavior:

Odoo does not import translation record of this message from Transifex: https://github.com/odoo/odoo/blob/25943696ea00b140ea19de1c6ee6a42d97d8e2f7/addons/account/models/company.py#L43-L50

In Transifex, this string appears to belong to stock module which is strange: https://www.transifex.com/odoo/odoo-11/translate/#ja/stock/120654925?q=Dear Sir%2FMadam
![image](https://user-images.githubusercontent.com/7766939/34640918-bbf00734-f336-11e7-8904-f42a0486723a.png)

### Expected behavior:

Translation record gets imported as normal.

**Comment by mart-e** [comment]
Fixed at ff0abd214c89dce19984ed0f3c72ea556e23da01, thanks

**Comment by yostashiro** [comment]
@mart-e Thanks!  Out of curiosity, what is the implication of using lambda for default strings?

**Comment by mart-e** [comment]
@yostashiro it just mean I can call the translation method `_(...)` at execution time.
If I did something like `fields.Char(default=_('Default Value'))`, it would not work because the method would be evaluated when the server is started. It needs to be re-evaluated for each create as every user is probably not in the same language.

**Comment by yostashiro** [comment]
@mart-e Ah, I see.  Thanks a lot for the explanation.
