### ISSUE TITLE
[Odoo.sh]: No way to update Odoo source

### ISSUE THREAD

**Issue by gustavovalverde** [odoo/odoo#22071]
Impacted versions:
All

Steps to reproduce:
Try to update the source code with a `git pull`

Current behavior:
`error: cannot open .git/FETCH_HEAD: Read-only file system`

Expected behavior:
Option to update the source code, as there might be a new fix which we'd like to test on **dev stage**. Right now I'm working on source code outdated 20 days.

**Comment by danger89** [comment]
I think you have some mount problem, right issue. Either your system is failing or your storage is full. Maybe you incorrectly mount your disk..

**Comment by Yenthe666** [comment]
Hi @gustavovalverde,

Thank you for the report.
@dbo-odoo could you have a look at this one too?
@danger89 this is the Odoo.sh hosting platform so there is nothing he can about the issue, the shell user is very restricted.

Regards,
Yenthe

**Comment by Elkasitu** [comment]
@beledouxdenis @amigrave

**Comment by dbo-odoo** [comment]
Hello,

It is currently not possible to pull the Odoo code - this is done by the Odoo.sh team on a regular basis and shared amongst all containers on the same physical serve. It appears it was not the case for some time, surprisingly. I have notified them of the issue, the code should be updated today or tomorrow at most.

I'll close this issue since it's more a feature request (of which they are already aware).

Regards,

**Comment by dbo-odoo** [comment]
FIY, the code was pulled a few minutes ago :)

**Comment by amigrave** [comment]
Hi @gustavovalverde, in the future may I ask you not to use the `github/odoo` issue tracking for Odoo.sh specific issues/feedback?

For **issues** concerning the Odoo.sh platform, you can use the [Odoo ticketing system](https://www.odoo.com/help) (specifying your project name and the url of the concerned instance in the ticket will increase the reactivity of the support team) and for **feedback** about the Odoo.sh platform you can use the *"Send feedback"* option in the top right menu of the main Odoo.sh interface.

Regards.
