### ISSUE TITLE
[Master/12.0e] Promo Rules: Buy 2 Get 1 Free, In Increments of 2 (So Buy 4 Get 2, Buy 6 Get 3, etc.)

### ISSUE THREAD

**Issue by lukebranch** [odoo/odoo#22081]
<h1>Impacted Versions:</h1>
All
<h1>Steps to reproduce:</h1>
Try to setup buy 2, get 1 free rule in promotional rules, based on QTY increments of 2. 

<h1>Current behavior:</h1>
There is no way to setup this sort of QTY increment promotional rule in Odoo without custom development.

<h1>Expected behavior:</h1>
I should be able to create a rule that does not base on min QTY, but based on incremental QTY.<br/><br/>
For example I would like to setup one rule that handles a scenario like:<br/> 

- Buy 2 get 1 free
- Buy 4 get 2 free
- Buy 6 get 3 free
- Buy 8 Get 4 free
- and so on to infinity.

**Comment by lukebranch** [comment]
@Yenthe666 ,

If you don't mind, could you put a wishlist tag on this? It would be a useful function to have, however there is no current way to implement it reliably based on QTY increments.

For example if I have a rule, Buy 5 get 1 free I want to reliably execute this discount, or rule every time the 5 units increment is reached. So If they buy 9 units, it would apply the rule only once, but if they order 10 units it would apply twice.

**Comment by JKE-be** [comment]
already the case... not ?

**Comment by rdeodoo** [comment]
Yes, it is working that way currently. Every X product, you get Y free product. X and Y being defined in the promotion program.
Note that you might experience some bugs related to quantities or minimum threshold that will be fixed in the upcoming days.

**Comment by lukebranch** [comment]
@rdeodoo ,

Thanks for looking into this. Let me check again, perhaps i'm missing something.

**Comment by rdeodoo** [comment]
Hello @lukebranch 

Sorry for the late reply, kinda forgot about this one.
That can totally be done as you can see in this video: https://drive.google.com/file/d/1NIyRphWHQL3sc96y9uI5KnTD9ePTjqb6/view

You can tell that `x` product `A` give `y` product `B`. (B could be A, the same product like the example on the video and the ones you mentionned)

In my case, 5 Can of Coke give you access to 1 free Can of Coke.

There is some tips to understand:
1. The product you will offer as discount need to be on the cart itself. Meaning, if you want 5 Can of Coke to give a free iPad (What a beautiful world right :happy:), then having 5 Can of Coke in your cart won't be enough to enjoy the discount. You will need to add the iPad on the cart, and then free iPad will appear.
Extending that principle, if you have 50 Can of Coke in your cart, you are eligible to receive 10 free iPad but once again, you will need to set yourself iPad quantity to 10 to receive the 10 free iPad as you can see in this video: https://drive.google.com/file/d/1lbsrlzp4H7Dalgt7Y3WL1LT6md2MoaAt/view
If you want to offer the same product (5 Can of Coke = 1 free Can of Coke), you will need to have 6 Can of Coke in your cart (again, the free product need to be on your cart)
I know it might seems weird but it is for technical reasons.

2. When debugging your promotions/coupons that are automatically applied, you may ask yourself why is the coupon not being applied (eg: you don't have an ipad in your cart but 5 Can of Coke, you might be wandering why you don't get the free iPad).
In that case, I can suggest you to set your coupon to be used with a code, that way you will see a clear message on why you don't get it. (Theses messages obviously can't be displayed when on automatical applying mode since it tries to apply all coupons of your database).
