### ISSUE TITLE
Cannot install odoo

### ISSUE THREAD

**Issue by Halex21** [odoo/odoo#22151]
Hello, i am new in this and i have a problem installing the odoo dependencies.

When i try to install the python necessary dependecies i get the followin error:

The python-pypdf package does not have a candidate for installation.

I dont know what can i do. anyone can help me please?

**Comment by Elkasitu** [comment]
What OS are you using? what version? are you installing from source or from a packaged installation?

**Comment by Halex21** [comment]
Hello ,i am using Linux 17.10, and installing from source.

**Comment by Yenthe666** [comment]
@Halex21 you'll really need to answer all of those questions.
What Odoo version do you want to install?
What Python version are you running?
What steps did you follow to install Odoo?

**Comment by Halex21** [comment]
oh sry, in the mail dont appears the other 2 questions, I wan to install odoo 10.0
i dont know what version of python i am using(how can i see it?).

to install odoo i updated and upgraded linux,
 i created a new user called "odoo" with pass,
installed git, installed nodejs and ikts package manager,
get odoo source code from https://github.com/odoo/odoo.git -b 10.0 --depth=1
And them i try to install odoo dependencies with: "./odoo/setup/setup_dev.py setup_deps" but there i get the no candidate for installation error.

**Comment by Elkasitu** [comment]
@Halex21 hi, yep that's my fault, I edited some extra info in the comment which do not get sent over e-mail for spam reasons, probably.

Can I ask where did you learn about using setup_dev.py? It's very outdated and tries to install debian packages as dependencies (so if you were running arch linux, for example, it would throw out an error probably since apt-get is not the default package manager).

To fix your issue, I recommend going over to your odoo folder and executing the following command:

`pip install -r requirements.txt`

However you'll probably need to run that command as sudo or use the `--user` option for the `install` sub-command, I recommend looking into [virtualenv](https://github.com/pypa/virtualenv) which allows you to install python packages without the need for sudo permissions nor cluttering your system

**Comment by Yenthe666** [comment]
You might also want to have a look at https://www.odoo.com/documentation/10.0/setup/install.html

**Comment by Halex21** [comment]
I am following a PDF guide called "Odoo_10_Development_Essentials" that a friends gived to me, there i see the command setup_dev.py.

When i execute `pip install -r requirements.txt ` it says that the requeriments.txt donot exist.

**Comment by Halex21** [comment]
Hi again,

I have made a mistake, i was introducing the command into the odoo folder, but in this folder only was another folder called odoo  where is the content :S, newby fail sry.

So i executed the requirements.txt and i get the following error:
`could not find function xmlCheckVersion in library libxml2. Is libxml2 installed?` Its installed i checked it.
`error: command 'x86_64-linux-gnu-gcc' failed with exit status 1`

**Comment by cierek** [comment]
Read the comments above - Yenthee666 has provided the link to tutorial. He is also an author of very good script for auto install. Use simple steps:
1) Download the script:
wget https://raw.githubusercontent.com/Yenthe666/InstallScript/10.0/odoo_install.sh
2) Run the script:
./odoo_install.sh
3) Configure apache/nginx (or whatever else you are using)

Enjoy

**Comment by Halex21** [comment]
Ok, I'll try to reinstall all using the Yenthe666 coments guide. Thanks all.

**Comment by Yenthe666** [comment]
Hey @Halex21,

Could you give feedback? Did you get a working install?

**Comment by mart-e** [comment]
Closing as no apparent bug in Odoo (probably an issue in the installation process)

**Comment by nahilahmed** [comment]
@cierek I'm a beginner.How do you configure apache.I'm using Ubuntu 14.04

**Comment by mart-e** [comment]
@nahilahmed please check the documentation:
https://www.odoo.com/documentation/11.0/setup/install.html
https://www.odoo.com/documentation/11.0/setup/deploy.html
