### ISSUE TITLE
Widget many2onebutton missing in v11 

### ISSUE THREAD

**Issue by kaerdsar** [odoo/odoo#22152]
The widget many2onebutton is missing in the version 11 or at least I can not find it. 

In version 10, it can be found as ColumnMany2OneButton (addons/web/static/src/js/views/list_view.js line 1927).

Is it removed? Is it removed on purpose?

**Comment by kaerdsar** [comment]
@Yenthe666

**Comment by Yenthe666** [comment]
@ged-odoo did this get lost in the views and JS rewrite? Could you or one of the guys have a look please?

**Comment by ged-odoo** [comment]
yes, it looks like it was lost, probably because we do not use it at all. we'll have a look

**Comment by mge-odoo** [comment]
Hi @kaerdsar 

Thanks for reporting this issue.

I have taken a look and that's right, the widget got lost during the JS rewrite of the views (and widgets) because it is not used anymore in the core of Odoo (since v7.0).

In 10.0, this widget was only available in the list view and its only purpose was to display a green circle if the many2one was set and a red circle if the many2one was not set. Is this a functionality that you want to keep and you consider important?

Martin

**Comment by mge-odoo** [comment]
Hi @kaerdsar 

As I didn't get any answer from your side, I consider that this functionality wasn't that important for you and I therefore close this ticket.

Do not hesitate to reopen it I am wrong.

Martin

**Comment by everburgEvDev** [comment]
Not Sure if I'm too late, but I would like the to see the one2manybutton make it to V11 and greater.
thanks
Evan
