### ISSUE TITLE
web.base.url : automatic change 

### ISSUE THREAD

**Issue by auditum-sbl** [odoo/odoo#22210]
Impacted versions:
Odoo 10

Steps to reproduce:
Settings -> Activate the developer mode -> technical -> Parameters -> system Parameters -> Edit web.base.url -> from: 127.0.0.0 -> to: https://www.davidsontv.de 
(Online Website; Massmailing)

Current behavior:
The value of the web.base.url automatically changes back to 127.0.0.0 after one day. When that happens, the pictures disappear in a mass mail

Expected behavior:
The entered value "https://davidsontv.de" should not change!

Video/Screenshot link (optional):

![bildschirmfoto 2018-01-12 um 15 12 24](https://user-images.githubusercontent.com/22189188/34878618-0f269788-f7ab-11e7-9f54-35692237b7d5.png)

**Comment by Yenthe666** [comment]
Hi @auditum-sbl,

This is default behaviour. This is because the `web.base.url` looks at the URL that you type in to access your Odoo.
If you want to preven this you either set the `web.base.url` parameter and then add a new parameter `web.base.url.freeze` or you add a `report.url` parameter.

Regards,
Yenthe
