### ISSUE TITLE
Users can access everything despite they don't have permissions from a 3rd party mobile application called 'My Odoo' 

### ISSUE THREAD

**Issue by amir511** [odoo/odoo#22237]
Impacted versions:10.0

Steps to reproduce:
Install 'My Odoo' from : 
https://play.google.com/store/apps/details?id=org.bhc.android&hl=en
login to your odoo server using the ip and port number as well as the credentials of one of the already existing non-admin users on odoo

Current behavior:
User can view (and in some cases edit) data that is not permitted for him to view
Expected behavior:
User should not be able to access this data unless he is admin

**Comment by JKE-be** [comment]
Hi @amir511,

Thanks for your reporting.

"My Odoo" is not developed by Odoo S.A., so you can maybe try to get in touch with somebody from bhc here: https://bhc.be/page/contact

But to be honest, "My Odoo" is just a "PhoneClient" so if you get access to some documents, it is probably due to a misconfigured security rules on your server. 

Wich kind of documents are available by error according to you?

**Comment by amir511** [comment]
@JKE-be , Thanks for your reply
Actually although the application is third party but I believe this is a security issue with odoo
If we create a user and gave him 'user' permissions in one of these modules:
stock card, expenses, timesheet and sales
Then logged in from the mobile app, the user will be able to access with administrative privileges despite he is not an admin.

**Comment by JKE-be** [comment]
Ok, so we agree, the Third party is useless in your bug report...
If it is confirmed, you should be able to reproduce the issue on runbot without any other ThirdParty Apps.

Please give an explicit example with the demo data on runbot.
Which document should be not visible according to you once you give the right of "expenses' to a new user e.g.?

**Comment by Yenthe666** [comment]
Hi there,

Closing as there has been no feedback/answer on the latest question in a few months.
