### ISSUE TITLE
[11.0] Can't export list correctly when grouping

### ISSUE THREAD

**Issue by edsersolis** [odoo/odoo#22278]
Impacted versions: 11.0

Steps to reproduce:

1. Open any list (contacts, invoices, sales orders, any....)
2. Group them by some criteria in such way that it provides more than 1 group
3. Expand any group
4. Select all lines (by clicking top checkbox)
5. Export the list

Current behavior:

- Odoo will export all lines in the list even from those in groups that were not expanded.

Expected behavior:

- Only export lines from the expanded groups.

Video/Screenshot link (optional):

**Comment by sswapnesh** [comment]
Hello @edsersolis 

This works the same way in v10 as well.
You can refer to this issue as well  #20340.

**Comment by edsersolis** [comment]
Thanks for the reference @sswapnesh however it always worked good for us in v10 and earlier.

**Comment by lukebranch** [comment]
FWIW, i've encountered the same issue as well in 11.0.

**Comment by Yenthe666** [comment]
@JKE-be another report of https://github.com/odoo/odoo/issues/20340 where you responded with:

> It is more a debate of usability than an issue IMHO.
But your solution is to uncheck the first checkbox from the 'group by' to say "Not all but all what is selected" and after reselect the unchecked to get it. From this way, you will have "all selected record" instead of "all record of the current domain filter".
We should probably implement a warning in the Gmail style
![image](https://user-images.githubusercontent.com/4848797/31881872-37396418-b7e5-11e7-8cd5-89dfefd7e856.png)
![image](https://user-images.githubusercontent.com/4848797/31881843-171bd56c-b7e5-11e7-8a43-417f1746fbed.png)

Perhaps this behaviour should be changed or a warning should be added (as you suggested)
CC @ged-odoo

**Comment by ged-odoo** [comment]
@edsersolis In my opinion, this is a bug, but it needs some discussion about the meaning of the 'select all' checkbox.  What should it do when no groups are open?  (I suppose exporting all records) And when two groups is open? 

There is a simple (?) workaround: add a filter to the search view to only match the records in the column that you want to export, so selecting all will only select what you want.

I think that this is unlikely to be fixed in 11.0, but I can tell you that we have a task in the framework project named "[web] List view: add options to select all records same like gmail records selection bar". That task should solve all these issues.

**Comment by JKE-be** [comment]
Duplicated of #20340

> But your solution is to uncheck the first checkbox from the 'group by' to say "Not all but all what is selected" and after reselect the unchecked to get it. From this way, you will have "all selected record" instead of "all record of the current domain filter".

We have a task to improve it in the future
