### ISSUE TITLE
ProgrammingError: can't adapt type 'crm.activity'

### ISSUE THREAD

**Issue by syarofanz** [odoo/odoo#22424]
I using crm module, but i have a problem. Every i change stage of lead with actvity column not null always error 'ProgrammingError: can't adapt type 'crm.activity', help please

**Comment by Yenthe666** [comment]
Hi @syarofanz,

Thanks for your bug report.
We'll need more information in order to check/verify this bug.
- Which Odoo version are you using?
- What steps did you do to get this issue and how can we reproduce it?
- Can you reproduce it on an official Odoo test instance (at runbot.odoo.com) or on the latest source code?

Regards,
Yenthe

**Comment by syarofanz** [comment]
Hi @Yenthe666 

- Now i'am using odoo version 9
- If  i change stage of lead with activity column not null always error 'ProgrammingError: can't adapt type 'crm.activity'

**Comment by Yenthe666** [comment]
@syarofanz this seems to work fine on the latest V9. Can you please try to reproduce it on an official runbot (at runbot.odoo.com) and add the steps that you did to trigger this issue?
Have you updated your Odoo to the latest source code?

Regards,
Yenthe

**Comment by Yenthe666** [comment]
Closing as there has been no feedback on this issue.
