### ISSUE TITLE
Odoo Builds raise Warning from phonenumbers

### ISSUE THREAD

**Issue by feketemihai** [odoo/odoo#22426]
Impacted versions: 11.0

Steps to reproduce:
All builds from OCA raise a Warning because phonenumbers library is not installed
check
https://github.com/OCA/l10n-spain
https://github.com/OCA/l10n-romania

Current behavior:
phonenumbers library is not installed.

Expected behavior:
phonenumbers to be included in requirements.txt file and to be install at build.

Video/Screenshot link (optional):

**Comment by xmo-odoo** [comment]
It's a warning because the library is not required, you don't *have* to use it, but at the same time the installer is warned that there will be no phone numbers validation. If it were required, it'd be a requirement, but it's not.

**Comment by feketemihai** [comment]
@xmo-odoo I agree with you, but even the library should be put as external_dependencies on https://github.com/odoo/odoo/blob/bd760f074688fd92c96fd75ec33231bb9c3e7eff/addons/phone_validation/__manifest__.py, no?

**Comment by gurneyalex** [comment]
@xmo-odoo problem is some version of the runbot will generate an "orange" build when WARNING logs are found => not nice for CI

It is also not nice to have undocumented dependencies in the main resources, because then you cannot track them. Finally, this state of affair is sad, because your automated testing is likely only testing either the paths with phonenumbers installed or the branches without phonenumbers installed. Either way, you may get some bugs unreproducible on your own runbot which will make support harder.

What is the rationale behind making phonenumbers kind of a soft requirement ? 

I'd much rather have a configuration setting, possibly by company, allowing to disable the use of the module, rather than relying on it's installation or not...

**Comment by gurneyalex** [comment]
For the record, we will very probably be adding the library to the requirement.txt of OCA/OCB (https://github.com/OCA/OCB/pull/696)
