### ISSUE TITLE
Backorders not created anymore

### ISSUE THREAD

**Issue by gralet** [odoo/odoo#22440]
Impacted versions:
V11   (community + enterprise)     (Reproduced on runbot)

Steps to reproduce:
1- Create a purchase order containing 2 different stockable products
2- Validate PO 
3- Go on the Receipt picking
4- Set "Done" quantity = "Initial Demand" on one of the 2 products
5- Validate Picking
6- Choose "Create Backorder" on the backorder wizard

Current behavior:
The backorder is NOT created

Expected behavior:
The backorder should be created

Video/Screenshot link (optional):
![bug no backorder v11 community](https://user-images.githubusercontent.com/11177216/35244694-5d040d96-ffc1-11e7-8086-bf8ad1f9741b.png)

This behavior seems to appear with a commit between 16/01/2018 and 19/01/2018.

**Comment by Yenthe666** [comment]
@sle-odoo important one for you regarding backorders.

**Comment by sswapnesh** [comment]
@sle-odoo 
I can confirm this issue to.
Main method to create backorder `_create_backorder` is not called.

Since v10 _create_backorder was called from do_transfer method from Backorder Wizard.
Wizard:
https://github.com/odoo/odoo/blob/10.0/addons/stock/wizard/stock_backorder_confirmation.py#L26
Method:
https://github.com/odoo/odoo/blob/10.0/addons/stock/models/stock_picking.py#L911. 

In v11 it is replaced by `action_done`.
Wizard:
https://github.com/odoo/odoo/blob/11.0/addons/stock/wizard/stock_backorder_confirmation.py#L15
Method:
https://github.com/odoo/odoo/blob/11.0/addons/stock/models/stock_picking.py#L644


Introduced from this commit: https://github.com/odoo/odoo/commit/03559629ee3f8ef28e51d8ed659fc7c09b176955
