### ISSUE TITLE
[10.0][11.0] Odoo is unable to route incoming mail from Windows Outlook client to correct thread if the subject is changed

### ISSUE THREAD

**Issue by mlaitinen** [odoo/odoo#22488]
**Impacted versions:** 
10.0 and 11.0 (at least, most likely with every version)

**Steps to reproduce:**
1. Create a fresh database with demo data
2. Install project management
3. Add an incoming and an outgoing email server
4. Create a partner with an Office 365 email address
5. Add the partner as a follower to any of the demo tasks and send a message in the thread
6. In the Outlook Windows application, open the email, change the subject and reply
7. Follow Odoo logs

**Current behavior:**
Odoo is unable to do anything about the message because the headers `References` and `In-Reply-To` have been dropped by the Windows Outlook client. Or it generates a `crm.lead` from the astray message, if configured.

```
odoo_1         | 2018-01-24 13:28:49,651 1 INFO office365 odoo.addons.fetchmail.models.fetchmail: Failed to process mail from imap server gmail.
odoo_1         | Traceback (most recent call last):
odoo_1         |   File "/usr/lib/python2.7/dist-packages/odoo/addons/fetchmail/models/fetchmail.py", line 179, in fetch_mail
odoo_1         |     res_id = MailThread.with_context(**additionnal_context).message_process(server.object_id.model, data[0][1], save_original=server.original, strip_attachments=(not server.attach))
odoo_1         |   File "/usr/lib/python2.7/dist-packages/odoo/addons/mail/models/mail_thread.py", line 1281, in message_process
odoo_1         |     routes = self.message_route(msg_txt, msg, model, thread_id, custom_values)
odoo_1         |   File "/usr/lib/python2.7/dist-packages/odoo/addons/mail/models/mail_thread.py", line 1180, in message_route
odoo_1         |     (email_from, email_to, message_id)
odoo_1         | ValueError: No possible route found for incoming message from <microsoft@outlook-address.com> to "'Administrator'" <my_address@gmail.com> (Message-Id <000f01d39516$e032a170$a097e450$@outlook-address.com>:). Create an appropriate mail.alias or force the destination model.
```

**Expected behavior:**
Odoo shouldn't rely only on the email headers and it should connect the message into the right thread even if the email client has removed the original headers.

Possible ways to solve this issue:
1. Add an invisible tracking code into the content of the email. It seems that at least Zendesk does it like this.
2. Allow configuring `Reply-To` address in a way that it contains the necessary thread information. Eg. (simplified) `odoo+project.task.238@mygsuitedomain.com` or `project.task.238@myodoodomain.com`. It seems like this is the way how Intercom does it.

**Remarks:**
A large number of our clients and even larger number of our clients' clients use the Outlook application in Windows and there's nothing we can do about it. There might be even more email clients that remove `In-Reply-To` and `References` headers.

I tested this with Outlook web app and Android app and both left the appropriate headers intact. The problem only seems to occur when emails are sent from the Windows Outlook application.

**Comment by miqmago** [comment]
This error also happens when an email is sent directly to the catchall email address. It keeps trying once and again and throwing this error until the email is deleted from the inbox.

**Comment by pedrobaeza** [comment]
AFAIK, Odoo uses `Thread-Id` identifier for routing to the right object, so that client might strip that data when you change the subject. Any way, this happens only when changing the subject, isn't it?

**Comment by miqmago** [comment]
In my case, if I send an email with any subject and body to catchall email it also throws this error in every cron.
Maybe I don't have any "default routing" but I don't really know how to verify if there it is.

**Comment by pedrobaeza** [comment]
@miqmago yes the problem it's that you need a default routing in your inbox server, like creating a lead, so that's not a bug. It's the expected behavior.

**Comment by miqmago** [comment]
well in fact I don't want all the spam creating a lead! Maybe I don't know if there is the possibility to leave it pending to manage or similar... I agree that my comments maybe are not related with the bug described by @mlaitinen, I'm sorry if I've been mixing concepts...

**Comment by pedrobaeza** [comment]
@miqmago yes, it's offtopic I'm afraid. I'm going to mark the comments as such, but see https://github.com/OCA/social/tree/9.0/fetchmail_thread_default for a solution on your problem.

**Comment by mlaitinen** [comment]
@pedrobaeza I've seen this happen even when the subject wasn't changed. But that was something very specific, like ONLY on Lumia phones running Outlook (and possibly some specific version of it).

**Comment by pedrobaeza** [comment]
@mlaitinen but then it seems an issue on that mail client, not on Odoo. Take into account that Odoo can guess on irregular data, or the possibilities of making an incorrect match will be higher than the tolerable ones.

**Comment by mlaitinen** [comment]
I wouldn't blame the mail client (despite of having zero sympathy towards Outlook)

Are you getting GitHub discussions to your email? You probably have noticed that the reply-to address is unique. This way even those poor Lumia users can reply to GitHub threads even when Outlook drops the email headers. And this is the way I think Odoo should work as well.

We have created a module that generates a unique reply-to address (read: mail.alias) for each thread, so that no email gets dropped.

**Comment by mlaitinen** [comment]
I know it wouldn't make sense as a default behaviour in Odoo, but I think it should be a configuration option and shouldn't require creating such hacky modules.

**Comment by pedrobaeza** [comment]
I don't think the same: the more you complicate the software, the more bugs will appear, so following KISS principle, and more only for saving these rough edges, I wouldn't add this option.

At the end, you have the possibility of doing that through an extension module if you want to. But you have to think also on the overhead you are adding creating thousands and thousands of mail.alias records, and what that means in terms of performance when evaluating an incoming mail.

Definitively not something that I would recommend in the core.

**Comment by mlaitinen** [comment]
Ok. Then it would be at least fair to let users now that Odoo doesn't fully support emails coming from Outlook. But that wouldn't be very good marketing now would it?

And would you tell your clients that "Sorry, can't support Outlook since it creates overhead"?

**Comment by wtaferner** [comment]
Hmm, this topic is interesting as it is indeed sometimes a bit cumbersome...I was wondering without diving too deep how sometimes the context is lost and ended up by forwarding messages which were assumed not to be matched by Odoo to key users in order to not loose information or communication stream.

@tde-banana-odoo @odony  
Is there any RFC or best practice that says that Office365 or others are doing it wrong or is it something to be improved in the future to be safer to not loose communication via email?

**Comment by pedrobaeza** [comment]
But that's not true. I have customers using Outlook without problems. You have already said that is on old Lumia phones with Outlook installed, so it's a very specific niche.

@wtaferner this is not about Office365, but Outlook client.

**Comment by mlaitinen** [comment]
@pedrobaeza Please read my original issue (the Remarks part). This is about the Windows Outlook client and I wouldn't call it niche. That's probably the worlds most used desktop email client.

> I have customers using Outlook without problems.

Just because you didn't encounter this, it doesn't mean that the problem doesn't exist. We've seen plenty of emails either drop or use the fallback model (depending on the configuration) and show up as leads because 1) the sender of the email changed the subject OR his/her Windows Outlook client changed it for him/her or 2) the sender of the email used Outlook on Lumia.

**Comment by pedrobaeza** [comment]
One note: changing the topic doesn't waste this, and I have several customers using Outlook on Windows as well without these problems, so it should be something more specific. I said the Lumia thing as you mentioned it, but if not, maybe a very outdated Outlook version? My customers are using Outlook 2003 and Outlook 2008, which they are not even so modern and they work...

Maybe if you can share the header of one of those mails, this can be used for analysis.

You can see any way that the market share is not very generous to Outlook, which is going deeper and deeper each trimester: https://emailclientmarketshare.com/

**Comment by gdgellatly** [comment]
@pedrobaeza Those market shares are bs. Numbers from a mass mailing company relying on images to track READS is not the same as the market share of clients used for RESPONDING.  Especially since Outlook blocks those tracking images by default since at least Office 2016.

People simply do not use the same client for reading personal mass email, as for sending directed business responses.   Hell even this was read on Google phone Inbox client, reply started on google gmail client and then finished on Microsoft Github.

**Comment by tde-banana-odoo** [comment]
Hello,

Allowing people to target a thread with model / res_id has been removed since a few versions as this is not considered as a reliable way of working with threads. This cause issues notably with odoo servers replying to each others. It can also lead to security issues as people could try model / res_id batchs and find public documents to spam. Message IDs are (almost) unique and checking the references or in-reply-to hold a valid message ID stored in the target server database works and is reliable.

Having an invisible tracking code is not a solution as you cannot ensure nobody will remove it by mistake. It is a suboptimal solution that adds complexity to the code without fixing the issue.

If some email readers remove references and in-reply-to we cannot magically determine it is an answer to an existing thread or a new email. Even using aliases does not solve it as you still cannot determine if it is an answer or a direct call to the alias. For example in project the project alias is used for reply-to but the headers are used to see if it is a new thread or a reply.

Several people asked to add other headers specific to odoo, like Odoo-Reply-To. The issue is the same as using other headers, you cannot be sure it has not be stripped.

Currently I don't see any solution that is more optimal than using standard email headers. Do you see something else that could solve the issue ?

Best regards,

**Comment by janbec** [comment]
@tde-banana-odoo 
Thanks for giving some insight. I had rough time when we started using email servers in odoo as we lost messages silenty. I don't think you can fix this issue in odoo as in our case there were applicants replying from a email provider smart phone app that stripped header information or some outlook versions that also removed the data as soon as you change the subject.

Generally, losing a message from a customer who requests a quote is very very bad. I am checking the catchall inbox daily for unrouted messages. As a user, my preferred resolution would be to have an easily accessible email dump for unrouted emails. Ideally, you can route it manually. But having an overview for a few user to check or notify would be all I ask for.

**Comment by pedrobaeza** [comment]
@okuryan if they want to use one system on which relying, they should remove the virus part in their system, which is Outlook. Odoo can't do anything if other parts remove vital information.

**Comment by okuryan** [comment]
@pedrobaeza - problem is that are their clients who are using Outlook =) They just cannot say to them - stop using Outlook, because we are using Odoo.

@tde-banana-odoo thanks for reply. Really appreciate quick reaction. Yes, I myself very deeply involved in the mail related topic. So I know all problems about it also from technical side. So yes - I follow you fully on complexity of this.
But I like idea of @janbec - have list of unrouted mails somewhere in the Odoo inteface. At least than customer have no need to monitor "catchall" mailbox all the time.

BTW. human-monitoring  of Catchall mailbox also has problems: Customer can accidentally click on email and mark it as read. Than it will be ignored by Odoo.

**Comment by janbec** [comment]
We use Outlook as well and our solution is to check every mail from that catchall inbox to determine if thas been correctly routed. If someone has a better idea, please let me know!!

I understand it is not odoo's fault if information is missing. However, it is not just Outlook. For example, some Samsung Apps and gmx mobile apps completly remove header information not routing replies from applicants. So all I would ask for is just a notificaton that something went wrong.

I received an answer to a topic in February of this year saying that the team was working on it. But I think only the notificatons of erros for sent mail made it into v12, can somebody confirm?

**Comment by tde-banana-odoo** [comment]
Hello,

Indeed having a way to find those unrouted / lost emails in Odoo could be interesting. I forward it to the product owner team to see if we will do something in standard. I will let you know :) .

**Comment by HYROPES** [comment]
@janbec At moment, in Odoo online or Odoo.sh database, there is a workaround. 

Use the catchall@yourdomain.ext to receive all emails then auto forward all emails to catchall@databasename.odoo.com. If any mail get rejected by Odoo, then in the catchall@yourdomain.ext inbox will receive a bounce / rejection notice from mail provider. ( unable to delivery notice)

System admin can be notified on such notice arrival, and process the issue emails. (if you setup some smart routing, those notification can send to Odoo helpdesk ticket system)
At least the manual checking every single email is not needed.

If user not using Odoo online or Odoo.sh, then a second relay need to setup to catch such rejection notice before send directly to customers.

**Comment by janbec** [comment]
@tde-banana-odoo 
I honestly do not understand that this behavior does not seem to bother anyone in odoo. I have reported this with tickets 1724350 (v10) and 1816391 (v11, basically begging to re-think this). So, I'm, counting on you now ;).

For us, this happens on a weekly basis and if it was not for me checking that chatchall inbox, we would not use odoo for communicating with customers at all. Although most are routed correctly, missing only one request from a customer to change the quote is really bad practice.

@HYROPES 
Thanks for info but I tried the OCA module and it didn't work for us. While definitely being a remedy, it's not my desired behvaior. We should handle that stuff and not bother our customers with our technical problems...

How do you make odoo sending a rejection notice? That's basically what the OCA module does?

**Comment by odony** [comment]
When it comes to users rewriting the subject, I think the described behavior of Outlook is in fact sensible: the user has indicated that they want to start a new discussion, so old references should be dropped. It's a relatively common behavior for some users: instead of composing a new message they edit a reply to start a new discussion.
However, this remains an unusual situation for which there is no established rule/behavior, and the current behavior in Odoo is good as any - there's no way to guess the final intention of the user.

Seeing that this thread is not going to reach any conclusion, I think it's time to let it rest.
@tde-banana-odoo has explained why Odoo operates the way it does, and none of the suggested alternatives offer any better or more robust solution. Users who get bounces in those situations can fix it themselves by composing a proper email with a proper recipient.
