### ISSUE TITLE
Error in describing of creation Dashboard (creation modules)

### ISSUE THREAD

**Issue by FelixMailwriter** [odoo/odoo#22495]
Impacted versions:

Steps to reproduce:

Current behavior: ParseError: "External ID not found in the system:

Expected behavior:

Video/Screenshot link (optional):
![error](https://user-images.githubusercontent.com/22011261/35345921-9696e820-0139-11e8-9f7f-b02bb2807f25.jpg)

ref="openacademy.openacademy_session_graph_view"/>
...
ref="openacademy.session_calendar_view"/>

The first word 'openacademy' should be removed.

**Comment by sswapnesh** [comment]
This should not be Reported here.
CC: @Yenthe666

**Comment by Yenthe666** [comment]
@sswapnesh why shouldn't it? Its the documentation so there isn't really another place to report.

**Comment by sswapnesh** [comment]
Sorry, I misunderstood.

**Comment by Yenthe666** [comment]
Also, @mart-e for you. This could be improved / made more clear.

**Comment by mart-e** [comment]
Why so? The file is named `openacademy/views/session_board.xml` so implies the module is named `openacademy`.
If you named your module differently, you will need to adapt your code but actually that is a good thing. If you want the tutorial to be helpful, you need to understand what is happening.

If you get an error "`External ID not found in the system: openacademy.openacademy_session_graph_view`" it is important that you understand the source, that you learn how to read a traceback (because you will probably get a lot during your development).
If you copy-paste the answers, that will not be very helpful.

**Comment by Yenthe666** [comment]
From that point of view you have a good point @mart-e - it could indeed be one of the first steps in finding your bug/issue.
