### ISSUE TITLE
[11.0] You cannot use the same serial number twice. Please correct the serial numbers encoded.

### ISSUE THREAD

**Issue by max3903** [odoo/odoo#22528]
# Impacted versions
11.0

# Steps to reproduce
* Create products for parts with one being serialized (check the Serial Number)
* Create a products for the finished goods (serialized also)
* Create workcenter, routings and BOM
* Add some inventory for the parts
* Create a manufacturing order for 10 finished goods
* Start your MO and go to the first work order
* Enter the SN of the part and the one for the finished goods being produced
* Click on Validate

# Current behavior
```
Odoo Server Error - Validation Error
You cannot use the same serial number twice. Please correct the serial numbers encoded.
```

I have no serial number for the finished goods yet. I only have serial number for one part.

# Expected behavior
Same screen to do the same step for the second item being produced

**Comment by sle-odoo** [comment]
@max3903 Hello, i initially confirmed without testing it because i was sure it was broken, but actually i cannot reproduce the issue. Also, it seems a validation error is raised at your end, while we removed this constraint in a recent commit. Could you please update your codebase and test again? If you're still facing the issue, could you give me even more complete steps to reproduce it?

Thanks in advance

**Comment by Yenthe666** [comment]
Or, alternatively, can you reproduce it on an official runbot instance at runbot.odoo.com?

**Comment by max3903** [comment]
@sle-odoo @Yenthe666 Thank you guys. Updating the codebase fixed this issue. Have a great week-end.

**Comment by Yenthe666** [comment]
Thanks for the feedback! Have a great weekend too.
