### ISSUE TITLE
Clicking on an app, the app is not loaded, but the main page is refreshed 

### ISSUE THREAD

**Issue by TurboMikeBell** [odoo/odoo#22595]
Impacted versions:
Version 11.0

Steps to reproduce:
Clicking on a App developed using OdooStudio

Current behavior:
When I click on two of the App I have developed, those apps don't load and the _main page is refreshed_.

Expected behavior:
Normally, when I click on the others app I have created, the apps just open.

Video/Screenshot link (optional):

**Comment by mge-odoo** [comment]
Hi @TurboMikeBell 

Can you please give us a little bit more information about the issue?
By "the main page", you mean the App Switcher?

The issue seems to come from the menu which is not linked to an action. Have the developed apps been exported and imported? Can you share the exported file?

Regards,

Martin

**Comment by mge-odoo** [comment]
Hi @TurboMikeBell 

Due to the lack of answer, I therefore close this issue.
Do not hesitate to reopen it if the problem still occurs and if you have more information.

Regards,

Martin
