### ISSUE TITLE
[11.0] Schedule Activities - Missing date time information

### ISSUE THREAD

**Issue by hugho-ad** [odoo/odoo#22614]
Impacted versions:
11.0

Steps to reproduce:
Create new schedule activitie
1.- Set activity Type
2.- Set due date
3.- Assign the activity
4.- click on schedule button

when creation proces ends, a messages is added in the charter,
![image](https://user-images.githubusercontent.com/10233975/35531678-4d4c60c4-04fd-11e8-80e4-4f5a9e2c341f.png)

Current behavior:

The messages tries to show the activity info, date and the datetime , when? and at what time?

But the datetime info is missing since there is not way to set that info in the shechedule activity wizard

Expected behavior:
Change the field Due data from type date to datetime in order to allow user set at what time is going to be their activity

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/10233975/35531816-c49ba018-04fd-11e8-9b61-e9a70ea07921.png)

**Comment by fda-odoo** [comment]
As the ticket has been reported to the support, it will be fixed there, so I close this issue to avoid duplicates.

**Comment by Yenthe666** [comment]
@fda-odoo then please link to the PR & keep it open untill a commit lands in an official branche that fixes it?

**Comment by hugho-ad** [comment]
@nim-odoo 
Since the due date is a date field, 
was depreciated the feature about set the datetime info in the schedule wizard? 

Which is the working around to solve this? 
user needs to set that info like in older versions 
https://drive.google.com/open?id=1_fBlEIDz7jg0qqmjKn153enraTNJ5i7W


The fix https://github.com/odoo/odoo/commit/352be6b6dfbdb2ad02f331238c1eec448ff7b955 you provided does not fit with the requirement

**Comment by Ark74** [comment]
Well, seems like then activities will be treated as documents where they expire at the end of the day.

That's odd, since most of the time activities have to be done at a certain time in the day, or contracts can be lost. Any how.

If the goal is to delete all traces of it, I think there are still some places to clean.
![datetime1](https://user-images.githubusercontent.com/7444518/64479549-51cd3c00-d17e-11e9-911e-78db120d420c.png)
![datetime2](https://user-images.githubusercontent.com/7444518/64479550-5265d280-d17e-11e9-869b-de76965496e4.png)


Regards

**Comment by Ark74** [comment]
Hmm, a quick follow of on this, is that this change _breaks_ the calendar view on later versions since then all activities are treated as "**_All day activities_**".

Then what's the point of hour/time track on this view?

![activity-time-track](https://user-images.githubusercontent.com/7444518/74594473-c7dba600-502e-11ea-9dcf-635bb465e02a.png)
