### ISSUE TITLE
Submit Button Pay Now not translatable

### ISSUE THREAD

**Issue by dansanti** [odoo/odoo#22653]
Impacted versions: 11.0

Steps to reproduce:
1.- Export .po for website_sale
2.- Pay Now for submit_txt not generated
https://github.com/odoo/odoo/blob/11.0/addons/website_sale/views/templates.xml#L1320

**Comment by mart-e** [comment]
Looks like the bug is fixed
![screenshot-2018-3-19 boutique selectionner l acquereur de paiement](https://user-images.githubusercontent.com/564822/37606032-d8c532a8-2b94-11e8-8f40-f9bd4cb78681.png)

Please let me know if you are talking about a different button and give details to reproduce it.
Best
