### ISSUE TITLE
[11.0] Different time for message in Website Chatter and Backend

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#22812]
Impacted versions: 11.0

Steps to reproduce: Performed on [Runbot](http://300047-11-0-d130f2.runbot11.odoo.com/web#id=15&view_type=form&model=project.task&action=506) --> Go to My Account --> Task --> Log messge in chatter

Current behavior: Different time in Portal and Backend (Correct in Backend)

![](https://image.prntscr.com/image/f6BjPBQwSu6kNl66uC_q5Q.png)

![](https://image.prntscr.com/image/aYr_BB8EThWjDVTPmMQnmA.png)

Expected behavior: Message time should same at both place

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
@sswapnesh the website user his language is identical as the backend user his language? Do you test with the same user? (Haven't tested yet, just quick questions).

**Comment by sswapnesh** [comment]
Yes with Same User, Also checked language and timezone too.

**Comment by Yenthe666** [comment]
@JKE-be for your team to check.

**Comment by proloycoder** [comment]
Done

**Comment by sswapnesh** [comment]
Hello,
This Issue seems to have at other Place too.

Sales Order Backend: [https://prnt.sc/ihhn8u](https://prnt.sc/ihhn8u)
Frontend: [https://prnt.sc/ihhl09](https://prnt.sc/ihhl09)

**Comment by rdeodoo** [comment]
Hello,

Thank you for reporting this issue.

I was able to reproduce it on the chatter (your initial message). 
It is due to the fact that the code handling the chatter on the portal is not taking the user timezone into account. I will merge a fix ASAP.

But I was not able to reproduce the issue from the order date (your last message). 
Could you please confirm me that your are able to reproduce it on the runbot and double check that you:

1. did change your computer timezone
2. restart your browser (looks like firefox will not update its timezone and keep the original one if you don't restart?)
3. did change your odoo user timezone in preferences (exact same as your computer)

Because it seems odd the error occurs there as well since they are both rendered server side.

**Comment by sswapnesh** [comment]
I was able to Reproduce this on Runbot and also changed Timezone(On Chrome).  I will confirm aging this again on Runbot and will post video If still there is issue.

**Comment by rdeodoo** [comment]
Thank you @sswapnesh 
In the meantime, https://github.com/odoo/odoo/pull/23238 should be merged soon and will fix the chatter issue

**Comment by sswapnesh** [comment]
Hello @rdeodoo

I have Tested Same on Runbot again and still, Issue Persists.

- Tested On [Runbot](http://305065-11-0-6ec6d3.runbot11.odoo.com/web?#id=86&view_type=form&model=sale.order&menu_id=528&action=717)  --> Changed User's time zone to 'Asia/Calcutta' (Computer has already 'Asia/Calcutta')
    Still same behavior
    

- Tested the Same thing on the Local machine with 'Asia/Calcutta' timezone.
   This Works fine as Server Timezone and Computer timezone and User timezone are same.

Could you please try again by changing your system's timezone and User's timezone other than Runbot's timezone?

**Comment by rdeodoo** [comment]
Hello @sswapnesh 

I could not reproduce the issue on runbot or locally by doing your flow as you can see in this video: https://drive.google.com/file/d/1sctTYvaMUZiluFqnUJua6OwHGkYZSu7c/view
With computer system and odoo user timezone set to 'Asia/Calcutta' it works fine.

BUT I can reproduce the exact same behavior (4:30 hours difference) you mention by changing only the odoo user timezone and not the computer timezone as you can see here: https://drive.google.com/file/d/1gcFb-GkdyIeRF4i6aTbJFdMoa0v9aoN8/view
But this is the normal behavior since you have a red warning as you can see.

**Comment by sswapnesh** [comment]
I will double check again and will post video If still issue persist.

**Comment by sswapnesh** [comment]
Hello @rdeodoo 
[https://drive.google.com/file/d/19nihqH6OKDulnoeWw24EyGIVx9ZDYFt7/view?usp=sharing](https://drive.google.com/file/d/19nihqH6OKDulnoeWw24EyGIVx9ZDYFt7/view?usp=sharing)

**Comment by sswapnesh** [comment]
My bad, It works Perfect. I was changing TZ from Setting --> User.
After that Was Going to Sales --> SO --> Preview. (So Page was not refreshed yet.)
You were changing from Preference which refreshes the Page.

**Comment by rdeodoo** [comment]
Glad I could help and it now works fine, thank you for your cooperation
