### ISSUE TITLE
[11.0] Using CDN deployment with Odoo does not work

### ISSUE THREAD

**Issue by Yenthe666** [odoo/odoo#22878]
Impacted versions: Atleast 11.0 (both community and enterprise)

Steps to reproduce: Follow the documentation at https://www.odoo.com/documentation/11.0/setup/cdn.html. 
Create an account at KeyCDN, configure a zone and then enable the option in Odoo where you link to the CDN provider.
The Odoo configuration:
![image](https://user-images.githubusercontent.com/6352350/35912983-86ed1820-0bfe-11e8-9d2a-6f81555c4360.png)

The CDN configuration:
![image](https://user-images.githubusercontent.com/6352350/35913047-baca5a04-0bfe-11e8-8c00-31f5742b0ac0.png)
![image](https://user-images.githubusercontent.com/6352350/35913061-ce170d46-0bfe-11e8-9e52-066ab8405db5.png)

Current behavior: The CDN is not applied/used in the website as nothing in the HTML source code points to the CDN.

Expected behavior: The CDN is added in the source as mentioned in the docs https://www.odoo.com/documentation/11.0/_images/odoo_check_your_html.png

Video/Screenshot link (optional):

**Comment by qsm-odoo** [comment]
Hello @Yenthe666 
I just tested this in master for another issue (for which I am making a fix, https://github.com/odoo/odoo/issues/22516) and it worked. Are you sure it is not working ? The CDN urls only appear when not connected to the instance.

**Comment by Yenthe666** [comment]
Hi @qsm-odoo,

Thanks a lot for the quick feedback!
What exactly do you mean with 

> Are you sure it is not working ? The CDN urls only appear when not connected to the instance.

**Comment by qsm-odoo** [comment]
When you inspect the HTML source, you will only see the use of CDN if you are not connected to the website (the CDN is only enabled for public users).

**Comment by gustavovalverde** [comment]
@qsm-odoo Isn't the CDN (in it's roadmap) expected to work to optimize static files inside /web ?

**Comment by qsm-odoo** [comment]
@gustavovalverde Sorry, I am not sure to understand your question. Yes, with the *website* CDN option, you can optimize the delivery of all files (so this is true for static files in the */addons/web/static* folder too). This is still an optimization made to deliver files on the website for public users.

**Comment by gustavovalverde** [comment]
It seems I did the wrong question.

Actually, I mean why logged in users (module users) don't get this speed enhancement? Not just in the website, but also in the back-end.

I'm just curious, maybe this is on purpose, it might be on road map or it won't be considered because it could cause other unwanted behaviors.

**Comment by Yenthe666** [comment]
@qsm-odoo if I understand you correctly you mean that only a logged out user will see `CDN` urls in the source? For example for the page https://my.domain.com/shop I should see CDN links in the source, right? Because this is not the case.

**Comment by qsm-odoo** [comment]
@gustavovalverde The reason it is not enabled for connected users is a technical reason. We should check if it is still make sense in master. But as a functional point-of-view, the important is that it works for unconnected user as it is designed to make the best experience for the visitors of your website. For the backend, it makes less sense as the backend is not meant to be reloaded a lot.

@Yenthe666 I added the `//test/` CDN url on this runbot: http://300505-11-0-b5414e.runbot11.odoo.com/, as you can see in the source (the page is broken since the `//test/` url is not a real URL, so assets cannot be delivered). If you connect to that runbot, it works again as the CDN is not used for connected users. Note: @JKE-be just told me the CDN feature was partly broken since recent changes, maybe your bug is related to that.

**Comment by Yenthe666** [comment]
@qsm-odoo well if I follow the whole documentation it doesn't work so I guess so?
Can I send you a personal email with screenshots & details? I'd rather not post URL's etc here. is it qsm@odoo.com?

**Comment by Yenthe666** [comment]
*mumbles*, please? ☘️

**Comment by qsm-odoo** [comment]
@Yenthe666 Sorry, I forgot to reply. You can send me an email but I am not sure I will be able to test anything from screenshots... The latest 11.0 seems to be working as shown in my previous message, so I suppose the bug is related to your configuration. You can send me the details, I will have a look and tell you if I can do anything from those.

**Comment by Yenthe666** [comment]
@qsm-odoo Thanks, I've dropped you an e-mail. I guess we'll know soon enough.
About your note from @JKE-be telling that the CDN feature was partly broken: what was broken then and where can I find the fix/commit?

**Comment by Yenthe666** [comment]
As for my issue: I didn't add `https://` in front of the keyCDN URL that I entered in Odoo. /fail.

**Comment by deepa4lok** [comment]
Am facing the same issue, my CDN configuration seems fine, yet am unable to find its usage.

**Comment by JKE-be** [comment]
@deepa4lok did you check Not connected ?

**Comment by deepa4lok** [comment]
> @deepa4lok did you check Not connected ?

Sorry, I didnt get you, I added url along with https:, still no luck... I even upgraded the website module, later uploaded the images to product, it still didn't help.

**Comment by JKE-be** [comment]
Cdn is used only for public visitor on the website.

So if you are logged in as employee, you will not see the effect of the cdn.
