### ISSUE TITLE
Can't "lock" Serial Number

### ISSUE THREAD

**Issue by DbTechGit** [odoo/odoo#22964]
Impacted versions:

Odoo 11.0-20180208 (Community Edition) 

Steps to reproduce:
Load in the inventory five identical products with five  different serial number.

I created and  validate a sell order with a various products.
(That products are manage with "Serial Number Option")

Then i click on the lot icon, i choose the right serial number and i confirm order.
So Far, so Good.

After a couple of minutes, I create and validate another sell order that contains the same product  of the previous order.

I click on the lot icon, and the sistem it's allow me to choose the same serial number that i have previously used.

Current behavior:
The system allows me to select a previously used serial number.

Expected behavior:

When i choose a serial number that I have already used and shipped,  the system shouldn't  show me that serial number.

Video/Screenshot link (optional):

![order1_right](https://user-images.githubusercontent.com/33259480/36030639-541d25f6-0da8-11e8-89e7-4c1e7fda2b59.png)

![lot_icon_order_1](https://user-images.githubusercontent.com/33259480/36030638-53fa88fc-0da8-11e8-9ccd-aef1108d3229.png)

![trace_order1](https://user-images.githubusercontent.com/33259480/36030640-543d853a-0da8-11e8-9ca3-567e5ebb89a6.png)

![order2_right](https://user-images.githubusercontent.com/33259480/36030647-620062aa-0da8-11e8-920c-9e03907563b8.png)

![lot_icon_order2](https://user-images.githubusercontent.com/33259480/36030646-61e2b71e-0da8-11e8-938b-381ae93f199d.png)

**Comment by lap-odoo** [comment]
Hi, 

That's a good suggestion but not so easy to do in practice.

Let me explain : 
- I deliver Serial Number A 
- I'm back on a delivery order : I shouldn't see serial number A (ok, that's easy)
- But let's imagine that now I create a return : in that case, I should be able to select serial number A (if my customer returned it) 

As you can see, we cannot simply not show serial number A when used, we have to sometimes show it and sometimes not. These conditions are not easy to define. This explains why we still display it even if already delivered. 

However, we have put constraints into place in order to prevent the users from making mistakes. 
You'll see a visual indicator (line displayed in red) showing that the serial number is not available in that source location. And you won't be able to validate the picking if the serial number is already somewhere else.
