### ISSUE TITLE
[11.0] Issue to edit products variants in multicompany

### ISSUE THREAD

**Issue by deivislaya** [odoo/odoo#22975]
**Impacted versions:** 11.0

**Steps to reproduce:**

1. Modify the demo user, so that only belongs to the company: "My company, Chicago" and give manager permissions for the inventory module.

![demo user odoo](https://user-images.githubusercontent.com/5775695/36050561-541d733e-0dbd-11e8-844c-7db1be562f5e.png)

2. Go to Menu Inventory -> Master Data -> Products Variants

4. Find the product "Graphics Card"

3. Press button "Edit"

4. Change Name of the product

5. Press button "Save"

**Current behavior:**

When you edit the product name and try to save it appears a security restriction but this error only occurs when the current user is logged in the company "My company, Chicago".

![screenshot from 2018 02 09 17 19 55](https://user-images.githubusercontent.com/5775695/36050655-b75cdbba-0dbd-11e8-9dce-4cb0fd594fd9.png)

**Expected behavior:**

We expect edit products logged by any company.

**Video/Screenshot link (optional):**

https://youtu.be/szZGhBpFEMQ

**Comment by blaggacao** [comment]
To me it seems a valid report... @sle-odoo 
I beg there are other related models in the inventory module which would welcome a review of the security rules :wink:

**Comment by nhomar** [comment]
#opw 815485

**Comment by Whenrow** [comment]
Hello,
this is due to the field product_name in stock.inventory.line. Once you rename the product, the product's name in the inventory line must be updated. However the inventory line in not in the same company as the user so you have an access right issue.

The field product_name is removed in master version and the commit is already deployed in saas11.2. (see https://github.com/odoo/odoo/commit/8531af9c8bd32382052841bbca5dde17b739afd0)
