### ISSUE TITLE
[10.0/11.0] Save attribute filter preference on Shop

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#22982]
Impacted versions: 10.0/11.0

Steps to reproduce: Enable Product Attribute's Filters on Shop --> Filter Based on Black Color --> Open Product --> Add to Cart

![](https://image.prntscr.com/image/rEgroeD1ROSKFXMSartnmg.png)

![](https://image.prntscr.com/image/6VQxdCX8SkCVaZVuQZemPg.png)

![](https://image.prntscr.com/image/FEm6N4y_RbGGj8z_r5vPeA.png)

Current behavior: Product with the First Attribute in the list will be added  (Here White variant will be added)

![](https://image.prntscr.com/image/TQnUuYRzQmi0m7T_jQjHdQ.png)

It works Same for all attributes as well (Color, Size)

Expected behavior: Attributes Preference Should be Preserved in Product if Filter is applied.

Video/Screenshot link (optional):

**Comment by sswapnesh** [comment]
@JKE-be  Could you please check this?

**Comment by JKE-be** [comment]
Unfortunately, we have until now, no way to open a product page with a pre-defined variant selected.

I will ping the task, but in any case, that will be probably only available for future version since it is an improvement more than a fix.

Thanks for the reporting

PR to manage it in JS for stable version are welcome ;)
