### ISSUE TITLE
[10.0] [CRM] No image update based on contact type

### ISSUE THREAD

**Issue by ventilooo** [odoo/odoo#23015]
Impacted versions:
* Odoo 10.0-20180122 (Community Edition) 
* Postgres 9.4

Steps to reproduce:
1. Create a contact and *leave empty the image field* (company or contact)
2. Update the contact by changing the type.

Current behavior:
**The default image stay the same as the initial contact type**

Expected behavior:
* The same as in the 8.0 version
    * When you change the type of a contact the default image is changed accordingly to the contact type.

Video/Screenshot link (optional):

## Odoo 8.0
![v8](https://user-images.githubusercontent.com/9092178/36118966-af1c53ee-100c-11e8-9836-ea0d4740d9e3.gif)

## Odoo 10.0
![ezgif com-crop](https://user-images.githubusercontent.com/9092178/36118972-b679e534-100c-11e8-84b8-3fdfeb826d16.gif)

**Comment by Yenthe666** [comment]
@tde-banana-odoo CRM related, can you check?

**Comment by kebeclibre** [comment]
@ventilooo 
A few features have been added to the image onchange, i.e. the option to fetch the gravatar corresponding to the image.
In your case, you save a partner, then edit it.
At that point, there is no way to tell if the image is a custom one or a default one

Changing the image during onchange is also not an option, because you would change the image, change the partner type to company and, boom, the default image for company appears.

Changing that behavior would be too disturbing.

Finally, what you show in the v8 actually has been conserved: try to delete the image on your partner and go back to the kanban, it will display the corresponding default image (even the buildings image for company)

Since:
- it is too much of a change to correct, and too dangerous
- that there is a workaround, that actually works like v8
I am not correcting, and closing the issue
