### ISSUE TITLE
user email dont support well international domain names

### ISSUE THREAD

**Issue by icf20** [odoo/odoo#23011]
user can sing up using international domain names but nothing more 

Impacted versions:
11
Steps to reproduce:
signup with a email that have international domain and click on my profile
Current behavior:
Internal Server Error

The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
Expected behavior:
see my profile

**Comment by icf20** [comment]
> Can you give an example e-mail to reproduce it with? 

any domain that have ñ ç ă ș etc  so u can try spam@españa.com

> Can you please add some screenshots/example?

sure 

![image](https://user-images.githubusercontent.com/17784575/36100267-f7f53a6a-1005-11e8-89cf-7d6e5b786430.png)
![image](https://user-images.githubusercontent.com/17784575/36100300-11cf7cc0-1006-11e8-8b4f-25e2a97eb1fe.png)


on the official forum, the system never gets to send confirmation email

![image](https://user-images.githubusercontent.com/17784575/36100406-7187205a-1006-11e8-8b2e-fc3bbf57f566.png)

**Comment by Yenthe666** [comment]
Hey @icf20,

Thanks for the additional info! 
It actually seems to work fine on the latest Odoo 11.0 (on a runbot.odoo.com instance). Can you reproduce it on a runbot too?
Result from my side:
![image](https://user-images.githubusercontent.com/6352350/36102855-deac6f62-100d-11e8-9a3c-0a9b99d78d11.png)

Even with both the username & email the same it works:
![image](https://user-images.githubusercontent.com/6352350/36102891-ffc0be60-100d-11e8-8f63-cb97fea9aec7.png)

**Comment by icf20** [comment]
ă ș in domain make it fail 

![image](https://user-images.githubusercontent.com/17784575/36103080-9e463f42-100e-11e8-8003-7e7900dafd69.png)

**Comment by JKE-be** [comment]
The internal error is because you don't have the access right to read ir.ui.menu when you are portal user.

AccessError: ('AccessError', u'Lo siento, no est\xe1 autorizado para acceder a este documento. S\xf3lo usuarios con los siguientes permisos est\xe1n autorizados a hacer esto:\n- Human Resources/Employee\n\t- Administration/Settings\n\n(Modelo de documento: ir.ui.menu)')

![image](https://user-images.githubusercontent.com/4848797/36111527-b227b1d6-1026-11e8-8604-37dd2ef9ab98.png)



Since I don't have any mail server with ~spanish~ domain, I cannot reproduce your other issue that is probably related to signup/mail and not website.

**Comment by icf20** [comment]
@JKE-be 
> Since I don't have any mail server with ~spanish domain,

the runbot.odoo.com is on english
