### ISSUE TITLE
How to use CRM Phone Calls

### ISSUE THREAD

**Issue by axeforeverjumo** [odoo/odoo#23026]
Impacted versions: Lastest (Web Version: https://apps.odoo.com/apps/modules/9.0/crm_phonecall/)

Steps to reproduce: Create this module

Current behavior: I don't know how to create this module, I want to create a CRM Phone Calls, but i have not idea how to do it, Can I install Odoo in my Computer, them install a CRM Module, and the migrate it to another computer?

Expected behavior: If you can help me how can i create it?, what i need to change to make it personal, liike for example english text to spanish, etc. Or just a Tutorial Guide where i can do this please.

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Hi @axeforeverjumo,

The Github issue tracker is only for bug reports in the official code. Its no the right place to ask questions about other modules and/or custom development. As this is not an official module but one from OCA you could also reach out to them. Alternatively please do ask this on the official help forums at help.odoo.com.

To answer your question (a bit): You should install an Odoo, add this module to your Odoo, install the module and configure it in order to use the module.

Regards,
Yenthe
