### ISSUE TITLE
Odoov11E : Traceback while adding submenus.

### ISSUE THREAD

**Issue by dipsshah42** [odoo/odoo#23052]
Impacted versions:
	> Odoo V11E

Steps to reproduce:
	> Open Settings > Menuitems > Create > Submenu Tab > Add an Item

Current behavior:
	> Its Generating Traceback while adding a submenu.

Expected behavior:
	> It should allow to add submenu by opening its relevant formview.

Video/Screenshot link (optional):

Video > 	https://youtu.be/l34x4FaAxQc
Screenshot > 	
    https://www.awesomescreenshot.com/image/3172419/5c7a09e4ef648b4b5eeaa18a410b16f3

Many Thanks !

**Comment by Yenthe666** [comment]
Hi @dipsshah42,

Thanks a lot for your bug report. I was able to reproduce it:
![image](https://user-images.githubusercontent.com/6352350/36198095-ef2378f4-1175-11e8-9900-f501b1bc33f6.png)
Note that this bug only happens when you haven't filled anything else yet (not even the required menu field) and directly clicking on submenus, add.
@xmo-odoo could you have a look?

**Comment by xmo-odoo** [comment]
Seems to have been fixed by 4f8ae9f993b3423d4a6aead35be980895646a7cd
