### ISSUE TITLE
[11.0] Multi Company. When changing company, your leave cannot be approved

### ISSUE THREAD

**Issue by yung-wang** [odoo/odoo#23155]
Impacted versions:
V11

Steps to reproduce:
- There are 2 companies in the system (A and B).
- User 1 has rights to work in both companies. but as an employee he is linked to company A (work schedule, employee company etc...).
- User 1 creates a Leave Request in company A, but this needs to be approved.
- User 1 then decides to work in company B. At the end of the day, he logs out and his user is linked to company B.
- Now his manager wants to approve his leave. The system will generates the error (Document type: res.users, Operation: read). The manager cannot approved it. He needs to wait until user 1 comes back and log in into company A or that an admin change the user.

Current behavior:
User 1 needs to be logged in the company where the leave request is made. If he changes to another company, than you cannot approve his leaves.

Expected behavior:
Odoo does not need to check on the company linked to the res.users. But need to check on company linked to the employee tabel.

Video/Screenshot link (optional):

**Comment by ThijsvOers** [comment]
See also https://github.com/odoo/odoo/issues/22891, that issue is about invoicing, but describes the same type of error that we encounter in a multi company environment.

**Comment by yung-wang** [comment]
some extra info. In our leave type we made sure that when a leave is approved, it will generate timesheets and also a meeting.

**Comment by tivisse** [comment]
Hello @yung-wang 

Thanks for your feedback.

This functional issue is well known, and is generic to all the
flows on which we try to access to a resources that is not
shared between companies (Leaves, Timesheets, Expenses, ...).

The multi-company navigation has been improved in 13.0 and those
kind of issues won't occur again since that version.

Unfortunately, I'll have to reject your report. The 11.0 is now
in end of life cycle and will soon be unsupported. We are only
patching critical or security issues. The risk of regressions
or introducing side effects is too high.

Best regards,

Yannick.
