### ISSUE TITLE
[11.0] account: 'not draft' filter is completly dumb

### ISSUE THREAD

**Issue by edsersolis** [odoo/odoo#23212]
Impacted versions: 11.0

Steps to reproduce:
1. Open any list view
2. Start trying different filters

Current behavior:
1. Some filters do nothing (a simple example: Not Draft [Accounting > Sales > Customer Invoices])
2. Same thing has happened to our customers with other filters.

Expected behavior:
Information be filtered as requested.

This was working great in past versions and didn't require a modification in its behavior.

Also see related (but to grouping):
https://github.com/odoo/odoo/issues/22278
https://github.com/odoo/odoo/issues/20340

@JKE-be @ged-odoo

**Comment by ged-odoo** [comment]
@edsersolis The filter 'Not Draft' did not work great in past versions, since it was only introduced for v11 (commit https://github.com/odoo/odoo/commit/b31f7786f455574a0644294a91b652986abf6ee4)

In that specific case, the filter seems quite dumb, the 'Not Draft'  filter is actually mapped out to the domain "['&', ('state','in',['draft','open','paid']),('type','in',('out_invoice','in_invoice'))]".

This is definitely something for the accounting team to consider, not a framework issue.  If you have other example of filters that do not work properly, please report them.  But I think that the web framework is doing its job properly and the issue should be solved on a case by case basis.

**Comment by ged-odoo** [comment]
@qdp-odoo

**Comment by qdp-odoo** [comment]
indeed, it has to be handled case by case.

I updated the title for more convenience. It will be fixed by the end of the month.

Thanks for the report

**Comment by sswapnesh** [comment]
@qdp-odoo  PR #23191 is related to this I think.

**Comment by edsersolis** [comment]
Not Draft was only the example I had at hand, it has happened with other filters too.

If specific ones are required will be posting them as they come up as I can't test one by one at the time.

**Comment by nim-odoo** [comment]
Will be handled in https://github.com/odoo/odoo/pull/23191
