### ISSUE TITLE
Python constraint is run with incorrect values when it depends on computed & non-computed fields

### ISSUE THREAD

**Issue by luisg123v** [odoo/odoo#23242]
Impacted versions:
- 11.0
- 10.0

Steps to reproduce:
- Create a Python constraint (`api.constrains`) which depends on both computed and non-computed fields. For example, in the model `res.company`, add:
```
    @api.constrains('country_id', 'currency_id')
    def check_country(self):
        print("Country=%s, currency=%s" % (self.country_id.name, self.currency_id.name))
```
- Take any company, modify both country and currency at the same time, and save the changes

Current behavior:
The constraint is run two times, one when currency is modified, and one with when both currency and country are modified. For instance, if we take a company whose country and currency are Belgium and EUR, respectively; and we change them to United States and USD, respectively; the result would be:
- `Country=Belgium, currency=USD`
- `Country=United States, currency=USD`

Moreover, the first time it runs, there's no way to know whether there still are values to be modified; so in the above example, it wouldn't be possible to determine whether the country is about to be modified.

Expected behavior:
The constraint should run only once, or at least there should be any way to determine what fields are being written and their new values. The above example constraint would be useless, because we couldn't be sure those field values are the same being written.

**Comment by luisg123v** [comment]
CC @luistorresm  @nhomar

**Comment by rco-odoo** [comment]
This issue is indeed a bug, and it exists since version 8.0... I tried to fix it, but I could not find a reasonable way to fix it without breaking existing code.

When method `write` is invoked, it does the following:
 1. update stored fields
 2. validate stored fields from (1) (the constraint is called here)
 3. process fields with inverse
 4. validate non-stored fields from (2) (the constraint is called again here)

The trick would be to delay the invocation of constraint methods until after step 3 above, like:
 1. update stored fields
 2. process fields with inverse
 3. validate fields from (1) and (2) (the constraint is called here)

The problem is: some constraints should be checked as soon as possible. A typical example is ensuring that a hierarchy does not have cycles. If you delay that check too long, you may end up running an infinite loop, because you try to go up in a hierarchy that has cycles. I have seen a cycle in recomputations occurring like that. So the topic is actually very sensitive.

So the possible workarounds are:
 - do not mix stored and non-stored fields in `@api.constrains`;
 - override method `write`, and run the constraint method manually after the update if any of the fields is updated.

Sorry for the inconvenience,
Raphael

**Comment by luisg123v** [comment]
Hi @rda-odoo 

I'm curious, wouldn't it be possible to store temporarily inside the write method those fields being written or pending to be written?

**Comment by rda-odoo** [comment]
@luisg123v  I think you want to message @rco-odoo  or someone else :)

**Comment by rco-odoo** [comment]
@luisg123v yes, I thought about that idea, but it looks tricky to implement, and the complexity of such a solution might not be worth it. I will keep this in mind anyway.

**Comment by luisg123v** [comment]
Yhea @rda-odoo , thanks

@rco-odoo 
I understand, thanks a lot for the answer and your time, I appreciate them.
