### ISSUE TITLE
[11.0][Purchase] Scheduled Date do not save

### ISSUE THREAD

**Issue by grzekru** [odoo/odoo#23275]
**Impacted versions:**

11.0

**Steps to reproduce:**

Video

**Current behavior:**

Scheduled Date do not save

**Expected behavior:**

Save Scheduled Date

**Video/Screenshot link:**

https://youtu.be/8c2mo2fWjqE

**Comment by Yenthe666** [comment]
Hi @grzekru,

Thanks a lot for your bug report.
I've just tested this on the latest V11 and this is working fine. Please update your Odoo source code to the latest version in order to fix this issue at your end.

Regards,
Yenthe

**Comment by sswapnesh** [comment]
@Yenthe666, I can confirm this as a bug and able to reproduce on Runbot.
Try to create PO without any line.

This part of code is used: [https://github.com/odoo/odoo/blob/11.0/addons/purchase/models/purchase.py#L35](https://github.com/odoo/odoo/blob/11.0/addons/purchase/models/purchase.py#L35)

It is computing `Scheduled Date` even there is no line.

**Comment by vcloud9ray** [comment]
date_planned is a fuctional field - which means it isn't meant to be set or modified by the User.

The purpose of this field is to calculate the MIN or EARLIEST date of the LINES on the Purchase Order.
(That's what the code you link to is doing).  If there are no lines, there is no date, so it will (as designed) show FALSE when there is no line.  

The fact that it is editable is to support users who want to MASS UPDATE the date on Lines in conjunction with the SET DATE TO ALL ORDER LINES button, not because it is meant to solicit and update a value given by the user.  

I don't think this is a bug, but a user falsely expecting a field to update when it is changed - the code shows that this isn't the intention of the field.

**Comment by mart-e** [comment]
Indeed, it isn't meant to be set. If you want to explicitly set a value for all lines, you can use the "Set date" button below.
It is a bit confusing when you have a purchase order with no line, the interface will force you to give a value while it may be empty.

Improved that in master at https://github.com/odoo/odoo/commit/d8e2f6a89d3fb097e8233ad2c9beff6ebd3bc9c3
