### ISSUE TITLE
[...] map_tax's utterly inconsistent call signature

### ISSUE THREAD

**Issue by blaggacao** [odoo/odoo#23333]
Hi Folks,

I raised this issue some time ago. Unfortunately, as I can see throughout the v11 codebase, it has not been taken into account duly.
Resolving this has two aspects:

- Make map_tax call signature consistent wherever possible (including product and partner)
- Agree upon weather use partner_shipping_id, partner_id or partner_invoicing_id, there is a somewhat colorful mix and match in the present code...

I'll relate a couple of tickets to this issue.

**Comment by blaggacao** [comment]
Ticket: 1818803

**Comment by blaggacao** [comment]
Ticket: 1818808

**Comment by blaggacao** [comment]
Ticket: 1818819

**Comment by Yenthe666** [comment]
What do all those tickets link too? Are this all tickets about the same issue? O. O

**Comment by blaggacao** [comment]
It's a bit complicated, all those issues have the same root cause, but helpdesk does not like such arguments so I tried to help them understand each and every issue as an isolated case (how they are used to) but I guess at the technical level, developers might understand very quickly the underlying problem by just what's laid out in this github issue.

**Comment by nim-odoo** [comment]
Creating a ticket for each issue single issue is not a good idea, especially if you already have a PR in v10. Simply create a ticket with the PR and the description of the problem, this will avoid multiplying the workload...

**Comment by blaggacao** [comment]
@nim-odoo I would wholeheartedly agree with you (and believe me, also on my side!!), and it definitely is not very efficient. But from time to time, I get to deal with support agents who stubbornly ignores any technical insight and in-depth technical and functional analysis I give them and they just respond something like: "If we cannot replicate it then probably it's only your problem"... And I result never getting past this stage, so I assume I need to adapt to the form and function which is provided to me on the other end of [odoo.com/help](odoo.com/help). I feel really sorry and affected about...
So now you know the why, maybe you can rise this problem internally, I'l take it up once again with our account manager but it seems he/she cannot do a lot about it either...

**Comment by Yenthe666** [comment]
@nim-odoo I think the problem is a bit of a two way street. It is a bit difficult for us - as partners and customers - to get good feedback on issues. Because quite often I get mixed signals or feedback it becomes a little bit vague. I've noticed that sometimes on the official tickets from odoo.com/help there are people that seem to want get rid of tickets as fast as possible. Probably because you guys have a quota of issues to handle per week or so.

The thing is that this creates frustration at the customer or partner end. If they feel like they're not heard or understood they will try other ways, which often results into using multiple channels. I guess @blaggacao is one of those people who is doing his best and simply trying multiple flows/channels in order to get the most out of it. I'm one of those two. I tried tickets only, I tried Github only, I tried issues on Github which I linked on the tickets but sometimes the feedback is just honestly bad.

What do you expect to happen when a customer or a partner takes the time to create a whole issue with detailed information that then gets answered with a simple "we do not consider this a bug" or "internal task made, we'll add this to our list to check"? It feels like the time that the partner or customer invested is not invested from the Odoo side. I think that is a bit of what is happening every once in a while.

Now, on the other hand, I know you guys get a LOT of tickets and quite a lot of those tickets are probably of poor quality with little information. I can imagine that at times this gets frustrating and that it feels that you're 'fighting' an immense battle.

I honestly believe that there should be a better way for issues/tickets. Why isn't there an option to publicly publish issues made from odoo.com/help? Those issues should come on an overview page where everybody that is logged in can vote on tickets. If that is setup correctly you get an issue tracker which sorts on its own and creates priorities depending on the amount of votes.
I also believe that this should recude the huge amount of issues that Odoo gets every day as every partner can see the open tickets and just add a vote to it. Without these being public he has no single clue and you get duplicated tickets.
There just has to be an option to make tickets - or comments - private if they contain some form of sensitive date.

Anyways, just my five cents. We really appreciate your work and I believe we're all trying to do the same thing: improve Odoo one issue at a time.

**Comment by blaggacao** [comment]
As per https://github.com/odoo/odoo/commit/56eead83568c2df2184eb8b2e70a81b0b71d1f1f
the remaining task raised by this issue would be to ensure and verify consistency between `partner_shipping_id` vs `partner_invoicing_id` vs `partner_id` in all sale context applications...

shipping_id, to my own opinion is the right one...

**Comment by nim-odoo** [comment]
@blaggacao @Yenthe666 Github is not the place to discuss this.

**Comment by Yenthe666** [comment]
@nim-odoo I literally just try to give feedback / insight. Where would you like me to put it at then @nim-odoo? Dunno, just trying to help man. 😕

**Comment by qdp-odoo** [comment]
I won't feed any troll on this ticket ^^

I am a man of actions. I need concrete facts and the issue described here is too abstract for me, so I'm closing it because I can.

thanks for your understanding

**Comment by blaggacao** [comment]
@qdp-odoo :wink: Appreciate your clarifying intervention. Keep in mind though, that ultimately, people like @Yenthe666 and me are a out-of-payroll extensions of Odoo SA, acting in it's honorable best interest (as possibly most truthfully perceived by us). Joining efforts, we try to solve real clients problems to make odoo a better (in some cases: viable) alternative on the market place ensuring jobs (or generating new ones) throughout the ecosystem. We are all proud of that, I think! :smile: - One point should make you think though: There is a honestly perceived gap/inefficiency in parts of the feedback cycle.

**Comment by Yenthe666** [comment]
@qdp-odoo the man of actions, not words! Hehe. I understand you.

And agreed with @blaggacao

**Comment by qdp-odoo** [comment]
We're all improving Odoo, one issue at a time, folks. I've no doubt about that, and you shouldn't. :smirk:
