### ISSUE TITLE
Improve import & export tools

### ISSUE THREAD

**Issue by fgi-odoo** [odoo/odoo#23344]
Hello Odooers,

one of the big framework improvements we want for next releases is making import & export tools easier. Importing data is critical when starting with any management software, whatever the kind of business.

Here is our current blueprint: https://pad.odoo.com/p/r.cd3cc8461f8fee493394916c724fb49a

Your input will be much appreciated! Feel free to comment the document and to suggest other improvements in this thread.

Thanks in advance!

**Comment by LeartS** [comment]
the guys at [it-projects](https://github.com/it-projects-llc/misc-addons) have a great [`save_import_map` module](https://github.com/it-projects-llc/misc-addons/tree/10.0/base_import_map) that allows you to save the mapping used in an import so that it can be reused in new imports; be it 2 minutes or 2 years later.

Something like that would be great.

**Comment by RoelAdriaans-B-informed** [comment]
One issue we often have is that an export of the data has headers that do not match the field name a user expects. This is even worse when dealing with translations.

For example, from the current runbot 11.0: exporting a partner there are who fields "Bedrijf"
But, one of those exports as the "city_id/id" field.

For some exports we have to select Export All Data, importing this file again often fails.

**Comment by pedrobaeza** [comment]
There are several modules that we have developed in OCA for helping in import/export tasks. Please take them into account for including them in core:

* https://github.com/OCA/server-tools/tree/10.0/base_export_manager
* https://github.com/OCA/server-tools/tree/10.0/base_export_security
* https://github.com/OCA/server-tools/tree/10.0/base_import_match
* https://github.com/OCA/server-tools/tree/10.0/base_import_security_group

**Comment by fgi-odoo** [comment]
@LeartS the system should at least save the mapping when reloading the smae file (in case of mistake in the first import attempt). 
@RoelAdriaans-B-informed field labels have been improved in master, removing duplicates: https://drive.google.com/a/odoo.com/file/d/1gbY671Vq-OSi36Q0praIqJzz86ocHrOi/view?usp=drivesdk
@pedrobaeza what we want to improve at first is the general usability to ease initial imports. Those modules introduce new features, some of them being advanced (i.e. requiring some configuration).

**Comment by pedrobaeza** [comment]
@fgi-odoo OK, indeed it's new functionality, but very needed for general import/export managing IMO. Please consider them.

**Comment by PIERREHUMBLED** [comment]
I would appreciate to have the opportunity to empty a field by importing a "null" value.

**Comment by fclementic2c** [comment]
most important for me is that you can import 100 000 lines csv files.

*camptocamp*

INNOVATIVE SOLUTIONS
BY OPEN SOURCE EXPERTS

*Frédéric Clementi*
Project Manager
Business Solutions

+41 21 619 10 41

www.camptocamp.com


2018-02-27 14:38 GMT+01:00 PIERREHUMBLED <notifications@github.com>:

**Comment by bealdav** [comment]
I have added in the doc:
> In debug mode, you may want only see display the real field names in export wizard, not their strings, because real name field is unique by table, not the string one

**Comment by omalbastin** [comment]
When exporting data, it should be simple to export even if there are millions of record data to be exported

**Comment by ploegvde** [comment]
Import of large data files would also be mine first request. Chopin in smaller files manual is a not doable job mostly. So if Odoo can do a import of e.g. 500 lines, take a breath and continues with the next batch, until all is done. That would help us a lot.

**Comment by ploegvde** [comment]
Importing data based on a existing field. We often get the request to update prices of a product file, with e.g. EAN barcodes that we receive by mail. So if we could  update the price based on the EAN field as an example is great. Lot of trading companies are using a standard EAN product code or use the code of their vendor. Updating the prices becomes then much more easy.

**Comment by ploegvde** [comment]
When we want to update existing field by doing a import based on external ID, we often have to add some required fields to the import file (e.g. on product, the product name, if we only want to update price). Would be easier if that was not needed.

**Comment by fmdl** [comment]
**Export** 
- add the possibility to export in XML format
- add the possibility to export binary field (option)
See a module I was made to export in XML : xml https://github.com/OCA/server-tools/pull/1130, I generate data in Odoo then export to put in a module (data or demo data).

**Import**
- add the possibility to import in XML format
- add the possibility to import binary field (option)
- add the language flag on the field to import multilang (like that you can have col1 : name:fr_FR, col2 : name:en_US)

Importation sequence module:
On a form view you add importation line, in each importation line you choose the modele and the file (csv,xlsx,xml).
Like that you can prepare the importation sequence, make a test, and import.

**Security**
Add specifique right to Import/Export

**Comment by rvalyi** [comment]
You could also take a look to Akretion base_jsoniy module that exports data in JSON. This is what we use currently to export Odoo records into the Algolia NoSQL database for Shopinvader.
https://github.com/akretion/ak-odoo-incubator/tree/10-base_jsonify/base_jsonify

**Comment by fgi-odoo** [comment]
@PIERREHUMBLED you can actually do it, with both translated and original values.
@fclementic2c @ploegvde improving performance should be the next step. We all agree on the issue. Using scripts is still needed in too many cases.
@bealdav We fixed that issue in master by renaming most duplicates. I do agree that the debug mode should likely show the technical names as well. We will check that.
@ploegvde yes some specific objects (products, vendor pricelists) could be recognized based on more fields (barcode, internal ref, etc.). Regarding the update imports, resetting mandatory fields shouldn't be needed. Please give me the models where it happens so that we fix it.
@fmdl importing translations should be easier I agree.

**Comment by fhe-odoo** [comment]
I'd like a progress bar on the import (especially if it becomes possible to import tens of thousands of records). It should be doable since CSVs are handled line by line.
We can even imagine a sound at the end of the import and/or an email notification (if the import mechanism allows to kill the browser/turn off my computer before finishing in the background).

**Comment by abdallamohamed1992** [comment]
Please add progress bar for test import and import window

**Comment by adekock11** [comment]
I think both import and export should have the option of executing in the background. And I like the idea of receiving an email notification once the import or export has completed.

**Comment by gurneyalex** [comment]
1. manage timeouts : import can be killed by worker limits, but also by reverse proxy timeouts and this can result in duplicate imports because user retry. 

2. make reload button work again in the import screen (broken at least since 10.0)

3. make imports of record + o2m field support providing xmlid for the 'lines' (currently only works to update lines you cannot create lines).

**Comment by vcloud9ray** [comment]
I would love the ability to export records as XML.

This way I can create valid records via the UI, then export them into an XML file I can include in a module.

**Comment by fgi-odoo** [comment]
@gurneyalex I didn't experience any issue with the reload button. In anycase you can report a bug to odoo.com/help.
@vcloud9ray what you ask is only for expert users. The goal here is to improve the usability for any user. FYI, you can already export customizations made in Odoo Studio this way. This tool gives you a data module ready to install in any other database.

**Comment by bealdav** [comment]
@vcloud9ray @fgi-odoo Export as xml is the job of this one

https://github.com/OCA/server-tools/tree/10.0/module_prototyper

**Comment by gdgellatly** [comment]
For export it would be good to have a quick export. Basically what you see
on screen in a list view.

Other great things would be an export view, basically a preview list view
with search filters, column selection, and dynamic columns that exports all
matching records.

For import and also export security rules to restrict users and also log
exports for audit. Maybe even added to the current crud acls by model.

**Comment by BT-astauder** [comment]
Something that makes imports difficult are circular dependencies, e.g.
hr.employee needs a hr.department what needs a head of department that is an hr.employee.

Currently you can do this:
1) Import all departments without setting the head of department
2) Create all employees and set the department
3) Import all departments again, but now set the head of department

This is not that nice, because you have to split this up, it requires a good knowledge about the structure of the DB to do that and it is slower because you import hr_department twice.

The only way to resolve this problem is in fact to remove all database constraints, import and set the constraints again. When you do that in a transaction (not sure about that) the whole process should be save and would allow to have an incredible easy import:

Step 1: Importing hr.employee.csv:
__import__.person1,'Luc','__import__.hr_department_sale'

This creates an entry not only in hr_employee, but also an empty one in hr_department. In the same time '__import__.hr_department_sale' is saved as external reference to the new created hr_department entry.

Step 2: Importing hr.department.csv: Now you import all the data for the record '__import__.hr_department_sale'. You can set the head of department without any problems, because it already exists.

This workflow also works the same when you import first hr.department.csv. This would allow e.g. to create very easy import sheets, the client can fill out e.g. in google spreadsheets. It would be then a super easy to import them in a random order.

You see all consistency failures when you set the constraints in the DB again after the import. In case there is an error, you roll back the whole transaction.

**Comment by jvOrsouw** [comment]
I would like to easily make an export of the fields in a tree view, f.e. when exporting journal items, I would appreciate a default export template to be available so I don't have to go look for the fields. Or have the possibility to add the fields of the tree view with one click in the export-popup.
I also would like the possibility to update an existing export-template. Now, if I want to add a field to an existing export, I have to give it a new name, and delete the old one. If I accidentily give the new export the same name, I might delete the new export template in stead of the old one.
For import: a template with all / only mandatory fields would be helpful. At the moment, there are a few templates for the major items, I would like that to be expanded to more items

**Comment by fgi-odoo** [comment]
@gdgellatly yes a quick export is a good idea. We plan to do it, using the visible fields of list view.
@BT-astauder We want to allow to create unfound m2o or m2m records, with a checkbox showing up in the columns. This will considerably ease the import of master data covering several related objects. See in our prototype (last slide) https://app.moqups.com/fgi@openerp.com/fEZHhkGBbf/view
@jvOrsouw we work on new xls templates for master data, suggested when importing: contacts, products, product variants, sales and vendor pricelists, BoMs, employees, etc. The full list is in the specs https://pad.odoo.com/p/r.cd3cc8461f8fee493394916c724fb49a. If you think other templates are needed, let me know.

**Comment by CasVissers** [comment]
Would be nice that if an import fails the ID sequence is not increased.  Buy maybe I’m the only one that wants the first user to have ID 1.

**Comment by Yenthe666** [comment]
Agreed @CasVissers I too find it annoying that the sequence keeps going up even if it fails. But I guess we might be a bit OCD there. :)

**Comment by BT-astauder** [comment]
@fgi-odoo Sounds great! So for mandatory fields we do have to provide always a default value? Same to fulfill specific sql constraints? Otherwise it would be impossible to create this "empty" records. Here it would be nice to have e.g. a flag in the context to know in default_get() that it is called from a mass import.

**Comment by fhe-odoo** [comment]
@fgi-odoo When exporting, it would be really convenient if I could see an example of the value of the field I selected for export. The reason for this is that sometimes I export a field and I either get something different than what I wanted because the functional name in the export list was different than the one in the view, or I get some reference or id instead of the actual string I expected.
Ideally the example would be based on the first record I selected for export, or the first record that has a non-empty value for said field.

**Comment by nhomar** [comment]
completing what @fhe-odoo the column of the exported fields should have technical name [Huma readable name] - Example

**Comment by jvOrsouw** [comment]
What i'm missing is the possibility to clear fields by import: f.e. if by mistake on a product the field 'property_cost_method' has a value, the product no longer follows the cost method of the category it is in. I'd like to empty this field on the product, but can't do it manually (field not visible), but also not by import because 'false' is not a correct input, and by clearing the field, the input is not imported.

**Comment by Yenthe666** [comment]
@fgi-odoo what is the status of this? Did anything really happen with this?

**Comment by pedrobaeza** [comment]
@bealdav OCA module does that as an alternative.

**Comment by fgi-odoo** [comment]
It hasn't been done yet, as far as I know.

**Comment by Yenthe666** [comment]
So we're looking at V13 I assume? 😉

**Comment by CasVissers** [comment]
@fgi-odoo 
Something I forgot to mention here, would be very nice for service companies (big helpdesk users) to export datetime in user timezone.

**Comment by fgi-odoo** [comment]
This has been discussed many times, but it's quite tricky to do with the current framework. We keep this in mind for later though.
