### ISSUE TITLE
[11.0] Chart of Accounts Template: Incorrect Account Code for Cash Journal Account

### ISSUE THREAD

**Issue by SButko** [odoo/odoo#23414]
**Impacted versions:**

11.0

**Steps to reproduce:**

Create a COA Template with bank_account_code_prefix (leave cash_account_code_prefix empty). Load it. Automatically generated account (debit/credit) for cash journal will get an incorrect bank account prefix.

**Current behavior:**

Scheme:
bank_account_code_prefix, cash_account_code_prefix --> Account Code (Bank Journal), Account Code (Cash Journal)

Results:
1. False, False --> '1', '2' (OK)
2. False, 'TESTCASH' --> '1', 'TESTCASH1' (OK)
3. 'TESTBANK', False --> 'TESTBANK1', 'TESTBANK2' (BAD CODE GENERATED FOR CASH ACCOUNT)
4. 'TESTBANK', 'TESTCASH' --> 'TESTBANK1', 'TESTCASH1' (OK)

**Expected behavior:**

Scheme:
bank_account_code_prefix, cash_account_code_prefix --> Account Code (Bank Journal), Account Code (Cash Journal)

Results:
1. False, False --> '1', '2'
2. False, 'TESTCASH' --> '1', 'TESTCASH1'
3. 'TESTBANK', False --> 'TESTBANK1', '1'
4. 'TESTBANK', 'TESTCASH' --> 'TESTBANK1', 'TESTCASH1'

**Comment by csnauwaert** [comment]
Hello,

It would seems that this behavior was intended because a while ago we could not specify different prefix for cash account, and the prefix was the same for bank and cash. So when we added the feature we kept the previous behavior as we did not want to break all chart of accounts that only specified a prefix for bank account and were expecting the same prefix on both bank and cash.

We probably won't change that in a stable version as it would change the behavior of the feature but we can do it for the next version. Could you please tell us for which chart template do you need to have a bank account prefix and no cash prefix?

Best regards

**Comment by SButko** [comment]
Thank you for your answer.
We are building our own COA template and adding some tests which fail because of this issue.
