### ISSUE TITLE
[11.0][stock] - Wrong Picking creation using stock schedulers (Odoo's Ticket No. 1820226)

### ISSUE THREAD

**Issue by ougc27** [odoo/odoo#23441]
Impacted versions 
11.0

What are the steps to reproduce your issue?
I configured the stock module to use a multiple-step deliveries (Pick + Pack + Ship).

Case 1:
* Create a sale order with a stockable product.
* Confirm the sale order
* Cancel de sale order
* Run the stock scheduler.

Case 2:
* Create a sale order with a stockable product.
* Confirm the sale order.
* Validate the pick.
* Validate the pack.
* Validate the OUT.
* Run the stock scheduler.

What is the current behavior that you observe?
Case 1:
* The stock scheduler creates two stock pickings, one of pick operation and other of pack operation.

Case 2: 
* The stock scheduler creates two stock pickings, one of pick operation and other of pack operation but not of OUT operation. 

What would be your expected behavior in this case?
Case 1:
* The scheduler should not create any stock picking because my sale order is canceled so, I don't want deliver anything.

Case 2:
* The scheduler must create only the out picking to complete the delivery process of the sale order.

Video/Screenshot link (optional):
On this  [link](https://youtu.be/GooCFGOqSQ0) i have a video replying this issue.

Regards

**Comment by fmdl** [comment]
I confirme this issues. See https://github.com/odoo/odoo/pull/23458

cc @alnslang @sylvain-garancher

**Comment by amoyaux** [comment]
@ougc27 Yep it's a bug for case 1 and 2. However I do not agree with the expected behavior in second case and the PR of @fmdl do not create the missing moves neither (anyway thanks for the contributions).

This functionality comes from v10. In v10 you had an object procurement that could be with a state exception. For example you had a product with routes MTO and buy but no vendor(supplierinfo). In 10.0 it would create all the move except the receipt from supllier and since it can't find a supplier it would pass the procurement in state exception. The scheduler each day checked all the procurements in exception and try to run them again until it can process them(in our case if a user finally set a vendor on the product).

In v11 we removed the procurement and an error is directly raised if the moves's chain couldn't be totally created if the action comes from a user. A next activity is created with the error if the action comes from the scheduler(a reordering for example). No move at all are created if the MTO/RR moves's chain couldn't be completed.

Thus the scheduler should now only be responsible to log next activity on product with missing information in order to help the user to correct it. Once the error is corrected, the user can run the scheduler manually or wait the cron responsible for it, it should then create the complete move's chain.

In your case2 since you deleted manually the picking. You should be aware that there will be missing quantity for the customer and create a new picking(or better don't cancel it but use the backorder functionality). I agree that the system should help the user for it but we won't create a new move automatically since a user deleted it on purpose. Instead we should log a note or an activity on the SO (as we did in saas11-2).

**Comment by ougc27** [comment]
Hello @amoyaux 

Thank you for all the explanation and the fix PR. I agree with your opinion, the system only should help to the user to make more easier his job but not all his job.

I'll pull the new changes and I'll talk with my client to explain the correct process.
Thanks & Regards!
