### ISSUE TITLE
Critical Security Issue

### ISSUE THREAD

**Issue by hieuht817** [odoo/odoo#23462]
## Steps to reproduce:
1, Create user (A) with 
Administration: Access Rights
2. Create user (B) with
Administration: None
3. Login as user A

## Current behavior:
user A can edit user B to have Administration: Setting
## Expected behavior:
user A can not edit other user Administration to Setting
Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
@odony this is one for you.

**Comment by odony** [comment]
Well, that's the expected behavior. The "Access Rights" group is meant for users who are allowed to modify the groups and access levels of all other users, without restriction. Effectively these guys have full control of the database.
The difference between users with "Admin/Access Rights" and "Admin/Settings" is mostly in terms of usability, not privileges.

Note that preventing this action would make little sense with the current security model. Users with "Admin/Access Rights" can modify the ACL/Rules in the database, so they could give themselves (or others) full control on anything, any table, regardless of the actual groups they have. Bottom-line: you have to trust the admins.

**Comment by hieuht817** [comment]
So, Why user A, with Administration: Access Rights, can't set himself with Administration: Setting?

**Comment by odony** [comment]
> So, Why user A, with Administration: Access Rights, can't set himself with Administration: Setting?

They can, but it fails if they do it from the "User form", for a technical reason. The "User form" shows a selection drop-down, so when that form is saved, the user temporarily loses the "Access Rights" group while they get the "Settings" group instead. But the "WRITE" permissions on Users is only given to the "Admin/Access Rights" group.
So the user become unable to accomplish the second part of the change: re-add themselves to the "Access rights" group again because of the inheritance between these 2 groups.

This should be relatively obvious, as the error message complains about missing the "Admin/Access Rights" group, which the user was supposed to have...

These alternatives should work without error:
- add yourself to the Admin/Settings groups via the form view of the Group, not via the User form
- or add an extra Access Right entry to give "WRITE" permission to "Admin/Settings" group directly, not via inheritance

If you think this is a blocking problem, [please feel free to make a PR to fix it](https://github.com/odoo/odoo/wiki/Contributing#making-pull-requests) (adding the extra ACL entry should be the easiest option)

**Comment by hieuht817** [comment]
I'm sorry, I've not read it. But I'll do.
