### ISSUE TITLE
Work Orders and capacity

### ISSUE THREAD

**Issue by max3903** [odoo/odoo#23552]
Impacted versions:

11.0

Steps to reproduce:

* Create 2 users with the Manufacturing / User group
* Create products for a finished good and 4 parts
* Set tracking by serial number on the finished good and the parts
* Create a work center "Assembly" with a capacity of 2
* Create a routing with the previous work center
* Create a BOM for the finished good with the previous routing and the parts
* Create an inventory for the parts
* Create a Manufacturing Order for the finished good with a quantity of 4 and plan it
* As user1, go to the work order, start producing the first finished good and create the serial number "0001"
* In another browser, as user2, go to the same work order, start producing another finished good

Current behavior:

* user2 gets the serial number "0001" selected on his screen
* serial numbers of the parts chosen by user1 and user2 are mixed together on 0001

Expected behavior:

* user2 has no serial number and creates a new serial number "0002"
* serial numbers of the parts selected by user1 are on 0001
* serial numbers of the parts selected by user2 are on 0002

My capacity is 2 so I should be able to manufacture 2 finished goods in parallel with a correct traceability.

**Comment by jgrandguillaume** [comment]
Hi,


That's really an important issue... In short it means that Odoo is not capable to produce several products in parallel on a same work center when traceability is a requirement ! In a lot of area though, you have several people working on the same place and producing the same product..

We received an answer by email that the capacity is only here to compute the number of cycle necessary to produce the needed quantity.

How can we move forward on this one ?

Thanks in advance for your input,

Regards,

Joël

**Comment by amoyaux** [comment]
Hi,

Currently the capacity is only used in planning and report.
If you want to have multiple users working on the same operation for different finished product at the same time. The solution is to create duplicate work orders instead of creating a MO of 4 create 4 MO of 1 products. That will create 4 work orders of 1 and you users will be able to work in parallel.

(Same behaviour if you are using recursive BOM with MTO,... instead of using a bom line of 4, use 4 bom lines of 1.)

It's possible to create a custom addons in order to split the work orders depending the work center capacity however it's not in odoo standard.
The conclusion if that a user should be responsible for one workorder and don't work in parallel inside the same WO, thus you should try to create the same number of WO than the number of workman you have.

I hope this can help you,

Regards,

Arnold

**Comment by Yenthe666** [comment]
@amoyaux in short: this is the desired behaviour for Odoo and it will not be fixed/changed?

**Comment by amoyaux** [comment]
@Yenthe666 Yep

**Comment by Yenthe666** [comment]
Thanks for the feedback, I guess this can be closed then. Sorry guys.
