### ISSUE TITLE
[11.0][BUG] about stock barcode's problems with poor performance

### ISSUE THREAD

**Issue by sum1201** [odoo/odoo#23574]
Impacted versions:
11.0
Steps to reproduce:
[stock.move Poor performance when product have serial number](https://github.com/odoo/odoo/issues/22476)
[barcodes: Do not trigger useless onchange server side.](https://github.com/odoo/enterprise/commit/e709492887220d3c3fb35bcafa304441c4fe398c)

Thank you very much for the changes you have made for this, but it seems that you have not solved my previous question.

When I enter a barcode, the server triggers the onchange_serial_number method. When the number of products is very large, the performance here is very low. It usually takes 2 seconds before jumping to the next line.

![qq20180310-105507](https://user-images.githubusercontent.com/5398273/37237659-87c4509a-2451-11e8-99b3-d644895378d7.png)

https://github.com/odoo/odoo/blob/0ddcdb1315e96954c1193af550344921ff844a7a/addons/stock/models/stock_move_line.py#L110-L136

**I recommend deleting the onchange_serial_number method, which checks only when saving data to the database to improve performance.**

Current behavior:

Expected behavior:

Video/Screenshot link (optional):

**Comment by sum1201** [comment]
@amoyaux 
If you have time, please help. Thank you

**Comment by leangjia** [comment]
@amoyaux  +1

**Comment by lonelyleaves** [comment]
I have zhis problem,when the number of products is very large, the performance here is very low

**Comment by yaodongshi** [comment]
I also encountered this problem and hope to solve it

**Comment by wdmsyf** [comment]
I have same problem too.

**Comment by woodheadhn** [comment]
I also encountered this problem and hope to solve it

**Comment by amoyaux** [comment]
Dear,

You should try to use the scanner and scan the product barcode instead of use the 'register pack ,lot, locations' button on operation. It will open a specific wizard with improved perf for barcode scanning.

Could you try?

**Comment by sum1201** [comment]
@amoyaux 
I understand what you mean, but also consider the absence of a bar code device and the need to manually enter and select the serial number/batch number.

**Comment by amoyaux** [comment]
I checked and it seems more difficult than just removing the compute on stock.move.line Here are the flamegraph with and without the onchange. Also it does not show a lot of performance improvement neither in the browser. The flamegraphs show a lot of time in the framework itself. However I think that 2s for 500 move_lines with SN is okay (we do not consider this as a bug). Anyway we will not remove an onchange that will modify the behavior in a stable version. You can write some modules yourself in order to override them (do not call super) and thus bypass them. We will try to improve the performance in the future.

[onchange.zip](https://github.com/odoo/odoo/files/1802754/onchange.zip)
