### ISSUE TITLE
About www.transifex.com  account: e2f  translate error.

### ISSUE THREAD

**Issue by sum1201** [odoo/odoo#23720]
Impacted versions:
10.0
Steps to reproduce:
I loaded chinese po , found system can't login .
I found this error:
![qq20180317-093016](https://user-images.githubusercontent.com/5398273/37550301-d4b9b8da-29c5-11e8-99c2-34a1621173a4.png)

i found error at zh_CN.po,found it chang by e2f.
![e225dbb67385eeddca2d897e06c3d880](https://user-images.githubusercontent.com/5398273/37550313-09b3f76c-29c6-11e8-8bdd-c6923666d3b4.jpg)
![qq20180317-093337](https://user-images.githubusercontent.com/5398273/37550337-70b586e2-29c6-11e8-9e85-0eb1d5ff9ca3.png)

I have discovered several errors due to e2f translated entries.
How can we prevent such mistakes.
Current behavior:

Expected behavior:

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
Yeah, I also fix some translations coming from this user/service. @mart-e what is this mysterious user that is editing all languages?

**Comment by wtaferner** [comment]
@pedrobaeza 
It is a paid translator (service company) from Odoo to speed up translations...unfortunately sometimes they translate not really well :-) but yeah, at least they try to push forward here...someone needs to do it and it is still not easy to translate Odoo for normal users...I try to ask my customers to join and contribute (with my help for the review) as they are the one who are complaining most of the times ;-)

**Comment by pedrobaeza** [comment]
Well, although it's always welcome, then they at least shouldn't break Odoo with their translations...

**Comment by proloycoder** [comment]
Done is all .

**Comment by sum1201** [comment]
@mart-e 
How to prevent such errors?
The problems found so far are basically caused by %s.

**Comment by mart-e** [comment]
Hello,

Indeed e2f is a translation company we have paid to speed up the translations.
We have already worked with them and we are usually satisfied with their work. They ask a lot of clarifications about unclear context so I believe they are professional.
Due to the number of translations that were made, errors are unavoidable. We do see a lot of these %s missing in non-latin languages, it is unfortunately a common mistake, whoever the translator is.
We will however ask them to double-check the Chinese translation.

In case of similar mistakes that are detected. please comment on Transifex. You can ping the translator and [myself](https://www.transifex.com/user/profile/mart_e/) on the wrong term.

**Comment by mart-e** [comment]
And by the way, [fixed](https://github.com/mart-e/odoo-scripts/blob/master/transifex/sanitize-po.py) the wrong `%s` I found in the text at 6292600b8574bc730d0468d1b5bb00d8235d18de
I will see if we can integrate this in the synchronisation bot to avoid committing wrong translations.
