### ISSUE TITLE
[10.0][11.0] hr_payslip: sum() shouldn't consider the inputs of refunded Payslips

### ISSUE THREAD

**Issue by gustavovalverde** [odoo/odoo#23734]
#### Impacted versions:
10.0, 11.0

#### Steps to reproduce:
Create a rule using the `sum()` method, considering the last 12 months. 

#### Current behavior:
It sums all the payslips that have been refunded, which complicates any sum that requires legal amounts, as this would double the amount when a refunded payslip is inside the `sum `time frame.

#### Expected behavior:
If a payslip has been refunded, it means it was wrongly done, or the money was returned to the employeer, or any other reason that makes this payslip "special", and thus an exception in any calculation needed for legal reasons.

Special care has to bee taken here: https://github.com/odoo/odoo/blob/5ce76a0e7099c7da21787d6cfb82d3305678bfe0/addons/hr_payroll/models/hr_payslip.py#L255 as this is considering the "**done**" state on the payslip, but it does not consider the boolean `credit_note`.

cc: @tivisse as you've been working on the payslip lately.

**Comment by tivisse** [comment]
Hi @gustavovalverde 

It certainly looks like a bug. Could you please open a ticket (See: https://www.odoo.com/help) and also put the link to this issue on it ? 

It will be managed by our bug fix team. 

Thanks for the feedback and have a nice day,

Yannick.

**Comment by gustavovalverde** [comment]
Ticket 1830756

**Comment by nim-odoo** [comment]
Hello,

Can you please elaborate the use case? From what I can see, the piece of code you point to is used in case of "Other Inputs" are added in the payslip. However, when creating a refund, these lines are not copied on the refund (v10 & v11). So I don't really see the problem... (or maybe the problem is that the "Other Inputs" should be copied as well on the refund and then we need to manage them).

Thanks
