### ISSUE TITLE
Inconsistent retries in case of PostgreSQL Concurrency Error. Arguments modified between calls

### ISSUE THREAD

**Issue by jbaudoux** [odoo/odoo#23816]
In case of concurrency error raised by PostgreSQL, odoo retries the function call. However, the arguments are not copied between calls and if the arguments are modified during the first failed call, the second call is executed with a different arguments list content.
This causes the function to not behave as expected and leads to unexpected processing and committed data with inconsistent result.

Let me give you an example with the accounting, for instance the bank statement reconciliation. Have 2 lines for a same partner. At the end of the reconciliation, the last reconciliation date on the partner is updated. As the partner is read at the begin of processing the reconciliation, it will raise a concurrency access error when it tries to update the date on the partner if you reconcile the 2 lines at the same time. This can be performed by clicking OK in the reconciliation interface on the 2 lines, the reconciliation will start in background. In the reconciliation function call, the counterpart is given inside a dict argument. This is removed during the reconciliation processing. When the first call fails with a concurrent access error, it will be retried with the modified arguments and without counterpart. The bank statement line will be marked as reconciled, the moves are created but in fact the reconciliation entry is not created anymore and related invoice won't be marked as paid. By the way, it would be worth taking a lock for update on the partner at the beginning of processing the reconciliation.

**Comment by jbeficent** [comment]
What version?

**Comment by jbaudoux** [comment]
All versions 7,8,9,10,11

**Comment by StefanRijnhart** [comment]
Indeed, here is such a case https://github.com/OCA/OCB/pull/623

**Comment by manitra** [comment]
In version 11, we're running into random issues which might be caused by this kind of behaviour : 

- the partner field of journal entries generated by validated invoices are sometime undefined
- the document source field of delivery orders generated by sales orders are sometime undefined

@jbaudoux, could you point me to the lines of codes which makes Odoo to "retry the function call upon concurrency error please" ?

**Comment by sbidoul** [comment]
This issue is still present in 12 and 13. This can clearly lead to data corruption.

Here is an example with a stack trace. It occurs in reconciliation with VAT on payment which is a kind of reconciliation which generates journal entries which in turn can have contention on no-gap sequences.

Impacted versions: 12.0, 13.0, maybe others

Steps to reproduce:

This is hard to reproduce because you need to trigger a transaction retry following a postgres lock in `account.reconciliation.widget.process_bank_statement_line`.

Still I think this is an interesting bug :)

<details>
<summary>stack trace</summary>
<pre>
oct. 11 12:23:06 odoo01 odoo-prod[2759]: 2019-10-11 10:23:06,967 16763 INFO odoo-prod werkzeug: 127.0.0.1 - - [11/Oct/2019 10:23:06] "POST /web/dataset/call_kw/account.invoice/read HTTP/1.1" 200 - 103 0.852 0.167
oct. 11 12:23:06 odoo01 odoo-prod[2759]: 2019-10-11 10:23:06,507 8895 INFO odoo-prod odoo.service.model: LOCK_NOT_AVAILABLE, retry 1/5 in 0.7626 sec...
oct. 11 12:23:07 odoo01 odoo-prod[2759]: 2019-10-11 10:23:07,277 8895 ERROR odoo-prod odoo.http: Exception during JSON request handling.
oct. 11 12:23:07 odoo01 odoo-prod[2759]: Traceback (most recent call last):
oct. 11 12:23:07 odoo01 odoo-prod[2759]:   File "/home/odoo-prod/instance/venv-11.0.7/lib/python3.5/site-packages/odoo/http.py", line 656, in _handle_exception
oct. 11 12:23:07 odoo01 odoo-prod[2759]:     return super(JsonRequest, self)._handle_exception(exception)
oct. 11 12:23:07 odoo01 odoo-prod[2759]:   File "/home/odoo-prod/instance/venv-11.0.7/lib/python3.5/site-packages/odoo/http.py", line 314, in _handle_exception
oct. 11 12:23:07 odoo01 odoo-prod[2759]:     raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
oct. 11 12:23:07 odoo01 odoo-prod[2759]:   File "/home/odoo-prod/instance/venv-11.0.7/lib/python3.5/site-packages/odoo/tools/pycompat.py", line 87, in reraise
oct. 11 12:23:07 odoo01 odoo-prod[2759]:     raise value
oct. 11 12:23:07 odoo01 odoo-prod[2759]:   File "/home/odoo-prod/instance/venv-11.0.7/lib/python3.5/site-packages/odoo/http.py", line 698, in dispatch
oct. 11 12:23:07 odoo01 odoo-prod[2759]:     result = self._call_function(**self.params)
oct. 11 12:23:07 odoo01 odoo-prod[2759]:   File "/home/odoo-prod/instance/venv-11.0.7/lib/python3.5/site-packages/odoo/http.py", line 346, in _call_function
oct. 11 12:23:07 odoo01 odoo-prod[2759]:     return checked_call(self.db, *args, **kwargs)
oct. 11 12:23:07 odoo01 odoo-prod[2759]:   File "/home/odoo-prod/instance/venv-11.0.7/lib/python3.5/site-packages/odoo/service/model.py", line 97, in wrapper
oct. 11 12:23:07 odoo01 odoo-prod[2759]:     return f(dbname, *args, **kwargs)
oct. 11 12:23:07 odoo01 odoo-prod[2759]:   File "/home/odoo-prod/instance/venv-11.0.7/lib/python3.5/site-packages/odoo/http.py", line 339, in checked_call
oct. 11 12:23:07 odoo01 odoo-prod[2759]:     result = self.endpoint(*a, **kw)
oct. 11 12:23:07 odoo01 odoo-prod[2759]:   File "/home/odoo-prod/instance/venv-11.0.7/lib/python3.5/site-packages/odoo/http.py", line 941, in __call__
oct. 11 12:23:07 odoo01 odoo-prod[2759]:     return self.method(*args, **kw)
oct. 11 12:23:07 odoo01 odoo-prod[2759]:   File "/home/odoo-prod/instance/venv-11.0.7/lib/python3.5/site-packages/odoo/http.py", line 519, in response_wrap
oct. 11 12:23:07 odoo01 odoo-prod[2759]:     response = f(*args, **kw)
oct. 11 12:23:07 odoo01 odoo-prod[2759]:   File "/home/odoo-prod/instance/venv-11.0.7/lib/python3.5/site-packages/odoo/addons/web/controllers/main.py", line 962, in call_kw
oct. 11 12:23:07 odoo01 odoo-prod[2759]:     return self._call_kw(model, method, args, kwargs)
oct. 11 12:23:07 odoo01 odoo-prod[2759]:   File "/home/odoo-prod/instance/venv-11.0.7/lib/python3.5/site-packages/odoo/addons/web/controllers/main.py", line 954, in _call_kw
oct. 11 12:23:07 odoo01 odoo-prod[2759]:     return call_kw(request.env[model], method, args, kwargs)
oct. 11 12:23:07 odoo01 odoo-prod[2759]:   File "/home/odoo-prod/instance/venv-11.0.7/lib/python3.5/site-packages/odoo/api.py", line 745, in call_kw
oct. 11 12:23:07 odoo01 odoo-prod[2759]:     return _call_kw_model(method, model, args, kwargs)
oct. 11 12:23:07 odoo01 odoo-prod[2759]:   File "/home/odoo-prod/instance/venv-11.0.7/lib/python3.5/site-packages/odoo/api.py", line 718, in _call_kw_model
oct. 11 12:23:07 odoo01 odoo-prod[2759]:     result = method(recs, *args, **kwargs)
oct. 11 12:23:07 odoo01 odoo-prod[2759]:   File "/home/odoo-prod/instance/venv-11.0.7/lib/python3.5/site-packages/odoo/addons/account/models/reconciliation_widget.py", line 37, in process_bank_statement_line
oct. 11 12:23:07 odoo01 odoo-prod[2759]:     aml_dict['move_line'] = AccountMoveLine.browse(aml_dict['counterpart_aml_id'])
oct. 11 12:23:07 odoo01 odoo-prod[2759]: KeyError: 'counterpart_aml_id'
</pre>
</details>

Current behavior:

KeyError on `counterpart_aml_id` at [this line](https://github.com/odoo/odoo/blob/1e012dda76601437659b640b389fe2b73b6cbb3b/addons/account/models/reconciliation_widget.py#L38).

Expected behavior:

No KeyError. 

Analysis:

This is most probably due to the [del at line 39](https://github.com/odoo/odoo/blob/1e012dda76601437659b640b389fe2b73b6cbb3b/addons/account/models/reconciliation_widget.py#L39) which modifies the `data` argument of the method. At first glance the del is *after* the place where the key is used. But when Odoo does a transaction retry with the same `data` object that has been modified, the expected key is not present anymore.

A local fix should consist in not modifying `data`.

On a more fundamental level, one could think about doing the [transaction retry](https://github.com/odoo/odoo/blob/89270ee39c0daa46ae8e2e3e57d7e512a1a65ddf/odoo/service/model.py#L95-L110) at higher in the call stack, based on immutable serialized input arguments, and not on arguments that may have been modified by the business logic. Or doing a deep copy of the arguments before calling the retryable function.

**Comment by sbidoul** [comment]
OPW 2085822
