### ISSUE TITLE
Not using CDN for qweb t-field with t-options using widget image

### ISSUE THREAD

**Issue by aek** [odoo/odoo#23811]
Impacted versions:
tested with 10 and possibly happening(not sure) 11 and master
Steps to reproduce:
Activate CDN as described in the [Docs](https://www.odoo.com/documentation/10.0/setup/cdn.html)
Look at some website page that has this kind of qweb code using t-field and t-options with widget = image
You could find and example in the /shop url for the website_sale module. Specifically use this code as example:
```
<span itemprop="image" t-field="product.image" t-options="{'widget': 'image', 'class': 'product_detail_img', 'alt-field': 'name', 'zoom': 'image'}" groups="!website_sale.group_website_multi_image"/>
```
Current behavior:
It generates this code kind of:
```
<span itemprop="image" alt="Product Name">
    <img class="img img-responsive" src="/web/image/product.template/20/image/300x300?unique=96dece9" data-zoom="1" data-zoom-image="/web/image/product.template/20/image/300x300"/>
</span>
```
Expected behavior:
It should generate it with the cdn url included(at least the img src attr) like:
```
<span itemprop="image" alt="Product Name">
    <img class="img img-responsive" src="//d23atan1rmviow.cloudfront.net/web/image/product.template/20/image/300x300?unique=96dece9" data-zoom="1" data-zoom-image="/web/image/product.template/20/image/300x300"/>
</span>
```
Related to: https://github.com/odoo/odoo/issues/22878

The issue could be easily solved by adding the CDN conversion URL at:
https://github.com/odoo/odoo/blob/10.0/addons/web_editor/models/ir_qweb.py#L298

Or at the website module where the CDN features are handled

**Comment by Yenthe666** [comment]
@jke-be I know you where working on CDN and that there is a PR for similar things. Can you check and integrate?

**Comment by JKE-be** [comment]
We don’t plan to improve it in v10.
But it has been improved and this case will be handled with the new branch about cdn from Chm in the saas-11.(3|4) and so v12.

Thanks for the reporting

**Comment by aek** [comment]
No problem, I have a module for that already working. But Odoo 10 it's not still under support?
Also I found this line very restrictive for cdn features
https://github.com/odoo/odoo/blob/11.0/addons/website/models/website.py#L569
I have also changed that in my custom module to get everything working better.
Another issue that I have found is that there is no clear way to match font definitions with @font-face urls other than manually change it in the file. Maybe a CSS and LESS preprocessor could change that?
Should I create this in a separated issue since this one is already closed?
I don't think that a future and non-existing branch that probably will solve this issue and closing should be a way to manage this one, it's just a way of losing track of features and bug reports while keeping open issues number low.
I think that a Merged Pull Request should be the starting point to close all the related pending issues with the proper references to the code that solve things

**Comment by Yenthe666** [comment]
@aek if I'm not mistaking they make internal tasks for these kind of things. That is the Odoo management system, we just can't access/see it

**Comment by JKE-be** [comment]
> No problem, I have a module for that already working. 

Nice, maybe it could be interesting to publish it to help other guys who would like support CDN on IMG and that can take the risk to change their production code for a better use of CDN. Or maybe propose a clean PR?

> But Odoo 10 it's not still under support?

Yes, it is supported (until v13 released in ~ 1,5 years), but in this case, it is more an improvement than an issue. Your website works, assets, js, css... are loaded by CDN, but that true that image will be cool, but this feature is unfortunately not supported/broken in v10 until now. But the risk to add new bug adding this feature is probably biggest than the bug fixed itself.

> Also I found this line very restrictive for CDN features
> https://github.com/odoo/odoo/blob/11.0/addons/website/models/website.py#L569
> I have also changed that in my custom module to get everything working better.Yes, it is a historic line 

That could probably be removed. It has been already removed in the PR.

> Another issue that I have found is that there is no clear way to match font definitions with @font-face urls other than manually change it in the file. Maybe a CSS and LESS preprocessor could change that?

Thanks for the reporting, I don't think that we have fixed it. (@Gorash !!!)

> I don't think that a future and non-existing branch that probably will solve this issue and closing should be a way to manage this one, it's just a way of losing track of features and bug reports while keeping open issues number low.

Here the branch: https://github.com/odoo/odoo/pull/23745, so please don't imagine that we lose our time to close issue without reason.

> I think that a Merged Pull Request should be the starting point to close all the related pending issues with the proper references to the code that solve things.

Yes, but since the PR exists already, and there is no direct link to this issue. The result will be most than probably that this issue will be forgotten in the pipe of +1000 issues. And I don't see a PR from you that is related to this issue.
And yes, GitHub is able to close directly an issue, when the PR marks it as closed AND that you push the branch in the actual stable version; so if we push in the master, the PR will be not closed anyway!

**Comment by aek** [comment]
> Here the branch: #23745, so please don't imagine that we lose our time to close issue without reason.

Thanks for the reference to the branch. I don't imagine anything, I just misunderstood the fact that the branch already exists, sorry for that, my mistake but I think that always is a good practice to log some info related to where to find the solution/branch/commit/PR for the future searches and people with looking for the same.

**Comment by aek** [comment]
Today I realize that the images src of the mail.template inserted using the HTML editor are not using the CDN configuration. I know that CDN stuffs are added with the website module but perhaps this could be something that fits better into website_mail module
I think that the CDN URL could be used and inserted for generated emails like here:
https://github.com/odoo/odoo/blob/11.0/addons/mail/models/mail_thread.py#L1760
Would that make sense or I am missing something?
