### ISSUE TITLE
[11.0] Shop, eCommerce categories and attribuite filter in mobile view doesn't work

### ISSUE THREAD

**Issue by newodoo** [odoo/odoo#23864]
Impacted versions:
Odoo11 verified with runbot

Steps to reproduce:
-Create at least 2 product with common attribute
-Enable "eCommerce Category" in shop from Customize menu(them Will be visible in desktop and mobile view)
-Enable "Attributes filter" from Customize menu(them Will be visible in desktop view but not in mobile view, and also the category filter will disappear)

Current behavior:
In mobile view is not possible to show e-commerce category and attributes filter inside the shop page

Expected behavior:
Should be possible, as in desktop mode, allow to the customer to filter for both e-commerce category and products attributes

Video/Screenshot link (optional):

**Comment by alexkuhn** [comment]
This is a design choice to not display attributes filters in mobile, in order to not overload the panel on top of the product lists.

However, it is not intended that categories become hidden when attributes filters is set:
It occurs because both settings share the same `<div id='products_grid_before'>`, and we disable attributes filters in mobile by hiding this DOM element.

We won't fix this issue in v11, because it will likely break lots of customisations relying on this template.

In order to display attributes filters in mobile, you can remove `hidden-xs` in the following line:
https://github.com/odoo/odoo/blob/11.0/addons/website_sale/views/templates.xml#L358

You can also make this change in `/shop`: https://drive.google.com/file/d/18PyS1r5MCWBDAfmtuBUGRLTDc92gkJB4/view?usp=sharing

**Comment by Yenthe666** [comment]
@alexkuhn will we see a PR/commit for master though? We can fix this now in master before it gets lost, right?

**Comment by alexkuhn** [comment]
Ok, will prepare a fix in master soon!

**Comment by Yenthe666** [comment]
Thanks 😉

**Comment by newodoo** [comment]
Can I suggest to insert all attributes filters inside a collapsable element? Considering a catalog with a lot of products and variant, without attributes filter the mobile version is almost useless...

**Comment by pkrulz** [comment]
Has this issue been fixed in v12 ? The live version does not show categories or attribute filter in mobile view yet

**Comment by alexkuhn** [comment]
@pkrulz It hasn't been fixed in v12.
There's a 1 year-old PR (https://github.com/odoo/odoo/pull/24193) that fixes this issue in master, but it hasn't been approved until now.

**Comment by pkrulz** [comment]
Can we do the changes ourselves in the CSS and HTML. When I tries changing the category id tag in HTML  ... saving it caused a server error
