### ISSUE TITLE
[11.0] Inverse fields computation not triggered on the fly

### ISSUE THREAD

**Issue by pedrobaeza** [odoo/odoo#23891]
Impacted versions: 11.0

Steps to reproduce
===============

* Define a computed + regular field this way
```python
field_regular = fields.Float()
field_computed = fields.Float(
    compute="_compute_field_computed",
    inverse="_inverse_field_computed",
)

@api.one
@api.depends('field_regular')
def _compute_field_computed(self):
    self.field_computed = self.field_regular

@api.one
def _inverse_field_computed(self):
    self.field_regular = self.field_computed
```
* Add both fields to a view

Current behavior
=============
* Changing the value in `field_computed` doesn't update `field_regular` on the view.
* `_inverse_field_computed` is not called.
* When saving, the inverse method is called, but as `field_regular` contains the previous value, it doesn't work.

Expected behavior
===============
The contrary on alls points.

**Comment by pedrobaeza** [comment]
@ged-odoo I think this one is something on the web client part. Looking at the sent requests, on v10 that this was working, there are 2 calls more:

v10
===
![seleccion_004](https://user-images.githubusercontent.com/7165771/37926231-13a5194a-3137-11e8-857b-96b726754030.png)

v11
===
![seleccion_005](https://user-images.githubusercontent.com/7165771/37926247-227dc624-3137-11e8-9303-d7dd574ce81a.png)

but maybe is just an optimization of the web stack.

You can exercise the problem in this PR: https://github.com/OCA/contract/pull/152/files#diff-39922e75864d913d6612875e7bcbce42R56. The suspect about web client is because tests on server side are working correctly (https://github.com/OCA/contract/pull/152/files#diff-8b8162cf7b037d9ef8f62464d0c4c7c5R62).

**Comment by mart-e** [comment]
Hi Pedro,

Are you sure about this one? I tried on the inverse of the calendar fields and it was correctly updated on the fly.
https://github.com/odoo/odoo/blob/8327b67cf5498a1d9d133ec02f0e7619c4ce26d1/addons/calendar/models/calendar.py#L756-L759

Are you sure there is not some additional parameters or other conditions from the view?

**Comment by pedrobaeza** [comment]
Let me check again. Maybe the trees don't let me see the forest...

**Comment by pedrobaeza** [comment]
I see that you have edited the comment, so my comment was referring to the previous one. About the question: `Are you sure about there is a difference between v10 and v11?` I have this working on v10, but not on v11. Please check https://github.com/OCA/contract/pull/133 that adds this feature (in concrete, the inverse line is in https://github.com/OCA/contract/pull/133/files#diff-39922e75864d913d6612875e7bcbce42R98).

**Comment by rco-odoo** [comment]
@pedrobaeza the `onchange` method never calls inverse methods on fields. It simply was not meant to be that way. Therefore your proposal is clearly a behavior change.

To be more complete, doing what you propose is generally not a good idea. I have thought about that idea before, you know :wink:. There is a fundamental difference between compute methods and inverse methods:
* Compute methods should only read data, which is usually efficient thanks to the field prefetching mechanism. Assignments in compute methods are not an actual updates, they only modifie the cache.
* Inverse methods, on the other hand, are expected to update data. They should therefore be written to be efficient: use `write` on record batches, etc. Using assignments is usually inefficient, because each assignment is one call to `write`.
* Onchange methods are actually closer to compute methods. Assignments in onchange methods only modify the cache.

By the way, you can simply add `@api.onchange('field_computed')` on top of your inverse method to get it working with onchanges...

**Comment by pedrobaeza** [comment]
Thanks for the tip about the `onchange` on the field. Indeed, we can make several operations in inverse methods, like creating extra records, modify other records in other models... so it's logical to not call that inverse methods on the fly. Now I understand that my case was a very limited one for inverse method.

In v10 any way it was working that way, so we can consider this an improvement for avoiding side effects, hehe.

Thanks again!

**Comment by Frakenz** [comment]
> By the way, you can simply add `@api.onchange('field_computed')` on top of your inverse method to get it working with onchanges...
Doing this calls on the write function twice, once for the `onchange` (on edit) and one for the `inverse` (on save).
This doesn't solve my issue because the second call is overwriting some of my changes. Maybe it's my fault because my `inverse` function is not trully the f<sup>-1</sup> of my `compute` function.
Am using v13.

**Comment by Jny-z** [comment]
> > By the way, you can simply add `@api.onchange('field_computed')` on top of your inverse method to get it working with onchanges...
> 
> Doing this calls on the write function twice, once for the `onchange` (on edit) and one for the `inverse` (on save). This doesn't solve my issue because the second call is overwriting some of my changes. Maybe it's my fault because my `inverse` function is not trully the f-1 of my `compute` function. Am using v13.

I also have the same problem in odoo v17 i have a inverse function to set the price_unit field inside the purchase.order.line i used this function with @api.onchange() method but it calculates whever the field updates it leads to some minor miscalculations is there anything to avoid these issues if you know can you guide me
