### ISSUE TITLE
Manual Journal Entries in Bank Journal Are not reconcilable in bank statement 

### ISSUE THREAD

**Issue by seyed-mohammad-motahar** [odoo/odoo#23895]
Impacted versions:
11e and 10e

Steps to reproduce:
Go to runbot
Create 214100 Payroll Accruals Payable with the type of : Current Liabilities
Go to journal entries and create below transactions 

Account                                                     label                  debit             credit
214100 Payroll Accruals Payable            Salary-July          10,000         
101401 Bank                                             Salary-July                              10,000

post the journal and now go to the bank and create below entry in your bank statement:

Name : July Statement
Transaction : 
 
Date: 7/31/2017    
label   : WITHDRAWAL ONLINE MULTI 1084620 PYMT MANUAL group C - Salary Jul17 
Amount -10,000

click on save button and then click on reconcile. There is nothing to reconcile ! 
-

Current behavior:
Odoo ignores all manual journal entries created against the bank ledger. 

Expected behavior:
It should be possible to post journal entries in bank journal for none customer supplier payments like salary related entries or inter company transactions. Right now Odoo doesn't accept any of those. 

Video/Screenshot link (optional):
![transaction3](https://user-images.githubusercontent.com/4558819/37947387-5911b78c-31bd-11e8-8129-328cd13d1a91.png)

**Comment by pedrobaeza** [comment]
This is a design decision for avoiding to have a lot of "ghost" entries when you mass-import your account entries. See https://github.com/odoo/odoo/issues/18972#issuecomment-324619264

@qdp-odoo is there any news regarding this thing? A new mechanism for v12 that allows somehow this? I'm thinking in a simple flag at account.move.line that allows to discard the lines.

**Comment by qdp-odoo** [comment]
@seyed-mohammad-motahar as Pedro explained, we're currently bound to that design and cannot change it easily. 

@pedrobaeza not yet done, but we plan to use the 1st year opening entry date (can already be set in the configuration bar steps in v11, step 'INITIAL BALANCES') to discard all blue lines from the bank reconciliation widget with a older date.

That way, we would have another mean to control the problematic lines and we would be able to remove that problematic part of the domain that hides manual entries on the bank account... 

Well, that's just an idea from now but I suppose it'd do the trick... In the meanwhile, I'm closing the issue. Thanks for your understanding

**Comment by pedrobaeza** [comment]
Yeah, that date can be another good option. Let's hope it lands in v12. I have to propose you something more for v12, hehe, but I'll tell you in another issue.

**Comment by seyed-mohammad-motahar** [comment]
@pedrobaeza  I think the best workaround is to use voucher module. 

Just for anyone who might get in here, The process is to use the customer receipts to record a payment that debits the bank and mark the payment to "Pay Now" (NOT pay later). 

Using this method of debiting / crediting the bank, Entry will be visible in the bank reconciliation to tick off. 

Regards,
Mohammad

**Comment by qdp-odoo** [comment]
for the record: we've improved master to be able to filter out blue lines older than a threshold that can manually be set (I've no idea why a used a new setting instead of reusing the date of the opening move.... can't remember :expressionless: ).

Related commits are https://github.com/odoo/odoo/commit/3de75211744de22d78f0dceb270d196c8aeea8a3 and https://github.com/odoo/enterprise/commit/1aaa7d175a6e1c110b68dbd8be425b04744f9e1c

**Comment by pedrobaeza** [comment]
Thanks for the follow-up!

**Comment by markradabaugh** [comment]
I know you guys are trying to dumb this down so that not everyone needs to be an accountant but seriously - real accountants use journal entries all the time.   Intentionally breaking the ability to reconcile journal entries with a bank account is bizarre.

**Comment by JJebara** [comment]
Hi Everyone, we have the same problem and filter you are referring to does NOT fix the several issues were are having. You are simply filtering out transactions less than a certain date.  The manner to fix this is to fix https://github.com/odoo/odoo/blob/c023d0784f27622f185a1075cba8e408067b5352/addons/account/models/account_bank_statement.py#L495

Specifically 
OLD CODE WITH COMMENTS: (CHECK OUT THE  NEW CODE BELOW)
def _get_common_sql_query(self, overlook_partner = False, excluded_ids = None, split = False):
# Acc_type should be commented out, because the reconcile flag is ONLY for AP and AR accounts, if Bank accounts are set with reconcile, all the bank transactions will show under manual reconcile account !!! which is a problem There is a difference between Reconcile a bank account and reconciling AR or AP accounts
# The Bank Accounts Reconcile = Matching GL transactions to external imported statements to find differences 
# AP / AR RECONCILE = MATCHING Invoices to payments or Bills to payments. 

     
     
#        acc_type = "acc.reconcile = true"
        select_clause = "SELECT aml.id "
        from_clause = "FROM account_move_line aml JOIN account_account acc ON acc.id = aml.account_id "
        account_clause = ''
        if self.journal_id.default_credit_account_id and self.journal_id.default_debit_account_id:
# the select statment should replace aml.account_id IN %(account_payable_receivable)s AND aml.payment_id IS NOT NULL with aml.account_id = account id on the statement or journal id. 
            account_clause = "(aml.statement_id IS NULL AND aml.account_id IN %(account_payable_receivable)s AND aml.payment_id IS NOT NULL) OR"



        where_clause = """WHERE aml.company_id = %(company_id)s
                          AND (
                                    """ + account_clause + """
                                    
                                    OR
                                    
                                    
                                    ("""+acc_type+""" AND aml.reconciled = false)
                          )"""
        where_clause = where_clause + ' AND aml.partner_id = %(partner_id)s' if self.partner_id else where_clause
        where_clause = where_clause + ' AND aml.id NOT IN %(excluded_ids)s' if excluded_ids else where_clause
        if split:
            return select_clause, from_clause, where_clause
        return select_clause + from_clause + where_clause
======

NEW simplified CODE. 
def _get_common_sql_query(self, overlook_partner = False, excluded_ids = None, split = False):
# Change the from clause to restrict the transactions to ONLY transactions relevant to the bank or credit card we are reconciling from the journal id, by linking the account to the bank account of the journal. 
# When reconciling AP and AR odoo fills in reconcile = true and full_reconcile_id in account_move_line
# when reconciling bank statement , odoo sets the statement id and statement_line_id in account_move_line   
# the select statment should replace aml.account_id IN %(account_payable_receivable)s AND aml.payment_id IS NOT NULL with aml.account_id = account id on the statement or journal id. 

        select_clause = "SELECT aml.id "
        from_clause = "FROM account_move_line aml JOIN account_account acc ON acc.id = aml.account_id Join account_journal jrnl on jrnl.bank_account_id = aml.account_id "
        account_clause = ''
        if self.journal_id.default_credit_account_id and self.journal_id.default_debit_account_id:
            account_clause = "(aml.statement_id IS NULL"
        where_clause = """WHERE aml.company_id = %(company_id)s
                          AND (
                                    """ + account_clause + """)"""
        where_clause = where_clause + ' AND aml.partner_id = %(partner_id)s' if self.partner_id else where_clause
        where_clause = where_clause + ' AND aml.id NOT IN %(excluded_ids)s' if excluded_ids else where_clause
        if split:
            return select_clause, from_clause, where_clause
        return select_clause + from_clause + where_clause

**Comment by JJebara** [comment]
Sorry for the big bold letters. I pasted from text with "#" .. I think that applied Header format.

**Comment by JJebara** [comment]
We just need to restrict the transaction to the bank account the journal is liked to and we get ONLY to see the posted transactions, that have no statement id linked to them, that belong to the account we are reconciling.
