### ISSUE TITLE
AssertionError: Ran out of data to read in odoo.sh

### ISSUE THREAD

**Issue by salmankh334** [odoo/odoo#23928]
Impacted versions: v11

Steps to reproduce:

Current behavior:

Expected behavior:

Video/Screenshot link (optional):
![odoo_sh](https://user-images.githubusercontent.com/22784513/38045280-fd8065a8-32d9-11e8-9b76-746805e9b650.png)

**Comment by pedrobaeza** [comment]
Please provide more information about how to get the error.

**Comment by salmankh334** [comment]
We have created a custom module for brand based pricelist. After the development in our local system we tried to push it  to the odoo.sh and got some error in the query which we have used in the pricelist model. After correcting that we again tried to push it and it is showing like this.

**Comment by pedrobaeza** [comment]
Well, this is about odoo.sh, so this issue tracker is not exactly for that. @Yenthe666 do you know how to proceed here?

**Comment by Yenthe666** [comment]
Hi @salmankh334,

Thanks for the report. You should report these through the official support channel at Odoo.com/help though.
Judging by the traceback I'm assuming that your module is failing one of the tests. Usually this happens when you miss a module dependency or when you're working with website themes.
@dbo-odoo perhaps you could have a look though? 

Regards, 
Yenthe
