### ISSUE TITLE
Stock move state when purchase request (line) is deleted or cancelled

### ISSUE THREAD

**Issue by max3903** [odoo/odoo#23927]
Impacted versions:

11.0

Steps to reproduce:

* Configure your warehouse with 2 steps receiving
* Create a MTS product with a reordering rule and a vendor
* Run the scheduler
* Cancel the purchase request
  * or delete the purchase request
  * or delete the purchase order line

Current behavior:

* The stock move from input to stock is in state 'Waiting for another operation'

Expected behavior:

* The stock move from input to stock is in state cancelled or deleted.

**Comment by pimodoo** [comment]
fuxed in rev https://github.com/odoo/odoo/commit/7560bb7f42e82da0bd6f7ca8b0f4bc02979157b8

**Comment by max3903** [comment]
@pimodoo Your fix do not work. I cancelled the purchase request and the stock move from input to stock is still in state 'Waiting for another operation'.

Additionally here are other scenario that can help you:

1. Reordering rule →Request Procurement →PO → Confirm PO → Cancel the Receipt → Putaway is cancelled? Yes → :+1: 
2. Reordering rule →Request Procurement → PO with 100 → Change quantity to 80 → Confirm PO → Qty in putaway? 100→:-1:
3. Reordering rule  →Request Procurement→ PO → Remove PO line → Confirm PO → Line removed in putaway? No→:-1:
4. Reordering rules →Request Procurement → 2 PO → Confirm 2 PO → 1 putaway with all lines? Yes →:-1:
5. Create PO manually→ Confirm PO → Cancel the Receipt → Putaway is cancelled? Yes  → :+1: 
6. Create PO manually with 100 → Change quantity to 80 → Confirm PO → Qty in putaway? 80  → :+1: 
7. Create PO manually→ Remove PO line → Confirm PO → Line removed in putaway? Yes  → :+1: 
8. Create 2 PO manually→ Confirm 2 PO → 1 putaway with all lines? No, 2 putaway  → :+1:

**Comment by pimodoo** [comment]
@lap-odoo Could you give us your feedback about what can be done functionally to handle the not supported cases. Thx

**Comment by max3903** [comment]
@pimodoo 

I was expecting:

2. Qty in Internal Transfer? 80
3. Line removed in Internal Transfer? Yes
4. 1 Internal Transfer with all lines? No, 1 Internal Transfer per PO

**Comment by pimodoo** [comment]
Hello,

Thank you for your feedback, but from a functional point of view, we cannot support your three following case:
2: the difference, than when a PO is manually created, is that a reordering rule creates a procurement in a specific location, here in stock, that will create the move from Input -> Stock, and then the request for quotation to fulfill, what you need in Input -> Stock. In your case it's a RFQ, but in some other case, it can be another move from another warehouse. So decreasing you PO, doesn't change the fact that you said (with your reordering rule) that you need 100 pieces in stock, even if you decreased you PO to 80.
3: This is the exact same answer as for point 2.
4: The moves are grouped, in picking depending on their procurement group. When you create a PO manually, a procurement group is generated and propagated to all created moves from the PO. In the case a PO is generated from a reordering rule, the move from Input to Stock is created before the PO, and has the procurement group set on the reordering rule. By default the procurement_group of an order point is False, and that's why they are all merged in the same picking. You can changed the group_id on you reordering rules to group your pickings from internal to stock differently.

Best regards

**Comment by max3903** [comment]
@pimodoo Thanks @pimodoo. Setting the group_id seems to have the behavior we expect.

**Comment by max3903** [comment]
@pimodoo 

I have set a different group for each reordering rule. 

I ran the scheduler → I get 2 pickings from Input to Stock for 2 products →Those 2 products are purchased to the same supplier →1 PO→I confirmed the PO→I get 1 receipt for the 2 products, but I still have 2 pickings from Input to Stock.

Once the PO is confirmed, would it be possible to merge those 2 pickings together? and set the origin and procurement group to the PO one? This way we would have the same behavior whether the PO is created manually or from the rules. What do you think?

CC: @jgrandguillaume

**Comment by pimodoo** [comment]
@max3903 Hello, such a thing is actually not possible in Odoo.

**Comment by max3903** [comment]
@pimodoo Why not?
