### ISSUE TITLE
[bug] PurchaseRequisition had canceld ,but  procurement order not cancel

### ISSUE THREAD

**Issue by sum1201** [odoo/odoo#23977]
Impacted versions:
10.0
Steps to reproduce:

- create a product :test,
      routes: buy
      Procurement: Propose a call for tenders
- I create  a sale order , run mrp ,system can create  a procurement order , a purchase requisition..
     procurement order: OP/00006  state:running
     purchase requisition: TE00006 state :draft
-  i cancel this purchase requisition, but procurement order not canceled.
     procurement order: OP/00006  state:running
     purchase requisition: TE00006 state :draft

Current behavior:

Expected behavior:

I think  purchase requisition had canceled, it's procurment order shoud be canceled.

Video/Screenshot link (optional):
![qq20180401-194201](https://user-images.githubusercontent.com/5398273/38172843-1e5a9bfe-35e6-11e8-8369-3f7e4daa98a0.png)
![qq20180401-194519](https://user-images.githubusercontent.com/5398273/38172844-213b0386-35e6-11e8-9c5c-72980bedcd35.png)
![qq20180401-195035](https://user-images.githubusercontent.com/5398273/38172847-2569f57a-35e6-11e8-8135-7269ca8e0974.png)

**Comment by sum1201** [comment]
enterprise ticket 1833290

**Comment by Yenthe666** [comment]
Dear @sum1201,

As Odoo 13 has been released last week it means that our support for Odoo version 10 has been stopped.
If you can still reproduce this issue on a newer version (version 11, 12 or 13 at the point of writing) then please do respond back or create a new issue.
Sorry that we didn't get around to resolving your issue here but you should've gotten a good response on the enterprise ticket.

Regards,
Yenthe
