### ISSUE TITLE
Consider reconcilable accounts in AR/AP reports

### ISSUE THREAD

**Issue by mohamedhagag** [odoo/odoo#23976]
Impacted versions: 9, 10, 11

Steps to reproduce:
set an account as reconcilable and create a transaction with a credit or debit party

Current behavior:
when printing partner ledger or other AR/AP reports the amount of credit/debit on the other party will not show in the report.

Expected behavior:
the debit / credit amount should show in the report of partner_ledger even though the account type is not payable/receivable for **reconcilable** accounts .

Video/Screenshot link (optional):

**Comment by nhomar** [comment]
Hello.

I am agree in the way it works now, "reconciliable" is used to join or glue some moves for several reasons (one is payable and receivable, but you can use it for i.e: Accrual) on that case show it in the reports that I understand you are asking for in problematic.

We live that on past versions and the current behavior is a positive evolution I think.

Can you point which use case do you want to cover, because IMHO you are trying to jump the usage of an interim account to convert a payable in receivable or viceversa, if that the case with an interim move will be enough I think.

Let me know if this answer you question.

Regards.

**Comment by nhomar** [comment]
Fill free to reopen if not answered.

**Comment by nhomar** [comment]
>> Personally I used to make it payable to be able to get the report, but most of customers' accountants will not accept this and will consider it a workaround.

Well actually it IS a payable (even for few minutes between the computation and the payment itself), the concept of reconcilable and payable type is a technical concept for odoo itself, you should not have problems with that (I think).

I recommend to do that exactly as you said (payable + reconciliable for salaries to pay) and the counterpart will be normal expenses (or costs depending of your business type).

The point here is that it is far less expensive simple have few extras move lines that change the current behavior on the accounting which is working pretty well as it was designed on this regard.

But again, this can be considered a matter of PoV, I strongly recommend try to use it like that and give some time, you will see is less problematic, if in the next closing period it give problems then come here and reopen.

Regards.
