### ISSUE TITLE
If partner company_id is False don't show any fiscal position with actual company assigned

### ISSUE THREAD

**Issue by carlosdauden** [odoo/odoo#24256]
https://github.com/odoo/odoo/blob/7b49f5836c0f4a491631d27acb74ddd0106c86b1/addons/account/models/partner.py#L398

@Tecnativa

**Comment by pedrobaeza** [comment]
@mart-e I think you were the guy that changes this through #24056

**Comment by mart-e** [comment]
@pedrobaeza I am just the guy who deleted the branch but @kebeclibre can probably check it

**Comment by pedrobaeza** [comment]
OK, I see. I though @kebeclibre was not an Odoo's employee through his nickname.

**Comment by kebeclibre** [comment]
@carlosdauden 
I think I get what you mean, but not why.

**Comment by pedrobaeza** [comment]
@kebeclibre see this starting data:

- Product with no company
- Fiscal positions with the current company

No fiscal position is shown due to that domain.

**Comment by kebeclibre** [comment]
@pedrobaeza 
@carlosdauden 
I'm sorry, I don't understand what this is about. Please use screenshots, videos....

**Comment by carlosdauden** [comment]
You can try to set a fiscal position (with company set) in a partner without company set.
http://320544-11-0-b8133a.runbot8.odoo.com/web?debug#id=8&view_type=form&model=res.partner&action=93

![seleccion_193](https://user-images.githubusercontent.com/7701001/38816180-d52b834c-4195-11e8-9114-364e124e58d1.png)
![seleccion_192](https://user-images.githubusercontent.com/7701001/38816158-ca365926-4195-11e8-9ccd-d3d7b7ce9e60.png)
![consejo emergente_191](https://user-images.githubusercontent.com/7701001/38816191-da5ec5cc-4195-11e8-8788-5b14f0f7cb5f.png)


https://github.com/odoo/odoo/blob/88ccc406035297210cadd5c6278f6f813899001e/odoo/addons/base/res/ir_property.py#L138-L139

**Comment by kebeclibre** [comment]
@carlosdauden 
Alright, I get it.

What you want is actually what the fix intends to prevent.
Well, actually the use case I intended to fix was:
- Having multiple companies with many fiscal position each
- When creating an invoice or anything needing fiscal positions
             you end up in the selection list with all fiscal position, even the ones that are irrelevant (not in the company)
             Moreover, if an another user with less rights tries to edit that invoice, or read it, chances are he will get an access error because he can't see the elements of an other company (if the Fiscal position belongs to that other company)
- If a partner doesn't belong to any company, it shouldn't have attributes that do

- Business wise, if you want generic fiscal positions, just not set their company

Unless I missed something, I am closing that issue because:
- The code at hand does protect against security issues and access errors when sharing objects between user an companies.
- Business wise, it does make sense to prevent FPs that belong to a company to end up linked to a partner that is shared by every company
- On the other hand, objects in companies may use shared resources
- Workarounds are linked to what I qualify as good practices
If you want a pure shared object, do not link anything that has company_id to it

**Comment by carlosdauden** [comment]
@kebeclibre are you sure?
With a normal user (not admin), should not this be enough?
https://github.com/odoo/odoo/blob/81d1296323fdaeb88c37bde45f7443afd6ebd0ac/addons/account/security/account_security.xml#L96-L100

@mart-e do you agree with this?

**Comment by kebeclibre** [comment]
@carlosdauden 
That rule says to let users see FP without a company of FP's in companies that the user belongs to.
What if I follow you:
Create an invoice within a company A with admin 
assign a FP to it, which belongs to another company B that another user can't see

It is legitimate that a random user from company A accesses the invoice
But it will crash because the FP belongs to B

**Comment by pedrobaeza** [comment]
@kebeclibre what you are missing here is that the fiscal position in the partner is a company dependent field (old called property):

https://github.com/odoo/odoo/blob/1a80fc1ee7365059bb8ea5230e1f13360912e2b6/addons/account/models/partner.py#L395-L398

and thus with this commit you are preventing that any partner shared between several companies can set any fiscal position for the current company where the user is logged, and making impossible to use fiscal positions for these partners.

If you point me to the original reported issues, I can tell you another solution for that problems (I think they will probably has something to do with a missing `force_company=<company>` context in some places).

May I ask you to reopen this meanwhile?

**Comment by kebeclibre** [comment]
@pedrobaeza 
If by "partners are shared between companies" you mean that you have ticked the box "share partners" on the general settings then fiscal positions aren't shared. And you are back in the use case where if you put a FP that belongs to another company and you make an object with a regular user, it will crash if that user cannot see the other company

From a normal user in company B, editing a partner in company A is arguably not his job, and he will not be able, with my fix or not, to see FP from another company anyways.

If you meant that the partner has a company_id = False, then, logically, only FP that do not belong to any company are valid, for the same reason as before.
