### ISSUE TITLE
Upgrade base module error

### ISSUE THREAD

**Issue by Vegeta-D** [odoo/odoo#24271]
Impacted versions:
10.0

Steps to reproduce:
Upgrade base module

Current behavior:
ParseError: "Error: Duplicate key violates unique constraint" act_window_view_unique_mode_per_action"
DETAIL: The key value "(act_window_id, view_mode)=(55, tree)" already exists
" while parsing file:///odoo/addons/base/res/res_partner_view.xml:454, near

![image](https://user-images.githubusercontent.com/18547994/38859874-8715c5c4-4261-11e8-86f4-fad7ab1a4a69.png)

Expected behavior:

**When logout file:///odoo/addons/base/res/res_partner_view.xml:454-459，problem solved**

Personal guess：
The odoo/addons/base_vat/views/res_partner_views.xml  3
<record id="view_partner_form" model="ir.ui.view">
And odoo/odoo/addons/base/res/res_partner_view.xml  126
<record id="view_partner_form" model="ir.ui.view">
Also belongs to the res.partner module,Duplicate key violates unique constraint.

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/18547994/38858107-722b15e6-425d-11e8-8b10-b0c40d0526bc.png)
![image](https://user-images.githubusercontent.com/18547994/38858156-8bdc787c-425d-11e8-8cce-64d38e855c0d.png)

**Comment by Vegeta-D** [comment]
@mart-e Hello
I do not have delete or customize some views/actions，I just upgraded the base module, this error has appeared。

When I upgrade after annotating the red line, the error does not reappear
![image](https://user-images.githubusercontent.com/18547994/38915007-9986506c-4314-11e8-96a1-2af7e3f17be0.png)

Why is that？

**Comment by Vegeta-D** [comment]
I installed a custom module

SQL query result is
![image](https://user-images.githubusercontent.com/18547994/38969258-e8c13a40-43c1-11e8-85c2-7daade0fdc41.png)

**Comment by mart-e** [comment]
These two actions `action_contacts_of_customer1` and `action_contacts_of_supplier` and not standard, probably from your custom module (you can add `,d.module` at the end of the first line to see it).
The fact that the query do not return the `action_partner_tree_view1` is the proof that it was deleted.

Also, please make copy-paste in code blocks. Do not give screenshots, it prevents us to read it properly or copy the text.

Sorry but I have to reject this bug report by lack of information.
To be able to properly access it, I need a way to be able to reproduce it myself. You can use the [runbot](http://runbot.odoo.com/) if you want to have standard database to test.
If the problem comes from a custom module, you need to check with the developer of the module.

**Comment by Vegeta-D** [comment]
@mart-e 
Please take a look at my definition
`        <record id="action_contacts_of_supplier1" model="ir.actions.act_window.view">
`
`            <field name="view_mode">tree</field>
`
`            <field name="view_id" ref="contacts_of_supplier_tree"/>
`
`            <field name="act_window_id" ref="action_contacts_of_supplier"/>
`
`        </record>
`

`<record id="action_contacts_of_customer1" model="ir.actions.act_window.view">
`
`            <field name="view_mode">tree</field>
`
`            <field name="view_id" ref="contacts_of_customer_tree"/>
`
`            <field name="act_window_id" ref="action_contacts_of_customer"/>
`
`</record>
`
The ir.actions.act_window.view does not have the same id Why does it violate the restrictions?

**Comment by mart-e** [comment]
The two actions link indeed to a different action so indeed it is not the source of the problem.

A way to reproduce your problem is if you delete the ir.model.data `action_partner_tree_view1` but not the linked `ir.actions.act_window.view` record itself.

Check the existence of existing act_window.view in the database linked to the "Customers" action but where no ir.model.data is present

```sql
SELECT a.id,a.view_mode,w.id,w.name
FROM ir_act_window_view a
JOIN ir_act_window w
ON w.id=a.act_window_id
WHERE a.view_mode = 'tree'
AND w.res_model = 'res.partner';
```

If you find it, just delete the record and update base again.

Regards

**Comment by Vegeta-D** [comment]
@mart-e 
![image](https://user-images.githubusercontent.com/18547994/39051939-d99ca600-44dc-11e8-8258-21c3545cafd9.png)
However, it still does not have the same id.

**Comment by MartinAavastik** [comment]
Somehow I also had this problem. I solved it with deleting all the ir_act_window and that deleted also ir_act_window_view-s. After that I updated all modules and that fixed it for me.
