### ISSUE TITLE
stock.quant product_uom_id should not be a related field but a stored one

### ISSUE THREAD

**Issue by mohamedhagag** [odoo/odoo#24306]
https://github.com/odoo/odoo/blob/e41bcb0e311bfa67c78a13e377ae5c4931ecf24e/addons/stock/models/stock_quant.py#L28

https://github.com/odoo/odoo/blob/e41bcb0e311bfa67c78a13e377ae5c4931ecf24e/addons/stock/models/stock_quant.py#L30

This field should be a stored field on the quant not a related one, from business PoV we should be able to move and report quants with different UoMs and each quant should have its UoM stored on it.

Why we have this field implemented this way ?

**Comment by Yenthe666** [comment]
@lap-odoo can you check this and give feedback please? 😄

**Comment by sle-odoo** [comment]
@mohamedhagag quants `quantity` and `reserved_quantity` are always expressed in the product's unit of measure, but it doesn't restrict you from using other UOM that are compatible. If you make an incoming move for a dozen products while its product's unit of measure is unit, you'll get a quant of 12 units.

I'm closing this issue, if you have a blocking case because of the way it's implemented we can talk about it, but it is very unlikely we move away from this design choice.

Regards
