### ISSUE TITLE
Done Inventory Adjustment document can be deleted

### ISSUE THREAD

**Issue by smartboxid** [odoo/odoo#24328]
Impacted versions: 11.0

Steps to reproduce: 
I clone odoo 11 the latest one, run it. I create new database with demonstration data option checked, install only Inventory App and go to Inventory Adj., delete Starting Inventory and bam it will be deleted. Create new Inventory Adjustment, validated and it can be deleted as well. I've reported several days ago and commented the error has been fixed and closed. I've tried and the error is still there.
Current behavior: Validated Inv. Adj. can be deleted

Expected behavior: Validated Inv. Adj. must not be able to be deleted.

Video/Screenshot link (optional):

**Comment by fmdl** [comment]
I think you have not the last version of 11.0 because you can not delete an validated inventory (`done` state). But you can delete an inventory in progress.
https://github.com/odoo/odoo/blob/11.0/addons/stock/models/stock_inventory.py#L101

I have made a PR to fix : https://github.com/odoo/odoo/pull/24329

**Comment by smartboxid** [comment]
Sorry, my mistake. Yes, my code is not the latest one.
