### ISSUE TITLE
[bug][11.0]When receiving the product into the warehouse, the same batch of products, if stored in two locations, prompt error.

### ISSUE THREAD

**Issue by sum1201** [odoo/odoo#24333]
Impacted versions:
11.0
Steps to reproduce:
- create a product  A,tracking: lot.
- create a receive picking , product  A quantity 10,lot: 001,store A,B  location.
- validate picking ,throw error "The combination of serial number and product must be unique !".
- enterprise ticket : 1838203

Current behavior:

Expected behavior:

Video/Screenshot link (optional):

video: https://youtu.be/IB6doRD2nEk

![qq20180420-102503](https://user-images.githubusercontent.com/5398273/39027585-39594b00-4485-11e8-8b70-dc1d0e46a9b7.png)
![qq20180420-102441](https://user-images.githubusercontent.com/5398273/39027591-3da88554-4485-11e8-8783-3c6145b0a800.png)

**Comment by jco-odoo** [comment]
Maybe just setup the product as tracked by lots instead of tracked by serial number.

**Comment by aliomattux** [comment]
I would disagree with the closure of the ticket. IMO this is a bug or could be considered a feature enhancement to a broken feature. the exception is caused by an sql integrity constraint. A product can be configured to use lots or serial number, however when receiving it seems the system only behaves like serial numbers. It is very common for a product to have the same lot and received separately. For example a food product that has thousands of products under a lot or batch.

I will investigate this further and see if some patch can be provided as the current functionality is a blocker for my business process

**Comment by aliomattux** [comment]
In my tests, I worked with 12.0 however the 13.0 code for stock_move_line methods seems very similar so issue should be valid in both versions.

In stock/models/stock_move_line.py line 395 it checks if there is a lot name but not a lot id and if so, then it creates a production lot. There is also this commentary

                            # If a picking type is linked, we may have to create a production lot on
                            # the fly before assigning it to the move line if the user checked both
                            # `use_create_lots` and `use_existing_lots`.

IMO this logic is incorrect because it does not check to see if this lot number already exists or check if the implementation on the item is serial number, whatever.

The error that triggers is an sql integrity constraint because it creates another lot with the same name which isn't allowed.

IMO the proper fix would be to either on the create method of the stock production lot, implement some logic to check but this could be performance expensive, so my solution is to modify the create method of stock move line and add an additional check to see if the lot exists and if so, just return that lot id instead.

Unrelated, IMO there are a couple other usability issues such as the inability to specify an expiration date during the creation of the lot while receiving. Even though it supports creation on fly, if business depends on expiration then they will still need to create the lot before hand.

I created a module which solves the issue and will provide link when ready. My module simply overrides the create method so it isn't best but I did it for cheap time to move past an issue so just keep that in mind.

**Comment by aliomattux** [comment]
My fix:

                            # If a picking type is linked, we may have to create a production lot on
                            # the fly before assigning it to the move line if the user checked both
                            # `use_create_lots` and `use_existing_lots`.
                            #Modified for bug fix
                            if ml.lot_name and not ml.lot_id:
                                lot_obj = self.env['stock.production.lot']
                                lots = lot_obj.search([('name', '=', ml.lot_name)])
                                if not lots:
                                    lot = lot_obj.create(
                                        {'name': ml.lot_name, 'product_id': ml.product_id.id}
                                    )
                                else:
                                    #There can only be 1
                                    lot = lots[0]
                                    if lot.product_id.id != ml.product_id.id:
                                        raise UserError(_('The Lot: %s is assigned to a different product and cannot be used.') % lot.name)

**Comment by hparfr** [comment]
@aliomattux 
On the picking operation settings, you can activate "use_existing_lots".
Then, ml.lot_id is already before action_done().
