### ISSUE TITLE
Pricing model is confusing and overly complicated

### ISSUE THREAD

**Issue by KeithCu** [odoo/odoo#24356]
I checked out your website and system recently.

It looks pretty interesting. I don't mind paying for a version with more features and support, etc. but the pricing gets expensive quickly, even without many applications.

My friend's business needs an inventory and accounting system and has 10 employees, all of whom will be accessing the inventory, etc. If I select inventory and accounting, invoice, sale, and the shipping modules, I'm at $6000 / year.

Once I go and add the modules they might want to use one day, like CRM, purchase, time-sheet, equipment, and the other interesting sounding ones, I got up to $9000.

And even then I didn't know what the Studio, Sign, and some of the other apps. You have expensive apps with no descriptions.

I think it is wrong to charge by application or function. Selling lots of apps goes against the spirit of free software model because it makes the purchase process confusing and expensive. I have to ask questions like is $12 / month for e-mail marketing worth it? Is it cheaper if only one person does it? What value are you adding each month?

That amount is before I sign up for a support contract.

I don't think you should use an open core model. Or at least, you should include basic important features like mobile. One can question whether this is a free software product without mobile support. The community version is also missing timesheets, e-signature, shipping, etc. Can you imagine business that doesn't want shipping?

Please think more about the breakup between the community and enterprise edition. As it is, I'm tempted to look at Tryton, which is another fork of OpenERP.

**Comment by Elkasitu** [comment]
Hi,

GitHub is not the place for discussing these kind of issues (we only handle technical details on GitHub), I suggest you either contact one of our salesmen for a quote / to answer all your pricing questions.



> I think it is wrong to charge by application or function.

What you pay for with odoo online is not a product but a service, each app you install means potentially more maintenance, infrastructure, support from our part (which effectively means more costs).

> Selling lots of apps goes against the spirit of free software model

Odoo is *not* free software, it is highly modular open source software, this means that literally anyone can make their own (free or proprietary at their choice) module and sell it if they wish, using whichever price model they choose. You can think of Odoo enterprise apps this way too.

> I don't think you should use an open core model.

This is Odoo's strength, thanks to this the community version exists.

> One can question whether this is a free software product without mobile support.

Again, not free software and I don't see the relationship between free software and mobile support.

> Can you imagine business that doesn't want shipping?

Yes, I can, a business that only sells services does not need shipping.

**Comment by KeithCu** [comment]
Thanks for the info.

I understand that I'm paying for a service, but you created a complicated purchasing process that doesn't relate to the complexity of the software or of your work required.

Open core aka making stuff proprietary isn't really a strength. It might be a good way to make money, but it is taking away freedom. Presumably means I can't see the mobile client or make changes to it.

The community version doesn't exist because of open core. It exists because it is a fork of OpenERP and there is a huge market for ERP.

You are correct that a business that sells only services wouldn't need shipping. Although even accountants need to mail things out. It was just another example of how the community version is crippled.

My friend is probably going to use Five M software. Your pricing is too complicated that I don't want to bother trying to convince him what you have is better.

**Comment by fpodoo** [comment]
> Open core aka making stuff proprietary isn't really a strength.
>
It is a strength if you consider the big picture, and the long term
evolution and sustainability of Odoo Community.

Odoo Enterprise brings revenues. These revenues are invested to sustain the
fast evolution of Odoo (development investments are about 75% open source,
25% Enterprise --> for every $1 we put on paying features, we put $3 on the
open source product)

Would Odoo Community be better if it was 100% open source? Some people
thought so: tryton is a fork of Odoo, without open core model. Just compare
Odoo Community and Tryton today [1]. You will understand why our open core
model is good as it allows to build a better open source product.

No other open source management software reached the quality of Odoo
Community. [2] It probably means that the model is good.


[1] https://tryton.org
[2] https://odoo.com/r/zUx

might be a good way to make money, but it is taking away freedom.
> Presumably means I can't see the mobile client or make changes to it.
>
Odoo Enterprise does not prevent any freedom from Odoo Community.

> The community version doesn't exist because of open core. It exists
> because it is a fork of OpenERP and there is a huge market for ERP.
>
The community version still exists because we poured $25m into developing
the product, with hundred+ developers. Over the first years, this has been
financed by VC money, then it has been financed by Odoo Enterprise (more
sustainable)

It was just another example of how the community version is crippled.
>
The community version is used by millions of users. It probably means it's
not that bad and crippled.

Of course it might be frustrating to have a better product that is for a
fee. But, please, balance the pros and the cons and you will see that the
current approach of Odoo is great for every one: open source users benefits
from a fast evolving product, customers gets good service and top notch
features, and partners + Odoo SA have a sustainable business model.

My friend is probably going to use Five M software. Your pricing is too
> complicated that I don't want to bother trying to convince him what you
> have is better.
>
I am surprised about this.

Can you provide more feedback of what would be a cheaper alternative for
the same features / scope?
- if you compare to ERPs, Odoo is on average 5x cheaper (Netsuite,
Dynamics, sap are $150/user/month)
- if you compare to single apps: CRM + eCommerce + inventory + mass
mailing... You might have a similar price but a huge complexity of
integrating different software, leading to a worse solution to end users.
- if you compare to others open source software, you should choose Odoo
Community: free as well, but more mature.


I might be wrong, so I would be interested to know what is a cheaper
alternative to Odoo? (Of course, for same scope + service)

Could it be possible that you misread the pricing? For your scope, even for
the most expensive country, I get $4000, not $6000 for 10 users. (for
product + hosting + unlimited support & upgrades)

-- 
Fabien


>

**Comment by js-landoo** [comment]
Hi Fabien, I see 2 problems:
1) this price has no hosting (odoo.sh is about $1500 more and other options are similar) and available enterprise service is only for migration (very appreciated by our customers) and bugs (very few, fortunately).
Customer needs more support service and partner has to charge adittionaly for it, so total amount increases from your $4000, easily to $7000 ($1500 for hosting and $1500 for partner support service).
I think you compare with Nav and SBO prices that include really both services: hosting and support (tel, web and email).
I don't know USA market but in Spain now we are at same price with our competitors.
2) 2018 pricelist is about 200% compared with 2017 for companies with 5-10 users and same price for  40 users. This is what I get in all my quotations, because my customers want to use between 10 and 15 modules. You made numbers with 7 modules and can be right for saas but not for custom implementations.
This way we are making much more difficult for small companies to adopt enterprise contract.
I only see a reason for that: includes a yearly migration service and the cost for Odoo of that service is bigger than contract price. If it's true (and is very possible), you have two options: 
- keep actual pricelist and loose half of contracts between 5 and 15 users
- for small companies, offer one migration each 2 years

Hope it helps. Best regards.

**Comment by forksand** [comment]
There are a few versions of OpenERP/Odoo. When we started using it, OpenERP was 100% free software / open source software, which we expected to continue. They then started locking it down.

There is the (1) official enterprise version and there is (2) the "official community" version. But the best version is the (3) "real community" version maintained by the Odoo Community Association (OCA):

https://github.com/OCA/

This is true open source without the tricks (baitware).

https://odoo-community.org/

Unfortunately, people try the official "community" version and see how useless it is. If you want a full, truly open source ERP, get OCA!

**Comment by KeithCu** [comment]
Opencore might seem like a strength, but it will also decrease interest in people using your product. For example, it enabled you to setup a painful purchasing process that some won't want to bother with. Also, people might feel like the code they care to see and customize is not available.

I'm not arguing for 100% open source. I'm saying that you should consider a dividing line that makes it easy for your customers, and where the price is related to the value the customer receives. Nginx, for example, offers two versions, a free, and an enterprise. It makes it very easy to purchase. You don't have to keep going back to add or remove modules. (which are just a few thousand lines of code.) Once I've bought your software, I want all the modules so I can decide which ones will work for me. Also check out the nextCloud purchase process. They forked to create nextCloud because they found the open core model created by the VCs didn't work. I don't know the whole history, but you should talk to them.

It's not frustrating to have a better product for a fee. The title of this bug report is about how the current purchase process is confusing and complicated.

Odoo is not cheaper if you want all the apps. For a 10 person company, I got $12700 per year.

I didn't misread the pricing. I installed a few modules, and all the shipping modules and got $6000 before any support contract.

**Comment by nhomar** [comment]
¿Did somebody makes the math about buying all the apps on separated suppliers (with their own price system)?

**Comment by edsersolis** [comment]
I don't care much at the pricing, what I don't like is that it was "intended" to be cheaper for small companies and more expensive for larger ones... It was totally the opposite. And yes, you have to pay for admin user which you should never use for production matters. 

But ok... We stop selling to small companies, and from time to time we get a small one or at the end we opt for community for these...never for a large one. 

Yes it's true that Odoo is 5x cheaper than competitors... But others already are well known everywhere, usually people don't know Odoo... But ok we're working on that to happen.

But what I truly hate is that the value paid for Enterprise more than additional features is the support Odoo is supposed to provide. 

Odoo's support is CRAP. Always trying to argue that Odoo is perfect and has no issues when we all know it isn't, we report issues so that you take a time and understand, test it and fix it... No crappy "workarounds" that only work for you to close your ticket and say you have a good support when it isn't.

Everyone in Odoo technical team is like a spoiled child who always must be right even when they're totally NOT.

But that's not it... what I hate the most is that Odoo keeps competing with their partners... People go on Odoo.com see the pricing and always think that they just need to pay for licensing and they get the whole service...all these because you have some "hosting" options there and they even say they're free... If partners pay for a large fee for partnership (with no filter at all at the point that Dynamics and SAP partners become partner to harm the market possibilities for Odoo) at least Odoo should not try to compete with them, or at least stop confusing customers with erroneous information in your pricing section.

Odoo is great, we sell Enterprise to 99% of our customers, only sell community to very small or startup companies, but @fpodoo partners are your allies and you have to start listening to them.

**Comment by fpodoo** [comment]
> Hi Fabien, I see 2 problems:
>
>    1. this price has no hosting
>
> Please note that:

- Odoo Online includes free hosting
- Both Odoo Online & Odoo Enterprise includes unlimited functional support,
in addition to bugs (it changed since v11)
- Odoo.sh is free for partners (they get 100% commission)

>
>    1. I only see a reason for that: includes a yearly migration service
>    and the cost for Odoo of that service is bigger than contract price.
>
> Although the cost of services (hosting, support and migration) starts to
be significant, the main cost is by far the R&D, that allows the product to
evolve. (for both Odoo Community and Enterprise)


Our goal has always been to make integrated management software affordable
to SMEs: simple and unexpensive. We pushed hard on these two (improve
usability & keep very low price) to the point of burning a few million $,
and putting our company at serious risk.

Now, we finally have the right balance: an amazing product at an affordable
price. Our feedback from the market (when we sell in direct) is that price
is not an issue. So, we don't plan to review our pricing.


A price is fair if the value you get from it is worth paying the price. We
are working hard to improve the value to satisfy the few who think the
price is not fair.


To come back to the real issue: complexity. Odoo is not the easiest pricing
ever made, but it's still very simple to understand and it fits in one
page. Compared to the complexity of such a product, our pricing is
relatively easy.

The price has the advantage to scale fairly: larger companies pay more as
they have more users, a CRM project is cheaper than a full ERP project as
the users get more value from the software.


-- 
Fabien

>

**Comment by KeithCu** [comment]
Hi Fabien,

Your pricing is not simple to understand for someone who doesn't know your product. You've got a module called "Leaves." How many years have you worked on this codebase? I suggest showing it to someone new. 

Your pay for apps and users system does scale, but it's not easy to understand, and in fact the value proposition is nonsensical in certain cases. Please explain to me why my friend's 10-person company should pay $120 / month for an email marketing system unless you are going to be composing and sending out the emails.

I again recommend you talk to / research NextCloud and NGINX and their Open Core model. How many checkboxes on their purchase page? Do they charge per user as well as per feature?

In my opinion, the Odoo Community Association should disband and join Tryton.
