### ISSUE TITLE
Need to release spec file to generate rpm

### ISSUE THREAD

**Issue by joequant** [odoo/odoo#24399]
Impacted versions:
11.0

Steps to reproduce:
Would like to generate local rpm of odoo from source.  Would be nice to check in the spec file used to generate a package

Current behavior:
spec file to generate rpm not available

Expected behavior:
add spec file to repository so that users can generate their own rpms

Video/Screenshot link (optional):

**Comment by d-fence** [comment]
You can build an rpm package by using the setup.py like this:
`$ python setup.py bdist_rpm`

You 'll then find the rpm package in the `dist` directory.

The [setup.cfg](https://github.com/odoo/odoo/blob/11.0/setup.cfg) contains the rpm configuration and you'll find some scripts in the [setup/redhat](https://github.com/odoo/odoo/tree/11.0/setup/redhat) directory.

Be aware that you need to move the addons directories from [addons](https://github.com/odoo/odoo/tree/11.0/addons) to [odoo/addons](https://github.com/odoo/odoo/tree/11.0/odoo/addons) before building the rpm. Otherwise, the addons will not be included in the rpm package.

I'm closing this issue as we actually use this system to build the Odoo rpm package.
