### ISSUE TITLE
[Proposal] --init --update --without_demo regex/globbing

### ISSUE THREAD

**Issue by blaggacao** [odoo/odoo#24459]
The proposal consists in supporting a simple regex formulation when specifying --init & co parameters,
this would ease to create well defined topic akin test pipelines in CI/CD, like for example:

`--test-enable --init /pos.*/,point_of_sale`

Currently you only have one option: look them up and concatenate them manually. This does not proliferate best practices and constant test execution.

/cc @yelizariev

**Comment by blaggacao** [comment]
Related: https://github.com/odoo/odoo/pull/24234 https://github.com/odoo/odoo/pull/24452#issuecomment-384749160

**Comment by yelizariev** [comment]
This would simplify deployment scripts. E.g. https://github.com/it-projects-llc/odoo-saas-tools/blob/025a860/saas.py#L145

**Comment by Elkasitu** [comment]
We have an internal task for refactoring the CLI, the specs are all written and module globbing is one of the intended features, unfortunately the task has been in a stall for a while and we have no ETA on when the development will be started.

Due to the nature of this task we don't want to do any improvements on the current CLI.

**Comment by blaggacao** [comment]
This is very good news... Might you be entitled to give a private peak preview on the SPEC? I think @yelizariev and myself would be grateful power users... :wink:
