### ISSUE TITLE
[11.0] I cannot create a mass mailing with public images

### ISSUE THREAD

**Issue by yaniaular** [odoo/odoo#24508]
Impacted versions: 11.0

Steps to reproduce: 

1. Go to **Email Marketing** Menu
2. Create a new mail.mass_mailing
3. Attach an image
4. Save the mail.mass_mailing

![image](https://user-images.githubusercontent.com/7602170/39441119-86598b28-4c72-11e8-9ea2-363a981946fc.png)

5. The image is not public

![image](https://user-images.githubusercontent.com/7602170/39441128-8d5f78ec-4c72-11e8-898b-015b9387d734.png)

Current behavior:

The image attached from mail.mass_mailing is[ saved like NOT public](https://github.com/odoo/odoo/pull/23188). 

Expected behavior:

The image attached from mail.mass_mailing is saved like Public.

**Comment by yaniaular** [comment]
OPW 1840429

**Comment by dbo-odoo** [comment]
Not a bug, it's not supposed to be public; images work fine in the mass mailing since there is an access token in the URL.

If you tried this on a runbot, it's not supposed to work because runbots are multitenant without a dbfilter or reverse proxy, so it cannot work there.

In conclusion, your expected behaviour is wrong; it should *not* be saved in public :)

Nothing wrong here :+1: 

Cheers,

Damien
