### ISSUE TITLE
[10.0/11.0] Issue with editable list view with m2m fields in it

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#24559]
Impacted versions: 10.0/11.0

Steps to reproduce: Go to editable List view having m2m field in it.

Current behavior:
10.0

![](https://image.prntscr.com/image/XufvgPXjRIWGy2uTYLxeDg.png)

11.0
Could not access the field
![](https://image.prntscr.com/image/ChD99PgJSuamzLT4jhsrTA.png)

Expected behavior: Can edit field.

Video/Screenshot link (optional):

**Comment by DionysusJake** [comment]
This is a common issue. Using widget="many2many_tags" on the xml view's field definition will help solve this.

**Comment by adrianlaraperez88** [comment]
In case is normal fields?? https://github.com/odoo/odoo/issues/24536

**Comment by aab-odoo** [comment]
Hello @sswapnesh 

Actually, list views inside list views worked before v11 by chance, not by design. With the new views, this isn't possible anymore. Anyway in you case, your inner list view only displays the display_name, so I recommend you to set widget="many2many_tags", as @DionysusJake suggested. The same information will be displayed, with the same edition features, and it will be way cleaner.

Regards.
