### ISSUE TITLE
lot not required in performing "update quantity on hand" in product master data

### ISSUE THREAD

**Issue by ccandito** [odoo/odoo#24581]
Impacted versions: 10 community edition

Steps to reproduce:
entering stock for a product managed by lots in product master data through the function "update quantity on hand"
do not enter the lot

Current behavior:
the posting is performed without issuing any error message

Expected behavior:
an error message should be come up to avoid posting stock record without lots for product managed with lots

Thanks 
claudio candito

**Comment by pedrobaeza** [comment]
Hi @ccandito I already put an enterprise ticket about this, and the official answer was that this behavior is being reviewed for master, but not possible to be changed on stable versions, as there might be people relying on the current behavior.

Thus, I'm closing this as there's no possibility to be "fixed" in the sense of not breaking current flows, but expect on v12 that this will be fixed in one way or another. Meanwhile, a possible solution is to add a custom module that limits this.

**Comment by ccandito** [comment]
thanks

2018-05-07 10:25 GMT+02:00 Pedro M. Baeza <notifications@github.com>:
