### ISSUE TITLE
[11.0] point_of_sale: Pricelists are not being respected with client change

### ISSUE THREAD

**Issue by gustavovalverde** [odoo/odoo#24611]
#### Impacted versions:
11.0

#### Steps to reproduce:
- Create 2 Pricelists: '_Default_'  and '_Wholesale_' 
- Create Customer '_Gustavo_'
- Assign the '_Wholesale_' Pricelist
- Open the Point of Sale and validate that Gustavo has the right pricelist in his contact card
- Select Gustavo

#### Current behavior:
- Gustavo (in his contact) has the '_Wholesale_' Pricelist
- If we select Gustavo, the pricelist doesn't change in the POS

#### Expected behavior:
The Pricelist has to dinamically change based on the Pricelist set on the Client.

**Comment by pedrobaeza** [comment]
On the PoS configuration, you have to check which pricelists to import. Please check that 90% sure that is the problem.

**Comment by gustavovalverde** [comment]
@pedrobaeza I have this example:
![image](https://user-images.githubusercontent.com/16890942/39710277-579f4e30-51ea-11e8-9298-961c64fcdf26.png)

The default: **Precio de Lista** is always selected not matter which Pricelist (from above) the client has. And the cashier has to manually select the pricelist each time.

**Comment by gustavovalverde** [comment]
I also tested on runbot and had the same result.

**Comment by gustavovalverde** [comment]
Just for the record:
![image](https://user-images.githubusercontent.com/16890942/39711329-701c6210-51ed-11e8-86ea-a13296910cc5.png)

![image](https://user-images.githubusercontent.com/16890942/39711363-8ae3f70c-51ed-11e8-9e07-1a4e8d7ac1c7.png)

**Comment by gustavovalverde** [comment]
OPW 1843709

**Comment by Yenthe666** [comment]
"We do not consider this a bug. Thank you for your understanding.", same old, same old? 😉

**Comment by pedrobaeza** [comment]
Well, the important part is the explanation why is not a bug. Can you share it here?

**Comment by gustavovalverde** [comment]
![image](https://user-images.githubusercontent.com/16890942/39758223-4255512e-529d-11e8-9318-3e6c95cbd34d.png)

**Comment by Yenthe666** [comment]
😕 is he really saying that you should set the desired pricelist for every customer manually in the point of sale? So by default the POS always takes the same pricelist?

**Comment by beledouxdenis** [comment]
Hi Gustavo,

I just solved the issue in Odoo 11.0 with revision 5603b778f6a52a0c251be8d871139efdeeff5a40.

Thank you for your accurate bug report.

We apologize for the misunderstanding that happened in the early discussion regarding this ticket. 

This feature is available since 11.0 only. Before that, the customer pricelists were not implemented at all in the point of sale and it was therefore an expected behavior in previous releases.

For information, here is the revision that added the support of customer pricelists in the point of sale:
https://github.com/odoo/odoo/commit/ac89783d2f6cf5477de1c5e576e90ee0f576c9cc

As you can see, it was added on Apr 21, 2017 (in master) and therefore landed in the stable release 11.0 only.

Regards,

**Comment by pedrobaeza** [comment]
For v10, you have https://github.com/OCA/pos/tree/10.0/pos_pricelist :)

**Comment by Yenthe666** [comment]
@beledouxdenis,

Thanks a lot for the detailed information and the fix. It is very nice to see that you took the time for a second look and a fix. Great job guys!

**Comment by gustavovalverde** [comment]
Hi @beledouxdenis, thanks for the Fix 👍
