### ISSUE TITLE
disalignment between PO and MO's quantity in MTO scenario

### ISSUE THREAD

**Issue by ccandito** [odoo/odoo#24634]
Impacted versions: 10 community edition

Steps to reproduce:
create a MO with some purchase components managed with MTO rule.
1) update the MO's quantity by decreasing it
2) cancel MO

Current behavior:
1) the RfQ's quantities are not align (causing overplanning so over stock); please take into account this does not occur in increasing MO's quantity
2) RfQ is not cancelled 

Expected behavior:
1) in MTO scenario replenished quantities (in RfQ) have to be always aligned to requested quantities in (MO header).... in this example for the sake of clarity the BOM factor is always 1.
2) the RfQ has to be deleted when MO is deleted 

thanks in advance
Regards
claudio candito

**Comment by pedrobaeza** [comment]
Hi @ccandito,

I'm afraid this is not really a bug, but a specific use case. Odoo has decided in most of the cases to not make the propagation of some things full sync, as there can be in the middle manual manipulations that can be affected. For example, in your concrete scenario, although there's a MTO purchase order created with the initial MO quantity, you might change the quantity in the PO because you have called the supplier and they have told you that the minimum quantity allowed to purchase is quantity + 50, so you put that in your order. Making some kind of automatic modification when you decrease the MO quantity would waste your PO.

Any way, you can make a custom module that behaves the way you want for your use case.

Closing this issue.

**Comment by ccandito** [comment]
Thanks for your reply.
Do you think this is proper when cancelling MO also?
Please take into account we are speaking to RfQ, so internal documents, and not PO already communicated to vendors
Regards
Claudio
