### ISSUE TITLE
[11.0]Serial number tracking is not working properly with POS

### ISSUE THREAD

**Issue by CybroOdoo** [odoo/odoo#24755]
Impacted versions: Odoo v11

Steps to reproduce: 
1: Make a sale in POS for an item having serial number tracking
2: Get out of the POS screen and Check the inventory operation related to that POS Order.
3: You can see the transfer is in 'Ready' state.
4: Check the serial number area

Current behavior:
The serial number is not filled even though we have given in POS screen.
Expected behavior:
Odoo must take the serial number given in POS screen to the related inventory transfer.

**Comment by pedrobaeza** [comment]
@CybroOdoo I have just tried on runbot and that's because you don't have stock for that indicated S/N. Having stock of it, everything is done correctly:

![seleccion_001](https://user-images.githubusercontent.com/7165771/40112361-070323ac-5906-11e8-9236-4e81ab2d0569.png)

As PoS if offline and it supposes that if you are including a product, it's because physically is available, then everything should be correct. If not, you have check your inventory before starting PoS.

Closing as no real issue.
