### ISSUE TITLE
[Not a issue] It should be a tansient model

### ISSUE THREAD

**Issue by omalbastin** [odoo/odoo#24797]
Not a issue. I believe It should be a tansient model.
https://github.com/odoo/odoo/blob/4e71bd5caf741b8b45b037fc8b4222927801ff18/addons/account/models/account_bank_statement.py#L32

**Comment by qdp-odoo** [comment]
mmh... I think we left that as a non-transient model for the case where you want to check the current balance of the cashbox during its use.

For example, if you're using the cashbox for a long period without closing it (because there isn't a lot of operations made on it), let's say a week or a month, but you wanna check the balance from time to time. It might be useful to restart the counting based on what was previously inside (transient would be garbage collected at some points). 

So it seems it's making a tiny bit of sense, what do you think?

Anyway, keeping as it doesn't look awfully wrong nor critical to me

**Comment by pedrobaeza** [comment]
Closing as no critical and working as is.
