### ISSUE TITLE
Renovate: CI

### ISSUE THREAD

**Issue by blaggacao** [odoo/odoo#24869]
https://github.com/marketplace/category/continuous-integration

The issue with runbot is:

- Not future proof, nor standard compliant
- Ignores best practices (eg. CI pipeline yml files)
- High ongoing investment in maintenance
- Makes Odoo a bad ecosystem player (for me that's the most worry-some)

@yelizariev

**Comment by pedrobaeza** [comment]
Sorry, but this is not an issue report, but a suggestion that I personally don't share. Odoo decides this kind of things internally and reviews it regularly and a link to all the players in GitHub is not helping.

**Comment by blaggacao** [comment]
@pedrobaeza You're right, I'll reopen label it [Proposal]

**Comment by blaggacao** [comment]
@pedrobaeza Remember, we are not on enterprise repo here, but on the LGPL part of the project.. :wink:

**Comment by pedrobaeza** [comment]
It's not only the label, but this is nothing specific. If you want a discussion, use the mailing lists, not the issue tracker.

**Comment by blaggacao** [comment]
Why? Is there a written general accepted or odoo-specific policy on not allowing discussions to happen on github? See: https://github.com/moby/moby/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+Proposal

**Comment by blaggacao** [comment]
The term "mailing list" not even present here: https://github.com/odoo/odoo/wiki/Contributing

Please stick to good OSS governance and clarify rules pulicly before applying them...

**Comment by blaggacao** [comment]
https://guides.github.com/features/issues/ 

>Issues are a great way to keep track of **tasks**, **enhancements**, and bugs for your projects. They’re kind of like email—except they can be shared and discussed with the rest of your team.

**Comment by blaggacao** [comment]
And if the question is maintainer conveniance stick with best practices like for example a labeling bot like https://blog.alexellis.io/derek/

**Comment by pedrobaeza** [comment]
https://github.com/odoo/odoo/wiki/Contributing doesn't include as well nothing about this kind of proposal. Do you seriously think that Odoo is going to pull to the trash 5 years of work in runbot because of your opened issue? Or even that this will initiate the best discussion ever? If Odoo decides to change anything in their CI, they will analyze options, and maybe then ask to the community about their opinions, but they are fully qualified for deciding things by their own.

And this has nothing to do with OSS spirit. The spirit is to get things done, and this is what we do every day. From your part, only theory, vague links, and no contributions at all, so this is not community spirit also.

Please stick to things important enough.

**Comment by blaggacao** [comment]
> Please stick to things important enough.

[Proposal]s usually are strategic.

**Comment by blaggacao** [comment]
Having the facts together the call is the editor's.

As far as it concerns me: choice is important.

**Comment by Yenthe666** [comment]
@pedrobaeza easy there, it is not because you do not find it important that somebody else doesn't find it important. 😉 
However, you shouldn't really hope on changes there as runbot is actively used, migrated and I believe quite similar to Odoo.sh too, so I don't expect a shift/change there.

**Comment by blaggacao** [comment]
@Yenthe666 As far as you are able to take note of this... THANKS!

**Comment by Yenthe666** [comment]
@blaggacao well, closing based on power is never the answer. Every topic that has an introduction and enough information deserves atleast a response saying why the issue is closed. That is basic communication 101.

**Comment by blaggacao** [comment]
We should all agree with you @Yenthe666 !

**Comment by pedrobaeza** [comment]
@Yenthe666 There is already background for closing that way, as it's not without reasoning. As stated, a link to the possible CIs in the world is not something for discussing. And at the end, the discussion leads to nothing, as there's no evaluation for other CIs for changing the current one. That kind of discussions, whoever wants to have it, should take place on forums, mailings lists, or in their favorite coffeehouse.

**Comment by Elkasitu** [comment]
It is not based on power, it's based on the fact that your issue has no value and is extremely vague, you make a lot of statements but provide no source.

Furthermore, the runbot is an internal tool that we decided to make open source just because there is no reason to make it private, we are not committed to investing more resources into it than what we need, for us it works as it is and we don't need to make it "future-proof" or "standard compliant", however you're free to fork it and do with it what you will.

**Comment by Yenthe666** [comment]
@pedrobaeza I'm not arguing about the closure though, closing it was fine for this one as we both know it won't be changed. I'm just saying that the response felt rather passive/agressive while @blaggacao is simply trying to get insights and information. We can still close off an issue in a friendly way and give some usefull information, no? The answer from @Elkasitu actually explains it well. It has an answer to the why and a clear vision of what will (not) happen, that is the answer I expect from a closure.

**Comment by Yenthe666** [comment]
Thank you for the detailed and well explained response Martin.
