### ISSUE TITLE
POS Ticket / Receipt issue v11.0

### ISSUE THREAD

**Issue by josephrenda** [odoo/odoo#24970]
Please don't kill me, I'm trying to be a odoo dev one day! I know python, ERP, but am having a hard time following the python - Qweb - HTTP/Rest 

example, I'm trying to add a simple sales_order.date_order on the POS ticket; 

I noticed inside, addons/point_of_sale/static/src/xml.pos.xml   there is the follow XML that creates a ticket/receipt! 

   <t t-name="PosTicket">
        <div class="pos-sale-ticket">
            <div class="pos-center-align"><t t-esc="order.formatted_validation_date"/> <t t-esc="order.name"/></div>
</div>

The TICKET contains the Sales Order number;  "order.name" is the SO00001 Odoo number; 

I want to DISPLAY also the sales order DATE! (order date)  (SQL database  sales_order.date_order 

I TRIED ;  (obviously WRONG) 

<t t-esc="order.date_order"/> 

But how do I get it to go onto the ticket? I'm sure theres a model to file out, get the data somehow over to qweb, just can't figure it out. Can some gear me? 

Thank you, in advance.

**Comment by pedrobaeza** [comment]
We are not going to kill you, but this is not an Odoo issue, but a question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

The PoS thing is very special, due to its offline capabilities. Maybe try something easier first.

Closing this by the reason above.
