### ISSUE TITLE
[account] wrong date with account tax cash basis

### ISSUE THREAD

**Issue by JulioSerna** [odoo/odoo#25057]
reference to this issue https://github.com/odoo/odoo/issues/9972

Impacted versions:
* 11.0

Steps to reproduce:
* create and set tax like cash basis in payment
* create invoice and validate
* Payment invoice with date 01/01/2018

Current behavior:
The journal entry created by account tax cash basis is taking the [max date](https://github.com/odoo/odoo/blob/11.0/addons/account/models/account_move.py#L1652)

Expected behavior:
The journal entry must be take the date of the payment 01/01/2018

Video/Screenshot link (optional):
https://www.youtube.com/watch?v=0uhT0HDtp4Q

**Comment by pedrobaeza** [comment]
Why is this a problem? 

If you make a payment in the past, then this should be in the latest date, not in the past. If the payment is in the future, then the taken date will be the payment one.

**Comment by JulioSerna** [comment]
@pedrobaeza 
The problem is that the feature is cash basis and not matter if the payment is in the past or the future always must be in the date of the payment, if you make one payment in the past the journal entries are in the past(with date that you set in payment) the journal entries by tax cash basis must be in the same date

**Comment by pedrobaeza** [comment]
Well, I don't agree, but I let @qdp-odoo last word about this.

**Comment by qdp-odoo** [comment]
I might be wrong, but in case of a prepayment, I don't see why the tax should appears under the period of the payment in the tax report. 

Let's say I have a prepayment in January, and the customer invoice is made in March only. For me it's normal to declare the VAT in March, even if the payment was prior to it (not even talking about the fact that the prepayment period might already be closed).

In case of prepayments, making the tax exigible at the payment date seems counter-intuitive to me as
- it seems to me that the idea behind the cash basis taxes was to avoid "advancing" money due to the Estate by making sure we already received the cash from the clients first. So why would you hurt yourself with the exact inverse logic?
- as the invoice is still being created after, thus the reconciliation made at most at the invoice time, why would it still have any impact on the past?

So I'm afraid that unless you have other opinons going in your way, or a legal source somewhere, this would stay as it.

Thanks for your understanding

**Comment by gdgellatly** [comment]
@qdp-odoo Sorry I only just saw this.
> 
> I might be wrong, but in case of a prepayment, I don't see why the tax should appears under the period of the payment in the tax report.
In most jurisdictions I know of, the rule is earlier of payment or invoice under invoice basis, and payment under payments basis. In practice, unless it is your business model (hotels etc), I doubt it gets enforced too much.
> 
> Let's say I have a prepayment in January, and the customer invoice is made in March only. For me it's normal to declare the VAT in March, even if the payment was prior to it (not even talking about the fact that the prepayment period might already be closed).

That is definitely not normal. In practice, during the period the accountant should determine the value of future contracts for which deposits have been received (and the reverse) and include those amounts in the return. (Or for EU - the amounts of deposits)

> In case of prepayments, making the tax exigible at the payment date seems counter-intuitive to me as
> 
>     * it seems to me that the idea behind the cash basis taxes was to avoid "advancing" money due to the Estate by making sure we already received the cash from the clients first. So you want to postpone the VAT recognition as much as possible... why would you hurt yourself with the exact inverse logic?
> 
It is often convenient (or not even a consideration) to trigger an early time of supply. Such as impending VAT rate hikes. Regardless, whether it is counterintuitive or not, you consider just one side of the transaction. For every loser there is a winner (the depositor can claim the refund) and in any case the businesses don't get to decide, usually the local tax jurisdiction.

In any case, ordinarily the primary reason for selecting a cash basis is that the accounting is simpler, in fact you can run your business off bank statements alone. The cashflow benefits of VAT are secondary.

>     * as the invoice is still being created after, thus the reconciliation made at most at the invoice time, why would it still have any impact on the past?
> 
> 
> So I'm afraid that unless you have other opinons going in your way, or a legal source somewhere, this would stay as it.
While not related to cash basis directly (as it also applies to accrual accounting) - in most VAT/GST jurisdictions a tax payment is deemed due at the earlier of payment or invoice. https://www.ird.govt.nz/resources/f/3/f384108042c8346bbff5bfa271adc868/is1003.pdf is for NZ. 
In Australia its a bit more complicated as it distinguishes between deposit, forfeited deposit and part payment. https://www.ato.gov.au/law/view/document?DocID=GST/GSTR20062/NAT/ATO/00001&PiT=99991231235958.
In UK, same rules as NZ pretty much. https://www.gov.uk/guidance/vat-instalments-deposits-credit-sales. Not also there are some counter rules in the UK concerning VAT on cross border transactions when you are on a cash basis, I'm pretty sure those are EU wide and actually the VAT is due at time of invoice rather than payment.
In the EU - pretty much same rules as UK and NZ except it only applies to the amount prepaid - https://ec.europa.eu/taxation_customs/business/vat/eu-vat-rules-topic/chargeable-event-chargeability_en
https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:02006L0112-20150101&qid=1425211536658&from=EN - If deposit is forfeited in EU it is then no longer subject to VAT as no consideration was applied, opposite to Australia.

Note that none of those sources are for cash basis accounting specifically - it applies to all bases for tax accounting. Earlier of payment or invoice.
> 
> Thanks for your understanding
