### ISSUE TITLE
Email doesn't sent with account.invoice , sale.order or purchase order

### ISSUE THREAD

**Issue by audreypapin** [odoo/odoo#25072]
Impacted versions: Odoo V10 

Steps to follow to reproduce:

In the invoice view, when we use the "send by email" button, the form for sending mail opens.
We then click on send but the email does not appear as an email in the emails sent.
It sends a notification that the invoice has been sent (message subtype) but the email does not leave but does not appear anywhere. in the tracking exchange we see that there was no mail sent. in the tasks no problem. this error is specific to these three objects : account.invoice , sale.order or purchase order

Current behavior
No mail sent

Expected behaviour:
Invoice sent to customers by email

![image](https://user-images.githubusercontent.com/26871401/40982832-8c0241e0-68de-11e8-8ab3-bb780745fe17.png)

**Comment by sswapnesh** [comment]
Hello @audreypapin 
Could you Check `Auto Delete` Configuration in mail template ?

![](https://image.prntscr.com/image/73WEHKAFTCq0ipB0ZJSD5Q.png)

**Comment by pedrobaeza** [comment]
@sswapnesh that's not the problem. They are not seen there because they are not technically emails, but messages, so you should look for them. The other setting is when you send mails in mass mailing mode. In that moment, they are registered as emails (which is a heavier data model), and it's auto-deleted if the mark is checked.

Closing as no real issue.

**Comment by sswapnesh** [comment]
Thanks @pedrobaeza 
This makes more Sense.

**Comment by pedrobaeza** [comment]
Can you explain better then?
