### ISSUE TITLE
[11.0] odoo 11, does not save attribute values ​​in variants

### ISSUE THREAD

**Issue by nuelgoz** [odoo/odoo#25083]
Impacted versions: 

Odoo 11 with postgres 9.6 or 10, this also happens in version 10

when you generate variants in the product template, odoo creates these products with these variables, generating thousands of products with different variants, when you create these products in a random way you can sometimes create more than 9000 different products and at other times it does not exceed 4000 products .

if you manage to configure many variables, the load of the variables becomes heavy and slow both in the backend or in the online store.

we do not look for this to be fixed by a module that complicates even more the management of these variables, I believe that odoo performs well this management but requires some adjustments in the programming, and I think it has to be in the core and not in increasing the resources of process neither the time of use of the cpu nor the time of the user session, etc ...

we believe that this would be useful, today many products are configurable, even customizable by the consumer, imagine that you sell computers, bicycles, tires, etc ... we have a product that has 7 attributes.

the first attribute has 2 variables
the second attribute has 6 variables
the third attribute has 4 variables
the fourth attribute has 9 variables
the fifth attribute has 5 variables
the sixth attribute has 2 variables
the seventh attribute has 5 variables

this generates a total of one product template of 3602 different products.

I understand that some do not consider this a programming problem, I think it is a problem that must be solved.

I would like to continue using Odoo.

**Comment by pedrobaeza** [comment]
And what is the problem? The speed of the variant creation?

**Comment by nuelgoz** [comment]
I do not know, I do not think it is a problem of slowness in the log it is seen that when it generates the products it takes little time.

but at other times it never starts.

**Comment by pedrobaeza** [comment]
Sorry to insist, but we need a reproducible steps to get to that situation. If you can't say "doing this and that, you get this", then this can't be solved.

**Comment by nuelgoz** [comment]
'

**Comment by nuelgoz** [comment]
to reproduce it you just have to create several products with variants and see the log.

you will see that it does not always behave the same

tomorrow I will try to document it

**Comment by gdgellatly** [comment]
@nuelgoz between myself and @pedrobaeza we probably have as much experience with variant creation as anyone in community.  We both probably know the exact piece of code you are talking about almost by memory, and it is as optimised as it will get within the limits of the ORM.  

So don't think we think it isn't useful, clearly we both have similar requirements, for me dating back to 2009, rather we accept that within the core product there is no programmatic answer to magically speed up creation while maintaining integrity for the general case.

You can also search loads of places to find our very differing opinions on it.  Fundamentally here is the problem.

ORM creation is slow and resource consuming.  On average 1 second per variant is a good guide.  If you are creating a single complicated record, it really is unnoticeable, but create any 3000 records of any complexity and you will get the same issue as you get here.  This is because the ORM is doing all sorts of things for the generalized case (setting defaults, computing some values, checking constraints for example).  I just cannot see Odoo changing the ORM to support a single use case for a single model never encountered by the vast majority of users.

So you have 4 choices, none of which I can ever see getting put in core.

1. Avoid creation - @pedrobaeza has done some work here with a module that doesn't immediately create variants, rather on demand.
2. Speed up creation - this is an approach I took, but it is not easily repeatable as it depends on what is installed.  There is no change at all to interface or user.  Essentially, in a well controlled environment rather than single record creates/updates you replace with carefully crafted SQL into a temporary table and copy across.  In this manner I get about 5000 products / minute created, updates about 40,000.  v10 of postgres simplifies this a little bit as you can skip the temp table using ON CONFLICT.
3. Defer creation - using something like oca's queue job on a long running cron server set up for such jobs.  It will still take the same amount of time, but the user is returned and it gets done eventually.
4. Live with the time and set resource limits appropriate to your data.  Generally that means high CPU timeouts and a high hard limit.  Its not like you are doing them every single day, and then you rely on soft limits to kill workers.

There is a 5th possibility which is to custom develop to avoid needing so many variants.  I actually recently did this for a manufacturer with very large variant combinations and while the work was extensive, in the end a 5 attribute template was reduced to 1, and now they can support virtually unlimited "variants" of a single product template with individual pricing for each.  The product list also dropped from roughly 1m to 5000 products.

**Comment by intero-chz** [comment]
I think the point here is not slowness but more 

> but at other times it never starts.

@nuelgoz what is never starting here? The creation of variants after saving the template attribute settings?

**Comment by gdgellatly** [comment]
@intero-chz Of course I read the report, but both are symptoms of the same root cause IMO.  Resource limits in multi worker mode that are too small for the work they are being asked to do.  

You can replicate this behavior by setting a hard limit at 512mb (depending on modules you might need to bump up a bit, sometimes the worker grabs 512 before its even started, but 768 will generally work so somewhere between) and printing an invoice.  Nothing happens.  

Of course while you can't prove a negative, you could also try the reverse, and try and make it "do nothing" with workers set to 0.

Note "Do nothing" here is far from actually doing nothing.  There is a ton of preprocessing that goes into determining variant creation/update before actually writing or updating anything.

That said, I'm open to being proven wrong.  Variant creation is a very unfun piece of code to work with and its had a few changes lately.

**Comment by intero-chz** [comment]
I don't know if you're right or wrong here, the OP has to clarify it with more information. It seemed to me, that the creation just don't start at all, which is weird.
Yes i know the creation of variants has cost me a lot of time, too. IIRC one of our customers is using @pedrobaeza attempt of creating the variant on ordering of a variant by a customer. Actually i think this attempt and your 5th possibility are the best for the most situations, but not all.
But that is off-topic, so let's wait for more information :-)

**Comment by fmdl** [comment]
Hi @nuelgoz please find this PR to increase a lot the time to create lot of variants : https://github.com/odoo/odoo/pull/23108

**Comment by nuelgoz** [comment]
Thanks for your contribution, odoo, can you dispense with these previous calculations?

improves performance in the backend and the online store.

I can reduce the number of variables, but the question is if odoo can handle a lot of variants without losing performance, I think this is the problem.

but not only is it a matter of performance, I think the system also becomes unstable, constantly making unnecessary calculations.

You could even do it without generating products, it is not always necessary to control stock, as it can be in the retail sector, where you can sell products by catalog without having stock or in the sale of customized products where you can generate a lot of variables of the same product

Surely someone can provide more technical information than me.

Odoo can tell us how to solve this question and if they are willing to contribute to improve the generation of variables in Odoo.

**Comment by gdgellatly** [comment]
@nuelgoz Not creating stock items already exists for ecommerce, you just uncheck that box on the variant

https://github.com/odoo/odoo/blob/e1a954633494923ba770e2641a558ae4c050d483/addons/product/models/product_attribute.py#L18

**Comment by nuelgoz** [comment]
Thanks @gdgellatly, this works well for me, but I can not assign a different price for that variant, I use it to be able to put selection variants that do not modify the sale price and reduce the vriantes that are created.

Thank you.

**Comment by nuelgoz** [comment]
Solved with the update of odoo 12, in this new version the attribute values ​​can be configured so that variants are created on demand at the time of selecting the products for purchase.
