### ISSUE TITLE
[11.0]Leaves manager is not able to approve a leave request due to security restrictions

### ISSUE THREAD

**Issue by bennals** [odoo/odoo#25114]
Impacted versions: V11 CE - tested on runbot 335231-11-0-ab1690 this hour.

Steps to reproduce:
1.  Log in as admin
2. Make demo user 'Leaves Manager' in Settings/Users.
3. Log out and log in again as demo
4. Go to Leaves/Leaves to approve/Leaves
5.  Select Pieter Parker's leave request and click 'Approve'.

Current behavior:
Access error occurs due to security restrictions on Analytic Line, Operation: write

Expected behavior:
The leave request should be approved as the Leaves Manager should have permission to approve leave.
Video/Screenshot link (optional):
![screen shot 2018-06-07 at 11 13 23 am](https://user-images.githubusercontent.com/7786180/41072899-de072ab2-6a43-11e8-83e6-1ea354424c86.png)

**Comment by bitssg** [comment]
Issue remains unsolved on CE

**Comment by bennals** [comment]
@bitssg Sadly yes:(
I suspect now that 12 has been released a lot of these unresolved bugs will remain that way as the pre-occupation with new features, disrupting etc. rolls on in high gear.  
I fixed my problem manually by adding/editing the necessary record rules, but I need to redo it whenever I update the Odoo base code and the default rules get re-established.  I wish I had the skills to make a pull request to fix it - I suspect it's not a complicated one.

**Comment by bitssg** [comment]
@bennals the manual solution is simple enough in our case. If the leave type is associated with timesheet creation then the account.analytic.line.timesheet.manager rule is required for the user. This rule is also available through the timesheet manager group. You can manually add your user to this group so that base updates to not override your permissions profiles. I am not entirely sure if this can be considered a bug. We can create a PR to associate the rule with the Leave Officer group. @Yenthe666 would that be an acceptable solution?

**Comment by bennals** [comment]
Great!  That's a much better solution.  Thank you!

**Comment by tivisse** [comment]
Fixed at https://github.com/odoo/odoo/pull/42772

Thanks.

**Comment by bennals** [comment]
Thanks @tivisse!
