### ISSUE TITLE
update quantity on hand strange behaviour

### ISSUE THREAD

**Issue by ndemoreau** [odoo/odoo#25155]
Impacted versions:
Odoo11e Runbot
Steps to reproduce:
I have a quantity on hand of 16
I click on the update quantity on hand button and type 0
Nothing happens
I click again and type 1
The quantity increases to 17
I click again and type -17
Error message "negative quantities are not allowed"

How can I put the quantity on hand to zero then?

Thanks.

**Comment by pedrobaeza** [comment]
That's because you have lots on that product, so you need to specify the lot for affecting to the quantity with that lot. Putting 0 without lot doesn't change anything because you have the 16 units with lot. Putting 1 without lot, add one unit without lot to the stock.

About allowing to put stock without lot, this is something not fixable on this version, but will be handled on v12.

Closing as no real issue.
