### ISSUE TITLE
[11.0]PoS: Tracback on Lot/Serial Number Popup

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#25515]
Impacted versions: 11.0
Runbot: [http://342910-11-0-bb78b7.runbot16.odoo.com/web?debug=1#view_type=kanban&model=pos.config&menu_id=558&action=775](http://342910-11-0-bb78b7.runbot16.odoo.com/web?debug=1#view_type=kanban&model=pos.config&menu_id=558&action=775)
Steps to reproduce: Pos Session --> Add Product which requires Lot number
![ss](https://user-images.githubusercontent.com/16624719/41993687-d311dda6-7a69-11e8-8be9-cb59de2493ff.png)

Current behavior:
![ss1](https://user-images.githubusercontent.com/16624719/41993682-ceceafda-7a69-11e8-804e-770a5f4640ca.png)

Expected behavior: Should be able to enter lot number.

Video/Screenshot link (optional):

Adding Screenshot of Pos Config for Reference.
![abc1](https://user-images.githubusercontent.com/16624719/41993928-6a40da1a-7a6a-11e8-85bf-975bf7ea5de9.png)
![abc2](https://user-images.githubusercontent.com/16624719/41993930-6afc3f62-7a6a-11e8-9553-a0bb26cf7813.png)

**Comment by CybroOdoo** [comment]
![pos](https://user-images.githubusercontent.com/15099781/42450583-463d7592-83a2-11e8-955d-ba0de086c4a2.png)
Same issue

**Comment by Yenthe666** [comment]
@pimodoo can you check please?

**Comment by pimodoo** [comment]
@qle-odoo You are the new one

**Comment by Yenthe666** [comment]
How fast do you guys move from one app to another? Woha.

**Comment by sswapnesh** [comment]
May be can solve it by making this required (and adding proper domain)

**Comment by raishak6** [comment]
Hello,
The solution to the problem is by applying the following:

1. Go to **Inventory** - **Configuration** -  **Warehouse Management** - **Operation Types** - **POS Orders**  and un-check the box **Use Existing Lots/Serial Numbers** and then save the screen.

![capture1](https://user-images.githubusercontent.com/19860912/42578802-dd767198-851e-11e8-9171-d2f2ac2d47dd.JPG)

2. Then, go to **Inventory** - **Configuration** -  **Warehouse Management** - **Locations** , select your location for the POS and set the **Removal Strategy** under **Logistics** to either FEFO, FIFO or LIFO and then save the screen.

![capture2](https://user-images.githubusercontent.com/19860912/42579233-bfcbc8f4-851f-11e8-9839-6c891b48f464.JPG)

Then go to the POS module and load the POS session. Now when you select and item for sales Odoo will not prompt for Lot Number again. The Lot Numbers will be automatically selected by Odoo based on the default **Removal Strategy** you have defined for your POS Location configuration.

Afterwards, your POS screen should look like this

![capture3](https://user-images.githubusercontent.com/19860912/42579692-c6c02348-8520-11e8-970e-c6cba7fdc568.JPG).

**Comment by sswapnesh** [comment]
Ping @qle-odoo  (Not tested again but just Ping incase you have any reference)

**Comment by switch87** [comment]
> Ping @qle-odoo (Not tested again but just Ping incase you have any reference)

Hi @sswapnesh can you test it again? I did not manage to reproduce the error.

**Comment by sswapnesh** [comment]
> Hi @sswapnesh can you test it again? I did not manage to reproduce the error.

Hello @switch87,
Seems working well now. (Tried with new Config + Sessions)
