### ISSUE TITLE
[10.0] translation error on copying views

### ISSUE THREAD

**Issue by yelizariev** [odoo/odoo#25550]
Impacted versions:
10.0
It's not reproduced in odoo 12.0 (master)

Steps to reproduce:

* Load translation. E.g. ``fr_FR``
* Open view ``Continue Shopping Button``
* Click ``Action -> Duplicate``

Current behavior:

Error is raised:
```
Translation is not valid:
<span class="fa fa-long-arrow-left"></span>
<span class="hidden-xs">Retourner à la boutique</span>
<span class="visible-xs-inline">Continuer</span>
```

Expected behavior:

no errors

Video/Screenshot link (optional):

![error](https://user-images.githubusercontent.com/186131/42126683-e8fa50ca-7ca4-11e8-96be-5af2cc0c13bb.png)

**Comment by yelizariev** [comment]
@Yajo this issue affects on ``website_multi_theme``

**Comment by ilmir-k** [comment]
I confirm the issue

**Comment by pedrobaeza** [comment]
@mart-e can you check this?

**Comment by mart-e** [comment]
Hi,

Thanks for the report, you are right, it was due to translation that did not respect the same structure as the source.
Change the translation, from
```xml
<span class="fa fa-long-arrow-left"></span>
```
to
```xml
<span class="fa fa-long-arrow-left"/>
```
and it will work.

I have already applied the changes in Transifex at https://www.transifex.com/odoo/odoo-10/translate/#fr/website_sale/96760955?q=text%3A'continue+shopping'
