### ISSUE TITLE
Adjusting Qty To Produce on MO's deletes consumed qty from some raw material lines

### ISSUE THREAD

**Issue by tr3ysmith** [odoo/odoo#25573]
**Impacted versions:**
Version 11

**Steps to reproduce:**
Create a BOM with 3 raw materials:
Product A
Product B
Product C

Update qty on hand of each product like so:
Product A: 10
Product B: 8
Product C: 10

Create a Manufacturing Order of that BOM with a Qty to produce of 10. Produce 8 finished goods, since thats all you can produce at that time. To finish the current MO, update the "Qty To Produce" line to 8 instead of 10.

**Current behavior:**
You'll notice that Product A and Product C both go to 0 consumed while Product B stays at 8 consumed. This causes incomplete data and doesn't explain why the other two lines go to 0

**Expected behavior:**
All current consumed items should stay when Qty To Produce is updated. So if you're only able to make 8 and thus produce 8 of the 10, updating the QTY to Produce to the current produced Qty should keep everything the same and just allow you to mark as done.

**Video/Screenshot link (optional):**
![image](https://user-images.githubusercontent.com/15764606/42185907-a09cba82-7e18-11e8-968b-64aaa4176d32.png)
![image](https://user-images.githubusercontent.com/15764606/42185934-b17506fc-7e18-11e8-814c-35fbb46278c0.png)
![image](https://user-images.githubusercontent.com/15764606/42185958-c6280054-7e18-11e8-8698-fd58acade7d5.png)
![image](https://user-images.githubusercontent.com/15764606/42185976-d88a8a3c-7e18-11e8-846a-57e9f9b1b14f.png)

**Comment by tr3ysmith** [comment]
this isn't a big issue until you use tracking by lot/serial number. When doing that, this bug adds a lot of work in redoing stuff.

**Comment by intero-chz** [comment]
Why isn't that a big issue? What about stock reports? You will lose some stock history with this bug, and that can be a big issue.

**Comment by tr3ysmith** [comment]
No yes it is a big issue regardless, but I what I mean is it escalates the issue when you track raw materials and finished goods by serial/lot numbers.

**Comment by alelio** [comment]
This issue is indeed present and serious.
Followed the same steps and the result was that the item has been manufactured, but no raw material has been consumed.

Create MO > Produce partial quantity (all consumed updated correctly and product listed in "Finished products" tab > reduce the Quantity to Produce > complete remaining production/close order

The result is that the material consumed BEFORE the quantity to be produced is changed are "discounted", but the final products are manufactured anyway (for free!).

The production resumes from the point reached and the only material consumed are the one used AFTER the Quantity to Produce is changed.

While partial production could be something that is not used by every customer I would see it as a fairly basic and common requirement. Is there any plan to implement a fix?

**Comment by sle-odoo** [comment]
This should be fixed by 8db7d70776a276d153d62708c9b703b0b756dae6

If you're still facing this issue feel free to comment.

Regards
