### ISSUE TITLE
[11.0] web: lessc 3.5.1 is not compatible

### ISSUE THREAD

**Issue by moylop260** [odoo/odoo#25632]
Impacted versions:
11.0 (Maybe other ones)

Steps to reproduce:
 - Install `npm install -g lessc` today.
 - `lessc --version`
   - lessc 3.5.1 (Less Compiler) [JavaScript]
 - Start odoo
 - Open `/web/login` page

Current behavior:
```bash
ParseError: Unrecognised input in /home/odoo/odoo-11.0/addons/web/static/lib/bootstrap/less/carousel.less on line 204, column 28:
203     // set alpha transparency for the best results possible.
204     background-color: #000 \9; // IE8
205     background-color: rgba(0,0,0,0); // IE9
```

I just have separated the small section with the issue running:
`lessc /home/odoo/odoo-11.0/addons/web/static/lib/bootstrap/less/carousel.less --no-js --no-color --include-path=/home/odoo/odoo-11.0/addons/web/static/lib/bootstrap/less`

Output:
```bash
The "--no-js" argument is deprecated, as inline JavaScript is disabled by default. Use "--js" to enable inline JavaScript (not recommended).
ParseError: Unrecognised input in /home/odoo/odoo-11.0/addons/web/static/lib/bootstrap/less/carousel.less on line 204, column 28:
203     // set alpha transparency for the best results possible.
204     background-color: #000 \9; // IE8
205     background-color: rgba(0,0,0,0); // IE9
```

FYI using an old version like `npm install -g less@3.0.4` is working as well.
Less package has [released a new version today](https://www.npmjs.com/package/less)
I don't know if there is an issue with `less` or a real compatibility problem, but here we can follow it the matter.

Expected behavior:
Working as well.

**Comment by mart-e** [comment]
Hi,

Thanks for the report. It seems that the issue is inside a [bootstrap file](https://github.com/odoo/odoo/blob/896e3f4c1eace0c1ad3e3b472fa373e62d7cddb5/addons/web/static/lib/bootstrap/less/carousel.less#L204).
Have you been able to identify a related issue upstream (either at bootstrap or lessc)? Or was it already fixed and we need to update the library we ship?
As we do not support IE8, we could probably remove that problematic line from bootstrap but it means modifying the library we ship (which we try to avoid).

**Comment by pedrobaeza** [comment]
I don't see any on Bootstrap: https://github.com/twbs/bootstrap/issues

**Comment by Yajo** [comment]
You should only use `less@2` for Odoo, because Less 3.x has other incompatibilities that disable you from using `theme_bootswatch`: https://github.com/odoo/odoo/pull/24246#issuecomment-386278164

**Comment by qsm-odoo** [comment]
Hello,

I have no problem running Odoo 11.0 with the latest less version (which is 3.5.3). In any case, as @Yajo said, you could use `less@2` which is known to be working. We mainly used version 2 to develop Odoo 11.0, even if it is designed to work with `less@1.4.2`.

Also you should know that Odoo 12.0 will be using sass instead of less.

**Comment by moylop260** [comment]
@qsm-odoo
The official documentation of odoo is not using a pinned version of this package.

Shouldn’t be added all your comments on the documentation?

**Comment by qsm-odoo** [comment]
I don't think so as the latest version (3.5.3) works. The fact that 3.5.1 did not work was probably a LESS library bug.

**Comment by Yajo** [comment]
No, Odoo does not work flawlessly with Less 3.x. Just read the full story in https://github.com/odoo/odoo/pull/24246, where I also suggested that `less@2` should be added to the docs.
