### ISSUE TITLE
I cant find any bruteforce protection of logins in Odoo 11

### ISSUE THREAD

**Issue by zem** [odoo/odoo#25696]
Impacted versions: 11 and below 

Steps to reproduce: 
  Try to brute force passwords.

Current behavior: 
   The login neither slows down nor blocks the user after several wrong password attemts. 

Expected behavior:
   I think the easiest way to implement brute force protection is to block the complete user account for, lets assume, 60 minutes, as soon as a user sends a wrong password lets say 4 times in a row. Schould be configureable by the Administrator and it must be enabled by Default. 

For an online system like Odoo that keeps this all the business intelligence, some sort of brute force protection is mandatory, and it would be a consequent fix for all upcoming bugs like  the one described in #15251

**Comment by pedrobaeza** [comment]
You don't really need Odoo to handle that. Check https://www.odoo.com/documentation/11.0/setup/deploy.html#login-brute-force

**Comment by xmo-odoo** [comment]
@pedrobaeza that's true but there's still a plan to introduce basic rate limiting to Odoo, hopefully for v12, see #22212

**Comment by pedrobaeza** [comment]
True, thanks for noticing that also!

I tend to forget it as we are using https://github.com/OCA/server-auth/tree/11.0/auth_brute_force meanwhile. The fail2ban method has the only flaw of not logging when the user is not correct, but with the PR you mention everything will be covered and that module won't be needed.

**Comment by zem** [comment]
Thanks for your Help. :)

I will keep a look in that. good to see that a feature is on its way.  

fail2ban is of course the obvious choice but it will basicly block everything as soon as it kicks in unless I oversee some magic there. I will dig into that logon module on my next session.

**Comment by eHanseJoerg** [comment]
I created an Ansible role that sets up fail2ban if Odoo works behind an proxy like Apache. Instead of parsing the Odoo log entries, the fail2ban filter will parse the Apache log entries. This is possible, because a failed login attempt will cause Odoo to POST the /web/login page to the user again. Maybe someone finds this useful and can work it out from here:
[https://github.com/eHanse-IT/ansible-odoo-rules-for-fail2ban](https://github.com/eHanse-IT/ansible-odoo-rules-for-fail2ban)
