### ISSUE TITLE
[11.0] _run_fifo implementation : FIFO + real_time

### ISSUE THREAD

**Issue by ke-real** [odoo/odoo#25716]
Impacted versions:
11.0

Steps to reproduce:
1. Setup product stock valuation to FIFO + real_time
2. Create two warehouses within a company
3. Receive products in warehouse A, then warehouse B with different prices at different time
4. Sell a product from a warehouse B where stock was received later than in warehouse A
5. (variation) do the same for a uniquely serialised product

Current behavior:
Warehouse A valuation price is used for resulting stock moves.

Expected behavior:
Warehouse B valuation price has to be used

This is even a more general question: what is the reason behind refactoring of valuation logic? Previously (versions 6-10) this kind of valuation worked perfectly and now it is completely broken. It is also not possible to get valuation for a specific location, since stock valuation report returns stock value per product across the whole company. One option would be to use multi-company, but this is not exactly the same as different warehouses.

**Comment by edsersolis** [comment]
Glad that this subject keeps coming up. No matter how much issues you close, it will keep coming up from different sources as it's a HUGE ISSUE that maybe you haven't taken the time to analyze and try to understand, with this you've taken Odoo back to version 5.

**Comment by edsersolis** [comment]
https://github.com/odoo/odoo/issues/25055

**Comment by pedrobaeza** [comment]
Well, the problem here is the current implementation, which relies in financial information. I don't have this need, but I understand that can be needed. At least on v11 this can't be handle due to stability policy. I think there's a link between the generated account entry and the move, so that can be the start for a custom module for reconstructing the information by logistic metrics instead of financial ones.

@jco-odoo about future releases, is there any plan to release new features that cover this?

**Comment by jco-odoo** [comment]
No, no plans.  In v10, the logic was real price valuation, in v11 it is fifo financial valuation.  Both are also different from financial fifo by warehouse also.
