### ISSUE TITLE
import data from child company

### ISSUE THREAD

**Issue by leenzahran** [odoo/odoo#25769]
Impacted versions: 10.0

i have parent company with two child companies (A,B)
i want to import data directly from company (A) and its give this error .
if its not supported on odoo to import from child company can you show me how to import from administrator to that child company
by the way: i tried this its working on administrator but no result shown on the child company

Current behavior:
![37126554_10156026705038705_1715161388264980480_n](https://user-images.githubusercontent.com/37477000/42722828-a89d1316-875b-11e8-92bf-fcb2497b66d7.jpg)

Expected behavior: import done successfully

**Comment by pedrobaeza** [comment]
This is because the data you are trying to import violate the multi-company rules (probably due to the company 10 not being accessible in the current user or the account 589 belonging to another company).

Any way, this is not an Odoo issue, but a misuse over multi-company management, which is hard and should be very precise. Closing due to this reason.
