### ISSUE TITLE
[11.0] Slow response time when workers > 0

### ISSUE THREAD

**Issue by davidgomezq** [odoo/odoo#25790]
Impacted versions:
11.0-ee (I also think on 11.0-ce)

Steps to reproduce:
configure workers > 0

Current behavior:
First response time is very slow +2s to response web HTML code when workers are active

Expected behavior:
-0.5s response time when workers are active

Video/Screenshot link (optional):

- Response time with workers: https://imgur.com/UzgTUU2
- Response time without workers: https://imgur.com/CLr7245

#### Nginx

Enable gzip compression, http2 (I try without http2), https, cache headers active

#### Odoo

Deployed with docker based on https://github.com/odoo/docker

#### Server

8 CPU, 30GB RAM, 50GB SSD

#### Odoo.conf

I try with any values of workers, limit_memory_hard, limit_memory_soft...

```
# PERFOMANCE
limit_memory_hard = 2560000000
limit_memory_soft = 2048000000
limit_request = 8192
limit_time_cpu = 30
limit_time_real = 120
limit_time_real_cron = -1
workers = 17
max_cron_threads = 2

# LOGGING
log_db = False
log_handler = [':INFO']
log_level = info
logfile = None

# OTHERS
longpolling_port = 8072
osv_memory_age_limit = 1.0
osv_memory_count_limit = False
smtp_password = False
smtp_port = 25
smtp_server = localhost
smtp_ssl = False
smtp_user = False

# XML RPC Configs
xmlrpc = True
xmlrpc_interface = 
xmlrpc_port = 8069
xmlrpcs = True
xmlrpcs_interface =
xmlrpcs_port = 8071
```

#### Postgresql

Official Postgresql docker image 9.4 and configured with https://pgtune.leopard.in.ua/#/

I try with/without these parameters 

```
# DB Version: 9.4
# OS Type: linux
# DB Type: web
# Total Memory (RAM): 30 GB
# CPUs num: 8
# Connections num: 960
# Data Storage: ssd

max_connections = 960
shared_buffers = 7680MB
effective_cache_size = 23040MB
maintenance_work_mem = 1920MB
checkpoint_completion_target = 0.7
wal_buffers = 16MB
default_statistics_target = 100
random_page_cost = 1.1
effective_io_concurrency = 200
work_mem = 8MB
checkpoint_segments = 32
```

**Comment by sswapnesh** [comment]
Related to #21391

**Comment by pedrobaeza** [comment]
@odony should we consider here the same answer as in #21391 ?

**Comment by aselcis** [comment]
I read #21391 but I consider that it isn't the same, because the problem on #21391 is 10 seconds of diff and I have tried solutions considered on #21391 and problem it isn't solved.

**Comment by davidgomezq** [comment]
I read #21391 but I consider that it isn't the same, because the problem on #21391 is 10 seconds of diff and I have tried solutions considered on #21391 and problem it isn't solved.

**Comment by odony** [comment]
That sounds like the normal behavior to expect when you enable multi-process mode, especially if you're testing cold or partially warmed servers. With 17 workers it will take much longer to fully warm up the system. It's a trade-off: more processes = more boot work, but more performance after that.

In multithreaded mode (workers=0), there is only a single Python process, so the work of starting up the server only needs to be done once. There is a delay when answering the *first* request (you see in the logs that the server is generating the routing map, etc.), but after that, no more delay. 

In multi-process mode (workers>0), you start X processes, so you have to pay the cost of initializing them X times. The delay will occur *every time each  worker* receives its first request (you will see each time the same log entries, with a different process ID).

What happens should be pretty obvious if you look at the logs of the server. Every log line is prefixed with the process ID of the worker, so you can clearly see when each worker receives its first request after startup.

Here is an example startup with `-d 11e --workers=3`: https://pastebin.com/raw/j3BWpP42
3 HTTP workers start (18899, 18900, 18901), and get assigned their first request randomly. Once they are all initialized they handle requests without extra steps: no more delay.

You can try to cut down on the initialization by specifying `db_name` in your config. This will ensure that the database registry is preloaded before forking the workers, and can cut the first request time by as much as 50%. But you cannot do much more than that, because the rest of the process memory is lazily initialized when the first request comes through.
And it's okay, really :-) Multi-process mode is meant for long-running, production deployments, where performance and limits are critical. Those environments are not restarted often, and it's not a big deal if the first few clicks are delayed by a 1 or 2 seconds.
If you need a server that starts very fast because you restart it often (dev/test environment), you probably want to stick with the default multithreaded mode.

**Comment by pedrobaeza** [comment]
Thanks for the elaborated answer, @odony, so we can consider this as won't fix, but due to reasonable causes and being not critical, and thus, I'm closing the issue.

**Comment by azergha** [comment]
@odony 
Thank you for the answear, it is technically very clear. But sounds very unpleasent for user experience esecially in an ecommerce context where the customer is the one who will trigger system warm up, which would probably lead him to leave the website after some time.
Is there a mean to warm up the server ourselves instead of waiting for an end user to do it?
