### ISSUE TITLE
[11.0] Ordering of lines in sales ordes

### ISSUE THREAD

**Issue by deivislaya** [odoo/odoo#25902]
**Impacted versions:** 
11.0 ee

**Steps to reproduce:**
 
1.  Create or modify an A sales order with at least ten lines
2.  Create or modify an B sales order with at least ten lines
3.  Return to order A and enter new product lines

**Current behavior:**

The lines are added unordered, without following the sequence of the last product already added

**Expected behavior:**

Add lines of product following the sequence existing in the order

**Video/Screenshot link (optional):**

https://youtu.be/SDyXZ40JhrQ

**Comment by pedrobaeza** [comment]
Hi @deivislaya. This is a known issue from old handle widget implementation that can't be fixed in current version, but fortunately, this has been handled for the upcoming version 12 (with some little constraints) in https://github.com/odoo/odoo/pull/25483. Please check runbot in master branch to try out.
