### ISSUE TITLE
[11.0] Sale Order: not select a customer first, price set to 0

### ISSUE THREAD

**Issue by diendang271** [odoo/odoo#25917]
Impacted versions:
11.0
Steps to reproduce:
Sales > Quotation > Create > Add item to Order Lines
(Not select customer in advance, select customer after add item to order lines)
Current behavior:
Price set to 0
Expected behavior:
Product price is set correctly
Video/Screenshot link (optional):
[Price set to 0](https://prnt.sc/k9pd4g)
[Correct price of product](https://prnt.sc/k9pd9z)

**Comment by intero-chz** [comment]
IIRC the price is computed by pricelists, even without activating them. Without a customer there is no pricelist set, so every line price will be zero. So maybe it is enough to just set a default pricelist on "virtual" creation of an order?

**Comment by sswapnesh** [comment]
I can confirm this Behaviour.
In v8 We have to select Customer first 
https://github.com/odoo/odoo/blob/8.0/addons/sale/sale.py#L1121
        

```
if not partner_id:
            raise osv.except_osv(_('No Customer Defined!'), _('Before choosing a product,\n select a customer in the sales form.'))
```

**Comment by Yenthe666** [comment]
I think that warning was removed because it was blocking the user quite a bit. @mart-e can you verify please?

**Comment by mart-e** [comment]
I guess so, was removed at 0af4da6ab5dcf8144b63a5bce8595c6663949c85 
Setting a default pricelist is probably a good idea to avoid that but we need to make sure it is still the one of the customer that takes the precedence. What do you think @tde-banana-odoo?

**Comment by sswapnesh** [comment]
Seems same behaviour on v12 too.
Cc: @tde-banana-odoo

**Comment by dbo-odoo** [comment]
Hi,

Indeed, without a pricelist set (even if they are not visible) all prices will be 0. In fact there might not even be a currency on the SO since the currency comes from the pricelist (even in mono-currency mode).

Unfortunately, I won't change this in 11/12 since the use case is 1/ rather meaningless (what does it mean to create a SO without a customer anyway?) and 2/ is easy to bypass using the 'set default values' debug menu.

I keep that in mind for v13 though, we could certainly take the first pricelist we find by default when no customer is set.
