### ISSUE TITLE
Invalid behaviour when parsing XML content to HTML in Odoo webpages

### ISSUE THREAD

**Issue by Yenthe666** [odoo/odoo#26038]
Impacted versions: 9.0, 10.0, 11.0

Steps to reproduce:
1. Go to an existing webpage and take the XML editor, for example on the contact page. Paste in the following two examples of code:
```
<span class="hljs-tag">&lt;<span class="hljs-name">title</span>&gt;</span>Title<span class="hljs-tag">&lt;/<span class="hljs-name">title</span>&gt;</span>
<br/><br/>

<span class="hljs-tag">&lt;<span class="hljs-name">title</span>&gt;</span>Title<span class="hljs-tag">&lt;<span>/</span><span class="hljs-name">title</span>&gt;</span>
```
2. Save the page and now look at the XML that is converted to HTML. You'll see that the first tag is rendered invalid while the second one is rendered correctly:
![image](https://user-images.githubusercontent.com/6352350/43357934-0cae4e68-928a-11e8-8dbc-a2f9cd06d820.png)
3. Do the same behaviour in a plain HTML webpage or an online fiddle, you'll see that both are rendered correctly:
![image](https://user-images.githubusercontent.com/6352350/43357942-28e3fd4e-928a-11e8-8f87-df7fb7a472c1.png)
You can find an example fiddle at https://jsfiddle.net/zqtfc0ru/

Current behavior: XML content is not correctly parsed into html if there is a "/" after a encoded character, for example `&lt;/` will be rendered as `<` and not `</`. If you place an element (or space) between the `&lt;` and the `/` it will render correctly, that is why my second example works. Mind the `&lt;<span>/</span>` part in my second code example for this.
Placing random HTML elements between these statements is not an option (and a bad practice). Placing a space between the `&gt;` and `/` will result in a literal space between both characters, so that is not an option either (`< /` instead of `</`)

Expected behavior: XML content is correctly parsed to HTML, both when there is a character against the special encoded character as when there is a space next to it.

**Comment by Yenthe666** [comment]
OPW 1870229

**Comment by JKE-be** [comment]
Hi Yenth,

It seems to work in standard html, but it doesn't work ;)
Your code is wrong


First, simplify your example with this code:

```xml
Sample A        <div>&lt;/<span>title</span>&gt;</div>
Sample B        <div>&lt;<span>/</span><span>title</span>&gt;</div>
```

Visible output will be:

> Sample A
> title>

> Sample B
> </title>


Now, take a look to html source:

![image](https://user-images.githubusercontent.com/4848797/43367576-8b809118-934f-11e8-8f25-7daefd046ff5.png)

As you can see, the / is well printed, but escaped because you have a html char '<' before.
Probably that what you want was to show this < in plain text.

```
< in html = &lt;
&lt; in html = &amp;lt;
```

So if you replace your `&lt;` (that generate in html `<`) by `&amp;lt;` (that generate in html `&lt;`)
That will works as expected:


**Fixed Code**
```xml
Sample A        <div>&amp;lt;/<span>title</span>&amp;gt;</div>
Sample B        <div>&amp;lt;<span>/</span><span>title</span>&amp;gt;</div>
```

Result:

> Sample A
> </title>

> Sample B
> </title>

In code source:

![image](https://user-images.githubusercontent.com/4848797/43367628-5cd275d8-9350-11e8-9321-e9d1e334fb01.png)



So it is not a bug, just a classic error about the escaping of html char ;)
Have a good week end

**Comment by Yenthe666** [comment]
Hey,

Just a quick note & feedback here as we discussed through another channel.
Thanks a lot Jérémy, `t-ignore` is probably my best bet to get around this annoying problem.

Have a good weekend too.
