### ISSUE TITLE
 Inheritance by delegation views and active_id

### ISSUE THREAD

**Issue by master-one** [odoo/odoo#26168]
**LIKE IT OR NOT.**
 ****IT'S A FAULT OF ODOO.**** 

**REASON:** 
WHEN INHERITING BY DELEGATION, 

THE INHERITED VIEW USES THE 
ID OF THE INHERITING MODEL (SUBCLASS) AS THE ACTIVE ID 

FOR THE ELEMENTS OF THE FORM ASSOCIATED WITH
THE INHERITED MODEL (SUPERCLASS). 

I've created a child module of product.template using Inheritance by delegation. I've created a view that inherits product.product_template_form_view.

Problem is that when I'm viewing my child form the buttons that are referring to the product.template model are using the id of my module and not product.template. This is causing issues for variant prices. 

I still want the all the functionally of product.template to be associated with that model.

Here is some excerpt of code to help illustrate what my problem is.
![2018-08-04 14_24_36-aashvi bra - odoo](https://user-images.githubusercontent.com/42087736/43676252-18386d14-980b-11e8-8f4a-8b2a184bb3d7.png)
![2018-08-04 14_23_38-variant values - odoo](https://user-images.githubusercontent.com/42087736/43676253-1d5edb8e-980b-11e8-95e3-305a8fa6447a.png)
![2018-08-04 14_31_01- models py - official - visual studio code](https://user-images.githubusercontent.com/42087736/43676255-2bded3ee-980b-11e8-9e41-533fe99eeff0.png)
![2018-08-04 14_41_04- views xml - official - visual studio code](https://user-images.githubusercontent.com/42087736/43676256-30482066-980b-11e8-9713-206e4e858647.png)
![2018-08-04 16_27_36- views xml - official - visual studio code](https://user-images.githubusercontent.com/42087736/43676258-32bcd21a-980b-11e8-9c2b-4131c1f980fd.png)

The view inherits product.product_template_form_view but  working with official.bra ( inherited product.template by delegation). 
All fields and buttons will be displayed. Problem is that when the variant prices button is clicked it's supplied the official.bra id as the active_id, not the corresponding product.template id. 

In this case product.attribute(variant) is using the wrong ID.

I would expect that when a view is being extended to a different model, the components that where added would work with the model of the view they are added to, not the model of the final. Otherwise, any component would need to work its way up the inheritance until it found the expected model.

**Comment by pedrobaeza** [comment]
OK, you got it: you will have an opened issue for now... but unresolved.

I think you try to create a product.product instead of a product.template, and thus the inheritance by delegation should be on product.product record, but I'm not able to deduce it from you report, as spitting out a lot of code and screenshots is not the way for understanding it. You should focus on the exact problem and put only the relevant things. This is better explained in http://www.catb.org/esr/faqs/smart-questions.html, but some people get offended with this.

Remember that this issue tracker is for putting direct problems in features or bugs, but not to cover general development questions. And even not being the case, there's no obligation of answering it, as this is made in a best effort approach (I'm myself not and Odoo employee). Please take this into consideration before being unrespectful writing everything in upper case.

**Comment by Elkasitu** [comment]
Try again by being more civil

**Comment by Yenthe666** [comment]
@master-one in fact you're talking to one of the most known community members. Pedro has years of experience and out knowledges plenty of people from the community. You might want to rethink your steps here, think about you communicate in a decent way and then we can see if we can help you again.
Yelling or throwing dirt at somebody is easy but has no purpose, you'll only achieve the opposite of what you want.

**Comment by Yenthe666** [comment]
Not compliments, it's true. You have a great knowledge of Odoo and others should respect that. We don't always agree on each other but I can see you have some great skills and knowledge. ;)
