### ISSUE TITLE
No way to associate a transfer with a purchase order

### ISSUE THREAD

**Issue by mightyiam** [odoo/odoo#26324]
Impacted versions:
11.0

Steps to reproduce:
1. Create a purchase order.
1. Delete its automatically created transfer

Current behavior:
There is no way to create another associated transfer!

Expected behavior:
There should be a way to create a new transfer and have it associated with the purchase order.

**Comment by mightyiam** [comment]
Is there a workaround, please?

**Comment by sswapnesh** [comment]
Hello @mightyiam
You should ask this on Odoo official forums ([https://www.odoo.com/forum/help-1](https://www.odoo.com/forum/help-1)) or mailing list ([https://odoo.com/groups](https://odoo.com/groups))

As a workaround You can Cancel it --> Reset to Draft --> Confirm again, So this will generate Transfer.

**Comment by mightyiam** [comment]
@sswapnesh thank you for responding.

Regarding posting it here or in the forums, [I did post it in the forums and got no help](https://www.odoo.com/forum/help-1/question/can-t-associate-a-transfer-with-a-purchase-order-after-probably-deleting-the-automatically-created-one-137659). But regardless of that, this seems like a bug to me. Doesn't it? I can't associate a transfer with a purchase order manually. If I delete the automatically created one, I end up with a purchase order that could not be fulfilled.

> As a workaround You can Cancel it --> Reset to Draft --> Confirm again, So this will generate Transfer.

I don't have access at this particular moment but I remember that I can't cancel it because it has bills already.

I tried to fix the situation via a Python shell so [I asked this question on how to do it](https://www.odoo.com/forum/help-1/question/how-to-obtain-and-run-a-method-on-a-model-instance-through-the-python-shell-137933) and looked at the following code to understand what I could do to recreate another transfer in a way similar to what `_create_picking` does and I'm not sure what I did wrong. In the UI a new transfer was not showing. Maybe I missed a necessary method that performs the actual write to the database? Maybe I just made a mistake. I'll try again. I'd love some tips. I can read the code. I don't know the API.

https://github.com/odoo/odoo/blob/a06747c03d30b6b463655884b6875db6b9588003/addons/purchase/models/purchase.py#L332

https://github.com/odoo/odoo/blob/a06747c03d30b6b463655884b6875db6b9588003/addons/purchase/models/purchase.py#L419-L440

**Comment by nhomar** [comment]
Hello.

@mightyiam the **workaround** should be not delete it but cancel it, and add an access rule to avoid delete it by mistake.

IMHO this is an expected behavior in odoo, Why?.

- The auto creation of pickings is not only for the purpose of the new picking document, 
- costs are computed based on this relation.
- FIFO is automated also and set in quants.

Then this is not as simply as **Allow create a new picking** we should program the inverse relation which will lead to more questions.

- What if the total of elements in the new picking is not in the purchase order?.
- What if the new picking does not match with the lines in the order.

Then, Solution?

1. Delete the picking? , block that option.
2. Cancel the picking, cancel the order and re-validate it again.
3. The reception is not the same of the asked? that's ok, create a backorder (in the reception wizard it is available).
4. Are you receiving more than what was asked for?, set a different **done** value.

If both auto-related records (picking and order) are does not match, the order will not be auto-closed, then **lock it manually**

In terms of report the **Locked** PO's will be the one with differences, the properly **done**.

I hope it helps.

**PS:** I am not saying this is not an issue by itself, but IMHO with th current state it is more a wish list.
**PS2:** In master you can try it and now is the time before it is freezed to see if it is considered or not.

**Comment by mightyiam** [comment]
To try to fix the problem in my database, I got a shell running with `odoo shell -d dbname`.

Then, I did something like this:
```python3
>>> order = env['purchase.order'].search([('name', '=', 'PO00015')])
>>> order.picking_ids
stock.picking()
>>> order._create_pickings()
stock.picking(44,)
```
And so I had hopes that this would do it, yet, I'm not seeing this new transfer in the UI at all. I'm sure to be missing something critical, such as a method that actually performs the write to the database or maybe I'm not working on the correct database? There's only one...

This this approach make sense, anyway? It seems so to me, according to the code.

**Comment by lap-odoo** [comment]
@mightyiam I definitely agree with @nhomar , it's not as simple as allowing to create a new picking and link it to the PO.  That's definitely not a bug but a feedback (especially since there is an acceptable workaround as explained by Nhomar).  Thanks

**Comment by mightyiam** [comment]
I appreciate the help. I do not understand the workaround entirely. Something to do with locking the PO, right?

Why wouldn't the approach of calling `order._create_pickings()` work, please?

And why do I not see the new picking (id 44 in the example) in the UI, please? I must be missing something basic that I don't know about the API.

**Comment by gdgellatly** [comment]
you probably didn't commit the transaction before closing your session.

**Comment by mightyiam** [comment]
I searched around a bit and couldn't find how to commit a transaction. An Odoo developer should know, I guess. Is it very simple?

**Comment by gdgellatly** [comment]
Env.commit() or similar depending on exact setup

**Comment by mightyiam** [comment]
`env.cr.commit()`. Thank you. This seems to have done the trick.

I'm not sure what the issue tracker policy is, so I'm not sure what to suggest. Wishlist? I wish this bug hadn't hit me and cost me so many hours to workaround.
