### ISSUE TITLE
[10.0][Community] account asset active true/false

### ISSUE THREAD

**Issue by HaraldPanten** [odoo/odoo#26374]
Impacted versions: 

at least V 10.0. I don't know if it happens in 9.0 and 11.0 as well.

Steps to reproduce:

1- Accounting --> Adviser --> Assets

2- Create an asset as an example (name = EXAMPLE). And make a relation with an invoice. (field invoice_id), we can imagine INV/001.

3- Go to INV/001 and cancel it.

4- If you go back to Accounting --> Adviser --> Assets you can create a filter in the advanced search option. 

The filter should be: "Active" - "is false". It means that the invoice that the asset was related to, has been cancelled. 

You'll see that EXAMPLE is in "Active" - "is false" category right now.

That's the normal/correct behaviour.

5 - Go back to INV/001 and reset that to draft. Validate it again.

6- The EXAMPLE asset should be active again, cause the invoice is not in cancelled status. But it still un "Active" - "false" status whe you search it in Accounting --> Adviser --> Assets.

Current behavior:

The asset still not active, even if validating the invoice related to it.

Expected behavior:

The asset should be active if the invoice related to it is not in status "Cancelled".

P.D: I know it's not a critical bug, but I think it should be corrected.

Thanks!

**Comment by pedrobaeza** [comment]
Current behavior is correct:

* You create an invoice with an asset category.
* When confirming the invoice, the asset is created.
* If you cancel the invoice, the asset is set as active = False.
* If you move to draft and reconfirm the invoice, then a new asset is created (because you might change amount, quantity, etc).

And thus, there's no bug in Odoo core.

Closing by the reasons above.

**Comment by HaraldPanten** [comment]
OK @pedrobaeza ,

Thanks for your immediately reply :+1:
