### ISSUE TITLE
Double iteration through the objects in the mrp.repair report in Odoo v.10

### ISSUE THREAD

**Issue by DarkoNikolovski** [odoo/odoo#26440]
https://github.com/odoo/odoo/blob/b4cbf0bb61590680ae0e56a254d72e966977b8d2/addons/mrp_repair/report/mrp_repair_templates_repair_order.xml#L5

Since it is done in `report_mrprepairorder2` no need for that in `report_mrprepairorder`

**Comment by pedrobaeza** [comment]
It has been repaired in 11.0 in https://github.com/odoo/odoo/commit/869b833618f727710f75ee61eca508bd3128e181, but 10.0 still keeps it. @tde-banana-odoo can you backport the fix?

**Comment by DarkoNikolovski** [comment]
@tde-banana-odoo any chance of backporting the fix into 10.0 following days?

**Comment by Yenthe666** [comment]
Dear @DarkoNikolovski,

As Odoo 13 has been released last week it means that our support for Odoo version 10 has been stopped.
If you can still reproduce this issue on a newer version (version 11, 12 or 13 at the point of writing) then please do respond back or create a new issue.
Sorry that we didn't get around to resolving your issue for V10 but it has been fixed in V11 and up normally.

Regards,
Yenthe
