### ISSUE TITLE
Report Designer can´t download reports

### ISSUE THREAD

**Issue by StefanKlatt** [odoo/odoo#2654]
odoo 8 (clone from yesterday evening) on CentOS 7
OpenOffice Report Designer 8.0.0.1
OpenOffice 4.1.1 on Windows 7 64Bit German

I can connect to the odoo server, see the reports, but if I try to open one I get the following error:

The report could not be downloaded
Report: d:\users\stefan1.bue\appdata\local\temp....
Details: URL seems to be an unsupported one.

"d:\users\stefan1.bue" isn't correct, it should be "d:\users\stefan.buero"
Openoffice is configured correct. 

![140923 report designer1](https://cloud.githubusercontent.com/assets/1131895/4380802/b233187a-436d-11e4-984e-9c9137a4b51b.PNG)
![140923 report designer2](https://cloud.githubusercontent.com/assets/1131895/4380803/b232d9be-436d-11e4-8500-25325051966b.PNG)

**Comment by BrahimDa** [comment]
same problem here,

Anybody got the solution???

**Comment by lukebranch** [comment]
@BrahimDa ,

I believe this is related to an issue with the uno package in Ubuntu 14.04. In Ubuntu 14.04 this package is written for Python 3+, however Odoo and all (standard) related dependencies are written for Python 2.7+.

This is also an issue that I ran into with the Aeroo Reports library which also uses OpenOffice/LibreOffice  and as a result also pyuno. Aeroo reports has since resolved this issue for Aeroo reports using the Aeroo_DOCS (https://github.com/aeroo/aeroo_docs) module.

What I recommend is learning to use Aeroo reports. I've written a quick step-by-step tutorial on how to install it in Ubuntu 14.04 here:

https://www.odoo.com/forum/help-1/question/8-0-how-can-i-install-the-official-aeroo-reports-alistek-for-odoo-version-8-solved-76044

I have not had any success with the OpenOffice Reports Designer in Odoo 8.0 for Ubuntu 14.04 however so I would not recommend pursuing this method unless you are using a version of Ubuntu (eg. 12.04) that includes a Python 2.7 version of the uno package.

**Comment by mrpatos** [comment]
Well I can confirm the Error.. running Debian Wheezy which should run Phyton 2.7

**Comment by Yenthe666** [comment]
Hi @StefanKlatt ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment). This tool is no longer supported in later versions so you shouldn't ever run into it again.

Regards,
Yenthe
