### ISSUE TITLE
Archive contact: another refresh issue

### ISSUE THREAD

**Issue by Linekio** [odoo/odoo#26604]
Impacted versions:
11.0
Steps to reproduce:
I added this code to add an "Active/Archive" button on Partner's contact forms:
```
<record id="view_partner_form.inherit" model="ir.ui.view">
    <field name="name">res.partner.form.inherit</field>
    <field name="model">res.partner</field>
    <field name="inherit_id" ref="base.view_partner_form"/>
    <field name="arch" type="xml">
        <xpath expr="//field[@name='child_ids']//form//field[@name='type']" position="before">
            <div class="oe_button_box" name="button_box">
                <button name="toggle_active" type="object" class="oe_stat_button" icon="fa-archive">
                    <field name="active" widget="boolean_button" options="{'terminology': 'archive'}"/>
                </button>
            </div>
        </xpath>
    </field>
</record>
```
Current behavior:
On click "Archive", the contact continue to appear. I have to refresh the browser so that it doesn't appear anymore
Expected behavior:
Works :)
Video/Screenshot link (optional):
[Click here](http://www.k-upload.fr/afficher-video-2018-08-27-1d9a992beoutput.mp4.html)

**Comment by pedrobaeza** [comment]
You have to add `options="{'reload_on_button': true}"` for that.

**Comment by Linekio** [comment]
It's doesn't work.
I think that the feature "reload_on_button" doesn't exist anymore in V11.0.

**Comment by pedrobaeza** [comment]
Yeah, it seems so...

@ged-odoo is `reload_on_button` deprecated? What is the alternative?

**Comment by ged-odoo** [comment]
Hey @pedrobaeza 

I was not aware of the reload_on_button attribute!  It is most likely one of the casualties of the rewrite of the views.  Since it is not documented nor tested, it was lost.

I do not have a really good alternative, but I can tell you that some people implement a dummy method on the model (see https://github.com/odoo/odoo/blob/11.0/addons/account/models/account_payment.py#L449) and add it to the footer of the form view (see https://github.com/odoo/odoo/blob/11.0/addons/mrp_repair/views/mrp_repair_views.xml#L128)

This is not very clean, but I suppose it works.

**Comment by ged-odoo** [comment]
I hope that this kind of situation will not happen again in the future.  We need to be much more rigorous regarding the documentation and the tests...

**Comment by Linekio** [comment]
But in this example the dummy method requires a manual action from the user. (As much as a refresh of the page...).

**Comment by intero-chz** [comment]
@ged-odoo please don't reintroduce those dummy buttons again. I know it's only a suggestion for a workaround, but these buttons are just user UNfriendly, especially since computed fields "reload" so beautiful in the client.

I've started with Odoo 7 and the documentation for widget options and other useful attributes or widgets themself were not existing then. You are the JS god at Odoo (and after your presentation at last years odoo days you're my JS god, too ;-)), could you please force a good documentation for such things? Odoo has so much potential on that side and it even improved after the big rewrite. With proper documentation developers can exploit the full potential :-)

**Comment by ged-odoo** [comment]
@Linekio In your video, the user clicked on the footer button to close the dialog.  Maybe you can replace the footer of the dialog with your own footer (using the <footer> tag) and add your button Close which has the dummy method as mentioned.

This is just an idea to work around your issue.  I agree that the issue would be better solved by an appropriate attribute (with documentation and tests!)

@intero-chz wow, thanks for the part about JS:)

About the documentation, all new commits are now reviewed, and we enforce tests/documentation if we change the attributes/options/architecture of something. We also have now 2 new documentation pages:

* https://www.odoo.com/documentation/master/reference/javascript_reference.html
* https://www.odoo.com/documentation/master/reference/javascript_cheatsheet.html

I think that last year was the year we started to get 'serious' about testing the javascript. My team and I are working on 'professionalizing' various aspects of the framework (code, but also doc/tests/migrations/internal processes/onboarding/...).  There are so many things to do (also, this year, we had other non framework JS code to write), and progress is slow.  But I think that the team is good, and I have the feeling that more positive changes are coming.

**Comment by Linekio** [comment]
@ ged-odoo Since the active / archive button is already a call to a method (toggle_button), I suppose a dummy method will not refresh the view. (And will not close the popup)

**Comment by msh-odoo** [comment]
@Linekio I have two other workaround for this: 1) Create a button in footer as @ged-odoo suggest which will call method, pass context on button for parent record ID like ```context={'parent_id': parent.id}```, now you method will do operation of archive/unarchive and then returns same action which opens partner's form view, we will pass ```res_id: context.get('parent_id')``` in action

2) Return client action with tag reload(which I will not prefer as it will reload whole page)

I agree with @ged-odoo It is just alternatives, better solution is to support option to reload view(we had ```reload_on_button``` option for this purpose).

**Comment by Linekio** [comment]
Thank you it works well.
Whatever I would prefer for example a solution like:
```
@api.multi
def toogle_active(self):
    super().toogle_active()
    return {'type': 'ir.actions.client', 'tag': 'refresh'}
```
And in JS:
```
function Refresh() {
    // What to write here ?
}
core.action_registry('refresh', Refresh)
```

**Comment by Linekio** [comment]
@ged-odoo  Replace the "close" button for a dummy method cause another issue: if I create a new partner, and a new contact, and I want to cancel by clicking on "close" button.
