### ISSUE TITLE
Empty notebook, because of 'groups' attribute, shows the first page content.

### ISSUE THREAD

**Issue by MicheleZak** [odoo/odoo#26677]
Impacted versions: 
10.0

Steps to reproduce: 
Add a notebook to a form view, with one or more pages, and make each page not visible with the 'groups' attribute.

Current behavior:
It prints the content of the first page, i think because of the 'active' class given to that page.

Expected behavior:
If all pages are invisible the whole notebook should be hidden.

**Comment by pedrobaeza** [comment]
As this has been fixed in latest version, and it's quite difficult to achieve in previous one due to the change of the JS engine, I will close this as won't fix for this version, sorry.

However, if you have an enterprise contract and want to try if this can be solved through enterprise service support, put a ticket in https://odoo.com/help to see possibilities.

**Comment by sswapnesh** [comment]
As workaround I would suggest you to add same Groups on those fields.

**Comment by MicheleZak** [comment]
Ok. I added the 'groups' attr to the notebook listing all the groups used in the pages, so it hides the whole notebook. Thanks
