### ISSUE TITLE
Leaves by Department report not displaying correctly

### ISSUE THREAD

**Issue by E4O** [odoo/odoo#26790]
Impacted versions:
Odoo v 11 Leaves app 11.0.1.5

Steps to reproduce:
1. Go to the Leaves app
2. Select from reporting Leaves by department
3. From options, select department where you have more than 15 employees
4. Print it out.

Current behavior:
Currently, on the print out, first 2 rows areon top of each other:
![image](https://user-images.githubusercontent.com/40301417/45087696-79bf3500-b10f-11e8-9808-22af9d1c331c.png)

In the first 2 rows there is information as "month", "department and Employees". At the same time on the first 2 rows there are already employees names.

Expected behavior:
Employees names should start on the 3rd row.

Video/Screenshot link (optional):

**Comment by JeelBKhanpara** [comment]
it working perfect on Odoo v 11 Leaves app 11.0.1.5

tested on http://371478-11-0-1b4757.runbot17.odoo.com/web/login

![leave](https://user-images.githubusercontent.com/13703474/45355012-d7a2bf80-b5dc-11e8-8afe-0efc23a0e7dc.png)

**Comment by E4O** [comment]
Please scroll down a bit, you are on the first page but the problem appears on second and third and etc pages. First page is fine.

**Comment by JeelBKhanpara** [comment]
> Please scroll down a bit, you are on the first page but the problem appears on second and third and etc pages. First page is fine.

you can see in pdf there is no issues i think wkhtmltopdf version issues at your side or something customized.

[Leaves Summary (4).pdf](https://github.com/odoo/odoo/files/2382631/Leaves.Summary.4.pdf)

**Comment by RomainLibert** [comment]
Hello @E4O 
It seems that your issue is not reproducible, as pointed by  @JeelBKhanpara this issue might come from wkhtmltopdf.

The problem with wkhtmltopdf is that it is never easy to know exactly how to fix the issue, these issue often have to do with the fonts installed on your system or the version of wkhtmltopdf (Currently I'm using v0.12.1 which is 4 years old and I am afraid to upgrade because it will break things
