### ISSUE TITLE
Supplier discount

### ISSUE THREAD

**Issue by ahetland** [odoo/odoo#26803]
Impacted versions: v9 - v11

Steps to reproduce: Enter a supplier invoice having activated discount on lines give it 100 net and a 2% discount (no tax).

Current behavior: When entering an invoice net 100 (without vat) and give 2% discount the amount entered / posted to the account_move_line is 98 (net of 2 discount).

Expected behavior: The 100 should be posted. 
Reason: The full liability must be posted and only when paying you can deduct the discount that has been granted (according to GAAP). The 2 in "income" will then be credited to an account. The argument in GAAP is that you do not know if you will take the discount or not therefore you actually pay. 

Video/Screenshot link (optional):

**Comment by gdgellatly** [comment]
@ahetland You need to reference the exact standard.  Under IFRS this is simply not true.  In fact the exact opposite is true.

For a product discount you would need to recognise the net amount at the time under IAS 2.
For a prompt payment discount it would depend on past behaviour.  If you always paid early and received the discount, then effectively IAS 12 applies.  

Otherwise it would require recognition under IAS 37.  As the event giving rise to the payment is wholly within the entities control, then you would need to recognise a provision in your Trade Payables.  However, you would still need to recognise the corresponding amount in your inventory under IAS 2 paragraph 11.

In fact it is even more complex than that, because under paragraph 11 you must recognise all discounts, and rebates at the time of goods reception including those not on the invoice.  Ordinarily I do that through a custom module which netts out the inventory and raises an accrual in assets for amounts due.

But moreover, given nearly all accounting standards at least under IFRS  have moved to a more principle based economic substance test rather than transaction form (e.g. Lease changes effective 1/1/18) I simply cannot see how your assertions can be correct under any GAAP.

However if you believe otherwise, you can simply add discount as a separate line and accrue those amounts wherever you like.  In this case you would probably accrue to trade payables, or a provision therein, and then deduct from that account at payment.

**Comment by gdgellatly** [comment]
@ahetland where are your references again to this. I have never heard of prudence being a principle of IFRS.  AFAIK the only 2 required principles of presenting financial information are faithful representation and relevance.  And even then it is pretty narrowly targeted to creditors and investors.

In any case, there is an easy way, and that is to add a seperate discount line.  If you put it to trade payables you end up with an entry of something like.

CR Trade Payables 98
DR Product 100

In terms of how this discounts work under varying tax laws will depend on whether you apply tax to the discount line.

I can assure you IAS 37 must apply as there is a constructive obligation arising from a past event, and therefore that information

**Comment by pedrobaeza** [comment]
No more answer, so closing this.
