### ISSUE TITLE
After creating new price list, it was randomly assigned to several other customers 

### ISSUE THREAD

**Issue by zkranjcec** [odoo/odoo#26842]
Impacted versions: 10

Steps to reproduce: Create new pricelist from Customers Form and then several other customers are linked to that same pricelist

Current behavior: User creates pricelist for almost all their customers becasue of the complex pricing model. After user creates new pricelist from Customers form and assign it to a customer which happens automatically, randomly several other customers were assigned to the same newly created pricelist. Problem is that those customers had already assigned pricelists. There should be no way for this kind of behaviour, but it is happening.

Expected behavior: This new pricelist should be assigned to only one customer at the moment of pricelist creation starting from Customers form and using Edit. 

Video/Screenshot link (optional):

**Comment by nhomar** [comment]
I am pretty sure the customer is by mistake editing the existing one, and/or some development there is creating wrongly things.

I have some setups like this one and I did not have this behavior.
I think we need more information to help you:

Version?.
Enterprise?.
Customs / no customs?
Since wqhen?
An step by step way of reproduce it?

**Comment by pedrobaeza** [comment]
Other possibility is that the order of the pricelists change, and now the default one is another.
