### ISSUE TITLE
[11.0] Error onchange mail.contact_list_ids  in mass_mailing

### ISSUE THREAD

**Issue by DR4RCON** [odoo/odoo#27094]
Impacted versions: 11

Steps to reproduce: Install mass_mailing, create a new mail.mass_mailing object. Select self.mailing_model_name == 'mail.mass_mailing.list', when changing the contact_list_ids  firefox throws javascript exception

```
Uncaught TypeError: Cannot read property 'apply' of undefined
    at OdooClass.normalizeArray (domain.js:265)
    at Class._initialize (domain_selector.js:512)
    at Class.prototype.(/anonymous function) [as _initialize] (http://mariew.tomws.ddnss.de/web/static/src/js/core/class.js:90:38)
    at Class._redraw (domain_selector.js:547)
    at Class.setDomain (domain_selector.js:494)
    at Class._render (basic_fields.js:2278)
    at Class.reset (abstract_field.js:299)
    at basic_renderer.js:110
    at Function._.each._.forEach (underscore.js:145)
    at Class.confirmChange (basic_renderer.js:107)
```

Expected behavior: no javascript error

Problem seems to be, that the domain variable is at this position https://github.com/odoo/odoo/blob/11.0/addons/web/static/src/js/core/domain.js#L255 a string, but have to be a javascript array.

Coming from here https://github.com/odoo/odoo/blob/11.0/addons/mass_mailing/models/mass_mailing.py#L455

**Comment by pedrobaeza** [comment]
I have just tried on runbot and there's no such problem. Look at the mass mailing:

http://375440-11-0-190841.runbot18.odoo.com/web#id=3&view_type=form&model=mail.mass_mailing&menu_id=217&action=253

Maybe a custom module or outdated code?

If you are still experimenting the same problem in your side, try first to update your source code to latest version, restart your server, and make a general module update for being sure that the problem is not there. 

If the problem continues, then it can be due to a third party module or indeed an Odoo bug. For discarding the first one, you have to try the use case in the runbot infrastructure, that are DBs automatically deployed with all the standard modules installed, accessible in http://runbot.odoo.com/runbot. If you reproduce the problem there, then please open a new issue with all the steps done before getting the error. Don't be shy to include all the possible details, and even better if you provide some screenshots or videos.
