### ISSUE TITLE
[WISH] [USABILITY] option to skip dropdown search and go straight to popup

### ISSUE THREAD

**Issue by elgow** [odoo/odoo#27205]
Impacted versions: 10.0, 11.0

Steps to reproduce:  Have a related field with many rows in the DB. 

Current behavior: User searches to select one item. Odoo related field JS code first displays a small drop-down list with a few items, plus a "Search more..." link. User ALWAYS has to select "Search more..." to get an effective search. 

Expected behavior:  Users really want to skip the extra click every time to get to the full search popup.  Can it be made possible with a context option to skip the initial dropdown and go straight to the popup provided by `_searchCreatePopup`?  Users would appreciate the improved usability.  

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
@ged-odoo might be interesting for you in V13 or up?

**Comment by pedrobaeza** [comment]
I don't think this should go in core, as I find very useful the short list, and putting option makes unnecessary complicated the base. This is the perfect candidate for an extension module that provides that option.

**Comment by gdgellatly** [comment]
@ged-odoo This was actually the behaviour in v7.  It is a little bit annoying, enough to comment on a bug report, not enough to raise one :).  I spend a bit of time with users doing training and it is often a mistake they make, unknowingly searching instead of selecting dropdown.  For me, I agree it should be an option, applying to frequently searched fields, e.g. Customer on Sales Orders, Or account on journal items.  Otherwise those big search views will get a lot longer. (Or of course you could arbitrarily say, the first n items in a search view are the "frequent" ones).

**Comment by elgow** [comment]
Having looked at the code I'd say @ged-odoo is correct. The option would be a few lines of JS code around addons/web/static/src/js/fields/relational_fields.js:373. Doing it as an extension module would likely require replacing that whole function and it would be fragile if the web code ever changes. 

It is not a bug, which is why I marked it [WISH]. The difference is only 2 clicks per search, but it's at the top of the list of complaints from my users (after I patched in full-text search, that is).
