### ISSUE TITLE
[11.0] Could not delete Archived Calendar event

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#27267]
Impacted versions: 11.0-saas~11.5 @ [Runbot](http://378641-saas-11-5-8eb766.runbot18.odoo.com/web?#action=167&model=calendar.event&view_type=list&menu_id=113)
Steps to reproduce:
Archive Calendar Event and Try to delete
![9 9](https://user-images.githubusercontent.com/16624719/46102567-46426880-c1ec-11e8-8962-d35267871b25.png)

Current behavior:
Event is not deleted
Expected behavior:
Event should be deleted
Video/Screenshot link (optional):

**Comment by sswapnesh** [comment]
@mart-e  Thanks for Correcting labels.
I am able to reproduce same on v11.

**Comment by bennals** [comment]
I also experienced this yesterday on 11.0 CE (local installation, source code pulled from github a week or so ago).  I was seeing 'phantom' notifications from a calendar item that I thought I had deleted weeks ago.  Turned out the item hadn't been deleted - just archived - and I couldn't delete it until I made it active again.

**Comment by bennals** [comment]
I also experienced this yesterday on 11.0 CE (local installation, source code pulled from github a week or so ago).  I was seeing 'phantom' notifications from a calendar item that I thought I had deleted weeks ago.  Turned out the item hadn't been deleted - just archived - and I couldn't delete it until I made it active again.

**Comment by bennals** [comment]
Still not resolved nine months later:(

It would be great if this could be addressed before support for 11.0 ends.  We use a lot of recurring calendar events and reminder notifications in my organisation and when schedules into the future are changed (like every 1st Wednesday to every 3rd Wednesday for a given event) it's very confusing for users, not to mention  inspiring of doubt about the robustness of Odoo for those new to the platform, when they keep getting reminded to do something at the wrong time and the admin can't do anything about it.

**Comment by Yenthe666** [comment]
In all honesty: I do not think that anybody at Odoo S.A. will look back at this one as the 11.0 is nearly end of life.. :-/ You might want to make a PR against 11.0 to fix this yourself, it is probably your best bet to get it in the official code.

**Comment by mart-e** [comment]
Hi,
Actually I did not understood the bug report.

> Steps to reproduce:
> Archive Calendar Event and Try to delete
> Current behavior:
> Event is not deleted
> 
What do you mean it is not deleted? Do you get an error when deleting?
I just tried, removing an archived calendar.event record works.

**Comment by sswapnesh** [comment]
Hello @mart-e 

I am able to reproduce same on Latest v11 Build at http://541000-11-0-ca8b35.runbot21.odoo.com/web?#view_type=list&model=calendar.event&menu_id=149&action=182

![screenshot-541000-11-0-ca8b35 runbot21 odoo com-2019 06 17-22-32-30](https://user-images.githubusercontent.com/16624719/59622675-dc8a3600-914f-11e9-8b57-401db99cadc9.jpg)

> Do you get an error when deleting?

No

> I just tried, removing an archived calendar.event record works.

After deleting it is still there. (Archived records were there and Maybe they are linked to `recurrent_id`)

Ps: Looking at the code it seems like intended behaviour when `recurrent_id` is linked to event. I don't know the reason behind keeping them. (or Maybe it should be deleted when we are removing it explicitly)

https://github.com/odoo/odoo/blame/12.0/addons/calendar/models/calendar.py#L1715-L1738

**Comment by bennals** [comment]
@Yenthe666 I would if I had the skills...unfortunately I don't.

@sswapnesh Yes, that's the same thing I experience.

Delete a calendar event that is recurring -> Event appears to be deleted at first glance but filtering on 'Active' = 'False' reveals that the events are still there...just archived.

Try to delete said archived event -> Nothing happens.  The event just stays there in the 'Active' = 'False' filtered list.

As previously described, notifications associated with archived calendar events (recurring ones so that they occur into the future) continue to fire.

To be honest, I wouldn't mind if deleted events were actually only archived, as long as associated notifications stopped firing once they were archived.

**Comment by mart-e** [comment]
@sswapnesh ok I understand now, your report lacked the recurrent information.
So when trying to delete a recurrence of a recurrent event, it is not deleted but, instead, it is converted to a real event (to be able to change its attribute) and archived (to hide it from the calendar).
If you try to delete the newly created archived event, it is not deleted but this is a good thing, otherwise another virtual event would be created again.

@bennals could you please open another issue to describe your issue and how to reproduce it? Thanks

**Comment by bennals** [comment]
@mart-e ok, will do.
