### ISSUE TITLE
[11.0] HR Holidays/leaves request: default creation state 'confirm' instead of 'draft'

### ISSUE THREAD

**Issue by dz-hurricane** [odoo/odoo#27270]
Impacted versions: 11

Steps to reproduce: Create a new HR holidays/leave request

Current behavior: Confirm as default state

Expected behavior: Draft as default state

Video/Screenshot link (optional):

**Comment by RomainLibert** [comment]
Hello @dz-hurricane 
I understand that you might find that behaviour counter intuitive as when created the leave request is already confirmed.
But this is not a bug as we definitely chose to implement it that way (it is like that since v7.0), hence we will not change that in a stable version of Odoo (like the 11.0)
