### ISSUE TITLE
12.0 - iap: commit is executed from partner_autocomplete.default_get

### ISSUE THREAD

**Issue by moylop260** [odoo/odoo#27318]
Impacted versions:
12.0 (saas-11.5)

Steps to reproduce:
`partner_autocomplete` module has a field default defined for `res.config.settings` like:
 - `default=lambda self: self.env['iap.account'].get('partner_autocomplete').insufficient_credit)`

   - https://github.com/odoo/odoo/blob/a01c1bf5bf377471c1c0fb31a20b59fc116fd545/addons/partner_autocomplete/models/res_config_settings.py#L7-L9

`iap.get` method calls `self.env.cr.commit()` method:
  - https://github.com/odoo/odoo/blob/a01c1bf5bf377471c1c0fb31a20b59fc116fd545/addons/iap/models/iap.py#L151-L158

Run a script similar to
```bash
# Code that I like to rollback
self.env['res.config.settings'].create({...}).execute()
self.env.cr.rollback()
```

Current behavior:
A commit is executed and it is not possibe to rollback it.

Expected behavior:
Rollback available

If you run a tests checking a configuration you will have the tests commited too :(

**Comment by rrahir** [comment]
I agree with you, the commit() should not happen be default. Since we want to keep the default behaviour of the get() method on iap.account objects, we suggest the following fix https://github.com/odoo-dev/odoo/commit/9f18d4c7d3408916eaaa973ecd354e8bf9b846f2
This will ensure that we only create the account on a user input.

**Comment by rrahir** [comment]
Fixed as suggested in the previous message in commit 0dd92f7f2150355c1d9e2e28e4c44dd833e8e868
