### ISSUE TITLE
Will accounting module be removed from community edition on Odoo 12?

### ISSUE THREAD

**Issue by AngelGL** [odoo/odoo#27386]
Impacted versions:
12.0

Link to commit -> https://github.com/odoo/odoo/commit/2e63ead842a0d2ccd3a78e9453e6d224650b8790

The last commit removes the account_asset completely and moves it to the enterprise. Does it mean that we won't be able to use the accounting module on open source edition?

**Comment by Yenthe666** [comment]
Hi there,

Looks to be the case yes. I'll let @antonylesuisse or @mart-e confirm this.

**Comment by jlzhou** [comment]
account budget module went to heaven together.

**Comment by lukebranch** [comment]
I wonder if this is meant for 12.0, or 13.0.

Another branch was added:
saas-11.5-start12

Which seems to suggest it will become 12.0 instead of 11.5 as originally thought.

The modules account_asset and account_budget are both in this branch:

https://github.com/odoo/odoo/tree/saas-11.5-start12/addons/account_asset
https://github.com/odoo/odoo/tree/saas-11.5-start12/addons/account_budget

With that being said It would still be a great loss to lose these modules in 13.0.

As OEX2018 is a few hours away, I guess we will know soon enough once the 12.0 branch is created.

**Comment by mart-e** [comment]
Hello,

As you saw in the given commits, these modules were moved to enterprise in saas-11.5 which will become the v12 (as soon as it is released). Do not mind about the saas-11.5-start12 branch, it is for internal needs and will be discarded soon.

**Comment by dan18fan** [comment]
Yes I think so.

**Comment by AngelGL** [comment]
RIP Odoo CE (V12). Without the Accounting Module it's basically useless

**Comment by FanisTGT** [comment]
> RIP Odoo CE (V12). Without the Accounting Module it's basically useless

I completely agree

**Comment by pedrobaeza** [comment]
This is not true, as Odoo CE has accounting (module `account`), but it's hidden by default (you need to check "Show full accounting features" in your user), and some accounting features are enterprise only: reports, assets and budget, but this for OCA ecosystem exists: for having these features (and a lot more not covered by the core). You have the modules `account_financial_report`, `account_asset_management`, `mis_builder` and `mis_builder_budget`, and a a long etcetera.

**Comment by earmero** [comment]
Hi @pedrobaeza  could You please tell me Where I can Enable this feature??

**Comment by pedrobaeza** [comment]
It's already said.

**Comment by earmero** [comment]
just a comment if it can help someone in order to enable the "Show full accounting features" You need to have developer mode Enabled.

**Comment by FanisTGT** [comment]
@pedrobaeza, what about a common user of ERP system like a accountant. Developer mode is available only for superuser. In Odoo v12 account advisers or accountants does not have ability to manage accounts, moves, reconciling and so on?

**Comment by FanisTGT** [comment]
@pedrobaeza, I think it is very bad idea to ask regular users to use debug mode of system.
Don't you think so?

**Comment by pedrobaeza** [comment]
I don't like debug mode also, but this is current situation. You can pre-activate it with the module https://github.com/OCA/server-ux/tree/11.0/base_technical_features.

Any way, I think you don't need debug mode for using accounting, only for activating the permission (I'm not sure because I'm always on "debug" mode).

**Comment by FanisTGT** [comment]
I dare say that decision to move accounting features to enterprise version alarms others developers and most of them will stay in v11 or start to search other systems.

**Comment by pedrobaeza** [comment]
What they should do is to join OCA and start contributing there if they want to be on open source side, or check enterprise offer if they go on commercial reseller side, but the solution isn't to stay in previous versions or go away.

**Comment by rmurillo21** [comment]
This videos shows how to enable this feature, and also refers to recently deprecated accounting reports in v12. https://www.youtube.com/watch?v=60p2prCrn2k
