### ISSUE TITLE
Unable to create bank profile because of STATE issue

### ISSUE THREAD

**Issue by bsurfing** [odoo/odoo#27497]
Impacted versions:12

Steps to reproduce:Accounting>Bank>(click in bank)>enter address>enter state

Current behavior:It won't search for state (which is in Odoo) and asks to create the state but when you enter the details it won't save because it already exists.

Expected behavior:Search and find the state (US) and allow to enter in the bank form

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/31522016/46588823-1870e580-ca70-11e8-9e5f-c06edcc55af7.png)
![image](https://user-images.githubusercontent.com/31522016/46588826-232b7a80-ca70-11e8-9373-e8895d26d884.png)
![image](https://user-images.githubusercontent.com/31522016/46588836-3f2f1c00-ca70-11e8-9e2c-41e6593f67c0.png)
![image](https://user-images.githubusercontent.com/31522016/46588838-46eec080-ca70-11e8-8350-7ab469142db0.png)

**Comment by Elkasitu** [comment]
Hello, this is not a bug but just a case of, IMO, bad view design:

The state field depends on the country selected, therefore in order for you to see the states, you must select a country first (United States in your case), which is unintuitive since the country field is after the state field in the view.

I will check with our Product Owners to see if it makes sense to change this
