### ISSUE TITLE
Cart content does not get cleared when checkout is done from another device

### ISSUE THREAD

**Issue by yostashiro** [odoo/odoo#27508]
### Impacted versions:

10.0, 11.0, 12.0

### Steps to reproduce:

- Log in to Odoo from Device A.
- Log in to Odoo from Device B with the same login.
- Add products to cart through Device A (note that the cart cart appears updated from Device B as well).
- Proceed with checkout through Device A.

### Current behavior:

Cart of Device B does not appear to be cleared (clearing cache also does not work).  It only appears to be cleared when user tries to update the cart next time (i.e. when user tries to add product to cart from Device B after the checkout from Device A, the first attempt does not work - it only seems to trigger the clearance of the cart in Device B).

It sometimes causes confusion to the user. e.g. User thinks a product has been added to the cart when it actually hasn't. 

### Expected behavior:

Cart of Device B gets cleared immediately after the checkout through Device A.

**Comment by yostashiro** [comment]
The same issue seems to exist in 12.0 so I just added the version.  It may be more problematic in 12.0 as it seems to trigger an internal server error when you try to update the cart from Device B after checkout from Device A.

**Comment by rdeodoo** [comment]
Fixed with https://github.com/odoo/odoo/commit/ef48b81ab127dd717a4a9d106edd5c51121bc8f7 in Odoo 10.0

**Comment by TimLai125** [comment]
>  Fixed with [ef48b81](https://github.com/odoo/odoo/commit/ef48b81ab127dd717a4a9d106edd5c51121bc8f7) in Odoo 10.0
> Thanks for your report

@rdeodoo, may I know what exactly has been fixed in the commit since we have actually reported two issues, i.e.
1. Cart of Device B does not appear to be cleared (clearing cache also does not work). It only appears to be cleared when user tries to update the cart next time (i.e. when user tries to add product to cart from Device B after the checkout from Device A, the first attempt does not work - it only seems to trigger the clearance of the cart in Device B).
2. in 12.0 as it seems to trigger an internal server error when you try to update the cart from Device B after checkout from Device A.

**Comment by rdeodoo** [comment]
_Short answer_: **both**.

_Long answer_:
Both were fixed with this commit.
It was the same issue in Odoo 10.0 11.0 and 12.0. Except the error would raise a traceback in 12.0 (before 12.0 it would just make the RPC to crash without a visual error for the user).
Note that the fix hasn't been forwardported to 12.0 yet.

For extended explanation, in both cases as the devices/browsers had their own different session and the sale order is stored in session, device B would still have the old sale order in it (the one that was paid with device A).

It would then throw an 'invisible' error for the user since it was a RPC fail if you tried to add a product in cart.
But changing quantity from the cart directly would indeed reset the cart since that part of the code was already handling the possibility of a wrong sale order in session and would reset it, redirecting you to the /shop.

**Comment by rdeodoo** [comment]
Note that the fix needed to be extended to `website_sale_options` module as this module has his own route to add the product to the cart that would not benefit from the original fix.

**Comment by rdeodoo** [comment]
The behavior is fixed in 10.0 and 11.0.
Fix will land in 12.0 asap.

About the `website_sale_options` that still has the issue, it will be fixed with https://github.com/odoo/odoo/pull/28209 once merged (again, in 10.0 and forwardported a few days after in 11.0 and 12.0)
