### ISSUE TITLE
PosBoxless setup issue

### ISSUE THREAD

**Issue by bishamontn** [odoo/odoo#2781]
I am trying to follow this guide https://doc.odoo.com/trunk/hw_proxy/ to setup the PosBoxless in an Ubuntu 14.04 server.

I have the latest github odoo 8.0 version up to date and a fresh database. I have installed the pyserial, pyusb and qrcode dependencies.

Then I need to install hw_proxy, hw_escpos, and hw_scanner. I can only install hw_proxy and hw_scanner because when I try to install hw_escpos give an "XmlHttpRequestError" in a white window and I can't do anymore until restart the server.

I have no error in logfile so I don't know how to fix it. Could it be some bug?

**Comment by JavierSantosLuna** [comment]
I'm just facing this issue, has someone solved it yet?

**Comment by yulybaseball** [comment]
I have the same problem. I installed this way:

$ sudo pip install qrcode
$ sudo pip install pyserial
$ sudo pip install --pre pyusb

Then I installed module hw_proxy.
After this, Odoo server stops every time a make a request. So, the error 'XmlHttpRequestError' you are seeing, is just because server stops. I started again... and again it stops...
I could never get to install hw_escpos and hw_scanner modules... server stopped every time I tried to install them.

**Comment by idncom** [comment]
Wow...so my solution on this made me feel a bit stupid but just in case others made the same mistake I did I figured I'd post a solution.

I am doing this on a vmware server and I did not have a USB controller on the hardware itself.  So I added the usb controller, rebooted ubuntu, typed lsusb and now there is a device.  Then went back and installed and everything worked.

1. Make sure you have a usb controller
2. Make sure operating system recognizes controller
3. Drink a cold beer as a reward for stumbling on something stupid for hours

**Comment by ticsemx** [comment]
No module named usb.core (Driver ESC/Pos Hardware)

TRY WITH:

##Remove existing Ubuntu/Deb usb app
sudo apt-get remove python-usb

##Since all versions of pyusb are either alpha or beta you must declare a specific version. 1.0.0b2 was the latest at this time.
pip install pyusb==1.0.0b2 

##QR Code is the next requirement
apt-get install python-qrcode

OR

$ sudo apt-get update
$ sudo apt-get install python-pip  #if you don't have pip installed already
$ sudo pip install pyusb

pip install pyserial

**Comment by Yenthe666** [comment]
Hi @bishamontn,

Thank you for your bug report.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
