### ISSUE TITLE
odoo12 website, Custom theme menu color is invalid.

### ISSUE THREAD

**Issue by offlove** [odoo/odoo#27821]
google cloud:
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic
Impacted versions: odoo12

**Odoo12 Choose BOOTSWATCH theme: Select theme's menu is invalid.
Odoo12 Choose DEFAULT theme: Custom theme menu color is invalid.**

![18_54_13__10_15_2018](https://user-images.githubusercontent.com/43988295/46987688-dd357d00-d127-11e8-90ec-6840d4789d2a.jpg)
<img width="1376" alt="20181015180611" src="https://user-images.githubusercontent.com/43988295/46987689-dd357d00-d127-11e8-81e9-c8bde4c47075.png">
<img width="1386" alt="20181015180827" src="https://user-images.githubusercontent.com/43988295/46987691-ddce1380-d127-11e8-90f3-401e1fae2df6.png">

**Comment by offlove** [comment]
> 请放一个相关的主题而不是“我认为这是一个错误”，并且不清楚你认为这是一个错误，虽然屏幕截图。我知道有时图像的数量超过1000个单词，但没有单词上下文的图像则不会。
> 
> 我看到你写的是[＃27808](https://github.com/odoo/odoo/pull/27808)。这是你提到的错误吗？

Odoo12: custom theme menu color is invalid.
Odoo12: selects the theme of the menu color is invalid.

> Please put a relevant subject instead of "I think this is a bug", and it's not clear what do you think it's a bug although the screenshots. I know that sometimes an image counts more than 1000 words, but an image with no word context doesn't.
> 
> I see that you have written in #27808. Is it the bug you are mentioning?

Odoo12: custom theme menu color is invalid.
Odoo12: selects the theme of the menu color is invalid.

**Comment by qsm-odoo** [comment]
@offlove I understand the issue, I will have a look but it has nothing to do with https://github.com/odoo/odoo/pull/27808

**Comment by offlove** [comment]
> @offlove我理解这个问题，我会看一下，但它与[＃27808](https://github.com/odoo/odoo/pull/27808)无关[](https://github.com/odoo/odoo/pull/27808)



> @offlove I understand the issue, I will have a look but it has nothing to do with #27808
tks reply,
There is also a css problem。
<img width="971" alt="11_42_15__10_16_2018" src="https://user-images.githubusercontent.com/43988295/47004762-d842ee80-d164-11e8-8979-348367aec1bf.png">

**Comment by pedrobaeza** [comment]
@offlove that's another issue that is already reported. Please don't mix things in the same thread.

**Comment by offlove** [comment]
> Please put a relevant subject instead of "I think this is a bug", and it's not clear what do you think it's a bug although the screenshots. I know that sometimes an image counts more than 1000 words, but an image with no word context doesn't.
> 
> I see that you have written in #27808. Is it the bug you are mentioning?

I installed this myself and found this problem.
And I found the same problem on many demo sites of odoo12.

**Comment by qsm-odoo** [comment]
About your 3 screenshots:

- I do not understand the first one, it works on my side:
![image](https://user-images.githubusercontent.com/10338094/47023788-b5164000-d160-11e8-9694-7bc4c610804a.png)
- Theme bootswatch interaction with website will be fixed by https://github.com/odoo/odoo/pull/27855. However, it will not make the navbar blue or dark as you want. When you choose a bootswatch theme, we only apply the theme to the website but we do not change the DOM of the website. The standard odoo navbar uses the light version of the bootstrap navbar and with cerulean theme it is still gray as you can see in their documentation: https://bootswatch.com/cerulean/. If you want to choose your colors, you should not use theme bootswatch.
- For the timezone bug, I suppose it will be handled elsewhere as @pedrobaeza said.

**Comment by offlove** [comment]
Your understanding is wrong.
Both default themes cannot change the color of the menu.
Can you try changing the menu color of the theme?

**Comment by qsm-odoo** [comment]
With default theme, as you can see, it works:
![image](https://user-images.githubusercontent.com/10338094/47029630-4ccd5b80-d16c-11e8-8a20-bd350deda80f.png)

In odoo 10.0 and odoo 11.0, we cannot choose the menu color with the default theme.

As for theme bootswatch: before odoo 12.0, we used bootstrap 3.3.7 and the navbar used the "default" style, which happened to be blue with the cerulean theme. Since odoo 12.0, we use bootstrap 4.1.3 and updated the bootswatch themes. The navbar we use is the "light" version (as the "default" version does not exist anymore), which happens to be gray in the new updated cerulean theme. If you want it to be blue as before, you can change the HTML thanks to the HTML editor to use bg-primary instead of bg-light and you will get the primary cerulean version which is blue.

**Comment by offlove** [comment]
> With default theme, as you can see, it works:
> ![image](https://user-images.githubusercontent.com/10338094/47029630-4ccd5b80-d16c-11e8-8a20-bd350deda80f.png)
> 
> In odoo 10.0 and odoo 11.0, we cannot choose the menu color with the default theme.
> 
> As for theme bootswatch: before odoo 12.0, we used bootstrap 3.3.7 and the navbar used the "default" style, which happened to be blue with the cerulean theme. Since odoo 12.0, we use bootstrap 4.1.3 and updated the bootswatch themes. The navbar we use is the "light" version (as the "default" version does not exist anymore), which happens to be gray in the new updated cerulean theme. If you want it to be blue as before, you can change the HTML thanks to the HTML editor to use bg-primary instead of bg-light and you will get the primary cerulean version which is blue.

Very strange,
I updated the code, selected the default theme, and the menu color options can be modified.
But it can only be modified once, and the modification has not changed.
If you select the BOOTSWATCH theme, the color of the menu has not changed.

Do I need to install a special dependency package for the theme of odoo12?

Install using ' https://github.com/Yenthe666/InstallScript '

**Comment by offlove** [comment]
<img width="1421" alt="20181017150654" src="https://user-images.githubusercontent.com/43988295/47068279-7050de80-d21e-11e8-8c45-4ffdc5682c49.png">

**Comment by qsm-odoo** [comment]
No fix was made for the default theme, it already worked.

And for bootswatch, I just gave you an explanation about the navbar: we use the third version of the navbar as you can see on the official demo pages: https://bootswatch.com/cyborg/, if you want something else, just use the HTML editor to change the class.
