### ISSUE TITLE
[12] Multi-Websites - user from other company is able to edit all websites

### ISSUE THREAD

**Issue by cierek** [odoo/odoo#27904]
Impacted versions:
12
Steps to reproduce:
Creata another company and user that is employee of that company and has only permissions to edit websites, create a website for the other company.

Log in as other user and edit websites from all cmpanies in the system.
Current behavior:

Any user with Webdesigner permissions from any company is able to edit and save all websites.

Expected behavior:

Only "company" employee is able to edit the website that belongs to "company"

Business use case:
Customer decided to create additional websites, third-party was hired to design one of them. 
Employee from third party company accidentally changed the wrong website as he taught he can work on every single website visible for him.
Video/Screenshot link (optional):
https://youtu.be/KDJ_sgyuI48

Please delete if not an issue. Many companies are using different web-designers/agencies to take care of the websites. Restricting the access to specific websites would be highly appreciated.

**Comment by JKE-be** [comment]
Thanks

As you suppose, it is not an issue for us.

We plan to improve it in a futur version to allow a subset of employee to edit a subset of page.

But in anycase that will not remove the fact that once you can edit 1 page, you can have sudo access. So it required to trust all user that have the website access. (What's seems logic, since they can insert xss to stole your session or ...)
