### ISSUE TITLE
Cannot create partial picking of certain values

### ISSUE THREAD

**Issue by laetitia-gangloff** [odoo/odoo#2793]
issue #1125 seems not ok.

step to reproduce (runbot 7.0):
-create a new unit of measure (pack6) in category unit with rounding 1 and ratio 6 (bigger)
-check rounding of unit is 1
-create and confirm a PO for 1 pack6 of a product

When you try to receive product, you get the following message :
"The unit of measure rounding does not allow you to ship "1.0 Pack-6", only rounding of "1.0 Pack-6" is accepted by the Unit of Measure."

**Comment by Yenthe666** [comment]
I believe this was fixed in https://github.com/odoo/odoo/commit/7705f883d23b71cdb1d30300ce69d9df665ae55e?
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
