### ISSUE TITLE
[12] User (Public users also) is able to view other website

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#27998]
Impacted versions: 12.0

Steps to reproduce:
(Based on discussion from https://github.com/odoo/odoo/pull/27737)
Enable Multi-Websites --> Create Websites (Website,Website 1  and Website 3) --> Disable  Multi-Websites Feature
Current behavior: 
![screenshot from 2018-10-20 20-33-59](https://user-images.githubusercontent.com/16624719/47257123-7dccc980-d4a7-11e8-93e5-61c453627717.png)
![screenshot from 2018-10-20 20-33-44](https://user-images.githubusercontent.com/16624719/47257124-7dccc980-d4a7-11e8-922d-79bd19df6c88.png)

User is able to Visit all website by changing url  (add /?fw=2 or /?fw=2)

Expected behavior:  If feature is disabled User should not be allowed to view other website

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
I think this is because the company of the websites is the same as the user's one, so that's expected.

**Comment by sswapnesh** [comment]
Enabled Multi company --> Created new company --> Created new Website with that company and still same Issue.
Internal Users and Public user is able to view all websites by modifying url.

**Comment by JKE-be** [comment]
Like for previous issue,  Disable Multi-Websites  will not disable  Feature but just hide field in form.
There are not business logic on this field.

We don't really want to support "Multi website mode enable or not", this checkbox is just there for visu.

Now it's true that it is a rare case where we could make this cheap test before to respect the ?fw
But that 's not a jurisprudence for other way to see other website since it is really not the purpose of this group.

**Comment by rdeodoo** [comment]
Hello @sswapnesh 
I just worked on this and for technical reason, we won't be able to prevent `?fw` to forward to another site.

Our position about this one will be the same as other multi-website behavior, we won't disable the feature/behavior but just hide the UI elements (the website selector in this case).

Indeed, what we had in mind by seing your issue was to keep the `?fw` behavior only for designer, editor and admin while preventing the behavior for other users.

But this is not possible, see https://github.com/odoo/odoo/pull/29136 we need to force the website before the authentication phase, then we don't know which user is doing the request at that point.

**Comment by rdeodoo** [comment]
Hi @sswapnesh 
Just to let you know that we changed our mind on this since there was actually a 'bug' for the public user in muti-website/multi-company environnement (with different public user and with website with same domain) when public user would switch website (which he is not supposed to without playing with the URL but still).

See the previous PR I mentionned https://github.com/odoo/odoo/pull/29136
To avoid any (future) issues, we decided that to be able to use the `fw` in URL, you basically need the same rights as you need to have to use the website switcher in the navbar: having multi-website enabled and being at least a restricted editor (on the leaving website).

**Comment by sswapnesh** [comment]
Thanks for the Update Romain.
