### ISSUE TITLE
arabic langauge (Right To Left) problem

### ISSUE THREAD

**Issue by spectra10008** [odoo/odoo#28006]
Hi , I'm using Odoo 12 , And i was changed language from English to Arabic , it was change but direction Left To Right instead Right to Left. 
what solve to these problem??? 
 
![capture](https://user-images.githubusercontent.com/34648267/47266593-0b0c2e80-d539-11e8-8dea-2e1cbbb4d8da.PNG)

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.

**Comment by spectra10008** [comment]
i see just like these question before here , why you close it without answer 
if you know answer what that cost you ???

**Comment by pedrobaeza** [comment]
Sorry, but I don't know it. Any way, I won't answer it if I know it because I don't want to promote the wrong channel for answering.

Why? Because once answered, a closed issue reduces drastically the visibility, and other with the same problem won't find this answer. Forums on contrary are the suitable place for not losing it, including also upvote mechanisms for giving more relevance to great answers.
