### ISSUE TITLE
[11.0] get_module_resource fails when file is not found and blocks UI

### ISSUE THREAD

**Issue by Yenthe666** [odoo/odoo#28036]
Impacted versions: Atleast 11.0, I assume all of them.

Steps to reproduce:
1. Create a module where you have a custom image/file set you want to handle.
2. Create a field with a `default=` function to set an image on the field. For example:
```python
    def _get_default_image(self):
        with open(modules.get_module_resource('your_module', 'static/src/img', 'your_file_typo.png'),
                  'rb') as f:
            return base64.b64encode(f.read())

preview_image = fields.Binary("Image preview", default=_get_default_image)
```

Current behavior: The loadscreen is triggered and it never stops. The UI is blocked and the spinner keeps turning endless.

Expected behavior: The function returns a `False` result and the spinner is stopped, unblocking the UI.

**Comment by pedrobaeza** [comment]
This can be somehow related to #18562 (with when default method is called).

**Comment by Yenthe666** [comment]
I also made an OPW for it - 1903423

**Comment by Julien00859** [comment]
Hello, this is not a bug, the path doesn't exist and `modules.get_module_resource` returns `False` for such paths.

`open` work with both file path and file descriptor, in python `False` equals the integer `0` so `open` opens the standard input which never gets any data so the read blocks and freeze the entire application.

https://github.com/odoo/odoo/blob/11.0/odoo/modules/module.py#L205

The problem here is that your path is wrong and you don't verify the return of the function call. It is not a bug, just a poor choice of return value. Sorry guys but we don't change the behavior of the API in stable versions.

@Xavier-Do @rco-odoo maybe we can change the return to another falsy value like `None` or `""` in master

**Comment by Yenthe666** [comment]
Hi @Julien00859,

Thank you for the feedback and especially for the detailed information as to why it happens. Atleast now I learn something from it too 😉 
I understand you cannot change the behaviour in stable however a change in master would be great. Not getting any exception is a problem to me. Imagine that you as a developer linked to a wrong file (or the file was removed at some point by another developer). The people using the view where you used this function will get an ending loading screen without knowing why. The developer would spend quite some time on figuring it out too.

If it triggers an exception you atleast know something is wrong and there is a traceback giving you a good hint at what is wrong.
I hope you don't mind me keeping this open untill there is a decision for the master version. If you let me know what would be accepted I'm more than happy to make a PR.

**Comment by Yenthe666** [comment]
@Julien00859 just a quick check, did you ever hear something back from the R&D team?

**Comment by Julien00859** [comment]
Yes, they are unwilling to change to API, sorry

**Comment by Yenthe666** [comment]
Too bad. Atleast I know now, thanks.
