### ISSUE TITLE
Project / Tasks / Step grouping

### ISSUE THREAD

**Issue by aitalinassim** [odoo/odoo#28110]
**Impacted versions:** 
12, fetched from github on 23th october (last version)

**Steps to reproduce:** 
1. create two projects (project A and project B)
2. Create on each project two steps: New and Closed
3. On each step add Tasks (Projet A New: Task 1; Projet A closed: Task 2; Projet B New: Task 3; Projet B closed: Task 4)
4. Go to All tasks
5. Group tasks by step

**Current behavior:**
Tasks are not grouped by step, we see 4 steps: New / New / Closed / Closed

**Expected behavior:**
Tasks should be grouped in two steps only: New / Cloused.

**Comment by pedrobaeza** [comment]
This is because you are not reusing the stages (not steps). You should go to the stage and add both projects instead.

You can use also OCA module called project_task_default_stage (https://github.com/OCA/project/tree/11.0/project_task_default_stage - not migrated yet to v12).

Closing as no valid issue.
