### ISSUE TITLE
[12.0][BUG] address_home_id prevents from opening employee form

### ISSUE THREAD

**Issue by alexey-pelykh** [odoo/odoo#28445]
Impacted versions:
12.0-latest

Steps to reproduce:
Try to open employee page/card as regular employee

Current behavior:
```
odoo.models: Access Denied by ACLs for operation: read, uid: 25, model: hr.employee, fields: address_home_id
```
appears in logs and page does not open

Expected behavior:
Page opens normally

**Comment by litnimax** [comment]
It's not the matter of XML.
The problem is that client tries to read columns and if column has special group access it gives an error.
Here is the example from today:

```
e_c = erppeek.Client('http://localhost:8072', db='test', user='broker', password='broker')
e_c.read('res.partner', [('id','=',1)])
```
gives mlrpclib.Fault: <Fault warning -- AccessError

And in Odoo log:
```
2019-02-07 16:37:35,734 143 INFO barrier odoo.models: Access Denied by ACLs for operation: read, uid: 6, model: res.partner, fields: signup_token
```

Here is the field:

addons/auth_signup/models/res_partner.py:    signup_token = fields.Char(copy=False, groups="base.group_erp_manager")

So if I give user Access Rights group, it starts to work.

**Comment by Yenthe666** [comment]
@RomainLibert perhaps relevant for you?

**Comment by litnimax** [comment]
Or may be my report is another bug?

**Comment by aidoskz** [comment]
i think it is problem with method
https://github.com/odoo/odoo/blob/8cc62b1a6def6f74dd0e3ccdc9831b98f6078230/odoo/models.py#L2701
     def check_field_access_rights(self, operation, fields):

**Comment by RomainLibert** [comment]
Hello @alexey-pelykh ,

1) I cannot reproduce your issue on latest 12.0 runbot. I tried removing all the rights of a user and I can still access the employee page.
2) Adding a groups in the xml file will indeed avoid js trying to read the field hence avoiding the error. This should already be done in the view here (https://github.com/odoo/odoo/blob/12.0/addons/hr/views/hr_views.xml#L80).

Maybe I missed something in your issue and there is indeed a bug in the standard Odoo, but I believe the error might be caused by the removal of the groups attribute at the aforementioned line.
