### ISSUE TITLE
XLSX export should be provided

### ISSUE THREAD

**Issue by yann-papouin** [odoo/odoo#2848]
This new MS Excel file format (Office 2007) is able to extend the built-in limits of the XLS file format and would allow to provide a workaround for the 65535 row limit.

Possible migration to openpyxl (or XlsxWriter) and xlsx/xlsb.

**Comment by nhomar** [comment]
This is working since few time ago (> 9.0)

**Comment by mlaitinen** [comment]
@nhomar What do you mean it's "working since few time ago"? I'm checking the `12.0` and `master` source code and Odoo is still using the `xlwt` library that only produces `.xls` files, not `.xlsx`.

Yes, it's possible to **import** `.xlsx` files, but not to **export** them.

It's 2019. I don't see a reason to support Excel 2003 format anymore.

Seems like #32339 is our best bet.
