### ISSUE TITLE
[11.0] Attributes not working in one2many editable view 

### ISSUE THREAD

**Issue by Gokulakannanaj** [odoo/odoo#28509]
Impacted versions:
[11.0]
I am using odoo 11.0 working on ubuntu platform
i have a one2many editable tree view having three fields.
the fields are
check : boolean field
test_readonly_id_1 : selection field
test_readonly_id : char field

in xml view of it:
 i have given
```xml
<field name="check" />
<field name="test_readonly_id_1" />
<field name="test_readonly_id" attrs="{'readonly': [('check', '=', False)]}"/>
```

I update the "check" field value based on "test_readonly_id_1"

so when I execute:
with check field False everything is ok
but when 'check field' is True , the field: 'test_readonly_id ' not allowed to edit.

**Comment by yusraalroom** [comment]
because you set  field  test_readonly_id  readonly  when check = False and you can not edit test_readonly_id  untill enter any value to field check

**Comment by Gokulakannanaj** [comment]
@yusraalroom you said correct. But i update the field 'check' based on selection field. So its value changed from False to True

**Comment by mart-e** [comment]
Hi,

Sorry for the lack of reply but this kind of `attrs` readonly is used on many places (e.g. here [in mrp](https://github.com/odoo/odoo/blob/2d12bc09f3256b10dc5a4e18b1cc0ca426ef8ae9/addons/mrp/views/mrp_production_views.xml#L134)) and it works. The problem is most likely on your side.

If you can still reproduce it with a standard installation (e.g. on a [runbot](http://runbot.odoo.com/runbot) with standard modules), let me know and we will investigate.
