### ISSUE TITLE
wkhtmltopdf doesn't support bootstrap 4

### ISSUE THREAD

**Issue by Yajo** [odoo/odoo#28681]
Impacted versions: 12.0

Steps to reproduce:

1. Design a report with some flexbox utilities, such as this example:
![captura de pantalla de 2018-11-14 13-44-39](https://user-images.githubusercontent.com/973709/48486449-76cd7880-e813-11e8-9547-b0dc604dafa8.png)
1. Print it.

Current behavior: 

It produces [Order - SO101-7.pdf](https://github.com/odoo/odoo/files/2580939/Order.-.SO101-7.pdf), which looks like this:
![captura de pantalla de 2018-11-14 13-45-47](https://user-images.githubusercontent.com/973709/48486494-9f557280-e813-11e8-90cd-cce33904d42d.png)

Expected behavior:

It should look as expected, like when printing from HTML:
![captura de pantalla de 2018-11-14 13-46-27](https://user-images.githubusercontent.com/973709/48486529-b6946000-e813-11e8-9417-d1e191099231.png)

See https://github.com/wkhtmltopdf/wkhtmltopdf/issues/1522 and https://github.com/wkhtmltopdf/wkhtmltopdf/issues/4173.

**Comment by pedrobaeza** [comment]
I don't know if @qsm-odoo is the most suitable person for answering this. Quentin, can you tell us?

**Comment by switch87** [comment]
Like you can read in the issues you provided this is a wkhtmltopdf issue that cannot be fixed in the Odoo framework. You can open a issue on their project or comment on the existing one with your findings.

**Comment by pedrobaeza** [comment]
@switch87 Then Odoo is not using any `col` or similar BS4 feature in the core reports?

**Comment by switch87** [comment]
I did a fast search in the source, and indeed we do. 
What I did see is that the ml-auto seems to be used only for cols that have to be at the far right. So you should test what happens if you remove this class. A solution could be to add a empty col before these two or insert them into a bigger col that has the class ml-auto? I did not try myself so my suggestions may or may not have the wanted results. 
It would be great if you could report all your findings to wkhtmltopdf so they can fix it. Thank you for reporting it to us.

**Comment by rafaelbn** [comment]
@Yajo maybe we should take care of https://github.com/OCA/reporting-engine/issues/254

**Comment by qsm-odoo** [comment]
@Yajo We added explicit support for flex rules so that reports work with BS4. I was curious about that one though, so I tried a little to fix it. I however cannot seem to do much about this `ml-auto` bug, it seems that wkhtmltopdf computes the margin without caring about the other columns (so your blue one is in fact after the red one). There are quite some alternatives though for your example:
- use the `justify-content-end` class on the `row` (I added explicit support for that one)
- use `offset-4` instead of `ml-auto`

So yes, reports do not support all the BS4 functionalities (to not say all HTML functionalities) but I think there is always an alternative even using other BS classes. Still more possibilities than if we kept BS3 :+1:

**Comment by qsm-odoo** [comment]
If we find other problems and if someone gets the time... maybe...
But in this case, the two alternatives I mentioned are explained on the bootstrap documentation *before* using margin classes :wink:

**Comment by pedrobaeza** [comment]
Thanks for the help, Quentin and Gert!

**Comment by Yajo** [comment]
> We added explicit support for flex rules so that reports work with BS4

I'm curious on this. What do you mean? :thinking:

**Comment by qsm-odoo** [comment]
https://github.com/odoo/odoo/blob/12.0/odoo/addons/base/models/assetsbundle.py#L515

**Comment by amkarthik** [comment]
@Yajo 
I can't even rotate the barcode image in the printed pdf.
Please see the below code.
The barcode is rotated on the qweb-html report and not on the qweb-web.
Do we have any workaround for this? 
Any little help could be useful.
Thanks

`                            <div class="row">

                                <div class="col-4">

                                  <img t-if="o.name" t-att-src="'/report/barcode/?type=%s&amp;value=%s&amp;width=%s&amp;height=%s' % ('Code128', o.name, 600, 150)" style="width:200px;height:100px;transform: rotate(270deg);"/>

                                </div>

                            </div>
`

**Comment by Yajo** [comment]
I guess it's not possible unless we dump wkhtmltopdf and use something with a more modern rendering engine. :shrug:

**Comment by amkarthik** [comment]
@Yajo Thanks for the info
