### ISSUE TITLE
[12.0] duplicated template views, Default homepage don't loaded- multi website

### ISSUE THREAD

**Issue by hugho-ad** [odoo/odoo#28695]
Impacted versions:
12.0

Steps to reproduce:

- Go to Settings/technical/User interface/ views
- search home view

There duplicated views
![image](https://user-images.githubusercontent.com/10233975/48501831-c73cda00-e803-11e8-8d38-5f4a07143e43.png)

Current behavior:
Modify website.homepage 
in order to see the change in website homepage
![image](https://user-images.githubusercontent.com/10233975/48501784-b12f1980-e803-11e8-8296-0b62326c91a7.png)

![image](https://user-images.githubusercontent.com/10233975/48502045-47fbd600-e804-11e8-8e8e-121abe56f602.png)

Expected behavior:
See the modification at homepage and no duplicated views!

Video/Screenshot link (optional):

OPW 1909476

**Comment by JKE-be** [comment]
hi @hugho-ad 

I don't see the error ? 

If you update the generic homepage (without website_id) while you have a specific homepage (website_id set) it is normal to see the content of the homepage with website_id ! 
It is by design !

**Comment by hugho-ad** [comment]
@JKE-be 


Why the generic homepage got duplicated instead of using it?

The only change that I see at the copy of homepage view it's the website_id. but I can't figure it out why was made view duplication.

Could you point me out to where the duplicated views are created, please?

Best Regards!

**Comment by JKE-be** [comment]
By default, when we create a new website, we always bootstrap an new homepage for the current website
https://github.com/odoo-dev/odoo/blob/d13fb278268a379d5447b7fa076fbb7db26d9004/addons/website/models/website.py#L168

**Comment by hugho-ad** [comment]
@JKE-be 

So how customization must be done?
If my_app  inherits and modifies the homepage, how can I inherit the duplicated template, the one that has the website_id (It hasn't xml_id),  in order to make visible my changes at the end of my_app installation?.

Best Regards!

**Comment by rdeodoo** [comment]
Hello @hugho-ad 

> how can I inherit the duplicated template

In that case you should probably target the duplicated-specific view with something like:
```xml
<field name="inherit_id" search="[('name', '=', 'Home'), ('website_id', '=', 2)]"/>
```
You could also search on `key` instead of `name` since default homepage's view got a key set to 'website.homepage' and the duplicated specific views share the same key:
```xml
<field name="inherit_id" search="[('key', '=', 'website.homepage'), ('website_id', '=', 2)]"/>
```

And preferably make that new inheriting view website specific too with:
```xml
<field name="website_id" eval="2" />
```
(it won't be problematic to not set the `website_id` as it would be a generic view under a specific view hierarchy so it will be taken into account but I would recommend setting it)

Note: If you don't know the website_id/ref-xmlid to search, that should work:
```xml
<field name="inherit_id" search="[('key', '=', 'website.homepage'), ('website_id.name', '=', 'Second Website')]"/>
<field name="website_id" search="[('name', '=', 'Second Website')]"/>
```

**Comment by hugho-ad** [comment]
got it, thanks

**Comment by vco-subteno-it** [comment]
Hi there,

I saw your issue which is very similar to what I'm facing actually. Perhaps, this solution seems to work on odoo views only. 

How could I do the same trick on website templates? I tried :

<template id="something" inherit_id="module.somethingelse" search="[('key', '=', 'website.homepage'), ('website_id', '=', 2)]"/>

But I got an assert error then. Anyone tried?

**Comment by frankmiao2015** [comment]
> An XML example if somebody else should land here and is uncertain about what to do:
> 
> ```
> <?xml version="1.0" encoding="utf-8"?>
> <odoo>
>     <record id="homepage_custom" model="ir.ui.view">
>         <field name="name">Custom homepage</field>
>         <field name="type">qweb</field>
>         <field name="inherit_id" search="[('website_id', '=', 1), ('key', '=', 'website.homepage')]"/>
>         <field name="key">website.homepage.custom</field>
>         <field name="website_id" eval="1" />
>         <field name="arch" type="xml">
>             <t t-call="website.layout">
>                
>                <p>Some example text</p>
>          </field>
>     </record>
> </odoo>
> ```

What if I use several websites with the same theme and I want add the feature to the theme applied to all websites by another module? Should I copy the record to suit all websites by changing the search domain website id? And If I create a new website with the same theme, should I go back the code and add the record for the new website? Thank you!

**Comment by Yenthe666** [comment]
Yeah, I don't think there is better or safer way than the example I provided. I'd just add the new website in then.

**Comment by frankmiao2015** [comment]
> Yeah, I don't think there is better or safer way than the example I provided. I'd just add the new website in then.

Thanks for your quick reply. Is it possible to add the website_ids to the same record domain to make the process simpler. I just tried or  (,'|', )  and & conditions between the website ids in the domain without no success. Thank you!

**Comment by JKE-be** [comment]
@frankmiao2015 

You can inherit the main theme template, and after ugrade your themes.
All websites that uses it will be updated, and all futur new website will have your new feature.

**Comment by frankmiao2015** [comment]
The problem is there is no external identifier for the theme views in odoo12  and I can not inherit the template view. And there will be duplicated views for several websites if the multi website use the same theme(same key but no identifier). I think that is what this topic is about? Or is odoo 12 encourage do all changes within the theme itself? But in some case we just want keep the theme original just like odoo core for easy updating from our theme provider. Thank you for your answers.

**Comment by frankmiao2015** [comment]
@Yenthe666 @JKE-be 
If I do not add the  ('website_id', '=', x) in search domain, should't it be add the record to all relevant websites using the same theme since they have the same key? It seems it randomly add to one website only. The above record inheritance for the same theme is not flexible at all. Am I the only one cares or do I miss something. Thank you!

**Comment by IlirBajrami** [comment]
> An XML example if somebody else should land here and is uncertain about what to do:
> 
> ```
> <?xml version="1.0" encoding="utf-8"?>
> <odoo>
>     <record id="homepage_custom" model="ir.ui.view">
>         <field name="name">Custom homepage</field>
>         <field name="type">qweb</field>
>         <field name="inherit_id" search="[('website_id', '=', 1), ('key', '=', 'website.homepage')]"/>
>         <field name="key">website.homepage.custom</field>
>         <field name="website_id" eval="1" />
>         <field name="arch" type="xml">
>             <t t-call="website.layout">
>                
>                <p>Some example text</p>
>          </field>
>     </record>
> </odoo>
> ```

how do i replace the website.layout and not add my content after the default layout? i want to replace only the <main> tag and not the default navigation bar.
