### ISSUE TITLE
Feature Request: AsyncIO Support

### ISSUE THREAD

**Issue by v3ss0n** [odoo/odoo#28764]
Since PostgreSQL have asyncio drivers and Odoo is Already on Python3.5 , replacing Gevent with asynio: async/await will be a lot cleaner. But that will be huge rewrite.

Any Plan to support asyncio in coming years?

**Comment by pedrobaeza** [comment]
What are the benefits of this?

**Comment by v3ss0n** [comment]
Performance
Cleaner Async.
AsyncIO LongPoll + Postgre Listen/Notify can make everything Realtime.
Realtime KanBan and many realtime stuff will be very powerful.

**Comment by v3ss0n** [comment]
Thanks ! Since odoo already have some realtime stuff , it will be truly collaborative framework if most part of odoo is realtime (longpoll) .

**Comment by em230418** [comment]
Any news?

**Comment by hoangpq** [comment]
I created a simple **[Gist](https://gist.github.com/hoangpq/16139539a3783e9b532604db06ad3c65)** to use Python asyncio in Odoo controller 

Odoo route will take less than `2s` to complete 2 requests to [Nodejs Server](https://gist.github.com/hoangpq/16139539a3783e9b532604db06ad3c65#file-server-js) which take 1s responding to client for each request.

In my case: 
![image](https://user-images.githubusercontent.com/5939997/69415986-310d8f00-0d48-11ea-90bb-b2e83d195d30.png)

**Comment by antonylesuisse** [comment]
Not that easy, when processing a "longpolling" request any odoo business code could run, so the semantics of those non async code should be maintained (opening a file, socket operation, sleep, ...).

Gevent is a hack but it has the merit to look just like plain simple threaded code, context switches happens magically at io calls whenever needed.

**Comment by rco-odoo** [comment]
Adapting Odoo to async/await requires to make almost every method asynchronous.  That's a damn huge work.  But it will not make Odoo faster when most of its time is spent waiting for PostgreSQL.  It might reduce a bit the server's memory footprint.  It will inevitably come with new bugs, and really really subtle bugs!

You should have a look at [Some thoughts on asynchronous API design in a post-async/await world](https://vorpus.org/blog/some-thoughts-on-asynchronous-api-design-in-a-post-asyncawait-world/).

To me, async/await is like the "goto" of concurrent programs.  It looks nice and smart, but is actually terrible programming language design in a so-called "high-level" programming language.  The main issue being that asynchronous functions are not *composable* with synchronous functions: you cannot pass a function that does asynchronous IO to `map`, for instance.  It only works well when *everything* is asynchronous, and in that case, it does not need to be explicit in the language, it can be hidden in the language runtime (like Gevent does).

**Comment by pedrobaeza** [comment]
Thanks for your statements. Then it seems clear: there's not too much benefit on adding that, so closing this issue.

**Comment by llacroix** [comment]
> It only works well when everything is asynchronous, and in that case, it does not need to be explicit in the language, it can be hidden in the language runtime (like Gevent does).

Well no, you can't make it all async. Even Node.js has sync methods and obviously sync methods don't work the same way as async ones. You can't go from one to the other transparently without causing issues somewhere else. Even javascript now has async/await keywords to make the code easier to write in order to await a Promise instead of explicitely write `.then(promise)` which in returns makes it possible for the JS Engine to create proper stacktraces in the future.

The way Python is designed, it simply isn't possible to know ahead of time if a method has to be run in an event loop or not. Being explicit make sure you cannot mix async and sync methods together, it's a bit like singing a contract. One of the reason you'd want sync method is when timing is an issue. With a "Gevent" way of doing things by  making it all async you're virtually breaking a whole ecosystem along. Anything timing specific task will stop working unexpectedly as async cannot guarantee certain timings. For that exact reason, implicitly making python run completely async is wishful thinking. So what you're asking is to making it impossible to run sync io from within an async task. Not going to happen.

Implicit also means you cannot select the event loop you want your async task to run on, in the link you provided it makes it possible to use asyncio or curio. So implementation isn't ingrained inside python but as a library. 

> But it will not make Odoo faster when most of its time is spent waiting for PostgreSQL

Well, you're having it backward here. If you're spending most of the time waiting for IO, you should really start using async io as it's exactly designed to solve the problem of "waiting". Instead of locking the process until something is read, the process can be used for something else during the waiting time and once data is fetched or available. The task can be resumed to do something useful.
In other words, with current API, if you spend 50% of the time waiting for IO, It means you have to start a new worker to cover there 50% of wait. But if you do that, you have to make sure your 2 workers will never trigger the OOM killer. So you can never use 100% of your resources. With async, you're reducing the amount of time of a process being idle by having it it do anything it can constantly and being idle the very least amount of time. So you're in fact using the time waiting doing other stuff and you can maximize your resource usage. In other words, you can be closer to the maximum without fearing to trigger the OOM killer. With the current API. I'd have to have a server with a lot of ram to even dream to use the most of my CPUs. But since we're pretty much limited by RAM, it means I'll never have 100% processing power which means that async python would be able to process more request per second that MultiProcess or Threaded server could. More requests per seconds, means faster odoo experience. In some of our servers, I can see odoo struggle with 4 workers and around 600 request per minutes vs a few thousands requests per second on async frameworks. It's not a fair comparison but Odoo is far from being optimal in this regard and that would definitely help. 

Gevent has been designed for a special purpose and cannot be seen as a solution that solves all problem. It's really nothing more than a hack. I'd rather see an async implementation done right. It's a lot of work but it will be worth it.
