### ISSUE TITLE
[8.0] Fiscal positions in POS don't work

### ISSUE THREAD

**Issue by serkia** [odoo/odoo#2908]
Under Sales > Order > create order

my fiscal positions work fine, but if I use the Point of Sale module and select the customer that the fiscal position applies to the tax is not calculated the way I would like.

**Comment by wtaferner** [comment]
Can be closed with cec7a02.

**Comment by Yenthe666** [comment]
Hi @serkia,

Thank you for your report.
This should have been fixed in https://github.com/odoo/odoo/commit/cec7a02fdda1f0ccf856b99841a209c1f15e9c83 and as a sidenote Odoo 8.0 is no longer officially supported.
There have been improvements and expansions on this subject in V10 + V11 too.

Regards,
Yenthe
