### ISSUE TITLE
Field Appears on payslip in Salary rules not working in Employee Payslips

### ISSUE THREAD

**Issue by doanvanthien** [odoo/odoo#29133]
Impacted versions: ODOO 11.

I defined a rule Company Allowance and not tick field appears on payslip. 

![screenshot from 2018-11-29 17-15-03](https://user-images.githubusercontent.com/13639302/49215084-914e4700-f3fa-11e8-89ba-acfce77f5563.png)

Then I inserted rule Company Allowance into Salary Structure. When I clicked button COMPUTE SHEET in payroll, the rule Company Allowance still show up in payroll. 

![screenshot from 2018-11-29 17-14-55](https://user-images.githubusercontent.com/13639302/49215071-87c4df00-f3fa-11e8-979e-21a59236c569.png)

I think it's bug. 

Video/Screenshot link (optional):

**Comment by RomainLibert** [comment]
In fact the appears_on_payslip boolean does not control what you can see on the payslip **in Odoo**, but rather what will be seen on **the pdf** printed via Odoo.
This is done in order for you to check that there is no mistake in the computation of the rule.

As it is the expected behaviour this cannot be considered a bug.

**Comment by doanvanthien** [comment]
Are you sure the meaning right?  Because of the help field's appears_on_payslip don't show your thought.

**Comment by doanvanthien** [comment]
> > In fact the appears_on_payslip boolean does not control what you can see on the payslip **in Odoo**, but rather what will be seen on **the pdf** printed via Odoo.
> > This is done in order for you to check that there is no mistake in the computation of the rule.
> > 
> > As it is the expected behaviour this cannot be considered a bug.
> 

Are you sure the meaning right? Because of the help field's appears_on_payslip don't show your thought.

**Comment by RomainLibert** [comment]
Yes using payslip for both the object in Odoo and the pdf document is a bit confusing.
Basically when we use the word ```payslip``` in the help message and in the name of the field we refer to the document, which as you can see is called ```payslip``` in the interface (https://drive.google.com/file/d/1We66YJAsCyCW-U7Dtjg3bhz1rAu9Q7Tn/view?usp=sharing).

We did this because usually the payslip is only valid to law when printed, so you can choose what you will put on the legal document, but in the interface of Odoo you see everything. Seeing every rule in Odoo facilitates the debugging of the computation.

If the rule appears in the pdf document then it can be considered as a bug, otherwise it is not a bug.
Can I know the reasons as to why you would like to hide a rule on the interface?

**Comment by doanvanthien** [comment]
Thanks. Maybe I didn't understand ideal and design Odoo's in version 11.
