### ISSUE TITLE
[8.0] Problems with concurrency and chat updating status.

### ISSUE THREAD

**Issue by nhomar** [odoo/odoo#2919]
This error appear on my logs frequently since the update where the odoo_chat was marked as "autoinstall": True.

```
2014-10-06 07:18:42,270 44021 ERROR dbname openerp.sql_db: bad query: update im_chat_presence set "status"='online',"last_poll"='2014-10-06 07:18:42',write_uid=1,write_date=(now() at time zone 'UTC') where id IN (1)
Traceback (most recent call last):
  File "/Users/nhomar/Trabajo/odoo/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
TransactionRollbackError: could not serialize access due to concurrent update
```
1.- Any external presence checking can bring problems to my logs I feel like somebody is waching me :-)
2.- The chat system has a problem because is causing concurencies problems.

Thanks for your time.

**Comment by lapagept** [comment]
Somebody else knows how to avoid this error? Same here.

**Comment by eneldoserrata** [comment]
someone could find the cause of this problem?

**Comment by Karsten-77** [comment]
Same here!

**Comment by andrius-preimantas** [comment]
I can confirm bug still exists.

**Comment by spadae22** [comment]
Yes, confirmed when workers>0, chat will not work, I have read setting a reverse proxy server, but this should work out of the box as workers>0 is needed for an real use in odoo. This question is also posted in detail here: https://github.com/odoo/odoo/issues/6852

**Comment by svetbg** [comment]
+1

**Comment by Sarfarazsajjad** [comment]
+1

**Comment by tarzan0820** [comment]
+1

**Comment by OpenERPJeff** [comment]
Same here, no solution and no odoo staff care about this?

**Comment by Yenthe666** [comment]
@mart-e quite some people seem to be reporting this. Any idea?

**Comment by mart-e** [comment]
The query indicates that the presence status (online, away or offline) failed to be updated. It's not a big deal, it happens when you have two tabs open for instance and the two tries to set the user as online.
In 9.0 we have [muted these errors](https://github.com/odoo/odoo/blob/5ca8f087309b16f4527a91fbb490b4a8f804e7f9/addons/bus/models/bus_presence.py#L53) but really it's just the process trying to set the same information (a few millisec of difference maybe)
