### ISSUE TITLE
[12.0] payment_stripe: Duplicate record created in payment transaction

### ISSUE THREAD

**Issue by vjd8866** [odoo/odoo#29297]
Impacted versions: 12.0 (payment_stripe)

Steps to reproduce: try to create payment from ecommerce

Current behavior: Duplicate record created in payment transaction

Expected behavior: It should be one

Video/Screenshot link (optional):

![screenshot from 2018-12-06 12-07-49](https://user-images.githubusercontent.com/22145648/49566224-ee448280-f94f-11e8-829c-214fb1d6bc79.png)

**Comment by JKE-be** [comment]
Hello,

btw, since only one is in done, and the other is in draft it can be easily reproductible, but not considered as a bug.

If you initiate a transaction for soxxx, we will create soxxx-1, if you click on back and click again, or simply click on the same link in another tab, we will generate a second tx soxxx-2 since stripe don't allow to re-use an existing reference for a payment.

Bets regards
Don't hesitate to reply if you have some doubts.
