### ISSUE TITLE
[10.0] Expense report daughter company - Document type: hr.department, Operation: read

### ISSUE THREAD

**Issue by bnjroos** [odoo/odoo#29335]
Impacted versions: 10.0 CE

Steps to reproduce: User employee from daughter company tries to create an expense report.

Current behavior: When the user employee creates an expense report (hr.expense.sheet), he won't be able to save it and will get a warning message.

Expected behavior: The user employee can save and create an expense report.

Video/Screenshot link (optional): [screenshot](https://i.imgur.com/nycjmlp.png)

**Comment by pedrobaeza** [comment]
Hi @bnjroos, but full multi-company support with parent/children companies is not yet implemented, also due to some design decisions. You should switch to the company you are creating the expense to, and have enough care for not mixing records from several companies if you have access to them within the hierarchy.

In general for multi-company, company hierarchy is not a good idea, except for having a readonly parent company for analyzing several companies data together, but NEVER for recording documents.

Closing as a restriction impossible to fix without changing current paradigm.
