### ISSUE TITLE
v8 BI  Entries Analysis -> Mesure 'balance' does not work

### ISSUE THREAD

**Issue by fclementic2c** [odoo/odoo#2935]
You adding the mesure 'balance' on a BI table based on entries analysis, the balance is always zero even if you see numbers in columns Debit / Credit. Please see following print screen :  

![1](https://cloud.githubusercontent.com/assets/5735158/4526428/0cf741a0-4d5f-11e4-9156-5bbd2d0b0b73.png)

**Comment by christopherdurr** [comment]
I believe the "balance" measure on the table is supposed to subtract debit from credit. In this case, since credit and debit are equal then the balance comes out to zero. I would recommend checking with different credit/debit values where the difference between them is greater than 0, and then seeing if balance is still 0. If that's the case, then it does not work properly

**Comment by Yenthe666** [comment]
Hi @fclementic2c,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
