### ISSUE TITLE
VAT Validation for Chile is not expected

### ISSUE THREAD

**Issue by rsilvam21** [odoo/odoo#29394]
Impacted versions:
v.11

Steps to reproduce:
Create a new partner
Assign Chile as the country
Put the VAT number
Save

Current behavior:
A VAT validation error

![screen shot 2018-12-10 at 09 49 28](https://user-images.githubusercontent.com/7602896/49743693-f0188980-fc60-11e8-88df-7b04235023b3.png)

Expected behavior:
We do not expect a VAT validation because there isn't one in the [code](https://github.com/odoo/odoo/blob/12.0/addons/base_vat/models/res_partner.py#L28-L61) for Chile.

Video/Screenshot link (optional):

Thanks!

**Comment by pedrobaeza** [comment]
You should provide what is the incorrect VAT number you are trying and why it's incorrect.

**Comment by pedrobaeza** [comment]
Well, that list is only for fallback check, but if you have the library vatnumber it will check other like Chilean ones. If I don't remember bad, in Chile it's called RUT and it has a proper format. The problem here is the dash. If you introduce `761141430`, it works without problem.

Closing there as no real issue.
