### ISSUE TITLE
immediate transfer in Stock is broken in V12

### ISSUE THREAD

**Issue by icoro** [odoo/odoo#29543]
Immediate transfer in Stock V12 does not work same as in V11. In V12, when I make a new immediate transfer, the "Done" column is not editable anymore. I have to go through a popup to change the quantity. In settings "Lots and serial numbers" is NOT enabled. I tested with V11 with the exact same settings and it works as expected ("Done" column is editable)

**Comment by sswapnesh** [comment]
Related (Duplicate) to https://github.com/odoo/odoo/issues/29474 (Both belongs to same source)

**Comment by icoro** [comment]
@sluggogle I agree 100%. From usability point of view, immediate transfer now doesn't make sense. I hope someone in the odoo dev team can take care of this.

**Comment by sle-odoo** [comment]
It was probably fixed in the meantime, you have do disable packages, multi locations and lot and you can write directly on the stock move. For v13, once one of these groups is enable the "detailed operations" setting is ticket so you'll be working with directly the move line one2many, not through a popup.

Regards
