### ISSUE TITLE
product supplier code is linked to a product template, not to a variant

### ISSUE THREAD

**Issue by gurneyalex** [odoo/odoo#296]
in the current master branch, the product.supplierinfo stores a supplier code. However it is linked to the product template not to the variants (product.product) which means it is not possible to have different supplier codes for different variants.

**Comment by gurneyalex** [comment]
@Gorash probably the worst reason for doing such a bad design choice. 

shit has hit the fan on a customer project because of this choice. As soon as you purchase products with several variants, you get horribly wrong PO. 

@odony: any opinion about this?

**Comment by lepistone** [comment]
For the record, the change was done in https://github.com/odoo/odoo/commit/66528564456553812311180d

Basically this means that you can sell 16GB and 32GB iPads for a different price, but you must pay the same price to your supplier. Not sure what's the logic behing this.

**Comment by jkevin530** [comment]
Issues 296 and 2679 are related.

**Comment by sebastienbeau** [comment]
Just for information, we hit the same problem (note that in 6.1 the problem was here too) I see that @pedrobaeza have started this module https://github.com/serviciosbaeza/serviciosbaeza-odoo-addons/tree/8.0/product_supplierinfo_variant

I didn't have tested it for now but I think it's miss some feature for getting the right code and the right price on the purchase order.

@gurneyalex what do you think about doing a OCA module for solving the issue?

**Comment by pedrobaeza** [comment]
Yeah, I don't put it on OCA yet because it was only a POC for solving one of the existing problems with this bad design. We can patch via a module another functionalities like the one you are mentioning, but we will need some glue modules for patching all the interactions with this model along the main modules (product, purchase, procurement...)

**Comment by legalsylvain** [comment]
:+1: to make this change in the core and not in a custom module.

There is no good reason to have this link.
Supplier info only depends on variant info : supplier code & supplier product name, prices ...

regards.

**Comment by lepistone** [comment]
Apparently v9 has https://github.com/odoo/odoo/commit/b65c67a2598fd3ad433af05ed49d. Now idea how that works though.

**Comment by ruuter** [comment]
@lepistone apparently setting `product_id` on `product_supplierinfo` table, makes it magically, at least connect correct variant when creating a PO. :+1: 

You can import Supplier Pricelist and set `product_id/id` in the .csv file.

**Comment by lepistone** [comment]
Hi @ruuter. But As far as I remember, there is no UI to actually use this thing, it looked unfinished.

I unsubscribed from this thread because I don't work on this anymore, but I am sure the other participants are still interested.

Thanks!

**Comment by pedrobaeza** [comment]
The module https://github.com/OCA/product-variant/tree/8.0/product_variant_supplierinfo has been moved and improved in OCA for filling the existing gap. You can use it or migrate it to 9.0 as your wish.

**Comment by jholze** [comment]
seems to be fixed here https://github.com/odoo/odoo/pull/12580

**Comment by Yenthe666** [comment]
Dear @gurneyalex ,

Thank you for reporting this issue!
It looks like it has already been fixed, as noted by @jholze so I'm closing this one.
V7 and below are no longer supported anymore, so I'm closing it for that reason too.

Regards,
Yenthe
