### ISSUE TITLE
There is no partner_id in account_analytic_line

### ISSUE THREAD

**Issue by VooVoo01** [odoo/odoo#29657]
Impacted versions: Odoo 11.0-20181031 (Community Edition)

The partner_id field in account_analytic_line always is null.
There is no partner_id field when preparing the data in _`account/models/account_move.py`_
Will it be correct to add it like below? Or is there any reason why it is not?

```
    @api.one
    def _prepare_analytic_line(self):
        """ Prepare the values used to create() an account.analytic.line upon validation of an account.move.line having
            an analytic account. This method is intended to be extended in other modules.
        """
        amount = (self.credit or 0.0) - (self.debit or 0.0)
        default_name = self.name or (self.ref or '/' + ' -- ' + (self.partner_id and self.partner_id.name or '/'))
        return {
            'name': default_name,
            'date': self.date,
            'account_id': self.analytic_account_id.id,
            
>           'partner_id': self.partner_id and self.partner_id.id or False,

            'tag_ids': [(6, 0, self.analytic_tag_ids.ids)],
            'unit_amount': self.quantity,
            'product_id': self.product_id and self.product_id.id or False,
            'product_uom_id': self.product_uom_id and self.product_uom_id.id or False,
            'amount': self.company_currency_id.with_context(date=self.date or fields.Date.context_today(self)).compute(amount, self.analytic_account_id.currency_id) if self.analytic_account_id.currenc
            'general_account_id': self.account_id.id,
            'ref': self.ref,
            'move_id': self.id,
            'user_id': self.invoice_id.user_id.id or self._uid,
        }
```

**Comment by jem-odoo** [comment]
Hello,

in 11.0 and before, the account module forced the partner of analytic lines to be the one from the analytic account. This was change in 12.0 because 
1/ changing field semantic is not a good idea
2/ as analytic line can come from several origin (customer invoice, refunds, expense or timesheet), to have a better reporting, we wanted to allow having lines with different partner in the same analytic account.

As you proposal is in account module, and that the field partner_id is a related, it is not correct.
The avoid an empty partner on analytic line, in 11.0 with account installed, you have to set the partner on the analytic account.
