### ISSUE TITLE
odoo v12 installation error

### ISSUE THREAD

**Issue by rmorgan999** [odoo/odoo#29670]
Impacted versions: 12

Steps to reproduce: install on Windows 10

Current behavior:  It wont install

Expected behavior:  it installs!!

Video/Screenshot link (optional):

Fatal Python error: Py_Initialize: unable to load the file system codec
  File "C:\ProgramData\Anaconda2\Lib\encodings\__init__.py", line 123
    raise CodecRegistryError,\
                            ^
SyntaxError: invalid syntax

Current thread 0x00004450 (most recent call first):

**Comment by pedrobaeza** [comment]
Sorry, but this is something specific of your deployment. If using Windows, which is not the preferred deployment method any way, but supported, you have to use the bundled package, instead of using weird things like Anaconda.

If you go that way, then you are alone on the possible problems.

Closing this by the reasons above.

**Comment by rmorgan999** [comment]
This was the output from the windows installer - I copied and pasted the error from the window!  I already have python installed on my machine as I use for my own software development.  Surely you must cater for this when you write the install package?

**Comment by rmorgan999** [comment]
https://en.wikipedia.org/wiki/Anaconda_(Python_distribution)

PS Not sure why you think Anaconda weird - its very widely used in the python community - see the numbers in the link above

**Comment by pedrobaeza** [comment]
I see weird because Odoo bundles its own Python distribution, not Anaconda, not because Anaconda is weird per se.
