### ISSUE TITLE
[8.0] Banner slide changes automatically in edit mode - makes changing content really hard.

### ISSUE THREAD

**Issue by michaelkarrer81** [odoo/odoo#2979]
The banner snippet should not automatically rotate it's slides when in edit mode - sometimes you are changing text and then the next slide slides in automatically which is really annoying and makes changing the text or the image nearly impossible.

**Comment by Yenthe666** [comment]
Hi @michaelkarrer81,

Thank you for your report.
This should have been fixed in https://github.com/odoo/odoo/commit/f30ab4a9904854c251a3e669cd20fe35bc7e9627 and as Odoo no longer supports Odoo 8.0 I'm closing this report.
If you can reproduce it in 9.0, 10.0 or 11.0 then please create a new report.

Regards,
Yenthe
