### ISSUE TITLE
[stock_account] compute product standard price while purchase

### ISSUE THREAD

**Issue by wangyuhuiever** [odoo/odoo#29805]
Impacted versions:
odoo 11.0

Steps to reproduce:
Create a purchase order, add one product twice in the order line with different price.
 
Current behavior:
The product standard price compute only use the latest price.
Expected behavior:
It should use the amount and quantity of the two lines to compute the standard price.
Video/Screenshot link (optional):

**Comment by sswapnesh** [comment]
I am able to reproduce this on Latest v11 Runbot

**Comment by wangyuhuiever** [comment]
I forget said, I used the average method.

**Comment by sswapnesh** [comment]
Yep, I reproduced it with AVCO on Product category.

**Comment by sswapnesh** [comment]
Adding Steps with Screenshot for reference

Steps to reproduce:

Set Costing method:  **AVCO** on Product Category

Create Product (Eg, **BOOM**) Belong to that Category

Create MO with two lines of **BOOM** product having different Unit price (1 Qty --> 10, 2 Qty --> 20)
![screenshot](https://user-images.githubusercontent.com/16624719/50536598-22d8e200-0b7c-11e9-8f3f-b755db2a5f1a.png)

Process Shipment

Current behavior:
On Product Price is **20**
![screenshot](https://user-images.githubusercontent.com/16624719/50536567-b231c580-0b7b-11e9-8a00-8b9382e515da.png)


Expected behavior: Price should be **15**

**Comment by sswapnesh** [comment]
Fixed in https://github.com/odoo/odoo/commit/ac270d63adee08128deea19286651b12bf73a91a

**Comment by pedrobaeza** [comment]
Closing then.
