### ISSUE TITLE
[12] Issue with _check_holidays constrains on leave

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#29806]
Impacted versions: 12

Steps to reproduce: Add leave and Save

Current behavior: 
`Compensatory Days (7 remaining out of 7)`
There is no leave for selected Employee "Anita"
![screenshot](https://user-images.githubusercontent.com/16624719/50534905-9cb3a000-0b69-11e9-8f29-bfa50678dba7.png)

![screenshot](https://user-images.githubusercontent.com/16624719/50534863-1008e200-0b69-11e9-87aa-e0302d561c5f.png)

Expected behavior: Able to Add leave

Video/Screenshot link (optional):

**Comment by RomainLibert** [comment]
Hello
Basically the problem you are having is that there is no allocation of compensatory days for `Anita Olivier` which means that you cannot take some `Compensatory Days` for her as those require an allocation.
There is nonetheless some problems in the application, pinpointed by your screenshots : 
   1) The numbers behind the name of the leave type does not contain a unit (it should always be days).
   2) The number of remaining leaves is not updated when changing the employee for which you take the leaves.

The first is "easily" fixable but will require to update the translation files of the module hr_holidays if we want it in 12.0.
The second problem is trickier as the remaining leaves are added in the `name_get` method and the javascript does not know that it has to be updated every time any field is edited, hence no update is visible until you click on the field to select another value. This problem will probably not be fixed in a stable version.

**Comment by sswapnesh** [comment]
IMO, making Leave type (Holiday status id) empty on Onchange of employee should the best and simpler.

**Comment by sswapnesh** [comment]
By adding
`holiday_status_id = False
`here https://github.com/odoo/odoo/blob/12.0/addons/hr_holidays/models/hr_leave.py#L348
