### ISSUE TITLE
[12] Use correct Unit (Take Leaves in) in Display Name of Leave request

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#29804]
Impacted versions: 12.0

Steps to reproduce: Put leaves in Hours
![screenshot](https://user-images.githubusercontent.com/16624719/50534687-442ed380-0b66-11e9-9a05-470f3c176660.png)

Current behavior: Mitchell Admin on Compensatory Days :0.19 day(s)

Expected behavior: Mitchell Admin on Compensatory Days :1.30 hours (and use float_time widget on number_of_hours_display field)

![screenshot](https://user-images.githubusercontent.com/16624719/50534703-8fe17d00-0b66-11e9-8880-1cd896b72e38.png)

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
I personally don't really consider it a bug and like it as is, but that is my opinion.

**Comment by sswapnesh** [comment]
IMO this should consider Leave unit there too.

**Comment by alexey-pelykh** [comment]
The origin of this "Take Leaves In" is not clear to me: the "unit to display in" and "amount of time to be exact in days" are mixed up, to allow users to take 1.5 days I have to use "take leave in hours" while "1.5 days" is totally fine. The `request_*` fields are so overcomplicated - instead of all this voodoo magic it should've been a wizard and straightforward leave request editing form with "from/to" timestamps, IMO.
