### ISSUE TITLE
Issue in Importing the CSV for 2 level one2many fields

### ISSUE THREAD

**Issue by KrishnaSingh7** [odoo/odoo#29877]
Impacted [versions]: `12`
![image](https://user-images.githubusercontent.com/46344494/50634108-93fd0880-0f73-11e9-96a9-5f7ab28a5ac1.png)

Current behavior: While importing the CSV not able to see the one2many fields within the one2many fields. because of the that not able to map them.

Expected behavior: Like v11 it should show the fields to map in the header.

**Comment by pedrobaeza** [comment]
Which one are you talking about specifically? Was this working in v11?

**Comment by KrishnaSingh7** [comment]
When we import nested one2many fields, its fields not showing in the dropdown for mapping.
yes, it is working on odoo 11.

**Comment by pedrobaeza** [comment]
Uhm, it seems so... @xmo-odoo I think it was you the one making the refactoring of the import tool, isn't it?

**Comment by Yenthe666** [comment]
@xmo-odoo could you give us an update please?

**Comment by sjpatel21** [comment]
This seems to be a deal breaker in one of our ported imported scripts. Would like to know the status of this as well.

**Comment by pedrobaeza** [comment]
Have you tried with latest code?

**Comment by spoerp** [comment]
I just checked with the latest code too, same result. You can only select External ID or Database ID of the O2M line at second level, but cannot see its fields.

**Comment by pedrobaeza** [comment]
@xmo-odoo can you give us some feedback?

**Comment by xmo-odoo** [comment]
@pedrobaeza looking back into [the original change](https://github.com/odoo/odoo/commit/d680ae5619eb16177178779420a9f386fc7fb4d6) it seems the selection depth was intended to be 2 from the start (though I'm guessing that was completely arbitrary back when it was first implemented 8 years ago) as the `FIELDS_RECURSION_LIMIT` constant was that value all along, but until 11.0 it was checked at the "wrong" place so there'd be a third level of recursion.

I apparently changed that as part of a bunch of other QoL changes, according to the commit message under the assumption that this level of depth was unnecessary but it would cause an unwieldy combinatorial explosion in the number of visible fields and thus the size of the fields list. In retrospect it might not have mattered that much as there's a FAYT and recursion ("Show fields of relation fields") is not enabled by default.

@sjpatel21 not sure why it'd impact scripts, it's only a UI limitation of the import wizard thing, the underlying import system should not be affected, or are your scripts UI automation somehow rather than RPC?

**Comment by pedrobaeza** [comment]
@xmo-odoo thanks for the follow-up, so should we conclude that this feature is not possible to be done? If so, I don't see that as a good decision, as it's very usual to create/update o2m fields (for example, importing a product and their product.supplierinfo, or a bank statement with its lines), so the xid is needed for knowing if you have to update or to create.

**Comment by spoerp** [comment]
@xmo-odoo the script just generated csv file with these relations. 
You are right, I was trying to import this csv through the UI itself, and had this issue.

It would be very helpful if you even increase the FIELDS_RECURSION_LIMIT to 3.

**Comment by xmo-odoo** [comment]
> @xmo-odoo the script just generated csv file with these relations.
> You are right, I was trying to import this csv through the UI itself, and had this issue.

Ah yes, that'd make sense.

> @xmo-odoo thanks for the follow-up, so should we conclude that this feature is not possible to be done?

Not necessarily, at a technical level it's just a matter of bumping the `FIELDS_RECURSION_LIMIT` up, it could be set to 20 or something (though that would probably be a very bad idea). It's more of a UI/business question.

> If so, I don't see that as a good decision, as it's very usual to create/update o2m fields (for example, importing a product and their product.supplierinfo, or a bank statement with its lines), so the xid is needed for knowing if you have to update or to create.

Technically the xid is available as it identifies the record itself (and so are the database id or "name search" finder), it's setting the fields themselves which is not.

**Comment by mssm199996** [comment]
I know this is a little bit late but here i wrote something that can help:

`
    from odoo import models, api

    FIELDS_RECURSION_LIMIT = 3

    class Import(models.TransientModel):
        _inherit = 'base_import.import'

        @api.model
        def get_fields(self, model, depth=FIELDS_RECURSION_LIMIT):
            return super(Import, self).get_fields(model, depth)

Just put that in a custom module and install it, and whenever you wish to go back to the previous config, just uninstall the module.
