### ISSUE TITLE
12.0 Impossible to run stock for FIFO multicompany manufacturing

### ISSUE THREAD

**Issue by gdgellatly** [odoo/odoo#29960]
Impacted versions: 12.0

Steps to reproduce:
Set a company on the production location (a necessity in multicompany for WIP valuation)

Current behavior:
The function _get_in_base_domain (and I imagine its counterparts) decided that company_id and NOT location usage is the sole arbiter of whether a location is internal, therefore manufactured moves can never be found.  The same is true for stock that came from taking Inventory Valuation.

Expected behavior:
Determining whether a move is incoming (or outgoing) should be determined by the locations usage, not by the company_id.  What I think is needed is for the parts where company_id is False for those to read usage != internal, and for those parts where company_id is set, an additional setting for usage == internal.

https://github.com/odoo/odoo/blob/52057da36f71d89f902fa3b9ace97f04ed260795/addons/stock_account/models/stock.py#L157-L178

@nim-odoo 
Video/Screenshot link (optional):

**Comment by sle-odoo** [comment]
Hi,
The "correct" logic is used [there](https://github.com/odoo/odoo/blob/12.0/addons/stock_account/models/stock.py#L186) by looking on the location's usage and company [here](https://github.com/odoo/odoo/blob/12.0/addons/stock_account/models/stock.py#L52). I'm not sure why we still need `_get_all_base_domain` though, which is slightly different. I'll have a look next week.

> Set a company on the production location (a necessity in multicompany for WIP valuation)

Can you elaborate? I think i know where you're going to though, if you want different accounts for different companies, you would need different production's locations (similar to what you should do with different inventory loss locations). 

We were aware of this issue and it's halfway fixed in 12.1 [with this commit](ee1ea10c8cc35c13439ef455a0eef454b7abaf85). Here we automatically create the different production locations, however i'm pretty sure the stock_account part you're referring to hasn't changed. I'll have a look next week.

Thanks for the report

**Comment by gdgellatly** [comment]
Hi @sle-odoo ,

`_get_all_base_domain` if I recall correctly, is only used in fifo_valuation, interestingly it's effect is to exclude moves which should be included in this scenario. Which gives a rather weird inventory report. For manufactured goods (either raw materials or finished products) the quantities are wrong, but clicking the action they are the right quants.

Yes naturally it is for company specific Work In Progress accounts. They are more analogous to stock input/output accounts consuming and creating inventory than inventory loss accounts and they typically sit on the balance sheet. 

Yes, the correct logic that you point to was before the scheduler refactor from a report I made in 2017. Reviewing that, it seems I forgot the transit location case which I also forgot in 2017.

**Comment by pedrobaeza** [comment]
@sle-odoo any extra comments here, or what should we do with this issue?

**Comment by sle-odoo** [comment]
@pedrobaeza this seems fixed for a long time now

``` python
    def _should_be_valued(self):
        """ This method returns a boolean reflecting whether the products stored in `self` should
        be considered when valuating the stock of a company.
        """
        self.ensure_one()
        if self.usage == 'internal' or (self.usage == 'transit' and self.company_id):
            return True
        return False
```

anyway, i would highly recommend to open an opw if there's still indeed an issue here. it would be handled properly.

**Comment by pedrobaeza** [comment]
OK, closing then. Thanks for the followup :)
