### ISSUE TITLE
Unread Messages not working in odoo 11

### ISSUE THREAD

**Issue by kamleshahir** [odoo/odoo#30250]
### Impacted versions: 10, 11
Steps to reproduce:
**1. Go to Project menu
2. Go to Task menu
3. Open Filter and Apply Unread Messages**
**I have checked on runbot for v10 and v11 but not working there also.**
**In version 8 and 9 this functionality is working fine. **

`<filter string="Unread Messages" name="message_needaction" domain="[('message_needaction','=',True)]"/>
`

**Comment by kamleshahir** [comment]
> `<filter string="Unread Messages" name="message_needaction" domain="[('message_needaction','=',True)]"/> `
> 
> In version 11 project this filter not working.

**Comment by kamleshahir** [comment]
**Impacted versions: 10, 11**
Steps to reproduce:
**1. Go to Project menu
2. Go to Task menu
3. Open Filter and Apply Unread Messages**
I have checked on runbot for v10 and v11 but not working there also.
**In version 8 and 9 this functionality is working fine. **

<filter string="Unread Messages" name="message_needaction" domain="[('message_needaction','=',True)]"/>

**Comment by Yenthe666** [comment]
@kamleshahir,

I've tested it and it works fine in both V10 and V11.
Steps:
1. Login with account X and add a message on a task
2. Login with account Y and apply the filter.

Result:
![image](https://user-images.githubusercontent.com/6352350/51323657-0f2ce700-1a69-11e9-816e-a3bdec1d244e.png)

You might want to update your Odoo.

**Comment by kamleshahir** [comment]
Hello @Yenthe666 
I've testes on runbot odoo 11 community
But not able to find unread messages task's

![r1](https://user-images.githubusercontent.com/16555768/51324805-a86ff380-1a91-11e9-892c-9c8ea2f25cf9.png)

**Comment by Yenthe666** [comment]
Hi @kamleshahir,

I've actually tested this with another account and you're right. It only seems to work with the administrator user. If you're a follower and tagged it should show up for sure.

I made an official ticket at Odoo under number 1930258

**Comment by sswapnesh** [comment]
That's because of explicitly writing `'is_read': True` for each Notification at https://github.com/odoo/odoo/blame/11.0/addons/mail/models/res_partner.py#L145

(Commenting that line enables Unread Messages, However I am not sure about the Intended behaviour)

Related commit: https://github.com/odoo/odoo/commit/2950ffaa86ef38263e9a4a59a30d0768f82a61fa

**Comment by sswapnesh** [comment]
Looks intended behaviour to me (Sorry but I was slow to understand commit message)

This is because of Email Preferences for that User
![screenshot](https://user-images.githubusercontent.com/16624719/51340965-4a093c00-1ab6-11e9-95c5-38270ad822d3.png)

Set it to **Handle in Odoo** and this will work fine.
(Handle by Emails will always mark to All Notifications as Read)

Can some one please confirm ? 
@kamleshahir or @Yenthe666

**Comment by Yenthe666** [comment]
Hi,

I've also checked with the guys from Odoo and in fact you're right! When it is set to "Handle in Odoo" it will show up as unread, if you set it to "Handle by Emails" you won't get results with the unread messages filter.
I never knew this. On a sidenote, the behaviour was different in V10 for this filter too.

**Comment by sswapnesh** [comment]
There are plenty of things like this which we never knew without digging more. (and Indeed commit message helps a lot)
