### ISSUE TITLE
Wrong Manufacturing Sequence Bug when log in not admin user in Odoo 11

### ISSUE THREAD

**Issue by Sroeurnsuon** [odoo/odoo#30287]
Impacted versions:
11.00
Steps to reproduce:
Correct this problem
Current behavior:
The MO sequence leap not in sequence when log in not admin user
Expected behavior:
Correct MO sequence number not leap
Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/25451156/51295812-f530db80-1a4b-11e9-9501-e94397c0942b.png)

**Comment by pedrobaeza** [comment]
I don't get the problem. Is it that there are not used MO/XXXX numbers?

**Comment by Sroeurnsuon** [comment]
Dear Mr. Pedro,

Thank you for your answer. 
I used that number format MO/XXXX as you can see in the image.
If you tested with Admin user is OK, but other user that has limited the permission, has a problem?

Best regards,
Sroeurn

**Comment by pedrobaeza** [comment]
That can be due to several reasons:

- Not full rights over manufacturing.
- Manufacturing orders over several companies.
- Default filter applied.
- Custom module acting.

In any case, this doesn't seem a problem of Odoo itself.

You can check also on runbot, which is a fresh DB without modifications: https://runbot.odoo.com/runbot - admin/admin.

Closing this for now until further things are provided proving that this is a real issue.
