### ISSUE TITLE
float_round don't work with some values

### ISSUE THREAD

**Issue by carlosdauden** [odoo/odoo#30354]
If you want round 6.1 with 0.001 precision the result is 6.1000000000000005
This operation 
https://github.com/odoo/odoo/blob/c45a4e8f835fd8d22af8941fd85e2b951f1e046b/odoo/tools/float_utils.py#L100
with rounded_value=6100 and rounding_factor=0.001
returns 6.1000000000000005

@Tecnativa

**Comment by carlosdauden** [comment]
May be related with this closed issue: https://github.com/odoo/odoo/issues/20856

**Comment by pedrobaeza** [comment]
Yeah, but this answer is the right one also for this one: https://github.com/odoo/odoo/issues/20856#issuecomment-344585431

The problem is in the nature of floats. The solution is to use the proper tools for comparing results, like done in #30352.

As this is not possible to be fixed in a general way, closing.

**Comment by carlosdauden** [comment]
Ok. Thanks
