### ISSUE TITLE
When select some records to export, all records are exported OPW-1938267

### ISSUE THREAD

**Issue by edy1192** [odoo/odoo#30939]
Impacted versions: 12.0

Steps to reproduce:
1. Go to a tree view. As Quotations or Contacts.

1. Group records by some field.

1. Expand the records to export, select them and export them.

Current behavior:
In the first instance, all records are exported.

To export only those selected, it must expand and collapse some of the records (do not deselect them) and then export again.

Expected behavior:
Only the records selected the first time must be exported.

Video/Screenshot link (optional):

[Video](https://drive.google.com/file/d/1vlrKAx73cuCVmSUWn6tLqL9Uwt494Rsx/view?usp=sharing)

**Comment by Boudmir-Ibrahim** [comment]
Hi @edy1192 ,
I try to reproduce your issue in V12  and i always get the right results.. 
I wen to Quotation and Group them by Salesperson. Then, I selected different records from both 'groups' 
hit export Excel fomat.
The result : I get the correct number of lines that represent the quotations i have selected. 
Can you check once again ?
Regards.

**Comment by edy1192** [comment]
Hi @Boudmir-Ibrahim 
Sorry, what I meant it was expand one group and check the `select all` check. 

![image](https://user-images.githubusercontent.com/11479473/52573725-5dbb7000-2de0-11e9-87ab-f42127ff391a.png)


How is this box supposed to work? Select all records on the screen or only those in the expanded group? I expect it select only those records in the expanded group.

Thanks for your help.

**Comment by Boudmir-Ibrahim** [comment]
Hi @edy1192 
AFAIK, If you expand one group and then click on Select All, it will only select the records related to the group expanded and not all the records in the list view

**Comment by edy1192** [comment]
Hi @Boudmir-Ibrahim 
So, the behavior that I explained is a wrong behavior, right? because when I expand one group and then click on `Select All`, all records in the view are exported and not just the records related to expanded group.

Thanks for your help.

**Comment by Boudmir-Ibrahim** [comment]
Exactly.

**Comment by Julien00859** [comment]
If the "select all" checkbox is checked then export will export all records (even those not visible because unfolded by a *group by* and those on other pages), otherwise if the checkbox is not checked then it exports only the selected records (those visible **and** checked).

Doing any operation in the list (like unchecking any record) will automatically uncheck the "select all". I would suggest you to a filter instead of the *group by* if you wish to just export specific records.

I did a feedback to take action in the future versions, we agree the feature is misleading but we don't change behaviors in stable version :/
