### ISSUE TITLE
[POS] Error "Uknown Barcode" while entering customer's email or phone 

### ISSUE THREAD

**Issue by tglukhov** [odoo/odoo#30941]
Hello everyone, 

I just found this issue:

Impacted versions: v12
ONLY ANDROID DEVICES

Steps to reproduce:
Point of Sale>>Customer>>Add a customer (button on the right from field "search customers") 
enter one or more signs in the field "Email" or "Phone". 

Current behavior:
When you enter one or two symbols then the keyboard disappears.
When you type quickly 3 or more symbols, an error popup appears "Unknown Barcode"

Expected behavior:
You enter customer's email and phone like others fields like "City" "Street" etc..

Video/Screenshot link (optional):

![Screenshot](https://user-images.githubusercontent.com/45606959/52456439-d5e01800-2af8-11e9-8c18-b10532ce5ecd.jpg)

**Comment by switch87** [comment]
@tglukhov I tried to reproduce this but did not get this error. I tested with the android browser, Chrome and Firefox. Can you give more details?

**Comment by switch87** [comment]
@tglukhov If you have seen my previous answer, ignore it. I confirm this bug. If you want to be able to edit customer information while not fixed, you can use Firefox, this seems to work.

**Comment by tglukhov** [comment]
@Yenthe666 the issue persists also in V11, I've tried it on runbot. 

@switch87 Thank you, indeed, using Firefox solves(or avoids) the issue.

**Comment by elementgreen** [comment]
Because Chrome is much faster on the tablet I'm trying to use, I put some additional effort into tracking this down. It appears to be caused by HTML input element 'type' attributes in the addons/point_of_sale/static/src/xml/pos.xml file. The partner.email field is declared with type='email' and the partner.phone has type='tel'. Removing those attributes fixes the problem. I'm not sure why Chrome on Android is having issues with them though.

**Comment by switch87** [comment]
@elementgreen Chrome should have support for type email and type tel, so this seems to be a Chrome bug and not an Odoo compatibility issue. I tested again just now, and aparently on the chrome I have on my smartphone it works again as should. If you or @tglukhov can confirm this issue can be closed.

**Comment by elementgreen** [comment]
@switch87 I created a test HTML file with just a form with email and tel type input fields and loaded it up on the same Android Chrome browser. The issue did not occur in that case. So I don't think the problem is because Chrome doesn't support these fields, but that this is triggering the problem somehow. I see there is a lot of keypress related Javascript code, which is suspect to me. What happens when a key is pressed is that the field loses focus, but I'm not sure where the focus goes to. I also tested the Android on screen keyboard and the built in POS on screen keyboard. In all 3 cases (hardware keyboard, Android on screen keyboard, and POS on screen Keyboard) the field loses focus when a key is pressed. However, with the POS on screen keyboard, the key is successfully input into the field before losing focus, with the other two options the key is not captured. Going to try disabling some of this keyboard related Javascript code to see if that fixes it.

**Comment by elementgreen** [comment]
After hooking up a remote Chrome debug session over USB to my tablet, I figured out what Javascript function is causing this problem. It is _listenBarcodeScanner in addons/barcodes/static/src/js/barcode_events.js. The following JQuery statement is evaluating to true, when it supposed to be false:
`if (!$('input:text:focus, input[type=number]:focus, textarea:focus, [contenteditable]:focus').length) {`

This results in the the following line getting executed:
`this.$barcodeInput.focus();`

Which results in the text input losing focus.
The text input having an "email" or "tel" type attribute seems to be making JQuery not match any of the listed selectors. Technically it seems like it shouldn't match input:text (not a type='text' input) so that leaves [contenteditable] which doesn't seem to be an attribute that is set by default.

I set the conditional to the following and it fixed the issue:
`        if (!$('input:text:focus, input[type=number]:focus, input[type=email], input[type=tel], textarea:focus, [contenteditable]:focus').length) {
`
Maybe there is a more general JQuery selector which would include these input fields also though?

**Comment by tglukhov** [comment]
@switch87 saw the answers of @elementgreen I prefer to leave this issue opened for now. 
Thank you

**Comment by switch87** [comment]
> After hooking up a remote Chrome debug session over USB to my tablet, I figured out what Javascript function is causing this problem. It is _listenBarcodeScanner in addons/barcodes/static/src/js/barcode_events.js. The following JQuery statement is evaluating to true, when it is supposed to be false:
> `if (!$('input:text:focus, input[type=number]:focus, textarea:focus, [contenteditable]:focus').length) {`
> 
> This results in the the following line getting executed:
> `this.$barcodeInput.focus();`
> 
> Which results in the text input losing focus.
> The text input having an "email" or "tel" type attribute seems to be making JQuery not match any of the listed selectors. Technically it seems like it shouldn't match input:text (not a type='text' input) so that leaves [contenteditable] which doesn't seem to be an attribute that is set by default.
> 
> I set the conditional to the following and it fixed the issue:
> ` if (!$('input:text:focus, input[type=number]:focus, input[type=email], input[type=tel], textarea:focus, [contenteditable]:focus').length) {`
> Maybe there is a more general JQuery selector which would include these input fields also though?

@elementgreen You did not test this on the latest version right? I investigated the code and I found a line that is similar to your solution. Please only test on latest github versions, preferable on http://runbot.odoo.com/runbot (user:admin password: admin) before reporting a bug.
