### ISSUE TITLE
[12.0] Error with revert on invoices (with cash basis)

### ISSUE THREAD

**Issue by luistorresm** [odoo/odoo#30972]
Impacted versions:
12.0

Steps to reproduce:
Previous configurations:
1. Active cash basis on the accounting settings
2. Configure the `Tax Due` = `Based on Payment` on the purchase tax
3. Configure the tax account as `Allow Reconciliation`
4. Generate a new supplier invoice with the same tax configured.
5. Validate the invoice
6. Go to the journal entry on the invoice and try to generate a `Reverse Entry`

Current behavior:
`You are trying to reconcile some entries that are already reconciled.` is returned when trying to generate the reversal.

Expected behavior:
The `Reverse Entry` is generated

Video/Screenshot link (optional):
https://www.youtube.com/watch?v=Xxdr3sysn1Y

Ticket #1938809

**Comment by edy1192** [comment]
This same behavior occurs in the following case:
Steps to reproduce:
Previous configurations:

1. Active cash basis on the accounting settings
2. Configure the `Tax Due` = `Based on Payment` on the purchase tax
3. Configure the tax account as `Allow Reconciliation`
1. Create a customer invoice in foreign currency with the same tax configured; with a past date invoice (eg. 12/17/2018)
1. Make a payment to the invoice with a past date (eg. 12/31/2018) and leave a residual of 0.01.
1. Make another payment for the residual amount in local currency with current date.

Current behavior:
`You are trying to reconcile some entries that are already reconciled.` is returned when validate the second payment.

Expected behavior:
The second payment should be validated.

[Video](https://www.google.com/url?q=https://drive.google.com/file/d/1MCoRr_OfNSMM_b0A8rytSJuwAD5gkWTv/view?usp%3Dsharing&sa=D&source=hangouts&ust=1549762673712000&usg=AFQjCNHkLGJAX5Y3L50phuzUD5NpGlCYug)

**Comment by moylop260** [comment]
FYI I just have created a unittest to reproduce this issue here:
 - https://github.com/odoo/odoo/pull/31168

**Comment by moylop260** [comment]
FYI Changing to `usd.rounding = 0.0001` the issue is not reproduced in the tests

**Comment by moylop260** [comment]
@qdp-odoo 
Could you check the main description of this issue, please?

And the following video:
 - https://youtu.be/Xxdr3sysn1Y

cc @nhomar @hbto

**Comment by keylor2906** [comment]
@moylop260 
This is test for the main issue of @luistorresm https://github.com/odoo/odoo/pull/31480

**Comment by moylop260** [comment]
@smetl 
Could you check the unittest from https://github.com/odoo/odoo/pull/31480?
IMHO a reverse shouldn't make cash basis journa items
