### ISSUE TITLE
[12.0] Multicompany permission bug

### ISSUE THREAD

**Issue by reinaldoramosarxi** [odoo/odoo#31376]
Impacted versions: 12.0

Steps to reproduce: 
1. On a Multi-company context, have two different users with all permissions on all companies;
2. User A is currently in one company while user B is in another company;
3. User B creates a (eg. project task) record on that company for user A;

Current behavior: Despite user A and B having permissions on both companies, apparently the permission validation is based on current company and not on company permissions, so it throws a permission error.

Expected behavior: Since user A has permissions on the other company, user B should be able to create a task on the other company, regardless of user A's current company.

**Comment by pedrobaeza** [comment]
Which is the error? Is it reproducible on runbot?

**Comment by reinaldoramosarxi** [comment]
It's the following error:
![error](https://user-images.githubusercontent.com/42942314/53253190-97ca2300-36b8-11e9-9777-d216368a73b2.png)

It is reproducible on runbot. 

In this case, we reproduced the error by scheduling an activity to a user that is currently on a different company.

**Comment by pedrobaeza** [comment]
But that's expected. A user can work for you companies. If needed, then you should have 2 users for the same physical person.

**Comment by reinaldoramosarxi** [comment]
Two users would mean two paid licenses, how would that work for a customer?

**Comment by pedrobaeza** [comment]
Then the user should stay in the same company when assigning. This limitation is somehow technical (due the way multi-company by record rules work), but also by design, as you shouldn't have tasks from several companies assigned to the same user. If you are using tasks as TODO, use activities instead.

**Comment by reinaldoramosarxi** [comment]
Well, technical or otherwise, we did manage to circumvent it, but if it is by design, then it is peculiar: isn't it the goal of a multi-company context to be able to access several companies with the same user? Consider that the user manages a group that is all under a main company, and all of these companies are managed in Odoo (which is the case of some of our customers). This manager user (that has access to all companies) cannot be constantly switching companies just so someone in a sub company can assign something to him, or when he needs to access a document and he's not sure what company it was created in: it's simply not feasible.

But the issue is not only with tasks, it happens when you try to see a sale order that was created with a different company_id as the one you're currently on. I understand the rule, but the fact that it bases itself on current company rather than the companies you have access to is not logical or ergonomic.

**Comment by a-willem** [comment]
Seconded, we experience the same use cases and same problems w/r to permissions.


Arnaud Willem
Directeur Adjoint

03 88 27 90 00
06 98 74 56 36

**Comment by pedrobaeza** [comment]
The golden rule of multi-company is to operate in only one company each time. Parent companies for seeing aggregated data for several companies must be used only as read only. If you operate from the parent company for introducing things in children companies, data will be mixed from the several companies (customers, payment mode, journals...).

If you circumvented it in your DB, then you might find one day that the data is mixed this way.

This is because the approach is multi-company per DB, not multi-company per document. Changing this approach is in the mind of Odoo people, but not so simply to be performed.

**Comment by reinaldoramosarxi** [comment]
What we did was changing the rule, and that worked for us.

I understand why it works that way, and it is not our goal to mix data. The problem is that it doesn't even allow reading.

**Comment by pedrobaeza** [comment]
I'm not sure if there's a way to mitigate it for this specific case.

@tde-banana-odoo I remember that you have handled in the past other things like this. What do you think about this one?

**Comment by popiahalex** [comment]
i can't even edit setting for company b. (Document Type: res.users, Operation:read)

**Comment by mdmfox** [comment]
I've been experiencing the same issues. Monitoring the database I could see that 
whenever user X login into company B, odoo sets res_user.company_id as company B for this user.
The table res_company_assignment_res_partner_rel column res_company_assignment_id, change from A to B as well. 
So then, if user Y tries to print a receipt that was made by user X in company A; the system will throw a permission exception. 
I looked into the code this company id validation in order to eliminate it, but it's taking too long. 
@reinaldoramosarxi would you mind sharing with us the rule you changed to get it working?

**Comment by reinaldoramosarxi** [comment]
@mdmfox We changed pretty much every document's rule for multi company access, basically changing it from the user's current company to the user's list of authorized companies.

**Comment by Moto017** [comment]
I came across this issue today as well.  Assigned Task User who changes to alternate company raises security issues under res.user.

**Comment by mdmfox** [comment]
Hi @Moto017, first of all I set permission access based on menus to filtering what each user/group should really see. After that, with the remaining errors, I checked one by one and set sudo in the QWEB Report field to give extensive access to anyone that could reach that report.

For example:
One report was throwing doc.user permission error:   
<p t-field="doc.user_id"/>
After changing as following below, no more errors:
<p t-field="doc.sudo().user_id"/>

With that I allowed anyone to access that object as a root user, but my security was already set filtering who would reach that report. Moreover, there is no editable fields for pdf reports.
