### ISSUE TITLE
Odoo 12EE - Problem extending a view in custom theme 

### ISSUE THREAD

**Issue by Apollo21ap** [odoo/odoo#31636]
# **Impacted versions:**
v12 Community and Enterprise.
# **Steps to reproduce:**
Install a custom theme and then try in a new module to extend a view from this theme.
# **Current behavior:**
Every time when I try to inherit a template from a custom them and to extend it in a custom module, I've got the same problem: can not be located in parent view. My xpath expressions that I tried are correctly. 
I installed the custom theme from the "Website" menu, in "Settings", choose a theme item. 
In apps I can't find this module that contains theme. I used update apps list and nothing to show.
In views from Technical, I can't find the real external ID for the theme views. 
In v11, in a theme for this version, all views from a theme got external id!
When I tried to extend I took template id from the team (module_name.template_id). It's not first time when I extend a view from a theme. But I did that in v11 and v10. 
I think I have identified where the problem starts. There are two tables in the database: ir_ui_view and theme_ir_ui_view;
When you inherit a theme view, theme.ir.ui.view takes over the parent view id from the theme_ir_ui_view table, but then associates with a record in the ir_ui_view table that is the same id.
The only solution I have found so far is to add the active = "False" attribute when you make a view and after you manually add (from Technical, Views) id of the inherited view from the theme and set view to active true. Obviously, this is not a good or temporary solution. Moreover, it only works once (the next update of the way initially returns the problem that it does not find the xpath what you are looking for).

# **Expected behavior:**
Can extend views from a theme.

# **Video/Screenshot link (optional):**

-

**Comment by pedrobaeza** [comment]
Please see https://www.odoo.com/documentation/user/12.0/website/publish/multi_website.html#technical-hints-for-customization

**Comment by pedrobaeza** [comment]
And also https://github.com/odoo/odoo/issues/28695#issuecomment-441007826

**Comment by AdrianTeng** [comment]
I don't think this issue has a solution at all (and the closing of this issue is premature):

@Apollo21ap correctly identifies that `<template>` from a theme module writes first to `theme.ir.ui.view`. Code inside `website_theme_install` then handles the replication of template contents from `theme.ir.ui.view` to `ir.ui.view`. However, `website_theme_install` only update themes views from active theme module, which means your addon on top of the theme will not be updated.

There are few workarounds:

1) as @Apollo21ap suggested, put `active=False` first, then fix the inherit ID manually on technical settings (one could surround the xml with `noupdate="1"` and maintain that xml manually from now on)
2) directly edit the theme in xml or in technical settings -> view ¯\_(ツ)_/¯
3) create a separate theme module, move the views over, and manually trigger the update function `_update_records` from shell (I have not tried this)

**Comment by AdrianTeng** [comment]
Made an actual solution building on top of workaround 3 above:

First build a new theme module -- make sure the name starts with `theme_`. Place all your qweb templates that would inherit from another theme here.

Then place the following inherited ir_module_module class in your theme module, assuming your theme name is `theme_my_fancy_theme`

```
class IrModuleModule(models.Model):
    _inherit = "ir.module.module"

    def write(self, vals):
        for module in self:
            if module.name in ['theme_my_fancy_theme'] and vals.get('state') == 'to upgrade':
                for website in self.env['website'].search([]):
                    module._theme_load(website)
        return super(IrModuleModule, self).write(vals)
```

This forces the theme copy logic to run on your theme module as well.

I suspect there might be accidental triggers of this logic in some unknown circumstances, so I would recommend users of this to avoid making db direct changes on any xml your theme touches
