### ISSUE TITLE
[11.0] account: Unreconciled filter shows residual=0 move lines

### ISSUE THREAD

**Issue by carlosdauden** [odoo/odoo#32044]
I think that `balance` should be replaced by `amount_residual`

https://github.com/odoo/odoo/blob/d2d7f575298f57365c23d86566f7fb5ea50c284c/addons/account/views/account_view.xml#L1298

@Tecnativa

**Comment by pedrobaeza** [comment]
Long explanation is because if you reconcile for example 90 against 100, both items are shown as not reconciled, while one of them is already reconciled (in this case the 90 one).

**Comment by carlosdauden** [comment]
Sorry by my short explanation.
Thanks @pedrobaeza

**Comment by pedrobaeza** [comment]
@qdp-odoo maybe you can confirm this change is the suitable one and we can do the PR.

**Comment by qdp-odoo** [comment]
No, I don't. 

That's what we made previously at the release of v11, but back then people were confused because they couldn't see all the items involved in partial reconciliations.... For example, a payment of 50€ reconciled with an invoice of 75€ would show only the invoice but 
1) the payment doesn't have the matching number written
2) it looks like the open balance of the customer is 75€ whereas it's actually 25€. This is because we don't show the amount_residual column.

So I don't think it's a good idea, and I'm closing this suggestion. I hope it's clear and that you agree with me.

**Comment by rafaelbn** [comment]
Dear @qdp-odoo ,

I fight with Odoo accountants and I agree that the sometimes want to see "all the items involved in partial reconciliations".

But sometimes they don't want to see and furthermore the can make mistakes. So if you agree, would be a pleasure for as make two simple and really nice (powerful) improvements in **views** for v13

1. Add the option for the users to show or hide the "Amount Residual" fields in the list view. No there is not option and is easy as adding one single line

`<field name="amount_residual" optional="hide"/>`

![2019-10-23_17-29-45](https://user-images.githubusercontent.com/8736623/67409649-25993d80-f5bb-11e9-91a4-5ba43c88896f.png)

2. Add a filter to hide unreconciled with residual = 0 and let Accountants to choose

`<filter string="Unreconciled (residual=0)" domain="[('full_reconcile_id', '=', False), ('amount_residual','!=', 0), ('account_id.reconcile','=',True)]" help="Journal items where matching number isn't set" name="unreconciled"/>`

![2019-10-23_17-29-31](https://user-images.githubusercontent.com/8736623/67410505-7cebdd80-f5bc-11e9-95a8-8092502434e4.png)


If you agree we can do a PR with:

- [ ] 1 + 2
- [ ] only 1
- [ ] only 2

Thank you!

**Comment by qdp-odoo** [comment]
I read you, and agree we have some usability work to do for the matter. That will be addressed in master, for a next saas release
