### ISSUE TITLE
same error solved in #20784 for Community version 12

### ISSUE THREAD

**Issue by OpenTechValue** [odoo/odoo#32197]
Impacted versions:
Community 12

Steps to reproduce:
when creating a backorder in performing a goods receipt from PO this error message has occurred:
It is not possible to unreserve more products of XXX than you have in stock.

Current behavior:

Expected behavior:

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by OpenTechValue** [comment]
sorry, this is related to a custom module
I've fixed it
sorry for wasting your time
Regards

**Comment by shivbhadrasinh003** [comment]
> sorry, this is related to a custom module I've fixed it sorry for wasting your time Regards

Pleasse explain. How it can be fixed?
