### ISSUE TITLE
aria-hidden css error

### ISSUE THREAD

**Issue by rowemoore** [odoo/odoo#32265]
Impacted versions:
12, probably all
Steps to reproduce:
try to see an aria-hidden element in a normal browser
Current behavior:
css generated from web/static/src/scss/ui.scss is creating a rule that hides aria-hidden=true from all browsers, not just screen readers
Expected behavior:
That aria-hidden would be handled by screen readers, etc., not css
Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
I don't get the problem. aria-hidden is intended for screen readers. Why do you want to see them in a normal browser?

**Comment by rowemoore** [comment]
I don't want to see them.  There is a css file (see above) that is hiding elements with aria-hidden.  This is supposed to be done with screen readers, not css, right?  I'm guessing I am doing something wrong as it would be hard to believe that this behavior has not be noticed before.  Nevertheless, the only fix I could come up with was to override the css in my custom module.  These images should clarify.

![aria-hidden-by-css](https://user-images.githubusercontent.com/14188201/55282381-15103580-5300-11e9-9261-c269182d0443.jpg)

![aria-hidden-fixed-by-css](https://user-images.githubusercontent.com/14188201/55282384-222d2480-5300-11e9-99a4-5c29c089255f.jpg)

**Comment by pedrobaeza** [comment]
No, that's done on purpose for dual compatibility with regular things and screen readers.

Closing as no real issue (or not proved). Please comment back and it will be reopened when a real problem is shown.

**Comment by rowemoore** [comment]
Aria-hidden=true should appear in a normal, fairly modern browser.  I have no idea by what you mean by "regular things."

**Comment by pedrobaeza** [comment]
OK, I got your idea. I meant that all the elements are available with double aria and normal specifications, but I was not aware of the aria visibility. Reopening this and asking to @qsm-odoo what is the reason for that CSS.

**Comment by qsm-odoo** [comment]
@rco-odoo @odony (cc @JKE-be)

**Comment by odony** [comment]
Judging from [this comment](https://github.com/odoo/odoo/pull/25481#issuecomment-400586517) on #25481, the rationale of @kujiu was that we use `aria-hidden` too often, instead of properly describing screen elements, e.g. with a `role` and `aria-label`.
The WAI spec clearly recommends to use `aria-hidden` [exclusively to improve the accessibility for assistive technologies](https://www.w3.org/TR/wai-aria/#aria-hidden), but making sure that the functionality is available in an equivalent manner elsewhere, and that's clearly not what we do everywhere.

As a result, making `aria-hidden` a synonym for `hidden` in Odoo is our incentive to avoid it, as it cannot be used by non-impaired users either - even if that indeed appears to be backwards semantics with regards to the specification.

I guess when we face a case where `aria-hidden` hides important content, it's a trigger to tell us we should _not_ be using `aria-hidden`there.

The canonical example is a "X" mark used as a close button for a dialog or alert. It's an actionable item that must not be hidden from screen-readers, so `aria-hidden` is not appropriate, and we should instead use `aria-label="Close"` or something similar, in combination with a proper `role` if the element is not a `<button>`.

@rowemoore in your case it seems that your flickity carousel [has chosen to use `aria-hidden` to hide cells that are supposed to be off-screen](https://github.com/metafizzy/flickity/pull/350). I'm not sure that gives proper accessibility to the carousel items. There seems to be a vast debate about this. You can have a look at the [accessibility-related issues](https://github.com/metafizzy/flickity/issues?utf8=%E2%9C%93&q=is%3Aissue++accessibility+) in flickity's bug tracker, and this interesting [list of pointers related to carousel accessibility](https://ux.stackexchange.com/questions/118607/content-slider-carousel-accessibility-best-practices#answer-118677).
Either way, I think it's fair to consider this a complex interaction between Odoo's accessibility choices, and flickity's own accessibility choices - both subjective and defendable. In that context, a little bit of custom CSS does not seem an inacceptable price to pay... :wink:

**Comment by rowemoore** [comment]
@odony, I agree custom css is an easy enough solution and also understand the logic on why Odoo has chosen to hide aria-hidden for normal browsers. 
With that said, IMO, I think Odoo should not override the intended behavior and let the front-end designer decide if an element is, for example, off-screen.  3d sliders would be an example where several slides are on-screen but only one should be presented at a time to a screen reader.  In my case, I would be tricky (for me) to write code that would determine if one of my slides is completely off screen  (it's a slider, after all) to decide when the attribute aria-hidden = true should be added.  In my case, it makes more sense to have screen readers step through the slides using the keyboard and then the element is described to the user.  Regardless of how many slides are on screen, only one is "active".

Not sure about other areas, but in California the accessibility issue for websites is becoming a big issue.   [Opportunistic lawyers are suing businesses](https://www.dailyrepublic.com/all-dr-news/wires/business/lawsuits-targeting-business-websites-over-ada-violations-are-on-the-rise/) because there websites are not completely accessible.

Thanks to all for your help.
