### ISSUE TITLE
[Master] SearchPanel LazyLoading

### ISSUE THREAD

**Issue by keshrath** [odoo/odoo#32275]
Impacted versions:

Master // 12.2

Steps to reproduce:

For example, if there are a lot of workspaces in the Documents app.

Current behavior:

Loading the SearchPanel data happens in the methods `willStart `and `update`. With both methods, the rendering of the view is only performed after the loading process has been completed. In my opinion this results in a not ideal user experience. Because in most cases the SearchPanel will not be used at all but the user has to wait for it to execute another action. It is comparable to a view without limit and instead of loading the first 80 records all are loaded, which can take much longer.

Expected behavior:

My suggested solution to this problem would be to load the SearchPanel asynchronously, i.e. the user can already use the view as usual and once the data has been loaded the SearchPanel will be rendered.

**Comment by keshrath** [comment]
The loading time in this example is artificially increased to better illustrate the problem and my attempt to solve it. 

![ezgif com-video-to-gif (14)](https://user-images.githubusercontent.com/4851083/55280571-bbbbfc80-5327-11e9-9166-697264324246.gif)

If this is a suitable solution I can do a PR with the necessary changes.

**Comment by keshrath** [comment]
@aab-odoo 

I hope it's okay if I tag you here. So far I've seen, but you've written most of the SearchPanel. And I would be very interested to know if you have already stumbled across this problem and if you have another plan to solve it.

**Comment by aab-odoo** [comment]
Hello @keshrath 

We considered your solution but it is not easily applicable. Indeed, we need the search panel information before fetching the records, as it may add parts to the search domain. Even though we have the information before doing the RPC (as we retrieve the categories default value from the context or local storage), we need to validate it first, since it may be deprecated, or simply not applicable for the current user.

Also, we are talking about a potential performance issue. It's probably too soon to try optimize it.

Anyway, we keep this in mind and will improve/fix it in future if it shows bad performance issues.

Regards.
