### ISSUE TITLE
multiwebsite and multicompany

### ISSUE THREAD

**Issue by andete22** [odoo/odoo#32374]
Impacted versions: odoo12
Hello,
Use odoo12. I raise my situation:
I have 4 users:
--Admin: Administrator
--User1: Editor and Designer
--User2: Editor and Designer
--User3: Editor and Designer
I have 3 companies:
--CO1, to which User1 belongs
--CO2, to which User2 belongs
--CO3, to which User3 belongs
I have 3 website, with 1 e-commerce each:
--WebCO1, from the company CO1
----Market1, with specific products for the company CO1
--WebCO2, from the company CO2
----Market2, with specific products for the company CO2
--WebCO3, from the company CO3
----Market3, with specific products for the company CO3
Configured as multiweb and multi company.
My problem:
Any user can edit any website:
Desired case:
That each user can edit ONLY, the website and the electronic commerce of his company. And that does not have access to the edition of the other website and electronic commerce.
Example: User1 enters and can view and edit only WebCO1 and Market1. You can not see any other website.
What you are really doing:
When entering with any user you can edit any website and any electronic commerce.
Example: User1 enters and you can edit WebCO1, WebCO2 and WebCO3.

**Comment by JKE-be** [comment]
It not considered as a bug.

Even if it could be an improvement to avoid the edition by error in the future, it will not avoid completely to break others websites.

You can easily as user 1 from company 1, to write in QWeb on a record on which you don't have the access rights (same for mail template, tax python, ... ).
Since you can execute what you want in Qweb, you can add more access right to yourself or alter other record.

The improvement will be more "A visual/client restriction" than a security.
