### ISSUE TITLE
[11.0] Stock Valuation report takes 20 mins to run in large DB

### ISSUE THREAD

**Issue by max3903** [odoo/odoo#32524]
Impacted versions:

11.0

Steps to reproduce:

On a large DB (10+ millions moves), go to Inventory > Reporting > Inventory Valuation

Current behavior:

Wait 20+ minutes to get the result.

Expected behavior:

Wait less than 5 min?

Pyflame graph:
[Inventory-valuation.zip](https://github.com/odoo/odoo/files/3055634/Inventory-valuation.zip)

Enterprise Ticket:
https://www.odoo.com/my/task/1961412

**Comment by moylop260** [comment]
Seems that the following lines are slow.

 
 - https://github.com/odoo/odoo/blob/9a7e3c8b4986fcfecf3699a194e45f5ec94bde6c/addons/stock_account/models/product.py#L213-L215

I saw 2 good ways to improve.
1) If you are using `prefetch_fields=False` and you are reading 2 fields without pre-filled it then you will have 2 calls for each stock move to database.
I mean,
SQL1: `move.product_id` <- `SELECT product_id FROM account_move ... `
SQL2: `move.remaining_value ` <- `SELECT product_id FROM account_move ... `

If we use a pre-fill of the cache with read

```python
moves = StockMove.search(domain).with_context(prefetch_fields=False)
moves.read(['product_id', 'remaining_value'])   # Pre-fill cache
for move in moves:
     product_values[move.product_id] += move.remaining_value 
     product_move_ids[move.product_id].append(move.id) 
```

Then the query executed will be just one:
SQL1: `SELECT product_id, remaining_value FROM account_move ...` 

It could optimize it 20% faster. (I think so)

2) In fact, it is a operation to optimize using `read_group`
```python
StockMove.read_group(domain, ['product_id', 'remaining_value'])
```

Then you avoid fetching `name_get`, fetching unused fields, slow python process to sum instead of faster postgresql one.
It could improve the performance 90% (I think so).

**Comment by moylop260** [comment]
FYI I just have created the following PR to fix it:
 - https://github.com/odoo/odoo/pull/32529/files

**Comment by odony** [comment]
Please see #32520 first, let's no duplicate more work ;-)

**Comment by sle-odoo** [comment]
I'm closing this one since the linked PR is merged and the delay when opening this report is reduced.

Regards
