### ISSUE TITLE
Image don't displayed in qweb-pdf report

### ISSUE THREAD

**Issue by maksymkv25** [odoo/odoo#32674]
Impacted versions:
12.0
Steps to reproduce:
In custom qweb-pdf report add a local image file:
`<img t-att-src="'/vendor_package_frontend/static/img/CD_Logo.png'" />`

Current behavior:
I don't see the image.
Expected behavior:
I expected that the image would be displayed.
Video/Screenshot link (optional):
![no_image_report](https://user-images.githubusercontent.com/12529036/56113655-234c8b80-5f67-11e9-8449-59f5cbdaef41.png)

**Comment by pedrobaeza** [comment]
This can be due to incorrect deployment without proper wkhtmltopdf access to instance resources:

- No report.url or incorrect one.
- Multiple databases without dbfilter.
- No proper reverse proxy configuration.

Please check that ones and go to forums for further questions.

Closing as no real Odoo issue.

**Comment by JayVora-SerpentCS** [comment]
I assume its mostly the path/relative path.

**Comment by akhmadali22** [comment]
I get this issue too in odoo12

this is my code:
`<img src="/my_module/static/img/img.png" width="100%" height="100%"/>`

this is my print out:
![1](https://user-images.githubusercontent.com/51687742/109448299-35127b80-7a78-11eb-9894-651092c0d4bb.PNG)
