### ISSUE TITLE
[12.0] "website" variable not present in view context, but as some sort of "global" variable

### ISSUE THREAD

**Issue by reinaldoramosarxi** [odoo/odoo#32743]
Hello,

We've had some problems in a few of our web templates, namely some that have forms and an input field called "website", for a customer to input their website, if any.

We finally pinpointed it to a variable that exists in these views, called "website", which obviously created problems if we had a char field by that name in the same view (namely, this "global" variable's methods and attributes being accessed, and obviously being non existant in our string object).

Apparently, some developers have made modules that have this problem, but didn't notice it (lack of testing, maybe).

We'd like to know if this is something that was intended, if maybe the env.context.get() method doesn't work in some places and this was the way to fix it, because it is a bit limiting whenever you need to call a variable "website" for readability purposes.

Thank you.

**Comment by Yenthe666** [comment]
Maybe @JKE-be can answer. For me there is no problem though, just use another variable than "website"?

**Comment by JKE-be** [comment]
It is one of the reserved keyword because we use it in qwebcontext.

Here a non exhaustive list:
- slug
- unslug_url
- main_object
- multi_website_websites_current
- multi_website_websites
- multi_website_companies_current
- multi_website_companies
- website
- url_for
- res_company
- default_lang_code
- languages
- translatable
- editable
- menu_data
- env
- user_id
- res_company
- keep_query
- request
- debug
- json
- quote_plus
- time
- datetime
- relativedelta
- xmlid
- viewid
- to_text
- image_data_uri

+ all the keys of the current context

**Comment by reinaldoramosarxi** [comment]
@Yenthe666 Sure, that's what makes sense now that we know it's a reserved word, but people will keep making that mistake :P
@JKE-be Thank you for the list, it's going to be really useful!
