### ISSUE TITLE
chinese font not diplay correct in rml report

### ISSUE THREAD

**Issue by jeffery9** [odoo/odoo#3288]
as titile,   latTest odoo run on ubuntu 12.04 with chinnese fonts installed, and have set report font as chinese font via report font configure option.   but still not work for report such as leave summary report and invoice.

**Comment by Yenthe666** [comment]
Hi @jeffery9,

I'm closing this issue since Martin gave a very good response that explains everything.
I believe this answers your question(s).
RML is deprecated and in Odoo 10 there will be nothing left of RML either.
Don't hesitate to comment on this topic if you do not agree with this.

Regards,
Yenthe
