### ISSUE TITLE
Html field with company_dependent=True on save a form view throw an error

### ISSUE THREAD

**Issue by akevinieron** [odoo/odoo#33026]
Impacted versions:
- 11.0

Steps to reproduce:
1. Make an HTML field with company_dependent=True on a model
2. Add the new field to a Form View
3. Try to create a new record

Current behavior:
When click save on form view with a html field with company_dependent=True, a raise with the followin text: "Invalid Type".

Expected behavior:
Save the record successfully

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/2160489/56916520-11023f80-6a87-11e9-8747-ab250f208da4.png)

**Comment by sswapnesh** [comment]
Hello @akevinieron  
This is expected behavior for now, You can add Company depended fields as mentioned in  https://github.com/odoo/odoo/blob/12.0/odoo/addons/base/models/ir_property.py#L8

Ps: PR https://github.com/odoo/odoo/pull/26556 is already proposed to allow html fields as company-dependent.

Cc: @pedrobaeza  (I think this can be closed as PR is already there :smile:)

**Comment by pedrobaeza** [comment]
Yes, closing as duplicated.
