### ISSUE TITLE
Install third party apps on odoo 12 CE

### ISSUE THREAD

**Issue by yakthungba** [odoo/odoo#33161]
Hello,

 Just installed odoo 12 CE on Debian 9.  I have no patience to score 3 karma points on odoo forum, so I came here with my newbie question. Hope you guys won't mind.
I have extracted some v12 apps inside the addons directory I have set in /etc/odoo/odoo.conf. None of those extracted apps are showing up inside apps list, also tried enabling developer's mode. Please give me some hint on how to install third party apps.

**Comment by Yenthe666** [comment]
Hi,

The Github tracker is for bugs in the official code and it is not the place to ask help questions.
You should really do this on the help forums 😉 
To answer your question:

1. Make sure the custom app directory is inside your Odoo configuration file
2. Make sure you've restarted your Odoo so that the new directories are load
3. Make sure you update your apps list before searching for the app

It should then show up.

Regards,
Yenthe
