### ISSUE TITLE
odoo requires postgres database to exist

### ISSUE THREAD

**Issue by litnimax** [odoo/odoo#33198]
Trying to use Digital Ocean PostgreSQL databases service.
Cannot overcome the fact Odoo trying to connect to postgres database that is not available.

```
odoo@d2ac7da555c7:/$ /entrypoint.sh odoo -d odoo --db_user=odoo --db_password=xxxxxx --log-level=debug_sql
2019-05-06 19:57:13,583 75 INFO ? odoo: Odoo version 12.0-20190424
2019-05-06 19:57:13,584 75 INFO ? odoo: Using configuration file at /etc/odoo/odoo.conf
2019-05-06 19:57:13,584 75 INFO ? odoo: addons paths: ['/var/lib/odoo/addons/12.0', '/mnt/extra-addons', '/usr/lib/python3/dist-packages/odoo/addons']
2019-05-06 19:57:13,585 75 INFO ? odoo: database: odoo@db-postgresql-fra1-xxxxx-do-user-xxxxx-0.db.ondigitalocean.com:25060
2019-05-06 19:57:13,585 75 DEBUG ? odoo.sql_db: create serialized cursor to {'user': 'odoo', 'database': 'postgres', 'sslmode': 'prefer', 'host': 'db-postgresql-fra1-xxxxx-do-user-xxxxxx-0.db.ondigitalocean.com', 'password': 'u5kcjz0arq20iuca', 'port': 25060}
2019-05-06 19:57:13,614 75 INFO ? odoo.sql_db: Connection to the database failed
Traceback (most recent call last):
  File "/usr/bin/odoo", line 8, in <module>
    odoo.cli.main()
  File "/usr/lib/python3/dist-packages/odoo/cli/command.py", line 60, in main
    o.run(args)
  File "/usr/lib/python3/dist-packages/odoo/cli/server.py", line 176, in run
    main(args)
  File "/usr/lib/python3/dist-packages/odoo/cli/server.py", line 140, in main
    odoo.service.db._create_empty_database(db_name)
  File "/usr/lib/python3/dist-packages/odoo/service/db.py", line 95, in _create_empty_database
    with closing(db.cursor()) as cr:
  File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 657, in cursor
    return Cursor(self.__pool, self.dbname, self.dsn, serialized=serialized)
  File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 171, in __init__
    self._cnx = pool.borrow(dsn)
  File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 540, in _locked
    return fun(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 608, in borrow
    **connection_info)
  File "/usr/lib/python3/dist-packages/psycopg2/__init__.py", line 130, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: FATAL:  database "postgres" does not exist
```

As we can see -d arg is used but it does not help. Also tried to set db filter arg but also no help.
May be Odoo should not require postgresql db to exist?

**Comment by gdgellatly** [comment]
`template1` is guaranteed to exist. Maybe we should use that instead of `postgres` for this operation. 

@odony

**Comment by Yenthe666** [comment]
Hmm I've had multiple Odoo's running on DigitalOcean without this problem though. I wonder how you've got it. :D

**Comment by litnimax** [comment]
Do u use new DO Databases service?

**Comment by Yenthe666** [comment]
Ahh no I don't, I use 'normal' droplets.

**Comment by litnimax** [comment]
Using template1 is not  a solution:
```
odoo@39268a4063ec:/$ psql  -h db-postgresql-fra1-xxxx-do-user-xxxxx-0.db.ondigitalocean.com -p 25060 -U doadmin template1
psql: FATAL:  pg_hba.conf rejects connection for host "x.x.x.x", user "doadmin", database "template1", SSL on
FATAL:  no pg_hba.conf entry for host "x.x.x.x", user "doadmin", database "template1", SSL off
odoo@39268a4063ec:/$
```

**Comment by litnimax** [comment]
I did a test. The resume is the following - Digital Ocean Databases services does not accept connections to any database except user's.
By default this is defaultdb.

```
defaultdb=> \l
                                  List of databases
   Name    |  Owner   | Encoding |   Collate   |    Ctype    |   Access privileges
-----------+----------+----------+-------------+-------------+-----------------------
 _dodb     | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 |
 defaultdb | doadmin  | UTF8     | en_US.UTF-8 | en_US.UTF-8 |
 template0 | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 | =c/postgres          +
           |          |          |             |             | postgres=CTc/postgres
 template1 | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 | =c/postgres          +
           |          |          |             |             | postgres=CTc/postgres
(4 rows)
```

**Comment by litnimax** [comment]
> Ahh no I don't, I use 'normal' droplets.

No this is a new offer from them.

So I suppose the correct patch would be connecting to database specified in --database parameter and when no database is specified only then connect to postgresql or template1.

**Comment by gdgellatly** [comment]
@litnimax that is absolutely not correct to use `-d` arg. One reason for specifying the database name is in order to create it if it doesn't exist. The only simple answer is an odoo.conf parameter similar to `dbtemplate`. 

Otherwise `createdb` in `psql` only requires credentials, so an `os call` could do it. I'm not a fan of shell calls, but this is one place it would make sense as it doesn't have any preconditions on the underlying postgres version or deployment method, although it does require psql to be installed.

**Comment by odony** [comment]
This is addressed by #12885 which proposed to introduce a `--maintenance-db` option. Not too sure about the parameter name, but we should probably refresh this PR for master, if there is enough interest.

That said, for production deployments it is actually dangerous to let Odoo create the database for you - this stuff is meant for development. Instead you should be provisioning the database with a different account, in order to ensure that the db account used by Odoo does not own the database (and is not a superuser) (1)

@litnimax if #12885 is a good match for this issue you could close it as a duplicate, and follow up there.

(1) See our [deployment security checklist](https://www.odoo.com/documentation/10.0/setup/deploy.html#security)

**Comment by litnimax** [comment]
Yes #12885 addresses the same issue.
Thanks.

**Comment by ZERO20** [comment]
Can you help me? psycopg2.OperationalError: connection to server at "" failed: FATAL:  no such database: postgres
Im using cluster db in Digital Ocean and a pool conection but I cant login
