### ISSUE TITLE
8.0 Bug: No customer on opportunity when converting lead to opportunity with existing partner

### ISSUE THREAD

**Issue by jlaloux** [odoo/odoo#3351]
If i create a Lead and i put the name of an existing partner in the company name. When i want to convert the lead to an opportunity and in the wizard i use "link to an existing customer", it will find my partner but it will not put the partner in my opportunity

**Comment by ramagea** [comment]
I am experiencing the same problem.

**Comment by Yenthe666** [comment]
Hi @jlaloux,

I've just tested this and this issue is no longer present in the latest Odoo 8.
I've created a new contact, created a new lead, converted it to prospect with the option "Link to an existing customer" and it is correctly linked:
![image](https://cloud.githubusercontent.com/assets/6352350/15772452/6e69cb3e-2971-11e6-9b03-e5c546bbe036.png)
If you still face this problem please update your Odoo codebase and it will be fixed.

Regards,
Yenthe
