### ISSUE TITLE
Paperformat QWeb Report

### ISSUE THREAD

**Issue by msteinfeld** [odoo/odoo#3367]
Hello,

my colleague meant to find some issue in the paperformat.

If you declare 0mm for the right and the left border, in the generated pdf File, 5mm borders for right and left. He think that could be a default value.

In the file /odoo/addons/report/models/report.py arguments for wkhtmltopdf are generated. Here seems to be a wrong condition:

instead of if paperformat.margin_left and if paperformat.margin_right it should be something like if paperformat.margin_left or paperformat.margin_left == 0:

equivalent for right margin.

i think there is a nicer solution for that.

If we understood something wrong, please advice us the right way :+1: 

Greets  Maik

**Comment by mart-e** [comment]
Hello,

After internal discussion, we consider this change is finally safe enough for 8.0 as setting margin to 0 is an explicit choice due to the default values. Changing this should not impact many people and especially not in a bad way.

In 8.0 we have removed the if clause at 1d99784a0a095fa522b99f3ce9cd145c35f68f52
In master we have transformed the field to float at 57707b65c95bcb013d9188faa239320548035653

Thanks for the report

**Comment by msteinfeld** [comment]
:+1:
