### ISSUE TITLE
Longpolling 503 Error 

### ISSUE THREAD

**Issue by Elbagoury** [odoo/odoo#33684]
Impacted versions:
V12 EE and V12 CE 
Steps to reproduce:
1- open runbot.odoo.com 
2- open any app and wait, it will start appearing 
![longpolling](https://user-images.githubusercontent.com/9639673/58418937-eb6e5300-8091-11e9-80ae-5d811dad5a9b.png)

**Comment by Elbagoury** [comment]
I tested it on odoo.com the Error not appearing so there is a problem in runbot server configuration
![longpolling2](https://user-images.githubusercontent.com/9639673/58420128-376ec700-8095-11e9-9ed3-00612f2f5dfe.png)
s.

**Comment by Yenthe666** [comment]
@mart-e FYI

**Comment by mart-e** [comment]
Hi,

Thanks for the report but I would not worry very much about it.
The runbot is a test instance where many people connect to it simultaneously and are quickly discarded. You may get temporary issues. It is not always reliable but it is not the purpose of the runbot either. I just tested on a community and enterprise runbot and it worked fine. Your issue was probably due to a concurrent transaction (I don't think the runbot instances are configured in multi-worker mode).

As long as it works on a "real" on instance, that is what matters :) 

Let me know if you have this issue on other services or if this is really blocking and we can reopen to investigate.

**Comment by Elbagoury** [comment]
@mart-e  but it is not a temporary issue it appears for 3 weeks now and appears on my production servers on GCP and AWS, In your opinion, what may be causing this issue..?

**Comment by mart-e** [comment]
503 means "Service Unavailable". Check your server logs to see why the request failed.
Have you checked the deployment documentation, we have a section about livechat configuration
https://www.odoo.com/documentation/12.0/setup/deploy.html#livechat
Do you have enough workers?
