### ISSUE TITLE
[12.0] website_slides: upload security issue for portal user

### ISSUE THREAD

**Issue by eversatis** [odoo/odoo#34269]
I intend to let my customers to share their projects on my website presentation. But public user can not upload their presentations after I added all portal and public users to the Upload group of the Channel.

Impacted versions: 12.0

Steps to reproduce:
Install website_slider, Create a Channel like Customer Share, Under Security Tab, I added the following user to Upload Groups: User types / Internal User, User types / Portal, User types / Public. On Portal end, the customer can see the upload button. But when I upload a slide, I encounter the following error:

Sorry, you are not allowed to create this kind of document. Only users with the following access level are currently allowed to do that: - User types/Internal User (Document model: slide.slide)

Expected behavior:
Since we can add both portal and public user to the channel upload group, the public or portal user should have the access to upload their presentation.

And I can reproduce the error on odoo runbot

**Comment by rdeodoo** [comment]
Thank for reporting the issue.

Public user is not supposed to ever see the upload button, as you can see [here](https://github.com/odoo/odoo/blame/78004338969b996d6ca0b881691d60e74ff77a65/addons/website_slides/views/website_slides.xml#L107).

About portal user, I can indeed reproduce your error. The user can see the button, the modal, can select a file, but when saving the access error appear on the modal.

@JKE-be Shouldn't the slide creation on `/add_slide` controller be done in `sudo()` in a condition check on `can_upload` and raise the access error manually if can_upload is false?
Right now, the create will always fail for portal user, since the [security file](https://github.com/odoo/odoo/blame/78004338969b996d6ca0b881691d60e74ff77a65/addons/website_slides/security/ir.model.access.csv#L3) is not allowing that (but the `upload_group_ids` does..).

**Comment by frankmiao2015** [comment]
Yes, I just had some misunderstanding concept on the portal and public user. And now all clear. And what I reported is same as your changed title. It is upload security issue for portal user. Thank you for taking care of this.

**Comment by frankmiao2015** [comment]
@rdeodoo Sorry to disturb but I just wonder how long it is normally taken to fix a confirmed bug? It seems quite a long time since the bug is confirmed and it seems no one working on it. I still do not know how the odoo official and community works but I simply need the feature resolved. Is there any one I can contact with for a paid service to resolve the bug?

Thank you.

**Comment by pedrobaeza** [comment]
@frankmiao2015 There are no SLA nor guarantee of something being fixed for community bug reports. If you have enterprise contract, you can report it through OPW (Odoo Publisher Warranty) in odoo.com/help, and there you will have an SLA by contract to receive an answer/bugfix.

**Comment by Yenthe666** [comment]
Plus since Odoo 13 is around the corner changes of these being handled soon are probably not very high.

**Comment by JKE-be** [comment]
Meanwhile a fix, you can always update security in your own instance to allow the upload for portal user.
For public user, probably not ;)

**Comment by Yenthe666** [comment]
@rdeodoo @JKE-be what is the status of this? :)

**Comment by Yenthe666** [comment]
@frankmiao2015 actually it seems to work better now in the meanwhile? My config:
![image](https://user-images.githubusercontent.com/6352350/71816608-792c0b00-3083-11ea-8dc1-7764641a9d4a.png)
![image](https://user-images.githubusercontent.com/6352350/71816618-7fba8280-3083-11ea-95f8-a46c068d238e.png)

Frontend for a non-logged in user:
![image](https://user-images.githubusercontent.com/6352350/71816659-98c33380-3083-11ea-946f-5f893b3cfd21.png)

**Comment by JKE-be** [comment]
Seems fixed according to last  comment of yenth
