### ISSUE TITLE
[12.0] Can't cancel SO even when the associated stock moves are returned

### ISSUE THREAD

**Issue by reinaldoramosarxi** [odoo/odoo#34584]
Impacted versions: 12.0

Steps to reproduce: 
- Create a SO then validate it so it creates an exit stock move
- Validate the stock move with the quantities, then return and validate the return move

Current behavior:
- When trying to cancel the SO, it shows the error "You cannot cancel a stock move that has been set to 'Done'"

Expected behavior: Seeing as the exit stock move was returned, it should be allowed to cancel the associated SO.

Tested it on demo, behaves the same way.

**Comment by pedrobaeza** [comment]
This is the expected behavior, as there are linked moves. No matter that the "final balance" is that you haven't delivered anything, because determining this can be costly and not always deterministic IMO. Any way, this version is going to be this way.

@fgi-odoo what do you think about a possible enhancement of this in future versions?

**Comment by reinaldoramosarxi** [comment]
@pedrobaeza How would one go about cancelling a Sale Order when items are returned to stock then? 
It really does look like a bug, considering the SO will just stay there as "done"... trying to explain that to customers will be pretty hard.

**Comment by pedrobaeza** [comment]
I don't think so: there has been activity, so the sales order is done, but returned.

**Comment by Yenthe666** [comment]
maybe @tde-banana-odoo can give his final saying on this.

**Comment by nhomar** [comment]
@reinaldoramosarxi 

>> @pedrobaeza How would one go about cancelling a Sale Order when items are returned to stock then?
>> It really does look like a bug, considering the SO will just stay there as "done"... trying to explain that to customers will be pretty hard.

I agree with @pedrobaeza, it is as simple as: It is a **done** SO but returned, It is an expected behavior.

Remembe once you mark something as **done** (the picking) there should not be a non-technical coming back, Why? simply answer **security**.

The border case is a technical approach **You do not want to have that traceability** on that cas that is a development and it depends on your organization ACL and internal process, IMHO it is a difficult generic implmenetation with left a huge security hole there.
