### ISSUE TITLE
Group Administration/Access Rights bypasses Allowed Companies for a given user

### ISSUE THREAD

**Issue by Gumaa** [odoo/odoo#34613]
Impacted versions: 12.0 Community

Steps to reproduce:
- Create multiple companies (for the sake of this example CompanyA, CompanyB, CompanyC,)
- Add user with group _Administration / Access Rights_ and assign him to some of the companies (not all of them - for example only Company A and B)

Current behavior:
User with given group is able to modify _Allowed Companies_ field (for all the users) and add companies that he **does not have access to**  - in this example he can extend his _Allowed Companies_  with CompanyC.

Expected behavior:
User with given group is able modify _Allowed Companies_ field of all the users but is not able to assign _Allowed Companies_ that he himself doesn't have.

I don’t know if this is expected behaviour - probably iI is considered as such. But I saw many complains about behaviour of that group and sadly no real solution. How can I make user group with privileges to create and modify other users but without exceeding his own?

**Comment by pedrobaeza** [comment]
Thanks for notifying this.

I'm afraid this is something expected, as someone with that permission is able to do that changes whatever his/her allowed companies. The permission is to modify any permission in general, not restricted to the allowed companies.

This is also coherent with the current permission system. Imagine you restrict this way. Going to debug mode and becoming superuser will invalidate that limitation.

Closing then as expected behavior.
