### ISSUE TITLE
Allow to obtain .pot without installing module

### ISSUE THREAD

**Issue by Yajo** [odoo/odoo#34793]
Impacted versions: all

Steps to reproduce: 

Imagine that you are a developer and you need to apply a single-line fix to an addon, which happens to affect somehow translations.

You'd be so happy to use gitlab/github online editors, or just to do a local commit & push, and let your CI/CD do the hard job. However, your customer needs that line translated into Swahili and you cannot translate it unless you have the updated .pot file, so you want to get it.

Current behavior: To obtain the .pot file you need to install the addon, which includes installing all its dependencies.

Expected behavior: AFAIK all translations from the .pot file come from static resources: either records generated from data files which store data in translatable strings, or from py/js code that has calls to `_()` or `_t()` respectively. I'd expect to be able to generate the .pot without installing the addon. This would speed up much deployment of the fix.

**Comment by pedrobaeza** [comment]
I think this is not so easy technically speaking, as it will require to maintain some parallel code that performs the same as current one, but @mart-e would answer better.

**Comment by mart-e** [comment]
Hi,

If it is a single line patch in static files, generating the .pot entry manually should be rather easy.

The issue is for more complex translations. You call the records generated from data file static resources but I disagree. It goes through a lot of processing, you can't just take the content inside the `<field>` tag (e.g. the HTML content is split in smaller chunks).

You could try to call `babel_extract_terms` on your python and js files manually but knowing you will miss a lot of translations that are stored on records
https://github.com/odoo/odoo/blob/8f9e1e40a32748e576084320b4f9a4c1165b7a10/odoo/tools/translate.py#L990
