### ISSUE TITLE
yaml: chained onchange methods are not run

### ISSUE THREAD

**Issue by lepistone** [odoo/odoo#3503]
Tested on v8.

To reproduce: find a record where a `fieldA` has an onchange method that changes `fieldB`, where also `fieldB` has on onchange method.
Try to write `fieldA` but not `fieldB`.
In production, both onchange methods are run.
In a yaml `!record` block, only the first onchange is run.

It looks like the onchange simulation done in `yaml_import.py` does not simulate reliably the behaviour of production code.
Maybe the new phantomjs tests are a better way to test the interface (specifically, onchange methods) ?

Thanks!

**Comment by rco-odoo** [comment]
@lepistone I confirm that the onchange stuff done in `yaml_import.py` does not reproduce faithfully what the web client does. In particular, new-API onchange methods are chained properly, while old-API ones are not.

This issue has been fixed in 9.0 by #9896.

Please reopen this issue in case the issue really needs to be fixed in 8.0. I will backport the fix done in 9.0. Thanks!

**Comment by lepistone** [comment]
Noted @rco-odoo. Thanks!
