### ISSUE TITLE
Grant Portal Access email is not being sent

### ISSUE THREAD

**Issue by makiavel** [odoo/odoo#35081]
Impacted versions: Odoo 12.0 (Community Edition)

Steps to reproduce: Sales/Ordes/Customers/Actions/Grant Portal Acess

Current behavior: The email is not sent. This happens because no outgoing email server is being used. But I have configured a working SMTP outgoing server. I can test that emails are being sent on other occasions. If I manually select the outgoing mail server on Configurations/Technical/Emails I see that the email is being sent correctly.

Expected behavior: The customer should receive a message on the email configured in the account.

Video/Screenshot link (optional): 
![image](https://user-images.githubusercontent.com/1656861/61665639-64bea680-accd-11e9-8a3b-0595d59d371f.png)

![image](https://user-images.githubusercontent.com/1656861/61665666-7738e000-accd-11e9-9274-92e9aaad696e.png)

**Comment by pedrobaeza** [comment]
You should have something misconfigured in your system, as "Outgoing mail server" is not needed to be filled. If empty, it takes the top priority outgoing server. You probably have several outgoing servers, and the most priority is not correct (localhost?), and that's why you get this problem.

Any way, it's not a problem of Odoo, but misconfiguration. Closing then.
