### ISSUE TITLE
[11.0] point_of_sale: ir.rules corrupted by orm.cache at evaluation of search account.journal

### ISSUE THREAD

**Issue by hugho-ad** [odoo/odoo#35123]
Impacted versions:
11.0 maybe 12.0

Steps to reproduce:
- Create an ir.rule like
![image](https://user-images.githubusercontent.com/10233975/61739354-e0facd80-ad51-11e9-971a-82d57607381e.png)
- Open a new session on pos under a user different than admin (make sure access to pos and account as advisor user in order to see all journals)
- Create a pos.order
- Go back to all orders (without closing pos session)
- make a return of products of the pos.order
- Use the button payment
![image](https://user-images.githubusercontent.com/10233975/61739538-3c2cc000-ad52-11e9-8bd5-1ffba72a0268.png)
- On the wizard will list all journals available on the pos config of the session
- Finally, go to Account/Configuration/Accounting/Journals

Current behavior:
- Can't see all journals
- Clean the cache by changing the name of a ir.rule e.g 
   test ir.rule > test ir rule
- Go back to all journals and you will see all journals correctly

Expected behavior:
ir.rules not be corrupted by orm.cache

Replicated at http://569884-11-0-7acdce.runbot23.odoo.com

This is the line that introduces the issue
https://github.com/odoo/odoo/blob/bdfed675044e5e7b65621ae875392395076a0108/addons/point_of_sale/models/account_journal.py#L19-L24
But MUST be fixed properly from ir.rule 
Video/Screenshot link (optional):

https://youtu.be/rXRe6wDHFMY

OPW 2041667

**Comment by hugho-ad** [comment]
FYI I open following pr
https://github.com/odoo/odoo/pull/35125

**Comment by pedrobaeza** [comment]
Why are you using such rule?

Do directly `[('id', 'in', [25, 26,...])]`

**Comment by hugho-ad** [comment]
I'm using that rule, because of I wan to trigger the search at  
https://github.com/odoo/odoo/blob/bdfed675044e5e7b65621ae875392395076a0108/addons/point_of_sale/models/account_journal.py#L19-L24

That rule could be change for a x2many field e.g.
```
user.sale_team.journals_ids
```

Any way, to poing here is how is corrupted the ormcache with a wrong domain evaluation, as explained  on
https://github.com/odoo/odoo/pull/35125

**Comment by pedrobaeza** [comment]
Not sure about the corruption you mention. @rco-odoo will tell.

But this can be for sure modeled other way for avoiding that consuming evaluation. An stored m2m for example.

**Comment by moylop260** [comment]
In fact,
@hugho-ad is talking about a m2m field

Let me explain it using the following table:

| No | operation | field                                                 | ids     |
|----|-----------|-------------------------------------------------------|---------|
| 1. | write       | user.sale_team.journals_ids                           | 1,2,3,4 |
| 2. | write     | session_id.config_id.journal_ids                      | 1,2     |
| 3. | read      | user.sale_team.journals_ids                           | 1,2,3,4 |
| 4. | read      | user.sale_team.journals_ids.with_context(session_id=X) | 1,2     |

https://github.com/odoo/odoo/blob/0375c0174da4f6489ecbace7740fdccec106b8e1/addons/point_of_sale/models/account_journal.py#L18-L24

Then using a `ir.rule` evaluating `user.sale_team.journals_ids` using a view with the context `session_id` assigned so odoo will have cached from orm.cache the ids 1,2

 - https://github.com/odoo/odoo/blob/0375c0174da4f6489ecbace7740fdccec106b8e1/odoo/addons/base/ir/ir_rule.py#L64-L65
Since that context is not part of the cached key.
But the result is affected because of the context.

Then, next time that the user wants see all journals it is limited to 1,2 (instead of 1,2,3,4) because a wrong result was cached.

# For version 12.0 

Version 12.0 adds a new method to use part of a context in the key of the cache:
 - https://github.com/odoo/odoo/blob/ffe58a56bf78f37d8b62e028b262c7e7b42f6e1a/odoo/addons/base/models/ir_rule.py#L72-L75

However, here the issue is reproduced too since that the method is not using just the context cached, in fact, it is using full context too.

Do we explained it better?

**Comment by Julien00859** [comment]
Ok... Sorry for my dumbiness but I ultimately got the full picture. Doing `search`es in record rule is not supported in standard Odoo, there are multiple problem doing it like possible infinite recursion, invalid context propagation, wrong cache, ...

Please find a workaround that does not involve putting searches in ir.rules.
