### ISSUE TITLE
Website main menu compute is broken

### ISSUE THREAD

**Issue by simahawk** [odoo/odoo#35149]
**Impacted versions:** 10, 11, 12, master

**Steps to reproduce:**

1. create a new main menu and assign it to current website
2. check the menu used on the website

**Current behavior:**

You still see the old one

**Expected behavior:**

You must see the new one as it should be computed (which is kind of dangerous IMO).

Bad computation happens here:

https://github.com/odoo/odoo/blob/master/addons/website/models/website.py#L126-L129

```py
    def _compute_menu(self):
        Menu = self.env['website.menu']
        for website in self:
            website.menu_id = Menu.search([
                ('parent_id', '=', False), ('website_id', '=', website.id)
            ], order='id', limit=1).id
```

It should be explicitly ordered by `id DESC` instead of just `id` otherwise is impossible to replace the menu w/out deleting the others.

I can open a PR if you want.

**Comment by pedrobaeza** [comment]
I agree. @JKE-be what do you think about this?

**Comment by JKE-be** [comment]
Initial idea is to have only one main menu by website.

If you want another that the current, your update the current and not create a new one.

Take sense no ?

**Comment by pedrobaeza** [comment]
Is the main one overwritten on module update?

**Comment by JKE-be** [comment]
since v12 menu is bootstrapped at creation of the new website.

We duplicate the default menu (which add /shop, blog, ...)

https://github.com/odoo/odoo/blob/master/addons/website/models/website.py#L193

**Comment by simahawk** [comment]
> Initial idea is to have only one main menu by website.
> 
> If you want another that the current, your update the current and not create a new one.
> 
> Take sense no ?

no, because - for instance - you could have several menu for the same website to be used in different context (eg: a sidebar nav) or you simply want to stay secure and avoid any injection of new menu items by odoo modules or third party modules at module install or update

Also, every time you make an update the menu are re-created if you update base (at least until 11.0).

Furthermore, now this duplication behavior creates duplicated records all around included homepage records w/out any use even for the existing default website (but this another story).

In any case, to me the main menu of the website should be in full control via configuration hence I'd remove the computation and make the field explicit and stored. If you want to keep it computed, at least compute it properly ;)

**Comment by JKE-be** [comment]
> Furthermore, now this duplication behavior creates duplicated records all around included homepage records w/out any use even for the existing default website (but this another story).

Ok, what do you suggest instead ? 

Seems like the critic is easy, how do you suggest to implement a multi website feature without impact other website without duplicate a minimum of record ? 

Open issue is easy, why not open a pr to allow the fix/merge easily

about your "secure menu", it will no work btw

On creation of menu, we create of submenu, we create it in the menu too


If you really want a "secure"/"distinct" menu, you should create a new one like you did now, and t-call this one in your template instead of website.menu_id  (what we do on odoo.com)

**Comment by pedrobaeza** [comment]
Maybe the problem @simahawk has in on v11, but extending to v12 seeing the same code?

Indeed in v12 there's seems to not have a better way right now.

**Comment by simahawk** [comment]
> Ok, what do you suggest instead ?

I said "this is another story" -> not the place to discuss this. We can open another ticket IF is there any interest (**).

> Seems like the critic is easy [...] Open issue is easy, why not open a pr to allow the fix/merge easily

Dude, please, read my initial message carefully. I said "I can open a PR if you want."
I have the fix for this small issue and it's working. Point is that many times you guys assume the position of "yeah, is a feature" or "yeah it works for all our simple cases so its good" and then we waste time in opening PRs that just get ignored or closed because you think you already addressing the best case. I'm not complaining, I'm raising an issue.

That being said, do you agree w/ me on this fact: the computation - as is - it's broken? (**)

> If you really want a "secure"/"distinct" menu, you should create a new one like you did now, and t-call this one in your template

Eh, this is what I do most of the times included this one.

> instead of website.menu_id (what we do on odoo.com)

and **this is not a good point**: why on heart shall I not rely on something that should reliable (the main menu of the website) only because its computation is broken?

**Comment by rdeodoo** [comment]
> we waste time in opening PRs that just get ignored or closed

I don't think that's no more true in website, we try to take care of every issues/PR related to it as quick and objective as possible. Just filter those by `Website` tag to figure.

> because its computation is broken

Because it does not fit your need doesn't mean it is broken.

Anyway, I don't think changing the order would please everyone, no? What if an user still want the first menu to be used, not his second (the opposite of you), since the second menu is used elsewhere.

But I get your point. If something need to be done, that would probably be in master. Why not ordering by sequence? That way you could easily manage what menu will be used in the compute by changing its sequence.

**Comment by simahawk** [comment]
> Because it does not fit your need doesn't mean it is broken.

@rdeodoo is broken because if you always get the same menu there's nothing to compute IMO :)

Yes, as a patch, ordering by sequence makes more sense.

IMHO it would make even more sense to remove the computation and make it frozen: you should declare which menu you want on your website specifically w/out relying on "black magic".

What do you think?

**Comment by JKE-be** [comment]
I think that if you delete your main menu from website 1, and create a new one, you will never understand that without setting your new menu on the website, it will not works.

While the compute let you select automatically the menu of the current website whatever the ID.

**Comment by rdeodoo** [comment]
Well, we all came to an agreement then :-)

>  I said "I can open a PR if you want."

That would be more than welcome, order by sequence on master as IMP, ensure it does not change any current behavior but just let the possibility to affect the compute result if you play with sequence

**Comment by simahawk** [comment]
> I think that if you delete your main menu from website 1, and create a new one, you will never understand that without setting your new menu on the website, it will not works.

That's the point. Actually you have to tell ppl: hey guys, if you want to use a different menu: nuke the original one. 

> While the compute let you select automatically the menu of the current website whatever the ID.

Sorry, but is exactly the opposite: the compute does not allow you to select anything.
Being computed, it does what it wants.

> Well, we all came to an agreement then :-)

I'm not sure yet :smile: 

> 
>     I said "I can open a PR if you want."
> 
> That would be more than welcome, order by sequence on master as IMP, ensure it does not change any current behavior but just let the possibility to affect the compute result if you play with sequence

To me this could still be more error prone from user perspective as a simple dragging in the backend UI will screw your menu on the frontend w/out even noticing it.

If it goes to master I propose to store menu_id explicitly. By default, you can get the computed one by sequence. Would it work for you?

**Comment by pedrobaeza** [comment]
I think here "Explicit better than implicit" zen  is more suitable.

I prefer to have a many2one specifying the main menu on `website` object, with `ondelete=restrict` for avoiding incidental delete.

**Comment by JKE-be** [comment]
To me this could still be more error prone from user perspective as a simple dragging in the backend UI will screw your menu on the frontend w/out even noticing it.

Is it a joke ? 
You are in the backend, in the menu Website, Editing Menu from your website, and you will be not aware that is change something in front end ? 

So basically when you update the price in the backend, we should maybe show a toast to say 'be aware, your price is updated on the website too"

**Comment by rdeodoo** [comment]
Also remember that menu in backend is an advanced technical feature, only shown in debug mode, it is not like a lambda user would do something by error without knowing it.

**Comment by simahawk** [comment]
As @pedrobaeza said: explicit is better than implicit.

> You are in the backend, in the menu Website, Editing Menu from your website, and you will be not aware that is change something in front end ?

Frankly, managing the main menu of a website by hidden computation IS a joke.

> Also remember that menu in backend is an advanced technical feature, only shown in debug mode, it is not like a lambda user would do something by error without knowing it.

Which is another issue IMO: if I  have the powers to manage a website I should have the powers to set/change the menu of my website.

Doing this w/ an explicit field (w/ proper default) will always be better than doing it under the hood, assuming that your assumptions are always the right one in terms of using experience.
But don't worry, we gonna have yet another new addon in OCA to cover this design flaw :)

**Comment by pedrobaeza** [comment]
If it serves, some of my advanced customers has changed the order of the pricelists several times and then complain about the problem on websites, even when they were warned on teaching, but it was so long ago...

So I still prefer explicit better than implicit.

**Comment by pedrobaeza** [comment]
@simahawk please relax your tone, because we are all in the same wave: to improve Odoo website. @JKE-be, @rdeodoo and all Odoo website team are doing a great work and they are the most responsive in issues/PRs in Odoo, so let's try to expose facts and thinkings, and get to a possible agreement.

**Comment by rdeodoo** [comment]
> Which is another issue IMO: if I have the powers to manage a website I should have the powers to set/change the menu of my website.

You can manage your website menu in the frontend. We try to avoid the user to go in the backend as much as possible, ideally everything should be possible to be done in frontend. Cf page properties, field edit in frontend etc.
`Website` should remain a website builder app, as much standalone as possible, even if the module is part of an ERP. That's why menu should remain an hidden menu (so is website.page) and the 'bug' you describe here is just a limitation for advances cases.
Hopefully, we have debug mode for advanced, technical user.

Remember that our website module is firstly build for the basic user from the small shop from your street.
He will use one website menu, the default one. This debate is a really advanced one.

I don't think we can go much further here given our respective position if no one is willing to understand eachother.

I do understand you want to be able to impact the compute result. I suggested the sequence imp.
But you don't understand our POV to keep it simple for the lambda user which is our main target. Yes, odoo is an ERP but remember our website module should be seen as a standalone website builder, built on an ERP ecosystem.

We are in a weird position as website, between ERP quite 'complexe' backend and an easy to use frontend (at least, that's what we try to do).

We will discuss this internally tomorrow and come back to you to what we are open to accept on master as imp.

Either with sequence, M2O with default as current compute or nothing.

**Comment by simahawk** [comment]
@JKE-be @rdeodoo I apologize if I sounded rude. I had no intention to say that you guys are doing a crapy work. You have done a lot of progress here and this deserves kudos.

At the same time it would be nice that if someone raises an issue you don't get as an answer "show me the code or shut up" or "your proposal is a joke". I admit, this pissed me off a little bit :sweat_smile: and is really connected to what I mentioned here https://github.com/odoo/odoo/issues/35149#issuecomment-514738597.

Anyway, please, let's start from scratch :white_flag: 

I do understand your POV but it seems you don't get ours. What I'm proposing (stored field + default compute) goes exactly in the direction of satisfying all the needs.
Even more, I'm saying: I can implement it and propose a PR.

So, yes please, think about it and let me know.

**Comment by rdeodoo** [comment]
Let's raise the :white_flag:.

We will discuss this and come back to you ASAP.
Indeed, your suggestion is not bad, we just need to choose between both, note that with it, the menu_id should be in debug mode on website view form (which is already in debug mode anyway).

**Comment by rdeodoo** [comment]
ASAP didn't turn out as expected :grimacing: 
Anyway, as a quick summary, you would like the `website.menu_id` field to be a many2one field that can be set manually.
We, at Odoo, prefer to keep it as such, as you say, an `hidden computation`.

If we read your issue report, your need was to fix that computation:
> It should be explicitly ordered by id DESC instead of just id otherwise is impossible to replace the menu w/out deleting the others.

Which was done in 13.0 as we don't order by `ID` anymore.

Since your initial issue is resolved, despite not agreeing on the improvement you suggested later, I will close this one.

Note that I remain on my position explained [here](https://github.com/odoo/odoo/issues/35149#issuecomment-514992575): This is a super advanced need, even if the way the code is done is not convincing you, you can do what you need in debug mode.
