### ISSUE TITLE
Menu Problem when scrolling down

### ISSUE THREAD

**Issue by bahram-css** [odoo/odoo#35320]
Impacted versions: 12.0

Steps to reproduce: When Opening sub menus and scrolling page down, menu with sub menus doesn't close.

Current behavior: The menu doesn't close.

Expected behavior: The Menu to be closed.

I think problem is on javascript SCROLL event.
I try it on Odoo runbot.

Video/Screenshot link (optional):
![Screenshot from 2019-07-31 13-16-35](https://user-images.githubusercontent.com/51145639/62198178-6d327380-b396-11e9-94f1-967985edb0e5.png)

**Comment by pedrobaeza** [comment]
I don't consider that it should be auto-closed. That complicates code without too much gain.

**Comment by bahram-css** [comment]
I don't mean it's auto closed. It doesn't close even we click on it. As you see in the image, three sub menus are open.

**Comment by pedrobaeza** [comment]
And how did you get to that situation? Scrolling up and down?

**Comment by bahram-css** [comment]
When opening sub menus and scrolling down.

**Comment by bahram-css** [comment]
https://youtu.be/H2sRXHxHM-M

**Comment by bahram-css** [comment]
@pedrobaeza 
Please see this video.

**Comment by pedrobaeza** [comment]
Issue tagged

**Comment by bahram-css** [comment]
Thank you

**Comment by rdeodoo** [comment]
Indeed, we have a custom code to close the dropdown on scroll/windows update which removed the `show` class from the dropdown menu but not from the dropdown's content. 
This is why it remains open.

Afterward, since there is a mismatch regarding the `show` class between those 2, it remains opened without possibility to close it.

Fix coming
