### ISSUE TITLE
Password field can be shown

### ISSUE THREAD

**Issue by nguyenductamlhp** [odoo/odoo#35429]
Impacted versions:
12.0
Tested on [http://578888-12-0-431b7d.runbot26.odoo.com](http://578888-12-0-431b7d.runbot26.odoo.com)

Steps to reproduce:
- Create Incomming mail server record
- Edit record
- Right click on field *Password*, inspect field
- Edit type of field from `password` to `text`

Current behavior:
Password is shown

Expected behavior:
Display `*******` instead of original password 

Video/Screenshot link (optional):
[Video](https://www.youtube.com/watch?v=CldfOE6CGkg&feature=youtu.be)

**Comment by pedrobaeza** [comment]
@odony what do you think about this?

**Comment by odony** [comment]
We don't consider this a bug: we currently have no other way than storing the cleartext passwords of the servers as Odoo will need to authenticate with it - we can't hash it like other passwords. Users can use API keys rather than real passwords, but it carries roughly the same risk.

However Incoming/Outgoing mail servers are only accessible to database administrators, so only them will be able to set or read those passwords - they should be safe from other eyes. Also note that admins can run server actions and execute arbitrary SQL code in the database, so there is no way to hide the actual passwords from them anyway, even if we fake it on the form view. If we did this it would not be real security, rather pseudo-security through obscurity, which we generally dislike.

If admins are concerned that someone could walk up to their screen and play with their session they should really think about auto-locking their sessions.

**Comment by Yenthe666** [comment]
@odony have there been any thoughts about hashing passwords with key(s) that are stored on the OS? I'm curious about some insights from your end. :)
