### ISSUE TITLE
Product Attribute Error on import

### ISSUE THREAD

**Issue by master041** [odoo/odoo#35477]
Impacted versions:
odoo 12.0
Steps to reproduce:

Current behavior:
while importing products if i choose attributes that i created by myself it gives an error that the attribute value does not exist although it exists.
in the same way if i choose the attribute and it's value that is in odoo by default it works without error
Expected behavior:
if I create My own attributes and values i should be able to import product with those attributes.
Video/Screenshot link (optional):
![sc](https://user-images.githubusercontent.com/16923209/62519759-79f51280-b841-11e9-8cab-3f77df6884fd.png)

**Comment by pedrobaeza** [comment]
This is because you have to reference them through an external or internal identifier, or check also the translations. For further questions, you should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.
