### ISSUE TITLE
[12.0] Wrong dependency name

### ISSUE THREAD

**Issue by eltantillo** [odoo/odoo#35470]
https://github.com/odoo/odoo/blob/dc0630833b2a43373b9da45cf310039510fd2f7d/addons/sale/models/sale.py#L39

I think this should be order_line.price_subtotal instead of order_line.price_total

**Comment by sswapnesh** [comment]
Is there any case when it is not working Properly because of this?

**Comment by eltantillo** [comment]
Not in odoo native, but I'm working in a development that adds a freight cost to each sale.order.line price_subtotal, and it's not adding in the sale.order amount_untaxed. Thought if I make this change it works fine.

Is there a reason I'm missing for this depend?

**Comment by pedrobaeza** [comment]
That depends is correct, because all the values are chained in standard code, so if `price_total` changes, that means that `price_subtotal` has changed as well.

If in your custom code, you need to react to the other field, it's as easy as overwrite the method adding the depends, and calling super:

```python
@api.depends('order_line.price_subtotal')
def _amount_all(self):
    return super()._amount_all()
```

Closing as answered.
