### ISSUE TITLE
Giving an error of wizard model when i try to delete Manufacturing order.

### ISSUE THREAD

**Issue by goyanipankaj** [odoo/odoo#35548]
Impacted versions: Odoo-11.0 Enterprise

Steps to reproduce: I have created MRP order and after check availability and plan the process.

Current behavior: Giving an error when i try to delete the MRP order

Expected behavior: i think no giving an error of wizard record.

Video/Screenshot link (optional): Attached screenshot

![22](https://user-images.githubusercontent.com/8874012/62683040-30402f80-b9db-11e9-84e7-6c92ea8e0f66.png)
![111](https://user-images.githubusercontent.com/8874012/62683041-30402f80-b9db-11e9-8f7c-9066c39b1efe.png)

**Comment by pedrobaeza** [comment]
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by goyanipankaj** [comment]
Hi,
I will try to reproduce in runbot and update surely.
Thanks.

**Comment by goyanipankaj** [comment]
Its a transient model issue so i have run the scheduler its resolved.
and i am close the ticket
Thanks.

**Comment by goyanipankaj** [comment]
Closed!!!!
