### ISSUE TITLE
I custom a web client extend AbstractAction,when I use do_action method run not as my expect

### ISSUE THREAD

**Issue by iaminvictus1993** [odoo/odoo#35546]
Impacted versions:12

Steps to reproduce:

Current behavior: when i  first run into the custom web client. I can use do_action correctly.but after I did some options in other view, I go back to the custome web client. do_action cant run well

**Comment by pedrobaeza** [comment]
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by iaminvictus1993** [comment]
thanks, its  third jquery plugin  cause this. i had a wrong way to use it
