### ISSUE TITLE
Unable to set return path with website.published.mixin

### ISSUE THREAD

**Issue by Yenthe666** [odoo/odoo#35621]
Impacted versions: All

Steps to reproduce:
1. Create a new model (for example `article`) and inherit `website.published.mixin`
2. Create a new app, menuitem and view for your new model
3. Add the `website_published` field on the form with a widget:
```
<button class="oe_stat_button" name="website_publish_button" type="object" icon="fa-globe">
    <field name="website_published" widget="website_button"/>
</button>
```
4. Click on the button to open the record in the frontend.
5. Now click on the "edit in backend" button from the frontend

Current behavior:
You're redirected to the backend and the correct form view with the right record is loaded within the website module

Expected behavior:
It would be great if you'd be able to specify the module in the `website.published.mixin` model and that Odoo would redirect the user to the backend form view in the correct module. This would mean that you're able to directly go from the current record (form view) to the tree view with all other related records. This has two benefits:
1. You're directly in the right module
2. You're directly able to go to the list view and continue editing records without having to go back from the website module to your module and continue from there on.

**Comment by Yenthe666** [comment]
@rdeodoo what do you think of this suggestion/idea? Could you have a look please? :)

**Comment by rdeodoo** [comment]
I think this could have a value, especially since `website_slides` has his own module now but edit in backend goes in website module, it does not really make sense indeed.

But for the list view, this can already be done if you specifiy an `act_window` to the 'Edit in backend' link.

This can be done as for ecommerce (see [here](https://github.com/odoo/odoo/blame/8becb17b8a3aa18b92629c4ddd33630ea4b1444e/addons/website_sale/views/templates.xml#L457)), it will display the list view link in the breadcrumb.

**Comment by Yenthe666** [comment]
Yeah but what if you don't specify an `act_window` in the frontend record though and have it auto generated from the backend? For example:
```
    @api.multi
    def _compute_website_url(self):
        super(YourClass, self)._compute_website_url()
        for record in self:
            record.website_url = "/example/%s" % slug(record)
```

This will work perfectly fine with a backend/frontend navigation that is auto generated and there is no XML code by default. As you've mentioned with your reference to `website_sale` you can set an action so that you have the breadcrumbs to go back to the list of records. However, you're still in the `website` app, not in your custom app, not even if the action definition is outside of the `website` module.
I think we should have an option to override a new function in the model `website.published.mixin` which sets the navigation through Python code. What do you think @rdeodoo?

Could you also point me to where in the code the trigger is set to return to the backend?

**Comment by Yenthe666** [comment]
Sidenote for myself to remember: Tutorial creating button to (un)publish content.

**Comment by rdeodoo** [comment]
> 3. Add the `website_published` field on the form with a widget:
> 
> ```
> <button class="oe_stat_button" name="website_publish_button" type="object" icon="fa-globe">
>     <field name="website_published" widget="website_button"/>
> </button>
> ```

Btw in backend, you could/should use the `is_published` field from the mixin, no reason to use the `website_published` which is only a related to `is_published` when read outside a website context. But that's not that critical to use `website_published`, it just goes through the related for nothing.


>However, you're still in the website app, not in your custom app, not even if the action definition is outside of the website module.
I think we should have an option to override a new function in the model website.published.mixin which sets the navigation through Python code. What do you think @rdeodoo?

Yep, that's what I said, and it is probably a need for Odoo core since `website_slides` got moved outside website and has his own module (eLearning), but you are still redirected to website backend where slide has nothing to here for a regular user.

Imo what should be done is not to create a new function to specify it, but to redirect inside the module where the `act_window` was defined. It would require to investigate if that could be implemented and if this behavior should not be limited when coming from a frontend context.

> Could you also point me to where in the code the trigger is set to return to the backend?

The code redirecting to the backend is [this one](https://github.com/odoo/odoo/blame/7c5b4cbc03f2e62439a8af1928ccdca5f38316ca/addons/website/views/website_templates.xml#L423) and it is handled by the JS [here](
https://github.com/odoo/odoo/blame/7c5b4cbc03f2e62439a8af1928ccdca5f38316ca/addons/web/static/src/js/chrome/action_manager.js#L215).

**Comment by Yenthe666** [comment]
@rdeheele thanks for the feedback and the tips! Wouldn't it be easier if we could just modify the `return_label` and that Odoo would handle it accordingly? We already have the `model`, `id` and `action` in place with the right values. If we can set/modify the `return_label` and if Odoo then opens the right module we're good to go, no?
Looking in the current V12.0 code it is always set to website and there is no JS/controller logic for it right now. See https://github.com/odoo/odoo/search?l=XML&q=return_label

What do you think about this approach?

**Comment by rdeodoo** [comment]
Hi @Yenthe666 
First, `return_label` is not working since 8.0. This dead code will be removed with https://github.com/odoo/odoo/pull/36325
Second, about this issue, it actually works already, I was not aware of it but as @JKE-be showed me, you just need to set another `menuitem` on the link ([here](https://github.com/odoo/odoo/blob/86809804f98b3891b9c002f82eedcbb4c7691e9c/addons/website/views/website_navbar_templates.xml#L167)).

It will land in the menuitem module. By default it uses the website one so you land on website. But the code support `menu` in stable right now as you can see on the line I linked.

This is also improved with https://github.com/odoo/odoo/pull/36325, I will let you have a look.

Can we consider this one closed?

**Comment by Yenthe666** [comment]
Thanks for getting back to me! I didn't know about this either. I'll look into this soon and I'll test it. Along with your PR for improvements in SaaS 12.5 I guess we can close this off :)

Thanks for the great work!
