### ISSUE TITLE
The invoice Point of Sales label is not translated

### ISSUE THREAD

**Issue by CarlesAntoli** [odoo/odoo#3566]
Impacted versions:

8.0 and above

Location error:
Line:  1074
Error: 

label: 'Invoice', 
I should be -> label: _t('Invoice'),

**Comment by Yenthe666** [comment]
Hi @user,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
This issue has been fixed in Odoo 9 and up though.

Regards,
Yenthe
