### ISSUE TITLE
[master] account: Impossible read list view of journals   account.journal(2,).belongs_to_company

### ISSUE THREAD

**Issue by nhomar** [odoo/odoo#35881]
Impacted versions:

master** (not tested in other version).

Steps to reproduce:

- GO to accounting, 
- Journal menu.

Current behavior:

![image](https://user-images.githubusercontent.com/338634/63408978-d9146480-c3b5-11e9-840c-3a10fbab6dd2.png)

Expected behavior:

Read it.

Video/Screenshot link (optional):

**Comment by nhomar** [comment]
Tested on this  runbot.

http://595604-master-242b60.runbot13.odoo.com/web#action=523&model=account.journal&view_type=kanban&cids=1&menu_id=552

**Comment by mart-e** [comment]
Hi,

Sorry but we do not accept master issues as it is not a supported version.
It is changing too fast, especially lately with all the rush merging. The kind of bugs reports will be outdated very quickly.
We will create the saas-12.5 version in a few days (once everybody has merged its refactoring). In stabilisation period, it will make more sense to report issues.

For instance, we just merged the big refactoring at 9920f20e4c7753bc17bea71dea3a90f7de687196 which may be the reason. We do expect errors due to this one and we will fix it soon.
If it is still present after the freeze, then it will be worth a report.

PR for master are accepted though, but keep in mind it also gets outdated very quickly.

**Comment by nhomar** [comment]
@mart-e We are early testing, if you think just ignore the, we found ugly conceptual problems and they are just for our **open*+ indexing purposes, If you want don't bother closing them (I can do it efficiently following the PRs).

Thanks for point me out when this was fixed. (it help me with the huge testing process we are doing).

**Comment by mart-e** [comment]
As discussed privately, master issues about functional behaviour with a good analysis of the problem like #35841 useful and can be kept open. The tracebacks like this one is due to very recent changes and is likely to be fixed very early. Don't bother opening issues about this, wait the saas-12.5 release to fix these ones.
Thanks again for the testing.
