### ISSUE TITLE
A disabled website-specific view will never get user modifications

### ISSUE THREAD

**Issue by Yajo** [odoo/odoo#35905]
Impacted versions: 12.0

Steps to reproduce:

1. Using website 1, browse to /shop and open one product.
1. Edit.
1. Alter the text you find in the "Add to cart" button. Let's write "Put in cart".
1. Save.
1. You can see the button says "Put in cart".
1. Go to settings > Technical > Views and find the view with key website_sale.product and website_id=1.
1. Set it to active=False.
1. Using website 1, browse to /shop and open the product page you opened in step 1.
1. You can see it says "Add to cart", which is OK because you disabled the view.
1. Edit.
1. Alter the text you find in the "Add to cart" button. Let's write "Put in cart".
1. Save.

Current behavior: It says "Add to cart"

Expected behavior: It should say "Put in cart".

The problem is in the COW system, which doesn't activate a view when it's being modified and reused: https://github.com/odoo/odoo/blob/472bfdca561fcdf3a535c4c92cadf0ede1d4fab4/addons/website/models/ir_ui_view.py#L52-L64

I don't know if the proper fix goes into `save()`, `write()` or in the JS code that calls `save()` in `ir.ui.view`, so I opened the issue instead of a PR.

@Tecnativa

**Comment by pedrobaeza** [comment]
@JKE-be discovered while we explore more and more new COW system.

**Comment by JKE-be** [comment]
At first view:

```python
if not website_specific_view.active and 'active' not in vals: 
    vals['active'] = True
```

[here](https://github.com/odoo/odoo/blob/472bfdca561fcdf3a535c4c92cadf0ede1d4fab4/addons/website/models/ir_ui_view.py#L63) should fix it.

**Comment by Yajo** [comment]
I guess... I'm just afraid if that would get in the way when editing a `ir.ui.view` record from the backend (under Settings).

**Comment by rdeodoo** [comment]
COW is never triggered in backend, see [this line](https://github.com/odoo/odoo/blob/472bfdca561fcdf3a535c4c92cadf0ede1d4fab4/addons/website/models/ir_ui_view.py#L40). only when in a frontend context (`website_id` set)

**Comment by rdeodoo** [comment]
If I am correct:

1. This problem can only happen with a base view, as an inactive specific child view would 'hide' its generic active counterpart and you would not be able to edit that same element since it would not be displayed.
2. This problem can only happen if you go in debug in technical > views. I don't like to handle such behavior as we could find infinite issues like this, mostly when playing with `inherit_id` field, it will break everytime.

I confirm the fix from @JKE-be works, not sure we should add it to COW method as it is already complex and this flow is not possible without going through backend technical. Plus it only concern base views.

**Comment by rdeodoo** [comment]
Unless this can be reproduced from the front-end, this won't be considered as a bug.
Indeed, when going into `technical > views` in debug, there is multiple ways to break your website (changing inherit_id, changing website_id..) and we don't want to support it.
