### ISSUE TITLE
Normal user can Improve permissions by himself 

### ISSUE THREAD

**Issue by camel007** [odoo/odoo#36151]
## Impacted versions:
12.0 

## Steps to reproduce:
User A has "access rights" permission, but without settings permission. So A can not improve himself with "settings" permission, but A can create a new user with "setting" permission.

Same with this description:  [Administration, "settings" and "access rights"](https://www.odoo.com/forum/help-1/question/administration-settings-and-access-rights-7270#answer_53117)

## Expected behavior:

User with "access rights" permission cannot create new user with "setting" permission

**Comment by Yenthe666** [comment]
Well, you shouldn't give people those rights if you don't trust them no? @odony could you please give an official response on this as it is security related? ::

**Comment by camel007** [comment]
@Yenthe666  Thanks for you reply  

But it is not appropriate for a person to give permission to go beyond himself.

**Comment by odony** [comment]
As other people have pointed out in the forum post referred by the OP, this is not considered a bug. Some users may need to manage access rights of other users, but they don't want to see the advanced settings menus if they don't need to use them, because they want to avoid mistakes.

That does not mean that these users have lower access rights, they are full administrators too, and should be trusted to the highest level. In many cases in Odoo, groups are used also for usability reasons, not only for access control.

In fact I'm not even sure we explicitly block the case where a user with "Access Rights" would give themselves the "Settings" group. If it does not work it may simply be a side-effect of the transition between the two groups. Either way the point of having "Access Rights" management in Odoo is to be able to change the rights of all users.
