### ISSUE TITLE
XML id in compute and stored function did a module install crash

### ISSUE THREAD

**Issue by Sirfanas** [odoo/odoo#36202]
## Impacted versions 12.0 (Maybe previous too ?)
Actually using latest Docker image (Release 20190816)
### Steps to reproduce:
Create a new fresh module, let's call it my_module
Create a data file that create a record (a product.category for exemple)
```
<record model="product.category" id="my_category">
   <field name="name">My Category name</field>
</record>
```
Create a python file that inherit (or create) any model, create a field as computed and stored
```
my_awesome_field = fields.Char(_('My field'), compute='_cpt_my_awesome_field', store=True)

def _cpt_my_awesome_field(self):
    for record in self:
        my_categ = self.env.ref('my_module.my_category')  # Crash here at module installation
        record.my_awesome_field = 'My categ is %s' % (my_categ.name)
```

Of course make sure your xml data file is loaded in __manifest__ and make your python code imported too !

### Current behavior:
At installation it get a big crashes because of an external id not found.
I think this is because the python file is loaded before XML

### Expected behavior:
To install itself without crashing and compute my fields

### Solution idea
I'm actually conscient this is impossible to load XML after python, because some XML need Python first (if new field is added for example) but maybe it can be usefull to add something like data_before_python in __manifest__ dict, so specified file are loaded before Python ?

**Comment by pedrobaeza** [comment]
This is a known limitation of the ORM, the same as putting a default value which points to an XML-ID of the same module. But we have here the chicken-egg problem as you have already pointed: if we switch order, models are not yet loaded, so XML files won't be loaded as well. Deferring computed fields computation will lead also to side effects. Your idea is not possible as well, as you will have some models available and others that don't, so it will generate more confusion and not valid for usual use cases, where the model you are declaring data for is also declared in the same module. Thus, you have to do other thing for the purpose you want to achieve, for example creating 2 modules, the first one with the data, and the second with the computed.

Closing there as not solvable due to the reasons above.
