### ISSUE TITLE
[11.0] mail.activity: user: own only ir.rule not working

### ISSUE THREAD

**Issue by hugho-ad** [odoo/odoo#36210]
Impacted versions:
12.0

Steps to reproduce:
- Create an internal user
- Create an employee-related with the above user
- Assing it a department with a manager different that the new user
- Create a leave
Current behavior:
The leave is created successfully 
Expected behavior:
An Access error must appear because of the ir.rule 
https://github.com/odoo/odoo/blob/412117c2a789a24191cda040614d01fe290e77cc/addons/mail/security/mail_security.xml#L43-L52
![image](https://user-images.githubusercontent.com/10233975/63898908-6ceebd80-c9c0-11e9-9998-9376cef498f6.png)
But nothing happen

There is not any sudo statement at creation of the lead
https://github.com/odoo/odoo/blob/ebb61753bf3d3dd8d3f53db088112b9e4beb813d/addons/mail/models/mail_activity.py#L662

Video/Screenshot link (optional):
https://youtu.be/itM2GKvoNeU

Replicated at http://603342-12-0-42a6a7.runbot20.odoo.com

OPW 2061574

**Comment by tde-banana-odoo** [comment]
"Expected behavior:
An Access error must appear because of the ir.rule"

So you expect a crash because of activities ? Seems interesting ...

**Comment by hugho-ad** [comment]
@tde-banana-odoo 

That's right!

**Comment by tde-banana-odoo** [comment]
Hello,

Code in create and _check_access is clear enough. You can create activities for documents on which you can write if the rule is not sufficient. We don't want to block creation of business documents because of automated activities. Those are side records, what is important is the document itself.

Indeed you may have more rights than what ACLs tells you because of this custom behavior. This is intended. For example rights on leave should be managed on leave if you feel there is too much flexibility given by standard rules. This should not crash because of activities.

Please have a deeper look at the code and feel free to come back if you find any bug and/or strange behavior.

Thanks,

**Comment by hugho-ad** [comment]
you right!, thanks! now I founded the sudo statement at 
https://github.com/odoo/odoo/blob/ebb61753bf3d3dd8d3f53db088112b9e4beb813d/addons/mail/models/mail_activity.py#L282

Regards!
