### ISSUE TITLE
[12.0 CE]Translation cannot be overwritten

### ISSUE THREAD

**Issue by yuzifu** [odoo/odoo#36302]
Impacted versions:
12.0 CE

Steps to reproduce:
1.login to 606196-12-0-b3c345.runbot27.odoo.com
2.active zh_CN in languages, and load zh_CN translation
3.change user language to zh_CN
4.checked "Overwrite Existing Terms" to Import a PO file with the following contents：
```
# Translation of Odoo Server.
# This file contains the translation of the following modules:
#	* uom
#
msgid ""
msgstr ""
"Project-Id-Version: Odoo Server 12.0\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2019-08-31 13:11+0000\n"
"PO-Revision-Date: 2019-08-31 13:11+0000\n"
"Last-Translator: <>\n"
"Language-Team: \n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: \n"
"Plural-Forms: \n"

#. module: uom
#: model:uom.uom,name:uom.product_uom_dozen
msgid "Dozen(s)"
msgstr "打"

#. module: uom
#: model:uom.uom,name:uom.product_uom_floz
msgid "fl oz"
msgstr "液盎司"
```

Current behavior:
translation term "fl oz" and "Dozen(s)" are not overwriten.
 
Expected behavior:
After importing the translated po file with overwrite option, the same item will be overwritten.

Video/Screenshot link (optional):
![2019-09-02 09 50 30](https://user-images.githubusercontent.com/853731/64085752-22c25f00-cd67-11e9-966d-c405d1a0c638.png)

**Comment by mart-e** [comment]
Hello,

This is because the uom records are in `noupdate`. If updating a module does not change it's English name, it's logical that it doesn't change its name in other languages.
The correction must be done manually then.
If you want, the translations are handled on [Transifex](https://transifex.com/odoo/public) and you will be able to contribute there.

Don't hesitate to ask if you have issues on Transifex

Thanks
