### ISSUE TITLE
[13.0][idea] account: grouping account.move.line

### ISSUE THREAD

**Issue by fmdl** [odoo/odoo#36319]
Impacted versions: V13

After this commit https://github.com/odoo/odoo/commit/beaa30a3d1843de43a45f419bfbc1bfa7613a920 it is not possible to group `account.move.line`.

The idea is to create this model :

```python
class AccountMoveLineGroup(models.Model):
    _name = acccount.move.line.group
    _description = Line Group

    name = fields.Char(required=True)
    move_line_ids = fields.One2Many('account.move.line','group_id')

class AccountMoveLine(models.Model):
   group_id = fields.Many2one('acccount.move.line.group')

```

During the validation of the account.move, a group is created depending some custome rule (can be bypassed).
By default no group is created. It is just a base for exented module (for developper, OCA, ...).

@qdp-odoo 
@pedrobaeza 

Regards

**Comment by qdp-odoo** [comment]
I'm afraid we won't do such thing in core module unless we have a good (read "legally binding") reason to do so. Removing the grouping feature of invoice lines was a decision taken in full awareness and I don't see why we should take half a step back. 

That idea, though, would still work if implemented in the said extension module.

**Comment by fmdl** [comment]
Thanks.

**Comment by john-herholz-dt** [comment]
Hello,
I was investigating a tax rounding issue and came to the conclusion that the reason for it is that on invoices the move line ids are not grouped by same account type.

Lets say two lines with taxes result in move lines with two times the same account.
The problem here is that this gets rounded and it ends to a wrong tax calculation.

Is this what this ticket is about?

I understand the "decision taken in full awareness" but let's face the fact: The calculation of the taxes is wrong.
I tried all possibilities and this is my final result of this investigation.

Working example was an order with two lines of a product with a price of 3.15 gross (2.6470 net) and 19% tax.
The total was 6.30 including tax and subtotal without tax is 5.30 instead of 5.29.

You would get the correct result if you did only one line but quantity is set to two instead of one.

It all comes down to the fact that on the invoices odoo does not group the account move lines and the rest of the system was built to behave the same as on the invoices.
