### ISSUE TITLE
[IDEA] base: simplify control access and rules by inherit security

### ISSUE THREAD

**Issue by fmdl** [odoo/odoo#37053]
Today you cannot inherit security access from a model to an other model.
Exemple you need to create access rules for `account.move` and `account.move.line`. It make sens that if you have access to `account.move`, you have also access to `account.move.line`. 
I think we can reduce the number of access rules (and like that is more simpler to maintain them).

Exemple :
```python
Class AccountMoveLine():
   _name = 'account.move.line'
   _inherit_security = 'move_id'  #field to check access

   move_id = fields.Many2ne('account.move')
```

It is alway possible to bypass the `_inherit_security` with an access rules:

@odony

**Comment by odony** [comment]
Sorry, that sounds like too much magic for my taste. Explicit is better than implicit, especially for ACLs. Also there will be all sorts of inconsistencies as we want to be able to customize the rules separately: so we'll need to have them as actual records in `ir.rule`, yet they won't match any module data, so updates will be an issue. And then `_inherit_security` won't mean anything because the parent/child rules could diverge at any point. 
That's a lot of moving parts and sources of confusion, just to save a few CSV entries...

**Comment by fmdl** [comment]
Understand
