### ISSUE TITLE
Raspberry pi 4

### ISSUE THREAD

**Issue by abou-uthmaan** [odoo/odoo#37477]
Impacted versions: IoT box - odoo 12

Steps to reproduce: installed the image on sd card and inserted in rapsberry pi 4.

Current behavior: Doesnt show anything black screen.

Expected behavior: That IoT box starts

**Comment by Yenthe666** [comment]
@mart-e do you know who can check this and give feedback?

**Comment by mart-e** [comment]
Hi,

I believe @qle-odoo has worked to have an image working. Due to the [heat issues of the RP4](https://www.jeffgeerling.com/blog/2019/raspberry-pi-4-needs-fan-heres-why-and-how-you-can-add-one), we are afraid this is model is not suitable for a box that you will leave turned on 24/7. Quentin will give you more details about our plan for the future but at the moment, it is better to use a RP3 model (if you still have one).

> do you know who can check

See https://github.com/odoo/odoo/wiki/BugManagement#issues for who to ping ;-)

**Comment by Yenthe666** [comment]
My bad, I've missed the IOT one :) thanks.

**Comment by qle-odoo** [comment]
Hello @Yenthe666 ,

Indeed the image of the IoT does not work on a Raspberry pi 4 because the image of Raspbian is "Stretch".
To support the new Raspberry you have to use the "Buster" version but that implies to change some things in the "build" of the box.
In addition, the overheating problems of the RP4 mean that in production it is too risky to use it in the long term.

cc @mart-e

**Comment by Yenthe666** [comment]
@qle-odoo thanks for the update. So, in short, there is no direct support for RP4 coming and Odoo will stay on RP3?

**Comment by mart-e** [comment]
@Yenthe666 in short, at the moment, no support for RP4.
But who knows what the future will be? We will run out of RP3 at some point anyway...

**Comment by mart-e** [comment]
Closing as the question was answered.
You can check on http://nightly.odoo.com/master/posbox/iotbox/ if a new image pops up supporting the fourth version in the future

**Comment by spoerp** [comment]
It seems the RP4's new firmware has managed to reduce the heat.
Also the reviews where they stress test and connect displays and drive the graphics are the real culprit here for these extreme temperature.

A RP4 case like the one provided by the with inbuilt fan would even work . As the benefits RP4 would provide to IoT box performance are substantial.

**Comment by qle-odoo** [comment]
Hello yes indeed.
Moreover for the next version of IoT Box the raspberry pi 4 will be supported.
https://github.com/odoo-dev/odoo/commits/master-iot-support-rpi4-qle

There is still a high temperature and so I recommend a case that will dissipate heat better than the official case.
https://flirc.tv/more/raspberry-pi-4-case
https://shop.pimoroni.com/products/aluminium-heatsink-case-for-raspberry-pi-4?variant=29430673178707

**Comment by UnixedIT** [comment]
Hello @Yenthe666 , I have just tested it on last iotbox image it works fine. 

v19.12

**Comment by nick2474** [comment]
If you are using Odoo +v9,v10 or +any the old version of posbox image won't work with RP4.

I fix my issue with a new Raspberry PI 4 image.
1.Use the imager_1.4 installer. 
2.Install the image iotboxv20_06.img (latest on this post)
3.Now once turned the RP4 its not printing on but not printing the posbox ticket reference for IP, with the old version for RP3B+ this was printing  and reachable the setup with IP: 10.11.12:8069.
4.You should login on RP4 wifi and start the setup http:localhos:8069, lookup wifi-setup.
5.Wait until reboot and login on the network using on mobile.
6.I used Thether App on my local router to determine whats the ip for the RP4 connected.
7.Then i was able to check the IP assigned and the Hardware status with the url: http://YOUR_IP_ADDRESS:8069/hw_proxy/status.
