### ISSUE TITLE
Should not use gethostname() to build the Message-id of emails

### ISSUE THREAD

**Issue by ccomb** [odoo/odoo#3762]
The first step of this bug report is interesting to do, but the bug is present on all versions, from 6.0 to current master, and probably before.
- Setup a high-availability hosting with PostgreSQL master-slave replication with failover on a different host
- Create a lead and send an e-mail to a customer using the openchatter (we're on host1)
- Promote the slave as a master by running your failover procedure. We're now on host2.
- Receive the answer from the customer on this new master host through your catchall address

→ the e-mail sent by the customer is not correctly routed to the created lead

The problem is that gethostname( ) is used in the Message-id generation (openerp.tools.mail.generate_tracking_message_id),
and in the message routing (mail.mail_thread.py:message_route).
So the sent mail contains a Message-id that looks like: ...-openerp-804-crm.lead@host2 while the code that routes the message expects ...-openerp-804-crm.lead@host1

Instead of gethostname( ), something like ir_configparameter.get_param('catchall.domain') or similar may be used.

**Comment by Yenthe666** [comment]
@tde-banana-odoo can you give a statusupdate about this please?

**Comment by ccomb** [comment]
```socket.gethostname()``` is still used in ```odoo/tools/mail.py``` to generate the tracking id. So it's still impossible to move an odoo from one server to another...

And FYI there is another socket.gethostname() in ```addons/mail/models/mail_thread.py``` but my vim tells that  ```local variable 'local_hostname' is assigned to but never used [F841]```...

**Comment by mlaitinen** [comment]
I was banging my head against a wall because of an Odoo email relayed via Office 365 servers ended up in – you guessed it – Office 365 spam filters. SPF was ok, email was delivered to GSuite without problems, but the client's emails ended up in Office 365 junk mail, including emails sent from their domain to their domain.

So I noticed the email Message ID didn't contain the correct sending domain and thought it might have an effect. I changed the hostname to the sending domain and voilà: no more junk mail. 

Then I found the `generate_tracking_message_id()` function and was disappointed to see that the only way the Message ID can be changed is to change the hostname (in this case, a Docker container's hostname). I hope this issue gets more attention because otherwise I will have to monkey-patch this in multi-tenant environments with >1 Office 365 SMTP relay connections.

**Comment by pedrobaeza** [comment]
Is this still happening in latest versions?

**Comment by ccomb** [comment]
A grep -nr gethostname still give results, but last time I've looked it was not really used. Seems the implementation has changed for real.

**Comment by pedrobaeza** [comment]
OK, then I think we can triage (as it's one of the oldest issues) this and if still happening, we can reissue it. Thanks for the follow up.

**Comment by ronluna** [comment]
This error still occurs on odoo 13

**Comment by tde-banana-odoo** [comment]
We don't route based on message id content; it is used only to find parent of incoming emails and detect if it is an answer. Changing the generation of message IDs should not impact anything.

What is exactly the issue then ?

**Comment by ccomb** [comment]
Since the hostname changes, the answer won't be detected as an answer to the original message, so the thread is lost.

**Comment by tde-banana-odoo** [comment]
Not since several versions. Exact message ID is used, not the parsed version of it. Unless I am mistaken we search for existing messages with the references / in reply to message ID and take their model / res_id to find the original thread.

**Comment by mart-e** [comment]
As explained by Thibault, we do an exact match now so no need to have a matching hostname

https://github.com/odoo/odoo/blob/6db7b375d10d0dc2428469c84f9144bb432929d1/addons/mail/models/mail_thread.py#L903-L906

There is a `socket.gethostname()` remaining but it's dead code, no longer used.
By the way, we are using several hosts on odoo.com, so emails from a same thread will be using different hostname from time to time but it isn't an issue, all the emails endup in the right place.
