### ISSUE TITLE
l10n_ch does not handle ISR reference

### ISSUE THREAD

**Issue by fclementic2c** [odoo/odoo#37716]
Impacted versions: Saas 12.5

Steps to reproduce: https://docs.google.com/document/d/1M_BODGG8djHbXeWhZXs_BX6e_bGs71jOP_rxLagxyE8/edit#

**Comment by Yenthe666** [comment]
@jco-odoo for you I assume?

**Comment by fclementic2c** [comment]
Situation is even worst than I though... bank reconciliation based on payment ref do not work and Swiss SEPA neither... 

There is 4 big uses cases we need to make running : https://docs.google.com/document/d/14hy3FZkZUE90QLdLSkaycuJRgMVHlAZ5LnRGIjit1PE/edit#heading=h.x09m8vi47mi

Today none of them pass the test with Odoo13 :\

**Comment by avw-odoo** [comment]
@fclementic2c Could you tell me what's wrong with case 4 ?

![Case 4 - Bank reconciliation based on ISR ref](https://user-images.githubusercontent.com/8666736/66511937-308ea100-ead8-11e9-8b64-7a79dbf00093.png)

**Comment by avw-odoo** [comment]
@fclementic2c We have been finding some improvements for cases 1, 2, 3. We will know if we agreed that everything works well.

@jco-odoo & @jcr-odoo Will check that with you...

**Comment by fclementic2c** [comment]
Thank you. I cannot test until next week since I am traveling. But I will
come back to asap.

**Comment by fclementic2c** [comment]
Hello @avw-odoo, do you mean that you have merged few fixes ? should I update my code and do the 4 uses cases again ? cc @jco-odoo 
thxs

**Comment by jco-odoo** [comment]
During the Odoo XP, we merged to have a structured payment reference and
some days ago, we merged that the register payment also takes that
reference in the Memo field.  Of course you can test that again, but I
think we know where the problems are.

**Comment by fclementic2c** [comment]
ok so I do not test yet.

BTW, I started an new Odoo13 project last monday. Go live for accounting will be in 1 month...so it starts to urgent a bit :) sorry

**Comment by jcr-odoo** [comment]
Hello, 

We made some changes to make the ISR reference work.
- We made some improvements on the Labels and the tooltips, according to the labeling in this documentation. https://www.raiffeisen.ch/rch/fr/clients-entreprises/trafic-paiements-et-liquidites/debiteurs/bulletin-de-versement-orange.html 
- Some other bugs regarding the reconciliation and the payment reference were already fixed in stable. 
- The bank creation wizard was improved.
You can retest all changes on this branch http://runbot.odoo.com/runbot/repo/git-github-com-odoo-dev-enterprise-8?search=13.0-chbvr-jco

Please let me know if something is not clear, we can do a walktrough and complete test together to make sure that we didn't missed anything. 

We stay available and sensitive to this matter.

**Comment by fclementic2c** [comment]
Uses Case 1, 2 and 3 passed :)
Use case 4 do not pass if the ISR on the bank statement line has spaces which is always the case I think.

**Comment by fclementic2c** [comment]
Hello guys @jco-odoo @jcr-odoo 

Can you merge all features already validated ? What are your plan ? 
(please keep in mind that I have 2 go live Odoo13 for CH very soon :)

**Comment by jcr-odoo** [comment]
@fclementic2c 
Everything is merged in v13 now :)

**Comment by fclementic2c** [comment]
cool :) thanks



*camptocamp*

INNOVATIVE SOLUTIONS
BY OPEN SOURCE EXPERTS

*Frédéric Clementi*
Project Manager
Business Solutions

+41 21 619 10 41

www.camptocamp.com

**Comment by Yenthe666** [comment]
I think this one can be closed now? :)

**Comment by jco-odoo** [comment]
Yes, if there is still a problem, a new issue/pr can be made.
