### ISSUE TITLE
[v8] New columns not created inheriting models.AbstractModel

### ISSUE THREAD

**Issue by NicolasWebDev** [odoo/odoo#3786]
I am creating three classes like this:

```
class class1(models.Model):
    _name = 'class1'

class class2(models.AbstractModel):
    _name = 'class2'
    _inherit = 'class1'

class class3(osv.Model):
    _name = 'class3'
    _inherit = 'class2'

    _columns = {
                 'test': fields.char('test'),
     }
```

As you can see, I have to mix v8 classes (class1 and class2) with v7 classes (class3).
When I add columns to class3, in this example if I add the test column, after an update of the database/module, the new column doesn't get created in the database, and I have an error everytime I try to access a class3 object (`ProgrammingError: column class3.test does not exist`).

If I change the class2 from models.AbstractModel to models.Model, then after an update, the new field does get created.

Class 1 isn't abstract, because another object "inheritS" it.

My odoo code is the last one as of today.

**Comment by Cuauhtemoc-tzin** [comment]
From https://www.odoo.com/documentation/8.0/reference/orm.html
in Porting from the old API to the new API we have:

uses of _columns or _all_columns should be replaced by _fields, which provides access to instances of new-style openerp.fields.Field instances (rather than old-style openerp.osv.fields._column)
