### ISSUE TITLE
[13.0] Autocomplete API  Trackback Error.

### ISSUE THREAD

**Issue by KapilPatel-KP** [odoo/odoo#38000]
**Impacted versions:**
odoo 13.0
**Steps to reproduce:**
1) Go to sales >> Order >> Customer >> Create >> Enter name of customer like odoo select form list(Autocomplete)

**Current behavior:**
1) Enter Customer Name Select form suggestion list (Autocomplete), Like i have type odoo 
![Screenshot from 2019-10-05 13-23-56](https://user-images.githubusercontent.com/24518821/66251951-af4fab00-e773-11e9-8b70-ccef7003de30.png)

2) select form list it raise trackback
![New - Odoo](https://user-images.githubusercontent.com/24518821/66251975-f76ecd80-e773-11e9-9f37-8a5102ab05e7.png)

3) Terminal error Image
![Selection_019](https://user-images.githubusercontent.com/24518821/66252063-8ed42080-e774-11e9-8ef9-858586f58d80.png)

**Expected behaviour:**

Video/Screenshot link (optional):

![Peek 2019-10-05 13-18](https://user-images.githubusercontent.com/24518821/66251993-14a39c00-e774-11e9-8aeb-2c2835fb2346.gif)

**Comment by sswapnesh** [comment]
I am not sure but It seems due to Odoo IAP services
![Screenshot from 2019-10-06 13-20-42](https://user-images.githubusercontent.com/16624719/66265953-20f32c00-e83c-11e9-93e9-8c8502022af4.png)


--------------------------
I am getting Error from Other IAP services as well (and  500 on https://iap-services.odoo.com)
![Screenshot (18)](https://user-images.githubusercontent.com/16624719/66265966-4bdd8000-e83c-11e9-9349-073537ffa76b.png)
![Screenshot (18)](https://user-images.githubusercontent.com/16624719/66265987-8a733a80-e83c-11e9-9884-1adb952fae65.png)

**Comment by sswapnesh** [comment]
It seems this is working well now
Tested on latest v13 at http://658714-13-0-c757e1.runbot21.odoo.com/web#id=&action=824&model=sale.order&view_type=form&cids=&menu_id=584

**Comment by pedrobaeza** [comment]
OK, closing then. Please reply if any question.
