### ISSUE TITLE
[13.0] Improve Possition of o_chatter_button_attachment on Chatter

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#38013]
Impacted versions: 13.0

Steps to reproduce: 

Current behavior:  We should not leave him alone :wink: 
![Screenshot (16)](https://user-images.githubusercontent.com/16624719/66265510-9c051400-e835-11e9-9e68-a31af2217cfd.png)

Expected behavior: As v12  
![Screenshot (17)](https://user-images.githubusercontent.com/16624719/66265519-c787fe80-e835-11e9-8a92-440fec663e6b.png)

Video/Screenshot link (optional):

**Comment by seb-odoo** [comment]
Maybe it was introduced because it looks better when the chatter is on the right instead of the bottom (no idea, just wondering).

Do you have a PR for this? Is it a one line fix?

cc @alexkuhn

**Comment by sswapnesh** [comment]
> Do you have a PR for this? Is it a one line fix?

I don't have any idea about the fix. (Haven't touched Css/Js ever :disappointed: )

**Comment by alexkuhn** [comment]
This button is usually placed between "Schedule an activity" and the follower widget.
Channel form view is special, in that it doesn't have the left buttons (send message, log note, etc.).
The style is quite a mess, as it uses `float` left/right, so that's why the attachment button floats on the left.

**Comment by sswapnesh** [comment]
If we have this situation at only few such places then It's okay to keep it like this

**Comment by seb-odoo** [comment]
Then is in on purpose that there we can still have attachments even if there is no way to add message?

**Comment by sswapnesh** [comment]
I think yes but I don't know why Logger/Messages are not Implemented there.

**Comment by alexkuhn** [comment]
This is intentionally not implemented because this wouldn't work **at all**.
I won't give details (otherwise this would be a very, very long post) but to make it short, this is due to the many hacks that are used to make Discuss work. I think the motivation was that this was the easiest and fastest way to implement Discuss, and the initial thought process was that _channels would not have form view anyway_ so many sad shortcuts have been taken.

`mail.channel` is a heavily customised `mail.thread`. Because this is a `mail.thread`, it has a chatter (hence follower and attachment). But at the same time, it has so many customisations that it cannot work as a usual `mail.thread`, hence no messages are displayed.

**Comment by seb-odoo** [comment]
@alexkuhn thank you for the (unfortunate) details. Hopefully we can improve this some day.

So for the current PR, what do you suggest? 

If I understand correctly, the choices are:
- we leave it like this and close the PR?
- we hide the attachments if they have no purpose there?
- we find a simple fix to place it correctly? maybe just a custom css for this case?

**Comment by alexkuhn** [comment]
I would leave it like this. Fixing this issue may likely introduce some flickers in other chatters, and hiding attachments adds too much complexity for what is worth in my opinion.

**Comment by seb-odoo** [comment]
Sounds reasonable, let's close it then.
