### ISSUE TITLE
[13.0] Trackback : Lunch app > Group by Vendor > Add Column title.

### ISSUE THREAD

**Issue by dipsshah42** [odoo/odoo#38014]
Impacted versions: 13.0 C

Steps to reproduce:
- Go to Lunch App
- Group by Vendor
- Add Column title and Enter.

Current behavior:
- Showing Traceback.

Expected behavior:
- Should work thoroughly.

Video/Screenshot link (optional):
[Link](https://youtu.be/RfnVX5RYX6s)

**Comment by pedrobaeza** [comment]
Maybe the quick create should be deactivated there

**Comment by sswapnesh** [comment]
> Showing Traceback.

`ERROR: null value in column "partner_id" violates not-null constraint`

That's because `partner_id` is required.

-----------------------------

> Maybe the quick create should be deactivated there

@pedrobaeza  We can but we have a similar situation at other places too where required field on models blocks such operation, So I am not sure If this can be considered a bug or not
