### ISSUE TITLE
How to Manage cron (ir.cron) when use Odoo Server with Load Balancing 

### ISSUE THREAD

**Issue by vipin9457** [odoo/odoo#38044]
Impacted versions:11.0

Steps to reproduce:
Install odoo in aws and add the load balancer over application end .When load in increased then new application server will be automatically launch with same configuration and now application server are two so that two cron job are running at a same time with different slave because all server embedded his scheduler job .

Current behavior: When use load balancer (hardware or software) with multiple Odoo Server, (1 master and multiple slave), there is a problem with scheduling (ir.cron), because all server embedded his scheduler job .

Expected behavior: How to run the cron job in case of load balancer.

Video/Screenshot link (optional):

**Comment by codeagencybe** [comment]
hmm good point...
I'm currently working on something similar with Kubernetes and nginx or Traefik as load balancer to create an high availibility setup. But this is good point you mention, because otherwise each instance/replica will start firing off crons simultaneously. 

Did you test this with a different version like Odoo12 (or 13)? Same behaviour? 
Maybe somebody can explain how to do this properly. 

Perhaps there is a specific configuration option to disable application CRON and replace by server CRON? This same concept is also done in Wordpress where you disable cron in wp-config.php and must use a server cron. Hoping Odoo has some kind of a similar method.

**Comment by vipin9457** [comment]
@codeagencybe  Same thing happen in odoo version 12 and 13 as well

**Comment by pedrobaeza** [comment]
I'm afraid this is not an Odoo issue, but a question about some deployment things. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Little tip not tested: Use different configurations with max_cronthreads = 0 in one of them for not enabling the cron.

Closing this by the reason above.

**Comment by vipin9457** [comment]
@pedrobaeza  Unable to post the question on https://www.odoo.com/forum/help-1 it's generate the message like **"3 karma is required to perform this action. You can earn karma by having your answers upvoted by the community."**

**Comment by pedrobaeza** [comment]
You have to verify your email before being able to post it
