### ISSUE TITLE
[V8] HTML Editor in secondary language fails

### ISSUE THREAD

**Issue by lucode** [odoo/odoo#3808]
When I try to translate text (website builder), i can't overwrite some words. Even if I change them, they do not disappear after saving changes. And it is not possible to access in HTML edit the translated text block.
# Steps to reproduce:
1. Having secondary language installed
2. Go to website
3. Translate a text block with headers into secondary language
4. ev. copy and paste content into translated block
5. Click on the customize menu on top right side.
6. Open "HTML Editor"
7. You will see the content of the primary language

As far I could figure out there is no way to correct this false html code except in accessing the database.

Screenshot (primary lang DE, secondary lang EN)
![Screenhot](http://welfair.net/docs/images/2014-11-22%2008_46_41-Jeema%20solutions%20-%20ngo-npo.png)

**Comment by Yenthe666** [comment]
Hi @lucode ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.
P.S: Both the website and the translation tools have improved quite a bit since V8 😉 

Regards,
Yenthe
