### ISSUE TITLE
_filter_access_rules: hard coded record ids in sql lead to low performance

### ISSUE THREAD

**Issue by RealSolutionsLux** [odoo/odoo#38107]
Impacted versions: 12.0

Steps to reproduce: 

Have multiple POS running daily producing some thousand pos_orders every day.

Current behavior:

watch how the time to validate a pos order increases every day to 5-10 seconds in the presence of about 70.000 pos orders in the backend.

Expected behavior:

Validating a pos order should be more or less constant time in the order of around or less than a second.

Observations:

In POS, validating a pos order creates a pos order in backend with bank account statement lines for the payments. However there is an access rule for bank account statement lines for the POS user with a domain filter "[('statement_id.pos_session_id', '!=', False)]" that gets evaluated in odoo/models.py:_filter_access_rules() returning many thousands of ids for existing bank account statement lines linked to a pos_session.

The IDs of these existing accounting.bank.statement.line are added to the query during execution of "create_from_ui" for the pos order.

The problem is somehow similiar to issue #12801

How can performance be improved without desactivating the record access rule?

**Comment by switch87** [comment]
Thanks for reporting the issue, my colleague is verifying it.

**Comment by caburj** [comment]
@RealSolutionsLux I talked to @rco-odoo about this issue, but unfortunately, this can't be fixed in the stable version. One thing to note though is that this is not a problem anymore in the new version (v13) because filtering access rules has new implementation.

We do, however, have a suggestion if you are on-premise or in odoo.sh to solve this problem in your instance. What you can do is create a simple module that inherits the `pos.session` model and reimplement its `statement_ids` field to contain 'auto_join=True', like so:
```
statement_ids = fields.One2many('account.bank.statement', 'pos_session_id', string='Bank Statement', readonly=True, auto_join=True)
```
This will modify the query generated in the `_filter_access_rules` method to a more optimized one.

**Comment by rco-odoo** [comment]
@RealSolutionsLux @caburj I actually suggested to add `auto_join=True` on the field `statement_id` of the model `account.bank.statement.line`:
```python
class AccountBankStatementLine(models.Model):
    _inherit = 'account.bank.statement.line'

    statement_id = fields.Many2one(auto_join=True)
```
so that the SQLization of the domain
```python
[('statement_id.pos_session_id', '!=' False)]
```
on this model does not generate a query on `account.bank.statement`.

**Comment by pedrobaeza** [comment]
Can we consider this as answered and close it?
