### ISSUE TITLE
Wrong sale-manager assign in Quotation.

### ISSUE THREAD

**Issue by androver1** [odoo/odoo#38179]
Impacted versions:
ODOO 12 CE

Steps to reproduce and current behavior:
There is an issue of assigning sale-manager in a workflow lead-opportunity-quotation. The standard ODOO workflow is as follows:
1. User "Administrator" creates a lead and assign "Manager 1" from "sales team 1" as a sale-manager in this lead
2. User "Manager 1" converts this lead to opportunity and assign other manager manually (for example, this opportunity has Manager 2 as sale-manager)
3.   User "Manager 2" creates quotation from that opportunity an there is ALWAYS assigned sale-manager who was in lead (i.e. Manager 1 in our case)

Expected behavior:
The issue is: the sale-manager in the quotation has to be Manager 2

**Comment by pedrobaeza** [comment]
That's not the expected behavior, as the salesman assigned to the lead always have priority. Imagine you have an administrative person that is doing the quotation. That doesn't mean this person should be the salesman. You have to manually change it if you want that flow, or do a customization that allows it.

Closing as expected behavior.
