### ISSUE TITLE
[13.0]Event : Responsiveness is missing in Calendar Date selection

### ISSUE THREAD

**Issue by dipsshah42** [odoo/odoo#38562]
Impacted versions: 13.0 C

Steps to reproduce:
- Create Event.
- When Entering the start date and end date.
- And Scrolling up/down to select Hours.

Current behavior:
- responsiveness is missing.
- The video will explain it better.

Expected behavior:
- it should handle in well manner, the way normal date field is handled.

Video/Screenshot link (optional):
[Video ref](https://youtu.be/glC3UeTbF9w)
[Image](http://tinyurl.com/yxafw2vb)

**Comment by pedrobaeza** [comment]
This is something that will generate a lot of JS stuff to be added and performance problems when doing scroll. It has been reported in the past the same with many2one dropdowns and it's not expected to be fixed because it's not impacting in the operative as is. The focus is to keep that floating window in the same position, which also benefits in mobile views.

Closing as won't fix.
