### ISSUE TITLE
[Wishlist] Make sections not just text but real records

### ISSUE THREAD

**Issue by Yenthe666** [odoo/odoo#38778]
Impacted versions: 12 and above

Steps to reproduce:
1. Login to any runbot instance and go to sales.
2. Create a new quote and add a section to it.

Current behavior:
At this point the section logic in Odoo is just plain text being shown and some JavaScript/CSS modifying the look of the line depending on the `display_type` of the sale order line:
https://github.com/odoo/odoo/blob/5f25bc2d0be59b9d1d4414fc1fcfecb5f49726a5/addons/sale/models/sale.py#L1239-L1241 
This has some downsides/limitations though. There is no link to another table and no easy way to map lines to a specific section for example.

I'd like to propose to change the sections logic to a `Many2one` field referencing a new model `section.section`. It would have the following benefits:
- Ability to quickly select sections and no need to type/recreate them every time
- Ability to translate sections in multiple languages. Sections can now be added to templates and they are copied over to the sale order once you select a template. In the current situation we're copying over plain text but if it would be a model it could copy over the record and translate it depending on the customer its language.
- Possibility to set a section on a product (or even product group) configuration so that product lines are automatically sorted/shown under its relevant section.

I personally feel this would make the feature way more dynamic and it opens up a set of new options.

**Comment by pedrobaeza** [comment]
@Yenthe666 on v11 was this way you described, and the switch to sale.order.line was done for commodity.

**Comment by Yenthe666** [comment]
@dbo-odoo / @JKE-be  any chance I could get your feedback on this one? I genuinely do not get why this was dropped (thanks for the reference @pedrobaeza) and why we went with text above this logic..

**Comment by dbo-odoo** [comment]
This was dropped because it adds a lot of logic and complexity in the UI, just go have a look at v11 to see how sections worked for an example.

Regarding the benefits you mention:
- you can use quotation templates to have sections, etc. ready for re-use you do it often; section titles should be rather short anyway (a few chars, maybe 2-3 words). Notes, if used that often, should perhaps then be included in the sales description of the product itself
- translation in a quote/invoice/PO etc. has very little use imho, you should always write them in the language of the customer anyway (however it would make sense to make this translatable on quotation templates, so i'll keep that from this feedback)

I think it's a matter of using the right tool for the job: if you need to re-use constantly the same notes, then you should probably be using the description of the product or the default Terms and Conditions to do that. Having a menu to configure existing notes and sections titles is just feature creep from my point of view - lots of complexity in the code and the UI for a feature that will benefit very few people... And most typical user would not even be able to use it properly, possibly introducing confusion.

I'll close this, because we're not going back to the v11 model for sure.

I'll forward the translation for templates though, this one is nice.

Thx for your understanding :)

**Comment by haddo** [comment]
i am tying to add section to odoo v10 i added the display type but nothing shown
