### ISSUE TITLE
[12/13] Calendar: Could not add Read virtual Ids on list view

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#38840]
Impacted versions: 12/13

See https://github.com/odoo/odoo/issues/27474#issuecomment-427587249 and  https://github.com/odoo/odoo/issues/27474#issuecomment-541853108

Steps to reproduce: Show Id field on List view --> Create Recurrent Event--> Load tree view

Current behavior: 

![](https://user-images.githubusercontent.com/16624719/66775225-278b3e80-eee1-11e9-88ec-9db63cf76cd1.png)

Expected behavior: Shos Id on the list view

Video/Screenshot link (optional):

**Comment by len-odoo** [comment]
>Show Id field on List view
The calendar.event model has the unique specificity to have virtual ids, which are strings and not integers.
Since the use case is not really supported, that would be a limitation of Odoo.
It could be solved by overriding the relevant function in calendar (e.g. the list renderer) but it's clearly not worth the hassle.
So I would mark that as wontfix.
