### ISSUE TITLE
[13.0] MRP : Traceback when creating Workorder By Going in Workcenter.

### ISSUE THREAD

**Issue by dipsshah42** [odoo/odoo#38992]
Impacted versions: 13.0

Steps to reproduce:
- MRP > Create Any work center and Save it.
- Open that work center > Go into 2nd smart button named 'Lost hours' something.
- which will open the **Productivity Losses** menu.
- Create any record manually here and create a **work order** from here.

Current behavior:
- Traceback is throwing.

Expected behavior:
- Should handle in well manner.

Video/Screenshot link (optional):
[Screenshot](http://tinyurl.com/y685xk6o)
[Video](https://youtu.be/p_2zgsd8SqE)

Thanks!

**Comment by sswapnesh** [comment]
Create and Edit should be Removed from there as It doesn't make any sense to create a record from there.

Added fix at https://github.com/odoo/odoo/pull/39071.
However, Still, you will get `You have to produce at least one False.` due to  https://github.com/odoo/odoo/blob/e398db8783c2c88ffbb571b14758281ba6f382d1/addons/mrp/models/mrp_abstract_workorder.py#L57
