### ISSUE TITLE
[Website-Forum] Bio view is limited to last 20 Questions & Answers

### ISSUE THREAD

**Issue by smack815** [odoo/odoo#3955]
On September 2 in commit 78fa86193612e6831453bba003a8045a7d3b7c6c forum users were limited  to only see their last 20 Questions and Answers.  This artificial limitation to reduce the stress on odoo's servers really causes problems with heavy forum users, like myself.  

Now it is nearly impossible to look up previous answers in order to link them to duplicate questions.  It would be nice if there were a link at the bottom of the list to see the rest of the questions/answers.  This would be a good balance between performance and functionality.  Another option would be to make the forum search feature more powerful.

**Comment by smack815** [comment]
@tde-banana-odoo @odony I know this is a wishlist item but it really makes it difficult to help people on the forums.  When you spend 20 minutes researching all the links, taking screen shots uploading them to hosing sights formatting your text and making it easily understandable... 

There is not time in the day to do that more than once.  Please consider this request.

**Comment by odony** [comment]
@smack815 as a quick fix we can lift the limit to 20 posts for users with high karma - there are only a few of them so they (you) won't impact overall performance much, and seeing the full list of posts would be useful to them as a moderation tool as well (think, e.g. when tracking a spammer's posts).

@dvdhinesh Making it a user preferences wouldn't work so well because we introduced this limit for performance reason. It would also change the database schema, something that would require waiting for the next release. As for following the latest answers and comments on your posts, you should be receiving email notifications as with any Odoo document you are following. You can also login on odoo.com and look at your Messaging/Inbox for notifications.

**Comment by smack815** [comment]
Thanks @odony.  High karma = karma_unlink_all = 1000 currently... correct?

**Comment by Yenthe666** [comment]
Thank you very much for this fix @odony. Have been waiting weeks for this. +1

**Comment by odony** [comment]
@smack815 Yes that's correct, it's currently available for 1000+ karma users. In master we should replace this with proper pagination, this is just a quick fix that does not require changing the templates too much.
