### ISSUE TITLE
mrp.bom doesn't account for manufacturing in different timezones other than localtime

### ISSUE THREAD

**Issue by kitsunde** [odoo/odoo#3961]
We're manufacturing in Singapore (GMT+8) but the server is in UTC, the model only uses a `fields.date` field which isn't timezone aware. The is a problem because our BOM is only valid for 1 day it should be _dec 2nd - dec 3rd_ but is compared as _dec 2nd 8am - dec 3rd 8am_. It's an issue of having a timezone unaware `fields.date` and using `localtime()` comparison:

```
domain = domain + [ '|', ('date_start', '=', False), ('date_start', '<=', time.strftime(DEFAULT_SERVER_DATETIME_FORMAT)),
                            '|', ('date_stop', '=', False), ('date_stop', '>=', time.strftime(DEFAULT_SERVER_DATETIME_FORMAT))]
```

I'd suggest changing the `date_start` and `date_stop` into a `fields.datetime`, so it can be properly normalized into UTC and not be tied to the system time. It should also compare against `datetime.utcnow()` rather than `localtime()` which is the case with `time.strftime`.

**Comment by scosist** [comment]
I'm not sure if things have changed since the time this was posted but in the context of a running Odoo instance (tested in 9.0) `datetime.now()`, `datetime.utcnow()`, `time.localtime()`, and `time.gmtime()` are all equivalent as Odoo is running in UTC.

I agree `date_start` and `date_stop` should be a `fields.Datetime` object instead of `fields.Date`. Judging by this commit (https://github.com/odoo/odoo/commit/70a51cd7610111d840ea8b2e8f7b609a1d983769#diff-200a0bd9e95f58f31b37039e65f28d69L301) it appears perhaps they were intended to be `fields.Datetime` and the original fields definitions for `date_start` and `date_stop` were a mistake that at this point had to be followed.

**Comment by Yenthe666** [comment]
Hi @kitsunde ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.
P.S: Just like the other report, the PR might still be relevant against 9.0.

Regards,
Yenthe
