### ISSUE TITLE
When creating a new line in a quote, it does not maintain order

### ISSUE THREAD

**Issue by maitaoriana** [odoo/odoo#39741]
**Impacted versions:**
11.0
**Steps to reproduce:**

1. Create sale order
2. Add three lines and save.
3. Move last line to firts position and save.
4. Adde line new.

**Current behavior:**

The new line is added in the second position

**Expected behavior:**

It must be added at the end

**Video/Screenshot link (optional):**

[Video](https://youtu.be/W-EBbt9WB6Q)

**Comment by pedrobaeza** [comment]
This is something known, but not possible to be fixed in 11.0 in core. In 12.0 it's fixed though, so please upgrade your instance as soon as possible for benefiting of this fix.

If you want it in 11.0, you can use https://github.com/OCA/OCB, as the patch that was considered too big for being put in stable, was integrated by community in https://github.com/OCA/OCB/pull/855.

Closing then as won't fix, but with possible provided paths.
