### ISSUE TITLE
[13.0] Email aliases depends on the sort order of recipients

### ISSUE THREAD

**Issue by nafex** [odoo/odoo#39783]
Odoo aliases sometimes works and sometimes not. It depends on the sort order of the email recipients (email to's).
If I send an email to support@mycompany.com, it lands in the catchall@mycompany.com mailbox.
When odoo fetches the emails from catchall@mycompany.com sometime the recipients (`message_dict['to']`) are "support@mycompany.com,catchall@mycompany.com" and sometimes "catchall@mycompany.com,support@mycompany.com".
https://github.com/odoo/odoo/blob/cf54606edb9130f2c5b351150f0e37b75f10ae66/addons/mail/models/mail_thread.py#L906

In the second case no support ticket is created because odoo get the catchall@mycompany.com as `email_to_localpart`
https://github.com/odoo/odoo/blob/cf54606edb9130f2c5b351150f0e37b75f10ae66/addons/mail/models/mail_thread.py#L907

Odoo bounces the email because catchall is on first place in `email_to`:
https://github.com/odoo/odoo/blob/cf54606edb9130f2c5b351150f0e37b75f10ae66/addons/mail/models/mail_thread.py#L964

My suggestion is to first look for aliases and if no matching is found then check if `catchall_alias` is in `email_to_localpart`

**Comment by pedrobaeza** [comment]
I think #38459 will solve this.

**Comment by nafex** [comment]
@pedrobaeza Thank you, will checkout #38459 and test with my scenario. Also I found https://github.com/odoo/odoo/issues/34777 which seems to be the same issue...

**Comment by nafex** [comment]
Cannot apply #38459 because the patch is for 11.0 and I'm using 13.0, too many changes...

The origin of the issue in 13.0 is here:
https://github.com/odoo/odoo/blob/ac90d8584f99e24aed931eb5186c360f9dfbf399/addons/mail/models/mail_thread.py#L1394-L1403
and here:
https://github.com/odoo/odoo/blob/ac90d8584f99e24aed931eb5186c360f9dfbf399/addons/mail/models/mail_thread.py#L1404-L1410

A `set()` is not ordered, so sometimes `Delivered-To` is first and sometimes `To`. Then here the first is set as `email_to_localpart`:
https://github.com/odoo/odoo/blob/cf54606edb9130f2c5b351150f0e37b75f10ae66/addons/mail/models/mail_thread.py#L907
and here checked if it is the catchall address:
https://github.com/odoo/odoo/blob/cf54606edb9130f2c5b351150f0e37b75f10ae66/addons/mail/models/mail_thread.py#L964

Because the `set()` is not ordered the catchall address check is arbitrary.

I have open an enterprise ticket. Hope this is soon fixed, as the aliases are not usable at the moment :-(

**Comment by pedrobaeza** [comment]
There's #38484 for 12.0 and should be similar for 13.0

**Comment by nafex** [comment]
@pedrobaeza yes this one is better, thank you.
I have applied the changes from Yajo adapting it for 13.0. But with this changes all my emails to an alias are bounced because of this:
https://github.com/odoo/odoo/blob/938d2d933b1b58307ad05e7502b8c5d6bd4efd93/addons/mail/models/mail_thread.py#L1270
In my case the `catchall_alias` is always in `email_to_localparts`.
`Delivered-To` always holds the catchall address (catchall@x.com) and `To` holds the alias (support@x.com)...

**Comment by pedrobaeza** [comment]
Thanks for the feedback. It's interesting that you comment that on the PR itself so that my colleague is aware of that.

**Comment by tde-banana-odoo** [comment]
To be managed when forward-porting https://github.com/odoo/odoo/pull/38459 indeed.

**Comment by tde-banana-odoo** [comment]
Integrated in 11.3 forward port of https://github.com/odoo/odoo/commit/e40f3ccad627af5f74be4fe9f73c201447cb6eb1 at https://github.com/odoo/odoo/commit/3aa26ed078f46345ffff4cd7136309ccfc600f28 .

**Comment by nafex** [comment]
> Integrated in 11.3 forward port of [e40f3cc](https://github.com/odoo/odoo/commit/e40f3ccad627af5f74be4fe9f73c201447cb6eb1) at [3aa26ed](https://github.com/odoo/odoo/commit/3aa26ed078f46345ffff4cd7136309ccfc600f28) .

When this will be ported to 13.0? I found only your forward port to 12.0...

**Comment by nafex** [comment]
@tde-banana-odoo is the forward port for 13.0 in progress or has it been forgotten?

**Comment by Yajo** [comment]
I'll try to help everyone<sup>1</sup> track this issue

<details>
<summary>Odoo history on this bug</summary>

- 11.0:
  - Fixed originally in https://github.com/odoo/odoo/pull/38459. This PR was fixing 2 scenarios, A (this one) and B (Odoo believes `sales@google.com` is your sales department).
  - Fix for scenario B introduced a BaaS<sup>2</sup> regression https://github.com/odoo/odoo/pull/38459#issuecomment-555598458
  - @tde-banana-odoo tried to add a setting to satisfy everyone in https://github.com/odoo/odoo/pull/41042. Namely, https://github.com/odoo/odoo/commit/8d5dd14e125f5167ea110c6426a0b18c98e57dba<sup>4</sup>. It got rejected.
  - Finally in that same PR, scenario B fix was simply removed; only buggy behavior is supported. Landed in https://github.com/odoo/odoo/commit/52d6f0e3ee90874fc93fec9cdff74ec71d3b991f.
- 12.0:
  - Full fix landed with https://github.com/odoo/odoo/pull/40737
  - Scenario B rollback landed in https://github.com/odoo/odoo/pull/41070
- saas-12.3: https://github.com/odoo/odoo/pull/40821 squashes fix for scenario A + revert for scenario B. It's awaiting @odony approval.
- 13.0: https://github.com/odoo/odoo/pull/40824. Squashed fix<sup>3</sup>. It's awaiting for https://github.com/odoo/odoo/pull/40821.
- saas-13.1: https://github.com/odoo/odoo/pull/46764. Squashed fix<sup>3</sup>. It's merged.
- saas-13.2: https://github.com/odoo/odoo/pull/46780. Squashed fix<sup>3</sup>. It's merged.
- master: https://github.com/odoo/odoo/pull/46784. Squashed fix<sup>3</sup>. It's merged.

There are plenty of other PRs involved, but I think this history highlight the actually important ones.

</details>

Summarizing, it seems this issue (scenario A in 1st PR for v11) is fixed everywhere except in branches 13.0 and saas-12.3.

@tde-banana-odoo, it seems to me that the only blocking point is the inclusion of the extra fix<sup>3</sup> that is awaiting for @odony's review in https://github.com/odoo/odoo/pull/40821 and https://github.com/odoo/odoo/pull/40824. I suggest you to remove that extra fix<sup>3</sup> from those PRs, so you can already merge them and finally close this issue.

---

<details>
<summary>Footnotes</summary>

<sup>1</sup> Including myself, as this keeps happening and is a mess of PRs, commits, rollbacks and ports. :dizzy_face: 

<sup>2</sup> Bugs as a Service.

<sup>3</sup> Actually it includes an additional commit that seems to be trying to fix yet another problematic scenario: https://github.com/odoo/odoo/commit/9c6b904bef1e8cd59a9d737d6557703fe9c79511. But I say "squashed" because scenarios A and B from the original fixes in branch 11.0 are squashed into one.

<sup>4</sup> In OCB we included this very smart patch, respecting @tde-banana-odoo authorship, so we can fix scenario B also with an `ir.config_parameter`. See PRs for details:

- 11.0: https://github.com/OCA/OCB/pull/913
- 12.0: https://github.com/OCA/OCB/pull/914
- 13.0: TODO. https://github.com/odoo/odoo/pull/40824 has to be merged before.

</details>

**Comment by tde-banana-odoo** [comment]
@Yajo 12.3 and 13 PRs have indeed been forward-ported to 13.1+, allowing to pre-test patches. I suppose once it is considered tested enough they will land in 12.3 and 13 .

Like the wise says: you cannot change the wind's direction, you can only adapt your sails.

Or buy a big motor. But that would not be wise because it disturbs fishes.

Cheers,

**Comment by tde-banana-odoo** [comment]
PS: thanks for the summary, this PR becomes quite complicated indeed :D .

**Comment by Yajo** [comment]
Lol thanks. :blush:  

Well, my suggestion about accelerating the merge for 13.0 is because the fix is already is present in 11.0 and 12.0.

I mean, if it is considered stable enough for those older branches, it should be stable enough for 13.0. :man_shrugging: 

If there were any bug, we would have been hit already in 11 or 12, isn't it? And the latest fix for v11 [was merged in november](https://github.com/odoo/odoo/pull/41042#event-2839704809)...
