### ISSUE TITLE
ERROR : print purshase order in frensh

### ISSUE THREAD

**Issue by Menks** [odoo/odoo#40248]
Impacted versions:13

Steps to reproduce: print purshase order in frensh
![Capture](https://user-images.githubusercontent.com/6191474/68849080-5b68a800-06c9-11ea-9239-7800e9d9cdf6.PNG)

Erreur:
Odoo Server Error

Traceback (most recent call last):
  File "/home/odoo/src/odoo/13.0/addons/web/controllers/main.py", line 2031, in report_download
    report_name = safe_eval(report.print_report_name, {'object': obj, 'time': time})
  File "/home/odoo/src/odoo/13.0/odoo/tools/safe_eval.py", line 347, in safe_eval
    c = test_expr(expr, _SAFE_OPCODES, mode=mode)
  File "/home/odoo/src/odoo/13.0/odoo/tools/safe_eval.py", line 206, in test_expr
    code_obj = compile(expr, "", mode)
  File "<string>", line 1
    (object.state in ('draft', 'sent') and 'Demande de Prix - %s' % (object.name) or                 Bon de Commande - %s' % (object.name))
                                                                                                          ^
SyntaxError: invalid syntax

Video/Screenshot link (optional):

**Comment by mart-e** [comment]
Hi,

Thanks for the report, it was due to a bad translation.
I have fixed it at https://www.transifex.com/odoo/odoo-13/translate/#fr/purchase/180739865?q=text%3A'request+for+q'
It will be included in the [next translation synchronisation](https://github.com/odoo/odoo/wiki/Translations#when-will-my-translations-appear-in-the-software-or-in-github)
Best,
