### ISSUE TITLE
[13][mail] Wrong message language

### ISSUE THREAD

**Issue by grzekru** [odoo/odoo#40304]
**Impacted versions:**

13

**Steps to reproduce:**

1. Create two users (internal or portal) with different languages.
For example:
User A with language Polish
User B with language French
2. Add those two users to the same chatter in task.
3. User B writes message
4. User A receive message in french instead of polish.

**Expected behavior:**

User receive message in his own language, not in senders language

**Video/Screenshot link (optional):**

![image](https://user-images.githubusercontent.com/5862658/68900203-9b647500-0733-11ea-9f75-3b6077a94e6c.png)
![image](https://user-images.githubusercontent.com/5862658/68900220-a7503700-0733-11ea-96e8-11ef738f75da.png)

**Comment by pedrobaeza** [comment]
@tde-banana-odoo what do you think about this?

**Comment by Yenthe666** [comment]
@tde-banana-odoo kind reminder, could you check this please?

**Comment by tde-banana-odoo** [comment]
Hello,

Indeed it is a known limitation. If you have a PR to give I would gladly have a look (or if you open an OPW for this). Currently an improvement of the template rendering lies in a backlog to handle in master, no ETA currently as usual for master tasks.

Cheers,

**Comment by Yenthe666** [comment]
@tde-banana-odoo OPW `2153127` 😉

**Comment by Yenthe666** [comment]
Odoo closed off this ticket stating this is not implemented and that it won't be added so let's close off this report too.

**Comment by tde-banana-odoo** [comment]
Hello @Yenthe666 ,

We made some investigations about this ticket. Issue is that we basically have two use cases. Lets have our 2 users, A is in french, B in polish. Both working with emails.

A/ Classic post: A post a message in french, then it is encapsulated in a small layout with header / footer. Currently those are in french. Rendering them in polish as requested here is relevant as polish part contains mostly contextual information and actions.

B/ Post with template linked to another encapsulation template, for exemple "Pay Now" (all "send by emails" action on SO / PO / invoice): A post a message in french, then it is encapsulated in a more complex layout with button, small text and footer. Currently those are in french. Rendering them in polish is wrong as it would lead to emails containing both french and polish text parts which is really strange (and would break an OPW https://github.com/odoo/odoo/commit/9e71d228edb4a4405c6c17fbeabc8f7969c26dc5 ).

Conclusion: choosing one use case breaks the other. We therefore choose to keep the standard behavior: everything is in the language on sender. Supporting both seems unnecessarily complex as it would imply some configuration on templates themselves (and those are already complex enough) or some hardcoded magic.

We know this may be annoying but at least it is consistent, trying to keep sender language instead of having bits of emails in one language, bits in other language.

Thanks,

**Comment by Yenthe666** [comment]
Appreciate the detailed feedback @tde-banana-odoo. Now that I've read your comment you might actually be right that it adds quite some complexity honestly. It is at least good to keep it as-is for stable, who knows for a future version ;)
