### ISSUE TITLE
Multi site product - not possible to choose part of sites. 

### ISSUE THREAD

**Issue by OnePoi** [odoo/odoo#40365]
Impacted versions: 11(?),12, 13

Current behavior:
Now it is only possible to either not assign a site to a product and it will be shown on all, or it is possible to select single. So if you have three sites and want it visible on two it is not possible.
Expected behavior:
Sites should be selectable in same way "Accessory Products" is selected and added to selected websites.
Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
This is something not allowed in standard, so it's not a bug. It can be a wishlist, but not sure if Odoo itself wants that behavior.

@JKE-be can this be something to be considered in the future?

**Comment by Feyensv** [comment]
The generic multi behavior (company, website, ...) does only allow to publish a record on one or all instances ...  It has been chosen that way for performance purposes (less tables and query complexity for many2one than many2many because of the intermediary table needed).
If you want to share a product only on some websites, the only clean way would be to duplicate it IMO.

The current behavior surely won't be changed in stable, and if changed in master, should be done everywhere for coherence (for companies and websites), and would be a huge change.  

I don't think it will be considered soon, but who knows what the future holds :man_shrugging:.

**Comment by JKE-be** [comment]
No we don’t plan to change it for now.

You can use a bom to sell the same product in a second site ... and avoid to duplicate it and manage distinct stock and co !

As explain it is for performance reason and it is a rare usecase ...
