### ISSUE TITLE
superadmin and admin hierarchy issue

### ISSUE THREAD

**Issue by sivaj** [odoo/odoo#4040]
Hi....
i am create super admin account access rights is (admin/setting)
then create admin account access rights is (admin/access rights)

But the hierarchy cannot set...admin change the super admin password and rights.....i don't like this....

i like admin cannot view super admin.....

**Comment by alejandrosantana** [comment]
Same here.
Checked right now at demo1.odoo.com
This way, any user with "Access rights" permissions could hijack 'admin' account by changing its password. Then enter as 'admin' and do whatever she wants.
I would say this is a security hole.
@odony Any idea on this? What about only allowing 'admin' himself to change his own password?

**Comment by odony** [comment]
Indeed, Odoo does not restrict the kind of access rights changes allowed for members of the "Access Rights" group. It's everything or nothing. If you have access to the access rights system, you are allowed to manage users fully (including the Administrator account) and modify any access right. This is by design and is consistent with the rest of the ACL system.

It means that indeed, you should only give the "Access Rights" access to trusted users... which seems natural enough. It's like being a "sudoer" unix account, or a member of the "Administrators" group in Windows, you're allowed to do anything if you need it, even if you're not logged in as the "Administrator" account.

If we prevented changing the admin password or access rights of the admin, it would not prevent users in the 'Access Rights' control group to do anything they like with the database contents - they can grant themselves any access without touching the admin account anyway.

Other permissions systems exist in other software, but that's how Odoo works.

**Comment by alejandrosantana** [comment]
Thanks for the explanation.
