### ISSUE TITLE
[13] email template tools bar missing

### ISSUE THREAD

**Issue by jalzaga** [odoo/odoo#40410]
Impacted versions: 13

Steps to reproduce: edit email template

Current behavior: Tools bar is not shown only the html view is available

Expected behavior: Show tools bar and have the possibility to edit html in developer mode 

Video/Screenshot link (optional):
In version 13: 
![image](https://user-images.githubusercontent.com/7764079/69047426-5eca9f00-09fb-11ea-9539-6ce2a582fbd4.png)

In other versions, e.g. v12:
![image](https://user-images.githubusercontent.com/7764079/69047341-3cd11c80-09fb-11ea-85bb-f5804f58d780.png)

**Comment by Yenthe666** [comment]
@jalzaga thanks for the report. I've already reported this one to Odoo a few days ago actually, under the OPW `2123730` and it is in bugfixing

**Comment by nle-odoo** [comment]
Hi,


The feature of having only source editor if there is multiline template directive (if there is a `% if` or `% set` line inside the template) was introduced in 12.3 version and some changes of 12.3 were reverted in 13.0 version.

This was done because often people would make things like changing the color / size of text or some other things around the directive which would break the template and it would not work when sending the mail.

The changes removed both:

- the source mode and
- this obligation of having the source mode when editing a template with complex templating directives

so when I reintroduced the mode I also reintroduced the "disabling" wysiwyg editor but it does not seem clear so I will see if I can make it clearer or revert it.
