### ISSUE TITLE
Onchange methods don't be executed in existing records on form load

### ISSUE THREAD

**Issue by cmayo** [odoo/odoo#40784]
Impacted versions:

13.0

Steps to reproduce:

For example, in the crm module:

- Create new lead in the crm module using the form.
- Set the `country_id` and the `_onchange_country_id` will be executed to set the domain for the `state_id` field and show only the states for that country.
- Save the lead
- Open again the previously created lead
- The `_onchange_country_id` method is not executed and the `state_id` field shows all the states of all the countries.

Current behavior:

The onchange methods are not executed when load a form of existing records.

Expected behavior:

The onchange methods will be executed when load a form of a existing record. This is need for example in the case metioned above. The crm form of a existing lead would execute the onchange methods to set the domains for the `many2one` fields.

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
This is a known limitation of the current framework, and although I agree it's not the best thing, solving this will require much more load on the form time, and worst, possible conflicts depending on the applied onchange order.

The only workaround with standard for this is to have a domain with `[('id', 'in', computed_field_ids)]`, and have a computed field `computed_field_ids` that gets the corresponding records according current situation.

Closing then as won't fix due to known ORM limitation by the stated above.

**Comment by pedrobaeza** [comment]
FYI, Odoo is changing the approach for not having that dynamic domains in PRs like #40957

**Comment by cmayo** [comment]
Thanks a lot for the help and the information, I'm going to take a look to this PR
