### ISSUE TITLE
[ 8.0 , master ] translation malfunction on website,website-sale,website-crm modules

### ISSUE THREAD

**Issue by vilder** [odoo/odoo#4078]
In the bellow screenshots I choose the Spanish translation which is 100 % translated, but there are
a few words that are always in English.

![untranslated](https://cloud.githubusercontent.com/assets/7828591/5326903/69056164-7d31-11e4-8aef-fabe90131740.png)
![untranslated2](https://cloud.githubusercontent.com/assets/7828591/5326905/6909936a-7d31-11e4-9e64-37d378b7f6ca.png)
![untranslated3](https://cloud.githubusercontent.com/assets/7828591/5326907/690d0a04-7d31-11e4-81fb-5c39b4035b1d.png)
![untranslated4](https://cloud.githubusercontent.com/assets/7828591/5326904/69080964-7d31-11e4-953c-eb9a5f35fbda.png)
![untranslated5](https://cloud.githubusercontent.com/assets/7828591/5326908/6911c210-7d31-11e4-8814-04772b21d48e.png)
![untranslated-crm](https://cloud.githubusercontent.com/assets/7828591/5326906/690b970a-7d31-11e4-986a-a683ba61eb6a.png)
![untranslated-shop](https://cloud.githubusercontent.com/assets/7828591/5326909/691be43e-7d31-11e4-8d25-297327010061.png)
![untranslated-tutorial](https://cloud.githubusercontent.com/assets/7828591/5326910/691fb730-7d31-11e4-9081-fe3c550161b1.png)

**Comment by Yenthe666** [comment]
Hi @user,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment). Quite a lot of these translation terms have been fixed in the meanwhile though.
If you can still find missing ones in Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
