### ISSUE TITLE
https://pendulum.eustace.io/

### ISSUE THREAD

**Issue by blaggacao** [odoo/odoo#41145]
A _suck-less_ `datetime`.

... write-up, bla ...

@xoe-labs

**Comment by Yenthe666** [comment]
I assume you're still going to add info here & that this is just a placeholder? :)

**Comment by Yenthe666** [comment]
@blaggacao can you add extra info to the ticket please?

**Comment by blaggacao** [comment]
https://pendulum.eustace.io/

Fortunately, it's self explanatory.

**Comment by Yenthe666** [comment]
Well I'm pretty sure this'll be denied but lets call @mart-e to decide :)

**Comment by mart-e** [comment]
Hi,

If you search a bit in the history of PRs, you will find #24125 where we made an experiment using pendulum (the Research part in "R&D") but we dropped it in the end as we wanted to be still compatible with naive datetime objects.
A bit sad because pendulum was an interesting option but too much drawbacks as explained on the PR.

**Comment by blaggacao** [comment]
@mart-e Thanks for your explanation. Yes a bit sad. Maybe you bother to comment: why are external dependencies considered so much of inconvenience? It seems like a repeating design guideline. Theoretically, Odoo could just offer to take over maintenance, if it's really a good library maintained by a Singleton and earn the banana of beein a good open source ecosystem player.  My 2 cents.

**Comment by mart-e** [comment]
@blaggacao I can not really comment because I have not participated in the decision but I think the main problem was to no longer work with standard date objects. My don't take my word for credit.
