### ISSUE TITLE
l10n_de: Bank / Accounting

### ISSUE THREAD

**Issue by philku79** [odoo/odoo#41894]
Impacted versions: 13

Steps to reproduce: Use german translations and try to create a new bank

Current behavior: wrong translations
"Einen Bank erstellen" in` ir.actions.server,name` and `ir.ui.menu,name` in File `odoo/addons/account/i18n/de.po:msgstr "Einen Bank hinzufügen`

"neues Bankkonto hinzu fügen" in` addons/account/i18n/de.po:msgstr`

Expected behavior: correct translations
"Eine Bank hinzufügen" and
"Neues Bankkonto hinzufügen"

Video/Screenshot link (optional):

**Comment by philku79** [comment]
I can provide a PR for the fixes in german translation files.

**Comment by Yenthe666** [comment]
Hi @philku79,

Wrong translations are no longer managed/fixed/changed through PR's. They're now directly modified on Transifex, the translation platform for Odoo. For more info see https://github.com/odoo/odoo/wiki/Translations#translating-with-transifex
Closing as this can only be fixed in Transifex and as you can do it :)

Regards,
Yenthe

**Comment by philku79** [comment]
@Yenthe666 thanks - just applied to the translating team to fix the wrong german translations - as soon as i am allowed to, i will fix them.

**Comment by Yenthe666** [comment]
Awesome, thanks for the report & already a thank you for fixing it ;)
