### ISSUE TITLE
Can't use & operator for the same field in search filters

### ISSUE THREAD

**Issue by mmcdevelopments** [odoo/odoo#41983]
Impacted versions:
10.0
Steps to reproduce:
I want to search an oportunity that have this two tags: "IPC" and "BCN"
1. Create new search filter in configuration, user filters, the example for Lead/Oportunity
2. Set domain to: [u'&', [u'tag_ids', u'ilike', u'ipc'], [u'tag_ids', u'ilike', u'bcn']]
3. Use created search filter in opportunity pipeline.
Current behavior:
When I apply search I gut opportunity with (IPC or BCN) but not (IPC & BCN):
![image](https://user-images.githubusercontent.com/56870492/70979510-119d2400-20b2-11ea-8dda-12796b6c430e.png)
 
Expected behavior:
When I search I have to get only opportunities with (IPC & BCN) tags. Something like this (image edit):
![image](https://user-images.githubusercontent.com/56870492/70980205-35149e80-20b3-11ea-800e-08b6feb6e635.png)

Video/Screenshot link (optional):

**Comment by kos94ok-3D** [comment]
Hi @mmcdevelopments 
It is impossible with one filter because conditional applies per tag.
You have a record with two tags "IPC" and "BCN".
Your filter does:
1) check "IPC": "IPC" == "IPC" and "IPC" == "BCN" -> False
2) check "BCN": "BCN" == "IPC"  and "BCN" == "BCN" -> False
3) exclude record

You have to create two filters like this:
![изображение](https://user-images.githubusercontent.com/33932458/70993175-183c9300-20d4-11ea-9e4a-36d73a6af7e8.png)

**Comment by mmcdevelopments** [comment]
Hi @kos94ok-3D 
Finally, I've decided to add two additional fields of search next to "tag_ids" that filter the same field:
![image](https://user-images.githubusercontent.com/56870492/71009288-43ca7800-20ea-11ea-8cbc-199422f1920f.png)

This way search more flexible and voiding to create lots of filters for all tags. That's result:
![image](https://user-images.githubusercontent.com/56870492/71009438-7f654200-20ea-11ea-853e-dd1aa688b98b.png)

Thank you so much for your help.
