### ISSUE TITLE
V13 Js error on Accounting -> Journal Items

### ISSUE THREAD

**Issue by bumblebeey** [odoo/odoo#42149]
When i try open journal item from **Accounting -> Journal Items** view show .js error. 
after activating debug mode with assets, console show error "**Error: Unknown field state in domain**"
in /web/static/src/js/core/domains.js line 68

` if (!(this._data[0] in values) && !(isParentField)) {
                throw new Error(_.str.sprintf(                   <- Line 68
                    "Unknown field %s in domain",
                    this._data[0]
                ));
            }`

error log is clean.

**Comment by pedrobaeza** [comment]
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by bumblebeey** [comment]
Hi again pedrobaeza thank you for your interest and attention me, i check custom addons. you are right. OCA bank account_payment_partner addon is problem. thank you again.
