### ISSUE TITLE
[8.0] Cannot redefine a field having an en_US translation

### ISSUE THREAD

**Issue by yvaucher** [odoo/odoo#4246]
If I create a en_US.po, it will work to override any translation. However, if I try to edit an object it will rewrite only base string and not it's en_US translation. Thus, the user won't see his edition.

What I expect is that if en_US translation exists when a user has English (en_US) set in preference, edition of the term in form will edit both base string and translation value.

To reproduce this effect you can
- Go on runbot last 8.0 build.
- Install a second language
- Ensure your user has `Technical Features` enabled
- Go to product category "All"
- Create an english translation for `name` field (Click on translation button and turn to **form view** to create a new translation)
  
  Translated field: product.category,name
  Language: English
  Module: product
  Type: Object
  Record ID: 1
  Source Term: All
  Translation: Everything
- Save it
- Return on product category. It is correctly renamed.

Now, try to rename it to "Hello" directly from product category form view, without using translation view. 
### What happens

You won't be able to rename it anymore.
You can change the value in `name` field, however once you save it, it will return to new translation value ("Everything" in our case)

And if you look at translations, source is "Hello" and english translation is "Everything"
### What I expect

Field is changed when saved. Opening translation should show translated value as value entered in form for product category field `name`.

**Comment by gurneyalex** [comment]
Would it not be easier to have a 'C' locale corresponding to the untranslated strings from the source code, as is the common practice in the gettext world?

**Comment by gurneyalex** [comment]
@rco-odoo hello, do you have any update on this issue?

**Comment by odony** [comment]
This begs the question of *why* you would want to create en_US translations for overriding record fields instead of setting their values directly? Creating en_US entries explicitly is useful for hardcoded strings that cannot be changed dynamically, but makes less sense for records (`Object` translations) which could simply be edited.
One reason that comes to mind is that you might have expected to put all your translation overrides in a single PO file, and you currently need to use an extra data (CSV/XML) file to set the record field values.

Perhaps an extra data file wouldn't be such a bad idea, as you're overriding record values, and it would behave predictably (w.r.t updates, `noupdate` flag, etc.), whereas translation management/updates is a bit specific. In fact the same could be done for other languages, as you can specify the context language to use when importing XML data (`<record context="{'lang': 'fr_FR'}"`>).

Now I agree that "reading" the en_US overrides for `Object` translations in the UI while not allowing to "write" them is not consistent. But we should perhaps get rid of the "reading" part here instead of adding a corner case to the writing part. This would avoid creating useless `ir.translation` entries, and would not break other languages because the `src` value for `model/Object` translations is ignored anyway, it does not have to match. Thoughts?

**Comment by Yenthe666** [comment]
Hi @yvaucher ,

Thank you for your bug report.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.
P.S: I think odony gave quite a good answer too.

Regards,
Yenthe
