### ISSUE TITLE
[13.0] mass_mailing: Couldn't change 'Recipients' to Mailing List if domain is applied

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#42883]
Impacted versions: 13.0

Steps to reproduce: Create Mailing Record (For Contact or Sale order) --> Apply some domain
![Screenshot (54)](https://user-images.githubusercontent.com/16624719/71915124-1892f000-31a1-11ea-905f-b21c62b777e0.png)

Current behavior: Change Recipients Type to Mailing List
![Screenshot (55)](https://user-images.githubusercontent.com/16624719/71915150-2a749300-31a1-11ea-96f4-6034e4c85f61.png)

Server Log 
```
  File "/home/sswapnesh/WorkSpace/odoo/odoo/osv/expression.py", line 855, in parse
    raise ValueError("Invalid field %r in leaf %r" % (left, str(leaf)))
ValueError: Invalid field 'active' in leaf "<osv.ExtendedLeaf: ('active', '=', True) on mailing_contact (ctx: )>"

```

On Save
![Screenshot (56)](https://user-images.githubusercontent.com/16624719/71915216-49732500-31a1-11ea-81b2-2d45e17ade8b.png)

Expected behavior: Remove domain and Save Record

Video/Screenshot link (optional):

**Comment by sswapnesh** [comment]
@tde-banana-odoo  Not sure if this can be the Solution https://github.com/odoo/odoo/pull/25663

**Comment by tde-banana-odoo** [comment]
Hello,

In master (target 13.2) mailing domain is now a computed field, and changing the model resets the domain, see notably https://github.com/odoo/odoo/commit/ffe1d4047da181f97fafe2a69f64e6f283fbeb0e (onchange -> compute) and https://github.com/odoo/odoo/commit/110decad006c89c6462308245a4f295c5bf570f5 (domain reset). However this latter commit is a bit too broad for a stable.

Mailing domain are a bit harsh to use since they have been introduced. I would vote to avoid changing it in stable, as master version now correctly resets it and also uses interesting default domains based on mail / phone blacklist, opt-out, ...

Thanks,

**Comment by sswapnesh** [comment]
In that case we can tag this as Won't Fix nd close it.
