### ISSUE TITLE
[13] account: Payment link is not updated on Changing amount 

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#42891]
Impacted versions: 13.0

Steps to reproduce: 
![Screenshot (65)](https://user-images.githubusercontent.com/16624719/71926462-63206680-31b9-11ea-8cac-a748967e8796.png)
![Screenshot (66)](https://user-images.githubusercontent.com/16624719/71926476-6f0c2880-31b9-11ea-9bad-610ed37a1313.png)

 Change Amount and Click on Copy Button
![Screenshot (67)](https://user-images.githubusercontent.com/16624719/71926548-9662f580-31b9-11ea-9b27-8ae9c0bbb66d.png)

Current behavior: Link is Copied with Old Amount

Expected behavior: Link should be updated with new Amount

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
@dbo-odoo is this for you?

**Comment by dbo-odoo** [comment]
It is.

I'm aware of this behaviour, which is a bit annoying indeed. However, I'm afraid that's just how the framework behaves: the onchange is only called when there's a blur event on the amount field. While it would be nice to have the amount update live, it would necessitate more JS override for the view than I believe is justified.

The behaviour is not error-inducing imho, since the onchange happens when you try to click on 'copy'. In that case, the value is not actually copied if the onchange is not finished, so you'll need to re-click on copy to get the value - which has been updated with the correcty value in that interval. You can't copy the wrong value when the onchange is happening, so besides having to click twice, it doesn't impact anything.

Annoying? A bit.
Error-inducing? No.
Justifies rewriting the form controller of the wizard for that? Not in my opinion.

I am more annoyed by the display issue, honestly :p I thought we'd fixed it, but it was done in master and not in 13.0. I'm going to backport 92c26dff5 to 13.0, since it's a really small change.

**Comment by sswapnesh** [comment]
Clicking on Copy twice works but How to explain this annoying Behavior to Customers 🤔

**Comment by dbo-odoo** [comment]
"The link will only update once the amount has been processed, which only happens when you click outside of the 'amount' field." is how I would put it.

Regarding your comment on the PR, you're right about the won't fix tag, but it's a justification for a closed issue. I see no reason to leave open an issue that we won't fix :p
