### ISSUE TITLE
[8.0] _inherits on a model that already use _inherits sorting column fails

### ISSUE THREAD

**Issue by komsas** [odoo/odoo#4308]
Example:
do _inherits on the project.project and try on a new model to order/sort column in a list view by e.g. 'name' field.
```
class NewModel(models.Model):
    _name = 'new.model'
    _inherits = {'project.project': "project_id"}
    _inherit = ['mail.thread', 'ir.needaction_mixin']

    project_id = fields.Many2one(
        'project.project', string='Project', ondelete="cascade",
        required=True)
```

**Comment by xmo-odoo** [comment]
Under the hood, _inherits simply creates a bunch of related fields, which are a variant of (non-stored) function fields. Because sorting is performed in SQL, non-stored function fields can not be sorted.

I believe we had a wishlist issue on the subject (of being able to sort on non-stored function fields) in the previous tracker, feel free to open a new one but I would not expect this to be changed in the short or medium run.
