### ISSUE TITLE
http.route type=json no csrf verification

### ISSUE THREAD

**Issue by fr3aker** [odoo/odoo#43151]
Impacted versions:
11.0+

On http controller endpoints with `type="json"` no CSRF token verification is performed. I am not sure if this is intentional but undocumented or a bug. Right now the documentation does not mention any such restriction which may lead developers to erroneously assume CSRF verification is performed.

To be honest I'm not clear at all what the `type="json"` endpoint is supposed to be used for at all, since it assumes JSON-RPC communication but not through the actual odoo JSON-RPC interface(?). But that is probably nothing to be discussed here.

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.

**Comment by fr3aker** [comment]
uhm, this is at least a lack of documentation that can lead to security vulnerabilities.

**Comment by pedrobaeza** [comment]
AFAIK, crsf protection is enabled by default.

**Comment by ryanc-me** [comment]
Just FYI, and for the sake of posterity, you can see from the [`JsonRequest` definition](https://github.com/odoo/odoo/blob/14.0/odoo/http.py#L552) that CSRF tokens are definitely _not_ validated (for reference, the `HttpRequest` class validates CSRF tokens [here](https://github.com/odoo/odoo/blob/14.0/odoo/http.py#L772)).

Perhaps this is because JSON routes are typically used with JSON-RPC, where the user session is authentication anyway?

Either way, it would be very nice if JSON routes did support CSRF tokens, even if it were opt-in for JSON routes.
