### ISSUE TITLE
12.0 _get_payment_type defined twice

### ISSUE THREAD

**Issue by omalbastin** [odoo/odoo#43445]
https://github.com/odoo/odoo/blob/4f6417b715cfebfa75d939797d935e0d008f854a/addons/sale/models/sale.py#L136

 and

https://github.com/odoo/odoo/blob/4f6417b715cfebfa75d939797d935e0d008f854a/addons/sale/models/sale.py#L930

**Comment by Elkasitu** [comment]
But does this yield a bug within Odoo? Otherwise it just seems like the second definition supersedes the first and seems to be the more correct of the two, making the first definition dead code, which is unfortunate but not worth making a patch for in a stable version

/cc @seb-odoo @rdeodoo Since you guys wrote / merged [this](https://github.com/odoo/odoo/commit/34c47eecd30bdf66bc057bf285a51cff956cd0e8#diff-39d0613187d36f16c541734e80925e9dR891-R894) after [this](https://github.com/odoo/odoo/commit/3504529fb5d8b2fa8c6fce862e4979b3dbb43c64)

**Comment by omalbastin** [comment]
@Elkasitu not a bug. but confusing.

**Comment by seb-odoo** [comment]
Probably a mistake on my part indeed. The duplicate is removed in v13 too, the last one was kept.
