### ISSUE TITLE
[Wishlist][12.0/13.0] Product description field on Stock Pickings

### ISSUE THREAD

**Issue by reinaldoramosarxi** [odoo/odoo#43648]
Hello,

While implementing some of our stock modules, we have noticed that we'll need to implement descriptions in stock.picking product lines.

We realize that those lines may be created from several lines, but we figured that an empty, editable description field would be useful in the long run.

Could this maybe be implemented in a future update?

Thank you.

**Comment by pedrobaeza** [comment]
I agree. Meanwhile, you can use https://odoo-community.org/shop/product/stock-picking-report-custom-description-4551

**Comment by sle-odoo** [comment]
Hi,
There's already a field for this purpose in v13,  `description_picking`.

Regards

**Comment by pedrobaeza** [comment]
Hi @sle-odoo, thanks for telling us. The problem is that such field has several problems:

- If you change the description in sales order:

  ![Selección_003](https://user-images.githubusercontent.com/7165771/72937599-b83bab00-3d69-11ea-88d0-4e7191f297c7.png)

  the description in picking is not filled with that custom description, but another that I don't know where it comes from (product name without reference):

  ![Selección_004](https://user-images.githubusercontent.com/7165771/72937666-d73a3d00-3d69-11ea-8172-e9bf002cfa93.png)

* The description is not printed any way in delivery slip:

  ![Selección_005](https://user-images.githubusercontent.com/7165771/72937776-0a7ccc00-3d6a-11ea-8394-76d0a5ec3ec0.png)

  ![Selección_006](https://user-images.githubusercontent.com/7165771/72937840-297b5e00-3d6a-11ea-80b8-32f4f4152321.png)

**Comment by sle-odoo** [comment]
> the description in picking is not filled with that custom description, but another that I don't know where it comes from (product name without reference):

- It comes from the product form view for default values but is editable on a picking basis
- If we do use the description from the so, it will never use the default values (since the description is automatically filled with the product name)

> The description is not printed any way in delivery slip:

It should be, are you sure you did not print the picking report?

**Comment by sle-odoo** [comment]
@pedrobaeza actually we had to fix a few things
see 2142647ad6b0c0521a1b834c159139bec7b3149d and 5d08bdfb0430d9e65cfd9cdd3e129d33f2b4e497

**Comment by Yenthe666** [comment]
Aha I was just about to report a problem with the `move_ids_without_package` which is fixed in your commit. Thanks :)

**Comment by pedrobaeza** [comment]
Great, thanks!! 

I still think we should handle the custom description from sales order to picking. There are several reasons for that:

* Custom description for adding details. A lot of people don't want to create specific products for little variations of the same product and want to put them on the sales order description (I know it's not the best practice, but the other one creating thousand of products is also not good).
* Specific language stuff (that is not on the product translations). Imagine the case that you don't want to load an specific language only for one order but you want to put the product description in that language.
* Others that for sure we haven't thought about.

My proposition: when creating the stock.move, check if the sale.order.line description is the same as the automatic one, and if not, then propagate that description.

**Comment by sle-odoo** [comment]
we're kind of doing that in https://github.com/odoo/odoo/pull/34174 but it still needs to be reviewed because we're adding a new description field sadly :(

**Comment by pedrobaeza** [comment]
Then please take into account my comments. I can PR anything if you want.
