### ISSUE TITLE
[11.0] Unable to navigate to sale order from Product → Sales

### ISSUE THREAD

**Issue by rajeeshknambiar** [odoo/odoo#43734]
Impacted versions: 11.0

Steps to reproduce: Install `Sales` module. Create a product and create a sale order for the product. Go to `Sales → Catalog → Products` and select the product. Click on the button `Sales` (`action_view_sales`)to display the list of orders. Click on any lines to and you expect it to take to the particular sales order.

Current behavior: Nothing happens. Not able to go to the sales order selected/clicked.

Expected behavior: Navigates to the clicked sales order.

Video/Screenshot link (optional):

**Comment by mart-e** [comment]
hi,

This is because this action lead to sale order lines, not sale orders. We do not have any view to visualise sale order lines so it's not clickable. The action leads you to the lines where the product was sold but not the actual orders.
It's a known limitation and maybe it will be improved by the sale team for a future version (cc @tde-banana-odoo ) but it's a new feature, it's not something we are going to change in stable version, especially the 11.0 that is end of life, sorry.

**Comment by Yenthe666** [comment]
I still think we should have a menu for sale order lines honestly, along with a pivot & graph view on it. Nearly every customer I work with asks it.
