### ISSUE TITLE
Odoo Breadcrumb should be proper.

### ISSUE THREAD

**Issue by gbhagwan** [odoo/odoo#44191]
Impacted versions: 12

Steps to reproduce: 
 1. Create Invoice.
 2. Add note in log note from the chatter.
 3. Click on notification option from header.
 4. Click on "invoice" notification.
 5. Repeat step 3 & 4 for multiple times. 

Current behavior: 
 Multiple times "invoice No " is getting displayed in breadcrumb.

Expected behavior:
It if click on multiple times then also it should display single "invoice No" in the breadcrumb.

Video/Screenshot link (optional):
![Screenshot (24)](https://user-images.githubusercontent.com/60430612/73355579-70afa480-42be-11ea-992a-7648b6fd30d8.png)
![Screenshot (25)](https://user-images.githubusercontent.com/60430612/73355580-71483b00-42be-11ea-8af8-ad8565b66f08.png)

**Comment by pedrobaeza** [comment]
The behavior is correct because you are stacking multiple openings of the same object. An optimization can be done for not stacking it if the record is the same, but there are more factors that are involved (like the opened action and context), so it's risky to assume that.

Closing due to the reasons explained.
