### ISSUE TITLE
Sale Order. Price recalculate on pricelist change. 

### ISSUE THREAD

**Issue by tigrus** [odoo/odoo#4428]
**Entry point**: 
We have 2 pricelists in different currencies(EUR & USD). 
Sale module installed.
" Use pricelists to adapt your price per customers" feature enabled in settings. 

**Steps to reproduce**: 
1. Create sale order 
2. Set customer 
3. Pick pricelist in USD
4. Add items to order 
5. Change pricelist to EUR

**Result**:
Currency sign in total field changes. Price stays the same. 

**Expected Result**:
Currency sign in total field changes. Price recalculates to EUR.

**Comment by javieralmancevo** [comment]
I can confirm this bug.

It happens also if you dont select a pricelist, add lines, they will show costing 0 because there is no pricelist, and when you select a pricelist the price remains 0.

I have checked the code of the sale module and there is no onchange_pricelist() or similar. It seems the functionality is just missing. This function is needed, but it would also be positive to not allow to introduce any line until a pricelist or a client (which automatically sets a pricelist) has been selected. It is confusing to add lines and have they cost 0.

**Comment by gdgellatly** [comment]
This so called bug gets raised every few months. It isn't. I raised it 6
years ago myself. @odony kindly wrote a module for me at the time,
sale_pricelist-recalculation. There are just as many scenarios where your
desired behaviour would be considered a bug. Also where does it then stop.

What if I'm doing purchases and change partner. Do I update all the product
codes?

If I change fiscal position on an invoice?

Hopefully you can see that the requested behaviour is quite inconsistent
with everything else. Fixing your specific issue the way you want makes
problems for others.

Better to put a button to do that change.

On Wed, 9 Dec 2015 2:48

fi

AM javieralmancevo <notifications@github.com> wrote:

I can confirm this bug.

It happens also if you dont select a pricelist, add lines, they will

sho

costing 0 because there is no pricelist, and when you select a pricelist
the price remains 0.

I have checked the code of the sale module and there is no
onchange_pricelist() or similar. It seems the functionality is just
missing. This function is needed, but it would also be positive to not
allow to introduce any line until a pricelist or a client (which
automatically sets a pricelist) has been selected. It is confusing to add
lines and have they cost 0.

—
Reply to this email directly or view it on GitHub
<https://github.com/odoo/odoo/issues/4428#issuecomment-162884350>.<img src="
https://ci4.googleusercontent.com/proxy/kCib8lpzzpoI2Z0WTaCJrXdZv3A28R6JcrXiP8IKwbiLMSyVTLt5Gc5ZmBj5WvutI_5d0V2xJKwtKAgllFZjd3dgEmsDbMVeBUvCU4JYv38cq5DkMePaGgDM9sZ8Kqs2XtUSrwQrYCKT6C9KqGlvl_Oxu_zkcw=s0-d-e1-ft#https://github.com/notifications/beacon/AE23kLHnm5Sbflkp9wZ7EgjuazNDv46Bks5pNtccgaJpZM4DMMVI.gif
">

**Comment by Yenthe666** [comment]
Answered by (@)gdgellatly and this version is no longer supported.
