### ISSUE TITLE
Access Denied  The requested operation cannot be completed due to security restrictions. Please contact your system administrator.(Document type: Email composition wizard, Operation: create)

### ISSUE THREAD

**Issue by Mbunto** [odoo/odoo#4437]
I duplicate the Administrator account
I log with the new account
From the menu Human Resource / Job Positions
I click on a Job Positions
I chose one application from this job position
and when I want to move to the first interview I have this error
Access Denied
The requested operation cannot be completed due to security restrictions. Please contact your system administrator.(Document type: Email composition wizard, Operation: create)

Anybody can help me to solve this issue

**Comment by vitasoa** [comment]
Hi,
I've the same problem in my openerp 7 installation, have you managed it?

**Comment by sjpatel21** [comment]
I am too facing this Issue in Odoo 8 with latest updates,  when HR Manager tries to change the state of an hr application, and an email template is tied with that state. It says

File "/home/sunny/project/odoo/odoo_8/odoo8/addons/mail/mail_message.py", line 777, in check_access_rule
    (self._description, operation))
except_orm: (u'Access Denied', u'The requested operation cannot be completed due to security restrictions. Please contact your system administrator.\n\n(Document type: Email composition wizard, Operation: create)')

**Comment by Yenthe666** [comment]
Hi @Mbunto ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 7 & Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe

**Comment by samwitney** [comment]
I have the same Issue on odoo 11

**Comment by Agacolor** [comment]
Confirmed still same problem in V12 enterprise (but no longer supported so we'll have to use the super user workaround )
