### ISSUE TITLE
[8.0] Bank statement operation VAT included in price not working

### ISSUE THREAD

**Issue by sbidoul** [odoo/odoo#4452]
Hi,

While looking for a workaround for #4450, I tried with a VAT Included in price tax such as this one:
![image](https://cloud.githubusercontent.com/assets/692075/5569764/6e037ed8-8f76-11e4-888f-e063b96cb9a2.png)

When using such a tax in a statement operation, things look good in the reconcile screen:
![image](https://cloud.githubusercontent.com/assets/692075/5569768/84675afa-8f76-11e4-9ee3-acc7c03c04a4.png)

However, the generated moves are incorrect:
![image](https://cloud.githubusercontent.com/assets/692075/5569775/aa7eda06-8f76-11e4-84ab-7971b7c39455.png)

**Comment by Whisno** [comment]
Ouch. Actually, what happens is that the tax has no base code or tax code defined.

When creating an account.move.line with a tax, if there is no base code the base line is not adjusted and if there is no tax code the tax line is not created. (funny things happen if you have either base code or tax code but not both)

However, invoices do not behave the same way because of the account.invoice.tax intermediary. In case of an invoice, the move.lines will just be created without the tax code.

So basically, the tax is properly configured to be used as a parent tax but is not properly applicable as is.

We definitively should throw an exception if creating a move line with a tax that has base code XOR tax code. But I don't know what to do when there's neither base code and tax code. Invoices accept it so forbidding it in a stable version might be a bad idea. On the other hand, allowing it by default doesn't seem really safe either.

In V9, this issue will be fixed by the new tax system. For V8, do you think we should allow move.lines creation with no base code and tax code ? Or something else ?

**Comment by sbidoul** [comment]
@Whisno I think move.lines with no base code and no tax code can happen: for instance with eco taxes wich do not impact the VAT declaration. In such case we just want to put the tax amount on a different account and leave the tax code alone.

**Comment by Whisno** [comment]
Ok, so let's go for : invoices behavior remains unchanged, move lines creation with a tax that has both base code and tax code or neither is permitted, otherwise it throws an exception. Thank for this minesweeping !
