### ISSUE TITLE
QWeb loop cannot set value to vaiables outside the loop

### ISSUE THREAD

**Issue by pishpecki** [odoo/odoo#4461]
Hello. I have foud this example on the forum:
```
<t t-set="i" t-value="1"/>
<tr t-foreach="o.order_line" t-as="l">
                        <td> <span t-esc="i"/> </td>
    <t t-set="i" t-value="i+1"/>
</tr>
```
Any value to a variable set inside the loop, exsists only as loong as the loop exsists. If you try: <span t-esc="i"/> after the loop, you will see that the value is again 1.  You cannot set the value of variable declaired outside the loop. Is this the correct place to report htis bug?

Regards

**Comment by OpenCode** [comment]
I confirm this bug. It's not a "wishlist" bug. We need to write reports and this feature is important FOR US!

**Comment by dreispt** [comment]
I'm also facing the issue. Best workaround I found is quite ugly - repeat the loop at the report footer. 
Example:

                    <t t-set="total" t-value="0" />
                    <t t-foreach="o.message_follower_ids" t-as="f">
                        <t t-set="total" t-value="total+1" />
                        <t t-if="f_last">
                            <strong><p class="text-right"><t t-esc="total"/> followers</p></strong>
                        </t>
                    </t>

**Comment by asofan** [comment]
Does anyone from Odoo care to comment on this?

**Comment by andrea4ever** [comment]
I also confirm this bug. Please resolve ASAP!

**Comment by Yenthe666** [comment]
The bug is still here and is a rather big problem. This shouldn't be labelled as 'Wishlist' but as a bug..
Is there any planning on when this will be fixed?

**Comment by pishpecki** [comment]
Here is a workaround. If you need to set a value on a variable do a lambda function returning a single value. For example I want to check if a product in  sales order line belongs to a certain group, and if so do make a "div" visible I would put t-if tag on the div like so:

t-if=" True in [z.product_id.categ_id.name == 'WiMax' for z in o.order_line]"

Hope this helps to somebody.

**Comment by OpenCode** [comment]
@pishpecki We are tired to use workarounds everywhere. We use your code, too. But if a feature exists, it must works! This is not a "wishlist" bug.

**Comment by Yenthe666** [comment]
I agree with @OpenCode.. why should we keep trying and keep building workarounds when this are 'default' features in Odoo?
When it is built by Odoo and it is not working it is a bug. Not a wishlist..

**Comment by asofan** [comment]
It has been a month and no one from odoo cares to comment on this???!!!

**Comment by smack815** [comment]
Odoo accepts pull requests or for anyone with a maintenance contract unlimited bug fixes ;)

**Comment by Yenthe666** [comment]
@sle-odoo can you give an update on this please?
@odony could you review this.. I honestly think this should be handled as a bug, not wishlist.
@smack815 I don't even think this would fall under bug fixes lol. If they would accept this as an option for a bug fix they're literally saying it <b>is</b> a bug. While they've set it as 'Wishlist' here. And honestly for this one I have no clue how to fix it..

**Comment by yvaucher** [comment]
@antonylesuisse ping

**Comment by odony** [comment]
The reason it was working like this is to avoid leaking all the `$as_*` [internal values](https://www.odoo.com/documentation/8.0/reference/qweb.html#reference-qweb-loops) of the `foreach` loop. The implementation can be changed slightly to propagate changes to variables that were defined outside the loop, while still avoiding the leak, with minimal risk. A tentative patch is available [here](b2c0b4e9edc9c439c9a868d39356b7c442f3e253), to be ported to 8.0 soon.
Other more advanced changes (such as using an internal `loop` object with properties as in Jinja2) cannot be implemented in 8.0 as they would break all existing templates.

That being said, the issue seems inflated by a series of invalid use cases, making it look like a bigger shortcoming than it is (hence the wishlist flag). For instance, I'm surprised to see that all the examples in this thread illustrate wrong use cases. QWeb is a templating language, meant to be used for presentation, not for business logic such as sums, etc. And if there is no function field for the sum you need, why not call the model's `read_group()` method with a proper domain and field, and print the result? You're not saving any performance by trying to accumulate the results yourself in QWeb, it's just more error-prone: no decimal precision, no rounding, etc.

Finally, if you absolutely need to compute a value in QWeb, why not use a sensible Python expression such as: 
```html
   Total: <t t-esc="sum(l.amount for l in object.lines)"/>
```
or 
```html
   # Followers: <t t-esc="len(object.follower_ids)"/>
```
rather than accumulating the result using a loop?

**Comment by smack815** [comment]
@odony @JKE-be I think most of us **armchair developers** are honestly ignorant of what can be done in odoo.  That is why the Technical documentation that is being developed is so valuable.  Your comments should be added to the documentation as examples to keep people from writing inefficient, error prone code.

Ignorant does not mean stupid just not properly educated ... until now.  Thanks for responding to your community!

**Comment by alejandrosantana** [comment]
@odony I agree with @smack815 These kind of things should add up to technical documentation.
It has been discussed many times, but a *complete* technical documentation explaining *all* the possibilities of Odoo saves us and you a lot of time and pain. Better documentation, better code, better developer experience, less errors, less bugs, less hours spent by you.

**Comment by smack815** [comment]
@alejandrosantana considering we went from little technical documentation to what we have now in 6 months... the Odoo development ecosystem is getting much better.  I would hope that the community has patience for developers to continue to write these types of documents.  But it is very clear that the community needed this resource badly.

Thanks for all you guys do and educate us a little every day, and we will help educate the next generation of odoo developers.

**Comment by rupalipalshikar1** [comment]
@odony Thank you very much.Your solution helped us to solve our problem.

**Comment by shefalishirodkar** [comment]
Hey @odony  your solution proved to be the best solution. It helped me to solve my issues.:)

**Comment by sehrishnaz** [comment]
working with qweb loops: https://learnopenerp.blogspot.com/2020/08/create-custom-report-in-odoo-using-qweb.html
