### ISSUE TITLE
Missing indexes on stock_move_line

### ISSUE THREAD

**Issue by MeeleCode** [odoo/odoo#44623]
Impacted versions: 13.0 Community

I've been doing some stress testing of stock module using Locust and there is a problem with reserving/finishing pickings after a couple of 100K pickings have been created in Odoo. The actions slow down because of missing indexes on stock_move_line on fields picking_id and result_package_id (picking_id is more important).
I've done testing from 50 to 800 parallel users in multicompany setup who create and validate incoming and outgoing pickings. After I've reached about a couple of 100K picking the actions slow down and it is especially visible after I've reached 1MIL of pickings.
This is the locust graph showing response times before and after the two indexes were added:
![Index problem](https://user-images.githubusercontent.com/30649715/73821981-6842f680-47f5-11ea-80dd-ad7646cb8f7d.png)

So, you should add "index=True" to the fields picking_id and result_package_id in the stock_move_line file in stock module:
picking_id = fields.Many2one('stock.picking', 'Stock Picking', auto_join=True, check_company=True, **index=True**, help='The stock operation where the packing has been made')
result_package_id = fields.Many2one('stock.quant.package', 'Destination Package', ondelete='restrict', required=False, check_company=True, **index=True**, domain="['|', '|', ('location_id', '=', False), ('location_id', '=', location_dest_id), ('id', '=', package_id)]", help="If set, the operations are packed into this package")

**Comment by pedrobaeza** [comment]
@carlosdauden didn't you propose these indexes for 11.0 and were accepted?

**Comment by Yenthe666** [comment]
@sle-odoo this is for your interest

**Comment by MeeleCode** [comment]
@Yenthe666 thank you for tagging @sle-odoo 
Hi Simon, we were talking about concurrent updates during Odoo Experience 2019, this is another problem that I've found while testing stock and it think that this indexes could be very useful.

**Comment by carlosdauden** [comment]
Finally, I only did propouse sale_line_id index:
https://github.com/odoo/odoo/pull/25985

**Comment by odony** [comment]
Thanks for the documented case! We're likely to index those fields, but we'll need to determine whether to index them individually or with a composite index (which would waste less space, but may not work depending on the kind of query).

PS: your graphs seem to indicate saturation on the Locust side, otherwise you should see a bump in RPS after adding the indexes, shouldn't you? Might be worth a look... Increasing the Locust resources could avoid saturation and allow you to really simulate that many parallel users.

**Comment by MeeleCode** [comment]
Hi Olivier!
There shouldn't be a bump as this testing had parallel users with time waits between actions so RPS should be the same, only the responses were faster after adding the index.
I'm attaching the pgBadger printscreen of parsed postgresql log where you can see the problematic query so you can choose between adding individual indexes or composite index on those two fields.
![PgBadger](https://user-images.githubusercontent.com/30649715/73931909-75d1ac80-48d9-11ea-8146-9ae8cfe274fc.png)

**Comment by Yenthe666** [comment]
@odony is there any update or PR for this? My customer is affected by the same (123K moves in V13) and the issue becomes increasingly bad along with the amount of moves growing. There are also big performance penalties on cancelling/deleting `stock.picking` records along with their `stock.move` and `stock.move.line` records by the way - I'll create a separate issue for this.

**Comment by sle-odoo** [comment]
@Yenthe666 according to my tests 100k moves won't degrade in a remarkable way the performances so it's very unlikely you'll benefit from these indices right now

we were working on this (played with [locust](https://github.com/sle-odoo/odoo_locust_scripts) and reproduced the results of @MeeleCode because the issue was very well explained, thanks a lot by the way) but we had to work on something else because priorities.

i planned to and i will update this task once it's all done and tested.

>  There are also big performance penalties on cancelling/deleting stock.picking records along with their stock.move and stock.move.line records by the way - I'll create a separate issue for this.

Yes please, a separate issue with more information.

**Comment by Yenthe666** [comment]
@sle-odoo see https://github.com/odoo/odoo/issues/45838 (along with OPW 2201251) for the other issue :) Let me know what else you need and I'll make it happen.
