### ISSUE TITLE
Auto Stock Unreserved

### ISSUE THREAD

**Issue by goyanipankaj** [odoo/odoo#44686]
Impacted versions: 12.0 

Steps to reproduce: 
- Create product + Tracking Unique Lot Serial
- Received qty (Ex. 3 Units) and done Picking
- Internal transfer Source: WH/Stock Destination: Virtual Locations/Inter Company Transit 
  after Mark as ToDo > Check Availability >> change  Lot/Serial 
  Asigned: LT1, LT2, LT3     New Change Update Sequence: LT3, LT1, LT2
- Confirm that lines and then pickign line in Reserver qty: 2 instead of 3.
Its updated reserved qty after change the Lot/Serial sequences.

Current behavior: Auto unreserved stocks

Expected behavior: Not  unreserved auto.

Video/Screenshot link (optional):
Tested in runbot odoo-12.0 and getting this issue.
http://1131019-12-0-5489cc.runbot19.odoo.com/web?#id=401&action=392&model=stock.picking&view_type=form&menu_id=282

Video:
https://drive.google.com/file/d/1Kt8K7EP_rDzTEOKUAB5J38eut0pdxIyg/view?usp=sharing

**Comment by sle-odoo** [comment]
Hi,

The behaviour is correct.

the situation: 
lot1 - reserved 1
lot2 - reserved 1
lot3 - reserved 1

1) you changed lot1 in lot3, it un-reserves lot1 but since lot3 is already set elsewhere else, you got a waning
2) you changed lot2 into lot1, it worked since lot1 is available from 1)
3) you changed lot3 into lot2, it worked since lot2 is available from 2)

Regards
