### ISSUE TITLE
[13.0] Removing of model with selection field failed

### ISSUE THREAD

**Issue by Tatider** [odoo/odoo#44767]
Impacted versions:
13.0

Steps to reproduce:
1. Create a model with `selection` field
```python
from odoo import fields, models


class TestModel(models.Model):
    _name = "test.model"
    _description = "Test Model"

    name = fields.Char()
    state = fields.Selection(
        [
            ("draft", "New"),
            ("sent", "Sent"),
            ("failed", "Failed"),
        ],
        "State",
    )

```
2. Import new model to a module.
3. Update/install the module .
4. Remove the model
5. Update the module

Current behavior:
Raise an exception for selection option removing.
[selection_field_traceback.txt](https://github.com/odoo/odoo/files/4166553/selection_field_traceback.txt)

Expected behavior:
Remove model with all fields and selection options with out exceptions.

Video/Screenshot link (optional):

**Comment by Elkasitu** [comment]
I don't think it's a bug, more of a limitation of the ORM and frankly I don't know if we want to support this use-case.

Deleting a model is considered an "unstable change" i.e. should not be done in production because the mechanism that cleans up models is done during module uninstallation, the problem in your case is that there's a leftover reflection model (`ir.models.fields.selection`) that points to a model that is not loaded and does not exist anymore, it's not something specific to a `Selection` field, if you replace your `Selection` field by a `Many2many` field you will face the same error as it creates an `ir.model.relation` record that points to your deleted, unloaded model.

The uninstall process takes care of all of these steps

https://github.com/odoo/odoo/blob/a798e234c63c62c48278e91b896e985d05c2c663/odoo/addons/base/models/ir_model.py#L1813-L1926

If you want to do it for development purposes, it may be best to first uninstall the module and then reinstall it or to start with a fresh database

**Comment by Jerther** [comment]
Sorry don't want to necro-thread ;) But I got here from the 4th result in Google trying to find a solution to this in 14.0. The problem here occurs on a production database because I'm removing an obsolete model so uninstalling the module or restarting a database is out of question ;)

So to fix this you have to do proceed in two phases:
### Phase 1
- Delete everything that's related to this model (views, records, security stuff, etc.)
- Keep the class definition but remove all fields from it:
```python
from odoo import models


class TestModel(models.Model):
    _name = "test.model"
    _description = "Test Model"
```
- Upgrade the module. This will delete all the fields including the problematic ones.
### Phase 2:
- Delete the class
- Upgrade the module again. This will delete the model, and won't fail because of the selection fields (or any other field) because they're already gone.

Hope this helps someone :)
