### ISSUE TITLE
Product done quantity not updating correctly in appropriate next line on barcode scan in detailed operation(stock.move.line)

### ISSUE THREAD

**Issue by johar13** [odoo/odoo#44848]
Impacted versions:
12.0
Steps to reproduce:
1) Create a sale order with 2 lines of the same product
2) In detailed operations of delivery click on edit and scan the barcode of the product

Current behavior:
The quantity of the product keeps on updating on the first line

Expected behavior:
The quantity of the product should be incremented in the next line if the todo qty is already completed 
It should not keep updating the first line of the product.

Video/Screenshot link (optional):
![delivery](https://user-images.githubusercontent.com/47169184/74029509-d42e8600-49d2-11ea-8cef-f77da266ea2c.png)

**Comment by sle-odoo** [comment]
Hi,
This is specifically handled in the barcode client action, not sure if it's already present in 12 though. In most cases, moves of the same product are merged, so this problem doesn't really happen. You probably got here because you made two sale order line of the same product.

It's unlikely we write of fix for this, but you could open a PR or an officiel ticket if you want, since this is an enterprise feature. The method to adapt is `_check_product`.

Regards
