### ISSUE TITLE
POS Fiscal Positions Not Working Properly

### ISSUE THREAD

**Issue by senolsun** [odoo/odoo#44925]
Impacted versions:
13.0

Steps to reproduce:

Add a fiscal position "ZERO TAX" to one customer (ex: Agrolait)
Add a customer tax ( 18% VAT) to one product (ex: Lays Natural Light 170g)
Open a POS session and select the customer Agrolait
Add the product Lays Natural Light 170g in your order.
Choose the cash journal and ask an Invoice
Current behavior:

Taxes are shown in the POS
Odoo ask to pay in cash the amount with taxes
The invoice is generated without taxes
Pos order is created with taxes
Expected behavior:

Taxes should be at 0 in this case in the POS
Odoo should ask to pay in cash the right amount (with taxes = 0)

**Comment by Yenthe666** [comment]
@pimodoo

**Comment by pimodoo** [comment]
@senolsun Hello,

The problem here probably comes from your pos configuration. If you want to allow use of fiscal positions in your POS, you should tick "Fiscal Position per Order", in your pos configurations, and put the fiscal position '0%' in the available fiscal positions.

So the real problem here is that the invoice apllies the fiscal position, even if it has not been set on the pos order, so I'll look to fix this.

**Comment by pimodoo** [comment]
I've just checked, when an invoice is generated from the POS, and the invoice was corresponding to the pos config, so I think it was only a configuration problem from you side.
