### ISSUE TITLE
[8.0] AccessError when searching translated field = 'product.template,name' using admin account

### ISSUE THREAD

**Issue by yostashiro** [odoo/odoo#4497]
**AccessError when searching translated field = 'product.template,name' using admin account**
# Impacted versions:
- 8.0 (haven't checked other versions)
# Steps to reproduce:
1. go to Settings > Translations > Application Terms > Translated Terms
2. try searching 'translated field' for 'product.template,name'
# Current behavior:
- Get this error message:

> AccessError
> 
> The requested operation cannot be completed due to security restrictions. Please contact your system administrator.
> 
> (Document type: product.template, Operation: read)
- Also see this post (it is probably related): https://www.odoo.com/fr_FR/forum/help-1/question/why-do-i-get-accesserror-on-document-type-email-template-operation-read-with-administrator-account-67131
# Expected behavior:
- There should be no such error message and translation records should show.

**Comment by geekobi** [comment]
Hi,
Some month ago, I had the same error message.
I went into the code at that time and found that security checks was implemented in at least 2 places and in my case :
- a first function took into account the inheritance between groups and in my case the user was authorized to access the field
- a second didn't took in account this inheritance but only the direct right on the direct groups of the user and I got a message like above.

I remember that I turnaround the issue by adding the appropriate group directly on my user and I don't remember where the issue was in the code.
But I can search in the comment of my internal issues and find where I found this issue in the code if it is usefull.
Herve

**Comment by Yenthe666** [comment]
Hi @yostashiro ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
