### ISSUE TITLE
[13] base: Selection field left over when related module is uninstalled

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#45240]
Impacted versions: 13.0
http://1219203-13-0-4901fb.runbot27.odoo.com/web
Steps to reproduce: 
- Install module which adds New selection using `selection_add` (Tried with `account_tax_python`)
- Create Record which points to It
- Uninstall that module

Current behavior: While Creating New Record that Option is available

![image](https://user-images.githubusercontent.com/16624719/74359686-b9507d00-4de9-11ea-9906-ef133b3d3961.png)

Select that
![image](https://user-images.githubusercontent.com/16624719/74359635-a2118f80-4de9-11ea-8b7a-efb045de0213.png)

Expected behavior: Same as v12 in this case.

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Isn't this the same as https://github.com/odoo/odoo/issues/44767 ? Might be misunderstanding though.

**Comment by intero-chz** [comment]
Shouldn't title be a bit clearer as "Selection option" or "Selection value" instead of "Selection field"?

**Comment by Feyensv** [comment]
When removing a selection field choice, the ORM doesn't know what to put instead and tries to set the values to NULL, which crashes because the `amount_type` is required.  This leads to the `ir.model.fields.selection` staying in database because it couldn't be deleted and therefore the choice is still available in the web client, even after module deletion.

The incoherence comes from the fact that the orm doesn't recognize the values because it checks the python code, whereas the web client uses the ir_model_fields_selections to get the available choices.

IMO, it is kind of expected and won't be changed.  You have a nice ERROR log to explain that something failed to be deleted along the module uninstall and this should be fixed manually, because the orm cannot suppose which value it should put instead in database.  This only crashes because you didn't take your logs into consideration after update AND you are doing something which shouldn't work anymore anyway.

The only possibility of fix would be to block the uninstall of the module, saying it couldn't be correctly uninstalled, but I'm really not sure that's what we want.  As said by @Elkasitu in #44767, playing with module install and uninstall in production is risky and should only be done when we really know what we do, while taking a look at the logs :D.

**Comment by Elkasitu** [comment]
For the time being, this is considered a limitation of the ORM.

The procedure would be for developers who introduce `selection_add` in their modules, to handle their cleanups using an `uninstall_hook`, you can see an example of a fix and a more detailed explanation at #45180

Perhaps in the future we will manage to enforce some kind of hook for Selection fields with `selection_add`, so that the lack of a cleanup makes the runbot red/yellow.

**Comment by MiquelRForgeFlow** [comment]
> Perhaps in the future we will manage to enforce some kind of hook for Selection fields with selection_add, so that the lack of a cleanup makes the runbot red/yellow.

That would be top 🚀
