### ISSUE TITLE
In stock move lines text-danger style is applied even if there are quantities available

### ISSUE THREAD

**Issue by MarkingSC** [odoo/odoo#45349]
Impacted versions:
v13

Steps to reproduce:
Create a outgoing shipment with available products and type a quantity in done field.

Current behavior:
The move line text turns into red style even when available quantity is greater than done quantity

Expected behavior:
As far as I know it should keep on green style, because product is really available in the location.

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/26973424/74493855-cd06ec80-4e98-11ea-87df-54f85c3af4ec.png)

**Comment by pedrobaeza** [comment]
This is not because there are no available quantities, but the way you have created the outgoing, not filling initial planned quantity, so the done quantity is higher than this planned one, putting in red.

Choose to create a planned transfer instead of immediate transfer from the picking type rectangle in the dashboard, and there put the initial quantity. Mark as todo, and you will see the check availability button and everything will turn in what you expect.

Closing as no issue at all.

**Comment by MarkingSC** [comment]
Thank you, @pedrobaeza, it's good to know it!
