### ISSUE TITLE
[account] Wrong journal entries of Exchange Rate with Bank Statement

### ISSUE THREAD

**Issue by JulioSerna** [odoo/odoo#4542]
Impacted versions:
* 8.0

Steps to reproduce:

* To set allow multi currencies
![configure accounting odoo](https://cloud.githubusercontent.com/assets/7595505/5622937/a8c62d5a-9510-11e4-9079-5b0c3d40c098.png)

* To create one invoice with currency different to company(USD)
* To create payment with bank statement with different date to the invoice and with journal in USD
* To pay invoice with bank statement

Current behavior:
Bank statement only creates a journal items for reconciling amount of the invoice and loss or gain exchange rate amount
![journal entries odoo](https://cloud.githubusercontent.com/assets/7595505/5623046/5944d4be-9512-11e4-810a-0e323e94d5e2.png)

The amount currency **-448.00** not correspond to the amount **349.07**

Expected behavior:
Should create two journal items one with the amount of the loss or gain and one with the amount of the invoice
![customer payments odoo](https://cloud.githubusercontent.com/assets/7595505/5623134/bf3beb08-9513-11e4-8a2c-110a4e301c18.png)

**Comment by hbto** [comment]
What we mean with this issue is that both Account Voucher & Bank Statement must be consistent when booking Exchange rate difference.

Right now they do not yield the same results.

Account Voucher yet not perfect is the one we have been dealing with since a long time and has been
performing and improving over the time.

Bank Statement though is not the new kid on the block is been touted as the more user friendly tool 
for end users yet is lacking some features that have proven to be correct in account voucher, at least 
from my PoV.

By using the approach in bank statement we are going back to v6.1 and below where there were no
way to track gain and losses in payables and receivables, and where exchange rate, i.e, debit/credit divided by amount_currency is not the same as date rate.

That approach take us, and odoo, away from the goal of having a multicurrency-aware software
where we can audit what was happening at any given time as depicted here in [1]

Best Regards.

[1] http://www.mathstat.dal.ca/~selinger/accounting/tutorial.html

**Comment by JulioSerna** [comment]
This issue is still happening in master,

Create invoice with **USD**
https://docs.google.com/a/vauxoo.com/file/d/0BxOBOIFMBX7-ZUQ3UXFLMjFJNXM/edit?usp=drivesdk

Create statement in **USD**
https://docs.google.com/a/vauxoo.com/file/d/0BxOBOIFMBX7-dlp4REd5SjdwMW8/edit?usp=drivesdk

and journal entries is still wrong
https://docs.google.com/a/vauxoo.com/file/d/0BxOBOIFMBX7-dHZ0akZQRGJza0U/edit?usp=drivesdk

**Comment by fclementic2c** [comment]
Maybe this will help :  
https://github.com/odoo/odoo/issues/4043

**Comment by qdp-odoo** [comment]
Hello,

In fact, the current journal item created on the Debtor account is simply the merge of the 2 lines you'd like to have on the same account. So it won't change anything in your balances or whatever... For me, the fact there is a single line or two is just an implementation detail you shouldn't care about as the result is the same. (actually, in v9 it _will_ be as you requested.. but not because we believe the current behavior is wrong, simply because, for technical reasons, we decided to do in another way)

To be sure, we have double-and-triple-checked here: at least in belgium, it's allowed to book the accounting entries as they are now. I beleive this is the same for a lot of countries otherwise someone else than you, guys, would have complained about it.

Still, if you have a legal document proving your requirements towards that point, we may include a fix in the Venezuelan localization. If it's the case, please proceed with the support process by provide that document.

Hope you'll understand our position,
Quentin

**Comment by nhomar** [comment]
2015-03-09 9:26 GMT-06:00 qdp-odoo <notifications@github.com>:

> To be sure, we have double-and-triple-checked here: at least in belgium,
> it's allowed to book the accounting entries as they are now. I beleive this
> is the same for a lot of countries otherwise someone else than you, guys,
> would have complained about it.


I honestly think it is because you work with 2 currencies with a difference
of cents, then the difference is almost deprecable.

I think you need both account move lines as explained, one to considere the
invoice itself and another one to create the exchange difference, you will
be consistent in all your reports, this time I ask to yopu a document that
support explicitally the actual behavior legally in Belgium because, it is
a matter of Common Accepted practices, not of legal itself behavior.

We will make the investigation deeper in our side, but I think it should be
cool if you show me how it is expressed in your legislation also, which
will support your technical decision.

Regards.-


-- 
--------------------
Saludos Cordiales

  [image: --]
Nhomar Hernandez
[image: http://]about.me/nhomar
     <http://about.me/nhomar?promo=email_sig>
