### ISSUE TITLE
--save command line option should not save deprecated options

### ISSUE THREAD

**Issue by gurneyalex** [odoo/odoo#4550]
Version affected: 7.0 and later

steps to reproduce:

1. run:

    openerp --save -c /tmp/config  --stop-after-init

2. open `/tmp/config`

expected result: deprecated options should not be saved

actual result: there is at least one line

    log_level = info

in the file

This is bad because the interaction between log_level and log_handler is confusing.

**Comment by mart-e** [comment]
Why do you say that log_level is deprecated? It's still used and working.
If there is options that you believe should not be present, we can add them in the [blacklist](https://github.com/odoo/odoo/blob/7.0/openerp/tools/config.py#L77) but log_level should be present.

**Comment by gurneyalex** [comment]
@mart-e the [help message for the option](https://github.com/odoo/odoo/blob/7.0/openerp/tools/config.py#L195) says the option is deprecated. It was already deprecated in 6.1 AFAICT, got suppressed altogether at some point, then readded in https://github.com/odoo/odoo/commit/09dc03a30fb328d8861e82c1a877e2f6f32b075f

**Comment by mart-e** [comment]
You are right, I hadn't noticed it was marked as deprecated.
After discussion, this was due to an initial plan to replace fully by log-handler option but log-level is still a way more convenient way to manage the output so we prefer to keep it.
I have removed the deprecated comment at ae34a1e93ec3e6e54ece9d546d527af5787f5c3f
