### ISSUE TITLE
residual amount in invoice stays to 0 when duplicating the invoice

### ISSUE THREAD

**Issue by mamaf** [odoo/odoo#4551]
After having duplicated an invoice, and changed amounts, the residual amount stays to 0
=> Impossible to proceed payment

**Comment by mart-e** [comment]
Please give more detail on how to reproduce your issue. Which version, steps, which view do you have the issue, etc.

**Comment by mamaf** [comment]
create an invoice and go to the end of the process => payment => resdual amount is 0
Then duplicate this invoice, change the amount of invoice_line then save and validate the invoice => residual amount is still 0 (should be the amount of invoice 
version 8.0

**Comment by mart-e** [comment]
When you validate an invoice, the value for the field "residual" is recomputed correctly.
My guess is that you are talking about the fact that the balance is still 0 when you have not validated yet the invoice but modify it (by the way amount field is readonly).
As this field is the sum of unreconciled amount and we have no accounting entries on a draft invoice, it's the expected behaviour that it's not computed yet.

If I have misunderstood, give more detail to reproduce on standard version (try on [runbot](http://runbot.odoo.com/runbot), screenshots, etc..)

**Comment by mamaf** [comment]
No, the invoice is validated and residual amount is incorrect : it should be the total amount, but it is 0
