### ISSUE TITLE
Disable line statements in jinja

### ISSUE THREAD

**Issue by Yajo** [odoo/odoo#45611]
Impacted versions: all

Steps to reproduce:

1. Use Odoo's HTML editor and edit any template that contains jinja line statements.

Current behavior:

The HTML editor does whatever it wants with whitespace, randomly rendering the template unusable.

Expected behavior:

Just changing one phrase in a template shouldn't break it.

To avoid that, the easiest way is to disable (and remove from Odoo source code) jinja line statements. This way, templates will be required to transform:

```jinja
% if condition:
    <p>True!</p>
% endif
```

into:

```jinja
<% if condition %>
    <p>True!</p>
<% endif %>
```

It's more verbose but it's unaffected by whitespaces.

Note: If you write `<% if condition %>` using the HTML editor, it converts it into `&lt;% if condition %&gt;`, making it impossible to workaround this problem using the UI, not even in developer mode. Possibly Odoo should switch to standard jinja tags `{% ... %}` to avoid that problem.

@Tecnativa TT22275

**Comment by pedrobaeza** [comment]
I don't get your suggestion.

@mart-e any comment about this?

**Comment by Yajo** [comment]
Add 13.0 too please.

My suggestion is to use the tag style that is independent of whitespace, instead of the whitespace-based style. Whitespace is stripped sometimes from the HTML widget, breaking rendering.

With this change, it would be easier too to edit the templates with the HTML editor, while now it's only possible using the source code mode available in developer mode.

**Comment by pedrobaeza** [comment]
But this can't be done in stable...

**Comment by Yajo** [comment]
It doesn't mean it's not affected.

**Comment by pedrobaeza** [comment]
Yeah, but I mean we should find another solution for stable versions.

**Comment by Yajo** [comment]
At least _not_ escaping `<%` and `%>` would be good, so users aware of this could actually use the feature from UI.

More radical changes, such as changing the markers and/or forbidding line statements, should land into master of course.

**Comment by mart-e** [comment]
This is an old known issue : the HTML editor is not compatible with jinja syntax.
Our goal is to actually get rid of jinja templates and replace them by QWeb. There is a task ongoing for several years but I am not sure why it was never completed (I guess priorities, maybe @tde-banana-odoo knows more?).
We don't want to spend a lot of time to improve the jinja engine but if you have an easy PR, we can have a look nevertheless.

(FYI we don't use the HTML widget on mail.template form at Odoo SA ;-) )

**Comment by tde-banana-odoo** [comment]
"Our goal is to actually get rid of jinja templates and replace them by QWeb."

Is it ?

"There is a task ongoing for several years but I am not sure why it was never completed"

Because editor does not support writing raw Qweb without interpretating it + drag 'n drop of model-based fields. Not ready at all for replacing jinja.

**Comment by tde-banana-odoo** [comment]
And indeed best way to edit jinja templates is to use the text widget. Sad but true.

**Comment by mart-e** [comment]
> Is it ?

Don't break my dreams please...

**Comment by Yenthe666** [comment]
Just posting a message so I can filter this out in my messages.. I'm interested about this subject :)

**Comment by Yajo** [comment]
There you have it for master: https://github.com/odoo/odoo/pull/45633

**Comment by Yajo** [comment]
This bug is still a big problem. Would you please fix it? 🙄

**Comment by Yenthe666** [comment]
I'd also log an OPW for this tbh :)

**Comment by Yajo** [comment]
Yes, do it please. I think they'll listen to you more than me.

**Comment by tde-banana-odoo** [comment]
Hello,

Just to revive this one. Just to know, how does the html editor behave with construct like
```
<% if condition %>
    <p>True!</p>
<% endif %>
```
Does he correctly handle < and > ? Are they considered as broken tags, or displayed as they are ?

We could think of improving templates to make them easier to edit, but we have to be sure we effectively gain something :D .

Cheers,

**Comment by Yajo** [comment]
They are escaped and thus broken:


https://user-images.githubusercontent.com/973709/111279001-21e3dc00-8632-11eb-80c5-4a3fa0171904.mp4

**Comment by luisg123v** [comment]
> > Is it ?
> 
> Don't break my dreams please...

:laughing: 

I also though Jinja templates will progressively be removed, because they have several (IMHO) important drawbacks:
- They can't be inherited:
  * one has to replace them al togeter to make a small change 
  * This also means if the original template is improved, those changes won't be applied. This is specially relevant when migrating code that applies changes over mail templates. It's like inheriting a very long Python method just to change a few lines
- Translations are a mess:
  * they include code statements, which it's harder to translate and increase chances of human mistakes when translating
  * all the content is exported in a single translation and again, if you perform a small change, you have to export the whole content
  * New translations are not exported in the module applying the changes, Which means they need to be manually placed in the directory `i18n_extra` to work
- Qweb templates are more powerful, aren't they?

I hope the above could be considered for future versions

**Comment by pedrobaeza** [comment]
Check https://twitter.com/PedroMBaeza/status/1382705268031696898?s=20

**Comment by luisg123v** [comment]
@pedrobaeza thanks a lot for the link!

I came from that PR but I hadn't read the latest comments.

**Comment by Yajo** [comment]
Closing as jinja is removed for 14.5: https://github.com/odoo/odoo/pull/67868#issuecomment-930029870
