### ISSUE TITLE
[saas-3] Mass mailing: The mail stats are incorrect if no mail are sent

### ISSUE THREAD

**Issue by anthony-muschang** [odoo/odoo#4640]
**The mass mailing stats are incorrect if no mail are sent**

When sending a mass mailing, the statistic value shows the mail as sent and as delivered before the mail is sent & delivered. Also If there is an exception which prevent the mail to be sent, the mail stat will be set as sent & delivered. 

Impacted versions:

 - saas-3

Steps to reproduce:
With the module mass mailing:
 1. Got to Messaging/Organizer/Contacts edit or create a partner with no email address
 2. Select the partner with no email in the list view, go to "More", select "Partner Mass Mailing"
 3. In the Partner Mass Mailing window, create a Mass Mailing Campaign and send the mail.
 4. Go to Marketing/Campaigns and open the created Mass Mailing Campaign

Current behavior:
 - The mail stat is set to sent and delivered even if nothing have been sent

Expected behavior:
 - The mail stat is set to not sent and not delivered because no mail have been sent

**Comment by anthony-muschang** [comment]
Linked to opw-625347

**Comment by beledouxdenis** [comment]
Hello Anthony,

In Odoo saas-3, the count of "sent" email is the count of emails created / that will be sent by the mass mailing campaign.

We understand this is confusing. Sadly, your issue is not fixable in saas-3, as it would require database structure changes for the model mail.mass_mailing.campaign, which are forbidden in stable releases (such as saas-3).

Nevertheless, this issue has been resolved in Odoo 8.0, during the refactoring and the usability enhancement of the module mass_mailing.
You can notice the structure changes of the model from:

- saas-3 : https://github.com/odoo/odoo/blob/saas-3/addons/mass_mailing/mass_mailing.py#L356
to

- 8.0: https://github.com/odoo/odoo/blob/8.0/addons/mass_mailing/models/mass_mailing_stats.py#L61
That allow us to display the actual number of sent & delivered emails.
We therefore encourage you to upgrade your system to Odoo 8.0.

We hope you will understand.

Regards,
