### ISSUE TITLE
[13] purchase: Wrong number of Picking count when 3 steps are activated

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#46472]
Impacted versions: 13.0

Steps to reproduce: Activate 3 step Incoming/Outgoing Shipment from WH settings

![image](https://user-images.githubusercontent.com/16624719/74169745-d05c6700-4c51-11ea-80ca-495478266977.png)

Create PO and Confirm it

Current behavior: Count of Incoming Shipment is 1 while there are there Pickings Created based on configuration (Receive goods in input, then quality and then stock (3 steps))
![image](https://user-images.githubusercontent.com/16624719/74169891-10234e80-4c52-11ea-8b24-f7e21fd5b130.png)

Three shipments are created: 
![image](https://user-images.githubusercontent.com/16624719/74169973-2fba7700-4c52-11ea-9ec5-1909cc8b12db.png)

Expected behavior: Count should be 3 and It should Open List with these three Pickings
Eg, the Same thing works well on Outgoing shipment

![image](https://user-images.githubusercontent.com/16624719/74170108-64c6c980-4c52-11ea-98c5-b26c5d753e08.png)

![image](https://user-images.githubusercontent.com/16624719/74170135-6f815e80-4c52-11ea-925d-3583a931efbc.png)

 

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
I think this was deactivated on purpose for not being affected on chained things, but I don't remember exactly.

**Comment by sswapnesh** [comment]
Maybe @sle-odoo  Knows

**Comment by sle-odoo** [comment]
it's because there's no easy way to do it

if you just follow the procurement group you could go too far (display the ship picking) or to close (only the receipt and not the pickings created by the push rule)

we tried to follow until the main warehouse location but it's not always crisp since you could send products to sublocations of the main warehouse, and the performance cost was too high for a small benefit

so this is a "won't fix" issue at the moment sadly

regards

**Comment by sswapnesh** [comment]
Isn't it the same Situation for Deliveries as well?

**Comment by sle-odoo** [comment]
> Isn't it the same Situation for Deliveries as well?

yes the count of pickings from the SO could go two far: 3-steps receipt and 3-step deliveries, you'll get 5 picking in the stat button (because we follow blindly the procurement group)
