### ISSUE TITLE
[13.0] Breadcrumb stacks when click back button browser

### ISSUE THREAD

**Issue by andrepurnomo** [odoo/odoo#46616]
Impacted versions: 13.0

Steps to reproduce: just open a link and back, breadcrumb stack

Video/Screenshot link (optional):

This example

First i open products
![Screen Shot 2020-02-29 at 18 01 09](https://user-images.githubusercontent.com/24785523/75606303-de4d2b80-5b1d-11ea-9092-14c7e40fdc8f.png)

Breadcrumb still fine
![Screen Shot 2020-02-29 at 18 01 15](https://user-images.githubusercontent.com/24785523/75606314-fb81fa00-5b1d-11ea-905d-1b79e4a9fcc8.png)

Then open stock, breadcrumb still fine
![Screen Shot 2020-02-29 at 18 01 20](https://user-images.githubusercontent.com/24785523/75606327-16546e80-5b1e-11ea-8950-5047dcf7acbd.png)

And im click back in my browser
![Screen Shot 2020-02-29 at 18 01 26](https://user-images.githubusercontent.com/24785523/75606341-3edc6880-5b1e-11ea-86e8-d42b1e12756e.png)

It works well if I click directly on the breadcrumb link, this only happens when I click the browser back button. I'm using odoo:13 docker image with latest update.

**Comment by pedrobaeza** [comment]
This is something expected, as URL doesn't contain full breadcrumb history, so you can't expect clicking on back button on the browser that. Just don't use that button if you expect the breadcrumb to be kept, and use the own breadcrumb to go "back" on your Odoo navigation.

Any way, it would be great to have this feature. @mart-e do you remember that we talked about this in last Odoo XP? encoding the breadcrumb in the navigation URL (or any other technique for preserving it - maybe some cookies/browser storage?) can be very interesting for avoiding this side effect.

Closing as won't fix on current versions, as it's the expected behavior.

**Comment by vuvivian** [comment]
oh, so sad~
