### ISSUE TITLE
%if %endif does not work with mail templates. Sent e-mails are blank.

### ISSUE THREAD

**Issue by Yenthe666** [odoo/odoo#4671]
**Adding %if %endif in mail templates destroys e-mails.**

Impacted versions:

 - 8.0 and above

Steps to reproduce:

 1. Install mass mailing and check both 'Mass mailing' and 'Manage mass mailing using campagn' under settings > Marketing.
 2. Create a new mail template under marketing > mail templates
 3. Give it a name and an applies to and then click on 'Edit template'
4. Add a %if %endif statement to the e-mail. for example:

<code>
Dear ${(object.name or 'Sir / Madam')|safe}
Thank you for registering.. We have these details:
% if object.street2:   ${(object.street or '-')|safe}
% endif
</code>

Current behavior:

 - The send e-mail will be blank as you can see in the image:
<img src="http://i.imgur.com/1ReHcr8.png"/>

Expected behavior:
 - The e-mail gets send with all content and respects %if %endif statements just like any other e-mail template under settings > Email > Templates.

I'm not sure if this is a bug or just not built but this would be highly useable. The ability to make parts of e-mail lay-outs with %if % endif statements makes templates a lot more useable. E-mails can be personalised way more by this.

**Comment by esperandus** [comment]
Completely agreed. Amusingly enough, I am running into this exact same issue this morning. Was floored that this does not appear to be supported. Before digging into the guts and checking into whether the email templates can use the same QWEB syntax, thought I'd show up here. If anyone from the odoo team is listening, this would be a great enhancement.

**Comment by Yenthe666** [comment]
@esperandus exact same thoughts, I was floored too. I've been looking a bit in to the code but there doesn't seem to be any support for %if %endif in the code of Odoo. I assume this isn't even built in for custom templates..
Adding this would greatly enhance your options in mass mailing though. I hope to hear from somebody of Odoo soon about this!

**Comment by intero-chz** [comment]
Hi,

if model email.template is used for this, there already is demo data (e.g. for module sale) using if/endif. And the preview of these templates seem to be correct, what means that it is using if/endif correctly. (tested on runbot 8.0)

On 7.0 i had a similar problem with "mass mailing" and templates. It seemed that using this combination wasn't rendering templates correct, because the server was rendering each e-mail twice or something like that (maybe threefoldly), which produced some weird mistakes.

**Comment by Yenthe666** [comment]
@intero-chz the mass mailing templates are indeed stored in email.template.
If I make an e-mail templates <b>without</b> any %if %endif everything works.
Example code:
<img src="http://i.imgur.com/Sc48Nhp.png"/>

If I place a %if %endif statement in the template it will fail, both on sending and preview.
Example code:
<img src="http://i.imgur.com/7w5pqJ6.png"/>

Preview with %if %endif:
<img src="http://i.imgur.com/1Vy62y2.png"/>

**Comment by intero-chz** [comment]
Hm that's weird. My problem was a bit different: On preview it was all fine, but sending mass mails failed or rather rendered nothing (blank mail). Odoo's sale order template uses if/endif too, and preview is how it has to be.

**Comment by Yenthe666** [comment]
@intero-chz the default templates for sale orders etc (under settings > emails > templates) do seem to work with %if and %endif indeed. And you can see the previews fine there. 
As soon as you create your own, new, template the %if %endif statement does not work. So I assume it doesn't work at your side either?
@xmo-odoo can you have a look at this? This has been confirmed by three people and is a rather big and handy feature.

**Comment by PeterA-OpusVL** [comment]
I have just been playing around with if statements in the email templates. I found entering them manually through the gui doesn't work - they just show up as '% if ********* % endif' and don't actually do the calculations. The changes I am making are meant to be persistent though, so I edited them in the xml (odoo/addons/sale/edi/sale_order_action_data.xml) specifically. The others look something like this (indented, with br and p tags)
    % if object.paypal_url:
    <br/>
    <p>It is also possible to directly pay with Paypal:</p>
        <a style="margin-left: 120px;" href="${object.paypal_url}">
            <img class="oe_edi_paypal_button" src="https://www.paypal.com/en_US/i/btn/btn_paynowCC_LG.gif"/>
        </a>
    % endif

this may be of help to some people, but mine is working fine through the xml

**Comment by Yenthe666** [comment]
@PeterA-OpusVL yes you are right, if you define it in XML there aren't any problems. It only happens when you create templates through the GUI.. But I don't want my users to be able to modify XML files etc so I'd love the GUI way to work.
@antonylesuisse can you have a look at this? Nobody seems to have a look at this..

**Comment by odony** [comment]
I think you're mixing HTML and "Plain Text" versions of the templates, and getting confused.
If you follow the steps in this issue description you'll end up editing the HTML version of your template. This is fine as long as you don't try to use the "line statement" version of the Jinja2/Mako syntax, i.e. the "%" line prefix which your example tried to use.

[Line statements](http://jinja.pocoo.org/docs/dev/templates/#line-statements) in Jinja2/Mako work only when the first non-blank character of the line is the percent (%) character. When you're dealing with HTML templates, there's a very very good chance every line has a lot of HTML tags before the % sign, or that the % sign is not on its own line.

To convince yourself, switch to the source view of your template (the rightmost icon in the HTML editor toolbar, looking like `[<>]`), and you'll see the mess.
This is why it works when you change the XML source files, as you're dealing with the raw HTML source directly too.

**Solution:** use the source view to write HTML directly, and thus use the full Jinja2/Mako syntax including line statements. Some advanced users might also want to permanently switch to a plaintext version of the template body, by editing the form view of mail templates and forcing `widget="text"` for the `body_html` field. It's safer if you do advanced things, because the HTML editor will also plainly reject/mess up templates that do not contain valid HTML, for example with % line statements in between `<tr>` or `<td>` elements in a table.
You could also try to use the ``<%`` and ``%>`` markers for block statements, but that will definitely fail with the HTML editor (even in source mode) because the angle brackets will be auto-escaped, being invalid HTML tags.

We have not yet found any smart HTML editor that has WYSIWYG **and** also properly supports Jinja2/Mako markers, because it indeed is a *hard* thing to do.


Oh, and watch out that you cannot use variables expressions on the line statement itself,  another mistake that seems present in the issue description... 

This is invalid:
```mako
% if object.street2: ${(object.street or '-') | safe}
% endif
```
While this is valid (even if quite strange):
```mako
% if object.street2:
    ${(object.street or '-') | safe}
% endif
```
I suppose your real use case makes more sense than this example which could be trivially replaced by the simpler ``${object.street2 and object.street or '-'}``.
If you're not sure, check the [Jinja2 documentation](http://jinja.pocoo.org/docs/dev/templates/#line-statements).

**Comment by odony** [comment]
I should also mention that as soon as there is a syntax error in the template, making it unparseable by the rendering engine, it will end up blank. At that point you might want to undo the last change you did and look at the real source of your template to fix the syntax errors.

You might also be tempted to use the CMS/Website editor, available via the "Edit template" button on the mail template form, in order to use smarter building blocks for your emails.
In that case you'll experience similar problems with line statements and invalid XHTML contents, because this is another HTML editor, basically.

This is unfortunately not very user-friendly, but those tools are for advanced usage :disappointed:  

In the future we might switch email templates to the QWeb syntax, just like the CMS/Website pages. This will at least avoid the non-HTML vs HTML mixing issue, as QWeb is XML-based, unlike Jinja2.

**Comment by Yenthe666** [comment]
@odony thank you very much for this detailed explenation! Its great to hear some more detailed and tech responses about these kind of things. 
Alright so if I understand correctly and make a new template through 'Marketing' > 'Mail templates' in the rich text/HTML version it should work?
Like this:
<img src="http://i.imgur.com/vA4J27n.png"/>
This has the %if on the first line, first character and is in HTML code view. So this means there can nothing else HTML-related be added. When I check out the preview my template doesn't work though.
<img src="http://i.imgur.com/ccvg4AT.png">
Can you also explain me why this would not work then? :s

<b>Note:</b> Thanks for pointing out the wrong syntax on my %if %endif too by the way!

**Comment by odony** [comment]
@Yenthe666 There's a good chance your template is working, and correctly produces an empty result. By default in demo data the `street2` field is empty, even though `street` is often set. Try using `street` in your `if` condition too.

**Comment by gdgellatly** [comment]
My experience of this issue is that more often than not it is related to
translations.  At least it would be the first thing I'd check.  The
document in the language of the current user gets updated but the
translations (including en-US) do not if you are logged in with another
language.  Then if there is no language set on partner but on the user
editing, then output doesn't change.

**Comment by TheCloneMaster** [comment]
Hi Olivier,

As always, great explanation !!


These two posts deserve their own space on Odoo help Q&A...

Regards,

**Comment by esperandus** [comment]
Agreed - very helpful!

And a +1 for switching the email template to Qweb syntax.

**Comment by smack815** [comment]
+1 for @Yenthe666 to write a [Odoo Help question](odoo.com/forum/1) and for @odony to answer it.

**Comment by Yenthe666** [comment]
@odony it seems that you're right. If I use street or name the template seems to work!
When creating a template from the browser lay-out the %if %endif seems to work too but there are some flaws here. 
When you create a mass mailing template through the "Edit template", then save it and then edit it (through marketing > mail templates)  to view the code you'll see it generates <br>. If you now go into HTML mode to edit it and then do a preview you'll see the <br> isn't converted anymore. It prints out the br and if you go into HTML edit mode and replace <br> by <br /> it will still be rendered to <br>. I assume this is done automaticly by the parser.. so there seems to be some things off there!

Could these things also be included in the official documentation with a few samples / use cases? I feel that this is something that more people could use and it is a great benefit for mass mailing.
Is the descision already taken to switch over to QWeb e-mail templates in place of Jinja2 by the way? I feel that this has much better options and would make it easier for people to use since it both uses the same technology. Is there any date planned on when the QWeb version will be rolled out in place of Jinja2?

**Comment by odony** [comment]
@Yenthe666 You have to keep in mind that the backend HTML editor (*edit*) and the frontend (*edit template*) are completely different for the moment, so they may parse/modify the template quite differently. The old backend editor deals with HTML, while the frontend uses XHTML documents (as the frontend templates are supposed to be XML views, CMS pages, etc.). This typically explains differences in taste for ``<br>`` vs ``<br/>``.

There is no date set for switching email templates to QWeb yet, but it is likely to happen for Odoo 9. The problem here is not the switch of technology (that's trivial), but rather the planning and rewriting all existing templates to the new format.

Regarding user documentation, a good place to include this kind of advanced user guide would be the [Odoo Help promoted questions](https://www.odoo.com/forum/how-to). As mentioned by @TheCloneMaster and @smack815 you could start by asking a nicely worded question in the [Help Forum](https://www.odoo.com/forum/1), then someone can summarize the comments on this issue, and then we can promote this question as a "how to".

**Comment by Yenthe666** [comment]
@odony thanks for the feedback and extra information. First of all, its great to hear the switch will most likely be made to Odoo V9! I have a feeling QWeb has a lot more possibilities.
I will create a help question about this with some detailed examples / problems in my question and then you can provide your answer perhaps? Your comments explain a lot they only need some minor tweaking to make it fit. Give me about a day to create this.

**Comment by Yenthe666** [comment]
@odony I've made the question on the forums. You can find it here: https://www.odoo.com/forum/help-1/question/if-endif-does-not-seem-to-work-with-mail-templates-sent-e-mails-are-blank-74389
Could you please add your answer? I don't want to run off with the credit/karma :) I'll accept & upvote it when you posted it and we'll then promote it to the docs.

**Comment by ossimantylahti** [comment]
Updating a bit for this original question for Odoo 13. The issue is still present and can easily cause total e-mail template rendering failing if one evaluation fails. We ran into this when modifying Spanish language version of the offer e-mail template. A typical use case is to check if a field has content or not before printing it out to the e-mail template as fields without any content set to them evaluate as text "False".

In our case we wanted to print tittle of the recipient if he has one ("Dear doctor Stephen Strange" if Stephen Strange has tittle defined). The field is object.partner_id.title.name and to check if it is filled, the code is following:

```
% if object.partner_id.title.name:
 ${object.partner_id.title.name}
% endif

```

So the whole block becomes:


```
<div style="font-size:13px;font-family:&quot;Lucida Grande&quot;, Helvetica, Verdana, Arial, sans-serif;margin:0px;padding: 0px;">
    <p style="margin:15px;font-size:13px;font-family:&quot;Lucida Grande&quot;, Helvetica, Verdana, Arial, sans-serif;padding: 2px; font-size: 13px;">
% set doc_name = 'oferta' if object.state in ('draft', 'sent') else 'orden'
        Estimado  
% if object.partner_id.title.name:
 ${object.partner_id.title.name}
% endif

${object.partner_id.name},
        <br><br>
        Su
% if ctx.get('proforma'):
            Pro forma factura ${doc_name} <strong style="font-weight:bolder;">${object.name}</strong>
% if object.origin:
                (with reference: ${object.origin} )
% endif
            con el precio total de <strong style="font-weight:bolder;">${format_amount(object.amount_total, object.pricelist_id.currency_id)}</strong> está disponible.
% else:
            ${doc_name} <strong style="font-weight:bolder;">${object.name}</strong>
% if object.origin:
                (with reference: ${object.origin} )
% endif
            con el precio total de <strong style="font-weight:bolder;">${format_amount(object.amount_total, object.pricelist_id.currency_id)}</strong> está listo para su revisión.
% endif
        <br><br>
        No dude en contactarnos si tiene alguna pregunta.
        <br><br></p>
    <p style="margin:15px;font-size:10px;font-family:&quot;Lucida Grande&quot;, Helvetica, Verdana, Arial, sans-serif;padding: 2px; font-size: 8px;">
Términos y condiciones generales: ...Terms and conditions here...
    </p>
</div>
```

**Comment by pedrobaeza** [comment]
You must edit the template always in code mode for avoiding that.

**Comment by source-promo** [comment]
@Yenthe666 @ossimantylahti @Yenthe666 
I followed all your discussion here in detail and I have exact same issue! Unfortuantely I was not able to really extract the solution for this back and forth.

So I am usering Odoo V12 and run into this issue! 
I try to create a mass mailing where my Name (Christian Mahlich) is added if no sales person is linked to the partner (object.partner_id.user_id)

![Bildschirmfoto 2020-08-28 um 17 10 45](https://user-images.githubusercontent.com/46195184/91583381-70a97d00-e951-11ea-9c1d-e1b23a35e46d.png)

I tried many things (also switched to code view) but I always receive Mails like this (if else code printed out and not executed):
![Bildschirmfoto 2020-08-28 um 17 15 47](https://user-images.githubusercontent.com/46195184/91583918-24127180-e952-11ea-8041-9577583f13d1.png)

I tried to work on code view directly:
![Bildschirmfoto 2020-08-28 um 17 18 34](https://user-images.githubusercontent.com/46195184/91584189-95522480-e952-11ea-89c8-1b46ab2a6b1e.png)
Becomes this:
![Bildschirmfoto 2020-08-28 um 17 20 35](https://user-images.githubusercontent.com/46195184/91584368-d21e1b80-e952-11ea-90d3-9f15b3801f06.png)

I hope you can help me how to use if else code in mass mails on Odoo V12!
Thanks in advance!

**Comment by MaximeDelarue** [comment]
@source-promo 
the <br> tags are breaking the template.
Remove them and try again 
(working fine in V13 with HTML editor)

**Comment by koulchi** [comment]
@source-promo
the `<br>` tags are breaking the template.
Remove them and try again
(working fine in V13 with HTML editor)
