### ISSUE TITLE
[13] Employee should not be his own Manager

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#47043]
Impacted versions: 13.0

Steps to reproduce: Assign same employee as manager.

Current behavior: It allows you to Select same employee as manager
![screenshot-1639418-13-0-6ecc34 runbot41 odoo com-2020 03 06-00_22_08](https://user-images.githubusercontent.com/16624719/76015003-9294ea80-5f40-11ea-8bd8-69dac21db43c.png)

Expected behavior: Same as v12, recursion should be blocked 
![screenshot-1637045-12-0-319ea5 runbot11 odoo com-2020 03 06-00_23_09](https://user-images.githubusercontent.com/16624719/76015093-b6583080-5f40-11ea-8773-2a030e6d26ad.png)

Video/Screenshot link (optional):

**Comment by LucasLefevre** [comment]
Hello @sswapnesh 

Thanks for the feedback. But it is an intentional behavior. Recursion was explicitly added with https://github.com/odoo/odoo/commit/48254cc8a153e061b64c399abb90cf4d4440bd65

While having the employee manager being the employee himself is a bit weird, it's not a real issue.
Hence I'll close this issue.

Thanks

**Comment by sswapnesh** [comment]
> While having the employee manager being the employee himself is a bit weird,

Maybe we should Remove that constraint in the `hr_org_chart` module only. (Not from `hr`)
