### ISSUE TITLE
[13] base: Translations are not Removed on Module Uninstall/Duplicated on Reinstall

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#47139]
Duplicate of https://github.com/odoo/odoo/issues/25105
Fixed at https://github.com/odoo/odoo/pull/30721

Impacted versions: 13.0
Tested with Project module at http://1666860-13-0-ccb00b.runbot23.odoo.com/

Steps to reproduce: 
- Activate other Language (Which loads Translations)
- Uninstall module

Current behavior: Translated Terms related to the module are not deleted

![image](https://user-images.githubusercontent.com/16624719/76143829-ac4d4380-60a0-11ea-9dd3-5c8f216636c1.png)

Expected behavior:  Translated Terms Should be deleted on Uninstallation

Video/Screenshot link (optional):

**Comment by mart-e** [comment]
Hello,

We have reverted the patch at e2e4b16751a23f591f9 to make a different patch at 112bd835d80619a03.
It's actually fine to keep translations in the database, we cover the problematic scenario at 112bd835d80619a03 (column removal).
If you can reproduce a scenario similar to #25105 where we had a traceback because of this, we can investigate. Otherwise, let's not do anything.

**Comment by sswapnesh** [comment]
>  where we had a traceback because of this,

I don't think I got any traceback because of that.
