### ISSUE TITLE
[13] account: Required field is invisible on form view

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#47144]
Impacted versions: 13.0

Steps to reproduce: 
- Create a Company with No address (or Just Remove `country_id`)
- Create a new Tax Report line

Current behavior: Required field `country_id` is not set
![image](https://user-images.githubusercontent.com/16624719/76163275-c4899500-616a-11ea-8ee4-3ac93eecdfe6.png)

Expected behavior: Make field visible on the view (or Not required _if not needed_)

Video/Screenshot link (optional):

**Comment by sswapnesh** [comment]
@oco-odoo  I initially made a Commit to Fix this at https://github.com/odoo/odoo/commit/8f2f688f07781146476b4e6fdf128e1fdafd9dcb  but we have to handle few more cases as well.

- Re-evaluate domain when we change `country_id` 
https://github.com/odoo/odoo/blob/ed459c1bcfa8104c4116da2d5767d5ea4457463d/addons/account/views/account_tax_report_views.xml#L30

- Force the same `country_id` on `children_line_ids` as well. (Maybe Readonly on `children_line_ids`)
https://github.com/odoo/odoo/blob/ed459c1bcfa8104c4116da2d5767d5ea4457463d/addons/account/views/account_tax_report_views.xml#L55


What is your opinion?

**Comment by oco-odoo** [comment]
Hi @sswapnesh 

Though I agree this is a limitation of the model, it's still relatively small: in practice, won't the company always have a country_id set ? Combined to the fact creating tax report lines manually (though it's perfectly legit) is also something pretty rare, I think we would just be adding complexity by allowing changing the country_id of tax report lines manually, which could end up in additional bugs. Plus, the company will need to have the right country_id anyway in order for the tax report to be visible for it (otherwise it won't be selectable from the generic tax report). 

We actually added an account.tax.report object in 13.1, which gathers all the report lines and now contains the country_id field (so, it's ot on the lines anymore). This was initially done to support multiple tax reports for a single country, but it also allows changing the country of an existing report directly from the form view (this was required by some countries using the report of others, Egypt, for example, if I remember well). Hence, this feature also solves the problem you have here, so nothing to worry about for future versions. 

I suggest we close this issue; is it ok with you?

**Comment by Yenthe666** [comment]
Sounds like a better solution in 13.1 so I'd vouch to keep it as-is for V13 and handled in V13.1.
