### ISSUE TITLE
This is a bug. You should not close it. If you are just using runbot to close issues, that is bad practice.

### ISSUE THREAD

**Issue by deepdad** [odoo/odoo#47394]
This is a bug. You should not close it. If you are just using runbot to close issues, that is bad practice.

_Originally posted by @deepdad in https://github.com/odoo/odoo/issues/47356#issuecomment-597616268_

**Comment by Yenthe666** [comment]
Don't create duplicates because you're not happy with the response from somebody. You can carry on the discussion on the original report.

**Comment by deepdad** [comment]
Don't ask people to use the slow runbot to deny Odoo bugs.

**Comment by Yenthe666** [comment]
Its not slow and it is policy if we do not find a way to reproduce it. Just follow what is asked and you will see that people genuinely try to help you :)

**Comment by deepdad** [comment]
It is clear from the screen shots that it is a bug. It is impossible to replicate my configuration in runbot. Which is slow. It is policy that closed issues count as resolved.

**Comment by Yenthe666** [comment]
@deepdad it is not because you have an error in your local instance - where Odoo has no control over - that the issue is actually there in Odoo. Perhaps your instance is still running on older code? Have you updated it to the latest code?
Besides of this I've tried to reproduce it and the behaviour works fine on the latest 13.0 so I don't know what else you'd expect from me and @pedrobaeza.

**Comment by deepdad** [comment]
If you hadn't closed the issue or even just read it, you would have noticed the version number and not be wasting time on asking me this question. I'm willing to help you fix up the software. I can't pull a more recent docker image.

Now you don't know what the issue is either. I think the odoo docker log shows it: when you start typing the URL, a (JSON?) request is made upon typing the first letter. Prematurely.

I haven't been in developer mode and I haven't installed apps from other developers. User configurations are too complex to replicate in runbot completely. You apparently still ask users to try and do so. Then close the issue without looking at logs. Kind of sucks.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by Yenthe666** [comment]
@deepdad okay, I'm done with your arrogance. Both @pedrobaeza and myself have tried to ask for extra info for helping in the ticket and you've only started ranting right away. We have no clear way to reproduce it and your Odoo code doesn't seem to be up to date.

Let me be clear: both me and @pedrobaeza are not official Odoo employees. We do the issue triaging without being paid or compensated in any way and we spent several hours a week doing so. In fact, I have spent thousands of hours of my life to help others and fix bugs in Odoo so don't call me out for not wanting to help. If you put so much of your time and effort into Odoo as we do we'll talk again.

This will be my final comment and I will not repeat myself. Give us a reproducable way on runbot or in written steps (on the initial ticket) and we'll look into it, otherwise we cannot do anything for you.

**Comment by deepdad** [comment]
Oh, I'm sorry. My apologies. I thought you were with the Odoo company. I am not calling you out for not wanting to help. I would have just liked you to consider the facts that I use the default docker image and that configurations are not easily replicated in runbot. I understand your capacity limitations however and that your standard procedure is your best practice that helps you with this. So, my apologies.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by Yenthe666** [comment]
Appreciate the apoligies, thanks :) I personally don't use docker images so I'm not the best to advise here but the code in your instance is out of date with the latest from Odoo so try upgrading that first
