### ISSUE TITLE
is odoo 13 is stable version ?

### ISSUE THREAD

**Issue by composercodes** [odoo/odoo#47392]
Hi
 please I want to ask you if odoo 13 is stable version, or you would prefer use odoo 12
What do you think please
Or wait for 14
Thanks,

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here. Any way, yes Odoo v13 is released since October 2019 and stable, but maybe your stability concept may differ.

Closing this by the reason above.

**Comment by Yenthe666** [comment]
For the record: Odoo 13 is stable and working great. Running it for three customers in production already.
