### ISSUE TITLE
The --without-demo flag does not seem to be working

### ISSUE THREAD

**Issue by Sathors** [odoo/odoo#4780]
**The --without-demo flag does not seem to be working**

Impacted versions:

 - 8.0

Steps to reproduce:

 1. create a new database with the "Load demo data" checked.
 2. issue on the command-line `./openerp-server -c my_rc_file -d my_db -i account_asset --without-demo=account_asset` to install the account_asset module.

Current behavior:

 - account_asset demo data is loaded in the db

Expected behavior:

 - that it does not get loaded in the db

**Comment by xmo-odoo** [comment]
`—without-demo` is really a database-creation flag. It does work when installing things into a completely empty database (just created with `createdb`).

Other cases aren't supported, in the best cases the option is essentially ignored and in the worst cases it can leave the database in a state requiring manual intervention.

And the value is more or less ignored, since demo data generally relies on dependencies's demo data loading the demo data for half the module and not the other half tends to have problematic results.

That is definitely something which should be improved and better documented (by deprecating/removing the existing option and adding a binary flag which is only active when initialising a new database), feel free to open a wishlist issue for that.

**Comment by Sathors** [comment]
Thanks for the prompt behavior.

Actually I wanted to use it because, it seems that in order to test I need a database demo, and I didn't want to load the account_asset demo data, because it is not compatible with my custom account_asset module. Or I was looking for a way to overwrite the father's data for example.

As for the issue at hand, when you advise me to create a wishlist issue, I just have to create other issue with another name which represents better a wish? Because I don't think I can flag it as wishlist, can I?

Thanks.

**Comment by xmo-odoo** [comment]
> Actually I wanted to use it because, it seems that in order to test I need a database demo

Yeah, many tests rely on demo data to do their thing, so they require demo data to be installed.

> I didn't want to load the account_asset demo data, because it is not compatible with my custom account_asset module. Or I was looking for a way to overwrite the father's data for example.

It might be possible by altering the database itself (marking the `account_asset` as not having demo data) but that's risky if account_asset alters existing models.

> Or I was looking for a way to overwrite the father's data for example.

It is possible to overwrite existing demo data with your own, or alter existing demo records.

> As for the issue at hand, when you advise me to create a wishlist issue, I just have to create other issue with another name which represents better a wish?

Yep, maybe refer to this issue for background as well

> Because I don't think I can flag it as wishlist, can I?

Correct
