### ISSUE TITLE
traceback in docunent app while open studio

### ISSUE THREAD

**Issue by sangitassh** [odoo/odoo#48267]
Impacted versions:
13.0
Steps to reproduce:
open document app
then open studio then trackback will occurred
Current behavior:

Expected behavior:

Video/Screenshot link (optional):

![pppp](https://user-images.githubusercontent.com/62560455/77432694-6e704f00-6e04-11ea-8bfd-0efb09f6c7d3.png)

**Comment by sangitassh** [comment]
@jvm-odoo  ping

**Comment by sangitassh** [comment]
@Yenthe666  ping

**Comment by pedrobaeza** [comment]
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by sangitassh** [comment]
yes

**Comment by pedrobaeza** [comment]
Also as this is something enterprise, you should report it on odoo.com/help, not here.

**Comment by sangitassh** [comment]
i have provieded screenshot

**Comment by pedrobaeza** [comment]
Yeah, right, but as said, this is something enterprise. Can you please put the ticket on odoo.com/help?

**Comment by Yenthe666** [comment]
Besides, please don't ping random people on all those tickets ;) This is the third one you ping me in already.

**Comment by sangitassh** [comment]
ok thank you
