### ISSUE TITLE
List of accounts is too slow (__compute balance debit credit)

### ISSUE THREAD

**Issue by ccomb** [odoo/odoo#4835]
Even on relatively small databases, the list view of the accounts is too slow (because of the balance, credit and debit columns, computed by the __compute method). For instance on a small database with ~12000 move lines and ~1200 accounts, it takes 3 to 4 seconds to display. On a database with 100k+ or 1M lines, it can take several minutes. the problem is that the account list is used everywhere to select an account and it becomes unusable.

This has already been reported on LP and I didn't find the equivalent report on github : https://bugs.launchpad.net/openobject-addons/+bug/887376
There is an old merge proposal here : https://code.launchpad.net/~vauxoo/openobject-addons/trunk-bug_887376-account_move_compute_with_btree-moylop260/+merge/81731 which is superceded by a newer one: https://code.launchpad.net/~vauxoo/openobject-addons/trunk-bug_887376-account_move_compute_with_btree-moylop260/+merge/89623

Even if this is supposed to be rewritten for v9, I think it's worth optimizing the __compute method.

**Comment by nhomar** [comment]
@ccomb the problem with our solution is that it uses a solution that is very advanced in terms of postgresql.

odoo must be aware of such technique to compute btree elements, but even the hierarchy will not be available for v9.0 then not only our solution will be useless, even wors without hierarchy on v9.0 as a mandatory feature on account_account object our patch will not be possible to be ported (at least in a communitary way we encourage such feature).

I really appreciate the PoV of @qdp-odoo and @fpodoo on this topic because IMHO it is critical for several reasons.

I can not face a correct way to achieve a better and more efficient approach than this without out parent - child relation as a mandatory data structure on account_account (as it is planned to be done on v9.0).

AFAICU the new approach will be throught account types (which I strongly beleive It is wrong, but it is a decisition taken I think.).

For better references of [new accounting approach](https://docs.google.com/document/d/1MahXh0TdfjI0ohdTSz_c8cML7HqxvcAtvSAY63N20Tc/edit?usp=sharing) follow the link.

Regards.

**Comment by Yenthe666** [comment]
Hi @ccomb,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
