### ISSUE TITLE
Field with `compute` recomputed with wrong values  in some conditions

### ISSUE THREAD

**Issue by guewen** [odoo/odoo#4851]
**Field with `compute` recomputed with wrong values in some conditions**

Sorry, this is really, really vague. But the test that I will push will help I hope.

Impacted versions:

 - 8.0 and above, since 5fee95c (or 2f06add, I ran git bisect but couldn't run the tests on those commits)

Steps to reproduce:

 1. Here is a test case (it is extracted and simplified from a larger module): https://github.com/guewen/odoo-test-case-4851 

Current behavior:

 - The test is red

When the test run on the HEAD of 8.0, in `SaleVIPCoupon._compute_used` (https://github.com/guewen/odoo-test-case-4851/blob/master/model/sale_vip_coupon.py#L48), `self.order_line_ids` is `sale.order.line()`. When it runs on a commit preceding the recent changes on the fields, `self.order_line_ids` is `sale.order.line(31,)` (it was ok so).

I don't know if it can help but a possible cause is that the field in `@api.depends` is a `Many2many` and is the field we are modifying. The compute function is probably called *before* that the new relation is written on `sale.vip.coupon` so the lines do not appear when the function is called.

**Comment by guewen** [comment]
ping @rco-odoo :relieved:

**Comment by rco-odoo** [comment]
This is a nasty bug indeed. In your example, the field `used` was simply not recomputed after the field `vip_coupon_ids` was modified.

The issue comes from the setup of many2many fields. In your example, both many2many fields `order_line_ids` and `vip_coupon_ids` must be recognized as inverse of each other, so that touching `vip_coupon_ids` triggers the recomputation of field `used` that depends on `order_line_ids`. This recognition step only worked if the many2many field was derived from an old-api many2many column.

Thanks a lot for the example module. It helped me a lot for spotting the source of the bug!

**Comment by guewen** [comment]
Thanks @rco-odoo for the fix and for taking the time to explain the issue  :star:!
