### ISSUE TITLE
[13] Error - validate the closure and post entries

### ISSUE THREAD

**Issue by SistemERP** [odoo/odoo#48550]
Make a sale with price 0, from the point of sale.
Then validate the closure and post entries

Error:
You are trying to reconcile some entries that are already reconciled.

Issue:
The box cannot be closed at the point of sale.

**Comment by SistemERP** [comment]
I mean when making an invoice from the point of sale

**Comment by pedrobaeza** [comment]
Please explain clear steps to reproduce the problem, step by step.

**Comment by SistemERP** [comment]
Video
https://youtu.be/4GcU2vT_Tok

**Comment by sswapnesh** [comment]
I can confirm this Behaviour.
Adding Detailed steps

----------------------------------

Impacted versions: 13.0

Steps to reproduce: Runbot https://1940146-13-0-9e41d9.runbot36.odoo.com/pos/web?config_id=1#action=pos.ui&cids=1

* Enable Invoicing from POS Settings
![screenshot-1940146-13-0-9e41d9 runbot36 odoo com-2020 03 29-13_08_17](https://user-images.githubusercontent.com/16624719/77843826-63c80800-71be-11ea-8230-4a4ee82d7466.png)

* Create a Product with 0.0 Sales Price and Make it available on POS
* Create an order with that Product --> Print Invoice from POS
![screenshot-1940146-13-0-9e41d9 runbot36 odoo com-2020 03 29-13_10_12](https://user-images.githubusercontent.com/16624719/77843849-a4c01c80-71be-11ea-8eea-bacf6a987258.png)
* Validate Closing & Post Entries
Current behavior:
![screenshot-1940146-13-0-9e41d9 runbot36 odoo com-2020 03 29-13_10_53](https://user-images.githubusercontent.com/16624719/77843858-c8836280-71be-11ea-8c67-bd4a28ae7e53.png)

Expected behavior: Able to Close session

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
@pimodoo

**Comment by pimodoo** [comment]
@caburj can you have a look when you have some time, not a pirority

**Comment by caburj** [comment]
@pimodoo I saw the problem quickly so I made a quick fix. The pull request solves the problem in more general way. And I believe we can also use this strategy for other issues just like this.

**Comment by SistemERP** [comment]
Thanks

**Comment by trinanda** [comment]
In Odoo16 I'm facing the same problem, create an order with a total of 0, the same error will appear:

**You can only reconcile posted entries.**

**Comment by imunisasi** [comment]
> In Odoo16 I'm facing the same problem, create an order with a total of 0, the same error will appear:
> 
> **You can only reconcile posted entries.**

same here but the order isn't 0
it's on invoice , try to confirm

You can only reconcile posted entries
