### ISSUE TITLE
Accept Meeting in Calendar

### ISSUE THREAD

**Issue by manishpatell** [odoo/odoo#4858]
1- When user send meeting invitation to customer 
2. customer try to Accept, Decline, View from email 
3. Error: Forbidden
You don't have the permission to access the requested resource. It is either read-protected or not readable by the server.
4. Reason: customer not logged in (as per my understanding)
5. Resolution: it would be wise move if 'Customer get Sign Up page' where he can sign up and view/ accept meeting invitation.

**Comment by fdu007** [comment]
I experience the same issue... :-(

**Comment by harsh3547** [comment]
there' no bug......the error message is
"""Invitation cannot be forwarded via email. This event/meeting belongs to xxxxxx@xxxxx.com and you are logged in as admin@yourcompany.example.com."""
if you are testing this functionality....you'll have to log out and accept this invitation via email
the customer who'll be accepting this invitation via email....won't face this problem coz he'll not be logged in....
even if he is logged in the attendee.email==user.email will be the same for the customer so there'll be no error

**Comment by manishpatell** [comment]
Harsh, Thanks for consider this issue,
1- Invitation is not forwarded to any 
2. I logged out from 'admin' account then opened Invitation directly from email.
3. I am getting 'Forbidden' error.

**Comment by fdu007** [comment]
I confirm I try it also but still facing the same forbidden error. 

> Le 29 janv. 2015 à 11:21, manishpatell <notifications@github.com> a écrit :
> 
> Harsh, Thanks for consider this issue,
> 1- Invitation is not forwarded to any 
> 2. I logged out from 'admin' account then opened Invitation directly from email.
> 3. I am getting 'Forbidden' error.
> 
> —
> Reply to this email directly or view it on GitHub.
> 

-- 
 
------------------------------
Keystone Solutions disclaimer: 
https://www.keystone-solutions.be/disclaimer/e-mail

**Comment by harsh3547** [comment]
sorry for the last incorrect answer.......

the problem for most of you will be because you are running multiple databases.............

when u accept the invitation check the server logs and you'll see the "None werkzeug" in the line where the accept invitation link was received"

the solution is to run the server with --db-filter

eg...     openerp-server --db-filter demobase

when the meeting is accepted , openerp will by default check in demobase

for more clarification check the docs folder in odoo---------odoo/setup/deploy.rst

**Comment by JosefKaser** [comment]
@harsh3547:
That's an explanation but not a solution. What if one needs to run his odoo with multiple databases?

Me and some of our customers are facing this "broken link problem" with meeting invitations and password reset links. And for none of our customers the db-filter thing would be a valid solution.

Anyone having another idea to fix this?

**Comment by nathanclayton** [comment]
This issue also  comes up with a use who isn't logged in. Ideally if it's not the correct user, an error page would come up with a link to log out, which would flow to the next sentence. If there isn't a user logged in, an error page with a login form would come up.

**Comment by Yenthe666** [comment]
Hi @JosefKaser,

The issue that you're facing is because you have multiple databases. When you have multiple databases and want to use features such as mass mailing you should configure a `dbfilter`.
You can find the documentation regarding dbfilter at https://www.odoo.com/documentation/8.0/setup/deploy.html.
Without this dbfilter the URL that is created (and e-mailed to the customer) will not have an unique identifier to link to the correct database. Since Odoo does not know which database you're referring too the URL will not work.
After configuring a dbfilter the URL's will pass on extra data in order to link to the correct database.

Regards,
Yenthe

**Comment by oerp-odoo** [comment]
When I click invitation link, get this error: `Invitation cannot be forwarded via email. This event/meeting belongs to email@email.com and you are logged in as email@email.com. Please ask organizer to add you.`

This error occurs, if you try to accept invitation, while you are logged in Odoo. If I log out (or use incognito), then I can accept invitation via email. I would say it is kind of dumb that you can only accept via link if you are not logged in..

Also whats funny, my login uses same email I got invitation for. Even Error shows that (which could look confusing. Saying invitation is for email A, but you are logged in as email A. What?..)

P.S. Reproduced on Odoo 11

**Comment by Yenthe666** [comment]
@oerp-odoo this is in all Odoo versions actually. It's indeed preventing accepts of your own.

**Comment by oerp-odoo** [comment]
@Yenthe666 so it is intended? It does not make sense. And its not accepts of my own. 
In our case, we have people that plan meetings for us and they create events and invite other users (from Odoo), so we can accept or decline invitation.

So this case I mentioned was not accept of myself (like if I invited myself), other user invited me (and Im not the owner of that event).

Its also gives same error when I try to view event view 'View' button, that I receive via email, where you can accept/reject/view.

If its intended, can anyone explain the reasoning here?

P.S. I think it should behave similarly as it is in let say Google calendar. You can accept/decline event if you are logged in gmail.

**Comment by Yenthe666** [comment]
I think @JKE-be actually was involved in this development at that point, maybe he knows more about it
