### ISSUE TITLE
document management system module

### ISSUE THREAD

**Issue by ccandito** [odoo/odoo#4864]
Dear Odoo Support,
I've installed the DMS module in V8.0 replayed the same setting done in V7.0.
Unfortunately it does not work out.
I've also noticed the document link in missing in knowledge screen on left side.
Regards
claudio

**Comment by LeartS** [comment]
I also spent a lot of time trying to understand and debug the document module and its various quirks. [I opened an issue](https://github.com/odoo/odoo/issues/4868), didn't see you already opened this one.

**Comment by Yenthe666** [comment]
Hi @ccandito I'm closing this issue. The issue made by @LeartS (found at https://github.com/odoo/odoo/issues/4868) has more details and information, which makes the whole topic more clear.
Both are about exactly the same so I'm closing this one as a duplicate in favour of https://github.com/odoo/odoo/issues/4868 due to more information.

Regards,
Yenthe
