### ISSUE TITLE
ERROR : print purshase order in frensh

### ISSUE THREAD

**Issue by kazi94** [odoo/odoo#48654]
Impacted versions: 13

Steps to reproduce: print purshase order in frensh
![image](https://user-images.githubusercontent.com/16700169/78008068-761d7f80-733f-11ea-8104-044ea5b99b64.png)
```
Server Error :
Odoo Server Error
Traceback (most recent call last):
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\addons\web\controllers\main.py", line 2031, in report_download
    report_name = safe_eval(report.print_report_name, {'object': obj, 'time': time})
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\tools\safe_eval.py", line 347, in safe_eval
    c = test_expr(expr, _SAFE_OPCODES, mode=mode)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\tools\safe_eval.py", line 206, in test_expr
    code_obj = compile(expr, "", mode)
  File "<string>", line 1
    (object.state in ('draft', 'sent') and 'Demande de Prix - %s' % (object.name) or                 Bon de Commande - %s' % (object.name))
                                                                                                          ^
SyntaxError: invalid syntax
```

**Comment by Yenthe666** [comment]
@kazi94 this happens because somebody has made a mistake in the translation term of the template. Please find the template on https://www.transifex.com/odoo/ and correct it both in Transifex and in your local database.
This:
(object.state in ('draft', 'sent') and 'Demande de Prix - %s' % (object.name) or Bon de Commande - %s' % (object.name))
Should be:
(object.state in ('draft', 'sent') and 'Demande de Prix - %s' % (object.name) or 'Bon de Commande - %s' % (object.name))

**Comment by kazi94** [comment]
Hi,

Thank you for your quick response to my issue.

i am novice in Odoo, can you help me how to correct the translation in my local database?
I appreciate it

Thank you so much.

**Comment by mart-e** [comment]
Hello,

The translation was already [fixed upstream](https://www.transifex.com/odoo/odoo-13/translate/#fr/purchase/180739865?q=translation_text%3A'Demande+de+Prix') 4 months ago so you should first make sure your Odoo installation is up to date.
Once this is done you should refresh your translations by doing to Settings > Languages and reload the French language to overwrite the previous terms.

Alternatively, you can go, in debug mode, to Settings > Technical > Report and search for the purchase order report to manually correct the translation.

Closing was already fixed in Odoo
