### ISSUE TITLE
[13] Changing current company through User setting doesn't work

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#49436]
Impacted versions: 13.0

Steps to reproduce: On a Multi-company mode

- Add both Companies in Allowed Companies and Select one of them as Current company
![screenshot-2157817-13-0-b06fed runbot44 odoo com-2020 04 11-12_18_58](https://user-images.githubusercontent.com/16624719/79037443-ad691780-7bee-11ea-9b3d-b8728223e932.png)

- Change Current company from User --> Current Company

Current behavior:
Current Company is not updated (As you can see in Header and On creating new Record)
![screenshot-localhost_8069-2020 04 11-12_28_08](https://user-images.githubusercontent.com/16624719/79037563-f40b4180-7bef-11ea-89ca-541d2c2ec623.png)
![screenshot-localhost_8069-2020 04 11-12_28_46](https://user-images.githubusercontent.com/16624719/79037574-04232100-7bf0-11ea-8356-16e36a83acb0.png)

Expected behavior:
The current company should be updated.

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
I think you have missed refresh the page, which is something expected.

**Comment by sswapnesh** [comment]
Refresh doesn't update Company as well, (`cid` in URL is unchanged)

**Comment by pedrobaeza** [comment]
OK, let's tag it

**Comment by pedrobaeza** [comment]
@Feyensv not sure who should handle this.

**Comment by sswapnesh** [comment]
I think this is for @tivisse  as he has worked on Company switcher (IMO we need a solution like https://github.com/odoo/odoo/pull/44386 which changes current company on Header too)

**Comment by tivisse** [comment]
Hi @sswapnesh 

Thanks for the feedback.

Well, your last preferences are stored in the browser's cookies. We could do something to keep the last preferences modification date too, and add a check to know whether we should adapt the cids or not.

But, if you refresh your browser or forge the cids in the url (for example on email notification link), we have to take this info into account. Otherwise you could try to load an invoice form view while being logged in another company -> Access Error.

So it means, that as we have the same entry point for classic navigation and links opening, i.e. /web and the abstract webclient, we shouldn't apply the behavior you describe. 

Imagine:
- I change my default company from A -> B
- I click on a link I received by mail to open a record available on A only
- It opens it on the company B --> Access Error.

Side Note: The default company on the user's form is the company on which the user should land when NO information is available (no cids on the url + no cookies). So in my opinion it does what it is supposed to do :)

So I'm closing this. 

Have a nice day,

Yannick.

**Comment by sswapnesh** [comment]
> But, if you refresh your browser or forge the cids in the url (for example on email notification link), we have to take this info into account. 

But in that case, cids should be updated when you change the company from user's from.

You are right about the Use case about Email link but here I was talking about updating current company.

**Comment by tivisse** [comment]
Ok right, so I misunderstood the purpose. 

Sorry about that. ;)

I'm opening an internal task for a functional validation. 

But I'm not sure that it should be done. It's quite subjective. Personally I wouldn't like to be switched to another company. If I want to stay in the same company, I have 2 more page refreshes instead of 0.

Thanks for the feedback anyway. 

NB: https://www.odoo.com/web#id=2259629&action=333&active_id=809&model=project.task&view_type=form&cids=&menu_id=4720

**Comment by mfhm95** [comment]
> Impacted versions: 13.0
> 
> Steps to reproduce: On a Multi-company mode
> 
> * Add both Companies in Allowed Companies and Select one of them as Current company
>   ![screenshot-2157817-13-0-b06fed runbot44 odoo com-2020 04 11-12_18_58](https://user-images.githubusercontent.com/16624719/79037443-ad691780-7bee-11ea-9b3d-b8728223e932.png)
> * Change Current company from User --> Current Company
> 
> Current behavior:
> Current Company is not updated (As you can see in Header and On creating new Record)
> ![screenshot-localhost_8069-2020 04 11-12_28_08](https://user-images.githubusercontent.com/16624719/79037563-f40b4180-7bef-11ea-89ca-541d2c2ec623.png)
> ![screenshot-localhost_8069-2020 04 11-12_28_46](https://user-images.githubusercontent.com/16624719/79037574-04232100-7bf0-11ea-8356-16e36a83acb0.png)
> 
> Expected behavior:
> The current company should be updated.
> 
> Video/Screenshot link (optional):

the field in the screenshot which should contain the default company for the user,  if you need to get the selected company , 
you may get it by using self.env.company 
because the record in field above returned if you are used self.env.user.compny_id

**Comment by sswapnesh** [comment]
> Ok right, so I misunderstood the purpose.
> 
> Sorry about that. ;)
> 
> I'm opening an internal task for a functional validation.
> 
> But I'm not sure that it should be done. It's quite subjective. Personally I wouldn't like to be switched to another company. If I want to stay in the same company, I have 2 more page refreshes instead of 0.
> 
> Thanks for the feedback anyway.
> 
> NB: https://www.odoo.com/web#id=2259629&action=333&active_id=809&model=project.task&view_type=form&cids=&menu_id=4720

@tivisse  Any Feedback ?
