### ISSUE TITLE
[13.0] product expense account is not used on invoice lines

### ISSUE THREAD

**Issue by jjscarafia** [odoo/odoo#49444]
Impacted versions:
13.0

Steps to reproduce:
1. set an expense account different to default one, to any product
2. create a vendor bill and add this account

Current behavior:
1. default account is used

Expected behavior:
1. product account should be used

Video/Screenshot link (optional):
https://drive.google.com/file/d/1hJo9QPRPlvsemi2csQQrW5C9ed3i6Fwn/view

**Comment by HalaSalameh** [comment]
it doesnt even take the default account, it takes based on alphabetical . try naming the product anything that has a word , ie: bank and add an account with "bank" word in it, and it chooses this account regardless of the expense account in the product. if you change the name of the product, the chosen account changes too!

**Comment by gdgellatly** [comment]
Do you have predictive Bill's enabled?

**Comment by jjscarafia** [comment]
Yes @gdgellatly , it seams predictive bills is installed by default.
After uninstalling it works correctly, so the error seams to be with predictive bills, because for a new product with an expense account the expense account is not used.

**Comment by jco-odoo** [comment]
@csnauwaert @oco-odoo Probably not wanted behaviour?

**Comment by gdgellatly** [comment]
@jco-odoo Honestly predictive bills is really, really bad in any kind of large environment, especially where 90%+ of transactions are just regular stock supplier invoices because it hugely distorts results. At least part of the fix should be not enabling it by default.

Hence why it was so easy for me to guess the problem. It can end up in a self perpetuating clusterfk. Its like those word games as kids when you start with a word and replace 1 letter at a time to form a new word eventually transforming to the final word.

A recent example I saw on an instance.

- A company buys a bitumised paper with the word underlay as part of its description, normal stockable product, company buys thousands of rolls per month.
- A random supplier invoice for a new office being built to install `carpet and underlay`. Autocodes to the product and account  (which is anglo saxon AP Accrual) .
- You see the problem, so you credit it and code correctly, but guess what, the incorrect coding for carpet outweighs the correct coding 2 to 1.
- Next a carpet cleaner comes in and it gets coded to that account and product code.
- Do the credit, now you losing 4 to 1 because cleaning office carpets (expense) and installing new carpets (asset) are different accounts.
- A few weeks later you get to where catering for the office opening party is now also underlay.
- A few weeks later again, you may as well have one product code and account.

Don't even get me started on the multicompany chaos or even just the UI issues in changing a precedent field in an onchange. 

Its like a miniature game built into Odoo for admins and support people to check they are paying attention.

The first time I got a bug report I was incredulous, told my support guys to sort it out themselves, figuring the user had setup some stupid kind of default, so they stepped it through live in UI. Lucky it is just one little check box to fix permanently.

**Comment by oco-odoo** [comment]
I found this by having a quick look at the code: https://github.com/odoo/enterprise/blame/13.0/account_predictive_bills/models/account_invoice.py#L178 

@smetl What do you think ?

**Comment by smetl** [comment]
@oco-odoo Maybe the prediction shouldn't predict the default account to avoid erasing the product's account? I'm not sure ...

**Comment by smetl** [comment]
Issue fixed in 13.0 at revision:
https://github.com/odoo/enterprise/commit/8c846950bf38e3bfe7dc21df9f33fec8294d6b9a
