### ISSUE TITLE
asset_styles_company_report.scss file does not exist.

### ISSUE THREAD

**Issue by aakashct** [odoo/odoo#49456]
Impacted versions:
odoo v-13
Steps to reproduce:

Current behavior:
the scss asset_styles_company_report.scss mentioned in the file https://github.com/odoo/odoo/blob/13.0/addons/web/views/report_templates.xml does not exist at the given web/static/src/scss path.
It does not give error when you print the quotation pdf but it gives error when you print the report in the html format.
Expected behavior:

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
@qsm-odoo probably for you

**Comment by pedrobaeza** [comment]
Are you installing from deb package?

**Comment by pedrobaeza** [comment]
Related to #48227 ?

**Comment by aakashct** [comment]
@pedrobaeza @Yenthe666 Thanks for the reply. i have not installed from the deb package, i am running odoo by cloning the 13.0 repository. i am not sure if that is what you are asking though.

**Comment by pedrobaeza** [comment]
Yes, then it's not related, so let's see the answer from Odoo team.

**Comment by qsm-odoo** [comment]
Hello, the file apparently exists as a DB attachment. @kebeclibre this seems related to https://github.com/odoo/odoo/commit/7c488b7180f620e28bc747c9b85f630d0b2b798a, I did not investigate further... somehow the assets here were updated but the required attachment not created?

**Comment by kebeclibre** [comment]
@aakashct 
It is perfectly normal that the file does not exist in the file system.
The path would just serve as the src of the <link /> tag in the HTML source. Then, when the browser makes its request to Odoo to load the file, Odoo knows it is an attachment.

Now, we made sure we tested that thing in a new db as well as on an already existing db on which one would upgrade a module.

So, I'd like you to be extra precise in describing what you've done, Because:
- If the DB is new, there should be no problem with objects and meta objects (i.e. external identifiers or xml_id for short)
- if the the meta objects (xml_id) doesn't exist, there is a silent fallback, I think it just ignores it.

My bet is that the attachment had been deleted, but not its meta object which points to it. But even in this case there is a fallback.

I guess the vital minimum to avoid back and forth and wasting time is posting the error you get, and be a bit more specific in the steps to reproduce.

**Comment by aakashct** [comment]
@kebeclibre My DB is new. Here is the photo of the error. This error only comes when i print the report in the HTML format. 
When i print the report in the PDF, i don't get the error but the header does not come in the PDF report(I thought the issue was with the web.base.url but it wasn't). 
The header in report only shows when i comment the line which adds the asset_styles_company_report.scss in report_templates.xml file.
I should also mention that the error does not reproduce in the runbot. So please let me know what could be the reason for this. Thanks for your time.
![error](https://user-images.githubusercontent.com/44608752/79205789-07bae000-7e5c-11ea-8dd8-46a922fd59dc.png)

**Comment by kebeclibre** [comment]
@aakashct 
https://github.com/odoo/odoo/blob/13.0/odoo/addons/base/models/assetsbundle.py#L674
The error comes from there.
I think the original error is triggered by b64decode, either because the string it tries to decode is not actually b64, or because it is a string or not bytes.
Anyways, it is probably a mis-manipulation on your side, so, until proven otherwise, i close the ticket

**Comment by kebeclibre** [comment]
haha, gotcha. You deleted the view web.styles_company_report
