### ISSUE TITLE
Use subsequences of odoo13(Changing the order date causes the order number to repeat)

### ISSUE THREAD

**Issue by naxiangzi** [odoo/odoo#50184]
Impacted versions:odoo13

Steps to reproduce:
 Define "Purchase Order" sequence for using date ranges checking "Use subsequences per date_range".
Define the reset order number as 1 for each day
Create a purchase order with order date in 2020 (a different day than current one).
Will cause today's order number to duplicate
Current behavior:
Got a purchase order with 2020 (current daily) number.
Expected behavior:
The order number will not be repeated
Video/Screenshot link (optional):

**Comment by nhomar** [comment]
Hello.

As far as I can see, you edited a technical feature that must be managed properly on the technical side.

What you did is expected to have such behavior, if you edit a sequence with the things you mentioned (If I understood properly) that's the expected result.

Sequence feature is not intended to control duplicated, it works straight forward reading what you set on the settings.

I think this issue is invalid, if you thing what I say is not correct feel free to reopen it.
