### ISSUE TITLE
Creating an Issue or Task generates duplicate tracking notifications

### ISSUE THREAD

**Issue by dreispt** [odoo/odoo#5023]
When creating a Task or Issue, some notifications are triggered that should happen only on "on change", such as "Task Assigned".

This can be reproduced on Runbot both for 8.0 and master:
- With the admin user, edit the configuration for the The Jackson Group's Project
- In the project followers widget , check all boxes on "Edit Subscription of Demo User"
- Now create a new Issue or Task for that project
- Duplicate notifications are sent: "Created" and "Assigned"

**Comment by dreispt** [comment]
@tde-banana-odoo I would love to hear your opinion on my proposed solution.

**Comment by tde-banana-odoo** [comment]
Indeed currently several subtypes may be triggered by a single tracking mechanism. It is not linked to the subscriptions of the followers. It is due to the fact that when checking changed values, the tracking satisfies more than one condition linked to subtypes, therefore triggering several subtypes.

As a message (mail.message) is linked to only one subtype (mail.message.subtype) through a many2one relationship, this implies that several messages are produced, one for each subtype.

We could link a message to several subtypes, but this would have an heavy impact on performances (numerous searches and filters on message by subtype, having a m2m relationship is costly). So for v9, we will reduce a bit the number of different subtypes, and make them ordered. It means that the first triggered subtype will be the only one producing a message. For example if you create a task and with a responsible, the subtype will be "Task Assigned"; task created will not be triggered.

The tracking itself will be modified; instead of storing a message with the modified values, the values will be stored and the message dynamically composed based on those values. This will make tracking available for searching, reporting, analyzing, ...

**Comment by dreispt** [comment]
@tde-banana-odoo Good to know this will be revisited for v9.
Meanwhile, for v8 I managed to find a low footprint solution that works around the issue.
Do you see anything you dislike about it?

**Comment by Yenthe666** [comment]
@tde-banana-odoo and @dreispt any update on this one?

**Comment by tde-banana-odoo** [comment]
The behavior has been improved in v9. We did it as explained in my message of 2015. We won't change the behavior in 8, because it is not considered as a bug; the behavior is that several messages can be produced, one for each trigerred subtypes. So for me, nothing to do here.

**Comment by Yenthe666** [comment]
I guess this can be closed then. @dreispt are you fine with this?

**Comment by dreispt** [comment]
The point here is not to consolidate several notification into a single one, that's an enhancement.

The point is that an "on change" event shouldn't be triggered on a record creation.
The "onchange" tracked fields are really triggered "always".
That's what the proposed fix tried to do.

**Comment by Yenthe666** [comment]
Hi @dreispt ,

Thank you for your bug report.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
As tde-banana-odoo mentioned it has been improved in 9.0 and up so it shouldn't be a real issue anymore.

Regards,
Yenthe
