### ISSUE TITLE
Dependency missing in latest rpm  odoo-8.0_20150203-1.noarch

### ISSUE THREAD

**Issue by a-atalla** [odoo/odoo#5037]
i have downloaded this rpm and install on Fedora-21 , when i wanted to start the server i get the erro that it can't import  unittest2  , i  solved this by manually installing python-unittest2 and it works 

please add python-unittest2 to the rpm dependencies 

thanks and best regards

**Comment by aab-odoo** [comment]
Hello,

python-unittest2 is already in the RPM dependencies. Actually, everything works fine on centos, and even on Fedora-20, with this package. The problem seems to be linked to Fedora-21. We will keep looking at this and come back to you when it is solved.

Thanks for reporting it anyway.
Regards.

**Comment by Yenthe666** [comment]
Hi @a-atalla ,

Thank you for your bug report.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
