### ISSUE TITLE
Proposal :: Delta Accounting

### ISSUE THREAD

**Issue by blaggacao** [odoo/odoo#5044]
# Proposal
- Author: David Arnold (DevCO)
- Date: 03.02.2015
- Target Domain: Accounting

## Context
We are living in a world, where we need to live with various consumers of accounting, such as internal, fiscal, headquarter, transitional accounting (eg IFRS adoption), etc. Each of them might have different requirements and definitions. Managing those can be headache and require a generic management tool.

## Triage
When it comes to the options to solve this, we have to meta approaches:
- Double Accounting, that is, writing every transaction multiple times independently
- Delta Accounting, defining one base and apply patch-like changes on top of it.

## Choice Motivation
As Odoo beeing a management centric tool with second class consumers, I would argue this can be best reflected by a delta accounting design, where the internal accounting is the base upon which one or several patched accountings can be applied. This is why double acocunting based on multi chart/multi analytic accounts is not the solution that fit's best this generic use case.

## Proposal
I propose therefore the introduction of a generic (and optional) delta accounting concept. Every transaction must be able to write primary accounting entries, and **tagged** higher level shadow/delta entries. Tagging will allow to cluster entries towards multiple target consumer. Naming them as "shadow" entries underpins their shadowy status: as with normal accounting entries, they should follow the usual lifescycle of draft, posted, etc.. but they should do so on a meta level, which indicates to the genral programm logic that they should be automatically precluded from **any** operation unless explicitly specified (similar to inactive state). Precluding them from any operations will hlep minimize the performance impact. It should be implemented as an overlay: if you don't need t, don't install it.
The missing peace in this line of thought no is, *how* delta entries' patch design is envisioned by this proposal. If delta accounting towards a targed consumer (by tag) is invoked, a checkbox should toggle between *manual delta entries* which just alter the base state as is or *manual replay entries*, which then automatically creates tagged zeroing entires in the shadow jurnal, so that the manual entries are applied on a state identical to the inital state of the base accounting.

**This is envisioned as an add-on layer wich is optional and design for perfect coexistence to the base installation. Not everyone might need this complexity.**

## Conclusion
This simple logic allows a super powerful multiple target consumer accounting, like it is in lot's of cases implied by law. (eg. IFRS transitory phase). This also proposes a solid framework to build dockument specific logic on top of it. Like for example: Mark Invoice Non-Deductible (== reverting base entries by eliminating deltas and replay base entries onto a designated account all on the "fiscal" target consumer tag)

## Discussion
I would encurage everyone to engage on a conceptual discussion about this prolem to solve (in a generic way). I think github is a good space to marry use case conceptualization and developing efforts in an efficient way, so I hope mailing-listers, as well as, hackers might participate.
especially, I'd like to ping @qdp-odoo and ask him to open up or preclose the discussion to get inline with official roadmap or filosofy. Thanks.

**Comment by qdp-odoo** [comment]
Hi,

this is by far out of the scope of our roadmap for v9. It deals with concepts that i don't yet understand clearly and adds a new layer of complexity whereas we aimed to simplify the accounting for the next version :-) So, i won't discuss that much on this point but i encourage you to go on with other people from the community if they're interested.

That being said, if i understood correctly you plan to have that as an extra feature on top of the existing, with both 'accounting' that could possibly exist together without any side effect... Well i'd say this is the first and most important point you should deal with because that will be the condition sine qua non to be, one day, integrated as an official core module.

best regards,
Quentin

**Comment by nhomar** [comment]
IMHO, totally out of scope.
And mention parellel accounting just because a possible bad design since the begining without the correct approach from an accountant, and with the correct legal validation is too dangerous.

Today we have bugs opened 3 years ago because a date is not correctly setted in some place, then imagen have 2 accounting which are not availables to be linked, audited because they are with different purposes.

I don't know if somebody else in the community is agreed, but I prefer 1 very well tested, and with all the tools to desing it correctly since the begining that 2 half done.

May be for v11 buyt until today even with huge implementations is first time I hear "parallel accounting" in a freely way that does not include something illegal in the middle.

my 2 cents.

**Comment by gdgellatly** [comment]
Did you just write a very confusing definition of Multi-Analytic/Mutli
chart accounting?  I can't really see anything in the logic those 2
concepts don't address already.

**Comment by jbeficent** [comment]
@blaggacao, you're proposing new accounting concepts. If you are passionate about them, please develop them further, and support them with existing accounting literature (books, publications,...) or some reference where such concepts have already been put in place. Otherwise I encourage you to write a paper and submit it to an accounting magazine. 

New ideas are great and much needed, but in order to achieve acceptance by the wider community you need to develop them in detail, and then get to know the proper channels of communication in order for them to sink in the community.

**Comment by blaggacao** [comment]
I try to answer all pints quickly:

@qdp-odoo I updated the proposal section at it's end to make clear coexistence. I already head pretty much doubted it would fit v9 roadmap :)

@nhomar I understand your concerns, however it is very common indeed, that you have a difference between internal acocunting and fiscal accounting for example, or that your migrating to a new standard but need to comply with the old for some time as well. (there is actually a hard legal fundament for this proposal) In any case, as long as you adhere to the oficial standards in your official accounting, ther is no legal issue. But management might want to have a differnet view. I don't see, that if this envisioned as a lightwight delta layer how this could be divering in quality from the underlying layer.

@gdgellatly I thoaught about that too, but I think, as stated in the choice motivation part, that a delta approach would be better fit the managmeent's point of view: "we adapt our truth to fit the requirements of somebody else truth", so looking at the delta layer you get exactly thos differences pointed out. Clarifying it in the choice motivation section.

@jbeficent I very much appreciate your comment, especialy about the right channel. I might indeed want to look up some litterature, which reflects this organisational reality in a comprehensive way. I don't think you're right, assuming that it's new concepts. If you don't mind an edge case documented in a spanish decree, this might already help you, although beeing a very weak support in the domain of this discussion: Articulo 3 : http://www.dian.gov.co/descargas/normatividad/2014/Decretos/Decreto_2548_del_12_de_diciembre_2014.pdf Again: I consider this a weak reference.

**Comment by jbeficent** [comment]
@blaggacao I reviewed your link. Looks to me that systems such as SAP (New GL) or Compiere (http://www.compiere.com/products/global-ready/multi-accounting.php) use parallel ledgers to support differences in accounting standards across countries. This approach seems to be widely adopted.

What intrigues me in Odoo is that the interface between the transactional events and the recording of the recognition of that transaction in the accounting journal is hardcoded.

For example, the anglo-saxon accounting module.

You should be able to configure the derivation of a transactional event to a an accounting journal under each accounting standard / method.

SAP hardcodes all transactional events under certain posting keys. And then you are free to decide how to determine, for an accounting standard, which transactional events are relevant for your Accounting Standard, and what is the rule to derive the GL accounts.

**Comment by blaggacao** [comment]
> You should be able to configure the derivation of a transactional event to a an accounting journal under each accounting standard / method.

@jbeficent I think, I didn't fully understand. can you elaborate? Is it a rephrasing of the proposal as opposed to..

>SAP hardcodes all transactional events under certain posting keys. And then you are free to decide how to determine, for an accounting standard, which transactional events are relevant for your Accounting Standard, and what is the rule to derive the GL accounts.

which I understand as a middle-layer approach (postin gey layer) and would thus be the double accounting model. As it becomes clear, this model would allow for transactions which are not relevant in the base case, but relevant in a different case to be recorded (which is not trivial in the delta model, note that the exact reverse case indeed is trivial).

Still I argue that a delta model caters for better consistency and is more transparent to the user. We should probably cater edge cases by the ability to directly record to target layers / target tags / target standard / target method (roughly used as synonyms) as a well custodied expcpetion case.

**Comment by blaggacao** [comment]
by now, we solved it by multi-charting and the use of consolidating accounts, this is convenient and actually represents standard accounting concepts. It's clearly not new at all, maybe you got it wrong:

We have A) Managment Accounting, B) Fiscal Accounting and probably C) Reporting to Headquarter and probably D) Transitory Accounting. Nothing special about it, just quite normal stuff.
