### ISSUE TITLE
[account_bank_statement] wrong move counterpart in reconciliation widget

### ISSUE THREAD

**Issue by JulioSerna** [odoo/odoo#5129]
Impacted versions:
* 8.0

Steps to reproduce:
First to create one refund debit/credit with **amount = 10 €**
![odoo](https://cloud.githubusercontent.com/assets/7595505/6084424/93907ff4-adf6-11e4-9dd8-32455e2efe0c.png)

after create one invoice with **amount = 40 €**
![odoo_invoice](https://cloud.githubusercontent.com/assets/7595505/6084465/e52a10dc-adf6-11e4-8624-fb3e2077a5ec.png)

to make manual reconciliation partial
![journal items to reconcile odoo](https://cloud.githubusercontent.com/assets/7595505/6084510/25c790d8-adf7-11e4-9dda-e7270f23f698.png)

after in one bank statement payment the residual of invoice by **30€**
![bank statements odoo](https://cloud.githubusercontent.com/assets/7595505/6084713/f92aaa86-adf8-11e4-8817-122bd3008eed.png)

current behavior
When the refund debit/credit is made first that invoice in the bank statement reconciliation widget show refund to reconciliation
![reconciliation on bank statements odoo](https://cloud.githubusercontent.com/assets/7595505/6084695/d7d538ec-adf8-11e4-9f78-f1531bfc6e98.png)

expected behavior
The move in widget  should be the of invoice

**Comment by Whisno** [comment]
Currently, a partial reconciliation is just a link between several move lines. So In your case, there's a refund of 10€ and an invoice of 40€ that share the same partial_reconcile_id. I agree it really should be considered as a 10€ refund that is reconciled and an invoice whith 30€ left unreconciled, so it's just the invoice that should be selected for bank reconciliation.

Unfortunately, in V8, the residual amount of a partial reconciliation is just 'shared' between the move lines which where partially reconciled together. In this situation, we can just see that there is an invoice with credit=40, residual_amount=30, reconcile_partial_id=42 and a refund with debit=10, residual_amount=30, reconcile_partial_id=42.

So to handle this, when we get move lines for a reconciliation, we first fetch the move lines that are relevant, which include both your refund and your invoice, then keep only one for each partial reconciliation, since it only makes sense to show the result of the partial reconciliation. As long as the significant journal item is the first to be created (hear: create the invoice before the refund), it works.

This partial reconciliation logic is fixed in the upcoming V9. As far as V8 is concerned, well, I agree this is a bug, but it's a bug that is quite unlikely to happen and whose consequences aren't extremely severe. So we are probably not going to fix it because we feel it's more important to focus on delivering a great V9 accounting than patching up its flaws in V8 (which is extremely time-consuming)

**Comment by nhomar** [comment]
Hello @Whisno 

The solution ios fairly simple. If you create the line to show in bank recociliation interface more explicit it will help a lñot.

We know about the issue of the conceptual meaning of recociliation.

But the algorithm today is taking "First Found" and showing it in lines, which I think is incorrect.

Normally we pay Invoices with credit notes, then the solution should be:

The credit note must be forced to not be shown and always show invoices (payables and receivables) if the amount is less than the invoice and the invoice is not paid, contrary, show the credit note, because you must return money to the customer, it is a change that does not impact at all the actual logic, but can improve a lot the usability.

I refuse make patches on Bank Statement, due to those patches will be losed with new stuff ans logic in v9.0 (I think you think the same).

This is way you comprehension and helpful explanation is right, and exactly what we saw already, but a solution must be given.

When you built and incomplete/buggy beautiful interface which automate several things, this kind of details must be fixed, because if not the process become more dangerous than helpful.

Let's wait for Odoo's PoV.

Regards.

**Comment by Whisno** [comment]
Maybe something like
```
foreach line in partial reconciliation:
    if abs(line.debit - line.credit) < abs(line.amount_residual)
        ditch line
```
could do the trick.
I'll try this in the course of the week.
