### ISSUE TITLE
It should be possible to call onchange without creating a "update chain"

### ISSUE THREAD

**Issue by agenterp** [odoo/odoo#5133]
I have 3 fields a b c.
all have onchnage handler.

a updates b and c
b updates a and c
c updates a and b

at the moment odoo calls the first, checks if a field is affected with an onchnage handler.
if yes, the onchnage is called for the same.

**Comment by odony** [comment]
Hi,
Maybe your problem is that your onchange results are not consistent... You need to write them in a way that ensures they reach a fixed point after getting all called. Once the value for the results stop changing the chain stops. If the computed values change every time, which one of these results is the correct one?

If that's your problem, you can close your issue and fix your onchange code :-)

If you think your onchange logic is correct and always gives the same result, then please explain with a real use case or give a real code example so we understand better your issue.

Thanks,

**Comment by Yenthe666** [comment]
Hi @agenterp,

Thank you for your bug report.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
