### ISSUE TITLE
[13.0] website/e-commerce cart not adding products on IOS 13.4.1

### ISSUE THREAD

**Issue by edwardmac** [odoo/odoo#51338]
Impacted versions: 
odoo 13
IOS 13.4.1

Steps to reproduce: 
on website/ecommerce site, add products

Current behavior:
after adding products odoo redirects to an empty cart page.
tested on safari and google chrome(81.0.4044.124). both browsers have the issue.

Expected behavior:
after adding product should redirect to a cart with product selected.

if on windows 10(1909) browsers and android device(8.1.0) works as intended.

**Comment by pedrobaeza** [comment]
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - click on the blue door icon of the version row - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by edwardmac** [comment]
it was a nginx configuration issue.
