### ISSUE TITLE
Wrong tax evaluation after import invoice/purchase bill

### ISSUE THREAD

**Issue by jprokop1** [odoo/odoo#51364]
Impacted versions: 12.0 Community

Steps to reproduce: Import invoice or purchase bill from xls

Current behavior: tax evaluated only for first position on invoice/bill (Invoice.jpg, VendorBill.jpg)
after insert+delete new position is tax correct (Invoice_1.jpg, VendorBill_1.jpg)

Expected behavior: correct tax evaluation

Video/Screenshot link (optional):
![Invoice](https://user-images.githubusercontent.com/46556236/82141572-1f103300-9837-11ea-8644-eff9d7f93a86.jpg)
![Invoice_1](https://user-images.githubusercontent.com/46556236/82141584-29323180-9837-11ea-8a1d-13bc158d564a.jpg)
![VendorBill](https://user-images.githubusercontent.com/46556236/82141587-2fc0a900-9837-11ea-8963-5fd3c6314f23.jpg)
![VendorBill_1](https://user-images.githubusercontent.com/46556236/82141593-364f2080-9837-11ea-8525-64895886e187.jpg)

**Comment by pedrobaeza** [comment]
Unless you provide the source XLS (with the minimum data to reproduce the problem), this can't be investigated.

**Comment by jprokop1** [comment]
I hope with the examples is possible to reproduce the problem

[Products.xlsx](https://github.com/odoo/odoo/files/4640135/Products.xlsx)
[Bills.xlsx](https://github.com/odoo/odoo/files/4640140/Bills.xlsx)
[Invoice.xlsx](https://github.com/odoo/odoo/files/4640141/Invoice.xlsx)

**Comment by pedrobaeza** [comment]
@xmo-odoo @qdp-odoo is it expected that a user must be able to import whole invoices with consistency?

**Comment by qdp-odoo** [comment]
Well... There is an import wizard for bills but it was never meant to be used with xls files (XML or OCR). I don't know why we never thought about the regular csv/xls files. So I suppose we must speak about a missing feature rather than a proper bug.

Anyway, I'm not able to get the provided files imported at all, so I can't test it properly to see if it's easily doable. But we'll gonna check that and make sure in master that this use case is fully supported.

**Comment by qdp-odoo** [comment]
ping @bfr-o
