### ISSUE TITLE
gevent is used even when workers are not used

### ISSUE THREAD

**Issue by clonedagain** [odoo/odoo#5173]
From @antonylesuisse's comment at https://github.com/odoo/odoo/pull/5043#issuecomment-73441515 I gather that gevent should not be used when workers are unused.

But from reading the code I can see workers are only tested after openerp.evented in start() in server.py : https://github.com/odoo/odoo/blob/8.0/openerp/service/server.py#L931
So if gevent is available it gets used no matter what.

**Comment by antonylesuisse** [comment]
The check is here https://github.com/odoo/odoo/blob/8.0/openerp/__init__.py#L30

If you run openerp-server or odoo.py gevent is not imported thus it is disabled.

If you run oepnerp-gevent gevent is imported thus enabled https://github.com/odoo/odoo/blob/8.0/openerp-gevent#L3

Your debugger probably import gevent sneakily you should disable that behaviour.

If you cannot I would accept a patch that check for a better condition in __init__.py like is_it_gevent_monkey_patched() ? The condition would be true if "gevent.monkey.patch_all()" has been executed instead of just the gevent import.
