### ISSUE TITLE
[13.0] sale/purchase: Add 'Not Available' for unavailable combination on sale/purchase report

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#51735]
Impacted versions: 13.0

Steps to reproduce: Add Product Grid on Sales order Line which includes one Unavailable Variant
![screenshot-2772141-13-0-be4d0d runbot29 odoo com-2020 05 23-22_35_17](https://user-images.githubusercontent.com/16624719/82736234-b567bb80-9d45-11ea-87e0-1dd2e9db7162.png)

Current behavior: Product qty is 0 instead of 'Not Available' 
![screenshot--2020 05 23-22_36_37](https://user-images.githubusercontent.com/16624719/82736253-e5af5a00-9d45-11ea-976a-7bf71bd07b4f.png)

Expected behavior: Display 'Not Available' on the 0 on the Report.

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
@Feyensv @dbo-odoo what do you think about this?

**Comment by dbo-odoo** [comment]
Not really a bug, and I don't want to add translation values in a stable version and I don't even think it's trivial since the ORM will return unset float values as 0; sent to backlog internally but i'll close this issue as it's not a _bug_ but rather an improvement.

This is not _wrong_ (if the product is unavailable, then yes the ordered qty is obvsly 0), it's just _annoying_...

**Comment by sswapnesh** [comment]
> it's just annoying...

`0` != `Not Available`

Hope to fix it in upcoming version :+1:
