### ISSUE TITLE
Error "There is no vendor associated to the product Product" when selling kit type BOM which includes only components that do not have reordering rules set

### ISSUE THREAD

**Issue by E4O** [odoo/odoo#51861]
Impacted versions:
v12

Steps to reproduce:
1. Create two products
1.1 Product (Can be purchased, Storable product, Buy selected from routes)
1.2 Test BOM (Can be sold, Storable product, Manufacture and Make to order selected from routes)

2. Create bill of material for BOM product (Bom type = Kit).
2.1 Add one component "Product".
![image](https://user-images.githubusercontent.com/40301417/82881382-4c9c6100-9f48-11ea-94fe-e89f1eeb5601.png)

3. Sell "Test BOM" product to a customer. Confirm quotation.

Current behavior:
I will get an error message "There is no vendor associated to the product Product. Please define a vendor for this product."
![image](https://user-images.githubusercontent.com/40301417/82881506-75bcf180-9f48-11ea-9742-705c2e373977.png)

Expected behavior:
I should be able to confirm this quotation without any error messages because I do not have any automatic reordering rules described on my "Product". I will buy it manually. When BOM type is Kit and product has "make to order" rule checked, then Odoo runs "make to order" rule on components also.

**Comment by pedrobaeza** [comment]
You are mixing some concepts, and this error is the result of it: if a product has a kit BoM, then you mustn't put it with "Make To Order" + "Manufacture". On sales order confirmation, a product without that routes creates the line for the component. With that configuration, "Make To Order" is propagated to components, having the error.

Closing as expected behavior.
