### ISSUE TITLE
[12.0] auth_signup: Users without group_erp_manager can't create contacts

### ISSUE THREAD

**Issue by gustavovalverde** [odoo/odoo#52088]
### Impacted versions:
12.0

### Steps to reproduce:
- Install `auth_signup` in a multi-company environment.
- Try to create a contact with a normal user (no access to settings)

### Current behavior:
- **Write** access error on field `signup_token`

### Expected behavior:
- Allows to create the user

**Ticket 2258118**

**Comment by gustavovalverde** [comment]
cc: @mart-e the enterprise ticket has credentials to test. You can do whatever you want there.

**Comment by pedrobaeza** [comment]
Module for autenthicating in FB/Google is `auth_oauth`, not `auth_signup`.

**Comment by gustavovalverde** [comment]
Yes, I'm aware, but those depend on `auth_signup`. Anyways, just installing  `auth_signup` generates the error.

**Comment by pedrobaeza** [comment]
Then it's better to reduce the steps to reproduce to the minimal one for simplifying the hunting and solution.

**Comment by gustavovalverde** [comment]
Done

**Comment by mart-e** [comment]
Hi,

I have checked a bit your instance and branch and, [looking at the traceback](https://gist.github.com/mart-e/561ee4b4ab181b2234d61dc2f34d63c4) it seems the issue is from the `auditlog` module:

https://github.com/OCA/server-tools/blob/2e38043f27216851f983a3475187675df8341ce5/auditlog/models/rule.py#L226-L228

There, the code is iterating on all fields, including the ones the user may not have access to (as this is the case here).

**Comment by gustavovalverde** [comment]
Actually, just changing the auditlog `log_type` from full to fast, fixes the issue as the fast method does not iterate through all fields.

Thank you very much @mart-e for taking the time and analyzing it a bit further. Got a bit blind there :)

**Comment by mart-e** [comment]
No problem, but still the `log_type` full of `auditlog` is probably buggy and should skip the fields he does not have access to ;-)
Anyway, glad it was solved
