### ISSUE TITLE
Qweb Report Type Text  Issue

### ISSUE THREAD

**Issue by sarangshaikh** [odoo/odoo#52200]
7Impacted versions: 13.0

Steps to reproduce
1. Go to technical setting/reporting/reports.
2. Change Quotation/Saleorder's report type to Text.
3. Go to Sale order and print quotation/saleorder.

Current behavior: When clicking on print button, It returns HTML  on Text file.

Expected behavior: When we click on print button, It should return content in text format on Text file.

Video/Screenshot link (optional):

[Order - S00040.txt](https://github.com/odoo/odoo/files/4704928/Order.-.S00040.txt)

**Comment by Yenthe666** [comment]
I don't really think its built that way. It literally prints the text from the QWeb report in a text file now, right? @pedrobaeza probably knows.

**Comment by sarangshaikh** [comment]
You can try it on demo.odoo.com and also on runbot, It builts that way as i attached sample Text file of Quotation.

**Comment by pedrobaeza** [comment]
Yeah, but I'm afraid it has created false expectations on you. That option is doing what you get. Not sure if Odoo's original intention was to provide a different renderer if this option was chosen, but for now, it only does that.

That's why none of the core addons use this format.

Closing as no issue, but not feature at all.
