### ISSUE TITLE
"Activity types" action has inconsistent domain

### ISSUE THREAD

**Issue by Kowsto** [odoo/odoo#52367]
Impacted versions: v12

Steps to reproduce:
Install CRM, then install Sales (without sale_crm)
Current behavior:
The action window "sales_team.mail_activity_type_action_config_sales" has a domain:
 ['|', ('res_model_id', '=', False), ('res_model_id.model', 'in', ['crm.lead', 'res.partner'])]

When installing sales, that domain is replaced with:
['|', ('res_model_id', '=', False), ('res_model_id.model', 'in', ['sale.order', 'res.partner', 'product.template', 'product.product'])].

Therefore, activity types linked to the model 'crm.lead' are no longer visible. This is usually overriden by an update of "sale_crm", which contains the full domain. However, sale_crm is not necessarily installed (because unrequired).

Expected behavior:
Updating the app 'sale' or 'crm' should not completely overwrite the domain.
OR
Make sale_crm a mandatory module if both sale and crm are installed.

**Comment by pedrobaeza** [comment]
`sale_crm` is already auto-installed:

https://github.com/odoo/odoo/blob/05ee3a9ef3e2ff5e489e73061f8f7ee9db0963b8/addons/sale_crm/__manifest__.py#L26

so everything seems OK and it's the way it works. You just don't need to mangle with the standard installation procedures (removing for example addons).

Closing as no issue, but expected behavior.
