### ISSUE TITLE
[8.0] product: When duplicate product set default_code and ean13 to False

### ISSUE THREAD

**Issue by moylop260** [odoo/odoo#5237]
Steps:
http://youtu.be/4SmFZpNlzZo

I expected:
ean13 and default_code duplicated

I saw:
ean13 and default_code is empty

**Comment by Sameer1990** [comment]
For ean13 , there is a constraint to not duplicate for custom ean13 .

**Comment by moylop260** [comment]
@Sameer1990 
:+1: with ean13 unique constraint

But, What happen with default_code?

**Comment by Sameer1990** [comment]
When you duplicate product variants (product.product) will not set fields to empty , it will duplicate the ean13 and default_code .
But when you duplicate product (product.template) will be as you mention in your video .
It seems in template will not duplicate because the two fields are constraint .

Try it in http://47422-8-0-222b2d.runbot6.odoo.com/?db=47422-8-0-222b2d-all and figure that .

**Comment by moylop260** [comment]
The code don't have a constraint.
Do you have a line of code of this constraint?

**Comment by Yenthe666** [comment]
Hi @moylop260,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
