### ISSUE TITLE
[13] website_sale: Image of Archived variant is displayed on main page

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#52463]
Impacted versions: 13.0

Steps to reproduce: Archive one of the Variant which is used on Shop
![Screenshot from 2020-06-04 23-24-46](https://user-images.githubusercontent.com/16624719/83793730-990b3d80-a6ba-11ea-9768-70f0403b3b7b.png)

Current behavior: Still it is displayed as main image on `/shop
![12fb23090feb440a3fbd396a0a0f3dc9](https://user-images.githubusercontent.com/16624719/83794095-12a32b80-a6bb-11ea-803f-db6355bb2ef7.png)

(and adding Product on wishlist/compare is adding next available variant)`

Expected behavior: Archived product's image should not be displayed

Video/Screenshot link (optional):

**Comment by bso-odoo** [comment]
Note that test scenario is not correct:
- in the demo data, the product template has the shown image configured, but 3 of its variants have no image and thus default to the image of the template
- therefore, whichever variant is archived has no effect because the product template image always wins

Here is the suggested new behavior:
- if the product template has no image, then use the image from the first available variant

**Comment by rdeodoo** [comment]
Fixed with https://github.com/odoo/odoo/pull/61322
