### ISSUE TITLE
Return a picking break the pick-pack-ship process

### ISSUE THREAD

**Issue by jgrandguillaume** [odoo/odoo#5253]
Hi,

Returning a picking break the pick-pack-ship process by blocking the availability of the next operation. To reproduce on runbot v8.0:

1) Configure the warehouse "Your company" to pick-pack-ship operation (you'll need to  activate the advance route on WH config + set up the correct process through the warehouse configuration wizard.

2) Create a SO with a product (on stock) and confirm it

3) Display the deliveries, you'll have 3 : pick, pack, ship

4) Take the pick, force availability if needed, and confirm it

5) Return the pick and validate (e.g. imagine you missed something like puting the lot, so you want to reverse the pick).

6) Go back to the SO, click to view the deliveries

7) You now have another, new, pick here (which is correct). Take it and confirm it.

8) Look at the pack => his state is "Waiting another operation"... This is not good ! We should have it "Ready to transfer" because we just (re)confirm the pick operation.

My guess is that move_dest_id is not populated properly when returning a pick and creating the new one. So Odoo don't know he should make the next operation (pack) available.

Thanks for having a look at it.

Joël

P.S. Note that I opened an OPW for this one.

**Comment by jco-odoo** [comment]
Hi Joël, this is indeed like this.  I thought about this when implementing the returns and I did not see an easy and correct solution to link the two at the time.  Somehow the Pack which is "Waiting another Operation" needs to know indeed if it can be linked to this previous one.  The simple solution was to use the 'Force Availability'.  

We could do a logic that says: if the move was a return and this return was a return of one of the original moves of this move then you can add it to the original moves of that move that was waiting another operation.  (I am correct that you did a return of a return?)

I don't see it as a pure bug, but would like to find a solution together.  

The problem is when to link the returned move with this move.  I think we should do it simply when the return wizard finishes: if the returned move was a return and that return has a move_dest_id and this move_dest_id is not in done/cancel state (and has no split moves?), then link it to this move.  I wonder if there is no danger with chained returns (for example when returning a pack to stock or when partially delivering something already)

**Comment by jco-odoo** [comment]
@jgrandguillaume  The second PICK mentioned is actually the return (back to stock), so at that time it should still be Waiting Another Operation.  It is only when we make the return of this PICK that we could put it in Ready To Transfer.  (which is not the case right now)

**Comment by nhomar** [comment]
2015-02-12 10:51 GMT-06:00 Josse Colpaert <notifications@github.com>:

> Hi Joël, this is indeed like this. I thought about this when implementing
> the returns and I did not see an easy and correct solution to link the two
> at the time. Somehow the Pack which is "Waiting another Operation" needs to
> know indeed if it can be linked to this previous one. The simple solution
> was to use the 'Force Availability'.
>

The force availability button should not be used in any normal operation
process, IMHO it s too dangerous.


-- 
--------------------
Saludos Cordiales

  [image: --]
Nhomar Hernandez
[image: http://]about.me/nhomar
     <http://about.me/nhomar?promo=email_sig>

**Comment by jgrandguillaume** [comment]
Hi Joss,

Thanks to have a look cause we definitely need this fixed !

a) I agree with Nhomar, we can't use "force availability" in a normal process. People will start to do wrong things otherwise. 

b) I made a mistake in my previous bug description, no new pick is generated in fact...

My suggestion to fix this is that the "Reverse Transfer" wizard create 2 stock.picking : one for the return, one for the "new" delivery. As the "Reverse Transfer" wizard is called from the original picking, you have the move_dest_id, so you can store it in the new delivery.

The new process will then look like:

1) Configure the warehouse "Your company" to pick-pack-ship operation (you'll need to activate the advance route on WH config + set up the correct process through the warehouse configuration wizard.

2) Create a SO with a product (on stock) and confirm it

3) Display the deliveries, you'll have 3 : pick001, pack001, ship001

4) Take the pick001, force availability if needed, and confirm it

5) Return the pick001 using the "Reverse Transfer" wizard. Here you have:
   - pick001 "Transferred" (the original picking)
   - pick002 "Ready to transfer" (the return of the original picking)
   - **pick003 as the new pick operation to process. This new pick is created in the mean time that the reverse picking "pick002" and its stock.move has a move_dest_id equal to the original one**

6) Go back to the SO, click to view the deliveries

7) You can now confirm the "pick002" to return goods in stock

8) The "pick003", when processed, will make the pack001 available as move_dest_id has been set correctly. 

This should work for any operation (pick or pack or even ship), it is not difficult to implement and I think it even work for partial as various pick move can be linked to a single pack move line.

What do you think ?

Regards,

Joel

**Comment by jco-odoo** [comment]
- Force Availability should be avoided as much as possible, but not having
it at all, could block you in certain situations.  (e.g. if you don't do a
return of a return)
- I am not convinced that creating a return should create a return of the
return immediately as there is the case where you want to return and cancel
the sale order.

We can still do the linkage when we create the return of the return.  (as
we can check if the return we return its original move (the move we
returned from) had a move_dest_id)

**Comment by jco-odoo** [comment]
Please let me know if you still have any suggestions.

**Comment by nhomar** [comment]
@jco-odoo 

Force Availability will not be ever available for any user only super admins.

I insist, any normal process can depend of something that only in the "exceptions" will do thing correctly.

Can you list cases where you thing "Force Availability" most be there in order to not talk about Generic Things.

On our side we are agreed with the solution proposed by Joel.

Conceptual proposal.
Location A - B and C.

If you create a chained move from A > B > C

And you return from C > B the move from B > A should not need "Force Availability" at all and should be created automatically.

If I return from B > A and B > C is not approved yet it should be cancelled/unassigned automatically also.

All this logic should be done line by line not picking by picking in order to be consistent no matter where you are (barcode interface for example) and it is a normal process not an special one, then I should not need access to Force Availability button.

IOH. If you have assigned product from B > C and return from B > A then the return process should be preceded by an "Unassign" process which is a missing feature right now.

Now I don't find a way to one time a product is "Assigned" be "Unassigned" then the only way is make a "return" and the "re-start" the process, which becomes really painfull when you have delivery orders with hundreds of lines (I don't know if this leak of functionality can be considered as part of this issue of it is a leak of knowledge on my side).

Regards.

**Comment by jgrandguillaume** [comment]
Hi @jco-odoo @nhomar ,


May be when you return a pack, you have 2 buttons in the wizard and can chose:

 * Return pack only (to cancel the SO for example)
 * Return pack and create a new one (to proceed it another time)

IMO, the various cases are (based on locations : A ->PICK-> B -> PACK -> C -> SHIP -> D) :

1) You started to do PICK001 by mistake and want to reverse your operation (for example, you take the wrong one in the interface). In that case, you want to return PICK0001 AND re-create another PICK0002 to process later on

2) You did PICK0001 but you just get the info that the SO has to be canceled. Here you want to return PICK0001 in stock, no new pack, and then cancel the PACK00001 and the SHIP0001 to finally cancel the SO.

3) You did PICK0001 AND PACK0001 when you receive the info that you need to return this in stock to deliver it next week only. Here you: Return PACK0001 AND create a new PACK0002, then return PICK00001 AND create a new PICK00002. 
**WARNING:  Here, PICK0002 and PACK0002 must be linked together. So when I will process again this SO deliveries, marking the PICK0002 as done will make the PACK0002 available.**

Here is what we want.

What do you think about this solution @jco-odoo ?
Regards,

Joël

**Comment by nhomar** [comment]
2015-02-23 2:32 GMT-06:00 Joël Grand-Guillaume <notifications@github.com>:

> What do you think about this solution @jco-odoo
> <https://github.com/jco-odoo> ?
>
*jgrandguillaume <https://github.com/jgrandguillaume>*

I am agreed about the cases (alá credit note) it is good to point that
out....




-- 
--------------------
Saludos Cordiales

  [image: --]
Nhomar Hernandez
[image: http://]about.me/nhomar
     <http://about.me/nhomar?promo=email_sig>

**Comment by jco-odoo** [comment]
Makes sense to me.  I will do a simple patch in 8.0 without the option in the wizard (as it changes the model,....) as in the branch referred to and check with feedback who can do the change of the wizard in master.

**Comment by gurneyalex** [comment]
Additional notes:

* currently it is possible to reverse a transfer several times :open_mouth: 
* when a picking is waiting for another operation, the Cancel picking button is not available. It makes cancelling a Sale Order difficult when the chained moves have gone wrong.
