### ISSUE TITLE
Database restore error: 'transient'

### ISSUE THREAD

**Issue by rakibulinux** [odoo/odoo#52548]
Hello, Dear, Odoo Team,
I get a new error for restore DB from Odoo 8 to Odoo 13. Can you please tell me what is this and how it can be fixed. I try community and there is no post about this error and also your Odoo community not much active. This error is "Database restore error: 'transient'"

"https://www.behance.net/gallery/98403489/Database-restore-error-transient"

**Comment by Yenthe666** [comment]
@rakibulinux the Github issue tracker is only for bug reports about bugs in the official Odoo code.
Since you're talking about migrations this doesn't belong here. If you've used the official upgrade service from Odoo you can comment on the migration ticket. If you have migrated it yourself you can ask on the official help forums (help.odoo.com) or any other forum.

Regards,
Yenthe
