### ISSUE TITLE
Default value are not set when edit in tree

### ISSUE THREAD

**Issue by laetitia-gangloff** [odoo/odoo#5266]
Impacted versions:
- 7.0

Steps to reproduce:
1. On runbot, log in  as admin
2. Activate the developer mode
3. Go in Warehouse > Configuration > Reordering Rules
4. Click on create and check Warehouse and location are filled
5. Go back in list view
6. Edit tree view (debug view) to set the attribute "editable='top'" on the tree
7. Save and reload the view
8. Create a reordering rules

Current behavior:
- Warehouse and location are empty

Expected behavior:
- Warehouse and location fill with same information than in form

**Comment by Yenthe666** [comment]
Hi @laetitia-gangloff,

Thank you for your report.
As Odoo only supports the last three versions (at this point 8.0, 9.0 and 10.0) this report won't be handled anymore. I believe this is fixed in V8, V9 and V10 though.
If you still face this issue (but on a newer version) please don't hesitate to create a new bug report and we'll try to look at it as soon as possible.

Regards,
Yenthe
