### ISSUE TITLE
PoS: VAT from another fiscal position does not apply properly when product price is taxe included

### ISSUE THREAD

**Issue by groolot** [odoo/odoo#52945]
Impacted versions:
13

Steps to reproduce:
1. Create a product AAA with VAT 10% and price at 10€
1. Configure VAT 10% to be included in price
1. Configure VAT 5.5% to be included in price
1. Create a new fiscal position FFF that map VAT 10% to VAT 5.5%
1. Configure PoS to accept multiple fiscal position, FFF included
1. Enter PoS
1. Sell the product AAA at fiscal position FFF

Current behavior:
The AAA product is sold at 9.09€ with VAT 5.5% included

Expected behavior:
The AAA product sold at 10€ with VAT 5.5% included

Video/Screenshot link (optional):
https://youtu.be/gRPUcD6E6_0

**Comment by pedrobaeza** [comment]
Have you tried to remove and add again the product?

**Comment by groolot** [comment]
yes, I did it.

**Comment by groolot** [comment]
The workaround I did is:

1. Create a new taxe name "No Taxe" with a 0%
1. Assign this taxe to products I want to sell in PoS
1. Create two Fiscal Position, one with "No Taxe" to "10%" mapping, the other with a 5.5% mapping
1. Permit PoS to use the two fiscal positions

**Comment by gaikaz** [comment]
I was about to create a new issue but fortunately found this one.
This wrong behavior affects normal sales and invoicing and not only version 13.0, but 12.0 and 14.0 as well.

Video showing the problem in invoices of 13.0:
https://youtu.be/hKGhzB3Sr5Q
I show here how taxes (A and B configures how @groolot showed) work without fiscal position (the "FFF") mapping. The main takeaway is that because taxes are "tax-included", the total doesn't change from what unit cost is when selling a single unit.
As soon as we apply the fiscal position, that changes tax A to tax B, it changes the total.
From what I understand, the original tax A is then "computed out" of unit price, which becomes the "Untaxed amount" and then the new tax B is applied on the wrong untaxed amount. 

It's even worse on Sale Orders. I could make a similar video of that.

**Comment by Yenthe666** [comment]
@pimodoo

**Comment by pimodoo** [comment]
Hello, the goal of fiscal position is to change the taxes, not the prices. So we understand that you want to keep the same price with different taxes to perform this have to also apply a pricelist that'll change the price to the price you want to apply.

**Comment by gaikaz** [comment]
Hi, @pimodoo , thank you for the response.
> the goal of fiscal position is to change the taxes, not the prices.

This is exactly the point. For some reason, prices are affected by tax change when the change is initiated via fiscal position and not when taxes are changed manually as you can see in the previous video.

Also, I have to clarify that the video shows version 13.
Odoo 14.0 does have the issue but only on Sale Orders. It seems to work correctly on Invoices. 

Please watch this short (30s) video of how badly this works with Sale Orders on v14:
https://youtu.be/3TMeeFagCQk

Notice, how it works correctly until the fiscal position ("A -> B" for tax mapping) is set.
After that, **taxes start changing the unit price**, which AFAIK should never be touched by taxes (included or not).
The unit price here should be 100, but instead tax A (%10) gets deducted `100 - 10% = 90.91` and then the mapped tax B (5.5%) gets also subtracted from the result: `90.91 - 5.5% = 86.17` to get the "Untaxed amount".

**Comment by pimodoo** [comment]
@gaikaz We could discuss all day about which behavior is the correct one, because both are valid. I your case you don't want to change the price because it increase your margin on the product price. But if you had the normal  tax rate at 5%, and another one changed by the fiscal position at 20%. The behavior you expect would lead to loosing money if you only have a margin of 10% on your product.

By the way I'll check the behavior consistency between Invoicing, sales and point of sales.

**Comment by gaikaz** [comment]
@pimodoo I totally agree that in things like this there is no single truth.
Thought, I reckon that Odoo 14.0 invoices have it working in the most intuitive way.
That is - fiscal position tax mapping is simply an automation feature for tax changing on lines.
So the computation should be persistent in both scenarios:
1. Change tax A to tax B manually
2. Have a fiscal position change tax A to tax B automatically

**Comment by gaikaz** [comment]
@pimodoo Any news?
One of our clients has suffered from this because they have been selling with taxes being deducted twice.

**Comment by pimodoo** [comment]
@gaikaz it has been fixed in https://github.com/odoo/odoo/commit/f8737b4676ea86abc0f39e448849453f28d4b10f  it is now the same behavior than accounting, so it changes the price.

**Comment by gaikaz** [comment]
Thanks, but that seems to be a fix for just POS only.
How about the inconsistencies between Invoicing and Sales?

**Comment by pimodoo** [comment]
there left sales with wrong values, but invoicing and POS are now good
