### ISSUE TITLE
[8.0] Odoo freezes when entering Fiscal Position under quotations

### ISSUE THREAD

**Issue by Wishtech** [odoo/odoo#5301]
I am using the Odoo Version 8.0-a2115ef and it freezes after entering the Fiscal Position in Quotation.

![capture](https://cloud.githubusercontent.com/assets/11029413/6212393/d684164c-b60a-11e4-81d7-798e65bf4d96.JPG)

Even after discarding previous quoted items automatically appear

![capture3](https://cloud.githubusercontent.com/assets/11029413/6212398/e215eb20-b60a-11e4-9f66-ce4c792d68df.JPG)

**Comment by Yenthe666** [comment]
Hi @Wishtech,

Thank you for your report.
This bug has been fixed in the meanwhile and it now works fine:
![image](https://user-images.githubusercontent.com/6352350/28361437-108b58a6-6c79-11e7-9fc4-9f165b0683f9.png)
If you still face this issue please update your source code to the latest version.

Regards,
Yenthe
