### ISSUE TITLE
8.0 osv: Use osv.osv_memory and inherit with osv.osv is allowed from orm

### ISSUE THREAD

**Issue by moylop260** [odoo/odoo#5332]
If you have created a py code as next case:

wizard definition

``` python
class account_invoice_refund(osv.osv_memory):
    _name = "account.invoice.refund"
```

bad wizard inherit (different osv class)

``` python
class AccountInvoiceRefund(osv.osv):
    _inherit = 'account.invoice.refund'
```

I saw:
Inconsistent

I expected:
Error or warning from log of odoo

I know that is a developer error not a osv error.
But with a log warning many developers could be happier.

NOTE: We can help to make a new pr with this feature.
The question is: Your would consider approving the change of this feature?

**Comment by nhomar** [comment]
2015-02-17 18:51 GMT-06:00 moylop260 <notifications@github.com>:

> NOTE: We can help to make a new pr with this feature.
> The question is: Your would consider approving the change of this feature?
>

Just to compliment.

The behavior is really extrange due to the original view and behavior of
the wizard will staty some like equal but _only_ with admin user, with any
aother user all field will be shown as readonly.

IMHO it should show some warning, error mesaage or something that say the
programmer on CI time "Hey you overwrite incorrectly something that we can
not automate to work correctly."

Regards,.


-- 
--------------------
Saludos Cordiales

  [image: --]
Nhomar Hernandez
[image: http://]about.me/nhomar
     <http://about.me/nhomar?promo=email_sig>

**Comment by wfrisson** [comment]
when i browse any object created via osv.osv, i can get access to its its column, how can i get column labels (instead of column name)?

**Comment by Yenthe666** [comment]
Hi @moylop260,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
As Odoo 9 and newer have the new API it shouldn't be any problem anymore.

Regards,
Yenthe
