### ISSUE TITLE
Wrong criteria used to check if under a testing environment

### ISSUE THREAD

**Issue by luisg123v** [odoo/odoo#53362]
Impacted versions:
- Tested only in 12.0, but it could affect other versions

Steps to reproduce:
- Implement a unittest inheriting from `HttpCase`
- Use the method `url_open` to test a controller
- Perform any operation that vary depending whether test are running, e.g. [this one](https://github.com/Odoo/odoo/blob/517a13b967a07fe1e71b9c5308d185c4e45f1a2d/addons/crm/models/crm_lead.py#L1539) or [this other one](https://github.com/Odoo/odoo/blob/517a13b967a07fe1e71b9c5308d185c4e45f1a2d/addons/mail/models/mail_mail.py#L134)

Current behavior:
The operation is identified as if tests were not running. This is because the criteria is to check current thread, and when several threads are involved, only the first one is marked as testing

Expected behavior:
It should be identified that tests are running. This could be achieved by using the same criteria followed on [the report model](https://github.com/odoo/odoo/blob/790cde7cc466e62db03331ce00f310153d668077/odoo/addons/base/models/ir_actions_report.py#L659), i.e. checking if the config option `test_enable` is present.

**Comment by odony** [comment]
The `thread.testing` flag is specifically meant for the main thread that is loading the demo/test files during module installation. This is different and is needed also when the server is not loaded with `test_enable` (for demo files).

Anyhow `HttpCase` [puts the registry in test mode](https://github.com/odoo/odoo/blob/12.0/odoo/tests/common.py#L880), so that other threads share the same TestCursor (which never commits, BTW).

The fix for your decorator is to also check whether the registry is in test mode with `self.env.registry.in_test_mode()`. It's used similarly in other places.

**Comment by luisg123v** [comment]
Hi @odony,

Thanks a lot for the suggestion for fixing the decorator. However, I still consider that the reported issue is valid. In the posted examples, when the testing flag is not present, [changes are auto committed](https://github.com/Odoo/odoo/blob/517a13b967a07fe1e71b9c5308d185c4e45f1a2d/addons/crm/models/crm_lead.py#L1545). I'm aware that changes are not usually auto-committed during tests, but, if you manually call:
`self.env.cr.commit()`
they certainly will be committed.

Would you consider reopen this issue, please?

CC @moylop260
