### ISSUE TITLE
print RFQ(purchase module) in chinese

### ISSUE THREAD

**Issue by linzhihao0826** [odoo/odoo#53372]
Impacted versions: odoo13

Steps to reproduce: print purchase order

I‘been track this exception,but i have no idea how to fix it

The following is the output stack information
`Odoo Server Error
Traceback (most recent call last):
  File "e:\pycharmworkspace\odoo13\addons\web\controllers\main.py", line 2041, in report_download
    report_name = safe_eval(report.print_report_name, {'object': obj, 'time': time})
  File "E:\PyCharmWorkspace\odoo13\odoo\tools\safe_eval.py", line 349, in safe_eval
    c = test_expr(expr, _SAFE_OPCODES, mode=mode)
  File "E:\PyCharmWorkspace\odoo13\odoo\tools\safe_eval.py", line 208, in test_expr
    code_obj = compile(expr, "", mode)
  File "<string>", line 1
    请求引用- %s' % (对象.名称)
          ^
SyntaxError: invalid syntax`

**Comment by pedrobaeza** [comment]
That's because the translation on your system is incorrect. Try to load latest translation, and if still not working, then the translation should be incorrectly translated in Transifex. See https://github.com/odoo/odoo/wiki/Translations on how to contribute to translations.

Closing as this is an issue with translations, not with code, and should be handled at Transifex level.
