### ISSUE TITLE
Can not use international signs in Email Aliases

### ISSUE THREAD

**Issue by akselon** [odoo/odoo#53403]
Impacted versions:
13

Steps to reproduce:
1. Install Recruitment app,
2. Create a job position with email alias: testß@yourdomain.odoo.com
3. Try to add a new applicant to this job position.
4. If no error appeared yet, you can try to log a note.

Current behavior:
When Odoo tries to send an email to the applicant, it is computing the reply-to field:
https://github.com/odoo/odoo/blob/13.0/addons/mail/models/mail_thread.py#L2671
When email alias of job position contains international signs, it throws:
**UnicodeEncodeError: 'ascii' codec can't encode character '\xdf' in position 4: ordinal not in range(128)**

Expected behavior:
No error should be thrown. A mail should be sent. If Odoo allows creation of aliases with international signs, it should work properly with those.

Video/Screenshot link (optional):

**Comment by akselon** [comment]
I created an account on oddo.com. It does not support utf8 as well. When I send email from Gmail to Odoo, I get this email back:

Mail Delivery Subsystem <mailer-daemon@googlemail.com>
**Delivery Status Notification (Failure)**


_local-part of envelope RCPT address contains utf8 but remote server did not offer SMTPUTF8_
Final-Recipient: utf8-addr; testß@XXX.odoo.com
Action: failed
Status: 5.6.7
Remote-MTA: dns; eu47a.odoo.com. (35.241.232.92, the server for the domain XXX.odoo.com.)
Diagnostic-Code: smtp;  local-part of envelope RCPT address contains utf8 but remote server did not offer SMTPUTF8
Last-Attempt-Date: Mon, 22 Jun 2020 04:13:10 -0700 (PDT)

**Comment by pedrobaeza** [comment]
But the problem then is that mail servers doesn't support that characters, so basically you are restricted everywhere, so better to not use them. Anyway, the codification problem seems to be only on your side.

**Comment by akselon** [comment]
Thank you for your answer @pedrobaeza  I don't know if use of those signs is supported on mail servers or not, but maybe it would prevent some confusions if we do not allow creating email aliases with those signs? Because currently if an email alias is created with those signs, Odoo throws errors.

The problem is not only on my side. It is reproducible on fresh Odoo online trial instance as well as in the community version.

**Comment by Yenthe666** [comment]
Hmm, I know we have had some discussions about it before. If I'm not mistaking the general rule/idea was to avoid these kind of names as they're not really officially supported. @mart-e probably knows a bit more 😄

**Comment by Julien00859** [comment]
Hello @akselon, our official position on the subject is we don't want you register email addresses with anything else than ascii in the local-part (before the `@`) of addresses. To work such address need the `SMTPUTF8` extension to be enabled in the SMTP server, our SMTP server doesn't support it and there is quite a poor support out there on the internet. For the record, google mail prevent registering such addresses too.

We agree the error modal isn't user friendly, the user should get a pretty error modal "you cannot use anything else than unaccented latin characters in the email address" instead of an exception. About the online instance, you pointed an error our side, we granted SMTPUTF8 support for *outgoing* emails (odoo -> customer) and so removed the sanity check in the `formataddr` function. We need to reintroduce that sanity check for email aliases.

**Comment by pedrobaeza** [comment]
@Julien00859 what about adding a constraint at `mail.alias` level for avoiding to save alias with that characters?

**Comment by Julien00859** [comment]
> @Julien00859 what about adding a constraint at `mail.alias` level for avoiding to save alias with that characters?

That's exactly what we are going to do :)

**Comment by akselon** [comment]
I'm happy, that you made the fix @Julien00859 . Will this also be merged to the V13 branch?

**Comment by Julien00859** [comment]
Yes sure ! We first fix the oldest buggy version and then forward-port the fix up to master. There is a bot that does the most of the forward-port by itself.

**Comment by Yenthe666** [comment]
Let's close this one since it has been fixed in 12 already and the forward port is ongoing.
