### ISSUE TITLE
8.0 Wrong stock locations in Transfer pop-up

### ISSUE THREAD

**Issue by alexis-via** [odoo/odoo#5340]
Here is the scenario to reproduce the issue: I want to cancel a manufacturing order that has been validated ; for that, I want to create manually the "reverse" stock moves for the finished product (USB Headset) and the consumed products (USB Adapter):
1) Connect to runbot v8
2) Create a new picking. In this picking, create 2 stock moves:
* Product = USB Headset, source location = WH/Stock, destination location = Virtual/Production
* Product = USB Adapter, source location = Virtual/Production, destination = WH/Stock
3) Clic on "Mark as Todo"
4) Clic on "Transfer": in the transfer pop-up, you have 2 lines that have the same source location and the same destination location (taken from the first stock move)
When you Validate: in the first tab of the picking, you see the 2 stock moves with "good" source and destination locations ; but, in the second tab, you see the 2 operations with "wrong" source and destination locations (same source and destination on the 2 operations)

This issue was not present in openerp v7.

**Comment by jco-odoo** [comment]
@alexis-via In v8, pickings should be between two (parent) locations.  (this is for the application of putaway/removal strategies, giving certain freedoms to the warehouse operator, because it is logical not to send someone from whatever place(s) to whatever other place(s) in one assignment)

**Comment by alexis-via** [comment]
@jco-odoo So we should have a constraint or raise a warning when we click on transfer in this scenario ! We can't just silently fail in this case...

**Comment by intero-technologies** [comment]
I understand this way, when there is Recipt in 3 steps. So coming into warehouse, and then transfer to shelf or another final place. But what is with receipt in 1 step? Here it shouldn't ask for zones, because this isn't needed.

@jco-odoo could you clarify me, how i should book incoming products? Incoming goes to /WH/Stock but my destination is WH/Stock/F01-02. How i have to do it right?

Sorry for double posting, but when someone uses google, he will find it in both :)
