### ISSUE TITLE
[Idea][Core] @api.override

### ISSUE THREAD

**Issue by fmdl** [odoo/odoo#53450]
Hi @xmo-odoo , @rco-odoo 

Odoo is updated each year, and each year some method are renamed or removed.
If in V12 you have inherit a method in a custom module, in V13 this method is removed, when you start Odoo V13, Odoo don't check if the initial method existing.

Exemple
in Odoo module
```python
class Oder()
    _name = 'order'

    def some_stuff():
         pass
```

in custom module
```python
class Oder()
    _inherit = 'order'

    @api.override()
    def some_stuff():
         return super().some_stuff()
```

During the load of Odoo (or upgrade), by the decorator @api.override, Odoo check if the method exist in the Odoo module, if it not exist it raise or log a warning.

Note : @api.override() is an option.

Regards

**Comment by pedrobaeza** [comment]
Personally I think that you have this problem because you don't have enough test coverage for assuring that.

**Comment by xmo-odoo** [comment]
@fmdl so something like Java `@Override` annotation?

**Comment by fmdl** [comment]
> @fmdl so something like Java `@Override` annotation?

I don’t know java code. 
But yes something like that (with a check, to prevent dead code after migration).

**Comment by xmo-odoo** [comment]
That's exactly the what Java's Override does (though at compile-time obviously) yeah:
> While it is not required to use this annotation when overriding a method, it helps to prevent errors. If a method marked with `@Override` fails to correctly override a method in one of its superclasses, the compiler generates an error.

**Comment by fmdl** [comment]
@xmo-odoo could you keep me in touch if you implement that. Regards

**Comment by xmo-odoo** [comment]
@fmdl I've been thinking about it, and I think we could get most of the benefit (and more, in fact) at a relatively acceptable cost if we just check all model methods which use super(). This way the code can be checked as-is without the need to explicitely annotate anything: #53721

Pro: no need to touch the existing code, it all gets checked (and I have to verify them but it looks like we have a good dozen of these methods overriding nothing in standard)
Con: no check if you override a method to replace it, I would expect that to be pretty rare though, and it should be possible to add it to the existing checker: if the function is flagged as `@override` it'd look for an item of the same name in the parent before (or instead of) looking for a super().
