### ISSUE TITLE
datetime for currency conversins is displayed in UTC (and ot local time)

### ISSUE THREAD

**Issue by vrms** [odoo/odoo#5368]
we are on UTC+8 When I add a curreny exchange rate in >Accounting>Miscellaneous>Currencies the chosen datetime entry is shown in local time but aparently computed in UTC.

I don't regard that as very severe but misconversion of UTC to local time is an old bug which in other scenarios affects usability of odoo pretty seriousely (attendance for exampe)

**Comment by florca1979** [comment]
Odoo is having a very bad reputation in South America with this problem
it turns out that is not working timedate the conversion conrecta
I agree the continued use of UTC but I am sure that in this way the converter to the local time or the user can not fail
I have problems you entodas my records and reports for this reason

**Comment by Yenthe666** [comment]
Hi @vrms,

Thank you for your bug report.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
