### ISSUE TITLE
Add Georgian Language

### ISSUE THREAD

**Issue by Otar-Siradze** [odoo/odoo#5375]
Add Georgian language to the ALL_LANGUAGES dict, making it installable.
openerp/tools/misc.py

There is ./addons/web/static/lib/datejs/globalization/ka-GE.js and other required .po files in Odoo,

Georgian translation team is working not bad on the Launchpad.net (https://translations.launchpad.net/openobject-server/8.0/+translations, https://translations.launchpad.net/openerp-web/8.0/+lang/ka).

Odoo version 8.0.

I added to the ALL_LANGUAGES dictionary in the openerp/tools/misc.py file new entry:

        'ka_GE': u'Georgian / ქართული',

and everything works good:
- Loaded an Official Translation;
- Synchronized Translations;
- Created new translation files for my apps.

So, Please add   
        'ka_GE': u'Georgian / ქართული',

to the ALL_LANGUAGES dictionary in the openerp/tools/misc.py file.

**Comment by mart-e** [comment]
Fixed in 7.0 at 0eeab361d9c14081a5f4d32cfc0a2a67fc0eeead (will soon be ported in 8.0).

By the way the we have moved our [translation](https://github.com/odoo/odoo/wiki/Translations) system to Transifex. So feel free to join Georgian team on [transifex project](https://www.transifex.com/projects/p/odoo-8/) and help making it better.
Once you have join, feel free to ping me so I can name you coordinator of the team (which is one of the orphan language, [see mailing list](https://www.odoo.com/groups/community-translators-63/community-translators-13027054))
