### ISSUE TITLE
[13.0] Contact Form always shows an error has occurred - /website_form/crm.lead returns 504

### ISSUE THREAD

**Issue by jtmorris245** [odoo/odoo#54071]
Impacted versions: Odoo 13.0-20200417

Steps to reproduce: Setup Contact Form with CRM, Activate Leads, Assign Form to sales team and person.

Current behavior:
After submitting a contact form, the Post to /website_form/crm.lead always returns a 504, despite the server-side logs showing it completed in only a second or so. this means the form will hang for around a minuite and a half, then show a message that an error has occoured.
The form submission *is* correctly shown in leads however.

Expected behavior:
Correct operation of the form showing a success message.

Video/Screenshot link (optional):
Screenshot links: https://imgur.com/a/LcTvVVZ

I'm afraid I lack the knowledge of how to go about diagnosing this further, but would happily carry out any instructions that may help.

Thanks.

**Comment by pedrobaeza** [comment]
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - click on the blue door icon of the version row - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by jtmorris245** [comment]
I haven't yet identified how to reproduce the issue in runbot, however I have no custom/community modules, and I've just tried updating to the latest version available on the odoo:13.0 docker tag (13-20200629), with no change.
I'm unaware of any configuration changes that could have caused this, there's nothing special set up, and everything else is working fine. The only reason I found the issue was a customer called me as they thought the form was broken.

If you have any advice for logs files to look through or otherwise where to look to pin the issue down that would be brilliant.
Thanks.

**Comment by pedrobaeza** [comment]
There should be an error in the Odoo server logs. Please check it, but you should know how to do it, as it depends on the way you have deployed your server.

**Comment by MjAbuz** [comment]
I guess you have installed reCaptha and its not configured properly.

**Comment by jtmorris245** [comment]
Closing Issue:
Found that SSL Termination proxy was not passing correct scheme headers, once corrected this issue stopped.
