### ISSUE TITLE
Consumable products should not follow real time valuation

### ISSUE THREAD

**Issue by jbeficent** [odoo/odoo#5479]
Hello, according tot he following post:
https://www.odoo.com/forum/how-to/warehouse-management-6/whats-the-difference-between-quants-lots-and-products-55243

, consumable products do not follow inventory valuation. I can understand that, because for those products, such as office supplies, you are not really interested to maintain a valuated inventory, but probably you want to use them as a stockable item in your warehouse (because it's a physical item). 

You then should recognize the expense in the supplier invoice for the value of the products ordered, and from then on those products should remain un-valuated in your inventory.

However I can see that in Odoo 8.0 you can create a consumable product with real time inventory valuation. The system then keeps posting accounting entries when the product is received into inventory, or when it's issued.

Unexperienced users tend to make mistakes, and can create inconsistent consumable products with real-time inventory valuation set. In my opinion the application should prevent this from happening.

**Comment by jco-odoo** [comment]
And/Or it should not create real-time entries for consumables anyways.

**Comment by jbeficent** [comment]
Yes, and it is now happening!

**Comment by vcloud9ray** [comment]
Was this resolved?

**Comment by vcloud9ray** [comment]
Related: "[IMP] Stock valuation: Avoid consumables with real-time valuation" at https://git.vauxoo.com/vauxoo-dev/odoo/commit/cf6d7479d57f9483809779dd363b7f201bd3368c

Some users are OK creating a separate Category for Consumables, others think this will lead to data entry errors because product creators won't always know the correct category and they don't think users should have to choose CONSUMABLE product TYPE and CONSUMABLE product CATEGORY.

**Comment by jco-odoo** [comment]
I quickly checked the code in v10 and v11 and it skips consumables for accounting entries.

**Comment by vcloud9ray** [comment]
A filter like:

`<filter name="stockable" string="Stockable" domain="[('product_id.type','!=','consu')]"/>`

can be used to exclude the records that are inaccurately inflating the value in stock (or worse, if the quantity goes negative because non a are re-ordered, then deflating the value).

I think they should never appear (consumable quants) in the first place.

**Comment by jco-odoo** [comment]
We could put this filter by default like the Internal locations.  (to be added in the act_window) @nim-odoo

**Comment by vcloud9ray** [comment]
Awesome - thanks for considering!!

**Comment by nim-odoo** [comment]
@vcloud9ray @jco-odoo you mean something like this: #20456 
Is there a reason why you'd prefer do `('product_id.type','!=','consu')` instead of `('product_id.type', '=', 'product')`?

**Comment by jco-odoo** [comment]
@nim-odoo Probably just because the existing filter is like this.  We should not show services either, but we don't have quants of services.

**Comment by vcloud9ray** [comment]
@nim-odoo - No reason other than knowing services don't generate quants.  Appreciate the rapid response on this one!
