### ISSUE TITLE
Warnig when template is deleted starting from the form shown clicking on name link of one of its variants

### ISSUE THREAD

**Issue by tafaRU** [odoo/odoo#5483]
**Warnig when template is deleted starting from the form shown clicking on name link of one of its variants**

Impacted versions:
- 8.0

Steps to reproduce:
1. create a new product (product.template)
2. starting from this template, create a new variant (product.product)
3. click on the variant product name as shortcut to quickly get its template
4. in the form that is shown, delete the template using the menu More  

Current behavior:
- The following warnig is raised: **_MissingError One of the documents you are trying to access has been deleted, please try again after refreshing.**_
  - template and variants are properly deleted

Expected behavior:
- Delete template and its variants without raise a warnig.

**Comment by beledouxdenis** [comment]
Hello Alex, 

I do not believe we will fix this. This is a corner case and this is not a blocking issue.

The problem comes from the fact that, when you delete a record, you are redirected back in the last view you were (you have the history in the breadcrumb). The thing is, in this specific case, the previous record also has been deleted, and is therefore no more available. 

What should we do ? Redirect again in the previous view ? On which criteria ? Because there is a warning ? That can't be right. Some warnings may be useful for usability.  What happens if there is no other view the breadcrumb ?

Regards,

**Comment by Yenthe666** [comment]
Hi @tafaRU,

Thank you for your bug report.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
