### ISSUE TITLE
Download Backup bug Uncaught SyntaxError: Unexpected token T

### ISSUE THREAD

**Issue by salixan** [odoo/odoo#5504]
Once you want to download the backup this error will be shown:
Uncaught SyntaxError: Unexpected token T

and you cannot download the backup
it is same erorr for binary and zip backups also

thanks
Salix

**Comment by lukebranch** [comment]
I'm wondering whether this is related to this issue:

https://github.com/odoo/odoo/issues/5241

**Comment by xmo-odoo** [comment]
@lukebranch nah, #5241 is an issue in 8.0, this one seems to only happen in master (testing on runbot)

**Comment by salixan** [comment]
@lukebranch  yes the issue only happen in master, you cannot make backup at all

@xmo-odoo shall I update my installation the issue has been solved?

**Comment by lukebranch** [comment]
@xmo-odoo ,

Thanks for letting me know.

**Comment by salixan** [comment]
@lukebranch @xmo-odoo   ThankYou it works perfect now

**Comment by Marco14e** [comment]
I am getting the same error when trying to backup my database... I read the conversation, but couldn't figure out the solution. Could you please help me by describing what worked for you? Thank you!

![20150623](https://cloud.githubusercontent.com/assets/13016520/8305316/cce064d6-197b-11e5-9d60-8efc6239e846.jpg)

**Comment by lukebranch** [comment]
@Marco14e ,

I recommend taking a look at https://github.com/odoo/odoo/issues/5241 to see if it helps. My issue (although not directly related to the issue in this post) was caused by a mismatch between postgreSQL versions.

My original database was installed on an instance with PostgreSQL 9.3, and my new installation was in PostgreSQL 9.4.
