### ISSUE TITLE
Taxes are not set for all companies when a product is created

### ISSUE THREAD

**Issue by luisg123v** [odoo/odoo#55177]
Impacted versions:
- 12.0
- 13.0

Steps to reproduce:
- Let's use two companies: CompanyA and CompanyB
- Create a sales tax on CompanyA
- Set it as default tax (Accounting -> Configurations -> Settings -> Taxes)
- Create an identical tax on CompanyB
- Set it as default sales tax
- Create a product being logged into CompanyA

Current behavior:
Sales taxes are set on the product taking into account only sales default taxes from CompanyA

Expected behavior:
Sales taxes should be set taking into account default sales taxes from CompanyA and CompanyB. Otherwise, it will forse us to switch to every available company and manually set the sales tax that's already configured as the default one for that company

**Comment by pedrobaeza** [comment]
This is something expected, as each company has its own taxes, and no deduction must be done even if they have the same CoA, as the fiscal conditions can be different, and apply different taxes. Anyway, we developed a module for easing this, as this can be a common case:

https://odoo-community.org/shop/product/product-tax-multi-company-default-1986

Closing as expected behavior.

**Comment by luisg123v** [comment]
opw-2309316

CC @hugho-ad @dsabrinarg @nhomar

**Comment by luisg123v** [comment]
@pedrobaeza,

I reported the opw before seeing your comment

**Comment by pedrobaeza** [comment]
OK, let's see the official statement, but will be similar. Use the OCA module for you convenience :wink:

**Comment by luisg123v** [comment]
@pedrobaeza Thanks for the suggestion. I had a look to that module and I thinks it just fix perfectly my requirements
