### ISSUE TITLE
Jquery 3.3.1 has a potential Object.prototype pollution vulnerability

### ISSUE THREAD

**Issue by benleedham** [odoo/odoo#55313]
Impacted versions: Odoo 13.0 / Jquery 3.3.1

Steps to reproduce: JQuery is an old version and has potential vulnerabilities

Current behavior: https://blog.jquery.com/2019/04/10/jquery-3-4-0-released/

Expected behavior: That blog details an Object.prototype pollution vulnerability.

**Comment by odony** [comment]
Unfortunately, like most javascript libs, jQuery does not provide security fixes for old impacted versions, and jumping major versions of jQuery on stable Odoo versions is impossible, as it breaks major things. Both standard features and customizations are impacted in a myriad of ways.

For such cases, what we do instead is we analyze the issue and its exploitability through Odoo, and evaluate the necessity of backporting the patch ourselves in the vendored version of the lib we ship with Odoo. This applies for all jQuery CVEs, not just the one you mentioned here.

For CVE-2019-11358 [1] (the issue you are referring to) our analysis with the Javascript framework team revealed that this issue is considered impossible to exploit based on the standard Odoo framework. Our JS code does not generally use `$.extend` for deep cloning, and when we use it, the arguments are not user-provided, and therefore not exploitable. A scan of the various JS libs we use did not reveal anything else that would represent a risk.

Moreover, such a prototype pollution, if ever possible, would have little impact on Odoo, as the security of Odoo is implemented 100% on the server-side - it would be impossible to bypass ACLs. An in-depth analysis of the issue can be found on this blog [2], where it shows the kind of JS applications that could be vulnerable to this.

As a result, we consider that backporting the jQuery patch[3] is not a risk we need to take for Odoo stable. For future versions we are considering upgrading jQuery, or possibly getting rid of it entirely.

**Important note**: the correct way to inquire about a security issue is to contact the security team, following the procedure on our Responsible Disclosure page[4].

*References*:
[1] https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2019-11358
[2] Snyk.io blog on this CVE https://snyk.io/blog/after-three-years-of-silence-a-new-jquery-prototype-pollution-vulnerability-emerges-once-again/
[3] https://github.com/jquery/jquery/commit/753d591aea698e57d6db58c9f722cd0808619b1b
[4] https://www.odoo.com/security-report
