### ISSUE TITLE
Performance issues using recordset.mapped()

### ISSUE THREAD

**Issue by Sathors** [odoo/odoo#5542]
I have discovered the mapped() method not so long ago, and I really find it helpful to reduce code lines.

But in some use cases, it really shows performance problems.

My models
--------------
Here are my custom models:
- model_a 150 000 records
- model_b 150 000 records

```python
class model_a(models.Model):
    model_b_id = fields.Many2one('model_b')
```

Goal
------
Get all the model_b records that are related to a model_a.

Timings
-----------
```python
model_bs = self.env['model.a'].search([]).mapped('model_b_id')
```
takes 35 minutes to complete, whereas

```python
model_b_ids = [record.model_b_id.id
               for record in self.env['model.a'].search([])]
model_bs = self.env['model.b'].browse(model_b_ids)
```
takes less than a minute.

Expected
------------
I would expect the two different ways to complete in the same time.
The first solution is much clearer and much nicer than the second one, at least to me.

**Comment by wtaferner** [comment]
Hi Raphael (@rco-odoo),
I was having performance issues with mapped too, but in relation to the on change mechanism [here] (https://github.com/odoo/odoo/blob/7349e23837e8433bedc134c6bd2c33e92b033209/openerp/models.py#L5851).

I have a record with about 4000 one2many records which are subject to several on change mechanisms.

So, I do understand that it is something to potentially think of in my own model and view design but do you see any possibility to improve this easily? I guess ```record._mapped_cache(field_seq)``` is the wrong improvement, isn't it? It would be great if we can only use mapped for example dirty secondary records...or any solution which improves the issue.

Another view of the issue is that the web client does fire on change requests too fast for x2many records as it is mostly redundant and maybe already invalidated information unnecessarily computed in the backend. For example if you unlink records by fast clicking in the embedded tree view. Partially https://github.com/odoo/odoo/pull/8273 does already help to have only one request per x2many unlink request...

I would be grateful if you could take a short look and help me to understand and it would be absolutely awesome if we could find a solution to tackle this issue.

Best regards,
Wolfgang
