### ISSUE TITLE
[8.0][Bug]Problem with nl_be language with specific Date format

### ISSUE THREAD

**Issue by jlaloux** [odoo/odoo#5555]
Impacted versions:

 - 8.0

Steps to reproduce:
 1. Connect on Runbot, Install nl_BE language and in the configuration of the language, change the date format to "%d %b %y". Set your user language to nl_BE too
![image](https://cloud.githubusercontent.com/assets/7678583/6462292/257fe566-c1a8-11e4-9e4f-2bdb29d3711d.png)

 2. Create a Purchase Order and create a Purchase Order Line
![image](https://cloud.githubusercontent.com/assets/7678583/6462301/3fd5c5a2-c1a8-11e4-8692-810b9e641704.png)

 3. Try to save and you will have an error message telling you that your field is invalid
![image](https://cloud.githubusercontent.com/assets/7678583/6462316/54144c82-c1a8-11e4-9aee-abed2f9e176d.png)

This is not a specific problem of Purchase Order, we encounter the same issue when trying to create a sale order for example

Current behavior:
 - Can't Save

Expected behavior:

 - Record should be saved

**Comment by beledouxdenis** [comment]
Hello Julien,

Set the date format to use the day/month names is not possible for any other languages than English. This is a known issue of Odoo 7.0/8.0.

Sadly, this cannot be fixed in stable releases, such as 7.0 or 8.0: The actual problem is the Javascript date library being used in these releases, that does not support the date translations.

Hopefully, this is being corrected in master, with the use of the library "moment.js" instead of the current library "datejs". See commit
https://github.com/odoo/odoo/commit/88dfd62aa539c5c2ad3e24be06c1ac7cffedd1a5

We hope you will understand.

Regards,

**Comment by jlaloux** [comment]
Thank you for your answer

**Comment by codejq** [comment]
the same problem exists in odoo 9 enterprise version
