### ISSUE TITLE
[12] When '+' is changed by '%2B' ocurrs an error 500

### ISSUE THREAD

**Issue by maitaoriana** [odoo/odoo#56087]
**Impacted versions:**
12.0

**Steps to reproduce:**

- Install website_sale
- Go to the shop
- Order by name 
- Change + by %2B in URL

I dont know how the request changed, but it causes some errors 500 in my server. 

**Current behavior:**

Error 500

`('Invalid "order" specified. A valid "order" specification is a comma-separated list of valid field names (optionally followed by asc/desc for the direction)', '')
`

**Expected behavior:**

Fix error 500

Video/Screenshot link (optional):

[Video](https://drive.google.com/file/d/1DWQzDYhhm9XtuY230fVUj9jj4LYlkBTc/view)

**Comment by pedrobaeza** [comment]
I personally doesn't find this problem using Odoo, but it's true that they should be equivalent. What do you think, @JKE-be ?

**Comment by Yenthe666** [comment]
Hmm, would be a good improvement :)

**Comment by JKE-be** [comment]
Hello
The real question, is where do you have link with double encoding in url ?

+ is the encoding of ' '
%2B is the encoding of '+'


Because if you click on 'order by name asc', and change into the url the 'asc' to 'ascending', you will have the same error...

We could be more 'compliant' and try to guess the double encoding, but it will be interesting to find the source of these ones.

ps: I have the same log error in my own db, most of them seems to be crawler/spider/seo tool.

**Comment by nim-odoo** [comment]
opw 2322186 was created, so closing this to avoid several persons working on this at the same time.
