### ISSUE TITLE
Image upload/URL: Make "alt" and "title" attributes available, especially also for copyright remarks

### ISSUE THREAD

**Issue by treviser** [odoo/odoo#5665]
When using images on a website, the "alt" and "title" attributes of the "img" tag are of utter importance, especially also for copyright remarks.

**Comment by lukebranch** [comment]
@treviser ,

I think this is also true for SEO (eg. Google Image search).

**Comment by jholze** [comment]
:+1:

**Comment by ddfs** [comment]
anyone on this?

**Comment by parthivgls** [comment]
:+1: some of the SEO concept in Odoo is good (e.g. keyword suggestion etc) but some still requires to be added eg. canonical URL, ALT text for images, faveicon config.

**Comment by jholze** [comment]
Hi, we will launch a suite of SEO Add-ons within the next weeks, because there are some important issues in the current odoo route/url handling. We will first improve the SEO handling for CMS pages and the blog addon. The suite is based on a core addon for the core features and each separate addon eg. website_sale can than be updated as well. I'll let you know if we are done with the first version of the SEPO suite hopefully next week. Thanks.

**Comment by treviser** [comment]
Thanks for your efforts, Jens. Keep us updated.

**Comment by lukebranch** [comment]
@jholze ,

Thanks for the update. Looking forward to seeing what your team have developed.

**Comment by ddfs** [comment]
@jholze any news?

**Comment by qsm-odoo** [comment]
Hello,
I am closing this issue, alt and title attributes are editable in supported versions (9.0 and higher).
