### ISSUE TITLE
[8.0 ]ValidationError installing Char of accounts

### ISSUE THREAD

**Issue by aristobulo-eezee** [odoo/odoo#5726]
When trying to install Belgian PCMN chart of accounts I get:

Field(s) `parent_id` failed against a constraint: Error!
You cannot create recursive accounts.

Error details:
CPU time limit exceeded.

Already tried increasing limit_cpu_time and still not working

**Comment by bplancher** [comment]
Hello aristobulo-eezee, 

I had the same issue with French chart of acounts (l10n_fr). 

The main problem is a "timeout" issue (the checks of each account takes too many time to compute).
i tried some things:
- increse limit_cpu_time to 180 and limit_real_time to 240
- add the option import_partial (in order to commit in db the accounts created before timeout)

None of this worked.
So, i commented 2 lines of the module account (/account.py file, arround line 574 and 575), to temporarilly deactivate the constraints "_check_recursion" and "_check_type", and finally, it works !
(I let my previous options too, limit_cpu_time, limit_real_time).
I then reactivated these 2 constraints after installing the module.

Hope it helps you, or someone in the same issue ^^
