### ISSUE TITLE
[7.0 & 8.0] Timesheet : two lines per day when not in UTC timezone

### ISSUE THREAD

**Issue by sylvain-garancher** [odoo/odoo#5809]
@beledouxdenis 
After updating our Odoo instance, timesheets are still broken.
First, we had a total attendance issue : https://github.com/odoo/odoo/issues/5379

Now, we have another issue : When the user's timezone is not UTC, the timesheet has two lines per day.
The problem is easilly reproduced on runbot.odoo.com
![x2znabz](https://cloud.githubusercontent.com/assets/2804014/6705536/07167644-cd56-11e4-8d09-9aef950f7ede.png)

In the query of the SQL view, we have a 2-parts subquery. One of the parts has a "UTC" forced timezone. Then, the "group by timezone" in the final query... splits each day in two lines if the user is not in UTC timezone.

**Comment by sylvain-garancher** [comment]
I just tested on v7, as @vrenaville issue was about 7.0, same issue.

**Comment by tafaRU** [comment]
@sylvain-garancher @beledouxdenis I bumped into same problem.

**Comment by sylvain-garancher** [comment]
@beledouxdenis In addition of the bug described yesterday, my total attendance is still wrong, because I leaved after midnight.

Here is my current timesheet :
![selection_010](https://cloud.githubusercontent.com/assets/2804014/6729041/e899c7aa-ce2e-11e4-9200-81340d77f1bc.png)
The negative value "-8:23" attendance corresponds to "0:34 to 8:57", when I was at home.
Yesterday's attendance is right.

**Comment by beledouxdenis** [comment]
Hello @sylvain-garancher @tafaRU, 

From what I see, the -08:00 value from the first comment message of this issue comes from demo data, adding details lines in the tab "Details".

As soon as you delete every line from this tab, the issue disappear, whatever your timezone and what ever you add as sign in / sign out  in the attendances array.

Now, I do not see the -08:00 is right anyway. There is maybe an issue regarding the "timesheet_ids" field (the lines in the "details" tab) within this SQL view. I will look around a bit more.

**Comment by beledouxdenis** [comment]
The -08:00 was indeed wrong. The difference between the timesheets hours and the attendances hours couldn't be done anymore due to the fact the timesheet timezone was always set to 'UTC' instead of the employee timezone, as you said.

I solved this issue with PR #5884.

I am still hesitating to set this join instead:
```
LEFT JOIN res_users u ON l.user_id = u.id
LEFT JOIN res_partner p ON u.partner_id = p.id
```
Which is shorter, and therefore more efficient, but the user on the analytic line is not required (at least not in the python model, it is in the views), while the employee is required on the timesheet, and the ```sheet_id``` field of sheet analytic lines is a function field choosing a timesheet of the employee matching the user of the analytic line, for the given period.
https://github.com/odoo/odoo/blob/7.0/addons/hr_timesheet_sheet/hr_timesheet_sheet.py#L295-L307

**Comment by sylvain-garancher** [comment]
Hello,

I just tested your patch with our database (v8.0), and the lines are now displayed as expected.
I don't know which join is the best. Maybe @vrenaville could give his opinion about that.

The only wrong value now is caused by a day starting by a sign out (cf my second screenshot).

**Comment by tafaRU** [comment]
Thanks @beledouxdenis
