### ISSUE TITLE
Multi-currency reconcile. 

### ISSUE THREAD

**Issue by tigrus** [odoo/odoo#5839]
Getting error "You have to provide an account for the write off/exchange difference entry." when trying to reconcile bank statement in multi-currency setup. In single currency setup everything works fine. Where to dig? 

I believe, that this error can be more verbose and contain link to instructions, how to resolve it.

**Comment by Whisno** [comment]
If the currency rate changes between the date you issue an invoice and the time you receive the corresponding payment, we create a foreign exchange gain/loss journal entry.
The accounts in which to create those entries need to be configured in the accounting settings (you'll see them just below the checkbox "Allow multi currencies").
I'll see to add a link to the config page in the warning or at least instructions.

**Comment by tigrus** [comment]
@Whisno , ok, what kinds of account must be selected there? We have "Root View" accounts there, and still have exception.

**Comment by Whisno** [comment]
Well, I'm not sure about how this kind of account should be configured. But here is the one from the demo data, I think it could make for a good example.

![capture du 2015-03-19 10 52 01](https://cloud.githubusercontent.com/assets/6009089/6727937/1c1121c2-ce26-11e4-837e-63c7a357af33.png)

**Comment by tigrus** [comment]
@Whisno have set settings to same (Regular / Income for gain, Regular / Expense for loss). Still getting exception. 

Where actually writeoff_acc_id comes from here? 
https://github.com/odoo/odoo/blob/4ed38c2a920aeaacb70c2a81967b57d8f6bb26f6/addons/account/account_move_line.py#L976

**Comment by Whisno** [comment]
The reconciliation is called, without writeoff_acc_id, from https://github.com/odoo/odoo/blob/4ed38c2a920aeaacb70c2a81967b57d8f6bb26f6/addons/account/account_bank_statement.py#L826
There is no writeoff_acc_id because the foreign exchange gain/loss journal entry is supposed to be created here https://github.com/odoo/odoo/blob/4ed38c2a920aeaacb70c2a81967b57d8f6bb26f6/addons/account/account_bank_statement.py#L794

Let's pray that it's not a bug about multicurrency and/or rounding errors.

However, I tried to reproduce and it went fine : 
![capture du 2015-03-19 12 03 55](https://cloud.githubusercontent.com/assets/6009089/6729187/16fbdce0-ce30-11e4-80de-ae62fc968279.png)

Do you have a scenario ?

**Comment by tigrus** [comment]
@Whisno , scenario will look complex, like: 

1) In settings we set our currency in TWD
2) We creating Sale Order in RUB 
3) We creating Invoice for Sale Order in RUB 
4) We creating incoming bank statement
5) In statement we create line, with currency RUB, that fits our Invoice
6) We go to reconcile 
7) On attempt to reconcile - we get exception 

In used accounts we have secondary currency set to RUB. Journals also use RUB.

**Comment by Whisno** [comment]
Sorry, I tried on this instance: http://55232-8-0-issue-629511-problemes-agend-772cfc.runbot6.odoo.com/ but couldn't reproduce

**Comment by tigrus** [comment]
@Whisno wow, thx for instances. We found, that we had secondary currency set. With secondary currency - exception. Without it - reconcile work. So, settings is not the only reason for exception. Please add in message couple of words about secondary currency.
