### ISSUE TITLE
LDAPS support

### ISSUE THREAD

**Issue by Fnux** [odoo/odoo#58456]
Hello!

The LDAP authentication backend does not support LDAPS as of writing (13.0 - it only supports plain connections, optionally upgraded to STARTTLS). Many LDAP servers are only available over TLS, hence not compatible with odoo right now. We need a new configuration option to use `ldaps://` instead of `ldap://` at https://github.com/odoo/odoo/blob/13.0/addons/auth_ldap/models/res_company_ldap.py#L74.

**Comment by pedrobaeza** [comment]
Not planned for now to add such support in core. Use https://odoo-community.org/shop/product/ldaps-authentication-3210

**Comment by azmeuk** [comment]
@pedrobaeza @beledouxdenis @tivisse @mart-e @hbrunn
Would [such a patch](https://github.com/supercoopbdx/odoo/commit/a70ff8fbb676c2d1a5d9e48647bb49cb123a5e2b) be acceptable?

This would provide core `ldaps` at very cheap cost, and is totally backward compatible.

With this patch users are able to pass the protocol with their ldap domain: `ldaps://ldap.mycompany.tld` instead of `ldap.mycompany.tld`, and `python-ldap` does all the magic.

**Comment by martinvonwittich** [comment]
> Not planned for now to add such support in core. Use https://odoo-community.org/shop/product/ldaps-authentication-3210

Please reconsider. The 3rd party module only supports up to odoo <= 14, which is by now two major versions out-of-date.

STARTTLS over implicit TLS was recommended in the past because it seemed backwards to require two separate ports per protocol when STARTTLS seemingly didn't have any disadvantages (at least for properly configured clients that enforce it), but in the e-mail world, where STARTTLS originated, this trend has made a U-turn in the past few years:

https://www.rfc-editor.org/rfc/rfc8314#section-1

Cleartext Considered Obsolete: Use of Transport Layer Security (TLS) for Email Submission and Access (January 2018)

>    In brief, this memo now recommends that:
> [...]
>   `o`  Connections to Mail Submission Servers and Mail Access Servers be
>      made using "Implicit TLS" (as defined below), in preference to
>      connecting to the "cleartext" port and negotiating TLS using the
>      STARTTLS command or a similar command.

https://www.rfc-editor.org/rfc/rfc8314#appendix-A (emphasis mine)

>  One author of this document was also the author of [RFC 2595](https://www.rfc-editor.org/rfc/rfc2595), which
>   became the standard for TLS usage with POP and IMAP, and the other
>   author was perhaps the first to propose that idea.  **In hindsight,
>   both authors now believe that that approach was a mistake.**  At this
>   point, the authors believe that while anything that makes it easier
>   to deploy TLS is good, the desirable end state is that these
>   protocols always use TLS, leaving no need for a separate port for
>   cleartext operation except to support legacy clients while they
>   continue to be used.  **The separate-port model for TLS is inherently
>   simpler to implement, debug, and deploy.**
> [...]
>   **Although STARTTLS appears only slightly more complex than
>   separate-port TLS, we again learned the lesson that complexity is the
>   enemy of security in the form of the STARTTLS command injection
>   vulnerability (Computer Emergency Readiness Team (CERT) vulnerability
>   ID #555316 [[CERT-555316](https://www.rfc-editor.org/rfc/rfc8314#ref-CERT-555316)]).  Although there's nothing inherently wrong
>   with STARTTLS, the fact that it resulted in a common implementation
>   error (made independently by multiple implementers) suggests that it
>   is a less secure architecture than Implicit TLS.**

https://www.usenix.org/system/files/sec21-poddebniak.pdf

Why TLS is better without STARTTLS: A Security Analysis of STARTTLS in the Email Context (August 2021)

> In summary, we conclude that STARTTLS has systemic
> problems that lead to implementation flaws, that STARTTLS
> is insufficiently specified, that STARTTLS has no security
> advantage over implicit TLS connections, and is slower than
> implicit TLS due to additional round trips. Therefore, we
> recommend using implicit TLS and deactivate STARTTLS
> for email submission and retrieval whenever feasible.

A corresponding discussion has happend on the OpenLDAP mailing list (https://www.openldap.org/lists/openldap-technical/201802/msg00004.html, February 2018):

> To me this rationale for SMTP submission with implicit TLS seems also
> applicable to LDAPS vs. StartTLS:
> 
> https://tools.ietf.org/html/rfc8314#appendix-A
> 
> So LDAPS should not be considered deprecated. Rather it should be
> recommended and the _optional_ use of StartTLS should be strongly
> discouraged.

It was met with strong approval, but unfortunately, no change has been made to the OpenLDAP documentation yet, which therefore still recommends STARTTLS over LDAPS. But as I have hopefully made my point, this is an outdated, insecure practice.
