### ISSUE TITLE
Value from DB when export field datetime

### ISSUE THREAD

**Issue by luistorresm** [odoo/odoo#5865]
1) Steps to reproduce the issue you have observed 
Set a time zone to user.
Create an stock.move in the system, with date expected.
Export this register whit this field.

Can find a demonstrative video here:
http://youtu.be/G7TddTprpn4

2) The result you observed
In the view I see a datetime and on the file exported I see different date and time

 3) The result you expected
That in the file exported I get the same datetime from view

4) The Odoo version
https://github.com/odoo/odoo/commit/efe8bfe5f17c0d60636d76e31852d64e8366e1ea

**Comment by beledouxdenis** [comment]
Hello Luis, 

We are not sure we can consider this as a bug.

Indeed, we understand your point, but, if the goal of exporting these fields is to re-import it in another database / with another user, the dates will be wrong if you do not have the same timezone in this other database / with this another user.

I believe the current behavior is the expected one, the dates in the csv export must always be set in UTC, because:
 1. The above reason
 2. The timezone won't be precised in the csv file exported. If you work in a company with employees working in different time zones, this could be problematic, as it will be impossible to know in which timezone the dates are in. If you always export the dates in UTC, you ensure to always know the timezone.

Regards,

**Comment by sbidoul** [comment]
@beledouxdenis while the current behaviour is correct for "import compatible export", the other mode "export all data" should export in the user's timezone.

**Comment by laetitia-gangloff** [comment]
OPW: 656713

**Comment by beledouxdenis** [comment]
Hello Laetitia,

This is a change of behavior, which are not accepted in stable releases of Odoo.
https://github.com/odoo/odoo/wiki/Contributing#what-does-stable-mean

Customers could rely on the current behavior. For instance, this is not impossible that a user exports his data with the mode "export all data", import it in another system than Odoo, and this system expects as well the imported datetime to be in UTC.

Regards,
