### ISSUE TITLE
[Bug] Odoo Client Error: when click on "Edit" button top right corner on website editor.

### ISSUE THREAD

**Issue by redapureskill** [odoo/odoo#58929]
After installing Odoo14 Community on windows, i'm testing the website module.
I get this error when i'm use **Google chrome** browser, but i dont get it when i use **Firefox**.

Error:

Traceback:
TypeError: Wysiwyg is not a constructor
    at http://localhost:8069/web/content/625-f196d89/2/web.assets_common_lazy.js:5100:55
    at async Class._startEditMode (http://localhost:8069/web/content/627-e7bc688/2/website.assets_editor.js:56:26)
    at async Promise.all (index 0)

**Comment by redapureskill** [comment]
Impacted versions: Odoo 14

Steps to reproduce: Go to Website> Settings> Got to website> Click action > Click "Edit"

Current behavior: Odoo Client Error.

Expected behavior: the website editor palette appears.
Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/9614843/94820149-070d0a80-03f8-11eb-85ff-895942f0bd7a.png)

**Comment by pedrobaeza** [comment]
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - click on the blue door icon of the version row - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by redapureskill** [comment]
Hi
i've donwloaded the latest code of website , upgraded the module and everything is working fine.
thank you for support.
