### ISSUE TITLE
[14.0] Purchase: Cannot add product after received.

### ISSUE THREAD

**Issue by kayue** [odoo/odoo#59664]
Impacted versions: 14

Steps to reproduce:
- Create and receive a PO
- Click "Edit" button to edit the PO
- Click "Add a product" link

Current behavior:
- Product field missing after click on "Add a product"

Expected behavior:
- Product field (dropdown) should appear after click on "Add a product"

Video/Screenshot link (optional):

![P00056__INV_91835-Bought__-_Odoo](https://user-images.githubusercontent.com/193112/95595598-e8a1b180-0a7e-11eb-9249-bc3882a205c9.jpg)

**Comment by pedrobaeza** [comment]
I think you need to show detailed operations.

**Comment by sswapnesh** [comment]
@pedrobaeza  I think you misunderstood this, @kayue  is talking about PO.

I can confirm this behavior, You are not able to select product once It is confirmed (While you can still do the same on v13)

It has same attrs on v13/14

https://github.com/odoo/odoo/blob/aa006658ea25abaa2b8d03003f1d4f9214fb6468/addons/purchase/views/purchase_views.xml#L228

**Comment by sswapnesh** [comment]
It seems due to setting up related field (state) on po line at https://github.com/odoo/odoo/pull/53898/commits/f18bdc4fcf2b6b0bdb7699c3b2aa38d332301a84

On v13 state is always blank on adding new lines (https://4500006-13-0.runbot56.odoo.com/web?debug=1#action=757&cids=1&id=10&menu_id=534&model=purchase.order&view_type=form)

![Screenshot from 2020-10-09 22-32-09](https://user-images.githubusercontent.com/16624719/95611316-4afab200-0a7f-11eb-9f4e-aa41658d2dbe.png)



and on v14 the state is added correctly so product_id is readonly
![Screenshot from 2020-10-09 22-32-56](https://user-images.githubusercontent.com/16624719/95611377-64036300-0a7f-11eb-8b78-5d3d5426582a.png)



I think its a regression from https://github.com/odoo/odoo/pull/53898 so we need to align the domain based on this.

cc @pedrobaeza  as you have checked same thing on https://github.com/odoo/odoo/issues/53253

**Comment by pedrobaeza** [comment]
@amoyaux can you please check as you did #53898 ?

**Comment by ryv-odoo** [comment]
Hi @kayue , 
Thank you to have report this issue
We created a fix in the https://github.com/odoo/odoo/pull/59720
