### ISSUE TITLE
[14.0] [i18n] Majority of the Arabic translations have disappeared

### ISSUE THREAD

**Issue by pawa2007** [odoo/odoo#59818]
Impacted versions:
14.0

Steps to reproduce:
1. Activate developer mode
2. Go to Settings > Translations > Languages and activate "Arabic" (ar_001)
3. Set the logged in user's language preference to Arabic

Current behavior:
A majority of the labels are still displayed in English

Expected behavior:
Labels should be displayed in Arabic

Video/Screenshot link (optional):
Sample screen when Arabic is selected in 14.0
![image](https://user-images.githubusercontent.com/21964536/95821515-b2e31e00-0d47-11eb-84d8-64f9340435aa.png)

Same screen when Arabic is selected in 13.0
![image](https://user-images.githubusercontent.com/21964536/95821210-26d0f680-0d47-11eb-8ee9-d428f578cb69.png)

**Comment by pawa2007** [comment]
Did some more research on this and it looks like the following commit that was done 2 days back (Oct 11, 2020) has wiped out a majority of the translations.

[Commit](https://github.com/odoo/odoo/commit/03e0c53f40ef30589ebea36b954b6966fe45e3e5)
[Link to blame of .po file in crm](https://github.com/odoo/odoo/blame/14.0/addons/crm/i18n/ar.po)

**Comment by Yenthe666** [comment]
@mart-e

**Comment by mart-e** [comment]
Hi,

This is because of the new version without all the terms from the previous one.
The sync is [now completed](https://www.transifex.com/odoo/odoo-14/language/ar/) and all the common terms will be present in the next synchronisation, this weekend.
See our [translation wiki page](https://github.com/odoo/odoo/wiki/Translations) if you wish to contribute to help the Arabic translation of Odoo.
Best,
