### ISSUE TITLE
[9.0][8.0][master][saas-6] statusbar_colors is no more supported 

### ISSUE THREAD

**Issue by JonathanNEMRY** [odoo/odoo#5987]
**statusbar_colors is no more supported**

Impacted versions:

 - 8.0, master, saas-6

I noticed that this property is no more supported since this commit b4c28050
Nervertheless in the same time this feature is used in a lot of Odoo native modules.

Are you sure that this code removal was a real intention covered by this commit ?

**Comment by yvaucher** [comment]
9.0 is still affected.

There are still a lot of example that still doesn't work in official addons.
Plus it is still referenced in documentation.

**Comment by phuihock** [comment]
I just made a PR. The problem was Odoo changed from simple color to gradient as background.

For this PR to work, the dict must be a valid JSON object.

This will works:
`statusbar_colors='{"onhold":"#ffcc00","cancel":"red"}''`

This won't work:
`statusbar_colors="{'onhold':'#ffcc00','cancel':'red'}"`

You will get the following error instead because `JSON.parse` fails to parse your object:
`Uncaught SyntaxError: Unexpected token '`

**Comment by dreispt** [comment]
Ping!

**Comment by yvaucher** [comment]
@phuihock you have an extra ' at end of your example of what is working
``` python
statusbar_colors='{"onhold":"#ffcc00","cancel":"red"}''
                                                      ^
```

**Comment by phuihock** [comment]
@yvaucher Typo. Fixed.

**Comment by mart-e** [comment]
Hello,

As explained at #11199, we do not wish to reintroduce this, sorry.

**Comment by phuihock** [comment]
This makes sense for 9 because we have `statusbar_visible`, but there isn't any substitute for 7 or 8.

No chance pushing this to 7/8 only?

**Comment by dreispt** [comment]
@phuihock That's one of the reasons why OCB exists.

**Comment by phuihock** [comment]
@dreispt Sad but true.

**Comment by NL66278** [comment]
I just created a PR on the OCA that will also support single quoted color properties in the view https://github.com/OCA/OCB/pull/524
