### ISSUE TITLE
[14.0]Accounting: Issue when Create Root Report Lines

### ISSUE THREAD

**Issue by hajajroshan** [odoo/odoo#60045]
**Impacted versions:**
14.0

**Steps to reproduce:**
1. Accounting -> Configuration -> Tax Report
2. Create Tax Report
3. Click add line
![image](https://user-images.githubusercontent.com/62367855/96088828-9ed42380-0ee3-11eb-9e1c-03ffb5767aaf.png)

4. fill the fields and try to save
![image](https://user-images.githubusercontent.com/62367855/96089063-ece92700-0ee3-11eb-9586-32b07220d89b.png)

**Current behavior:**

**Tax Report** field in Root Report Lines is required and read-only. So can't save it as shown in the above screenshot

**Expected behavior:**

- Either Tax Report not required or It shouldn't be a read-only filed

**Comment by sswapnesh** [comment]
Ping @oco-odoo

**Comment by oco-odoo** [comment]
It actually appears in saas-13.3. I fixed it here: https://github.com/odoo/odoo/pull/60274

Note that due to design limitations of our js framework (newids not being propagated like regular ids), it still won't work if you create the report and directly want to create its lines. Instead, you have to save first, then edit to add the lines. For now, I guess we have no better choice ( @ged-odoo possible improvement for future versions? :) )

**Comment by sswapnesh** [comment]
This has been fixed in https://github.com/odoo/odoo/pull/60280

**Comment by oco-odoo** [comment]
I'm closing the issue, then. Thank you for reporting :)

**Comment by hajajroshan** [comment]
> Note that due to design limitations of our js framework (newids not being propagated like regular ids), it still won't work if you create the report and directly want to create its lines. Instead, you have to save first, then edit to add the lines. For now, I guess we have no better choice.

I tried this way. but still the tax report field doesn't bring any value.

![Peek 2020-10-23 00-07](https://user-images.githubusercontent.com/62367855/96915456-dfbfcf80-14c3-11eb-8f95-6ae33cfed68f.gif)

**Comment by oco-odoo** [comment]
@hajajroshan It has indeed been merged. I just retested on runbot and it seems okay. Have you updated the module?
