### ISSUE TITLE
[13] Sale: "Product column" sorting is not working in the "Sales order" - if the "Product Configurator" is enabled

### ISSUE THREAD

**Issue by hrahuu** [odoo/odoo#60065]
Impacted versions: 
- Odoo 13 Enterprise

Steps to reproduce:
1. Install Sales app
2. Install "Product Configurator" module by checking it in the Odoo Sales settings.
3. Open a sales order that has multiple order lines.
4. Click Edit to edit this sales order.
5. Click Product column 

Current behavior:
-> Nothing happens

Expected behavior:
-> Order lines should be sorted according to items in the Product column (alphabetical order).
Notice: it works OK if "Product Configurator"-module is not installed. Thus the bug can be found in this module.

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/7082512/96107817-8b29bc80-0ee5-11eb-962a-b9d385d98f5c.png)
![image](https://user-images.githubusercontent.com/7082512/96108083-dcd24700-0ee5-11eb-89bb-a289fe69f835.png)

**Comment by Feyensv** [comment]
Indeed, it's due to the intrinsic implementation of the product configurator.

When installing `sale_product_configurator`, the field shown as "Product" on the sale order lines isn't the `product_id` (product.product) but the `product_template_id` (product.template) field, to allow the user to select a product template, before choosing the wanted variant (product.product) in the dedicated wizard.

As `product_template_id` isn't stored, you cannot order the sale order lines by this field.

If you really want to order by "Product", you have to manually show the `product_id` field column in the view, which could be used to sort the lines by product (but you will have 2 "Product" columns shown).
