### ISSUE TITLE
[13.0] Language Export to Error

### ISSUE THREAD

**Issue by altanmur** [odoo/odoo#60671]
Impacted versions: 13.0 Community, I not check 14

Steps to reproduce: Language export menu press

Current behavior: Error
```
File "/Volumes/DATA/workspace/framework/odoo/odoo-github/odoo-hub-13.0/odoo/api.py", line 374, in _call_kw_multi
    result = method(recs, *args, **kwargs)
TypeError: default_get() missing 1 required positional argument: 'fields'
```
Expected behavior: Select Module Wizard
Video/Screenshot link (optional):

![ezgif-1-dd5374568f75](https://user-images.githubusercontent.com/31090100/97078393-9768f480-161e-11eb-8630-d6ac8ad57e60.gif)

**Comment by pedrobaeza** [comment]
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - click on the blue door icon of the version row - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by sswapnesh** [comment]
Seems working well on Runbot

**Comment by altanmur** [comment]
Hello, Pedro Baeza

I use many versions at the same time.
I'm just running on a separate .sh, .conf, other port. Another user is working on the same database.

Maybe that's a problem.

How do you run in a separate environment?

I use VScode on MacOS.

**Comment by Yenthe666** [comment]
Well it doesn't really matter as that would mean it is a deployment issue. Can you reproduce the same behaviour on runbot @altanmur?

**Comment by altanmur** [comment]
Hello, @Yenthe666 @pedrobaeza 

I can not again reproduce the error on runbot.
Working export language of the module on my local CE.
