### ISSUE TITLE
[12.0] translations are not delete on unlink

### ISSUE THREAD

**Issue by celm1990** [odoo/odoo#61904]
**Impacted versions:**
12.0
**Steps to reproduce:**
Install language as Spanish

Create a Product Category, translated terms is created

![image](https://user-images.githubusercontent.com/7775116/99443410-c8b8a580-28e8-11eb-8be2-f586e01e0b31.png)

![image](https://user-images.githubusercontent.com/7775116/99443450-d5d59480-28e8-11eb-876f-a383e72d4277.png)

Delete Product Category, translate terms are not unlink
![image](https://user-images.githubusercontent.com/7775116/99443476-dd953900-28e8-11eb-8952-d56cf74c66f9.png)

![image](https://user-images.githubusercontent.com/7775116/99443521-edad1880-28e8-11eb-8afe-6592d96d1e08.png)

**Current behavior:**
Translate terms are not unlink to unlink records

Only affected V12, on V13 field name remove translate=True on https://github.com/odoo/odoo/pull/36717
**Expected behavior:**

Unlink translated terms to unlink records for avoid keep orphan records
Video/Screenshot link (optional):

@mart-e  is possible fixed this?

**Comment by sswapnesh** [comment]
Isn't it fixed in https://github.com/odoo/odoo/pull/32056 ?

**Comment by celm1990** [comment]
> Isn't it fixed in #32056 ?

I tested on runbot today and not is fixed

**Comment by mart-e** [comment]
Hi,

No, it's "fixed" because we don't consider it as a bug worth fixing. In #32056, we remove _some_ translations, the one linked to fields during uninstallation of a module because it could actually cause a traceback. Having leftover translations of random record isn't a big issue. It would slow down the unlink method without actually fixing a bug (i.e. having leftover translations that would cause an error), on the contrary (a bit tricky with inherited models, could remove translations that are still useful).
Sorry but we are most likely not going to change that if we don't have a good reason to do so.

**Comment by celm1990** [comment]
ok, thanks @mart-e for the explain :(
