### ISSUE TITLE
This webpage has a redirect loop

### ISSUE THREAD

**Issue by MohitShukla** [odoo/odoo#6202]
I was making a website using website builder of Odoo. 
URL: https://krotone.odoo.com/
After making a few changes I get error: "This webpage has a redirect loop".
You can see this by simply opening this page. even when I try to go back to website builder to try to edit I get same error.

So basically I can now neither view the site nor edit the site. I was building the site for commercial use. But I am getting shivers now. I am rethinking if I should use Odoo or not. I like the Odoo website builder a lot. But such issues are a de-railer.

**Comment by mart-e** [comment]
Hello,

That's a configuration issue. Your home menu was pointing to your domain (instead of a single page like `/page/homepage`) so getting to your home is redirecting you to the redirection page, so yes, infinite loop.
And note that setting a URL as destination of a menu is a feature we do want to allow.

**Comment by MohitShukla** [comment]
Thanks for looking into it. Much appreciated.

It would have been more useful if the error message told me how to fix the
issue rather than just telling me that there is an issue.

**Comment by techshaliblog** [comment]
I've recently had the chrome redirect loop on gmail.

Possibly significantly, I was doing some work involving changing my system time and it hasn't worked since. This [guide](https://techshali.com/fix-webpage-has-redirect-loop-error/) helped to do that.

There is an available work-around, which is to use gmail in incognito mode, which does still work, although requires you to log in each time
