### ISSUE TITLE
[13.0][BUG] account: compute_all method always rounds total_excluded

### ISSUE THREAD

**Issue by gaikaz** [odoo/odoo#62121]
After changes in https://github.com/odoo/odoo/commit/32d47d32c62abade2d27ffa231940811771566b7 it seems to no longer be possible to compute a `total_excluded` without it being rounded when using `compute_all` method **with context `round: False`**
This is a very needed context feature in some reporting cases, where a company is using "Tax included" pricing.

Exact place where rounding becomes no longer optionable:
https://github.com/odoo/odoo/commit/32d47d32c62abade2d27ffa231940811771566b7#diff-d6ae6cf48e0ebb6c568352a8eccb80526c6f53e66984a71f36179dd40641d163L1676-R1701

Impacted versions:
13.0

Steps to reproduce:
Create a `server.action` for model `server.action` (this way a "Run" button appears) with this code:
```python
tax = env['account.tax'].create({
  'name': 'Tax 20%',
  'amount': 20,
  'price_include': True,
})
res = tax.with_context({"round": False}).compute_all(
    1.23, # Price with tax included
)
raise Warning(res['total_excluded']) # Prints 1.03, when it should be 1.025
```

Current behavior:
`compute_all` method always rounds `total_excluded` to currency precision

Expected behavior:
Setting `round: False` in context, `compute_all` should not round the results

@smetl

**Comment by smetl** [comment]
This is the expected behavior. I don't understand why you need it "for some reporting cases". You must never recompute taxes on the fly when opening a report:
- very bad performances
- wrong in all corner cases (manual edition of taxes, cash basis taxes, python taxes, tax rounding etc)
You need to keep in mind everything returned by the `compute_all` method could land into a `monetary` field. Therefore, you can't simply round the result without opening the door to a lot of rounding issues.

For example:
Suppose an invoice line with  `price unit = 44.2478` and `quantity = 2` and a 2-digits currency. `2 * 44.2478 = 88.4956` but the taxes must be applied on `88.5`, not `88.4956`.

In your example, the `total_excluded` will be used in accounting entries as the `balance` so it must be round to 2 digits: `1.03`.

**Comment by gaikaz** [comment]
Thanks for your time and solid answer. Really appreciate it.
