### ISSUE TITLE
View inheritance mechanism fails in v14.0

### ISSUE THREAD

**Issue by olilau** [odoo/odoo#62327]
Impacted versions: 14.0

Steps to reproduce:

* create a module "mod_1" that depends on 'product'
* create a module "mod_2" that depends on "mod_1" and containing:
  - a model that inherit from 'product.template'
    this model defines a method named "get_result"
  - a view inheriting from "product.product_template_form_view" and adding a button:
    "<button name="get_result" type="object" ..."
* create a module "mod_3" that depends on "mod_2" along with 'sale_management'

Try to create a database and install the "mod_3" module
  odoo-bin -d DB -i mod_3

Current behavior:

a traceback will occur. The main error being:
  "get_result is not a valid action on product.product"

If instead of installing the "mod_3" module directly, you install the "sale" module before, everything is right:
  odoo-bin -d DB -i sale
  odoo-bin -d DB -i mod_3
  ->will install fine

Expected behavior:

The db should install fine.

I've attached an archive with the modules and the complete traceback.

[tb.log](https://github.com/odoo/odoo/files/5596980/tb.log)
[odoo_14_bug_inheritance.zip](https://github.com/odoo/odoo/files/5596982/odoo_14_bug_inheritance.zip)

**Comment by Feyensv** [comment]
https://github.com/odoo/odoo/blob/14.0/addons/product/views/product_views.xml#L4
>   ` <!-- base structure of product.template, common with product.product -->`

The view `product.product_template_form_view` is the base view for both `product.product` and `product.template` models

It is expected that the view validation raises because you didn't implement `get_result` on `product.product` model.
You should probably inherit the view `product.product_template_only_form_view` instead.

**Comment by olilau** [comment]
Thank you for your explanation Victor :) It works.
BTW, it worked in versions < 14.0

Closing this ticket.
