### ISSUE TITLE
[8.0] Create issue in followers-only project

### ISSUE THREAD

**Issue by mariuszmizgier** [odoo/odoo#6257]
1. Create a new project with followers only visibility.
2. Add a user, which has Projects/User access rights to followers.
3. Login as user from point 2.
4. Create an issue in project created in point 1.

Outcome - Access Denied
The requested operation cannot be completed due to security restrictions. Please contact your system administrator.
(Document type: project issue, Operation: create)

Expected outcome - issue being created
Problem source - record rule "Project/Issue: employees: public, portal, employee or (followers and following)"
After making that record rule not active issue is being created.

Movie with this issue - https://youtu.be/PfhR7e00pLY

**Comment by beledouxdenis** [comment]
Hello Mariusz, 

This is actually the expected behavior. As you can see in the Privacy / Visibility field tooltip of the Project:

"Followers Only: employees see only the followed tasks or issues; if portal\n"
                    "   is activated, portal users see the followed tasks or issues."

See the image below for illustration:
![screenshot from 2015 04 15 10 35 18](https://cloud.githubusercontent.com/assets/5822488/7155038/c8b6b712-e35b-11e4-9831-838994504970.png)


When the Project is set to followers only, the Project users aren't allowed to create new issues / new tasks. Only project managers can. Employees are only allowed to read, edit or send messages in issues in which they are already in the followers.

If this isn't what you want, you will have to customize the record rule you mention according to your needs, but the current behavior is the standard and expected behavior.

Regards,
