### ISSUE TITLE
Problem with cache system for new API

### ISSUE THREAD

**Issue by pedrobaeza** [odoo/odoo#6276]
I have detected a problem with cache system of the new API. The cache is stored in memory relying somewhat in a Python instance variable of the environment (env), but sometimes you need to do things like:
```
self.with_context(key=value)
```
For example, if you have two modules with this code (I omit obvious stuff like class declaration):
Module 1
------------
```
field_x = fields.Integer(compute="_get_field_x")

@api.one
def _get_field_x(self):
    if self.env.context.get('x'):
        self.field_x = self.env.context['x']
    self.field_x = 0
```
Module 2
------------
```
@api.one
def _get_field_x(self):
    obj = self.with_context('x': 2)
    super(Class, obj)._get_field_x()
```
you will get a KeyError when trying to retrieve this value afterwards, because the env you're assigning when overwriting, is not the same as the env without overwriting.

Compute method doesn't fail, but it's the start of the problem. When you make `self.field_x = ...`, ORM stores in cache the value with another env.

Then, if for example a view renders that field, it will try to find the value in the cache matching with its own env, and it will fail with the corresponding KeyError.

@rco-odoo, can you please check it.

**Comment by rco-odoo** [comment]
@pedrobaeza this problem is inherent to the cache structure: every environment `env` has its own cache, because the value of fields may depend on the environment. When you assign a field to a `record`, the value is stored in the cache of `record.env`. Thus, in your case, you should simply copy the value of the field from one cache to another.

#### Module 1

    field_x = fields.Integer(compute="_get_field_x")

    @api.one
    def _get_field_x(self):
        self.field_x = self._context.get('x', 0)

#### Module 2

    @api.one
    def _get_field_x(self):
        other = self.with_context(x=2)          # other belongs to a different env
        super(Class, other)._get_field_x()      # assign other.field_x in other's cache
        self.field_x = other.field_x            # copy value from other's cache to self's cache

Please tell me whether this fixes your problem.

**Comment by pedrobaeza** [comment]
Hi, Raphael, thanks for the quick response. Yeah, that solves this specifc problem, but you have to know which fields have been written on super call to copy their values in your env cache, and this is very little modular and maintainable.

I know that the change is huge, but shouldn't the cache change its structure to avoid this env dependency?

**Comment by rco-odoo** [comment]
@pedrobaeza I come back to you on this cache topic.

The problem is inherent to the ORM: the value of a field on a given record may depend on the `uid` or `context`. Examples:
- The value of translated fields depend on `context.get('lang')`.
- One2many/many2many fields may show different subsets of records depending on `uid` and its corresponding access rights: values are filtered by access rules.
- Function fields can depend on `uid` and `context`: think about the stock level of products depending on the user's main warehouse.
- Even plain stupid fields depend on `uid`: they should never occur in cache if the user does not have access rights on the model, record, or field.

I have recently tried to "merge" the record caches within a transaction (to reduce the number of SQL queries sent to fill in these caches), but things break very quickly :disappointed:

**Comment by pedrobaeza** [comment]
OK, I understand. Maybe we should consider for the next version a "double context variable" that allows to pass in one of them some values to other methods without altering the cache/environment, and another that effectively change them (for 'lang', 'force_company' and other possible ORM modifiers).
