### ISSUE TITLE
Run Schedulers does not finish running

### ISSUE THREAD

**Issue by felipeuy** [odoo/odoo#62896]
Impacted versions: 13 CE

Steps to reproduce: Go to Inventory Tab, run scheduler

Current behavior: Scheduler does not finish to generate automatic PO. 
Odoo logs: ```
odoo.sql_db: Cursor not closed explicitly
Please enable sql debugging to trace the caller 
```

Expected behavior: Finish running scheduler 

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - click on the blue door icon of the version row - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by felipeuy** [comment]
Hi Pedro! I will try to reproduce it un runbot and let you know of course.
Will also explain as further as possible, I really hope it is nothing. Odoo is great, and Is really helping my organization. 

— Felipe

**Comment by felipeuy** [comment]
@pedrobaeza I'm trying to reproduce the bug on the runbot instance, and it works ok. 
So I'm sure the issue is on our side due to a change made by an odoo partner we hired a while ago. 
I will close this issue and re open it once I am certain it is not on our side. Sorry for the inconvenience and thanks for your help. -- Felipe

**Comment by pedrobaeza** [comment]
No worries. I wish everybody understands the procedure as you have done.
