### ISSUE TITLE
Missing analytic account in write off

### ISSUE THREAD

**Issue by alexis-via** [odoo/odoo#63004]
Impacted versions: 14.0 and lower

This screenshot sums it up:

![missing_analytic_write_off](https://user-images.githubusercontent.com/1157917/101476220-b82aa680-394d-11eb-9019-58e96de071a4.png)

On an unpaid customer invoice, click on the button "Register Payment", enter a lower amount, then, in the "Payment difference" block, select "Mark as fully paid": you will see 2 fields "Post Difference In" and "Label"... but it misses a field to select an analytic account ! The writeoff account is an expense, so it should have a related analytic account.

I provide a patch for odoo v14 to fix this issue: https://github.com/akretion/odoo-usability/blob/14.0/account_usability/invoice_register_payment_writeoff_analytic.diff

As fixing the issue involve adding a field, I will probably never be fixed for v14, but it should be fixed in master.

**Comment by Yenthe666** [comment]
@oco-odoo this one is pretty important

**Comment by oco-odoo** [comment]
@alexis-via 
Thanks for reporting the issue. As you were suggesting, this kind of improvement can only be done in master, as it requires a new field. We are actually currently in the early process of revamping analytic accounting, so I discussed it with our product owner and added it to the list of improvements to make; your issue comes just in time ;) 

Also, thanks @Yenthe666 for pinging me on this :)


I'm closing the issue, so that we keep better track of what is new and what isn't, but we'll definitely do something about it :)

**Comment by bunhin** [comment]
I believe this is not implemented/fixed until now right? 14,15,16, even on master. @alexis-via do you create a custom module for it?
