### ISSUE TITLE
[Wishlist][OWL] PatchMixin should be the default

### ISSUE THREAD

**Issue by keshrath** [odoo/odoo#63118]
**Using React or Vue would make it significantly harder to monkey patch components, because a lot of the state is hidden in their internals.**

Source: https://github.com/odoo/owl/blob/master/doc/miscellaneous/why_owl.md

What is the reason that not all components are patchable? In the old widget system all widgets allow to call the `include` function. But now not all components are extendable. Why is that? This is one of the fundamental building blocks of the Odoo framework.

Example with patchMixin: https://github.com/odoo/odoo/blob/14.0/addons/web/static/src/js/control_panel/custom_filter_item.js
Example without Mixin: https://github.com/odoo/odoo/blob/14.0/addons/web/static/src/js/components/pager.js

If you don't want to have this functionality directly in the OWL Framework, you could patch it for the Comonent Class in general, like it was done with the `rpc` function.

I hope someone can give me some insight into this decision. I'm afraid that with version 15 and later many things will not be customizable anymore. 

@ged-odoo

**Comment by ged-odoo** [comment]
@keshrath Don't worry, we are aware of this issue and plan to work on it very soon. See https://github.com/odoo/owl/issues/794
The reason it was not done yet was because 1. we had a lot of urgent work. 2. we were not exactly sure of the best way to proceed.

But we have reached an agreement: owl components will have a new `setup` (or `init`?) method called by the constructor (and so will all the non component classes in odoo), and we will provide the `patch` method.

**Comment by ged-odoo** [comment]
(closing because we have already our internal issue tracking this)
