### ISSUE TITLE
Google Analytics - Conversion Tracking Tag

### ISSUE THREAD

**Issue by Uhub202** [odoo/odoo#63116]
Impacted versions: v 13.0

Steps to reproduce: 

Current behavior: I need to add a conversion tracking tag to the shop/confirmation page to track purchases, but I'm not sure how I should proceed. I think the best way is to create a qweb view and inherit it to website_sale.confirmation, but after that I don't know if I need to write an <xpath and <t t-if before the <script> with the conversion tracking tag.

Expected behavior: Be able to add a conversion tracking tag to the shop/confirmation page. 

Video/Screenshot link (optional): I attach a screenshot of how I'm thinking the code should look like.

<img width="922" alt="Screen Shot 2020-12-09 at 17 44 16" src="https://user-images.githubusercontent.com/71733271/101702342-46825380-3a46-11eb-8ffa-ee628a1d0c4c.png">

Support ticket number submitted via odoo.com/help (optional):
@JKE-be

**Comment by JKE-be** [comment]
Odoo 13 Is still using Analítics.js, so _ga and not gtag 

Else, yes... your code is ok

Xpath
    T-if
        <script>

**Comment by Uhub202** [comment]
Thank you for the response. Sorry for the ignorance, but what should I code in the expressions xpath and t-if?

So conversion tracking tag should be as follows:
            <script>
              ga('event', 'conversion', { 'send_to': 'AW-470801342/OFmACKSF4-wBEL63v-AB', 'transaction_id': '' });
            </script> 

Does it matter if its a GA4 account?

**Comment by JKE-be** [comment]
Here the doc, https://developers.google.com/analytics/devguides/collection/analyticsjs/events

xpath seems correct, if you want to add your script at the end of the <body>

t-if = python expression, so you can just remove it if you want to send each time the event, but you need to keep it e.g. if you want to send event only when you sold a specific product...

e.g. if only when you sold product with id 18
<t t-if="18 in order.order_line.product_id.ids">

But if you are just looking for ecommerce tracking, it is already implement in Odoo in standard.
https://github.com/odoo/odoo/blob/14.0/addons/website_sale/static/src/js/website_sale_tracking.js

Since this tracker is for bug, don't hesitate to ask help on our community forum: forum.odoo.com

KR
