### ISSUE TITLE
frontend_lang and session_id cookies use SameSite=None without Secure; they'll stop working soon

### ISSUE THREAD

**Issue by Yajo** [odoo/odoo#63226]
Impacted versions: all

Steps to reproduce:

1. Open Firefox.
1. Go to any odoo instance. It can be the runbot.
1. Check console.

Current behavior: A bunch of messages like: 

- *Cookie “session_id” will be soon rejected because it has the “SameSite” attribute set to “None” or an invalid value, without the “secure” attribute. To know more about the “SameSite” attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite*
- *Cookie “frontend_lang” will be soon rejected because it has the “SameSite” attribute set to “None” or an invalid value, without the “secure” attribute. To know more about the “SameSite” attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite*

Expected behavior: No warnings. Actually, if effectively in the future these cookies stop working, this could be a big problem...

Video/Screenshot link (optional):
![imagen](https://user-images.githubusercontent.com/973709/101898242-afcba900-3ba3-11eb-90e1-7aadc81b2ec7.png)

**Comment by celm1990** [comment]
Hi, I have problem with `cookie session_id` into a payment module(custom module for webpay) when return to odoo session is closed because cookie `session_id `is empty on this line https://github.com/odoo/odoo/blob/12.0/odoo/http.py#L1357

![image](https://user-images.githubusercontent.com/7775116/123373867-c9cf4680-d54b-11eb-9163-a1e64aafdd27.png)


My error happend only into Chrome, reading i see than on Google Chrome > 84 default value for SameSite=default=Lax(https://web.dev/samesite-cookies-explained/). 

![image](https://user-images.githubusercontent.com/7775116/123371614-b91cd180-d547-11eb-8e51-ec16abf22735.png)

If i disable flag working fine and session is not closed, but is not solution for customers on website, solution must be to odoo level maybe `set_cookie `(https://github.com/odoo/odoo/blob/12.0/odoo/http.py#L1434-L1435) or upgrade werkzeug V1.0.0+ ????

![image](https://user-images.githubusercontent.com/7775116/123371708-dfdb0800-d547-11eb-80e2-96aa7583d5d9.png)


I see werkzeug on V1.0.0 add support https://github.com/pallets/werkzeug/pull/1550 but odoo V12 use  0.11.15(https://github.com/odoo/odoo/blob/12.0/requirements.txt#L43).

Master and future V15 not upgrade werkzeug, any solution????

thans for advice

sorry for ping @odony @xmo-odoo @d-fence but somebody  helpme??

**Comment by celm1990** [comment]
UPDATE: temporary  i add `proxy_cookie_path / "/; secure; SameSite=none"; `to nginx and working fine, is ok this solution???

**Comment by pedrobaeza** [comment]
Duplicated of #71843

**Comment by odony** [comment]
> Hi, I have problem with `cookie session_id` into a payment module(custom module for webpay) when return to odoo session is closed because cookie `session_id `is empty on this line https://github.com/odoo/odoo/blob/12.0/odoo/http.py#L1357

That sounds fairly similar to what we fixed for `payment_sips` in #72267. There's a comment on that PR explaining how SameSite should work with Odoo and what we can do when some flow breaks because of it.

**Comment by celm1990** [comment]
> @celm1990 That sounds fairly similar to what we fixed for `payment_sips` in #72267. There's a comment on that PR explaining how SameSite should work with Odoo and what we can do when some flow breaks because of it.

Thanks @odony for your feedback ;)

**Comment by celm1990** [comment]
> @celm1990 That sounds fairly similar to what we fixed for `payment_sips` in #72267. There's a comment on that PR explaining how SameSite should work with Odoo and what we can do when some flow breaks because of it.

@odony I applied `save_session=False` on V12 and this working fine, but now on V15 is not working, any change into odoo core with sessions??
