### ISSUE TITLE
[Issue] product : chatter, attachment, activities is not the same on products, on database with group_product_variant = False

### ISSUE THREAD

**Issue by fmdl** [odoo/odoo#63275]
Impacted versions: All
- Create database (V14 for exemple)
- Install Sale, Purchase, Stock
- use database with `group_product_variant` = `False`
- All menu Product (in sale, purchase) open a `product.template`
- go to sale.order (or purchase.order, account.move, ...), open a line then open the product. You see a `product.product`

**It is a misunderstanding of all users**, that some times you open a `product.template`, and some times you open a `product.product`. If `group_product_variant` = `False`, you should always open a  `product.product`.

It is an issue, indeed chatter, attachments, activities are different between `product.template` and `product.product`.

Solution 1 : if `group_product_variant` = `False`, hide `product.template` menu, and show `product.product` menu.
Solution 2 : add an option to unify chatter, attachments, activities (can be also useful when `group_product_variant` = `True`)

@Yenthe666
@pedrobaeza 
@mart-e 
@fpodoo

**Comment by fmdl** [comment]
OPW #2416293

**Comment by extrememicro** [comment]
I just filled a support ticket about this. It's confusing for users using attachments/chatter with variants not enabled.

https://user-images.githubusercontent.com/372698/140175870-ebbd2809-163e-4142-ad16-d0b32d6b0852.mp4

If I create a product.template without variants, odoo internally creates a single product.product too. Odoo will replicate product.template information to product.product. For my point of view, chatter/attachments etc information need to be referenced there too. Or instead of that, not use product.template at all.

**Comment by PeterGilgen** [comment]
Why is this issue closed as completed?
Still the same issue with odoo16!
