### ISSUE TITLE
UTC time stamps in server log, disregarding of system time zone

### ISSUE THREAD

**Issue by onlyjob** [odoo/odoo#6350]
Odoo v8 ignores system time zone and log messages with UTC time stamps.
At very least this is inconvenient since every other daemon on system (e.g. Apache etc.) respect system time zone.

Please modify logger to respect system time zone and/or introduce configuration option to control logger time zone. Thanks.

**Comment by xmo-odoo** [comment]
sorry about that, wrong manipulation

**Comment by odony** [comment]
Hi, since version 6.1 Odoo exclusively deals with UTC timestamps on the server-side, in order to avoid timezone problems and allow moving the service and database on any system anywhere, regardless of system location and configuration.
Other programs have different purposes and needs, but we prefer to use consistent timestamps everywhere, in the database and in the logs too.
As a system administrator, you just have to be aware of this fact, it's really not a big deal.

We don't plan to change it, but we might add the TZ name in the logs (UTC), if that seems really useful. That would add several characters/bytes of redundant info on every log line, though.

**Comment by onlyjob** [comment]
@odony just make it configurable to let people have the choice please. ISO date with TZ in log may be nice but I want to be able to choose log time zone. I'm sure I'm not the first person who requested it. Besides change would be little and simple: one configuration option plus few lines of code to adjust logger. Should be easy enough to do...

**Comment by odony** [comment]
@onlyjob It's not really a question of being difficult to do or not. We just prefer not to add this, as a choice:

- It's definitely not a frequently asked feature (first time I remember seeing it, actually),
- It's more consistent with the rest of the TZ management in Odoo
- It avoids adding yet another configuration option that very few people will ever use (we already have too many, we need to remove some, not add more)
- Doing timezone conversions for each log line is really unnecessary... logging is already an expensive operation, let's avoid adding more work there

I hope you can understand this position...

**Comment by onlyjob** [comment]
> We just prefer not to add this, as a choice

I smell denial... ;)

> It's definitely not a frequently asked feature (first time I remember seeing it, actually),

 * https://bugs.launchpad.net/openobject-server/+bug/1257827
 * http://stackoverflow.com/questions/20382138/openerp-logs-are-in-utc-how-to-get-them-in-the-same-timezone-as-the-server

> I hope you can understand this position...

No I do not understand. You are just rationalising why not to do that and ignoring valid report of incorrect behaviour. I am very unhappy about such bug handling. :(
Please re-open.

**Comment by harkx** [comment]
I agree that having "wrong timezone" logs is annoying. It doesn't help debugging. (comparing 2 logfiles for example)

Imho, system logs and database are an entirely different thing.

Every other linux daemon (apache, nginx, name it..) uses the system time. That's why there's a system time setting. Too bad we won't be seeing this in Odoo.

Or could you point us to where we could change this ourselves?

**Comment by acidtv** [comment]
Just wanted to chime in here. 

Logging with UTC dates is very confusing for sysadmins, because basically every other daemon uses the configured timezone.

I understand you want to use UTC for internal timekeeping, but logs are not an internal system really. The other arguments for not wanting to do this aren't all that convincing either.

**Comment by kengonn** [comment]
I agree with onlyjob, harkx, and acidtv - Odoo should use system time instead of UTC for logging. Just to give you an example, when checking log files while troubleshooting issues, I look at both nginx and Odoo logs: nginx gives me my current time (e.g. 12:18 AM AEST because I'm in Australia), while Odoo gives me 14:18). This is really quite inconvenient, and confusing too (I was wondering why the times were different and whether I needed to change some setting in Odoo, before I Googled upon this issue).

**Comment by alex2grad** [comment]
I agree that logging has to be in system time instead of UTC.

**Comment by alex2grad** [comment]
small patch which use config param 'timezone' to log in system time

```
diff -ur orig/netsvc.py my/netsvc.py
--- orig/netsvc.py	2015-01-08 20:00:05.000000000 -0500
+++ my/netsvc.py	2015-10-09 15:24:45.395663337 -0400
@@ -26,6 +26,8 @@
 import release
 import sys
 import threading
+import pytz
+from datetime import datetime
 
 import psycopg2
 
@@ -112,6 +114,27 @@
 }
 
 class DBFormatter(logging.Formatter):
+    def converter(self, timestamp):
+	if tools.config['timezone']:
+    	    return datetime.fromtimestamp(timestamp,pytz.timezone(tools.config['timezone']))
+	else:
+    	    return datetime.fromtimestamp(timestamp)
+
+    def formatTime(self, record, datefmt=None):
+        dt = self.converter(record.created)
+        if datefmt:
+            s = dt.strftime(datefmt)
+        else:
+	    try:
+        	t = dt.strftime(self.default_time_format)
+	    except AttributeError:
+		t = dt.strftime("%Y-%m-%d %H:%M:%S")
+	    try:
+        	s = self.default_msec_format % (t, record.msecs)
+	    except AttributeError:
+        	s = "%s,%03d" % (t, record.msecs)
+        return s
+
     def format(self, record):
         record.pid = os.getpid()
         record.dbname = getattr(threading.currentThread(), 'dbname', '?')

```

**Comment by odony** [comment]
Actually there's a simple workaround for those who are annoyed by this: start Odoo with `--syslog`. Then configure your logging facilities, log files and log rotations via syslog. You'll get the timestamps in the system timezone without requiring any patch.

**Comment by spadae22** [comment]
You learn something new everyday. config file: syslog = True.

**Comment by arigirlforever** [comment]
@odony How I do that?
