### ISSUE TITLE
[14.0 ] Submit sitemap to Google - no Domain defined

### ISSUE THREAD

**Issue by fizcris** [odoo/odoo#63602]
Impacted versions: 14.0

Steps to reproduce: Trigger Submit sitemap to Google

Current behavior: User error : You haven't defined your domain
System parameter web.base.url  = https://test.com
There is a sitemap-1.xml file in the database but if its deleted it´s not possible to be regenerated through the Submit sitemap to Google action.

Expected behavior: No User error

**Comment by pedrobaeza** [comment]
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - click on the blue door icon of the version row - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by fizcris** [comment]
@pedrobaeza Many thanks for the thorough reply.

Unfortunatelly my technical knowledge is not enough to track the issue but basically the **Domain form** under Settings - website - website i**s not showing on my odoo instance**. I have just pulled the latest image from dockerhub and it is not present neither so I must be a **configuration issue present in my db.**

I vae checked the odoo community 14.0 runbot instances and none of them are affected. 

I finally updated the record mynually in the db with SQL commands and it seems to have made the trick.

Cheers.

**Comment by maartenschalekamp** [comment]
@pedrobaeza I have the same issue. I have checked on runbot and noticed its the same error there. Under Settings -> Website and and at the bottom `Submit sitemap to Google` it will then show the message `You haven't defined your domain`

![image](https://user-images.githubusercontent.com/28432355/103541484-29556f00-4ea4-11eb-8ccb-3a3e766f3af3.png)

There is not much details on this functionality.

**Comment by slv177** [comment]
Me too, I have the same issue.
Odoo 14, no custom modules, only web, CRM, email marketing and project.
In the sitemap all links poitns to 127.0.0.1. (web base URL in settings points to real URL of web site).
I install another server with the same procedure, and there is ok.

**Comment by jayadigital** [comment]
I have encountered the same issue - web.base.url points to ****.com with web.base.url.freeze set to True.
Meanwhile Odoo doesn't submit sitemap with the same error and shows localhost in shared messages to WhatsUp. 

Odoo 14.0-20201130
