### ISSUE TITLE
[14.0] Chatter Dropdown items scrolling also scrolling the document page. 

### ISSUE THREAD

**Issue by dipsshah42** [odoo/odoo#63797]
Impacted versions: [14.0]

Steps to reproduce:
- Go to chatter of any document like Sales order, Purchase order etc.
- Click on **Log note** > And start typing @ and scroll (using Arrow key e.g UP, DOWN) when it display list of users.
- So Use Arrow key to scroll between the users displayed in drop down followed by @ sign

Current behavior:
- its also scrolling the document page when scrolling the list of user using Key. and interestingly it doing for first 3 and last 3 items.

Expected behavior:
- it should not scroll the document page. only it should scroll among list of items same as we see in any dropdown of odoo.
  same as working properly in discuss app . you can find it in attached video.

Video/Screenshot link (optional):
[Video link](https://www.awesomescreenshot.com/video/2191760?key=73f825a0b04afe84ce119746eda45521)

![image](https://user-images.githubusercontent.com/35560490/103146902-c5c99400-4775-11eb-899f-d71192026723.png)

Support ticket number submitted via odoo.com/help (optional):

**Comment by pedrobaeza** [comment]
I have been checking in runbot, and that happens when chatter doesn't fit in the screen, and it's done on purpose for always showing the proper element on the dropdown, so it's not bad that this happens. If you continue pressing down arrow you will see that the scroll finishes when the elements ensure that they are seen.

Closing thus as no bug, but expected behavior.
