### ISSUE TITLE
[14.0] website: steps block removed background line when changing colour

### ISSUE THREAD

**Issue by Yenthe666** [odoo/odoo#63814]
Impacted versions: 14.0

Steps to reproduce:
1. Login to the latest runbot 14.0 with the admin user
2. Open the website and click on edit
3. Add the "Steps" building block
4. Change the colour of one of the blocks.
See the video:

https://user-images.githubusercontent.com/6352350/103205359-a78ca100-48f9-11eb-8cb6-edc4b1d5ea8e.mp4

Current behavior: The background line is now completely gone & hidden and there is no way for you to get it back visible

Expected behavior: The line colour changes or is changeable through the UI.

OPW `2423785`

**Comment by Yenthe666** [comment]
@sbuhl another one. I made a separate ticket/OPW for this one as this issue is a bit different :)

**Comment by sbuhl** [comment]
Hello @Yenthe666 
Thank you. In this case, more an imp than a fix. We'll work on it.

Cheers

**Comment by Yenthe666** [comment]
Erm, it removes the background line so that's literally broken 😆

**Comment by sdegueldre** [comment]
@sbuhl definitely something funky going on here. The reason it removes the background line is because a `<span>` gets removed from the DOM (which I guess you could say is intended and would be an IMP, though it's a stretch), but the removed `<span>` does not come back if you just hover a colour to preview and then move your cursor out of the colour picker without clicking anything, and the background colour of the icon also gets set to its default value, rather than resetting to its value before the preview correctly. So there is at least the preview to fix, and it's likely that we can find a fix that does both.

@Yenthe666 thanks for your report. I'll take a closer look, unfortunately my intuition tells me that it has something to do with the way our HTML editor sanitizes the DOM (eg fusing 2 empty nested nodes) and this code is something that we prefer not to touch in stable if we can avoid it because it can have unforeseen rippling effects in other parts of the editor that may rely on those behaviours. I just hope I can find a way to fix this without breaking other things, which wouldn't help at all.

**Comment by Yenthe666** [comment]
Fixed in https://github.com/odoo/odoo/commit/9dd7e037239ff7b124d36f176fe4c66091e2cc4e
