### ISSUE TITLE
[13.0] After Latest v13 code pull not able to do a base module upgrade. Whole instance stopped working.

### ISSUE THREAD

**Issue by bhaveshselarka** [odoo/odoo#63962]
![image](https://user-images.githubusercontent.com/7733043/103440374-e65c8700-4c6a-11eb-8e5c-e8dd4ff26524.png)

**Comment by bhaveshselarka** [comment]
@sswapnesh @pedrobaeza @Yenthe666 have you guys faced any such issues near days ? 
Thanks.

**Comment by bhaveshselarka** [comment]
I have found a commit : https://github.com/odoo/odoo/commit/0b7ba571431d694dea7db3ba1da4c7e86d1013e5

which causes a issue after this.

**Comment by bhaveshselarka** [comment]
ping @abz-odoo

**Comment by bhaveshselarka** [comment]
ping @abz-odoo

**Comment by abz-odoo** [comment]
@bhaveshselarka Have you changed the view? Cause normally unless you haven't removed `<script id="web.layout.odooscript" type="text/javascript">` it should work

**Comment by bhaveshselarka** [comment]
thanks for your response, no i haven't change the view. Even on that server I have 5 different running instances all having a same problem after latest pull and upgrade the "base" module.

**Comment by nle-odoo** [comment]
Hi @bhaveshselarka 

If an error happens, it should be a customization that modify web.layout and for example replace it entirely or replace the `script` element.

It should be fixed by this change: https://github.com/odoo/odoo/pull/64062

To test the fix before it is merged, you could edit the view (by going to http://yourinstance/web?debug=1 => Settings => Technical | Views) web.frontend_layout (named "Frontend Layout") and replace:

```xml
<xpath expr="//head/script[@id='web.layout.odooscript']" position="after">
```

by:

```xml
<xpath expr="//head/script[@id='web.layout.odooscript'] | //head/script[last()]" position="after">
```

**Comment by bhaveshselarka** [comment]
Hello @nle-odoo @abz-odoo 

Thanks for fix !! Its resolved my issue, so I am closing this ticket.

Again thanks a lot for your efforts.
