### ISSUE TITLE
view choosen on page refresh

### ISSUE THREAD

**Issue by 4fuss** [odoo/odoo#64]
I have two form views for model account.analytic.account - the *original* (id="view_account_analytic_account_form") and *simplified* (id="portal_agreement_form_view") with low priority = 1000 used for Portal users. 
The *simplified* form is loaded from another form m2o field defined as: 
   <pre>field name="user_agreement" context="{'form_view_ref' : helpdesk_currenda.portal_agreement_form_view', 'tree_view_ref' : 'helpdesk_currenda.portal_agreement_form_view'}"</pre>
When click on m2o field *simplified* form is loaded. But when I refresh the page in the browser system gets the original view, which is not desired. Is there a way to avoid this behaviour?

**Comment by yaniaular** [comment]
Hello, this problem is affecting me.

1. I try with 'form_view_ref' like made @4fuss 
2. I used the method get_formview_id

... and the problem persists. 

By example:

When i click in the invoice_id many2one field from invoice line form, the link is like this: http://localhost:10000/web/?debug=#id=7&view_type=form&model=account.invoice

This link is not specifying the action, although it go to the action of form_view_ref or the returned by the get_formview_id method. Therefore, when i click f5, go to the view with more high priority, because the action is not specified in the link.

Now,

When go to invoice from a menuitem, and i click F5, this problem is not happen, because the link is correct with the action specified in the menuitem.

http://localhost:10000/web/?debug=#id=7&view_type=form&model=account.invoice&menu_id=522&action=684

**Comment by Yenthe666** [comment]
Dear @4fuss,

Thank you for reporting this issue!
At this point Odoo 6.0, 6.1 and 7.0 are no longer supported for bugsfixes anymore, which means we will no longer handle these bugs.
If you still face this issue on Odoo 8, 9 or 10 we'd like to ask you to create a new issue on how to reproduce this.
Our apologies.

Regards,
Yenthe
