### ISSUE TITLE
[14] MRP creates multiple MO for same Product and date

### ISSUE THREAD

**Issue by assenovg** [odoo/odoo#64124]
Impacted versions: 14

Steps to reproduce:
Product A is manufactured internally
Product B is manufactured internally from product A (component)
Product C is manufactured internally from product A (component)

Customer1 orders:
5 PC of product B in Sales Order (SO) 1
10 PC of product C in SO 1

Customer 2 orders:
14 PC of product B in SO 2
4 PC of product C in SO 2

Current behavior:
Run Scheduler and get:
1 Manufacturing order (MO) for 19PC of product B (SO1+SO2) - correct
1 MO for 14 PC of product C (SO1+SO2) - correct

1 MO for 19 PC of product A - incorrect
1 MO for 14 PC of product A - incorrect

Expected behavior:
1 MO for 33 PC of product A - correct

The above scenario was reproduced on Runbot version 14 yesterday

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by ryv-odoo** [comment]
It is a side effect of the new way of trigger the replenishment of Reordering Rule (method `_trigger_scheduler`). It is now trigger directly when there is a need (And because the MO isn't merge, it will create 2 MO). 
If you want to avoid this side effect and manage the creation by the "Old School" scheduler, you can add a System Parameters with key=`stock.no_auto_scheduler` and value="True" (see odoo/odoo#68283).
