### ISSUE TITLE
Redundant minified `bootstrap.min.js`

### ISSUE THREAD

**Issue by onlyjob** [odoo/odoo#6425]
Please remove unused redundant minified `addons/web/static/lib/bootstrap/js/bootstrap.min.js` which is safe to remove as the following files already refer to uncompressed `bootstrap.js`:
- `addons/web/views/database_manager.html`
- `addons/web/views/webclient_templates.xml`

Thanks.

**Comment by Yenthe666** [comment]
@JKE-be is there a reason why we have both minified and non minified? https://github.com/odoo/odoo/tree/8.0/addons/web/static/lib/bootstrap/js

**Comment by online-odoo** [comment]
@Yenthe666 

Yes, by default we don't use minified version because our Qweb rendering does this job.

But in some case (eg. database manager during the first launch) we don't have Qweb available, so we load minified bootstrap directly.

@onlyjob 
So no, we will not remove it, but since it is not loaded into the assets, that have no impact on your website...

**Comment by JKE-be** [comment]
@Yenthe666

Yes, by default we don't use minified version because our Qweb rendering does this job.

But in some case (eg. database manager during the first launch) we don't have Qweb available, so we load minified bootstrap directly.

@onlyjob
So no, we will not remove it, but since it is not loaded into the assets, that have no impact on your website...
