### ISSUE TITLE
Unreconciliation massive of account entries has a bug

### ISSUE THREAD

**Issue by gustavoecordero** [odoo/odoo#6464]
When you want to unreconcile many account entries (from tree view), and each entry has a different reconciliation, all the counterparts will be reconcilied with the same new reconciliation.

For example:

The reconciliation A100 involves the followings amls (account_move_line):

aml id = 1      debit 100    credit 0        [A100]
aml id = 2      debit 0        credit 100    [A100]

reconciliation A101 involves the follow amls:

aml id = 3      debit 200    credit 0                [A101]
aml id = 4      debit 0        credit 200            [A101]

if wants unreconcile the amls (id) 2 and 4, at the same time, the system creates a new reconciliation bettween the conterparts id (1 and 3) and this is wrong.

New reconcilation A200

aml id = 1      debit 100    credit 0           [A200]
aml id = 3      debit 200    credit 0           [A200]

The mistake is in _remove_move_reconcile method of the objecto account_move_line in account/account_move_line.py file

**Comment by Yenthe666** [comment]
Hi @gustavoecordero ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.
P.S: Always feel free to make PR's when you know exactly where the issue is.

Regards,
Yenthe

**Comment by tejastank** [comment]
Yes. in odoo 11.0 bug their, if website footer disable, complete website down, raise big bug .
Old clients migrated in #ERPNEXT, but new users also face till bugs in odoo.

Hope this time don't take 2/3 years to fix bug :)

**Comment by Yenthe666** [comment]
@tejastank that bug has been fixed and handled a while ago, unless you've found a new way to reproduce it. Please do update your codebase. If you can still reproduce it on a runbot or your updated instance then do create a new bug report explaining how you did it.
