### ISSUE TITLE
Default value of related field are not correct (due to this commit https://github.com/odoo/odoo/commit/2ccc735253405b03927e2b08eab57427e65e4050 )

### ISSUE THREAD

**Issue by mourad-ehm** [odoo/odoo#64672]
Impacted versions: 14.0 due to this commit https://github.com/odoo/odoo/commit/2ccc735253405b03927e2b08eab57427e65e4050 

Steps to reproduce:
Create a related field  on sale order (related to company for example brand_use_level or any other configuration field). 
Create new sale order.

remark : 
The same error for  company dependent configuration values (in res.config.setting). They are not displayed correctly even if values are stored correctly in res.company object. 

Current behavior:
Default value of related field is not equal to value stored in the res_company. 

Expected behavior:
without this commit, 
the default value is equal to the value stored in company.

**Comment by rco-odoo** [comment]
@mourad-ehm we are struggling to reproduce your issue.
Also, the description you gave looks confusing.

The *default value* of a field is a value set *explicitly* for the field to be its *initial value* in the form.  It can be specified on the field itself (with the parameter `default=...`), in the context (with the key `"default_`*fieldname*`"`) or in settings (in model `ir.default`).  If you set a default value on a computed field, the initial value of the field will be its default value instead of its computed value.  This behavior is the same as the creation of a record by invoking `create()`.  This is exactly what the commit you pointed out ensures.

I tried what you proposed: I added a custom related field on sales orders that is defined as `company_id.currency_id`.  The field is stored and does not have a default value in its definition.  When you open a new sales order's form, the company field is set to its default value (the user's current company), and the related field shows the currency on the corresponding company.  That's what you expected, right?

Now, if you add a default value for that field, opening the form view shows that default value instead of computing the field.  The field keeps that value until you modify the field itself or one of its dependencies.  Things are designed to be that way.

**Comment by Elkasitu** [comment]
Also, could you try to reproduce your issue on the latest v14 [runbot](http://runbot.odoo.com)? Thanks

**Comment by mourad-ehm** [comment]
Thanks for your response. In fact we have make a quick migration of module brand and the related field was defined like this (selection defined) :
`    brand_use_level = fields.Selection(
        string="Brand Use Level",
        selection=BRAND_USE_LEVEL_SELECTION,
        default=BRAND_USE_LEVEL_NO_USE_LEVEL,
        related="company_id.brand_use_level",
        readonly=False,
    )`
the behaviour was strange and set value is not saved correctly.
When we define field without selection redefinition it work correctly.  
`
    brand_use_level = fields.Selection(
        string="Brand Use Level",
        related="company_id.brand_use_level",
        readonly=False,
    )`
