### ISSUE TITLE
[14] group order to invoice payment terms

### ISSUE THREAD

**Issue by eguane** [odoo/odoo#64760]
Impacted versions:
14 latest on github
Steps to reproduce:
Group two order for one invoice 
Current behavior:
invoice payment term not applied
Expected behavior:
payment term applied
Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by pedrobaeza** [comment]
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - click on the blue door icon of the version row - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by eguane** [comment]
Hi tested again but without the same issue, rgds
