### ISSUE TITLE
Sale Amazon update MWS code

### ISSUE THREAD

**Issue by william-andre** [odoo/odoo#64837]
**Impacted versions:** 
All, but to do in master

**Steps to reproduce:**
https://github.com/odoo/enterprise/tree/14.0/sale_amazon/lib/mws
is not updated anymore and not in sync with https://github.com/python-amazon-mws/python-amazon-mws 

**Current behavior:**
Some region are not recognized (13 regions in Odoo and 20 in MWS)

**Expected behavior:**
All available regions are available in Odoo too

**Video/Screenshot link (optional):**

**Support ticket number submitted via odoo.com/help (optional):**

**Comment by AntoineVDV** [comment]
The lib is not updated **yet** because we don't miss any feature atm.
We only support marketplaces for which we have a registered Amazon developer account. This is a limitation due to how authentication flows work in Amazon MWS and, currently, we are not willing to expand our support to other marketplaces (pay subscriptions fees for more accounts).
Nevertheless, we're looking forward to the SP-API that should replace the horribly broken MWS API. Maybe that this one will allow more flexibility.

**Comment by AntoineVDV** [comment]
Closed with https://github.com/odoo/enterprise/pull/18597
