### ISSUE TITLE
[8.0] Pricelist default price evaluation method

### ISSUE THREAD

**Issue by francoislawarree** [odoo/odoo#6500]
Hello,

I'm working on the definition of Pricelists (PL) mechanism that compute the products' prices based on their discounts applied by the suppliers and also with their margins

Sales price = (Brut price \* discount) \* margin

To implement it, i've grouped all the products concerned by a discount or a margin into a pricelist (see my illustration below).

![pricelist_screen](https://cloud.githubusercontent.com/assets/11072956/7372227/f44eed08-edc5-11e4-8bc3-21b2dc4c201e.png)

My problem occurs during the computation of a product's price for the rules defined in my 2 main pricelists. These rules don't specify any specific product or product's category and their sequences are the same. Then, during the computation of a product's price, only the first rule that match with the product will be considered.

In my example it means that only the rules : 
"x 0.8 <- PLA - 20%" (from the ).
"x 1.5 <- Margin 1.5" will be evaluated (from the ).

The others will be omitted
"x 0.6 <- PLA - 40%" (from the ).
"x 2.0 <- Margin 2.0" will be evaluated  (from the ).

I find that the method should be adapted to evaluate all the rules that match with the product until the price returned is different of "False".

Thanks in advance.

François Lawarrée

**Comment by francoislawarree** [comment]
** Computed price ignored when multiple matching rules are defined **

Let assume that all the products have a public price defined at 1€

1) Create 2 new sales pricelists (PL) where each of them represent a set of products

PL_A
Product1
Product2
Product3
PL_B
Product4
Product5
Product6
Remark : the scope of each rule is defined for one product

2) Create another pricelist where the rules apply a computation based on the 2 others PL (PL_A & PL_B):

PL_Main
2 * (other PL: PL_A)
4 * (other PL: PL_B)
Remark : the scope of the 2 rules are defined for all the products


3) Create a new SO (Sale Order) and choose the “PL_Main” pricelist, the result will be : 
	- Product1 : 2€
	- Product2 : 2€
	- Product3 : 2€
	- Product4 : 0€ (instead of 4€)
	- Product5 : 0€ (instead of 4€)
	- Product6 : 0€ (instead of 4€)

The prices of the products 4,5,6 are not well computed due to the PL’s method that will match with the first rule and will end the process whatever if the price returned is “False”.

=> My request is to continue the evaluation of the rules while the price returned is “False”.

**Comment by odony** [comment]
Hi,

As you mention in your last comment, this is indeed a change request, not a bug. And if I recall correctly the current behavior has been there forever, so it should not be specific to Odoo 8.0.

The current behavior of Odoo pricelist rules is described [in the documentation](https://doc.odoo.com/book/6/6_16_Sales/6_16_Sales_pricing/#calculation-rules) and cannot be modified in the middle of a stable series. Whenever a rule matches, the pricelist calculation stops there, and never resumes to the following rules. So if you have a "match anything" rule it will always finish the pricelist calculation, and if no rule ever matches, the price is undefined (->0). That's why it is recommended to have a "match anything" rule at the end of every pricelist.

Now if you've already considered using product categories to organize your pricelists and this approach was not suitable, then I suggest you redesign your pricelists and chain them "in series" instead of chaining them "in parallel". For instance, instead of having:
```
    PL_Main -> 2x PL_A
           `-> 4x PL_B
```
you could have:
```
    PL_Main -> 2x PL_A -> 2x PL_B and so on... (with PL_B the last rule in PL_A)
```

This approach uses the current Odoo paradigm, and there is no limit to the chaining of the rules this way. It's also not slower than what you were trying to do, because in any case you will need to test all rules of PL_A before you can try PL_B.

**Comment by Yenthe666** [comment]
@odony what is the final call for this one? I'm not sure, I believe we can handle a lot of cases in the newer versions.

**Comment by pedrobaeza** [comment]
Any news about this, @odony. See also #21845 for something similar.
