### ISSUE TITLE
Email_template: Email does not send by outgoing mail server selected.

### ISSUE THREAD

**Issue by pvanthony** [odoo/odoo#6554]
On Odoo V8, the email_template does not use the outgoing mail server set in the template.

Seems that this bug was reported for V7 at the following link.
https://bugs.launchpad.net/openobject-addons/+bug/1171507

Need help to confirm if this is really a bug in Odoo V8.  So that I can rule out that it was my setting that has caused the problem.

**Comment by tompickering** [comment]
I'm also experiencing the same problem (albeit on V9) when posting messages on a mail thread via the composition wizard; the outgoing mail server set on the selected mail template is not used.

Steps to reproduce on V9:
* Create two outgoing mail servers with different priority.
* Create a template which explicitly specifies the lower-priority (higher priority value) mail server.
** (My template applies to 'Partner', although I don't believe this is significant).
* Click 'New Message' from a partner form view and open the composition wizard.
* Select the template created previously.
* Send the message.

Expected result: Outgoing mail is sent via the (lower-priority) server set on the template.
Actual result: Outgoing mail is sent via the high-priority server.

The outgoing server is selected properly if I access the wizard from the 'Action' drop-down menu and apply the same template. Another difference here is that the mail_server_id field is set correctly on the mail_message record in this scenario, whereas it is blank on the record created following the process described above.

I believe the difference is due to the wizard's composition_mode, which affects the fields returned by get_mail_values() in addons/mail/wizard/mail_compose_message.py. 'mail_server_id' is specified in the return value when accessing the composition wizard from the 'Action' menu, but not from the message thread.

**Comment by nim-odoo** [comment]
It doesn't seem to occur in V8 anymore, although the issue appears in V9
