### ISSUE TITLE
[14.0] account.move -> action_post -> "TypeError: cannot marshal <class 'odoo.api.account.move'> objects"

### ISSUE THREAD

**Issue by Prometee** [odoo/odoo#65706]
**Impacted versions:** 14.0

**Steps to reproduce:** Create an `account.move` (an invoice) with the XML-RPC API and then make a new http request to call the action named `action_post`.

**Current behavior:** An error is return with an http response code 200 :

```
Traceback (most recent call last):
  File "/usr/lib/python3.8/xmlrpc/client.py", line 509, in __dump
    f = self.dispatch[type(value)]
KeyError: <class 'odoo.api.account.move'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/addons/base/controllers/rpc.py", line 69, in xmlrpc_2
    response = self._xmlrpc(service)
  File "/home/odoo/src/odoo/odoo/addons/base/controllers/rpc.py", line 50, in _xmlrpc
    return dumps((result,), methodresponse=1, allow_none=False)
  File "/usr/lib/python3.8/xmlrpc/client.py", line 968, in dumps
    data = m.dumps(params)
  File "/usr/lib/python3.8/xmlrpc/client.py", line 501, in dumps
    dump(v, write)
  File "/usr/lib/python3.8/xmlrpc/client.py", line 513, in __dump
    raise TypeError("cannot marshal %s objects" % type(value))
TypeError: cannot marshal <class 'odoo.api.account.move'> objects
```

**Expected behavior:** a result with an ok message should be at least returned instead of an error.

**Comment by pedrobaeza** [comment]
@xmo-odoo is this a problem in the XML-RPC layer or business logic?

**Comment by xmo-odoo** [comment]
@pedrobaeza that looks like a business logic issue: AFAIK we still don't support recordset output at the RPC layer, but 82dc0cb7b91ae59beae7e1c865b670afc5958b31 modified post/action_post to return a recordset (formerly the constant `True`).

This may have been missed because the json serialisation (unfortunately) falls back on stringifying everything, so this would return `str(recordset)` instead of blowing up. Not that it ever makes sense to return a recordset (or a list of ids) from an action method: if they return something other than a simple constant, it should be the next action in the sequence. I'd guess the web client doesn't blow up because it ignores all non-object results.

`action_post` should return a constant `False`, or an explicit `ir.actions.act_window_close`.

**Comment by pedrobaeza** [comment]
Thanks for the explanation. @william-andre can you check this and see if that recordset return may be changed?
