### ISSUE TITLE
Version 8.0 computed fields non stored will never be created in ir.model.field table

### ISSUE THREAD

**Issue by nbessi** [odoo/odoo#6625]
This is mainly due to two behaviors:
- the `to_column` function of the Field class will not create a column instance if a function field is not stored
- the `_field_create` function of model is based on `_columns` property instead of `_fields` property

By doing so you have an incoherence between old and new API behavior and end user will not see the field in the UI.

Regards

Nicolas

**Comment by lmignon** [comment]
@nbessi Take a lokk at https://github.com/odoo/odoo/pull/5618

**Comment by Yenthe666** [comment]
Hi @nbessi,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.
P.S: Am I wrong that this is fixed in https://github.com/odoo/odoo/commit/4a5e2fe99ea2f7f7f2f9be9e591211c86e191cc8 ?

Regards,
Yenthe
