### ISSUE TITLE
[Product Variant] Traceback on graph view

### ISSUE THREAD

**Issue by dsu-odoo** [odoo/odoo#6638]
Go to product variant >> Open any product >> from more button click on product margin and click on button open margin then from right top corner click on graph view, see here: https://goo.gl/N4w0Ak
in saas-6

**Comment by mart-e** [comment]
@ged-odoo I think it's due to the refactoring of graph view. Somehow we got the non-stored `turnover` field that got into the [group_by attribute](https://github.com/odoo/odoo/blob/4a81e8aba13f3a306e51b0414d89c64d3ae03ba6/addons/web/static/src/js/view_graph.js#L164) but not in 8.0

**Comment by ged-odoo** [comment]
This is actually due to the fact that graph view does not support (non stored) computed fields (and never did).  In this case, the graph view is defined with the "turnover" field, which is not stored.

So, a possible fix is to remove the field from the graph view.  Another fix is to make this field stored.  But this is more a functional decision.  I'll let jco decide.

**Comment by ged-odoo** [comment]
i should have mentioned @jco-odoo

**Comment by mart-e** [comment]
Ok I agree but the graph view has not changed since in a few years so it was ignored before somehow

**Comment by ged-odoo** [comment]
ok, i just had a look in saas3.  It does not crash (so, that's good), but it did not work either.  The turnover field was not returned and was not used by the graph view.

Agreed that the javascript should not crash, I'll fix that part, and possibly display a notification.
