### ISSUE TITLE
Forums comments are 'destroyed' when they contain code and/or specific characters

### ISSUE THREAD

**Issue by Yenthe666** [odoo/odoo#6656]
**Forum comments are destroyed when containing specific characters and/or code**

Impacted versions:
- 8.0 and above (up to latest runbot)

Steps to reproduce:
1. create a new forum topic
2. Click on comment and add something which contains a <, >, ... or XML code
   Some examples that will be destroyed when posted:

```
Let me try something with a < this will not work as a comment.
<t t-esc="name"/>
<t t-if="o.name == 'Yes'">
```
1. Post them.

Current behavior:
- When posting one of those comments the text after a specific character or code will be destroyed.
  - When using something with t-if you will get a strange block
    <img src="http://i.imgur.com/nONcyCm.png" alt="Incorrect messages"/>

Expected behavior:
- The comment is just built and posted, if it has to without the specific sign or encapsulated code.

**Comment by lukebranch** [comment]
i've had this issue on the forums in help.odoo.com as well. Perhaps Odoo could come up with a markup like <code></code> or something similar to allow for proper formatting of code in the comments. I think the <code> tags would be very useful, as it's often necessary to add code in the comments rather than/in addition to the answer.

Line breaks do not work as well, so they need to be added manually with a <br/>. It would be great if this wasn't necessary.

**Comment by Yenthe666** [comment]
This issue has been fixed in the meantime, in every Odoo version.
