### ISSUE TITLE
The salesperson can’t check his order after reading the forecast report

### ISSUE THREAD

**Issue by ljsrzc007** [odoo/odoo#66587]
Impacted versions:14
Community Edition 
Steps to reproduce:
A company, A warehouse and B warehouse, salesperson (only can see his own documents). his default warehouse is B warehouse. There is a product C, which is out of stock. The salesperson placed an order for the customer, including product C, he clicked the forecast button on the quotation sheet, and checked the balance of warehouses A and B. There was an order from someone else in the forecast report of warehouse A. He clicked, Of course, it won't open, and an error pops up. Then he set the quotation to be shipped from warehouse A. Confirm as an order. Then he couldn't open this order, the prompt is: 

Current behavior: He can’t view the order just generated.

Expected behavior:He deserves to see his order.

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by pedrobaeza** [comment]
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - click on the blue door icon of the version row - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by ljsrzc007** [comment]
Yes, I used the latest runbot, the problem disappeared, thank you very much for your guidance.
