### ISSUE TITLE
[8.0] Can't change project's uom on company

### ISSUE THREAD

**Issue by sylvain-garancher** [odoo/odoo#6659]
The project's uom can be changed on the company only if we work with the "english" language.

This is caused by a non translated domain in the project module :
https://github.com/odoo/odoo/blob/8.0/addons/project/project_view.xml#L753

I didn't check, but this issue seems to also appear here :
https://github.com/odoo/odoo/blob/8.0/addons/project/res_config_view.xml#L58
https://github.com/odoo/odoo/blob/8.0/addons/sale/res_config_view.xml#L29
https://github.com/odoo/odoo/blob/8.0/addons/sale_stock/res_config_view.xml#L61

**Comment by Yenthe666** [comment]
Hi @sylvain-garancher ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.
P.S: Don't hesitate to create PR's when you know where the problem is (as you knew with this report).

Regards,
Yenthe
