### ISSUE TITLE
[8.0][account] Account Analytic Line Creation Fun

### ISSUE THREAD

**Issue by wtaferner** [odoo/odoo#6675]
## Impacted versions:

8.0 and above
## Steps to reproduce:
- Add a logger to create of account.analytic.line (to see the values passing)
- Create an invoice by adding an analytic account to at least one line
- Validate the invoice
## Current behavior:
- Each invoice line creates one analytic line BUT does this by iterating depending on the modules installed 4 times (based on create_analytic_lines > https://github.com/odoo/odoo/search?q=create_analytic_lines&type=Code) and actually unlink the predecessors on the fly
## Expected behavior:
- Each invoice line should create exactly one analytic line and should not unlink for example the created records of the initial dictionary values of account.invoice (https://github.com/odoo/odoo/blob/8.0/addons/account/account_invoice.py#L660).

This is especially not nice in case you try to inherit to add extra information to the account analytic line as only standard information might end up in the database.

**Comment by beledouxdenis** [comment]
Hello Wolfgang, 

After analysis, it looks like the fact `create_analytic_lines` is called several times is not due to the several modules installed and the several overrides (as you mention using the search https://github.com/odoo/odoo/search?q=create_analytic_lines&type=Code),  but from the fact the `validate` of the model `account.move` is called several times, and this `validate` method calls each time the `create_analytic_lines` method. 

The problem is therefore the fact `validate` of the model `account.move` is called several times. Sadly, this is a critical spot, and we cannot take the risks to change the number of calls to such a tricky method in such a tricky model within a stable release, especially for a non-blocking bug, for a override easiness. 

In addition, this is possible that the values of the analytic lines changed between each call to the validate method.

Hopefully, this will be solved in master, with the refactoring of the account module. I forwarded this to the team in charge to make sure to handle this case.

I hope you will understand.

Regards,

**Comment by wtaferner** [comment]
Hi Denis,
I have already overridden it in my own fork as I knew that this one is not easy to resolve and might have unforeseen side-effects for others (I did not stumble across any by now myself). 
I guess my hints were enough to reproduce the issue and see it clearly. Whether it is triggered by validate or by inherited functions calling super is not important as it is a bad behavior to delete already existing records from the same transaction anyway ;-)

I highly appreciate that this will be fixed in master and as long nobody else does having issues with extending analytic lines I understand that this won't be fixed in stable.

Regards,
Wolfgang

**Comment by whulshof** [comment]
This problem also exists for 7.0 and makes life difficult for those who want to be able to confirm an invoice and therefor do have to be able to unlink Analytic Lines, but do not want to be able to delete the Analytic Lines in the Analytic Lines Tree. Is there any work around for these tragic souls?
