### ISSUE TITLE
Valid Australian VAT is rejected

### ISSUE THREAD

**Issue by matyee** [odoo/odoo#67001]
Impacted versions: v14

When I try to save a partner company with country Australia and VAT 51 824 753 556 I got the error 

```
The VAT number [51 824 753 556] for partner [Sierraforce] does not seem to be valid. 
Note: the expected format is 83 914 571 673
```

The VAT I am trying is valid according to [https://abr.business.gov.au/Help/AbnFormat](https://abr.business.gov.au/Help/AbnFormat) The VAT should be accepted since it is valid. Tried the expected one in the error message, that is rejected too.

**Comment by pedrobaeza** [comment]
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - click on the blue door icon of the version row - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by matyee** [comment]
It works in runbot infrastructure. I am using the Ubuntu odoo package. There is a version difference, Ubuntu package uses version `Odoo 14.0-20201218 (Community Edition)`. Probably there is a problem with the packaging. I checked the code and I believe that an external library is used for AU VAT validation from `stdnum`. I am going to investigate further.

Thanks.

**Comment by Yenthe666** [comment]
Yes, update your packages for stdnum & your Odoo :) Various VAT fixes have been made in the last month

**Comment by matyee** [comment]
To give a solution to others who are going to find the issue later, this is what solved the problem:

I am using `ubuntu 20.04` and the only available package of `python3-stdnum` is version `1.13`. After updating to the latest version of `stdnum` with `pip3` which is at the moment `1.16` the AU VAT validation works well.
