### ISSUE TITLE
POS Editing Customer Error

### ISSUE THREAD

**Issue by Darakjian** [odoo/odoo#67026]
Impacted versions:
14.0
Steps to reproduce:

- Navigate to http://demo.odoo.com/
- open up the point of sale session
- pick a customer and edit anything other than his name and save.
Current behavior:
- Error Pop-up (A Customer Name Is Required)
Expected behavior:
- Should save the modifications.
Video/Screenshot link (optional):
https://drive.google.com/file/d/1ToYD-8EmcniTm-zWQfye2hO-GAZBKWAA/view
Support ticket number submitted via odoo.com/help (optional):

**Comment by pedrobaeza** [comment]
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - click on the blue door icon of the version row - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by Darakjian** [comment]
Hi, Thanks for your response.
It seems it's ok In runbot and I believe the demo.odoo.com code may be outdated, anyways I redownloaded the code and it works now.

thanks a lot for your help
