### ISSUE TITLE
[8.0] Incorrect gantt chart for Work Orders

### ISSUE THREAD

**Issue by jbeficent** [odoo/odoo#6710]
Hello,

The GANTT chart for MRP Work Orders is generated on the basis of the work order planned start date (field "date_planned") + date_delay = effort (field "hour"). That is completely incorrect, because effort != duration.

As a consequence of this, normally the gantt chart will have a bar shorther than what it should be.

Steps to reproduce in a demo environment:
1. Create a manufacturing order for product [LAP-CUS] Laptop Customized. Set quantity to 1 and start date = 18th march 2015 at 07:00:00
2. Confirm the MO
3. Go to 'Manufacturing | Work Orders' and search for this MO. Open the Gantt chart.

See the results:
![image](https://cloud.githubusercontent.com/assets/7683926/7641305/220d27ee-fa89-11e4-8e1c-039112ba52d0.png)

And then see how it looks when you change the gantt view "workcenter_line_gantt" to use date_stop = "date_planned_end" instead of date_delay="hour":

![image](https://cloud.githubusercontent.com/assets/7683926/7641337/6da1ff72-fa89-11e4-813c-6285d84ef35e.png)

**Comment by anajuaristi** [comment]
Could be related to https://github.com/odoo/odoo/issues/6694

**Comment by mlaitinen** [comment]
We also had issues with the Work Orders' Gantt view, but in our case, the bar was way longer than it should've been. We found out that the JavaScript component [dhtmlxGantt]( https://github.com/odoo/odoo/blob/8.0/addons/web_gantt/static/lib/dhtmlxGantt/sources/dhtmlxgantt.js#L359) used to render the gantt chart has 8 hours as daily work time hard-coded and in our case the work time was 24/7 (=machine).

Using `date_planned_end` instead of `hour` would be a solution for some, but using that would prevent us to resive/move the gantt bars.

**Comment by Yenthe666** [comment]
Hi @jbeficent,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
