### ISSUE TITLE
demo data noupdate="0" not working

### ISSUE THREAD

**Issue by oerp-odoo** [odoo/odoo#6784]
It seems when upgrading module, on demo data, `noupdate="1"` is always forced, even if I specifically set to `noupdate="0"`, it still does not update. 

Scenario to reproduce. Define any demo data with `noupdate="0"` option. Install/Upgrade module. demo data will be created. Now change anything in demo data`xml`. Upgrade module. Result `=>` no changes.

P.S. maybe there is some work around? It limits unittests a lot. Tests will pass if no demo data is modified. But if it will be modified, it won't restore back (with noupdate false option) and tests will start failing, when it should not. Sure I can prepare same data for every test class (inside test file), but that is lots of repetitive work.

**Comment by Sathors** [comment]
I can confirm this bug. It is indeed really annoying for testing.
There is nothing about noupdate in the v8 documentation.

**Comment by yulybaseball** [comment]
Same for me!
Testing this way has become in a "complicated" task.

**Comment by odony** [comment]
This is [by design](https://github.com/odoo/odoo/blob/eeffda9689acde940d31499e76bc2ff00ce88819/openerp/modules/loading.py#L116-L117):
- demo data are meant to be only used to "bootstrap" a database, so the users can test and play with the data. This is exactly the idea behind typical "noupdate" data, such as initial config, default templates, etc.
- updating demo data after users have already started to test/modify the data is bound to cause inconsistencies and not produce the desired result anyway (crashes due to violated constraints, desynchronized workflows, etc.)

For unit tests you are strongly encouraged to use test fixtures, especially if you'd like to execute them repeatedly without starting with an empty database every time. Unit tests have `setUp()` and `setUpClass()` methods used exactly for the purpose of creating the test data. Here is [an example](https://github.com/odoo/odoo/blob/eeffda9689acde940d31499e76bc2ff00ce88819/addons/mail/tests/common.py#L38-L133) in the tests of the core `mail` module.

Pull Requests are welcome if you would like to help us improve the [technical documentation](https://www.odoo.com/documentation/9.0/reference/data.html) (See the "Edit on GitHub" link) :-)

**Comment by oerp-odoo** [comment]
@odony but puting eveything in `setUp()` for examples, makes tests take very long compared to if they would load data from demo xml for example. For example if you need to set up some invoices and then validate it, it would increase unittests time dramatically.

Maybe there is some other way, tricks/suggestions to save time for setting up the data then?

**Comment by odony** [comment]
@oerp-odoo Well, you only need to create the data that is strictly needed for your tests, so that should usually be rather quick. Creating an invoice and validating it does not take much time unless you make the invoice huge. And this is not a time-critical process anyway, it's just a manual execution of the tests in your dev environment, so a couple of seconds won't make much difference. Have you tried it and measured the actual overhead?

BTW test results are never committed, so if you do not modify the demo data manually you should be able to simply re-run the tests as many times as you want. (This may fail when modules modify each other's demo data)

There's no workaround to magically reset the demo data to their original state within Odoo, but you could also just take a snapshot copy of your database with PostgreSQL (`dropdb --if-exists test_db ; createdb -T demo_db test_db`) and run your tests on a fresh copy every time. Make an alias command to do this before running the tests every time and you're done. (On my SSD a typical copy takes 3 seconds)

Most of this definitely sounds overkill to me, but you mileage may vary.

**Comment by oerp-odoo** [comment]
Well yes I'm trying to use demo data from xml files, because it 
completes tests much faster. When we run like one test, then yes the 
difference is maybe few seconds, but when there are hundreds of 
unittests, then those seconds add up. And unfortunately, the biggest 
part of time sink is setting up the data. But anyway thanks for 
suggestions. Those might come in handy.

On 2016.03.25 19:52, Olivier Dony wrote:
>
> @oerp-odoo <https://github.com/oerp-odoo> Well, you only need to 
> create the data that is strictly needed for your tests, so that should 
> usually be rather quick. Creating an invoice and validating it does 
> not take much time unless you make the invoice huge. And this is not a 
> time-critical process anyway, it's just a manual execution of the 
> tests in your dev environment, so a couple of seconds won't make much 
> difference. Have you tried it and measured the actual overhead?
>
> BTW test results are never committed, so if you do not modify the demo 
> data manually you should be able to simply re-run the tests as many 
> times as you want. (This may fail when modules modify each other's 
> demo data)
>
> There's no workaround to magically reset the demo data to their 
> original state within Odoo, but you could also just take a snapshot 
> copy of your database with PostgreSQL (|dropdb --if-exists test_db ; 
> createdb -T demo_db test_db|) and run your tests on a fresh copy every 
> time. Make an alias command to do this before running the tests every 
> time and you're done. (On my SSD a typical copy takes 3 seconds)
>
> Most of this definitely sounds overkill to me, but you mileage may vary.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub 
> <https://github.com/odoo/odoo/issues/6784#issuecomment-201385339>
>

-- 

Pagarbiai / Regards

Andrius Laukavičius

Boolit programuotojas / developer


(+370) 52 032 766

dev@boolit.eu <mailto:info@oerp.lt>


Odoo Partner <https://www.odoo.com/partners/NOD-3621>

www.oerp.lt <http://www.oerp.lt>

www.odoolietuva.lt <http://www.odoolietuva.lt>

**Comment by Sathors** [comment]
Actually I would have defined the terms diferently. For me demo data represents the base fixtures, the same data for ALL of my tests, whereas creating the records needed in the setUp() or in the individual test_* methods is more a use of factories (creating the record when you need it, instead of preloading it).

As oerp-odoo says, it may become quite cumbersome to create the records in every class, for every test. And the record creation has quite an impact on the performances.
In some cases it may be quite complicated to create a record, because of all the other models it may depend on. I admit that it is usually a sign of bad design, but well, I am not the only one on my team.

Seems to me pretty hard to TDD with Odoo in general actually.

But thanks for the tip and indicating that this behavior is not a bug (but a feature!).
I was using the interface to duplicate a demo db, never thought of aliasing it!

**Comment by boolit-eivydas** [comment]
@odony I am grateful for the functionality of the `setUp()` method but I disagree with the forcing of `noupdate=1` on demo data. I believe that this switch could be used for just the goal it is made for - regulate which parts of the data are not to be renewed on module updates.

You could let the developers use this switch, since it is already there, but disabled.

**Comment by odony** [comment]
Thanks for your comments, but it would not work reliably (as I tried to explain), so we don't plan to change that.

**Comment by Sathors** [comment]
Well, I think we understood your point, but in my case, and maybe in @boolit-eivydas case, we don't mind much that the db gets corrupted while being used by users, because we don't give demo dbs to our users.
It is just a different use of demo data actually.

So backing up @boolit-eivydas, I think letting the programmer decide would be the most flexible way.
Even though you seem to already have taken your decision.

Thanks nonetheless.

**Comment by bnisevic** [comment]
And try to update decimal.precision by csv or xml using "decimal_price" or 1. Simply it doesn't go even demo data is switched off and removed from the DB. This is one sorry ass feature.
