### ISSUE TITLE
Regresion from older versions. Services to buy, make to order do not generate procurement

### ISSUE THREAD

**Issue by anajuaristi** [odoo/odoo#6808]
it's a very usual case that someone wants to buy services MTO (subcontracting)

in olders versions from V5, it was possible to configure this case standar way. Just setting the product as a service, and fixing procurement route to buy, make to order.

It is not possible to configure anymore this case in V8. 
Routes are only visible where product is stockable or consumable, so the only way to mark a service buy MTO is first setting this type and after setting service (routing checks stay clicked) 

Even on this case, procurement is never created when sale order is confirmed so it's not possible procuring services to buy.
Am I missing any module to be installed or it's just a regression in V8? 
Thank you very much:
Ana

**Comment by pedrobaeza** [comment]
This is a very common case in companies with subcontracting routes.

Even sale_service module doesn't make it well because as Ana said, procurement routes are hidden when you select service products.

**Comment by falinwa** [comment]
Hi Anna,

What I remember in version 7, we don't have that function again and need to install other module to provide that function.

I think Odoo must fix it on the module sale_service

The expected behavior must be:
When we installed sale_service module,
We created product type to be service, and the routes will be still available,
when its manufacture, procurement will create task,
but if its buy, procurement will create purchase order.

**Comment by anajuaristi** [comment]
Hi falinwa

Exactly +1 to your aproach

**Comment by Yenthe666** [comment]
Hi @anajuaristi ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 7 & Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
