### ISSUE TITLE
[8.0] Debian Dependency Not Listed - Psycogreen Needed for Chat With Worker Processes > 0

### ISSUE THREAD

**Issue by michaeljohn32** [odoo/odoo#6852]
On a fresh installation of Debian Wheezy and installing the odoo package, I was receiving the following error when using Odoo in multi-worker mode:
**Exception: bus.Bus unavailable**

I did a ps aux and found that openerp-gevent was running, but a netstat didn't reveal anything listening at port 8072.

I ran openerp-gevent manually:

> root@testxx:/usr/bin# openerp-gevent
> Traceback (most recent call last):
>   File "/usr/bin/openerp-gevent", line 5, in <module>
>    import psycogreen.gevent
> ImportError: No module named psycogreen.gevent

After **pip install pyscogreen**, I do see a listening server at port 8072 and no error when running openerp-gevent manually.  Did I miss that dependency somewhere?

**Comment by spadae22** [comment]
No, the issue is with the install and there are not clear guidlines and how the chat works with workers>0. I see some users install a reverse proxy server. I am still waiting for clear instruction on how to get chat to work with workers>0.

**Comment by michaeljohn32** [comment]
@spadae22, yes, I believe a reverse proxy server is necessary with something like this. For apache (I believe nginx is documented elsewhere), I did the following:

  ## Proxy rules
  ProxyRequests Off

  ProxyPass /longpolling/ http://server:8072/longpolling/
  <Location /longpolling/>
    ProxyPassReverse http://server:8072/longpolling/
  </Location>

  ProxyPass / http://server:8069/
  <Location />
    ProxyPassReverse http://server:8069/
  </Location>

**Comment by spadae22** [comment]
Ok, I test on develpment server, we are live now, so do not want to risk the crash. I already have nginx ready to go, tx

**Comment by michaeljohn32** [comment]
Also, please note that there is no Debian package for the psycogreen dependency.  There was a bug opened with an "Intent to Package" at: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=782367

However, it appears that Debian maintainer was not happy with how slow the odoo team was with fixing bugs and didn't like some of their answers, so I think we may not be seeing that package anytime soon.

**Comment by alejandrosantana** [comment]
Sí, if there is no Debian package for psycogreen, is there any workaround
to install Odoo on Debian?

**Comment by michaeljohn32** [comment]
@alejandrosantana, 

To be clear, psycogreen may not be required if you use the default odoo and do not want more than the default number of worker processes.  But, if you want to install it on debian and set the number of workers to more than zero, do the following:

* Install the odoo .deb from odoo nightly.
* Then run:
<pre><code>
sudo /etc/init.d/odoo stop
sudo apt-get install python-pip
sudo pip install psycogreen
sudo /etc/init.d/odoo start
</code></pre>
and confirm that openerp-gevent is now running (if you have the workers set to a number different than the default in the configuration file).  Hope that helps!

**Comment by alejandrosantana** [comment]
All right, just use pip, then.


--
*Alejandro Santana*
alejandrosantana@anubia.es
· · · · · · · · · · · · · · · · · · · · · · · · · · · · ·

ANUBÍA, soluciones en la nube, S.L.

Colón 26, planta 3, oficina 1
36201, Vigo (Pontevedra)

www.anubia.es

[image: anubía_logo_2014_i_o_140x140.png][image:
odoo_logo_odoo_ready_140x140.png] <http://www.anubia.es/>



2015-06-10 16:14 GMT+02:00 John Walsh <notifications@github.com>:

**Comment by jebba** [comment]
Woo! Me too.

Anytime workers set to greater than zero, the load would go above 1.00 with Odoo, even when the system was idle. What was happening is the main parent process was spawning a new process that would "instantly" die due to no psycogreen. I installed that via pip on Debian Jessie, and all is now fine.

**Comment by spadae22** [comment]
I still cannot get chat to work with workers > 0. I am running 17 workers.

**Comment by Diftraku** [comment]
The `psycogreen` Python dependency has been packaged on Ubuntu since Wily (see http://packages.ubuntu.com/search?keywords=python-psycogreen&searchon=names&suite=all&section=all ) as `python-psycogreen`. Installing the package manually and then restarting Odoo brings up the polling server (if it doesn't spawn itself after installation of the python package).

This should be listed as an additional step on https://www.odoo.com/documentation/9.0/setup/install.html#setup-install-packaged , be it via `pip` or `apt-get/apt` on newer Ubuntu versions.

**Comment by odony** [comment]
@Diftraku good point, though we typically need the dependency to be in Debian before we can depend on it in our .deb packages. Now that's in Debian 9, so we could add it by default.
Right, @sle-odoo?

Otherwise indeed, switching to workers mode with our DEB package requires a manual install of psycogreen, typically using `pip`. The documentation could mention that.

**Comment by Yenthe666** [comment]
Hi @michaeljohn32 ,

Thank you for your bug report.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.
@d-fence you might want to double check this one for V9, V10 and V11 though. Is psyco by default in the debian package now?

Regards,
Yenthe
