### ISSUE TITLE
[11.0] Vulnerability detected CWE ID 798 addons/web_editor/static/src/js/editor/snippets.options.js

### ISSUE THREAD

**Issue by TatianaGarcia94** [odoo/odoo#68616]
Impacted versions: Odoo 11
En la ruta: addons/web_editor/static/src/js/editor/snippets.options.js 387, 395, 399, 403
Nombre de la vulnerabilidad: Use of Hard-coded Credentials
Modo de detección: Se realizó un escaneo estático, el cuál detecto la línea mencionada como vulnerabilidad según los estándares de seguridad

**Comment by pedrobaeza** [comment]
Sorry, but 11.0 is a deprecated version that is already not being supported, so any bug report about this old version won't be attended, and thus I close this issue. Please check if the problem is still there in new versions, and if so, you can open a new issue regarding that version (and please use English).

Thanks for your comprehension.

**Comment by Yenthe666** [comment]
Plus should be through security & not Github.
