### ISSUE TITLE
footer is missing in PDF reports if developer mode is active

### ISSUE THREAD

**Issue by razvanioan** [odoo/odoo#69301]
Impacted versions: 14

Steps to reproduce: activate developer mode and generate any PDF report

Current behavior: footer (company contact data + custom footer message if configured) is not displayed (only design lines according with the template selected)

Expected behavior: footer data should be there

HTML report (preview) is working fine

This [happened and been fixed in v13](https://github.com/odoo/odoo/issues/38394), but somehow is still happening now

**Comment by pedrobaeza** [comment]
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - click on the blue door icon of the version row - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by razvanioan** [comment]
I cannot reproduce it in runbot for the moment, I'll come back if I succeed
