### ISSUE TITLE
There's a code visible in the title when e-mailing the purchase order

### ISSUE THREAD

**Issue by revitasurya** [odoo/odoo#69354]
Impacted versions: Odoo 14.0+e (Enterprise Edition)

Steps to reproduce:
1. Go to Order application
2. Create new purchase order
3. Send email to the vendor

Current behavior:
The title of the file sent in pdf is -> PO_$ {(object.name or '') .replace('/','_')}.pdf

Expected behavior:
The title should match the purchasing number and vendor name.

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/28603739/114968974-9fa13e80-9ea1-11eb-9894-cd3f32668493.png)

Support ticket number submitted via odoo.com/help (optional):

**Comment by pedrobaeza** [comment]
You have introduced an space in your email template:

![wyAdXV0Gxy](https://user-images.githubusercontent.com/7165771/114980555-ecc6e580-9e8c-11eb-9f03-2957ea83e1f0.png)

and it fails because of that. This works correctly without it:

![Selección_005](https://user-images.githubusercontent.com/7165771/114980595-f9e3d480-9e8c-11eb-8c83-28f1d8e3a239.png)
