### ISSUE TITLE
[MASTER] Changes by frontend editor not saved

### ISSUE THREAD

**Issue by Fl0rianFischer** [odoo/odoo#6992]
**Changes by frontend editor not saved**

Impacted versions:

 - Master

Steps to reproduce:

1. Drop a snippet with resizable columns into the website
2. Adapt column sizes before saving
3. Save
4. Changes are saved correctly
5. Hit the edit button
6. Resize columns again and save

Current behavior:

- Changes to snippets in frontend are not saved after the snippet has been saved once

Expected behavior:

 - Changes to the layout should always be saved and visible in the frontend no matter when the user does them.

**Comment by jholze** [comment]
@Fl0rianFischer can you please check the behavior also in other browsers please.

**Comment by jholze** [comment]
@odony already a know issue ?

**Comment by odony** [comment]
Which `master` version are you using? The front-end editor is being completely reworked, and those changes are going to land in `odoo/master` soon (in the coming weeks). In the mean time you are likely to experience various UI bugs in the `master` branch, because it is really a work-in-progress. Please do not report bugs about this.
Thanks!

**Comment by jholze** [comment]
Thanks.
