### ISSUE TITLE
[14.0] website_sale : wrong price if stock limit is reached

### ISSUE THREAD

**Issue by fmdl** [odoo/odoo#70064]
Impacted versions: 14.0 (and maybe other)

Steps to reproduce:
- create a product, set 2 unit in stock, choose Availability : Show inventory on website and prevent sales if not enough stock
- add pricelist : 1 unit = 100€, 2 unit = 80 €, 3 unit = 60€, 4 unit = 50€
- go to web shop, 
- buy product, click on the plus button, to go 3, quantity is set 2 by Odoo (qty in stock) but the price is 60 €.

Note : if you add in the cart then go in the cart the price is 80 €.

Current behavior:
Price is 60 €

Expected behavior:
Price should be 80 €

Video/Screenshot link (optional):

https://user-images.githubusercontent.com/16716992/116474537-eb2bf300-a878-11eb-99c9-a4e0d634fd69.mov

Support ticket number submitted via odoo.com/help (optional):
OPW #2519174

**Comment by fmdl** [comment]
@JKE-be

**Comment by fmdl** [comment]
https://github.com/odoo/odoo/pull/70066

**Comment by Yenthe666** [comment]
Honestly if there is a PR and an OPW I really see no point in creating issues and what's even worse is that you don't link the issue on the PR. You're causing overhead on the tickets here and on the official tickets and we're risking a constant double use of resources due to this. 
Since you have an OPW and a PR I'm closing this in favor of the other ones.

**Comment by fmdl** [comment]
@Yenthe666 oups if forgot to close the issues, sorry
