### ISSUE TITLE
README.md hyperlink broken

### ISSUE THREAD

**Issue by sidneylopes** [odoo/odoo#70497]
Impacted versions: 13.0

Steps to reproduce:

Current behavior: Setup instructions hyperlink leads to nowhere

Expected behavior: Lead to setup instructions

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by pedrobaeza** [comment]
Which hyperlink?

**Comment by sidneylopes** [comment]
The Setup instructions one

**Comment by sswapnesh** [comment]
This one ?
https://www.odoo.com/documentation/13.0/setup/install.html

![Screenshot(15)](https://user-images.githubusercontent.com/16624719/117344189-c19b4900-aec2-11eb-8511-5fd32c3ca2b0.png)

**Comment by sidneylopes** [comment]
Here on github, in the 13.0 branch. Its readme has a broken hyperlink under "Getting started with Odoo". "Setup instructions" leads to nowhere.

**Comment by pedrobaeza** [comment]
I think this is because Odoo documentation has been recently reordered. @Feyensv may help on this.

**Comment by Feyensv** [comment]
Indeed, the documentation just got a full reorganisation (and new style).
But the deployment isn't fully completed at the moment, therefore:
* The "new" documentation is only build for [12.0](https://www.odoo.com/documentation/12.0/) & [13.0](https://www.odoo.com/documentation/13.0/) (the code is already merged for 14.0 & master but not built already).
* Some old links are broken since the files were reorganized.  A bunch of redirection rules should be deployed soon, but currently, the majority of the old links do not work (for v12 & v13).

Concerning the install page, you can find the 13.0 page on https://www.odoo.com/documentation/13.0/administration/install.html

The different links referencing the doc here and there will be fixed progressively (manually or by the redirections once deployed).
Thanks for reporting this one, I'll fix it :+1:

**Comment by sidneylopes** [comment]
If this issue gets solved and closed, do I get the artic code vault badge?

**Comment by Yenthe666** [comment]
@sidneylopes nope :) You didn't make a PR so there is no commit plus the arctic code vault badge was only given to those that have done commits before it was sent to the vault.
