### ISSUE TITLE
Possible registered users enumeration on reset login page

### ISSUE THREAD

**Issue by ebirbe** [odoo/odoo#71179]
This is a report a customer received via email from a so called ethical hacker.

Impacted versions:

v13.0 and I thinks all others.

Vulnerability: User Enumeration/ Information Disclosure

The username enumeration is an activity in which an attacker tries to retrieve valid emails from a web application. The web applications are mostly vulnerable to this type of attack on password reset pages. If the system is vulnerable to the user enumeration attack, the attacker may be able to obtain a list of existing user's email in the system by submitting input (valid and invalid user names) and analyzing the server response (error messages). The attacker can then run a dictionary attack or brute force attack to further exploit the obtained information.

Description:
At the forgot password page of your website, when you enter an invalid email the error message is: " Reset password: invalid username or email    ".

Steps to reproduce:
1. Navigate to Login Page
2. Click on forgot password
3. Enter an invalid email address
4. Error Message: "    Reset password: invalid username or email       "
5. Now enter a valid Email
6. The Message is different

Patch/Fix:
Make sure in both conditions the response message is "If email is registered, you will get a reset link."

Impact:
Due to this vulnerability Enumeration of email addresses of already registered users is possible, and or, checking if a user with specific email address is registered in the website and will then be used for phishing attacks or any malicious intent.

/cc @moylop260 @luisg123v

**Comment by ebirbe** [comment]
OPW #2538554

**Comment by Yenthe666** [comment]
I'd like to point out that these kind of issues probably belong to https://www.odoo.com/security-report and since you have an OPW I don't really think this should be out here in the public.

**Comment by fmdl** [comment]
@odony

**Comment by odony** [comment]
Hello, this is listed on our [Responsible Disclosure page](https://www.odoo.com/security-report) as an exclusion, because it's considered a feature:

> User enumeration (ability to verify that a username exists). Does not carry much risk, and can't be prevented without deteriorating the user experience.

There is very little value in enumerating users, and no way to really prevent it without deteriorating the user experience. We prefer giving better feedback to users who are trying to sign up or get back into their account, and to implement rate-limiting to mitigate attacks instead.

Many other software packages and cloud providers do the same, e.g. Google.

PS1: if you're truly concerned about this, you could customize the software to behave differently, but we're not planning to introduce this by default.

PS2: as noted by @Yenthe666, if you think you've found a security issue, please follow the responsible disclosure described on the responsible disclosure page ;)

**Comment by kwoot** [comment]
Hm, I'm not a security expert but if I would be working for, I don't know, let's say a Russian government organization and I can harvest emails from the Internet and see which citizen has an account on some Odoo run Human Rights website, that could be of interest to me, no?
