### ISSUE TITLE
Duplicate pos_reference lead to missing orders

### ISSUE THREAD

**Issue by hedshefer** [odoo/odoo#71455]
Impacted versions:

V 14.0

Steps to reproduce:

I have reproduced it here in odoo runbot (standard V14.0):

Duplicate tab in an open session (POS)-> create order in the new opened tab. then, we get recipt with existing sequence number.

Current behavior:

The reciept (pos_reference field) contains the following structure: session number+login+sequence, and It looks like the duplicated tabs, started the qequence from 1, but kept the same login param of the first tab.

Expected behavior:

New order generated with unique pos_reference and sync with db.

Video/Screenshot link:

https://drive.google.com/file/d/1fcW6YAgpIrCyhvxeytrUCn9nMgZxjR16/view

It seems that the order process fails in the following function:

@api.model

def create_from_ui(self, orders, draft=False):

""" Create and update Orders from the frontend PoS application.

I assuming that the logic of this function have to be change:

generate_unique_id: function() {

// Generates a public identification number for the order.

// The generated number must be unique and sequential. They are made 12 digit long

// to fit into EAN-13 barcodes, should it be needed

function zero_pad(num,size){

var s = ""+num;

while (s.length < size) {

s = "0" + s;

}

return s;

}

return zero_pad(this.pos.pos_session.id,5) +'-'+

zero_pad(this.pos.pos_session.login_number,3) +'-'+

zero_pad(this.sequence_number,4);

},

Support ticket number submitted via odoo.com/help (optional):
Ticket
#2549292

**Comment by hedshefer** [comment]
Similar to the following issue:
https://github.com/odoo/odoo/issues/7388#issue-92303136

**Comment by pedrobaeza** [comment]
The problem remains the same: you are tricking the system, and thus, no warning can't be displayed, as there's no way to detect such condition. PoS is designed to be offline first, so some restrictions must happen on that environment. Duplicating tab is something outside Odoo (from browsers). If you open another tab with Odoo from the beginning, and try to open the session through the button in the Odoo UI, you will see that it's not possible, so the warning is there.

Closing as won't fix due to forbidden action.

**Comment by hedshefer** [comment]
@pedrobaeza @mart-e 
according to this reference:
https://github.com/odoo/odoo/issues/7388#issue-92303136
I think the second tab should be closed as well, otherwise we get the missing orders in the new tab.

**Comment by pedrobaeza** [comment]
I didn't know about that possibility to auto-close such tab, and I have never seen it working, but if Martin says so, then I wait for his answer.

**Comment by hedshefer** [comment]
@pedrobaeza @mart-e 
I'm able to reproduce the same issue with a different flow:
When a pos session is crash and the user click on "restore pages" in the browser, the new open session have a duplicated pos_reference and it leads to missing orders.
Reproducing steps:
https://drive.google.com/file/d/1K21unwwyPD7_9ssHUxkYYzTDWudUKZ1b/view

**Comment by pedrobaeza** [comment]
At the end, it's the same, as you are tricking the system with unsynchronized tabs, as the previous session was not "dumped" to the server.

**Comment by mart-e** [comment]
@pimodoo I am pretty sure the tab with an open session was self-closing (as in "back to `/web`", not close the browser tab) in 9.0 but it appears it is no longer the case. Are you aware of the change?

**Comment by pimodoo** [comment]
@mart-e The feature had been accidentally removed in refactoring, and recently set back in this commit: https://github.com/odoo/odoo/commit/51b2c7fad08354499503c5c444dd1a3ae1f26fc1#diff-1615bc14ca3bc6863acfafd2904c39c4640105b04decad05dfb99fcf82bb32c5

**Comment by pedrobaeza** [comment]
Good to know about the closing!

**Comment by hedshefer** [comment]
The auto-closing will close the first session, is't?
In those cases the issue is coming from the new open session and the restored session.

**Comment by pimodoo** [comment]
the auto closing, in this case is closing tab if there are multiple tabs in the same browser opened, because they will work on the same local storage and each tab may destrOy or alter data put in the local storage by the other tab.
@hedshefer 
I've just test what you did in your video, and it seems that restoring an old tab, won't call the server and'll use cache, meaning that the referene is not incremented. We'll check to solve that.

**Comment by hedshefer** [comment]
OK, please take into account also the case with the the new opened tab that has a wrong sequence which lead to missing orders.
https://drive.google.com/file/d/1fcW6YAgpIrCyhvxeytrUCn9nMgZxjR16/view
