### ISSUE TITLE
[14.0] XML record 'module_category_services_timesheets' is not available in base module.

### ISSUE THREAD

**Issue by omalbastin** [odoo/odoo#71680]
https://github.com/odoo/odoo/blob/cd9c071c9357cef14635ef094a9f14fc5431956c/odoo/addons/base/data/ir_module_module.xml#L23

Create a new database without hr_timesheet module. It will result in parse error.

**Comment by omalbastin** [comment]
same issue reported: https://github.com/odoo/odoo/issues/59335

**Comment by pedrobaeza** [comment]
Yes, but now the problem seems clear: you should deploy with such module in addons path, so while initializing the database, all detected categories are auto populated. I agree it's not ideal, and I also restrict the available addons even for Odoo core, but there are some that due to this, they should be there. As Odoo doesn't consider to deploy Odoo repository separately, then this can't be considered as a bug, but limitation that won't be changed, so closing.
