### ISSUE TITLE
[BUG] Module: Data Cleaning  - Duplicate Removal selection archive/delete disappears when model = res.partner is choosen

### ISSUE THREAD

**Issue by samannisar** [odoo/odoo#72089]
Module Name: Data Cleaning
Technical Name: data_cleaning
Impacted versions:    14.0.1.0

Steps to reproduce:
1. Go to Data Cleaning module
2. Go to Deduplication Rules
3. Create a new rule
4. Verify that the Duplicate Removal selection is present. To delete or archive the record. 
5. Choose Model = res.partner
6. Verify that the Duplicate Removal selection is present. To delete or archive the record.
7. Choose Archive
8. Save
9. Click on Deduplicate
10. Merge one of the proposals
11. Verify that the merged donor profile is archived and not deleted from the system. 

Current behavior: When res.partner is selected as model, it does not give an option to choose between archive/delete after merging. Currently it is deleting the merged profile by default. 

Expected behavior: Duplicate Removal Option to choose between Archive/Delete should be given, user should have option to choose between archive or delete. We need to archive the merged profile as part of our business. 

Video/Screenshot link (optional):
Step 3 & 4 from above: 
![image](https://user-images.githubusercontent.com/59840077/121724647-2a737380-cab6-11eb-817e-b5c90b6f3223.png)
Step 6 from above:
![image](https://user-images.githubusercontent.com/59840077/121724711-40813400-cab6-11eb-8b65-53d2bf4a79ca.png)

Support ticket number submitted via odoo.com/help (optional): Ticket#2569158

**Comment by pedrobaeza** [comment]
As this is an enterprise module, you should report the issue to odoo.com/help instead.

**Comment by samannisar** [comment]
Will do. Thanks.

**Comment by samannisar** [comment]
Ticket#2569158

**Comment by pedrobaeza** [comment]
OK, then we can close this one.

**Comment by moylop260** [comment]
@pedrobaeza @Yenthe666 @nhomar 

We prefer to follow-up in a public thread in order to avoid making duplicated issues/tickets
And follow-up the Odoo's replies

These kind of issues are generally labeled with `OE` tag

See the following example (Thanks @Yenthe666 for labeling it)
 - https://github.com/odoo/odoo/issues/70567

Could you help me with this, please?

**Comment by pedrobaeza** [comment]
This is very specific for being opened in the community issue tracker.

**Comment by Yenthe666** [comment]
Honestly, I'm totally fine with keeping it open as long as somebody let's us know when it is solved (or not considered a bug)

**Comment by nhomar** [comment]
@pedrobaeza This is not yours, just to say! do not close issues that are not solved.... (if you are not ok with working odoo as a hole it is up to you, but that is a discussion for other forums...

**Comment by pedrobaeza** [comment]
It's not something about Odoo as a whole, but don't put noise in the community issue tracker, as we have talked a lot of times, and not having yet any auto-closing mechanism, but if 2 of 3 think that it's OK to be opened, go ahead. I will continue closing the same what I don't consider correct to be here, the same I do with deployment or development things. Then a re-review can be done by you.

**Comment by nhomar** [comment]
Hello @samannisar 

I will answer and close:

The reason we can't create such an option is that the model has a method called _merge_method once you set such a method in the model there is no possibility to actually decide what to do (because the code will decide by you) the solution is to customize the code with an external module.

@pedrobaeza BTW you and your prejudices just confuse the users man, the actual code is 100% in community [1] and this is the reason why support both no matter where and why is perfect.

[1] https://github.com/odoo/odoo/blob/14.0/odoo/addons/base/wizard/base_partner_merge.py/#L625-L626
