### ISSUE TITLE
[8.0] Mismatch Total between SO and Invoice

### ISSUE THREAD

**Issue by mve-taktik** [odoo/odoo#7210]
Hi everyone,

***Impacted versions***

8.0

***Steps to reproduce***
1.Go to a v8 runbot instance

2.Go to Settings > Configuration > Warehouse and activate the option "Invoice products in a different unit of measure than the sales order"

3.Go to Settings > Technial > Database Structure > Decimal Accuracy and configure as follows:
- Product Price	 = 4
- Discount = 2
- Account = 2
- Stock Weight = 2
- Product Unit of Measure = 4
- Product UoS = 4

4.Select the product form of the Ipad Mini and set
- The public price = 65.8750
- Unit of Sale (Tab Sales) = m
- Unit of Measure -> UOS Coeff (Tab Sales) = 7.5
- Customer Taxes (Tab Accounting) = VAT-OUT-21-L (21%)

5.Create a Sale Order with the customer Agrolait, then buy one Ipad Mini (corresponding to 7.5m)

6.Validate the Sale Order and then create the Invoice.

***Current Behavior***
The total of the Sale Order is 79.71 €.
The total of the Invoice is 79.70 €

***Expected Behavior***
The total should be the same.

Regards, Matthias

**Comment by mve-taktik** [comment]
OPW : 643113

**Comment by nim-odoo** [comment]
The bug you describe is the intended behavior.

In your case, the sale order is the following:
Quantity: 1.0000
UoM: Units
Unit Price: 65.8750
==> Subtotal = 1.000 * 65.8750 = 65.8750 ==> 65.88 €

In the invoice, you change the UoM, and therefore digits are lost:
Quantity: 7.500
UoM: m
Unit Price: 8.7833
==> Subtotal = 7.500 * 8.7833 = 65.87475 ==> 65.87 €

The problem is that the unit price is calculated as 65.8750 / 7.500 = 8.783333333. If you choose a decimal precision of 4 digits, the unit price is rounded to 8.7833 before the calculation of the subtotal.
We cannot change this behavior, otherwise you would end up in a situation where Quantity * Unit Price would not be equal to the subtotal.

If you want to avoid this situation, you must increase the number of digits on the price unit.
