### ISSUE TITLE
cant load files for the display on odoo 

### ISSUE THREAD

**Issue by dustnnbones** [odoo/odoo#7227]
i didnt change any thing, restarting odoo server i got this error , i have access to the data base through the database manager ,but every page i open i got this errors i am new on odoo .
and thanks for ur help 
![aaaaaaaaa](https://cloud.githubusercontent.com/assets/13016785/8305597/7cade86c-19a8-11e5-8a43-e5a9c3e4c49e.png)

![screenshot from 2015-06-23 11 57 49](https://cloud.githubusercontent.com/assets/13016785/8305553/16e0ca0e-19a8-11e5-9086-7a323dd3e505.png)

**Comment by lukebranch** [comment]
@dustnnbones ,

I'm in no way connected to Odoo, i'm just a user like yourself, however I'd recommend trying to create another new database to see if the problem persists in the brand new database.

From what I can tell Odoo cannot access the modules directories and is only looking at the data stored in the database.

I would recommend checking:

1) Directory permissions for your Odoo addons directory to make sure that the Odoo user has access to those folders.
2) Check your /etc/odoo-server.conf file to make sure that your /addons directory is included.

I'd recommend using the forum for posting this kind of information, as from what I can tell this is related to incorrect deployment of Odoo, rather than a bug in the Odoo code itself.

You're best off looking for help for this kind of thing in the community forums:

http://help.odoo.com/

as they are more suited to these questions. The github issues are designed for reporting bugs with the code.

You may want to look into using an installation script to setup Odoo if you want to make your life easier. I've written one here (based on Andre Schenkel's original) that does the trick for my own deployments (the script includes options for install Aeroo Reports modules as well, if you don't need Aeroo reports you can just choose no when presented with the option):

https://github.com/OdooCommunityWidgets/install-scripts/blob/8.0/aeroo_reports/aeroo_install.sh

This is by no means the only (or even the best) method to install Odoo, however it works for me for setting up a development environment for testing.

Links to the official documentation for Odoo installation and deployment can be found here:

https://www.odoo.com/documentation/8.0/setup/install.html
https://www.odoo.com/documentation/8.0/setup/deploy.html

what I recommend is closing this github issue and trying the forums if you run into any issues with the script, or the instructions from Odoo for installation.

**Comment by Yenthe666** [comment]
Closing as there has been no feedback in ages.
Thanks for the very detailed answer/info @lukebranch 😉
