### ISSUE TITLE
Manufacturing Orders valueerrors

### ISSUE THREAD

**Issue by thebestpatrick** [odoo/odoo#7237]
When a large manufacturing order is generated with a nested BOM, sometimes odoo will throw a large XML recursion error.  There does not seem to be a pattern I can determine to when this issue is thrown or not, except that it occurs on larger BOMs, 30 or so nested BOMs corresponding to about 30 manufacturing orders and about 60 work orders.
![odoodeath](https://cloud.githubusercontent.com/assets/9068648/8309402/aea49198-1987-11e5-84d3-6d5ee0745ab4.png)

**Comment by sle-odoo** [comment]
Hi,
Is it possible you have an infinite recursion in your config? This should be detect by a133afe8a1e3741c7943a0db1a87fd68edfcb166. Can you export me a database with an example so we can check properly? It is also possible the bug was fixed in the meantime.

I'm closing this issue in the meantime.

Regards
