### ISSUE TITLE
Uncaught TypeError: Cannot user 'in' operator to search for 'context' in undefined

### ISSUE THREAD

**Issue by etechsam** [odoo/odoo#72412]
Impacted versions: 13e

Steps to reproduce: Login Odoo, Opening view, ...

Current behavior: A popup error show up, "Uncaught TypeError: Cannot user 'in' operator to search for 'context' in undefined"

Expected behavior: No error pops up

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/66409528/122740813-0588b880-d28d-11eb-9bba-489a72a0e50f.png)

Support ticket number submitted via odoo.com/help (optional):

**Comment by etechsam** [comment]
I often have this error but it seems not to be a blocking bug but I just want to know why do I have this error if anyone can help

**Comment by pedrobaeza** [comment]
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - click on the blue door icon of the version row - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by etechsam** [comment]
Actually, there no step to reproduce it because the error shows up randomly. As I said, it sometimes appeared after I logged in, sometime when I open a form view, ...
I have reproduiced it on runbot.
Maybe it's a cache issues.
Thanks

**Comment by pedrobaeza** [comment]
I'm afraid "random" is not enough for tracing the problem, so you need to define proper steps for reproducing it, and reproduce it on runbot, not on your instance, or nothing will be possible to do.

**Comment by etechsam** [comment]
Alright
Thank you anyway
