### ISSUE TITLE
[14.0] Why isn't it easier to edit sequences of journal ?

### ISSUE THREAD

**Issue by romaric-oci** [odoo/odoo#72486]
@Yenthe666 @william-andre here are some points that I note

- ODOO imposes a sequence by journals, which is not the case of other accounting software package (for example CEGID) it is already a first change for the user. 
- Conversely, ODOO easily allowed via the v13 interface sequences to include the year (which CEGID lacks). 
- The V14 **has lost the simplicity** of disassociating the prefix from the sequence of the log code (the code is used in an export for an external ERP, the prefix is visible on the sales invoice and have). 
- The V14 **has lost the simplicity** of continuing the sequence where the user was before the migration to ODOO
- V14 **imposes** the month on the user in the sequence

As an integrator, we are constantly confronted with the accompaniment to change or the taking into account of the constraints imposed by an external accounting firm. Whether the old software or that of the firm is CEGID, Quadra, Sage, Ciel ...
This is one more thorn for migration to Odoo

For the accounting revision/evolution, is PwC attached to the discussion? (author of all the Mémentos of the accounting range published by Éditions Francis Lefebvre)

_Originally posted by @romaric-oci in https://github.com/odoo/odoo/issues/58877#issuecomment-865160210_

**Comment by william-andre** [comment]
> ODOO imposes a sequence by journals, which is not the case of other accounting software package (for example CEGID) it is already a first change for the user.

What do you mean? You want multiple sequences per journal? Multiple journals per sequence?
Multiple sequences per journal: you can change your sequence whenever you want just by pressing edit, and you can have one sequence for the invoices and one sequence for the refunds.

> Conversely, ODOO easily allowed via the v13 interface sequences to include the year (which CEGID lacks).

And the month since v14. It was kind of possible before that, but with a lot of bugs and side effects because people didn't understand what they were doing in the complicated config of `ir.sequence`

> The V14 has lost the simplicity of disassociating the prefix from the sequence of the log code (the code is used in an export for an external ERP, the prefix is visible on the sales invoice and have).

Look at the field `sequence_prefix` on `account.move` for instance.

> The V14 has lost the simplicity of continuing the sequence where the user was before the migration to ODOO

That is a migration issue, and nothing related at all to the mechanism.

> V14 imposes the month on the user in the sequence

Simply, completely and utterly false.

________

Look at how the sequences are implemented, it might give you a better idea of how it works and why it is not as bad of an idea as you seem to think it is.

https://github.com/odoo/odoo/blob/14.0/addons/account/models/sequence_mixin.py

**Comment by qdp-odoo** [comment]
Truth is: the aim of that task _was_ to simplify the sequence editing. Either you didn't get how it's supposed to work, either we somehow fucked up its implementation as you seem to complain just about the opposite... You might argue that we lost some flexibility but don't say it's more difficult to edit the sequences

**Comment by romaric-oci** [comment]
thank you for your answer William
I especially insisted on the ** loss of simplicity **. Because even in debug mode, from the log it is no longer possible to access the sequence settings.

By default ODOO offers CODE / YEAR / MONTH / NUMBER but when we go into the sequence nothing gives the setting used
![image](https://user-images.githubusercontent.com/81656154/122889744-5824ac00-d343-11eb-9783-8d8513970a95.png)
no suffix, the subsequence by date interval is not activated, the size is 0 when it is really 4.

If on sequence I set a prefix + suffix + size of the sequence to 6
![image](https://user-images.githubusercontent.com/81656154/122890259-d1240380-d343-11eb-9d28-543883fe3307.png)
i get this error message
![image](https://user-images.githubusercontent.com/81656154/122890387-e862f100-d343-11eb-8f89-d2354639b784.png)

For Multiple journals per sequence : CEGID works with an accounting document number only depending on the year and company, the numbering of invoices being another sequence.

**Comment by romaric-oci** [comment]
@qdp-odoo it is no longer even modifiable by the sequence menu
It is necessary to go through the re-sequencing wizard but without being certain that the prefix request is understood by ODOO. 
_For example, the sequence is "INV / 2021/06/0001". The Customer wishes to have "Invoice 21-000001"_

In addition, it requires that a first invoice be posted to configure.

**Comment by william-andre** [comment]
That is because you don't need to edit it from a weird/complicated menu that nobody understand. Trust me. If you thought you understood it, you didn't.

Just change the sequence on a draft journal entry and let the magic happen. You could also use the resequence wizard .

_____

Regarding your screenshot of a traceback. (copy pasting the text is easier for us to debug and better for the usage of internet as it yields less traffic and storage needed, but ok...), once again it has ***NOTHING*** to do with this.

The sequence you are referring to is not related to the number of the Journal Entry, but to the hashing mechanism. Which is - once again - completely unrelated.

**Comment by william-andre** [comment]
> _For example, the sequence is "INV / 2021/06/0001". The Customer wishes to have "Invoice 21-000001"_
> _In 2022, will Odoo make the change? we must wait to see and possibly resume the wizard in 2022 at the first invoice._

@romaric-oci The answer is yes; it will be detected and make the change.
You might be interested in https://github.com/odoo/odoo/pull/70941

**Comment by romaric-oci** [comment]
Thank you @william-andre 
I understood in your previous answer that it was possible to modify the sequence to have a prefix different from the journal code. But it wasn't the right streak as I thought it would be.
The sequence view is more complete and auditable when the configuration is carried out. Now it's mysterious.

I did the test only with the draft move with previous customer request such as "Invoice 21 000 0001" for better reading but this bug if the numbering is not in one block.
![image](https://user-images.githubusercontent.com/81656154/122904995-21559280-d351-11eb-920b-c7c0baeefd8d.png)

Note that re-sequencing is not legal in France (and a priori in Germany: see the Compta FR Roadshow chat from 06/16/2021 https://www.youtube.com/watch?v=pCNd8K8c25I)
An invoice number is one of the inalterable elements allowing the correlation of the accounts of the customer and the supplier within the framework of the audits of statutory auditors and of the French tax administration.

**However, I take note for the configuration of the sequence that this is possible on the first draft** (of each year) it is necessary to trust the magic whose parameterization is not auditable. (only sequence_prefix on account.move)

**Comment by romaric-oci** [comment]
@qdp-odoo : Indeed, it is easier for an average user but it requires trusting "magic".
Accountants, auditors, management controllers rely on figures, traces, evidence: here no way to control the correct understanding by the regex of what makes up the prefix year month number suffix.

Moreover, depending on the customer's request, we may have surprises the following year requiring re-sequencing (previous post)

**Comment by albertopoljak** [comment]
Can someone please tell me the technical reason this was added?
Why was the previous system changed and this new one added?
