### ISSUE TITLE
Use Upstart in ubuntu

### ISSUE THREAD

**Issue by Anhlq87** [odoo/odoo#7252]
I have  a problem: I want to use upstart in ubuntu to automatically start service openerp when it die or stop. Everyone can help me to do and test it. Thanks.

**Comment by mbaragiola** [comment]
Hello @Anhlq87 , which release of Ubuntu is this? Ubuntu moved from Upstart to systemd. So, is it worth it to learn Upstart? Also, both init systems are documented and explained in their respective websites. Odoo is no different than any other daemon/service in these regards.

**Comment by Anhlq87** [comment]
Hi @mbaragiola, Thank you very much about your answer. I Know this but when i create file openerp.conf in /etc/init. I don't know the way to test it. I want: when openerp service die or stop, it will automatically start.
this is content in openerp.conf file:

#!upstart
description "openerp-server"

start on runlevel [2345]
stop on runlevel [!2345]

#Respawn, with a limit of 10 times in a timespan of 90 seconds, after which it stops respawning.
respawn
respawn limit 10 90

#Set user to openerp
setuid openerp

#Start job via the daemon control script.
exec /opt/odoo/server/openerp-server -c /etc/openerp-server.conf


Please help me way to run and test it.

**Comment by mbaragiola** [comment]
To see if it is running, run as root/sudo:

# service odoo status

To see if auto-restarts when crashes, do the following:

# ps | grep odoo
(it'll print PIDs here, see which PID is odoo.py or odoo-something)
# kill -9 <insert PID found here>

This way, upstart should restart the process right after. You can check it again with the first command I said here.

I can't help you with Upstart's syntax and semantics, since I don't use Ubuntu.

**Comment by Anhlq87** [comment]
Hi @mbaragiola 

I have just installed upstart in my server. then use create new job in job upstart. I use key start to use but it show error:
start job_name
-> Error:
unable to connect to upstart failed to connect to socket /com/ubuntu/upstart connection refused.

Can you pls help me to solve it. Thanks

**Comment by Anhlq87** [comment]
I done it. I reboot again server and it work :) Thanks
