### ISSUE TITLE
[8.0] Tree view, Click on a button which add a new line doesn't reload the view with the new line

### ISSUE THREAD

**Issue by tfossoul** [odoo/odoo#7287]
Hi,

The problem:
I have a tree view with a button on each lines.
The button launch a wizard which allow me to split the current line in 2 or more lines.
When I click on the "valid" button, I come back on my list. The current line data is reloaded. BUT the others new lines are not added. I have to refresh the view to see them.
## I don't wanna reload the view by launching an action (like stock.transfert_details). I only want to refresh the data of the view and not loose the research I made..

I thinks the solution will be complex and will be a modification on the javascript list view definition..
If this solution is made at this level, all the extension like "many2many" widget will be touched. Which is nice because this will cover the same problem on a many2many field on a form view..

**Comment by stijnh92** [comment]
Have you tried something like in the mrp module?

<field name="move_lines" nolabel="1" options="{'reload_on_button': true}">

**Comment by tfossoul** [comment]
It actually working fine for FORM view(so thanks). But not on a TREE view.a

**Comment by beledouxdenis** [comment]
Are you not looking for the `on_write` method ? Which is almost not used, but which should work. You have an example in the accounting module:
 - https://github.com/odoo/odoo/blob/8.0/addons/account/account_view.xml#L1199
 - https://github.com/odoo/odoo/blob/8.0/addons/account/account_move_line.py#L313-L318

**Comment by beledouxdenis** [comment]
See https://github.com/odoo/odoo/issues/7287#issuecomment-116594767

**Comment by fossoult** [comment]
Nop. 
The "onwrite" function is launched when the user click on the "save" button after he click on the line on the tree view (Just tested). You don't even need to really edit the line. juste pass in edit mode and save to trigger the onwrite function..


In my case: 
I want to reload the data on the screen (or the many2many field data on a form view) after clicking on a button on a line which launch a wizard through a action. The wizard will allow you to split the line so you want to reload the data of the screen to see the new lines added.
----

Actually there is several way to fix this bug.

1. My pull request will allow you to refresh the data easily by adding a attrs on the tree tag.
2. The "onwrite" function could be also called when the user open an action by clicking on a button on a line. but the function should be called just after the action. But it have to be analysed because if the action return a redirection to an other action...
3. The developper could have to possibility to configure the return of an action to have the possibility to return a list of ids in a kind of m2m way :
    - new list to show: [6,false, [x, x, x]],
    - add new elem : [4, [x, x, x]]   -> Improve performance
    - remove elem...
Actually an action cannot return a lot of things.. (see do_action on view.js) and I think it's a lack of opportunities...

I think the best way if the 3, then the 1. But i'm afraid you didn't do it yet before because you're blocked technically ? If yes my pull request which is "simple" should be the best way :)

**Comment by beledouxdenis** [comment]
Well, there is nothing intended in the web client to reload new lines coming from a wizard within a list view.

This is seen as a new feature, not as a bug, and our stable policy prevents us to add new features within stable releases, such as 8.0.

Instead, return an action at the end of your wizard, forcing the reload of your list view. This is what we commonly do. Here is an example, which is a fix that has been done for a similar case than you have:
bdd5ec8216d375ef2baf3e9903c394a8f13061a1

Regards,

**Comment by tfossoul** [comment]
Do you know this options already exist on the M2M form field ? ( options="{'reload_on_button': true}" )
I just make it available on TREE view with this PR.

I suppose it's no way to think about commit it on the v8.0 and thinks later replacing the form M2M option and tree view new option by a "smart return on action". Because replacing it will be done in years (v11?)... I need my option today ): . If not i'll patch it.

**Comment by beledouxdenis** [comment]
I know this already exists on M2M fields, but this is not available in the tree view, and making it available is seen as a feature, which are not allowed in stable releases such as 8.0.

The workaround I just gave you is what we do for such a requirement.

Regards,

**Comment by tfossoul** [comment]
Yes I use it all the time to make "redirection". The problem with that is the fact you make a redirection and not a data reloading. That mean a new view is generated (the breadcrumb is updated). That mean you loose your search configuration you made before...

Concerning the "on_write" method : Could we consider the fact the method is not called after a system modification (not a user action) ?  -> my button split the line and change the field "quantity" to decrease it (this is the system modification). The data line is reloaded but the on_write is not launched.

It should be analysed deeper but : the on_write should be launched when clicking on a button because the system save all data before execute the action of the button. But launch it after the execution of the action should be a better way because the action could causes a modification of the data...
We could consider this as a bug :)

Regards (I'll not insist anymore..),

**Comment by Nasjoe** [comment]
Hi ! Same question here. Did you find a solution ?
I'm on Odoo 9.
Thx !

**Comment by Yenthe666** [comment]
Hi @tfossoul ,

Thank you for your bug report.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
