### ISSUE TITLE
[12.0] Deactivated "Product attributes" leads to internal server error on viewing product

### ISSUE THREAD

**Issue by em230418** [odoo/odoo#73112]
Impacted versions:
12.0, did not check on others

Steps to reproduce:
- Activate developer mode
- Settings -> Technical -> Views -> Search for "Product attributes" (xmlid is website_sale.product_attributes) -> Edit -> Set active to false -> save.
- Enter to any product page in `/shop` 

Current behavior:

ValueError: Element '<xpath expr="//hr[@id='hr_product_attributes_simple']">' cannot be located in parent view

Error context:
View `Product attributes table`
[view_id: 2673, xml_id: website_sale_comparison.product_attributes_body, model: n/a, parent_id: 2531]

Expected behavior:

No exception happens. Product page is visible without attributes.

---

For some reason "website_sale_comparison.product_attributes_body" is inherited from "website_sale.product", but not from "website_sale.product_attributes" where element hr[@id='hr_product_attributes_simple'] is defined.

Reproduced on https://8641593-12-0-all.runbot58.odoo.com/shop/product/customizable-desk-9

**Comment by rdeodoo** [comment]
Hello and thank you for reporting the "issue".
Cross xpath are not suggested indeed, we try to get rid of them when we can.
For this case, this exact flow was fixed in later version with https://github.com/odoo/odoo/commit/52c38367801e9378812f8709f1f5d6ba5ef107ac
Since it doesn't qualifies as a bug and is fixed in later version (+ it would anyway require a change which is against the stable policy), I am closing this one
