### ISSUE TITLE
[8.0]product_margin doesnt have option include proforma

### ISSUE THREAD

**Issue by falinwa** [odoo/odoo#7330]
Hello Odoo,

In product_margin module,
We don’t have option to include the proforma option.
It just have:
Paid
Open, paid
Draft, open, paid

Expected behavior:
It should include proforma option, e.g:
Paid
Open, paid
Proforma, open, paid
Draft, proforma, open, paid

**Comment by Yenthe666** [comment]
Hi @falinwa ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
You can add a payment method on the order so that it contains the proforma text/terms though.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).

Regards,
Yenthe
