### ISSUE TITLE
Add a 'post_startup_hook' to allow custom logic right after all modules are loaded and initialized

### ISSUE THREAD

**Issue by rbuisson** [odoo/odoo#73309]
**Impacted versions:** 14, 13, 12, 11

**Current behavior:**
It is currently not possible for an addon to run code after all modules are loaded/initialized.
The existing hooks (`pre_init_hook`, `post_init_hook` and `uninstall_hook`) only expose per-module flow.
Calling a hook once all modules are loaded and initialized allows developers to run code independently of the modules loading order, and basically making sure that all installation is done.

**Expected behavior:**
`post_startup_hook` hook allows to run custom code right after all modules are loaded and initialized and right before the server gets accessible.

Note that `post_startup_hook`is a tentative naming that can be subject to discussion.

**Comment by pedrobaeza** [comment]
You already have `post_load`.

Closing as no issue, but question.

**Comment by chinzou** [comment]
as seen [here](https://github.com/odoo/odoo/blob/0d0458a0f370f872caacac26361f2c4730c2cbba/odoo/modules/module.py#L391), `post_load` is executed after only that module is loaded where the proposed hook is for "after all modules are loaded"

**Comment by pedrobaeza** [comment]
That hook hasn't been needed during a lot of versions, and introduce it can provoke problems on the modular system, so you should find another way of solving your problem, whatever it is. In my 10 years developing with Odoo, I haven't needed such thing yet, so that may denote a missing piece in other part that makes you try to solve it through this.
