### ISSUE TITLE
[14.0] TypeError: '<' not supported between instances of 'bool' and 'datetime.datetime': Sorting records by date 

### ISSUE THREAD

**Issue by hugho-ad** [odoo/odoo#74078]
Impacted versions:
14.0

Steps to reproduce:
Modify purchase.report_purchaseorder_document template in order to add a sorting on lines

                    <t t-foreach="o.order_line.sorted('date_planned')" t-as="line">

https://youtu.be/93LvcQDHmS8

Current behavior:
 TypeError: '<' not supported between instances of 'bool' and 'datetime.datetime'
![image](https://user-images.githubusercontent.com/10233975/126540792-12f31f11-937f-4d25-80a3-f33f0efd29b3.png)

Expected behavior:
Sorting without errors
Video/Screenshot link (optional):
https://youtu.be/93LvcQDHmS8

Support ticket number submitted via odoo.com/help (optional):
### 2609833

**Comment by nboulif** [comment]
The `object.sorted()` that is used in XML is nearly the same as the python builtin `sorted()` (https://docs.python.org/3/howto/sorting.html).

Since the sort do a comparison, the values must be of the same type.
In the video, one of the order_line does not have a 'date_planned' (this is the `Notes` line).
Therefore, at one point of the sorting, it will try to compare a setted value (ex datetime: 01.08.21) with
a non-setted value (False) who will raise an error.

Here what I can suggest you do; replace the following code in the `report_purchaseorder_document` template:

Replace this line :

  ```xml 
  <t t-foreach="o.order_line" t-as="line">
  ```
By this :

```xml
<t t-set="bulk_lines_1" t-value="o.order_line.filtered(lambda l: l.date_planned).sorted('date_planned')"/>
<t t-set="bulk_lines_2" t-value="o.order_line.filtered(lambda l: not l.date_planned)"/>
<t t-foreach="bulk_lines_1 | bulk_lines_2" t-as="line">```
