### ISSUE TITLE
Empty string is a value for Odoo, except from UI

### ISSUE THREAD

**Issue by corentinpb** [odoo/odoo#7414]
An empty string is a value for Odoo, except from UI. Consider an example :

name = fields.Char(required=True)

self.create({'name': ''})  # Returns an id. So '' is accepted as a value not null in Odoo. WTF ?!

**Comment by nim-odoo** [comment]
Hello,
A required field is indeed converted into a 'not nullable' constraint in SQL. An empty string is considered as a non null value by PostgreSQL, so the value is accepted. The behavior in the UI is different, because an empty field will be converted into a "False" or a "None" value by the JavaScript widget, which will be interpreted as null by PostgreSQL.
There is no plan to change this behavior. Indeed, at the level of the backend, we can make a distinction between an empty string and a null value, and it can be handy to keep this distinction. However, at the level of the UI, there is no way to make this distinction, therefore we assume an empty string correspond to a null value.
Regards

**Comment by corentinpb** [comment]
I know and understand the technical source of this bug. But I can't understand why you refuse to fix it. From a user's perspective, Odoo has an inconsistent behavior from a UI action and from a XMLRPC call.

**Comment by michaelkarrer81** [comment]
@nim-odoo
I do fully agree with @corentinpb  and personally i think it is NOT handy to have this distinction but a great source for misunderstandings and errors.

## Example from the user perspective:
A user searches in the web interface for *firstname is not set* ```[('firstname', '=', False)]``` He would definitely also expect to find any *empty* firstname also!

**But** any firstname with an empty string would **NOT** be found! **The user would have absolutely no idea why!** From the user perspective odoo seems broken at this point.

He would need to search for *firstname is not set or firstname is ""* ```['|', ('firstname', '=', False), ('firstname', '=', '')]``` to get the expected result which is really no where near reasonable for a normal user!

## Viewpoint of a programmer
Even as a programmer one has a hard time to always include  ('fieldname', '=', '') as an OR in any domain in the code where one needs to search for an empty char field!

The situation gets even worse with webforms done in odoo website qweb templates. You would need to think all the time if the field is just an empty string or Null ?!? 

Why not clean things up and always convert empty strings to Null > Which for me seems also the correct behaviour for required fields because in 100% a user would expect that a required field can not be filled empty = ""! But now with web controllers one could make a form add a requried field on it and then expects odoo to throw an exception if the field is not filled BUT this will never happen because "" is not translated to Null!

## Solution without fix from odoo?
@nim-odoo Could you name me at least one real real case right now in odoo where an empty string in an field should not or could not be converted to a Null ? 

If there is no case do you think it would be ok to overload the common write method to just convert any empty string to a False or None?
