### ISSUE TITLE
[14.0] Form builder submit error

### ISSUE THREAD

**Issue by ptoffy** [odoo/odoo#74486]
Impacted versions: 14.0

Steps to reproduce: Submitting a form created with the Form Builder.
 
Current behavior: The form has not been sent error. I have found that removing the language specification in the form action solves the error but I can't find a way to do that permanently, only using the HTML editor.

Expected behavior: The form gets sent and I am redirected to a confirmation page.

Video/Screenshot link (optional):
![Screenshot from 2021-07-30 13-16-13](https://user-images.githubusercontent.com/69189821/127645428-65c90c11-29ae-4290-a74c-b421b90127b1.png)

This is the form action, I need to remove the /nl_Be/ part.
![Screenshot from 2021-07-30 13-18-21](https://user-images.githubusercontent.com/69189821/127645550-95b1df8b-d899-4991-bf76-bf4c92b0c5de.png)

Support ticket number submitted via odoo.com/help (optional):

**Comment by pedrobaeza** [comment]
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - click on the blue door icon of the version row - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by ptoffy** [comment]
I don't have the possibility to test with the runbot, but I have found out that removing the language prefix from the form action solves the error, so I need to find out how to do that.
I think that this code should help with the issue since it should remove the language prefix from the form action, although I think it's not working (?), correct me if I am wrong.

![Screenshot from 2021-08-02 09-09-41](https://user-images.githubusercontent.com/69189821/127818766-6abd50ee-f4cb-4594-8fec-25be391fb8cb.png)

**Comment by ptoffy** [comment]
Thanks, solved by updating the Website Form module
