### ISSUE TITLE
[Functional][Buggy Odoo] No currency rate associated for currency 177 for the given period

### ISSUE THREAD

**Issue by tejastank** [odoo/odoo#7466]
Regarding currencies to remove.

Accounting -> configuration -> currencies.

Try to remove some it gives me 

"No currency rate associated for currency 177 for the given period"

Even period not relevant to this currency, we not using it too.

Hope you can soon fix them & update code.

**Comment by kingsleyuk2003** [comment]
I have encountered this error. The solution is to make sure you have at least two entries for the currency rate on the currencies configuration (Accounting->Miscellenous->Currencies) for the base currency and the counterpart currency.  The currency rates must be set with a date that is, on or before the order date. That is just the solution. I had to debug it on my development environment to figure out why the system raises that constriant error, depite having entered a single currency rate. Thanks. Please vote my answer if it solves your problem.

**Comment by pedrobaeza** [comment]
You shouldn't remove any currency, and now in later versions, there's an activation mechanism, so this is not a problem anymore. Closing this.

**Comment by tejastank** [comment]
@pedrobaeza  Thanks, we keep enjoy #odoobugs in current version ;)  
Will be in future version with future bugs too :)

**Comment by nhomar** [comment]
@tejastank 

Odoo is a ["Data Driven" system](https://en.wikipedia.org/wiki/Data-driven_programming) that means in few words that "Data matters" to have the correct behavior, and one of such data is the list of currencies and the proper currencies, you have also a auto-update mechanim, and the message is a controlled one telling you that "you do not hav the rate", once you have that understood properly then you stop seeing *"Ghost Bugs"*.

This statement is [explained in the documentation](https://www.odoo.com/documentation/10.0/howtos/backend.html#data-files), I strongly recommend to you read such documentation will help you to move forward faster and stop spreading sarcastic comments on threads and people that is trying to help you.

Thanks in advance for use odoo and help us to document better things.

Regards.

**Comment by tejastank** [comment]
@nhomar thanks for your philosophy and collecting wounderful words... technically it did not works ;) 
Just don't get fear of Bugs.... when such no bugs or issues. keep in mind poeple had alternative... 

So instead to doing flattery and fabrication of odoo over technical part. provide solution or patch or guide how technically overcome in that situation.

I don't mind in case you not understand.

**Comment by nhomar** [comment]
>> So instead to doing flattery and fabrication of odoo over technical part. provide solution or patch or guide how technically overcome that situation.

I think I gave you the information you need.

Just in case I can compliment something.

**Create at least 2 rates for your currency with a date before the one you need, no patch need just a little willing to do the job and understand the other part.**

**Option 2** Set active == False to the one you want to delete.**

**Option 3** Delete it... < THIS IS NOT AN OPTION THAT'S WHY YOU AR RECEIVING THE MESSAGE.

I do not need to understand or not understand, the one that needs to do a little effort to receive the help is yourself if you are not happy you just need to give a little more information (maybe I miss something).

I kindly ask you.

1. Not know how something works, does not mean it actually does not work.
2. Try to give me the benefit of the doubt, and create a rate, that all that you need to do.
3. The "Why" is in the email I just sent before.

Remember, nobody here has ANY obligation to help anybody, if you want to receive an obligated answer, try to buy professional services from Odoo and/or a professional, here we are all trying just to help and *for free*.

If you give more information (maybe I am missing something) like the version or something else, it can be better helped, this issue has too much time open and it is not because we do not want to help, maybe (give the benefit of the doubt) it is because we did not understand you or you are not explaining properly with enough information.

I hope it helps.

**Comment by mart-e** [comment]
Due to the repeated aggressive tone (https://github.com/odoo/odoo/issues/16056#issuecomment-309340823, https://github.com/odoo/odoo/issues/8514#issuecomment-194826027, https://github.com/odoo/odoo/issues/1880#issuecomment-52903140, https://github.com/odoo/odoo/issues/7019#issuecomment-222604898, https://github.com/odoo/odoo/issues/7085#issuecomment-224809626...) or failing to give useful information(https://github.com/odoo/odoo/issues/10931#issuecomment-186259362, https://github.com/odoo/odoo/issues/3443#issuecomment-61458005, https://github.com/odoo/odoo/issues/4544#issuecomment-68836908,...) with the one that are trying to help you to a point beyond bad faith, @tejastank is now the first person to be blocked on the Odoo repository.

I was hoping we could manage a solution but, after almost 4 years, it seems sadly that we can not discuss constructively with him.
