### ISSUE TITLE
Miss `pdf` in _index content attachment

### ISSUE THREAD

**Issue by peter-dinh** [odoo/odoo#74929]
Impacted versions: 12.0, 13.0

Video/Screenshot link (optional):

```py
FTYPES = ['docx', 'pptx', 'xlsx', 'opendoc']
```

**Comment by Yenthe666** [comment]
@mart-e hmm what do you think? :)

**Comment by mart-e** [comment]
I think it lacks of details :)
The pdf was added at 183af97168f38d4be20236dff76beecd8f009447 so it's there in 14.0 but not in 13.0.

**Comment by peter-dinh** [comment]
i used `_index_pdf` on version 12.0 & 13.0 but it is not working right

**Comment by mart-e** [comment]
@peter-dinh sorry but you have to give more details on what you are trying to achieve and why you think there is a bug.
You may refer to #30692 where we deactivated the indexing of pdf because of bad results made by the indexing of PyPDF2.
This was fixed in 14.0 at 183af97168f38d4be20236dff76beecd8f009447 but as this introduce a new dependency, we could not add it in the previous versions.
If you are having issues related to this, you may want to try to cherry pick this commit to port it in your deployment but at your own risks.

**Comment by peter-dinh** [comment]
Thanks @mart-e . i agree that PyPDF2 is not as expected. i will refer to version 14.0.
