### ISSUE TITLE
[8.0] External dependency for auth_ldap is wrong

### ISSUE THREAD

**Issue by csrocha** [odoo/odoo#7508]
The real external depedency for auth_ldap is python-ldap and not ldap.

Ref: http://www.python-ldap.org/download.shtml

**Comment by mart-e** [comment]
Seems like the one [we already install](https://github.com/odoo/odoo/blob/433351f566e82a5ea45809ef1895f26f122bfe91/setup.py#L152) in dependencies.

Please clarify the report if you mean another dependency.

**Comment by Olivier-LAURENT** [comment]
Hi @mart-e, maybe @csrocha pointed the manifest, i.e.
<pre>
    'external_dependencies' : {
        'python' : ['ldap'],
    } 
</pre>

**Comment by mart-e** [comment]
I don't think so, this is the lib that should be imported (`>>> import ldap`), it would fail if you put `python-ldap` there.
@csrocha please check [reporting guidelines](https://github.com/odoo/odoo/wiki/Contributing#reporting-issues) for proper issue format so we avoid losing time guessing what the issue is about.
