### ISSUE TITLE
[14] account: confirmed payments should not be deleted

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#75111]
Impacted versions: 14.0

Steps to reproduce: Create and Confirm/Post Payment.
Delete it

Current behavior: There is no Validation on deleting Payment.
https://github.com/odoo/odoo/blob/c0295d5844e2924e684312245e56e82be92458c1/addons/account/models/account_payment.py#L613-L617

Expected behavior: Only Draft/Cancelled Payment should be deleted.

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by bodedra** [comment]
@sswapnesh I don't think this is a bug. It will only delete Payment which is not reconciled against invoice.

Create an invoice and register payment. Now go to Payments and try to delete it. It will throw the following validation.

![Screenshot 2021-08-20 at 10-50-38 BNK1 2021 08 0001 - Odoo](https://user-images.githubusercontent.com/14229503/130274011-87bdfb3c-3580-4433-b23a-b4066edb5420.png)

We have reset to draft to delete reconciled payment.

**Comment by cvinh** [comment]
@sswapnesh I confirm the bug, it should not be possible to delete a confirmed payment because it deletes the validated journal entry also
@bodedra If you register directly a payment in cash (not from the invoice), it's not necessary reconciled as the invoice might come later

Our accountant expert thinks it's a critical issue

@Yenthe666 could you ping someone at Odoo SA please ?

Best regards to everyone

**Comment by Yenthe666** [comment]
@qdp-odoo can you check maybe?

**Comment by cvinh** [comment]
I pushed a PR to odoo to fix account_payment

On the other hand, account_bank_statement has the same behavior, actually we can delete a account_bank_statement that has been posted before... and it looks like it's deliberated... what do you think ?

**Comment by vin-odoo** [comment]
As I said on the PR above, I checked with Laurent (LAS) who told me this is intended behavior and thus not a bug.
Have a nice day :)

**Comment by cvinh** [comment]
Dear @vin-odoo here is the use case why we need this fixed : 
A company registers payments before they know if they have an invoice related to. At the end of the story, a lot of payments were mistakes and have to be reimbursed to the customers or transfered to another company.
The payment should not be deleted because if so, there is no trace anymore in the accounting. Some employee could steel the money then (if it's cash or unlabelled check)
Can you please reopen the issue as our accountant expert thinks it's a huge issue and it would be difficult for him to trust in Odoo ;-)

**Comment by tsb-odoo** [comment]
Believe me, if an employee wants to steal cash, the cash will be long gone and your priority will not be to investigate among your draft/cancelled or deleted payments whose original money it might be that got stolen. 

In Odoo, what you got is (unfortunately maybe) only a **representation of** cash money. This representation can be wrong, right ? What happens if your employee recorded 1,000 USD incoming while it was only but 100 USD. Did he make a mistake ? Or did he steal you 900 USD ?

I guess the issue is not to be found in Odoo when cash money disappears. 

Further, in v14, we removed the hash on cash journals because it would have conflicted with the v14 reconciliation where items on a cash suspense account can be turned into items on any other account upon reconciliation.

For those reasons, I agree with the first responders. Let's keep this ticket closed.

**Comment by cvinh** [comment]
@tsb-odoo thanks for explanation.
Then, how do you manage an accidental payment unreconciled deletion ?
BTW, we still would like to understand why do you allow posted payment

**Comment by tsb-odoo** [comment]
I don't manage it.

**Comment by tsb-odoo** [comment]
"BTW, we still would like to understand why do you allow posted payment deletion"
Odoo allows reseting them to draft, cancelling them, and delete them. Those moves are only temporary moves, they represent a flow that last few hours / days normally. And most of the time, from a helicopter view, they aren't meaningful.

**Comment by milwell** [comment]
Hello, I confirm this is a security issue,  I had a customer payment that was reconciled with bank statement. Then later on that payment was set to "Draft" then deleted.  If you look at the Journal entry for the Bank Statement line, you see still the Payment# on label and still credited to Outstanding Receipts.  Trying to search the Payment#, of course, will show nothing.  It would be better if we could see the Payment and know it was set to draft then cancelled.  Why can't it be just like in the Customer Invoice where in if a Customer Invoice was posted at least once you cannot delete it even when you set it to draft?

**Comment by cvinh** [comment]
@milwell for our production databases we patched with the PR above
