### ISSUE TITLE
[14] messages: export_data() takes 2 positional arguments but 3 were given

### ISSUE THREAD

**Issue by WatchingOn9** [odoo/odoo#75166]
Impacted versions: 14.0 (vanilla)

Steps to reproduce: Technical > Messages > Export

Current behavior: Prompt Server Error

![image](https://user-images.githubusercontent.com/9769260/129615661-f22e0bd2-ff49-465b-acef-5bcf7dc182a2.png)

`Odoo Server Error
Traceback (most recent call last):
  File "/opt/odoo14/odoo/addons/web/controllers/main.py", line 110, in wrap
    return f(*args, **kwargs)
  File "/opt/odoo14/odoo/addons/web/controllers/main.py", line 2000, in index
    return self.base(data, token)
  File "/opt/odoo14/odoo/addons/web/controllers/main.py", line 1951, in base
    export_data = records.export_data(field_names).get('datas',[])
  File "/opt/odoo14/odoo/addons/mail/models/mail_message.py", line 708, in export_data
    return super(Message, self).export_data(fields_to_export, raw_data)
TypeError: export_data() takes 2 positional arguments but 3 were given`

**Comment by pedrobaeza** [comment]
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - click on the blue door icon of the version row - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by WatchingOn9** [comment]
Hi, i found out this problem has been fix on Apr 27.

https://github.com/odoo/odoo/commit/02c3ecdefbe19c6a645c4a3ebd846e1c7126ca0f#diff-6039bdf622bf5417d796a812415303924107a9c8b37be05731aeaedd10beab21

My code base is outdated, thank you.

**Comment by sswapnesh** [comment]
Fixed in https://github.com/odoo/odoo/commit/02c3ecdefbe19c6a645c4a3ebd846e1c7126ca0f
