### ISSUE TITLE
JSONRpc 14.0 does not support API Keys

### ISSUE THREAD

**Issue by fotisp** [odoo/odoo#75331]
Impacted versions: 14.0

Steps to reproduce:

1) Run a vanilla instance of Odoo 14.0
2) Create an api for the Admin user as per the [documentation](https://www.odoo.com/documentation/14.0/developer/misc/api/odoo.html)
3) Assuming you are running on localhost:8069  call the following cURL using the key as the drop in password replacement

    curl -X POST 'http://localhost:8069/web/session/authenticate' -H 'Content-Type: application/json' \
                                                                         --data-raw '
    {
        "jsonrpc": "2.0",
        "params": {
            "login": "admin,
            "password": "[the generated api key]",
            "db": "odoo"
        }
    }'

Current behavior:

We get an Access Denied error

Expected behavior:

Based on the documentation an API key should be a drop in replacement for the password when authenticating. However this only works when using the XML_RPC API and not when using the JSON rpc API.

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by pedrobaeza** [comment]
@Yenthe666 I remember an issue about this from your side.

**Comment by Yenthe666** [comment]
Hmm I believe it was authored by somebody else & I joined in but can't seem to find it anymore 🤔 
@odony can you join in? I know you've been active on this part a bit too.

**Comment by odony** [comment]
You're mixing two different kinds of API, but the confusion is understandable because Odoo has 2 different JSON-based RPC APIs.


The API keys defined in the user preferences are meant to replace two-factor authentication for [non-interactive API calls](https://www.odoo.com/documentation/14.0/developer/misc/api/odoo.html#external-api) where it's impossible to perform 2FA. This corresponds to the stateless XML-RPC (`/xmlrpc/*`) and JSON-RPC (`/jsonrpc`) endpoints, typically operated with rpc libraries.

However, your `curl` example is using the *stateful* JSON-RPC endpoint, which is meant for browser-based calls only (the web client), and requires the establishment of a browser session with cookies. In this context, API keys are forbidden, and the full two-factor interactive flow is meant to be used. This is done to clarify the separation between interactive and non-interactive contexts.

**Comment by fotisp** [comment]
@odony Thank you for the clarification.
