### ISSUE TITLE
[14] (Security issue) Odoo changing the session's user by itself

### ISSUE THREAD

**Issue by bencherfa** [odoo/odoo#75419]
Impacted versions: 14.0

Steps to reproduce: log out ,exit the navigator before reopening it to connect to a user

Current behavior: many times,Once the user(for example a user 1 registered to the instance) exit the navigator or log out and try relog in once more, odoo change the user using the session by itself(to another user )

Expected behavior: not changing user using the session( must request credentials and not change the session user by itself )

**Comment by hoangtrann** [comment]
- Do you have multiple tabs open at the same time, logging in to the same instance using a different account?
- Can you reproduce the issue on runbot.odoo.com? A video showing how to reproduce the issue is apprecicated

**Comment by bencherfa** [comment]
Thank you for your reply, no there isn't any other tab in my browser connected, and this problem occure in 2 separate devices (the device should be logged in different users but sometimes odoo connects them on the same one  when one of them is disconnected) and also when i log out from my user, close the window , reopen my navigator and enter to the server's url(self hosted odoo 14 community) the server connects my device to a user registered in my instance(i never logged with it before and dont know it password this issue occures some times)

**Comment by pedrobaeza** [comment]
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - click on the blue door icon of the version row - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.
