### ISSUE TITLE
[14.0] *: translations not exported/loaded for OWL dialogs

### ISSUE THREAD

**Issue by Yenthe666** [odoo/odoo#75426]
Impacted versions: 14.0 At least

Steps to reproduce:
1. Create an app which has an OWL component (dialog) which is loaded in the frontend.
You can find a sample module `website_rentals` at https://github.com/Yenthe666/rental
2. Install this app on a latest 14.0
3. Activate multiple languages, for example `French`, `German` and `German (CH)`

Current behavior:
Two things:
1. After you've installed the module go to Settings > Translations > Export translation and export for example to `German / Deutsch`. You will see the following terms being exported:
![image](https://user-images.githubusercontent.com/6352350/130416864-84f8f192-d71a-45ca-b986-81b0cb323f68.png)
However, terms such as "No quantity available" are not being exported (ref https://github.com/Yenthe666/rental/blob/3c30a16ef446a8a22b35f7b69d00c92241c6d891/website_rentals/static/src/components/RentalWizard.js#L63)
2. If we manually generate translation terms and add them to the `.po`  file it seems to work or major languages such as French (`fr.po`) or German (`de.po`) but not for sublanguages such as `de_CH.po`. A sample for french can be found for "to" in https://github.com/Yenthe666/rental/blob/3c30a16ef446a8a22b35f7b69d00c92241c6d891/website_rentals/i18n/fr.po#L153 and https://github.com/Yenthe666/rental/blob/3c30a16ef446a8a22b35f7b69d00c92241c6d891/website_rentals/i18n/de_CH.po#L152
If we render it in French:
![image](https://user-images.githubusercontent.com/6352350/130417624-d49682d4-476a-4b2b-9a7e-e059da207791.png)
If we render it in German (CH):
![image](https://user-images.githubusercontent.com/6352350/130417696-db8212dd-ff24-4af4-bbb3-262ee4c4b881.png)

Expected behavior:
1. The terms in an XML dialog written in OWL should be exported just like we have with normal views.
2. If we manually add terms it works for major languages (`fr.po`, `de.po`, ...) but doesn't seem to work/load for sublanguages such as `de_CH`

**Comment by Yenthe666** [comment]
See also:
- https://github.com/Yenthe666/rental/issues/3
- https://github.com/Yenthe666/rental/pull/5#issuecomment-900616769
- https://github.com/Yenthe666/rental/pull/8#issuecomment-902215182

**Comment by Yenthe666** [comment]
@mart-e could you please take a look at this and see what is going on? OWL in combination with multi-lang is giving us a bit of a headache :)
CC @holdenrehg who's working on this
CC @ged-odoo because he gave us a good feedback/pointer on https://github.com/Yenthe666/rental/pull/5#issuecomment-900616769 but there seem to be additional issues.

**Comment by mart-e** [comment]
@Yenthe666 do you have f1d403723d59b8e53b00cf2d26bd9d3d54437803 in your source code ?
I haven't worked on OWL so for all the client side aspect the @odoo/rd-framework-js team should be more helpfull.

**Comment by Yenthe666** [comment]
@mart-e yeah we do, we're always at most 2 weeks behind on the latest source code :) Curious to see if anyone from the framework-js team can help us. I tagged you cause I thought you where the right guy due to translations 😰

**Comment by sdegueldre** [comment]
@Yenthe666 as far as I'm aware, we currently do not have extraction for xml templates declared in javascript, the "proper" way to do it is to declare the template in an XML file in your /static/ folder and add it to the web.assets_qweb bundle in your manifest, giving it a unique identifier under the `t-name` key in xml, and assigning that to your component's template field in javascript. This only works in the backend.

As far as using owl in the frontend, there is currently not much support built into the framework for it. You can probably achieve what you want by placing the xml file in static as suggested before, but adding the file path to the assets_qweb in the manifest won't work, you'll need to load the template manually (using fetch or an XHR), and then add it to owl's QWeb instance with `addTemplates`. The way that non-owl widgets load their XML in the frontend is by using the field xmlDependencies which will automatically fetch the xml files and add them to the QWeb engine, but you'll need to do something like that yourself because the legacy widget's QWeb engine and owl's QWeb engine are not the same, and there is currently no builtin mechanism to do that for owl in the frontend, although you can probably write a hook equivalent to the old xmlDependencies system. Something like:

```js
export function useExternalXml(urls) {
  const env = useEnv()
  onWillStart(async () => {
    const requests = await Promise.all(urls.map(url => fetch(url)));
    const contents = await Promise.all(requests.map(req => req.text());
    contents.forEach(xml => {
      env.qweb.addTemplates(xml);
    })
  })
}

// use it like:

class X extends Component {
  setup() {
    useExternalXml(['/module/static/yourfile.xml', '/module/static/yourfile2.xml']);
  }
}

X.template = 'some_template_defined_in_yourfile.xml'
```

(this code is just a draft and entirely untested)

**Comment by Yenthe666** [comment]
@sdegueldre thanks a lot for the detailed feedback! This really helped us and yes your solution does work :)
Is there any plan to add extraction for xml templates declared in javascript though? This would simplify things quite a bit.

**Comment by sdegueldre** [comment]
I don't think there is, we do not want to encourage definition of templates directly inside javascript files because it's not great for discoverability, it requires additional tooling to get syntax highlighting, and we'd need to parse JS files completely to make sure that what we're extracting is what we think we are, so I'd say there's very little chance that we do that in the future.

However I'd say there's a high probability that we make working with assets bundles much easier so that you no longer have to load your XML by hand, but I think that will have to wait for version 16 because we still have a lot on out plate for v15 and the release is fast approaching. This will also enable template inheritance using xpaths for frontend templates which is a big plus. Although I will tell you that we've made changes to the bundle system that will already afford the ability to implement such a system in user-code from v15 onwards, so if you can't wait for framework support for this feature it will still be possible to implement that yourself much like the hook I suggested for v14. (the hook that I've suggested should continue working in v15)

**Comment by Yenthe666** [comment]
Okay let's conclude we will get improvements in future versions but that for now it is a known limitation of the framework then :) thanks!

**Comment by Yenthe666** [comment]
@sdegueldre one more question.. how can you make sure that the template has been loaded before and that you do not reload it? See https://github.com/Yenthe666/rental/blob/14.0/website_rentals/static/src/js/useExternalXml.js which seems to be tried to reload every single time.
Our co-worker Rehg made a workaround by try/catching it (https://github.com/Yenthe666/rental/pull/13) but I can't imagine there is no saner way?

**Comment by sdegueldre** [comment]
Use a cache for the fetch promises:

```js
const fetchCache = {};
function useExternalXml(urls) {
    const env = useEnv();
    onWillStart(async() => {
        const requests = await Promise.all(urls.map(url => {
            if (!(url in fetchCache)) {
                fetchCache[url] = fetch(url);
            }
            return fetchCache[url];
        }));
        const contents = await Promise.all(requests.map(req => req.text()));
        contents.forEach(xml => env.qweb.addTemplates(xml));
    });
};
```
```

**Comment by Yenthe666** [comment]
Thank you so much! 🙏

**Comment by holdenrehg** [comment]
Thanks @sdegueldre !

Actually slightly modified the solution, because the error we were running into was from `env.qweb.addTemplate`. So even if you cache the fetch request, it would still try to add the template again and error out, throwing that the template is already defined.

Added in a filter to get if the request stream has already been read in and works well :+1: 

```js
const { useEnv, onWillStart } = owl.hooks;
const fetchCache = {};

function useExternalXml(urls) {
  const env = useEnv();

  onWillStart(async() => {
    const requests = await Promise.all(urls.map(url => fetchCache[url] || (fetchCache[url] = fetch(url))));
    const unreadRequests = requests.filter(req => !req.bodyUsed);
    const contents = await Promise.all(unreadRequests.map(req => req.text()));

    contents.forEach(xml => env.qweb.addTemplates(xml));
  });
};
```
