### ISSUE TITLE
Record created using assertRaises in unit tests

### ISSUE THREAD

**Issue by Sathors** [odoo/odoo#7570]
Hi,

With the following code with pyunit:
```python
def test_test(self):
    initial_rec_nb = len(self.env[model].search([]))
    with self.assertRaises(ValidationError):
        self.env[model].create(vals_that_will_raise_Validation_Error_in_constraint)
    self.assertEqual(len(self.env[model].search([])), initial_rec_nb)
```

**What I would expect**
That this test above pass, meaning that the record that failed on a constraint at creation did not get created, as is the case in the user interface.

**What is happening**
The record is created, leading to a different behavior between the testing environment and the web interface, hence tests that are impossible to write.

**Comment by xmo-odoo** [comment]
> That this test above pass, meaning that the record that failed on a constraint at creation did not get created

Records which fail Python constraints do get created beforehand or it wouldn't be possible to validate the records in the first place. The transaction in the HTTP dispatch layer simply rollbacks the creation on any error (including but not limited to a ValidationError).

If you try the exact same thing in your own Python code you'll see the same behaviour, and if you try this with an SQL constraint error the last line will completely blow up because the transaction is wedged.

> as is the case in the user interface.

That's not the case in the user interface.

If you want integration tests write integration tests. If you're writing unit tests, understand that their constraints are different and you're operating at a different level of abstraction. In this case you've had a validation error, why are you even looking at the number of records in database afterwards? You don't care, you just want to see that your validation function has caught the error in the original data.

**Comment by Sathors** [comment]
Hi @xmo-odoo,

Well, I do understand that unit testing has some limitations. But I guess they will be exactly the same if I use yaml tests, which are supposed to be for integration testing. Or I am missing something?

I wanted to witness and test this behavior of rolling back the creation of the record on a constraint failure.

As for your question on why I need this kind of testing, it is because I was using a sequence on my model, and I wanted to check exactly this behavior: that in the case of a constraint error at creation, that my sequence did not end up used.

I tried using rollback manually, but then all my testing setup becomes null.

Thanks for your reactivity though.

**Comment by xmo-odoo** [comment]
> I wanted to witness and test this behavior of rolling back the creation of the record on a constraint failure.

You can't do that from within Python code because the rollback is performed around user code.

> As for your question on why I need this kind of testing, it is because I was using a sequence on my model, and I wanted to check exactly this behavior: that in the case of a constraint error at creation, that my sequence did not end up used.

Fair enough. I don't know how `nogap` ir.sequences behave under savepoints /cc @odony (postgres sequences are non-transactional so they will get used and IIRC standard ir.sequence is backed by a postgres sequence)

> I tried using rollback manually, but then all my testing setup becomes null.

That would happen either way, the test and its setup are part of the same transaction, you can't rollback one without rolling back the other (unless you create savepoints and roll them back yourself).

**Comment by odony** [comment]
`nogap` sequences don't use PG-sequences in order to be transactional. They will thus be rolled back along with the rest of the transactions. That is, as soon as a rollback happens. As @xmo-odoo outlined, this will only happen automatically if you go through RPC entry points, the only places where the system can do a meaningful rollback/retry. You could do this in a web test or RPC test (there are examples in our codebase), or you have to manually craft a request and send it to the RPC dispatcher.

**Comment by Sathors** [comment]
Thanks for the help, I think that now I understand more clearly the reasons.

So normally, using manually savepoints and rollbacks I should be able to resolve my problem then, and I will investigate using an RPC call.
