### ISSUE TITLE
fatal-remaining-connection-slots-are-reserved-for-non-replication

### ISSUE THREAD

**Issue by hengkysipocs** [odoo/odoo#7571]
when i use odoo website and request database (open connection to postgre) there are so many connection to postgre that did not close so when it is reach max con that we define in the postgre config it will error because old connection remain idle
![screenshot from 2015-07-11 14 21 32](https://cloud.githubusercontent.com/assets/8923229/8632894/e21d4d6c-27d8-11e5-9685-a0694ddbcab4.png)

**Comment by Yenthe666** [comment]
Hi @hengkysipocs,

This issue is related to the configuration of your postgreSQL / configuration and doesn't fall under the Odoo issues. Github issues are only used for bugs in the official code, not for implements and other software issues.
If you still face this problem I'd suggest you to create a topic on help.odoo.com (the official Odoo help forum) where there are plenty of people that can help you!

Regards,
Yenthe
