### ISSUE TITLE
[DOC] Incorrect reference (Not sure) on doc.

### ISSUE THREAD

**Issue by nhomar** [odoo/odoo#7591]
Hello .

In the new doc in the section of reports qweb we have this reference:

![Imh](https://www.evernote.com/l/AJ6r_HSGqkRPrIVgoJ2VvuCaQ1UooyaSCwgB/image.png)

Then, the correct reference that works for me was:

inherit_id="website_report.layout" instead "report.layout".

I have a theme installed and a report which only need to manage an specific css.

Am I right (The reference in doc has a problem if website + themes installed?) or did I miss something?

Regards.

**Comment by sle-odoo** [comment]
Hello,
You are right, once you install website the website_module report is installed and change [report.html_container](https://github.com/odoo/odoo/blob/8.0/addons/website_report/views/layouts.xml#L42). It was a workaround so that we would be able to use the website editor in the reports once the website module is installed.

I suppose we can change the documentation to tell the user to add their custom css classes directly into the report.style template, which is correctly included by both layouts.

Regards

**Comment by nhomar** [comment]
@sle-odoo Just as comment, take care about the fact that we need be able to add css files also, then report.style should be prepared to add both link to css and included css. (if you decide use it).

Regards.

**Comment by sle-odoo** [comment]
It's not possible to fix that correctly in 8.0, so to add css link tags you should apply an xpath on the minimal layout (used in pdf rendering). If you need html output then use an xpath on report.layout and on website_report.layout (if website installed). It's a pain i know.

Regards

**Comment by sle-odoo** [comment]
@nhomar 
Hello,
For your information, in v9 the website_report module has been removed as well as the report.style template, and assets are now used (see rev f26988cf7a1eb59de980eb73796ea964b2ee08ad), so that there is only one place to add your stylesheets.

**Comment by nhomar** [comment]
solved in v9 and above, the report engine is cleanest now.
