### ISSUE TITLE
Backend BUS Doesn't work with remote location of the database

### ISSUE THREAD

**Issue by alacret** [odoo/odoo#7607]
I'm having troubles with v8 when the installation of the database it's outside (ip connection) of the machine where i'm running the odoo.

I narrow down the problem to the connection, i tested:
-  the database version, 
- the modules version, 
- the demo data, - 
- the server port, 
- from clean databases

And the results are that, the server bus in the backend does not register the messages in the database, therefore the frontend does not receive the message.

I did this: http://stackoverflow.com/questions/30784771/reload-kanban-view-after-a-wizards-closes-in-odoo-8 to reload a kanban view, but when i install the database outside the server (different machines different IP) the backend bus doesn't work:

This does absolutely nothing:

```
    bus = self.env['bus.bus']
    message = {
        'subject': '',
        'body': 'Appointment Set',
        'mode': 'notify',
    }
    bus.sendone('<CHANNEL-NAME>', message)
```

And does not give any error message.

I am investigating more about this, but with no good results. I am attaching the logs and the databases dump (FYI: i've try to restore the local database dump in the remote server, but that didn't work either)

**Comment by Jerther** [comment]
Odoo checks the database for new bus_bus records since a number of seconds. Records seem to be written in the database with create_date set to the database time, but odoo does its query using the system time. This works if both the database and odoo are on the same system, but could very well break if they are not.

Here's an example:

time on db system: 10:00:00
time on odoo system: 10:05:00

sendone() write a new bus_bus record with create_date set to 10:00:00
odoo receives a notification on imbus so it does a query on bus_bus for records after 10:04:10, and finds nothing, so no notifications are sent, no error, no nothing.

10:04:10 is 10:00:00 minus TIMEOUT which is hard coded to 50 seconds.

So odoo has to run on the same system as the database, or the clocks have to be precisely synchronized (using ntp perhaps?).

You can fin the code that builds and run the query in addons/bus/bus.py, ImBus.poll() line 65.

That being said, it'd be nice if Odoo would get its current time for this query from the database instead, and it'd make more sens.

**Comment by Yenthe666** [comment]
Hi @alacret,

Thank you for your bug report.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
