### ISSUE TITLE
recursion in hr.empoyees Organization Chart

### ISSUE THREAD

**Issue by lnf83515** [odoo/odoo#76134]
Impacted versions: 14.0

Steps to reproduce: 
when [hr.employees.id] and [hr.employees.manager_id] is same

Current behavior:
it makes recursion in Organization Chart
![cap0001](https://user-images.githubusercontent.com/59425312/132440464-5f2b6746-842e-4104-90e1-c55b7f9df0b4.png)

Expected behavior:
do not make recursion in Organization Chart

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by Yenthe666** [comment]
@tivisse

**Comment by tivisse** [comment]
Hi @lnf83515 

Thanks for your feedback. 

Actually, this behavior is intended, and was required by our Product Owners team, in order to prevent an error or a traceback if you have a recursion in your company organisation.

You will find more explanation here: https://github.com/odoo/odoo/commit/48254cc8a153e061b64c399abb90cf4d4440bd65

Have a nice day,

Yannick.
