### ISSUE TITLE
Python version for Odoo 15.0

### ISSUE THREAD

**Issue by bealdav** [odoo/odoo#76148]
## Impacted versions: 
15.0

## Steps to reproduce:

Use Odoo in master / 15.0

## Current behavior:
As we can see here https://github.com/odoo/odoo/blob/master/setup.py
https://github.com/odoo/odoo/blob/saas-14.5/setup.py#L60
future Odoo 15.0 rely on python 3.6.

In the same time here is python calendar
https://endoflife.date/python

I think to support older python versions for a fresh odoo version has manydrawbacks 

- it prevent to use new python features in odoo itself or in any contributed modules (paid or free).
- it contrains developpers to support misc use cases (required at least for paid module)
- redondant CI workflows are played everyday to support these versions **it's not really good for planet**

With massive use of containers for production in IT it's no more a problem to have a different python version between container and host. Then it don't lead to update your server.

## Expected behavior:

An option could be to focus on the python version used in odoo.sh
Then only change to do is the version in manifest

cc @moylop260 @Yajo  @sbidoul @jcdrubay @jjscarafia  @pedrobaeza @yvaucher @guewen

**Comment by Yenthe666** [comment]
Yeah maybe we could at least bump it to 3.7 :) 
@odony @mart-e

**Comment by bealdav** [comment]
I have heard than odoo.sh have python 3.8

**Comment by Yenthe666** [comment]
Yes they do ;)

**Comment by bealdav** [comment]
Odoo policy seems to be version in last Debian stable

https://github.com/odoo/odoo/pull/71437#issuecomment-853865869

Last Debian stable is Bullseye/11 and has Python 3.9

https://wiki.debian.org/Python#Supported_Python_Versions

Then should we waiting for 3.9 for Odoo15 ?

**Comment by cvinh** [comment]
We use python 3.7 in production for v14 already (because of lack of security for python 3.6)
In development we use python 3.9 for v14

**Comment by mart-e** [comment]
> redondant CI workflows are played everyday to support these versions it's not really good for planet

Forcing people to upgrade is not good for the planet either (new hardware,...) :man_shrugging: 

We will see once Odoo 15.0 is actually released, maybe if one of the dependency is not compatible with 3.6, we will change that but franckly, if it doesn't cost a lot to allow people with older versions to keep running Odoo, I think it's a good thing to still be compatible.

Anyway @d-fence is our packaging expert for this kind of question and is the one that will probably decide in the end :)

**Comment by Yajo** [comment]
I think the question comes from the fact that we're getting ready our deployment systems for Odoo 15.0. Since most people (stats N/A) just use containers, we don't really care about Debian stable supported version anymore (I guess that made sense a decade ago, but today... 🤷🏼‍♂️).

So the main question is: **On which python version will Odoo S. A. run its production deployments for Odoo 15.0?** It is important, so we make sure to share the same bugs.

**Comment by bealdav** [comment]
Thanks for your reply @mart-e 

> Forcing people to upgrade is not good for the planet either (new hardware,...)

Upgrade is just once, CI cycle is for each PR at least.

I didn't know that recent recent version of debian or python required new hardwares (which ones).
Maybe you have news on this topic, it could be interesting.

It sounds weird to have a new fresh odoo version with deprecated python libs on next month (security)

Thanks

cc @d-fence

**Comment by d-fence** [comment]
It's not that simple but I agree that we have to bump the minimal version.
We have to take more situations than "most people just use containers".
1) our base policy is to stick to the Debian version at the time of the release : which is [3.9 in bullseye](https://packages.debian.org/bullseye/python3)
2) mix that with the ubuntu LTS ... widely used on servers: which is [3.8.2](https://packages.ubuntu.com/focal/python3)
3) take care of people who cannot update their Debian Buster [3.7.3](https://packages.debian.org/buster/python3)

So the minimal version for 15.0 will be 3.7.
I'll make a PR for that soon

Thanks for the issue and the comments.

**Comment by bealdav** [comment]
Thanks @d-fence for your quick reply.
That's the odoo's position and we respect it.

Now OCA have its own decision to take to run the CI : 

- follow the lowest python version compatible with Odoo (a future obsolete/unsecure version). This version is required by very few people in the community (probably also people running with a very old odoo version)
- use the mainstream python version (maybe the version use in .sh, 3.9 or 3.8), then we'll speak the same bugs as said by @Yajo 

And then this decision should be the OCA one not these of Odoo I suppose.

my 2 cents

**Comment by Yajo** [comment]
@bealdav I think OCA discussions don't belong here but in OCA mailing list.

---

Thanks, @d-fence. According to https://endoflife.date/python and https://endoflife.date/debian, python 3.7 and Debian 10 Buster will have a shorter support lifespan than Odoo 15.0 (3 years). Taking that into account, you may want to upgrade a little bit the baseline.

Besides, it would be nice to upgrade the `requirements.txt` file a little bit, but I understand it has security implications. I just wanted to mention that.






> our base policy is to stick to the Debian version at the time of the release : which is [3.9 in bullseye](https://packages.debian.org/bullseye/python3)

Is that the official answer to https://github.com/odoo/odoo/issues/76148#issuecomment-915906037?

**Comment by lem8r** [comment]
I've been testing custom Odoo docker images based on `debian:bullseye` to see if older Odoo releases can be run on Python 3.9.
Odoo 14 works fine because it has commit https://github.com/odoo/odoo/commit/4f03a5f136ab928ae74322bf1c34a1b6a6baf979 which replaces `base64.encodestring` →  `base64.encodebytes` and  `base64.decodestring` → `base64.decodebytes`.

But Odoo 13 doesn't. It means that it won't work on Python 3.9 since it has dropped encodestring/decodestring aliases.

https://docs.python.org/3.9/whatsnew/3.9.html#removed
> base64.encodestring() and base64.decodestring(), aliases deprecated since Python 3.1, have been removed: use base64.encodebytes() and base64.decodebytes() instead. (Contributed by Victor Stinner in bpo-39351.)

Seems like upper limit of Python is 3.8 for Odoo <= 13.0.

**Comment by sbidoul** [comment]
> So the minimal version for 15.0 will be 3.7.

I personally think sticking to previous debian stable pins it back to a very old version.

> mix that with the ubuntu LTS ... widely used on servers: which is 3.8.2

Regarding Ubuntu LTS, there is an easy and well supported solution (the deadsnakes ppa) to install any python version so that should not be a blocking factor.

> take care of people who cannot update their Debian Buster 3.7.3

Is a Debian upgrade a significant part of an Odoo migration project ?

One must also take into consideration the fact that the [Python release cadence is accelerating](https://www.python.org/dev/peps/pep-0602/).

**Comment by mart-e** [comment]
By the way, 3.7 min was forced by @d-fence at 794677fb6a3391379200eb2144a6ed372e89c17a so I guess we can close this one
