### ISSUE TITLE
Reached maximum value of sequence "ir_translation_id_seq" (2147483647): SequenceGeneratorLimitExceeded

### ISSUE THREAD

**Issue by MohammadSalek** [odoo/odoo#76188]
_Impacted versions:_
14.0 Ent

_Steps to reproduce:_
Creat a new database and install many modules (as my need). Add a new language and make it default. Re-run odoo-bin with `-u all` argument.

_Current behavior:_
During module update it appears:
`psycopg2.errors.SequenceGeneratorLimitExceeded: nextval: reached maximum value of sequence "ir_translation_id_seq" (2147483647)`

_Expected behavior:_
Expecting to see no `SequenceGeneratorLimitExceeded` errors. The sequence error in `ir_translation` is generated due to installation/removal of many translations that auto-increment `seq` for current table. After re-arranging the sequences with a custom postgres function (which removes the gap between available sequences by re-arranging), then the issue was solved. But I guess this problem could occur somewhere else as the posgtres limitation of `serial` is 2147483647 and some taken actions could push the limits. I don't think there is much to do about number of installed modules - they were necessary to install in the first place - and their translations. But I believe changing `serial` to `bigserial` in table creation mechanism could increase the limits up to 9223372036854775807 according [here](https://www.postgresql.org/docs/current/datatype-numeric.html). And this solves the mentioned issue for those odoo instances which have many modules installed.

**Comment by pedrobaeza** [comment]
As this debate is out of reach, as it requires support in the framework to bigint, and there are other threads opened for that, let's close this one.

**Comment by odoodaddy** [comment]
@pedrobaeza   you and your kind of nuts really showing off for ODOO.

ODOO community and enterprise both have plenty of bugs and you nuts keep trying to hide them.

You mentioned "other threads opened for that
![Screenshot 2021-09-15 at 5 34 44 PM](https://user-images.githubusercontent.com/44615008/133430167-13dd182e-93cc-4589-ab30-fd70d480bc53.png)


Please give a reference having exact details as @MohammadSalek reported.


@fpodoo have enough funded for fake people to hide bugs and drawback of ODOO.

@MohammadSalek mentioned is clearly bug and as well limiting ODOO, instead of accepting you guys closes issues and blocking users on github.com 

Welldone @fpodoo

**Comment by odoodaddy** [comment]
@MohammadSalek 

Solution that's working perfectly for me, I like to suggest here.

1. take backup of your database
2. via SQL update int to bigInt


Go to terminal of your server
login to your database

sudo su - postgres
psql -d mydatabase

mydatabase=# ALTER TABLE ir_translation ALTER COLUMN id TYPE bigint;
-> result : ALTER TABLE

mydatabase=# ALTER SEQUENCE ir_translation_id_seq AS bigint;  
-> result : ALTER SEQUENCE


int to bigint is essential when you working with some tables where its size going to increase a lot,
like customers or products in case its e-commerce 

I helps plenty of startup with very large scale business.

I hope @MohammadSalek this will be helpful to you.

**Comment by bursao** [comment]
Now it says psycopg2.errors.NumericValueOutOfRange: integer out of range
