### ISSUE TITLE
All applications can be moved to specific department stage. 

### ISSUE THREAD

**Issue by bene1505** [odoo/odoo#7729]
Impacted versions:

 - 8.0

Steps to reproduce:

 1. create a new stage in hr_recruitment
 2. specify a department on this stage
 3. drag and drop an application from another department to this stage

Current behavior:

 - all applications can be moved to a stage which has a specific department mentioned 

Expected behavior:

 - Only the application from the department specified should be accepted in this stage

**Comment by nle-odoo** [comment]
Hello,


I tried something in this diff: https://gist.github.com/nle-odoo/1c6dee64804808cda3e8  but since:

* it may broke other things and some external modules might have used it and expected it without the warning,
* the issue is more of a usability issue,
* it seems to be solved in master (where the module and the department has been changed),
* you could filter (in the search bar) on a department, this way is the best since you should also see the empty column (in your use case if you refresh without adding an application in the column, she will disappear).

It seems we will not solve this in stable 8.0 :disappointed: 

Thanks for your report.
