### ISSUE TITLE
[Imp]Proposal for messaging menu replacement

### ISSUE THREAD

**Issue by flotho** [odoo/odoo#7824]
Hi all of you,

I found that the new way of splitting the V8 messaging menu into sub menus is actually not such a bad idea. Yet, I don't think that having 4 menus in the top is more efficient regarding the UX especially for accessing to other menus.
I personally would have imagined a kind of "Start menu" in the top left corner that will be dynamic and show submenus (Chat/ note / agenda / contact) when hovering. This "Start menu" will be close to personal usage in everyone environment and also combined all the daily task in a single graphical menu without name.
The benefits will be real :
* No need to search for a name for this menu ;-)
* All those transversal menus could be stored in this one 
* The widget function could simply be done without changing the organisation of the messaging menu

It could also be done as the "Menu " of the odoo.com website, so nothing difficult to migrate.

Anyway, I really thanks all the team for the effort and hope this ideas could find some relay or any kind of interests from the community,

Regards

**Comment by flotho** [comment]
Hi @mart-e ,

I hope this message is in the right place.
regards

**Comment by mart-e** [comment]
Hello,

Thank you for your suggestion.
As you may know, the version 9 will have 2 different designs: the community (+/- the same as in version 8) and a new, for now, only available to enterprise customers. You can take a look at the current community master version [here](http://runbot.odoo.com/runbot/1/master) and the same master version but with the new design [here](http://runbot.odoo.com/runbot/7/master).

As you see, the new design has an app switcher that is +/- what you ask with a start menu.
As this the difference in both is only the representation, all the views and menus are still common to both design. This means that the menu hierarchy is also shared between both so that "apps" in the new design are top level menus in community version. When changing in one, we need to now consider two rendering.

We are still tweaking the menu organisation to find the best in both design. We are aware that the current menu disposition does not look good in the community version. The disposition is probably not the definitive so it may still change a bit before the release of version 9 (but *probably* no major changes either). It's probably in the rendering that we will be working (remember, still in dev).
If you would like to improve the rendering in the community design (so changes in CSS and JS), please feel free to submit a pull request.

**Comment by flotho** [comment]
The enterprise release looks awesome !

**Comment by mart-e** [comment]
Thanks for the feedback :-)
Keep also in mind that on the runbot, you are testing Odoo will every app installed. For somebody using only a few apps like CRM and sale, the number of top level menus will still be limited so it shouldn't be a big issue either.
However I am still convinced that splitting messaging/notes/calendar was a good move. These should be independent.
