### ISSUE TITLE
[15.0] module description (from within odoo) is rendered incorrectly

### ISSUE THREAD

**Issue by oerp-odoo** [odoo/odoo#78641]
**Impacted versions:** 
15

**Steps to reproduce:**
Create Odoo instance without installing any modules
Open any module from within Odoo instance, via Apps (that has description)

**Current behavior:**
It shows raw HTML instead of rendered and formatted text.  

**Expected behavior:**

Should properly render description.

**Video/Screenshot link (optional):**
![Selection_155](https://user-images.githubusercontent.com/7812986/137933246-ee575e35-fbd8-488e-be21-819a49e5e1ff.png)

**P.S.** Do note, if you install for example `mail` module, problem goes away. So it might be dependency issue where `base` odoo does not have some functionality that it expects.

**Comment by odooaktiv** [comment]
@oerp-odoo 
I have found what the underlying issue is.

Html field widget is defined in "web_editor" module. In previous version, it has only dependency of "web" and now in v15 they have added also "mail" as dependency. Hence, the HTML field only renders correctly after the "mail" module is installed. 

![Build 10633270](https://user-images.githubusercontent.com/32053757/138083566-a8e9c6d9-36e3-4837-a2c0-a8ea36dac6d7.png)

![Screenshot from 2021-10-20 16-34-59](https://user-images.githubusercontent.com/32053757/138083577-ee448b00-4384-454d-9455-b5ba83a436b2.png)

I can try to fix this but I am not sure how we can update dependency in a stable version or what is correct way to handle this. If anyone has idea please let me know. @Yenthe666 if you can help.

**Comment by Goaman** [comment]
Solved with: https://github.com/odoo/odoo/pull/80610
