### ISSUE TITLE
Upgrade Docker version 14 to 15

### ISSUE THREAD

**Issue by vincent41** [odoo/odoo#78877]
Affected versions: 15

Steps to reproduce: When I try to connect version 15 to the version 14 database I get an "Internal Server Error". Database manager has an exclamation mark This database may not be compatible.

But since Postgresql also runs on Docker, I can't run this script there
python <(curl -s https://upgrade.odoo.com/upgrade) test -d myDBname -t 15.0
because it shows me an error there / bin / sh: 1: Syntax error: "(" unexpected

what am I doing wrong?

Please help me

**Comment by davidmonterocrespo24** [comment]
Hello, you cannot connect a database created in version 14 to an odoo 15 installation, because they are not compatible.
If you want to use https://upgrade.odoo.com/upgrade you can do these steps
1- raising the database with the odoo instance with which it was created, try to make a backup:

![image](https://user-images.githubusercontent.com/47928504/139612904-f9aac098-53c6-4b0e-8f98-61afa8f8194d.png)

2-upload that database to this form .. [https://upgrade.odoo.com/] 

![image](https://user-images.githubusercontent.com/47928504/139613040-2f501b61-1b0a-410b-8173-6aec2930b476.png)


Wait for the base to be sent to you via email

**Comment by Yenthe666** [comment]
Indeed. You cannot simply run against a new version. You will need to migrate your custom code & the database itself.

**Comment by cliffkujala** [comment]
> But since Postgresql also runs on Docker, I can't run this script there python <(curl -s https://upgrade.odoo.com/upgrade) test -d myDBname -t 15.0 because it shows me an error there / bin / sh: 1: Syntax error: "(" unexpected
> 
> what am I doing wrong?
> 
> Please help me

The original poster wrote that he tried to upgrade the database from the command line, but since he is running Odoo in docker it would not work.  I have same situation.  

Are there any specific instructions on how to get command line version upgrades to work while running Odoo inside Docker?
