### ISSUE TITLE
[8.0] mail templates in marketing never translate

### ISSUE THREAD

**Issue by Endika** [odoo/odoo#7896]
I tested in Runbot (http://3112434-8-0-45b4b9.runbot2.odoo-community.org/)
When i sending email multi language, always arrives in English.
The email text should be translated to customer language, no?

My steps:
* 1- I install new language 
![screenshot from 2015-08-05 15 08 14](https://cloud.githubusercontent.com/assets/568585/9086296/dfaf3af4-3b83-11e5-8fd3-8a217fe0107a.png)

* 2-  Edit "Partner Mass Mail" email template
![screenshot from 2015-08-05 15 03 24](https://cloud.githubusercontent.com/assets/568585/9086387/6bdfa9d2-3b84-11e5-8286-9ea0ba392fff.png)

* 3- After save the email template. I translate the text.
![screenshot from 2015-08-05 15 03 29](https://cloud.githubusercontent.com/assets/568585/9086423/b0e75d7c-3b84-11e5-8111-76afcec4df88.png)

* 4- I go to "Customers" and search "Agrolait", Spanish customer.
![screenshot from 2015-08-05 15 06 19](https://cloud.githubusercontent.com/assets/568585/9086459/d7bc8e90-3b84-11e5-9c00-19b83ecef0b0.png)

* 5- After send "Partner Mass Mail"
![screenshot from 2015-08-05 15 18 23](https://cloud.githubusercontent.com/assets/568585/9086558/5c9696f6-3b85-11e5-81ec-74ef6f20b791.png)

* 6- And the end
![screenshot from 2015-08-05 15 20 34](https://cloud.githubusercontent.com/assets/568585/9086621/bc67113c-3b85-11e5-8dda-5333590abc1a.png)

**Comment by rafaelbn** [comment]
Why message take language from the res.user and not from the res.partner? Any sense?

**Comment by francoislawarree** [comment]
hi,

I have relaunched this issue to be fixed on the Odoo V8 release.

Regards,

François

**Comment by rafaelbn** [comment]
:+1:

**Comment by beledouxdenis** [comment]
Hello François, Rafaël,

The current behavior is the expected behavior.

To have an email template translated when sending it to a partner, you must:
 1. Fill the "lang" field of the email.template, with ${object.lang} in this case
 2. Not being in a mass mailing mode.

Indeed, if you use the partner list view as you do, and select multiple partners, with different languages, what should be done ? In which language should the email be sent ? 
 - The language of the first partner selected ? It doesn't make much sense
 - Display / preview the email in the user language, but send it in the customer language ? This isn't user-friendly at all, you won't see what is actually sent.
 - If you select two partners in two different languages, and change the content of the email in the email compose message, what should happen for the translations ? Send the modified content, not in the customer language, or send the translations without the modification you just did ?

If you want the email to be translated, you must send it from the partner form, from the discussion thread.

See the below video for illustration of the email template being translated as expected:
https://drive.google.com/a/openerp.com/file/d/0B5GVjjwUC-ygbXRQSTNaZHdMVFE/view?usp=sharing

I hope you will understand.

Regards,

**Comment by francoislawarree** [comment]
Hello Denis,

Sorry to re-open the issue but the work-flow defined for the the mass mailing isn’t as you described.

When you design a campaign of mass mailing here are the steps that i follow : 

-> you prepare your email in the 3 languages (EN-NL-FR) from the Marketing menu > Mass mailing template
-> you defined the list of partners concerned by the emails designed
-> the email is sent to them; the language of the partner is taken into account to send the good translation (EN-NL-FR)

In your explication, you start from the partner’s list view to make the mass mailing… but normally it should be the inverse… otherwise the "mass-mailing” module become useless and i design only email-template.

The use of “Mass mailing” module aims to define a large number of receipt partners and where the option to take their language into account is logical and should be allowed as for the email-template design.

Thanks for your return.

Regards,

François

**Comment by beledouxdenis** [comment]
Hello François,

> In your explication, you start from the partner’s list view to make the mass mailing… but normally it should be the inverse… otherwise the "mass-mailing” module become useless and i design only email-template.

This is not my explanation, this is the explanation given in 
https://github.com/odoo/odoo/issues/7896#issue-99206010

I strictly followed the case written in this issue.
Do you have a different use case ? If so, can you specify it, entirely ? With the menus path, what you do, what you fill, etc. So we can reproduce the issue using runbot

Regards,

**Comment by JonathanNEMRY** [comment]
Hi @beledouxdenis 
I think something should be done for this issue. I'll try to explain you why:
If the customer prepares a template into 3 languages and then he want to send a mail with this template to a lot of partners each speaking a different language.
Then this is not normal that the considered language of the mail will be the user and not the language of the contact that will read the mail.

Moreover as you said and as it is the current behavior: this is possible by sending a mail from the partner's form with a template. (see https://drive.google.com/a/openerp.com/file/d/0B5GVjjwUC-ygbXRQSTNaZHdMVFE/view?usp=sharing)
But for 1000 partners, that is not "user-possible"

So this specific behavior should be apply into a ```'composition_mode': 'mass_mail',``` too.

In order to answer to your questions:
[...and select multiple partners, with different languages, what should be done ? In which language should the email be sent ?...] 

* *[..The language of the first partner selected ? It doesn't make much sense...]*:fully agree with you that's why there is "${object.lang}" into email template, it could be rendered just as the other fields that are rendered for each partners and then translated.

*  *[...Display / preview the email in the user language, but send it in the customer language ? This isn't user-friendly at all, you won't see what is actually sent....]*: When you use ${object.something} you actually dont't see what will be send too. You could have a preview that take the first partner. But you are not able to see the complete result for each partners. Why should it be different with the translations?
* *[...If you select two partners in two different languages, and change the content of the email in the email compose message, what should happen for the translations ?Send the modified content, not in the customer language, or send the translations without the modification you just did?]*: Issue is talking about using template. If the user change the body-content then it will be not translated by contacts (native behavior of odoo translations). But for astronomic mass mailing :prepared templates are generally used without changing spontaneously before sending

I think it should be changed and works as described above

Regards,

Jonathan

**Comment by rafaelbn** [comment]
cc @Yajo @antespi  take care. We will touch this.

**Comment by JonathanNEMRY** [comment]
OPW 659027

**Comment by Yajo** [comment]
This seems fixed in master.

**Comment by rafaelbn** [comment]
@Yajo have you check v9? or only master?

**Comment by JonathanNEMRY** [comment]
OPW 660128

**Comment by rafaelbn** [comment]
@JonathanNEMRY what "OPW 660128" means?

**Comment by JonathanNEMRY** [comment]
hi @rafaelbn 
OPW means that this issue is referenced into an issue to the Odoo support

**Comment by rafaelbn** [comment]
Thanks

**Comment by Yajo** [comment]
I only tested on master.

**Comment by rafaelbn** [comment]
@pedrobaeza @Yajo @antespi be aware of this issue an this fix: https://github.com/acsone/mozaik/commit/09dbc54a2c2d87b21c2316118bb17d535a056600

**Comment by euroblaze** [comment]
Hello all,

has this issue been fixed for good. I am seeing similar wierd behavior in 10E, as [reported on the Forum](https://www.odoo.com/forum/help-1/question/german-language-salutations-119737).

What is "strange" is that my user-language is German, and all of the partner-languages are German too. Still all recipients receive English **salutations**.

Thank you
Ashant Chalasani

ps: we provide a [mail-marketing solution for e-commerce companies using odoo](https://www.simplify-erp.com/odoo-komplettloesungen/e-commerce/omnichannel-marketing/).
