### ISSUE TITLE
Issue Subtask not linked to Project

### ISSUE THREAD

**Issue by odooaktiv** [odoo/odoo#79558]
Impacted versions: V15

Steps to reproduce:
1. Create project and Task.
2. Create Subtask.
3. Hit on View task.

Current behavior: Subtask are not linked to project or Project is not fetched automatically from parent task.

Expected behavior: Subtask should be linked to parent task's project.

Video/Screenshot link (optional): https://www.awesomescreenshot.com/video/5943967?key=5cf9d185f380eee7a3cfe8c5a5f7bc40

Support ticket number submitted via odoo.com/help (optional):

**Comment by xavierbol** [comment]
Hello @odooaktiv, it is not an issue. When the `display_project_id=False` then the subtask is not shown in the *main* kanban view of tasks because by default we don't want to display the subtask. If the user wants to see the subtask in the kanban view of tasks then he can add the project in the `display_project_id` field.
However, the subtask is correctly linked to project with the `project_id` field. 🙂 

I hope everything is clear for you.

**Comment by odooaktiv** [comment]
Closing this as it is not a bug.
