### ISSUE TITLE
project seems to be drowning in pull requests

### ISSUE THREAD

**Issue by steverweber** [odoo/odoo#8016]
pull requests are good... but it seems to-many are queued up.

**Comment by lem8r** [comment]
Same thing with issues

**Comment by Yenthe666** [comment]
Hi @steverweber,

Thanks a lot for your 'report'.
It is indeed true that the amount of issues and pull requests have been growing quite big. This is the reason why Odoo has decided to try and start tackling this issue by closely monitoring issues. You can already see the result, since the amount of open issues has dropped with about 300+ in 3 months.
On the other hand we have the large amount of pull requests but there are a lot of PR's open that are still actively worked on and/or tested with. Most of those PR's are from Odoo itself though.

If you find any issue or PR that has been open for a long time and that you feel that should be really addressed you can ping me and I'll try to get things going.
P.S: I'm closing this one since it is not really an issue but a question, which I (hopefully) answered.

Regards,
Yenthe
