### ISSUE TITLE
MS 365 mail not working

### ISSUE THREAD

**Issue by oerp-odoo** [odoo/odoo#8021]
Does Odoo support 365 mail server? I can't seem to run it successfully.

Trying to send it, I get this error:

```
 Traceback (most recent call last):
  File "/home/oerp/openerp80/odoo/addons/mail/mail_mail.py", line 303, in send
    context=context)
  File "/home/oerp/openerp80/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/oerp/openerp80/odoo/openerp/addons/base/ir/ir_mail_server.py", line 503, in send_email
    raise MailDeliveryException(_("Mail Delivery Failed"), msg)
MailDeliveryException: (u'Mail Delivery Failed', u"Mail delivery failed via SMTP server 'smtp.office365.com'.\nSMTPDataError: 550\n5.7.60 SMTP; Client does not have permissions to send as this sender")
```

I'm using SMTP server  as `smtp.office365.com` Port `587` and  TLS (STARTTLS) encryption. Testing connection, returns that everything is fine.

There is this same problem for other people too:

https://community.office365.com/en-us/f/158/t/401406

It seems configurations from 365 side do not help.

P.S it looks as if Odoo tries to send as different sender than the one authorized. At least looks from the error, but it shouldn't send from different sender.

**Comment by Duvelken** [comment]
+1

Same issue, i made a special mailbox odoo@mydomain.com.
Connection test seems to be ok but no mails are sending.

on another post the solution was to set the odoo site domain into the same domain as the O365 domain. Test failed

setting it up with gmail worked fine.

any update on the issue ?

**Comment by i4knowledge** [comment]
Setup Office 365 SMTP outlook.office365.com 995 SSL/TLS fails -> Client does not have permissions to send as this sender
1. In Odoo setup a SMTP server user your mail exchange (MX) endpoint record with port 25
2. In Office 365 configure a connector so Odoo can send email to Office 365. Office 365 can then relay email to your organization mailboxes and to external recipients. Office 365 > admin > exchange > mail flow > connectors: configure a connector for your Odoo ("email") server with IP address.

**Comment by Duvelken** [comment]
hi i4knowledge,

i get what you are doing but can you give some more information about step 1 ?

thanks in advance.

**Comment by pedrobaeza** [comment]
This is not an Odoo issue itself, but a configuration question, so I close for triaging it.

**Comment by gdgellatly** [comment]
There is nothing special about office 365 mail. I use it in all versions
and in loads of other software. It will be configuration.

**Comment by AMhadhbi** [comment]
@gdgellatly while trying to add new outgoing Mail server SMTP Port : 465 and SSL/TLS I found message *Connection Test Failed! Here is what we got instead:1 [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:847)"** do you think also the issue related to wrong configuration? Thank you

**Comment by gdgellatly** [comment]
I don't know. Why use port 465? Does anyone still use that? Did anybody ever actually use that? Normally you would use 587.

**Comment by Dhananajay13** [comment]
Does anybody have solution to error
using office365 and port 587.

In outgoing server setting it give successful message. But mail are not getting delivered.

Below is the log 


Mail Delivery Failed
Mail delivery failed via SMTP server 'None'.
SMTPDataError: 554
5.2.0 STOREDRV.Submission.Exception:SendAsDeniedException.MapiExceptionSendAsDenied; Failed to process message due to a permanent exception with message Cannot submit message. 0.35250:0A006F81, 1.36674:0A000000, 1.61250:00000000, 1.45378:02000000, 1.44866:BB3C0000, 1.36674:0E000000, 1.61250:00000000, 1.45378:C03C0000, 1.44866:2A020000, 16.55847:571E0000, 17.43559:0000000004020000000000000000000000000000, 20.52176:140FC1880000101043050000, 20.50032:140FC1887017000000000000, 0.35180:48050000, 255.23226:0A007481, 255.27962:0A000000, 255.27962:0E000000, 255.31418:0A007581, 0.35250:0A000000, 1.36674:0A000000, 1.61250:00000000, 1.45378:02000000, 1.44866:24000000, 1.36674:32000000, 1.61250:00000000, 1.45378:29000000, 1.44866:01000000, 16.55847:90000000, 17.43559:00000000F0020000000000000000000000000000, 20.52176:140FC188000070200A007A81, 20.50032:140FC188701710106B050000, 0.35180:0A007B81, 255.23226:4800D13D, 255.27962:0A000000, 255.27962:32000000, 255.17082:DC040000, 0.27745:75050000, 4.21921:DC040000, 255.27962:FA000000, 255.1494:7A050000, 0.38698:00000000, 0.37692:01000001, 0.37948:1FDFF165, 5.33852:00000000534D545000000100, 7.36354:0100000000000109302E3232, 4.56248:DC040000, 7.40748:010000000000010B3A623434, 7.57132:00000000000000003965652D, 1.63016:32000000, 4.39640:DC040000, 8.45434:4240E406299456418586F61B5D17239610000100, 5.10786:0000000031352E32302E323234312E3030303A484B30505230344D42323430323A62343435386162342D613933662D343965652D393334352D61343939356537643164366400001007000000, 255.1750:0A008681, 255.31418:0A000D80, 0.22753:AC050000, 255.21817:DC040000, 4.60547:DC040000, 0.21966:B1050000, 4.30158:DC040000 [Hostname=HK0PR04MB2402.apcprd04.prod.outlook.com]

**Comment by gdgellatly** [comment]
It just works. This is not an odoo issue  In terms of setting smtp most of it needs doing in exchange admin, not odoo. Setting connectors, or mailboxes and associated dns mail relevant entries with dns provider.

**Comment by anderwm** [comment]
I use this same email address and smtp settings on ~5 other applications and it works fine. If you try to use ssl it says version mismatch and you get this error with STARTTLS.

**Comment by Dhananajay13** [comment]
I have fixed the issue.
for office365. you need to make sure "from email Id" in mail template is office365 id not admin@example.com or anything else. otherwise it blocks the connection.


Above solution will work only if your test connection in outgoing mail is working. If not please check your outgoing mail setting. for me its working on port 25 and 587 and TLS on.

**Comment by Dhananajay13** [comment]
@anderwm try and use above solution. It should work.

**Comment by anderwm** [comment]
Ok thanks. I am new to this software. Are you suggesting I should go into Settings->Technical->Email->Templates and change each of them? Or is there some other place more convenient?

**Comment by Dhananajay13** [comment]
Go to users and and change the email id of admin with office365 id.

If your mail template is by default taking admin's id then It should work.

**Comment by anderwm** [comment]
Thanks man, the template's from looked like this: ${('"%s" <%s>' % (object.company_id.name, object.company_id.email or user.email))|safe}
So I changed the company email to office365 ID and it works.

**Comment by eLBati** [comment]
To solve the original problem (`Client does not have permissions to send as this sender`) you could also use [mail_outbound_static](https://github.com/OCA/social/tree/12.0/mail_outbound_static)

**Comment by matteoopenf** [comment]
@eLBati confirm it works also on  odoo.sh
