### ISSUE TITLE
[8.0][website] Error if creating a page with name "info"

### ISSUE THREAD

**Issue by jarmokortetjarvi** [odoo/odoo#8022]
If you create a new page named "info" in the website-module, you will get an Internal Server Error:

```
Error message:

"'NoneType' object has no attribute 'get'" while evaluating
"version.get('server_version')"
```

How to reproduce:
1. Take a clean Odoo 8 installation with 'website'-module installed
2. Try to create a new page with name "Info" or "info".

**Comment by Yenthe666** [comment]
Hi @jarmokortetjarvi,

Thanks a lot for your report. I've just tested this and this is indeed a bug.
Example:
![image](https://cloud.githubusercontent.com/assets/6352350/17432081/980a285e-5afd-11e6-808b-ed23f9f20dca.png)

@JKE-be can you look at this please?

Regards,
Yenthe

**Comment by JKE-be** [comment]
@jarmokortetjarvi 
Thank you for the reporting.
I will try to add a warning.

But this route/'view name' is forbidden since the controller /website/info use it by default.

Maybe we could user other 'view name' for v10, but for stable version, it is not possible.

**Comment by Yenthe666** [comment]
@JKE-be it works in V9, so perhaps that should be backported.

**Comment by JKE-be** [comment]
behavior is not really the same...
Since v9, if you try to create a page which one already exists, the name is appended with a numbered suffix.

In v8, you was redirected... to the existing page.

So if we backport it, that will change the behavior from the stable version 8.
What I suggest is a redirect... directly in the view of website.info. but it will require a manual update of the view... or an update of website module to be fixed.

**Comment by JKE-be** [comment]
Thanks for the reporting 

Require an update of website to have the fix.
Or apply the diff manually in the view website.info
