### ISSUE TITLE
[Security] passwords are stored as cleartext in session

### ISSUE THREAD

**Issue by christophlsa** [odoo/odoo#8029]
I and @Benniphx found a possible security issue:

As you maybe know the sessions are stored in the filesystem (at ~/.local/share/Odoo/sessions). If you open the files you can find the cleartext login names and passwords of the users.

To print out all data of the session files you can use these lines:

```
from pickle import load
import os
for file in os.listdir('~/.local/share/Odoo/sessions/'):
    f = open(file, 'rb')
    print load(f)
```

In my opinion the login data shouldn't be saved as cleartext in the filesystem. Since odoo 8 the module auth_crypt is used to encrypt the password in the database to avoid persons to read the secrets. Everybody who has access to these session files can read the login data of the users. For me this is a security issue.

**Comment by lem8r** [comment]
Same thing with /etc/odoo/openerp-server.conf

Try to use password in format md5+long_random_password so it will look like md5 hash in plain text ;)

**Comment by mgielissen** [comment]
Almost all popular PHP apps have also a SQL password in plain text in their config.

**Comment by christophlsa** [comment]
Yes, sql passwords are the one thing. But if you get access to the database you can't read the passwords of the users. With the session files you can read the user passwords.

**Comment by wtaferner** [comment]
@odony 
I hope you guys are already working on a solution.
@christophlsa 
https://www.odoo.com/page/responsible-disclosure would have been the better way to report this or did you and no action taken yet?

**Comment by antonylesuisse** [comment]
This does not constitute a security vulnerability according to our security policy. In short, when you have access to the odoo code, data files and processes you can easily collect the passwords. You may patch the code to dump password or use pyrasite on a running odoo.

But if there is clean way to not store the password serialized in sessions without regression and  while keeping all the features we will be happy to merge it.

The code path is tricky because it involves authentication at the low level (/xmlrpc /jsonrpc) with the different auth_* mechanisms (password, crypt, oauth2, ldap ...) and authentication session based used by the other routes (/ /web ....) so you should make sure that you dont break or slow the slightest thing.

**Comment by wtaferner** [comment]
@antonylesuisse 
I am very sorry to hear your PoV. I admit it is hard to fix this BUT referring to your own [security page](https://www.odoo.com/page/security) you write...

**Password Security**
* Customer passwords are protected with industry-standard PBKDF2+SHA512 encryption (salted + stretched for thousands of rounds)
* Odoo staff does not have access to your password, and cannot retrieve it for you, the only option if you lose it is to reset it
* Login credentials are always transmitted securely over HTTPS

So, based on this you should adapt your security page as you say Odoo staff does not have access to passwords which is therefore not true ;-) 

Anyway, this needs to be fixed at some point...maybe something to promote the announced rerun of the security campaign...but still, as you said it is tricky who should be better in fixing this than the software publisher?

**Comment by antonylesuisse** [comment]
Odoo saas uses oauth no password are stored in session on the could servers.

If you want this to be fixed create a pull request to change it. Talk is cheap show me the code :)

**Comment by wtaferner** [comment]
Haha, to the point and I agree (Linus Torvalds)...so you recommend to use external mechanisms to stay safe about passwords in Odoo :-) Gotcha! I doubt I will do a PR soon for this one, but never say never ;-)

**Comment by llacroix** [comment]
Really? Why store the password in the session in the first place. If your session is authenticated you can simply mark it as authenticated and trust that the session is authenticated for that session id. If you add the password in the session it will always allow you to authenticate yourself so it doesn't really matter if the password is present or not in the session.

If the password changes, you only need to invalidate all the sessions for that particular user. Or even simpler a date field on the user could be stored making any session prior to that date invalidated. 

There is simply no need at all to store the password in the session.

**Comment by lasley** [comment]
I tried hard to work around this. The main blocker I ran into is how the JavaScript client uses RPC under the hood, which requires the password. 

I’ve created some malicious browser plugins and XSS PoCs that grab the password from the client as well. Basically a giant security hole that is insanely difficult to work around while still keeping RPC for JavaScript. The real solution is reimplementing the client to use Oauth2 and a REST client such as implemented [here](https://github.com/OCA/server-tools/pull/889)

**Comment by llacroix** [comment]
@lasley From my point of view, the problem could be fixed by odoo itself. Right now, storing the password inside the session is pretty much the same thing as providing the password along with an oauth token.

The problem as I see it is that if we can store information that the session is authenticated, there is no point to keep a password. It's redundant. The only thing that is required is prevent RPCs to create or modify sessions object directly. If the data in the session object is trustable, there is no need to keep a password to authenticate or check credentials.. You can take it for granted that the user is authenticate if the session id says so. In some ways, the session id isn't much different from a token in oauth. The only difference is that it keeps some data the same way you could have a session linked to your oauth token.

For xmlrpc, as you send the password on each request, there is no need to keep it in a session too. For JSONRpc, you can simply keep the same trust with the session_id. 

The logic here is if you can't trust the data in the session object so you have to store the password in it to check for authentication, then you can't in your right mind store a password in a container that can't be trusted.

**Comment by lasley** [comment]
Honestly the only difference in OAuth is that the tokens rotate, so they aren’t replayable. 

I’m not denying this is an issue that Odoo should fix, but we see their standpoint on this above. Take it from someone that’s tried to solve the issue - it’s more complex than it seems. My real solution is provide an additional encryption layer for confidential data (https://github.com/OCA/server-tools/issues/673)

**Comment by llacroix** [comment]
I'm not really arguing with you, it's the Odoo team's standpoint that is scary. Technically, the sessions are also rotated and have and have an expiry date. One other analogy would be to store the refresh token in the session on the server... This way any use that has access to your session can create himself a new session/token with the refresh token. Unfortunately, it's even worse than that because I'd expect a call to refresh token to actually invalidate earlier tokens. 

It's really deceiving that the odoo standpoint is pretty much to not solve this while people use this to store corporate data. I mean, stuff that gets in odoo aren't thing that don't matter much like a blog.

**Comment by lasley** [comment]
Oh yeah totally. My plan was to use Odoo as an EMR until I found this (and a few other glaring security issues). The plan is still there, but it because obvious earlier on that an out-of-the-box installation is not good.

An interesting side-effect to the passwords being plain text here is that if you are integrating with an authentication provider, such as Active Directory, the attack surface of the password exposure increases drastically.

In light of all this, we do not allow our customers to use Odoo authentication, and we created a module to disallow the changing of passwords for users in a certain group (we'll be releasing in OCA soon). Combine this strategy with an external OAuth provider (Gluu), and the system doesn't suck anymore.

**Comment by llacroix** [comment]
I discovered that while trying to print pdf from a cron job. It appears that we must provide a valid session to the wkthtmltopdf process. The wkhtmltopdf process needs this to find which database to look for and possibly access private resources. In this case, I'm not sure it's possible to work around this with a different authentication or the session can be authentified differently with something else.

**Comment by lasley** [comment]
Well technically it's still Odoo authentication, it's just using an [external OAuth provider](https://github.com/odoo/odoo/tree/10.0/addons/auth_oauth). I haven't run into any issues with reports or the JS client yet. I haven't checked the session to see what is stored for the password, but I don't see how it could be the actual password given the way that OAuth works.

By then disallowing the users from setting their password, you effectively lock them from entering a password into Odoo in the first place.
