### ISSUE TITLE
[14.0+] account: séquençage des factures illégale (France)

### ISSUE THREAD

**Issue by fmdl** [odoo/odoo#80442]
**Impacted versions: 14.0 and more**
Le nouveau système de séquençage des factures de la V14.0 pose un énorme problème légale.

En effet l'Article 242 nonies A du Code général des impôts, annexe 2, alinéa 7 indique : `Un numéro unique basé sur une séquence chronologique et continue`. https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000027356476/

En plus des possibilités de re-séquencer, ou de pouvoir écrire à la main un numéro.
Le fait que les séquences mensuelles (ou annuelles) reparte à zéro chaque mois pose un problème légale. En effet un contrôleur des impôts ne peut être sur qu'il ne manque pas des factures. La séquence n'est pas continue.

Afin de respecter la loi française, merci de faire en sorte que
- qu'il n'y ai pas de remise à zéro de la séquence
- que l'utilisateur ne puisse pas modifier le système de numérotation en cours de route
- interdire le re-séquensage (même pour les journaux non haché (le hachage des journaux n'est pas une obligation en France (sauf sur le POS)) (les comptables sont tombée des nues sur la possibilités de re-séquencer).

**Exemples:**
**_Illégale_**
Dernière facture du mois de novembre :  FAC/2021/11/0026
Première facture du mois de décembre : FAC/2021/12/0001

Il est possible de supprimer 0026 ou de rajouter 0027 après 12/0001, sans que cela soit visible par un contrôleur des impôts.

**_Légale (comme en V13)_**
Avant Dernière facture du mois de novembre :  FAC/2021/11/0026
Dernière facture du mois de novembre :  FAC/2021/11/0028 (car créée après FAC/2021/12/0027)
Première facture du mois de décembre : FAC/2021/12/0027

Ce problème m'a été rapporté par différents experts comptables et commissaires aux comptes.

Voici les spécifications pour mettre Odoo conforme aux lois françaises.
**Spécifications:**
Le numéro de facture est composé de la manière suivante : Prefix + Numéro de Sequence
- Le prefix n'a pas vraiment d'importance, il peut être `FAC` ou `FAC/année` ou `FAC/année/mois` ou autre chose. Il doit être unique par journaux. Si il y a année et mois on veillera à la cohérence avec la date de la facture. A partir du moment où il y a une facture générer il n'est plus possible de modifier le préfix du journal.
- Le numéro de séquence doit être unique et continu. Il y a un compteur par journaux. Le numéro de séquence doit être calculé lors de la comptabilisation (et non lors de la création). Le compteur démarre à 1 (ou à une autre valeur choisi par l'utilisateur, mais qui ne pourra être modifier dès la première facture comptabilisée). Il est incrémenté de 1 à chaque nouvelle facture comptabilisée. Il est jamais remis à zéro (donc prévoir des padding de minimum de 6). Il n'est pas possible de changer le journal d'une pièce déjà comptabilisée.
- Lorsque l'on change la date seul le prefix est mis à jour, le numéro de séquence reste le même.
- Il est interdit de supprimer une pièce qui a déjà un numéro de séquence (sauf pour les journaux d'OD et de banque).

Dans l'attente de votre retour.

@alexis-via 
@oco-odoo 
@qdp-odoo 
@fpodoo 
@sla-subteno-it

**Comment by fmdl** [comment]
OPW #2700236

**Comment by alexis-via** [comment]
I agree with you @fmdl 
For those who want to solve this now on v14, they should have a look at my community module **account_move_name_sequence** which restore the behavior of v13 with the use of ir.sequence to generate the number of the account.move (same datamodel as v13, for easier migration). This module also removes the ACL on account.resequence.wizard, so the wizard is not available to users any more.
This module is available here https://github.com/OCA/account-financial-tools/pull/1228
I **always** install this module on v14.

**Comment by oco-odoo** [comment]
Hello, 

Thank you for reporting this issue. 

The fact is, even though we let them the possibility to, people should not do that in France, and nothing forces them to. Therefore, we won't consider it as a bugfix to do in 14.0. However, we discussed it with the team and agreed that this feature should be improved on master. A task has been created in our pipe; we'll be in touch when it's merged.

**Comment by fmdl** [comment]
@oco-odoo can you make your fix in a special module for V14 and V15 (l10n_fr_sequence_fix) ?

Can you explain how french user can not use the current sequence system ?

**Comment by intero-chz** [comment]
@fmdl other language speaking users want to know that, too :-P

**Comment by tsb-odoo** [comment]
Hi @fmdl, 

Let's start highlighting some of the benefits of the resequence feature : 

1/ When importing invoices from a distinct invoicing/accounting package, in case of numbering error, it's super easy to align Odoo's sequence numbers on the ones of the original package.

2/ As said, there's nothing illegal in adding bills at end of October while November bills have already been posted. Now, suppose the user would have had an annual sequence on its vendor bills. He might decide to switch to a monthly one because - just like you - he feels the need to respect the law (incremental, continuous, chronologic). Thanks to the resequence feature, it's super easy. 

If we will not change behavior in stable versions, we though considered seriously the feedbacks received and kept improving the feature in v15. 

In v15, Resequence is : 
- a technical feature
- only available in debug mode, 
- for admin users or advisors only.

All changes in the sequences are logged in the chatter. So, there is clearly no intention to cheat.  

The examples given get immediately counter-balanced by the fact nothing in the law prevents a user to create a distinct journal per month and have as many journals as he would like in its accountancy. So, even independently from Odoo's features, the continuous numbering constraint is so easy to overcome. 

The default sequence on invoices is annual. So again, Odoo's suggested behavior is a continuous numbering.  
If you don't want any interruption between year N and year N+1, don't put meaning in the sequence (e.g. dont use /2021/ ). And it will work fine. 

If by accident, you did include "INV/2021/" in your sequences, then the Resequence feature will help you resequence the first invoice of 2022 (INV/2022/0001) into INV/2021/xxxx+1). In this example, Resequence is as much the solution to a potential problem as it brings the solution. It will help users respect the strictest interpretation of law. 

The resequence feature is not something we will abandon. 
Last but not least, users are certainly not forced to use if if they don't want to. 
Challenging business processes seems here more important than the feature itself.

Customizing is always possible, of course, with its own drawbacks too.

**Comment by qdp-odoo** [comment]
So, I suppose the above message of Benjamin settles this issue as nobody complains?

**Comment by fmdl** [comment]
@qdp-odoo @tsb-odoo I have speak with a french statutory auditor. The current system is too open (you can write any sequence, any prefix, ...). Can you add a solution (with ir.parameter for exemple) to block the prefix and prevent the reset sequence each. Or come back to the V13 system (or keep the two choice).

Can you fix that, if not your software it is not usable in France.
