### ISSUE TITLE
[15.0] stock.inventory model

### ISSUE THREAD

**Issue by rousseldenis** [odoo/odoo#81361]
@amoyaux Could you confirm that stock.inventory model has been removed and why ? In terms of usability, I think it is a drawback...

https://github.com/OCA/stock-logistics-warehouse/issues/1328

**Comment by amoyaux** [comment]
@rousseldenis Yes we removed the `stock.inventory` model and merge it in the `stock.quand`. In order to keep track of count we added a flag inventory on `stock.move` and create `stock.move.line` without quantity done for correct quantities.

However we tried to keep the same functionality as before.
For the different usability drawback I suggest you to contact @thomasdeleval directly

**Comment by rousseldenis** [comment]
@thomasdeleval Do you have a link to the documentation about that ?

**Comment by rousseldenis** [comment]
Ok, saw the presentation video.
