### ISSUE TITLE
[13.0, 15.0] Can't access to some attachments created by another user

### ISSUE THREAD

**Issue by Linekio** [odoo/odoo#81935]
Impacted versions:
13.0, 15.0
Steps to reproduce:
Add demo user to group Email Marketing>User
With admin user, create a mailing and add an attachment **before the first saving** .
With demo user, try to read the mailing.
Current behavior:
_Access Error: Sorry, you are not allowed to access this document._
Expected behavior:
Demo user should be able to access the mailing
Video/Screenshot link (optional):
https://swizzin.linekio.fr/filebrowser/api/public/dl/nFeKfg4p?inline=true 

Adding the attachment before the first save causes the attachment to have res_id=0.
See
https://github.com/odoo/odoo/commit/5e81850e#diff-ab3dadc37163820f8e863edb1dd216f8b0e7ccf19cf4e2052577a7bae7ddd7e8R352
and
https://github.com/odoo/odoo/commit/ad434b00163a4c033c2df403adb5f119ada347cb#diff-ab3dadc37163820f8e863edb1dd216f8b0e7ccf19cf4e2052577a7bae7ddd7e8R443

seems it's not merged in 14.0

**Comment by odony** [comment]
Thanks for reporting. As you've probably noted, a workaround is to save the mailing first, and only add the attachments afterwards.

This is due to the peculiar way static attachments are managed on mailings and mail templates: they're not attached to the document but merely linked with a m2m, so they're not correctly owned if the record doesn't have an ID when they're uploaded.

Hopefully #82105 will fix this (for 13.0, forward-ports will follow for the next series)
