### ISSUE TITLE
[13.0] Problem with report PDF APi external in java

### ISSUE THREAD

**Issue by DiegoSelles** [odoo/odoo#81972]
Impacted versions:
13.0

Steps to reproduce:
-Create an invoice and post it
-Execute "render_qweb_pdf" function of the ir.actions.report model. This function returns what the PDF data would be once obtained, and then I would parse them with this data and obtain the PDF, or I could also create an attachment and access it.

`models.execute("execute_kw", Arrays.asList(db, uid, password,"ir.actions.report", "render_qweb_pdf",Arrays.asList(id, res_ids));`

Current behavior:

When I run this function it returns:

> Failed to parse server's response: An invalid XML character (Unicode: 0x10) was found in the element content of the document

Expected behavior:

To create my pdf I need to generate an attachment to later download it, this attachment is generated from the data returned from the previous function. Ideally, create the attachment as follows.

`Integer idAttach = (Integer)models.execute("execute_kw", Arrays.asList(`
                   `db, uid, password, "ir.attachment", "create",`
                    `Arrays.asList(new HashMap() {{`
                            `put("name", "Name of my invoice");`
                            `put("type", "binary");`
                            `put("datas", "/*Response of the function render_qweb_pdf*/");`
                           ` put("store_fname", "Name of my invoice");`
                            `put("res_model", "account.move");`
                            `put("res_id", "id of my invoice");`
                            `put("mimetype", "application/x-pdf");`
                    `}})`
        `));`

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by odony** [comment]
So what happens is that `render_qweb_pdf()` returns the PDF as a byte array, which Odoo tries to marshal for XML-RPC as a string (for backwards compatibility with older versions). That string isn't ASCII-compatible as it contains arbitrary bytes from the PDF, so it becomes an invalid XML document, because some byte values are forbidden inside XML, like 0x10.

If you want more details, see similar issue #61919, which @xmo-odoo fixed in 14.0 via #74699. As you're using 13.0 you still have the original behavior. Either way that patch wouldn't actually help you, because you'd get an empty result instead of broken XML ;-)

There are a lot of options to work around your issue.
Here are just a few:
- don't call methods that directly return bytes, have the invoice printed by a method called via RPC and directly saved into an attachment. This can be done automatically by the report when you print it, depending on the `save_attachment` setting on the report. This seems to achieve your second goal automatically ;) You can always `read()` the `datas` field of that attachment later via RPC - you'll get the bytes encoded into a base64 string
- use the JSON-RPC API (`/jsonrpc`) instead. It doesn't suffer from the various compatibility problems of the XML-RPC API and would allow you to call methods returning bytes
- don't use RPC for printing to PDF, use the HTTP route (`/report/pdf/<report_name>/<doc_id>`). This requires a session cookie.

Hope this helps, closing this ticket as there seems to be no bug that we plan to address.
