### ISSUE TITLE
crm.lead @api.onchange('won_status') not work.

### ISSUE THREAD

**Issue by telesoho** [odoo/odoo#82241]
```python
    @api.onchange('stage_id')
    def onchange_stage(self):
        if not self.x_Proposal and self.stage_id.name == 'R5（成約）':
            return {'warning': {
                'title': _("保存依頼"),
                'message': _("提案書があればアップロードをお願いします。\nアップロード場所：契約関連書類タブ")
            }}
            
    @api.onchange('won_status')
    def _onchange_won_status(self):
        if self.won_status == 'lost':
            return {'warning': {
                'title': _("保存依頼"),
                'message': _("見積書、提案書があればアップロードをお願いします。\nアップロード場所：契約関連書類タブ")
            }}            

```

Onchage method of stage_id work well, But onchange method of won_status does't work at all.

What diffrent between won_status and stage_id?

**Comment by niyasraphy** [comment]
hi @telesoho ,
seems both the functions are from the third party apps, in case if the issue is with third party apps, feel free to ask in forums.
for now, the functions will get triggered only when the value of the field changes, change the value of won_status field and your function will get triggered.

feel free to close the ticket, as it is not a bug in odoo core.
thanks
