### ISSUE TITLE
Packaging affects all Product Variants

### ISSUE THREAD

**Issue by vvro** [odoo/odoo#8237]
Packaging affects all variants, because of being added to Product Template. I think it should be Product Product.
How do you distinguish between different variants in the packaging, if it's on the product template?

Here's the pull where changes were made from product product to product template.
https://github.com/odoo/odoo/pull/310

**Comment by qtheuret** [comment]
If you have product variants, the packaging might be the same for all the variants. For example, if you have 4 colors for a same T-shirt, the packaging is defined for the T-shirt product (w/o variants), not for each variants.
Plus, if you have a product with 500 variants (sizes, colors…), you have to re-encode the packaging for all variants. It's time-consuming !

**Comment by vvro** [comment]
What happens if the variants have different packaging, the warehousing control won't work.
Still on the t-shirt example, how would you order only the sizes and colors you don't have. 
I think it should still be product product, The fixing of time-consuming, because of the variants, could be done with a wizard, with a table crossing size and color.
Using the sample data in odoo, you can't say that a Ipad 16G and 32G have the same packaging, or would you?

**Comment by diggy128** [comment]
@qtheuret 
This is just WRONG!
Since product.packaging model includes EAN codes, every single packaging holding a different product MUST have a different EAN that "describes" the items within.

GS1 guidelines are very clear and simple about this.
Implementing packaging without obeying global, universally used standards all over the products' chain (from warehouse to retail) simply means poor code review and another useless feature.

@vvro 
Of course you are right and since we're upgrading from 7 to 8 we'll have to code yet another modules as we used extensively this feature both for transfers as well as Logistic Units List along with Product Specifications.

**Comment by qtheuret** [comment]
Thanks @diggy128 for you reply. You're right about the packaging with EAN. Thanks to mentioning that.
So, I'm ok to put product.packaging in product.product instead of product.template.

**Comment by diggy128** [comment]
Definitely OK. If you code a module that implements this change I'll be happy to review as I'm still a bit far away from implementing this myself. Maybe even suggest push to OCA?

**Comment by pedrobaeza** [comment]
As this is a feature request, and can be handled via an extension module (OCA or community), I close this.
