### ISSUE TITLE
Overriding an action is "destructive" (module uninstallation does not revert changes)

### ISSUE THREAD

**Issue by AaronBeaudoin** [odoo/odoo#82513]
## Steps To Reproduce

Override an existing `ir.actions.act_window` for example:

```xml
<record id="portal.partner_wizard_action" model="ir.actions.act_window">
    <field name="binding_model_id" eval="False"/>
</record>
```

This example causes the "Grant portal access" action to be hidden from the contextual menu on the `res.partner` form view.

## Current Behavior

After verifying that this override works as expected, **uninstall the module the override is defined in**. You will see that after the uninstallation the action is still hidden. To revert this, the `portal` module must be upgraded.

## Expected Behavior

Uninstalling the custom module causes the action to appear in the contextual menu again. The action is properly overridden in an "inheritance" fashion instead of being sort of "monkey patched" in place.

## Impacted Versions

At least v13. Not sure about other versions.

## Related Question

https://stackoverflow.com/questions/70656563/how-do-i-hide-a-ir-actions-act-window-defined-in-another-module

**Comment by AaronBeaudoin** [comment]
I was able to get around this for this particular example using `uninstall_hook` as follows:

```py
def uninstall_hook(cr, registry):
    env = api.Environment(cr, SUPERUSER_ID, {})
    env.ref("portal.partner_wizard_action").binding_model_id = env.ref("base.model_res_partner").id
```

This causes `binding_model_id` be reset to it's original value which can be seen in the source code at `odoo/addons/portal/wizard/portal_wizard_views.xml`:

```xml
<act_window id="partner_wizard_action"
    name="Grant portal access"
    binding_model="res.partner"
    res_model="portal.wizard"
    view_mode="form" target="new"
    groups="base.group_partner_manager"/>
```

The problem is that since it isn't relying on the original code in any way, if the `portal` module is ever updated for any reason then this code will need to be updated as well. This is not ideal.

**Comment by odony** [comment]
Yes that’s the expected behavior, it is impossible to exactly undo the installation of a module, there are too many side effects and variations that are possible.

Just one example: the current source code of the module may not even be what it was when the module was installed, so you cannot even determine what should undone.

Uninstallation is a rare and dangerous operation, it is not meant for production. There is a big warning in the UI for that, we are unlikely to go further. 

If you are unsure about installing a module the recommandation is to install it in a staging copy of your database for testing.
And if you must do it, you can always force an update of the `base` module after uninstallation, in the hope of « resetting » other modules to their defaults - but that comes with its own risks.
