### ISSUE TITLE
[8.0] Bug - Only a project manager can create issues

### ISSUE THREAD

**Issue by rafaelbn** [odoo/odoo#8286]
Hi,

I have been testing in runbot. Nobody except a Project manager can create issues.

This has no sense as project manager has other functionality and not create issues.

* An employee cannot create issues
* A project user cannot create issues!
* Nobody can create issues, only a project manager! Any sense?

When trying to create an issue with a project user I get this error:

> Access Denied
The requested operation cannot be completed due to security restrictions. Please contact your system administrator.
(Document type: project issue, Operation: create)

![29-08-2015 9-30-01](https://cloud.githubusercontent.com/assets/8736623/9562774/729f4de0-4e76-11e5-9091-dfb51d1e88d3.png)

Let me know how we can solve this

Regards,
Rafael

**Comment by lithint** [comment]
Dear Rafael Blasco,
you can gave permission to other user groups like project user,employee etc
in Access control list.

On Sat, Aug 29, 2015 at 7:52 PM, Rafael Blasco <notifications@github.com>
wrote:

> Hi,
>
> I have been testing in runbot. Nobody except a Project manager can create
> issues.
>
> This has no sense as project manager has other functionality and not
> create issues.
>
>    - An employee cannot create issues
>    - A project user cannot create issues!
>    - Nobody can create issues, only a project manager! Any sense?
>
> When trying to create an issue with a project user I get this error:
>
> Access Denied
> The requested operation cannot be completed due to security restrictions.
> Please contact your system administrator.
> (Document type: project issue, Operation: create)
>
> [image: 29-08-2015 9-30-01]
> <https://cloud.githubusercontent.com/assets/8736623/9562774/729f4de0-4e76-11e5-9091-dfb51d1e88d3.png>
>
> Let me know how we can solve this
>
> Regards,
> Rafael
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/odoo/odoo/issues/8286>.
>



-- 
Thanks & Regards,

Lithin T
Software Engineer
Mob  : +91 7736561076(India), +971556712557(UAE)
Mail  : lithint.mail@gmail.com | Skype : lithint.skype

**Comment by rafaelbn** [comment]
@lithint thanks for your answer. I know, but this is not the solution. I open this issue because this is not correct in 100% cases.

In fact odoo.com doesn't work like this.

* rarely a project manager create issues
* never a project manager classify and assign issuer
* as only a project manager can create or assign issue, how Odoo could think that this is not a bug?

**Comment by nhomar** [comment]
I confirm if it is happening that we have a bug but @rafaelbn some statements on your side are worng for me.

>>
>>    rarely a project manager create issues

On my side the project manager is who assing the issues, but I am not facing such problem.

>>    never a project manager classify and assign issuer

In my case 100% of times Project manager is who assign issues.

>>    as only a project manager can create or assign issue, how Odoo could think that this is not a bug?

The creation of issues is more frequent by email using the gateway. The user send an email and the issue is automatically created, but YES project manager should be able to create issues.

BTW, you can either:

- Give both ACL to your user project manager and project user and you will be able to create issues.
- Enable the gateway and everybody will create issue by email.

I hope it helps to you.

Regards.

**Comment by rafaelbn** [comment]
@nhomar thanks!. OK, I agree that other companies manager could work with issue... In you case is software development. But there are other cases that issues are very basic and any user could registry them or also an external call center.
Sometimes issues comes also by phone not only gateway, this means that person which answer phone must be able to create an issue and not send a e-mail to project manager and project manager create the issue. No sense! :-)
Well in general we are agree, this is a bug.
I thanks everyone for suggestions but I didn't open the ticket because I need help, I have the problem solved! :-), I open it, because this is IMO a bug and Odoo must fix it. Remark: I didn't a fix because the fix I did for my customers and me is maybe not the one Odoo will accept.
Regards

**Comment by dreispt** [comment]
In general Odoo provides two access levels to apps: "User" and "Manager". 
"Manager" is expected to edit all app tables, including setup data (Projects, Stages, Tags, etc)
"User" level is expected to edit transactional records, such as Tasks and Issues, and read only access to the setup tables.

So regarding the Project modules defaults, two things come unexpected:
- The "Project User" can't edit Issues (as Rafael reported)
- The default group for the "Demo" user is "Project Manager" (!)

These are just default values, but since unexpected IMO they should be fixed.

**Comment by rafaelbn** [comment]
Thank @dreispt , could I use you text to add in my internal issue in odoo.com?

**Comment by dreispt** [comment]
@rafaelbn Of course.

**Comment by rafaelbn** [comment]
I all, Odoo answer me

> you've reported it but it's not possible to do it in stable due to our stable policy (https://github.com/odoo/odoo/wiki/Contributing#what-does-stable-mean) and all our customers that are using it that way. We can't change the record rules in their instances in a stable version.

So.. I'm closing this issue.
Thanks to all

**Comment by dreispt** [comment]
That's a bad answer: the change would only affect new databases, since ACLs are not affected by module upgrades.
