### ISSUE TITLE
@api.depends triggers errors in edge cases

### ISSUE THREAD

**Issue by tarzan0820** [odoo/odoo#8332]
```python
class fleet_vehicle(models.Model):
    _inherit = "fleet.vehicle"

    @api.one
    @api.depends('log_fuel')
    def _last_fuel_log(self):
        pass
```

The above results in  an error message of  'column "vehicle_id" does not exist\nLINE 1: SELECT "vehicle_id" FROM "fleet_vehicle_log_fuel" WHERE "id"...\n               ^\n; 

Appears that it is not being detected that  the vehicle_id field is declared in the fleet.vehicle.cost model rather than the fleet.vehicle.log.fuel model which inherits fleet.vehicle.cost

**Comment by rco-odoo** [comment]
When triggering the recomputation of the field that depends on `log_fuel`, we search for the records to recompute, and the search involves searching on the one2many field `log_fuel`. The issue is: search on one2many fields does not work when the inverse field (many2one) is not in the comodel's table...

**Comment by rco-odoo** [comment]
By the way, which version of Odoo are you using?

**Comment by tarzan0820** [comment]
Version is 8.0; thanks for the fix
