### ISSUE TITLE
qty_to_invoice in sale order line not updated when product_template invoice_policy is changed.

### ISSUE THREAD

**Issue by boemba** [odoo/odoo#84063]
Impacted versions: 14

Steps to reproduce: Create a sale order with a product. Change the invoice_policy of this product. The qty_to_invoice of the sale order is not recalculated. This is a problem for all the sale orders already created with this product. The invoicing will not work correctly this way.

Current behavior: see above

Expected behavior: The qty_to_invoice should be updated when the invoice_policy of the product changes.

Solution:  add product_template_id.invoice_policy to the @api.depends() of the _get_to_invoice_qty function in the SaleOrderLine class

    @api.depends('qty_invoiced', 'qty_delivered', 'product_uom_qty', 'order_id.state', 'product_template_id.invoice_policy')
    def _get_to_invoice_qty(self):

Support ticket number submitted via odoo.com/help (optional):

**Comment by Feyensv** [comment]
You are expected to do a proper setup of your products before selling them.
We do not want to modify existing Sales Orders on product updates.

Otherwise, by modifying the invoicing policy, you would see old invoiced orders as invoiceable because of the recomputation.
Furthermore, this would also cause performance problems when you update the product invoice_policy.
