### ISSUE TITLE
[9.0] Invoicing group cannot be done on Picking/Delivery anymore

### ISSUE THREAD

**Issue by falinwa** [odoo/odoo#8470]
Hi Odoo,

On version 9, we don't have possibility to create invoice based on delivery order.
and we don't have possibility to create group invoice on delivery order(create invoice by more than 1 invoice).

This will have remove the feature when the user want to select the delivery order that they want to invoice. If you remove this, how you can do it on version 9?

Thank You.

**Comment by kovika** [comment]
Same question

**Comment by ausuwardi** [comment]
Same question.

**Comment by lukebranch** [comment]
@falinwa @kovika @ausuwardi ,

I'd recommend asking this one in the forum here:

http://help.odoo.com

I believe this has been explained and discussed in detail in some of the Odoo 9 Upgrade Training days.

You can find some documentation here:

https://www.odoo.com/documentation/user/9.0/accounting/receivables/customer_invoices/overview.html#sales

I think there will be some videos surfacing from the training sessions soon so that you can find the answer to your question. It's covered here from slide 32 onwards:

https://www.odoo.com/slides/slide/odoo-9-upgrade-training-session-349

**Comment by kovika** [comment]
@lukebranch

Thanks. But in sales it's working right. At purchases, don't.

**Comment by pedrobaeza** [comment]
Hi, invoicing system has changed for being done from sales orders for sales workflow, and adding purchases orders to vendors bills, but it has been a change of approach that doesn't mean that it's a bug to not have the picking invoicing. Please check new flows and ask of forums for doubts about them.
