### ISSUE TITLE
Check if user is administrator

### ISSUE THREAD

**Issue by scigghia** [odoo/odoo#8565]
at line https://github.com/odoo/odoo/blob/8.0/addons/stock/stock.py#L1981 whe see the message "'Quantities, Units of Measure, Products and Locations cannot be modified on stock moves that have already been processed (except by the Administrator).'" but i'm unable to find the point where check if user is administrator or not

**Comment by aisopuro** [comment]
The line has moved: as of this writing it is (in the latest commit) at https://github.com/odoo/odoo/blob/d39d191cec76a69cf63b9834e1a99aa87f8be9c4/addons/stock/stock.py#L2009

The author who last touched it was @fpodoo in 863ef7cf7aa6b1d802abc85a046f57c42dd78941. I agree that the error message is misleading, since there really doesn't seem to be anything even the administrator can do. But this likely cannot be fixed for a while, since it is a translatable term, and translations would go out of date if it were changed.

**Comment by Yenthe666** [comment]
@scigghia the administrator user has all rights on all models so this probably works by default. 
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
