### ISSUE TITLE
Unable to process 'stock.immediate.transfer' in Odoo 15 

### ISSUE THREAD

**Issue by thetrebelcc** [odoo/odoo#85724]
Impacted versions:
Odoo 15 enterprise 

Steps to reproduce:   

With Odoo 13, I could close stock.picking records by doing the following. 

```

    models.execute_kw(db, uid, password, 'stock.immediate.transfer',
                                                'create',
                                                ({'pick_ids': [pickid]})
        )
       
       models.execute_kw(db, uid, password, 'stock.immediate.transfer', 'process',
                                    [createdid], {})
```

Current behavior:

With Odoo 15, immediate transfers are returned as True, but the stock picking record is not closed. 

Expected behavior:

Stock picking records should be closed from processing immediate transfers. 

I have checked the documentation but was not able to find anything regarding if this process changed.

**Comment by ticodoo** [comment]
The code was refactored in v14 to work better. The easiest way to see how to adjust your code to match is by looking at the difference between v13: https://github.com/odoo/odoo/blob/13.0/addons/stock/wizard/stock_immediate_transfer.py
and v15: https://github.com/odoo/odoo/blob/15.0/addons/stock/wizard/stock_immediate_transfer.py

Normally it is expected you would have the immediate transfer wizard be created when trying to validate the pickings directly, which is why your flow currently isn't working. It would make more sense for you to use `button_validate` command on the pickings you want it to occur on and then process via the immediate transfer afterwards. If you don't want to follow this flow then you will have to make sure you correctly set the `button_validate_picking_ids` in the env.context.

**Comment by thetrebelcc** [comment]
Thank you! Was able to solve the issue following your logic, added the extra validation steps.

**Comment by cgrisar** [comment]
Hi @tunahorse ,
I'm struggling with the same issues (in PHP, btw)
What steps did you add?
