### ISSUE TITLE
Inheriting from project.task gives error when creating new regular task.

### ISSUE THREAD

**Issue by mariepizzer** [odoo/odoo#8614]
I was trying to create a new model inherited from <code>project.task</code>, and everything was working fine with this new model, except that when I went back to create a regular task, it showed me a MissingError:

<code>MissingError: ('MissingError', u'One of the documents you are trying to access has been deleted, please try again after refreshing.')
</code>

Looking at the log file, the error was thrown by this line: <code>\openerp\addons\project\project.py", line 658, in <strong>_hours_get</strong></code>

That function contains this code:
<code>cr.execute("SELECT task_id, COALESCE(SUM(hours),0) FROM project_task_work WHERE task_id IN %s GROUP BY task_id",(tuple(ids),))</code>
<code>hours = dict(cr.fetchall())</code>

And then it accesses <code>hours.get(task.id, 0.0)</code> without validating whether it contains something.

When I corrected that, the MissingError disappeared and I got to create a new task as wanted.
Maybe it could help somebody.

**Comment by Yenthe666** [comment]
Hi @mariepizzer,

This looks like you did something wrong in your custom code. I only see a part of the code but usually you don't even need `cr` to create raw queries.
I'm closing this since only issues with the official code from Odoo are tracked and solved here, custom development doesn't fall under this.
I'd suggest you to open a new topic on the official Odoo help forums if you would still face this issue (help.odoo.com).

Regards,
Yenthe
