### ISSUE TITLE
[9.0] Product returns and credit notes are not reflected in sale order

### ISSUE THREAD

**Issue by lvalenzu** [odoo/odoo#8621]
scenario:

a sales order is created with:

product: [A1232] iPad Mini
Ordered Qty 5
Delivered: 0
invoiced: 0

when recording the order, one delivery is created, after shipping, the order is:

product: [A1232] iPad Mini
Ordered Qty 5
delivered 5
invoiced: 0

After creating the invoice and validate it, the order is:

product: [A1232] iPad Mini
Ordered Qty 5
delivered 5
invoiced 5

Modify sales order:

product: [A1232] iPad Mini
Ordered Qty: 3

Odoo not make an additional delivery nor create button activates the bill, so the only option to regularize the situation is:

-Return 2 products, from the original delivery
-Create a refund invoice from the original invoice

After these operations, the order is:

product: [A1232] iPad Mini
Ordered Qty: 3
delivered 5
invoiced 5

smart buttons are:

2 delivery (1 delivery + 1 refund)
2 invoices (1 invoice + 1 invoice refund)

Briefly after these operations the stock is correct and billing too, the problem is that the returns and credit notes are not reflected in the sales order (delivery columns and invoiced).

Besides this inconsistency occurs again if I change the sales order increasing the amount requested 7 the transactions created are incorrect

**Comment by lvalenzu** [comment]
Version 9.0

http://102518-9-0-ec949a.runbot6.odoo.com/

**Comment by fpodoo** [comment]
Hello,

The usual approach by Odoo is to not try to handle exceptions automatically since there are lots of different ways to handle an exception. We prefer the user to handle it manually and decide what he really wants to do.

So, the expected behaviour is the following:
- if you refund an invoice (from accounting app), we do nothing on the sale order. Otherwise, if we apply this to the SO, he may retrigger an invoice right after. If the user wants to ship less, he should go himself to the SO/delivery order and decrease quantities purchased.
- if you create a refund from the SO: the invoiced quantity on the dale order is impacted. (as opposed to doing a refund from the accounting app)
- if you decrease quantities on the order, we let the user decide what he wants to do withall stock operations: decrease them, ask returning of the products, ... Because a lot of things may have happened, it's better that the user handle the exception by changing documents himself (already purchased/manufactured products may have been shipped and returned, ...)

**Comment by fpodoo** [comment]
We will add a warning to explain this to the user, if he decrease quantities on a confirmed SO. That way, the expectations are clear.

**Comment by lvalenzu** [comment]
Fabien thanks for your answer,

When a decrease in the quantity ordered on the sales order that is manually adjusted (both shipping and billing if applicable) occurs The problem is that they are inconsistent quantities shipped and invoiced in the sales order. The operations associated with the sales order are correct (2 shipping (shipping + back), 2 invoice (invoice + refund))

**Comment by nhomar** [comment]
@fpodoo as you are saying that the warning will be added, don't you think is beetter if we left the issue open until you finish that in order of not consider it "ready"?

**Comment by fpodoo** [comment]
To be checked, but I think I have seen the warning yesterday.
