### ISSUE TITLE
[9.0] concept: Order never really finished.

### ISSUE THREAD

**Issue by nhomar** [odoo/odoo#8635]
Hello.

This is a conceptual issue.

When the order is considered really "done".

I make this user case:

1. Sale 6 Cases.
2. Deliver 3 cases.
3. Go to order and mark as "Done".
4. Create the invoice and validate the 3 invoiced elements.
5. Deliver the other 3 Cases.
7. Invoice them "but" change to 4 the quantity invoiced.

Then we will have per line:

6 Ordered.
6 Delivered.
7 Invoiced.

And the order still have th button "Create Invoice" active even if we already delivered the order completelly and exceding the ordered quantities.

**What I expect:**
Order is marked as done, quantities are higher than the ordered ones then order can bi considered as "finished" and manage a "process" to reopen it securely.

**What I get:**
An infinite posibility to continue invoicing orders but not deliver anything, and order confused and marked as done.

Did I miss something or is this the expected behavior?.

**Comment by nhomar** [comment]
A preview of what I am talking about:

![ds](https://www.evernote.com/l/AJ4nz_ZCZX1C2rSQFyfUeEyHkn8LhJyZHV0B/image.png)

**Comment by nhomar** [comment]
I think this issue has relation with this one:

https://github.com/odoo/odoo/issues/8636

**Comment by fpodoo** [comment]
No, it's not because you delivered/invoiced the order that it is done.

Think about "open orders": the customer may request you new products, under the same order.  It's very common in manufacturing industries to have open orders. Also, services companies often need this: you may have invoiced all services but as you work based on timesheets / time and material, new delivered quantities may appear . (or you may have billed the whole project but you will add travel and expenses a few days later, when the employee have filled in his expenses.)
