### ISSUE TITLE
[9.0] Group by doesn't Total information anymore

### ISSUE THREAD

**Issue by falinwa** [odoo/odoo#8639]
Hi Odoo,

when I go to sale order, and I group by customer.
On the Total field, the system doesn't show the total anymore like version 8.
We should have this figure in this view.

![groupbyso](https://cloud.githubusercontent.com/assets/7590534/9989464/21b0a0a6-608b-11e5-8ded-48ecde66dc1c.JPG)

**Comment by fpodoo** [comment]
This is the expected behaviour.

We don't want to mix different currencies. We think it's better to not provide a Total rather than providing a wrong one (as we summed USD and EUR in v8) But you can quickly get the total by switching to the pivot or graph view, where the total does the correct sum according to currencies.

If you really want a total, you can add a field in the tree view. All invoice have a field "Total in Company Currency" We did not add it by default in the tree view as we prefer to not mess the UI with too many columns.
