### ISSUE TITLE
[8.0][BUG] Error with attachments when sending by e-mail

### ISSUE THREAD

**Issue by rafaelbn** [odoo/odoo#8766]
Steps:

1.	Log in As administrator
2.	Go to settings -> Reports -> Reports
3.	In the list of reports search for “Quotation"
![29-09-2015 10-53-10](https://cloud.githubusercontent.com/assets/8736623/10159988/61add712-669b-11e5-965f-10810edee7e1.png)

4.	Edit the Quotation / Order with model sale.order
5.	In the field “Save as attachment prefix” write ‘Quotation’ OR any name with variables like for example (object.name.replace('/','')+'('+object.partner_id.name+')'+'.pdf'). Error occurs in all cases.
6.	Save the report with the changes done in “Save as attachment prefix”
7.	Go To Sales -> Sales -> Quotations
8.	Create a new quotation with Customer Agrolait (for example), add an item of proctuct in sale order line like for example ipad mini, save and close.
9.	Press the button “send by email” and send it!
10.	[BUG][ERROR] Check a attachment and you will find that Odoo has printed 3 of them and not only one, the one we have send by e-mail
![29-09-2015 11-12-03](https://cloud.githubusercontent.com/assets/8736623/10159992/66015546-669b-11e5-945d-5f8d063100b9.png)

**We expected that Odoo creates a single PDF.**

**Comment by beledouxdenis** [comment]
As discussed in the OPW ticket related to this issue, this isn't a bug.

The report is already attached when sending the quotation email template, due to the configuration of the email template:
https://github.com/odoo/odoo/blob/8.0/addons/sale/edi/sale_order_action_data.xml#L28-L29

So, filling "the field “Save as attachment prefix" on the report itself will indeed save the report on the sale order another time, making the report attached several times on the sale order.

If you want the report attached only once, you should configure the report name either on the email template, either on the report, but not on both. If you want it on both, you should then use the "Reload from attachment" field, combined with conditions in the attachment name, as this is the case in the invoice:
https://github.com/odoo/odoo/blob/8.0/addons/account/account_report.xml#L39-L40

Regards,
