### ISSUE TITLE
[wishlist] Search History in the search box at Odoo TreeView pages

### ISSUE THREAD

**Issue by tvibliani** [odoo/odoo#8770]
**Search utility used in Odoo does not support "search history" feature**

Impacted versions:

 - 8.0 & above 

Steps to reproduce:

 1. Go to any TreeView page in Odoo.
 2. Search the page using any search term (using Odoo search utility at top-right side).
 3. Refresh the page
 4. Try to find out what search terms were used before on the page.

Current behavior:

 - No search history.

Expected behavior:

 - Search history available in search utility.
 - Optionally with auto completion as well, when user types in new search term, such that is matching one from history.

**Comment by Yenthe666** [comment]
Hi @mart-e and @odony is this something that you guys would consider as wishlist or is this something that you guys don't want at all?

**Comment by odony** [comment]
Hmm, I don't think we'll add that. The auto-completion system is already quite complicated, adding more stuff will only make it even harder to use.
Perhaps this will be mitigated by the fact that we plan to make the search filter feature smarter, so that you can restore/re-edit a saved filter. When we do that we might be able to also save the current filter in the URL as well, so that it persists after reloading.
We should probably close this wishlist to make it clear that we don't plan to do this for the moment.

**Comment by Yenthe666** [comment]
Alright as stated by @odony this will probably not be added as wishlist but an alternative might the smarter search filter.
Closing this issue.

**Comment by tvibliani** [comment]
Hi @Yenthe666, now you have write access to odoo repo? That's cool!

**Comment by Yenthe666** [comment]
Hi @tvibliani I have the same rights as developers from Odoo but I'm technically not allowed to merge PR's. This does give me the ability to manage and maintain bugs here. :smile:
