### ISSUE TITLE
[8.0][BUG]Sales journal on customer invoice should be default journal

### ISSUE THREAD

**Issue by analisaodoo** [odoo/odoo#8786]
Impacted versions:
    - 8.0

Steps to reproduce
    1. Activate the developer mode
    2. Go To Accounting -> Customer Invoices -> Create, take journal_id different to the first in the list.
    3. Go to Set Defaults and convert the Journal selected in the User-defined Defaults value 
    4.Go To Sales Order -> Convert to Invoice -> Convert and View Invoice

Current behaviour
    - Create invoice by Sales Oder, creates the invoice with another journal_id (not the value configured by default)

Expected behaviour
    - Create invoice by Sales Oder, must creates the invoice with journal_id configured by default in Setting -> Technical -> Actions -> User-defined Defaults

**Comment by analisaodoo** [comment]
Hello Denis, thank you very much for your answer.

However, I was reviewing and the solution is not working correctly in all cases. The case for which it's not working correctly occurs when the default value is setting with a condition, as example Type=Customer Invoice

Steps to reproduce
    - Activate the developer mode
    - Go To Accounting -> Customer Invoices -> Create, take journal_id different to the first in the list 
    - Go to Set Defaults and convert the Journal selected in the User-defined Defaults value AND select 
      condition 'Type=Customer Invoice'
    - Go To Sales Order -> Convert to Invoice -> Convert and View Invoice

Current behaviour
    - Create invoice by Sales Oder, creates the invoice with another journal_id (not the value configured 
      by default)

could you please reopen the issue? Thanks in advance

**Comment by beledouxdenis** [comment]
Unfortunately, this second case, with the condition, is not supported by Odoo.

User-defined defaults with conditions only works in the web client, within the according view. The conditions are not used server side, they are only use in the web client, through a Javascript call.

Therefore, defaults values loaded through a server call, through `default_get` will never load conditional user-defined defaults. This is he case here, since you are creating the invoice from the 'Create Invoice' wizard from the sales order form, you are not directly in the invoice form.
