### ISSUE TITLE
[9.0 Enterprise] Journal entries list must have a balance column

### ISSUE THREAD

**Issue by fclementic2c** [odoo/odoo#8805]
![image](https://cloud.githubusercontent.com/assets/5735158/10197430/d54ad470-6797-11e5-8b59-fed918263c06.png)

From the journal item menu, when user filter on a account a extra column balance must be displayed to show the balance.

**Comment by fclementic2c** [comment]
cf : https://github.com/OCA/account-financial-tools/tree/8.0/account_balance_line

**Comment by qdp-odoo** [comment]
not sure why you need this since you have both the debit and credit fields... but the 'balance' field actually already exists on the journal item. You can modify the tree view to add it, if you want. 

If you could explain more on the reasons why you'd need such a field it would be cool, in the meanwhile i'm closing this bug report

thanks

**Comment by fclementic2c** [comment]
Ok 1 example : 

I have have posted my year end cut-off entry on the sales account (revenue recognition to excludes sales related to the next fy) and I want to check if now the sales account balance is as expected. 
Then I want to see an extract of account where I can immediately see if the ending cumulative balance is ok for my current fy (or range of date if I do a quaterly closing for ex....this is why I need a better filter that the cistom one - I refer to https://github.com/odoo/odoo/issues/8806) and I want to see the move lines so I can see if I did not post a debit instead of a credit by mistake for ex.
