### ISSUE TITLE
[15.0]Cron thread can not auto restart in ThreadedServer in Odoo15

### ISSUE THREAD

**Issue by lin-ww** [odoo/odoo#88984]
Impacted versions: 
15.0

Steps to reproduce: 
postgresql db disconnect will cause cron thread down in ThreadedServer in Odoo15, because of `LISTEN cron_trigger`.

**Comment by Julien00859** [comment]
Auto restart of failed threads is not a feature we want for `ThreadedServer`. It is a feature, along many others, that is implemented in the `PreforkServer`. If you need that feature, I suggest you start Odoo in the [multi-workers](https://www.odoo.com/documentation/16.0/administration/install/deploy.html#builtin-server) mode of operation (i.e. `--workers=x`)

A connection to the postgres database is mandatory since 15.0, any failure to establish a connection or failure in the connection link is considered a fatal error that needs to be addressed by the system administrator.

**Comment by baguenth** [comment]
> Impacted versions: 15.0
> 
> Steps to reproduce: postgresql db disconnect will cause cron thread down in ThreadedServer in Odoo15, because of `LISTEN cron_trigger`.

Hey @lin-ww, 

just in case you are still struggling with this: I have build a workaround, you may want to check out.

https://github.com/OCA/server-tools/pull/3717

**Comment by baguenth** [comment]
> Auto restart of failed threads is not a feature we want for `ThreadedServer`. It is a feature, along many others, that is implemented in the `PreforkServer`. If you need that feature, I suggest you start Odoo in the [multi-workers](https://www.odoo.com/documentation/16.0/administration/install/deploy.html#builtin-server) mode of operation (i.e. `--workers=x`)
> 
> In case you want to _just_ start the crons with the `PreforkServer` and keep on using the `ThreadedServer` for http (I do **not** recommand it) you can start two processes:
> 
> ```
> $ odoo-bin --max-cron-thread=0
> $ odoo-bin --no-http --workers=-1 --max-cron-threads=2
> ```
> 
> The max-cron-_threads_ option name is misleading, it really starts 2 _workers_ cron
> 
> A connection to the postgres database is mandatory since 15.0, any failure to establish a connection or failure in the connection link is considered a fatal error that needs to be addressed by the system administrator.

@Julien00859 Is this still Odoo’s official position as of 2026? I’m asking because the issue is still present. ;)

Given that this appears to be a clear bug—especially since other threads spawned by Odoo are able to recover—and that the fix seems fairly straightforward, I’m wondering why Odoo is still reluctant to address it.

**Comment by Julien00859** [comment]
Solved in 19.3, won't backport it: 6278dbc53d617ab50ca2ba5ddd87f46851ce081a
