### ISSUE TITLE
[9.0] account_yodlee install not possible without account_plaid

### ISSUE THREAD

**Issue by richard-willowit** [odoo/odoo#8908]
The version 9 account_yodlee module makes a number of explicit (in security) to account_plaid.

The US account install does install both, but AU / NZ / ad-hoc installation does not.  There should not be a dependency.

Installation crashes without account_plaid installed.

**Comment by csnauwaert** [comment]
Actually the security file in yodlee does not have any reason to exists, it is not even loaded since it is not present in the __openerp__ manifest. The file could therefore not make the installation crash. I tried installing only yodlee without plaid and it worked like a charm. The security file is probably a remnant from a refactoring and it needs to be deleted.
FYI security is defined in online_sync module and both plaid and yodlee extends that one, there should not be any dependencies between plaid and yodlee.

If installation crashes without plaid installed, could you please copy the traceback here? Thanks a lot.
