### ISSUE TITLE
[8.0 ]Wrong Tax Calculation

### ISSUE THREAD

**Issue by jas-odoo** [odoo/odoo#9037]
Test Case:
1. Make two tax 12.5 and 2.5(included in price)
2. Create Product and apply that two tax in customer tax
3. create sale order with that product (Note calculated tax price)
4. Select that product in pos, It calculates wrong tax

Am i right or there is some setting for point of sale?

**Comment by nim-odoo** [comment]
Hello,
Yes, we are aware of this situation. This configuration is actually not supported.
Thanks!

**Comment by wtaferner** [comment]
@nim-odoo 
Can you explain further what kind of configuration is not supported?
Having two different taxes applied on a sale order line w/ tax included?

**Comment by nim-odoo** [comment]
@wtaferner : the configuration not supported is to have a tax included **and** a tax excluded on the same product. In this case, the tax excluded will be applied on the tax included amount as well. This is because of this: https://github.com/odoo/odoo/blob/8.0/addons/point_of_sale/static/src/js/models.js#L884
`base` actually contains the product price unit, which can include a tax.

This is supported for a standard sale order, but not for the POS. To make a long story short, the POS must be able to work offline, which implies to reimplement some Python methods in Javascript. In other words, duplicate the code, which we want to avoid when it is not necessary.

**Comment by wtaferner** [comment]
Thank you for your nice explanation which was not clear before based on the use case but now I understand the use case and that what is not supported.

So you say in v9 it is possible to combine tax included and excluded in a sale order line or it is possible to mix in a sale order and the created invoice? Even for the round per line and round globally issue? ;-) Seriously? This would be great!

Well, it does not make sense to mix two taxes (included and excluded) anyway, but most of the times the issue was/is the central rounding setting where you have/had to decide for the whole company/instance if you use tax included or excluded. Anyway, I have to test it on my own to see what really happened to the code and if the implementation rocks now, but if you are 100% sure this info would make my day :-)

**Comment by nim-odoo** [comment]
About the tax included/excluded issue, this should be solved with 5a8a0d2
About the  round per line and round globally issue, I don't know.
