### ISSUE TITLE
gevent error

### ISSUE THREAD

**Issue by SBollatti** [odoo/odoo#9056]
After a few minutes last pull got
/home/aeroclub/odoo/90/bin/python: can't open file '/home/aeroclub/odoo/90/bin/openerp-gevent': [Errno 2] No such file or directory

recursively and not running server! ...trying to reboot VPS

**Comment by SBollatti** [comment]
Still strugling with this, can't find anything about it

**Comment by sle-odoo** [comment]
how did you install your odoo? something looks unusual with your path

**Comment by SBollatti** [comment]
I used virtualenv in order to avoid dependencies then cloned from github

**Comment by SBollatti** [comment]
Deleted odoo folder and cloned again (into the enviroment using virtualenv) and worked

**Comment by flotho** [comment]
Hi,

I also have the same issue with rpm packages

**Comment by adekock11** [comment]
Also struggling with this. Installed Odoo 9.0 from nightly build. Taking a look at the nightly build folder, there is no openerp-gevent file like there always was, which means the error makes sense. However, why is there no openerp-gevent?

**Comment by flotho** [comment]
Hi @adekock11,
I desperately try to have an answer to https://github.com/odoo/odoo/issues/9673.
Actually it looks like the remove of the dependency is a voluntary and motivated https://github.com/odoo/odoo/commit/a0eb172cab590982168492ad16ad90c2228c6424
That is really weird because it looks like the procedure hasn't change on the official documentation https://www.odoo.com/documentation/9.0/setup/deploy.html#livechat
Maybe you could also vote here : https://github.com/odoo/odoo/pull/8551
