### ISSUE TITLE
[8.0/9.0] Method call in New API for inheritance and AbstractModel

### ISSUE THREAD

**Issue by pedrobaeza** [odoo/odoo#9084]
@rco-odoo, there's a problem when having multiple inheritance.

This [module](https://github.com/OCA/social/pull/22) overwrites a method (`message_subscribe`) in the AbstractModel mail.thread: https://github.com/OCA/social/pull/22/files#diff-5bbee5996045357b8f181a533b6e622dR20

I don't have this overwrite called when using `self.env[<model>].message_subscribe(` for some models, but others do. The models that I get it working are _account.invoice_ or _sale.order_. The models that don't work are _res.partner_ and _mail.group_.

I'm not able to deduce exactly what is the problem, because I don't find any exact pattern (inherit order, having multiple inheritance, having inherit and inherits...), but the problem is there. One of the test of the PR exercises the case for the mail.group model.

**Comment by rco-odoo** [comment]
This issue is known for a long time, and it is not easy to fix without breaking existing APIs. The typical use case is this one:

    class A(models.AbstractModel):
        _name = 'a'
        ...

    class B(models.Model):
        _name = 'b'
        _inherit = 'a'
        ...

Model `b` looks like a copy of model `a` with its own extensions. When the model registry is built,
 - the model `a` is made as a class that inherits from `(A,)`, and
 - the model `b` is made as a class that inherits from `(B, A)`.

Now imagine you load a module that extends model `a` with

    class A1(models.AbstractModel):
        _inherit = 'a'
        ...

When processing that class, the registry simply patches model `a` by making a new class that inherits from `(A1, A)`. And here you can see what is missing: the class of model `b` does not inherit from `A1`. The class of `b` would be correct if it was created *after* processing `A1` (the module loading order explains why your extension works on some models but not all).

Fixing this properly requires to remake the classes of all the models that inherit from `a`, and make them inherit from `(A1, A)`.

One ugly way to fix this is to "remake" the inheritance of `b` by adding the following class definition in the new module:

    class B(models.Model):
        _name = 'b'
        _inherit = ['b', 'a']

**Comment by rco-odoo** [comment]
BTW, fixing this on a stable version would potentially break quite a few models.

Imagine, in the example above, that class `A1` adds a field on model `a`. As a consequence, making the class of model `b` inherit from `A1` requires a database schema update, since a new field appears on `b`.

**Comment by pedrobaeza** [comment]
OK, I see. Thanks for the answer.

Are you working on a fix for master? Do you want me to help you in that?

**Comment by rco-odoo** [comment]
@pedrobaeza I am putting this on my todo list.
I already know what has to be done, but the details are tricky.

I mark this issue as "wont fix" for versions up to 9.0.

**Comment by hbrunn** [comment]
@rco-odoo @pedrobaeza meanwhile, this code works for me: https://github.com/hbrunn/social/blob/8.0-mail_follower_custom_notification/mail_follower_custom_notification/models/mail_thread.py#L82

(be cautious, I noticed just now after several hours that my first version of this reset all triggers on the patched models' fields. Currently, I can't find any more bugs on the code)

**Comment by rco-odoo** [comment]
@pedrobaeza @hbrunn this issue has been fixed on branch `master`.
The fix will be available in the future release Odoo 10.

**Comment by pedrobaeza** [comment]
Thanks you very much!

**Comment by pedrobaeza** [comment]
For references, the commit is https://github.com/odoo/odoo/commit/35bcd2c2a497c02d496568203fb241f99691642a

**Comment by hbrunn** [comment]
thanks @pedrobaeza - for older releases, I try to do a similar thing with https://github.com/hbrunn/social/blob/8.0-mail_follower_custom_notification/mail_follower_custom_notification/models/base_patch_models_mixin.py - but it's not flawless up to now, which is why I didn't propose it as its own module yet. I'll study the commit hoping to find a smarter way to recreate the objects
