### ISSUE TITLE
[9.0 Enterprise] [event_sale]  Setting maximum available seats doesn´t work

### ISSUE THREAD

**Issue by schmidtwastl** [odoo/odoo#9189]
It shouldn´t be possible to still buy Tickets from the website if if there are already more attendees registered than the maximum available seats. 
Setting the Maximum attendees number doesnt´t work as well.
Reproducing this is very easy: Just create an event and then make some reservations from the event-frontend 
![bug1](https://cloud.githubusercontent.com/assets/9939435/10641538/f227b120-7819-11e5-8049-a41123303060.PNG)

**Comment by Yenthe666** [comment]
Hi @schmidtwastl,

Thanks a lot for your bug report.
This issue has been fixed in the meanwhile.
Backend:
![image](https://user-images.githubusercontent.com/6352350/36088446-a13e438e-0fd7-11e8-9a86-603922d17e3e.png)


Frontend:
![image](https://user-images.githubusercontent.com/6352350/36088427-8cf7b1ee-0fd7-11e8-88f1-b6cfa5888e08.png)
Please update your local Odoo instance in order to fix this.

Regards,
Yenthe
