### ISSUE TITLE
How to run Odoo with docker postgres as database.

### ISSUE THREAD

**Issue by pyDjangoDev** [odoo/odoo#92010]
Hi, I started using Odoo, and first, I appreciate this awesome Odoo.
I installed Odoo on my local machine.
I wanted to not install PostgreSQL on my machine. because I use Docker.
I tried to use Postgres from Docker as a database.
But Odoo didn't work with it.
So I installed the PostgreSQL server on my local machine, and it is working well now.
Is there any way to use Postgres from docker as the database?

**Comment by netfxtech** [comment]
This is definitely not the right place for this question but I will give you the answer. In the future, post these types of questions in the community forum.


![image](https://user-images.githubusercontent.com/62037189/169721766-cabe085f-7809-4b1e-a1ac-96a21eaac6a1.png)


forum: https://www.odoo.com/forum/help-1

**Comment by pyDjangoDev** [comment]
Thanks for your help.
Excuse me, Did you try to run Odoo with the compose file yourself?
I tried the same one before I ask this question here.
But it was not working properly.

![2022-05-23_16-23](https://user-images.githubusercontent.com/61251512/169776429-a8918b09-450c-4c3d-8745-38f51c44ae87.png)

**Comment by netfxtech** [comment]
This is why they don't want these issues posted in the repo issues. To be blunt - "this is a configuration issue"... While I thing it's borderline unprofessional seeing that response myself I guess I understand it. Just be happy I saw it before Pedro ;p


The screenshot says what your problem is - You're trying to run odoo-bin and connect to the database via the unix domain socket but you're running the database in docker and not exposing the socket. I know the docker logs says it's available via "/var/run/..." but that's **ONLY** inside of the container.


Start at whatever step you're comfortable with but if you follow these steps perfectly it will work for you



If you're using running your databasse in a docker container and the OS you're using is
debian/ubuntu/or any other debian based distro then follow the steps below perfectly and it will work

1. Run the code below

> sudo apt-get update && sudo apt-get install -y \
>     curl liblday2-dev libsasl2-dev git \
>     python3 python3-dev python3-pip python3-setuptools python3-wheel \
>     wkhtmltopdf


2. Then run:

> git clone --depth 1 -b 15.0 https://github.com/odoo/odoo

4. Then run:

> cd odoo && mkdir data

5. Modify requirements.txt
   - if you're using vscode type in:
      
>  code requirements.txt

    - if you're not using vscode type in:

>   nano requirements.txt

    - go to the line starting with psycopg2== and comment it out (should look like this)
    - on a new line type "psycopg2-binary" (no quotes)
    
![image](https://user-images.githubusercontent.com/62037189/169877637-4e8a0b07-daca-4407-8adc-043a6f41370c.png)

    - if you're using vs code make sure you press save
    - if you're using nano to edit the file type in (no quotes)
       

>  "control X (at same time)"    "Y"  and then press "Enter"



6. Run the following command:

> pip3 install -r requirements.txt

7. Start odoo for your first time with the command below - if you copy and paste it then it will work, if you type it out manually, make sure it's all on one line

**NO DEMO DATA W/ BELOW COMMAND:**

> ./odoo-bin --db_user odoo --db_password odoo --db_port 5432  --db_host 127.0.0.1 -d odoo \
> --without-demo all -i base,web --addons-path ./addons,./odoo/addons --data-dir ./data -sc ./odoo.conf

**DEMO DATA INCLUDED W/ BELOW COMMAND:**

> ./odoo-bin --db_user odoo --db_password odoo --db_port 5432  --db_host 127.0.0.1 -d odoo \
> -i base,web --addons-path ./addons,./odoo/addons --data-dir ./data -sc ./odoo.conf

8. In the future, you will start the command with the argument below:

> ./odoo-bin -c ./odoo.conf


**Important Notes:**
- default login with or without demo based off the commands above:
**username: admin
password: admin**

**- Make sure you bind mount your docker volume if you're planning on keeping the database!**

Make sure your docker-compose.yml for the database looks like below - the one I sent earlier actually had the wrong environment variables.

![image](https://user-images.githubusercontent.com/62037189/169878359-6ff274bb-605e-4335-82e9-c822d370e55f.png)

**Comment by pyDjangoDev** [comment]
I already used the psycopg2-binary package.
And I run it with command `./odoo-bin --addons-path="addons/" -d odoo`.
How is the compose file different from the old one?
I see the same one

**Comment by pyDjangoDev** [comment]
I still can't run Odoo with docker postgres.

**Comment by netfxtech** [comment]
When you run Odoo-bin what is the error message you’re receiving now? Is it still complaining about not being able to connect to the database? If so, it’s because Odoo cannot reach your psql server.

Will you type in:
docker ps -a

Send me a screenshot please. I just want to make sure your ports are opened correctly.



Steven Bouillon
[Logo]<https://netfxtech.com/>

NetFX Tech
2372 Morse Avenue, Suite 494
Irvine, CA 92614


The content of this email is confidential and intended for the recipient specified in message only. It is strictly forbidden to share any part of this message with any third party, without a written consent of the sender. If you received this message by mistake, please reply to this message and follow with its deletion, so that we can ensure such a mistake does not occur in the future.

On May 23, 2022, at 11:02 AM, pydjangodev ***@***.***> wrote:

﻿

I still can't run Odoo with docker postgres.

**Comment by netfxtech** [comment]
If you run this command I would truly be shocked if it didn’t work, assuming there’s not an issue anywhere else. Just humor me and give it a try from inside your odoo folder. 

./odoo-bin --db_user odoo --db_password odoo --db_port 5432 --db_host 127.0.0.1 -d odoo 
-i base,web --addons-path ./addons,./odoo/addons --data-dir ./data -sc ./odoo.conf

**Comment by pyDjangoDev** [comment]
![2022-05-24_02-35](https://user-images.githubusercontent.com/61251512/169885199-06c39789-4317-4a30-b0db-52604891a3fa.png)


![2022-05-24_02-36](https://user-images.githubusercontent.com/61251512/169885142-e5669909-7208-4c07-8091-2486915fb784.png)

**Comment by netfxtech** [comment]
> ![2022-05-24_02-35](https://user-images.githubusercontent.com/61251512/169885199-06c39789-4317-4a30-b0db-52604891a3fa.png)
> 
> ![2022-05-24_02-36](https://user-images.githubusercontent.com/61251512/169885142-e5669909-7208-4c07-8091-2486915fb784.png)

Thank you for sending that.  It confirms my previous messages - when you run Odoo-bin you need to tell it where your database is 

run this without adding any quotes. It will definitely work

./odoo-bin --db_user odoo --db_password odoo --db_port 5432 --db_host 127.0.0.1 -d odoo
-i base,web --addons-path ./addons,./odoo/addons

**Comment by netfxtech** [comment]
You can also run odoo in a container. Here's a compose file
![image](https://user-images.githubusercontent.com/62037189/169895854-f9183d24-bb72-4344-a52a-4cc5cea3f32d.png)

**Comment by pyDjangoDev** [comment]
> > ![2022-05-24_02-35](https://user-images.githubusercontent.com/61251512/169885199-06c39789-4317-4a30-b0db-52604891a3fa.png)
> > ![2022-05-24_02-36](https://user-images.githubusercontent.com/61251512/169885142-e5669909-7208-4c07-8091-2486915fb784.png)
> 
> Thank you for sending that. It confirms my previous messages - when you run Odoo-bin you need to tell it where your database is
> 
> run this without adding any quotes. It will definitely work
> 
> ./odoo-bin --db_user odoo --db_password odoo --db_port 5432 --db_host 127.0.0.1 -d odoo -i base,web --addons-path ./addons,./odoo/addons

it works.
`--db_port 5432 --db_host 127.0.0.1`, Do I have to set the parameters?
If I don't give the parameters, it doesn't work.
It does not default parameters?

**Comment by netfxtech** [comment]
You cannot use the default parameters because you're running your database in Docker. 

That's why I suggested above to use a configuration file that Odoo will generate for you. That way you only need to start Odoo with:

./odoo-bin -c ./odoo.conf


All of the parameters would go in the odoo.conf and it makes life really easy. 

:)

**Comment by pyDjangoDev** [comment]
I don't have ./oddo.conf file

**Comment by pyDjangoDev** [comment]
![2022-05-24_04-51](https://user-images.githubusercontent.com/61251512/169904059-6baf9d8a-9ae7-4cf5-a798-d5d16248c0fb.png)

**Comment by netfxtech** [comment]
I truly urge you to start over at the steps that I outlined above. It will take care of everything for you, including creating an odoo.conf automagically.


On May 23, 2022, at 1:50 PM, pydjangodev ***@***.***> wrote:

﻿

I don't have ./oddo.conf file

**Comment by pyDjangoDev** [comment]
@netfxtech.
Thanks for your help.
