### ISSUE TITLE
LICENCE file saas 6

### ISSUE THREAD

**Issue by nuria-opusvl** [odoo/odoo#9215]
Hi, this might not matter but I've noticed the licence file reads OpenERP instead of Odoo.

"OpenERP is published under the GNU AFFERO GENERAL PUBLIC LICENSE, Version 3
(AGPLv3), as included below. Some external libraries and contributions bundled
with OpenERP may be published under other AGPLv3-compatible licenses. For
these, please refer to the relevant source files and/or license files, in the
source code tree."

So I'm wondering if it's out of date?

Will that cause problems?

Thanks

**Comment by bistaray** [comment]
Can you edit your Issue title to reflect your issue?  adding the words 'uses OpenERP instead of Odoo' would make this issue understandable without needing to read your description, saving people time.

Contribution guidelines can be reviewed at [https://github.com/odoo/odoo/wiki/Contributing] (https://github.com/odoo/odoo/wiki/Contributing) if you haven't seen them

I don't believe there will be any problems, Odoo was formerly known as OpenERP and there is widespread knowledge of this in the Community.

**Comment by nuria-opusvl** [comment]
Title sorted :-)

Thanks for looking into this. I know OpenERP is widely known, but what I'm a bit concerned about is that under the Odoo name licensing is changing.

I'm no lawyer, but I'm thinking that if there is an issue with licenses I do believe it would be better to have the correct name on the license file. It makes sense.

**Comment by rvalyi** [comment]
this is fixed in recent versions. Can it be closed?
cc @Yenthe666

**Comment by Yenthe666** [comment]
Hi @nuria-opusvl,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.
@rvalyi thanks a lot for the ping!

Regards,
Yenthe
