### ISSUE TITLE
[9.0] "Properties on order line" option no longer there

### ISSUE THREAD

**Issue by edsersolis** [odoo/odoo#9228]
On Odoo 8 if this option was unchecked (Settings->Configuration->Sale->Properties on order line) a popup was shown when on a quotation or sale order you clicked "Add new item". This option is no longer there or anywhere related.

On Odoo 9 Enterprise this popups is shown by default, but on Odoo 9 Community you must activate the developer mode, go to Settings->Technical->User Interface->Views and add the user group to sale.order.form.editable.list for it to be shown.

If you search the web for this, none of the options and combinations provided work except for adding the user group to the form view.

The sale orders still work without this, however, users tend to like the popup better for some reason. So if you're used to work on the list view instead of the popup this won't be an issue to you.

**Comment by odony** [comment]
Hi,
In Odoo 9.0 Community the behavior is the same as in Odoo 8, the main difference is that the various options that used to enable the "popup mode" for editing SO lines have moved or been hidden.
There are still [3 groups that activate this feature](https://github.com/odoo/odoo/blob/1c5c25518/addons/sale/sale_view.xml#L236), and the "Properties on order line" is still one of them, the option is simply not visible by default because it was considered a technical/complex feature.
You can still enable this particular option if you switch to technical/developer mode and go to the Sales settings.
![propssolines](https://cloud.githubusercontent.com/assets/2039870/11399108/844194b4-9385-11e5-8f38-6665669cf2e0.png)
