### ISSUE TITLE
Missing translation terms

### ISSUE THREAD

**Issue by Ryoko04** [odoo/odoo#92956]
Impacted versions: 15.0+

Steps to reproduce:  Search missing terms in transifex

Current behavior: Some terms such as 'Horizontal align', 'Merge cells', 'Borders', 'More formats', 'Increase decimal places', etc. in spreadsheet app can't be translated, because they are not in transifex.

Expected behavior: No missing terms.

Video/Screenshot link (optional):
<img width="958" alt="image" src="https://user-images.githubusercontent.com/70553601/172379814-f8d0712d-b49a-4e6a-a0f0-faebcbc8d3fd.png">
<img width="489" alt="image" src="https://user-images.githubusercontent.com/70553601/172379611-fa1d0f84-960b-48cb-9deb-a51a7132b64b.png">

Support ticket number submitted via odoo.com/help (optional):
#2880591

**Comment by rrahir** [comment]
Hello, Tahnk you for reporting the issue.
This issue was fixed in the o-spreadsheet library. Due to the library not being opensource at the time, we didn't link it to this issue.
Since the release of Odoo 16, we have open the repository publicly at https://www.github.com/odoo/o-spreadsheet !
Your issue was addressed and fixed in https://github.com/odoo/o-spreadsheet/pull/1444
