### ISSUE TITLE
odoo 9.0 running on two different servers

### ISSUE THREAD

**Issue by lizebin** [odoo/odoo#9301]
I have a question:
I odoo 9.0 running on two different servers, use the same database, use load balancing reflecting both servers. But the existence of the server attachment upload a local server b can not get to. When the load balancing distributed to the server b error.

**Comment by adekock11** [comment]
That happens because the ir.attachment model will by default store any attachments on the local server and *not in the database*.

1) Server A stores file
2) Load balancing moves to Server B
3) Server B tries to locate file, but the file does not exist (because it is on Server A)

To resolve this you may be interested in installing this module: https://apps.openerp.com/apps/modules/8.0/ir_attachment_force_storage/

**Comment by Yenthe666** [comment]
Hi @lizebin,

@adekock11 gives some great information regarding this.
Github issues are technically only for issues with a default Odoo setup, not for custom development or configuration.
If you'd still face this issue please post it at help.odoo.com and I'm sure somebody can help you further with this! The community is always there to help.

Regards,
Yenthe
