### ISSUE TITLE
I only see the top menu and entering website only

### ISSUE THREAD

**Issue by nkoddlb** [odoo/odoo#9322]
This has happened after changing the names of some menus. "Purchases" for "Shopping" and "Brand Products" by "marks". I deleted the translations directly in the table but do not appear.

![image](https://cloud.githubusercontent.com/assets/14835390/10841098/b5b49b44-7ee6-11e5-8836-594ba131f76c.png)

**Comment by Yenthe666** [comment]
Hi @nkoddlb,

Thanks a lot for your report. As you've indicated that you've changed translations etc and this is not a bug in the official Odoo code I can't really 'fix' this.
If you still face this issue you should update your Odoo codebase and database so that all data is rendered again. Your issues should be gone then.

Regards,
Yenthe
