### ISSUE TITLE
[FEATURE] Standardize access rules and rights

### ISSUE THREAD

**Issue by kmagusiak** [odoo/odoo#93372]
Impacted versions: all

Steps to reproduce:
Here is an example of an issue that may occur when adding new permission
1. Create a model, give access rights to Sales/Administrator. => Now sale administrators can do anything.
2. Add a field x_anyone: boolean
3. New requirements arrive: give access to sale users if x_anyone = true.
4. You would add access rights to "Sales/Users: all documents" and a record rule to restrict that group to only [('x_anyone', '=', True)].

Current behavior:
*To get access, a user must be part of a group which has access rights and, if applicable record rules exist, they must evaluate to true (where: global rule1 and global rule2 and (group1 rule or group2 rule or ...)*.
Sales administrators are restricted if you don't add an empty domain record rule. Here's it's simple, but you may not know that some groups are part of the same hierarchy.

Suggested behavior:
Merge both Access rules and record rules into a model: record rules which is more restrictive. This way, you can easily check who is allowed to do what. If there are no record rules, you don't have access.

**Comment by VincentSchippefilt** [comment]
Hello @kmagusiak,
I have a good news and a bad news: the good news is that it's a good idea that has been in our backlog since ~2020. 
The bad news is that it's been in our backlog since ~2020 because it's massively complex, that everything that has to do with security has to be very carefully considered for obvious reasons and that it is not yet in our priority list for this year.

I am cross referencing the issue in our tracker and closing it here.

For odoo people: task-id 2366634
