### ISSUE TITLE
[9.0] Incorrect reconciliation of journal items when making payment on invoice.

### ISSUE THREAD

**Issue by twinslady1612** [odoo/odoo#9361]
Steps to reproduce:

Visit runbot and login to the latest release of Odoo 9.0 Community (in my test, it is 110828-9-0-b7c1a9)
### Case 1: Partial Payment
1. Create SO (total $5000) -> Confirm -> Create invoice (select `Invoiceable lines` on the opening wizard) -> Validate Invoice > Check Total Receivable: $5000
   ![image](https://cloud.githubusercontent.com/assets/3737567/10880179/aebdf1a8-818b-11e5-9fe2-a2f125471ffd.png)
2. Payment $2000 -> Check Total Receivable, it's still $5000 while it should be $3000
   ![image](https://cloud.githubusercontent.com/assets/3737567/10880189/d53a1d52-818b-11e5-8c72-eab8dc9e71ea.png)
3. Generated Journal Items after payment:
   ![image](https://cloud.githubusercontent.com/assets/3737567/10880022/6491de7e-818a-11e5-9b0c-be37459b644e.png)
### Case 2: Paid amount > Amount to pay
1. Create SO (total $5000) -> Confirm -> Create invoice (select `Invoiceable lines` on the opening wizard) -> Validate Invoice > Check Total Receivable: $5000.
   ![image](https://cloud.githubusercontent.com/assets/3737567/10880206/f5449280-818b-11e5-9f95-602aca6b6501.png)
2. Payment $6000 
   ![image](https://cloud.githubusercontent.com/assets/3737567/10880085/f25cdd1c-818a-11e5-89c8-ab340e3b7419.png)
3. Check Total Receivable: - $6000 but it should be - $1000
4. Generated Journal Items after payment:
   ![image](https://cloud.githubusercontent.com/assets/3737567/10880134/45537f12-818b-11e5-93f7-970c026df4e2.png)

Both case 1 and case 2, Odoo got the problem with the reconciliation. Only one journal Item is checked field `Reconciled` while it should be 2 journal items with account `101200 Account Receivable`

**Comment by csnauwaert** [comment]
Hello,

Sorry for the time it took to reply to this issue.
First of all, the problem with the field "total receivable" on the customer has been fixed in version 9 and it now shows the correct value.
Secondly, when looking at the journal item view in your example, the reconciled flag is set to True only if the move line is totally reconciled. in your first example the line with 5000 is not fully reconciled as it still have a remaining of 3000 to reconcile. So only the line with 2000 is marked as reconciled.
It is the same in your second example. The line with 5000 is fully reconciled, as for the line with 6000, it still has a remaining of 1000 so it is not marked as reconciled.
If you want to see which move is reconciled with which one, you can do so from the journal entries and not the journal items.

Since this issue is fixed, I'm closing it
Best regards
