### ISSUE TITLE
Odoo V9 : Not able to set differant Sales price on product variant

### ISSUE THREAD

**Issue by AmitBista** [odoo/odoo#9404]
1 Create one product I-mobile with variant 16GB , 32GB
2 now go to product variant and update variant difference price for both
3 But not able to update price different for both, even update sales price in Template also

**Comment by Hassani87** [comment]
I can't add variant for a product, can somebody helps me ?

**Comment by peremartinezqubiq** [comment]
Hi!

As far as I know, it has to been set as a new development, like it was in v8:
https://www.odoo.com/apps/modules/8.0/product_variant_sale_price/

I have the same problem and I think the best way to accomplish that is to upgrade the module. 

You also have the analog module to put the cost price: 
https://www.odoo.com/apps/modules/8.0/product_variant_cost_price/

Cheers!

Pere

**Comment by Yenthe666** [comment]
Hi @AmitBista ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.
@Hassani87 in order to use variants you need to configure it under sales > settings.

Regards,
Yenthe
