### ISSUE TITLE
[BUG][15.0] payment: Unable to create new payment acquirer in multi-company environment

### ISSUE THREAD

**Issue by tranngocson1996** [odoo/odoo#94128]
This Issue:
-----------

- [x] Unable to create new payment acquirer in multi-company environment
- [x] Do not automatically generate payment acquirer

Video/Screenshot link (optional):
https://watch.screencastify.com/v/8kDYRe4YB754Z5XwvR65

**Comment by tranngocson1996** [comment]
@hote-odoo Are you in charge of payment modules? Do you know about this issue?
cc: @mart-e

**Comment by mart-e** [comment]
:wave:  @odoo/rd-payment :point_up: multi-company payment acquirers

**Comment by hote-odoo** [comment]
@tranngocson1996 , there is issue really, duplicate first the acquirer on the main company and assign them to the company that you want.

**Comment by tranngocson1996** [comment]
@hote-odoo Thanks for your direction but I think it's not a good solution for this problem 😄

**Comment by Feyensv** [comment]
It might not be the most intuitive, but why isn't it a good solution?
If you enable both companies in the company widget, you'll see the acquirers from the main company, and you're able to duplicate them and change the company field to the second company.

**Comment by hantt05** [comment]
@Feyensv Why don't we use Create button instead of duplicating these acquirers?

I think this is a solution but UI/UX is not good. 
At payment acquirers list view, there isn't button Create. When you access to detail one, you can see this button and create a new acquirer. However, system will warning: "Warning Creating a payment acquirer from the CREATE button is not supported. Please use the Duplicate action instead." 

![duplicate](https://user-images.githubusercontent.com/45425212/174965796-6b27e5a9-b2a0-400c-ac12-167700e2eee3.png)

cc @hote-odoo @tranngocson1996

**Comment by hote-odoo** [comment]
@hantt05 You cannot create acquirers yourself, only acquirers supported by odoo are available and thus you can only duplicate them. What could be discussed is to automatically generate acquirers for a company when the company is created. This however might not what some users want, leaving the choice to the user is better IMHO.

cc @tranngocson1996

**Comment by hantt05** [comment]
@hote-odoo thanks for your response. As you said, the create button has no function. It should be invisible because it confuses users.
cc @tranngocson1996

**Comment by tranngocson1996** [comment]
@hote-odoo I also agree with you. Thank you so much ✋🏿
