### ISSUE TITLE
Rounding problems when storing gross prices as net prices

### ISSUE THREAD

**Issue by rruebner** [odoo/odoo#9417]
Hi all,

we have some rounding problems in one of our projects, maybe someone can help or maybe its a bug in the odoo calculation, I don't know.

We have some kind of sale order creation process in the frontend, means a logged in user can create a sale order + a new product via the frontend. The user has to fill in the product gross price in the frontend but the price itself is stored as net price in the backend. So far so good. There are some cases where the re-calculation of the gross price is wrong, there is a 1 Cent difference.

I know that we could store the product gross price at the product with an assigned tax which has the flag "Tax Included in Price" activated. But our customer don't want this because all other backend created products are managed with net prices.

**Example:**

**Affected version:** v8 and above

* the user fills in 4000 in the frontend, the tax is 19%
* the net amount 3361.34 will be stored as net price in the backend (in the product and in the sale order line)
* the tax amount is 638,65
* the total is 3999.99 which is unequal to 4000, means the re-calculation of the gross price is wrong in this case

We tried several hints from the help forum / internet seraches (in any combination):

* changing the tax calculation rounding method form "Round per line" to "Round globally"
* changing the decimal precision for products from 2 to 4
* changing the currency rounding factor from 0.010000 to 0.000100
* changing the currency computational accuracy from 2 to 4

This solves the 4000 issue but at the end we have other 1 Cent problem with other prices.

Does anyone know how we can solve this issue?

**Comment by jholze** [comment]
@rruebner would be good if you can add the affected / tested versions

**Comment by fpodoo** [comment]
The computation gross --> net is not symetrical to net --> gross, when using decimal number.(it's mathematics, not related to Odoo)

By storing the net number, you loose information since there are more gross than net numbers.  So, it's impossible, unless you increase the decimal precision, but this is a bad practice since legal accounting requires rounding at two digits.

The clean solution is to store the gross number, not the net, anf work with tax included in prices.

**Comment by wtaferner** [comment]
@rruebner @jholze 
I know exactly what you mean and yes, Fabien is not completely wrong about his opinion and how Odoo is approaching...but actually it is a missing feature (https://github.com/odoo/odoo/issues/6275) and a lack of consistency and it is somehow complicated :-)

Anyway, I have done an implementation for a customer who can deal with both use cases in one instance in v8 (without PoS) as the global setting is allowing only one approach. Feel free to take a look at https://github.com/wt-io-it/odoo-addons - it is far from perfect (not 100% generic and needs some knowledge how to setup) but I am sure you guys can use the approach as it does not affect the way Odoo is meant to be used and imho future-upgrade proof...and if you need help just let me know and I will try to help or we can cooperate.

I was hoping that Odoo will provide both use cases in v9 and I have not yet checked if it became better or it is done (I kinda doubt it from the changes I have seen) but I guess sooner or later as they are heading the right direction I would say it will happen also for the core generically and easy to setup and use ;-)

**Comment by fpodoo** [comment]
@wtaferner I am not sure it's legal to mix both. It would mean that, for a $3361.34 product at 19%, sometime you will apply a tax of $639.64, sometimes $639.65: depending on your customer.

The feature of having two prices for a single product is standard, we sometimes do it for our SaaS customers: create two pricelists VAT included and excluded (using one of the two fields on the product form), create a fiscal position that set the right tax: included or excluded. (You can set an automated action to compute the net based on the gross, if you want)

PS: Althought most countries allows you to choose how you want to compute/round your VAT, most accounting regulations requires consistency on your accounting rules. So, I am not sure it's a good practice. To be checked

**Comment by wtaferner** [comment]
Hi Fabien,
I am not talking about to mix it in one business case but to use both business cases in one instance which is impossible by now for the given reasons and as you said, we would have to store the gross price which is very unpleasant for a business owner who normally don't care about gross prices internally except for sale reasons ...so my target was to have all prices stored in net and based on the fiscal position, the pricelist, the representation and calculation per line/globally accordingly aligned and therefore correctly calculated by Odoo's implementation with some tweaks.

So, yes, what you normally do on your SaaS is more or less the same but the underlying issue is to find in the global rounding setting and the representation in the shop at least for v8. 

But anyway, if I can help and you are interested I am ready to share my knowledge and my experience personally in a hangout, but probably in writing it is too complicated and does not lead to a common view. I doubt that I was missing any feature Odoo is already providing and working out of the box although I could be wrong too which is human. As long Jens and Robert find a solution which fits their needs I am happy that I have shared this.

**Comment by grexe** [comment]
glad this is solved now, we had the same problems here and my customer wants to have gross prices as product prices so he sees them on the POS terminal as is (he's more familiar with the gross price, this is much more common in Austria than e.g. US stores where alwasy net prices are shown, even to the customer).
Confusingly, the price on the printed receipt was correct, but the monthly reports had rounding errors in the grand total...
