### ISSUE TITLE
[9.0] [Purchase] If same vendor defined multiple times then variants are duplicated in po

### ISSUE THREAD

**Issue by jni-odoo** [odoo/odoo#9447]
See the following steps to confirm the issue 

(1) Create one product say mobile phone

(2) Create 2 variants of color : red and white

(3) In the main product define the same vendor multiple times 

```
see here https://drive.google.com/file/d/0B5j41T1Hqv1sdGE0d0s3X2ZjM0k/view?usp=drivesdk
```

(4) Create a po , select the vendor and then try to select one variant , you will see multiple entries of the same

   see here 
![repeated_items](https://cloud.githubusercontent.com/assets/7600117/10994420/501b0d48-849c-11e5-819d-1dc4a985fd3a.png)

Thanks & Regards,
Nikunj Jani (Odoo India)

**Comment by DarkoNikolovski** [comment]
I reproduced this issue in the SO also. Confirmation steps are same as in PO.

**Comment by Yenthe666** [comment]
Hi @jni-odoo,

Thanks a lot for the bug report.
This issue has been fixed in the meanwhile.
The product:
![image](https://user-images.githubusercontent.com/6352350/36167025-ae276f4e-10f4-11e8-95c0-ef8038b2ab31.png)

The PO:
![image](https://user-images.githubusercontent.com/6352350/36166971-895224a2-10f4-11e8-8562-77146dc92fcd.png)


Regards,
Yenthe
