### ISSUE TITLE
Anonymous User requests for (404) Not Found URLs triggers deletion of critical website files

### ISSUE THREAD

**Issue by DamianBere** [odoo/odoo#9495]
Detail here: https://www.odoo.com/forum/help-1/question/updated-anonymous-user-requests-for-404-not-found-urls-triggers-deletion-of-critical-website-files-what-code-in-odoo-v9-could-be-causing-this-deletion-to-occur-due-93163

**Given:**
A new (official) Odoo v9 docker image is started using official postgres db image, the DB created and website-builder App installed.

**When:**
A User is logged in (tested with a user that has admin privileges (not Administrator) - but not tested with a normal user)
..and: An Anonymous User (e.g. a web crawler/bot/etc) requests a URL
..and: The URL is unknown and results in a 404
..and: A new page request is made by the User logged in

**This Happens:**
 - A file (a common assets file, containing compressed javascript) is deleted
 - The website is unusable due to no scripts to load menus etc

This consistently occurs (the same file is deleted) based on those trigger conditions. If more Apps are installed, then the filename changes due to the new content it contains, but this same file still gets deleted regardless of the filename.

This still happens with the latest nightly build (set the ODOO_RELEASE to 20151109 in the Dockerfile to grab the latest available as of today).

This also happens with the Enterprise Edition, pulling the latest *.deb from Odoo official downloads.

**This is clearly a significant security issue**

More Detailed Steps To Recreate:

0.  On Linux with Docker installed...
1.  Pull official odoo:latest (Odoo 9 Community Edition) and postgres:latest docker images from Docker Hub. 
2.  Run Containers linking between Odoo & Postgres, as described in the Odoo Installation Guide.
3.  Access Odoo URL
4.  Create New Database and Log in as Administrator
5.  Goto Apps and install Web Builder
6.  Goto Website Home Page (still logged in)
7.  Log in via SSH and view docker logs for odoo - see no errors for missing files
8.  Hard Refresh (Shift F5 or Cmd-Shift F5 on Mac) Website Home Page
9.  View docker logs for odoo - see no errors for missing files
10. Use wget to fetch a URL that is not found (e.g. /page/nosuchpagehere)
11. Hard Refresh (Shift F5 or Cmd-Shift F5 on Mac) Website Home Page
12. View docker logs for odoo - see error for missing file 
13. Check website home page - menus will not work.

**Comment by raycarnes** [comment]
I just tried this:

1) Visit http://112183-9-0-1e64c6.runbot7.odoo.com
2) Login with admin/admin
3) Visit http://112183-9-0-1e64c6.runbot7.odoo.com/shop 
4) Visit http://112183-9-0-1e64c6.runbot7.odoo.com/shop/wont_be_found (get a 404)
5) Visit http://112183-9-0-1e64c6.runbot7.odoo.com/event
6) Hit F5
7) Visit http://112183-9-0-1e64c6.runbot7.odoo.com/
8) Hit F5
9) Visit http://112183-9-0-1e64c6.runbot7.odoo.com/ in a new browser

Should I have seen the problem sometime after step 5?

(I am NOT doing this with docker in the mix, I am doing it via runbot - what Odoo uses to replicate issues as part of the bug evaluation process).

**Comment by EnterpriseCore** [comment]
Hi Ray, not quite, but almost.  

You need to hit the 404 / unknown URL from a non-logged in browser (e.g. use incognito for chrome and hit the 404...) it doesn't cause this when the logged in user requests the unknown URL - /support is the one I'm using most frequently.   I would also do a **Shift** F5 to do a full(ish) refresh to force it to download the css/js/etc files again.  This will appear in the logs as per the community question post, and also that the menus wont load (however, you have to ensure the browser isn't caching a local version of this file to see this, hence partly why we do a forced full refresh).  Hope that helps you replicate it.  

BTW... the docker image I'm using is the official one, and defaults to v9.0 release 20151008 on docker hub, though I have also modified this to try with the 20151109 release, with same results.   I've not tried this in any other set-up, so it is a possibility that the docker image is in some way assisting this problem.

**Comment by DamianBere** [comment]
Hi Ray, not quite, but almost.

You need to hit the 404 / unknown URL from a non-logged in browser (e.g. use incognito for chrome and hit the 404...) it doesn't cause this when the logged in user requests the unknown URL - /support is the one I'm using most frequently. I would also do a Shift F5 to do a full(ish) refresh to force it to download the css/js/etc files again. This will appear in the logs as per the community question post, and also that the menus wont load (however, you have to ensure the browser isn't caching a local version of this file to see this, hence partly why we do a forced full refresh). Hope that helps you replicate it.

BTW... the docker image I'm using is the official one, and defaults to v9.0 release 20151008 on docker hub, though I have also modified this to try with the 20151109 release, with same results. I've not tried this in any other set-up, so it is a possibility that the docker image is in some way assisting this problem.

**Comment by DamianBere** [comment]
I just accessed the runbot urls you posted above and logged in with admin/admin.

Oddly, I can get this to happen, but it seems to take a few requests for the unknown URL for it to trigger the failure - so if you hit Shift-F5 a few times on the unknown URL, at some point it seems to trigger this deletion (and at least in my tests seems to fail to render the page properly, like a css file was missing).

However... something new I have discovered (that happens on my installation too), if I then log in from the browser that requested the unknown URL, the file will be restored and normal service resumed......  

It does seem as if the refresh/housekeeping process for these website static files is failing in a certain scenario, and just requires to be run again to succeed and thus restore the file that was missing.  e.g. the function to refresh js script static file tries initially to delete the old file, then recreate... however in the first time round it fails to complete, the second time round it succeeds.  Pure Speculation (TM) at this stage, but it feels like that mechanism at work.

**Comment by ashernevins** [comment]
Having this issue too. Awesome work figuring out reproduction steps. Is there a way to rebuild these files somehow to restore service to the site? I can still access the site in debug mode but normal users can't.

**Comment by DamianBere** [comment]
A quick means to restore the file from the front end:

- Use a Browser not logged into Odoo already (e.g. Chrome Incognito Mode) 
- Goto Sign-In page and log in with an admin rights user (may work with other users)  -this will trigger the recreation of that cached file
- Refresh other browser and they will now be restored to full function. 

Of course, the file will be deleted again soon enough, so rinse and repeat... and repeat... and repeat... :-)

**Comment by beledouxdenis** [comment]
Hello everyone,

We spotted this issue as well, and we were working on a fix to solve this. Unfortunately, after a deep analysis, we discovered that part of the issue could be found as well in Odoo 8.0. We therefore had to solve this in Odoo 8.0 first, and then port the revision to latest releases, including Odoo 9.0, thus.

There were 4 different problems that leaded to this issue:

1. In Odoo, when there is an exception, the SQL transactions of the request are roll-backed. A `404` being currently seen as an exception, the transactions are rollback-ed, including the JS/CSS assets that have been generated during the webpage rendering.

2. There is a bug in `postgresql`, leading to a serialization failure when the users signs in while the assets are being generated:
http://www.postgresql.org/message-id/20151014164844.3019.25750@wrigleys.postgresql.org
The assets building leading to the creation of attachments, with `create_uid` being a foreign key to `res_users`.`id`

3. The content of the `assets_common` was different in some cases, while it should never be the case (except when installing a new module):
 - 3a. The content was different for a user having the rights to edit the website when he was in the website/front-end and when he was in the back-office/back-end.
 - 3b. The content was different according to the users rights. Part of the assets was added only when the user was in a specific group, making the content different according to the users access rights.

Finally, the main issue was the fact the assets were being generated too often:
 - When there was a website editor and a visitor on the website, the assets were regenerated each time the editor opened a page after the visitor just did, and vice-versa.
 - When a website editor went from the website to the back-office.
 - When two users were connected in the back-end, with one with the group "group_website_designer", and one without.

This leaded to the fact: 
 - the assets were often generated, which is against the assets principle
 - sometimes, the assets were not regenerated correctly due to concurrent access, two different assets content being generated concurrently.

Issues 3a & 3b mentioned above are solved, respectively, with the below revisions:
 - 6f29cbe3ace5302781aa51d727b4358903efb373
 - f9a462f3e215f68f544f615cc16f0606f60194a9

The first one being applied in Odoo 8.0 as well.

Regarding the issue 2, there is not much we can do. We won't solve `Postresql` ourself, obviously. All we could do is find a work-around (like prevent to write the `create_uid` and `write_uid` when creating the attachment of the assets, but this is not clean at all).
 
Regarding the first issue, we are not yet sure what to do, if rollbacking SQL transactions with a 404 must be prevented or not (what about the other error codes ?).

Anyhow, issue 1 & 2 will occur way less frequently, maybe not at all, thanks to the revisions mentioned above, solving issue 3a & 3b, as the assets content will no longer be different on some cases, and the assets won't be regenerated all the time. For instance, for issue 1 (`404`), if indeed the assets are not generated yet, and are generated during the rendering of the page then rollbacked and deleted, the assets will be generated correctly as soon as you visit a "working" page, a page not being a `403`/`404`/`500`.

If this issue still occurs despite the two above revisions, we can of course re-open this issue, and I will  personally take care to solve the issue.

I hope this explanation will meet your expectations !

**Comment by DamianBere** [comment]
Thanks Denis, that looks like a thorough analysis of the causes of the problem, which I'm sure couldn't have been easy to track down given the variables leading to the reproduction of the error.

This certainly makes sense, and whilst there are still some remaining concerns, I'd expect this problem to be resolved in the scope of the normal usage that has triggered the issue.    

We will update to the latest build as soon as possible and feedback if the issue still occurs or not.

I'm pretty sure there are at least two organisations that are very thankful for your work to resolve this today :-)

**Comment by beledouxdenis** [comment]
Notice that for the revision f9a462f3e215f68f544f615cc16f0606f60194a9, updating the server sources won't be enough for existing databases: You will have to update the according view as well.

**Comment by DamianBere** [comment]
Thanks for the tip, I would have definitely missed that.
