### ISSUE TITLE
[8.0][BUG] Missing Company whe registering to an Event

### ISSUE THREAD

**Issue by rafaelbn** [odoo/odoo#9508]
**[8.0][BUG] Missing Company whe registering to an Event**

**Impacted versions:**

* 8.0

**Steps to reproduce:**

* Go to runbot
* Select database all
* Go in website Menu to "Events"
* For example, select "Technical training"
* But 1 ticket
* Fill checkout with:
   * You Name: Fabien
   * Company Name: Odoo
   * email: odoo@example.com
   * and fill all the form
* Confirm
* Select wire transfer and "Pay now"
* Go To Sign in: http://112198-8-0-c33338.runbot8.odoo.com/web/login
* Log in with admin / admin
* Go To Sales - Quotations and search for your quotation with "Customer" = Fabien

**Current behavior**

* Odoo write the form's field company in the field street of res.parner
* Odoo doesn't create a res.partner which is a company and a res.partner which is a contact of the company

**Expected behavior**

* Odoo must create a res.partner with the company name and create a res.partner with the name of the customer and this customer must be a contact of the company.

![2015-11-10_11-38-58](https://cloud.githubusercontent.com/assets/8736623/11060346/d58ee76e-879f-11e5-8235-c20938f3912a.png)

**Comment by rafaelbn** [comment]
cc @janetrp @JavierIniestra @JMODaERP

**Comment by beledouxdenis** [comment]
Hello Rafaël, 

The current behavior is the expected behavior.

When this feature has been designed, we had three choices regarding the subscription of partners with companies through the ecommerce:
 - Create a new partner for the company.
 - Search if the company doesn't exist, and associate the company to the partner if it does, create it otherwise.
 - Put the company name in the address

The first option would lead to a huge amount of duplicated partners.
The second would lead to privacy concerns, as anybody could claim himself as being in a company without any checks, and would potentially be able to access the data of the according company (sale orders, contacts, etc.)
The only disadvantage of the third option was to set the company name in a field labelled as "Street" in the back-end.

The third option was considered as the least bad solution.

Regards,
