### ISSUE TITLE
[9.0] [website] Edit Button not working for Editors (only)

### ISSUE THREAD

**Issue by lisandi** [odoo/odoo#9566]
In a fresh Odoo install we assigned a person to edit (Editor) the website but the edit button is showing but not working. 

When you assign the same person as (Editor and Designer) than the edit button is working. It would be good if editors could only Edit and are not capable to redesign a complete webpage or even being able to call the HTML Editor - which might crash the site completely afterwards if Editors start editing in the HTML Editor.

The problem had been reproduced in FF / Chrome / Safari / Opera on MAC and been verified by another person not at our site here: https://www.odoo.com/de_DE/groups/community-59/community-14964828?mode=thread&date_begin=&date_end=

**Comment by lukebranch** [comment]
@lisandi ,

Have you added any custom code to your website template? I had this problem in version 8.0 and it was due to me adding some conflicting javascript that interacted with jQuery and bootstrap that is already bundled with Odoo's website builder.

I'd recommend trying on the runbots here:

http://runbot.odoo.com

to see if you can reproduce the issue on a clean runbot.

just choose the 8.0 or 9.0 branch (whichever applies) and click the blue button to access an instance with the latest code updates. The login is:

admin
admin

If you are able to reproduce the issue on a clean runbot then I would recommend posting detailed step by step points for steps to reproduce, and also creating a screencapture demonstrating the whole process using licecap found here:

http://www.cockos.com/licecap/

**Comment by muneeburrahman** [comment]
Hi , I am having the same issue,  The problem is that i have put custom code to web.assets_common file by selecting it from html editor. I wanted to include velocity.js to my website. Now I am stuck how to reset the web.assets_common to default . Please help.

**Comment by treviser** [comment]
Well, I can confirm this behaviour, but I understand it meanwhile as expected behaviour. 
First, if somebody is assigned the rights to edit and design, it does not matter if he is a simple employee or not, assigned is assigned.
Second, the user with access rights "Edit" only, has also only access to parts of the website, where he can edit, means access to everything which is listed on the content dropdown menu on the top right side. He is only allowed to edit the dynamic parts of the website, not the static parts, which are in the sole responsibility of the designer.
For me that is more than only expected behaviour, it makes truly sense.

**Comment by qrinno** [comment]
Hi , we are having the same issue at Odoo 9, the site has been working for long time and we have not touched anything except run Ubuntu "apt update". Please help.

**Comment by JKE-be** [comment]
If you find this issue because your javascript is not more loaded after adding custom JS code.

You can find all the view from the html_editor into the backend in debug mode and remove the broken code (enable developer mode in settings dashboard _or_ about us top right menu _or_ add ?debug in url): 
    For views, in: Settings / Technical / User interface / views
    For static file modified at fly, in: Settings / Technical / Database structure / Attachments

I any case, don't forget to delete the compiled asset to regenerate it. (all attachments where name start with web/content)
