### ISSUE TITLE
[l10n_bo] Wrong tax rate for IT3%

### ISSUE THREAD

**Issue by elicoidal** [odoo/odoo#9569]
Tax rate is defined as 30% instead of 3% ( odoo/addons/l10n_bo/account_tax.xml, line 48)

**Comment by hrazera** [comment]
I already submitted a pull request (Update i10n_bo account_tax.xml #10070
https://github.com/odoo/odoo/pull/10070). the solution is to update account_tax.xml line 48 from 30 to 3.

**Comment by Yenthe666** [comment]
Hi @elicoidal,

This has been fixed quite a while ago at https://github.com/odoo/odoo/commit/d13d57292b37baaf10d36cc29d9b508ff39ab0f4#diff-8d266100290611db08df99bc50ac2542 but nobody ever closed this one.
If you still face it then please update your local instance in order to fix it.

Regards,
Yenthe
