### ISSUE TITLE
[ALL] Security Issue

### ISSUE THREAD

**Issue by manishkumarbohra** [odoo/odoo#95713]
Impacted versions:
13,14,15
Steps to reproduce:
Inspect Element - find css class "o_invisible_modifier" and comment this class code in web browser
Current behavior:
All Hidden/Invisible information visible to users.
Expected behavior:
Hidden/Invisible information not visible to users after remove this class
Video/Screenshot link (optional):
![Screenshot from 2022-07-09 08-28-44](https://user-images.githubusercontent.com/72200254/178089189-4238d1f2-5c00-4ac6-b0c9-5d3d1d101295.png)

Support ticket number submitted via odoo.com/help (optional):

**Comment by odony** [comment]
Hi,

What you describe is actually the expected behavior of the Odoo framework. Marking a field as invisible in the view does not make it private, it is only hidden in the UI to improve user experience. It is still accessible to the user for other purposes.
Revealing those fields inside the browser using dev tools is not a security problem.

If you wish to make some fields inaccessible to specific users, you should use the field-level `groups` attribute [^1] or move the data to another model with a specific ACL [^2].

In case you encounter a usage of attrs in a view to protect private information, please let us know and the view definition should be fixed instead.

By the way, please report security-related issues to the Security Team, following the instructions in our Security Policy; https://github.com/odoo/odoo/security/policy

Thanks

[^1]: https://www.odoo.com/documentation/15.0/developer/reference/backend/security.html#field-access
[^2]: https://www.odoo.com/documentation/15.0/developer/reference/backend/security.html#access-rights
