### ISSUE TITLE
Profiling code not working for Odoo version 15.0

### ISSUE THREAD

**Issue by shazzwazz20** [odoo/odoo#95805]
Impacted versions: 15.0

Steps to reproduce: Add below syntax for code profiling
from odoo.tools.profiler import profile
@profile
@api.model
def mymethod(...):
  My code

Current behavior:
 i am getting below error on terminal "ImportError: cannot import name 'profile' from 'odoo.tools.profiler'"

Expected behavior:
Profiler should work
Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by intero-chz** [comment]
The decorator was removed here: https://github.com/odoo/odoo/commit/4444475ef477d986040dbc435e1b2286b52e51ce

The commit message could help you. The documentation should be changed, but don't wait for that ;-)

**Comment by AyoubZahid** [comment]
> can you try from odoo.tools.profiler import Profiler? That one should work I believe.

No it does not work.
there is another profile function in `odoo.tools.misc`  [https://github.com/odoo/odoo/blob/aa5076941c48b660007be0bda3eb73e965bea931/odoo/tools/misc.py#L466](url)


 but it throws this error:

> TypeError: __call__() missing 1 required positional argument: 'f'

**Comment by anhvu-sg** [comment]
Hello, I had the same problem a couple of weeks ago.

The new [Profiling-tool](https://github.com/odoo/odoo/commit/4444475ef477d986040dbc435e1b2286b52e51ce) in Odoo v15 is very nice but I think it's only helpful for the Odoo UI not for the developer

In my scenario
1. My clients migrate from v11 to v15
2. They use Odoo for Backend only and integrated with other systems via API
3. In v11 I used `profiler` to identify the issue and  improve performance but in v15 I can't
4. So I ported the `profiler.py` to v15 and it works well

@AyoubZahid  for a quick fix, I think you can put [profiler.py](https://github.com/odoo/odoo/blob/14.0/odoo/tools/profiler.py) in your custom module

`from odoo.addons.your_custom_module.models.profiler import profile
`

Just a question @Xavier-Do , can we put back function `profile` ?

**Comment by Xavier-Do** [comment]
The old profiler was neither accurate (can have an overhead) neither easy to understand. This is the reason why we decide to remove it and replace it with the current version.

The new profiler can be used in code and the result should appear in the ir.profile as when used from the interface. The result can also be used in place to do a specific analysis/write to a file and it should possible to output a result similar to the previous version. We never bothered do do that since the speedscope view is usually way better to understand what's going on.

There is a wip documentation here http://runbot32.odoo.com/runbot/static/build/17082503-15-0/logs/build/html/developer/reference/backend/performances.html (my bad, it should have been in the official documentation for a long time) 

Note that the profiler must be used as a context manager not a decorator.
Note that for security reason you have to enable profiling on the database to display the results.

Don't hesitate to suggest improvements on the current version of the tool. It isn't a priority but some changes are already planned to make it even easier to use.

**Comment by hoangtrann** [comment]
Thumbs up for putting back old `profiler` and keeping it along with the new one, since this new way of profiling code is more useful from UI perspective but not for developers 😄

**Comment by Xavier-Do** [comment]
The documentation was updated.

The new profiler is also adapted for dev since you can target any piece of code using the context manager. 

The result can be found from the debug menu in a flamegraph using speedscope. It is usually easier to spot where is the problem using this interface when you are used to it. It is not always convenient to start the server and enable the profiling only to consult the result and I would work on that but it isn't a priority.

If you really want a printed output It is still possible to get the result from the profiler as dict and postprocess it. It is the raw information collected by the profiler. We can imagine to add more output tooling but we have no real use case right now, it is usually specific and dev will create there own output tools depending on their preferences and needs.
