### ISSUE TITLE
[9.0] overrideing __getattr__ causes a maximum recursion depth error

### ISSUE THREAD

**Issue by etoanik** [odoo/odoo#9612]
My Class inherit models.Model
and when i overrideing __getattr__ method, it causes
```
File "D:\Git\odoo\openerp\models.py", line 5652, in __str__
    return "%s%s" % (self._name, getattr(self, '_ids', ""))
```

**Comment by xmo-odoo** [comment]
Yes? I assume you're printing `self` in your overload, this invokes `__str__` which tries to fetch `self._ids` in case it's a recordset, which calls `__getattr__` because it's a base model rather than a recordset, which recurses and ultimately blows up. Implementing `__getattr__` on Odoo models is anything but a good idea, but if you insist on doing that you'll have to deal with that kind of cases.

/cc @rco-odoo

**Comment by etoanik** [comment]
thanks a lot
