### ISSUE TITLE
Unable to register payment 

### ISSUE THREAD

**Issue by ConnieXiao** [odoo/odoo#9613]
Hi 

We use multi-currency.  
For eg., CNY is setup as company currency.   The currency of Bank A and its related Bank journal A are set up as  CNY.   When we register customer payment, error pop up when we choose Bank journal A as Payment Method.

Error information:
Error while validating constraint

The selected account of your Journal Entry forces to provide a secondary currency. You should remove the secondary currency on the account or select a multi-currency view on the journal.
None

Thanks for your help.
Best Regards
Connie

**Comment by mkschreder** [comment]
This shit is so annoying. It's almost like they are doing this on purpose. I just commented out this constraint and everything works fine (line 443 in addons/account/models/account_move.py). The thing with odoo is that you usually either have to edit the code or sit in postgres and manually modify table entries because it wouldn't let you do things easily.

**Comment by csnauwaert** [comment]
Hello,

Sorry for the long time it took to answer this issue.
Actually you have this error because you've specified as secondary currency on the journal the same currency as the company. If you remove the currency on the journal it will work as by default it will take the currency of the company.
I agree that this is annoying and not intuitive, this has been fixed in v11 where you can specify as secondary currency the same currency as the company and it will be ignored by the system and you won't have a warning.

Best regards
