### ISSUE TITLE
Ensure ids in Model.browse() is an int

### ISSUE THREAD

**Issue by Yajo** [odoo/odoo#9650]
Not doing that leads to problems like https://github.com/OCA/website/pull/116.

**Comment by xmo-odoo** [comment]
There are two issues with that:

1. ids aren't necessarily integers, they can also — at the very least — be str, unicode and a special `NewId` placeholder
2. more extensive type-checking in `_normalize_ids` would have an outsized negative impact on the speed of odoo (because `browse` is called *a lot*), after the initial implementation we actually went and dumped all of the call stats for `_normalize_ids` to try and make it acceptably fast, including by removing or simplifying checks. See comments in that function on the subject.

As things stand, unless `_normalize_ids` is implemented in native code (and maybe even with that) fetching the type of the current model's `id` field and checking the type of all values in potentially huge iterables is going to destroy its performances and the performances of much of Odoo alongside it.

/cc @rco-odoo @odony
