### ISSUE TITLE
ir.cron concurrent update error

### ISSUE THREAD

**Issue by leopard7777777** [odoo/odoo#9657]
When i upgrade modules, cron job load module and raise "TransactionRollbackError: could not serialize access due to concurrent update"

def _acquire_job need to select ir_module_module where state='to upgrade' and stop cron when upgrade modules

cr.execute("SELECT * FROM ir_module_module WHERE state='to upgrade'")
            if cr.fetchone():
                _logger.info('The modules is to upgrade')
                return

**Comment by odony** [comment]
That's simply not possible. The cron worker may very well be in the middle of a cron job execution, of a cron job that belongs to a module that is going to be upgraded. The cron worker cannot magically abort its operation because a user suddenly decided to upgrade a module.

More to the point, could you follow the [contributing guidelines](https://github.com/odoo/odoo/wiki/Contributing#reporting-issues) and among other things, precisely outline the results you got and the results you expected. In terms of results I'm specially interested in the "business" or "user" result, in addition to the detailed error log, traceback, etc.
What operation was aborted, with what error message exactly, and what was the real problem?

Thanks.
