### ISSUE TITLE
[9.0 Enterprise] Confirming a sale order with a subscription product and a serviceproduct with invoicing policy "Invoice based on time and material" creates no subscription 

### ISSUE THREAD

**Issue by darenkster** [odoo/odoo#9668]
** Confirming a sale order with a subscription product and a serviceproduct with invoicing policy "Invoice based on time and material" creates no subscription **

Impacted versions:

- 9.0 Enterprise

Steps to reproduce:

1. create a subscription template with the subscription product.
2. create a new product with the following settings: 
    - Product type: Service
    - Invoicing Policy: Invoice based on time and material	
    - Track Service: Timesheets on contract
    - Unit of Measure	: Hour(s)
3. create a quotation template with the previously created subscription template as the contract template.
4. Add the service product to the quotation template.
5. create a new quotation with the previously created quotation template as the Quotation Template.
6. Confirm quotation.

Current behavior:

    - No subscription will be created
    - A analytic account for the service product will be created

Expected behavior:

    - A new subscription with the subscription product on it will be created.
    - The analytic account of the subscription is also set as the analytic account for the service product.

Additional notes:

   - When viewing the online quotation, the subscription is still mentioned ( ans the service product as a One-time Fee), although no subscription will be created.

**Comment by dbo-odoo** [comment]
Indeed, the code prevents the creation of a subscription if there's already an analytic account linked to the SO.

In your case, the code from sale_timesheet creates the analytic account before the code from website_contract, which then prevents the creation of the subscription.

A simple fix will be to check for a subscription on the SO (there's a computed field subscription_id that does this already), but since sale_subscription is an inherits of account_analytic_account, we need to prevent some info from being written over in the analytic account (partner_id and name fields, to be more specific).


Fixed as of 2c41977 in odoo/enterprise

Thanks for your feedback!
