### ISSUE TITLE
[9.0] No html/xml syntax check in translations which can break features

### ISSUE THREAD

**Issue by sdaguet** [odoo/odoo#9698]
In the french translation of website module, some incorrect syntax where present, breaking web page edition (JSON error, no snippets in the bar)

For example: `</br>`, `&` (correct syntax is `<br/>` and `&amp;`)

A syntax check before importing the transifex translations would enhance code quality and product usability.

**Comment by lukebranch** [comment]
@sdaguet ,

Where is the file with this incorrect syntax?

**Comment by antonylesuisse** [comment]
On a daily baiss @mart-e takes care of those problems. I close this issue if you know the specific term please report it.

**Comment by sdaguet** [comment]
I corrected the elements in transifex already.
However, the problem may appear again with a next translation ...

**Comment by mart-e** [comment]
@sdaguet adding a syntax check doesn't seem like something realisable. What would you check? You can get pretty much everything in the terms: xml (for views), mako (email templates), python (e.g. ` %(document)s`, should NOT be translated).
Well if you succeed to develop such test, I can add it to my [import script](https://github.com/mart-e/odoo-scripts/blob/master/transifex/pull-translations.py).

Another solution I could see would be to run the [runbot](http://runbot.odoo.com/runbot) in every language (but that would make the test time multiplied by 80).

So that seems over complex for the few potential issues that we can quickly fix manually when reported (ping me on github or send a email to Odoo support)

**Comment by xmo-odoo** [comment]
> xml (for views), mako (email templates), python (e.g. %(document)s, should NOT be translated).

also HTML (the views themselves are XML, but HTML fields are not)
