### ISSUE TITLE
[9.0] one2many dialog issue

### ISSUE THREAD

**Issue by etoanik** [odoo/odoo#9749]
I had find a one2many dialog editable view bug, it would lose record value

follow my step:
1. open view  
http://i.imgur.com/aHpL10w.png
2. edit #1 record  
http://i.imgur.com/qRM1noV.png
3. unfocus #1 and click #2  
http://i.imgur.com/DFRKWP0.png
4. then save it
http://i.imgur.com/9cNtGzD.png
5.  open record again, then lose my value
http://i.imgur.com/RJAVBEX.png

**Comment by Khwunchai** [comment]
Also happens when create new records in one2many, some values will be lost.

**Comment by Gorash** [comment]
Could I get more information: browser used? The model / action? In order to reproduce it. (It's can be a js/framwork or a python/model error)

To analyze the problem:
Can you test with google chrome and display dev informations?
* In Google chrome (the others browser have also a dev mode I need the 'write' 'Headers' result)
* Open the dev console (F12)
* Perform the actions listed
* Go to the Network tab in the console
* Click on item 'write' (you can search it)
* Details are displayed, I'll need all the content "Headers"

Thanks

**Comment by Yenthe666** [comment]
Hi there,

I'm closing this bug report as there has been no response in over a year. Without more information we cannot reproduce it and/or help you.

Regards,
Yenthe
