### ISSUE TITLE
[15.0] Website show html code instead of page data

### ISSUE THREAD

**Issue by ikus060** [odoo/odoo#98625]
Impacted versions:
15.0 

Steps to reproduce:
1. Loging to Odoo
2. Go browse a blog post in original language

Current behavior:

The content of the page is not displayed and HTML code are shown.
![image](https://user-images.githubusercontent.com/921251/186016899-83966c92-ca21-4ccc-840f-aaafba1aa6d6.png)

Expected behavior:
The content of the page should not include HTML code and should display the blog post.

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by 3piece** [comment]
Confirmed, it seems to be impacitng all odoo.sh instances that are on v15 with nightly builds acitve.

With the editor active the issue is present.

As a public user, it seems okay.

We are experiencing this inside the product catalog / listing page where categories are active.


![broken_odoo_sh](https://user-images.githubusercontent.com/2265129/186104814-8ca5c5ae-5052-4ff9-9cd9-2906b6217d3f.png)

![broken_sh_2](https://user-images.githubusercontent.com/2265129/186104853-c48c629e-50f0-4a69-9718-5ab9cedd0ec8.png)
