### ISSUE TITLE
can anyone tell me how i can add custom addons path ? I can't seem to find the conf file.

### ISSUE THREAD

**Issue by Retr0l1acker** [odoo/odoo#99056]
Impacted versions:

Steps to reproduce:

Current behavior:

Expected behavior:

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by saeed-raeisi** [comment]
Create a folder named for example
custom_addons
Copy the module folder into the folder
Then link the folder to the project config file:

odoo.conf (Create it if it doesn't exist)
linux :
addons_path = /home/[user]/addons, /home/[user]/custom_addons
windows:
addons_path = C:/project/odoo/addons,C:/project/odoo/custom_addons

After the run
If this is the first time you have created a database, go to step 2

otherwise
First, activate the developer mode from the settings section, then go to the apps menu and click on Update Apps List

Step Two

Now find and install the module by searching for the module name
And enjoy the module :)

**Comment by nhomar** [comment]
Can you go to odoo.com/forum for functional questions?

thanks for your understanding.
