### ISSUE TITLE
Wrong Calculation of Journal Entry when return the purchased stock and not updating unit cost on returning of stock in Average AVCO method

### ISSUE THREAD

**Issue by ABXTTI** [odoo/odoo#99190]
Impacted versions:
 Version 13, 14 , 15

Steps to reproduce:
1. Create a Product category with Average AVCO method and with automated accounting.
2. Create a product with any name e.g. Car
3. Create a purchase order with Quantity 2 and unit price 100. and confirm it.
4. Go to top right shipment button then receive the products i.e. validate the form
5. Check on product form unit cost is 100
6. Check Journal Entry it will be with 100 which is ok
7. Now Create Purchase Order Again with same product and Quantity 2 and unit price 200 confirm it
8. Go to top right shipment button then receive the products i.e. validate the form
9. Now go to product form Check unit cost .... it will be 150. which is ok for now.
10. Check the journal entry it will be with 400 both debit and credit.
11. Now return 1 Quantity from second Purchase Order's Receipt. and validate it.
12. Now go to product form check unit cost = 150 --------------- Its wrong should be 133.33 both debit and credit
13. Check the journal entry it will be amounting to 150 ------------- which is wrong should be 200 both debit and credit

Current behavior:
For Example:- I will be taking 2 Purchase orders  example.
1. We purchased a product naming ABC  Quantity=2 and Unit cost = 100 then in product field unit cost will be = 100 when we receive the product.
    Journal Entry =  debit = Stock Valuation Account  Amount=200   and credit = Stock Input Account  Amount = 200  which is OK.
    Average cost on product form = 100
14. We purchased again the same product product ABC Quantity = 2 and unit cost = 200 in product field unit cost will be = 150 in average.
Journal Entry =  debit = Stock Valuation Account  Amount=400   and credit = Stock Input Account  Amount = 400  which is OK.
 Average cost on product form would be = 150 which is OK
15. The problem arise e.g. when we return from second Purchase order's Delivery with 1 quantity.
   Journal Entry = Debit = Stock Input Account  ---- Amount = 150 and Credit = Stock Valuation Account --- Amount = 150
   unit cost on product form = 150 which is wrong
 the journal Entry is correct but the amount is not correct since I have returned my second Order and unit cost has not changed.
   
Expected behavior:
On return of inventory the entry should be if we take the above point 3 should be like that:
   Journal Entry = Debit = Stock Input Account  ---- Amount = 200 and Credit = Stock Valuation Account --- Amount = 200
   unit cost on product form should be  = 133.33  [i.e. (2 x 100 + 1 x 200)/3] i.e 400/3 = 133.33

**Comment by gdgellatly** [comment]
Actually the behaviour is correct. You are conflating actual cost with average cost. But average cost presumes that the items are fungible, therefore there is no guarantee that the item you returned is exactly the one you received. It is after all, the only justification under IAS2 to use average cost, is that the items are readily interchangeable.

In any case upon receiving, that items cost is no longer 200, it is 150.

**Comment by ABXTTI** [comment]
> Actually the behaviour is correct. You are conflating actual cost with average cost. But average cost presumes that the items are fungible, therefore there is no guarantee that the item you returned is exactly the one you received. It is after all, the only justification under IAS2 to use average cost, is that the items are readily interchangeable.
> 
> In any case upon receiving, that items cost is no longer 200, it is 150.

Brother the purpose of IAS-2 is to not to over cost your products because it will understate your profit margin.

The problem is that for example when you purchased first your average cost was same as your purchase price i.e. 100 but when you have purchased again 2 units @ rate of 200 your average cost would become 150 i.e. (600/4) but  the question is that what if you return the whole of your second purchase (that you had purchased @ 200) in this case the unit cost remains the same i.e. 150 which is over costing your product . the cost should have returned to 100 again since we have returned the 2nd purchase order whole. Actually that is my question. 
And the purpose of IAS-2 is to check that products are not over costed.

**Comment by gdgellatly** [comment]
I do understand what you are saying. But whether it is over costed is not a matter of your opinion on a very simplistic example, it is a matter of the standard. If you used actual cost for returns, it just gets impossible. In your very simple case you think this looks wrong and intuitively it does. In the reality of what goes on in high volume inventory, what you want is basically impossible.

Let's say you bought it two years ago for $200.00. Now you return it, in the meantime the cost has dropped to $100 and your net realisable value was $150 so you write the value down. Now your supplier allows a return, but only for an agreed value of $140.00.  You can't even remember/identify exactly which purchases they were so you just pick ones from around that time.

However once you sell the other 2 it all balances out. It will not understate your profit margin at all. On the 2 you "sold back" you either make $100 or $0. On the other 2 you make either $100 less or nothing. If anything, you get $100 profit earlier than you would. But all this is so insignificant, it just washes through.

I'm an accountant with nearly 20 years in systems stock accounting, this standard is practically unchanged since the 70's. When I was younger, I asked exactly these questions. It is just the way it is, although I doubt the treatment you propose would attract any real attention for your very simple case, at scale it could be easily abused to swish at end of period, the current behaviour is correct.

**Comment by ABXTTI** [comment]
Thanks for the clarification, you are absolutely right. That was very helpful...
