### ISSUE TITLE
Computed fields are not computed if compute method has no @depends annotation

### ISSUE THREAD

**Issue by tortabevonas** [odoo/odoo#9946]
Compute method is not called in this case, even though other computed fields depend on it.

**Comment by rco-odoo** [comment]
A computed field is (re)evaluated whenever some of its dependencies are modified.
If you don't specify dependencies with `@depends`, nothing triggers its evaluation.
This is not a bug, what you get is the expected behavior.

If the field really has no dependency, simply add a `@depends` on a required field.
If the field should not be reevaluated, do not define it as a computed field and override the method `create` instead.

**Comment by tortabevonas** [comment]
It sounds very logical. You're absolutely right, thanks.
