### ISSUE TITLE
[14.0,15.0] grouped list view editable=top/bottom does not recompute grouped values

### ISSUE THREAD

**Issue by lem8r** [odoo/odoo#99780]
Impacted versions: 15.0

Steps to reproduce:
- install planning app (it has editable list view)
- open planning slots as list view and group by employee. Add lines

Current behavior: total hours of employee is not updated on lines edit

Expected behavior: grouped values should be recomputed

Video/Screenshot link (optional):

https://user-images.githubusercontent.com/5942291/188966041-6889f44c-917b-48ae-b748-f410f242e1ef.mp4

Support ticket number submitted via odoo.com/help (optional): 2977115

**Comment by lem8r** [comment]
Hi,
 @aab-odoo could you please have a look at this?
 
 It happens in v14 as well. Before grouping by m2m was added.

**Comment by bouvyd** [comment]
Hello,

Although I understand your point, the problem is a bit deeper than that, and for the moment we do not wish to change/update that behaviour.

The problem with reflecting the changes in a live way is that it would/could cause records to move around as they are edited, which would not be a nice experience (jarring/confusing behaviour).

I we wanted your behaviour but not have records move around, we would have to give a way for the view to know for which field it needs to refresh - but then you run into issues as well. If the view knows to refresh when the value for allocated hours is changed, but not for the employee (as we may not want records to move around), what should happen if I edit both? Should the number be used in the aggregate of the (now incorrect) employee? Should the record have moved anyway for that specific order of operations? Either solution we choose for that kind of behaviour would ultimately be reported as a bug, like this issue.

My point being that behaving in the way you suggest leads to other inconsistent behaviours, which we do not want to address. Neither do we wish to add complex logic in the views to attempt to partially support these usecases - besides more complexity, it would not yield a lot of value. We would keep getting bug reports and inconsistent behaviours - like now - but now with added complexity and maintenance.

For these reasons, we do not think this should changed at the moment.

Thank you for the report, have a good day :)

**Comment by lem8r** [comment]
Hi,

Thanks for detailed explanation.
My actual problem was that onchange values on other rows were not updated. I see that this all is global problem of state management.
Hope rewrite in owl will help with that.
